ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

[[installation-general-requirements]]
= 일반 요구사항
:description: 시스템 설치를 위한 요구 사항을 확인하십시오. 여기에는 계정 설정, 지원되는 브라우저, SSL 인증서 구성이 포함됩니다.
:revdate: 2026-06-12
:page-revdate: {revdate}

설치를 시작하기 전, 다음이 준비되었는지 확인해야 합니다.

. {scclongform} 계정입니다.
  이 계정을 통해 {productname} 서버, 프록시 및 소매 지점 서버에 대한 조직 자격 증명 및 등록 키에 액세스할 수 있습니다.
. {productname} {webui}에 대한 지원되는 브라우저입니다.
. 환경에 대한 SSL 인증서입니다.
  기본적으로 {productname} {productnumber}는 자체 서명된 인증서를 사용합니다.

[NOTE]
====
{sl-micro} {microversion} 권한은 {productname} 권한에 포함되어 있으므로 별도의 등록 키가 필요하지 않습니다.
====

다음 섹션은 이러한 요구사항에 대한 자세한 정보를 제공합니다.


[[install.scc-register]]
== {scclongform} 계정 및 자격 증명


{scclongform}의 배포 전에 {productname} {productnumber} 계정을 생성하십시오.

[[creating.scc.account.mgr]]
.절차 조직 자격 증명을 얻으세요.
. 웹 브라우저에서 https://scc.suse.com/login으로 이동합니다.
. {scc} 계정에 로그인하거나 프롬프트를 따라 새 계정을 생성합니다.
. 아직 수행하지 않은 경우, btn:[조직에 연결]를 클릭하고 조직을 입력하거나 검색합니다.
. btn:[내 조직 관리]를 클릭하고 목록에서 조직 이름을 클릭하여 조직을 선택합니다.
. btn:[사용자] 탭을 클릭한 후 btn:[조직 자격 증명] 하위 탭을 선택합니다.
. {productname} 설정 중에 사용할 로그인 정보를 기록합니다.

조직의 설정에 따라 왼쪽 탐색 모음에서 btn:[구독 활성화] 메뉴를 사용하여 구독을 활성화해야 할 수도 있습니다.

{scc} 사용에 대한 자세한 내용은 https://scc.suse.com/docs/help.를 참조하십시오.



[[installation-general-supportedbrowsers]]
== {productname} {webui}에 대한 지원되는 브라우저입니다.

{webui}를 사용하여 {productname} 환경을 관리하려면 최신 웹 브라우저를 실행해야 합니다.

{productname}은 다음에서 지원됩니다:

* {sles}과 함께 제공되는 최신 Firefox 브라우저
* 모든 운영 체제의 최신 Chrome 브라우저
* Windows와 함께 제공되는 최신 Edge 브라우저

Windows Internet Explorer는 지원되지 않습니다.
{productname} {webui}는 Windows Internet Explorer에서 올바르게 렌더링되지 않습니다.



== SSL 인증서

{productname}은 클라이언트가 올바른 서버에 등록되었는지 확인하기 위해 SSL 인증서를 사용합니다.
기본적으로 {productname}는 자체 서명된 인증서를 사용합니다.
타사 CA에 의해 서명된 인증서가 있는 경우, 이를 {productname} 설치에 가져올 수 있습니다.
인증서 체인의 모든 CA 인증서는 `X509v3 Basic Constraints`을(를) `critical`로 표시하고 `CA:TRUE`을(를) 포함해야 합니다.
Python 3.13 이상을 포함한 엄격한 인증서 유효성 검사기는 이 요구 사항을 충족하지 않는 CA 인증서를 거부합니다.

* 자체 서명된 인증서에 대한 자세한 내용은 xref:administration:ssl-certs-selfsigned.adoc[]을 참조하십시오.
* 가져온 인증서에 대한 자세한 내용은 xref:administration:ssl-certs-imported.adoc[]을 참조하십시오.





