ifndef::backend-pdf[]
[[installation-and-upgrade-overview]]
= 배포 및 업그레이드 가이드 개요
:description: SUSE Multi-Linux Manager 서버 및 프록시를 배포하고 관리하는 방법을 단계별로 안내합니다.
:revdate: 2025-05-21
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

// HTML Publication date 
**발행일:** {docdate}

== 기본 설정 


이 안내서는 {productname} 서버 및 프록시 배포, 업그레이드 및 관리에 대한 포괄적인 단계별 지침을 제공합니다.

다음 방법으로 명령 사용:

* **요구사항:** 원활한 설정을 위한 필수 하드웨어, 소프트웨어 및 네트워킹 전제 조건을 설명합니다.
* **배포 및 설치:** {productname}를 컨테이너로 배포하고 초기 구성을 완료하는 방법을 안내합니다.
* **업그레이드 및 마이그레이션:** 작동 중지 시간을 최소화하면서 {productname}를 업그레이드하고 마이그레이션하는 과정을 자세히 설명합니다.
* **기본 서버 관리:** 기본적인 서버 작업을 다루며, {productname}를 효율적으로 시작하는 데 도움을 줍니다. 

== 저작권 고지

// HTML Copyright
저작권 © {copyrightdate} SUSE LLC 및 기여자들. All rights reserved.
GNU 자유 문서 라이선스 버전 1.2 또는 (귀하의 선택에 따라) 버전 1.3의 조건에 따라 이 문서를 복사, 배포 및/또는 수정할 수 있는 권한이 부여됩니다. 불변 섹션은 이 저작권 고지 및 라이선스입니다. 라이선스 버전 1.2의 복사본은 xref:legal:license.adoc[GNU 자유 문서 라이선스]라는 제목의 섹션에 포함되어 있습니다.

== 상표
// HTML Trademarks
SUSE 상표에 대한 내용은 https://www.suse.com/company/legal/을 참조하십시오. 모든 제3자 상표는 해당 소유자에게 속합니다. 상표 기호(®, ™ 등)는 SUSE 및 그 계열사의 상표를 나타냅니다. 별표(*)는 제3자 상표를 나타냅니다.
이 책에 포함된 모든 정보는 최대한 주의를 기울여 작성되었습니다. 그러나 이것이 완전한 정확성을 보장하지는 않습니다. SUSE LLC, 그 계열사, 저자 및 번역자는 가능한 오류나 그로 인한 결과에 대해 책임을 지지 않습니다.
endif::[]

ifdef::backend-pdf[]

<<<

:!sectnums:

[preface]
== 기본 설정

배포 및 업그레이드 가이드 개요 +
{productname} {productnumber}

이 안내서는 {productname} 서버 및 프록시 배포, 업그레이드 및 관리에 대한 포괄적인 단계별 지침을 제공합니다.

다음 방법으로 명령 사용:

* **요구사항:** 원활한 설정을 위한 필수 하드웨어, 소프트웨어 및 네트워킹 전제 조건을 설명합니다.
* **배포 및 설치:** {productname}를 컨테이너로 배포하고 초기 구성을 완료하는 방법을 안내합니다.
* **업그레이드 및 마이그레이션:** 작동 중지 시간을 최소화하면서 {productname}를 업그레이드하고 마이그레이션하는 과정을 자세히 설명합니다.
* **기본 서버 관리:** 기본적인 서버 작업을 다루며, {productname}를 효율적으로 시작하는 데 도움을 줍니다. 

// PDF Publication

**발행일:** {docdate}


// PDF Copyright
저작권 © {copyrightdate} SUSE LLC 및 기여자들. All rights reserved.
GNU 자유 문서 라이선스 버전 1.2 또는 (귀하의 선택에 따라) 버전 1.3의 조건에 따라 이 문서를 복사, 배포 및/또는 수정할 수 있는 권한이 부여됩니다. 불변 섹션은 이 저작권 고지 및 라이선스입니다. 라이선스 버전 1.2의 복사본은 xref:legal:license.adoc[GNU 자유 문서 라이선스]라는 제목의 섹션에 포함되어 있습니다.

// PDF Trademarks
SUSE 상표에 대한 내용은 https://www.suse.com/company/legal/을 참조하십시오. 모든 제3자 상표는 해당 소유자에게 속합니다. 상표 기호(®, ™ 등)는 SUSE 및 그 계열사의 상표를 나타냅니다. 별표(*)는 제3자 상표를 나타냅니다.
이 책에 포함된 모든 정보는 최대한 주의를 기울여 작성되었습니다. 그러나 이것이 완전한 정확성을 보장하지는 않습니다. SUSE LLC, 그 계열사, 저자 및 번역자는 가능한 오류나 그로 인한 결과에 대해 책임을 지지 않습니다.

<<<

toc::[]

:sectnums:

endif::[]
