[[install-pubcloud-requirements]]
= 공용 클라우드 요구사항
:description: 공용 클라우드 인프라에서 이러한 테스트된 요구 사항으로 SUSE 다중 리눅스 관리자를 구성하여 안전한 설정을 보장하십시오.
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

이 섹션에서는 공용 클라우드 인프라에 {productname}을 설치하기 위한 요구 사항을 제공합니다.
우리는 Amazon EC2, Google Compute Engine 및 Microsoft Azure에서 이러한 지침을 테스트했지만, 다른 제공업체에서도 약간의 변형이 있을 수 있습니다.

시작하기 전 고려해야 할 사항은 다음과 같습니다.

* {productname} 설정 절차는 전방 확인된 역 DNS 조회를 수행합니다.
  설정 절차가 완료되고 {productname}가 예상대로 작동하려면 이것이 성공해야 합니다.
  {productname}을 설정하기 전에 호스트 이름 및 IP 구성을 수행하는 것이 중요합니다.
* {productname} 서버 및 프록시 인스턴스는 DNS 항목을 관리할 수 있는 네트워크 구성에서 실행해야 하지만 인터넷에서 전체적으로 액세스할 수 없습니다.
* 이 네트워크 구성에서는 DNS 확인이 제공되어야 합니다: `hostname -f`은 FQDN(정규화된 도메인 이름)을 반환해야 합니다.
* DNS 확인은 클라이언트 연결에도 중요합니다.
* DNS는 선택한 클라우드 프레임워크에 따라 다릅니다.
  자세한 지침은 클라우드 제공업체 문서를 참조하십시오.
* 소프트웨어 리포지토리, 서버 데이터베이스 및 프록시 Squid 캐시를 외부 가상 디스크에 위치시키는 것을 권장합니다.
  이것은 인스턴스가 예기치 않게 종료될 경우 데이터 손실을 방지합니다.
  이 섹션에는 외부 가상 디스크를 설정하는 지침이 포함되어 있습니다.



== 네트워크 요구사항


공용 클라우드에서 {productname}을 사용할 때는 제한된 네트워크를 사용해야 합니다.
적절한 방화벽 설정이 적용된 VPC 프라이빗 서브넷을 사용하는 것을 권장합니다.
지정된 IP 범위에 있는 기계만 인스턴스에 액세스할 수 있어야 합니다.

[WARNING]
====
공용 클라우드에서 {productname}을 실행하는 것은 강력한 보안 조치를 구현하는 것을 의미합니다. 인스턴스에 대한 액세스를 제한하고 필터링하며 모니터링하고 감사하는 것이 필수적입니다. {SUSE}는 적절한 경계 보안이 없는 전 세계적으로 접근 가능한 {productname} 인스턴스에 대해 강력히 반대합니다.
====

{productname} {webui}에 액세스하려면 네트워크 액세스 제어를 구성할 때 HTTPS를 허용하십시오.
이것은 {productname} {webui}에 액세스할 수 있게 해줍니다.

EC2와 Azure에서 새 보안 그룹을 생성하고 HTTPS에 대한 인바운드 및 아웃바운드 규칙을 추가하십시오.
GCE에서는 `Firewall` 섹션 아래에 있는 `Allow HTTPS traffic` 확인란을 선택하십시오.



== 스토리지 볼륨 준비

저장소와 데이터베이스는 {productname}의 루트 볼륨과 별도의 저장 장치에 저장하는 것이 좋습니다.
이렇게 하면 데이터 손실을 방지하고 성능을 향상시킬 수 있습니다.

{productname} 컨테이너는 기본 저장소 위치를 사용합니다. 이 위치는 사용자 지정 저장소를 위해 배포 전에 구성해야 합니다. 
자세한 내용은 xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[지속적인 컨테이너 볼륨]을 참조하십시오. 

[IMPORTANT]
====
공용 클라우드 설치에는 논리적 볼륨 관리(LVM)를 사용하지 않아야 합니다.
====


리포지토리 저장용 디스크의 크기는 {productname}으로 관리할 배포판 및 채널의 수에 따라 다릅니다.
가상 디스크를 연결하면 인스턴스에 Unix 장치 노드로 나타납니다.
장치 노드의 이름은 제공업체와 선택한 인스턴스 유형에 따라 다를 수 있습니다.

{productname} 서버의 루트 볼륨이 100{nbsp}GB 이상인지 확인하십시오.
500{nbsp}GB 이상의 추가 저장 디스크를 추가하고 가능하면 SSD 저장소를 선택하십시오.
{productname} 서버의 클라우드 이미지는 인스턴스가 시작될 때 이 별도의 볼륨을 할당하는 스크립트를 사용합니다.

인스턴스를 시작할 때 {productname} 서버에 로그인하고 이 명령을 사용하여 사용 가능한 모든 저장소 장치를 찾을 수 있습니다:

----
hwinfo --disk | grep -E "Device File:"
----

어떤 장치를 선택해야 할지 확실하지 않은 경우 `lsblk` 명령을 사용하여 각 장치의 이름과 크기를 확인하십시오.
찾고 있는 가상 디스크의 크기와 일치하는 이름을 선택하십시오.

`mgr-storage-server` 명령을 사용하여 외부 디스크를 설정할 수 있습니다.
`/manager_storage`에 마운트된 XFS 파티션을 생성하고 이를 데이터베이스와 저장소의 위치로 사용합니다:

----
/usr/bin/mgr-storage-server <devicename>
----

ifeval::[{mlm-content} == true]
저장소 볼륨 및 파티션 설정에 대한 자세한 내용은 xref:installation-and-upgrade:hardware-requirements.adoc[]을 참조하십시오.
endif::[]
