= {productname} Server Deployment on {opensuse} {tumbleweed}
:revdate: 2025-10-08
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]


== 배포 준비


이 섹션에서는 {productname} 서버 설정 및 배포에 대한 전문 지식을 습득할 수 있습니다. 이 프로세스는 [command]``Podman``, [systemitem]``Uyuni 컨테이너 유틸리티``의 설치, 배포, [command]``mgrctl``을 통해 컨테이너와의 상호작용을 시작하는 프로세스로 구성됩니다.

[NOTE]
====
This section assumes you have already configured an {opensuse} {tumbleweed} host server, whether it is running on a physical machine or within a virtual environment.

https://download.opensuse.org/tumbleweed/
====


== 컨테이너 호스트 일반 요구사항

일반 요구사항은 xref:installation-and-upgrade:general-requirements.adoc[일반 요구사항]에서 확인할 수 있습니다.

An {opensuse} {tumbleweed} server should be installed from installation media.

https://download.opensuse.org/tumbleweed/

이 절차는 아래에 설명되어 있습니다.

[[installation-server-containers-requirements]]
== 컨테이너 호스트 요구사항

CPU, RAM, 스토리지 요구사항은 xref:installation-and-upgrade:hardware-requirements.adoc[하드웨어 요구사항]에서 확인할 수 있습니다.


[IMPORTANT]
====
클라이언트가 FQDN 도메인 이름을 확인할 수 있도록 하려면 컨테이너화된 서버와 호스트 컴퓨터가 모두 올바르게 작동하는 DNS 서버에 연결되어 있어야 합니다. 또한 역방향 확인도 올바르게 구성해야 합니다.
====


== 컨테이너와 함께 사용할 수 있도록 Uyuni 도구 설치


.Procedure: Installing Uyuni Tools on {opensuse} {tumbleweed}
[role="procedure"]
____

. On your local host, open a terminal window and log in.
. Add the following repository to your {opensuse} {tumbleweed} server. You might need to use `sudo` for the following commands.

+

----
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-$(arch)-Media1/ uyuni-server-stable
----

+

. Refresh the repository list and import the key:

+

----
zypper ref
----

+

When prompted, trust and import the new repository GPG key.

+

. 컨테이너 도구를 설치합니다.

+

[source, shell]
----
zypper in mgradm mgrctl mgradm-bash-completion mgrctl-bash-completion uyuni-storage-setup-server
----

____

Uyuni 컨테이너 유틸리티에 대한 자세한 내용은 link:https://build.opensuse.org/repositories/systemsmanagement:Uyuni:Stable:ContainerUtils[Uyuni 컨테이너 유틸리티]를 참조하십시오.


== 사용자 정의 영구 스토리지 구성

이 단계는 선택 사항입니다. 그러나 인프라에 사용자 정의 영구 스토리지가 필요한 경우 [command]``mgr-storage-server`` 도구를 사용하십시오.

자세한 내용은 [command]``mgr-storage-server --help``를 참조하십시오. 이 도구는 컨테이너 스토리지 및 데이터베이스 볼륨 생성을 간소화합니다.

다음 방법으로 명령 사용:
----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----

예:
----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----

[NOTE]
====
이 명령은 [path]``/var/lib/containers/storage/volumes``에 영구 스토리지 볼륨을 생성합니다.

자세한 내용은 xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]에서 확인할 수 있습니다.
====


== Install and Enable Podman

Before deploying {productname}, you must install and enable [package]``podman``.

.Procedure: Installing and Enabling Podman
[role=procedure]
____

. Log in as root and install podman:
+
[source, shell]
----
zypper in podman
----

. Start and enable the Podman service:
+
[source, shell]
----
systemctl enable --now podman.service
----

____


== Podman을 사용한 Uyuni 컨테이너 배포

=== [command]``mgradm`` 개요

[command] ``mgradm`` 도구를 사용하여 {productname}을(를) 컨테이너로 배포합니다. {productname} 서버는 2가지 방법으로 컨테이너로 배포할 수 있습니다. 이 섹션에서는 기본 컨테이너 배포를 중심으로 설명합니다.

사용자 정의 구성 파일을 사용하여 배포하는 방법에 대한 자세한 내용은 xref:installation-and-upgrade:container-management/mgradm-yaml-custom-configuration.adoc[]에서 확인할 수 있습니다.

자세한 내용은 명령줄에서 [command]``mgradm --help``를 실행하여 확인할 수 있습니다.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../installation-and-upgrade/partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
endif::[]

.절차: Podman을 사용한 Uyuni 컨테이너 배포
. 터미널에서 sudo 사용자 또는 루트로 다음 명령을 실행합니다.
+
[source, shell]
----
sudo mgradm install podman
----
+
[IMPORTANT]
====
컨테이너를 sudo 또는 루트로 배포해야 합니다. 이 단계를 건너뛰면 터미널에 다음과 같은 오류가 표시됩니다.

[source, shell]
----
INF Setting up uyuni network
9:58AM INF Enabling system service
9:58AM FTL Failed to open /etc/systemd/system/uyuni-server.service for writing 
error="open /etc/systemd/system/uyuni-server.service: permission denied"
----
====

. 배포가 완료될 때까지 기다립니다.
. 브라우저를 열고 서버 FQDN으로 이동합니다.

//In this section you learned how to deploy an {productname} Server container.



=== 영구 볼륨

많은 사용자가 영구 볼륨의 위치를 지정하기를 원할 것입니다.

[NOTE]
====
{productname}을(를) 테스트하는 경우에는 이러한 볼륨을 지정할 필요가 없습니다. [command]``mgradm``은 기본적으로 올바른 볼륨을 설정합니다.

볼륨 위치 지정은 일반적으로 대규모 프로덕션 배포에서 사용됩니다.
====

기본적으로 [command] ``podman``은 볼륨을 [path]``/var/lib/containers/storage/volumes/``에 저장합니다.

이 경로 또는 그 하위에 예상되는 볼륨 경로(예: [path]``/var/lib/containers/storage/volumes/var-spacewalk``)에 디스크를 마운트하여 볼륨에 대한 사용자 지정 스토리지를 제공할 수 있습니다. 이는 데이터베이스 및 패키지 미러에 특히 중요합니다.

컨테이너의 모든 영구 볼륨 목록은 다음을 참조하십시오.

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]


