= {productname} 서버 air-gapped 배포
:revdate: 2025-07-25
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

== air-gapped 배포란?


air-gapped 배포란 안전하지 않은 네트워크, 특히 인터넷으로부터 물리적으로 격리된 네트워크 시스템을 설정하고 운영하는 것을 의미합니다. 이러한 유형의 배포는 일반적으로 군사 설치, 금융 시스템, 중요 인프라 및 민감한 데이터를 처리하고 외부 위협으로부터 보호해야 하는 모든 곳에서 보안 수준이 높은 환경에서 사용됩니다.

인터넷이 연결된 컴퓨터에서 [systemitem]``Podman`` 또는 [systemitem]``Docker``를 사용하여 컨테이너 이미지를 쉽게 당겨올 수 있습니다.

.절차: 이미지 당겨오기
. 원하는 이미지를 당겨온 다음, 이미지를 [literal]``tar`` 아카이브로 저장합니다. 예:

+
.Podman
----
podman pull registry.opensuse.org/uyuni/server:latest registry.opensuse.org/uyuni/server-postgresql:latest
podman save -m --output images.tar registry.opensuse.org/uyuni/server:latest registry.opensuse.org/uyuni/server-postgresql:latest
----
+
.Docker
----
docker pull registry.opensuse.org/uyuni/server:latest registry.opensuse.org/uyuni/server-postgresql:latest
docker save --output images.tar registry.opensuse.org/uyuni/server:latest registry.opensuse.org/uyuni/server-postgresql:latest
----
+
. Transfer the resulting [filename]``images.tar`` to the Server container host and load it using the following command:
+
.서버 이미지 로드
----
podman load -i images.tar
----

== air-gapped 환경에서 {salt} 공식의 컨테이너 이미지 가져오기

일부 공식(예: Bind 및 DHCP(Kea))도 컨테이너를 사용합니다. air-gapped 환경에서 이를 사용하려면 해당 이미지를 가져와 아카이브에 저장한 후 {productname} 프록시 또는 다른 관리형 시스템에 로드해야 합니다.

이미지는 ``registry.opensuse.org``에서 제공됩니다.

.절차: air-gapped 환경의 공식 이미지 가져오기
. 인터넷에 연결된 시스템에서 필요한 이미지를 당겨옵니다. 예를 들어:
+
[source, shell]
----
podman pull registry.opensuse.org/opensuse/bind:latest
podman pull registry.opensuse.org/opensuse/kea:latest
----
. 이미지를 TAR 아카이브에 저장합니다.
+
[source, shell]
----
podman save -o formula-images.tar registry.opensuse.org/opensuse/bind:latest registry.opensuse.org/opensuse/kea:latest
----
. ``formula-images.tar`` 파일을 air-gapped 시스템으로 전송합니다.
. air-gapped 시스템에 이미지를 로드합니다.
+
[source, shell]
----
podman load -i formula-images.tar
----

=== Deploy {productname} on {opensuse} {tumbleweed}

또한 {productname}은(는) 필요한 모든 컨테이너 이미지를 시스템에 설치할 수 있는 RPM 패키지로 제공합니다.

[NOTE]
====
사용자는 필요한 RPM을 내부 네트워크에서 사용할 수 있도록 해야 합니다. 이 작업 두 번째 {productname} 서버 또는 일종의 미러를 사용하여 수행할 수 있습니다.
====

.Procedure: Install {productname} on {opensuse} {tumbleweed} in air-gapped environment
. Install {opensuse} {tumbleweed}.
. 시스템을 업데이트합니다.
. 도구 패키지 및 이미지 패키지 설치($ARCH$를 올바른 아키텍처로 대체):

+

[source, shell]
----
zypper install mgradm* mgrctl* uyuni-server*-image*
----

+

. {productname}을(를) [command]``mgradm``으로 배포합니다. Air-gapped 환경에서는 [command]``--pullPolicy Never`` 옵션을 사용할 수 있습니다.


For more detailed information about installing {productname} Server on {opensuse} {tumbleweed}, see xref:container-deployment/uyuni/server-deployment-uyuni.adoc[Server Deployment].

{productname} 서버를 업그레이드하려면 시스템의 모든 패키지를 업그레이드하고 xref:container-management/updating-server-containers.adoc[서버 업그레이드]에 정의된 절차를 따릅니다.

