= {productname} Documentation

ifeval::[{mlm-content} == true]
[.currentrel]**Version: {productnumber} {currentversion}**
endif::[]

ifeval::[{uyuni-content} == true]
**Version**: {productnumber} 
endif::[]

ifeval::[{mlm-content} == true]
[IMPORTANT]
====
We are currently in the process of enhancing the [.currentrel]**{productnumber}** **{currentversion}** documentation. 

**We Value Your Input:** Your feedback is crucial to us! 
If you find any aspects of the documentation unclear or notice missing information, please do not hesitate to reach out. 
We appreciate your questions and suggestions, which are vital in helping us improve.


Submit feedback: https://github.com/uyuni-project/uyuni-docs/issues
====
endif::[]

ifeval::[{uyuni-content} == true]
[IMPORTANT]
====
We are currently in the process of enhancing the [.currentrel]**{releaseversion}** documentation. 

**We Value Your Input:** Your feedback is crucial to us! 
If you find any aspects of the documentation unclear or notice missing information, please do not hesitate to reach out. 
We appreciate your questions and suggestions, which are vital in helping us improve.


Submit feedback: https://github.com/uyuni-project/uyuni-docs/issues
====
endif::[]


== What is {productname}?

// [#salt.gloss] may be used to create a tooltip for a glossary term: see branding/supplemental-ui/mlm/mlmcom/partials/footer-scripts.hbs

{productname} is a solution for organizations that require robust control over maintenance and package deployment on their servers.
It enables you to manage large sets of Linux systems and keep them up-to-date, with automated software management, asset management, and system provisioning.
It also allows you to maintain a high level of security while effectively managing system life-cycle requirements.

{productname} uses {salt} to provide event-driven configuration and management control.
The Salt-master orchestrates tens of thousands of {salt} clients ({productname} clients) using remote execution.

{productname} offers seamless management of {sle}, {opensuse}, {rhel}, {centos}, {oracle}, {ubuntu}, {debian}, {amazon}, {almalinux}, and {raspberrypios} client systems.
They can be on-premise, or on public cloud, private cloud, hybrid cloud or even multi-cloud environments.



// MLM index content

ifeval::[{mlm-content} == true]
== Available Documentation

The following documentation for {productname} version {productnumber} is available in PDF format for easy download and reference.


Download the complete set of PDFs icon:caret-right[] icon:file-archive[link="../suse-multi-linux-manager-docs_en-pdf.zip"]

[TIP]
====
{productname} documentation is available in several locations and formats.
For the most up-to-date version of this documentation, see link:https://documentation.suse.com/[SUSE Multi-Linux Manager].
====

endif::[]


//Uyuni Index content

ifeval::[{uyuni-content} == true]
== Available Documentation

The following documentation for {productname} version {productnumber} is available in PDF format for easy download and reference.

Download the complete set of PDFs icon:caret-right[] icon:file-archive[link="../uyuni-docs_en-pdf.zip"]
endif::[]
