[[installation-general-requirements]]
= 一般要求

在开始安装之前，请确保：

* 准备好当前的 {scc} 组织身份凭证
* 能够访问安装媒体
* 环境符合硬件和网络要求
* 准备好环境所需的任何 SSL 证书

本节包含其中每项要求的详细信息。

有关支持的客户端和功能的完整列表，请参见 xref:client-configuration:supported-features.adoc[]。


[IMPORTANT]
====
{productname} {productnumber} 基于主机操作系统 SLES {sles-version} {sp-version}。{productname} 附带两年的维护生命周期。有关详细信息，请参见 link:https://www.suse.com/lifecycle/[]。

{sles-version} 的长期服务包支持 (LTSS) 不可添加到 {productname}。此外，无法使用 SLES for SAP 作为 {productname} 的基础来延长底层操作系统的生命周期。
====



[[install.scc-register]]
== 获取 SUSE Customer Center 身份凭证

安装 {sles} 和 {productname} 之前在 {scc} 中创建一个帐户。

[[creating.scc.account.mgr]]
.过程：获取 SCC 组织身份凭证
. 在网页浏览器中导航到 https://scc.suse.com/login。
. 登录到您的 SCC 帐户，或遵照提示创建一个新帐户。
. 如果您尚未这样做，请单击 btn:[连接到组织] 并键入或搜索您的组织。
. 单击 btn:[管理我的组织]，并在列表中单击您的组织名称以将其选中。
. 单击 btn:[组织] 选项卡，然后选择 btn:[组织身份凭证] 选项卡。
. 记下您的登录信息，以便在设置 {productname} 期间使用。

根据组织的设置，还可能需要使用 btn:[Activate Subscriptions] 菜单激活您的订阅。

有关使用 SCC 的详细信息，请参见 https://scc.suse.com/docs/help。


[[install.media]]
== 统一安装程序

通过 {sle} 统一安装程序来安装 {susemgr} Server 和 Proxy。

ifeval::[{suma-content} == true]
只需提供 {productname} 的有效注册代码，而无需单独提供 SLES{nbsp}{sles-version} {sp-version} 的注册代码。
endif::[]

请从 https://download.suse.com 上下载 {sle} 统一安装程序（如果尚未下载）。

用于安装 SUSE Manager 的 {sle} {sles-version} {sp-version} 直接链接：https://www.suse.com/download/suse-manager。

如需更高版本或不同的体系结构（例如 {ibmz}），请选择相应的项。使用统一安装程序可以安装许多基于 SLE 的基础产品，例如 SLES、SLES for SAP Applications 或 {susemgr}。



[[installation-general-supportedbrowsers]]
== {susemgr} {webui} 支持的浏览器

要使用 {webui} 来管理您的 {susemgr} 环境，需确保运行最新的网页浏览器。

以下浏览器支持 {susemgr}：

* {sles} 随附的最新 Firefox 浏览器
* 所有操作系统上的最新 Chrome 浏览器
* Windows 随附的最新 Edge 浏览器

不支持 Windows Internet Explorer。在 Windows Internet Explorer 中无法正常呈现 {productname} {webui}。



== SSL 证书

{productname} 使用 SSL 证书来确保客户端注册到正确的服务器。{productname} 默认使用自我签名证书。如果您的证书已由第三方 CA 签名，可将其导入 {productname} 安装。

* 有关自我签名证书的详细信息，请参见 xref:administration:ssl-certs-selfsigned.adoc[]。
* 有关导入的证书的详细信息，请参见 xref:administration:ssl-certs-imported.adoc[]。
