[[pubcloud-setup]]
= 公有云设置

{productname} Server 需要注册到 {scc} 中以接收更新，之后您才能登录。

[IMPORTANT]
====
必须在运行 YaST {productname} 设置过程之前设置储存设备。有关详细信息，请参见 xref:installation:pubcloud-requirements.adoc[]。
====

请按照云提供商的说明通过 SSH 连接实例，然后运行以下命令启动设置过程：

----
yast2 susemanager_setup
----

按照提示操作，然后等待设置过程完成。

有关使用 {yast} 设置 {productname} 的详细说明，请参见 xref:installation:server-setup.adoc[]。




== 激活公有云模块

要在公有云实例上使用 {productname}，需要激活公有云模块。



.过程：激活公有云模块
. 在 {productname} Server 上打开 {yast} 管理工具，然后导航到menu:软件[软件储存库]。
. 单击 btn:[添加] 并选择[guimenu]``注册服务器上的扩展和模块``。
. 在[guimenu]``可用的扩展``字段中选择[guimenu]``Public Cloud Module``。

如果您偏爱使用命令行，可通过以下命令添加该模块：
----
SUSEConnect -p sle-module-public-cloud/15.2/x86_64
----

安装过程完成后，可以检查是否已安装全部所需的模块。在命令提示符下输入：

----
SUSEConnect --status-text
----

对于公有云上的 {productname} Server，预期安装的模块包括：

* {sles} Basesystem Module
* Python 2 Module
* Server Applications Module
* Web and Scripting Module
* SUSE Manager Server Module
* Public Cloud Module



== 在 {webui} 中完成设置

使用类似如下的地址在网页浏览器中打开 {productname} {webui}：

----
https://<public_IP>
----

使用管理员帐户登录 {productname} {webui}。用户名和口令因提供商而异。

.默认管理员帐户细节
[cols="1,1,1", options="header"]
|===
| 提供商              | 默认用户名  | 默认口令
| Amazon EC2            | ``admin``         | ``<instance-ID>``
| Google Compute Engine | ``admin``         | ``<instance-ID>``
| Microsoft Azure       | ``admin``         |``<instance-name>-suma``
|===

可以从公有云实例的 Web 控制台或者从命令提示符检索实例名称或 ID：

Amazon EC2：

----
ec2metadata --instance-id
----

Google Compute Engine：

----
gcemetadata --query instance --id
----

Microsoft Azure：

----
azuremetadata --compute --name
----


首次登录到管理员帐户时，系统会为您分配一个自动生成的组织名称。请导航到menu:管理[组织]编辑组织名称，以更改此名称。


[IMPORTANT]
====
首次登录到管理员帐户时，请更改默认口令以保护您的帐户。
====

有关设置 {productname} Server 的详细信息，请参见 xref:installation:server-setup.adoc[]。


使用 {productname} {webui} 添加所需的软件产品，并安排储存库同步。为此，最好的办法是导航到menu:管理[安装向导]并按照提示操作。

有关安装向导的详细信息，请参见 xref:installation:setup-wizard.adoc[]。


如果您打算注册 {ubuntu} 或 {rhel} 客户端，则需要设置自定义储存库和频道。有关详细信息，请参见 xref:client-configuration:registration-overview.adoc[] 中的相关章节。


要同步您的频道，请导航到menu:软件[管理 > 频道]。单击您创建的每个频道，导航到menu:储存库[同步]选项卡，然后单击 btn:[立即同步]。您也可以在此屏幕中安排同步。


[IMPORTANT]
====
引导客户端之前，请确保为该产品选择的所有频道都已同步。

同步过程有时可能需要数小时才能完成，特别是 openSUSE、SLES ES 和 RHEL 频道。
====


设置好 {productname} Server 后，您便可开始注册客户端。有关在公有云上注册客户端的详细信息，请参见 xref:client-configuration:clients-pubcloud.adoc[]。
