[[setup-wizard]]
= 安装向导

完成 {productname} 安装后，可以使用安装向导来完成最后几个步骤。在安装向导中可以配置 HTTP 代理、组织身份凭证和 {suse} 产品。

当您首次登录到 {productname} {webui} 时，默认会显示安装向导。可以通过导航到menu:管理[安装向导]来直接访问安装向导。



== 配置 HTTP 代理

{productname} 可以使用代理连接到 {scc} (SCC) 或其他远程服务器。请导航到 [guimenu]``HTTP 代理``选项卡来配置代理。

需要提供代理的主机名。请使用语法 ``<主机名>:<端口>``。例如：``<example.com>:8080``。

可以通过清除字段来禁用代理。


[IMPORTANT]
====
请确保所选的 {productname} Proxy 用户名或口令不包含 ``@`` 或 ``:`` 字符。这些字符是保留的字符。
====



== 配置组织身份凭证

您的 {scc} 帐户与组织的管理帐户相关联。您可以与组织中的其他用户共享您的 {scc} 访问权限。导航到[guimenu]``组织身份凭证``选项卡，向组织中的用户授予对您的 {scc} 帐户的访问权限。

单击 btn:[添加新身份凭证]，输入要向其授予访问权限的用户的用户名和口令，然后单击 btn:[保存]。已向其授予访问权限的用户将显示一张新的身份凭证卡片。使用该卡片上的这些按钮可以编辑或撤消访问权限：

* 检查身份凭证验证状态（绿色对勾图标或红色划叉图标）。
    要在 SCC 中重新检查身份凭证，请单击该图标。
* 设置用于服务器间同步的主要身份凭证（黄色星形图标）。
* 列出与特定身份凭证相关的订阅（列表图标）。
* 编辑身份凭证（铅笔图标）。
* 删除身份凭证（垃圾桶图标）。



== 配置产品


您的 {suse} 订阅赋予您访问各种产品的权利。导航到[guimenu]``产品``选项卡可以浏览您的可用产品，以及将 {productname} 与 {scc} 同步。

过滤器可帮助您按说明或体系结构搜索产品。

列表已按产品名称进行组织。对于每个产品，可以查看其适用的体系结构。单击产品名称旁边的箭头可以查看关联的频道和扩展。单击 btn:[频道] 图标可以查看与每个产品关联的频道的完整列表。

对于基于 {sle}{nbsp}15 和更高版本的产品，可以选择仅同步所需的软件包，或者选择同时包括建议的产品。将 btn:[包括建议的项] 开关切换为打开可以同步所有产品，将此开关切换为关闭则只同步所需的产品。

可以通过选择或取消选取单个产品，来进一步具体化您要同步的产品。

完成选择后，请单击 btn:[添加产品]，然后单击 btn:[刷新] 以安排同步。

每个产品的同步进度显示在产品名称旁边的进度条中。根据所选的产品，同步最长可能需要花费几个小时。同步完成后，新产品即可供您在 {productname} 中使用。

如果同步失败，原因可能是使用了第三方 GPG 密钥。有关产品同步查错的详细信息，请参见 xref:administration:tshoot-sync.adoc[]。
