[[ref-software-channel-details]]
= Channel Details

The menu:Software[Channel List > Channel Details] section displays the details of a selected channel. Click the advisory number of a channel in the [menuitem]``Channel List`` to see more information about the channel.

This section is divided into tabs.



== 细节

The [guimenu]``Details`` tab shows the basic channel details, including a description of the channel, and the dates it was last modified and built. This tab also provides contact information for the maintainer of the product and the GPG key details, where available.



== Managers

The [guimenu]``Managers`` tab shows which users are authorized to manage the selected channel. The list shows the username, real name, and email address of the channel manager, as well as the current status of the user.

Organization and Channel administrators can manage any channel. {productname} Administrators can change roles for specific users by clicking the username.

For more information about user management, see xref:administration:users.adoc[].



== 补丁

The [guimenu]``Patches`` tab shows all available patches for packages in the selected channel. The list displays the advisory type, names, synopsis, and the date the patch was last updated. Click the advisory name to go to the [guimenu]``Patch Details`` page.

For more information about managing patches and packages, see xref:client-configuration:patch-management.adoc[].



== 软件包

The [guimenu]``Packages`` tab shows all packages in the selected channel. The list shows the package name, summary, and the provider of the package. Click the package name to go to the [guimenu]``Package Details`` page.

For more information about managing patches and packages, see xref:client-configuration:patch-management.adoc[].




== Subscribed Systems

The [guimenu]``Subscribed Systems`` tab shows the clients currently subscribed to the selected channel. The list shows the client name and type. Check a client in the list to add it to the system set manager. Click the client name to go to the [guimenu]``System Details`` page.

For more information about the system set manager, see xref:client-configuration:system-set-manager.adoc[].



== Target Systems

The [guimenu]``Target Systems`` tab shows the clients eligible for subscription to the selected channel. This tab is only available if the selected channel is a child channel. The list shows the client name and type, and the associated base channel.

To subscribe a client to the selected channel, check the client in the list, and click btn:[Confirm].

For more information about software channels, see xref:client-configuration:channels.adoc[].
