[[ref-software-channel-mapping]]
= Distribution Channel Mapping

The menu:Software[Distribution Channel Mapping] section lists your defined default base channels. When you register a client for the first time, they will automatically be assigned to these software channels, in accordance with their architecture and operating system. Default channel mappings can be edited, but not deleted.

Click btn:[Create Distribution Channel Mapping] to create a new channel map.


[[distribution-channel-map-columns]]
[cols="1,1", options="header"]
.Distribution Channel Mapping Columns
|===
| Column                | Description
| Operating System      | The client operating system this mapping applies to.
| Release               | The operating system release this mapping applies to.
| Architecture          | The client system architecture architecture this mapping applies to.
| Channel Label         | The label of the channel.
| Organization Specific | Checked if this mapping applies only to the current organization.
|===


For more information about software channels, see xref:client-configuration:channels.adoc[].
