[[ref-systems-sd-audit]]
= Audit

The menu:Systems[Audit] section displays the results of OpenSCAP scans that you have performed on the selected client.

The Security Certification and Authorization Package (SCAP) is a standardized compliance checking solution for enterprise-level Linux infrastructures. {productname} uses OpenSCAP to implement the SCAP specifications.

For more information about OpenSCAP, see xref:administration:openscap.adoc[].

The menu:Systems[Audit] subtab is split into sections:



== List Scans

This section displays ther results of openSCAP scans that have been performed on the selected client.

The table columns on this page are:

[[openscap-scan-results]]
[cols="1,1", options="header"]
.OpenSCAP Scan Results
|===
| Name              | Description
| Xccdf Test Result | The name of the test result
| Diff              | FIXME
| Completed         | The time that the scan was completed
| Compliance        | The unweighted pass/fail ratio
| P                 | The number of checks that passed
| F                 | The number of checks that failed
| E                 | The number of errors that occurred
| U                 | The number of checks with an unknown status
| N                 | The number of checks that were not applicable to the selected client
| K                 | The number of checks not run
| S                 | The number of checks that were not selected
| I                 | The number of checks that have information available for review
| X                 | The number of checks that reported a status of fixed
| Total             | The total number of checks run
|===


Click the name of a scan test result to see details about the result.



== Schedule

This section allows you to schedule a scan for the selected client.
