[[lsd-retail]]
= Managing Large Scale Deployments in a Retail Environment

{productname} {smr} {productnumber} is an open source infrastructure management solution, optimized and tailored specifically for the retail industry.
It uses the same technology as {susemgr}, but is customized to address the needs of retail organizations.

{productname} {smr} is designed for use in retail situations where customers can use point-of-service terminals to purchase or exchange goods, take part in promotions, or collect loyalty points.
In addition to retail installations, it can also be used for novel purposes, such as maintaining student computers in an educational environment, or self-service kiosks in banks or hospitals.

{productname} {smr} is intended for use in installations that include servers, workstations, point-of-service terminals, and other devices.
It allows administrators to install, configure, and update the software on their servers, and manage the deployment and provisioning of point-of-service machines.

Point-of-Service (POS) terminals can come in many different formats, such as point-of-sale terminals, kiosks, digital scales, self-service systems, and reverse-vending systems.
Every terminal, however, is provided by a vendor, who set basic information about the device in the firmware.
{productname} {smr} accesses this vendor information to determine how best to work with the terminal in use.

In most cases, different terminals will require a different operating system (OS) image to ensure they work correctly.
For example, an information kiosk has a high-resolution touchscreen, where a cashier terminal might only have a very basic display.
While both of these terminals require similar processing and network functionality, they will require different OS images.
The OS images ensure that the different display mechanisms work correctly.

For more information about setting up and using {productname} {smr}, see xref:retail:retail-overview.adoc[].
