[[installation-proxy-containers]]
= {productname} Proxy Deployment on {opensuse} {tumbleweed}
:revdate: 2025-10-08
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]


本指南概述了 {productname} {productnumber} 代理的部署过程。本指南假定您已成功部署 {productname} {productnumber} 服务器。要成功完成部署，请执行以下操作：


.核对清单：代理部署
. 查看硬件要求。
. Install {opensuse} {tumbleweed} on a bare-metal machine.
. 将代理作为 {salt} 受控端进行引导。
. 生成代理配置。
. 将服务器中的代理配置传输到代理
. 使用代理配置将 {salt} 受控端作为代理注册到 {productname}。


.代理容器主机支持的操作系统
[NOTE]
====
The supported operating system for the container host is {opensuse} {tumbleweed}.

容器主机:: 容器主机是配备了容器引擎（例如 Podman）的服务器，可用于管理和部署容器。这些容器包含应用程序及其必备组件（例如库），但不包含完整的操作系统，因此体量很小。此设置可确保应用程序能够在不同环境中以一致的方式运行。容器主机为这些容器提供必要的资源，例如 CPU、内存和存储。
====


== 代理的硬件要求


下表列出了部署 {productname} 代理所要满足的硬件要求。

[cols="1,3,2", options="header"]
.代理硬件要求
|===

| 硬件
| 详细信息
| 建议

| CPU
| {x86_64}、{arm}
| 至少 2 个专用的 64 位 CPU 核心

| RAM
| 至少
| 2 GB

|
| 建议
| 8 GB

| 磁盘空间
| [path]``/``（根目录）
| 至少 40 GB

|
| [path]``/var/lib/containers/storage/volumes``
| 至少 100 GB，应根据您要使用的 ISO 发行套件映像、容器和引导储存库的数量来计算存储要求。

|===



== 容器主机一般要求

有关一般要求，请参见xref:installation-and-upgrade:general-requirements.adoc[一般要求]。

An {opensuse} {tumbleweed} server should be installed from installation media. This procedure is described below.



[[installation-proxy-containers-requirements]]
== 容器主机要求

有关 CPU、RAM 和存储要求，请参见xref:installation-and-upgrade:hardware-requirements.adoc[硬件要求]。


[IMPORTANT]
====
为了保证客户端能够解析 FQDN 域名，容器化服务器和主机都必须连接到正常运行的 DNS 服务器。此外，必须确保反向查找的配置正确。
====


== 安装用于容器的 Uyuni 工具


.Procedure: Installing Uyuni Tools on {opensuse} {tumbleweed}
[role=procedure]

____
. On your local host open a terminal window or start up a virtual machine running {opensuse} {tumbleweed}.
. 登录系统。
. Add the following repository to your {opensuse} {tumbleweed} server:

+

----
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Proxy-POOL-$(arch)-Media1/ uyuni-proxy-stable
----

. 刷新储存库列表并接受密钥：

+

----
zypper ref
----

. 安装容器工具：

+

[source, shell]
----
zypper in mgrpxy mgrpxy-bash-completion uyuni-storage-setup-proxy
----

+

[NOTE]
====
或者，可以安装 [systemitem]``mgrpxy-zsh-completion`` 或 [systemitem]``mgrpxy-fish-completion``。
====

____


有关 Uyuni 容器实用程序的详细信息，请参见 link:https://build.opensuse.org/repositories/systemsmanagement:Uyuni:Stable:ContainerUtils[Uyuni 容器实用程序]。


== 配置自定义永久性存储

此步骤是可选的。但是，如果您的基础架构需要自定义的永久性存储，请使用 [command]``mgr-storage-proxy`` 工具。

有关详细信息，请参见 [command]``mgr-storage-proxy --help``。此工具可以简化容器存储和 Squid 缓存卷的创建。

如下所示使用命令：

----
mgr-storage-proxy <存储磁盘设备>
----

例如：

----
mgr-storage-proxy /dev/nvme1n1
----


[NOTE]
====
此命令将在 [path]``/var/lib/containers/storage/volumes`` 中创建永久性存储卷。

有关详细信息，请参见

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]
====


== 将代理主机作为受控端进行引导

.任务：引导代理主机
. 选择menu:系统[引导]。
. 填写代理主机的相关字段。
. 从下拉列表中选择上一步骤中创建的激活密钥。
. 单击 btn:[+ 引导]。
. 等待引导过程成功完成。检查 menu:Salt[] 菜单，确认 {salt} 受控端密钥已列出并已接受。
. 重引导代理主机。
. 从menu:系统[]列表中选择主机，并在所有事件完成后再次触发重引导以完成初始配置。


.任务：更新代理主机
. 从menu:系统[]列表中选择主机，并应用所有补丁以将其更新。
. 重引导代理主机。



// FIXME 2024-12-10, ke: use the snippet also here (see MLM equiv)
[[proxy-setup-containers-generate-config]]
== 生成代理配置

{productname} 代理的配置归档由 {productname} 服务器生成。每个附加代理都需要自身的配置归档。

[IMPORTANT]
====
在生成此代理配置之前，必须将 {productname} 代理的容器主机作为 Salt 受控端注册到 {productname} 服务器。
====


您将执行以下任务：

.过程：
. 生成代理配置文件。
. 将配置传输到代理。
. 使用 [literal]``mgrpxy`` 命令启动代理。

[[proc-proxy-containers-setup-webui]]
.任务：使用 Web UI 生成代理容器配置

. 在 {webui} 中，导航到menu:系统[代理配置]，然后填写所需数据：
. 在[guimenu]``代理 FQDN``字段中，键入代理的完全限定域名。
. 在[guimenu]``父 FQDN``字段中，键入 {productname} 服务器或另一个 {productname} 代理的完全限定域名。
. 在[guimenu]``代理 SSH 端口``字段中，键入 SSH 服务在 {productname} 代理上监听的 SSH 端口。建议保留默认值 8022。
. 在[guimenu]``最大 Squid 缓存大小 [MB]``字段中，键入允许的最大 Squid 缓存大小。一般该值最多应为容器可用存储空间的 60 %。
在 [guimenu]``SSH 证书``选择列表中，选择应为 {productname} 代理生成新服务器证书还是使用现有证书。您可以考虑作为 {productname} 内置（自我签名）证书生成的证书。
+
然后根据所做的选择提供用于生成新证书的签名 CA 证书的路径，或者要用作代理证书的现有证书及其密钥的路径。
+
The CA certificates generated on the server are stored in the [path]``/var/lib/containers/storage/volumes/root/_data/ssl-build`` directory.
+
有关现有或自定义证书的详细信息以及企业和中间证书的概念，请参见 xref:administration:ssl-certs-imported.adoc[]。

. 单击 btn:[生成] 以在 {productname} 服务器中注册新代理 FQDN，并生成包含容器主机细节的配置归档。
. 片刻之后，系统会显示文件可供下载。请将此文件保存在本地。


[[proxy-deploy-containers-transfer-config]]
== 传输代理配置

{webui} 将生成配置归档。需要在代理容器主机上提供此归档。


.任务：复制代理配置

. Copy the files to the Proxy host:
+
----
scp config.tar.gz <代理 FQDN>:/root
----

. 使用以下命令安装代理：
+ 

----
mgrpxy install podman config.tar.gz
----



[[proxy-deploy-containers-transfer-start]]
== 启动 {productname} {productnumber} 代理

现在可以使用 [literal]`mgrpxy` 命令启动容器：

[[proc-install-containers-setup-start]]
.任务：启动代理并检查状态

. 调用以下命令启动代理：
+

----
mgrpxy start
----

. 调用以下命令检查容器状态：
+

----
mgrpxy status
----
+

应该会显示以下五个 {productname} 代理容器，并且它们应该是 [literal]``proxy-pod`` 容器 Pod 的一部分：

* proxy-salt-broker
* proxy-httpd
* proxy-tftpd
* proxy-squid
* proxy-ssh



=== 为服务使用自定义容器映像

默认情况下，{productname} 代理套件设置为针对其每个服务使用相同的映像版本和仓库路径。但是，可以使用以 [literal]``-tag`` 和 [literal]``-image`` 结尾的 install 参数覆盖特定服务的默认值。

例如，可以按如下方式使用此命令：

----
mgrpxy install podman --httpd-tag 0.1.0 --httpd-image registry.opensuse.org/uyuni/proxy-httpd /path/to/config.tar.gz
----

该命令会在重启 httpd 服务之前调整其配置文件。其中 [path]``registry.opensuse.org/uyuni/proxy-httpds`` 是要使用的映像，[literal]``0.1.0`` 是版本标记。

要重置为默认值，请再次运行 install 命令但不要指定这些参数：

----
mgrpxy install podman /path/to/config.tar.gz
----

此命令首先将所有服务的配置重置为全局默认值，然后重新装载配置。
