[[ref-config-files]]
= Files
:revdate: 2026-04-08
:page-revdate: {revdate}

This page lists the configuration files managed by {productname} through configuration channels.

[[config-files-list-columns]]
[cols="1,1", options="header"]
.Files Columns
|===
| Column                | Description
| Path                  | Absolute filename of the configuration file.
| Configuration Channel | Name of the configuration channel that contains the file.
| Systems Subscribed    | Number of systems subscribed to the channel.
|===

Click the [guimenu]``Path`` of a file to see its [guimenu]``Details`` tab.
Click the name of the [guimenu]``Configuration Channel`` to see the [guimenu]``Overview`` tab of the channel.
Clicking [guimenu]``Systems Subscribed`` shows all systems currently subscribed to the channel containing that file.


[NOTE]
====
By default, the maximum file size for configuration files is 128 KB (131072 bytes).
{suse} supports a configuration file size up to 1 MB.
Larger files are not guaranteed to work.
====


ifdef::showremarks[]
# 2010-12-21 - ke: will "rhn" stay here? 2010-12-28 - kkaempf: "rhn" will
    stay here. #
endif::showremarks[]

The default maximum file size is set on the {productname} Server in these files:

----
# /usr/share/rhn/config-defaults/rhn_web.conf
web.maximum_config_file_size = 131072

# /usr/share/rhn/config-defaults/rhn_server.conf
maximum_config_file_size = 131072
----

Copy these variables to [filename]``/etc/rhn/rhn.conf`` and edit them.
Values are specified in bytes, for example:

----
# /etc/rhn/rhn.conf
web.maximum_config_file_size = 262144
server.maximum_config_file_size = 262144
----


Then restart [systemitem]``spacewalk``:

----
spacewalk-service restart
----
