// FIXME
// 2024-10-15, ke: Do we still need this or parts of it?
[[lsd-hub-install]]
= Hub XMLRPC API Deployment

Before you begin, you need to install the ``hub-xmlrpc-api`` package, and configure the Hub Server to use the API.



.Procedure: Installing and Configuring the Hub XMLRPC API
. On the Hub Server, or on a host that has access to all peripheral servers' XMLRPC APIs, install the ``hub-xmlrpc-api`` package.
    The package is available in the {productname} {productnumber} repositories.
. OPTIONAL: Set the Hub XMLRPC API service to start automatically at boot time, and start it immediately:
+
----
sudo systemctl enable hub-xmlrpc-api.service
sudo systemctl start hub-xmlrpc-api.service
----

. OPTIONAL: Check that these parameters in the [path]``/etc/hub/hub.conf`` configuration file are correct:
*  ``HUB_API_URL``: URL to the Hub Server XMLRPC API endpoint.
    Use the default value if you are installing `hub-xmlrpc-api` on the Hub Server.
* ``HUB_CONNECT_TIMEOUT``: the maximum number of seconds to wait for a response when connecting to a Server.
    Use the default value in most cases.
* ``HUB_REQUEST_TIMEOUT``: the maximum number of seconds to wait for a response when calling a Server method.
    Use the default value in most cases.
* ``HUB_CONNECT_USING_SSL``: use HTTPS instead of HTTP for communicating with peripheral Servers.
    Recommended for a secure environment.

. Restart services to pick up configuration changes.


[NOTE]
====
To use HTTPS to connect to peripheral Servers, you must set the ``HUB_CONNECT_USING_SSL`` parameter to ``true``, and ensure that the SSL certificates for all the peripheral Servers are installed on the machine where the ``hub-xmlrpc-api`` service runs.
Do this by copying the ``RHN-ORG-TRUSTED-SSL-CERT`` certificate file from each peripheral Server's [path]``http://<server-url>/pub/`` directory to [path]``/etc/pki/trust/anchors/``, and run [command]``update-ca-certificates``.
====
