[[lsd-multi-server]]
= Multiple Servers with Hub to Manage Large Scale Deployments

If you need to manage a large number of clients, in most cases you can do so with a single {productname} Server, tuned appropriately.

However, if you need to manage tens of thousands of clients, you might find it easier to use one of the following mechanisms:

* Inter-Server Sunchronization (ISS)
* {productname} Hub

ISS is based on exporting data from one server (source) and importing it on another (target) server.
For more information, see xref:administration:iss_v2.adoc[].


{productname} Hub helps you manage very large deployments.
The typical Hub topology looks like this:

image::typical-hub-architecture-overview.svg[scaledwidth=80%]

This chapter gives more details about Hub deployment.

//To copy contents between servers, you can use Inter-Server Synchronization (ISS).
//ISS allows you to export data from one server (source) and import it on another (target) server.
//For more information, see xref:administration:iss_intro.adoc[].

//{productname} supports the following mechanisms of synchronization between servers:

//* xref:administration:iss_v2.adoc[]
//* xref:specialized-guides:large-deployments/hub-online-sync.adoc[]

