[[lsd-hub-reqs]]
= Hub Requirements

To set up a Hub installation, you require:

* One central {productname} Server, which acts as the Hub Server.
* One or more additional {productname} Servers, registered to the Hub as clients.
    This document refers to these as peripheral servers.
* Any number of clients registered to the peripheral servers.
* Ensure the Hub Server and all peripheral servers are running {productname}{nbsp}4.1 or higher.

[NOTE]
====
The Hub Server must not have clients registered to it.
Clients should only be registered to the peripheral servers.
====

== Peripheral Servers

Peripheral servers must be registered to the Hub Server as clients.
When you register the peripheral servers, assign them the appropriate ``SUSE Manager Server`` software channel as their base channel.
Additionally, they must be registered to the Hub Server directly, do not use a proxy.

For more information about registering clients, see xref:client-configuration:registration-webui.adoc[].


You need credentials to access the XMLRPC APIs on each server, including the Hub Server.
