[[lsd-multi-server]]
= Multiple Servers with Hub to Manage Large Scale Deployments

If you need to manage a large number of clients, in most cases you can do so with a single {productname} Server, tuned appropriately.

However, if you need to manage tens of thousands of clients, you might find it easier to use one of the following mechanisms:

* Inter-Server Sunchronization (ISS)
* {productname} Hub

ISS is based on exporting data from one server (source) and importing it on another (target) server.
For more information, see xref:specialized-guides:large-deployments/iss_v2.adoc[Inter-Server Synchronization - Version 2].


{productname} Hub helps you manage very large deployments.
The typical Hub topology looks like this:

image::typical-hub-architecture-overview.svg[scaledwidth=80%]

* One central {productname} Server, which acts as the Hub Server.
* One or more additional {productname} Servers, registered to the Hub.
  This document refers to these additional servers as peripheral servers.
* Any number of clients registered to the peripheral servers.
  Some of these clients can act as {productname} Proxies.

This chapter gives more details about Hub deployment.
