[[lsd-hub-reqs]]
= Hub Requirements
:description: Configure a central SUSE Manager server and register multiple peripheral servers as Salt clients for a complete Hub installation
:revdate: 2025-07-03
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Manager
:page-product-version: 4.3

To set up a Hub installation, you require:

* One central {productname} Server, which acts as the Hub Server.
* One or more additional {productname} Servers, registered to the Hub as Salt clients.
    This document refers to these as peripheral servers.
* Any number of clients registered to the peripheral servers.
* Ensure the Hub Server and all peripheral servers are running {productname}{nbsp}4.1 or higher.

[NOTE]
====
The Hub Server must not have clients registered to it.
Clients should only be registered to the peripheral servers.
The exceptions are build hosts, which can be connected to the Hub.
====

== Peripheral Servers

Peripheral servers must be registered to the Hub Server as Salt clients.
When you register the peripheral servers, assign them the appropriate ``SUSE Manager Server`` software channel as their base channel.
Additionally, they must be registered to the Hub Server directly, do not use a proxy.

For more information about registering clients, see xref:client-configuration:registration-webui.adoc[].


You need credentials to access the XMLRPC APIs on each server, including the Hub Server.
