[[lsd-hub-reqs]]
= Hub Requirements

To set up a Hub installation, you require:

* One central {productname} Server, which acts as the Hub Server.
* One or more additional {productname} Servers, registered to the Hub.
  This document refers to these additional servers as peripheral servers.
* Any number of clients registered to the peripheral servers.
* Ensure the Hub Server and all peripheral servers are running {productname}{nbsp}5.0 or higher.



== SSL Ceritificates

The Hub Server's and the Peripheral Servers' SSL ceritificates must be signed by the same CA.
There are two ways to fulfill this requirement:

* Use third party certificates.
* Install Hub Server first and use it to generate the certificates for the Peripheral Servers.
  For more information, see XXX.



== Hub Server

Deploy the central {productname} Server, which acts as the Hub Server, with [command]``mgradm``.
Add [option]``--hubxmlrpc-replicas 1`` to the [command]``mgradm install`` command line.
For more information about deploying with [command]``mgradm``, see xref:installation-and-upgrade:container-deployment/suma/server-deployment-suma.adoc[].

[NOTE]
====
The Hub Server must not have clients registered to it.
Clients should only be registered to the peripheral servers.
====



== Peripheral Servers

Deploy the peripheral servers with [command]``mgradm``.
For more information about deploying with [command]``mgradm``, see xref:installation-and-upgrade:container-deployment/suma/server-deployment-suma.adoc[].

Peripheral servers must be registered to the Hub Server as foreign clients.
Standard registration methods cannot be used.
Use [command]``mgradm`` on the peripheral server host:

----
mgradm hub register --api-server <HUB_FQDN> --api-user <HUB_ADMIN> --api-password <HUB_ADMIN_PASSWORD>
----

The peripheral servers must be registered to the Hub Server directly, do not use a proxy.

Optionally, it is possible to register the podman container host as a standard client ({salt} minion) and manage it from {productname} Server.

You need credentials to access the XMLRPC APIs on each server, including the Hub Server.
