[[iss2]]
= Inter-Server Synchronization version 2

If you have more than one {productname} installation, you will need to copy contents between servers.
Inter-Server Synchronization (ISS) allows you to export data from one server (hub) and import it on another server (peripheral).
This is useful for hub deployment scenarios or disconnected setups.


== Install Inter-Server Synchronization packages

To use ISS you need to install the [package]``inter-server-sync`` package on hub and peripheral servers.



== Content synchronization


[IMPORTANT]
====
Use [literal]``mgrctl term`` before running steps inside the server container.
====

.Procedure: Export data on hub server
. On the hub server, on the command line execute the ISS export command.
  The [option]``-h`` option provides detailed help:
+
----
inter-server-sync export -h
----

The export procedure creates an output directory with all the needed data for the import procedure.



.Procedure: Copy export directory to peripheral server
. Contents from the hub server needs to be synchronized to the peripheral server.
  On the command line, as root, execute:
+
----
rsync -r <PATH_EXPORTED_DIR> root@<TARGET_SERVER>:~/
----


When all contents is copied, start importing it.



.Procedure: Import data on peripheral server
. On the peripheral server, on the command line execute the ISS import command.
  The [option]``-h`` option provides detailed help:
+
----
inter-server-sync import -h
----



== Database connection configuration


Database connection configuration is loaded by default from [path]``/etc/rhn/rhn.conf``.
Properties file location can be overridden with parameter [literal]``--serverConfig``.



== Known limitations

* Hub and peripheral servers need to be on the same version.
* Export and import organization should have exactly the same name.
  The organization name is case sensitive.
