[[lsd-monitoring]]
= Monitoring Large Scale Deployments


You can monitor your {productname} environment using Prometheus and Grafana.
{productname} Server and Proxy are able to provide self-health metrics.
You can also install and manage a number of Prometheus exporters on clients.

ifeval::[{mlm-content} == true]
Prometheus and Grafana packages are included in the {productname} Client Tools for {sle}{nbsp}12, {sle}{nbsp}15, {rhel}{nbsp}7, {rhel}{nbsp}8 and openSUSE 15.x.
endif::[]

ifeval::[{uyuni-content} == true]
Prometheus and Grafana packages are included in the {productname} Client Tools for {sle}{nbsp}12, {sle}{nbsp}15, {centos}{nbsp}7, {centos}{nbsp}8 and openSUSE 15.x.
endif::[]

You need to install Prometheus and Grafana on a machine separate from the {productname} Server.
We recommend you use a managed client as your monitoring server.

It is recommended to monitor the {salt} event bus in the large scale deployments with xref:specialized-guides:salt/salt-monitoring.adoc#saline[Saline] to identify possible bottlenecks.

For more information on monitoring, see xref:administration:monitoring.adoc[].
