[[large-deployments-overview]]
= Large Deployments Guide Overview

**Updated:** {docdate}

{productname} is designed by default to work on small and medium scale installations.
For installations with more than 1000 clients per {productname} Server, adequate hardware sizing and parameter tuning must be performed.

There is no hard maximum number of supported systems.
Many factors can affect how many clients can reliably be used in a particular installation.
Factors can include which features are used, and how the hardware and systems are configured.


[WARNING]
====
Large installations require standard Salt clients.
These instructions cannot be used in environments using traditional clients or Salt SSH minions.
====

There are two main ways to manage large scale deployments.
You can manage them with a single {productname} Server, or you can use multiple servers in a hub.
Both methods are described in this book.

With large scale environments one should also consider the usage of {productname} Proxies.
Sizing and location of the Proxies will dependent on the deployment topology.
For more information see xref:installation-and-upgrade:install-proxy.adoc[].

Additionally, if you are operating within a Retail environment, you can use {productname} {smr} to manage large deployments of point-of-service terminals.
There is an introduction to {productname} {smr} in this book.

Tuning and monitoring large scale deployments can differ from smaller installations.
This book contains guidance for both tuning and monitoring within larger installations.
