[[db-migration-10]]
= バージョン9から10へのデータベースの移行

このセクションでは、PostgreSQLデータベースをバージョン9からバージョン10にアップグレードする方法について説明します。 すでにPostgreSQL 10を使用している場合、この移行を実行する必要はありません。

最新バージョンの{productname}にアップグレードする場合、PostgreSQLバージョン10または12を使用する必要があります。 バージョン9.6など古いバージョンを使用している場合、{productname}の移行を開始する前にPostgreSQLをバージョン10に移行する必要があります。

[IMPORTANT]
====
{productname} 3.2でPostgreSQL{nbsp}9.4を実行している場合、製品ドキュメント(https://documentation.suse.com/external-tree/en-us/suma/3.2/susemanager-best-practices/html/book.suma.best.practices/bp.sp.migration.html#sp.migration.postgresql)を参照してください。 PostgreSQL{nbsp}9.4からバージョン10に直接移行することはできません。
====







[[db-migration-prepare]]
== アップグレードの準備

アップグレードを開始する前に、既存の{productname}サーバを準備して、データベースのバックアップを作成します。

PostgreSQLは[path]``/var/lib/pgsql/data/``にデータを保存します。

.プロシージャ: アップグレードの準備

. アクティブなPostgreSQLのバージョンを確認します。
+
----
psql --version
----
+
PostgreSQL{nbsp}9.6を使用している場合、PostgreSQL{nbsp}10にアップグレードできます。
+
すでにPostgreSQL 10を使用している場合、この移行を実行する必要はありません。
. アクティブなsmdbaのバージョンを確認します。
+
----
rpm -q smdba
----
+
PostgreSQL{nbsp}10では``smdba``のバージョン1.6.2以降が必要です。

. データベースのバックアップを実行します。
    バックアップの詳細については、xref:administration:backup-restore.adoc[]を参照してください。




== PostgreSQLのアップグレード

[WARNING]
====
移行を実行する前に、必ずデータベースのバックアップを作成してください。
====

PostgreSQLのアップグレードは、通常のアップグレードと高速アップグレードの2つの方法で実行できます。

通常のアップグレードでは、データベースの完全なコピーが作成されるため、既存のデータベースサイズの2倍の使用可能容量が必要になります。 通常のアップグレードは、データベースのサイズおよびストレージシステムの速度に応じて、長時間を要する場合があります。

高速アップグレードには数分しかかからず、追加のディスク容量はほぼ不要です。 しかし、高速アップグレードに失敗すると、データベースをバックアップから復元する必要があります。 高速アップグレードでは、ディスク容量を使い果たすリスクが軽減されます。 通常のアップグレードでは、ファイル間のハードリンクを作成する代わりに、データベースファイルをコピーします。

PostgreSQLは[path]``/var/lib/pgsql/data/``にデータを保存します。

.プロシージャ: 通常のアップグレードの実行
. データベースのバックアップを実行します。
    バックアップの詳細については、xref:administration:backup-restore.adoc[]を参照してください。
. アップグレードを開始します。
+
----
/usr/lib/susemanager/bin/pg-migrate-96-to-10.sh
----
. アップグレードが正常に完了すると、古いデータベースのディレクトリを安全に削除して、使用されていたディスク容量を再利用できます。
    古いディレクトリの名前は[path]``/var/lib/pgsql/data-pg96``に変更されます。

[path]``pg-migrate-96-to-10.sh``スクリプトは次の操作を実行します。

* spacewalkサービスを停止する
* 実行中のデータベースをシャットダウンする
* PostgreSQL{nbsp}10がインストールされているかどうかを確認し、必要に応じてインストールする
* 新しいデフォルトとしてPostgreSQL{nbsp}9.6からPostgreSQL{nbsp}10に切り替える
* データベースの移行を開始する
* {productname}による使用に合わせて調整されたPostgreSQL設定ファイルを作成する
* データベースおよびspacewalkのサービスを開始する

[NOTE]
====
アップグレードが失敗すると、移行スクリプトは、データベースを元の状態に復元しようとします。
====

.プロシージャ: PostgreSQLの高速アップグレードの実行
. データベースのバックアップを実行します。
    確認済みのデータベースのバックアップがない場合、高速アップグレードを開始しないでください。 バックアップの詳細については、xref:administration:backup-restore.adoc[]を参照してください。
. アップグレードを開始します。
+
----
/usr/lib/susemanager/bin/pg-migrate-96-to-10.sh fast
----
. アップグレードが正常に完了すると、古いデータベースのディレクトリを安全に削除して、使用されていたディスク容量を再利用できます。
    古いディレクトリの名前は[path]``/var/lib/pgsql/data-pg96``に変更されます。
