[[proxy-uyuni-ay]]
= プロキシ - AutoYaSTを使用したアップグレード


{productname}プロキシは、あるメジャーバージョンから次のメジャーバージョンにアップグレードできます。 アップグレードプロセスは自動化されますが、アップグレードを実行する前に準備手順を実行する必要があります。

アップグレードを開始する前に、{productname}サーバのアップグレードを完了する必要があります。

古いシステムでは、最新の更新をすべて適用して{productname}プロキシを実行する必要があります。 アップグレードを始める前に、システムが最新であり、すべての更新が正しくインストールされていることを確認してください。



== アップグレードの準備

プロキシを更新するには、自動インストールディストリビューションおよび自動インストールプロファイルが必要です。 ディストリビューションは、openSUSE Leap{nbsp}{opensuse-version}に基づいている必要があります。

.プロシージャ: インストールメディアの準備
. {productname}サーバで、openSUSE Leap{nbsp}{opensuse-version}インストールメディア用にローカルディレクトリを作成します。
+
----
mkdir -p /srv/images/opensuse152
----
. インストールソースでISOイメージをダウンロードし、ISOイメージをサーバにマウントします。
+
----
mount -o loop DVD1.iso /mnt/
----
. マウントしたISOからローカルファイルシステムにすべてコピーします。
+
----
cp -r /mnt/* /srv/images/opensuse152
----
. コピーが完了したら、ISOイメージをアンマウントします。
+
----
umount /mnt
----


.手順: コマンドプロンプトからのソフトウェアチャンネルの追加
. {productname} サーバのコマンドプロンプトで root になり、 [command]``spacewalk-common-channels`` コマンドを特定のチャンネルに対して実行します:
+
----
spacewalk-common-channels opensuse_leap15_2 \
opensuse_leap15_2-non-oss \
 opensuse_leap15_2-non-oss-updates \
 opensuse_leap15_2-updates \
 opensuse_leap15_2-uyuni-client \
 uyuni-proxy-stable-leap-152
----
. [command]``spacewalk-repo-sync``を使用して、すべてのチャンネルを完全に同期します。




.プロシージャ: 自動インストールのディストリビューションの作成
. {productname}の{webui}で、menu:システム[自動インストール > ディストリビューション]に移動し、［btn:[ディストリビューションの作成]］をクリックします。
. ［[guimenu]``自動インストール可能なディストリビューションの作成``］セクションで、次のパラメータを使用します。
* ［[guimenu]``ディストリビューションラベル``］セクションに、ディストリビューションの固有の名前を入力します。
    半角の英字、数字、ハイフン、ピリオド、および下線のみを使用し、5文字以上にします。 たとえば、``proxy_152-x86_64``です。
* ［[guimenu]``ツリーパス``］フィールドに、インストールソースへの絶対パスを入力します。
    たとえば、[path]``/srv/images/opensuse152``です。
* ［[guimenu]``ベースチャンネル``］フィールドで、[systemitem]``openSUSE Leap 15.2 (x86_64)``を選択します。
* ［[guimenu]``インストーラ生成``］フィールドで、［[systemitem]``SUSE Linux``］を選択します。
* ［[guimenu]``カーネルオプション``］フィールドに、インストールでブート時にカーネルに渡すオプションを入力します。
    [option]``install=``パラメータおよび[option]``self_update=0 pt.options=self_update``パラメータはデフォルトで追加されます。
* インストールしたシステムを初めてブートするときにカーネルに渡すオプションを［[guimenu]``カーネルの後のオプション``］セクションに入力します。
. ［btn:[自動インストール可能なディストリビューションの作成]］をクリックして保存します。


自動インストール可能なディストリビューションを作成するとき、これを編集できます。そのためには、menu:システム[自動インストール > ディストリビューション]に移動し、編集するディストリビューションを選択します。



== 自動インストールプロファイルの作成

自動インストールプロファイルには、システムをインストールするために必要なインストールデータおよび設定データがすべて含まれています。 インストール完了後に実行するスクリプトを含めることもできます。 手始めに使用できるスクリプトのサンプルは、https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaSTを参照してください。 有効なAutoYaSTアップグレード設定は、https://doc.opensuse.org/projects/autoyast/#CreateProfile-upgradeを参照してください。



.プロシージャ: 自動インストールプロファイルの作成
. {productname}の{webui}で、menu:システム[自動インストール > プロファイル]に移動し、自動インストールプロファイルのスクリプトをアップロードします。
    手始めに使用できるスクリプトのサンプルは、https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaSTを参照してください。
. ［``カーネルオプション``］フィールドに``autoupgrade=1``と入力します。
    ``Y2DEBUG=1``オプションを含めることもできます。 デバッグ設定は不要ですが、問題が発生したときの調査に役立ちます。
. 自動インストールプロファイルを貼り付けるか、またはファイルアップロードフィールドを使用します。
. ［btn:[作成]］をクリックして保存します。
. アップロードしたプロファイルで変数を設定する必要がある場合、menu:システム[自動インストール > プロファイル]に移動し、編集するプロファイルを選択し、［[guimenu]``変数``］タブに移動します。
    次のフォーマットを使用して必要な変数を指定します。
+
----
<key>=<value>
----

[NOTE]
====
Saltを使用して登録されたプロキシの場合、アップグレード完了後に``spacewalk/minion_script``スニペットを使用してプロキシを再登録します。
====



== アップグレード

自動インストールプロファイルで参照するチャンネルがすべて使用可能で完全に同期していることを開始前に確認してください。



.プロシージャ: アップグレード
. {productname}サーバの{webui}で、menu:システム[システム一覧]に移動してプロキシを選択し、［[guimenu]``プロビジョニング``］タブに移動し、アップロードした自動インストールプロファイルを選択します。
. ［btn:[自動インストールをスケジュールしてから終了する]］をクリックします。
    システムによって、必要なファイルがダウンロードされ、ブートローダのエントリが変更され、再起動され、アップグレードが開始されます。



== クリーンアップ

{productname}プロキシは、アップグレードを完了すると、元々割り当てられていたチャンネルを表示します。 移行後にクリーンアップすると、正しいチャンネルの表示が確認されます。


[WARNING]
====
プロキシに使用できる更新があることをサーバから報告された場合、クリーンアップを完了する前に更新を適用しないでください。
====



.プロシージャ: クリーンアップ
. {productname}サーバの{webui}で、［[guimenu]``システム一覧``］に移動してプロキシを選択し、menu:ソフトウェア[ソフトウェアチャンネル]サブタブに移動します。
. 古いチャンネルをクリアします。
. ［[guimenu]``ベースチャンネル``］フィールドで、`openSUSE Leap 15.2 (x86_64)``を選択します。
. ［[guimenu]``子チャンネル``］フィールドで、推奨チャンネルをすべて選択します。
