[[server-z]]
= サーバ - パッチレベルのアップグレード(Zアップグレード)

この更新プロシージャは、単純なパッケージ更新または協調マイクロ更新(保守更新(MU)とも呼ばれる)について説明しています。 MU実行中、ユーザは、サービスを停止し、パッケージを更新し、スクリプトを実行してデータベースを更新し、サービスを再起動します。

例: [literal]``4.2.0`` → [literal]``4.2.1``。

つまり、まず、最新バージョンのインストールパッケージがすべてインストールされていることを確認してください。 その後、データベーススキーマをアップグレードできます。



.プロシージャ: {productname}サーバのパッケージを更新する

デフォルトでは、複数の更新チャンネルが{productname}サーバ用に設定され、有効化されます。 新規および更新したパッケージは自動的に使用可能になります。

. {productname}サーバのコマンドプロンプトでrootとしてspacewalkサービスを停止します。
+
----
spacewalk-service stop
----
. 使用できるパッチをリストします。
+
----
zypper list-patches
----
. 適用可能なすべてのパッチを適用します。
+
----
zypper patch
----
+
このコマンドはパッチを適用するだけです。
  未適用の更新をすべて更新するには、代わりに[command]``zypper up``を使用します。
. spacewalkサービスを再起動します。
+
----
spacewalk-service start
----

[NOTE]
====
デフォルトでは、zypperは、10分ごとにリポジトリを更新します([path]``/etc/zypp/zypp.conf``の``repo.refresh.delay``を参照)。 ``autorefresh``は無効になっている場合、[command]``zypper ref``を実行してすべてのリポジトリを更新します。
====

[NOTE]
====
コマンド[command]``spacewalk-schema-upgrade``は不要になりました。 これは、[command]``spacewalk-service start``の実行中に自動的に実行されます。
====

[IMPORTANT]
====
パッケージの更新の影響を受けるサービスは更新後に自動で再起動されません。 これらのサービスは、潜在的な障害を回避するために、手動で再起動する必要があります。 [command]``zypper ps``を使用して、古いコードを使用していて再起動が必要なアプリケーションを確認してください。
====

パッチ更新が再起動を推奨している場合、再起動します。
