[[upgrade-troubleshooting]]
= トラブルシューティング

このセクションでは、{productname}のアップグレードで発生する一般的な問題およびその解決方法について説明します。

アップグレードの問題の詳細については、移行ログファイルを確認してください。 ログファイルは、アップグレードしているシステムの[path]``/var/log/rhn/migration.log``にあります。





== ディスク容量が不十分

移行を開始する前に、使用できるディスク容量を確認してください。 別々のXFSファイルシステムで[path]``/var/spacewalk``と[path]``/var/lib/pgsql``を探すことをお勧めします。

別々のファイルシステムを設定している場合、[path]``/etc/fstab``を編集し、[path]``/var/lib/pqsql``サブボリュームを削除します。 サーバを再起動して変更を取得します。



== ターゲットシステムの設定の再試行

ターゲットシステムの設定を再試行する必要がある場合、次の手順を実行します。

. [path]``/root/.MANAGER_SETUP_COMPLETE``を削除します。
. PostgreSQLを停止し、[path]``/var/lib/pgsql/data``を削除します。
. ターゲットシステムのホスト名をソースシステムのホスト名と一致するように設定します。
. [path]``/etc/hosts``ファイルを確認し、必要に応じて修正します。
. ターゲットシステムの[path]``/etc/setup_env.sh``を確認し、データベース名が設定されていることを確認します。
+
----
MANAGER_DB_NAME='susemanager'
----
. ターゲットシステムを再起動します。
. [command]``mgr-setup``を再実行します。



== スキーマのアップグレードが失敗する

スキーマのアップグレードに失敗すると、データベースのバージョン確認およびその他すべてのspacewalkサービスが開始されません。 詳細および続行する方法のヒントについては[command]``spacewalk-service start``を実行してください。

バージョン確認を直接実行することもできます。

----
systemctl status uyuni-check-database.service
----

または

----
journalctl -u uyuni-check-database.service
----

一般的な[command]``spacewalk-service``コマンドを実行しない場合、これらのコマンドを実行するとデバッグ情報が出力されます。



== {webui}の読み込みが失敗する

移行後、{webui}が読み込まれない場合があります。 新しいシステムのホスト名およびIPアドレスが古いシステムと同じ場合、通常、このエラーはブラウザのキャッシュが原因です。 この重複によって一部のブラウザが混乱する可能性があります。

この問題は、キャッシュをクリアしてページを再読み込みすると解決します。 ほとんどのブラウザでは、この操作は、kbd:[Ctrl+F5]を押すことで実行できます。
