= Proxy Migration from 5.1 to 5.2
:revdate: 2025-10-19
:page-revdate: {revdate}

== Introduction


This document provides the tested and validated procedures for migrating the **{productname} proxy extension** in environments managed by **{productname}**, specifically targeting systems deployed with **{productname} Proxy 5.1**.

The upgrade scenarios covered include:

* Upgrading {sle-micro} 6.2 with **{productname} Proxy Extension** from **version 5.1** to **version {productnumber}**
* Upgrading {sles} 15 SP7 with **{productname} Proxy Extension** from **version 5.1** to **version {productnumber}**

[IMPORTANT]
====
Before migrating the proxy, it is required to first migrate the SUSE Manager 5.1 Server to {productname} {productnumber}.
====


== {sle-micro} 6.2 Proxy upgrade

This section provides the tested procedure to upgrade a {sle-micro} 6.2 host deployed with {productname} 5.1 Proxy to {productname} {productnumber} Proxy.


=== Prerequisites

* {productname} 5.1 Proxy is installed and running on {sle-micro} 6.2.
* Proxy system is registered with the {productname} Server.


=== Proxy upgrade

.Procedure: Upgrade {productname} Proxy from 5.1 to {productnumber}
[role=procedure]
____

. Verify System and {productname} Tools version.

+

[source,console]
----
cat /etc/os-release
mgrpxy --version
----

+

Confirm:

* Operating System: [literal]``SL Micro 6.2``
* Tools version: [literal]``mgrpxy version 0.2.x`` or higher

+

. Check running containers.

+

[source,console]
----
podman ps
----

+

Ensure the following containers are running:

- `proxy-squid`
- `proxy-ssh`
- `proxy-httpd`
- `proxy-tftpd`
- `proxy-salt-broker`

+

. Synchronize the new Proxy Products in {productname} Server.
  For more information, see xref:client-configuration:products.adoc[].

+

Use the Web UI to synchronize:

* [literal]``{productname} Proxy Extension {productnumber}``

+

. Perform proxy product upgrade.
  For more information, see xref:client-configuration:client-upgrades-product-migration.adoc[].

+

Navigate to the proxy system and select menu:Systems[Overview] > menu:Software[Product Upgrade].

+

Upgrade

* [literal]``{productname} Proxy Extension`` from **5.1** to **{productnumber}**

+

[IMPORTANT]
====
**Do not select** optional channels when prompted, unless you have confirmed they are required.
====

+

[NOTE]
====
It is recommended to do a dry-run first before performing the actual upgrade.
====

+

. Monitor the upgrade action.

+

You can follow the process under menu:Systems[Details > Events] tab in the {webui}.

+

. After the upgrade completes, stop the proxy container and then reboot the system.

+

[source,console]
----
mgrpxy stop
reboot
----

+

. Perform post-reboot checks. 

+

Verify {productname} extension:

+

[source,console]
----
SUSEConnect --status-text
----

+

. Verify {productname} tools version.

+

[source,console]
----
mgrpxy --version
----

+

Expected output:

- `mgrpxy version 5.2.11` or higher

+

. Install the new proxy container images as RPM packages.

+

[source,shell]
----
transactional-update pkg install suse-multi-linux-manager-5.2-<arch>-proxy*
----

+

. Reboot the Proxy.

. Upgrade proxy containers and restart them.

+

[source,console]
----
mgrpxy upgrade podman
mgrpxy stop
mgrpxy start
----

+

. Confirm proxy containers are operational.

+

[source,console]
----
podman ps
----

+

All expected proxy containers should be up and running:

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

____


=== Proxy upgrade complete

The proxy host system is now running {productname} {productnumber} Proxy packages and synchronized product channels.


== {sles} 15 SP7 Proxy upgrade

This section provides the procedure to upgrade {sles} 15 SP7 host deployed with {productname} 5.1 Proxy to {productname} {productnumber} Proxy.


=== Prerequisites

* {productname} Proxy 5.1 is installed and running on {sles} 15 SP7.
* Proxy system is registered with the {productname} Server.


=== Proxy upgrade

.Procedure: Upgrade {productname} Proxy on {sles} 15 SP7
[role=procedure]
____

. Verify operating system and {productname} tools version.

+

[source,console]
----
cat /etc/os-release
mgrpxy --version
----

+

Confirm:

* Operating System: [literal]``SUSE Linux Enterprise Server 15 SP7``
* Tools version: [literal]``mgrpxy version 0.2.x`` or higher


+

. List running proxy containers.

+

[source,console]
----
podman ps
----

+

Ensure the following containers are running:

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

+

. Synchronize the new Products in {productname} Server using the Web UI.

+

For more information, see xref:client-configuration:products.adoc[].

+

Synchronize:

* [literal]``{productname} Proxy Extension {productnumber}``

+

. Perform proxy product upgrade.

+

For more information, see xref:client-configuration:client-upgrades-product-migration.adoc[].

+

Navigate to the proxy system and select menu:Systems[Overview] > menu:Software[Product Upgrade].

+

Upgrade

* [literal]``{productname} Proxy Extension`` from **5.1** to **{productnumber}**

+

[IMPORTANT]
====
**Do not select** optional channels when prompted, unless you have confirmed they are required.
====

+

[NOTE]
====
It is recommended to do a dry-run first before performing the actual upgrade.
====

+

. Monitor the upgrade action.

+

You can follow the process under menu:Systems[Details > Events] in the {webui}.

+

. After the upgrade completes, stop the proxy container and then reboot the system.

+

[source,console]
----
mgrpxy stop
reboot
----

+

. Perform post-reboot checks. 

+

Verify the OS and {productname} extension version:

+

[source,console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

. Verify {productname} tools version.

+

[source,console]
----
mgrpxy --version
----

+

Expected output:

- `mgrpxy version 5.2.11` or higher

+

. Install the new proxy container images as RPM packages.

+

[source,shell]
----
zypper install suse-multi-linux-manager-5.2-<arch>-proxy*
----

+

. Reboot the Proxy.

. Upgrade proxy containers and restart them.

+

[source,console]
----
mgrpxy upgrade podman
mgrpxy stop
mgrpxy start
----

+

. Confirm proxy containers are operational.

+

[source,console]
----
podman ps
----

+

All expected proxy containers should be up and running:

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

____


=== Proxy upgrade complete

The proxy host system is now running {productname} {productnumber} Proxy packages and synchronized product channels.
