= Proxy Migration from 4.3 to 5.1
:revdate: 2025-10-19
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

== Requirements and considerations

* To migrate a SUSE Manager 4.3 Proxy to {productname} {productnumber}, you require a new machine with {sl-micro} {microversion} or {sles} {bci-mlm} and [literal]``mgrpxy`` installed.

* An in-place migration from SUSE Manager 4.3 to {productnumber} requires host operating system reinstallation, regardless of whether the chosen host operating system is {sl-micro} {microversion} or {sles} {bci-mlm}.

* Before migrating from SUSE Manager 4.3 to {productnumber}, any existing traditional clients including the traditional proxies must be migrated to {salt}.
For more information about migrating traditional {productname} 4.3 clients to {salt} clients, see https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.html.

* Traditional contact protocol is no longer supported in {productname} 5.0 and later.

* Before migrating a SUSE Manager 4.3 Proxy to {productname} {productnumber}, the SUSE Manager 4.3 Server
needs to be migrated first, see xref:installation-and-upgrade:container-deployment/mlm/migrations/server/server-mlm-43-51.adoc[].


== Introduction

In {productname} {productnumber}, the proxy can be deployed using two different methods:

* containerized running on Podman
* containerized running on k3s

In {productname} {productnumber}, RPM based support was removed, and only the containerized version running with podman or k3s is supported. 
The management of the containerized proxy running with Podman is done using the [command]``mgrpxy`` tool.

image::43-proxy-migration.mmaid.svg[scalewidth=80%]

== Backup existing {susemgrproxy} data

{productname} {smr} 5.1.2 includes automated backup-migration procedure for both kinds of {susemgrproxy} variants. This procedure collects all required data and uploads them to the {productname} Server. For {susemgrbranch} this tool also creates and migrates {saltboot} related entities, see xref:retail:migration-from-43.adoc[].

There are multiple ways how to initiate {susemgrproxy} 4.3 migration:

* API call
+
Replace [literal]``$proxyid`` by a server id of the branch proxy, or multiple server ids separated by a comma.
+
[code]
----
mgrctl api login
mgrctl api post proxy/backupConfiguration '{"sids":[$proxyid]}'
----
* {salt} call
+
Replace [literal]``$proxy`` in command below by branch proxy minion id or [literal]``-L proxyminionid1,proxyminionid2,...`` when addressing multiple branch proxies.
+
[code]
----
salt $proxy proxy.backup
----

[NOTE]
====
It is recommended to do a manual backup of the proxy as well, particularly if there are custom modifications present.
====

[IMPORTANT]
====
{susemgrproxy} remain operational after backup step as before, however migrate the server host as soon as possible after backup step is performed to prevent potential inconsistencies.
====

== Deploy a new {susemgrproxy}

{susemgrproxy} host operating system can be either {sles} 15 SP7 or {sl-micro} {microversion}.
This guide however considers only {sles} 15 SP7 for AutoYAST based installation. {sl-micro} {microversion}  will require manual redeployment, see xref:installation-and-upgrade:container-deployment/mlm/proxy-deployment-mlm.adoc[]

=== Prepare autoinstallation distribution based on {sles} 15 SP7

- Download or obtain {sles} 15 SP7 installation ISO to the server host
- Use [command]``mgradm distribution copy $path_to_the_iso`` to copy installation files to the container
- Register the autoinstallation distribution, see xref:client-configuration:autoinst-distributions.adoc[].

=== Prepare autoinstallation profile

For more information, see xref:client-configuration:autoinst-profiles.adoc[].

- Create an autoinstallation profile based previously created distribution.
As a profile use profile provided at https://github.com/SUSE/manager-build-profiles/blob/master/AutoYaST/SUSE-Multi-Linux-Manager/SUSE%20Multi-Linux%20Manager%20Proxy/MLM_Proxy-51-SLES-Install.xml
- Once profile is created, switch to [menuitem]``Variables`` tab and fill in required variables:
+
[code]
----
org='organization_id'
distrotree='autoinstallation_distribution_label_from_previous_step'
channel_prefix='clm_channel_prefix' or blank for SCC channels
registration_key='activation_key_for_post_upgrade'
----
- In tab [menuitem]``Autoinstallation File`` you can see complete rendered profile for additional inspection

=== Provision autoinstallation of the proxy

Schedule an autoinstallation on the old {susemgr} Proxy 4.3 using the profile created in previous step.

- Use Web UI interface [menuitem]``Provisioning`` tab at the [menuitem]``System`` view of migrating branch server
- Or use API call [command]``system/provisionSystem`` to schedule the migration. For example execute following snippet from the {productname} host:
+
[code]
----
mgrctl api login
mgrctl api post system/provisionSystem '{"sid":$proxyid,"profileName":"$profileName"}'
----

== Validate proxy functionality

After migration is finished and salt is started first time, backed up proxy configuration is automatically deployed during [literal]``Hardware refresh`` step.

After finishing all onboarding steps, validate required proxy functionality


== TFTP files synchronization

Containerized proxies do not use tftpsync mechanism to transfer tftproot files.
Instead these files are transparently downloaded and cached on demand.

To prevent false positive errors during [command]``cobbler sync`` run, migrated 4.3 proxies need to be removed from tftpsync mechanism.

If you previously configured a 4.3 proxy to receive TFTP files, one of the following configuration option is required:

[NOTE]
====
To get to a shell inside the container, run on the container host:
----
mgrctl term
----
====

* In the {productname} {productnumber} server container, run [command]``configure-tftpsync.sh`` with the list of remaining 4.3 proxies as arguments.
If no 4.3 proxies remain, run [command]``configure-tftpsync.sh`` with no arguments.

* In the {productname} {productnumber} server container, manually remove the relevant proxy from the [option]``proxies`` setting in the [path]``/etc/cobbler/settings.yaml`` file.
If there are no 4.3 proxies remaining, then manually remove the [option]``proxies`` list completely.
