[[ref-systems-sd-config]]
= Configuration

The menu:Systems[Configuration] section allows you to manage the configuration files for the selected client.
Configuration files are distributed with a configuration channel.

For more information about configuration channels, see xref:client-configuration:configuration-management.adoc[].

The menu:Systems[Configuration] tab is split into subtabs:



== Overview

The menu:Systems[Configuration > Overview] subtab is split into sections:

Configuration Overview::
This section contained the total number of available configuration files, and channel subscriptions.
Click the name of a configuration file or channel to see more information.
Click btn:[Subscribe to channels] to subscribe to additional configuration channels.

Recent Events::
This section shows when the configuration channels was most recently deployed on the selected client.
It also shows the most recent time that a comparison was performed.

Configuration Actions::
This section allows you to deploy or to compare configuration channels on the selected client.



== View Files

The menu:Systems[Configuration > View Files] subtab is split into subtabs for centrally managed, and locally managed configuration files.

The [guimenu]``Centrally-Managed Files`` and [guimenu]``Locally-Managed Files`` subtabs both show a list of all available configuration files.
Click btn:[View] to see details about the configuration file.
Click btn:[Compare] to compare the configuration file to other files, or to various revisions of itself.
Click the configuration channel name to see more information about the channel that contains this configuration file.
Click the revision number to see additional details about the configuration file.



== Deploy Files

The menu:Systems[Configuration > Deploy Files] shows a list of available configuration files that can be deployed on the selected client.



== Compare Files

The menu:Systems[Configuration > Compare Files] shows a list of available configuration files that can be compared to {productname} managed configuration files.
Check the configuration file to compare and click btn:[Compare Files] to schedule a comparison.
Click the revision number to see additional details about the configuration file.
Click the configuration channel name to see more information about the channel that contains this configuration file.


== Manage Configuration Channels

The menu:Systems[Configuration > Manage Configuration] subtab is split into subtabs:

List/Unsubscribe from Channels::
This section shows the list of currently subscribed channels.
To unsubscribe the selected client from a configuration channel, check the channel, and click btn:[Unsubscribe].
Click the configuration channel name to see more information about the channel that contains this configuration file.

Subscribe to Channels::
This section shows the list of configuration channels that are available for the selected client to subscribe to.
To subscribe the selected client to a configuration channel, check the channel, and click btn:[Continue].

View/Modify Rankings::
This section shows the currently subscribed configuration channels, in ranked order.
Where settings conflicts occur between configuration channels, channels closer to the top of the list take precedence.
To complete subscription to a configuration channel, review the rankings, adjust as necessary using the up and down arrows, and click btn:[Update Channel Rankings].
