[[ref-systems-sd-hardware]]
= Hardware
:description: Learn about and configure detailed hardware information for selected clients in terms of their architecture, networking, and memory settings
:revdate: 2023-10-16
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

The menu:Systems[Details > Hardware] section shows detailed hardware information about the selected client, including architecture, networking, and memory.

Click btn:[Schedule Hardware Refresh] to update this page with the latest hardware information.
To change the primary network interface on the client, select the correct interface in the [guimenu]``Primary Network Interface`` field in the [guimenu]``Networking`` section.
For clients with multiple fully qualified domain names (FQDNs) configured, change the primary FQDN by selecting it in the [guimenu]``Primary FQDN`` field in the [guimenu]``Networking`` section.
Click btn:[Update Properties] to save your changes.

[NOTE]
====
Refreshing hardware information happens once a month automatically when the [systemitem]``system-profile-refresh`` taskomatic job runs.
====
