[[ref-systems-sd-provisioning]]
= Provisioning

The menu:Systems[Provisioning] section allows you to manage provisioning for the selected client.
This includes managing and scheduling autoinstallation and booting the selected client.

The menu:Systems[Provisioning] tab is split into subtabs:



== Autoinstallation

This section displays a list of the available autoinstallation profiles for the selected client.
Select a time and date for autoinstallation to re-install the client.

For more information about autoinstallation, see xref:client-configuration:autoinst-intro.adoc[].



== Power Management

This section allows you to power on, power off, and reboot the selected client.

This feature uses either the IPMI or Redfish protocol and is managed using a {cobbler} profile.
The selected client must have a power management controller supporting one of these protocols.
For Redfish, ensure you can establish a valid SSL connection between the client and the {productname} Server.

Complete the details for the power management server, and click the appropriate button for the action to take.
Click btn:[Get status] to determine if the client is currently running.
Click btn:[Save only] to save the details without taking any action.

Click btn:[Remove Cobbler System Profile] to remove the current client's system profile from {cobbler}.
For more information about unattended provisioning with {cobbler}, see xref:client-configuration:autoinst-unattended.adoc[].

For more information about power management, see xref:client-configuration:power-management.adoc[].
