[[ref-systems-sd-packages]]
= Packages

The menu:Systems[Software > Packages] section allows you to manage packages on the selected client.

Click btn:[Update Package List] to refresh the list of available packages.

The menu:Systems[Software > Packages] tab is split into subtabs:

List/Remove::
Lists all packages currently installed on the selected client.
Click the name of a package to see more information.
To uninstall packages, check the package in the list and click btn:[Remove Packages].

Upgrade::
Lists packages that have newer versions available.
Click the name of a package to see more information.
To upgrade packages, check the package in the list and click btn:[Upgrade Packages].
Any EULAs will be accepted automatically.

Install::
Lists packages that are available for installation on the selected client.
Click the name of a package to see more information.
To install packages, check the package in the list and click btn:[Install Selected Packages].
Any EULAs will be accepted automatically.

Profiles::
Compare packages installed on the selected client with a stored profile, or with packages installed on another client.
When the comparison is made, you can choose to modify the selected client to match.
To compare with a stored profile, select the profile and click btn:[Compare].
To compare with another client, select the client name and click btn:[Compare].

Non Compliant::
Lists packages that are installed on the selected client, but are not available in any of the subscribed software channels.


For more information about packages, see xref:client-configuration:package-management.adoc[].
