[[ref-systems-sd-channels]]
= Software Channels

The menu:Systems[Software > Software Channels] section allows you to manage the software channels on the current client.
For more information about software channels, see xref:client-configuration:channels.adoc[].

The menu:Systems[Software > Software Channels] subtab is split into sections:



== Base Channel

This section shows the base channel the current client is subscribed to, as well as any other available base channels.

Click the chain icon next to a base channel to see more information about the channel.
Change the base channel subscription by selecting the new base channel, and click btn:[Next] to schedule the change.

The child channels associated with the base channel are populated in the [guimenu]``Child Channels`` section.
Mandatory child channels are pre-selected.
Toggle the [guimienu]``include recommended`` switch to also select recommended child channels.



[NOTE]
====
By default, cloned vendor channels match the original vendor channel and automatically select the dependencies.
You can disable the automatic selection for cloned channels by adding the following option in [path]``/etc/rhn/rhn.conf``:
----
java.cloned_channel_auto_selection = false
----
====

In general, channel pre-selection is necessary to avoid problems with missing dependencies for a given channel but it only works flawlessly for vendor channels.
For cloned channels, {productname} relies on the channel label to define dependencies and use it in auto selection.
This heuristic sometimes lead to either selecting unnecessary child channels or overlooking some essential ones.
Users should exercise caution and pay attention in such case that correct channels are selected.
In such a case, it can be necessary to disable auto selection using the above mentioned setting.

For Salt clients, apply the highstate after changing software channels.



== Child Channels

This section shows the software product and child channels associated with the currently selected base channel.

Hover over the information icon next to the channel name to see channel requirements.
Click the chain icon next to a base channel to see more information about the channel.

Child channels are can be either recommended or mandatory.
Mandatory child channels must be installed for the selected client to use the associated base channel.
Recommended child channels should be installed to provide additional packages.
All other child channels are optional.

Check the child channels you want to install, and click btn:[Next] to schedule the change.
