[[ref-systems-sd-transfer]]
= Transfer
:description: Move clients between organizations by selecting the target organization in the Organization Name field and clicking Migrate System.
:revdate: 2023-10-04
:page-revdate: {revdate}

The menu:Systems[Details > Transfer] section allows you to move clients between organizations.
Clients can only belong to one organization at any time.

[NOTE]
====
You will need to establish trust between organizations when you want to move clients.
For more information, see xref:administration:organizations.adoc[].
====

To move a client to a different organization, select the name of the organization in the [guimenu]``Organization Name`` field, and click btn:[Migrate System].

[IMPORTANT]
====
When you move a client to a different organization, channel assignments, system group membership, custom data values, configuration channels, reactivation keys, and snapshots are deleted from the system configuration.
You will need to set these values again when the move is complete.
====