= {byos} Guide
:description: Deploy and register BYOS (bring-your-own-server) images on public clouds using your existing SUSE support contract
:revdate: 2025-06-23
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

== {byoslongform} ({byos})

{byoslongform} ({byos}) images are useful if you already have a support contract with SUSE and want to move your workloads to the public cloud.
An instance launched from a {byos} image is equivalent to a physical machine that just received a SUSE Linux Enterprise Server installation from the {sles} installation image.

After creation:

* use ``registercloudguest`` to register the instance with the SUSE-operated update infrastructure in the cloud framework, or
* use the command ``SUSEConnect`` to register the system with {scclongform} using the entitlements you already have.

.Obtaining a {productname} Server Subscription (optional)
[IMPORTANT]
====
For customers running 10 or more {payg} SLES for SAP Applications instances who also wish to access the {productname} {byos} Lifecycle subscription, an email must be sent to [literal]``susemanagerkey@suse.com``.
The email should include proof of at least 10 active SLES for SAP {payg} instances, such as a screenshot of the relevant section of their cloud console.
The subscription key is valid for one year and can be renewed by providing updated proof of the instances at the end of the subscription period.
====

Connect your system to your own running RMT or {productname} infrastructure in the same way you connect systems in your data center.

{byos} instances make it easier to manage extensions such as ``LTSS`` or ``kernel live-patching``.
Extensions for {payg} instances can only be used in conjunction with {productname}.
