= 使用 mgradm 进行自定义 YAML 配置和部署
:revdate: 2024-11-19
:page-revdate: {revdate}

您可以选择创建自定义的 [filename]``mgradm.yaml`` 文件，供 [command]``mgradm`` 工具在部署期间使用。

[IMPORTANT]
====
如果未提供基本变量，[command]``mgradm`` 将提示您使用命令行参数或 [filename]``mgradm.yaml`` 配置文件来提供这些变量。

为了安全起见，**应避免使用命令行参数指定口令**。请改用具有适当权限的配置文件。
====

.过程：使用自定义配置文件通过 Podman 部署 {productname} 容器
. 准备一个名为 [filename]``mgradm.yaml`` 的配置文件，以以下示例所示：
+
[source, yaml]
....
# 数据库口令。默认会随机生成
db:
  password: MySuperSecretDBPass

# CA 证书的口令
ssl:
  password: MySuperSecretSSLPassword

# 您的 SUSE Customer Center 身份凭证
scc: 
  user: ccUsername
  password: ccPassword

# 组织名称
organization: YourOrganization

# 用于发送通知的电子邮件地址
emailFrom: notifications@example.com

# 管理员帐户细节
admin:
  password: MySuperSecretAdminPass
  login: LoginName
  firstName: Admin
  lastName: Admin
  email: email@example.com
....

. 在终端中，以 root 身份运行以下命令。服务器 FQDN 是选填的。
+
[source, shell]
----
mgradm -c mgradm.yaml install podman <FQDN>
----
+
[IMPORTANT]
====
必须以 sudo 或 root 用户身份部署容器。如果您遗漏此步骤，终端中将显示以下错误。

[source, shell]
----
INF Setting up uyuni network
9:58AM INF Enabling system service
9:58AM FTL Failed to open /etc/systemd/system/uyuni-server.service for writing 
error="open /etc/systemd/system/uyuni-server.service: permission denied"
----
====

. 等待部署完成。

. 打开浏览器并访问您的服务器 FQDN 或 IP 地址。

//In this section you learned how to deploy an {productname} {productnumber} Server container using a custom YAML configuration.
