= Obtaining the {productname} Server {payg} Public Cloud Image on {azure}

Follow these step-by-step instructions to locate the {productname} {productnumber} {payg} image on {azure}.

. Firstly, log in to your Azure account, via https://portal.azure.com

+

This makes sure that the Azure system is able to identify in which country your account get billed.

+

It is important, as billing for {productname} {payg} is handled via the Azure Marketplace.
As there are restrictions on which countries this listing can be billed, the account you will transact to should be the one you are logged into.

+

There are currently two offers for {productname} {payg} on {azure}:

* ** {productname} {productnumber} with 24x7 Support (EMEA Orders only)**
* **{productname} {productnumber} with 24x7 Support**

+

Pick the listing that reflects in which country your Azure account gets billed. It depends on the _sold to address_ of the account, see https://learn.microsoft.com/azure/cost-management-billing/manage/change-azure-account-profile.

+

[NOTE]
====
Do *not* go directly to the Azure Marketplace and get the offer. Even if the offers are visible, they should not be selected from here, as the Azure Web page is not able to identify your billing account. *Always log into the portal first*
====

. After you are logged into the Azure Portal, click btn:[Create a resource].

. Enter {productname} {productnumber} into the search field on the top and press kbd:[RETURN]

+

You get a list of offerings and need to select the version of _{productname} {productnumber} with 24x7 Support_ depending on your billing country.

+

For example, for an account billed in Germany, it would be _{productname} {productnumber} with 24x7 Support (EMEA Orders Only)_.

+

[NOTE]
====
The offer show up as _Azure Application_ and not as a _Virtual Machine_
====

. Click the description text to get the Product description and then on btn:[Plans + Pricing]. If this is shown with a description and plan, you have chosen the right offer. If there is nothing shown you selected the wrong one.

. Next, click on the btn:[Create_ button]

+

This will bring you to a form similar you may know from creating other Azure resources.
There are two tabs you need to fill _Basic_ and _Virtual Machine Settings_