= Obtaining the {productname} Server {payg} public cloud image on {azure}

Follow these step-by-step instructions to locate the SUSE Manager {productnumber} {payg} image on {azure}.
You can also review the latest available images for the public cloud using Pint(Public Cloud Information Tracker). 

See: link:https://pint.suse.com/[pint.suse.com]


.Procedure: Obtaining the {productname} {payg} image on {azure}

. In your browser navigate to the link:https://portal.azure.com[Azure Portal].

. Enter your Azure credentials and log in.

. From the {azure} Management Console dashboard, locate the menu:Services[] dropdown.

. From the menu select menu:EC2[] under the **Compute** section.

. In the {azure} dashboard, in the main content section, you'll find the btn:[Launch Instance] button. Click it.

. From the **Choose an Amazon Machine Image (AMI)** page. 
Select **Browse more AMIs**

. Search for **SUSE Manager**

. Depending on your location select your AMI image. 

* **SUSE Manager Server Family (EU and UK only)**
* **SUSE Manager Server Family (non-EU and non-UK-only)**.

. Click btn:[Select].

. Proceed for image configuration.