[[azure-server-setup]]
= Initial Setup

.Procedure: Log in and Update the System
. SSH into your {azure} instance.

. Switch to the root user and update the system.
+
----
sudo -i
transactional-update
----
+
. Reboot the system.



== Network Configuration

// (Azure requirement, not ours).
For {productname} {payg} setup it is required, that a new Virtual Network and a new subnet is configured.
It is impossible to setup the instance in an existing network.
When you setup new clients which should be managed, take care that you put them into the private subnet which is configured with {productname} {payg}.


[NOTE]
====
If you want to manage systems in an already existing network, you must configure **peering**.

For more information, see link:https://learn.microsoft.com/en-us/azure/virtual-network/tutorial-connect-virtual-networks?tabs=portal#create-virtual-network-peer[Azure documentation].
====


.Procedure: Network Configuration
. Ensure the network configuration aligns such that `hostname -f` yields the identical name as the reverse DNS lookup of the private IP address. For instance, when executing `nslookup 10.0.0.X`.

. Insert the private IP with its Fully Qualified Domain Name (FQDN) into `/etc/hosts`. For example: +
`10.0.0.4   instancename.internal.cloudapp.net`

. Edit `/etc/sysconfig/network/config` and append `internal.cloudapp.net` to `NETCONFIG_DNS_STATIC_SEARCHLIST`.

. Execute `netconfig update`.

. Subsequently, `hostname -f` should return the same FQDN as obtained from `nslookup 10.0.0.X`.

[IMPORTANT]
====
When adding new virtual machines (VMs), such as {sles} 15 SP5, it is crucial to ensure that they are configured within the same subnet as the {productname} instance. 
This step is essential for successful network setup and integration.

Additionally, be mindful of the geographical restrictions associated with your plans. 
Make sure to utilize the appropriate Azure accounts which correspond to the specific geographic zones of your project. 
====


== Configure Storage

.Procedure: Configuring Storage
. SSH into your {azure} instance.
. Switch to the root user and update the system.
+

----
sudo -i
transactional-update
----

. Reboot the system.

. Configure storage with the [command]``mgr-storage-server`` tool or in the case of the proxy use [command]``mgr-storage-proxy``. 
For more information, see [command]``mgr-storage-server --help`` or [command]``mgr-storage-proxy --help``.
This tool simplifies creating the container storage and database volumes.

.Procedure
. Format the command in the following manner: 
+

----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----
+
For example: 
+
----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----
+

[NOTE]
====
This command will create the following persistent storage volumes at [path]``/var/lib/containers/storage/volumes``:

For more information, see xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[].
====

. As root run `mgradm install podman <FQDN>` to deploy.















