[[azure-server-setup]]
= Initial Setup

.Procedure: Log in and Update the System
. Within the Managed Resource group you have set up, you will find the virtual machine. To get the details, click on the name of the virtual machine.
Here you can see the (public) IP address which you need to connect to the running instance. SSH into your {azure} instance. 

. Switch to the root user and update the system .

+

[source,shell]
----
sudo -i
zypper refresh
zypper update
----

. Reboot the system.



== Network Configuration

// (Azure requirement, not ours).
Remember, the {productname} {payg} setup requires, that a new Virtual Network and a new subnet is configured, which was performed in the previous step.

Because {productname} {payg} is deployed as a 'Managed Application' it is not possible to deploy into an existing network.

Before moving on to the next step, ensure the network is correctly configured:

When you setup new clients which should be managed, take care that you put them into the private subnet which is configured with {productname} {payg} or peer your networks.

[NOTE]
====
If you want to manage systems in an already existing network, you must configure **peering**.

For more information, see link:https://learn.microsoft.com/en-us/azure/virtual-network/tutorial-connect-virtual-networks?tabs=portal#create-virtual-network-peer[Azure documentation].
====


.Procedure: Network Configuration
. Ensure the network configuration aligns such that `hostname -f` yields the identical name as the reverse DNS lookup of the private IP address. For instance, when executing `nslookup 10.0.0.X`.

. Insert the private IP with its Fully Qualified Domain Name (FQDN) into `/etc/hosts`. 

+

For example: 

+

`10.0.0.4   _instancename.location_.internal.cloudapp.azure.com`

. Edit `/etc/sysconfig/network/config` and append `internal.cloudapp.azure.com` to `NETCONFIG_DNS_STATIC_SEARCHLIST`.

. Execute `netconfig update`.

. Subsequently, `hostname -f` should return the same FQDN as obtained from `nslookup 10.0.0.X`.

[IMPORTANT]
====
When adding new virtual machines (VMs), such as {sles}, it's crucial to ensure that they are configured within the same subnet as the {productname} instance, or that you have setup network peering. 
This step is essential for successful network setup and integration.

Additionally, be mindful of the geographical restrictions associated with your plans. 
Make sure to utilize the appropriate Azure accounts which correspond to the specific geographic zones of your project.
====


== Configure Storage
<<<<<<< HEAD
. SSH into your {azure} instance.

. Switch to the root user and update the system.
=======

.Procedure: Configuring Storage

. SSH into your {azure} instance.

. Switch to the root user and update the system:

>>>>>>> 4861cf527 (Payg azure update jcayouette (#3746))
+

[source,shell]
----
sudo -i
transactional-update
----

. Reboot the system.

<<<<<<< HEAD
. Configure storage with the [command]``mgr-storage-server`` tool or in the case of the proxy use [command]``mgr-storage-proxy``. 
For more information, see [command]``mgr-storage-server --help`` or [command]``mgr-storage-proxy --help``.
This tool simplifies creating the container storage and database volumes.


. Format the command in the following manner: 
=======
. Configure storage using the appropriate tool:

* For a standard setup, use [command]``mgr-storage-server``.
* For a proxy configuration, use [command]``mgr-storage-proxy``.

For more details, run:

>>>>>>> 4861cf527 (Payg azure update jcayouette (#3746))
+

[source,shell]
----
<<<<<<< HEAD
mgr-storage-server <storage-disk-device> [<database-disk-device>]

#For example: 

mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
=======
mgr-storage-server --help
mgr-storage-proxy --help
----

These tools simplify the creation of container storage and database volumes.

. Identify the block devices:

+

[source,shell]
----
ls /dev/disk/azure/scsi1/
>>>>>>> 4861cf527 (Payg azure update jcayouette (#3746))
----

This command lists the disks created during deployment. Typically:

* `lun3` is the storage disk.
* `lun4` is the database disk.

. Configure storage using the identified devices:

+

[source,shell]
----
mgr-storage-server /dev/disk/azure/scsi1/lun3 /dev/disk/azure/scsi1/lun4
----

[NOTE]
====
This command creates persistent storage volumes at:

[path]``/var/lib/containers/storage/volumes``

For more details, see xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[].
====

<<<<<<< HEAD
. As root run `mgradm install podman <FQDN>` to deploy.















=======
. Deploy using `mgradm` as root:

+

[source,shell]
----
mgradm install podman <FQDN>
----
>>>>>>> 4861cf527 (Payg azure update jcayouette (#3746))
