[[troubleshooting-login-timeout]]
= Troubleshooting Login Timeouts
:revdate: 2025-07-16
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

By default, the {productname} {webui} requires users to log in again after 30{nbsp}minutes.
Depending on your environment, you might want to adjust the login timeout value.

To adjust the value, you need to make the change in both `rhn.conf` and `web.xml`.
Ensure you set the value in seconds in `/etc/rhn/rhn.conf`, and in minutes in `web.xml`.
The two values must equal the same amount of time.

For example, to change the timeout value to one hour, set the value in `rhn.conf` to 3600 seconds, and the value in `web.xml` to 60 minutes.



.Procedure: Adjusting the {webui} Login Timeout Value
. On the container host, open a command line inside the server container:

+

[source,shell]
----
mgrctl term
----

+

--

.. Open `/etc/rhn/rhn.conf` and add or edit this line to include the new timeout value in seconds:

+

----
web.session_database_lifetime = <Timeout_Value_in_Seconds>
----

.. Save and close the file.

.. Open `/etc/tomcat/web.xml` and add or edit this line to include the new timeout value in minutes:

+

[source,xml]
----
<session-timeout>Timeout_Value_in_Minutes</session-timeout>
----

.. Save and close the file.

--

+

. On the container host, restart the server to enforce the new configuration:

+

[source,shell]
----
systemctl restart uyuni-server.service
----
