[[troubleshooting-not-enough-disk-space]]
= Troubleshooting Not Enough Disk Space
:revdate: 2022-10-18
:page-revdate: {revdate}

////

PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step

////


Check the available disk space before you begin migration.
We recommend locating `/var/spacewalk` and `/var/lib/pgsql` on separate XFS file systems.

When you are setting up a separate file system, edit `/etc/fstab` and remove the `/var/lib/pqsql` subvolume.
Reboot the server to pick up the changes.

To get more information about an upgrade problem, check the migration log file.
The log file is located at `/var/log/rhn/migration.log` on the system you are upgrading.

