[[troubleshooting-]]
= Troubleshooting Container with Full Disk Event
:description: Troubleshoot a full disk event in your container by following these steps to resize the storage medium
:revdate: 2025-03-10
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1



////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

In case a dedicated disk mounted as a persistent storage medium of a container runs out of storage space, an emergency action is needed.

Proceed as follows to solve the problem with resizing the storage medium.
Run all listed commands as `root` on the container host.

.Procedure: Resize Storage Medium

. Increase the disk size.
  Actions to take depend on the installation scenario.

. If the disk is partitioned (for example, there is a `/dev/vdb1` for disk `/dev/vdb`), run the following commands:

+

Run the following commands:

+

--
.. `parted /dev/vdb`
.. `(parted)` `print`
.. `(parted)` `resizepart NUMBER 100%` where `NUMBER` is the partition number shown by `print` command (for example, `1` if `/dev/vdb1`)
.. `(parted)` `quit`
--

. Resize the filesystem.
  For example, for an XFS filesystem, run the command:

+

[source,shell]
----
xfs_growfs /dev/vdb1
----

After completing the procedure, an XFS filesystem should be using all space available on the disk.
