languages: #language parameters
  - langcode: "en"
    locale: "en_US.utf8"
    gnudateformat: "%B %d %Y"
    pdf_theme_suma: "suse-draft"
    pdf_theme_uyuni: "uyuni"
  - langcode: "cs"
    locale: "cs_CZ.UTF-8"
    gnudateformat: "%B %d %Y"
    pdf_theme_suma: "suse-draft"
    pdf_theme_uyuni: "uyuni"
  - langcode: "es"
    locale: "es_ES.UTF-8"
    gnudateformat: "%e de %B de%Y"
    pdf_theme_suma: "suse-draft"
    pdf_theme_uyuni: "uyuni"
  - langcode: "ja"
    locale: "ja_JP.UTF-8"
    gnudateformat: "%Y年%m月%e日"
    pdf_theme_suma: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "jaFlag"
    nation_in_eng: "japan"
    language_in_orig: "日本語"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
  - langcode: "zh_CN"
    locale: "zh_CN.UTF-8"
    gnudateformat: "%Y年%m月%e日"
    pdf_theme_suma: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "china"
    nation_in_eng: "china"
    language_in_orig: "中国人"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
  - langcode: "ko"
    locale: "ko_KR.UTF-8"
    gnudateformat: "%Y년%m월%e일"
    pdf_theme_suma: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "koFlag"
    nation_in_eng: "korea"
    language_in_orig: "한국어"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
sections: #Used by configure script to create book targets for each language.
  - name: "installation"
  - name: "client-configuration"
  - name: "upgrade"
  - name: "reference"
  - name: "administration"
  - name: "salt"
  - name: "retail"
  - name: "large-deployments"
  - name: "quickstart-public-cloud"
  - name: "quickstart-sap"
targets: #Other makefile target not strictly related to book. These targets will just execute all language targets (e.g. validate-suma executes validate-suma-en etc)
  - name: validate-suma
  - name: pdf-tar-suma
  - name: fix-lunr-search-in-translations-suma
  - name: antora-suma
    pre_lang_prerequisite: copy-branding 
    post_lang_prerequisite: fix-lunr-search-in-translations-suma
  - name: obs-packages-suma
  - name: pdf-all-suma
  - name: validate-uyuni
  - name: pdf-tar-uyuni
  - name: fix-lunr-search-in-translations-uyuni
  - name: antora-uyuni
    pre_lang_prerequisite: copy-branding
    post_lang_prerequisite: fix-lunr-search-in-translations-uyuni
  - name: obs-packages-uyuni
  - name: pdf-all-uyuni
