products:
  suma:
    antora:
      name: "suse-manager"
      title: "SUSE Manager Documentation"
    asciidoc:
      - attribute: productname
        value: "SUSE Manager"
      - attribute: productnumber
        value: "4.3"
      - attribute: docversion
        value: "4.3"
      - attribute: minorversion
        value: "4.3"
      - attribute: suma-content
        value: true
      - attribute: uyuni-content
        value: false
      - attribute: page-pagination
        value: true

    sections: #Used by configure script to create book targets for each language.
      - name: "quickstart"
      - name: "installation-and-upgrade"
      - name: "client-configuration"
      - name: "administration"
      - name: "reference"
      - name: "retail"
      - name: "common-workflows"
      - name: "specialized-guides"
    site:
      - attribute: title
        value: "SUSE Manager Documentation"
      - attribute: start_page
        value: suse-manager::index.adoc
      - attribute: url
        value: /
    ui:
      bundle:
        # Modify the default ui depending on your publishing endpoint
        # webui-branding-YYYY-default_ui.zip (use for OBS)
        # susecom-branding-YYYY-default_ui.zip (use for D.S.C)
        # latest-bundle.zip (translation changes)
        - attribute: url
          value: ./branding/default-ui/suma/ui-bundle.zip
        - attribute: snapshot
          value: true
      # Modify the custom branding depending on your publishing endpoint
      # webui-branding-YYYY (use for OBS)
      # susecom-branding-YYYY (use for D.S.C)
      supplemental_files: ./branding/supplemental-ui/suma/susecom-2023
  uyuni:
    antora:
      name: "uyuni"
      title: "Uyuni"
    asciidoc:
      - attribute: productname
        value: "Uyuni"
      - attribute: productnumber
        value: "2022.11"
      - attribute: docversion
        value: "2022.11"
      - attribute: minorversion
        value: "2022.11"
      - attribute: suma-content
        value: false
      - attribute: uyuni-content
        value: true
      - attribute: page-pagination
        value: true
    sections: #Used by configure script to create book targets for each language.
      - name: "quickstart"
      - name: "installation-and-upgrade"
      - name: "client-configuration"
      - name: "administration"
      - name: "reference"
      - name: "retail"
      - name: "common-workflows"
      - name: "specialized-guides"
    site:
      - attribute: title
        value: "Uyuni Documentation"
      - attribute: start_page
        value: "uyuni::index.adoc"
      - attribute: url
        value: /
    ui:
      bundle:
        # Modify the default ui depending on your publishing endpoint
        # webui-branding-YYYY-default_ui.zip (use for OBS)
        # susecom-branding-YYYY-default_ui.zip (use for D.S.C)
        # latest-bundle.zip (translation changes)
        - attribute: url
          value: ./branding/default-ui/suma/ui-bundle.zip
        - attribute: snapshot
          value: true
      # Modify the custom branding depending on your publishing endpoint
      # webui-branding-YYYY (use for OBS)
      # susecom-branding-YYYY (use for D.S.C)
      supplemental_files: ./branding/supplemental-ui/uyuni/uyuni-2023
languages: #language parameters
  - langcode: "en"
    locale: "en_US.utf8"
    gnudateformat: "%B %d %Y"
    pdf_theme_suma: "suse-draft"
    pdf_theme_uyuni: "uyuni"
  # - langcode: "cs"
  #   locale: "cs_CZ.UTF-8"
  #   gnudateformat: "%B %d %Y"
  #   pdf_theme_suma: "suse-draft"
  #   pdf_theme_uyuni: "uyuni"
  # - langcode: "es"
  #   locale: "es_ES.UTF-8"
  #   gnudateformat: "%e de %B de%Y"
  #   pdf_theme_suma: "suse-draft"
  #   pdf_theme_uyuni: "uyuni"
  - langcode: "ja"
    locale: "ja_JP.UTF-8"
    gnudateformat: "%Y年%m月%e日"
    pdf_theme_suma: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "jaFlag"
    nation_in_eng: "japan"
    language_in_orig: "日本語"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
  - langcode: "zh_CN"
    locale: "zh_CN.UTF-8"
    gnudateformat: "%Y年%m月%e日"
    pdf_theme_suma: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "china"
    nation_in_eng: "china"
    language_in_orig: "中国人"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
  - langcode: "ko"
    locale: "ko_KR.UTF-8"
    gnudateformat: "%Y년%m월%e일"
    pdf_theme_suma: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "koFlag"
    nation_in_eng: "korea"
    language_in_orig: "한국어"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
targets: #Other makefile target not strictly related to book. These targets will just execute all language targets (e.g. validate-suma executes validate-suma-en etc)
  - name: validate-suma
    pre_lang_prerequisite: configure-suma
  - name: pdf-tar-suma
    pre_lang_prerequisite: configure-suma
  - name: antora-suma
    pre_lang_prerequisite: configure-suma copy-branding 
  - name: obs-packages-suma
    pre_lang_prerequisite: configure-suma clean
  - name: pdf-all-suma
    pre_lang_prerequisite: configure-suma
  - name: validate-uyuni
    pre_lang_prerequisite: configure-uyuni
  - name: pdf-tar-uyuni
    pre_lang_prerequisite: configure-uyuni
  - name: antora-uyuni
    pre_lang_prerequisite: configure-uyuni copy-branding
  - name: obs-packages-uyuni
    pre_lang_prerequisite: configure-uyuni clean
  - name: pdf-all-uyuni
    pre_lang_prerequisite: configure-uyuni
asciidoc:
  - attribute: saltversion
    value: 3004
  - attribute: sles-version
    value: 15
  - attribute:  sp-version
    value: SP4 #use for normal text
  - attribute: sp-vert
    value: sp3 #use for terminal block
  - attribute: sp-version-l
    value: sp3
  - attribute: smrproductnumber
    value: 4.3
  - attribute: opensuse-version
    value: 15.4
  - attribute: linkattrs
    value: true
  - attribute: sectlinks
    value: true
  - attribute: sectnums
    value: true
  - attribute: sectnumlevels
    value: 5
  - attribute: icons
    value: font  
  - attribute: experimental
    value: true
  - attribute: susemgr
    value: "SUSE Manager"  
  - attribute: smr
    value: "for Retail"  
  - attribute: uyuni
    value: Uyuni  
  - attribute: slepos
    value: "SUSE Linux Enterprise Point of Service"
  - attribute: susemgrproxy
    value: "SUSE Manager Proxy"
  - attribute: sles
    value: "SUSE Linux Enterprise Server"
  - attribute: sle
    value: "SUSE Linux Enterprise"
  - attribute: sll
    value: "SUSE Liberty Linux"
  - attribute: es
    value: Expanded Support
  - attribute: micro
    value: 'SLE Micro'
  - attribute: microos
    value: MicroOS
  - attribute: slsa
    value: SLES
  - attribute: suse
    value: SUSE
  - attribute: slea
    value: SLE
  - attribute: sleses
    value: SUSE Linux Enterprise Server with Expanded Support
  - attribute: sleda
    value: SLED
  - attribute: unifiedinstaller
    value: Unified Installer 
    # Clients
  - attribute: alibabaclo
    value: 'Alibaba Cloud Linux'
  - attribute: almalinux
    value: AlmaLinux
  - attribute: amazon
    value: 'Amazon Linux'
  - attribute: centos
    value: CentOS
  - attribute: debian
    value: Debian
  - attribute: opensuse
    value: openSUSE
  - attribute: oracle
    value: 'Oracle Linux'
  - attribute: redhat
    value: 'Red Hat'
  - attribute: rhel
    value: 'Red Hat Enterprise Linux'
  - attribute: rhela
    value: 'RHEL'
  - attribute: rhnminrelease6
    value: 'Red Hat Enterprise Linux Server 6'
  - attribute: rhnminrelease7
    value: 'Red Hat Enterprise Linux Server 7'
  - attribute: rhnminrelease8
    value: 'Red Hat Enterprise Linux Server 8'
  - attribute: rocky
    value: 'Rocky Linux'
  - attribute: ubuntu
    value: Ubuntu
    # Architectures
  - attribute: aarch64
    value: aarch64
  - attribute: amd64
    value: amd64
  - attribute: arm64
    value: ARM64
  - attribute: ipf
    value: Itanium
  - attribute: ppc
    value: 'IBM Power'
  - attribute: ppc64
    value: ppc64
  - attribute: ppc64le
    value: ppc64le
  - attribute: s390x
    value: s390x
  - attribute: x86
    value: x86
  - attribute: x86_64
    value: x86-64
  - attribute: ibmz
    value: IBM Z
  - attribute: zseries
    value: IBM Z
  - attribute: zsystems
    value: IBM Z
    # Documentation 
  - attribute: homepage
    value: https://github.com/uyuni-project/uyuni-docs/
    # Everything else 
  - attribute: grub
    value: Grub
  - attribute: kickstart
    value: Kickstart
  - attribute: webui
    value: Web UI
  - attribute: jeos
    value: JeOS
  - attribute: minimal
    value: Minimal
  - attribute: minimalsles
    value: Minimal SLES
  - attribute: scc
    value: SUSE Customer Center
  - attribute: ncc
    value: Novell Customer Center
  - attribute: phub
    value: 'SUSE Package Hub'
  - attribute: ay
    value: AutoYaST
  - attribute: yast
    value: YaST
  - attribute: rootuser
    value: root
  - attribute: ruser
    value: root
  - attribute: mdash
    value: '\-'
  - attribute: openscap
    value: OpenSCAP
  - attribute: rmtool
    value: "Repository Management Tool"
  - attribute: smtool
    value: "Repository Management Tool"
  - attribute: vmguest
    value: VM Guest
  - attribute: vmhost
    value: VM Host Server
  - attribute: xen
    value: Xen
  - attribute: kvm
    value: KVM
  - attribute: kube
    value: Kubernetes
    # Table icon entities
  - attribute: check
    value: 'icon:check[role="green"]'
  - attribute: cross
    value: 'icon:times[role="danger"]'
  - attribute: question
    value: 'icon:question[role="gray"]'
  - attribute: star
    value: 'icon:asterisk[role="none"]'
  - attribute: salt
    value: Salt
  - attribute: trad
    value: Traditional
  - attribute: imagesdir
    value: images
  - attribute: listing-caption
    value: Listing
  - attribute: mgradvtop
    value: Advanced Topics Guide
  - attribute: mgrbestpract
    value: Best Practices Guide
  - attribute: mgrgetstart
    value: Getting Started Guide
  - attribute: mgrrefguide
    value: Reference Guide
  - attribute: upgrade
    value: Upgrade Guide
  - attribute: snippet
    value: ../../snippets/
  - attribute: sourcedir
    value: .
  - attribute: source-highlighter
    value: coderay
  - attribute: toclevels
    value: 3
  - attribute: toc
    value: left
  - attribute: doctype
    value: book
  - attribute: payg
    value: Pay-as-you-go