products:
  mlm:
    antora:
      name: "docs"
      title: "SUSE Multi-Linux Manager 5.1"
    asciidoc:
      attributes:
        - attribute: productname
          value: "SUSE Multi-Linux Manager"
        # Use single quotes inside double quotes to properly display float values. Zero values are dropped otherwise for example 5.0 = 5
        - attribute: productnumber
          value: "5.1"
        - attribute: currentversion
          value: "Beta 1"
        # License date adjust each year
        - attribute: copyrightdate
          value: "2011–2025"
        - attribute: mlm-content
          value: true
        - attribute: uyuni-content
          value: false
        - attribute: page-pagination
          value: true

    sections: #Used by configure script to create book targets for each language.
      - name: "installation-and-upgrade"
      - name: "client-configuration"
      - name: "administration"
      - name: "reference"
      - name: "retail"
      - name: "common-workflows"
      - name: "specialized-guides"
      - name: "legal"

    site:
      - attribute: title
        value: "SUSE Multi-Linux Manager 5.1 Documentation"
      - attribute: start_page
        value: docs::index.adoc
      # For d.s.c use: https://documentation.suse.com/multi-linux-manager/5.1/
      # For the webui use: /
      - attribute: url
        value: https://documentation.suse.com/multi-linux-manager/5.1/
    ui:
      bundle:
        - attribute: url
        # Set to draft for 5.0 beta2 release until GM then swap back to ui-bundle.zip
         # value: ./branding/default-ui/mlm/ui-bundle.zip
          value: https://github.com/SUSEdoc/dsc-style-bundle/raw/refs/heads/main/default-ui/ui-bundle.zip

        - attribute: snapshot
          value: true
      # Adjusting this is not required anymore as this is handled
      # by the Makefile. Adjust the targets there if you need to
      supplemental_files: ./branding/supplemental-ui/mlm/susecom-2025
  uyuni:
    antora:
      name: "uyuni"
      title: "Uyuni 2024.12"
    asciidoc:
      attributes:
        - attribute: productname
          value: "Uyuni"
        - attribute: releaseversion
          value: "2024.12"
        - attribute: productnumber
          value: "2024.12"
        - attribute: mlm-content
          value: false
        - attribute: uyuni-content
          value: true
        - attribute: page-pagination
          value: true
    sections: #Used by configure script to create book targets for each language.
      - name: "installation-and-upgrade"
      - name: "client-configuration"
      - name: "administration"
      - name: "reference"
      - name: "retail"
      - name: "common-workflows"
      - name: "specialized-guides"
      - name: "legal"
    site:
      - attribute: title
        value: "Uyuni Documentation"
      - attribute: start_page
        value: "uyuni::index.adoc"
      - attribute: url
        value: https://www.uyuni-project.org/uyuni-docs/
    ui:
      bundle:
        - attribute: url
          value: ./branding/default-ui/mlm/ui-bundle.zip
        - attribute: snapshot
          value: true
      # Custom branding
      # Changing this is not needed for Uyuni, as Uyuni has only a single
      # branding
      supplemental_files: ./branding/supplemental-ui/uyuni/uyuni-2023
languages: #language parameters
  - langcode: "en"
    locale: "en_US.utf8"
    gnudateformat: "%B %d %Y"
    pdf_theme_mlm: "suse"
    pdf_theme_uyuni: "uyuni"
  # - langcode: "cs"
  #   locale: "cs_CZ.UTF-8"
  #   gnudateformat: "%B %d %Y"
  #   pdf_theme_mlm: "suse-draft"
  #   pdf_theme_uyuni: "uyuni"
  # - langcode: "es"
  #   locale: "es_ES.UTF-8"
  #   gnudateformat: "%e de %B de%Y"
  #   pdf_theme_mlm: "suse-draft"
  #   pdf_theme_uyuni: "uyuni"
  - langcode: "ja"
    locale: "ja_JP.UTF-8"
    gnudateformat: "%Y年%m月%e日"
    pdf_theme_mlm: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "jaFlag"
    nation_in_eng: "japan"
    language_in_orig: "日本語"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
  - langcode: "zh_CN"
    locale: "zh_CN.UTF-8"
    gnudateformat: "%Y年%m月%e日"
    pdf_theme_mlm: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "china"
    nation_in_eng: "china"
    language_in_orig: "中文"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
  - langcode: "ko"
    locale: "ko_KR.UTF-8"
    gnudateformat: "%Y년%m월%e일"
    pdf_theme_mlm: "suse-cjk"
    pdf_theme_uyuni: "uyuni-cjk"
    flag_svg_without_ext: "koFlag"
    nation_in_eng: "korea"
    language_in_orig: "한국어"
    asciidoctor_pdf_additional_attributes: "-a scripts=cjk"
targets: #Other makefile target not strictly related to book. These targets will just execute all language targets (e.g. validate-mlm executes validate-mlm-en etc)
  - name: validate-mlm
    pre_lang_prerequisite: configure-mlm
  - name: pdf-tar-mlm
    pre_lang_prerequisite: configure-mlm
  - name: antora-mlm
    pre_lang_prerequisite: configure-mlm copy-branding
  - name: obs-packages-mlm
    pre_lang_prerequisite: configure-mlm clean
  - name: pdf-all-mlm
    pre_lang_prerequisite: configure-mlm
  - name: validate-uyuni
    pre_lang_prerequisite: configure-uyuni
  - name: pdf-tar-uyuni
    pre_lang_prerequisite: configure-uyuni
  - name: antora-uyuni
    pre_lang_prerequisite: configure-uyuni copy-branding
  - name: obs-packages-uyuni
    pre_lang_prerequisite: configure-uyuni clean
  - name: pdf-all-uyuni
    pre_lang_prerequisite: configure-uyuni
antora:
  extensions:
    - extension: "'@antora/lunr-extension'"
asciidoc:
  extensions:
    - extension: "'@asciidoctor/tabs'"
  attributes:
      # Base container image mlm
    - attribute: bci-mlm
      value: "15 SP7"
      # Base container image UYUNI
    - attribute: bci-uyuni
      value: "15.6"
    - attribute: opensuse-version
      value: 15.5
    - attribute: saltversion
      value: "'3006.0'"
    - attribute: postgresql
      value: PostgreSQL
    - attribute: postgresql-version
      value: 16
    - attribute: sles-version
      value: 15
    - attribute:  sp-version
      value: SP6 #use for normal text
    - attribute: sp-base
      value: SP6
    - attribute: sp-vert
      value: sp6 #use for terminal block
    - attribute: sp-version-l
      value: sp6
    - attribute: sp-version-number
      value: 6
    - attribute: smrproductnumber
      value: 4.3
    - attribute: linkattrs
      value: true
    - attribute: sectlinks
      value: true
    - attribute: sectnums
      value: all
    - attribute: sectnumlevels
      value: 5
    - attribute: icons
      value: font
    - attribute: experimental
      value: true
    - attribute: susemgr
      value: "SUSE Multi-Linux Manager"
    - attribute: smr
      value: "for Retail"
    - attribute: uyuni
      value: Uyuni
    - attribute: slepos
      value: "SUSE Linux Enterprise Point of Service"
    - attribute: susemgrproxy
      value: "SUSE Multi-Linux Manager Proxy"
    - attribute: sles
      value: "SUSE Linux Enterprise Server"
    - attribute: slesforsap
      value: "SUSE Linux Enterprise Server for SAP Applications"
    - attribute: sled
      value: "SUSE Linux Enterprise Desktop"
    - attribute: sle
      value: "SUSE Linux Enterprise"
    - attribute: es
      value: Expanded Support
    - attribute: sll
      value: 'SUSE Liberty Linux'
    - attribute: sle-micro
      value: 'SLE Micro'
    - attribute: sl-micro
      value: 'SL Micro'
    - attribute: microversion
      value: '6.1'
    - attribute: leap
      value: "openSUSE Leap"
    - attribute: leapmicro
      value: "openSUSE Leap Micro"
    - attribute: microos
      value: MicroOS
    - attribute: slsa
      value: SLES
    - attribute: sls4sapa
      value: "SLES for SAP"
    - attribute: suse
      value: SUSE
    - attribute: slea
      value: SLE
    - attribute: sleses
      value: SUSE Linux Enterprise Server with Expanded Support
    - attribute: sleda
      value: SLED
    - attribute: unifiedinstaller
      value: Unified Installer
      # Clients
    - attribute: alibabaclo
      value: 'Alibaba Cloud Linux'
    - attribute: almalinux
      value: AlmaLinux
    - attribute: amazon
      value: 'Amazon Linux'
    - attribute: centos
      value: CentOS
    - attribute: debian
      value: Debian
    - attribute: oes
      value: 'Open Enterprise Server'
    - attribute: oesa
      value: 'OES'
    - attribute: opensuse
      value: openSUSE
    - attribute: tumbleweed
      value: Tumbleweed
    - attribute: oracle
      value: 'Oracle Linux'
    - attribute: raspberrypios
      value: 'Raspberry Pi OS'
    - attribute: redhat
      value: 'Red Hat'
    - attribute: rhel
      value: 'Red Hat Enterprise Linux'
    - attribute: rhela
      value: 'RHEL'
    - attribute: rhnminrelease6
      value: 'Red Hat Enterprise Linux Server 6'
    - attribute: rhnminrelease7
      value: 'Red Hat Enterprise Linux Server 7'
    - attribute: rhnminrelease8
      value: 'Red Hat Enterprise Linux Server 8'
    - attribute: rocky
      value: 'Rocky Linux'
    - attribute: ubuntu
      value: Ubuntu
    - attribute: openeuler
      value: openEuler
      # Architectures
    - attribute: aarch64
      value: aarch64
    - attribute: amd64
      value: amd64
    - attribute: arm64
      value: arm64
    - attribute: armhf
      value: armhf
    - attribute: arm
      value: ARM
    - attribute: ipf
      value: Itanium
    - attribute: ppc
      value: 'IBM Power'
    - attribute: ppc64
      value: ppc64
    - attribute: ppc64le
      value: ppc64le
    - attribute: s390x
      value: s390x
    - attribute: x86
      value: x86
    - attribute: x86_64
      value: x86-64
    - attribute: ibmz
      value: IBM Z
    - attribute: zseries
      value: IBM Z
    - attribute: zsystems
      value: IBM Z
      # Documentation
    - attribute: homepage
      value: https://github.com/uyuni-project/uyuni-docs/
      # Everything else
    - attribute: cobbler
      value: Cobbler
    - attribute: grub
      value: Grub
    - attribute: kickstart
      value: Kickstart
    - attribute: webui
      value: Web UI
    - attribute: jeos
      value: JeOS
    - attribute: minimal
      value: Minimal
    - attribute: minimalsles
      value: Minimal SLES
    - attribute: scc
      value: SCC
    - attribute: scclongform
      value: SUSE Customer Center
    - attribute: ncc
      value: Novell Customer Center
    - attribute: phub
      value: 'SUSE Package Hub'
    - attribute: ay
      value: AutoYaST
    - attribute: yast
      value: YaST
    - attribute: rootuser
      value: root
    - attribute: ruser
      value: root
    - attribute: mdash
      value: '\-'
    - attribute: openscap
      value: OpenSCAP
    - attribute: rmtool
      value: "Repository Management Tool"
    - attribute: smtool
      value: "Repository Management Tool"
    - attribute: vmguest
      value: VM Guest
    - attribute: vmhost
      value: VM Host Server
    - attribute: xen
      value: Xen
    - attribute: kvm
      value: KVM
    - attribute: kube
      value: Kubernetes
    #SLES dependant documentation links
    - attribute: sles-base-os-documentation
      value: https://documentation.suse.com/sles/15-SP6/html/SLES-all
      # Table icon entities
    - attribute: check
      value: 'icon:check[role="green"]'
    - attribute: cross
      value: 'icon:times[role="danger"]'
    - attribute: question
      value: 'icon:question[role="gray"]'
    - attribute: star
      value: 'icon:asterisk[role="none"]'
    - attribute: minus
      value: 'icon:minus[role="blue"]'
    - attribute: salt
      value: Salt
    - attribute: saltboot
      value: Saltboot
    - attribute: imagesdir
      value: images
    - attribute: listing-caption
      value: Listing
    - attribute: mgradvtop
      value: Advanced Topics Guide
    - attribute: mgrbestpract
      value: Best Practices Guide
    - attribute: mgrgetstart
      value: Getting Started Guide
    - attribute: mgrrefguide
      value: Reference Guide
    - attribute: upgrade
      value: Upgrade Guide
    - attribute: snippet
      value: ../../snippets/
    - attribute: sourcedir
      value: .
    - attribute: source-highlighter
      value: highlight.js
    - attribute: toclevels
      value: 3
    - attribute: toc
      value: macro
    - attribute: doctype
      value: book
    - attribute: byos
      value: BYOS
    - attribute: byoslongform
      value: Bring-your-own-subscription
    - attribute: payg
      value: PAYG
    - attribute: payglongform
      value: Pay-as-you-go
    - attribute: aws
      value: AWS
    - attribute: awslongform
      value: Amazon Web Services
    - attribute: gcp
      value: GCP
    - attribute: gcplongform
      value: Google Cloud Compute
    - attribute: azure
      value: Microsoft Azure
    - attribute: CoCo
      value: Confidential Computing
