# Which branch and repository are you building from?
# Where are you publishing to and which UI should you use?
content:
  sources:
  # Uncomment to build from your local git clone
  - url: .
    start_path: .
  # Uncomment to build from the remote github repository.
  #- url: https://github.com/uyuni-project/uyuni-docs.git
    # Select the branch you want to build
    # If you make changes on a branch and have the wrong branch selected you will not see your changes in your build
    branches:
    - '.'  
output:
  dir: ./build/en
runtime:
  cache_dir: ./.cache/antora
antora:
  extensions:
    - '@antora/lunr-extension'
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
  attributes:
    bci-mlm: 15 SP7
    bci-uyuni: 15.6
    opensuse-version: 15.5
    saltversion: '3006.0'
    postgresql: PostgreSQL
    postgresql-version: 16
    sles-version: 15
    sp-version: SP7
    sp-base: SP7
    sp-vert: sp7
    sp-version-l: sp7
    sp-version-number: 7
    smrproductnumber: 4.3
    linkattrs: True
    sectlinks: True
    sectnums: all
    sectnumlevels: 5
    icons: font
    experimental: True
    susemgr: SUSE Multi-Linux Manager
    smr: for Retail
    uyuni: Uyuni
    slepos: SUSE Linux Enterprise Point of Service
    susemgrproxy: SUSE Multi-Linux Manager Proxy
    sles: SUSE Linux Enterprise Server
    slesforsap: SUSE Linux Enterprise Server for SAP Applications
    sled: SUSE Linux Enterprise Desktop
    sle: SUSE Linux Enterprise
    es: Expanded Support
    sll: SUSE Liberty Linux
    sle-micro: SLE Micro
    sl-micro: SL Micro
    microversion: 6.1
    microversionforuyuni: 5.5
    leap: openSUSE Leap
    leapmicro: openSUSE Leap Micro
    microos: MicroOS
    slsa: SLES
    sls4sapa: SLES for SAP
    suse: SUSE
    slea: SLE
    sleses: SUSE Linux Enterprise Server with Expanded Support
    sleda: SLED
    unifiedinstaller: Unified Installer
    alibabaclo: Alibaba Cloud Linux
    almalinux: AlmaLinux
    amazon: Amazon Linux
    centos: CentOS
    debian: Debian
    oes: Open Enterprise Server
    oesa: OES
    opensuse: openSUSE
    tumbleweed: Tumbleweed
    oracle: Oracle Linux
    raspberrypios: Raspberry Pi OS
    redhat: Red Hat
    rhel: Red Hat Enterprise Linux
    rhela: RHEL
    rhnminrelease6: Red Hat Enterprise Linux Server 6
    rhnminrelease7: Red Hat Enterprise Linux Server 7
    rhnminrelease8: Red Hat Enterprise Linux Server 8
    rocky: Rocky Linux
    ubuntu: Ubuntu
    openeuler: openEuler
    aarch64: aarch64
    amd64: amd64
    arm64: arm64
    armhf: armhf
    arm: ARM
    ipf: Itanium
    ppc: IBM Power
    ppc64: ppc64
    ppc64le: ppc64le
    s390x: s390x
    x86: x86
    x86_64: x86-64
    ibmz: IBM Z
    zseries: IBM Z
    zsystems: IBM Z
    homepage: https://github.com/uyuni-project/uyuni-docs/
    cobbler: Cobbler
    grub: Grub
    kickstart: Kickstart
    webui: Web UI
    jeos: JeOS
    minimal: Minimal
    minimalsles: Minimal SLES
    scc: SCC
    scclongform: SUSE Customer Center
    ncc: Novell Customer Center
    phub: SUSE Package Hub
    ay: AutoYaST
    yast: YaST
    rootuser: root
    ruser: root
    mdash: \-
    openscap: OpenSCAP
    rmtool: Repository Management Tool
    smtool: Repository Management Tool
    vmguest: VM Guest
    vmhost: VM Host Server
    xen: Xen
    kvm: KVM
    kube: Kubernetes
    sles-base-os-documentation: https://documentation.suse.com/sles/15-SP6/html/SLES-all
    check: icon:check[role="green"]
    cross: icon:times[role="danger"]
    question: icon:question[role="gray"]
    star: icon:asterisk[role="none"]
    minus: icon:minus[role="blue"]
    salt: Salt
    saltboot: Saltboot
    imagesdir: images
    listing-caption: Listing
    mgradvtop: Advanced Topics Guide
    mgrbestpract: Best Practices Guide
    mgrgetstart: Getting Started Guide
    mgrrefguide: Reference Guide
    upgrade: Upgrade Guide
    snippet: partials/
    sourcedir: .
    source-highlighter: highlight.js
    toclevels: 3
    toc: macro
    doctype: book
    byos: BYOS
    byoslongform: Bring-your-own-subscription
    payg: PAYG
    payglongform: Pay-as-you-go
    aws: AWS
    awslongform: Amazon Web Services
    gcp: GCP
    gcplongform: Google Cloud Compute
    azure: Microsoft Azure
    CoCo: Confidential Computing

    productname: "Uyuni"
    releaseversion: '2025.10'
    productnumber: "2025.10"
    mlm-content: False
    uyuni-content: True
    page-pagination: True

site:
  title: Uyuni Documentation
  start_page: uyuni::index.adoc
  url: https://www.uyuni-project.org/uyuni-docs/

ui:
  bundle:
    url: ./branding/default-ui/uyuni/ui-bundle.zip
    snapshot: True
  supplemental_files: ./branding/supplemental-ui/uyuni/uyuni-2023

