[[troubleshooting-container-inspection]]
= Troubleshooting Container Image Inspection



////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

The container image all the software to run {productname}, but not all tools and libraries you may need for debugging.

While inspecting a container image with {productname} you can see an error message such as:

----
libssl.so.1.1: cannot open shared object file: No such file or directory
----

To avoid such issues you need to add [systemitem]``libopenssl`` to the image with [systemitem]``Dockerfile`` and rebuild the container image with it inside.

The same can happen with [systemitem]``libexpat``.

