[[troubleshooting-retrying-setup-target-system]]
= Troubleshooting Retrying to Set up the Target System

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

////
Cause: Caches on the ISS slave and master can contain old or out-of-date entries.
Consequence: Synchronizing fails, with ``ERROR: Encountered IntegrityError``.
Fix: Delete the cache on the slave and the master
Result: Synchronization completes successfully.
////


If you need to retry setting up the target system, follow these steps:

. Delete [path]``/root/.MANAGER_SETUP_COMPLETE``.
. Stop PostgreSQL and remove [path]``/var/lib/pgsql/data``.
. Set the target system hostname to match the source system hostname.
. Check the [path]``/etc/hosts`` file, and correct it if necessary.
. Check [path]``/etc/setup_env.sh`` on the target system, and ensure the database name is set:
+
----
MANAGER_DB_NAME='susemanager'
----
. Reboot the target system.
. Run [command]``mgr-setup`` again.


