[[troubleshooting-hardware-refresh]]
= Troubleshooting hardware refresh

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

Hardware refresh takes place automatically and thus DMI info stored in the database can change.
This can result in misleading information if the client or parts of the clients infrastructure such as networking is temporarily unavailable.
The user can see it in the {productname} {webui} in the menu:Systems[Details > Hardware] tab.

Hardware refresh is part of the [systemitem]``system-profile-refresh`` taskomatic job that runs once a month.
For more information about configuring [systemitem]``system-profile-refresh``, see xref:administration:task-schedules.adoc[].
