[[troubleshooting-container-inspection]]
= Troubleshooting Container Image Inspection



////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

The base container image (BCI) comes with all the software to run {productname}, but because BCIs are lightweight they may not come with all tools and libraries you may need for debugging.

While inspecting a container image with {productname} you can see an error message such as:

----
libssl.so.1.1: cannot open shared object file: No such file or directory
----

BCI image can be used in the other scenarious than with the container build host and using the {salt} bundle for the inspection, but if you need inspection to work you need to add it in advance.

To avoid such issues you must add [systemitem]``libopenssl`` to the image with [systemitem]``Dockerfile`` (but not to the BCI) and rebuild the container image with it inside.

The same can happen with [systemitem]``libexpat``.

