[[troubleshooting-remote-root-on-micro]]
= Remote root login on {sl-micro}
:description: Enable password-based remote root login on SL Micro container hosts to access managed clients and Proxy components securely.
:revdate: 2025-06-17
:page-revdate: {revdate}

For enhanced security, new installations of {sl-micro} 6.1 and later do not allow password-based remote root login anymore, which also affects server and proxy container hosts running on {sl-micro} and managed {sl-micro} clients.
Also {sle-micro} 5.5 clients with password-based remote root login which will when be migrated to 6.1/6.2 will suddenly lose this access and must be newly configured.
For more information, see SL Micro Release Notes 6.1 (https://www.suse.com/releasenotes/x86_64/SL-Micro/6.1/index.html#jsc-SMO-405).


While deploying components of {productname} such as a {productname} Proxy, by default, password-based remote root login is required.
You can enable password-based remote root login with the following steps.



.Procedure: Enable SSH root login with a password on {sl-micro}

. On the container host, start a transactional shell:

+

[source,shell]
----
transactional-update shell
----

+

--

.. In [path]``/usr/etc/ssh/sshd_config`` file, set:

+

// FIXME: or better /etc/ssh/sshd_config.d/sshd.conf? (e.g., see server migration

+

----
PermitRootLogin yes
----

.. Leave the shell with [command]``exit`` to save the new configuration.

--

+

. Reboot the container host to activate the new configuartion:

+

[source,shell]
----
transactional-update reboot
----

For more information about [command]``transactional-update``, see https://documentation.suse.com/sle-micro/6.1/html/Micro-transactional-updates/.