[[troubleshooting-TEMPLATE]]
= Troubleshooting Registering traditional client as Salt minion after deleting it


////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

////
Cause: Caches on the ISS slave and master can contain old or out-of-date entries.
Consequence: Synchronizing fails, with ``ERROR: Encountered IntegrityError``.
Fix: Delete the cache on the slave and the master
Result: Synchronization completes successfully.
////

[WARNING]
====
This is not a valid scenario. Normally you migrate a traditional client to a Salt minion without deleting the client.
====
Salt automatically detects that you have a traditional client and does the necessary changes itself. But if you somehow
deleted the traditional client and want to register it as a Salt minion again, you have to do the following steps on the
client before registering it as Salt minion:

. Remove the following file:
+
----
/etc/sysconfig/rhn/systemid
----
+
. Remove the following package:
+
----
zypp-plugin-spacewalk
----
