[[troubleshooting-bare-metal-systems]]
= Troubleshooting Bare Metal Systems

If a bare metal system on the network is not automatically added to the [guilabel]``Systems`` list, check these things first:

* You must have the [path]``pxe-default-image`` package installed.
* File paths and parameters must be configured correctly. Check that the [path]``vmlinuz0`` and [path]``initrd0.img`` files, which are provided by [path]``pxe-default-image``, are in the locations specified in the [path]``rhn.conf`` configuration file.
* Ensure the networking equipment connecting the bare metal system to the {productname} server is working correctly, and that you can reach the {productname} server IP address from the server.
* The bare metal system to be provisioned must have PXE booting enabled in the boot sequence, and must not be attempting to boot an operating system.
* The DHCP server must be responding to DHCP requests during boot. Check the PXE boot messages to ensure that:
** the DHCP server is assigning the expected IP address
** the DHCP server is assigning the the {productname} server IP address as [option]``next-server`` for booting.
* Ensure Cobbler is running, and that the Discovery feature is enabled.

If you see a blue Cobbler menu shortly after booting, discovery has started.
If it does not complete successfully, temporarily disable automatic shutdown to help diagnose the problem. To disable automatic shutdown:
. Select [option]``pxe-default-profile`` in the Cobbler menu with the arrow keys, and press the Tab key before the timer expires.
. Add the kernel boot parameter [option]``spacewalk-finally=running`` using the integrated editor, and press Enter to continue booting.
. Enter a shell with the username [option]``root`` and password [option]``linux`` to continue debugging.

[IMPORTANT]
.Duplicate profiles
====
Due to a technical limitation, it is not possible to reliably distinguish a new bare metal system from a system that has previously been discovered.
Therefore, we recommended that you do not power on bare metal systems multiple times, as this results in duplicate profiles.
====
