[[troubleshooting-remote-root-on-micro]]
= Remote root login on {sl-micro}
:description: Enable password-based remote root login on SL Micro to deploy and configure components of the SUSE Multi-Linux Manager securely
:revdate: 2025-06-17
:page-revdate: {revdate}

For enhanced security, new installations of {sl-micro} 6.1 and later do not allow password-based remote root login anymore, which also affects server and proxy container hosts running on {sl-micro} and managed {sl-micro} clients.
Also, {sle-micro} 5.5 clients with password-based remote root login which will when be migrated to 6.1/6.2 will suddenly lose this access and must be newly configured.
For more information, see SL Micro Release Notes 6.1 (https://www.suse.com/releasenotes/x86_64/SL-Micro/6.1/index.html#jsc-SMO-405).

While deploying components of {productname} such as a {productname} Proxy, password-based remote root login is required by default.
You can enable password-based remote root login with the following steps.


.Procedure: Enabling SSH root login with a password on {sl-micro}
[role=procedure]
____
You can enable SSH root login in two different ways. 
Either of them will work; choose the one that best fits your setup.

.Option A: Use the preconfigured package

. Install the package [package]``openssh-server-config-rootlogin`` from the UI/API on the client.

. Reboot the container host to activate the new configuration either from UI or from terminal

.Option B: Edit the SSH configuration manually

. Add a drop-in config [path]``/etc/ssh/sshd_config.d/permit_root.conf`` file, with the following content:

+
----
PermitRootLogin yes
----

. Reload the SSH server configuration
+
[source,shell]
----
systemctl reload sshd
----

. If connected using SSH, before disconnecting from the server, validate the SSH server is working correctly by opening a new SSH connection.

____


For more information about [command]``transactional-update``, see https://documentation.suse.com/sle-micro/6.1/html/Micro-transactional-updates/.

