[[ref-patches-details]]
= Patch Details

{localesdir} 


The menu:Patches[Patch List > Patch Details] section displays the details of a selected patch.
Click the advisory number of a patch in the [menuitem]``Patch List`` to see more information about the patch.

This section is divided into tabs.



[[s4-sm-errata-details-details]]
== Details

The [menuitem]``Details`` tab shows the patch report provided by {suse}.

In the [guimenu]``Affected Channels`` section, all channels that contain the affected package are listed.
Click the channel name to go to menu:Software[Channel Details].

For security patches, additional information is shown about the vulnerability, including the CVE and OVAL details.

For more information about {suse} Update Advisories, see link:https://www.suse.com/support/update/[].



[[s4-sm-errata-details-packages]]
== Packages

The [menuitem]``Packages`` tab provides links to each of the updated packages by channel.
Click the name of a package to go to menu:Software[Channel Details].



[[s4-sm-errata-details-systems]]
== Affected Systems

The [menuitem]``Affected Systems`` tab provides a list of installed clients that the patch affects.
You can install updates from this tab.

Click the name of a client to go to menu:Systems[System Details].

Each client in the list shows the current status of the patch on that client.
This column identifies only the most recent action.
Click the name of a status in the list to go to the [guimenu]``Action Details`` page.


[[client-update-status]]
[cols="1,1,1", options="header"]
.Client Update Status Icons
|===
| Description | Action Required
| N/A | Check the status manually.
| Pending | The client will be updated at the next synchronization.
| Picked Up | The client is in the progress of updating.
| Completed | The client successfully installed the patch.
| Failed | The client attempted to install the patch, but encountered an error.
|===
