[[ref-patches-relevant]]
= Relevant Patches
:description: Learn how to effectively manage and prioritize patches for your SUSE clients in the Patches Patch List Relevant section, which displays a list of all applicable
:revdate: 2025-01-20
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Manager
:page-product-version: 4.3

The menu:Patches[Patch List > Relevant] section displays a list of all patches released by {suse} that apply to your installed clients.

Each patch in the list shows a patch type, an advisory number, a short description, the number of clients in your network affected, and the date the patch was last updated.
Click the advisory number to see more information about the patch.
For more information about the menu:Patches[Patch List > Patch Details] section, see xref:reference:patches/patch-details.adoc[]


[[patch-status]]
[cols="1,1,1", options="header"]
.Patch Status Icons
|===
| Icon | Description | Action Required
| icon:bug[role="none"] | Bug fix | Recommended
| image:spacewalk-icon-enhancement.svg[] | Product enhancement advisory | Optional
| icon:shield-alt[role="yellow"] | Security update | Essential
| icon:archive[role="none"]| Affects package management stack | Recommended
|===


[NOTE]
====
To receive email when new patches are available, navigate to menu:Home[My Preferences] and check [guimenu]``Receive email notifications``.
====
