[[ref-systems-keys]]
= Activation Keys
:description: Learn how to manage and configure your organizations activation keys through the Systems menu, where you can view current keys, monitor usage, enable or disable
:revdate: 2020-09-11
:page-revdate: {revdate}

The menu:Systems[Activation Keys] section lists the current activation keys for your organization.

The universal default activation key, if set, is automatically used for all clients registered to your organization, unless you specify a different activation key.

The list of activation keys shows the name and description for each key, and how many times the key has been used.
It also shows if the key is currently enabled for your organization.
Click the key description to see more information about the activation key.

Click btn:[Update Activation Keys] to refresh the list with recent changes.

Click btn:[Create Key] to create a new activation key.

For more information about activation keys, see xref:client-configuration:activation-keys.adoc[].
