[[ref-systems-keys]]
= Activation Keys
:description: Learn how to centrally manage your organizations current and historical activation keys, track usage statistics, and enable or disable them as needed for all
:revdate: 2020-09-11
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

The menu:Systems[Activation Keys] section lists the current activation keys for your organization.

The universal default activation key, if set, is automatically used for all clients registered to your organization, unless you specify a different activation key.

The list of activation keys shows the name and description for each key, and how many times the key has been used.
It also shows if the key is currently enabled for your organization.
Click the key description to see more information about the activation key.

Click btn:[Update Activation Keys] to refresh the list with recent changes.

Click btn:[Create Key] to create a new activation key.

For more information about activation keys, see xref:client-configuration:activation-keys.adoc[].
