[[ref-systems-autoinst-overview]]
= Autoinstallation Overview

The menu:Systems[Autoinstallation > Overview] section displays an overview of your autoinstallation settings, including clients that are autoinstalling, or scheduled to be autoinstalled.

The menu:Systems[Details > Overview] subtab is split into sections:

Autoinstallation Summary::
This section lists the {ay} and {kickstart} profiles currently available, and the number of clients installed with each profile.

Autoinstallation Actions::
This section provides links to actions related to autoinstallation.
You can also access these using the menu:Systems[Autoinstallation] menu.

Systems Currently Autoinstalling::
This section lists all clients that are currently autoinstalling, along with their status.

Systems Scheduled to be Autoinstalled::
This section lists all clients that are scheduled for autoinstallation, along with their status.


Click btn:[Create Kickstart Profile] to create a new {kickstart} profile.
Click btn:[Upload Kickstart/{ay} File] to upload a new autoinstallation file.


For more information about autoinstallation, see xref:client-configuration:autoinst-intro.adoc[].
