[[ref-systems-ssm-overview]]
= System Set Manager Overview

The menu:Systems[System Set Manager > Overview] section allows you to manage clients that you have added to the system set manager (SSM).
You can also access this page by clicking the [guimenu]``systems selected`` icon in the top menu bar.

For more information about SSM, see xref:client-configuration:system-set-manager.adoc[].

The menu:Systems[Systems Set Manager] menu is split into tabs:



== Overview

This section provides quick access to all the of the SSM tabs.



== Systems

This section lists all clients currently in the SSM.
It provides information about the updates available, when thew client last checked in, the registered base channel, and system type.
Click the client name to see more information.



== Patches

This section lists all patches available for upgrade on clients currently in the SSM.
Click the number in the [guimenu]``Affected`` column to see which clients a patch applies to.
To perform upgrades, check the patches to apply and click btn:[Apply Patches].

For more information about patch management, see xref:client-configuration:patch-management.adoc[].



== Packages

This section is split into subtabs.

The menu:Packages[Upgrade] subtab lists all packages available for upgrade on clients currently in the SSM.
To perform upgrades, check the packages to upgrade and click btn:[Upgrade Selected Packages].

The menu:Packages[Install] subtab allows you to install new packages on all clients currently in the SSM.
To install packages, click the base channel that contains the package, check the packages to install, and click btn:[Install Selected Packages].

The menu:Packages[Remove] subtab allows you to remove packages from all clients currently in the SSM.
If clients in the SSM have different versions of a package installed, multiple versions are available in the list.
To remove packages, select the packages to remove, and click btn:[Remove Selected Packages].

On traditional clients, the menu:Packages[Verify] subtab allows you to verify packages against the package repository.
To verify a package, check the package in the list and click btn:[Verify Selected Packages].
When the verification is complete, navigate to menu:Systems[Events > History] to see the results.

For more information about package management, see xref:client-configuration:package-management.adoc[].



== Groups

This section lists all system groups clients currently available in your organization.
Click btn:[Create Group] to create a new system group.
For each group in the list, check [guimenu]``Add`` to add all clients in the SSM to the group, check [guimenu]``Remove`` to remove all clients in the SSM from the group, or check [guimenu]``No Change`` to leave group assignments as they are.
Click btn:[Alter Membership] to change group assignments.

For more information about system groups, see xref:client-configuration:system-groups.adoc[].



== Channels

This section lists all base channels clients currently subscribed to by clients currently in the SSM.
You can change all clients subscribed to a current base channel to a new base channel, by selecting the new base channel and following the prompts.

For more information about software channels, see xref:client-configuration:channels.adoc[].

For more information about using the SSM to change base channels, see xref:client-configuration:system-set-manager.adoc[].



== Configuration

This section is split into subtabs.

The menu:Configuration[Deploy Files] subtab lists all configuration files available for deployment.
Click the number in the [guimenu]``Systems`` column to see which clients are currently subscribed to the configuration file.
To assign a configuration file to the clients currently in the SSM, check the configuration file, and click btn:[Schedule File Deploy].

The menu:Configuration[Compare Files] subtab lists all configuration files available for comparison.
This compares the configuration file deployed on a client with the configuration file stored on the {productname} Server.
Click the number in the [guimenu]``Systems`` column to see which clients are currently subscribed to the configuration file.
To compare configuration files, check the configuration files to compare, and click btn:[Schedule File Comparison].

The menu:Configuration[Subscribe to Channels] subtab lists all configuration channels available for subscription.
To subscribe the clients in the SSM to a new configuration channel, check the configuration channel, click btn:[Continue], and follow the prompts.

The menu:Configuration[Unsubscribe from Channels] subtab lists all configuration channels clients in the SSM are currently subscribed to.
To unsubscribe the clients in the SSM from a configuration channel, check the configuration channel and click btn:[Unsubscribe Systems].

The menu:Configuration[Enable Configuration] subtab lists clients in the SSM that are capable of using configuration management, but have not yet been enabled.
To enable clients in the SSM to use configuration management, check the client and click btn:[Enable Configuration Management].

For more information about configuration management, see xref:client-configuration:configuration-management.adoc[].



== Provisioning

This section is split into subtabs.

The menu:Provisioning[Autoinstallation] subtab lists all clients in the SSM available for autoinstallation, with their base channel.
To schedule autoinstallation, select an autoinstallable type, click btn:[Continue] and follow the prompts.

The menu:Provisioning[Power Management Configuration] subtab allows you to configure power management for the clients in the SSM.
For more information about power management, see xref:client-configuration:power-management.adoc[].

The menu:Provisioning[Power Operations] subtab allows you to power on, power off, or reboot the  clients in the SSM.
For more information about power management, see xref:client-configuration:power-management.adoc[].

For more information about autoinstallation, see xref:client-configuration:autoinst-intro.adoc[].



== States

For Salt clients, the menu:States[Highstate] subtab allows you to apply the highstate to all clients in the SSM.



== Audit

For traditional clients, this section allows you to schedule a new XCCDF scan on all clients in the SSM.
For more information about auditing, see xref:administration:auditing.adoc[].


== Misc

This section is split into subtabs.

The menu:Misc[Preferences] subtab allows you to configure the custom information, system types, and system preferences for the clients in the SSM.

The menu:Misc[Hardware] subtab allows you to schedule a hardware profile refresh for the clients in the SSM.

The menu:Misc[Software] subtab allows you to schedule a package profile refresh for the clients in the SSM.

The menu:Misc[Remote Command] subtab allows you to schedule a remote command to be executed on the clients in the SSM.

The menu:Misc[Custom Values] subtab allows you to set or remove custom key values for the clients in the SSM.

For traditional clients, the menu:Misc[Lock/Unlock] subtab allows you to lock or unlock clients in the SSM.

The menu:Misc[Reboot] subtab allows you to schedule a reboot for the clients in the SSM.

The menu:Misc[Transfer] subtab allows you to move clients in the SSM to a new organization.

The menu:Misc[Delete] subtab allows you to delete the system profiles of clients in the SSM.
