[[ref-systems-list]]
= Systems List

The menu:Systems[System List] section lists all clients available in your {productname} environment.

For more information about managing clients, see xref:client-configuration:client-config-overview.adoc[].

The menu:Systems[System List] section is split into submenus:



== All

The menu:Systems[System List > All] section lists every client that you have permission to manage.



== Physical Systems

The menu:Systems[System List > Physical Systems] section lists every client that is installed on physical hardware.



== Virtual Systems

The menu:Systems[System List > Virtual Systems] section lists every client that is installed on virtual hardware.
The list includes all your virtual hosts, and the virtual guests that are attached to them.

For virtual guests that are registered to the {productname} Server, click the name of the guest to manage it.
Virtual guests that are not registered are shown, but cannot be managed in the {webui}.

For more information about virtual clients, see xref:client-configuration:virtualization.adoc[].



== Unprovisioned Systems

The menu:Systems[System List > Unprovisioned Systems] section lists every bare metal client that the {productname} Server is aware of, but has not yet been registered.

For more information about bare metal clients, see xref:client-configuration:autoinst-intro.adoc[].


== Out of Date

The menu:Systems[System List > Out of Date] section lists every client that has available updates.

For more information about managing client updates, see xref:client-configuration:package-management.adoc[].



== Requiring Reboot

The menu:Systems[System List > Requiring Reboot] section lists every client that requires rebooting.



== Non Compliant

The menu:Systems[System List > Non Compliant] section lists every client that has non-compliant packages installed.
Packages are considered non-compliant if they have been installed from a source other than {productname}.
In the list, the [guimenu]``Packages`` column shows the number of non-compliant packages on the client.



== Without System Type

The menu:Systems[System List > Without System Type] section lists every client that does not have a base system type recorded.

For more information about system types, see xref:client-configuration:system-types.adoc[].



== Ungrouped

The menu:Systems[System List > Ungroups] section lists every client that is not assigned to a system group.

For more information about system groups, see xref:client-configuration:system-groups.adoc[].



== Inactive

The menu:Systems[System List > Inactive] section lists every client that has not checked in with the the {productname} Server in 24 hours or more.

For more information about client connections to the server, see xref:client-configuration:contact-methods-intro.adoc[].

For more information on troubleshooting inactive clients, see xref:administration:troubleshooting/tshoot-inactiveclients.adoc[].



== Recently Registered

The menu:Systems[System List > Recently Registered] section lists every client that has registered within a given period.
Select the period to view from the [guimenu]``View systems registered`` field.



== Proxy

The menu:Systems[System List > Proxy] section lists every client that is registered as a proxy.



== Duplicate Systems

The menu:Systems[System List > Duplicate Systems] section lists clients that share IP addresses, host names, or MAC addresses.
Use the tabs to compare clients.



== System Currency

The menu:Systems[System List > System Currency] section lists all clients with information about available updates, and provides a currency score for each.
You can use the currency score to determine in which order clients should be updated.
A score with a larger number indicates that a client is not current, and might require critical updates.



== System Types

The menu:Systems[System List > System Types] section lists every client, their base system type, add-on system type, and base channel.
It also gives a count of clients of each system type.

For more information about system types, see xref:client-configuration:system-types.adoc[].
