[[ref-systems-menu]]
= Systems Menu

The [guimenu]``Systems`` section allows you to manage your client systems.

The menu:Systems[] menu contains submenu entries in the left navigation bar and as its overview page displays the menu:Systems[System List > All] listing with all client systems registered to the {productname} Server.

This listing contains information about the clients, including available software updates, extra packages (otherwise often referenced as non-compliant packages), and the base channel they are subscribed to.














All the submenu entries:

* [guimenu]``System List``          - xref:reference:systems/systems-list.adoc[]
* [guimenu]``System Groups``	    - xref:reference:systems/system-groups.adoc[]
* [guimenu]``System Set Manager``   - xref:reference:systems/ssm-menu.adoc[]
* [guimenu]``Bootstrapping``	    - xref:reference:systems/bootstrapping.adoc[]
* [guimenu]``Proxy Configuration``  - xref:reference:systems/proxy-configuration.adoc[]
* [guimenu]``Advanced Search``	    - xref:reference:systems/advanced-search.adoc[]
* [guimenu]``Activation Keys``	    - xref:reference:systems/activation-keys.adoc[]
* [guimenu]``Stored Profiles``	    - xref:reference:systems/stored-profiles.adoc[]
* [guimenu]``Custom System Info``   - xref:reference:systems/custom-system-info.adoc[]
* [guimenu]``Autoinstallation``	    - xref:reference:systems/autoinst-menu.adoc[]
* [guimenu]``Virtual Host Managers` - xref:reference:systems/virtual-host-managers.adoc[]`


Click the name of a client to go to that client system's [guimenu]``Details`` overview page and all its tabs and subtabs.
For more information about the [guimenu]``System Details`` overview page in the {webui}, see xref:reference:systems/system-details/sd-details.adoc[].


Check a client to add it to the system set manager.
For more information about the system set manager, see xref:client-configuration:system-set-manager.adoc[].

Click btn:[Add Systems] to go to menu:Systems[Bootstrapping].
For more about bootstrapping new clients, see xref:reference:systems/bootstrapping.adoc[].

For more information about managing clients, see xref:client-configuration:client-config-overview.adoc[].
