
= {productname} Documentation
:revdate: 2025-04-30
:page-revdate: {revdate}

ifeval::[{mlm-content} == true]

[.currentrel]**Version: {productnumber}**
endif::[]

ifeval::[{uyuni-content} == true]

[.currentrel]**Version: {productnumber}**

endif::[]

ifeval::[{mlm-content} == true]

[IMPORTANT]
====
We are currently in the process of updating and enhancing the [.currentrel]**{productnumber}** documentation. Please note that this documentation is currently in **draft** form and should be considered a work in progress (WIP).

The final release of version 5.1 is expected mid 2025. Until then, content may evolve, and certain sections may be incomplete or subject to change.

Your Feedback Matters: We welcome and appreciate your feedback. If you encounter unclear information, gaps in coverage, or have suggestions for improvement, please let us know. Your input is invaluable in helping us deliver accurate and useful documentation.

📬 Submit feedback: https://github.com/uyuni-project/uyuni-docs/issues
====
endif::[]

ifeval::[{uyuni-content} == true]

[IMPORTANT]
====
We are currently in the process of enhancing the [.currentrel]**{productnumber}** documentation.

**We Value Your Input:** Your feedback is crucial to us! 
If you find any aspects of the documentation unclear or notice missing information, please do not hesitate to reach out. 
We appreciate your questions and suggestions, which are vital in helping us improve.


提交反馈：https://github.com/uyuni-project/uyuni-docs/issues
====
endif::[]


== 什么是 {productname}？


// [#salt.gloss] may be used to create a tooltip for a glossary term: see branding/supplemental-ui/mlm/mlmcom/partials/footer-scripts.hbs

{productname} 解决方案面向需要加强控制其服务器上的维护工作和软件包部署的组织。它可让您通过自动化软件管理、资产管理和系统置备来管理大型 Linux 系统集并使它们保持最新。它还可让您保持较高级别的安全性，同时有效管理系统生命周期方面的要求。

{productname} 使用 {salt} 提供事件驱动的配置和管理控制。Salt 主服务器使用远程执行方法来协调数万个 {salt} 客户端（{productname} 客户端）。

{productname} 提供 {sle}、{opensuse}、{rhel}、{centos}、{oracle}、{ubuntu}、{debian}、{amazon}、{almalinux} 和 {raspberrypios} 客户端系统的无缝管理。这些系统可能位于本地、公有云、私有云、混合云，甚至是多云环境中。



// MLM index content

ifeval::[{mlm-content} == true]
== 可用文档

The following documentation for {productname} version {productnumber} is available in PDF format for easy download and reference.


Download the complete set of PDFs icon:caret-right[] icon:file-archive[link="../suse-multi-linux-manager-docs_en-pdf.zip"]

[TIP]
====
{productname} documentation is available in several locations and formats. For the most up-to-date version of this documentation, see link:https://documentation.suse.com/[SUSE Multi-Linux Manager].
====

endif::[]


//Uyuni Index content

ifeval::[{uyuni-content} == true]
== 可用文档

The following documentation for {productname} version {productnumber} is available in PDF format for easy download and reference.

Download the complete set of PDFs icon:caret-right[] icon:file-archive[link="../uyuni-docs_en-pdf.zip"]
endif::[]
