ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

ifndef::backend-pdf[]
[[reference-guide-overview]]
= Reference Guide
:revdate: 2025-05-21
:page-revdate: {revdate}

// HTML Publication date 
**发布日期：**{docdate}

== 前言


This document is divided into several sections:

- **{webui} Reference:** Organized to mirror the structure of the {productname} {webui}, this section allows you to quickly find relevant information while navigating the interface.  
- **spacecmd Reference:** A comprehensive guide to the [command]``spacecmd`` command-line interface. It includes an **alphabetized list** of all available commands along with their correct usage.  
- **Command Line Tools:** An overview of the various **command-line utilities** available in {productname}, helping you streamline administrative tasks. 

== 版权声明

ifeval::[{mlm-content} == true]
// HTML Copyright
版权所有 © {copyrightdate} SUSE LLC 和撰稿人。保留所有权利。根据 GNU ⾃由⽂档许可证 (GNU Free Documentation License) 版本 1.2 或（根据您的选择）版本 1.3 中的条款，在此授予您复制、分发和/或修改本⽂档的权限；本版权声明和许可证附带不可变部分。许可版本 1.2 的副本包含在 xref:legal:license.adoc[GNU Free Documentation License] 章节。
endif::[]

ifeval::[{uyuni-content} == true]
// HTML Copyright
Copyright © 2011–2025 Uyuni contributors. All rights reserved. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].
endif::[]

== 商标
// HTML Trademarks
有关 SUSE 商标，请参⻅ https://www.suse.com/company/legal/[]。所有第三⽅商标分别为相应所有者的财产。商标符号（®、™ 等）代表 SUSE 及其关联公司的商标。星号 (*) 代表第三⽅商标。本指南⼒求涵盖所有细节，但这不能确保本指南准确⽆误。SUSE LLC 及其关联公司、作者和译者对于可能出现的错误或由此造成的后果皆不承担责任。
endif::[]

ifdef::backend-pdf[]


<<<

:!sectnums:

[preface]
== 前言

Reference | {productname} {productnumber}

This document is divided into several sections:

- **{webui} Reference:** Organized to mirror the structure of the {productname} {webui}, this section allows you to quickly find relevant information while navigating the interface.  
- **spacecmd Reference:** A comprehensive guide to the [command]``spacecmd`` command-line interface. It includes an **alphabetized list** of all available commands along with their correct usage.  
- **Command Line Tools:** An overview of the various **command-line utilities** available in {productname}, helping you streamline administrative tasks. 

// PDF Publication

**发布日期：**{docdate}

ifeval::[{mlm-content} == true]
// PDF Copyright
版权所有 © {copyrightdate} SUSE LLC 和撰稿人。保留所有权利。根据 GNU ⾃由⽂档许可证 (GNU Free Documentation License) 版本 1.2 或（根据您的选择）版本 1.3 中的条款，在此授予您复制、分发和/或修改本⽂档的权限；本版权声明和许可证附带不可变部分。许可版本 1.2 的副本包含在 xref:legal:license.adoc[GNU Free Documentation License] 章节。
endif::[]

ifeval::[{uyuni-content} == true]
// PDF Copyright
Copyright © 2011–2025 Uyuni contributors. All rights reserved. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].
endif::[]

// PDF Trademarks
有关 SUSE 商标，请参⻅ https://www.suse.com/company/legal/[]。所有第三⽅商标分别为相应所有者的财产。商标符号（®、™ 等）代表 SUSE 及其关联公司的商标。星号 (*) 代表第三⽅商标。本指南⼒求涵盖所有细节，但这不能确保本指南准确⽆误。SUSE LLC 及其关联公司、作者和译者对于可能出现的错误或由此造成的后果皆不承担责任。

<<<

toc::[]

:sectnums:

endif::[]
