ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

= {productname}プロキシ エアギャップ(された)デプロイメント
:description: 提供された仮想マシンイメージ、またはコンテナイメージがプリロードされた SL Micro を使用してエアギャップ(された)環境に Proxy をインストールし、mgrpxy upgrade でアップグレードしてください。
:revdate: 2026-04-29
:page-revdate: {revdate}

== Air-gapped配備とは


エアギャップ(された)デプロイメントとは、特にインターネットなどの不安全なネットワークから物理的に隔離されたネットワークシステムのセットアップと運用を指します。
このタイプのデプロイメントは、軍事施設、金融システム、重要なインフラストラクチャ、および機密データが取り扱われ、外部の脅威から保護されなければならない場所など、高セキュリティ環境で一般的に使用されます。

[NOTE]
====
現時点では、エアギャップ(された)デプロイメントは{sl-micro}でのみ利用可能です。
====


== 仮想マシンでの配備

推奨されるインストール方法は、提供されている{productname}の仮想マシンイメージオプションを使用する方法です。必要なツールとコンテナイメージがすべてプリロードされていて、すぐに動作するためです。

{productname}プロキシ仮想マシンのインストールに関する詳細情報は、xref:container-deployment/mlm/proxy-deployment-vm-mlm.adoc[プロキシを仮想マシンとしてデプロイする]を参照してください。

{productname} Proxy をアップグレードするには、ホストシステム上のすべてのパッケージをアップグレードしてから、`mgrpxy upgrade` を実行してください。
エアギャップ(された)環境でのインストールの場合は、`mgrpxy upgrade` を実行する前にコンテナ RPM パッケージをアップグレードしてください。


== {productname}を{sl-micro}にデプロイする

{productname}では、必要なコンテナイメージはすべてRPMとしても提供されており、これらのRPMをシステムにインストールすることができます。

.プロシージャ:エアギャップ(された)環境で{productname}を{sl-micro}にインストールします。
[role=procedure]
____
. {sl-micro}をインストールします。

. {productname}サーバ上のクライアントとしてプロキシホストOSを起動します。

. システムを更新します。

. ツールのパッケージとイメージパッケージをインストールします($ARCH$は適切なアーキテクチャと置き換えます)。

+

[source,shell]
----
transactional-update pkg install mgrpxy* mgrctl* suse-multi-linux-manager-5.2-$ARCH$-proxy-*
----

. 再起動します。

. mgrpxyを使用して{productname}をデプロイします。
____


{productname}プロキシを{sl-micro}にインストールするための詳細情報は、xref:container-deployment/mlm/proxy-deployment-mlm.adoc[プロキシを仮想マシンとしてデプロイする]を参照してください。

{productname} Proxy をアップグレードするには、ホストシステム上のすべてのパッケージをアップグレードしてから、`mgrpxy upgrade` を実行してください。
エアギャップ(された)環境でのインストールの場合は、`mgrpxy upgrade` を実行する前にコンテナ RPM パッケージをアップグレードしてください。


== 利用可能なイメージ

BindやDHCP（Kea）などの一部のフォーミュラもコンテナを使用します。
エアギャップ(された)環境でそれらを使用する予定がある場合は、イメージをプルし、アーカイブに保存し、{productname}プロキシまたは他の管理されたシステムにロードする必要があります。

イメージは`registry.suse.com`から入手できます。

.プロシージャ:エアギャップ(された)環境におけるフォーミュライメージの取得
[role=procedure]
____
. インターネットにアクセスできるシステムで、必要なイメージをプルします。

+

[source,shell]
----
podman pull registry.suse.com/suse/bind:latest
podman pull registry.suse.com/suse/kea:2.6
----

. アーカイブからイメージをロードします。

+

[source,shell]
----
podman save -m -o formula-images.tar registry.suse.com/suse/bind:latest registry.suse.com/suse/kea:2.6
----

. `formula-images.tar`ファイルをエアギャップ(された)システムに転送してください。

. アーカイブからイメージをロードします。

+

[source,shell]
----
podman load -i formula-images.tar
----
____
