= 使用 `mgradm` 进行自定义 YAML 配置和部署
:description: 学习如何以特定示例格式创建自定义 mgradm.yaml 文件，然后在部署时结合 mgradm 工具使用，并确保密码安全。
:revdate: 2024-11-19
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

您可以选择创建自定义 `mgradm.yaml` 文件，供 `mgradm` 工具在部署期间使用。
所有 `mgradm` 参数都有其 YAML 对应项。
例如，`mgradm` 参数 `--ssl-db-ca-intermediate` 可以在 `mgradm.yaml` 文件中指定，如下所示：

[source, yaml]
ssl:
  db:
    ca:
      intermediate: /path/to/ca-intermediate.crt

[IMPORTANT]
====
如果未通过命令行参数或 `mgradm` 配置文件提供基本变量，`mgradm.yaml` 将提示您输入这些变量。

出于安全考虑，**应避免使用命令行参数指定密码**。
请使用具有适当权限的配置文件。
====

.过程：升级使用自定义配置文件通过 Podman 部署 {productname} 容器
. 准备一个名为 `mgradm.yaml` 的配置文件，内容如下示例所示：
+
[source, yaml]
....
# Database password. Randomly generated by default
db:
  password: MySuperSecretDBPass

# Password for the CA certificate
ssl:
  password: MySuperSecretSSLPassword

# Your SUSE Customer Center credentials
scc: 
  user: ccUsername
  password: ccPassword

# Organization name
organization: YourOrganization

# Email address sending the notifications
emailFrom: notifications@example.com

# Administrators account details
admin:
  password: MySuperSecretAdminPass
  login: LoginName
  firstName: Admin
  lastName: Admin
  email: email@example.com
....

. 作为 root，从终端运行以下命令。
  输入您服务器的 FQDN 是可选的。
+
[source, shell]
----
mgradm -c mgradm.yaml install podman <FQDN>
----
+
[IMPORTANT]
====
您必须以 sudo 或 root 身份部署容器。
如果您错过此步骤，终端将显示以下错误。

[source, shell]
----
INF Setting up uyuni network
9:58AM INF Enabling system service
9:58AM FTL Failed to open /etc/systemd/system/uyuni-server.service for writing error="open /etc/systemd/system/uyuni-server.service: permission denied"
----
====

. 等待部署完成。

. 打开浏览器并访问您的服务器 FQDN 或 IP 地址。

//In this section you learned how to deploy an {productname} {productnumber} Server container using a custom YAML configuration.
