[[client-cfg-tools-repository]]
= 부트스트랩 리포지토리
:revdate: 2025-02-06
:page-revdate: {revdate}

부트스트랩 리포지토리에는 부트스트랩 중에 클라이언트를 등록하기 위한 필수 패키지가 포함되어 있습니다. 제품이 동기화되면 부트스트랩 리포지토리가 자동으로 생성되고 {productname} 서버에서 다시 생성됩니다.


== 부트스트랩 리포지토리 생성 준비


동기화를 위해 제품을 선택하면 모든 필수 채널이 완전히 미러링되자마자 부트스트랩 리포지토리가 자동으로 생성됩니다.

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]

ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]



== 자동 모드를 위한 옵션

자동 부트스트랩 리포지토리가 생성되는 방식을 변경할 수 있습니다. 이 섹션에서는 다양한 설정에 대해 자세히 설명합니다.

플러시 모드::
기본적으로 기존 리포지토리는 최신 패키지로만 업데이트됩니다. 대신, 빈 리포지토리로 항상 시작하도록 구성할 수 있습니다. 이 동작을 활성화하려면 다음과 같이 [path]``/etc/rhn/rhn.conf``에서 이 값을 추가하거나 편집합니다.
+
----
server.susemanager.bootstrap_repo_flush = 1
----

자동 모드::

기본적으로 부트스트랩 리포지토리 자동 재생성은 활성화되어 있습니다. 이 작업을 비활성화하려면 다음과 같이 [path]``/etc/rhn/rhn.conf``에서 이 값을 추가하거나 편집합니다.
+
----
server.susemanager.auto_generate_bootstrap_repo = 0
----



=== 부트스트랩 데이터 파일 구성

도구는 각 배포에 어떤 패키지가 필요한지에 대한 정보가 포함된 데이터 파일을 사용합니다. 이 데이터 파일은 [path]``/usr/share/susemanager/mgr_bootstrap_data.py``에 저장되어 있습니다. {suse}는 이 파일을 정기적으로 업데이트합니다. 이 파일을 변경하고 싶은 경우 직접 편집하지 마십시오. 대신, 다음과 같이 영구 디렉토리에 사본을 생성하고 이 사본을 편집합니다.

----
cp /usr/share/susemanager/mgr_bootstrap_data.py /srv/susemanager/my_data.py
----

변경을 완료했으면 새 파일을 사용하도록 {productname}를 구성합니다. 다음과 같이 [path]``/etc/rhn/rhn.conf``에서 이 값을 추가하거나 편집합니다.

----
server.susemanager.bootstrap_repo_datamodule = my_data
----

[IMPORTANT]
====
다음 업데이트에서 {suse}의 새 데이터는 새 데이터 파일이 아닌 원본 데이터 파일을 덮어씁니다. {suse}에서 제공하는 변경 사항으로 새 파일을 최신 상태로 유지해야 합니다.
====



== 부트스트랩 리포지토리를 수동으로 생성

기본적으로 부트스트랩 리포지토리는 매일 다시 생성됩니다. 명령 프롬프트에서 부트스트랩 리포지토리를 수동으로 생성할 수 있습니다.



.절차: {sle}용 부트스트랩 리포지토리 생성
[role=procedure]
_____

. {productname} 서버의 명령 프롬프트에서 루트 권한으로 다음과 같이 부트스트랩 리포지토리를 생성하는 데 사용 가능한 배포를 나열합니다.

+

----
mgr-create-bootstrap-repo -l
----

. 다음과 같이 적절한 리포지토리 이름을 제품 레이블로 사용해 부트스트랩 리포지토리를 생성합니다.

+

----
mgr-create-bootstrap-repo -c SLE-version-x86_64
----

+

. 또는 사용 가능한 배포 목록에서 배포 이름 옆에 표시된 번호를 사용합니다.

_____

클라이언트 리포지토리는 [path]``/srv/www/htdocs/pub/repositories/``에 있습니다.



제품을 두 개 이상 미러링한 경우(예: SLES, SAP용 SLES) 또는 사용자 지정 채널을 사용하는 경우 부트스트랩 리포지토리를 생성할 때 사용할 상위 채널을 지정해야 합니다. 이는 모든 상황에서 필수가 아닙니다. 예를 들어, 일부 SLES{nbsp}15 버전에는 공통 코드 기반이 있으므로, 상위 채널을 지정할 필요가 없습니다. 환경에서 필요한 경우에만 이 절차를 사용하십시오.



.선택 사항 절차: 부트스트랩 리포지토리에 상위 채널 지정
[role=procedure]
_____

. 사용 가능한 상위 채널을 확인합니다.

+

----
mgr-create-bootstrap-repo -c SLE-15-x86_64
여러 개의 상위 채널용 옵션을 찾았습니다. 
--with-parent-channel <label>옵션을 사용하고 다음 중 하나를 선택하십시오.
- sle-product-sles15-pool-x86_64
- sle-product-sles_sap15-pool-x86_64
- sle-product-sled15-pool-x86_64
----

. 다음과 같이 적절한 상위 채널을 지정합니다.

+

----
mgr-create-bootstrap-repo -c SLE-15-x86_64 --with-parent-channel sle-product-sled15-pool-x86_64
----

_____


=== 아키텍처가 여러 개인 리포지토리


아키텍처가 여러 개 포함된 부트스트랩 리포지토리를 생성하는 경우 모든 아키텍처가 올바르게 업데이트되는지 주의 깊게 살펴봐야 합니다. 예를 들어 {slea}용 {ibmz} 및 {x86_64} 아키텍처가 ``/srv/www/htdocs/pub/repositories/sle/15/2/bootstrap/``에서 동일한 부트스트랩 리포지토리 URL을 사용합니다.

``flush`` 옵션이 활성화된 상태에서 여러 아키텍처에 대해 부트스트랩 리포지토리를 생성하려고 하면 하나의 아키텍처만 생성됩니다. 이를 방지하려면 추가 아키텍처를 생성할 때 명령 프롬프트에서 ``--no-flush`` 옵션을 사용하십시오. 예:

----
mgr-create-bootstrap-repo -c SLE-15-SP2-x86_64
mgr-create-bootstrap-repo --no-flush -c SLE-15-SP2-s390x
----



== 부트스트랩 및 사용자 지정 채널

사용자 지정 채널을 사용 중인 경우 [option]``--with-custom-channels`` 옵션을 [command]``mgr-create-bootstrap-repo`` 명령과 함께 사용할 수 있습니다. 이 경우 사용할 상위 채널도 지정해야 합니다.

사용자 지정 채널을 사용 중인 경우 부트스트랩 리포지토리 자동 생성에 실패할 수 있습니다. 이러한 경우에는 리포지토리를 수동으로 생성해야 합니다.

사용자 지정 채널에 대한 자세한 내용은 xref:administration:custom-channels.adoc[]에서 참조하십시오.
