[[clients-oracle]]
= {oracle} 클라이언트 등록

이 섹션에는 {oracle} 운영 체제를 실행하는 기존 및 Salt 클라이언트를 등록하는 방법에 대한 정보가 포함되어 있습니다.

ifeval::[{suma-content} == true]
[IMPORTANT]
====
{oracle} 리포지토리 URL은 {scc}가 제공하지만 패키지 및 메타데이터는 {suse}가 아닌 Oracle이 제공합니다. {oracle} 기본 미디어 리포지토리는 https://yum.oracle.com/에서 무료로 다운로드할 수 있습니다.
====
endif::[]


[IMPORTANT]
====
기존 클라이언트는 {oracle}{nbsp}8에서 사용할 수 없습니다. {oracle}{nbsp}8 클라이언트는 Salt 클라이언트로만 지원됩니다.
====


== 소프트웨어 채널 추가

{oracle} 클라이언트를 {productname} 서버에 등록하기 전에 필요한 소프트웨어 채널을 추가하고 이 채널을 동기화해야 합니다.

ifeval::[{suma-content} == true]

이 절차에 필요한 제품은 다음과 같습니다.

[[oracle-channels-wizard]]
[cols="1,1", options="header"]
.Oracle 제품 - WebUI
|===
| OS 버전 | 제품 이름
| {oracle} 6 | Oracle Linux 6 x86_64
 | {oracle} 7 | Oracle Linux 7 x86_64
 | {oracle} 8 | Oracle Linux 8 x86_64
|===

include::snippets/addchannels_vendor_webui.adoc[]

또는 명령 프롬프트에서 채널을 추가할 수 있습니다. 이 절차에 필요한 채널은 다음과 같습니다.

[[oracle-channels-suma-cli]]
[cols="1,1", options="header"]
.Oracle 채널 - CLI
|===
| OS Version | Base Channel
| {oracle} 6 | oraclelinux6-x86_64
 | {oracle} 7 | oraclelinux7-x86_64
 | {oracle} 8 | oraclelinux8-x86_64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
이 절차에 필요한 채널은 다음과 같습니다.

[[oracle-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.Oracle 채널 - CLI
|===

| OS 버전
| 기본 채널
 | 클라이언트 채널
 | 업데이트 채널
 
 | {oracle} 6
 | oraclelinux6
 | oraclelinux6-uyuni-client
 | -
 
 | {oracle} 7
 | oraclelinux7
 | oraclelinux7-uyuni-client
 | -
 
 | {oracle} 8
 | oraclelinux8
 | oraclelinux8-uyuni-client
 | oraclelinux8-appstream

|===

include::snippets/addchannels_novendor_cli.adoc[]

[NOTE]
====
[command]``spacewalk-common-channels``가 제공하는 클라이언트 도구 채널은 {suse}가 아닌 {uyuni}가 공급합니다.
====

endif::[]

[IMPORTANT]
====
{oracle} 8 클라이언트의 경우 기본 채널과 AppStream 채널을 모두 추가하십시오. 사용자에게는 두 채널의 패키지가 모두 필요합니다. 두 채널을 모두 추가하지 않으면 패키지가 누락되어 부트스트랩 리포지토리를 생성할 수 없습니다.
====


include::snippets/appstream_admon.adoc[]



== 동기화 상태 확인

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== 활성화 키 생성

{oracle} 채널에 연결된 활성화 키를 생성해야 합니다.

활성화 키에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]를 참조하십시오.




== 클라이언트의 GPG 키 신뢰

include::snippets/trust_gpg.adoc[]




== 클라이언트 등록

{oracle} 클라이언트는 기타 모든 클라이언트와 동일한 방식으로 등록됩니다. 자세한 내용은 xref:client-configuration:registration-overview.adoc[]를 참조하십시오.


[WARNING]
====
{oracle}{nbsp}6 클라이언트를 등록하고 사용하려면 {productname} 서버가 이전 형식의 SSL 암호화를 지원하도록 구성해야 합니다. 이 오류를 해결하는 방법에 대한 자세한 내용은 xref:client-configuration:tshoot-clients.adoc[]에서 ``이전 클라이언트 등록``을 참조하십시오.
====
