[[clients-rh-cdn]]
= {rhel} 클라이언트를 CDN으로 등록
:revdate: 2026-03-17
:page-revdate: {revdate}


ifndef::backend-pdf[]
include::client-configuration:partial$rhel10_cpu_architecture_warning.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/rhel10_cpu_architecture_warning.adoc[]
endif::[]


ifeval::[{mlm-content} == true]

// SUSE Liberty Linux not available at Uyuni for now
{sleses}가 아닌 {rhel} 클라이언트를 직접 실행 중이라면 {redhat} 소스를 사용해 패키지를 검색하고 업데이트해야 합니다.
endif::[]

이 섹션에는 {rhel} 운영 체제를 실행하는 클라이언트를 등록하기 위해 {redhat} CDN(콘텐츠 전송 네트워크)을 사용하는 방법에 대한 정보가 포함되어 있습니다.

대신에 {redhat} 업데이트 인프라(RHUI) 사용법에 대한 정보는 xref:client-configuration:clients-rh-rhui.adoc[]를 참조하십시오.

[IMPORTANT]
====

ifeval::[{mlm-content} == true]

// SUSE Liberty Linux not available at Uyuni for now
{rhel} 클라이언트는 {redhat}을 기반으로 하며 {sleses}, RES 또는 {sles}와 관련이 없습니다.
endif::[]

{redhat} 기본 미디어 리포지토리 및 {rhela} 설치 미디어에 대한 액세스를 준비하고 {productname} 서버를 {redhat} 콘텐츠 전송 네트워크에 연결할 책임은 사용자에게 있습니다. 사용자는 모든 {rhela} 시스템과 관련하여 {redhat}의 지원을 받아야 합니다. 그렇지 않으면 {redhat}과의 약관을 위반하게 될 수 있습니다.
====

== 자격 및 인증서 임포트


{redhat} 클라이언트는 {redhat} 인증 주체(CA)와 자격 인증서 및 자격 키가 있어야 합니다.

자격 인증서에는 지원 구독 기간과 일치하는 만료일이 포함되어 있습니다. 중단을 방지하려면 지원 구독 기간이 종료되는 시점이 될 때마다 이 프로세스를 반복해야 합니다.

{redhat}은 구독 할당을 관리할 수 있도록 구독 관리자 도구를 제공합니다. 이 도구는 로컬로 실행되어 설치된 제품 및 구독을 추적합니다. 클라이언트는 구독 관리자로 등록되어 있어야 인증서를 취득할 수 있습니다.

{redhat} 클라이언트는 URL을 사용해 리포지토리를 복제합니다. URL은 {redhat} 클라이언트가 어디에 등록되었는지에 따라 달라집니다.

{redhat} 클라이언트는 다음 세 가지 방식으로 등록할 수 있습니다.

* redhat.com의 {redhat} 컨텐트 제공 네트워크(CDN)
* {redhat} Satellite 서버
* 클라우드의 {redhat} 업데이트 인프라(RHUI)

이 안내서에서는 {redhat} CDN에 등록된 클라이언트에 대해 설명합니다. CDN에 등록된 시스템이 최소 한 개 있어야 하고, 이와 함께 리포지토리 컨텐트에 대한 인증 구독이 있어야 합니다.

대신에 {redhat} 업데이트 인프라(RHUI) 사용법에 대한 정보는 xref:client-configuration:clients-rh-rhui.adoc[]를 참조하십시오.


[IMPORTANT]
====
클라이언트 시스템에 대한 Satellite 서버는 Satellite 서버 및 구독이 있어야 합니다. Satellite 인증서를 사용하는 클라이언트는 {productname} 서버에서 지원하지 않습니다.
====

[WARNING]
====
자격 인증서에는 지원 구독 기간과 일치하는 만료일이 포함되어 있습니다. 중단을 방지하려면 지원 구독 기간이 종료되는 시점이 될 때마다 이 프로세스를 반복해야 합니다.
====

{redhat}은 구독 할당을 관리할 수 있도록 구독 관리자 도구를 제공합니다. 이 도구는 클라이언트 시스템에서 로컬로 실행되어 설치된 제품 및 구독을 추적합니다. 구독 관리자로 redhat.com에 등록한 후, 이 절차에 따라 인증서를 취득하십시오.


.절차: 클라이언트를 구독 관리자에 등록

. 클라이언트 시스템의 명령 프롬프트에서 다음과 같이 구독 관리자 도구로 등록합니다.
+
----
subscription-manager register
----
+
프롬프트가 표시되면 {redhat} 포털 사용자 이름 및 비밀번호를 입력합니다.
. 다음 명령을 실행합니다.
+
----
subscription-manager activate
----
+
. 다음과 같이 클라이언트 시스템에서 {productname} 서버가 액세스할 수 있는 위치로 자격 인증서 및 키를 복사합니다.
+
----
cp /etc/pki/entitlement/ /<example>/entitlement/
----
+
[NOTE]
====
자격 인증서 및 키에는 [path]``.pem``이라는 파일 확장자가 있습니다. 또한 키는 파일 이름에 [path]``key``가 포함되어 있습니다.
====
+
. 다음과 같이 클라이언트 시스템에서 자격 인증서 및 키와 동일한 웹 위치로 {redhat} CA 인증서 파일을 복사합니다.
+
----
cp /etc/rhsm/ca/redhat-uep.pem /<example>/entitlement
----


{redhat} 클라이언트에서 리포지토리를 관리하려면 CA 및 자격 인증서를 {productname} 서버로 임포트해야 합니다. 이렇게 하려면 임포트 절차를 세 차례 수행하여 자격 인증서, 자격 키, {redhat} 인증서 각각에 대해 하나씩 세 항목을 생성해야 합니다.



.절차: 인증서를 서버에 임포트

. {productname} 서버 {webui}에서 menu:시스템[자동 설치 > GPG 및 SSL 키]로 이동합니다.
. btn:[저장된 키/인증서 생성]을 클릭하고 자격 인증서에 대해 다음 파라미터를 설정합니다.
* [guimenu]``설명`` 필드에 [systemitem]``Entitlement-Cert-date``를 입력합니다.
* [guimenu]``유형`` 필드에서 [systemitem]``SSL``을 선택합니다.
* [guimenu]``업로드할 파일을 선택해주십시오`` 필드에서 자격 인증서를 저장한 위치로 이동하여 [path]``.pem`` 인증서 파일을 선택합니다.
. btn:[키 생성]을 클릭합니다.
. btn:[저장된 키/인증서 생성]을 클릭하고 자격 키에 대해 다음 파라미터를 설정합니다.
* [guimenu]``설명`` 필드에 [systemitem]``Entitlement-key-date``를 입력합니다.
* [guimenu]``유형`` 필드에서 [systemitem]``SSL``을 선택합니다.
* [guimenu]``업로드할 파일을 선택해주십시오`` 필드에서 자격 키를 저장한 위치로 이동하여 [path]``.pem`` 키 파일을 선택합니다.
. btn:[키 생성]을 클릭합니다.
. btn:[저장된 키/인증서 생성]을 클릭하고 {redhat} 인증서에 대해 다음 파라미터를 설정합니다.
* [guimenu]``설명`` 필드에 [systemitem]``redhat-uep``를 입력합니다.
* [guimenu]``유형`` 필드에서 [systemitem]``SSL``을 선택합니다.
* [guimenu]``업로드할 파일을 선택해주십시오`` 필드에서 {redhat} 인증서를 저장한 위치로 이동하여 인증서 파일을 선택합니다.
. btn:[키 생성]을 클릭합니다.



== 소프트웨어 채널 추가

// 2022-04-21, ke:
// Section sequence according to https://github.com/uyuni-project/uyuni-docs/pull/1535

{redhat} 클라이언트를 {productname} 서버에 등록하기 전에 필요한 소프트웨어 채널을 추가하고 이 채널을 동기화해야 합니다.

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]

ifeval::[{mlm-content} == true]

{susemgr} 구독을 통해 사용자는 {sleses}용 도구 채널({redhat} Expanded Support 또는 RES라고도 함)을 이용할 수 있는 자격을 얻게 됩니다. 사용자는 클라이언트 도구 채널을 사용해 부트스트랩 리포지토리를 생성해야 합니다. 이 절차는 Salt 클라이언트에 적용됩니다.
endif::[]

ifeval::[{mlm-content} == true]

이 절차에 필요한 제품은 다음과 같습니다.

// SUSE Liberty Linux not available at Uyuni for now
[[redhat-channels-wizard]]
[cols="1,1", options="header"]
.Red Hat 제품 - WebUI
|===

ifeval::[{mlm-content} == true]
| OS Version  | Product Name
| {redhat} 10 | RHEL and Liberty 10 Base
| {redhat} 9  | RHEL and Liberty 9 Base
| {redhat} 8  | RHEL or SLES ES or CentOS 8 Base
| {redhat} 7  | RHEL7 Base x86_64
endif::[]

ifeval::[{uyuni-content} == true]
| OS Version | Product Name | {redhat} 10 | RHEL 10 | {redhat} 9 | RHEL | {redhat} 8 | RHEL or CentOS 8 Base | {redhat} 7 | RHEL7 Base x86_64
endif::[]

|===


ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]


endif::[]

ifeval::[{uyuni-content} == true]

이 절차에 필요한 채널은 다음과 같습니다.

[[redhat-channels-cli]]
[cols="1,1,1,1", options="header"]
.Red Hat 채널- CLI
|===

| OS Version
| Base Channel
| Client Channel
| Tools Channel
| {redhat} 10
| rhel10-pool-uyuni
| -
| rhel10-uyuni-client
| {redhat} 9
| rhel9-pool-uyuni
| -
| rhel9-uyuni-client

| {redhat} 8
| rhel8-pool-uyuni
| -
| rhel8-uyuni-client

| {redhat} 7
| rhel7-pool-uyuni
| -
| rhel7-uyuni-client

|===


ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli_multiarch.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli_multiarch.adoc[]
endif::[]


[NOTE]
====
[command]``spacewalk-common-channels``가 제공하는 클라이언트 도구 채널은 {suse}가 아닌 {uyuni}가 공급합니다.
====

endif::[]


== 사용자 정의 리포지토리 및 채널 준비

{redhat} CDN에서 소프트웨어를 미러링하려면 URL로 CDN에 링크된 사용자 정의 채널 및 리포지토리를 {productname}에 생성해야 합니다. 이 작업을 올바르게 수행하려면 {redhat} 포털에 이러한 제품에 대한 자격이 있어야 합니다. 미러링하려는 리포지토리의 URL은 다음과 같이 구독 관리자 도구를 사용해 가져올 수 있습니다.

----
subscription-manager repos
----

이 리포지토리 URL을 사용해 사용자 정의 리포지토리를 생성할 수 있습니다. 이렇게 하면 클라이언트를 관리하는 데 필요한 컨텐트만 미러링할 수 있습니다.

[IMPORTANT]
====
{redhat} 포털에 올바른 자격이 있는 경우 {redhat} 리포지토리의 사용자 정의 버전만 생성할 수 있습니다.
====


이 절차에 필요한 상세 정보는 다음과 같습니다.

[[redhat-repos-manual]]
[cols="1,1", options="header"]
.Red Hat 사용자 정의 리포지토리 설정
|===

| 옵션                 | 설정
| 리포지토리 URL         | {redhat} CDN이 제공하는 컨텐트 URL
 | 서명 메타데이터가 있습니까?   | 모든 {redhat} Enterprise 리포지토리를 선택 취소
 | SSL CA 인증서     | [systemitem]``redhat-uep``
 | SSL 클라이언트 인증서 | [systemitem]``Entitlement-Cert-date``
 | SSL 클라이언트 키         | ``Entitlement-Key-date``
|===


ifndef::backend-pdf[]
include::client-configuration:partial$manual_repos.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_repos.adoc[]
endif::[]



이 절차에 필요한 채널은 다음과 같습니다.

[[redhat-channels-custom]]

ifeval::[{mlm-content} == true]
[cols="1,1,1", options="header"]
.Red Hat 사용자 정의 채널
|===

| OS Version  | Base Product                     | Base Channel
| {redhat} 10 | RHEL and Liberty 10 Base         | el10-pool-x86_64
| {redhat} 9  | RHEL and Liberty 9 Base          | el9-pool-x86_64
// SUSE Liberty Linux not available at Uyuni for now
| {redhat} 8  | RHEL or SLES ES or CentOS 8 Base | rhel8-pool-x86_64
| {redhat} 7  | RHEL7 Base x86_64                | rhel7-pool-x86_64

|===
endif::[]

// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{uyuni-content} == true]
[cols="1,1", options="header"]
.Red Hat 사용자 정의 채널
|===

| OS Version  | Base Channel
| {redhat} 10 | rhel10-pool-uyuni
| {redhat} 9  | rhel9-pool-uyuni
| {redhat} 8  | rhel8-pool-uyuni
| {redhat} 7  | rhel7-pool-uyuni

|===
endif::[]


ifndef::backend-pdf[]
include::client-configuration:partial$manual_channels.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_channels.adoc[]
endif::[]

[IMPORTANT]
====
For {redhat} 10, {redhat} 9 and {redhat} 8 clients, add both the Base and AppStream channels. You require packages from both channels. If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====

모듈형 채널을 사용하는 경우 클라이언트에서 Python 3.6 모듈 스트림을 활성화해야 합니다.Python 3.6이 제공되지 않으면 [package]``spacecmd`` 패키지의 설치가 실패합니다.

ifndef::backend-pdf[]
include::client-configuration:partial$manual_associate.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_associate.adoc[]
endif::[]



== 동기화 상태 확인

ifeval::[{mlm-content} == true]


ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]


endif::[]

ifeval::[{uyuni-content} == true]


ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]


endif::[]


ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]


[NOTE]
====
{rhel} 채널은 규모가 매우 클 수 있습니다. 일부 경우 동기화에 몇 시간이 걸릴 수 있습니다.
====


.절차: 옵션: Salt 상태를 생성하여 구성 파일 배포

. {productname} 서버 {webui}에서 menu:구성[채널]로 이동합니다.
. btn:[상태 채널 생성]을 클릭합니다.
* [guimenu]``이름`` 필드에 [systemitem]``subscription-manager: disable yum plugins``를 입력합니다.
* [guimenu]``레이블`` 필드에 [systemitem]``subscription-manager-disable-yum-plugins``를 입력합니다.
* [guimenu]``설명`` 필드에 [systemitem]``subscription-manager: disable yum plugins``를 입력합니다.
* [guimenu]``SLS 컨텐트`` 필드를 빈 상태로 둡니다.
. btn:[구성 채널 생성]을 클릭합니다.
. btn:[구성 파일 생성]을 클릭합니다.
* [guimenu]``파일 이름/경로`` 필드에 [systemitem]``/etc/yum/pluginconf.d/subscription-manager.conf``를 입력합니다.
* [guimenu]``파일 내용`` 필드에 다음과 같이 입력합니다.
+
----
[main]
enabled=0
----
. btn:[구성 파일 생성]을 클릭합니다.
. [guimenu]``Salt 파일 시스템 경로`` 필드의 값을 적어 둡니다.
. 구성 채널의 이름을 클릭합니다.
. [guimenu]``'init.sls' 파일 보기/편집``을 클릭합니다.
* [guimenu]``파일 내용`` 필드에 다음과 같이 입력합니다.
+
----
configure_subscription-manager-disable-yum-plugins:
  cmd.run:
     - name: subscription-manager config --rhsm.auto_enable_yum_plugins=0
     - watch:
       - file: /etc/yum/pluginconf.d/subscription-manager.conf
   file.managed:
     - name: /etc/yum/pluginconf.d/subscription-manager.conf
     - source: salt:///etc/yum/pluginconf.d/subscription-manager.conf
----
. btn:[구성 파일 업데이트]를 클릭합니다.


[NOTE]
====
``구성 파일을 배포할 Salt 상태 생성`` 절차는 선택 사항입니다.
====


.절차: {rhel} 클라이언트에 대해 시스템 그룹 생성

. {productname} 서버 {webui}에서 menu:시스템[시스템 그룹]으로 이동합니다.
. btn:[그룹 생성]을 클릭합니다.
* [guimenu]``이름`` 필드에 [systemitem]``rhel-systems``라고 입력합니다.
* [guimenu]``설명`` 필드에 [systemitem]``모든 RHEL 시스템``이라고 입력합니다.
. btn:[그룹 생성]을 클릭합니다.
. [guimenu]``상태`` 탭을 클릭합니다.
. [guimenu]``구성 채널`` 탭을 클릭합니다.
. 검색 상자에 [systemitem]``subscription-manager: disable yum plugins``라고 입력합니다.
. btn:[검색]을 클릭하여 상태를 확인합니다.
. [systemitem]``할당`` 열에서 상태의 확인란을 클릭합니다.
. btn:[변경 사항 저장]을 클릭합니다.
. btn:[확인]을 클릭합니다.

RHEL 시스템을 {productname}에 이미 추가했다면 새 시스템 그룹에 할당하고 Highstat를 적용합니다.



.절차: 시스템 그룹을 활성화 키에 추가

위에서 생성한 시스템 그룹을 포함하려면 RHEL 시스템에 사용한 활성화 키를 수정해야 합니다.

. {productname} 서버 {webui}에서 menu:시스템[활성화 키]로 이동합니다.
. RHEL 시스템에 사용한 각 활성화 키를 클릭하고 다음과 같이 합니다.
. [guimenu]``그룹`` 탭의 [guimenu]``조인`` 하위 탭으로 이동합니다.
. [systemitem]``rhel-systems 선택``의 확인란을 선택합니다.
. btn:[선택한 그룹 조인]을 클릭합니다.


== GPG 키 관리

클라이언트는 소프트웨어 패키지가 설치되기 전에 GPG 키를 사용해 신뢰성을 확인합니다. 신뢰할 수 있는 소프트웨어만 클라이언트에 설치할 수 있습니다.

[IMPORTANT]
====
클라이언트의 보안을 위해 GPG 키를 신뢰하는 것이 중요합니다. 어떤 키가 필요하고 신뢰할 수 있는지 결정하는 것은 관리자가 수행해야 하는 작업입니다. GPG 키를 신뢰할 수 없는 경우 소프트웨어 채널을 사용할 수 없기 때문에 채널을 클라이언트에 할당하는 결정은 키를 신뢰하는 결정에 따라 달라집니다.
====

GPG 키에 대한 자세한 내용은 xref:client-configuration:gpg-keys.adoc[]에서 확인할 수 있습니다.

[NOTE]
====
{redhat} 사용자 정의 채널의 경우, [guimenu]``GPG 확인 활성화`` 필드를 확인하려면 [guimenu]``GPG 키 URL`` 필드를 채워야 합니다. {redhat} 미니언의 [systemitem]``/etc/pki/rpm-gpg`` 디렉토리에 저장된 GPG 키의 파일 URL을 사용할 수 있습니다.

예: [systemitem]``file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release``

{redhat} 제품 서명 키의 전체 목록은 https://access.redhat.com/security/team/key[]를 참조하십시오.
====


== 클라이언트 등록

ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]
