[[clients-sleses]]
= {sleses} 클라이언트 등록

이 섹션에는 {sleses}({es}) 운영 체제를 실행하는 기존 및 Salt 클라이언트를 등록하는 방법에 대한 정보가 포함되어 있습니다. {es} 클라이언트는 {rhel} 또는 {centos}에 기반을 두고 있으며 SLESES, RES 또는 {redhat} {es}라고도 합니다.

{suse}가 제공하는 {es} 소프트웨어 채널은 패키지에 대한 업데이트만 제공하고 패키지 자체는 제공하지 않습니다. {es} 클라이언트를 등록하려면 {productname} 서버에서 비어 있는 사용자 정의 기본 및 하위 채널을 생성한 다음, {redhat} 또는 {centos} 패키지를 사용자 정의 채널로 임포트해야 합니다. 초기 패키지를 {redhat} 또는 {centos}에서 직접 가져와야 {es} 소프트웨어 채널이 제공하는 업데이트를 적용할 수 있습니다.


[IMPORTANT]
====
사용자는 {redhat} 또는 {centos} 기본 미디어 리포지토리 및 설치 미디어에 대한 액세스를 정렬할 책임이 있습니다.
====


ifeval::[{suma-content} == true]
[IMPORTANT]
====
사용자는 모든 {es} 시스템에 대해 {suse}의 지원을 받아야 합니다.
====
endif::[]


ifeval::[{uyuni-content} == true]
[IMPORTANT]
====
{suse}는 {uyuni}에서 {es} 시스템에 대한 지원을 제공하지 않습니다.
====
endif::[]


[IMPORTANT]
====
기존 클라이언트는 {es}{nbsp}8에서 사용할 수 없습니다. {es}{nbsp}8 클라이언트는 Salt 클라이언트로만 지원됩니다.
====



== 소프트웨어 채널 추가


{es} 클라이언트의 경우 일부 필수 패키지는 {rhel} 또는 {centos} 설치 미디어에 포함되어 있습니다. 먼저 이 패키지를 설치해야 {es} 클라이언트를 등록할 수 있습니다.

{es} 제품은 {scc}가 제공합니다. 이 제품은 클라이언트 도구 패키지도 포함합니다.

{es} 클라이언트를 {productname} 서버에 등록하기 전에 필요한 소프트웨어 채널을 추가하고 이 채널을 동기화해야 합니다.

하나는 {es}용으로, 다른 하나는 클라이언트 도구용으로 두 가지 채널 세트를 선택해야 합니다.

올바른 {es} 채널과 연결된 활성화 키가 필요합니다. 활성화 키에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]를 참조하십시오.

ifeval::[{suma-content} == true]

이 절차에 필요한 제품은 다음과 같습니다.

[[es-channels-wizard]]
[cols="1,1", options="header"]
.ES 제품 - WebUI
|===

| OS 버전
| 제품 이름
 
 | {es} 6
 | SUSE Linux Enterprise Server with Expanded Support 6 x86_64
 
 | {es} 7
 | SUSE Linux Enterprise Server with Expanded Support 7 x86_64
 
 | {es} 8
 | RHEL 또는 SLES ES 또는 CentOS 8 기본 및 SUSE Linux Enterprise Server with Expanded Support 8 x86_64

|===

{productname}에는 추가 소프트웨어가 포함된 도구 채널이 필요합니다. 이 절차에서는 이러한 도구 채널을 생성합니다.

[[es-channels-tools]]
[cols="1,1,1", options="header"]
.ES 도구 채널
|===
| OS 버전 | 기본 채널                     | 도구 채널
| {es} 6     | RHEL Expanded Support 6          | RES6-SUSE-Manager-Tools  x86_64
 | {es} 7     | RHEL Expanded Support 7          | RES7-SUSE-Manager-Tools  x86_64
 | {es} 8     | RHEL 또는 SLES ES 또는 CentOS 8 기본 | x86_64용 RES8-Manager-Tools-Pool 및 x86_64용 RES8-Manager-Tools-Updates
|===

include::snippets/addchannels_vendor_webui.adoc[]


endif::[]


ifeval::[{uyuni-content} == true]
이 절차에 필요한 채널은 다음과 같습니다.

[[es-channels-cli]]
[cols="1,1,1,1", options="header"]
.ES 채널 - CLI
|===

| OS 버전
| 기본 채널
 | 클라이언트 채널
 | 도구 채널
 
 | {es} 6
 | rhel-x86_64-server-6
 | -
 | res6-suse-manager-tools-x86_64
 
 | {es} 7
 | rhel-x86_64-server-7
 | -
 | res7-suse-manager-tools-x86_64
 
 | {es} 8
 | rhel-x86_64-server-8
 | -
 | res8-suse-manager-tools-x86_64

|===

include::snippets/addchannels_novendor_cli.adoc[]

endif::[]


include::snippets/appstream_admon.adoc[]



=== 기본 미디어 추가

{suse}가 {rhel} 또는 {centos} 기본 미디어를 제공하지 않으므로 기본 {es} 채널에는 패키지가 전혀 포함되어 있지 않습니다. {es} 상위 채널에 하위 채널로 추가할 수 있는 {redhat} 또는 {centos}의 기본 미디어를 가져와야 합니다. 필요한 모든 패키지가 있는지 확인하려면 최소 또는 {jeos} 이미지가 아닌 전체 DVD 이미지를 사용하십시오.

{productname} 사용자 정의 채널을 사용해 {rhel} 또는 {centos} 미디어를 설정할 수 있습니다. 기본 미디어의 모든 패키지는 하위 채널로 미러링해야 합니다.

채널의 이름을 자유롭게 선택할 수 있습니다.

include::snippets/manual_channels.adoc[]


[IMPORTANT]
====
{redhat} 8 클라이언트의 경우 기본 채널과 AppStream 채널을 모두 추가하십시오. 사용자에게는 두 채널의 패키지가 모두 필요합니다. 두 채널을 모두 추가하지 않으면 패키지가 누락되어 부트스트랩 리포지토리를 생성할 수 없습니다.
====


.절차: 기본 미디어를 사용자 정의 채널에 추가
. {productname} 서버의 명령 프롬프트에서 루트 권한으로 기본 미디어 이미지를 [path]``/tmp/`` 디렉토리로 복사합니다.
. 미디어 컨텐트를 포함할 디렉토리를 생성합니다.
    다음과 같이 [command]``<os_name>``을 ``sleses6``, ``sleses7`` 또는 ``sleses8``으로 교체합니다.
+
----
mkdir -p /srv/www/htdocs/pub/<os_name>
----
. 다음과 같이 이미지를 마운트합니다.
+
----
mount -o loop /tmp/<iso_filename> /srv/www/htdocs/pub/<os_name>
----
. 다음과 같이 패키지를 앞서 생성한 하위 채널로 임포트합니다.
+
----
spacewalk-repo-sync -c <channel-label> -u file:///srv/www/htdocs/pub/<os_name>/<repopath>/
----


==== 옵션: 컨텐트 URL에서 기본 미디어 추가

또는 {redhat} CDN이나 {centos}가 제공하는 컨텐트 URL에 대한 액세스 권한이 있는 경우 사용자 정의 리포지토리를 생성하여 패키지를 미러링할 수 있습니다.

이 절차에 필요한 상세 정보는 다음과 같습니다.

[[es-repos-manual]]
[cols="1,1", options="header"]
.ES 사용자 정의 리포지토리 설정
|===
| 옵션                 | 파라미터
| 리포지토리 URL         | {redhat} CDN 또는 {centos}
가 제공하는 컨텐트 URL | 서명 메타데이터가 있습니까?   | 모든 {redhat} Enterprise 리포지토리를 선택 취소
 | SSL CA 인증서     | [systemitem]``redhat-uep`` ({redhat}만 해당됨)
 | SSL 클라이언트 인증서 | [systemitem]``Entitlement-Cert-date``({redhat}만 해당됨)
 | SSL 클라이언트 키         | ``Entitlement-Key-date``({redhat}만 해당됨)
|===

include::snippets/manual_repos.adoc[]

include::snippets/manual_associate.adoc[]

== 동기화 상태 확인

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[NOTE]
====
{es} 채널은 규모가 매우 클 수 있습니다. 초기 채널 동기화는 때로 몇 시간이 걸릴 수 있습니다.

초기 동기화가 완료되면 채널로 작업하기 전에 채널을 복제하는 것이 좋습니다. 이렇게 하면 원본 동기화 데이터를 백업할 수 있습니다.
====



== {es} 클라이언트 등록

이제 {es} 클라이언트가 등록할 준비가 되었습니다.

클라이언트 등록에 대한 자세한 내용은 xref:client-configuration:registration-overview.adoc[]를 참조하십시오.


[WARNING]
====
{sleses}{nbsp}6 클라이언트를 등록하고 사용하려면 {productname} 서버가 이전 형식의 SSL 암호화를 지원하도록 구성해야 합니다. 이 오류를 해결하는 방법에 대한 자세한 내용은 xref:client-configuration:tshoot-clients.adoc[]에서 ``이전 클라이언트 등록``을 참조하십시오.
====
