[[clients-pubcloud]]
= Registering clients on a public cloud

When you have your {productname} Server set up, you are ready to start registering clients.



== Prepare on-demand images

An instance started from an on-demand image provided by {suse} is automatically registered, and the update infrastructure and {sle} modules are activated. To use your on-demand image as a {productname} client, you need to disable this automation before you begin.



.Procedure: Preparing on-demand images
. Log in to the on-demand instance.
. At the command prompt, as root, remove the registration data and repositories:
+
----
registercloudguest --clean
----
. Remove the ``cloud-regionsrv-client`` package:
+
----
zypper rm cloud-regionsrv-client
----
. Remove additional packages specific to your cloud provider:
+
* Amazon EC2:
+
----
zypper rm regionServiceClientConfigEC2 regionServiceCertsEC2
----
+
* Google Compute Engine:
+
----
zypper rm cloud-regionsrv-client-plugin-gce regionServiceClientConfigGCE regionServiceCertsGCE
----
+
* Microsoft Azure:
+
----
zypper rm regionServiceClientConfigAzure regionServiceCertsAzure
----

For instructions on registering {productname} to {scc}, see xref:installation:server-setup.adoc[].



== Register clients

In the {productname} {webui}, navigate to menu:Systems[Bootstrapping], then fill in the ``Host``, ``SSH Port``, ``User``, and ``Password`` fields. Make sure you use stable FQDNs for the ``Host`` field, or {productname} cannot find your host when your Public Cloud gives you a different short-lived FQDNS.

[NOTE]
====
기존 클라이언트를 부트스트랩하려면 클라이언트에 로그인한 상태에서 서버의 호스트 이름을 확인할 수 있는지 확인하십시오. 서버의 FQDN을 클라이언트의 [path]``/etc/hosts`` 로컬 확인 파일에 추가해야 할 수도 있습니다. 서버의 로컬 IP 주소가 포함된 [command]``hostname -f`` 명령을 사용하여 확인할 수 있습니다.
====

Public cloud images usually do not allow SSH login with username and password, but only SSH with a certificate. If you want to use bootstrap from the {webui}, you need to enable SSH login with username and SSH key. You can do this by navigating to menu:Systems[Bootstrapping] and changing the authentication method.

If your cloud provider is Microsoft Azure, you can log in with username and password. To do this, you need to allow the AzureUser to run commands as root without a password. To do this, open the [path]``/etc/sudoers.d/waagent`` file, and add or edit this line:

----
AzureUser ALL=(ALL) NOPASSWD: ALL
----

[WARNING]
====
Allowing the AzureUser to run commands as root without a password carries a security risk. Use this method for testing only. Do not do this for production systems.
====

When the bootstrap process has completed successfully, your client is listed at menu:Systems[System List].

* If you want more control over the process, have to register many clients, or are registering traditional clients, create a bootstrap script. For more information, see xref:client-configuration:registration-bootstrap.adoc[].
* For Salt clients and even more control over the process, executing single commands on the command line can be useful. For more information, see xref:client-configuration:registration-cli.adoc[].
* If you are attempting to register clients that are cloned from each other, you need to do some extra configuration to prevent them from over-writing each other. For more information about registering clones, see xref:administration:tshoot-registerclones.adoc[].



== Activation keys

활성화 키는 기존 및 Salt 클라이언트에서 클라이언트가 올바른 소프트웨어 자격이 있는지, 적절한 채널에 연결하고 있는지, 관련 그룹에 가입되어 있는지 확인하는 데 사용됩니다. 각 활성화 키는 조직에 구속되며 키를 생성할 때 설정할 수 있습니다.

For more on activation keys, see xref:client-configuration:activation-keys.adoc[].
