[[client-upgrades-clm]]
= 컨텐트 라이프싸이클 관리자를 사용하여 업그레이드

관리할 {sles} 클라이언트가 많은 경우 컨텐트 라이프싸이클 관리자를 사용하여 현재 위치에 업그레이드를 자동화할 수 있습니다.



== 업그레이드 준비

클라이언트를 업그레이드하려면 먼저 다음과 같은 준비 작업을 마쳐야 합니다.

* 컨텐트 라이프싸이클 프로젝트 생성
* 활성화 키 생성
* Create an autoinstallable distribution
* 자동 설치 프로파일 생성

.절차: 컨텐트 라이프싸이클 프로젝트 생성
. 배포를 위한 컨텐트 라이프싸이클 프로젝트를 생성합니다.
    자세한 내용은 xref:administration:content-lifecycle.adoc[]을 참조하십시오.
. 프로젝트에 대해 설명하는 짧은 이름을 선택해야 합니다.
. 배포에 필요한 모든 소스 채널 모듈을 포함합니다.
. 필요에 따라 필터를 추가하고 하나 이상의 환경을 설정합니다.



.절차: 활성화 키 생성
. 배포를 위한 활성화 키를 생성합니다.
    자세한 내용은 xref:client-configuration:activation-keys.adoc[]를 참조하십시오.
. 활성화 키에 필터링된 프로젝트 채널이 모두 포함되어 있어야 합니다.



.절차: 자동 설치 가능한 배포 생성
. Create an autoinstallable distribution for every base channel you want to migrate.
    For more information, see xref:client-configuration:autoinst-distributions.adoc[].
. 컨텐트 라이프싸이클 프로젝트의 이름을 참조하는 레이블을 배포에 지정합니다.
. ``설치 프로그램 생성`` 필드에서 사용 중인 SLES 버전을 선택합니다.



.절차: 자동 설치 프로파일 생성
. 업그레이드하여 도달하려는 모든 대상 배포 및 서비스 팩에 대해 자동 설치 프로파일을 생성합니다.
    For more information, see xref:client-configuration:autoinst-profiles.adoc[].
. Salt 및 기존 클라이언트에 대해 다른 프로파일을 생성해야 합니다.
. 프로파일의 변수를 사용해 다양한 라이프싸이클 환경을 구별할 수 있습니다.


자동 설치 프로파일의 예는 https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST를 참조하십시오.

현재 위치에 업그레이드를 자동화하기 위해 자동 설치 프로파일에서 다음 변수를 사용하십시오.



.예: 자동 설치 프로파일에서 사용할 변수
----
registration_key=1-15sp1-demo-test
org=1
 channel_prefix=15sp1-demo-test
 distro_label=15sp1-demo-test
----



.예: 자동 설치 프로파일에서 사용할 항목
----
 <listentry>
     <ask_on_error config:type=\boolean\>true</ask_on_error>
       <media_url>https://$redhat_management_server/ks/dist/child/$channel_prefix-sle-module-web-scripting15-sp1-pool-x86_64/$distro_label</media_url>
      <name>$channel_prefix SLE-Module-Web-Scripting15-SP1 X86_64용 풀  </name>
      <product>웹 스크립팅 모듈 15 SP1 x86_64 풀</product>
 </listentry>
----



== 업그레이드


업그레이드를 위해 서버 준비를 완료했으면 이제 클라이언트를 조달할 수 있습니다.



.절차: 클라이언트 조달
. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 조달할 클라이언트를 선택하고 선택한 클라이언트에 시스템 세트 관리자를 추가합니다.
. menu:시스템[시스템 세트 관리자 > 개요]로 이동하여 [guimenu]``조달`` 탭을 클릭합니다.
. 사용할 자동 설치 프로파일을 선택합니다.


PXE를 사용할 수 있는 클라이언트의 경우 마이그레이션은 클라이언트를 조달하자마자 자동화됩니다. 기타 모든 클라이언트의 경우에는 Cobbler를 사용해 업그레이드를 수행할 수 있습니다.



.절차: Cobbler를 사용한 클라이언트 업그레이드
. 다음과 같이 명령 프롬프트에서 루트 권한으로 사용 가능한 Cobbler 프로파일을 확인합니다.
+
----
cobbler profile list
----
. 다음과 같이 선택한 프로파일로 ISO 파일을 빌드합니다.
+
----
cobbler buildiso --iso=/tmp/SLE_15-sp1.iso --profiles=SLE_15-sp1:1:Example
----

For more information about using CD-ROMs to provision clients, see xref:client-configuration:autoinst-cdrom.adoc[].
