[[client-upgrades-uyuni]]
= Uyuni 클라이언트 업그레이드
:revdate: 2025-02-26
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

이 섹션에서는 openSUSE Leap을 예로 사용합니다.

== 업그레이드 준비


.절차: 클라이언트 업그레이드 준비
. {productname} 서버의 명령 프롬프트에서 루트 권한으로 [command]``spacewalk-common-channels`` 명령을 사용해 적절한 채널을 추가합니다.
+
----
spacewalk-common-channels \
opensuse_leap15_4 \
opensuse_leap15_4-non-oss \
opensuse_leap15_4-non-oss-updates \
opensuse_leap15_4-updates \
opensuse_leap15_4-uyuni-client
----

. [command]``spacewalk-repo-sync``로 모든 채널을 완전히 동기화합니다.
+
// These are custom channels.
// For more information, see xref:client-configuration:clients-opensuse.adoc[].

. {productname} 서버 {webui}에서 menu:소프트웨어[관리 > 채널]로 이동하여 이름이 [systemitem]`` Uyuni Client Tools for openSUSE Leap 15.4(x86_64)``인 채널을 클릭합니다.

. 오른쪽 상단에서 btn:[채널 관리]를 클릭합니다.

. [guimenu]``리포지토리`` 탭을 클릭하고 [systemitem]``외부 - openSUSE Leap 15.3(x86_64)용 Uyuni 클라이언트 도구``를 선택합니다.

. btn:[리포지토리 업데이트]를 클릭합니다.

. menu:리포지토리[동기화] 하위 탭으로 이동하여 btn:[지금 동기화]를 클릭합니다.

. [systemitem]``openSUSE Leap 15.4(x86_64)`` 및 [systemitem]``외부 - openSUSE Leap 15.3(x86_64)``에 대해서도 동일한 작업을 합니다.

[systemitem]``openSUSE Leap 15.4(x86_64)``를 펼쳐 패키지로 채워져 있는 모든 하위 채널을 표시합니다.



== 업그레이드

클라이언트를 업그레이드하려면 소프트웨어 리포지토리를 교체하고 소프트웨어를 업데이트한 후 끝으로 클라이언트를 재부팅하십시오.



.절차: 클라이언트 업그레이드

. {productname} 서버 {webui}에서 menu:시스템[]으로 이동하여 클라이언트의 이름을 클릭합니다.
. menu:소프트웨어[소프트웨어 채널]을 클릭하고 [systemitem]``Customs Channels`` 목록에 나열된 openSUSE Leap {opensuse-version} 채널을 기본 채널로 선택합니다.
. [guimenu]``하위 채널`` 창에서 {opensuse-version} 하위 채널을 선택합니다.
. btn:[다음]을 클릭하고 [guimenu]``소프트웨어 채널 변경 확인``에서 btn:[확인]을 클릭합니다.
. menu:소프트웨어[패키지 > 업그레이드]를 클릭하고 클라이언트에서 업데이트할 패키지를 모두 선택한 다음, 선택을 적용합니다. btn:[패키지 업그레이드]를 클릭하고, 상세 정보를 확인한 후 btn:[확인]을 클릭하여 업데이트를 완료합니다.
. 클라이언트를 재부팅합니다.

여러 클라이언트를 업데이트해야 하는 경우 {productname} 서버에서 이 명령 시퀀스의 작업 체인을 생성하면 됩니다. 이 작업 체인을 사용해 여러 클라이언트에서 업데이트를 동시에 수행할 수 있습니다.


////
. Assign the new channels to the clients instead of the old channels.

. Update all the packages.  This can either be done with the {webui} or better run [command]``zypper dup`` manually on the command line local on the systems or remotely as a Salt command.
////

////
I think the better way to document this is if giving it a try. Create an Uyuni server, sync Leap 15.1 (spacewalk-common-channels), create a Leap 15.1, onboard it, sync Leap 15.2 (spacewalk-common-channels), and then try to adjust the channels and trying to upgrade. I recommend you use VMs and take snapshots of the VMs so you can repeat steps as needed.
////

////
But for now you need to create and mirror at least the target channels with spacewalk-common-channels.

You adjust the channels for the client and best is to call "zypper dup". Either from the commandline on that system or using remote command.
////
