[[clients-rh-rhui]]
= RHUI를 사용하여 {rhel} 클라이언트 등록
:revdate: 2026-03-17
:page-revdate: {revdate}

// SUSE Liberty Linux not available at Uyuni for now

// 2024-04-04 OM: It had been decided in the conversation with the mlm PO 
// that this Public Cloud related file can stay in the Uyuni books


이 섹션에는 {rhel} 운영 체제를 실행하는 클라이언트를 등록하기 위해 {redhat} RHUI(업데이트 인프라)를 사용하는 방법에 대한 정보가 포함되어 있습니다.

ifndef::backend-pdf[]
include::client-configuration:partial$rhel10_cpu_architecture_warning.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/rhel10_cpu_architecture_warning.adoc[]
endif::[]

ifeval::[{mlm-content} == true]

{sleses}가 아닌 {rhel} 클라이언트를 직접 실행 중이라면 Red Hat 소스를 사용해 패키지를 검색하고 업데이트해야 합니다.
endif::[]

Amazon EC2와 같은 공용 클라우드에서 클라이언트를 실행하는 경우 이 방법을 사용합니다.

RHUI를 {redhat} 컨텐트 제공 네트워크(CDN)와 함께 사용하여 {rhel} 구독을 관리할 수 있습니다. {redhat} CDN 사용에 대한 정보는 xref:client-configuration:clients-rh-cdn.adoc[]을 참조하십시오.

[IMPORTANT]
====

// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{mlm-content} == true]

{rhel} 클라이언트는 {redhat}을 기반으로 하며 {sleses}, RES 또는 {sles}와 관련이 없습니다.
endif::[]

사용자는 {productname} 서버를 {redhat} 업데이트 인프라에 연결할 책임이 있습니다. 이 RHUI 인증서를 사용해 업데이트를 가져오는 모든 클라이언트는 올바른 라이선스를 보유해야 합니다. 자세한 내용은 해당 클라우드 공급자에게 문의하거나 {redhat} 서비스 약관을 확인하시기 바랍니다.
====

[NOTE]
====
RHUI로 등록한 {rhel} 클라이언트가 켜져 있지 않은 경우 {redhat}은 인증서가 잘못되었다고 선언할 수 있습니다. 이 경우 클라이언트를 다시 켜거나 새 RHUI 인증서를 가져와야 합니다.
====



== 자격 및 인증서 임포트


이전에는 인증서 및 자격 데이터 설명서를 {productname} 서버로 임포트해야 했습니다. 이 작업은 SUSE {payg} 인스턴스와 동일한 메커니즘을 사용하여 자동화되었습니다. 자세한 내용은 xref:specialized-guides:public-cloud-guide/payg/payg-overview.adoc[]에서 확인할 수 있습니다.

이 안내서에서는 {redhat} 업데이트 인프라(RHUI)에 등록된 클라이언트에 대해 설명합니다. RHUI에 등록된 시스템이 최소 한 개 있어야 하고, 이와 함께 리포지토리 컨텐트에 대한 인증 구독이 있어야 합니다.

{redhat} 컨텐트 제공 네트워크(CDN)를 사용하는 방법에 대한 정보 대신에 xref:client-configuration:clients-rh-cdn.adoc[]을 참조하십시오.


[IMPORTANT]
====
클라이언트 시스템에 대한 Satellite 서버는 Satellite 서버 및 구독이 있어야 합니다. Satellite 인증서를 사용하는 클라이언트는 {productname} 서버에서 지원하지 않습니다.
====


[IMPORTANT]
====
{payg} 연결은 클라이언트를 정기적으로 확인하여 최신 인증 데이터를 가져옵니다. 클라이언트가 계속 실행 중이고 정기적으로 업데이트하는 것이 중요합니다. 그러지 않으면 특정 시점에 인증 오류가 발생하며 리포지토리 동기화가 실패합니다.
====


[NOTE]
====
{redhat} 7 인스턴스를 업데이트한 후 연결하십시오.
====


// mc: this depends on the version of Jsch we use. The current version 0.1.55 only support rsa-ssh auth
//     which is forbidden with the DEFAULT policy. If we decide to switch to a different implementation
//     of Jsch (0.2.9 or higher) this limitation is gone and the note can be removed
[NOTE]
====
{redhat} 9 인스턴스를 연결하려면 [literal]``LEGACY`` 암호화 정책을 사용하여 구성해야 합니다. [command]``sudo update-crypto-policies --set LEGACY``를 실행하여 적절하게 구성하십시오.
====


== {redhat} 업데이트 인프라에 연결

[[proc-connecting-new-rhui]]
.절차: 새 {redhat} 인스턴스 연결
[role=procedure]
. {productname} {webui}에서 menu:관리[설치 마법사 > {payg}]으로 이동하고 btn:[{payg} 추가]를 클릭합니다.
. 페이지 섹션 [guimenu]``{payg} 연결 설명``으로 시작하십시오.
. [guimenu]``설명`` 필드에 설명을 추가합니다.
. [guimenu]``인스턴스 SSH 연결 데이터`` 페이지 섹션으로 이동합니다.
. [guimenu]``호스트`` 필드에 {productname}에서 연결할 인스턴스 DNS 또는 IP 주소를 입력합니다.
. [guimenu]``SSH 포트`` 필드에 포트 번호를 입력하거나 기본값 22를 사용합니다.
. [guimenu]``사용자`` 필드에 클라우드에 지정된 대로 사용자 이름을 입력합니다.
. [guimenu]``암호`` 필드에 암호를 입력합니다.
. [guimenu]``SSH 개인 키`` 필드에 인스턴스 키를 입력합니다.
. [guimenu]``SSH 개인 키 암호 문구`` 필드에 키 암호 문구를 입력합니다.


[IMPORTANT]
====
인증 키는 항상 PEM 형식이어야 합니다.
====


인스턴스에 직접 연결하지 않고 SSH 배스천을 통해 연결하는 경우 <<proc-adding-ssh-bastion-connection-data>>를 진행합니다.

그 외의 경우, <<proc-finishing-rhui-connecting>>를 진행합니다.


[[proc-adding-ssh-bastion-connection-data]]
.절차: SSH 배스천 연결 데이터 추가
[role=procedure]
. [guimenu]``SSH 배스천 연결 데이터`` 페이지 섹션으로 이동합니다.
. [guimenu]``호스트`` 필드에 배스천 호스트 이름을 입력합니다.
. [guimenu]``SSH 포트`` 필드에 배스천 포트 번호를 입력합니다.
. [guimenu]``사용자`` 필드에 배스천 사용자 이름을 입력합니다.
. [guimenu]``암호`` 필드에 배스천 암호를 입력합니다.
. [guimenu]``SSH 개인 키`` 필드에 배스천 키를 입력합니다.
. [guimenu]``SSH 개인 키 암호 문구`` 필드에 배스천 키 암호 문구를 입력합니다.

<<proc-finishing-rhui-connecting>>로 설정을 완료합니다.


[[proc-finishing-rhui-connecting]]
.절차: {redhat} 연결 종료
[role=procedure]
. 새 {redhat} 연결 데이터 추가를 완료하려면 btn:[생성]을 클릭합니다.
. {payg} 연결 데이터 [guimenu]``세부 정보`` 페이지로 돌아갑니다.
    업데이트된 연결 상태는 [guimenu]``정보`` 상단 섹션에 표시됩니다.
. 연결 상태는 [guimenu]``관리 > 설정 마법사 > 종량제`` 화면에도 표시됩니다.
. 인스턴스에 대한 인증 데이터가 올바른 경우 [guimenu]``상태`` 열에 [literal]``자격 증명이 업데이트되었습니다.``가 표시됩니다.


[IMPORTANT]
====
언제라도 잘못된 데이터가 입력되면 새로 생성된 인스턴스가 [guimenu]``관리 > 설정 마법사 > {payg}``에 표시되고 [guimenu]``상태`` 열에는 오류 메시지가 표시됩니다.
====


서버에서 인증 데이터를 사용할 수 있게 되면, 연결된 인스턴스에서 사용 가능한 모든 리포지토리에 대한 리포지토리가 추가됩니다. 리포지토리는 [guimenu]``소프트웨어 > 관리 > 리포지토리``에서 볼 수 있습니다.


[IMPORTANT]
====
{redhat} 연결은 기본적으로 조직 1이 소유하는 사용자 정의 리포지토리를 생성합니다. 다른 조직이 자동 생성된 리포지토리를 소유해야 하는 경우, ``/etc/rhn/rhn.conf``에서 [systemitem]``java.rhui_default_org_id``를 구성합니다.
====

이는 리포지토리만 정의하고 업데이트합니다. 관리 클라이언트용 리포지토리를 사용하려면 소프트웨어 채널을 지정하고 해당 채널에 리포지토리를 연결해야 합니다.


== 소프트웨어 채널 추가

// 2022-04-21, ke:
// Section sequence according to https://github.com/uyuni-project/uyuni-docs/pull/1535

{redhat} 클라이언트를 {productname} 서버에 등록하기 전에 필요한 소프트웨어 채널을 추가하고 이 채널을 동기화해야 합니다.

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]


ifeval::[{mlm-content} == true]

{susemgr} 구독을 통해 사용자는 {sleses}용 도구 채널({redhat} Expanded Support 또는 RES라고도 함)을 이용할 수 있는 자격을 얻게 됩니다. 사용자는 클라이언트 도구 채널을 사용해 부트스트랩 리포지토리를 생성해야 합니다. 이 절차는 Salt 클라이언트에 적용됩니다.
endif::[]


ifeval::[{mlm-content} == true]

이 절차에 필요한 제품은 다음과 같습니다.

[[redhat-rhui-channels-wizard]]
[cols="1,1", options="header"]
.Red Hat 제품 - WebUI
|===

// SUSE Liberty Linux not available at Uyuni for now
| OS Version | Product Name | {redhat} 10 | RHEL and Liberty 10 Base | {redhat} 9 | RHEL and Liberty 9 Base | {redhat} 8 | RHEL or SLES ES or CentOS 8 Base | {redhat} 7 | RHEL7 Base x86_64

|===


ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

이 절차에 필요한 채널은 다음과 같습니다.

[[redhat-rhui-channels-cli]]
[cols="1,1,1,1", options="header"]
.Red Hat 채널- CLI
|===

| OS Version
| Base Channel
| Client Channel
| Tools Channel

| {redhat} 7
| rhel7-pool-uyuni
| -
| rhel7-uyuni-client

| {redhat} 8
| rhel8-pool-uyuni
| -
| rhel8-uyuni-client

| {redhat} 9
| rhel9-pool-uyuni
| -
| rhel9-uyuni-client

| {redhat} 10
| rhel10-pool-uyuni
| -
| rhel10-uyuni-client

|===


ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli_multiarch.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli_multiarch.adoc[]
endif::[]


[NOTE]
====
[command]``spacewalk-common-channels``가 제공하는 클라이언트 도구 채널은 {suse}가 아닌 {uyuni}가 공급합니다.
====

endif::[]


== 사용자 정의 채널 준비

RHUI에서 소프트웨어를 미러링하려면 자동 생성 리포지토리에 연결된 {productname}에 사용자 정의 채널을 생성해야 합니다.

이 절차에 필요한 채널은 다음과 같습니다.

[[redhat-rhui-channels-custom]]

ifeval::[{mlm-content} == true]
[cols="1,1,1", options="header"]
.Red Hat 사용자 정의 채널
|===

// SUSE Liberty Linux not available at Uyuni for now
| OS Version  | Base Product                     | Base Channel
| {redhat} 10 | RHEL and Liberty 10 Base         | el10-pool-x86_64
| {redhat} 9  | RHEL and Liberty 9 Base          | el9-pool-x86_64
| {redhat} 8  | RHEL or SLES ES or CentOS 8 Base | rhel8-pool-x86_64
| {redhat} 7  | RHEL7 Base x86_64                | rhel7-pool-x86_64

|===
endif::[]


ifeval::[{uyuni-content} == true]
// SUSE Liberty Linux not available at Uyuni for now
[cols="1,1", options="header"]
.Red Hat 사용자 정의 채널
|===

| OS Version  | Base Channel
| {redhat} 7  | rhel7-pool-uyuni
| {redhat} 8  | rhel8-pool-uyuni
| {redhat} 9  | rhel9-pool-uyuni
| {redhat} 10 | rhel10-pool-uyuni

|===
endif::[]


ifndef::backend-pdf[]
include::client-configuration:partial$manual_channels.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_channels.adoc[]
endif::[]


[IMPORTANT]
====
{redhat} 9 및 {redhat} 8 클라이언트의 경우 기본 채널과 AppStream 채널을 모두 추가하십시오. 사용자에게는 두 채널의 패키지가 모두 필요합니다. 두 채널을 모두 추가하지 않으면 패키지가 누락되어 부트스트랩 리포지토리를 생성할 수 없습니다.
====


ifndef::backend-pdf[]
include::client-configuration:partial$manual_associate.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_associate.adoc[]
endif::[]



== 동기화 상태 확인

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]


ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]


[NOTE]
====
{rhel} 채널은 규모가 매우 클 수 있습니다. 일부 경우 동기화에 몇 시간이 걸릴 수 있습니다.
====


== GPG 키 관리

클라이언트는 소프트웨어 패키지가 설치되기 전에 GPG 키를 사용해 신뢰성을 확인합니다. 신뢰할 수 있는 소프트웨어만 클라이언트에 설치할 수 있습니다.

[IMPORTANT]
====
클라이언트의 보안을 위해 GPG 키를 신뢰하는 것이 중요합니다. 어떤 키가 필요하고 신뢰할 수 있는지 결정하는 것은 관리자가 수행해야 하는 작업입니다. GPG 키를 신뢰할 수 없는 경우 소프트웨어 채널을 사용할 수 없기 때문에 채널을 클라이언트에 할당하는 결정은 키를 신뢰하는 결정에 따라 달라집니다.
====

GPG 키에 대한 자세한 내용은 xref:client-configuration:gpg-keys.adoc[]에서 확인할 수 있습니다.


== 클라이언트 등록

ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]

