[[script-client-proxy]]
= 부트스트랩 스크립트로 클라이언트를 프록시에 등록
:revdate: 2025-03-20
:page-revdate: {revdate}


클라이언트는 {productname} 프록시를 통해 부트스트랩 스크립트를 사용하여 등록할 수 있습니다. 이 작업은 {productname} 서버에 직접 클라이언트를 등록하는 것과 거의 동일한 방식으로 수행됩니다.

{productname} 서버 컨테이너에서 [command]``mgr-bootstrap`` 명령줄 도구를 사용하여 부트스트랩 스크립트를 생성하십시오. [command]``mgr-bootstrap``은 프록시의 완전한 도메인 이름(FQDN), 활성화 키 또는 GPG 키와 같은 파라미터가 필요합니다. 프록시의 FQDN은 필수입니다. 다른 모든 파라미터는 특정 설정에 따라 다릅니다.


그런 다음 부트스트랩 스크립트는 클라이언트에 필요한 모든 정보를 배포합니다.



.절차: 부트스트랩 스크립트로 클라이언트를 프록시에 등록

. {productname} 서버에서 {webui}를 사용하여 클라이언트 활성화 키를 생성하십시오. 자세한 내용은 xref:client-configuration:activation-keys.adoc[]에서 확인할 수 있습니다.
. 서버의 컨테이너 호스트의 컨테이너에서 터미널을 시작하십시오.

+

[source, shell]
----
mgrctl term
----

+

--
.. 컨테이너 내에서 부트스트랩 스크립트를 생성하려면 [command]``mgr-bootstrap`` 명령을 다음 옵션과 함께 실행합니다.

+

[source, shell]
----
mgr-bootstrap --hostname=MLM_PROXY --activation-keys=ACTIVATION_KEY \
  --script bootstrap-MLM_PROXY.sh
----

+

[literal]``MLM_PROXY``를 프록시의 호스트 이름으로 바꿉니다.

+
[option]``--script`` 옵션을 사용하면 부트스트랩 스크립트를 설명적인 이름으로 저장할 수 있습니다.
   필요한 경우, 추가 명령줄 옵션을 사용하여 부트스트랩 스크립트를 사용자 정의하십시오.
   사용 가능한 옵션을 보려면 명령줄에 [command]``mgr-bootstrap --help``를 입력하십시오.

.. 옵션: 출력된 부트스트랩 스크립트를 편집합니다.
--

. 부트스트랩 스크립트를 실행합니다. 다음의 두 가지 옵션이 있습니다.

+

* 스크립트를 클라이언트로 전송하고 클라이언트에서 직접 실행합니다. 또는 프록시가 서버로 요청을 전달하므로 클라이언트는 http://MLM_PROXY/pub/bootstrap-MLM_PROXY.sh[]에서 다운로드할 수 있습니다. [literal]``MLM_PROXY``를 프록시의 호스트 이름으로 바꿉니다.

* 프록시에서 [command]``ssh`` 명령으로 스크립트를 실행합니다. [literal]``MLM_PROXY``는 프록시의 호스트 이름으로, [systemitem]`` <client.example.com>``는 클라이언트의 호스트 이름으로 각각 바꿉니다.

+

[source, shell]
----
cat /srv/www/htdocs/pub/bootstrap/bootstrap-MLM_PROXY.sh | ssh root@<client.example.com> /bin/bash
----
