[[clients-debian]]
= {debian} 클라이언트 등록

이 섹션에는 {debian} 운영 체제를 실행하는 Salt 클라이언트를 등록하는 방법에 대한 정보가 포함되어 있습니다.

[IMPORTANT]
====
{suse}는 {debian} 운영 체제에 대한 지원을 제공하지 않습니다. {productname}를 통해 {debian} 클라이언트를 관리할 수 있지만 지원은 제공되지 않습니다. {productname}를 사용해 {debian} 클라이언트를 관리하는 것은 현재 시험 중입니다. 이 지침은 {debian}{nbsp}9 Stretch 및 {debian}{nbsp}10 Buster에서 테스트를 완료하였습니다. 프로덕션 환경에서는 {debian} 클라이언트에 의존하지 마십시오.
====

[NOTE]
====
Salt 클라이언트에 대해서만 {debian}을 지원합니다. 기존 클라이언트는 지원하지 않습니다.
====

{debian} 클라이언트에서는 부트스트래핑을 사용해 초기 상태 실행을 수행하고 프로파일을 업데이트할 수 있습니다.



== 등록 준비

{debian} 클라이언트를 {productname} 서버에 등록하려면 다음과 같은 약간의 준비가 필요합니다.

* If you are using Debian{nbsp}9, install the required packages on the client before you attempt to register. On the client, at the command prompt, as root, run:
+
----
apt install apt-transport-https python-apt python3-apt
----

* Ensure DNS is correctly configured and provides an entry for the client. Alternatively, you can configure the ``/etc/hosts`` files on both the {productname} Server and the client with the appropriate entries.
* The client must have the date and time synchronized with the {productname} Server before registration.



== 소프트웨어 채널 추가

{debian} 클라이언트를 {productname} 서버에 등록하려면 먼저 필요한 소프트웨어 채널을 추가하고 이 채널을 동기화해야 합니다.

ifeval::[{suma-content} == true]

이 절차에 필요한 제품은 다음과 같습니다.

[[debian-channels-wizard]]
[cols="1,1", options="header"]
.Debian 제품 - WebUI
|===
| OS Version  | Product Name
| {debian} 9  | Debian 9
| {debian} 10 | Debian 10
|===

include::snippets/addchannels_vendor_webui.adoc[]

또는 명령 프롬프트에서 채널을 추가할 수 있습니다. 이 절차에 필요한 채널은 다음과 같습니다.

[[debian-channels-cli]]
[cols="1,1", options="header"]
.Debian 채널 - CLI
|===
| OS 버전  | 제품 이름
| {debian} 9  | debian-9-pool-amd64
 | {debian} 10 | debian-10-pool-amd64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]

이 절차에 필요한 채널은 다음과 같습니다.

[[debian-channels-cli]]
[cols="1,1,1,1,1", options="header"]
.Debian 채널 - CLI
|===

| OS 버전
| 기본 채널
 | 클라이언트 채널
 | 업데이트 채널
 | 보안 채널
 
 | {debian} 9
 | debian-9-pool-amd64-uyuni
 | debian-9-amd64-uyuni-client
 | debian-9-amd64-main-updates-uyuni
 | debian-9-amd64-main-security-uyuni
 
 | {debian} 10
 | debian-10-pool-amd64-uyuni
 | debian-10-amd64-uyuni-client
 | debian-10-amd64-main-updates-uyuni
 | debian-10-amd64-main-security-uyuni

|===

include::snippets/addchannels_novendor_cli.adoc[]

endif::[]



== 동기화 상태 확인

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[NOTE]
====
{debian} 채널은 규모가 매우 클 수 있습니다. 때로 동기화에 몇 시간이 걸릴 수 있습니다.
====



ifeval::[{uyuni-content} == true]

== 클라이언트의 GPG 키 신뢰

include::snippets/trust_gpg.adoc[]

[NOTE]
====
{debian} clients can require multiple GPG keys to be installed.
====

endif::[]



== 클라이언트 등록

{debian} 클라이언트를 등록하려면 부트스트랩 리포지토리가 필요합니다. 기본적으로 부트스트랩 리포지토리는 매일 재생성됩니다. 명령 프롬프트에서 다음 명령을 사용해 부트스트랩 리포지토리를 수동으로 생성할 수 있습니다.

----
mgr-create-bootstrap-repo
----

{debian}{nbsp}10의 경우 프롬프트가 표시되면 ``debian10-amd64-uyuni``를 선택합니다.


클라이언트 등록에 대한 자세한 내용은 xref:client-configuration:registration-overview.adoc[]를 참조하십시오.
