[[clients-centos]]
= {centos} 클라이언트 등록
:revdate: 2025-03-10
:page-revdate: {revdate}

이 섹션에는 {centos} 운영 체제를 실행하는 클라이언트를 등록하는 방법에 대한 정보가 포함되어 있습니다.

ifeval::[{mlm-content} == true]

// Use list format: repository URLs / packages and metadata / version info
// Do we need to provide special info for uyuni users?
[IMPORTANT]
====
* {centos} 리포지토리 URL은 {scclongform}에서 사용할 수 있습니다.
* 패키지 및 메타데이터는 {suse}가 아닌 CentOS에서 제공합니다.
* 지원되는 클라이언트에 대해서는 xref:client-configuration:supported-features-centos.adoc[]의 릴리스 노트 및 지원 테이블을 참조하십시오.
====
endif::[]

[IMPORTANT]
====

ifeval::[{mlm-content} == true]

{centos} 클라이언트는 {centos}를 기반으로 하며 {sleses}, RES, {redhat} 또는 {es}와 관련이 없습니다.
endif::[]

{centos} 기본 미디어 리포지토리 및 {centos} 설치 미디어에 대한 액세스를 준비하고 {productname} 서버를 {centos} 콘텐츠 전송 네트워크에 연결할 책임은 사용자에게 있습니다.
====

[NOTE]
====
{centos} 클라이언트를 {productname}에 등록하는 기능은 ``목표`` 정책으로 ``강제``하는 기본 SELinux 구성으로 테스트됩니다. SELinux를 비활성화해야 {centos} 클라이언트를 {productname}에 등록할 수 있는 것은 아닙니다.
====



== 소프트웨어 채널 추가


{centos} 클라이언트를 {productname} 서버에 등록하려면 먼저 필요한 소프트웨어 채널을 추가하고 이 채널을 동기화해야 합니다.

현재 지원되는 아키텍처는 ``x86_64`` 및 ``aarch64``입니다. 지원되는 제품 및 아키텍처의 전체 목록은 xref:client-configuration:supported-features.adoc[]에서 참조하십시오.

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]

ifeval::[{mlm-content} == true]

예를 들어, `x86_64` 아키텍처에서 작업 시 필요한 제품은 다음과 같습니다.

[[centos-channels-wizard]]
[cols="1,1", options="header"]
.CentOS 제품 - WebUI
|===

| OS 버전 | 제품 이름
| {centos} 7 | CentOS 7 x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]

또는 명령 프롬프트에서 채널을 추가할 수 있습니다. 이 절차에 필요한 채널은 다음과 같습니다.

[[centos-channels-MLM-cli]]
[cols="1,1", options="header"]
.CentOS 채널 - CLI
|===

| OS 버전 | 기본 채널
| {centos} 7 | centos7-x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_cli.adoc[]
endif::[]

endif::[]

ifeval::[{uyuni-content} == true]
이 절차에 필요한 채널은 다음과 같습니다.

[[centos-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.CentOS 채널 - CLI
|===

| OS 버전 | 기본 채널 | 클라이언트 채널       | 업데이트/Appstream 채널
| {centos} 7 | centos7      | centos7-uyuni-client | centos7-updates
|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli_multiarch.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli_multiarch.adoc[]
endif::[]

[NOTE]
====
[command]``spacewalk-common-channels``가 제공하는 클라이언트 도구 채널은 {suse}가 아닌 {uyuni}가 공급합니다.
====

endif::[]


모듈형 채널을 사용하는 경우 클라이언트에서 Python 3.6 모듈 스트림을 활성화해야 합니다.Python 3.6이 제공되지 않으면 [package]``spacecmd`` 패키지의 설치가 실패합니다.

[NOTE]
====
AppStream 채널에서 사용할 수 있는 패키지의 수가 업스트림과 {productname} 채널 간에 서로 약간 불일치함을 알 수 있습니다. 또한 다른 시점에 추가한 동일 채널을 비교하면 그 수가 다른 것을 알 수 있습니다. 이는 {centos}가 리포지토리를 관리하는 방식에 원인이 있습니다. {centos}는 새 버전이 릴리스되면 이전 버전의 패키지를 제거하지만 {productname}는 사용 기간과 관계없이 모두 그대로 유지합니다.
====


== 동기화 상태 확인

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]


ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]



== 활성화 키 생성

{centos} 채널에 연결된 활성화 키를 생성해야 합니다.

활성화 키에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]를 참조하십시오.



== GPG 키 관리

클라이언트는 소프트웨어 패키지가 설치되기 전에 GPG 키를 사용해 신뢰성을 확인합니다. 신뢰할 수 있는 소프트웨어만 클라이언트에 설치할 수 있습니다.

[IMPORTANT]
====
클라이언트의 보안을 위해 GPG 키를 신뢰하는 것이 중요합니다. 어떤 키가 필요하고 신뢰할 수 있는지 결정하는 것은 관리자가 수행해야 하는 작업입니다. GPG 키를 신뢰할 수 없는 경우 소프트웨어 채널을 사용할 수 없기 때문에 채널을 클라이언트에 할당하는 결정은 키를 신뢰하는 결정에 따라 달라집니다.
====

GPG 키에 대한 자세한 내용은 xref:client-configuration:gpg-keys.adoc[]에서 확인할 수 있습니다.



== 클라이언트 등록


[NOTE]
====
CentOS 7은 [path]``/etc/yum.repos.d/CentOS-Base.repo``에 URL이 활성화되어 있어 [command]``yum``이 fastmirror를 사용하여 리포지토리를 찾으려고 시도하기 때문에 온보딩에 실패할 수 있습니다. 그러면 부트스트랩이 실패하고 다음 오류 메시지가 표시됩니다.

----
호스트: mirrorlist.centos.org를 확인할 수 없음, 알 수 없는 오류
----

이 문제를 방지하려면 다음 명령을 수행하여 [path]``CentOS-Base.repo`` 파일을 제거하면 됩니다.

[source, shell]
----
rm -f /etc/yum.repos.d/CentOS-Base.repo
----

또는 파일을 유지해야 하는 경우에는 각 URL 섹션에 [literal]``enabled=0``을 추가하면 됩니다.

그런 다음, 어떤 경우든 다시 부트스트랩합니다.
====

ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]



ifeval::[{uyuni-content} == true]

== 정오표 관리

[NOTE]
====
이 섹션은 컨테이너화되지 않은 Uyuni에만 적용되며, {centos} 7의 수명 종료 이후에 제거됩니다.
====

{centos} 클라이언트를 업데이트할 때 패키지에는 업데이트에 대한 메타데이터가 포함되지 않습니다. 타사 정오표 서비스를 사용해 이 정보를 얻을 수 있습니다.

[WARNING]
====

// ifeval::[{mlm-content} == true]
//
// The third-party errata service described here, CEFS, is provided and maintained by the community.
// It is not supported by {suse}.
//
// endif::[]

CEFS의 원저자는 도움이 됐으면 하는 마음으로 최선을 다해 패치나 정오표를 제공하지만 정확성이나 최신 상태를 보장하지는 않습니다. 따라서 패치 날짜가 부정확할 수 있습니다. 한번은 게시 날짜가 한 달 이상 늦은 날짜로 표시된 적도 있습니다. 이러한 경우에 대한 자세한 내용은 https://github.com/stevemeier/cefs/issues/28#issuecomment-656579382 및 https://github.com/stevemeier/cefs/issues/28#issuecomment-656573607[]을 참조하십시오.

패치 데이터 관련 문제나 지연으로 인해 {productname} 서버로 신뢰할 수 없는 패치 정보가 임포트될 수 있습니다. 이로 인해 보고서, 감사, CVE 업데이트 또는 기타 패치 관련 정보가 부정확해질 수도 있습니다. 패치 데이터를 독립적으로 확인하거나 보안 관련 요구사항 및 인증 기준에 따라 다른 운영 체제를 선택하는 등 이 서비스 사용을 대체할 수 있는 수단을 고려해 보시기 바랍니다.
====




.절차: 정오표 서비스 설치

. {productname} 서버의 명령 프롬프트에서 루트 권한으로 ``sle-module-development-tools`` 모듈을 추가합니다.
+
----
SUSEConnect --product sle-module-development-tools/15.2/x86_64
----
. 다음과 같이 오류 서비스 종속성을 설치합니다.
+
----
zypper in  perl-Text-Unidecode
----
. [path]``/etc/rhn/rhn.conf``에서 다음 줄을 추가하거나 편집합니다.
+
----
java.allow_adding_patches_via_api = centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras
----
. Tomcat을 다시 시작합니다.
+
----
systemctl restart tomcat
----
. 다음과 같이 오류 스크립트에 대해 파일을 생성합니다.
+
----
touch /usr/local/bin/cent-errata.sh
----
. 이 스크립트를 포함할 새 파일을 편집하고, 필요에 따라 리포지토리 상세 정보를 편집합니다.
    이 스크립트는 외부 오류 서비스에서 오류 상세 정보를 가져와 압축을 풀고 세부 정보를 게시합니다.
+
----
#!/bin/bash
mkdir -p /usr/local/centos
cd /usr/local/centos
rm *.xml
wget -c http://cefs.steve-meier.de/errata.latest.xml
wget -c https://www.redhat.com/security/data/oval/v2/RHEL7/rhel-7.oval.xml.bz2
bzip2 -d rhel-7.oval.xml.bz2
wget -c http://cefs.steve-meier.de/errata-import.tar
tar xvf errata-import.tar
chmod +x /usr/local/centos/errata-import.pl
export SPACEWALK_USER='<adminname>';export SPACEWALK_PASS='<password>'
/usr/local/centos/errata-import.pl --server '<servername>' \
--errata /usr/local/centos/errata.latest.xml  \
--include-channels=centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras \
--publish --rhsa-oval /usr/local/centos/rhel-7.oval.xml
----
. 다음과 같이 cron 작업을 설정하여 매일 스크립트를 실행합니다.
+
----
ln -s /usr/local/bin/cent-errata.sh /etc/cron.daily
----

이 도구에 대한 자세한 내용은 https://cefs.steve-meier.de/[]를 참조하십시오.

endif::[]
