[[contact-methods-salt]]
= 기본 연락 방법
:revdate: 2025-02-06
:page-revdate: {revdate}

특별한 필요가 있는 경우를 제외하고 {salt} 프로토콜을 사용하는 기본 연락 방법을 사용하는 것이 좋습니다. {salt} 번들 구현([package]``venv-salt-minion``)이 기본으로 배포됩니다. {salt}에 대한 일반적인 사항은 xref:specialized-guides:salt/salt-overview.adoc[]에서 더 자세히 확인할 수 있습니다.

ifeval::[{mlm-content} == true]

기본 연락 방법([literal]``Default``)이 가장 적합한 크기 조정 방법입니다. 새로운 {productname} 기능은 모두 지원됩니다.

[IMPORTANT]
====
{productname} 5.0 이상에서는 기존 연락 프로토콜이 더 이상 지원되지 않습니다. 기존 프록시를 포함한 모든 기존 클라이언트를 {salt}로 마이그레이션하거나 {salt} 프록시로 바꾼 후 {productname} 4에서 5로 업그레이드해야 합니다.

기존 {productname} 4 클라이언트를 {salt} 클라이언트로 마이그레이션하는 방법에 대한 자세한 내용은 link:https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.html[]에서 확인할 수 있습니다.
====

endif::[]

소프트웨어 업데이트는 일반적으로 서버에서 클라이언트로 푸시됩니다. 연결은 클라이언트에서 시작됩니다. 즉, 클라이언트가 아닌 서버의 포트를 열어야 합니다. {salt} 클라이언트를 {salt} 미니언이라고도 합니다. {productname} 서버는 모든 클라이언트에 데몬을 설치합니다.

연결이 해제된 설정에서 {salt} 클라이언트를 사용해야 하는 경우 SSH 푸시를 연락 방법으로 구성할 수 있습니다. 이 연락 방법을 사용하면 클라이언트가 방화벽으로 보호되는 이름이 DMZ인 영역에 위치할 수 있습니다. SSH 푸시에 대한 자세한 내용은 xref:client-configuration:contact-methods-saltssh.adoc[]에서 확인할 수 있습니다.



[[onboarding-details]]
== 온보딩 정보


{salt}에는 미니언의 키를 보관하는 자체 데이터베이스가 있습니다. 이 데이터베이스는 {productname} 데이터베이스와 동기화 상태를 유지해야 합니다. {salt}에서 키가 수락되는 즉시 {productname}에서 온보딩 프로세스가 시작됩니다.

온보딩 프로세스는 {productname} 데이터베이스에서 ``minion_id``와 ``machine-id``를 검색하여 기존 시스템을 찾습니다. 결과에 따라, 다음과 같은 시나리오가 가능합니다.

* 아무것도 찾을 수 없으면 새 시스템이 생성됩니다.
* ``minion_id`` 또는 ``machine-id``가 있는 항목을 찾으면 해당 시스템은 새 시스템과 일치하도록 마이그레이션됩니다.
* 두 항목이 모두 일치하지만 동일한 시스템이 아닌 경우 오류가 발생하고 온보딩이 중단됩니다.
* 이 경우 관리자는 시스템 중 하나 이상을 제거하여 충돌을 해결해야 합니다.
