[[power-management]]
= 전원 관리

{productname} {webui}를 사용해 클라이언트를 켜고, 끄고, 다시 부팅할 수 있습니다.

이 기능은 IPMI 또는 Redfish 프로토콜을 사용하며 Cobbler 프로파일을 사용해 관리됩니다. 선택한 클라이언트에는 이러한 프로토콜 중 하나를 지원하는 전원 관리 컨트롤러가 있어야 합니다.

Redfish의 경우 클라이언트와 {productname} 서버 간의 타당한 SSL 연결을 설정할 수 있는지 확인하십시오. 사용자는 Redfish 관리 컨트롤러의 SSL 서버 인증서에 서명하는 데 사용되는 인증 주체를 신뢰했어야 합니다. CA 인증서는 ``.pem`` 형식이어야 하며 {productname} 서버의 [path]``/etc/pki/trust/anchors/``에 저장됩니다. 인증서 저장을 완료했으면 [command]``update-ca-certificate``을 실행하십시오.


.절차: 전원 관리 활성화
. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 관리하려는 클라이언트를 선택하고 menu:조달[전원 관리] 탭으로 이동합니다.
. [guimenu]``유형`` 필드에서 사용할 전원 관리 프로토콜을 선택합니다.
. 전원 관리 서버의 상세 정보를 모두 입력하고, 취할 조치에 해당하는 적절한 버튼을 클릭하거나 btn:[저장만]을 클릭하여 아무 조치도 취하지 않고 상세 정보를 저장합니다.

여러 클라이언트를 시스템 세트 관리자에 추가함으로써 전원 관리 조치를 여러 클라이언트에 동시에 적용할 수 있습니다. 시스템 세트 관리자에 대한 자세한 내용은 xref:client-configuration:system-set-manager.adoc[]를 참조하십시오.



== 전원 관리 및 Cobbler

전원 관리 기능을 처음 사용할 때 Cobbler 시스템 레코드가 자동으로 생성됩니다(클라이언트에 아직 없는 경우). 이렇게 자동으로 생성된 시스템 레코드는 네트워크에서 부팅할 수 없고 더미 시스템 이미지에 대한 참조를 포함합니다. 이 참조가 필요한 이유는 현재 Cobbler가 프로파일 또는 이미지 없는 시스템 레코드를 지원하지 않기 때문입니다.

Cobbler 전원 관리는 펜스 에이전트 도구를 사용해 IPMI가 아닌 프로토콜을 지원합니다. {productname}는 IPMI 및 Redfish 프로토콜만 지원합니다. [path]``rhn.conf`` 구성 파일의 [option]``java.power_management.types`` 구성 파라미터에 펜스 에이전트 이름을 쉼표로 구분된 목록으로 추가하여 클라이언트가 다른 프로토콜을 사용하도록 구성할 수 있습니다.
