[[registering.clients.webui]]
= {webui}로 클라이언트 등록
:revdate: 2025-07-09
:page-revdate: {revdate}

== 소개


{webui}를 사용하여 부트스트랩하는 클라이언트는 xref:specialized-guides:salt/salt-ssh.adoc[Salt SSH]를 사용하여 클라이언트에서 부트스트랩 프로세스를 실행합니다. Salt SSH는 Salt 번들과 포함된 Python 인터프리터를 사용합니다. 따라서 클라이언트에 다른 Python 인터프리터를 설치할 필요가 없습니다.

Salt 번들은 부트스트랩 리포지토리와 함께 제공됩니다. 따라서 클라이언트에 대한 부트스트랩 프로세스를 시작하기 전에 부트스트랩 리포지토리를 생성해야 합니다. 셸 스크립트는 클라이언트의 운영 체제를 감지하고 부트스트랩 스크립트와 동일한 논리를 사용하여 적절한 부트스트랩 리포지토리에서 Salt 번들을 배포합니다.

자세한 내용은 xref:client-configuration:bootstrap-repository.adoc#_prepare_to_create_a_bootstrap_repository[부트스트랩 리포지토리 생성 준비]에서 확인할 수 있습니다.

[IMPORTANT]
====
{productname} 서버에 서버 자신을 등록하지 마십시오. {productname} 서버는 개별 관리하거나 별도의 다른 {productname} 서버를 사용하여 관리해야 합니다. 여러 서버 사용에 대한 자세한 내용은 xref:specialized-guides:large-deployments/hub-multi-server.adoc[]에서 확인할 수 있습니다.
====

== {webui}로 클라이언트 등록

.절차: {webui}로 클라이언트 등록

. {productname} {webui}에서 menu:시스템[부트스트랩]으로 이동합니다.
. [guimenu]``호스트`` 필드에 부트스트랩할 클라이언트의 정규화된 도메인 이름(FQDN)을 입력합니다.
. [guimenu]``SSH 포트`` 필드에서 클라이언트를 연결하고 부트스트랩하는 데 사용할 SSH 포트 번호를 입력합니다.
    기본적으로 SSH 포트는 [systemitem]``22``입니다.
. [guimenu]``사용자`` 필드에서 클라이언트에 로그인할 사용자 이름을 입력합니다.
    기본적으로 사용자 이름은 [systemitem]``root``입니다.
. [guimenu]``인증`` 방법을 선택합니다:
.. SSH 키를 사용하여 클라이언트를 부트스트래핑하려면 [guimenu]``인증`` 필드에서 [guimenu]``SSH 개인 키``를 확인하고 클라이언트에 로그인할 때 사용할 SSH 개인 키를 업로드하십시오.
    SSH 개인 키에 암호문이 필요한 경우 [guimenu]``SSH 개인 키 암호문`` 필드에 입력하십시오. 또는 어떤 암호문에 대해서도 이 필드를 공백 상태로 두지 마십시오.
.. 비밀번호로 클라이언트를 부트스트래핑하려면 [guimenu]``인증`` 필드에서 [guimenu]``비밀번호``를 확인하고 비밀번호를 입력하여 클라이언트에 로그인하십시오.
. [guimenu]``활성화 키`` 필드에서 클라이언트를 부트스트랩하는 데 사용할 소프트웨어 채널과 연결된 활성화 키를 선택합니다.
    자세한 내용은 xref:client-configuration:activation-keys.adoc[]에서 확인할 수 있습니다.
. 옵션: [guimenu]``프록시`` 필드에서 클라이언트를 등록할 프록시를 선택합니다.
. 기본적으로 [guimenu]``SSH Strict 키 호스트 점검 비활성화`` 확인란이 선택되어 있습니다.
    따라서 사용자가 수동으로 인증할 필요 없이 부트스트랩 프로세스가 자동으로 SSH 호스트 키를 수락할 수 있습니다.
. 옵션: [guimenu]``SSH를 통해 시스템을 완전히 관리`` 확인란을 선택합니다.
    이 옵션을 선택하면 서버에 연결하기 위해 SSH를 사용하도록 클라이언트가 구성되고 다른 연락 방법은 구성되지 않습니다.
+
연락 방법에 대한 자세한 내용은 xref:client-configuration:contact-methods-intro.adoc[]에서 확인할 수 있습니다.
. btn:[부트스트랩]을 클릭하여 등록을 시작합니다.
. 부트스트랩 프로세스가 완료되면 클라이언트가 menu:시스템[시스템 목록]에 나열됩니다.


[IMPORTANT]
====
* SSH 개인 키는 부트스트래핑 프로세스가 진행되는 중에만 저장되며, 부트스트래핑이 완료되자마자 {productname} 서버에서 삭제됩니다.
* {productname}를 사용해 클라이언트에 새 패키지 또는 업데이트를 설치하면 최종 사용자 라이선스 계약(EULA)이 자동으로 수락됩니다. 패키지 EULA를 검토하려면 {webui}에서 패키지 상세 정보 페이지를 여십시오.
====


== 로컬 할당 리포지토리 처리

{productname}에서 제공하지 않는 클라이언트에 리포지토리를 직접 할당하는 것은 일반적인 사용 사례가 아닙니다. 이로 인해 문제가 발생할 수 있습니다. 그러므로 Salt를 통한 부트스트래핑은 부트스트랩 프로세스를 시작할 때 모든 로컬 리포지토리를 비활성화합니다.

나중에 Highstate 또는 패키지 설치를 실행할 때처럼 채널 상태를 사용할 때마다 로컬에 할당된 모든 리포지토리가 다시 비활성화됩니다.

클라이언트에서 사용되는 모든 소프트웨어 패키지는 {productname}에서 제공하는 채널에서 가져와야 합니다. 사용자 정의 채널을 생성하는 방법에 대한 자세한 내용은 xref:administration:custom-channels.adoc[]에서 ``사용자 정의 채널``을 참조하십시오.
