[[registering.clients.bootstrap]]
= 부트스트랩 스크립트로 클라이언트 등록
:revdate: 2025-06-10
:page-revdate: {revdate}

== 소개


부트스트랩 스크립트로 클라이언트를 등록하면 파라미터를 제어할 수 있고, 다수의 클라이언트를 한 번에 등록해야 하는 경우 도움이 됩니다.

부트스트랩 스크립트를 사용하여 클라이언트를 등록하려면 먼저 템플릿 부트스트랩 스크립트를 생성한 다음 복사하고 수정하는 것이 좋습니다. 생성한 부트스트랩 스크립트는 클라이언트가 등록될 때 클라이언트에서 실행되며, 필요한 모든 패키지가 클라이언트에 배포되도록 합니다. 부트스트랩 스크립트의 일부 파라미터는 활성화 키와 GPG 키를 사용하여 클라이언트 시스템을 기본 채널에 할당할 수 있도록 합니다.

리포지토리 정보를 주의 깊게 확인하여 기본 채널 리포지토리와 일치하게 하는 것이 중요합니다. 리포지토리 정보가 정확히 일치하지 않으면 부트스트랩 스크립트가 패키지를 정확히 다운로드할 수 없습니다.

추가 고려 사항:

* 모든 클라이언트에는 부트스트랩 리포지토리가 필요합니다. 부트스트랩 리포지토리는 제품이 동기화될 때 {productname} 서버에 자동으로 생성 및 재생성됩니다. 부트스트랩 리포지토리에는 클라이언트에 {salt}를 설치하고 클라이언트를 등록하기 위한 패키지가 포함됩니다. 부트스트랩 리포지토리 만들기에 대한 자세한 내용은 xref:client-configuration:bootstrap-repository.adoc[]에서 확인할 수 있습니다.

* openSUSE Leap 15 및 SLES 15는 기본적으로 Python 3를 사용합니다. Python 2에 기반을 둔 부트스트랩 스크립트는 openSUSE Leap 15 및 SLE 15 시스템에 대해 다시 생성해야 합니다. Python 2를 사용해 openSUSE Leap 15 또는 SLE 15 시스템을 등록하는 경우 부트스트랩 스크립트는 실패합니다.


ifeval::[{uyuni-content} == true]

[IMPORTANT]
.GPG 키 및 Uyuni 클라이언트 도구
====
Uyuni 클라이언트 도구가 사용하는 GPG 키는 기본적으로 신뢰할 수 없습니다. 부트스트랩 스크립트를 생성할 때 [systemitem]``ORG_GPG_KEY`` 파라미터와 함께 공용 키 지문이 포함된 파일의 경로를 추가하십시오.
====

endif::[]


ifeval::[{mlm-content} == true]

[IMPORTANT]
====
{productname}의 이전 버전에서 최신 버전으로 마이그레이션한 후에는 잠재적인 문제를 방지하기 위해 새 시스템을 온보딩하기 전에 부트스트랩 스크립트를 다시 생성하는 것이 적극 권장됩니다.
====

endif::[]

[IMPORTANT]
====
서버 컨테이너 내부의 셸에 액세스하려면 컨테이너 호스트에서 [literal]``mgrctl term``을 실행합니다. 이후에는 CLI 도구를 평소와 마찬가지로 사용할 수 있습니다.
====


[[registering.clients.bootstrap.mgr-bootstrap]]
== [command]``mgr-bootstrap`` 명령을 사용한 부트스트랩 스크립트 생성

[command]``mgr-bootstrap`` 명령은 사용자 정의 부트스트랩 스크립트를 생성합니다. 초기 등록 및 구성을 단순화하기 위해 {productname} 클라이언트 시스템은 부트스트랩 스크립트를 사용합니다.

[option]``--activation-keys`` 및 [option]``--script`` 인수가 유일한 필수 인수입니다. {productname} 서버에서 명령줄의 루트로 필수 인수를 사용하여 실행하십시오. 다음과 같이 [systemitem]``<ACTIVATION_KEYS>`` 및 [systemitem]``<EDITED_NAME>``을 사용자의 값으로 바꿉니다.

. {productname} 컨테이너 호스트의 명령 프롬프트에서 루트 사용자로 다음 명령어를 실행하여 서버 컨테이너에 진입합니다.

+
----
mgrctl term
----
+
. 다음 명령을 실행합니다(필요에 따라 값 조정).
+
----
mgr-bootstrap --activation-keys=<ACTIVATION_KEY> --script=bootstrap-<EDITED_NAME>.sh
----

[command]``mgr-bootstrap`` 명령은 특정 호스트 이름을 설정하고 특정 GPG 키를 설정하며 등록 방법(salt-minion 또는 salt-bundle)을 설정하는 기능 등 몇 가지 다른 옵션을 제공합니다.

[NOTE]
====

* 프록시에 등록하기 위한 부트스트랩 스크립트를 생성하려면 서버 컨테이너에서 다음 명령을 사용합니다.

+ 

----
mgr-boostrap --hostname <PROXY_FQDN>
----

+ 

이 명령은 새 부트스트랩 스크립트를 기본 이름 [literal]``bootstrap.sh``로 생성하며, 서버에 사용 중인 기존 [literal]``bootstrap.sh`` 파일을 덮어씁니다.


* 다른 스크립트를 지정하려면 다음 명령을 실행합니다.

+

----
mgr-bootstrap --hostname <PROXY_FQDN> --script=boostrap-<PROXY-SCRIPT>.sh
----

====

자세한 내용은 [literal]``mgr-bootstrap`` 사용자 지정 페이지를 참조하거나 [command]``mgr-bootstrap --help``를 실행하십시오.



== {webui}에서 부트스트랩 스크립트 생성

{productname} {webui}를 사용하면 편집 가능한 부트스트랩 스크립트를 생성할 수 있습니다.

// 2022-10-26, ke: In step 2, check whether we can use {productname} macro.

.절차: 부트스트랩 스크립트 생성
[role=procedure]
_____

. {productname} {webui}에서 menu:관리[관리자 구성 > 부트스트랩 스크립트]로 이동합니다.

. 필수 필드는 이전의 설치 단계에서 얻은 값으로 미리 채워져 있습니다. 각 설정에 대한 자세한 내용은 xref:reference:admin/bootstrap-script.adoc[]에서 확인할 수 있습니다.

. btn:[업데이트]를 클릭하여 스크립트를 생성합니다.

. 부트스트랩 스크립트는 생성되어 서버의 [path]``/srv/www/htdocs/pub/bootstrap`` 디렉토리에 저장됩니다. 또는, HTTPS를 통해 부트스트랩 스크립트에 액세스할 수 있습니다. [literal]``<example.com>``을 다음과 같은 {productname} 서버의 호스트 이름으로 바꿉니다.

+

----
https://<example.com>/pub/bootstrap/bootstrap.sh
----

_____


[IMPORTANT]
====
부트스트랩 스크립트에서 SSL을 비활성화하지 마십시오. {webui}에서 [guimenu]``SSL 활성화`` 확인란이 선택되어 있는지, 또는 ``USING_SSL=1``이라는 설정이 부트스트랩 스크립트에 있는지 확인합니다. SSL을 비활성화하면 등록 프로세스에 사용자 정의 SSL 인증서가 필요합니다.

사용자 정의 채널에 대한 자세한 내용은 xref:administration:ssl-certs.adoc[]에서 확인할 수 있습니다.
====



[[modify.bootstrap.script]]
== 부트스트랩 스크립트 편집

생성한 템플릿 부트스트랩 스크립트를 복사 및 수정하여 사용자 정의할 수 있습니다. {productname}에서 사용할 부트스트랩 스크립트를 수정할 때 충족해야 할 최소 요구사항은 활성화 키를 포함해야 한다는 것입니다. 대부분의 패키지는 GPG로 서명되므로 패키지를 설치할 시스템에 신뢰할 수 있는 GPG 키도 있어야 합니다.

이 절차에서 활성화 키의 정확한 이름을 알아야 합니다. menu:홈[개요]로 이동하여 [guimenu]``작업`` 상자에서 [guimenu]``활성화 키 관리``를 클릭합니다. 채널에 대해 생성된 모든 키는 이 페이지에 나열되어 있습니다. 부트스트랩 스크립트에서 사용하려는 키의 전체 이름을 키 필드에 표시된 대로 정확히 입력해야 합니다. 활성화 키에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]를 참조하십시오.



.절차: 부트스트랩 스크립트 수정
[role=procedure]
_____

. {productname} 컨테이너 호스트의 명령 프롬프트에서 루트 사용자로 다음 명령어를 실행하여 서버 컨테이너에 진입합니다.
+

----
mgrctl term
----
+

. {productname} 서버에서 명령줄의 루트 권한으로 다음과 같이 부트스트랩 디렉토리로 변경합니다.

+

----
cd /srv/www/htdocs/pub/bootstrap/
----

. 각 클라이언트에서 사용할 템플릿 부트스트랩 스크립트 사본 2개를 생성하여 이름을 변경합니다.

+

----
cp bootstrap.sh bootstrap-sles12.sh
cp bootstrap.sh bootstrap-sles15.sh
----

. 수정을 위해 [path]``bootstrap-sles15.sh``를 엽니다.
    아래와 같은 텍스트가 나올 때까지 아래로 스크롤합니다. ``exit 1``이 파일에 있는 경우 해시 또는 파운드 기호(&#35;)를 줄 첫머리에 입력하여 코멘트 아웃합니다. 이렇게 하면 스크립트가 활성화됩니다. 이 스크립트의 키 이름을 ``ACTIVATION_KEYS=`` 필드에 다음과 같이 입력합니다.

+

----
echo "Enable this script: comment (with #'s) this block (or, at least just"
echo "the exit below)"
echo
#exit 1

# 수정할 수 있으나 아마 정확할 것입니다(초기 설치 중에 생성하지 않은 경우):
# 참고: ACTIVATION_KEYS는 클라이언트 시스템을 부트스트래핑하는 데 *반드시* 사용해야 합니다.
ACTIVATION_KEYS=1-sles15
ORG_GPG_KEY=
----

+

[NOTE]
====
스크립트를 수작업으로 편집하는 대신, 사용자는 실행 시점에 다음 환경 변수를 전달할 수 있습니다.

- `ACTIVATION_KEYS`: 등록에 사용할 활성화 키
- `ORG_GPG_KEY`: GPG 키의 경로 또는 식별자
- `REACTIVATION_KEY`: 이전에 등록된 시스템의 재활성화 키
- `MGR_SERVER_HOSTNAME`: 클라이언트를 등록할 서버 또는 프록시의 호스트 이름

환경 변수를 사용하면 런타임에 동적 입력을 허용하고 여러 시스템이나 환경에서 동일한 부트스트랩 스크립트를 쉽게 재사용할 수 있습니다.
====

+

. 완료한 후 파일을 저장하고 두 번째 부트스트랩 스크립트에 대해 이 절차를 반복하십시오.

_____


[NOTE]
====
기본적으로 부트스트랩 스크립트는 부트스트랩 리포지토리에 {salt} 번들이 있으면 [package]``venv-salt-minion``을 설치하고 부트스트랩 리포지토리에 [package]``salt-minion``이 없으면 [package]``salt-minion``을 설치하려고 시도합니다. 부득이하게 필요한 경우 Salt 번들을 설치하지 않고 [package]``salt-minion``을 계속 사용하는 것이 가능합니다.

자세한 내용은 xref:client-configuration:contact-methods-saltbundle.adoc[Salt Bundle]에서 확인할 수 있습니다.
====



[[registering.clients.bootstrap.register]]
== 부트스트랩 스크립트를 실행하는 클라이언트 등록

스크립트 생성을 완료했으면 이 스크립트를 사용해 클라이언트를 등록할 수 있습니다.


.절차: 부트스트랩 스크립트 실행
[role=procedure]
_____

. {productname} 컨테이너 호스트의 명령 프롬프트에서 루트 사용자로 다음 명령어를 실행하여 서버 컨테이너에 진입합니다.
+

----
mgrctl term
----
+

. {productname} 서버에서 부트스트랩 디렉토리로 변경합니다.

+

----
cd /srv/www/htdocs/pub/bootstrap/
----

+

. 다음 명령을 실행하여 클라이언트에서 부트스트랩 스크립트를 실행하고, [systemitem]``EXAMPLE.COM``을 클라이언트의 호스트 이름으로 교체합니다.

+

----
cat bootstrap-sles15.sh | ssh root@EXAMPLE.COM /bin/bash
----

+

. 또는 클라이언트에서 다음 명령을 실행합니다.

+

----
ACTIVATION_KEYS="17-someactivationkey" \
MGR_SERVER_HOSTNAME="proxy.example.com" \
ORG_GPG_KEY="mykey" \
REACTIVATION_KEY=my-reactivation-key \
curl -Sks https://server_hostname/pub/bootstrap/bootstrap.sh | /bin/bash
----

+

값을 재정의할 필요가 없는 경우 다음과 같이 환경 변수를 완전히 생략할 수 있습니다.

+

----
curl -Sks https://server_hostname/pub/bootstrap/bootstrap.sh | /bin/bash
----

+

[IMPORTANT]
====
문제를 해결하려면 [command]``bash`` 명령을 사용하여 부트스트랩 스크립트를 실행해 확인하십시오.
====

+

이 스크립트는 앞서 생성한 리포지토리 디렉토리에 있는 필수 종속성을 다운로드합니다.

+

. 스크립트 실행이 완료되면 클라이언트가 올바르게 등록되었는지 확인할 수 있습니다. productname} {webui}를 열고 menu:시스템[개요]로 이동하여 새 클라이언트가 나열되었는지 확인합니다. 클라이언트가 나열되지 않으면 {productname} {webui}에서 menu:Salt[키]로 이동하여 클라이언트 키가 허용되는지 확인합니다.

_____

[WARNING]
====
{productname}를 사용해 클라이언트에 새 패키지 또는 업데이트를 설치하면 최종 사용자 라이선스 계약(EULA)이 자동으로 수락됩니다. 패키지 EULA를 검토하려면 {webui}에서 패키지 상세 정보 페이지를 여십시오.
====

