[[suse-registration-overview]]
= SUSE 클라이언트 등록
:revdate: 2025-02-06
:page-revdate: {revdate}

ifeval::[{mlm-content} == true]

// SUSE Liberty Linux not available at Uyuni for now
{sle} 및 {sleses} 클라이언트를 {productname} 서버에 등록할 수 있습니다.
endif::[]

ifeval::[{uyuni-content} == true]

// SUSE Liberty Linux not available at Uyuni for now
{sle} 클라이언트를 {productname} 서버에 등록할 수 있습니다.
endif::[]


새 클라이언트를 {productname} 서버에 등록하려면 먼저 {webui} 또는 명령줄 도구를 사용하여 새 클라이언트의 운영 체제 및 아키텍처에 대한 소프트웨어 채널을 동기화합니다.

ifeval::[{uyuni-content} == true]

그런 다음 명령줄 도구를 사용하여 새로 추가된 운영 체제에 대한 클라이언트 도구 리포지토리를 동기화합니다.
endif::[]

방법과 자세한 내용은 클라이언트의 운영 체제에 따라 다릅니다. 이에 대한 자세한 내용은 다음 섹션에 설명되어 있습니다.



== 사전 단계 또는 확인


시작하기 전에 클라이언트의 날짜 및 시간이 {productname} 서버와 정확히 동기화되었는지 확인하십시오.

또한 활성화 키 생성을 완료한 상태이어야 합니다. 활성화 키 생성에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]를 참조하십시오.



[IMPORTANT]
====
{productname} 서버를 자체에 등록하지 마십시오. {productname} 서버는 개별적으로 또는 별도의 {productname} 서버를 사용해 관리해야 합니다. 여러 서버를 사용하는 방법에 대한 자세한 내용은 xref:specialized-guides:large-deployments/hub-multi-server.adoc[]에서 확인할 수 있습니다.
====



[[suse-registration-overview-check]]
== 이전 동기화 상태 확인

클라이언트가 이전에 SCC, SMT 또는 RMT에 등록되어 있는 경우, 클라이언트를 {productname} 서버로 마이그레이션하기 전에 [command]``SUSEConnect``로 해당 등록을 제거하십시오. 이전 등록을 먼저 제거해야 합니다. 그렇지 않으면 더 이상 필요하지 않은 리포지토리가 클라이언트가 {productname}이(가) 포함된 {suse} 운영 체제의 최신 버전으로 마이그레이션된 후에 클라이언트에 추가됩니다.

{sle} 12 또는 15 클라이언트의 등록을 취소하려면 클라이언트에서 루트 권한으로 다음을 실행합니다.

----
SUSEConnect --de-register
SUSEConnect --cleanup
----

자세한 정리 명령 및 확인 단계에 대한 자세한 내용은 https://www.suse.com/de-de/support/kb/doc/?id=000019054[]에서 확인할 수 있습니다.
