[[system-locking]]
= 시스템 잠금
:revdate: 2024-11-21
:page-revdate: {revdate}

시스템 잠금은 클라이언트에서 작업이 이루어지지 못하게 하는 데 사용됩니다. 예를 들어 시스템 잠금은 클라이언트가 업데이트되거나 다시 시작되지 못하게 합니다. 이 기능은 프로덕션 소프트웨어를 실행하는 클라이언트나 실수로 인한 변경 방지에 유용합니다. 작업을 수행할 준비가 되었으면 시스템 잠금을 비활성화할 수 있습니다.



== 클라이언트의 시스템 잠금


클라이언트가 잠겨 있거나 차단 모드 상태인 경우 작업을 예약할 수 없고, 실행 명령이 비활성화되며, [guimenu]``시스템 정보`` 페이지에 노란색 배너가 표시됩니다. 이 모드에서는 {webui} 또는 API를 사용해 잠긴 클라이언트에 대해 작업을 예약할 수 있지만 작업이 실패합니다.


[NOTE]
====
{salt} SSH 클라이언트에 대해서는 잠금 메커니즘을 사용할 수 없습니다.
====



.절차: 클라이언트의 시스템 잠금
. {productname} {webui}에서 잠그려는 클라이언트의 [guimenu]``시스템 정보`` 페이지로 이동합니다.
. [guimenu]``수식`` 탭으로 이동하여 시스템 잠금 수식의 확인란을 선택한 후 btn:[저장]을 클릭합니다.
. menu:수식[시스템 잠금] 탭으로 이동하여 [guimenu]``시스템 잠금``의 확인란을 선택한 후 btn:[저장]을 클릭합니다.
    이 페이지에서는 클라이언트가 잠겨 있는 동안 특정 Salt 모듈을 활성화할 수도 있습니다.
. 변경한 후 highstate를 적용해야 할 수 있습니다.
    이 경우 {webui}의 배너가 이를 알려줍니다. 시스템 잠금 수식을 제거할 때까지 클라이언트는 잠긴 상태를 유지합니다.

{salt}의 차단 모드에 대한 자세한 내용은 https://docs.saltproject.io/en/latest/topics/blackout[]에서 확인할 수 있습니다.



== 패키지 잠금

패키지 잠금은 여러 클라이언트에서 사용할 수 있지만, 서로 다른 기능 집합을 사용할 수 있습니다. {sle} 및 {opensuse}(zypp 기반) 클라이언트와 {rhel} 또는 {debian} 클라이언트를 구분해야 합니다.



=== Zypp 기반 시스템의 패키지 잠금

패키지 잠금은 무단 설치나 소프트웨어 패키지로 업그레이드하는 것을 방지하는 데 사용됩니다. 패키지가 잠겨 있으면 자물쇠 아이콘이 표시되어 설치할 수 없음을 나타냅니다. 잠긴 패키지를 설치하려는 모든 시도는 이벤트 로그에 오류로 보고됩니다.

잠긴 패키지는 {productname} {webui}를 통해 또는 패키지 관리자를 사용하는 클라이언트 시스템에서 직접 설치, 업그레이드 또는 제거할 수 없습니다. 잠긴 패키지는 모든 종속 패키지도 간접적으로 잠급니다.


.절차: 패키지 잠금 사용하기
. 관리되는 시스템에서 menu:소프트웨어[패키지 > 잠금] 탭으로 이동하여 사용 가능한 모든 패키지의 목록을 확인합니다.
. 잠글 패키지를 선택하고 btn:[잠금 요청]을 클릭합니다. 잠금을 활성화할 날짜와 시간을 선택합니다. 기본적으로 잠금은 가능한 한 빨리 활성화됩니다. 잠금이 즉시 활성화되지 않을 수 있습니다. 잠금이 즉시 활성화되지 않을 수 있다는 점에 유의하십시오.
. 패키지 잠금을 제거하려면 잠금을 해제할 패키지를 선택하고 btn:[잠금 해제 요청]을 클릭하십시오. 잠금을 활성화할 때와 같이 날짜와 시간을 선택합니다.



=== {rhel} 및 {debian} 유사 시스템의 패키지 잠금

[NOTE]
====
일부 {rhel} 및 {debian} 유사 시스템에는 클라이언트에서 사용할 수 있는 패키지 잠금이 있습니다.
====

{rhel} 및 {debian}과 같은 시스템에서 패키지 잠금은 소프트웨어 패키지에 대한 무단 업그레이드 또는 제거하는 것을 방지하는 데만 사용됩니다. 패키지가 잠겨 있으면 자물쇠 아이콘이 표시되어 변경할 수 없음을 나타냅니다. 잠긴 패키지를 설치하려는 모든 시도는 이벤트 로그에 오류로 보고됩니다.

잠긴 패키지는 {productname} {webui}를 통해 또는 패키지 관리자를 사용하는 클라이언트 시스템에서 직접 업그레이드 또는 제거할 수 없습니다. 잠긴 패키지는 모든 종속 패키지도 간접적으로 잠급니다.


.절차: 패키지 잠금 사용하기
. {rhel} 7 시스템에서는 [package]``yum-plugin-versionlock``을 설치하고, {rhel} 8 또는 9 시스템에서는 [package]``python3-dnf-plugin-versionlock``을 [systemitem]``루트``로 설치합니다. {debian} 시스템에서는 ``apt`` 도구에 잠금 기능이 포함되어 있습니다.
. 관리되는 시스템에서 menu:소프트웨어[패키지 > 잠금] 탭으로 이동하여 사용 가능한 모든 패키지의 목록을 확인합니다.
. 잠글 패키지를 선택하고 btn:[잠금 요청]을 클릭합니다. 잠금을 활성화할 날짜와 시간을 선택합니다. 기본적으로 잠금은 가능한 한 빨리 활성화됩니다. 잠금이 즉시 활성화되지 않을 수 있습니다. 잠금이 즉시 활성화되지 않을 수 있다는 점에 유의하십시오.
. 패키지 잠금을 제거하려면 잠금을 해제할 패키지를 선택하고 btn:[잠금 해제 요청]을 클릭하십시오. 잠금을 활성화할 때와 같이 날짜와 시간을 선택합니다.
