[[system-groups]]
= 시스템 그룹
:revdate: 2024-04-17
:page-revdate: {revdate}

시스템 그룹을 사용해 다수의 클라이언트를 더 쉽게 관리할 수 있습니다. 그룹을 사용해 업데이트, 구성 채널, salt 상태 또는 수식의 적용과 같은 대량 작업을 클라이언트에서 수행할 수 있습니다.

환경에 적합한 방식으로 클라이언트를 그룹으로 편성할 수 있습니다. 예를 들어 클라이언트를 설치되는 운영 체제, 있어야 할 물리적 위치 또는 처리하는 워크로드 유형에 따라 체계적으로 편성할 수 있습니다. 클라이언트가 속할 수 있는 그룹의 수에는 제한이 없으므로 그룹을 다양한 방식으로 정의할 수 있습니다.

클라이언트를 그룹으로 구성한 경우 하나 이상의 그룹에 있는 모든 클라이언트 또는 그룹 간의 교차점에서 업데이트를 수행할 수 있습니다. 예를 들어, 웹 서버 소프트웨어가 있는 모든 클라이언트를 한 그룹을 정의하고 모든 SLES 클라이언트를 다른 그룹을 정의할 수 있습니다. 그런 다음, 웹 서버 소프트웨어가 있는 모든 클라이언트에 대해 업데이트를 수행하거나 그룹 간의 교집합을 사용하여 웹 서버 소프트웨어가 있는 모든 SLES 클라이언트를 업데이트할 수 있습니다.



== 그룹 생성


몇 개의 그룹을 먼저 생성해야 이 그룹을 사용해 클라이언트를 편성할 수 있습니다.



.절차: 새 시스템 그룹 생성
. {productname} {webui}에서 menu:시스템[시스템 그룹]으로 이동합니다.
. btn:[그룹 생성]을 클릭합니다.
. 새 그룹에 이름 및 설명을 부여합니다.
. btn:[그룹 생성]을 클릭하여 그룹을 저장합니다.
. 필요한 각 그룹에 이 작업을 반복합니다.



== 클라이언트를 그룹에 추가

개별 클라이언트를 그룹에 추가하거나 여러 클라이언트를 동시에 추가할 수 있습니다.



.절차: 단일 클라이언트를 그룹에 추가
. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 추가할 클라이언트의 이름을 클릭합니다.
. menu:그룹[조인] 탭으로 이동합니다.
. 조인할 그룹의 확인란을 선택하고 btn:[선택한 그룹 조인]을 클릭합니다.



.절차: 여러 클라이언트를 그룹에 추가
. {productname} {webui}에서 menu:시스템[시스템 그룹]으로 이동하여 클라이언트를 추가할 그룹의 이름을 클릭합니다.
. [guimenu]``대상 시스템`` 탭으로 이동합니다.
. 추가할 클라이언트의 확인란을 선택하고 btn:[시스템 추가]를 클릭합니다.



.절차: SSM으로 여러 클라이언트를 그룹에 추가
. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 추가할 각 클라이언트의 확인란을 선택하면 클라이언트가 시스템 세트 관리자에 추가됩니다.
. menu:시스템[시스템 세트 관리자]로 이동한 후 [guimenu]``그룹`` 탭으로 이동합니다.
. 조인할 그룹을 찾아 [guimenu]``추가``의 확인란을 선택합니다.
. btn:[멤버쉽 변경]을 클릭합니다.
. btn:[확인]을 클릭하여 선택한 그룹에 클라이언트를 조인합니다.

시스템 세트 관리자에 대한 자세한 내용은 xref:client-configuration:system-set-manager.adoc[]에서 확인할 수 있습니다.



menu:시스템[시스템 그룹]으로 이동하여 그룹 이름을 클릭한 다음 [guimenu]``시스템`` 탭으로 이동하면 그룹에 속한 클라이언트를 확인할 수 있습니다.



== 그룹 작업

클라이언트를 그룹에 배치하고 나면 그룹을 사용해 업데이트를 관리할 수 있습니다.
// For Salt clients, you can also apply states and formulas to all clients in a group.

{productname} {webui}에서 menu:시스템[시스템 그룹]으로 이동합니다. 그룹 내 클라이언트 중 어느 하나에 대해서라도 사용할 수 있는 업데이트가 있는 경우 목록에 아이콘이 표시됩니다. 사용 가능한 업데이트에 대한 자세한 정보를 확인하고 업데이트를 클라이언트에 적용하려면 아이콘을 클릭합니다.

한 번에 두 개 이상의 그룹으로 작업할 수도 있습니다. 작업할 그룹을 선택하고 btn:[합집합 작업]을 클릭하여 선택한 각 그룹에서 각 클라이언트를 선택합니다.

또는 그룹의 교집합에서 작업할 수 있습니다. 두 개 이상의 그룹을 선택하고, btn:[교집합 작업]을 클릭하여 선택한 모든 그룹에 있는 클라이언트만 선택하십시오. 예를 들어, 웹 서버 소프트웨어가 있는 모든 클라이언트의 그룹이 1개와 모든 SLES 클라이언트의 그룹 1개가 있을 수 있습니다. 이 그룹의 교집합은 웹 서버 소프트웨어가 있는 모든 SLES 클라이언트가 됩니다.
