[[system-locking]]
= 시스템 잠금

시스템 잠금은 클라이언트에서 작업이 이루어지지 못하게 하는 데 사용됩니다. 예를 들어 시스템 잠금은 클라이언트가 업데이트되거나 다시 시작되지 못하게 합니다. 이 기능은 프로덕션 소프트웨어를 실행하는 클라이언트나 실수로 인한 변경 방지에 유용합니다. 작업을 수행할 준비가 되었으면 시스템 잠금을 비활성화할 수 있습니다.

시스템 잠금은 기존 클라이언트와 Salt 클라이언트에서 서로 다른 방식으로 구현됩니다.



== 기존 클라이언트의 시스템 잠금

기존 클라이언트가 잠겨 있으면 {webui}를 사용해 작업 일정을 잡을 수 없고, menu:시스템[시스템 목록]에서 클라이언트의 이름 옆에 자물쇠 아이콘이 표시됩니다.



.절차: 기존 클라이언트의 시스템 잠금
. {productname} {webui}에서 잠그려는 클라이언트의 [guimenu]``시스템 정보`` 페이지로 이동합니다.
. [guimenu]``잠금 상태``에서 btn:[이 시스템 잠그기]를 클릭합니다.
    btn:[이 시스템의 잠금 해제]를 클릭할 때까지 클라이언트는 잠긴 상태를 유지합니다.


원격 명령, 자동 패치 업데이트와 같은 몇 가지 작업은 잠긴 기존 클라이언트에서 여전히 완료할 수 있습니다. 자동 패치 업데이트를 중지하려면 클라이언트의 [guimenu]``시스템 정보`` 페이지로 이동하여 [guimenu]``등록 정보`` 탭에서 [guimenu]``업데이트 자동 패치``의 확인란을 선택 취소하십시오.



== Salt 클라이언트의 시스템 잠금

Salt 클라이언트가 잠겨 있거나 차단 모드 상태인 경우 작업의 일정을 잡을 수 없고, Salt 실행 명령이 비활성화되며, [guimenu]``시스템 정보`` 페이지에 노란색 배너가 표시됩니다. 이 모드에서는 {webui} 또는 API를 사용해 잠긴 클라이언트에 대해 작업 일정을 잡을 수는 있지만 작업이 실패합니다.


[NOTE]
====
Salt SSH 클라이언트에 대해서는 잠금 메커니즘을 사용할 수 없습니다.
====



.절차: Salt 클라이언트의 시스템 잠금
. {productname} {webui}에서 잠그려는 클라이언트의 [guimenu]``시스템 정보`` 페이지로 이동합니다.
. [guimenu]``수식`` 탭으로 이동하여 시스템 잠금 수식의 확인란을 선택한 후 btn:[Save]를 클릭합니다.
. menu:수식[시스템 잠금] 탭으로 이동하여 [guimenu]``시스템 잠금``의 확인란을 선택한 후 btn:[저장]를 클릭합니다.
    이 페이지에서는 클라이언트가 잠겨 있는 동안 특정 Salt 모듈을 활성화할 수도 있습니다.
. 변경한 후 highstate를 적용해야 할 수 있습니다.
    이 경우 {webui}의 배너가 이를 알려줍니다. 시스템 잠금 수식을 제거할 때까지 클라이언트는 잠긴 상태를 유지합니다.


[NOTE]
====
{caasp}이 노드에서 감지되면 시스템 잠금 수식이 기본적으로 활성화됩니다.
====

Salt의 차단 모드에 대한 자세한 내용은 https://docs.saltstack.com/en/latest/topics/blackout/index.html을 참조하십시오.



== 패키지 잠금

[NOTE]
====
패키지 잠금은 Zypper 패키지 관리자를 사용하는 기존 클라이언트에서만 사용할 수 있습니다. 이 기능은 {rhel} 또는 Salt 클라이언트에서는 현재 지원하지 않습니다.
====

패키지 잠금은 기존 클라이언트에서 무단 설치나 소프트웨어 패키지로 업그레이드하는 것을 방지하는 데 사용됩니다. 패키지가 잠겨 있으면 자물쇠 아이콘이 표시되어 설치할 수 없음을 나타냅니다. 잠긴 패키지를 설치하려는 모든 시도는 이벤트 로그에 오류로 보고됩니다.

잠긴 패키지는 {productname} {webui}를 통해 또는 패키지 관리자를 사용하는 클라이언트 시스템에서 직접 설치, 업그레이드 또는 제거할 수 없습니다. 잠긴 패키지는 모든 종속 패키지도 간접적으로 잠급니다.


.절차: 패키지 잠금 사용하기
. 클라이언트 시스템에서 [systemitem]``루트`` 권한으로 다음과 같이 [package]``zypp-plugin-spacewalk``를 설치합니다.
+
----
zypper in zypp-plugin-spacewalk
----

. 관리되는 시스템에서 menu:소프트웨어[패키지 > 잠금] 탭으로 이동하여 사용 가능한 모든 패키지의 목록을 확인합니다.
. 잠글 패키지를 선택하고, btn:[잠금 요청]을 클릭합니다.
    활성화할 잠금에 대해 날짜 및 시간을 입력하는 것을 선택할 수도 있습니다. 잠금이 가능한 한 빨리 활성화되기 원한다면 날짜 및 시간을 공백으로 두십시오. 잠금이 즉시 활성화되지 않을 수 있다는 점에 유의하십시오.
. 패키지 잠금을 제거하려면 잠금을 해제할 패키지를 선택하고 btn:[잠금 해제 요청]을 클릭하십시오.
    잠금이 가능한 한 빨리 비활성화되기 원한다면 날짜 및 시간을 공백으로 두십시오. 잠금이 즉시 비활성화되지 않을 수 있습니다.
