[[troubleshooting-clients]]
= 클라이언트 문제 해결



== 자동 설치

기본 채널에 따라 새 자동 설치 프로파일이 필수 패키지가 누락된 채널에 가입될 수 있습니다.

자동 설치가 작동하려면 다음과 같은 패키지가 필요합니다.

* [package]``pyOpenSSL``
* [package]``rhnlib``
* [package]``libxml2-python``
* [package]``spacewalk-koan``

이 문제를 해결하려면 먼저 다음 사항을 확인하십시오.

* 자동 설치 프로파일의 기본 채널과 관련이 있는 도구 소프트웨어 채널이 조직 및 사용자에게 제공되는지 확인합니다.
* 도구 채널이 {productname}에 하위 채널로 제공되는지 확인합니다.
* 필수 패키지와 모든 종속성이 연결된 채널에 제공되는지 확인합니다.



== 베어메탈 시스템

네트워크의 베어메탈 시스템이 [guilabel]``시스템`` 목록에 자동으로 추가되지 않는 경우 먼저 다음 사항을 확인하십시오.

* [path]``pxe-default-image`` 패키지 설치를 완료한 상태이어야 합니다.
* 파일 경로 및 파라미터를 올바르게 구성해야 합니다. [path]``pxe-default-image``가 제공하는 [path]``vmlinuz0`` 및 [path]``initrd0.img`` 파일이 [path]``rhn.conf`` 구성 파일에 지정된 위치에 있는지 확인합니다.
* 베어메탈 시스템을 {productname} 서버에 연결하는 네트워킹 장비가 제대로 작동하고 있는지, 서버에서 {productname} 서버 IP 주소에 도달할 수 있는지 확인합니다.
* 조달할 베어메탈 시스템은 부팅 시퀀스에 PXE 부팅이 활성화되어 있어야 하며, 운영 체제를 부팅하려고 해서는 안 됩니다.
* DHCP 서버는 부팅 중에 DHCP 요청에 반드시 응답해야 합니다. PXE 부팅 메시지에서 다음 사항이 이루어지고 있는지 확인합니다.
** DHCP 서버가 예상 IP 주소를 할당하고 있습니다.
** DHCP 서버가 부팅을 위해 {productname} 서버 IP 주소를 [option]``next-server``로 할당하고 있습니다.
* Cobbler가 실행 중인지, 검색 기능이 활성화되어 있는지 확인합니다.

부팅 직후 파란색 Cobbler 메뉴가 보이면 검색이 시작된 것입니다. 완료되지 않는 경우 문제 진단에 도움이 되도록 일시적으로 자동 종료를 비활성화하십시오. 자동 종료를 비활성화하려면 다음과 같이 하십시오.

. Cobbler 메뉴에서 화살표 키로 [option]``pxe-default-profile``을 선택하고, 타이머가 만료되기 전에 <Tab> 키를 누릅니다.
. 통합된 편집기를 사용해 커널 부팅 파라미터인 [option]``spacewalk-finally=running``을 추가하고 <Enter> 키를 눌러 부팅을 계속합니다.
. 사용자 이름이 [option]``root``이고 비밀번호가 [option]``linux``인 셸을 입력하여 디버깅을 계속합니다.

[IMPORTANT]
.중복 프로파일
====
기술적 한계로 인해 새로운 베어메탈 시스템과 이전에 검색한 시스템을 확실히 구별할 수 없습니다. 따라서 베어메탈 시스템을 여러 차례 켜지 않는 것이 좋습니다. 그렇게 하면 중복 프로파일이 생기기 때문입니다.
====



== Bootstrap End-of-Life {centos} 6 Clients

{centos} 6 is now at end-of-life, and the images provided in the client repository for this operating system are out of date. Bootstrapping new {centos} 6 clients using these packages will fail. This failure will not happen on {centos} 6 clients that are already installed and bootstrapped.

If you need to bootstrap new {centos} 6 clients you can edit the existing repositories to reflect the correct URL.



.Procedure: Troubleshooting Bootstrapping a New {centos} 6 Client
. On the {centos} 6 client, at the command prompt, open the ``CentOS-Base.repo`` file, located in the ``/etc/yum.repos.d/`` directory.
. Locate the ``mirrorlist`` entry, pointing to ``mirrorlist.centos.org``. There may be more than one entry. For example:
+
----
mirrorlist=http://mirrorlist.centos.org/?release=6&arch=$basearch&repo=os
----
+
. Comment out the ``mirrorlist`` entry, to prevent the package manager looking for the URL.
. Edit the ``baseurl`` line to point to a ``vault.centos.org`` URL, and specify the {centos} 6 repositories. For example:
+
----
baseurl=https://vault.centos.org/centos/6/os/$basearch/
----
. Repeat for each repository listed in the file.
. Bootstrap the client. For more information about bootstrapping {centos} clients, see xref:client-configuration:clients-centos.adoc[].

For more information about the {centos} 6 end-of-life, see http://mirror.centos.org/centos/6/readme.



== 수명 종료 제품의 부트스트랩 리포지토리

지원하는 제품이 동기화되면 부트스트랩 리포지토리가 자동으로 생성되고 {productname} 서버에서 재생성됩니다. 제품이 수명 종료에 도달하여 지원이 중단된 경우 제품을 계속 사용하고 싶으면 부트스트랩 리포지토리를 수동으로 생성해야 합니다.

부트스트랩 리포지토리에 대한 자세한 내용은 xref:client-configuration:bootstrap-repository.adoc[]를 참조하십시오.



.절차: 수명 종료 제품의 부트스트랩 리포지토리 생성

. {productname} 서버의 명령 프롬프트에서 루트 권한으로 다음 예와 같이 [option]``--force`` 옵션을 이용해 사용 가능한 미지원 부트스트랩 리포지토리를 나열합니다.
+
----
mgr-create-bootstrap-repo --list --force
1. SLE-11-SP4-x86_64
 2. SLE-12-SP2-x86_64
 3. SLE-12-SP3-x86_64
----
. 다음과 같이 적절한 리포지토리 이름을 제품 레이블로 사용해 부트스트랩 리포지토리를 생성합니다.
+
----
mgr-create-bootstrap-repo --create SLE-12-SP2-x86_64 --force
----
부트스트랩 리포지토리를 수동으로 생성하고 싶지 않다면 필요한 제품 및 부트스트랩 리포지토리에 LTSS를 사용할 수 있는지 여부를 확인하시기 바랍니다.



== 복제된 Salt 클라이언트

하이퍼바이저 복제 유틸리티를 사용한 후 복제된 Salt 클라이언트를 등록하려 했다면 다음과 같은 오류가 표시될 수 있습니다.

----
죄송합니다. 시스템을 찾을 수 없습니다.
----

이러한 오류의 원인은 복제된 새 시스템에 등록된 기존 시스템과 동일한 시스템 ID가 있기 때문입니다. 이 ID를 수동으로 변경하여 오류를 바로잡고 복제된 시스템을 등록할 수 있습니다.


추가 정보 및 지침은 xref:administration:tshoot-registerclones.adoc[]를 참조하십시오.



== FQDNS grain 비활성화

FQDNS grain은 시스템에 있는 모든 전체 DNS 서비스의 목록을 반환합니다. 이 정보를 수집하는 작업은 대개 빠르게 완료되지만 DNS 설정이 잘못 구성된 경우 더 많은 시간이 소요될 수 있습니다. 어떤 경우 클라이언트는 무응답 상태가 되거나 작동을 중지할 수 있습니다.

이러한 문제를 방지하려면 Salt 플래그로 FQDNS grain을 비활성화하면 됩니다. grain을 비활성화하면 네트워크 모듈을 사용해 클라이언트가 무응답 상태가 될 위험 없이 FQDNS 서비스를 제공할 수 있습니다.

[NOTE]
====
이전 Salt 클라이언트에만 적용됩니다. 최근에 Salt 클라이언트를 등록했다면 FQDNS grain이 기본적으로 비활성화되어 있습니다.
====


{productname} 서버의 명령 프롬프트에서 다음 명령을 사용해 FQDNS grain을 비활성화합니다.

----
salt '*' state.sls util.mgr_disable_fqdns_grain
----

이 명령을 실행하면 각 클라이언트가 다시 시작되고 서버가 처리해야 하는 Salt 이벤트를 생성합니다. 클라이언트의 수가 매우 많은 경우 대신에 다음과 같이 배치 모드로 명령을 실행할 수 있습니다.

----
salt --batch-size 50 '*' state.sls util.mgr_disable_fqdns_grain
----

배치 명령이 실행을 완료할 때까지 기다립니다. kbd:[Ctrl+C]로 프로세스를 인터럽트하지 마십시오.



== noexec로 /tmp 마운팅

Salt는 클라이언트 파일 시스템의 [filename]``/tmp``에서 원격 명령을 실행합니다. 따라서 [option]``noexec`` 옵션으로 [filename]``/tmp``를 마운트해서는 안 됩니다.



== grain을 시작 이벤트로 전달

Salt 클라이언트는 시작할 때마다 ``machine_id`` grain을 {productname}로 전달합니다. {productname}는 이 grain을 사용해 클라이언트가 등록되었는지 여부를 판별합니다. 이 프로세스를 진행하려면 동기 Salt 호출이 필요합니다. 동기 Salt 호출은 다른 프로세스를 차단하므로 다수의 클라이언트가 동시에 시작하는 경우 프로세스가 상당히 지연될 수 있습니다.

이 문제를 해결하기 위해 별도의 동기 Salt 호출을 방지할 수 있는 새로운 기능이 Salt에 도입되었습니다.

이 기능을 사용하려면 이 기능을 지원하는 클라이언트에서 클라이언트 구성에 구성 파라미터를 추가하면 됩니다.

이 프로세스가 더 원활히 진행되게 하려면 ``mgr_start_event_grains.sls`` 도우미 Salt 상태를 사용하면 됩니다.

[NOTE]
====
이전에 등록한 클라이언트에만 적용됩니다. 최근에 Salt 클라이언트를 등록했다면 이 구성 파라미터가 기본적으로 추가되어 있습니다.
====


{productname} 서버의 명령 프롬프트에서 다음 명령을 사용해 ``start_event_grains`` 구성 도우미를 활성화합니다.

----
salt '*' state.sls util.mgr_start_event_grains
----

이 명령은 필요한 구성을 클라이언트의 구성에 추가하고, 클라이언트가 다시 시작할 때 이 구성을 적용합니다. 클라이언트가 수가 매우 많은 경우 대신에 다음과 같이 배치 모드로 명령을 실행할 수 있습니다.

----
salt --batch-size 50 '*' state.sls mgr_start_event_grains
----



== 프록시 연결 및 FQDN

Sometimes clients connected through a proxy appear in the {webui}, but do not show that they are connected through a proxy. This can occur if you are not using the fully qualified domain name (FQDN) to connect, and the proxy is not known to {productname}.

이러한 동작을 교정하려면 다음과 같이 프록시의 클라이언트 구성 파일에서 추가 FQDN을 grain으로 지정하십시오.

----
grains:
  susemanager:
     custom_fqdns:
       - name.one
       - name.two
----



== Red Hat CDN Channel and Multiple Certificates

The {redhat} content delivery network (CDN) channels sometimes provide multiple certificates, but the {productname} {webui} can only import a single certificate. If CDN presents a certificate that is different to the one the {productname} {webui} knows about, validation fails and permission to access the repository is denied, even though the certificate is accurate. The error message received is:

----
[error]
Repository '<repo_name>' is invalid.
<repo.pem> Valid metadata not found at specified URL
History:
 - [|] Error trying to read from '<repo.pem>'
 - Permission to access '<repo.pem>' denied.
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository '<repo_nam' because of the above error.
Could not refresh the repositories because of errors.
HH:MM:SS RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
----

To resolve this issue, merge all valid certificates into a single ``.pem`` file, and rebuild the certificates for use by {productname}:



.Procedure: Resolving Multiple {redhat} CDN Certificates
. On the {redhat} client, at the command prompt, as root, gather all current certificates from ``/etc/pki/entitlement/`` in a single ``rh-cert.pem`` file:
+
----
cat 866705146090697087.pem 3539668047766796506.pem redhat-entitlement-authority.pem > rh-cert.pem
----
. Gather all current keys from ``/etc/pki/entitlement/`` in a single ``rh-key.pem`` file:
+
----
cat 866705146090697087-key.pem 3539668047766796506-key.pem > rh-key.pem
----

You can now import the new certificates to the {productname} Server, using the instructions in xref:client-configuration:clients-rh-cdn.adoc[].



== 이전 클라이언트 등록







{centos}{nbsp}6, {oracle}{nbsp}6, {rhel}{nbsp}6 또는 {sleses}{nbsp}6 클라이언트를 등록하고 사용하려면 {productname} 서버가 이전 형식의 SSL 암호화를 지원하도록 구성해야 합니다.

명령 프롬프트에서 등록하려 하면 다음과 같은 오류가 표시됩니다.

----
‘<Repository_Name>’ 리포지토리가 잘못되었습니다.
[|] 지정된 URL에서 유효한 메타데이터를 찾을 수 없습니다.
 이 리포지토리에 정의된 URI가 유효한 리포지토리를 가리키고 있는지 확인하시기 바랍니다.
 위 오류로 인해 ‘<Repository_Name>’ 리포지토리를 건너뛰는 중입니다.
 ‘www.example.com’에 대한 다운로드 (curl) 오류:
 오류 코드: 알 수 없는 오류
 오류 메시지: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert  protocol version
----

{webui}에서 등록하려 하면 다음과 같은 오류가 표시됩니다.

----
SLS ‘base:bootstrap’ 렌더링에 실패함: Jinja 오류: >>> RHEL6 및 SLES11을 위한 TLS 1.2 이상 버전이 없습니다. Apache 구성을 확인하시기 바랍니다.
 ...
----

이 오류는 Apache에 TLS{nbsp}v1.2가 필요하지만 이전 운영 체제가 이 버전의 TLS 프로토콜을 지원하지 않기 때문에 발생합니다. 이 오류를 수정하려면 서버의 Apache가 넓은 범위의 프로토콜 버전을 수락하도록 강제해야 합니다. {productname} 서버에서 루트 권한으로 [path]``/etc/apache2/ssl-global.conf`` 구성 파일을 열고, [systemitem]``SSLProtocol`` 줄을 찾아 다음과 같이 업데이트합니다.

----
SSLProtocol all -SSLv2 -SSLv3
----

이러한 업데이트는 서버에서 수동으로 완료해야 하며, 해당되는 경우 프록시에서 Salt 상태로 수행해야 합니다. 변경한 후 각 시스템에서 [systemitem]``apache`` 서비스를 다시 시작하십시오.
