[[vhm-caasp]]
= VHM 및 {caasp}

You can use a virtual host manager (VHM) to manage {caasp} clusters. The VHM allows {productname} to obtain and report information about your clusters. For more information on VHMs, see xref:client-configuration:vhm.adoc[].


[NOTE]
====
VHM을 사용하지 않고 {productname}에서 직접 {caasp} 클러스터를 관리할 수도 있습니다. 자세한 내용은 xref:client-configuration:virt-clusters.adoc[]를 참조하십시오.
====



== CaaSP 노드 온보딩

Salt 클라이언트와 동일한 방법을 사용해 각 {caasp} 노드를 {productname}에 등록할 수 있습니다. 자세한 내용은 xref:client-configuration:registration-overview.adoc[]를 참조하십시오.

{caasp} 채널을 연결할 활성화 키를 생성하여 연결된 노드를 온보딩하는 것이 좋습니다. 활성화 키에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]를 참조하십시오.

``cloud-init``을 사용 중인 경우 ``cloud-init`` 구성에서 부트스트랩 스크립트를 사용하는 것이 좋습니다. 부트스트래핑에 대한 자세한 내용은 xref:client-configuration:registration-bootstrap.adoc[]을 참조하십시오.

{caasp} 노드를 {productname}에 추가하면 등록한 시스템이 시스템 잠금 Salt 수식을 자동으로 적용하여 클라이언트에서 의도하지 않은 작업을 방지합니다. 시스템이 잠겨 있으면 {webui}가 경고를 표시하고 사용자는 {webui}나 API를 사용해 작업 일정을 잡을 수 있지만 작업은 실패합니다. 시스템 잠금에 대한 자세한 내용은 xref:client-configuration:system-locking.adoc[]을 참조하십시오.

구성 파일을 편집하여 시스템 잠금 수식을 비활성화함으로써 자동으로 적용되지 않게 할 수 있습니다. [path]``/etc/rhn/rhn.conf``를 열고 다음 줄을 파일 끝에 추가합니다.

다음 줄을 [path]``/etc/rhn/rhn.conf`` 파일 끝에 추가합니다.

----
java.automatic_system_lock_cluster_nodes = false
----

다음과 같이 spacewalk 서비스를 다시 시작하여 변경 사항을 반영합니다.

----
spacewalk-service restart
----

{kube} 관련 업데이트는 ``skuba-update`` 도구를 사용해 관리됩니다. 자세한 내용은 https://documentation.suse.com/suse-caasp/4/html/caasp-admin을 참조하십시오.


[WARNING]
====
{caasp} 노드에서 (UI 또는 API를 통해) Salt 또는 {productname}를 사용할 때 주의할 사항은 다음과 같습니다.

* 패치를 적용하지 마십시오(패치가 interactive로 표시된 경우).
* 패치를 자동으로 설치할 시스템을 표시하지 마십시오.
* Do not perform a product migration
* 노드를 재부팅하지 마십시오.
* Cobbler를 통해 전원 관리 작업을 발급하지 마십시오.
* 패키지가 `patterns-caasp-Node-x.y`를 중단하거나 이와 상충하는 경우 패키지를 설치하지 마십시오.
* 패키지가 `patterns-caasp-Node-x.y`를 중단하거나 이와 상충하는 경우, 또는 `patterns-caasp-Node-x.y`와 관련된 패키지 중 하나인 경우 패키지를 제거하지 마십시오.
* 패키지가 `patterns-caasp-Node-x.y`를 중단하거나 이와 상충하는 경우, 또는 `patterns-caasp-Node-x.y`와 관련된 패키지 중 하나인 경우 패키지를 업그레이드하지 마십시오.

이러한 작업을 발급하면 {caasp} 클러스터가 사용할 수 없게 될 수 있습니다. 시스템이 잠겨 있지 않으면 {productname}는 사용자가 이러한 작업을 발급하지 못하게 합니다.
====

== {caasp}{nbsp}4 노드의 자동 설치 프로파일

{caasp}{nbsp}4는 노드를 자동 설치하는 데 사용할 수 있는 AutoYaST 프로파일을 제공합니다. 이 프로파일은 ``patterns-caasp-Management`` 패키지에 있습니다. 프로파일에 대한 자세한 내용은 https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-deployment/#_autoyast_preparation을 참조하십시오.

{productname}를 사용할 수 있도록 사용자 정의되는 {caasp}{nbsp}4 템플릿 기반 예제를 보려면 https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST/CaaSP-autoinstall을 참조하십시오.

== {productname}로 {caasp} 클러스터 관리

{productname}를 사용해 하나 이상의 기존 {caasp} 클러스터를 관리할 수 있습니다.

[NOTE]
====
현재 {caasp}{nbsp}4만 지원합니다.
====


시작하기 전에 {caasp} 클러스터를 설치했는지 확인하십시오.

=== 관리 노드 선택

{caasp} 클러스터를 관리하려면 클라이언트를 클러스터의 관리 노드로 선택해야 합니다. 이 관리 노드는 클러스터에 속할 수 없고 시작하기 전에 연결된 {caasp} 채널이 있어야 합니다. 클러스터가 모두 같은 종류인 경우에 한해 여러 클러스터에 단일 관리 노드를 사용할 수 있습니다.



.절차: 관리 노드 선택
. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 관리 노드로 선택할 클라이언트의 이름을 클릭합니다
. menu:수식[구성] 탭으로 이동하여 ``CaaSP 관리 노드`` 수식의 확인란을 선택합니다.
. btn:[저장]을 클릭하고 highstate를 적용합니다.


[NOTE]
====
highstate가 완료될 때까지는 관리 노드를 사용할 수 없습니다.
====


menu:클러스터[개요]로 이동하여 알려진 모든 클러스터를 나열하십시오. 이 목록에는 클러스터 유형과 함께 모든 기존 클러스터와 이 기존 클러스터와 연결된 관리 노드가 표시됩니다. 노드가 {productname}에 등록되어 있는 경우 클러스터 내부에 있는 노드도 표시합니다. 클러스터 내부의 노드에 대해서는 역할, 상태, 업데이트 사용 가능 여부 등 ``skuba`` 및 {kube} API의 추가 정보가 표시됩니다.

노드에 사용할 수 있는 데이터에 대한 자세한 내용은 https://documentation.suse.com/suse-caasp/4/html/caasp-admin/_cluster_updates.html을 참조하십시오.

다음과 같이 클러스터에서 관리 노드까지의 구성을 준비해야 합니다.

. 클러스터에서 관리 노드까지 ``skuba`` 구성 디렉토리를 복사합니다.
    클러스터가 부트스트래핑된 후 ``skuba`` 서비스가 생성하는 디렉토리입니다. {productname} {webui}에 클러스터를 추가하기 위해 새 파일 위치를 적어 두십시오.

. 인증 방식을 입력합니다. 다음과 같이 이를 완료할 수 있는 두 가지 방법이 있습니다. 환경에 가장 적합한 방법을 선택하십시오.
클러스터 노드에 액세스하는 데 사용되는 비밀번호 없는 개인 SSH 키를 {productname} 서버에 복사하고, 파일 위치를 적어 둡니다. 현재 키와 향후 사용하려는 클라이언트의 키가 필요합니다.
  * ``ssh-agent`` 소켓을 사용할 수 있습니다. 클러스터를 설정할 때 소켓 경로를 입력하십시오. ``ssh-agent``를 {caasp}에서 다음 두 가지 방식으로 사용할 수 있습니다.

    ** 로컬에서 ``ssh-agent``를 사용하는 경우:
    *** ssh-agent를 로컬에서 시작: ``eval $(ssh-agent)``
    *** SSH 키 추가: ``ssh-add <key>``
    *** 에이전트에 액세스하는 데 사용되는 소켓은 ``$SSH_AGENT`` 환경 변수에서 사용할 수 있습니다.

    ** 다른 시스템에서 관리 노드로 `ssh-agent`를 전달하는 경우:

      *** 원본 시스템에서: ``ssh -A <management node>``. 소켓 경로는 ``$SSH_AGENT`` 환경 변수에서도 사용할 수 있습니다.

[NOTE]
====
``ssh-agent`` 방법을 사용 중인 경우 소켓의 경로는 새 ``ssh-agent``가 시작되거나 새 ``ssh -A`` 연결이 시작될 때마다 변경됩니다. ``ssh-agent`` 소켓 경로는 {productname} {webui}에서 언제든지 업데이트할 수 있습니다. SSH 액세스가 필요한 클러스터 작업을 시작할 때 소켓 경로가 무효화될 수도 있습니다.
====


=== 클러스터 관리

{productname}에서 클러스터를 관리하려면 {webui}에서 클러스터를 추가하십시오.



.절차: 기존 클러스터 추가
. {productname} {webui}에서 menu:클러스터[개요]로 이동하여 btn:[FIXME]를 추가합니다.
. 프롬프트의 지시에 따라 클러스터 유형 등 클러스터에 대한 정보를 입력하고 연결할 관리 노드를 선택합니다.
. 클러스터의 ``skuba`` 구성 파일 경로를 입력합니다.
. 사용하려는 비밀번호 없는 SSH 키 또는 ``ssh-agent`` 소켓의 경로를 입력합니다.
. 클러스터의 이름, 레이블 및 설명을 입력합니다.
. btn:[FIXME]를 클릭합니다.


{productname}로 관리하는 각 클러스터에 대해 해당 시스템 그룹이 생성됩니다. 기본적으로 시스템 그룹은 ``클러스터<cluster_name>``라고 합니다. 시스템 그룹을 새로 고침하여 노드 목록을 업데이트합니다. {productname}에 알려진 노드만 표시됩니다.


{productname}에서 menu:클러스터[개요]로 이동하여 삭제할 클러스터의 확인란을 선택 취소하고 btn:[클러스터 삭제]를 클릭하여 클러스터를 제거할 수 있습니다.


[IMPORTANT]
====
클러스터를 삭제하면 {productname}에서 클러스터가 제거되며 클러스터 노드는 삭제되지 않습니다. 클러스터에서 실행되는 워크로드는 인터럽트되지 않고 계속됩니다.
====



=== 노드 관리

{productname}에서 클러스터 생성을 완료하고 나면 클러스터 내에서 노드를 관리할 수 있습니다.

클러스터에 새 노드를 추가하기 전에 비밀번호 없는 SSH를 사용해 추가하려는 노드 또는 전달하려는 ``ssh-agent`` 소켓에 관리 노드가 액세스할 수 있는지 확인합니다.

추가하려는 노드가 {productname}에 등록되어 있고 {caasp} 채널이 할당되어 있는지도 확인해야 합니다.


.절차: 클러스터에 노드 추가
. {productname} {webui}에서 menu:클러스터[개요]로 이동하여 btn:[노드 조인]을 클릭합니다.
. 사용 가능한 노드 목록에서 추가할 노드를 선택합니다.
    사용 가능한 노드 목록은 {productname}에 등록된 노드, 관리 노드가 아닌 노드, 현재 클러스터의 일부가 아닌 노드만 포함합니다.
. 프롬프트의 지시에 따라 추가할 노드에 대해 {caasp} 파라미터를 입력합니다.
. 옵션: 추가할 노드에 대해서만 유효한 사용자 정의 ``ssh-agent`` 소켓을 지정합니다.
. btn:[저장]을 클릭하여 노드 추가 작업의 일정을 잡습니다.
    이 작업 중에 {productname}는 바꾸기를 비활성화하여 노드를 조인할 준비를 한 다음, 노드를 클러스터에 조인합니다.



.절차: 클러스터에서 노드 제거
. {productname} {webui}에서 menu:클러스터[개요]로 이동하여 제거할 노드의 확인란을 선택한 다음, btn:[노드 제거]를 클릭합니다.
. 프롬프트의 지시에 따라 제거할 노드에 대해 파라미터를 정의합니다.
. 옵션: 제거할 노드에 대해서만 유효한 사용자 정의 ``ssh-agent`` 소켓을 지정합니다.
. btn:[저장]을 클릭하여 노드 제거 작업의 일정을 잡습니다.

노드 제거에 대한 자세한 내용은 https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_permanent_removal을 참조하십시오.



==== 클러스터 업그레이드

클러스터에 사용 가능한 업데이트가 있는 경우 {productname}를 사용해 업그레이드 일정을 잡고 업그레이드를 관리할 수 있습니다.

{productname}는 먼저 모든 제어 플레인을 업그레이드한 다음, 작업자를 업그레이드합니다. 자세한 내용은 https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_cluster_updates를 참조하십시오.


.절차: 클러스터 업그레이드
. {productname} {webui}에서 menu:클러스터[개요]로 이동하여 업그레이드할 클러스터를 클릭합니다.
. 옵션: 업그레이드를 위해 사용자 정의하는 데 사용할 수 있는 {caasp} 파라미터가 없습니다.
    하지만 업그레이드할 노드에 대해서만 유효한 사용자 정의 ``ssh-agent`` 소켓을 지정할 수 있습니다.
. btn:[저장]을 클릭하여 클러스터 업그레이드 작업의 일정을 잡습니다.


[NOTE]
====
{productname}는 클러스터 업그레이드를 위해 ``skuba``와만 상호 작용합니다. 필요한 다른 작업(예: 구성 변경)은 {productname}가 발급하지 않습니다.
====


업그레이드에 대한 자세한 내용은 https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4를 참조하십시오.
