[[vhm-aws]]
= 가상 호스트 관리자 및 Amazon Web Services
:revdate: 2025-02-06
:page-revdate: {revdate}

// 2024-04-04 OM: It had been decided in the conversation with the mlm PO 
// that this Public Cloud related file can stay in the Uyuni books


가상 호스트 관리자(VHM)을 사용하여 Amazon Web Services(AWS)에서 인스턴스를 수집할 수 있습니다.

VHM을 통해 {productname}는 클러스터에 대한 정보를 획득하고 보고할 수 있습니다. VHM에 대한 자세한 내용은 xref:client-configuration:vhm.adoc[]을 참조하십시오.



== Amazon EC2 VHM 생성



가상 호스트 관리자(VHM)는 {productname} 서버에서 실행됩니다.

{productname} 서버에 [systemitem]``virtual-host-gatherer-libcloud`` 패키지를 설치했는지 확인하십시오.


.절차: Amazon EC2 VHM 생성

. {productname} {webui}에서 menu:시스템[가상 호스트 관리자]로 이동합니다.
. btn:[생성]을 클릭하고 드롭다운 메뉴에서 [guimenu]``Amazon EC2``를 선택합니다.
. [guimenu]``Amazon EC2 가상 호스트 관리자 추가`` 섹션에서 다음과 같은 파라미터를 사용합니다.
* [guimenu]``레이블`` 필드에 VHM의 사용자 정의 이름을 입력합니다.
* [guimenu]``액세스 키 ID`` 필드에서 Amazon이 제공하는 액세스 키 ID를 입력합니다.
* [guimenu]``비밀 액세스 키`` 필드에 Amazon 인스턴스에 연결된 비밀 액세스 키를 입력합니다.
* [guimenu]``지역`` 필드에 사용할 지역을 입력합니다.
* [guimenu]`` 영역`` 필드에 VM이 있는 영역을 입력합니다. 이 영역은 작업과 일치하는 구독에 필요합니다. 지역 및 영역 설정에 대한 자세한 설명은 <<susesupport_and_vm_zones>>에서 확인할 수 있습니다.
. btn:[생성]을 클릭하여 변경 사항을 저장하고 VHM을 생성합니다.
. [guimenu]``가상 호스트 관리자`` 페이지에서 새 VHM을 선택합니다.
. [guimenu]``등록 정보`` 페이지에서 btn:[데이터 새로 고침]을 클릭하여 새 VHM을 목록에 포함합니다.

어떤 객체 및 리소스가 목록에 포함되었는지 확인하려면 menu:시스템[시스템 목록 > 가상 시스템]으로 이동하십시오.


Amazon 공용 클라우드에서 실행되는 인스턴스는 ``i`` 뒤에 17개의 16진 숫자가 나오는 형식으로 {productname} 서버에 UUID를 보고합니다.

----
I1234567890abcdef0
----


ifeval::[{mlm-content} == true]

[[susesupport_and_vm_zones]]
== SUSE 지원 및 VM 영역

공용 클라우드 공급자는 가상 머신을 제공하는 데이터센터의 물리적, 지리적 위치를 지역을 사용해 정의합니다. [systemitem]``미국 동부`` 또는 [systemitem]``아시아``를 예로 들 수 있습니다.

이어서 지역은 영역으로 한층 더 구분됩니다. 예를 들어 [systemitem]``미국 동부`` 지역은 특히 [systemitem]``us-east-2a`` 및 [systemitem]``us-east-2b``라고 하는 영역을 포함할 수 있습니다.

{suse}는 제공할 적절한 구독을 가상 머신 영역을 사용해 결정합니다. 모든 VM을 동일한 영역에서 제공하는 경우 ``1-2 가상 머신`` 구독의 규정 및 조건을 충족합니다.

VM을 여러 영역에서 제공하는 경우 동일한 지역 내에 있는 영역이라 하더라도 ``1-2 가상 머신`` 구독의 조건을 충족하지 못할 수 있습니다. 이 경우 구독을 주의 깊게 확인하십시오.

[NOTE]
====
{byos} 인스턴스({byoslongform})의 경우 설치된 모든 제품이 구독 선택기로 전달됩니다. 퍼블릭 클라우드 인스턴스가 {payg}({payglongform})인 경우, 해당 기본 제품은 구독 선택기 계산에서 제외됩니다.

인스턴스가 {payg} 또는 {byos}인지에 대한 계산은 등록 시점에 또는 하드웨어 새로 고침 작업이 실행될 때 수행됩니다.
====

자세한 내용은 https://www.suse.com/products/terms_and_conditions.pdf[]를 참조하거나 {suse}에 문의하십시오.

endif::[]




== 가상 호스트 관리자에 대한 AWS 권한

보안상의 이유로 항상 수행할 작업에 가능한 최소 권한을 부여해야 합니다. 사용자에게 과도한 권한이 있는 액세스 키를 사용하여 AWS에 연결하는 것은 권장되지 않습니다.

{productname}이(가) AWS에서 필요한 정보를 수집하기 위해서는 VHM에 EC2 인스턴스 및 주소를 설명할 수 있는 권한이 필요합니다. 이러한 권한을 부여할 수 있는 한 가지 방법은 이 작업과 관련된 새 IAM 사용자(ID 및 액세스 관리)를 생성하고 다음과 같이 정책을 생성한 후 사용자에게 연결하는 것입니다.

----
{
    "버전": "2012-10-17",
    "설명":[
        {
            "효과": "허용",
            "동작": [
                "ec2:DescribeAddresses",
                "ec2:DescribeInstances"
            ],
            "리소스": "*"
        }
    ]
}
----


특정 영역에 대한 액세스를 제한하여 권한을 자세하게 제한할 수 있습니다. 자세한 내용은 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ExamplePolicies_EC2.html#iam-example-read-only[]를 참조하십시오.
