[[virt-caasp]]
= 클러스터

{productname}를 사용해 {caasp} 클러스터를 직접 관리할 수 있습니다. {webui}에서 menu:클러스터[개요]로 이동하여 {productname}에서 등록한 클러스터를 관리하십시오.



== 자동 설치 프로파일

{caasp}{nbsp}4는 노드를 자동 설치하는 데 사용할 수 있는 AutoYaST 프로파일을 제공합니다. 이 프로파일은 ``patterns-caasp-Management`` 패키지에 있습니다.




{productname}를 사용해 하나 이상의 기존 {caasp} 클러스터를 관리할 수 있습니다.

[NOTE]
====
현재 {caasp}{nbsp}4만 지원합니다.
====


시작하기 전에 {caasp} 클러스터를 설치했는지 확인하십시오.



== 관리 노드 선택

{caasp} 클러스터를 관리하려면 클라이언트를 클러스터의 관리 노드로 선택해야 합니다. 이 관리 노드는 클러스터에 속할 수 없고 시작하기 전에 연결된 {caasp} 채널이 있어야 합니다. 클러스터가 모두 같은 종류인 경우에 한해 여러 클러스터에 단일 관리 노드를 사용할 수 있습니다.



.절차: 관리 노드 선택
. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 관리 노드로 선택할 클라이언트의 이름을 클릭합니다
. menu:수식[구성] 탭으로 이동하여 ``CaaSP 관리 노드`` 수식의 확인란을 선택합니다.
. btn:[저장]을 클릭하고 highstate를 적용합니다.


[NOTE]
====
highstate가 완료될 때까지는 관리 노드를 사용하지 마십시오.
====


menu:클러스터[개요]로 이동하여 알려진 모든 클러스터를 나열하십시오. 이 목록에는 클러스터 유형과 함께 모든 기존 클러스터와 이 기존 클러스터와 연결된 관리 노드가 표시됩니다. 노드가 {productname}에 등록되어 있는 경우 클러스터 내부에 있는 노드도 표시합니다. 클러스터 내부의 노드에 대해서는 역할, 상태, 업데이트 사용 가능 여부 등 ``skuba`` 및 {kube} API의 추가 정보가 표시됩니다.




.절차: 관리 노드 구성
. 클러스터에서 관리 노드까지 ``skuba`` 구성 디렉토리를 복사합니다.
    클러스터가 부트스트래핑된 후 ``skuba`` 서비스가 생성하는 디렉토리입니다. {productname} {webui}에 클러스터를 추가하기 위해 새 파일 위치를 적어 두십시오.
. 인증 방식을 입력합니다.

다음과 같이 {caasp} 클러스터를 인증할 수 있는 두 가지 방법이 있습니다. 환경에 가장 적합한 방법을 선택하십시오.

* 클러스터 노드에 액세스하는 데 사용되는 비밀번호 없는 개인 SSH 키를 {productname} 서버에 복사하고, 파일 위치를 적어 둡니다.
    현재 키와 향후 사용하려는 클라이언트의 키가 필요합니다.
* ``ssh-agent`` 소켓을 사용할 수 있습니다. 클러스터를 설정할 때 소켓 경로를 입력하십시오.

``ssh-agent``를 {caasp}에서 두 가지 방식으로 사용할 수 있습니다. 다음과 같이 ``ssh-agent``를 로컬에서 사용하거나 다른 시스템에서 `ssh-agent`를 관리 노드로 전달할 수 있습니다.



.절차: 로컬 ssh-agent 사용
. 관리 노드의 명령 프롬프트에서 다음과 같이 ``ssh-agent`` 서비스를 시작합니다.
+
----
eval $(ssh-agent)
----
. SSH 키 추가:
+
----
ssh-add <key>
----
. 에이전트에 액세스하는 데 사용되는 소켓은 ``$SSH_AUTH_SOCK`` 환경 변수에서 사용할 수 있습니다.



.절차: ssh-agent를 관리 노드로 전달
. ``ssh-agent``를 제공하는 시스템의 명령 프롬프트에서 다음과 같이 SSH 전달을 활성화하고, 관리 노드의 호스트 이름을 지정합니다.
+
----
ssh -A <management node>
----
. 에이전트에 액세스하는 데 사용되는 소켓은 ``$SSH_AUTH_SOCK`` 환경 변수에서 사용할 수 있습니다.


[NOTE]
====
``ssh-agent`` 방법을 사용 중인 경우 소켓의 경로는 새 ``ssh-agent``가 시작되거나 새 ``ssh -A`` 연결이 시작될 때마다 변경됩니다. ``ssh-agent`` 소켓 경로는 {productname} {webui}에서 언제든지 업데이트할 수 있습니다. SSH 액세스가 필요한 클러스터 작업을 시작할 때 소켓 경로가 무효화될 수도 있습니다.
====



== 클러스터 관리

{productname}에서 클러스터를 관리하려면 {webui}에서 클러스터를 추가하십시오.



.절차: 기존 클러스터 추가
. {productname} {webui}에서 menu:클러스터[개요]로 이동하여 btn:[추가]를 클릭합니다.
. 프롬프트의 지시에 따라 클러스터 유형 등 클러스터에 대한 정보를 입력하고 연결할 관리 노드를 선택합니다.
. 클러스터의 ``skuba`` 구성 파일 경로를 입력합니다.
. 사용하려는 비밀번호 없는 SSH 키 또는 ``ssh-agent`` 소켓의 경로를 입력합니다.
. 클러스터의 이름, 레이블 및 설명을 입력합니다.
. btn:[추가]를 클릭합니다.


{productname}로 관리하는 각 클러스터에 대해 해당 시스템 그룹이 생성됩니다. 기본적으로 시스템 그룹은 ``클러스터<cluster_name>``라고 합니다. 시스템 그룹을 새로 고침하여 노드 목록을 업데이트합니다. {productname}에 알려진 노드만 표시됩니다.


{productname}에서 menu:클러스터[개요]로 이동하여 삭제할 클러스터의 확인란을 선택 취소하고 btn:[클러스터 삭제]를 클릭하여 클러스터를 제거할 수 있습니다.


[IMPORTANT]
====
클러스터를 삭제하면 {productname}에서 클러스터가 제거되며 클러스터 노드는 삭제되지 않습니다. 클러스터에서 실행되는 워크로드는 인터럽트되지 않고 계속됩니다.
====



== 노드 관리

{productname}에서 클러스터 생성을 완료하고 나면 클러스터 내에서 노드를 관리할 수 있습니다.

클러스터에 새 노드를 추가하기 전에 비밀번호 없는 SSH를 사용해 추가하려는 노드 또는 전달하려는 ``ssh-agent`` 소켓에 관리 노드가 액세스할 수 있는지 확인합니다.

추가하려는 노드가 {productname}에 등록되어 있고 {caasp} 채널이 할당되어 있는지도 확인해야 합니다.

클러스터에 노드를 추가하기 전에 몇 가지 수동 구성을 해야 할 수 있습니다. 시스템이 {caasp} 노드로 배타적으로 사용되고 있고 스왑이 꺼져 있는지 확인하십시오. 자세한 내용은 https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-deployment/#_disabling_swap을 참조하십시오.



.절차: 클러스터에 노드 추가
. {productname} {webui}에서 menu:클러스터[개요]로 이동하여 btn:[노드 조인]을 클릭합니다.
. 사용 가능한 노드 목록에서 추가할 노드를 선택합니다.
    사용 가능한 노드 목록은 {productname}에 등록된 노드, 관리 노드가 아닌 노드, 현재 클러스터의 일부가 아닌 노드만 포함합니다.
. 프롬프트의 지시에 따라 추가할 노드에 대해 {caasp} 파라미터를 입력합니다.
. 옵션: 추가할 노드에 대해서만 유효한 사용자 정의 ``ssh-agent`` 소켓을 지정합니다.
. btn:[저장]을 클릭하여 {caasp} 클러스터에 노드를 추가하는 작업의 일정을 잡습니다 .



.절차: 클러스터에서 노드 제거
. {productname} {webui}에서 menu:클러스터[개요]로 이동하여 제거할 노드의 확인란을 선택한 다음, btn:[노드 제거]를 클릭합니다.
. 프롬프트의 지시에 따라 제거할 노드에 대해 파라미터를 정의합니다.
. 옵션: 제거할 노드에 대해서만 유효한 사용자 정의 ``ssh-agent`` 소켓을 지정합니다.
. btn:[저장]을 클릭하여 노드 제거 작업의 일정을 잡습니다.

노드 제거에 대한 자세한 내용은 https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_permanent_removal을 참조하십시오.



== 클러스터 업그레이드

클러스터에 사용 가능한 업데이트가 있는 경우 {productname}를 사용해 업그레이드 일정을 잡고 업그레이드를 관리할 수 있습니다.

{productname}는 먼저 모든 제어 플레인을 업그레이드한 다음, 작업자를 업그레이드합니다. 자세한 내용은 https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_cluster_updates를 참조하십시오.


.절차: 클러스터 업그레이드
. {productname} {webui}에서 menu:클러스터[개요]로 이동하여 업그레이드할 클러스터를 클릭합니다.
. 옵션: 업그레이드를 위해 사용자 정의하는 데 사용할 수 있는 {caasp} 파라미터가 없습니다.
    하지만 업그레이드할 노드에 대해서만 유효한 사용자 정의 ``ssh-agent`` 소켓을 지정할 수 있습니다.
. btn:[저장]을 클릭하여 클러스터 업그레이드 작업의 일정을 잡습니다.


[NOTE]
====
{productname}는 클러스터 업그레이드를 위해 ``skuba``와만 상호 작용합니다. 필요한 다른 작업(예: 구성 변경)은 {productname}가 발급하지 않습니다.
====


업그레이드에 대한 자세한 내용은 https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4를 참조하십시오.
