[[troubleshooting-corrupt-repos]]
= 破損したリポジトリのトラブルシューティング
:description: 破損したリポジトリの問題を、リポジトリデータの再生成で解決し、更新をスムーズに行う方法を学びましょう。
:revdate: 2024-11-26
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメントチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

リポジトリメタデータファイルの情報が破損したり、古くなったりすることがあります。
これにより、クライアントの更新に問題が生じる可能性があります。
ファイルを削除し、その後リポジトリメタデータを再生成することで解決できます。
新しいリポジトリデータファイルを使用すれば、更新は期待通りに動作するはずです。

.プロシージャ:破損したリポジトリデータの修復方法
. `/var/cache/rhn/repodata/<channel-label>`からすべてのファイルを削除してください。
    チャンネルラベルが分からない場合は、{productname} {webui}で確認できます。menu:ソフトウェア[チャンネル> チャンネルラベル]に移動してください。
. コンテナホストで、コマンドラインから、次のコマンドを実行してコンテナ内のファイルを再生成します。
+
----
mgrctl exec -ti -- spacecmd softwarechannel_regenerateyumcache <channel-label>
----
