[[troubleshooting-inactive-clients]]
= 無効なクライアントのトラブルシューティング
:description: 原因を特定し、SUSE Multi-Linux Manager Serverへの接続の問題を解決することで、非アクティブなクライアントをトラブルシューティングします。
:revdate: 2025-01-08
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

Taskomaticジョブは、クライアントが接続されていることを確認するために定期的にクライアントにpingを送信します。
クライアントが24時間以上Taskomaticのチェックに応答していない場合、非アクティブと見なされます。
{webui}内の非アクティブなクライアントのリストを表示するには、menu:システム[システムリスト> 非アクティブ]に移動します。

クライアントはさまざまな理由で無効になる可能性があります。

* クライアントは、いかなる{productname}サービスにも権利がありません。
* クライアントがHTTPS接続を許可しないファイアウォールの背後にある。
* クライアントが誤って設定されたプロキシの背後にある。
* クライアントが異なる{productname}サーバと通信しているか、接続が正しく設定されていません。
* クライアントが{productname}サーバと通信できるネットワーク内にありません。
* ファイアウォールがクライアントと{productname}サーバ間のトラフィックをブロックしています。
* Taskomaticが正しく設定されていない。


サーバへのクライアント接続に関する詳細については、xref:client-configuration:contact-methods-intro.adoc[]を参照してください。

ポート設定に関する詳細については、xref:installation-and-upgrade:network-requirements.adoc#ports[]を参照してください。

ファイアウォールのトラブルシューティングに関する詳細については、xref:administration:troubleshooting/tshoot-firewalls.adoc[]を参照してください。
