[[troubleshooting-taskomatic]]
= Taskomaticのトラブルシューティング
:description: Taskomatic（中央集約型リポジトリ管理システム）のトラブルシューティングと問題解決について学ぶ
:revdate: 2024-05-15
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////


リポジトリメタデータの再生成は比較的負荷の高い処理であるため、Taskomaticがこの処理を完了するまでに数分かかることがあります。
さらに、Taskomaticがクラッシュした場合、リポジトリメタデータの再生成が中断される可能性があります。

[IMPORTANT]
====
サーバコンテナ内のシェルにアクセスするには、コンテナホストで`mgrctl term`を実行します。
====

Taskomaticがまだ実行中であるか、処理がクラッシュした場合、{webui}にパッケージの更新が利用可能に見えることがありますが、クライアントには表示されず、クライアントの更新を試みると失敗します。
この場合、`zypper ref`コマンドは次のようなエラーを表示します：

----
Valid metadata not found at specified URL
----

これを修正するには、Taskomaticがまだリポジトリメタデータの生成を行っているか、クラッシュが発生した可能性があるかを確認します。
メタデータの再生成が完了するのを待つか、クラッシュ後にTaskomaticを再起動して、クライアントの更新が正しく行われるようにします。



.プロシージャ:Taskomaticの問題の解決

. {productname}サーバで、`/var/log/rhn/rhn_taskomatic_daemon.log`ファイルを確認して、メタデータ再生成処理がまだ実行中であるか、クラッシュが発生したかどうかを判断します。
. taskomaticを再起動します。
+
----
service taskomatic restart
----
+
. Taskomaticログファイルで、次のような開始および終了行を検索することで、メタデータ再生成に関連するセクションを特定できます。
+
----
<YYYY-DD-MM> <HH:MM:SS>,174 [Thread-584] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Generating new repository metadata for channel 'cloned-2018-q1-sles12-sp3-updates-x86_64'(sha256) 550 packages, 140 errata

...

<YYYY-DD-MM> <HH:MM:SS>,704 [Thread-584] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Repository metadata generation for 'cloned-2018-q1-sles12-sp3-updates-x86_64' finished in 4 seconds
----
