[[troubleshooting-rpc-timeout]]
= RPC接続タイムアウトのトラブルシューティング
:description: RPC接続タイムアウトを設定して、パッケージのダウンロードやバッチジョブがハングしないように、関連する設定ファイルで許可される最大時間を調整します。
:revdate: 2022-10-18
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

RPC接続は、遅いネットワークやネットワークリンクのダウンにより、タイムアウトすることがあります。
これにより、パッケージのダウンロードやバッチジョブがハングしたり、予想以上に時間がかかることになります。
RPC接続がかかる最大時間は、設定ファイルを編集することで調整できます。
これはネットワークの問題を解決するものではありませんが、プロセスがハングするのではなく失敗する原因となります。


.プロシージャ:RPC接続タイムアウトの解決

. {productname}サーバーで、`/etc/rhn/rhn.conf`ファイルを開いて、最大タイムアウト値（秒単位）を設定します。

+

----
server.timeout =`number`
----

+

. {productname}プロキシで、`/etc/uyuni/proxy/config.yaml`ファイルを開いて、最大タイムアウト値（秒単位）を設定します。
変更を有効にするには、プロキシコンテナを再起動する必要があります。

+

----
timeout =`number`
----

+

. zypperを使用する{sles}クライアントで、`/etc/zypp/zypp.conf`ファイルを開いて、最大タイムアウト値（秒単位）を設定します。

+

----
## Valid values:  [0,3600]
## Default value: 180
download.transfer_timeout = 180
----

+

. yumを使用する{rhel}クライアントで、`/etc/yum.conf`ファイルを開いて、最大タイムアウト値（秒単位）を設定します。

+

----
timeout =`number`
----

[NOTE]
====
RPCタイムアウトを`180`秒未満に制限すると、完全に正常な操作が中断されるリスクがあります。
====
