[[troubleshooting-register-clones]]
= クローンクライアントの登録のトラブルシューティング
:description: 重複するマシンIDを解決し、SUSE Multi-Linux Managerでクローンクライアントを正しく登録し、その手順を学びましょう。
:revdate: 2025-04-24
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////


仮想マシンを管理するために{productname}を使用している場合、VMのクローンを作成することが役立つかもしれません。
クローンとは、既存のディスクの正確なコピーであるプライマリディスクを使用するVMです。

仮想マシンのクローンを作成すると時間を大幅に節約できますが、ディスク上の識別情報が重複しているために問題が発生する可能性があります。

すでに登録されているクライアントがあり、そのクライアントのクローンを作成してからクローンを登録しようとする場合、{productname}でそれらを2つの別々のクライアントとして登録したいと考えるでしょう。
ただし、元のクライアントとクローンの両方のマシンIDが同じ場合、{productname}は両方のクライアントを1つのシステムとして登録し、その結果、既存のクライアントデータはクローンのデータで上書きされます。

これは、クローンのマシンIDを変更することで解決でき、{productname}がそれらを2つの異なるクライアントとして認識できるようになります。

[NOTE]
====
この手順の各ステップは、すべてクローンクライアントで実行されます。
この手順は元のクライアントを操作せず、元のクライアントは{productname}に引き続き登録されたままです。
====



.プロシージャ:クローンされたSaltクライアントでの重複するマシンIDの解決
[role=procedure]
____

. *初期のシステム設定*


.. クローンマシンで、ホスト名とIPアドレスを変更します。
    `/etc/hosts`に加えた変更と正しいホストエントリが含まれていることを確認してください。


. *重複するマシンIDの解決*

.. _systemdをサポートしているディストリビューションの場合:_

...   マシンに同じマシンIDがある場合は、rootとして、複製された各クライアントのファイルを削除し、再作成します。

+

----
rm /etc/machine-id
rm /var/lib/dbus/machine-id
rm /var/lib/zypp/AnonymousUniqueId
dbus-uuidgen --ensure
systemd-machine-id-setup
----

+

... クローンされたマシンが`/var/log/journal/`にフォルダーを持っている場合は、それを新しいマシンIDに合わせて名前を変更する必要があります。名前が一致しない場合、`journalctl`はログを取得できず、`podman logs`には何も表示されません。

+

----
mv /var/log/journal/* /var/log/journal/$(cat /etc/machine-id)
----

+

.. _systemdをサポートしていないディストリビューションの場合:_

...  systemdをサポートしないディストリビューションの場合: rootとして、dbusからマシンIDを生成します。

+

----
rm /var/lib/dbus/machine-id
rm /var/lib/zypp/AnonymousUniqueId
dbus-uuidgen --ensure
----

+ 

[IMPORTANT]
====

* 後で{sll}に解放される{rhel} 8.10サーバーのクローンを作成する場合は、カーネル設定ファイルを修正するために追加の手順を実行する必要があります。


* {rhel}はマシンIDを使用して、`/boot/loader/entries`にカーネルエントリーを生成します。
これらの手順を実行しないと、解放後に古いカーネルエントリーと新しいカーネルエントリーが混在することになります。なぜなら、{sll}カーネルは古いエントリーを置き換えるのではなく、新しいエントリーを作成するためです。


* マシンIDの変更後、および解放前に、次のコマンドを実行します。

+

----
sudo rm -rf /boot/loader/entries/
sudo for ver in $(rpm -q kernel --qf '%{VERSION}-%{RELEASE}.%{ARCH}\n'); do echo "Reinstalling kernel $ver..."; sudo kernel-install add $ver /lib/modules/$ver; done
sudo grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
----

* {rhel} 8.10サーバーの解放に関する詳細情報や例については、xref:common-workflows:workflow-liberate-rhel-with-secureboot.adoc[]を参照してください。

====

. *クライアントの再構成{salt}*

.. クライアントがまだ同じSaltクライアントIDを持っている場合は、各クライアントの`minion_id`ファイルを削除してください（クライアントの再起動時に再生成される際、FQDNが使用されます）。

...  Salt Bundleクライアントの場合:

+

----
rm /etc/salt/minion_id
rm -rf /etc/salt/pki
----

+

... Salt Bundleクライアントの場合:

+

----
rm /etc/venv-salt-minion/minion_id
rm -rf /etc/venv-salt-minion/pki
----

+

.. オンボーディングページから受諾されたキーと、{productname}からシステムプロファイルを削除し、その後クライアントを再起動してください。

... Salt Bundleクライアントの場合:

+

----
service salt-minion restart
----

+

... Salt Bundleクライアントの場合:


+

----
service venv-salt-minion restart
----

+

.. クライアントを再登録します。
   各クライアントは現在異なる`/etc/machine-id`を持っており、`System Overview`ページに正しく表示されるはずです。

____
