[[troubleshooting-remote-root-on-micro]]
= でのリモートルートログイン{sl-micro}
:description: SL Microでのパスワードベースのリモートルートログインを有効にして、SUSE Multi-Linux Managerのコンポーネントを安全にデプロイおよび設定します。
:revdate: 2025-06-17
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

セキュリティを強化するために、{sl-micro} 6.1以降の新しいインストールでは、パスワードベースのリモートルートログインが許可されなくなり、{sl-micro}上で実行されているサーバーおよびプロキシコンテナホストや管理された{sl-micro}クライアントにも影響します。
また、パスワードベースのリモートルートログインを持つ{sle-micro} 5.5クライアントは、6.1/6.2に移行されると、このアクセスを突然失い、新たに構成する必要があります。
詳細については、SL Microリリースノート6.1をご覧ください（ https://www.suse.com/releasenotes/x86_64/SL-Micro/6.1/index.html#jsc-SMO-405）。

{productname}のコンポーネント（{productname}プロキシなど）をデプロイする際には、デフォルトでパスワードベースのリモートルートログインが必要です。
次の手順でパスワードベースのリモートルートログインを有効にできます。


.プロシージャ:{sl-micro}でのパスワードを使用したSSHルートログインの有効化
[role=procedure]
____
SSHルートログインを有効にする方法は2つあります。
どちらも機能しますので、あなたの設定に最も適したものを選んでください。

.オプションA:事前設定されたパッケージを使用する

. クライアントのUI/APIからパッケージ`openssh-server-config-rootlogin`をインストールします。

. UIまたは端末からコンテナホストを再起動して新しい設定を有効化します。

.オプションB:SSH設定を手動で編集する

. 以下の内容で、ドロップイン設定`/etc/ssh/sshd_config.d/permit_root.conf`ファイルを追加します。

+
----
PermitRootLogin yes
----

. サーバ設定
+
[source,shell]
----
systemctl reload sshd
----

. SSHを使用して接続している場合、サーバから切断する前に、新しいSSH接続を開いてSSHサーバが正しく機能していることを確認します。

____


`transactional-update`の詳細については、 https://documentation.suse.com/sle-micro/6.1/html/Micro-transactional-updates/.を参照してください。

