[[troubleshooting-customchannel]]
= パッケージが競合するカスタムチャンネルのトラブルシューティング
:description: YaSTツールを使用してカスタムチャンネルを作成する際の競合を回避する方法を学び、スムーズなインストールプロセスを確保します。
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

////
Cause: Conflicting packages in custom channel
Consequence: Creating bootstrap repo can fail
Fix: Separate trees from each other
Result: Clean and functional boostrap repo will be created
////

パッケージが競合するカスタムチャンネルを設定する場合、ブートストラップリポジトリの作成などの機能が未定義の動作を引き起こし、クライアントの登録に失敗する可能性があります。

例えば、より高いバージョン番号の競合するパッケージがブートストラップリポジトリに含まれる可能性があります。
そのようなパッケージ（例えば、`python3-zmq`や`zeromq`）は、起動リポジトリの作成を損ねたり、クライアントの起動中に問題が生じる可能性があります。

カスタムチャンネル（例えば、EPELチャンネル）が親ベンダーチャンネルの下に追加されると、競合するパッケージに関する問題は直接解決できません。
これを解決する方法は、カスタムチャンネルをベンダーチャンネルから分離することです。
カスタムチャンネルは別のツリーで作成する必要があります。
カスタムチャンネルを子として配信する必要がある場合、そのような環境はコンテンツライフサイクル管理（CLM）を使用して作成できます。
CLMプロジェクト内のソースは、異なるツリーから追加できます。
このようなアプローチを使用すると、カスタムチャンネルは構築環境内で親の下に留まります。
ただし、ベンダーチャンネルツリーはカスタムチャンネルとブートストラップリポジトリなしで維持されます。
その後、クライアントの登録が正しく機能します。

競合するパッケージ（salt、zeromqなど）を持つカスタムチャンネルを子チャンネルとして作成する場合は、次のステップに従うことで問題を回避できます。

.プロシージャ:カスタムチャンネルで競合するパッケージを回避する

. 親チャンネルから子チャンネルとしてのカスタムチャンネルを削除します。
  詳細については、xref:administration:custom-channels.adoc#_manage_custom_channels[]を参照してください。
. カスタムチャンネルを別のツリーで作成します。
  詳細については、xref:administration:custom-channels.adoc#_creating_custom_channels_and_repositories[]を参照してください。
. コンテンツライフサイクル管理（CLM）内で子チャンネルとしてカスタムチャンネルを取得するには、次の手順に従います。
+
* {productname} {webui}で、menu:コンテンツライフサイクル[]に移動し、btn:[プロジェクトを作成]をクリックします。
  `Name`と`Label`を入力してください。
* ソースをプロジェクトに割り当てます。
  必要なベンダチャンネルとカスタムチャンネルを使用します。  (CentOS8を使用した共有例)
* プロジェクトに環境を追加します。 例えば、CentOS8を使用します。
* 環境を構築するには、btn:[ビルド]ボタンをクリックします。
  これにより、アクティベーションキーに関連付けて、クライアントのブートストラップに使用できるベンダチャンネルとカスタムチャンネルを備えた環境が作成されます。
. 重要:CLMプロジェクトでは、問題のあるパッケージや競合するパッケージを除外するフィルタを追加することをお勧めします。
  そうしないと、クライアントの更新中に高いバージョン番号の競合するパッケージがインストールされることになります。
  フィルタ処理の詳細については、xref:administration:content-lifecycle-examples.adoc#exclude-higher-kernel-version[]を参照してください。
. 最新のパッチをCLM環境(ベンダチャンネルおよびカスタムチャンネルを使用)に取得するには、プロジェクトのbtn:[ビルド]ボタンをクリックします。
  これは、環境を再構築するために必要です。

* CLMの詳細については、xref:administration:content-lifecycle.adoc[]を参照してください。

ifeval::[{mlm-content} == true]

[NOTE]
====
Extra Packages for Enterprise Linux (EPEL)を{rhel}クライアント（または互換性のある{sll}、{centos}、{oracle}など）で直接使用すると、EPELから{salt}パッケージがインストールされ、{productname}が提供する{salt}パッケージにあるいくつかの機能が欠落します。
これは特に重要です。なぜなら、非SUSE {salt}パッケージを含むブートストラップリポジトリが生成されるからです。
したがって、これはサポートされていないシナリオです。

EPELリポジトリを有効にする必要がある場合は、事前にEPELから{salt}パッケージをフィルタで除外してください（たとえば、menu:ソフトウェア[管理> チャンネル> EPEL> パッケージ]で{salt}パッケージを削除します）。
====
endif::[]
