[[troubleshooting-schema-upgrade-fails]]
= スキーマのアップグレードが失敗する場合のトラブルシューティング
:description: Spacewalkサービスにおけるスキーマアップグレードのエラーのトラブルシューティングおよび解決方法を学び、データベースバージョンチェックエラーの原因を特定し、理解する。
:revdate: 2024-05-15
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////

PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step

////



スキーマアップグレードがエラーの場合、データベースバージョンチェックと他のすべてのSpacewalkサービスが起動しません。
詳細情報や進め方のヒントを得るには、コンテナホストで`mgradm start`を実行してください。

[IMPORTANT]
====
サーバコンテナ内のシェルにアクセスするには、コンテナホストで`mgrctl term`を実行します。
====

バージョン確認をコンテナ上で直接実行することもできます。

----
systemctl status uyuni-check-database.service
----

または

----
journalctl -u uyuni-check-database.service
----

より一般的な`mgradm`コマンドを実行したくない場合、これらのコマンドを実行するとデバッグ情報が出力されます。
