[[troubleshooting-not-enough-disk-space]]
= 十分なディスク容量がない場合のトラブルシューティング
:description: 成功する移行のために、利用可能なディスクスペースを確認し、重要なファイルを別のXFSファイルシステムに移動し、fstabを編集してディスクスペースを構成します。
:revdate: 2022-10-18
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////

PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step

////


移行を開始する前に、利用可能なディスクスペースを確認してください。
`/var/spacewalk`と`/var/lib/pgsql`は、別々のXFSファイルシステム上に配置することをお勧めします。

別のファイルシステムをセットアップする際は、`/etc/fstab`を編集し、`/var/lib/pqsql`サブボリュームを削除する。
変更を反映させるためにサーバを再起動してください。

アップグレードの問題に関する詳細情報を得るには、移行のログファイルを確認してください。
ログファイルは、アップグレード対象のシステムの`/var/log/rhn/migration.log`にあります。

