[[troubleshooting-packages]]
= パッケージの不整合のトラブルシューティング
:description: SUSE Multi-Linux Manager Serverを使用してパッケージの不整合をトラブルシューティングする方法を学び、クライアントの更新が成功するようにします。
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

クライアント上のパッケージがロックされている場合、{productname}サーバーは適用可能なパッチのセットを正しく判断できないことがあります。
このような場合、パッケージの更新は{webui}に利用可能ですが、クライアントには表示されず、クライアントの更新を試みると失敗します。
クライアント上でパッケージのロックと除外リストをチェックして、パッケージがロックされているか、除外されているかを判断します。

クライアント上で、パッケージのロックと除外リストをチェックして、パッケージがロックされているか、除外されているかを判断します。

// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{mlm-content} == true]

* Expanded Support Platformで、`/etc/yum.conf`を確認し、`exclude=`を検索します。
endif::[]

* {sle}および{opensuse}で、`zypper locks`コマンドを使用します。
