[[autoinst-cdrom]]
= Install via a CD-ROM or a USB Key

For clients that are not yet registered to {productname}, and if network boot over PXE is not an option, a bootable CD-ROM or USB key can be used to install the system.

One option to prepare such a removable medium is to use Cobbler.
For information about using Cobbler to prepare an ISO image, see xref:client-configuration:autoinst-cdrom.adoc#build-iso-with-cobbler[Build an ISO Image With Cobbler].

The other option is to use mechanisms specific to the distribution:

* For {suse} systems, prepare an ISO image using KIWI.
  For information, see xref:client-configuration:autoinst-cdrom.adoc#build-iso-with-kiwi[Build a SUSE ISO Image With KIWI].

* For {redhat} systems, use ``mkisofs``.
  For information, see xref:client-configuration:autoinst-cdrom.adoc#build-iso-with-mkisofs[Build a RedHat ISO Image With mkisofs].

In all cases, you use the resulting image to burn a CD-ROM or prepare a USB key.


[[build-iso-with-cobbler]]
== Build an ISO Image With Cobbler

Cobbler can create ISO boot images that contain a set of distributions, kernels, and a menu that works in a similar way to a PXE installation.

[NOTE]
====
Building ISOs with Cobbler is not supported on {ibmz}.
====

In order to prepare an ISO image with Cobbler, you need to prepare a distribution and a profile, similar to using network boot over PXE.
For information about creating a distribution, see xref:client-configuration:autoinst-distributions.adoc[Autoinstallable Distributions].
For information about creating a profile, see xref:client-configuration:autoinst-profiles.adoc[Autoinstallation Profiles].

The Cobbler [command]``buildiso`` command takes parameters to define the name and output location of the boot ISO.
Specifying the distribution with [option]``--distro`` is mandatory when running [command]``buildiso`` command.

----
cobbler buildiso --iso=/path/to/boot.iso --distro=<your-distro-label>
----

To list the names of distributions and profiles stored by Cobbler, run the commands:

----
# cobbler distro list
# cobbler profile list
----

The boot ISO includes all profiles and systems by default.
You can limit which profiles and systems are used with the [option]``--profiles`` and [option]``--systems`` options.
For example:

----
cobbler buildiso --systems="system1 system2 system3" \
  --profiles="<your-profile1> <your-profile2> <your-profile3> --distro=<your-distro-label>"
----

[NOTE]
====
If you cannot write an ISO image to a public [path]``tmp`` directory, check your systemd settings in [path]``/usr/lib/systemd/system/cobblerd.service``.
====


[[build-iso-with-kiwi]]
== Build a SUSE ISO Image With KIWI

KIWI is an image creation system.
You can use KIWI to create a bootable ISO image to be used by the target system for installation of a {suse} system.
When the system is rebooted or switched on, it boots from the image, loads the {ay} configuration from your {productname}, and installs {sles} according to the {ay} profile.

To use the ISO image, boot the system and type `autoyast` at the prompt (assuming you left the label for the {ay}  boot as ``autoyast``).
Press kbd:[Enter] to begin the {ay}  installation.

////
we would love a bit more details - ebischoff
////

For more information about KIWI, see http://doc.opensuse.org/projects/kiwi/doc/.


[[build-iso-with-mkisofs]]
== Build a RedHat ISO Image With mkisofs

You can use [command]``mkisofs`` to create a bootable ISO image to be used by the target system for installation of a {redhat} system.
When the system is rebooted or switched on, it boots from the image, loads the {kickstart} configuration from your {productname}, and installs {rhel} according to the {kickstart} profile.



.Procedure: Building a Bootable ISO With mkisofs
. Copy the contents of [path]``/isolinux`` from the first CD-ROM of the target distribution.
. Edit the [path]``isolinux.cfg`` file to default to 'ks'.
  Change the 'ks' section to read:
+
----
label ks
kernel vmlinuz
  append text ks=`url` initrd=initrd.img lang= devfs=nomount \
    ramdisk_size=16438 `ksdevice`
----
+
IP address-based {kickstart} URLs look like this:
+
----
http://`my.manager.server`/kickstart/ks/mode/ip_range
----
+
The {kickstart} distribution defined via the IP range should match the distribution from which you are building, to prevent errors occurring.
. OPTIONAL: If you want to use the [replaceable]``ksdevice``, it looks like this:
+
----
ksdevice=eth0
----
+
It is possible to change the distribution for a Kickstart profile within a family, such as {rhel} AS 4 to {rhel} ES 4, by specifying the new distribution label.
Note that you cannot move between versions (4 to 5) or between updates (U1 to U2).
. Customize [path]``isolinux.cfg`` further as required.
  For example, you can add multiple options, different boot messages, or shorter timeout periods.
. Create the ISO with this command:
+
----
mkisofs -o file.iso -b isolinux.bin -c boot.cat -no-emul-boot \
  -boot-load-size 4 -boot-info-table -R -J -v -T isolinux/
----
+
Note that [path]``isolinux/`` is the relative path to the directory containing the modified isolinux files copied from the distribution CD, while [path]``file.iso`` is the output ISO file, which is placed into the current directory.
. Burn the ISO to CD-ROM and insert the disk.
  Alternatively prepare an USB key and insert it.
. Boot the system and type [command]``ks`` at the prompt (if you left the label for the Kickstart boot as 'ks').
. Press kbd:[Enter] to start {kickstart}.
