[[automatic-client-registration]]
= Automatic Client Registration


Newly created public cloud clients can be automatically registered to {productname}.

{productname} supports two ways of registering new cloud VMs:

* cloud-init based registration
* remote execution provisioner based regsitration

[[cloud-init-based-client-registration]]
== cloud-init based client registration

Registering by leveraging cloud-init is the preferred way of automatic registering of the newly created public cloud clients. 
This solution avoids configuring SSH connection to the host.
It can be used regardless of the tool used for clients creation. 

User can pass the set of user data when deploying the image, in order to create the image instance.
[literal]```user_data``` is run only once at bootstrap, and only the first time the instance is started. 

Before using cloud-init to register clients, the user must configure:

* Bootstrap script. See xref:client-configuration:registration-bootstrap.adoc[]
* Activation keys. See xref:client-configuration:activation-keys.adoc[]


This command will download the bootstrap script and register the new machine when it is created:
----
curl -s http://hub-server.tf.local/pub/bootstrap/bootstrap-default.sh | bash -s
----

[NOTE]
====
Anytime [literal]```user_data``` is updated to change the provisioning, Terraform will destroy and then recreate the machines with new IP etc.
====

For more information about cloud-init on AWS, see:  
. https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/cloudinit_config

For a cloud-init example, see:  
. https://registry.terraform.io/providers/hashicorp/cloudinit/latest/docs/data-sources/cloudinit_config#example-usage



[[remote-exec-provisioner-based-client-registration]]
== remote-exec provisioner based registration

The second solution for automatic registering of the  newly created public cloud uses Terraform's remote-exec provisioner.

remote-exec provisioner interacts with the newly created machines. 
It has access to open and SSH connections, and can run single or batch commands.

[IMPORTANT]
====
Before using remote-exec provisioner to register clients, the user must configure SSH connection between the machine running Terraform, and the recently created machine. 
====

The remaining requirements are the same as when using <<cloud-init-based-client-registration>> 

* Bootstrap script. See xref:client-configuration:registration-bootstrap.adoc[]
* Activation keys. See xref:client-configuration:activation-keys.adoc[]


This command will download the bootstrap script and register the new machine when it is created:
----
curl -s http://hub-server.tf.local/pub/bootstrap/bootstrap-default.sh | bash -s
----

For more information about remote-exec provisioner, see:
https://www.terraform.io/docs/provisioners/remote-exec.html

