[[autoyast-example]]
= AutoYast Example File

{suse} provides templates of various AutoYaST profiles in the https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST[SUSE/manager-build-profiles/AutoYaST] public GitHub repository.

Each script requires you to set some variables before you use it.
Check the ``README`` file included with the script to determine which variables you need.

Ensure that the distribution label corresponds to the autoinstallation distribution, available in the {webui} from menu:Systems[Autoinstallation > Distributions].

[NOTE]
====
It is required that you add the updates tools channel to the `<add-on>` {ay} snippet section.
This ensures your systems are provided with an up-to-date version of the `libzypp` package.
If you do not include the updates tools channel, you encounter `400` errors.
====

Set the variables (such as ``$c_server``) according to your environment.

For more information about using variables in {ay} scripts, see xref:client-configuration:autoinst-setup.adoc[].
