[[autoinst-unattended]]
= Unattended Provisioning



[[create-system-record]]
== Create a System Record Manually

You can use an API call to declare an association between a client identified by its MAC address and an autoinstallation profile.
Next time the system reboots, it starts the installation based on the specified profile.

.Procedure: Reinstallation From a Manually Declared Profile

. On the {productname} Server, at the command prompt, use the [systemitem]``system.createSystemRecord`` API call.
  In this example, replace [literal]``name`` with the name of your client, [literal]``<profile>`` with the profile label, [literal]``<iface>`` with the name of the interface on the client such as [literal]``eth0``, and [literal]``<hw_addr>`` with its hardware address such as [literal]``00:25:22:71:e7:c6``:
+
----
$ spacecmd api -- --args '["<name>", "<profile>", "", "", \
  [ {"name": "<iface>", "mac": "<hw_addr>"} ]]' \
  system.createSystemRecord
----
. Power on the client.
  It boots from the network, and the correct profile is selected for installation.

This command creates a system record at {cobbler}.
You may also specify additional parameters, like kernel options, the IP address of the client, and its domain name.
For more information, see the API documentation for [systemitem]``createSystemRecord call``.
