[[channels]]
= Software Channels

Channels are a method of grouping software packages.
Software packages are provided by repositories, and repositories are associated with channels.
Subscribing a client to a software channel allows the client to install and update any of the software associated with it.

In {productname}, channels are divided into base channels and child channels.
Organizing channels in this way ensures that only compatible packages are installed on each system.
A client must be subscribed to only one base channel, assigned during registration based on the client operating system and architecture.
For paid channels provided by a vendor, you must have an associated subscription.

A base channel consists of packages built for a specific operating system type, version, and architecture.
For example, the {sles}{nbsp}15 {x86_64} base channel contains only software compatible with that operating system and architecture.

A child channel is associated with a base channel and provides only packages that are compatible with the base channel.
A system can be subscribed to multiple child channels of its base channel.
When a system has been assigned to a base channel, it is only possible for that system to install the related child channels.
For example, if a system has been assigned to the {sles}{nbsp}15 `x86_64` base channel, they will only be able to install or update packages made available through the compatible base channel, or any of its associated child channels.

In the {productname} {webui} you can browse your available channels by navigating to menu:Software[Channel List > All].
You can modify or create new channels by navigating to menu:Software[Manage > Channels].

On Salt clients, you must apply the highstate after subscribing to the channel to be able to install packages.

For more on using channels, including custom channels, see xref:administration:channel-management.adoc[].



== Packages Provided by {phub}

{phub} is an extension to {sle} products that provides additional open source software provided by the {opensuse} community.

[IMPORTANT]
====
The packages in {phub} are provided by the {opensuse} community.
They are not supported by {suse}.
====

If you are using {sle} operating systems on your clients, you can enable the {phub} extension to access these additional packages.
This provides the {phub} channels, which you can subscribe your clients to.

{phub} provides a large number of packages, which can take a long time to synchronize and consume a large amount of disk space.
Do not enable {phub} unless you require the packages it provides.

To avoid unintentionally installing or updating unsupported packages, we recommended that you implement a content lifecycle management strategy that initially denies all {phub} packages.
You can then explicitly enable the specific packages you require.
For more information about content lifecycle management, see xref:administration:content-lifecycle.adoc[]



== Packages Provided by AppStream

AppStream is a modular package repository that provides additional software for most non-{suse} Linux distributions, including {redhat} and {oracle}.
In most cases, you will need to install the base channel for your distribution, and the appropriate AppStream channel to ensure that you have all the software you need.

If you need to transform AppStream repositories into non-modular repositories for use with some upgrade operations, you can use the AppStream filter with the content lifecycle management tool.
For more information about the AppStream filter, see xref:administration:content-lifecycle-examples.adoc[].



== Unified Installer Updates Channels on {sle} Clients

This channel is used by the unified installer to ensure it is up to date before it installs the operating system.
All {sle} proucts should have access to the installer updates channel during installation.

For {sles} clients the installer updates channel is synchronized by default when you add a product that contains them, and are enabled when you create an autoinstallation distribution with these product channels.

For all other {sle} variants, including {sle} for SAP,  you must add the installer updates channel manually.
To do this, clone the appropriate {sles} installer updates channel below the base channel of these {sle} variants.
When creating a autoinstallation distribution for these {sle} variants after the channel was cloned, it will be used automatically.
