[[channels]]
= Software Channels


Channels are a method of grouping software packages.
In {productname}, channels are divided into base channels and child channels.
Organizing channels in this way ensures that only compatible packages are installed on each system.

A base channel consists of packages built for a specific operating system type, version, and architecture.
For example, all of the packages in {sles}{nbsp}12 for the `x86_64` architecture make up a base channel.
The list of packages in {sles}{nbsp}12 for the `s390x` architecture make up a different base channel.
A system must be subscribed to only one base channel, which is assigned automatically during registration based on the {sle} release and system architecture.
For paid channels provided by a vendor, you must have an associated subscription.

A child channel is associated with a specific base channel and provides only packages that are compatible with that base channel.
A system can be subscribed to multiple child channels of its base channel.
When a system has been assigned to a base channel, it is only possible for that system to install the related child channels.
For example, if a system has been assigned to the {sles}{nbsp}12 `x86_64` base channel, they will only be able to install or update packages compatible with {sles}{nbsp}12 `x86_64`.

In the {productname} {webui} you can browse your available channels by navigating to menu:Software[Channel List > All].
You can modify or create new channels by navigating to menu:Software[Manage > Channels].

For more on using channels, including custom channels, see xref:administration:channel-management.adoc[].



== Using PackageHub Channels

Monotonectally synergize cooperative platforms for maintainable growth strategies. Interactively generate multidisciplinary users via enterprise catalysts for change. Phosfluorescently drive technically sound sources vis-a-vis competitive intellectual capital. Distinctively grow standards compliant partnerships with functionalized portals. Phosfluorescently initiate enterprise web-readiness with premium process improvements.



== Using Appstream Channels

Rapidiously reinvent optimal "outside the box" thinking and web-enabled human capital. Globally architect client-centered innovation after client-focused leadership skills. Appropriately extend error-free "outside the box" thinking rather than synergistic imperatives. Holisticly incubate extensible methodologies via quality niches. Quickly disintermediate cross-platform strategic theme areas with resource maximizing results.