[[clients-centos]]
= Registering {centos} Clients

This section contains information about registering traditional and Salt clients running {centos} operating systems.

[IMPORTANT]
====
{centos} clients are based on {centos} and are unrelated to {sleses}, RES, {redhat}, or {es}.
You are responsible for arranging access to {centos} base media repositories and {centos} installation media, as well as connecting {productname} Server to the {centos} content delivery network.
====

[NOTE]
====
Traditional clients are not available on {centos}{nbsp}8.
{centos}{nbsp}8 clients are only supported as Salt clients.
====

[NOTE]
====
Registering {centos} clients to {productname} is tested with the default SELinux configuration of ``enforcing`` with a ``targeted`` policy.
You do not need to disable SELinux to register {centos} clients to {productname}.
====



== Add Software Channels

Before you can register {centos} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: `x86_64` and `aarch64`.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

//The products you need for this procedure are:
For example, when working with `x86_64` architecture, you need this products:

[[centos-channels-wizard]]
[cols="1,1", options="header"]
.CentOS Products - WebUI
|===

| OS Version | Product Name
| {centos} 6 | CentOS 6 x86_64
| {centos} 7 | CentOS 7 x86_64
| {centos} 8 | CentOS 8 x86_64

|===

[NOTE]
====
{centos} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {centos} 6 clients using these packages will fail.
If you need to bootstrap new {centos} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[centos-channels-suma-cli]]
[cols="1,1", options="header"]
.CentOS Channels - CLI
|===

| OS Version | Base Channel
| {centos} 6 | centos6-x86_64
| {centos} 7 | centos7-x86_64
| {centos} 8 | centos8-x86_64

|===

[NOTE]
====
{centos} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {centos} 6 clients using these packages will fail.
If you need to bootstrap new {centos} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[centos-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.CentOS Channels - CLI
|===

| OS Version | Base Channel | Client Channel       | Updates/Appstream Channel
| {centos} 6 | centos6      | centos6-uyuni-client | centos6-updates
| {centos} 7 | centos7      | centos7-uyuni-client | centos7-updates
| {centos} 8 | centos8      | centos8-uyuni-client | centos8-appstream
|===

[NOTE]
====
{centos} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {centos} 6 clients using these packages will fail.
If you need to bootstrap new {centos} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_novendor_cli_multiarch.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]

ifeval::[{uyuni-content} == true]
[IMPORTANT]
====
For {centos} 8 clients, add both the Base and AppStream channels.
You require packages from both channels.
If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====
endif::[]

If you are using modular channels, you must enable the Python 3.6 module stream on the client.
If you do not provide Python 3.6, the installation of the [package]``spacecmd`` package will fail.

[NOTE]
====
You might notice some disparity in the number of packages available in the AppStream channel between upstream and the {productname} channel.
You might also see different numbers if you compare the same channel added at a different point in time.
This is due to the way that {centos} manages their repositories.
{centos} removes older version of packages when a new version is released, while {productname} keeps all of them, regardless of age.
====


include::snippets/appstream_admon.adoc[]


== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]


include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You need to create an activation key that is associated with your {centos} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].



ifeval::[{uyuni-content} == true]

== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]

endif::[]



== Register Clients

{centos} clients are registered in the same way as all other clients.
For more information, see xref:client-configuration:registration-overview.adoc[].


[WARNING]
====
To register and use {centos}{nbsp}6 clients, you need to configure the {productname} Server to support older types of SSL encryption.
For more information about how to resolve this error, see ``Registering Older Clients`` at xref:client-configuration:tshoot-clients.adoc[].
====



== Manage Errata

When you update {centos} clients, the packages do not include metadata about the updates.
You can use a third-party errata service to obtain this information.

[WARNING]
====

ifeval::[{suma-content} == true]

The third-party errata service described here, CEFS, is provided and maintained by the community.
It is not supported by {suse}.

endif::[]

The authors of CEFS provide patches or errata on a best-effort basis, in the hope they are useful but with no guarantees of correctness or currency.
This could mean that the patch dates could be incorrect, and in at least one case, the published data was shown to be more than a month old.
For more information on these cases, see https://github.com/stevemeier/cefs/issues/28#issuecomment-656579382 and https://github.com/stevemeier/cefs/issues/28#issuecomment-656573607.

Any problems or delays with the patch data might result in unreliable patch information being imported to your {productname} Server.
This would cause reports, audits, CVE updates, or other patch-related information to also be incorrect.
Please consider alternatives to using this service, such as independently verifying patch data, or choosing a different operating system, depending on your security-related requirements and certifications criteria.
====




.Procedure: Installing an Errata Service

. On the {productname} Server, from the command prompt, as root, add the ``sle-module-development-tools`` module:
+
----
SUSEConnect --product sle-module-development-tools/15.2/x86_64
----
. Install errata service dependencies:
+
----
zypper in  perl-Text-Unidecode
----
. Add or edit this line in [path]``/etc/rhn/rhn.conf``:
+
----
java.allow_adding_patches_via_api = centos7-updates-x86_64,centos7-x86_64,centos7-extras-x86_64
----
. Restart Tomcat:
+
----
systemctl restart tomcat
----
. Create a file for your errata script:
+
----
touch /usr/local/bin/cent-errata.sh
----
. Edit the new file to include this script, editing the repository details as required.
    This script fetches the errata details from an external errata service, unpacks it, and publishes the details:
+
----
#!/bin/bash
mkdir -p /usr/local/centos
cd /usr/local/centos
rm *.xml
wget -c http://cefs.steve-meier.de/errata.latest.xml
#wget -c https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml
wget -c https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
bzip2 -d com.redhat.rhsa-RHEL7.xml.bz2
wget -c http://cefs.steve-meier.de/errata-import.tar
tar xvf errata-import.tar
chmod +x /usr/local/centos/errata-import.pl
export SPACEWALK_USER='<adminname>';export SPACEWALK_PASS='<password>'
/usr/local/centos/errata-import.pl --server '<servername>' \
--errata /usr/local/centos/errata.latest.xml  \
--include-channels=centos7-updates-x86_64,centos7-x86_64,centos7-extras-x86_64 \
--publish --rhsa-oval /usr/local/centos/com.redhat.rhsa-RHEL7.xml
----
. Set up a cron job to run the script daily:
+
----
ln -s /usr/local/bin/cent-errata.sh /etc/cron.daily
----

For more information on this tool, see https://cefs.steve-meier.de/.
