[[clients-opensuseleapmicro]]
= Registering {leapmicro} Clients

This section contains information about registering clients running these {leapmicro} operating systems on {x86_64} and {aarch64} architectures.

The {leapmicro} is an ultra-reliable, lightweight operating system purpose built for edge computing.
It leverages the enterprise hardened security and compliance components of SUSE Linux Enterprise and merges them with a modern, immutable, developer-friendly OS platform.

The {leapmicro} uses transactional updates.
Transactional updates are atomic (all updates are applied only if all updates succeed) and support rollbacks.
They do not affect the running system because no changes are activated until the system is rebooted.
This information is displayed in the menu:Systems[Details > Overview] subtab.

For more information on transactional updates and rebooting, see
https://documentation.suse.com/sles/html/SLES-all/cha-transactional-updates.html.

ifeval::[{suma-content} == true]

// WARNING: The product names and channels for SCC here are a guess, and could change. Make sure you review them before publishing this for SUSE Manager!!!
[[opensuse-channels-wizard]]
[cols="1,1", options="header"]
.{opensuse} Products - WebUI
|===

| OS Version
| Product Name

| {leapmicro} 5.3
| {leapmicro} 5.3 {x86_64}

| {leapmicro} 5.3
| {leapmicro} 5.3 {aarch64}

|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[opensuse-leapmicro-channels-cli]]
[cols="1,1", options="header"]
.{opensuse} Channels - CLI
|===

| OS Version | Base Channel
| {leapmicro} | opensuse-leap-micro-5.3-pool

|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
[[opensuse-leapmicro-channels-cli]]

[cols="1,1", options="header"]
.{opensuse} Channels - CLI
|===

| OS Version          | {leapmicro} 5.x
| Base Channel	      | opensuse_micro5_x
| Client Channel      | opensuse_micro5_x-sle-updates
| SLE Updates Channel | opensuse_micro5_x-uyuni-client

|===

include::snippets/addchannels_novendor_cli.adoc[]

endif::[]


== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[IMPORTANT]
====
{leapmicro} channels can be very large.
Synchronization can sometimes take several hours.
====

== Register Clients

[WARNING]
====
{leapmicro} clients require reboot after registering.
Reboot is automatically scheduled after registration is completed, but it is respecting the default reboot manager maintenance window.
This window may be several hours after the client is registered.
To speed up {leapmicro} registration, manually reboot the client after the registration script finishes.
====

include::snippets/create_bootstrap_repo_register.adoc[]
