[[clients-amazon]]
= Registering {amazon} Clients

This section contains information about registering clients running {amazon} operating systems.

ifeval::[{mlm-content} == true]
// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====
* {amazon} repository URLs are available from {scclongform}
* Packages and metadata are provided by Amazon, not by {suse}
* For supported products, see the support table and the release notes
====
endif::[]



[WARNING]
====
When created at {aws}, {amazon} 2 instances always have the same `machine-id` id at `/etc/machine-id`.
If you are creating {amazon} 2 instances, make sure you regenerate the `machine-id` after the instances are created.
For more information, see xref:administration:troubleshooting/tshoot-registerclones.adoc[].

ifeval::[{uyuni-content} == true]
{amazon} 2023 is not affected by this.
endif::[]

====



== Add Software Channels

Before you register {amazon} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: `x86_64` and `aarch64`.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

include::snippets/arch-other-note.adoc[]

ifeval::[{mlm-content} == true]

//The products you need for this procedure are:
For example, when working with `x86_64` architecture, you need this product:

[[amazon-channels-wizard]]
[cols="1,1", options="header"]
.{amazon} Products - WebUI
|===

| OS Version | Product Name
| {amazon} 2 | {amazon} 2 x86_64

|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[amazon-channels-MLM-cli]]
[cols="1,1", options="header"]
.{amazon} Channels - CLI
|===

| OS Version | Base Channel
| {amazon} 2 | amazonlinux2-core-x86_64

|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[amazon-channels-uyuni-cli]]
[cols="1,1,1", options="header"]
.{amazon} Channels - CLI
|===

| OS Version
| Base Channel
| Client Channel

| {amazon} 2023
| amazonlinux2023
| amazonlinux2023-uyuni-client

| {amazon} 2
| amazonlinux2-core
| amazonlinux2-uyuni-client

|===


[NOTE]
====
For {amazon} 2, make sure you also add and synchronize `amazonlinux2-extra-docker` channel if you plan to use Docker at your {amazon} instances.
====

[NOTE]
====
For {amazon} 2023, make sure you also add and synchronize `amazonlinux2023-kernel-livepatch` channel if you plan to use Kernel Live patches at your {amazon} instances.
====

include::snippets/addchannels_novendor_cli.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]



== Check Synchronization Status

ifeval::[{mlm-content} == true]

include::snippets/check_sync_webui_mlm.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You need to create an activation key that is associated with your {amazon} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].



== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].



== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]
