[[clients-slemicro]]
= Registering {slemicro} Clients

This section contains information about registering clients running these {slemicro} Micro operating systems:

* {slemicro}{nbsp}5.0



== Prepare Custom Repositories and Channels

To mirror the software from the {suse} repositories, you need to create custom channels and repositories in {productname} that are linked to updates.suse.com by a URL.
You must have entitlements to these products in your {scc} account for this to work correctly.

[[IMPORTANT]]
====
Before you begin, ensure you have activated a {slemicro} subscription in {scc} for your {productname} organization.
====



.Procedure: Locate Custom Repository URLs
. In the {productname} {webui}, navigate to menu:Admin[Products], and refresh the product catalog.
  {slemicro} does not yet appear in the list.
. On the {productname} Server, at the command prompt, as root, determine which configuration file contains the repository information:
+
----
cd /var/lib/spacewalk/scc/scc-data/
grep -nro "SUSE-MicroOS-"
----
+
  The output of this command will be a list of filenames, the filename you want to look at will contain ``organizations_repositories`` in the filename.
  For example, ``AA1_organizations_repositories_page_1.json``.
. Open the configuration file, and locate the URLs for the MicroOS repositories.
  There are multiple entries that contain unique URLs.
  Take a note of the URLs for the ``SUSE-MicroOS-5.0-Updates`` and ``SUSE-MicroOS-5.0-Pool`` repositories:
+
----
{
  "id":1234,
  "url":"https://updates.suse.com/SUSE/Updates/SUSE-MicroOS/5.0/aarch64/update/?A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2",
  "name":"SUSE-MicroOS-5.0-Updates",
  "distro_target":"sle-15-aarch64",
  "description":"SUSE-MicroOS-5.0-Updates for sle-15-aarch64",
  "enabled":true,
  "autorefresh":true,
  "installer_updates":false
},

{
  "id":1234,
  "url":"https://updates.suse.com/SUSE/Products/SUSE-MicroOS/5.0/aarch64/product/?A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2",
  "name":"SUSE-MicroOS-5.0-Pool",
  "distro_target":"sle-15-aarch64",
  "description":"SUSE-MicroOS-5.0-Pool for sle-15-aarch64",
  "enabled":true,
  "autorefresh":false,
  "installer_updates":false
},
----


You can use these repository URLs to create custom repositories.
Create a repository for both ``SUSE-MicroOS-5.0-Pool`` and ``SUSE-MicroOS-5.0-Updates``, using the details from the configuration file.
You also need to create a client tools repository.


The details you need for this procedure are:

[[slemicro-repos-manual]]
[cols="1,1,1,1", options="header"]
.SLE Micro Custom Repository Settings
|===

| Option
| Pool repository
| Updates repository
| Client Tools repository

| Repository Label
| SUSE-MicroOS-5.0-Pool
| SUSE-MicroOS-5.0-Updates
| SUSE-MicroOS-5.0-Client-Tools

| Repository URL
| https://updates.suse.com/SUSE/Products/SUSE-MicroOS/5.0/aarch64/product/?<unique_code>
| https://updates.suse.com/SUSE/Updates/SUSE-MicroOS/5.0/aarch64/update/?<unique_code>
| *FIXME* https://download.opensuse.org/repositories/home:/pagarcia:/hackweek20:/SLEMicro5.0-Uyuni-Client-Tools/MicroOS/

| Repository Type
| yum
| yum
| yum

| Has Signed Metadata?
| Uncheck
| Uncheck
| Uncheck

|===

Leave all other fields blank.

include::snippets/manual_repos.adoc[]



When you have the three repositories created, you can create custom channels.

The details you need for this procedure are:

[[slemicro-channels-custom]]
[cols="1,1,1,1", options="header"]
.SLE Micro Custom Channel Settings
|===

| Option
| Base Channel
| Updates repository
| Client Tools repository

| Channel Name
| SLE Micro 5.0
| SLE Micro 5.0 Updates
| SLE Micro 5.0 Client Tools

| Channel Label
| suse-microos-5.0-pool
| suse-microos-5.0-updates
| suse-microos-5.0-client-tools

| Parent Channel
| None
| SLE Micro 5.0
| SLE Micro 5.0

| Architecture
| {x86_64}
| {x86_64}
| {x86_64}

| Repository Checksum Type
| sha256
| sha256
| sha256

| Channel Summary
| SUSE MicroOS 5.0 Base Channel
| SUSE MicroOS 5.0 Updates Channel
| SUSE MicroOS 5.0 Client Tools Channel

|===

Leave all other fields blank.

include::snippets/manual_channels.adoc[]

include::snippets/manual_associate.adoc[]



== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[IMPORTANT]
====
{slemicro} channels can be very large.
Synchronization can sometimes take several hours.
====



== Register Clients

To register your {slemicro} clients, you need a bootstrap repository.
By default, bootstrap repositories are automatically created, and regenerated daily for all synchronized products.
You can manually create the bootstrap repository from the command prompt, using this command:

----
mgr-create-bootstrap-repo
----

For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].
