[[clients-amazon]]
= Registering {amazon} Clients

This section contains information about registering traditional and Salt clients running {amazon} operating systems.

ifeval::[{suma-content} == true]
[IMPORTANT]
====
{amazon} repository URLs are available from {scc}, but the packages and metadata are provided by Amazon, not by {suse}.
====
endif::[]


[IMPORTANT]
====
Traditional clients are not available on {amazon}{nbsp}2.
{amazon}{nbsp}2 clients are only supported as Salt clients.
====

[WARNING]
====
When created at AWS, {amazon} instances always have the same `machine-id` id at `/etc/machine-id`.
Make sure you regenerate the `machine-id` after the instance is created.
For more information, see xref:administration:tshoot-registerclones.adoc[].
====



== Add Software Channels

Before you register {amazon} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: `x86_64` and `aarch64`.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

//The products you need for this procedure are:
For example, when working with `x86_64` architecture, you need this product:

[[amazon-channels-wizard]]
[cols="1,1", options="header"]
.Amazon Linux Products - WebUI
|===

| OS Version | Product Name
| {amazon} 2 | Amazon Linux 2 x86_64

|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[amazon-channels-suma-cli]]
[cols="1,1", options="header"]
.Amazon Linux Channels - CLI
|===

| OS Version | Base Channel
| {amazon} 2 | amazonlinux2-core-x86_64

|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[amazon-channels-uyuni-cli]]
[cols="1,1,1", options="header"]
.Amazon Linux Channels - CLI
|===

| OS Version
| Core Channel
| Client Channel

| {amazon} 2
| amazonlinux2-core
| amazonlinux2-uyuni-client

|===

[NOTE]
====
Make sure you also add and sync `amazonlinux2-extra-docker` channel if you plan to use Docker at your {amazon} instances.
====

include::snippets/addchannels_novendor_cli.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]



== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You need to create an activation key that is associated with your {amazon} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].




== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]




== Register Clients

{amazon} clients are registered in the same way as all other clients.
For more information, see xref:client-configuration:registration-overview.adoc[].
