[[client-upgrades-uyuni]]
= Upgrade Uyuni Clients

. At the command prompt on the {productname} Server, as root, use the [command]``spacewalk-common-channels`` command to add the appropriate channels.
+
----
spacewalk-common-channels \
opensuse_leap15_2 \
opensuse_leap15_2-non-oss \
opensuse_leap15_2-non-oss-updates \
opensuse_leap15_2-updates \
opensuse_leap15_2-uyuni-client
----

. Fully synchronize all channels with [command]``spacewalk-repo-sync``.
  In case of already defined repository URLs, continue with
  Uyuni 2020.07: Troubleshooting with Duplicated Repository URLs.
+
// These are custom channels.
// For more information, see xref:client-configuration:clients-opensuse.adoc[].

. In the {productname} Server {webui}, navigate to menu:Software[Manage > Channels] and click the [systemitem]`` Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)`` channel name.

. In the upper right corner, click btn:[Manage Channel].

. Click the [guimenu]``Repositories`` tab, and select [systemitem]``External - Uyuni Client Tools for openSUSE Leap 15.1 (x86_64)``.

. Click btn:[Update Repositories].

. Navigate to menu:Repositories[Sync] subtab, and click btn:[Sync Now].

. Do the same with [systemitem]``openSUSE Leap 15.2 (x86_64)`` and [systemitem]``External - openSUSE Leap 15.1 (x86_64)``.

If you unfold the [systemitem]``openSUSE Leap 15.2 (x86_64)``, you will see all child channels propulated with packages.

////
. Assign the new channels to the clients instead of the old channels.

. Update all the packages.  This can either be done with the {webui} or better run [command]``zypper dup`` manually on the command line local on the systems or remotely as a Salt command.
////

////
I think the better way to document this is if giving it a try. Create an Uyuni server, sync Leap 15.1 (spacewalk-common-channels), create a Leap 15.1, onboard it, sync Leap 15.2 (spacewalk-common-channels), and then try to adjust the channels and trying to upgrade. I recommend you use VMs and take snapshots of the VMs so you can repeat steps as needed.
////

////
But for now you need to create and mirror at least the target channels with spacewalk-common-channels.

You adjust the channels for the client and best is to call "zypper dup". Either from the commandline on that system or using remote command.
////
