[[client-upgrades-spmigration]]
= Service Pack Migration

Service Pack (SP) migration allows you to upgrade SLE-based client systems from an SP level to a later one.
For example, you can migrate {sle}{nbsp}15{nbsp}SP1 to {sle}{nbsp}15{nbsp}SP2.

You can also migrate openSUSE Leap to a later minor version or to the corresponding SLE SP level, for example:

* openSUSE Leap 15.1 to 15.2, or
* openSUSE Leap 15.2 to {sle} 15 SP2

[WARNING]
====
During migration, {productname} automatically accepts any required licenses (EULAs) before installation.
====

In {sle}{nbsp}12 and later, {suse} supports service pack skipping if {scc} provides it.
For example, you can upgrade from {sle}{nbsp}15 to SP2, without installing SP1.
For supported {sle} upgrade paths, see https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-upgrade-paths.html#sec-upgrade-paths-supported.



[IMPORTANT]
====
Service pack migration is for upgrading within the same major version.
You cannot use SP migration to migrate from {sle}{nbsp}12 to {sle}{nbsp}15.
For more information about major upgrades, see xref:client-configuration:client-upgrades-major.adoc[].
====


[WARNING]
====
SP migration does not have a rollback feature.
When the migration procedure has begun, rolling back is not possible.
Ensure you have a working system backup available, in case of an emergency.
====



.Procedure: Performing a Migration
. From the menu:Systems[Overview] page, select a client.
. From the system details page of the client, navigate to the menu:Software[SP Migration] tab.
. Select the target migration path and click btn:[Select Channels].
. From the [guimenu]``Service Pack Migration - Channels`` page select the correct base channel, including ``Mandatory Child Channels`` and any additional ``Optional Child Channels``.
. OPTIONAL: Check [guimenu]``Allow Vendor Change`` to allow packages that have changed vendors to be installed.
  If this occurs, a notification is shown with details before the migration is started.
+
[IMPORTANT]
====
To migrate openSUSE Leap to {sle}, you must check the [guimenu]``Allow Vendor Change`` option.
====
. Click btn:[Schedule Migration] when your channels have been configured properly.



== SP Mass Migration

If you want to migrate a large number of clients to the next SP version, you can use {productname} API calls.



.Procedure: Performing a Mass SP Migration
. List available migration targets, and take note of the system IDs you want to migrate:
+
----
spacecmd api -- system.listMigrationTargets -A 1000010001
----
. For each system ID, call [systemitem]``listMigrationTarget`` and check that the desired target product is available.
+
* If the system ID has an available target, call [systemitem]``system.scheduleSPMigration``.
* If the desired target is not available, skip the system.

Adapt this template for your environment:

----
target = '[....]'
basechannel = 'channel-label'
system_ids = [1, 2, 3]

session = auth.login(user, pass)
for system in system_ids
  if system.listMigrationTargets(session, system).ident == target
    system.scheduleSPMigration(session, system, target, basechannel, [], False, <now>)
  else
    print "Cannot migrate to requested target -- skipping system"
  endif
endfor
----

////
[WARNING]
====
The following examples are referenced for illustrative purposes only.
{suse} does not support these resources.
====

If you want to integrate such API calls into your scripts, see:

* https://github.com/bjin01/spmigration
* https://github.com/bjin01/spmigration-single
////
