[[clients-debian]]
= Registering {debian} Clients

This section contains information about registering Salt clients running {debian} operating systems.

[IMPORTANT]
====
{suse} does not provide support for {debian} operating systems.
{productname} allows you to manage {debian} clients, but support is not provided.
Using {productname} to manage {debian} clients is experimental.
These instructions have been tested on {debian}{nbsp}9 Stretch and {debian}{nbsp}10 Buster.
Do not rely on {debian} clients in a production environment.
====

[NOTE]
====
{debian} is supported for Salt clients only.
Traditional clients are not supported.
====

Bootstrapping can be used with {debian} clients for performing initial state runs, and for profile updates.



== Prepare to Register

Some preparation is required before you can register {debian} clients to the {productname} Server:

* If you are using Debian{nbsp}9, install the required packages on the client before you attempt to register.
  On the client, at the command prompt, as root, run:
+
----
apt install apt-transport-https python-apt python3-apt
----

* Ensure DNS is correctly configured and provides an entry for the client.
  Alternatively, you can configure the ``/etc/hosts`` files on both the {productname} Server and the client with the appropriate entries.
* The client must have the date and time synchronized with the {productname} Server before registration.



== Add Software Channels

Before you can register {debian} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

The products you need for this procedure are:

[[debian-channels-wizard]]
[cols="1,1", options="header"]
.Debian Products - WebUI
|===

| OS Version  | Product Name
| {debian} 9  | Debian 9
| {debian} 10 | Debian 10
| {debian} 11 | Debian 11
|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[debian-channels-cli]]
[cols="1,1", options="header"]
.Debian Channels - CLI
|===

| OS Version  | Product Name
| {debian} 9  | debian-9-pool-amd64
| {debian} 10 | debian-10-pool-amd64
| {debian} 11 | debian-11-pool-amd64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]

The channels you need for this procedure are:

[[debian-channels-cli]]
[cols="1,1,1,1,1", options="header"]
.Debian Channels - CLI
|===

| OS Version
| Base Channel
| Client Channel
| Updates Channel
| Security Channel

| {debian} 9
| debian-9-pool-amd64-uyuni
| debian-9-amd64-uyuni-client
| debian-9-amd64-main-updates-uyuni
| debian-9-amd64-main-security-uyuni

| {debian} 10
| debian-10-pool-amd64-uyuni
| debian-10-amd64-uyuni-client
| debian-10-amd64-main-updates-uyuni
| debian-10-amd64-main-security-uyuni

| {debian} 11
| debian-11-pool-amd64-uyuni
| debian-11-amd64-uyuni-client
| debian-11-amd64-main-updates-uyuni
| debian-11-amd64-main-security-uyuni

|===

include::snippets/addchannels_novendor_cli.adoc[]

endif::[]



== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[NOTE]
====
{debian} channels can be very large.
Synchronization can sometimes take several hours.
====



ifeval::[{uyuni-content} == true]

== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]

[NOTE]
====
{debian} clients can require multiple GPG keys to be installed.
====

endif::[]



== Register Clients

To register your {debian} clients, you need a bootstrap repository.
By default, bootstrap repositories are regenerated daily.
You can manually create the bootstrap repository from the command prompt, using this command:

----
mgr-create-bootstrap-repo
----

For {debian}{nbsp}10, select ``debian10-amd64-uyuni`` when prompted.


For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].
