[[clients-rh-cdn]]
= Registering {rhel} Clients with CDN

If you are running {rhel} clients directly, rather than using {sleses}, you need to use Red Hat sources to retrieve and update packages.
This section contains information about using the {redhat} content delivery network (CDN) to register traditional and Salt clients running {rhel} operating systems.

For information about using {redhat} update infrastructure (RHUI) instead, see xref:client-configuration:clients-rh-rhui.adoc[].



[IMPORTANT]
====
{rhel} clients are based on {redhat} and are unrelated to {sleses}, RES, or {sles}.
You are responsible for arranging access to {redhat} base media repositories and {rhela} installation media, as well as connecting {productname} Server to the {redhat} content delivery network.
You must obtain support from {redhat} for all your {rhela} systems.
If you do not do this, you might be violating your terms with {redhat}.
====


[NOTE]
====
Traditional clients are available on {rhel}{nbsp}6 and 7 only.
{rhel}{nbsp}8 clients are supported as Salt clients.
====



== Import Entitlements and Certificates

{redhat} clients require a {redhat} certificate authority (CA) and entitlement certificate, and an entitlement key.

Entitlement certificates are embedded with expiration dates, which match the length of the support subscription.
To avoid disruption, you need to repeat this process at the end of every support subscription period.

{redhat} supplies a subscription manager tool to manage subscription assignments.
It runs locally to track installed products and subscriptions.
Clients must be registered with the subscription manager to obtain certificates.

{redhat} clients use a URL to replicate repositories.
The URL changes depending on where the {redhat} client is registered.

{redhat} clients can be registered in three different ways:

* {redhat} content delivery network (CDN) at redhat.com
* {redhat} Satellite Server
* {redhat} update infrastructure (RHUI) in the cloud

This guide covers clients registered to {redhat} CDN.
You must have at least one system registered to the CDN, with an authorized subscription for repository content.

For information about using {redhat} update infrastructure (RHUI) instead, see xref:client-configuration:clients-rh-rhui.adoc[].


[IMPORTANT]
====
Satellite certificates for client systems require a Satellite server and subscription.
Clients using Satellite certificates are not supported with {productname} Server.
====

[WARNING]
====
Entitlement certificates are embedded with expiration dates, which match the length of the support subscription.
To avoid disruption, you need to repeat this process at the end of every support subscription period.
====

{redhat} supplies the subscription-manager tool to manage subscription assignments.
It runs locally on the client system to track installed products and subscriptions.
Register to redhat.com with subscription-manager, then follow this procedure to obtain certificates.



.Procedure: Registering Clients to Subscription Manager

. On the client system, at the command prompt, register with the subscription manager tool:
+
----
subscription-manager register
----
+
Enter your {redhat} Portal username and password when prompted.
. Run command:
+
----
subscription-manager activate
----
+
. Copy your entitlement certificate and key from the client system, to a location that the {productname} Server can access:
+
----
cp /etc/pki/entitlement/ /<example>/entitlement/
----
+
[NOTE]
====
Your entitlement certificate and key both have a file extension of [path]``.pem``.
The key also has [path]``key`` in the filename.
====
+
. Copy the {redhat} CA Certificate file from the client system, to the same web location as the entitlement certificate and key:
+
----
cp /etc/rhsm/ca/redhat-uep.pem /<example>/entitlement
----


To manage repositories on your {redhat} client, you need to import the CA and entitlement certificates to the {productname} Server.
This requires that you perform the import procedure three times, to create three entries: one each for the entitlement certificate, the entitlement key, and the {redhat} certificate.



.Procedure: Importing Certificates to the Server

. On the {productname} Server {webui}, navigate to menu:Systems[Autoinstallation > GPG and SSL Keys].
+
// Maybe we  should add a screenshot, as we have at the current guide: https://documentation.suse.com/sbp/all/html/SBP-sumaforrhel/index.html#sec-import
// Not necessary, it's pretty simple to navigate to a page. LKB

. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement certificate:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-Cert-date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement certificate, and select the [path]``.pem`` certificate file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement key:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-key-date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement key, and select the [path]``.pem`` key file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the {redhat} certificate:
* In the [guimenu]``Description`` field, type [systemitem]``redhat-uep``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the {redhat} certificate, and select the certificate file.
. Click btn:[Create Key].



== Add Software Channels

// 2022-04-21, ke:
// Section sequence according to https://github.com/uyuni-project/uyuni-docs/pull/1535

Before you register {redhat} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

Your {susemgr} subscription entitles you to the tools channels for {sleses} (also known as {redhat} Expanded Support or RES).
You must use the client tools channel to create the bootstrap repository.
This procedure applies to both Salt and traditional clients.
endif::[]

ifeval::[{suma-content} == true]

The products you need for this procedure are:

[[redhat-channels-wizard]]
[cols="1,1", options="header"]
.Red Hat Products - WebUI
|===

| OS Version | Product Name
| {redhat} 6 | RHEL6 Base x86_64
| {redhat} 7 | RHEL7 Base x86_64
| {redhat} 8 | RHEL or SLES ES or CentOS 8 Base
|===

[NOTE]
====
{redhat} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {redhat} 6 clients using these packages will fail.
If you need to bootstrap new {redhat} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====


include::snippets/addchannels_vendor_webui.adoc[]


endif::[]

ifeval::[{uyuni-content} == true]

The channels you need for this procedure are:

[[redhat-channels-cli]]
[cols="1,1,1,1", options="header"]
.Red Hat Channels - CLI
|===

| OS Version
| Base Channel
| Client Channel
| Tools Channel

| {redhat} 6
| rhel-x86_64-server-6
| -
| res6-suse-manager-tools-x86_64

| {redhat} 7
| rhel-x86_64-server-7
| -
| res7-suse-manager-tools-x86_64

| {redhat} 8
| rhel8-pool-x86_64
| -
| res8-suse-manager-tools-x86_64

|===

[NOTE]
====
{redhat} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {redhat} 6 clients using these packages will fail.
If you need to bootstrap new {redhat} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_novendor_cli.adoc[]


[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]


include::snippets/appstream_admon.adoc[]


////
I can't tell what this applies to?  --LKB 2020-06-10


ifeval::[{uyuni-content} == true]

spacewalk-common-channels can't be used because centosX-uyuni-client requires centos7 channel as well, which a RHEL user would not need.

.Procedure: Adding Client Tools Channels

. On the {productname} Server {webui}, navigate to menu:Software[Manage > Repositories].
. Click btn:[Create Repository] and set these parameters for the entitlement certificate:
* In the [guimenu]``Repository Label`` field, type [systemitem]``centos7-uyuni-client``.
* In the [guimenu]``Repository URL`` field, type the URL of the repository to mirror.
For example, [systemitem]``https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/``.
* In the [guimenu]``Has Signed Metadata?`` field, uncheck all Red Hat Enterprise Repositories.
* Leave all other fields as the default values.
. Click btn:[Create Repository].
. Navigate to menu:Software[Manage > Channels].
. Click btn:[Create Channel] and set these parameters.
Ensure you use the correct {rhela} version:
* In the [guimenu]``Channel Name`` field, type [systemitem]``Uyuni Client Tools for CentOS 7 (x86_64)``.
* In the [guimenu]``Channel Label`` field, type [systemitem]``centos7-uyuni-client-x86_64``.
* In the [guimenu]``Parent Channel`` field, select [systemitem]``rhel7-x86_64-server``.
* In the [guimenu]``Architecture`` field, select [systemitem]``x86_64``.
* In the [guimenu]``Repository Checksum Type`` field, select [systemitem]``sha1``.
* In the [guimenu]``Channel Summary`` field, type [systemitem]``Uyuni Client Tools for CentOS 7 (x86_64)``.
* In the [guimenu]``Organization Sharing`` field, select [systemitem]``Public``.
. Click btn:[Create Channel].
. Navigate to the [guimenu]``Repositories`` tab, check the [systemitem]``centos7-uyuni-client`` repository, and click btn:[Update repositories].
. OPTIONAL: Navigate to the [guimenu]``Sync`` tab to set a recurring schedule for synchronization of this repository.
. Click btn:[Sync Now] to begin synchronization immediately.
. Add the new channel to your activation key.

endif::[]

////


== Prepare Custom Repositories and Channels

To mirror the software from the Red Hat CDN, you need to create custom channels and repositories in {productname} that are linked to the CDN by a URL.
You must have entitlements to these products in your Red Hat Portal for this to work correctly.
You can use the subscription manager tool to get the URLs of the repositories you want to mirror:

----
subscription-manager repos
----

You can use these repository URLs to create custom repositories.
This allows you to mirror only the content you need to manage your clients.

[IMPORTANT]
====
You can only create custom versions of {redhat} repositories if you have the correct entitlements in your {redhat} Portal.
====


The details you need for this procedure are:

[[redhat-repos-manual]]
[cols="1,1", options="header"]
.Red Hat Custom Repository Settings
|===

| Option                 | Setting
| Repository URL         | The content URL provided by {redhat} CDN
| Has Signed Metadata?   | Uncheck all {redhat} Enterprise repositories
| SSL CA Certificate     | [systemitem]``redhat-uep``
| SSL Client Certificate | [systemitem]``Entitlement-Cert-date``
| SSL Client Key         | ``Entitlement-Key-date``
|===


include::snippets/manual_repos.adoc[]



The channels you need for this procedure are:

[[redhat-channels-custom]]
[cols="1,1,1", options="header"]
.Red Hat Custom Channels
|===

| OS Version | Base Product          | Base Channel
| {redhat} 6 | RHEL6 Base x86_64 | rhel6-pool-x86_64
| {redhat} 7 | RHEL7 Base x86_64 | rhel7-pool-x86_64
| {redhat} 8 | RHEL or SLES ES or CentOS 8 Base | rhel8-pool-x86_64
|===

[NOTE]
====
{redhat} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {redhat} 6 clients using these packages will fail.
If you need to bootstrap new {redhat} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/manual_channels.adoc[]

[IMPORTANT]
====
For {redhat} 8 clients, add both the Base and AppStream channels.
You require packages from both channels.
If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====

If you are using modular channels, you must enable the Python 3.6 module stream on the client.
If you do not provide Python 3.6, the installation of the [package]``spacecmd`` package will fail.

include::snippets/manual_associate.adoc[]



== Check Synchronization Status

ifeval::[{suma-content} == true]


include::snippets/check_sync_webui_suma.adoc[]


endif::[]

ifeval::[{uyuni-content} == true]


include::snippets/check_sync_webui_uyuni.adoc[]


endif::[]


include::snippets/check_sync_cli.adoc[]


[NOTE]
====
{rhel} channels can be very large.
Synchronization can sometimes take several hours.
====


.Procedure: OPTIONAL: Creating a Salt State to Deploy Configuration Files

. On the {productname} Server {webui}, navigate to menu:Configuration[Channels].
. Click btn:[Create State Channel].
* In the [guimenu]``Name`` field, type [systemitem]``subscription-manager: disable yum plugins``.
* In the [guimenu]``Label`` field, type [systemitem]``subscription-manager-disable-yum-plugins``.
* In the [guimenu]``Description`` field, type [systemitem]``subscription-manager: disable yum plugins``.
* In the [guimenu]``SLS Contents`` field, leave it empty.
. Click btn:[Create Config Channel]
. Click btn:[Create Configuration File]
* In the [guimenu]``Filename/Path`` field type [systemitem]``/etc/yum/pluginconf.d/subscription-manager.conf``.
* In the [guimenu]``File Contents`` field type:
+
----
[main]
enabled=0
----
. Click btn:[Create Configuration File]
. Take note of the value of the field [guimenu]``Salt Filesystem Path```.
. Click on the name of the Configuration Channel.
. Click on [guimenu]``View/Edit 'init.sls' File``
* In the [guimenu]``File Contents`` field, type:
+
----
configure_subscription-manager-disable-yum-plugins:
  cmd.run:
    - name: subscription-manager config --rhsm.auto_enable_yum_plugins=0
    - watch:
      - file: /etc/yum/pluginconf.d/subscription-manager.conf
  file.managed:
    - name: /etc/yum/pluginconf.d/subscription-manager.conf
    - source: salt:///etc/yum/pluginconf.d/subscription-manager.conf
----
. Click btn:[Update Configuration File].


[NOTE]
====
The ``Creating a Salt State to Deploy Configuration Files`` procedure is optional.
====


.Procedure: Creating a System Group for {rhel} Clients

. On the {productname} Server {webui}, navigate to menu:Systems[System Groups].
. Click btn:[Create Group].
* In the [guimenu]``Name`` field, type [systemitem]``rhel-systems``.
* In the [guimenu]``Description`` field, type [systemitem]``All RHEL systems``.
. Click btn:[Create Group].
. Click [guimenu]``States`` tab.
. Click [guimenu]``Configuration Channels`` tab.
. Type [systemitem]``subscription-manager: disable yum plugins`` at the search box.
. Click btn:[Search] to see the state.
. Click the checkbox for the state at the [systemitem]``Assign`` column.
. Click btn:[Save changes].
. Click btn:[Confirm].

If you already have RHEL systems added to {productname}, assign them to the new system group, and then apply the highstate.



.Procedure: Adding the System Group to Activation Keys

You need to modify the activation keys you used for RHEL systems to include the system group created above.

. On the {productname} Server {webui}, navigate to menu:Systems[Activation Keys].
. For each the Activation Keys you used for RHEL systems, click on it and:
. Navigate to the [guimenu]``Groups`` tab, and the [guimenu]``Join`` subtab.
. Check [systemitem]``Select rhel-systems``.
. Click btn:[Join Selected Groups].



ifeval::[{uyuni-content} == true]
== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]

endif::[]



== Register Clients

To register your {redhat} clients, you need a bootstrap repository.
By default, bootstrap repositories are automatically created, and regenerated daily for all synchronized products.
You can manually create the bootstrap repository from the command prompt, using this command:

----
mgr-create-bootstrap-repo
----

For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].


[WARNING]
====
To register and use {rhel}{nbsp}6 clients, you need to configure the {productname} Server to support older types of SSL encryption.
For more information about how to resolve this error, see ``Registering Older Clients`` at xref:client-configuration:tshoot-clients.adoc[].
====
