[[clients-debian]]
= Registering {debian} Clients
:revdate: 2025-03-10
:page-revdate: {revdate}

This section contains information about registering clients running {debian} operating systems.

Bootstrapping can be used with {debian} clients for performing initial state runs, and for profile updates.

ifeval::[{mlm-content} == true]

// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====
* {debian} repository URLs are available from {scclongform}.
* Packages and metadata are provided by {debian}, not by {suse}.
* For supported products, see the release notes and the support table at xref:client-configuration:supported-features-debian.adoc[].
====
endif::[]



== Prepare to Register


Some preparation is required before you can register {debian} clients to the {productname} Server:

* Ensure DNS is correctly configured and provides an entry for the client.
  Alternatively, you can configure the ``/etc/hosts`` files on both the {productname} Server and the client with the appropriate entries.
* The client must have the date and time synchronized with the {productname} Server before registration.



== Add Software Channels

Before you can register {debian} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]

ifeval::[{mlm-content} == true]

The products you need for this procedure are:

[[debian-channels-wizard]]
[cols="1,1", options="header"]
.{debian} Products - WebUI
|===

| OS Version  | Product Name
| {debian} 12 | {debian} 12
| {debian} 13 | {debian} 13
|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[debian-channels-cli]]
[cols="1,1", options="header"]
.{debian} Channels - CLI
|===

| OS Version  | Product Name
| {debian} 12 | debian-12-pool-amd64
| {debian} 13 | debian-13-pool-amd64
|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_cli.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

The channels you need for this procedure are:

[[debian-channels-cli]]
[cols="1,1,1,1,1", options="header"]
.{debian} 12 Channels - CLI
|===

| OS Version
| Base Channel
| Client Channel
| Updates Channel
| Security Channel

| {debian} 12
| debian-12-pool-amd64-uyuni
| debian-12-amd64-uyuni-client
| debian-12-amd64-main-updates-uyuni
| debian-12-amd64-main-security-uyuni

|===

[cols="1,1", options="header"]
.{debian} 13 Channels - CLI
|===

| Channel description         | Channel name
| Main                        | debian-13-pool-amd64-uyuni
| Main Updates                | debian-13-amd64-main-updates-uyuni
| Main Security               | debian-13-amd64-main-security-uyuni
| Main Backports              | debian-13-amd64-main-backports-uyuni
| Contrib                     | debian-13-amd64-contrib-uyuni
| Contrib Updates             | debian-13-amd64-contrib-updates-uyuni
| Contrib Security            | debian-13-amd64-contrib-security-uyuni
| Contrib Backports           | debian-13-amd64-contrib-backports-uyuni
| Non-Free                    | debian-13-amd64-non-free-uyuni
| Non-Free Updates            | debian-13-amd64-non-free-updates-uyuni
| Non-Free Security           | debian-13-amd64-non-free-security-uyuni
| Non-Free Backports          | debian-13-amd64-non-free-backports-uyuni
| Non-Free-Firmware           | debian-13-amd64-non-free-firmware-uyuni
| Non-Free-Firmware Updates   | debian-13-amd64-non-free-firmware-updates-uyuni
| Non-Free-Firmware Security  | debian-13-amd64-non-free-firmware-security-uyuni
| Non-Free-Firmware Backports | debian-13-amd64-non-free-firmware-backports-uyuni
| Client Tools                | debian-13-amd64-uyuni-client

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli.adoc[]
endif::[]

endif::[]



== Check Synchronization Status

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]

ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]

[NOTE]
====
{debian} channels can be very large.
Synchronization can sometimes take several hours.
====


== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].

[NOTE]
====
{debian} clients can require multiple GPG keys to be installed.
====

When synchronizing third-party {debian} repositories, you will need to import the appropriate GPG key on the server.
If the GPG key is missing, synchronization will fail.

For {debian} repositories, only the metadata is signed. Therefore importing a GPG key for the software channel is not needed.
Packages will not be re-signed by Uyuni.

To see which GPG keys are already imported to {productname} Server, run the following command:

----
mgrctl exec -- gpg --homedir /var/lib/spacewalk/gpgdir --list-keys
----

To import a new GPG key, run the following command:

----
mgradm gpg add <filename>.gpg
----



== Root Access

The root user on {debian} is disabled by default for SSH access.

To be able to onboard using a regular user, you need to edit the [filename]``sudoers`` file.

.Procedure: Granting Root User Access

. On the client, edit the [filename]``sudoers`` file:
+
----
sudo visudo
----
+
Grant [command]``sudo`` access to the user by adding this line at the end of the [filename]``sudoers`` file.
Replace [systemitem]``<user>`` with the name of the user that is bootstrapping the client in the {webui}:
+
----
<user>  ALL=NOPASSWD: /usr/bin/python, /usr/bin/python2, /usr/bin/python3, /var/tmp/venv-salt-minion/bin/python
----

[NOTE]
====
This procedure grants root access without requiring a password, which is required for registering the client.
When the client is successfully installed it runs with root privileges, so the access is no longer required.
We recommend that you remove the line from the [path]``sudoers`` file after the client has been successfully installed.
====



== Register Clients


ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]

