[[clients-oracle]]
= Registering {oracle} Clients

This section contains information about registering clients running {oracle} operating systems.

ifeval::[{suma-content} == true]
// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====
* {oracle} repository URLs are available from {scc}
* Packages and metadata are provided by Oracle, not by {suse}
* {oracle} base media repositories are freely available for download from https://yum.oracle.com/
* For supported products, see the support table and the release notes
====
endif::[]

[NOTE]
====
Direct synchronizing Unbreakable Linux Network (ULN) repositories with {productname} are not currently supported.
An Oracle Local Distribution for ULN must be used.
For more information about setting up a local ULN mirror, see the Oracle documentation provided at https://docs.oracle.com/en/operating-systems/oracle-linux/software-management/sfw-mgmt-UseSoftwareDistributionMirrors.html#local-uln-mirror.
====



== Add Software Channels

Before you register {oracle} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: `x86_64` and `aarch64`.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

//The products you need for this procedure are:
For example, when working with `x86_64` architecture, you need this products:

[[oracle-channels-wizard]]
[cols="1,1", options="header"]
.Oracle Products - WebUI
|===

| OS Version | Product Name
| {oracle} 9 | Oracle Linux 9 x86_64
| {oracle} 8 | Oracle Linux 8 x86_64
| {oracle} 7 | Oracle Linux 7 x86_64
|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[oracle-channels-suma-cli]]
[cols="1,1", options="header"]
.Oracle Channels - CLI
|===

| OS Version | Base Channel
| {oracle} 9 | oraclelinux9-x86_64
| {oracle} 8 | oraclelinux8-x86_64
| {oracle} 7 | oraclelinux7-x86_64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[oracle-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.Oracle Channels - CLI
|===

| OS Version
| Base Channel
| Client Channel
| Updates Channel

| {oracle} 9
| oraclelinux9
| oraclelinux9-uyuni-client
| oraclelinux9-appstream

| {oracle} 8
| oraclelinux8
| oraclelinux8-uyuni-client
| oraclelinux8-appstream

| {oracle} 7
| oraclelinux7
| oraclelinux7-uyuni-client
| -

|===

include::snippets/addchannels_novendor_cli.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]

ifeval::[{uyuni-content} == true]
[IMPORTANT]
====
For {oracle} 9 and {oracle} 8 clients, add both the Base and AppStream channels.
You require packages from both channels.
If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====
endif::[]

If you are using modular channels, you must enable the Python 3.6 module stream on the client.
If you do not provide Python 3.6, the installation of the [package]``spacecmd`` package will fail.


== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You need to create an activation key that is associated with your {oracle} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].




== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].

[NOTE]
====
For {oracle} 9 and {oracle} 8 clients use
----
ol8-gpg-pubkey-82562EA9AD986DA3.key
----

For {oracle} 7 clients use
----
ol67-gpg-pubkey-72F97B74EC551F0A3.key
----
====



== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]
