[[clients-alibaba]]
= Registering {alibabaclo} Clients

This section contains information about registering clients running {alibabaclo} operating systems.

ifeval::[{suma-content} == true]
// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====

* {alibabaclo} repository URLs are available from {scclongform}
* Packages and metadata are provided by Alibaba Cloud, not by {suse}
* For supported products, see the support table and the release notes

====
endif::[]

[WARNING]
====
Some {alibabaclo}{nbsp}2 instances will need two tries to register successfully.
====



== Add Software Channels

Before you register {alibabaclo} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

The products you need for this procedure are:

[[alibaba-channels-wizard]]
[cols="1,1", options="header"]
.Alibaba Cloud Linux Products - WebUI
|===
| OS Version | Product Name
| {alibabaclo} 2 | Alibaba Cloud Linux 2 x86_64
|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[alibaba-channels-suma-cli]]
[cols="1,1", options="header"]
.Alibaba Cloud Linux Channels - CLI
|===
| OS Version | Base Channel
| {alibabaclo} 2 | alibaba-2-x86_64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[alibaba-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.Alibaba Cloud Linux Channels - CLI
|===

| OS Version
| Core Channel
| Updates Channel
| Client Channel

| {alibabaclo} 2
| alibaba-2
| alibaba-2-updates
| alibaba-2-uyuni-client

|===


include::snippets/addchannels_novendor_cli.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]

== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You need to create an activation key that is associated with your {alibabaclo} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].



== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]

Some {alibabaclo}{nbsp}2 instances will fail to register on the first try.
This is due to a to a known bug in the {alibabaclo}{nbsp}2 image.

The `python-urlgrabber3` package is provided both as a Python pip package and an RPM package, which can cause a conflict on the first attempt to register.

If your instance is based on one of the affected image versions, the client should register correctly on the second registration attempt.
