[[client-proxy]]
= Client Registration on a Proxy

////
The following sections cover registering Salt and traditional clients on a {productname} Proxy.
When a client is registered it connect to the proxy exclusively for Salt operations (Salt client) and normal HTTP package downloads.
There are three ways to register Salt clients.
////


Proxy servers can act as a broker and package cache for both Salt and traditional clients.
Registering clients on a {productname} Proxy is similar to registering them directly on {productname}, with a few key differences.

These sections contain information on registering Salt clients on a proxy using the {webui}, commands on the command line, or a bootstrap script.
There is also information on registering traditional clients using a bootstrap script.

// Here starts what you can see on the server about proxy connected clients

Within the {webui}, proxy pages will show information about both Salt and traditional clients.
You can see a list of clients that are connected to a proxy by clicking the name of the proxy in menu:Systems[System List > Proxy], then select the [guimenu]``Proxy`` subtab of the [guimenu]``Details`` tab.

A list of chained proxies for a Salt client can be seen by clicking the name of the client in menu:Systems[All], then select the [guimenu]``Connection`` subtab of the [guimenu]``Details`` tab.

If you decide to move any of your clients between proxies or the server you will need to repeat the registration process from the beginning.
