[[client-upgrades-uyuni]]
= Upgrade Uyuni Clients

. On the {productname} Server, create the new openSUSE Leap channels with the [command]``spacewalk-common-channels`` command.
  [command]``spacewalk-common-channels`` is part of the [package]``spacewalk-utils`` package:
+
----
spacewalk-common-channels \
opensuse_leap15_2 \
opensuse_leap15_2-non-oss \
opensuse_leap15_2-non-oss-updates \
opensuse_leap15_2-updates \
opensuse_leap15_2-uyuni-client
----
+
These are custom channels.
For more information, see xref:client-configuration:clients-opensuse.adoc[].
+

. Assign the new channels to the clients instead of the old channels.

. Update all the packages.  This can either be done with the {webui} or better run [command]``zypper dup`` manually on the command line local on the systems or remotely as a Salt command.

////
I think the better way to document this is if giving it a try. Create an Uyuni server, sync Leap 15.1 (spacewalk-common-channels), create a Leap 15.1, onboard it, sync Leap 15.2 (spacewalk-common-channels), and then try to adjust the channels and trying to upgrade. I recommend you use VMs and take snapshots of the VMs so you can repeat steps as needed.
////

////
But for now you need to create and mirror at least the target channels with spacewalk-common-channels.

You adjust the channels for the client and best is to call "zypper dup". Either from the commandline on that system or using remote command.
////
