[[clients-ubuntu]]
= Registering {ubuntu} Clients

This section contains information about registering Salt clients running {ubuntu} operating systems.

{productname} supports {ubuntu} 16.04 LTS and 18.04 LTS Clients using Salt.
Traditional clients are not supported.

[IMPORTANT]
====
Canonical does not endorse or support {productname}.
====

Bootstrapping is supported for starting {ubuntu} clients and performing initial state runs such as setting repositories and performing profile updates.
However, the root user on {ubuntu} is disabled by default, so to use bootstrapping, you will require an existing user with [command]``sudo`` privileges for Python.



== Channel Details

When you are registering your {ubuntu} clients, use these channel details:

[[ubuntu-channels]]
[cols="1,1,1", options="header"]
.Ubuntu Channels
|===
| OS Version | {webui} | Command Prompt
| {ubuntu} 16.04 | [systemitem]``Ubuntu 16.04`` and [systemitem]``SUSE Linux Enterprise Client Tools Ubuntu 1604 amd64`` | [systemitem]``ubuntu-16.04-pool-amd64`` and [systemitem]``ubuntu-16.04-suse-manager-tools-amd64``
| {ubuntu} 18.04 | [systemitem]``Ubuntu 18.04`` and [systemitem]``SUSE Linux Enterprise Client Tools Ubuntu 1804 amd64`` | [systemitem]``ubuntu-18.04-pool-amd64`` and [systemitem]``ubuntu-18.04-suse-manager-tools-amd64``
| {ubuntu} 20.04 | [systemitem]``Ubuntu 20.04`` and [systemitem]``SUSE Linux Enterprise Client Tools Ubuntu 2004 amd64`` | [systemitem]``ubuntu-20.04-pool-amd64`` and [systemitem]``ubuntu-20.04-suse-manager-tools-amd64``
|===


Some preparation is required before you can register {ubuntu} clients to the {productname} Server.

ifeval::[{suma-content} == true]
include::snippets/add-client-tools.adoc[]
endif::[]

ifeval::[{uyuni-content} == true]
include::snippets/add-spacewalk-utils.adoc[]
endif::[]

include::snippets/custom-channels-repos.adoc[]

ifeval::[{suma-content} == true]
include::snippets/sync-webui.adoc[]
endif::[]

ifeval::[{uyuni-content} == true]
include::snippets/sync-cli.adoc[]
endif::[]

ifeval::[{uyuni-content} == true]
include::snippets/trust-gpg-keys.adoc[]
endif::[]

include::snippets/grant-root-access.adoc[]

include::snippets/register-clients.adoc[]
