[[clients-ubuntu]]
= Registering {ubuntu} 20.04 and 22.04 Clients

This section contains information about registering Salt clients running {ubuntu} 20.04 LTS and 22.04 LTS operating systems.

{ubuntu} is supported for Salt clients only.
Traditional clients are not supported.

ifeval::[{suma-content} == true]
{productname} supports {ubuntu} 18.04 LTS, 20.04 LTS and 22.04 LTS clients using Salt.
For information about registering Salt clients running {ubuntu} 18.04 LTS, see xref:client-configuration:clients-ubuntu-old.adoc[].
endif::[]

Bootstrapping is supported for starting {ubuntu} clients and performing initial state runs such as setting repositories and performing profile updates.
However, the root user on {ubuntu} is disabled by default, so to use bootstrapping, you require an existing user with [command]``sudo`` privileges for Python.

[IMPORTANT]
====
Canonical does not endorse or support {productname}.
====

== Add Software Channels

Before you register {ubuntu} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

The products you need for this procedure are:

[[ubuntu-channels-wizard]]
[cols="1,1", options="header"]
.Ubuntu Products - WebUI
|===

| OS Version     | Product Name
| {ubuntu} 20.04 | Ubuntu 20.04
| {ubuntu} 22.04 | Ubuntu 22.04
|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[ubuntu-channels-cli]]
[cols="1,1", options="header"]
.Ubuntu Channels - CLI
|===

| OS Version     | Base Channel
| {ubuntu} 20.04 | ubuntu-2004-pool-amd64-uyuni
| {ubuntu} 22.04 | ubuntu-2204-pool-amd64-uyuni
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[ubuntu-channels-cli-uyuni]]
[cols="1,1,1,1,1,1", options="header"]
.Ubuntu Channels - CLI
|===

| OS Version | Base Channel | Main Channel | Updates Channel | Security Channel | Client Channel

| {ubuntu} 20.04 | ubuntu-2004-pool-amd64-uyuni | ubuntu-2004-amd64-main-uyuni | ubuntu-2004-amd64-main-updates-uyuni | ubuntu-2004-amd64-main-security-uyuni | ubuntu-2004-amd64-uyuni-client
| {ubuntu} 22.04 | ubuntu-2204-pool-amd64-uyuni | ubuntu-2204-amd64-main-uyuni | ubuntu-2204-amd64-main-updates-uyuni | ubuntu-2204-amd64-main-security-uyuni | ubuntu-2204-amd64-uyuni-client
|===

Version 20.04 also requires the Universe channels:

[[ubuntu-universe-channels-cli-uyuni]]
[cols="1,1", options="header"]
.Ubuntu 20.04 Universe Channels - CLI
|===

| {ubuntu} 20.04           | {nbsp}
| Universe Channel         | ubuntu-2004-amd64-universe-uyuni
| Universe Updates Channel | ubuntu-2004-amd64-universe-updates-uyuni
| Universe Security Updates Channel | ubuntu-2004-amd64-universe-security-uyuni
| Universe Backports Channel | ubuntu-2004-amd64-universe-backports-uyuni

|===

include::snippets/addchannels_novendor_cli.adoc[]

[IMPORTANT]
====
You need all the new channels fully synchronized before bootstrapping any Ubuntu client.
====

endif::[]



== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[NOTE]
====
{ubuntu} channels can be very large.
Synchronization can sometimes take several hours.
====



== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].


== Root Access

The root user on {ubuntu} is disabled by default for SSH access.

To be able to onboard using a regular user, you need to edit the [filename]``sudoers`` file.

[NOTE]
====
This issue happens with self-installed versions of {ubuntu}.
If the default user has been granted administrative privileges during installation time, a password is requiered to perform privilege escalation using [command]``sudo``.
With cloud instances this does not happen because [command]``cloud-init`` automatically creates a file under [path]``/etc/sudoers.d`` and grants privilege escalation through [command]``sudo`` without the need for a password.
====

.Procedure: Granting Root User Access

. On the client, edit the [filename]``sudoers`` file:
+
----
sudo visudo
----
+
Grant [command]``sudo`` access to the user by adding this line at the end of the [filename]``sudoers`` file.
Replace [systemitem]``<user>`` with the name of the user that is bootstrapping the client in the {webui}:
+
----
<user>  ALL=NOPASSWD: /usr/bin/python, /usr/bin/python2, /usr/bin/python3, /var/tmp/venv-salt-minion/bin/python
----

[NOTE]
====
This procedure grants root access without requiring a password, which is required for registering the client.
When the client is successfully installed it runs with root privileges, so the access is no longer required.
We recommend that you remove the line from the [path]``sudoers`` file after the client has been successfully installed.
====



== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]

