[[clients-rh-rhui]]
= Registering {rhel} Clients with RHUI

If you are running {rhel} clients directly, rather than using {sleses}, you need to use Red Hat sources to retrieve and update packages.
This section contains information about using {redhat} update infrastructure (RHUI) to register traditional and Salt clients running {rhel} operating systems.
If you are running your clients in a public cloud, such as Amazon EC2, use this method.

It is possible to use RHUI in conjunction with the {redhat} content delivery network (CDN) to manage your {rhel} subscriptions.
For information about using {redhat} CDN, see xref:client-configuration:clients-rh-cdn.adoc[].



[IMPORTANT]
====
{rhel} clients are based on {redhat} and are unrelated to {sleses}, RES, or {sles}.
You are responsible for connecting {productname} Server to the {redhat} update infrastructure.
All clients that get updates using this RHUI certificate need to be correctly licensed, please check with your cloud provider and the {redhat} terms of service for more information.
====

[NOTE]
====
When {rhel} clients registered with RHUI are switched off, {redhat} might declare the certificate invalid.
In this case, you need to turn the client on again, or get a new RHUI certificate.
====


[NOTE]
====
Traditional clients are available on {rhel}{nbsp}6 and 7 only.
{rhel}{nbsp}8 clients are supported as Salt clients.
====



== Import Entitlements and Certificates

{redhat} clients require a {redhat} certificate authority (CA) and entitlement certificate, and an entitlement key.

{redhat} clients use a URL to replicate repositories.
The URL changes depending on where the {redhat} client is registered.

{redhat} clients can be registered in three different ways:

* {redhat} content delivery network (CDN) at redhat.com
* {redhat} Satellite Server
* {redhat} update infrastructure (RHUI) in the cloud

This guide covers clients registered to {redhat} update infrastructure (RHUI).
You must have at least one system registered to RHUI, with an authorized subscription for repository content.

For information about using {redhat} content delivery network (CDN) instead, see xref:client-configuration:clients-rh-cdn.adoc[].


[IMPORTANT]
====
Satellite certificates for client systems require a Satellite server and subscription.
Clients using Satellite certificates are not supported with {productname} Server.
====


The entitlement certificates and keys need to be copied from the client system to a location that the {productname} Server can access.

The keys and certificates might have slightly different names to those shown here.
Your entitlement certificate and the {redhat} CA Certificate file have file extensions of [path]``.crt``.
The key has a file extension of [path]``.key``.



.Procedure: Copying Certificates to the Server
. Copy your entitlement certificate and key from the client system, to a location that the {productname} Server can access:
+
Amazon EC2:
+
----
cp /etc/pki/rhui/product/content-<version>.crt /<example>/entitlement/
cp /etc/pki/rhui/content-<version>.key /<example>/entitlement/
----
+
Azure:
+
* Check the certificate chain using the command:
----
openssl s_client -connect rhui-1.microsoft.com:443 -showcerts
----
+
A sample output will look like the following:
+
----
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 06
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = rhui-1.microsoft.com
verify return+
----
* Check the second certificate ([literal]``CN = Microsoft Azure``), if it is the same on your VM, note the certificate name.
Refer to the https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/certificate-authorities to download the certificate.
Click the AIA link to download the certificate.
The certificate will be downloaded with the [literal]``.cer`` suffix.
Convert it to [literal]``.crt`` with the command:
+
----
openssl x509 -inform DER -in <example.cer> -out <example.crt>
----
+
Google Cloud Platform:
+
----
cp /etc/pki/rhui/product/content.crt /<example>/entitlement/
cp /etc/pki/rhui/key.pem /<example>/entitlement/
----
+
. Copy the {redhat} CA Certificate file from the client system, to the same location as the entitlement certificate and key:
+
Amazon EC2:
+
----
cp /etc/pki/rhui/cdn.redhat.com-chain.crt /<example>/entitlement
----
+
Azure:
+
Upload the converted certifcate to /<example>/entitlement
+
Google Cloud Platform:
+
----
cp /etc/pki/rhui/ca.crt /<example>/entitlement
----


To manage repositories on your {redhat} client, you need to import the CA and entitlement certificates to the {productname} Server.
This requires that you perform the import procedure three times, to create three entries: one each for the entitlement certificate, the entitlement key, and the {redhat} certificate.



.Procedure: Importing Certificates to the Server

. On the {productname} Server {webui}, navigate to menu:Systems[Autoinstallation > GPG and SSL Keys].
. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement certificate:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-Cert-Date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement certificate, and select the [path]``.crt`` certificate file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement key:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-Key-Date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement key, and select the [path]``.key`` key file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the {redhat} certificate:
* In the [guimenu]``Description`` field, type [systemitem]``redhat-cert``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the {redhat} certificate, and select the certificate file.
. Click btn:[Create Key].



== Add Software Channels

// 2022-04-21, ke:
// Section sequence according to https://github.com/uyuni-project/uyuni-docs/pull/1535

Before you register {redhat} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

Your {susemgr} subscription entitles you to the tools channels for {sleses} (also known as {redhat} Expanded Support or RES).
You must use the client tools channel to create the bootstrap repository.
This procedure applies to both Salt and traditional clients.
endif::[]

ifeval::[{suma-content} == true]

The products you need for this procedure are:

[[redhat-rhui-channels-wizard]]
[cols="1,1", options="header"]
.Red Hat Products - WebUI
|===

| OS Version | Product Name
| {redhat} 6 | RHEL6 Base x86_64
| {redhat} 7 | RHEL7 Base x86_64
| {redhat} 8 | RHEL or SLES ES or CentOS 8 Base
|===

[NOTE]
====
{redhat} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {redhat} 6 clients using these packages will fail.
If you need to bootstrap new {redhat} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_vendor_webui.adoc[]


endif::[]

ifeval::[{uyuni-content} == true]

The channels you need for this procedure are:

[[redhat-rhui-channels-cli]]
[cols="1,1,1,1", options="header"]
.Red Hat Channels - CLI
|===

| OS Version
| Base Channel
| Client Channel
| Tools Channel

| {redhat} 6
| rhel-x86_64-server-6
| -
| res6-suse-manager-tools-x86_64

| {redhat} 7
| rhel-x86_64-server-7
| -
| res7-suse-manager-tools-x86_64

| {redhat} 8
| rhel8-pool-x86_64
| -
| res8-suse-manager-tools-x86_64

|===

[NOTE]
====
{redhat} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {redhat} 6 clients using these packages will fail.
If you need to bootstrap new {redhat} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_novendor_cli.adoc[]


[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]


include::snippets/appstream_admon.adoc[]


To use RHUI, you need to manually add the required HTTP headers to the configuration file.
Without them, you cannot successfully perform a client synchronization.



.Procedure: Adding HTTP Headers to the Configuration File
. Locate the [systemitem]``X-RHUI-ID`` and [systemitem]``X-RHUI-SIGNATURE`` HTTP headers from your RHUI instance.
    You can use these commands on the {redhat} client to get the values from the cloud instance metadata API at [systemitem]``169.254.169.254``:
+
----
echo "X-RHUI-ID=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document|base64|tr -d '\n')"
echo "X-RHUI-SIGNATURE=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/signature|base64|tr -d '\n')"
----
. Open the [path]``/etc/rhn/spacewalk-repo-sync/extra_headers.conf`` configuration file, and add or edit these lines with the correct information:
+
----
[<channel_label_1>]
X-RHUI-ID=<value>
X-RHUI-SIGNATURE=<value>

[<channel_label_2>]
X-RHUI-ID=<value>
X-RHUI-SIGNATURE=<value>
----
+
  Replace [literal]``<channel_label_X>`` above with channel names such as [literal]``rhel8-baseos-repo``:
+
----
[rhel8-baseos-repo]
X-RHUI-ID=...
X-RHUI-SIGNATURE=...
----



== Prepare Custom Repositories and Channels

To mirror the software from RHUI, you need to create custom channels and repositories in {productname} that are linked to RHUI by a URL.
You must have entitlements to these products in your Red Hat Portal for this to work correctly.
You can use the yum utility to get the URLs of the repositories you want to mirror:

----
yum repolist -v | grep baseurl
----

You can use these repository URLs to create custom repositories.
This allows you to mirror only the content you need to manage your clients.

[IMPORTANT]
====
You can only create custom versions of {redhat} repositories if you have the correct entitlements in your {redhat} Portal.
====


The details you need for this procedure are:

[[redhat-rhui-repos-manual]]
[cols="1,1", options="header"]
.Red Hat Custom Repository Settings
|===

| Option                 | Setting
| Repository URL         | The content URL provided by RHUI
| Has Signed Metadata?   | Uncheck all {redhat} Enterprise repositories
| SSL CA Certificate     | [systemitem]``redhat-cert``
| SSL Client Certificate | [systemitem]``Entitlement-Cert-Date``
| SSL Client Key         | [systemitem]``Entitlement-Key-Date``
|===


include::snippets/manual_repos.adoc[]



The channels you need for this procedure are:

[[redhat-rhui-channels-custom]]
[cols="1,1,1", options="header"]
.Red Hat Custom Channels
|===

| OS Version | Base Product          | Base Channel
| {redhat} 6 | RHEL6 Base x86_64 | rhel6-pool-x86_64
| {redhat} 7 | RHEL7 Base x86_64 | rhel7-pool-x86_64
| {redhat} 8 | RHEL or SLES ES or CentOS 8 Base | rhel8-pool-x86_64
|===

[NOTE]
====
{redhat} 6 is now at end-of-life, and the ISO images provided in the repository are out of date.
Bootstrapping new {redhat} 6 clients using these packages will fail.
If you need to bootstrap new {redhat} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/manual_channels.adoc[]

[IMPORTANT]
====
For {redhat} 8 clients, add both the Base and AppStream channels.
You require packages from both channels.
If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====


include::snippets/manual_associate.adoc[]



== Check Synchronization Status

ifeval::[{suma-content} == true]


include::snippets/check_sync_webui_suma.adoc[]


endif::[]

ifeval::[{uyuni-content} == true]


include::snippets/check_sync_webui_uyuni.adoc[]


endif::[]


include::snippets/check_sync_cli.adoc[]


[NOTE]
====
{rhel} channels can be very large.
Synchronization can sometimes take several hours.
====



ifeval::[{uyuni-content} == true]
== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]

endif::[]



== Register Clients

To register your {redhat} clients, you need a bootstrap repository.
By default, bootstrap repositories are automatically created, and regenerated daily for all synchronized products.
You can manually create the bootstrap repository from the command prompt, using this command:

----
mgr-create-bootstrap-repo
----

For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].


[WARNING]
====
To register and use {rhel}{nbsp}6 clients, you need to configure the {productname} Server to support older types of SSL encryption.
For more information, see ``Registering Older Clients`` at xref:client-configuration:tshoot-clients.adoc[].
====
