[[client-upgrades-clm]]
= Upgrade Using the Content Lifecycle Manager

When you have many {sles} clients to manage, you can automate in-place upgrades using the content lifecycle manager.



== Prepare to Upgrade

Before you can upgrade your clients, you need to make these preparations:

* Create a content lifecycle project
* Create an activation key
* Create an autoinstallable distribution
* Create an autoinstallation profile

.Procedure: Creating a Content Lifecycle Project
. Create a content lifecycle project for your distribution.
+
For more information, see xref:administration:content-lifecycle.adoc[].

. Ensure you a choose a short but descriptive name for your project.

. Include all source channel modules that you require for your distribution.

. Add filters as required, and set up at least one environment.



.Procedure: Creating an Activation Key
. Create an activation key for your distribution.
+
For more information, see xref:client-configuration:activation-keys.adoc[].

. Ensure your activation key includes all filtered project channels.



.Procedure: Creating an Autoinstallable Distribution

. Create an autoinstallable distribution for every base channel you want to migrate.
+
For more information, see xref:client-configuration:autoinst-distributions.adoc[].

. Give your distribution a label that references the name of the content lifecycle project.

. In the ``Installer Generation`` field, select the SLES version you are using.



.Procedure: Creating an Autoinstallation Profile

. Create an autoinstallation profile for every target distribution and service pack you want to upgrade to.
+
For more information, see xref:client-configuration:autoinst-profiles.adoc[].

. You can use variables in the profile to distinguish between the different lifecycle environments.


For example autoinstallation profiles, see https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST.

Use these variables in your autointallation profiles for automating in-place upgrades:



.Example: Variables for Use in Autoinstallation Profiles
----
registration_key=1-15sp1-demo-test
org=1
channel_prefix=15sp1-demo-test
distro_label=15sp1-demo-test
----



.Example: Entry for Use in Autoinstallation Profiles
----
 <listentry>
     <ask_on_error config:type="boolean">true</ask_on_error>
     <media_url>https://$redhat_management_server/ks/dist/child/$channel_prefix-sle-module-web-scripting15-sp1-pool-x86_64/$distro_label</media_url>
     <name>$channel_prefix SLE-Module-Web-Scripting15-SP1 Pool for x86_64 </name>
     <product>Web Scripting Module 15 SP1 x86_64 Pool</product>
</listentry>
----



== Upgrade

When you have prepared the server for the upgrade, you can provision the clients.

.Procedure: Provisioning the Clients

. In the {productname} {webui}, navigate to menu:Systems[System List], and select the clients you want to provision to add them to the system set manager.

. Navigate to menu:Systems[System Set Manager > Overview] and click the [guimenu]``Provisioning`` tab.

. Select the autoinstallation profile to use.


For clients that are able to use PXE, the migration is automated as soon as you have provisioned them.
For all other clients, you can use {cobbler} to perform the upgrade.



.Procedure: Using {cobbler} to Upgrade Clients
. At the command prompt, as root, to get to a shell inside the container, run:
----
mgrctl term
----

. Check the available {cobbler} profiles:
+

----
cobbler profile list
----
+

. Build the ISO file with your chosen profile and distribution:
+

// FIXME: 2024-05-06, ke: Do we want to use /tmp here within the container?
+
----
cobbler buildiso --iso=/tmp/SLE_15-sp1.iso --profiles=SLE_15-sp1:1:Example --distro=SLE_15-sp1
----
+

For more information about using CD-ROMs to provision clients, see xref:client-configuration:autoinst-cdrom.adoc[].
