[[clients-pubcloud]]
= Registering clients on a public cloud

When you have your {productname} Server set up, you are ready to start registering clients.



== Add Products and Synchronize Repositories

Ensure you have already added the corresponding products for your clients and synced the repositories to {productname}.
This is required to create the bootstrap repositories used for registering clients.

For more information, see xref:installation-and-upgrade:pubcloud-setup.adoc#add-product-sync-repo[].



== Prepare on-demand images

An instance started from an on-demand image provided by {suse} is automatically registered, and the update infrastructure and {sle} modules are activated.
To use your on-demand image as a {productname} client, you need to disable this automation before you begin.



.Procedure: Preparing on-demand images
. Log in to the on-demand instance.
. At the command prompt, as root, remove the registration data and repositories:
+
----
registercloudguest --clean
----
. Remove the ``cloud-regionsrv-client`` package:
+
----
zypper rm cloud-regionsrv-client
----
. Remove additional packages specific to your cloud provider:
+
* Amazon EC2:
+
----
zypper rm regionServiceClientConfigEC2 regionServiceCertsEC2
----
+
* Google Compute Engine:
+
----
zypper rm cloud-regionsrv-client-plugin-gce regionServiceClientConfigGCE regionServiceCertsGCE
----
+
* Microsoft Azure:
+
----
zypper rm regionServiceClientConfigAzure regionServiceCertsAzure
----

For instructions on registering {productname} to {scc}, see xref:installation-and-upgrade:server-setup.adoc[].



== Register clients

In the {productname} {webui}, navigate to menu:Systems[Bootstrapping], then fill in the ``Host``, ``SSH Port``, ``User``, and ``Password`` fields.
Make sure you use stable FQDNs for the ``Host`` field, or {productname} cannot find your host when your Public Cloud gives you a different short-lived FQDNS.

[NOTE]
====
If you are attempting to bootstrap traditional clients, check that you can resolve the host name of the server while you are logged in to the client.
You might need to add the FQDN of the server to [path]``/etc/hosts`` local resolution file on the client.
Check using the [command]``hostname -f`` command with the local IP address of the server.
====

Public cloud images usually do not allow SSH login with username and password, but only SSH with a certificate.
If you want to use bootstrap from the {webui}, you need to enable SSH login with username and SSH key.
You can do this by navigating to menu:Systems[Bootstrapping] and changing the authentication method.

If your cloud provider is Microsoft Azure, you can log in with username and password.
To do this, you need to allow the AzureUser to run commands as root without a password.
To do this, open the [path]``/etc/sudoers.d/waagent`` file, and add or edit this line:

----
AzureUser ALL=(ALL) NOPASSWD: ALL
----

[WARNING]
====
Allowing the AzureUser to run commands as root without a password carries a security risk.
Use this method for testing only.
Do not do this for production systems.
====

When the bootstrap process has completed successfully, your client is listed at menu:Systems[System List].

* If you want more control over the process, have to register many clients, or are registering traditional clients, create a bootstrap script.
  For more information, see xref:client-configuration:registration-bootstrap.adoc[].
* For Salt clients and even more control over the process, executing single commands on the command line can be useful.
  For more information, see xref:client-configuration:registration-cli.adoc[].
* When registering clients launched from a public cloud image (for example, AWS AMI), you need to do some additional configuration to prevent them from over-writing each other.
  For more information about registering clones, see xref:administration:tshoot-registerclones.adoc[].



== Activation keys

Activation keys are used with traditional and Salt clients to ensure that your clients have the correct software entitlements, are connecting to the appropriate channels, and are subscribed to the relevant groups.
Each activation key is bound to an organization, which you can set when you create the key.

For more on activation keys, see xref:client-configuration:activation-keys.adoc[].
