[[clients-openeuler]]
= Registering {openeuler} Clients
ifeval::[{mlm-content} == true]
:noindex:
endif::[]

This section contains information about registering clients running {openeuler} operating systems.

////
ifeval::[{mlm-content} == true]
// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====
* {openeuler} repository URLs are available from {scclongform}
* Packages and metadata are provided by XXX, not by {suse}
* For supported products, see the support table and the release notes
====
endif::[]
////


[WARNING]
====
When created at AWS, {openeuler} instances always have the same `machine-id` id at `/etc/machine-id`.
Make sure you regenerate the `machine-id` after the instance is created.
For more information, see xref:administration:troubleshooting/tshoot-registerclones.adoc[].
====



== Add Software Channels

Before you register {openeuler} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: `x86_64` and `aarch64`.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

include::snippets/arch-other-note.adoc[]

ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[openeuler-channels-uyuni-cli]]
[cols="1,1,1,1,1,1", options="header"]
.openEuler Channels - CLI
|===

| OS Version
| Core Channel
| Client Channel
| Update Channel
| EPOL Channel
| Everything Channel

| {openeuler} 22.03
| openeuler2203
| openeuler2203-uyuni-client
| openeuler2203-update
| openeuler2203-epol
| openeuler2203-everything

|===

include::snippets/addchannels_novendor_cli.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]



== Check Synchronization Status

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You need to create an activation key that is associated with your {openeuler} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].




== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]




== Register Clients

{openeuler} clients are registered in the same way as all other clients.
For more information, see xref:client-configuration:registration-overview.adoc[].
