[[clients-rh-cdn]]
= Registering {rhel} Clients with CDN

ifeval::[{suma-content} == true]
// SUSE Liberty Linux not available at Uyuni for now
If you are running {rhel} clients directly, rather than using {sleses}, you need to use {redhat} sources to retrieve and update packages.
endif::[]

This section contains information about using the {redhat} content delivery network (CDN) to register clients running {rhel} operating systems.

For information about using {redhat} update infrastructure (RHUI) instead, see xref:client-configuration:clients-rh-rhui.adoc[].

[IMPORTANT]
====

ifeval::[{suma-content} == true]
// SUSE Liberty Linux not available at Uyuni for now
{rhel} clients are based on {redhat} and are unrelated to {sleses}, RES, or {sles}.
endif::[]

You are responsible for arranging access to {redhat} base media repositories and {rhela} installation media, as well as connecting {productname} Server to the {redhat} content delivery network.
You must obtain support from {redhat} for all your {rhela} systems.
If you do not do this, you might be violating your terms with {redhat}.
====

== Import Entitlements and Certificates

{redhat} clients require a {redhat} certificate authority (CA) and entitlement certificate, and an entitlement key.

Entitlement certificates are embedded with expiration dates, which match the length of the support subscription.
To avoid disruption, you need to repeat this process at the end of every support subscription period.

{redhat} supplies a subscription manager tool to manage subscription assignments.
It runs locally to track installed products and subscriptions.
Clients must be registered with the subscription manager to obtain certificates.

{redhat} clients use a URL to replicate repositories.
The URL changes depending on where the {redhat} client is registered.

{redhat} clients can be registered in three different ways:

* {redhat} content delivery network (CDN) at redhat.com
* {redhat} Satellite Server
* {redhat} update infrastructure (RHUI) in the cloud

This guide covers clients registered to {redhat} CDN.
You must have at least one system registered to the CDN, with an authorized subscription for repository content.

For information about using {redhat} update infrastructure (RHUI) instead, see xref:client-configuration:clients-rh-rhui.adoc[].


[IMPORTANT]
====
Satellite certificates for client systems require a Satellite server and subscription.
Clients using Satellite certificates are not supported with {productname} Server.
====

[WARNING]
====
Entitlement certificates are embedded with expiration dates, which match the length of the support subscription.
To avoid disruption, you need to repeat this process at the end of every support subscription period.
====

{redhat} supplies the subscription-manager tool to manage subscription assignments.
It runs locally on the client system to track installed products and subscriptions.
Register to redhat.com with subscription-manager, then follow this procedure to obtain certificates.


.Procedure: Registering Clients to Subscription Manager

. On the client system, at the command prompt, register with the subscription manager tool:
+
----
subscription-manager register
----
+
Enter your {redhat} Portal username and password when prompted.
. Run command:
+
----
subscription-manager activate
----
+
. Copy your entitlement certificate and key from the client system, to a location that the {productname} Server can access:
+
----
cp /etc/pki/entitlement/ /<example>/entitlement/
----
+
[NOTE]
====
Your entitlement certificate and key both have a file extension of [path]``.pem``.
The key also has [path]``key`` in the filename.
====
+
. Copy the {redhat} CA Certificate file from the client system, to the same web location as the entitlement certificate and key:
+
----
cp /etc/rhsm/ca/redhat-uep.pem /<example>/entitlement
----


To manage repositories on your {redhat} client, you need to import the CA and entitlement certificates to the {productname} Server.
This requires that you perform the import procedure three times, to create three entries: one each for the entitlement certificate, the entitlement key, and the {redhat} certificate.



.Procedure: Importing Certificates to the Server

. On the {productname} Server {webui}, navigate to menu:Systems[Autoinstallation > GPG and SSL Keys].
. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement certificate:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-Cert-date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement certificate, and select the [path]``.pem`` certificate file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement key:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-key-date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement key, and select the [path]``.pem`` key file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the {redhat} certificate:
* In the [guimenu]``Description`` field, type [systemitem]``redhat-uep``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the {redhat} certificate, and select the certificate file.
. Click btn:[Create Key].



== Add Software Channels

// 2022-04-21, ke:
// Section sequence according to https://github.com/uyuni-project/uyuni-docs/pull/1535

Before you register {redhat} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

Your {susemgr} subscription entitles you to the tools channels for {sleses} (also known as {redhat} Expanded Support or RES).
You must use the client tools channel to create the bootstrap repository.
This procedure applies to Salt clients.
endif::[]

ifeval::[{suma-content} == true]

The products you need for this procedure are:

// SUSE Liberty Linux not available at Uyuni for now
[[redhat-channels-wizard]]
[cols="1,1", options="header"]
.Red Hat Products - WebUI
|===

ifeval::[{suma-content} == true]
| OS Version | Product Name
| {redhat} 9 | RHEL and Liberty 9 Base
| {redhat} 8 | RHEL or SLES ES or CentOS 8 Base
| {redhat} 7 | RHEL7 Base x86_64
endif::[]

ifeval::[{uyuni-content} == true]
| OS Version | Product Name
| {redhat} 9 | RHEL
| {redhat} 8 | RHEL or CentOS 8 Base
| {redhat} 7 | RHEL7 Base x86_64
endif::[]

|===


include::snippets/addchannels_vendor_webui.adoc[]


endif::[]

ifeval::[{uyuni-content} == true]

The channels you need for this procedure are:

[[redhat-channels-cli]]
[cols="1,1,1,1", options="header"]
.Red Hat Channels - CLI
|===

| OS Version
| Base Channel
| Client Channel
| Tools Channel

| {redhat} 9
| rhel9-pool-uyuni
| -
| rhel9-uyuni-client

| {redhat} 8
| rhel8-pool-uyuni
| -
| rhel8-uyuni-client

| {redhat} 7
| rhel7-pool-uyuni
| -
| rhel7-uyuni-client

|===


include::snippets/addchannels_novendor_cli_multiarch.adoc[]


[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]


== Prepare Custom Repositories and Channels

To mirror the software from the {redhat} CDN, you need to create custom channels and repositories in {productname} that are linked to the CDN by a URL.
You must have entitlements to these products in your {redhat} Portal for this to work correctly.
You can use the subscription manager tool to get the URLs of the repositories you want to mirror:

----
subscription-manager repos
----

You can use these repository URLs to create custom repositories.
This allows you to mirror only the content you need to manage your clients.

[IMPORTANT]
====
You can only create custom versions of {redhat} repositories if you have the correct entitlements in your {redhat} Portal.
====


The details you need for this procedure are:

[[redhat-repos-manual]]
[cols="1,1", options="header"]
.Red Hat Custom Repository Settings
|===

| Option                 | Setting
| Repository URL         | The content URL provided by {redhat} CDN
| Has Signed Metadata?   | Uncheck all {redhat} Enterprise repositories
| SSL CA Certificate     | [systemitem]``redhat-uep``
| SSL Client Certificate | [systemitem]``Entitlement-Cert-date``
| SSL Client Key         | ``Entitlement-Key-date``
|===


include::snippets/manual_repos.adoc[]



The channels you need for this procedure are:

[[redhat-channels-custom]]

ifeval::[{suma-content} == true]
[cols="1,1,1", options="header"]
.Red Hat Custom Channels
|===

| OS Version | Base Product          | Base Channel
| {redhat} 9 | RHEL and Liberty 9 Base | el9-pool-x86_64
// SUSE Liberty Linux not available at Uyuni for now
| {redhat} 8 | RHEL or SLES ES or CentOS 8 Base | rhel8-pool-x86_64
| {redhat} 7 | RHEL7 Base x86_64 | rhel7-pool-x86_64

|===
endif::[]

// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{uyuni-content} == true]
[cols="1,1", options="header"]
.Red Hat Custom Channels
|===

| OS Version | Base Channel
| {redhat} 9 | rhel9-pool-uyuni
| {redhat} 8 | rhel8-pool-uyuni
| {redhat} 7 | rhel7-pool-uyuni

|===
endif::[]


include::snippets/manual_channels.adoc[]

[IMPORTANT]
====
For {redhat} 8 clients, add both the Base and AppStream channels.
You require packages from both channels.
If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====

If you are using modular channels, you must enable the Python 3.6 module stream on the client.
If you do not provide Python 3.6, the installation of the [package]``spacecmd`` package will fail.

include::snippets/manual_associate.adoc[]



== Check Synchronization Status

ifeval::[{suma-content} == true]


include::snippets/check_sync_webui_suma.adoc[]


endif::[]

ifeval::[{uyuni-content} == true]


include::snippets/check_sync_webui_uyuni.adoc[]


endif::[]


include::snippets/check_sync_cli.adoc[]


[NOTE]
====
{rhel} channels can be very large.
Synchronization can sometimes take several hours.
====


.Procedure: OPTIONAL: Creating a Salt State to Deploy Configuration Files

. On the {productname} Server {webui}, navigate to menu:Configuration[Channels].
. Click btn:[Create State Channel].
* In the [guimenu]``Name`` field, type [systemitem]``subscription-manager: disable yum plugins``.
* In the [guimenu]``Label`` field, type [systemitem]``subscription-manager-disable-yum-plugins``.
* In the [guimenu]``Description`` field, type [systemitem]``subscription-manager: disable yum plugins``.
* In the [guimenu]``SLS Contents`` field, leave it empty.
. Click btn:[Create Config Channel]
. Click btn:[Create Configuration File]
* In the [guimenu]``Filename/Path`` field type [systemitem]``/etc/yum/pluginconf.d/subscription-manager.conf``.
* In the [guimenu]``File Contents`` field type:
+
----
[main]
enabled=0
----
. Click btn:[Create Configuration File]
. Take note of the value of the field [guimenu]``Salt Filesystem Path```.
. Click on the name of the Configuration Channel.
. Click on [guimenu]``View/Edit 'init.sls' File``
* In the [guimenu]``File Contents`` field, type:
+
----
configure_subscription-manager-disable-yum-plugins:
  cmd.run:
    - name: subscription-manager config --rhsm.auto_enable_yum_plugins=0
    - watch:
      - file: /etc/yum/pluginconf.d/subscription-manager.conf
  file.managed:
    - name: /etc/yum/pluginconf.d/subscription-manager.conf
    - source: salt:///etc/yum/pluginconf.d/subscription-manager.conf
----
. Click btn:[Update Configuration File].


[NOTE]
====
The ``Creating a Salt State to Deploy Configuration Files`` procedure is optional.
====


.Procedure: Creating a System Group for {rhel} Clients

. On the {productname} Server {webui}, navigate to menu:Systems[System Groups].
. Click btn:[Create Group].
* In the [guimenu]``Name`` field, type [systemitem]``rhel-systems``.
* In the [guimenu]``Description`` field, type [systemitem]``All RHEL systems``.
. Click btn:[Create Group].
. Click [guimenu]``States`` tab.
. Click [guimenu]``Configuration Channels`` tab.
. Type [systemitem]``subscription-manager: disable yum plugins`` at the search box.
. Click btn:[Search] to see the state.
. Click the checkbox for the state at the [systemitem]``Assign`` column.
. Click btn:[Save changes].
. Click btn:[Confirm].

If you already have RHEL systems added to {productname}, assign them to the new system group, and then apply the highstate.



.Procedure: Adding the System Group to Activation Keys

You need to modify the activation keys you used for RHEL systems to include the system group created above.

. On the {productname} Server {webui}, navigate to menu:Systems[Activation Keys].
. For each the Activation Keys you used for RHEL systems, click on it and:
. Navigate to the [guimenu]``Groups`` tab, and the [guimenu]``Join`` subtab.
. Check [systemitem]``Select rhel-systems``.
. Click btn:[Join Selected Groups].


== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].

[NOTE]
====
For the {redhat} custom channels, if you want to check the [guimenu]``Enable GPG Check`` field, you need to populate the [guimenu]``GPG Key URL`` field.
You can use the file URL of the GPG key stored in the directory [systemitem]``/etc/pki/rpm-gpg`` of the {redhat} minion.

Example:
[systemitem]``file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release``

For the complete list of the {redhat} product signing keys, see https://access.redhat.com/security/team/key.
====


== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]
