[[clients-almalinux]]
= Registering {almalinux} Clients

This section contains information about registering Salt clients running {almalinux} operating systems.

ifeval::[{suma-content} == true]
[IMPORTANT]
====
{almalinux} repository URLs are available from {scc}, but the packages and metadata are provided by AlmaLinux OS Foundation, not by {suse}.
====
endif::[]

[IMPORTANT]
====
Traditional clients are not available on {almalinux}{nbsp}8.
{almalinux}{nbsp}8 clients are only supported as Salt clients.
====

[WARNING]
====
When created at AWS, {almalinux} instances always have the same `machine-id` id at `/etc/machine-id`.
Make sure you regenerate the `machine-id` after the instance is created.
For more information, see xref:administration:tshoot-registerclones.adoc[].
====



== Add Software Channels

[NOTE]
====
Registering {almalinux} clients to {productname} is tested with the default SELinux configuration of ``enforcing`` with a ``targeted`` policy.
You do not need to disable SELinux to register {almalinux} clients to {productname}.
====

Before you can register {almalinux} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: `x86_64` and `aarch64`.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

//The products you need for this procedure are:
For example, when working with `x86_64` architecture, you need this product:

[[almalinux-channels-wizard]]
[cols="1,1", options="header"]
.{almalinux} Products - WebUI
|===

| OS Version | Product Name
| {almalinux} 8 | {almalinux} 8 x86_64

|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[almalinux-channels-suma-cli]]
[cols="1,1", options="header"]
.{almalinux} Channels - CLI
|===

| OS Version | Base Channel
| {almalinux} 8 | almalinux8-x86_64

|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[almalinux-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.{almalinux} Channels - CLI
|===

| OS Version | Base Channel | Client Channel       | AppStream Channel
| {almalinux} 8 | almalinux8      | almalinux8-uyuni-client | almalinux8-appstream

|===

include::snippets/addchannels_novendor_cli_multiarch.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]

ifeval::[{uyuni-content} == true]
[IMPORTANT]
====
For {almalinux} 8 clients, add both the Base and AppStream channels.
You require packages from both channels.
If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====
endif::[]

If you are using modular channels, you must enable the Python 3.6 module stream on the client.
If you do not provide Python 3.6, the installation of the [package]``spacecmd`` package will fail.

[NOTE]
====
You might notice some disparity in the number of packages available in the AppStream channel between upstream and the {productname} channel.
You might also see different numbers if you compare the same channel added at a different point in time.
This is due to the way that {almalinux} manages their repositories.
{almalinux} removes older version of packages when a new version is released, while {productname} keeps all of them, regardless of age.
====


include::snippets/appstream_admon.adoc[]


== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]


include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You need to create an activation key that is associated with your {almalinux} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].



ifeval::[{uyuni-content} == true]

== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]

endif::[]



== Register Clients

{almalinux} clients are registered in the same way as all other clients.
For more information, see xref:client-configuration:registration-overview.adoc[].


== Manage Errata

When you update {almalinux} clients, the packages include metadata about the updates.
