[[clients-centos]]
= Registering {centos} Clients

This section contains information about registering traditional and Salt clients running {centos} operating systems.

[IMPORTANT]
====
{centos} clients are based on {centos} and are unrelated to {sleses}, RES, {redhat}, or {es}.
You are responsible for arranging access to {centos} base media repositories and {centos} installation media, as well as connecting {productname} Server to the {centos} content delivery network.
====

[IMPORTANT]
====
Traditional clients are not available on {centos}{nbsp}8.
{centos}{nbsp}8 clients are only supported as Salt clients.
====



== Add Software Channels

Before you register {centos} clients to your {productname} Server, check that you have the {centos} product enabled, and the required channels are fully synchronized.

ifeval::[{suma-content} == true]

The channels you need for this procedure are:

[[centos-channels-wizard]]
[cols="1,1,1", options="header"]
.CentOS Channels - WebUI
|===
| OS Version | Base Channel   | Updates Channel
| {centos} 6 | centos6-x86_64 | centos6-updates for x86_64
| {centos} 7 | centos7-x86_64 | centos7-updates for x86_64
| {centos} 8 | centos8-x86_64 | centos8-appstream for x86_64
|===

include::snippets/add_channels_wizard.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[centos-channels-cli]]
[cols="1,1,1,1", options="header"]
.CentOS Channels - CLI
|===
| OS Version | Base Channel | Client Channel       | Updates Channel
| {centos} 6 | centos6      | centos6-uyuni-client | centos6-updates
| {centos} 7 | centos7      | centos7-uyuni-client |  centos7-updates
| {centos} 8 | centos8      | centos8-uyuni-client | centos8-appstream
|===

include::snippets/add_channels_cli.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]


[IMPORTANT]
====
For {centos} 8 clients, add both the Base and Appstream channels.
You will require packages from both channels.
If you do not add both channels, you will not be able to create the bootstrap repository, due to missing packages.
====



== Check Synchronization Status

ifeval::[{suma-content} == true]
include::snippets/check_sync_webui_suma.adoc[]
endif::[]

ifeval::[{uyuni-content} == true]
include::snippets/check_sync_webui_uyuni.adoc[]
endif::[]

include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You will need to create an activation key that is associated with your {centos} channels.

For more information on activation keys, see xref:client-configuration:clients-and-activation-keys.adoc[].



ifeval::[{uyuni-content} == true]
== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]
endif::[]



== Register Clients

{centos} clients are registered in the same way as all other clients.
For more information, see xref:client-configuration:registration-overview.adoc[].


[WARNING]
====
To register and use {centos}{nbsp}6 clients, you need to configure the {productname} Server to support older types of SSL encryption.
For more information about how to resolve this error, see ``Registering Older Clients`` at xref:client-configuration:tshoot-clients.adoc[].
====



== Manage Errata

When you update {centos} clients, the packages do not include metadata about the updates.
You can use a third-party errata service to obtain this information.

ifeval::[{suma-content} == true]

[IMPORTANT]
====
The third-party errata service described here is provided and maintained by the community.
It is not supported by {suse}.
====
endif::[]



.Procedure: Installing an Errata Service

. From the command prompt, as root, add the ``sle-module-development-tools`` module:
+
----
SUSEConnect --product sle-module-development-tools/15.1/x86_64
----
. Install the errata service:
+
----
zypper in  perl-Text-Unidecode
----
. Create a file for your errata script:
+
----
touch /usr/local/bin/cent-errata.sh
----
. Edit the new file to include this script, editing the repository details as required.
This script fetches the errata details from an external errata service, unpacks it, and publishes the details:
+
----
#!/bin/bash
mkdir -p /usr/local/centos
cd /usr/local/centos
rm *.xml
wget -c http://cefs.steve-meier.de/errata.latest.xml
#wget -c https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml
wget -c https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml
wget -c http://cefs.steve-meier.de/errata-import.tar
tar xvf errata-import.tar
chmod +x /usr/local/centos/errata-import.pl
export SPACEWALK_USER='<adminname>';export SPACEWALK_PASS='<password>'
/usr/local/centos/errata-import.pl --server '<servername>' \
--errata /usr/local/centos/errata.latest.xml  \
--include-channels=centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras \
--publish --rhsa-oval /usr/local/centos/com.redhat.rhsa-RHEL7.xml
----
. Set up a cron job to run the script daily:
+
----
ln -s /usr/local/bin/cent-errata.sh /etc/cron.daily
----

For more information on this tool, see https://cefs.steve-meier.de/.
