[[clients-sle]]
= Registering {sle} Clients

This section contains information about registering clients running these {sle} operating systems:

* {sles}{nbsp}15{nbsp}SP1
* {sles}{nbsp}15{nbsp}SP2
* {sles}{nbsp}15{nbsp}SP3

////
* {sles}{nbsp}12{nbsp}SP5
* {sles} for SAP{nbsp}15{nbsp}SP2
* {sles} for SAP{nbsp}12{nbsp}SP5
////

[NOTE]
====
Use the instructions in this chapter for preparing all {sle} products, including: 

* {sles} for SAP 
* {sle} Desktop 
* {sle} 
* {sle} Real Time

You can also use these instructions for older {sle} versions and service packs.
====



== Add Software Channels

Before you register {sle} clients to your {productname} Server, check that you have the {sle} product enabled, and the required channels are fully synchronized.

The products you need for this procedure are:

[[sle-channels-wizard]]
[cols="1,1", options="header"]
.SLE Products - WebUI
|===

| OS Version
| Product Name

| {sles} 15 SP1
| SUSE Linux Enterprise Server 15 SP1 x86_64

| {sles} 15 SP2
| SUSE Linux Enterprise Server 15 SP2 x86_64

| {sles} 15 SP3
| SUSE Linux Enterprise Server 15 SP3 x86_64

|===

include::snippets/add_channels_wizard.adoc[]

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[sle-channels-cli]]
[cols="1,1", options="header"]
.SLE Products - CLI
|===

| OS Version
| Base Channel

| {sles} 15 SP1
| sle-product-sles15-sp1-pool-x86_64

| {sles} 15 SP2
| sle-product-sles15-sp2-pool-x86_64

| {sles} 15 SP3
| sle-product-sles15-sp3-pool-x86_64

|===

[NOTE]
====
To find channel names of older products, at the command prompt on the {productname} Server, as root, use the [command]``mgr-sync`` command:

----
mgr-sync list --help
----

Then specify the argument you are interested in.
For example, [literal]``channels``:

----
mgr-sync list channels [-c]
----

====


include::snippets/addchannels_vendor_cli.adoc[]


ifeval::[{uyuni-content} == true]

To add the client tools, add these channels from the command prompt:

[[sle-channels-cli]]
[cols="1,1", options="header"]
.OpenSUSE Channels - CLI
|===

| OS Version
| Client Channel

| {sles} 15 SP1
| sles15-sp1-uyuni-client


| {sles} 15 SP2
| sles15-sp2-uyuni-client

|===

include::snippets/add_channels_cli.adoc[]

endif::[]



== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[IMPORTANT]
====
{sle} channels can be very large.
Synchronization can sometimes take several hours.
====



ifeval::[{uyuni-content} == true]
== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]

endif::[]



== Register Clients

To register your {sle} clients, you need a bootstrap repository.
By default, bootstrap repositories are automatically created, and regenerated daily for all synchronized products.
You can manually create the bootstrap repository from the command prompt, using this command:

----
mgr-create-bootstrap-repo --with-custom-channels
----

For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].
