[[client-upgrades-major]]
= Major Version Upgrade

The clients must have the latest available service pack (SP) for the installed operating system, with all the latest updates applied.
Before you start, ensure that the system is up to date and all updates have been installed successfully.

The upgrade is controlled by {yast} and {ay}, it does not use Zypper.



== Prepare to Migrate

Before you can migrate your client from SLE{nbsp}12 to SLE{nbsp}15, you need to:

. Prepare installation media
. Declare an autoinstallation distribution
. Create an activation key
. Create an autoinstallation profile



=== Prepare Installation Media

.Procedure: Preparing Installation Media
. On the container host, download an ISO image with the installation sources.

. Use [command]``mgradm`` to import the installation data from the ISO image:
+
----
mgradm distribution copy <image_name>.iso <image_name>
----

. Take a note of the distribution path reported by [command]``mgradm``.
  You will need it when you declare the distribution to {productname}.


[NOTE]
====
This image  can be used for multiple autoinstallation distributions.
====

For more information, see xref:client-configuration:autoinst-distributions.adoc[].



=== Declare an Autoinstallation Distribution

.Procedure: Declaring an Autoinstallation Distribution
. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > Distributions].
. Click [guimenu]``Create  Distribution`` , and complete these fields:
+
In the [guimenu]``Distribution Label`` field, enter a name to identify your autoinstallation distribution.
  For example, ``sles15sp6-x86_64``.
* In the [guimenu]``Tree Path`` field, enter the path to the installation media you already saved.
* Select the matching [guimenu]``Base Channel``.
  This must match the installation media.
* Select the [guimenu]``Installer Generation``.
  This must match the installation media.
* OPTIONAL: Specify kernel options to use when booting this distribution.
  There are multiple ways to provide kernel options.
  Only add options here that are generic for the distribution.
. Click btn:[Create Autoinstallable Distribution].


=== Create an Activation Key

For example, to switch from the old SLE{nbsp}12 base channel to the new SLE{nbsp}15 channel, you need an activation key.


.Procedure: Creating an Activation Key
. In the {productname} Server {webui}, navigate to menu:Systems[Activation Keys] and click [guimenu]``Create Key``.
. Enter a description for your key.
. Enter a key or leave it blank to generate an automatic key.
. OPTIONAL: If you want to limit the usage, enter your value in the [guimenu]``Usage`` text field.
. Select the [systemitem]``SLE-Product-SLES15-SP6-Pool for x86_64`` base channel.
. OPTIONAL: Select any [guimenu]``Add-On System Types``.
    For more information, see {sles-base-os-documentation}/article-modules.html.
. Click btn:[Create Activation Key].
. Click the [guimenu]``Child Channels`` tab and select the required channels.
. Click btn:[Update Key].



=== Create an Autoinstallation Profile

Autoinstallation profiles contain all the installation and configuration data needed to install a system.
They can also contain scripts to be executed after the installation is complete.
For example scripts that you can use as a starting point, see https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST.

For valid {ay} upgrade settings, see https://doc.opensuse.org/projects/autoyast/#CreateProfile-upgrade.


.Procedure: Creating an Autoinstallation Profile
. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > Profiles] and upload your autoinstallation profile script.
+
For example scripts that you can use as a starting point, see:
+
https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST.

. In the ``Kernel Options`` field, type ``autoupgrade=1``.
+
Optionally, you can also include the ``Y2DEBUG=1`` option.
The debug setting is not required but can help with investigating any future problems you might encounter.
+

[IMPORTANT]
====
Clients running in Azure cloud must add ``textmode=1 console=ttyS0`` to ``Kernel Options``.
====

. Paste the autoinstallation profile or use the file upload field.
. Click btn:[Create] to save.
. When the uploaded profile requires variables to be set, navigate to menu:Systems[Autoinstallation > Profiles], select the profile to edit, and navigate to the [guimenu]``Variables`` tab.
+
Specify the required variables, using this format:
+
----
<key>=<value>
----



== Migration

Before you begin, check that all the channels referenced in the autoinstallation profile are available and fully synchronized.

You can monitor the mirroring progress in [path]``/var/log/rhn/reposync/<channel-label>.log``.


.Procedure: Migrating
. In the {productname} Server {webui}, navigate to [guimenu]``Systems`` and select the client to be upgraded.
. Navigate to the [guimenu]``Provisioning`` tab, and select the autoinstallation profile you uploaded.
. Click btn:[Schedule Autoinstallation and Finish].
  The system downloads the required files, change the bootloader entries, reboot, and start the upgrade.


Next time the client synchronizes with the {productname} Server, it receives a re-installation job.
The re-installation job fetches the new kernel and initrd packages.
It also writes a new [path]``/boot/grub/menu.lst`` (GRUB Legacy) or [path]``/boot/grub2/grub.cfg`` (GRUB 2), containing pointers to the new kernel and initrd packages.

When the client next boots, it uses grub to boot the new kernel with its initrd.
PXE booting is not used during this process.

Approximately three minutes after the job was fetched, the client goes down for reboot.

[NOTE]
====
For clients, use the ``spacewalk/minion_script`` snippet to register the client again after migration has completed.
====
