[[clients-ubuntu-old]]
= Registering {ubuntu} 18.04 Clients


{productname} supports {ubuntu} 20.04 LTS and 22.04 LTS clients using Salt.
For information about registering Salt clients running {ubuntu} 20.04 and 22.04, see xref:client-configuration:clients-ubuntu.adoc[].

{ubuntu} 18.04 LTS has reached end-of-life.

include::snippets/eol-clients.adoc[]

[IMPORTANT]
====
* {ubuntu} 18.04 repository URLs are not available from {scc}
* Packages and metadata are provided by Ubuntu, not by {suse}
* For supported products, see the support table and the release notes
* Canonical does not endorse or support {productname}
====

[NOTE]
====
{ubuntu} is supported for Salt clients only.
Traditional clients are not supported.
====

Bootstrapping is supported for starting {ubuntu} clients and performing initial state runs such as setting repositories and performing profile updates.
However, the root user on {ubuntu} is disabled by default, so to use bootstrapping, you require an existing user with [command]``sudo`` privileges for Python.

This section contains information about registering {salt} clients running {ubuntu} 18.04 LTS operating systems.

== Add Software Channels

Before you register {ubuntu} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

The products you need for this procedure are:

[[ubuntu-old-channels-wizard]]
[cols="1,1", options="header"]
.Ubuntu Products - WebUI
|===

| OS Version     | Product Name
| {ubuntu} 18.04 | Ubuntu 18.04
|===

[IMPORTANT]
====
When using WebUI to add Ubuntu 18.04 channels, you also need to add ubuntu-1804-amd64-main and ubuntu-1804-amd64-main-updates channels using CLI, as described in <<ubuntu-old-channels-cli-suma>>.
====

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[ubuntu-old-channels-cli]]
[cols="1,1", options="header"]
.Ubuntu Channels - CLI
|===

| OS Version | Base Channel
| {ubuntu} 18.04 | ubuntu-18.04-pool-amd64
|===


include::snippets/addchannels_novendor_cli.adoc[]

[[ubuntu-old-channels-cli-suma]]
[cols="1,1,1,1,1", options="header"]
.Ubuntu Channels - CLI
|===

| OS Version
| Main Channel
| Security Channel
| Updates Channel

| {ubuntu} 18.04
| ubuntu-1804-amd64-main
| ubuntu-1804-amd64-main-security
| ubuntu-1804-amd64-main-updates

|===

Channels added using this method do not synchronize regularly by default.
You can configure a synchronization schedule using the {productname} {webui}.
Navigate to menu:Software[Manage > Channels], click the channel you added, and select the menu:Repositories[Sync] subtab.
Set a daily or weekly synchronization schedule, and click btn:[Schedule].


[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====


== Check Synchronization Status

include::snippets/check_sync_webui_suma.adoc[]


include::snippets/check_sync_cli.adoc[]

[NOTE]
====
{ubuntu} channels can be very large.
Synchronization can sometimes take several hours.
====



== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
A software channel cannot be assigned to a client when the GPG key is not trusted.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].


== Root Access

The root user on {ubuntu} is disabled by default for SSH access.

To be able to onboard using a regular user, you need to edit the [filename]``sudoers`` file.

[NOTE]
====
This issue happens with self-installed versions of {ubuntu}.
If the default user has been granted administrative privileges during installation time, a password is requiered to perform privilege escalation using [command]``sudo``.
With cloud instances this does not happen because [command]``cloud-init`` automatically creates a file under [path]``/etc/sudoers.d`` and grants privilege escalation through [command]``sudo`` without the need for a password.
====

.Procedure: Granting Root User Access

. On the client, edit the [filename]``sudoers`` file:
+
----
sudo visudo
----
+
Grant [command]``sudo`` access to the user by adding this line at the end of the [filename]``sudoers`` file.
Replace [systemitem]``<user>`` with the name of the user that is bootstrapping the client in the {webui}:
+
----
<user>  ALL=NOPASSWD: /usr/bin/python, /usr/bin/python2, /usr/bin/python3, /var/tmp/venv-salt-minion/bin/python
----

[NOTE]
====
This procedure grants root access without requiring a password, which is required for registering the client.
When the client is successfully installed it runs with root privileges, so the access is no longer required.
We recommend that you remove the line from the [path]``sudoers`` file after the client has been successfully installed.
====



== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]
