[[clients-slemicro]]
= Registering {micro} Clients

This section contains information about registering clients running these {nbsp}{micro} operating systems:

* {micro}{nbsp}5.1 {x86_64}
* {micro}{nbsp}5.1 {arm64}

[WARNING]
====
Support for {micro} clients is provided as a technology preview for testing purposes, and not all features are fully functional at this stage.
This feature is expected to be fully supported in a later version of {productname}.
Do not use this feature on production systems.
====

The {micro} is an ultra-reliable, lightweight operating system purpose built for edge computing.
It leverages the enterprise hardened security and compliance components of SUSE Linux Enterprise and merges them with a modern, immutable, developer-friendly OS platform.

The {micro} uses transactional updates.
Transactional updates are atomic (all updates are applied only if all updates succeed) and support rollbacks.
They do not affect a running system as no changes are activated until after the system is rebooted.
This information is displayed in the menu:Systems[Details > Overview] subtab.

For more information on transactional updates, see https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-transactional-updates.html

[WARNING]
====
When you install from a DVD or ISO image, [package]``salt-transactional-update`` and the dependencies such as Salt and [package]``python3`` are not installed.
These packages are required to register a {micro} client to {productname}.
On the client, before registering it, run as [literal]``root``:

----
transactional-update pkg install salt-transactional-update
----
====



== Add Software Channels

Before you register {micro} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]
The products you need for this procedure are:

[[slemicro-channels-wizard]]
[cols="1,1", options="header"]
.SLE Micro Products - WebUI
|===

| OS Version
| Product Name

| {micro} 5.1 {x86_64}
| SUSE Linux Enterprise Micro 5.1 aarch64

| {micro} 5.1 {arm64}
| SUSE Linux Enterprise Micro 5.1 x86_64

|===


include::snippets/addchannels_vendor_webui.adoc[]



Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[slemicro-channels-cli]]
[cols="1,1,1", options="header"]
.SLE Micro Products - CLI
|===

| OS Version
| Base Channel
| Updates Channel

| {micro} 5.1 {x86_64}
| suse-microos-5.1-pool-x86_64
| suse-microos-5.1-updates-x86_64

| {micro} 5.1 {arm64}
| suse-microos-5.1-pool-aarch64
| suse-microos-5.1-updates-aarch64

|===


include::snippets/addchannels_vendor_cli.adoc[]

endif::[]



== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== Register Clients

////
To register your {micro} clients, you need a bootstrap repository.
By default, bootstrap repositories are automatically created, and regenerated daily for all synchronized products.
You can manually create the bootstrap repository from the command prompt, using this command:

----
mgr-create-bootstrap-repo
----
////

For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].
