[[clients-ubuntu]]
= Registering {ubuntu} 20.04 Clients

This section contains information about registering Salt clients running {ubuntu} 20.04 LTS operating systems.

ifeval::[{suma-content} == true]
{productname} supports {ubuntu} 16.04 LTS, 18.04 LTS, and 20.04 LTS clients using Salt.
For information about registering Salt clients running {ubuntu} 16.04 LTS and 18.04 LTS, see xref:client-configuration:clients-ubuntu-old.adoc[].
endif::[]

[IMPORTANT]
====
Canonical does not endorse or support {productname}.
====

[NOTE]
====
{ubuntu} is supported for Salt clients only.
Traditional clients are not supported.
====

Bootstrapping is supported for starting {ubuntu} clients and performing initial state runs such as setting repositories and performing profile updates.
However, the root user on {ubuntu} is disabled by default, so to use bootstrapping, you require an existing user with [command]``sudo`` privileges for Python.



== Add Software Channels

Before you register {ubuntu} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

The products you need for this procedure are:

[[ubuntu-channels-wizard]]
[cols="1,1", options="header"]
.Ubuntu Products - WebUI
|===

| OS Version | Product Name
| {ubuntu} 20.04 | Ubuntu 20.04
|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[ubuntu-channels-cli]]
[cols="1,1", options="header"]
.Ubuntu Channels - CLI
|===

| OS Version | Base Channel
| {ubuntu} 20.04 | ubuntu-2004-amd64-main-amd64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[ubuntu-channels-cli-uyuni]]
[cols="1,1,1,1,1,1", options="header"]
.Ubuntu Channels - CLI
|===

| OS Version | Base Channel | Main Channel | Updates Channel | Security Channel | Client Channel

| {ubuntu} 20.04 | ubuntu-2004-amd64-main for amd64 | ubuntu-2004-amd64-main-uyuni | ubuntu-2004-amd64-main-updates-uyuni | ubuntu-2004-amd64-main-security-uyuni | ubuntu-2004-amd64-uyuni-client
|===

include::snippets/addchannels_novendor_cli.adoc[]

[IMPORTANT]
====
You need all the new channels fully synchronized before bootstrapping any Ubuntu client.
====

endif::[]



== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[NOTE]
====
{ubuntu} channels can be very large.
Synchronization can sometimes take several hours.
====



ifeval::[{uyuni-content} == true]

== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]

endif::[]



== Root Access

The root user on {ubuntu} is disabled by default.
You can enable it by editing the [filename]``sudoers`` file.

.Procedure: Granting Root User Access

. On the client, edit the [filename]``sudoers`` file:
+
----
sudo visudo
----
+
Grant [command]``sudo`` access to the user by adding this line at the end of the [filename]``sudoers`` file.
Replace [systemitem]``<user>`` with the name of the user that is bootstrapping the client in the {webui}:
+
----
<user>  ALL=NOPASSWD: /usr/bin/python, /usr/bin/python2, /usr/bin/python3
----

[NOTE]
====
This procedure grants root access without requiring a password, which is required for registering the client.
When the client is successfully installed it runs with root privileges, so the access is no longer required.
We recommend that you remove the line from the [path]``sudoers`` file after the client has been successfully installed.
====



== Register Clients

To register your {ubuntu} clients, you need a bootstrap repository.
By default, bootstrap repositories are automatically created, and regenerated daily for all synchronized products.
You can manually create the bootstrap repository from the command prompt, using this command:

----
mgr-create-bootstrap-repo
----

For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].
