[[clients-slemicro]]
= Registering {sle-micro} Clients

This section contains information about registering clients running {sle-micro} operating systems 5.1, 5.2, 5.3, 5.4, and 5.5 on {x86_64}, {arm64}, and {zsystems} (s390x) architectures.

The {sle-micro} uses transactional updates.
Transactional updates are atomic (all updates are applied only if all updates succeed) and support rollbacks.
They do not affect a running system as no changes are activated until after the system is rebooted.

For more information on transactional updates and rebooting, see
https://documentation.suse.com/sles/html/SLES-all/cha-transactional-updates.html.

// FIXME: We either must add this to the other client files (snippet), or
//        up to the suse registration page
The client registration described in this chapter, consists of these steps:

* Synchronize software channels for the new client's operating system and architecture by using either {webui} or command-line interface.

ifeval::[{uyuni-content} == true]

* Synchronize the client tool repository for the newly added operating systems by using command-line interface.

endif::[]

* Register the client with {productname} Server by using the {webui} or the command-line interface.

Additional sections describe ways to check and verify the registration procedure.


== Add Software Channels

Before you register {sle-micro} clients to the {productname} Server, you need to add the required software channels, and synchronize them.

You can add the software channels with the {webui} or from the command line.

include::snippets/arch-other-note.adoc[]

For the {webui} procedure, you need the following products:

//start with the NEWEST version on top
[[slemicro-channels-wizard]]
[cols="1,1", options="header"]
.SLE Micro Products - WebUI
|===

| OS Version
| Product Name

| {sle-micro} 5.5 {x86_64}
| SUSE Linux Enterprise Micro 5.5 x86_64

| {sle-micro} 5.5 {arm64}
| SUSE Linux Enterprise Micro 5.5 aarch64

| {sle-micro} 5.5 {s390x}
| SUSE Linux Enterprise Micro 5.5 s390x

| {sle-micro} 5.4 {x86_64}
| SUSE Linux Enterprise Micro 5.4 x86_64

| {sle-micro} 5.4 {arm64}
| SUSE Linux Enterprise Micro 5.4 aarch64

| {sle-micro} 5.4 {s390x}
| SUSE Linux Enterprise Micro 5.4 s390x

| {sle-micro} 5.3 {x86_64}
| SUSE Linux Enterprise Micro 5.3 x86_64

| {sle-micro} 5.3 {arm64}
| SUSE Linux Enterprise Micro 5.3 aarch64

| {sle-micro} 5.3 {s390x}
| SUSE Linux Enterprise Micro 5.3 s390x

| {sle-micro} 5.2 {x86_64}
| SUSE Linux Enterprise Micro 5.2 x86_64

| {sle-micro} 5.2 {arm64}
| SUSE Linux Enterprise Micro 5.2 aarch64

| {sle-micro} 5.2 {s390x}
| SUSE Linux Enterprise Micro 5.2 s390x

| {sle-micro} 5.1 {x86_64}
| SUSE Linux Enterprise Micro 5.1 x86_64

| {sle-micro} 5.1 {arm64}
| SUSE Linux Enterprise Micro 5.1 aarch64

| {sle-micro} 5.1 {s390x}
| SUSE Linux Enterprise Micro 5.1 s390x

|===

include::snippets/addchannels_vendor_webui.adoc[]



Alternatively, you can add channels from the command prompt.
For this procedure, you need the following products:

//start with the NEWEST version on top
[[slemicro-channels-cli]]
[cols="1,1,1", options="header"]
.SLE Micro Products - CLI
|===

| OS Version
| Base Channel
| Updates Channel

| {sle-micro} 5.5 {x86_64}
| sle-micro-5.5-pool-x86_64
| sle-micro-5.5-updates-x86_64

| {sle-micro} 5.5 {arm64}
| sle-micro-5.5-pool-arm64
| sle-micro-5.5-updates-arm64

| {sle-micro} 5.5 {zsystems} ({s390x})
| sle-micro-5.5-pool-s390x
| sle-micro-5.5-updates-s390x

| {sle-micro} 5.4 {x86_64}
| sle-micro-5.4-pool-x86_64
| sle-micro-5.4-updates-x86_64

| {sle-micro} 5.4 {arm64}
| sle-micro-5.4-pool-arm64
| sle-micro-5.4-updates-arm64

| {sle-micro} 5.4 {zsystems} ({s390x})
| sle-micro-5.4-pool-s390x
| sle-micro-5.4-updates-s390x

| {sle-micro} 5.3 {x86_64}
| sle-micro-5.3-pool-x86_64
| sle-micro-5.3-updates-x86_64

| {sle-micro} 5.3 {arm64}
| sle-micro-5.3-pool-arm64
| sle-micro-5.3-updates-arm64

| {sle-micro} 5.3 {zsystems} ({s390x})
| sle-micro-5.3-pool-s390x
| sle-micro-5.3-updates-s390x

| {sle-micro} 5.2 {x86_64}
| suse-microos-5.2-pool-x86_64
| suse-microos-5.2-updates-x86_64

| {sle-micro} 5.2 {arm64}
| suse-microos-5.2-pool-aarch64
| suse-microos-5.2-updates-aarch64

| {sle-micro} 5.2 {zsystems} ({s390x})
| suse-microos-5.2-pool-s390x
| suse-microos-5.2-updates-s390x

| {sle-micro} 5.1 {x86_64}
| suse-microos-5.1-pool-x86_64
| suse-microos-5.1-updates-x86_64

| {sle-micro} 5.1 {arm64}
| suse-microos-5.1-pool-aarch64
| suse-microos-5.1-updates-aarch64

| {sle-micro} 5.1 {zsystems} ({s390x})
| suse-microos-5.1-pool-s390x
| suse-microos-5.1-updates-s390x

|===

include::snippets/addchannels_vendor_cli.adoc[]

ifeval::[{uyuni-content} == true]

== Client Tools

Without client tools onboarding clients will fail.
Client tools you can only add from the command line.

To add the client tools, add these channels from the command prompt:

[[sle-micro-tools-channels-cli]]
[cols="1,1", options="header"]
.SLE Micro Channels - CLI
|===

| OS Version
| Client Channel

| {sle-micro} 5.5
| sle-micro-5.5-uyuni-client

| {sle-micro} 5.4
| sle-micro-5.4-uyuni-client

| {sle-micro} 5.3
| suse-micro-5.3-uyuni-client

| {sle-micro} 5.2
| suse-microos-5.2-uyuni-client

| {sle-micro} 5.1
| sle-microos-5.1-uyuni-client

|===


include::snippets/addchannels_novendor_cli.adoc[]


endif::[]



== Check Synchronization Status

ifeval::[{mlm-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== Register Clients

[WARNING]
====
{sle-micro} clients require a reboot after registering.

Following the bootstrapping process, automatic booting is disabled on {sle-micro} clients. This change was implemented due to intermittent automatic reboots, which could occurr before {salt} could relay the results of applying the bootstrap {salt} state.

Although a reboot is automatically scheduled after registration is completed, it is respecting the default reboot manager maintenance window.
This window may be several hours after the client is registered.
It is advisable to manually reboot the client after the registration script finishes, to speed up the registration and to see the system appear in the system list.
====

include::snippets/create_bootstrap_repo_register.adoc[]

When using a bootstrap script with {sle-micro} systems, ensure that the certificate section of the script has this content:

----
ORG_CA_CERT=RHN-ORG-TRUSTED-SSL-CERT
ORG_CA_CERT_IS_RPM_YN=0
----

Either edit the bootstrap script directly and add the settings, or create the bootstrap script with these parameters:

// 2023-12-12, ke: remains in /srv, see
// https://github.com/uyuni-project/uyuni-docs/pull/2682/files#r1423757456
----
mgrctl exec -ti -- mgr-bootstrap --script=bootstrap-sle-micro.sh \
    --ssl-cert=/srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT
----



[[clients-slemicro-reboot]]
== Reboot {sle-micro}

{sle-micro} is a transactional system.
Transactional updates in general support several reboot methods.
It is recommended to use [systemitem]``systemd`` for rebooting in systems managed by {productname}.
Using other methods can lead to undesired behavior.

When bootstrapping a transactional system on {productname}, [systemitem]``systemd`` will be configured as the reboot method ([literal]``REBOOT_METHOD``), if the system is in its default configuration.
Such a configuration allows {productname} to control the reboot action, and rebooting can be performed immediately or scheduled with {productname} as wanted.


=== Background Information

By default, the reboot method during client installation is set to [option]``auto``.
With the [option]``auto`` boot method, [command]``rebootmgrd`` will be used to reboot the system according to the configured policies if the service is running.
Policies can be to reboot instantly or during a maintenance window.
For more information, see the [command]``rebootmgrd``(8) man page.
Otherwise if [command]``rebootmgrd`` is not running, {productname} will call [command]``systemctl reboot``.

[NOTE]
====
Using any method different from [command]``systemd`` may cause undesired behavior.
====

// 2023-05-23, ke: The rest is commented and the user will not see the
//                 following remarks/background info:
////
Otherwise, the only thing Suma will be able to do is to ask for a reboot and it will be managed in the peculiarities of each reboot method. Not having control of when the reboot should happen, also takes away from Suma the ability to perform the reboot on its own maintenance windows, which is not the ideal configuration.

The user must be able to change reboot method at any time and SUSE Manager will keep it. But in this case we should alert in the documentation that using any method different from systemd may cause undesired behavior.
////
