[[clients-opensuse-tumbleweed]]
= Registering {opensuse} {tumbleweed} Clients
:revdate: 2025-10-08
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

This section contains information about registering clients running {opensuse} operating systems.
{productname} supports {opensuse} Tumbleweed clients using {salt}.

Bootstrapping is supported for starting {opensuse} clients and performing initial state runs such as setting repositories and performing profile updates.



== Add Software Channels


Before you register {opensuse} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: `x86_64` and `aarch64`.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

include::snippets/arch-other-note.adoc[]

For example, when working with `x86_64` architecture, you need this product:

ifeval::[{uyuni-content} == true]

[[opensuse-channels-wizard]]
[cols="1,1", options="header"]
.{opensuse} Products - WebUI
|===

| OS Version
| Product Name

| {opensuse} Tumbleweed
| {opensuse} Tumbleweed x86_64

|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[opensuse-leap-channels-cli]]
[cols="1,1", options="header"]
.{opensuse} Channels - CLI
|===

| OS Version | Base Channel
| {opensuse}  | opensuse-tumbleweed-pool

|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
[[opensuse-tumbleweed-channels-cli]]
[cols="1,1"]
.{opensuse} Channels - CLI
|===

| OS Version               | {opensuse} {tumbleweed}           
| Base Channel             | opensuse_tumbleweed                
| Client Channel           | opensuse_tumbleweed-uyuni-client   
| Updates Channel          | opensuse_tumbleweed-updates        
| Non-OSS Channel          | opensuse_tumbleweed-non-oss        
| Non-OSS Updates Channel  | opensuse_tumbleweed-non-oss-updates
| Backports Updates Channel| opensuse_tumbleweed-backports-updates
| SLE Updates Channel      | opensuse_tumbleweed-sle-updates

|===

include::snippets/addchannels_novendor_cli.adoc[]

endif::[]


== Check Synchronization Status

ifeval::[{mlm-content} == true]

include::snippets/check_sync_webui_mlm.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[IMPORTANT]
====
{opensuse} channels can be very large.
Synchronization can sometimes take several hours.
====


== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].



== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]
