[[clients-oracle]]
= Registering {oracle} Clients

This section contains information about registering traditional and Salt clients running {oracle} operating systems.

[IMPORTANT]
====
You are responsible for arranging access to {oracle} base media repositories and {oracle} installation media.
====

ifeval::[{suma-content} == true]

endif::[]


[IMPORTANT]
====
Traditional clients are not available on {oracle}{nbsp}8.
{oracle}{nbsp}8 clients are only supported as Salt clients.
====


== Server Requirements

Before you begin, check that your {productname} Server meets the requirements at xref:installation:hardware-requirements.adoc[].

Taskomatic uses one CPU core, and requires at least 3072{nbsp}MB of RAM.
To ensure that taskomatic has access to enough memory, open the [path]``/etc/rhn/rhn.conf`` configuration file, and add this line:

----
taskomatic.java.maxmemory=3072
----

Restart Taskomatic:
----
systemctl restart taskomatic
----



== Channel and Repository Management


[IMPORTANT]
====
For {oracle} 8 clients, add both the ``BaseOS`` and ``Appstream`` channels.
You will require packages from both channels.
If you do not add both channels, you will not be able to create the bootstrap repository, due to missing packages.
====



.Procedure: Adding Channels and Repositories
. At the command prompt on the {productname} Server, as root, install the [package]``spacewalk-utils`` package:
+
----
zypper in spacewalk-utils
----
. Add the {oracle} base, updates, and client channels, specifying the {oracle} version and architecture:
+
----
spacewalk-common-channels -a x86_64 oracle8 \
oracle8-uyuni-client oracle8-appstream
----

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====



.Procedure: Synchronizing {oracle} Repositories

. In the {productname} {webui}, navigate to menu:Software[Manage], and check every {oracle} channel.
. In the [guimenu]``Repositories`` tab, navigate to the [guimenu]``Sync`` subtab, and click btn:[Sync Now].
You can also create a regular synchronization schedule on this page.



== Create an Activation Key

You will need to create an activation key that is associated with your {oracle} channels.

For more information on activation keys, see xref:client-configuration:clients-and-activation-keys.adoc[].



== Register Clients

{oracle} clients are registered in the same way as all other clients.
For more information, see xref:client-configuration:registration-overview.adoc[].
