[[clients-rocky]]
= Registering {rocky} Clients

This section contains information about registering clients running {rocky} operating systems.

ifeval::[{suma-content} == true]
// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====
* {rocky} repository URLs are available from {scc}
* Packages and metadata are provided by Rocky Enterprise Software Foundation, not by {suse}
* For supported products, see the support table and the release notes
====
endif::[]



[NOTE]
====
Registering {rocky} clients to {productname} is tested with the default SELinux configuration of ``enforcing`` with a ``targeted`` policy.
You do not need to disable SELinux to register {rocky} clients to {productname}.
====



== Add Software Channels

Before you can register {rocky} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: `x86_64` and `aarch64`, on version 9 additionally {ppc64le} and {s390x}.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

include::snippets/arch-other-note.adoc[]

ifeval::[{suma-content} == true]

For example, when working with `x86_64` architecture, you need this product:

[[rocky-channels-wizard]]
[cols="1,1", options="header"]
.{rocky} Products - WebUI
|===

| OS Version | Product Name
| {rocky} 9  | {rocky} 9 x86_64
| {rocky} 8  | {rocky} 8 x86_64

|===

include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[rocky-channels-suma-cli]]
[cols="1,1", options="header"]
.{rocky} Channels - CLI
|===

| OS Version | Base Channel
| {rocky} 9  | rockylinux9-x86_64
| {rocky} 8  | rockylinux8-x86_64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]
The channels you need for this procedure are:

[[rocky-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.{rocky} Channels - CLI
|===

| OS Version | Base Channel | Client Channel           | AppStream Channel
| {rocky} 9  | rockylinux9  | rockylinux9-uyuni-client | rockylinux9-appstream
| {rocky} 8  | rockylinux8  | rockylinux8-uyuni-client | rockylinux8-appstream
|===

include::snippets/addchannels_novendor_cli_multiarch.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]


ifeval::[{uyuni-content} == true]
[IMPORTANT]
====
For {rocky}{nbsp}8 and {rocky}{nbsp}9 clients, add both the Base and AppStream channels.
You require packages from both channels.
If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====
endif::[]

[NOTE]
====
You might notice some disparity in the number of packages available in the AppStream channel between upstream and the {productname} channel.
You might also see different numbers if you compare the same channel added at a different point in time.
This is due to the way that {rocky} manages their repositories.
{rocky} removes older version of packages when a new version is released, while {productname} keeps all of them, regardless of age.
====

If you are using modular channels with {rocky} 8, you must enable the Python 3.6 module stream on the client.
If you do not provide Python 3.6, the installation of the [package]``spacecmd`` package will fail.


== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]


include::snippets/check_sync_cli.adoc[]



== Create an Activation Key

You need to create an activation key that is associated with your {rocky} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].



== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
A software channel cannot be assigned to a client when the GPG key is not trusted.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].



== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]



== Manage Errata

When you update {rocky} clients, the packages include metadata about the updates.
