[[clients-raspberrypios]]
= Registering {raspberrypios} Clients

This section contains information about registering clients running {raspberrypios} operating systems.

Bootstrapping can be used with {raspberrypios} clients for performing initial state runs, and for profile updates.

ifeval::[{suma-content} == true]
// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====
* {raspberrypios} repository URLs are available from {scc}
* Packages and metadata are provided by Raspberry Pi OS, not by {suse}
* For supported products, see the support table and the release notes
====
endif::[]

== Prepare to Register

Some preparation is required before you can register {raspberrypios} clients to the {productname} Server:

* Ensure DNS is correctly configured and provides an entry for the client.
  Alternatively, you can configure the ``/etc/hosts`` files on both the {productname} Server and the client with the appropriate entries.
* The client must have the date and time synchronized with the {productname} Server before registration.



== Add Software Channels

Before you register {raspberrypios} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The architectures currently supported are: {arm64} and {armhf}.
For full list of supported products and architectures, see xref:client-configuration:supported-features.adoc[].

ifeval::[{uyuni-content} == true]

The channels you need for this procedure are:

[[raspberrypios-channels-uyuni-cli]]
[cols="1,1,1", options="header"]
.Raspberry Pi OS Channels - CLI
|===

| Channel description
| {arm64}
| {armhf}

| Base Channel
| raspberrypios-12-pool-arm64-uyuni
| raspberrypios-12-pool-armhf-uyuni

| Client Channel
| raspberrypios-12-arm64-uyuni-client
| raspberrypios-12-armhf-uyuni-client

| Updates Channel
| raspberrypios-12-arm64-main-updates-uyuni
| -

| Contributions Channel
| raspberrypios-12-arm64-contrib-uyuni
| raspberrypios-12-armhf-contrib-uyuni

| Non Free Channel
| raspberrypios-12-arm64-non-free-uyuni
| raspberrypios-12-armhf-non-free-uyuni

| Non Free Firmware Channel
| raspberrypios-12-arm64-non-free-firmware-uyuni
| -

| Raspberry Channel
| raspberrypios-12-arm64-raspberry-uyuni
| raspberrypios-12-armhf-raspberry-uyuni

| Contribution Updates
| raspberrypios-12-arm64-contrib-updates-uyuni
| -

| Non Free Updates
| raspberrypios-12-arm64-non-free-updates-uyuni
| -

| Non Free Firmware Updates
| raspberrypios-12-arm64-non-free-firmware-updates-uyuni
| -

| Security Main Channel
| raspberrypios-12-arm64-main-security-uyuni
| -

| Security Contribution Channel
| raspberrypios-12-arm64-contrib-security-uyuni
| -

| Security Non Free Channel
| raspberrypios-12-arm64-non-free-security-uyuni
| -

| Security Non Free Firmware Channel
| raspberrypios-12-arm64-non-free-firmware-security-uyuni
| -

| RPI Channel
| -
| raspberrypios-12-armhf-rpi-uyuni

|===

include::snippets/addchannels_novendor_cli.adoc[]

[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

[IMPORTANT]
====
You need all the new channels fully synchronized before bootstrapping any {raspberrypios} client.
====

endif::[]

== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]


[NOTE]
====
{raspberrypios} channels can be very large.
Synchronization can sometimes take several hours.
====


== Create an Activation Key

You need to create an activation key that is associated with your {raspberrypios} channels.

For more information on activation keys, see xref:client-configuration:activation-keys.adoc[].




== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].

[NOTE]
====
{raspberrypios} clients can require multiple GPG keys to be installed.
====

When synchronizing third-party {raspberrypios} repositories, you will need to import the appropriate GPG key on the server.
If the GPG key is missing, synchronization will fail.

For {raspberrypios} repositories, only the metadata is signed.
Therefore importing a GPG key for the software channel is not needed.
Packages will not be re-signed by {productname}.

To see which GPG keys are already imported to {productname} Server, run the following command:

----
mgrctl exec -- gpg --homedir /var/lib/spacewalk/gpgdir --list-keys
----

To import a new GPG key, run the following command:

----
mgradm gpg add <filename>.gpg
----



== Root Access

The root user on {raspberrypios} is disabled by default for SSH access.

To be able to onboard using a regular user, you need to edit the [filename]``sudoers`` file.

.Procedure: Granting Root User Access

. On the client, edit the [filename]``sudoers`` file:
+
----
sudo visudo
----
+
Grant [command]``sudo`` access to the user by adding this line at the end of the [filename]``sudoers`` file.
Replace [systemitem]``<user>`` with the name of the user that is bootstrapping the client in the {webui}:
+
----
<user>  ALL=NOPASSWD: /usr/bin/python, /usr/bin/python2, /usr/bin/python3, /var/tmp/venv-salt-minion/bin/python
----

[NOTE]
====
This procedure grants root access without requiring a password, which is required for registering the client.
When the client is successfully installed it runs with root privileges, so the access is no longer required.
We recommend that you remove the line from the [path]``sudoers`` file after the client has been successfully installed.
====



== Register Clients


include::snippets/create_bootstrap_repo_register.adoc[]
