[[clients-oes]
= Registering {oes} Clients

This section contains information about registering clients running {oes} operating systems.



== Add Software Channels

include::snippets/arch-other-note.adoc[]

Before you register {oes} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

The products you need for this procedure are:

[[oes-channels-wizard]]
[cols="1,1", options="header"]
.OES Products - WebUI
|===

| OS Version
| Product Name

| {oes} 24.4
| Open Enterprise Server 24.4

| {oes} 23.4
| Open Enterprise Server 23.4

|===


include::snippets/addchannels_vendor_webui.adoc[]

Alternatively, you can add channels at the command prompt.
The channels you need for this procedure are:

[[oes-channels-cli]]
[cols="1,1", options="header"]
.OES Products - CLI
|===

| OS Version
| Base Channel

| {oes} 24.4
| 

| {oes} 23.4
| 

|===

To find channel names of older products, at the command prompt on the {productname} Server, as root, use the [command]``mgr-sync`` command:

----
mgr-sync list --help
----

Then specify the argument you are interested in.
For example, [literal]``channels``:

----
mgr-sync list channels [-c]
----


include::snippets/addchannels_vendor_cli.adoc[]


ifeval::[{uyuni-content} == true]

To add the client tools, add these channels from the command prompt:

[[oes-tools-channels-cli]]
[cols="1,1", options="header"]
.Open Enterprise Channels - CLI
|===

| OS Version
| Client Channel

| {oes} 24.4
| 

| {oes} 23.4
| 

|===


include::snippets/addchannels_novendor_cli.adoc[]


endif::[]



== Check Synchronization Status

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]


include::snippets/check_sync_cli.adoc[]


[IMPORTANT]
====
{sle} channels can be very large.
Synchronization can sometimes take several hours.
====


ifeval::[{uyuni-content} == true]

== Manage GPG Keys

Clients use GPG keys to check the authenticity of software packages before they are installed.
Only trusted software can be installed on clients.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients.
It is the task of the administrator to decide which keys are needed and can be trusted.
Because a software channel cannot be used when the GPG key is not trusted, the decision of assigning a channel to a client depends on the decision of trusting the key.
====

For more information about GPG keys, see xref:client-configuration:gpg-keys.adoc[].

////
[NOTE]
====
Use the same GPG key for both {sles}{nbsp}15 and {sles}{nbsp}12 clients.
The correct key is called ``sle12-gpg-pubkey-39db7c82.key``.
====
////

endif::[]



== Register Clients

include::snippets/create_bootstrap_repo_register.adoc[]
