[[clients-rh-rhui]]
= Registering {rhel} Clients with RHUI

If you are running {rhel} clients directly, rather than using {sleses}, you need to use Red Hat sources to retrieve and update packages.
This section contains information about using the {redhat} update infrastructure (RHUI) to register traditional and Salt clients running {rhel} operating systems.

For information about using {redhat} content delivery network (CDN) instead, see xref:client-configuration:clients-rh-cdn.adoc[].


[IMPORTANT]
====
{rhel} clients are based on {redhat} and are unrelated to {sleses}, RES, {redhat}, or {sles}.
You are responsible for arranging access to {redhat} base media repositories and {rhela} installation media, as well as connecting {productname} Server to the {redhat} content delivery network.
You must obtain support from {redhat} for all your {rhela} systems.
If you do not do this, you might be violating your terms with {redhat}.
====


[IMPORTANT]
====
Traditional clients are available on {rhel}{nbsp}6 and 7 only.
{rhel}{nbsp}8 clients are supported as Salt clients.
====



== Import Entitlements and Certificates

{redhat} clients require a {redhat} certificate authority (CA) and entitlement certificate, and an entitlement key.

Entitlement certificates are embedded with expiration dates, which match the length of the support subscription.
To avoid disruption, you will need to repeat this process at the end of every support subscription period.

{redhat} supply a subscription manager tool to manage subscription assignments.
It runs locally to track installed products and subscriptions.
Clients must be registered with the subscription manager to obtain certificates.

{redhat} clients use a URL to replicate repositories.
The URL will change depending on where the {redhat} client is registered.

{redhat} clients can be registered in three different ways:

* {redhat} content delivery network (CDN) at redhat.com
* {redhat} Satellite Server
* {redhat} update infrastructure (RHUI) in the cloud

This guide covers clients registered to {redhat} update infrastructure (RHUI).
You must have at least one system registered to RHUI, with an authorized subscription for repository content.

For information about using {redhat} content delivery network (CDN) instead, see xref:client-configuration:clients-rh-cdn.adoc[].


[IMPORTANT]
====
Satellite certificates for client systems require a Satellite server and subscription.
Clients using Satellite certificates are not supported with {productname} Server.
====

[WARNING]
====
Entitlement certificates are embedded with expiration dates, which match the length of the support subscription.
To avoid disruption, you will need to repeat this process at the end of every support subscription period.
====

{redhat} supplies the subscription-manager tool to manage subscription assignments.
It runs locally on the client system to track installed products and subscriptions.
Register to redhat.com with subscription-manager, then follow this procedure to obtain certificates.



.Procedure: Registering Clients to Subscription Manager

. On the client system, at the command prompt, register with the subscription manager tool:
+
----
subscription-manager register
----
+
Enter your {redhat} Portal username and password when prompted.
. Copy your entitlement certificate and key from the client system, to a location that the {productname} Server can access:
+
----
cp /etc/pki/entitlement/ /<example>/entitlement/
----
+
[NOTE]
====
Your entitlement certificate has a file extension of [path]``.crt``.
For example, [path]``/etc/pki/rhui/product/content-rhel8.crt``.
The key has a file extension of [path]``.key``.
For example, [path]``/etc/pki/rhui/content-rhel8.key``.
====
+
. Copy the {redhat} CA Certificate file from the client system, to the same web location as the entitlement certificate and key:
+
----
cp /etc/rhsm/ca/redhat-uep.pem /example/entitlement
----


To manage repositories on your {redhat} client, you need to import the CA and entitlement certificates to the {productname} Server.
This requires that you perform the import procedure three times, to create three entries: one each for the entitlement certificate, the entitlement key, and the {redhat} certificate.



.Procedure: Importing Certificates to the Server

. On the {productname} Server {webui}, navigate to menu:Systems[Autoinstallation > GPG and SSL Keys].
. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement certificate:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-Cert-date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement certificate, and select the [path]``.crt`` certificate file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement key:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-Key-date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement key, and select the [path]``.key`` key file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the {redhat} certificate:
* In the [guimenu]``Description`` field, type [systemitem]``redhat-uep``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``.
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the {redhat} certificate, and select the certificate file.
. Click btn:[Create Key].



== Prepare Custom Repositories and Channels

To mirror the software from RHUI, you need to create custom channels and repositories in {productname} that are linked to RHUI by a URL.
You must have entitlements to these products in your Red Hat Portal for this to work correctly.
You can use the yum utility to get the URLs of the repositories you want to mirror:

----
yum repolist -v | grep baseurl
----

You can use these repository URLs to create custom repositories.
This allows you to mirror only the content you need to manage your clients.

[IMPORTANT]
====
You can only create custom versions of {redhat} repositories if you have the correct entitlements in your {redhat} Portal.
====


The details you need for this procedure are:

[[redhat-repos-manual]]
[cols="1,1", options="header"]
.Red Hat Custom Repository Settings
|===
| Option                 | Parameter
| Repository URL         | The content URL provided by {redhat} CDN
| Has Signed Metadata?   | Uncheck all {redhat} Enterprise repositories
| SSL CA Certificate     | [systemitem]``redhat-uep``
| SSL Client Certificate | [systemitem]``Entitlement-Cert-date``
| SSL Client Key         | [systemitem]``Entitlement-Key-date``
|===


include::snippets/manual_repos.adoc[]



The channels you need for this procedure are:

[[redhat-channels-custom]]
[cols="1,1,1", options="header"]
.Red Hat Custom Channels
|===
| OS Version | Base Product          | Base Channel
| {redhat} 6 | RHEL6-Pool for x86_64 | rhel6-pool-x86_64
| {redhat} 7 | RHEL7-Pool for x86_64 | rhel7-pool-x86_64
| {redhat} 8 | RHEL8-Pool for x86_64 | rhel8-pool-x86_64
|===


include::snippets/manual_channels.adoc[]

[IMPORTANT]
====
For {redhat} 8 clients, add both the Base and Appstream channels.
You will require packages from both channels.
If you do not add both channels, you will not be able to create the bootstrap repository, due to missing packages.
====


include::snippets/manual_associate.adoc[]



== Add Software Channels

Before you register {redhat} clients to your {productname} Server, check that you have the {redhat} product enabled, and the required channels are fully synchronized.

ifeval::[{suma-content} == true]

Your {susemgr} subscription entitles you to the tools channels for {sleses} (also known as {redhat} Expanded Support or RES).
You must use the client tools channel to create the bootstrap repository.
This procedure applies to both Salt and traditional clients.
endif::[]

ifeval::[{suma-content} == true]

The products you need for this procedure are:

[[redhat-channels-wizard]]
[cols="1,1,1", options="header"]
.Red Hat Products - WebUI
|===
| OS Version | Base Channel                     | Pool Channel
| {redhat} 6 | RHEL6 Base x86_64                | RHEL6-Pool for x86_64
| {redhat} 7 | RHEL7 Base x86_64                | RHEL7-Pool for x86_64
| {redhat} 8 | RHEL or SLES ES or CentOS 8 Base | RHEL8-Pool for x86_64
|===


include::snippets/add_channels_wizard.adoc[]


endif::[]

ifeval::[{uyuni-content} == true]

The channels you need for this procedure are:

[[redhat-channels-cli]]
[cols="1,1,1,1", options="header"]
.Red Hat Channels - CLI
|===

| OS Version
| Base Channel
| Client Channel
| Tools Channel

| {redhat} 6
| rhel-x86_64-server-6
| -
| res6-suse-manager-tools-x86_64

| {redhat} 7
| rhel-x86_64-server-7
| -
| res7-suse-manager-tools-x86_64

| {redhat} 8
| rhel-x86_64-server-8
| -
| res8-suse-manager-tools-x86_64

|===


include::snippets/add_channels_cli.adoc[]


[NOTE]
====
The client tools channel provided by [command]``spacewalk-common-channels`` is sourced from {uyuni} and not from {suse}.
====

endif::[]


To use RHUI, you need to manually add the required HTTP headers to the configuration file.
Without them, you cannot successfully perform a client synchronization.



.Procedure: Adding HTTP Headers to the Configuration File
. Locate the [systemitem]``X-RHUI-ID`` and [systemitem]``X-RHUI-SIGNATURE`` HTTP headers from your RHUI instance.
. Open the [path]``/etc/rhn/spacewalk-repo-sync/extra_headers.conf`` configuration file, and add or edit these lines with the correct information:
+
----
[channel_label]
X-RHUI-ID=value
X-RHUI-SIGNATURE=value
----
. Alternatively, use these commands to locate the information and add it to the configuration file:
+
----
echo "X-RHUI-ID=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document|base64|tr -d '\n')"
echo "X-RHUI-SIGNATURE=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/signature|base64|tr -d '\n')"
----



== Check Synchronization Status

ifeval::[{suma-content} == true]


include::snippets/check_sync_webui_suma.adoc[]


endif::[]

ifeval::[{uyuni-content} == true]


include::snippets/check_sync_webui_uyuni.adoc[]


endif::[]


include::snippets/check_sync_cli.adoc[]


[NOTE]
====
{rhel} channels can be very large.
Synchronization can sometimes take several hours.
====


.Procedure: OPTIONAL: Creating a Salt State to Deploy Configuration Files

. On the {productname} Server {webui}, navigate to menu:Configuration[Channels].
. Click btn:[Create State Channel].
* In the [guimenu]``Name`` field, type [systemitem]``subscription-manager: disable yum plugins``.
* In the [guimenu]``Label`` field, type [systemitem]``subscription-manager-disable-yum-plugins``.
* In the [guimenu]``Description`` field, type [systemitem]``subscription-manager: disable yum plugins``.
* In the [guimenu]``SLS Contents`` field, leave it empty.
. Click btn:[Create Config Channel].
. Click btn:[Create Configuration File].
* In the [guimenu]``Filename/Path`` field, type [systemitem]``/etc/yum/pluginconf.d/subscription-manager.conf``.
* In the [guimenu]``File Contents`` field, type:
----
[main]
enabled=0
----
. Click btn:[Create Configuration File].
. Take note of the value of the field [guimenu]``Salt Filesystem Path``.
. Click the name of the configuration channel.
. Click [guimenu]``View/Edit 'init.sls' File``.
* In the [guimenu]``File Contents`` field, type:
----
configure_subscription-manager-disable-yum-plugins:
  cmd.run:
    - name: subscription-manager config --rhsm.auto_enable_yum_plugins=0
    - watch:
      - file: /etc/yum/pluginconf.d/subscription-manager.conf
  file.managed:
    - name: /etc/yum/pluginconf.d/subscription-manager.conf
    - source: salt:///etc/yum/pluginconf.d/subscription-manager.conf
----
. Click btn:[Update Configuration File].


[NOTE]
====
The ``Creating a Salt State to Deploy Configuration Files`` procedure is optional.
====


.Procedure: Creating a System Group for {rhel} Clients

. On the {productname} Server {webui}, navigate to menu:Systems[System Groups].
. Click btn:[Create Group].
* In the [guimenu]``Name`` field, type [systemitem]``rhel-systems``.
* In the [guimenu]``Description`` field, type [systemitem]``All RHEL systems``.
. Click btn:[Create Group].
. Click [guimenu]``States`` tab.
. Click [guimenu]``Configuration Channels`` tab.
. Type [systemitem]``subscription-manager: disable yum plugins`` at the search box.
. Click btn:[Search] and the state will appear.
. Click the checkbox for the state at the [systemitem]``Assign`` column.
. Click btn:[Save changes].
. Click btn:[Confirm].

If you already have RHEL systems added to {productname}, assign them to the new system group, and then apply the highstate.



.Procedure: Adding the System Group to Activation Keys

You need to modify the activation keys you used for RHEL systems to include the system group created above.

. On the {productname} Server {webui}, navigate to menu:Systems[Activation Keys].
. For each the Activation Keys you used for RHEL systems, click it and:
* Navigate to the [guimenu]``Groups`` tab, and the [guimenu]``Join`` subtab.
* Check [systemitem]``Select rhel-systems``.
* Click btn:[Join Selected Groups].



ifeval::[{uyuni-content} == true]
== Trust GPG Keys on Clients

include::snippets/trust_gpg.adoc[]

endif::[]



== Register Clients

To register your {redhat} clients, you need a bootstrap repository.
By default, bootstrap repositories are automatically created, and regenerated daily for all synchronized products.
You can manually create the bootstrap repository from the command prompt, using this command:

----
mgr-create-bootstrap-repo --with-custom-channels
----

For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].


[WARNING]
====
To register and use {rhel}{nbsp}6 clients, you need to configure the {productname} Server to support older types of SSL encryption.
For more information, see ``Registering Older Clients`` at xref:client-configuration:tshoot-clients.adoc[].
====



== Package Management and {rhel}{nbsp}8 Clients

If you are using {rhel}{nbsp}8 clients, you cannot perform package operations such as installing or upgrading directly from modular repositories like the {rhel} Appstream repository.
You can use the Appstream filter with content lifecycle management to transform modular repositories into regular repositories.

For more information about content lifecycle management, see xref:administration:content-lifecycle.adoc[].
