[[cli-client-proxy]]
== Register on the Command Line

// FIXME: 2023-10-24, ke: is preinstalled Salt still required?  Salt bundle?

Instead of the {webui}, you can use the command line to register a client to a proxy.
This procedure requires that you have installed the Salt package on the client before registration.
For SLE 12 based clients, you also must have activated the [systemitem]``Advanced Systems Management`` module.



.Procedure: Registering Clients to a Proxy Using the Command Line

. Choose a client configuration file located at:
+
----
/etc/salt/minion
----
+
or:
+
----
/etc/salt/minion.d/NAME.conf
----
+
This is sometimes also called a minion file.
. Add the proxy FQDN as the `master` to the client configuration file:
+
----
master: PROXY123.EXAMPLE.COM
----

. Restart the [systemitem]``salt-minion`` service:
+
----
systemctl restart salt-minion
----
. On the server, accept the new client key; replace [systemitem]``<client>`` with the name of your client:
+
----
salt-key -a '<client>'
----
