[[configuration-management]]
= Configuration Management
:description: Manage centrally distributed configuration files for your clients with SUSE Multi-Linux Manager and YaST tools
:revdate: 2026-04-20
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


You can use configuration files and channels to manage configuration for your clients, rather than configuring each client manually.

Configuration parameters are scripted and stored in configuration files.
You can write configuration files directly using the {productname} {webui}, or you can upload or link to files that exist in other locations.

Configuration channels are used to organize configuration files.
You can subscribe clients to configuration channels, and deploy configuration files as required.

Configuration files are version-controlled, so you can add configuration settings, test them on your clients, and roll back to a previous revision as required.
When you have created your configuration channels, you can also perform comparisons between various configuration files, and between revisions of the same configuration file.

Configuration files are provided through Configuration Channels or State Channels.

This table shows the supported features, where:

* {check} features are supported by {suse}
* {cross} features are not supported by {suse}
* {question} features are under consideration, and may or may not be supported at a later date.


.Configuration Management Supported Features
[cols="1,1", options="header"]
|===

| Feature
| Status

| Config Channels
| {check}

| State Channels
| {check}

| Deploying Files
| {check}

| Comparing Files
| {question}

| Applying the Highstate
| {check}

| File Import from a Client
| {cross}

| Jinja Templating
| {check}

|===



== Create configuration channels


=== Configuration channel

To create a new configuration channel:

.Procedure: Creating a configuration channel
[role=procedure]
____
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click btn:[Create Config Channel].

. Type a name for the channel.

. Type a label for the channel.
    This field must contain only letters, numbers, hyphens (``-``) and underscores (``_``).

. Type a description for the channel that allows you to distinguish it from other channels.

. Click btn:[Create Config Channel] to create the new channel.
____



=== State channel

State channels use {salt} states on clients:

.Procedure: Creating a {salt} state channel
[role=procedure]
____
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click btn:[Create State Channel].

. Type a name for the channel.

. Type a label for the channel.
    This field must contain only letters, numbers, hyphens (``-``) and underscores (``_``).

. Type a description for the channel that allows you to distinguish it from other channels.

. Type the [guimenu]``SLS Contents`` for the [path]``init.sls`` file.

. Click btn:[Create Config State Channel] to create the new channel.
____


== Add configuration files, directories, or symbolic links

When you have created a configuration channel you can add a configuration file, directory, or symbolic link:

.Procedure: Adding a configuration file, directory, or symbolic link
[role=procedure]
____
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click the name of the configuration channel that you want to add a configuration file to, and navigate to the menu:Add Files[Create File] subtab.

. In the [guimenu]``File Type`` field, choose whether you want to create a text file, directory, or symbolic link.
. In the [path]``Filename/Path`` field, type the absolute path to the location where the file should be deployed.

. If you are creating a symbolic link, type the target file and path in the [guimenu]``Symbolic Link Target Filename/Path`` field.

. Type the [guimenu]``User name`` and [guimenu]``Group name`` for the file in the [guimenu]``Ownership`` field, and the [guimenu]``File Permissions Mode``.

. If the client has SELinux enabled, you can configure [guimenu]``SELinux contexts`` to enable the required file attributes (for example: user, role, and file type).
. You can use Jinja templating with grains or pillar data instead of legacy macro delimiters.

. Enter the configuration file contents in the [guimenu]``File Contents`` text box, using the script drop-down box to choose the appropriate scripting language.

. Click btn:[Create Configuration File].

____


== Subscribe clients to configuration channels

You can subscribe individual clients to configuration channels by navigating to menu:Systems[System List], selecting the client you want to subscribe, and navigating to the [guimenu]``Configuration`` tab.
To subscribe multiple clients to a configuration channel, you can use the system set manager (SSM).


.Procedure: Subscribing multiple clients to configuration channels
[role=procedure]
____
. In the {productname} {webui}, navigate to menu:Systems[Systems List] and select the clients you want to work with.

. Navigate to menu:Systems[System Set Manager], and go to the menu:Configuration[Subscribe to Channels] subtab to see the list of available configuration channels.

. OPTIONAL: Click the number in the [guimenu]``Systems currently subscribed`` column to see which clients are currently subscribed to the configuration channel.

. Check the configuration channels you want to subscribe to, and click btn:[Continue].

. Rank the configuration channels using the up and down arrows.
    Where settings conflicts occur between configuration channels, channels closer to the top of the list take precedence.

. Determine how the channels are applied to the selected clients.
    Click btn:[Subscribe With Lowest Priority] to add the new channels at a lower priority than currently subscribed channels.
    Click btn:[Subscribe with Highest Priority] to add the new channels at a higher priority than currently subscribed channels.
    Click btn:[Replace Existing Subscriptions] to remove existing channels and replace them with the new channels.

. Click btn:[Apply Subscriptions].

____

[NOTE]
====
If new configuration channel priorities conflict with existing channels, the duplicate channel is removed and replaced according to the new priority.
If the client's configuration priorities are going to be reordered by an action, the {webui} requires you to confirm the change before proceeding.
====


== Compare configuration files

You can also use the system set manager (SSM) to compare the configuration file deployed on clients with the configuration file stored on the {productname} Server.

.Procedure: Comparing configuration files
[role=procedure]
____
. In the {productname} {webui}, navigate to menu:Systems[Systems List] and select the clients subscribed to the configuration files you want to compare.

. Navigate to menu:Systems[System Set Manager], and go to the menu:Configuration[Compare Files] subtab to the list of available configuration files.

. OPTIONAL: Click the number in the [guimenu]``Systems`` column to see which clients are currently subscribed to the configuration file.

. Check the configuration files to compare, and click btn:[Schedule File Comparison].
____


== Jinja templating on clients

Jinja templating is possible on {salt} clients.
Jinja provides variables from pillars or grains.
They can be used in configuration files or {salt} states.

For more information, see https://docs.saltproject.io/salt/user-guide/en/latest/topics/jinja.html with this example:

----
{% if grains.os_family == 'RedHat' %}
  {% set dns_cfg = '/etc/named.conf' %}
{% elif grains.os_family == 'Debian' %}
  {% set dns_cfg = '/etc/bind/named.conf' %}
{% else %}
  {% set dns_cfg = '/etc/named.conf' %}
{% endif %}
dns_conf:
  file.managed:
    - name: {{ dns_cfg }}
    - source: salt://dns/files/named.conf
----
