[[configuration-management]]
= Configuration Management

You can use configuration files and channels to manage configuration for your clients, rather than configuring each client manually.

Configuration parameters are scripted and stored in configuration files.
You can write configuration files directly using the {productname} {webui}, or you can upload or link to files that exist in other locations.

Configuration files can be centrally managed.
Centrally managed configuration files are provided by global configuration channels and can be applied to any client subscribed to the {productname} Server.

////
// 2023-10, julio:
Locally managed configuration files are used to override centrally managed configuration settings.
They are especially useful for {productname} users who do not have configuration administration privileges, but need to make changes to the clients that they manage.
////

Configuration channels are used to organize configuration files.
You can subscribe clients to configuration channels, and deploy configuration files as required.

Configuration files are version-controlled, so you can add configuration settings, test them on your clients, and roll back to a previous revision as required.
When you have created your configuration channels, you can also perform comparisons between various configuration files, and between revisions of the same configuration file.

Configuration files can be centrally managed.
Centrally managed configuration files are provided by global configuration channels.

The available configuration management features are different for Salt and traditional clients.
This table shows the supported features on different client types:


.Configuration Management Supported Features
[cols="1,1,1", options="header"]
|===

| Feature
| Salt
| Traditional

| Global Configuration Channels
| {check}
| {check}

| Deploying Files
| {check}
| {check}

| Comparing Files
| {question}
| {check}

| Locally Managed Files
| {check} (with {salt} features)
| {check}

| Sandbox Files
| {cross}
| {check}

| Applying the Highstate
| {check}
| {cross}

| File Import from a Client
| {cross}
| {check}

| Jinja Templating
| {check}
| {cross}

| Configuration Macros
| {check} with {salt} features (grains, pillar data, etc.)
| {check}

|===



== Create Configuration Channels

=== Central Configuration Channel

To create a new central configuration channel:

.Procedure: Creating Central Configuration Channel
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click btn:[Create Config Channel].
. Type a name for the channel.
. Type a label for the channel.
    This field must contain only letters, numbers, hyphens (``-``) and underscores (``_``).
. Type a description for the channel that allows you to distinguish it from other channels.
. Click btn:[Create Config Channel] to create the new channel.



=== Salt State Channel

You can also use a configuration channel to manage Salt states on Salt clients:



.Procedure: Creating a Salt State Channel
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click btn:[Create State Channel].
. Type a name for the channel.
. Type a label for the channel.
    This field must contain only letters, numbers, hyphens (``-``) and underscores (``_``).
. Type a description for the channel that allows you to distinguish it from other channels.
. Type the [guimenu]``SLS Contents`` for the [path]``init.sls`` file.
. Click btn:[Create Config Channel] to create the new channel.



== Add Configuration Files, Directories, or Symbolic Links

When you have created a configuration channel you can add a configuration file, directory, or symbolic link:



.Procedure: Adding a Configuration File, Directory, or Symbolic Link
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click the name of the configuration channel that you want to add a configuration file to, and navigate to the menu:Add Files[Create File] subtab.
. In the [guimenu]``File Type`` field, choose whether you want to create a text file, directory, or symbolic link.
. In the [path]``Filename/Path`` field, type the absolute path to the location where the file should be deployed.
. If you are creating a symbolic link, type the target file and path in the [guimenu]``Symbolic Link Target Filename/Path`` field.
. Type the [guimenu]``User name`` and [guimenu]``Group name`` for the file in the [guimenu]``Ownership`` field, and the [guimenu]``File Permissions Mode``.
. If the client has SELinux enabled, you can configure [guimenu]``SELinux contexts`` to enable the required file attributes (for example: user, role, and file type).
. If the configuration file includes a macro, enter the symbol that marks the beginning and end of the macro.
. Enter the configuration file contents in the [guimenu]``File Contents`` text box, using the script drop-down box to choose the appropriate scripting language.
. Click btn:[Create Configuration File].



== Subscribe Clients to Configuration Channels

You can subscribe individual clients to configuration channels by navigating to menu:Systems[System List], selecting the client you want to subscribe, and navigating to the [guimenu]``Configuration`` tab.
To subscribe multiple clients to a configuration channel, you can use the system set manager (SSM).



.Procedure: Subscribing Multiple Clients to Configuration Channels
. In the {productname} {webui}, navigate to menu:Systems[Systems List] and select the clients you want to work with.
. Navigate to menu:Systems[System Set Manager], and go to the menu:Configuration[Subscribe to Channels] subtab to see the list of available configuration channels.
. OPTIONAL: Click the number in the [guimenu]``Systems currently subscribed`` column to see which clients are currently subscribed to the configuration channel.
. Check the configuration channels you want to subscribe to, and click btn:[Continue].
. Rank the configuration channels using the up and down arrows.
    Where settings conflicts occur between configuration channels, channels closer to the top of the list take precedence.
. Determine how the channels are applied to the selected clients.
    Click btn:[Subscribe With Lowest Priority] to add the new channels at a lower priority than currently subscribed channels.
    Click btn:[Subscribe with Highest Priority] to add the new channels at a higher priority than currently subscribed channels.
    Click btn:[Replace Existing Subscriptions] to remove existing channels and replace them with the new channels.
. Click btn:[Apply Subscriptions].


[NOTE]
====
If new configuration channel priorities conflict with existing channels, the duplicate channel is removed and replaced according to the new priority.
If the client's configuration priorities are going to be reordered by an action, the {webui} requires you to confirm the change before proceeding.
====



== Compare Configuration Files

You can also use the system set manager (SSM) to compare the configuration file deployed on clients with the configuration file stored on the {productname} Server.



.Procedure: Comparing Configuration Files
. In the {productname} {webui}, navigate to menu:Systems[Systems List] and select the clients subscribed to the configuration files you want to compare.
. Navigate to menu:Systems[System Set Manager], and go to the menu:Configuration[Compare Files] subtab to the list of available configuration files.
. OPTIONAL: Click the number in the [guimenu]``Systems`` column to see which clients are currently subscribed to the configuration file.
. Check the configuration files to compare, and click btn:[Schedule File Comparison].



== Jinja templating on {salt} clients

Jinja templating is possible on {salt} clients.
Jinja provides variables from pillars or grains.
They can be used in configuration files or {salt} states.

For more information, see https://docs.saltproject.io/salt/user-guide/en/latest/topics/jinja.html with this example:

----
{% if grains.os_family == 'RedHat' %}
  {% set dns_cfg = '/etc/named.conf' %}
{% elif grains.os_family == 'Debian' %}
  {% set dns_cfg = '/etc/bind/named.conf' %}
{% else %}
  {% set dns_cfg = '/etc/named.conf' %}
{% endif %}
dns_conf:
  file.managed:
    - name: {{ dns_cfg }}
    - source: salt://dns/files/named.conf
----


////
// FIXME: how to use these vars with Salt?
In addition to variables for custom system information, the following standard macros are supported:

----
rhn.system.sid
rhn.system.profile_name
rhn.system.description
rhn.system.hostname
rhn.system.ip_address
rhn.system.custom_info(key_name)
rhn.system.net_interface.ip_address(eth_device)
rhn.system.net_interface.netmask(eth_device)
rhn.system.net_interface.broadcast(eth_device)
rhn.system.net_interface.hardware_address(eth_device)
rhn.system.net_interface.driver_module(eth_device)
----
////
