[[workflow-configuration-management]]
= Configuration Management Workflow

You can use configuration files and channels to manage configuration for your clients, rather than configuring each client manually.
This workflow shows you how to use the {productname} {webui} to create a centrally managed configuration file, assign it to a client, and apply the configuration.



== Use Case 

If you are managing a lot of clients, you probably do not want to manually apply configuration settings to each of them in turn.
Configuration channels are used to organize configuration files.
You can subscribe clients to configuration channels, and deploy configuration files as required.



== Outcome

When you have completed this workflow, you will have a configuration channel containing a configuration file, have assigned clients to the channel, and applied the configuration successfully.



== Preparation

Before you start, you should already have:

* {productname} Server installed, that you can access using the {webui}.
* At least one client registered to your server.
* Appropriate subscriptions from http://scc.suse.com for the products you are using.

This workflow uses a centrally managed configuration file and a {salt} state.
You can also use locally managed configuration files and different methods, to get more flexibility in how you manage configuration in your environment.
For more information about the different ways to manage configuration, see xref:client-configuration:configuration-management.adoc[].



== Step-by-step Workflow instructions

.Procedure: Create a New Configuration Channel and file
[role=procedure]

. In the {productname} {webui}, navigate to menu:Configuration[Channels] and click btn:[Create State Channel].
. Type a name, label, and description for your configuration file, and type the contents of your configuration file.
An example that you can copy is at the end of this section.
. Click btn:[Create Config State Channel]


. Procedure: Assign Clients to the Configuration Channel
[role=procedure]
. In the {productname} {webui}, navigate to menu:Systems[Systems List] and select the client you want to assign to your configuration channel.
. Navigate to the [guimenu]``Configuration`` tab.
  In the guimenu:``Configuration Overview`` section, click btn:[Subscribe to channels].
. Check the configuration channel you created earlier, and click btn:[Continue].
. If you have more than one configuration channel, you can rank them in order of importance, or click btn:[Update Channel Rankings] to finish.

.Procedure: Apply the Configuration to Your Client
[role=procedure]
. In the {productname} {webui}, navigate to menu:Systems[Systems List] and select the client you want to assign to your configuration channel.
. Navigate to the [guimenu]``Configuration`` tab.
  In the guimenu:``Configuration Actions`` section, click btn:[Deploy all managed config files].



== Example

=== SLS State for Keeping Clients Updated
----
include:
  - channels

int_keep_system_up2date_updatestack:
  pkg.latest:
    - pkgs:
      - salt
      - salt-minion
{%- if grains.os_family == 'Suse'%}
      - zypper
      - libzypp
{%- elif grains['os_family'] == 'RedHat' %}
{%- if grains['osmajorrelease'] >= 8 %}
      - dnf
{%- else %}
      - yum
{%- endif %}
{%- endif %}
    - require:
      - sls: channels
    - order: last

int_keep_system_up2date_pkgs:
  pkg.uptodate:
    - require:
      - sls: channels
      - pkg: int_keep_system_up2date_updatestack
    - order: last

int_reboot_if_needed:
  cmd.run:
    - name: shutdown -r +5
{%- if grains['os_family'] == 'RedHat' and grains['osmajorrelease'] >= 8 %}
    - onlyif: 'dnf -q needs-restarting -r; [ $? -eq 1 ]'
{%- elif grains['os_family'] == 'RedHat' and grains['osmajorrelease'] <= 7 %}
    - onlyif: 'needs-restarting -r; [ $? -eq 1 ]'
{%- elif grains['os_family'] == 'Debian' %}
    - onlyif: 
      - test -e /var/run/reboot-required
{%- else %}
    - onlyif: 'zypper ps -s; [ $? -eq 102 ]'
{%- endif %}
----



== Related Topics

* For more information about configuration management, see xref:client-configuration:configuration-management.adoc[].
* For more information about SLS files, see: https://docs.saltproject.io/en/latest/topics/tutorials/starting_states.html.

