[[configuration-management]]
= Configuration Management

You can use configuration files and channels to manage configuration for your clients, rather than configuring each client manually.

Configuration parameters are scripted and stored in configuration files.
You can write configuration files directly using the {productname} {webui}, or you can upload or link to files that exist in other locations.

Configuration files can be centrally managed, or locally managed.
Centrally managed configuration files are provided by global configuration channels and can be applied to any client subscribed to the {productname} Server.
Locally managed configuration files are used to override centrally managed configuration settings.
They are especially useful for {productname} users who do not have configuration administration privileges, but need to make changes to the clients that they manage.

Configuration channels are used to organise configuration files.
You can subscribe clients to configuration channels, and deploy configuration files as required.

Configuration files are version-controlled, so you can add configuration settings, test them on your clients, and roll back to a previous revision as required.

When you have created your configuration channels, you can also perform comparisons between various configuration files, and between revisions of the same configuration file.

Configuration files can be centrally managed, or locally managed.
Centrally managed configuration files are provided by global configuration channels.
Locally managed configuration files are created or uploaded to {productname} directly.


// These procedures need more editing for style. --LKB 2020-07-31
== Prepare Traditional Clients for Configuration Management

To manage traditional client configuration with {productname}, the client must have the appropriate tools and the [path]``config-enable`` file installed.
These tools will be available if you installed the system with the configuration management functionality using {ay} or Kickstart.
If not, they can be found in the Tools child channel for your distribution.
Download and install the latest [path]``mgr-cfg*`` packages:

* [path]``mgr-cfg`` -- the base libraries and functions needed by all [path]``mgr-cfg-*`` packages,
* [path]``mgr-cfg-actions`` -- the RPM package required to run configuration actions scheduled via {productname},
* [path]``mgr-cfg-client`` -- the RPM package with a command line interface to the client features of the Configuration Management system,
* [path]``mgr-cfg-management`` -- the RPM package with a command line interface used to manage {productname} configuration.


Installation of these packages can also be accomplished during bootstrapping if you enable [guimenu]``Configuration File Deployment`` on the [guimenu]``Details`` page of the activation key after creating that activation key.
For more information about activation keys, see
xref:reference:systems/activation-keys.adoc#s3-sm-system-keys-manage[].



== Create Configuration Channels

To create a new central configuration channel:

.Procedure: Creating Central Configuration Channel
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click btn:[Create Config Channel].
. Enter a name for the channel.
. Enter a label for the channel. This field must contain only letters, numbers, hyphens (``-``) and underscores (``_``).
. Enter a mandatory description for the channel that allows you to distinguish it from other channels.
. Click the btn:[Create Config Channel] button to create the new channel.
. The following page is a subset of the [guimenu]``Channel Details`` page and has three tabs: [guimenu]``Overview`` , [guimenu]``Add Files`` , and [guimenu]``Systems``.


You can also use a configuration channel to manage Salt states on Salt clients.



.Procedure: Creating a Salt State Channel
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click btn:[Create State Channel].
. Enter a name for the channel.
. Enter a label for the channel. This field must contain only letters, numbers, hyphens (``-``) and underscores (``_``).
. Enter a mandatory description for the channel that allows you to distinguish it from other channels.
. Enter the [guimenu]``SLS Contents`` for the [path]``init.sls`` file.
. Click the btn:[Create Config Channel] button to create the new channel.
. The following page is a subset of the [guimenu]``Channel Details`` page and has four tabs: [guimenu]``Overview``, [guimenu]``List/Remove Files``, [guimenu]``Add Files``, and [guimenu]``Systems``. The [guimenu]``Channel Details`` page is discussed in <<config-config-channels-channel-details>>.



== Add Configuration Files, Directories, or Symbolic Links

After you have created a configuration channel you can add a configuration file, directory, or symbolic link:

.Procedure: Adding a Configuration File, Directory, or Symbolic Link
. In the {productname} {webui}, navigate to menu:Configuration[Channels], and click the name of the configuration channel where you want to add a configuration file.
. Navigate to menu:Add Files[Create File] subtab, and in the [guimenu]``File Type`` section choose whether you want to create a text file, directory, or symbolic link.
. In the [path]``Filename/Path`` text box, set the absolute path to where the file should be deployed.
. If you are creating a symbolic link, indicate the target file and path in the [guimenu]``Symbolic Link Target Filename/Path`` text box.
. Enter the [guimenu]``User name`` and [guimenu]``Group name`` for the file in the [guimenu]``Ownership`` section, and the [guimenu]``File Permissions Mode``.
. If the client has SELinux enabled, you can configure [guimenu]``SELinux contexts`` to enable the required file attributes (such as user, role, and file type).
. If the configuration file includes a macro, enter the symbol that marks the beginning and end of the macro.
. Enter the configuration file content in the [guimenu]``File Contents`` text box, using the script drop-down box to choose the appropriate scripting language.
. Confirm with clicking the btn:[Create Configuration File] button.
