[[contact-methods-intro]]
= Client Management Methods

There are a number of ways that the {productname} Server can communicate with clients.
Which one you use depends on the type of client, and your network architecture:

Salt::
is the default choice and recommended unless there are specific needs.
For more information, see xref:contact-methods-salt.adoc[].
Salt SSH::
is useful only if network restrictions make it impossible for clients to establish contact to the server.
This contact method has serious limitations.
For more information, see xref:contact-methods-saltssh.adoc[].
Traditional::
is available for backwards compatibility only.
This contact method has serious limitations.
It does not scale as well as Salt.
+
[WARNING]
====
Newer operating systems are not supported and will not be added in the future.
The traditional contact method is deprecated and will be removed in the next version.
Use it only when a needed feature is still not covered by Salt.
For feature comparison, see xref:client-configuration:supported-features.adoc[].
====
+
For more information, see xref:client-configuration:contact-methods-traditional.adoc[].
