[[contact-methods-intro]]
= Contact Methods

There are a number of ways that the {productname} Server can communicate with clients.
Which one you use depends on the type of client, and your network architecture:

Salt::
is the default choice and recommended unless there are specific needs.
For more information, see xref:contact-methods-salt.adoc[].
Salt SSH::
is useful only if network restrictions make it impossible for clients to establish contact to the server.
This contact method has serious limitations.
For more information, see xref:contact-methods-saltssh.adoc[].
Traditional::
is available for backwards compatibility only.
////
use only when
there is a particular feature deemed essential and still not covered
by Salt (see
https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/client-configuration/supported-features.html). Updates
are pulled by clients from Server, does not scale as well as
Salt. Installs a small daemon on clients (rhnsd). Newer OSs are not
supported and will not be added in future
////
Traditional with OSAD::
is the same as traditional but allows the server to
push updates to clients.
////
Requires rhnsd and another additional daemon
(osad) on each client. Same restrictions apply
////
Traditional SSH Push::
is same as traditional but allows the server to
push updates to clients, using the SSH protocol as a
transport layer.
////
Requires rhnsd and sshd. Optionally allows to also tunnel
HTTP/HTTPS traffic (for package download) via SSH: this is called SSH
Push with Tunnel
////



The {productname} daemon ([command]``rhnsd``) runs on traditional client systems and periodically connects with {productname} to check for new updates and notifications.
It does not apply to Salt clients.

Push via SSH and Push via Salt SSH are used in environments where clients cannot reach the {productname} Server directly.
In this environment, clients are located in a firewall-protected zone called a DMZ.
No system within the DMZ is authorized to open a connection to the internal network, including the {productname} Server.

OSAD is an alternative contact method between {productname} and traditional clients.
OSAD allows traditional clients to execute scheduled actions immediately.
It does not apply to Salt clients.
