[[contact-methods-migrate-trad]]
= Migrate traditional clients to {salt} clients

To migrate a system from a traditional client to a {salt}, the user can create a {salt} bootstrap script and re-register the client system with it.

This could be done by:

* generating a reactivation key for the client,
* creating a bootstrap script with a specific activation key, and
* running the bootstrap script to register the client, with the aforementioned reactivation key.


== Generate Reactivation Key
A reactivation key can be used to re-register the client and regain all {productname} settings. 
For more information on how to create reactivation key, see xref:client-configuration/activation-keys.adoc#_reactivation_keys[]


== Create Bootstrap Script
.Procedure: Creating Bootstrap Script
A bootstrap script can be created through the {webui} or from the command line. 
For more information about creating bootstrap script, see xref:client-configuration:registration-bootstrap.adoc[].
[NOTE]
====
Use  the activation key created before to generate the bootstrap script.
====

. Once the bootstrap script is generated, it's stored on the server in the [path]``/srv/www/htdocs/pub/bootstrap`` directory.
  Alternatively, you can access the bootstrap script over HTTPS.
  Replace [literal]``<example.com>`` with the host name of your {productname} Server:
+
----
https://<example.com>/pub/bootstrap/bootstrap.sh
----

[IMPORTANT]
====
Bootstrap script will try to install [package]``venv-salt-minion`` for {salt} clients if it is available in the bootstrap repository, or [package]``salt-minion`` if there is no {salt} bundle in the bootstrap repository.
It is possible to avoid installing {salt} bundle and keep using [package]``salt-minion`` if you need it.


For more information, see xref:client-configuration:contact-methods-saltbundle.adoc[Salt Bundle].
====



== Run Bootstrap Script

As the final step, run the bootstrap script to migrate and register clients.


.Procedure: Running the bootstrap script

. On the {productname} Server, sign in as root.
  At the command prompt, change to the bootstrap directory:
+

----
cd /srv/www/htdocs/pub/bootstrap/
----
+

. Run the following command to execute the bootstrap script on the client.
  Replace [systemitem]``EXAMPLE.COM`` with the hostname of your client, and [systemitem]``REACT_KEY``:
+

----
cat bootstrap-migrate-to-salt.sh | ssh root@EXAMPLE.COM REACTIVATION-KEY=REACT_KEY /bin/bash
----
+

. Alternatively, on the client, run the command:
+

----
curl -Sks https://server_hostname/pub/bootstrap/bootstrap-migrate-to-salt.sh | REACTIVATION-KEY=REACT_KEY /bin/bash
----
+

The script downloads the required dependencies.
+
. Make sure to accept the new {salt} key before looking for your new {salt} minion. You can open the {productname} {webui} and navigate to menu:Salt[Keys] to accept the client key

. When the script has finished running, you can check that your client is registered correctly by opening the {productname} {webui} and navigating to menu:Systems[Overview] to ensure the new client is listed as Salt instead of Management.

[WARNING]
====
When new packages or updates are installed on the client using {productname}, any end user license agreements (EULAs) are automatically accepted.
To review a package EULA, open the package detail page in the {webui}.
====


For more information about using bootstrap scripts, see
xref:client-configuration:registration-bootstrap.adoc[].
