[[contact-methods-trad]]
= Contact Methods for Traditional Clients

Traditional clients can communicate with the {productname} Server using a range of methods.

The lightweight {productname} daemon ([command]``rhnsd``) runs on traditional client systems.
The daemon periodically connects with {productname} to check for new updates and notifications.

[WARNING]
====
The [command]``rhnsd`` method has serious limitations.
It does not scale as well as Salt.
Newer operating systems are not supported and will not be added in the future.
====

OSAD is an alternative contact method between {productname} and traditional clients.
OSAD allows traditional clients to execute scheduled actions immediately.

Push via SSH is used in environments where clients cannot reach the {productname} Server directly.
In this environment, clients are located in a firewall-protected zone called a DMZ.
No system within the DMZ is authorized to open a connection to the internal network, including the {productname} Server.
