[[contact-methods-salt-cfgfile]]
= Salt Minion Configuration File

In most cases, Salt clients are registered accurately with the default bootstrap methods.
However, you can use Salt to register the client to the {productname} Server manually by editing the Salt minion file on the client, and providing the fully qualified domain name (FQDN) of the server.
This method operates using ports 4505 and 4506 inbound to the server.
This method requires no configuration on the {productname} Server aside from ensuring that these ports are open.



.Procedure: Registering Clients with Salt Minion Configuration File
. On the Salt client, open the [path]``/etc/salt/minion`` configuration file.
. Add or edit this line, using the FQDN of the {productname} Server:
+
----
master: <SERVER-FQDN>
----
. Restart the Salt service:
+
----
service salt-minion restart
----
. On the {productname} Server, at the command prompt, accept all available Salt clients:
+
----
salt-key -A
----

For more information about the [path]``/etc/salt/minion`` configuration file, see https://docs.saltstack.com/en/latest/ref/configuration/minion.html.
