[[contact-methods-trad]]
= Contact Methods for Traditional Clients

Traditional clients can communicate with the {productname} Server using a range of methods.

The {productname} daemon ([command]``rhnsd``) runs on traditional client systems and periodically connects with {productname} to check for new updates and notifications.

Push via SSH is used in environments where clients cannot reach the {productname} Server directly.
In this environment, clients are located in a firewall-protected zone called a DMZ.
No system within the DMZ is authorized to open a connection to the internal network, including the {productname} Server.

OSAD is an alternative contact method between {productname} and traditional clients.
OSAD allows traditional clients to execute scheduled actions immediately.

[WARNING]
====
With SUSE Manager 4.3 release, traditional clients have been deprecated.
The release following SUSE Manager 4.3 will not support traditional clients and traditional proxies, and it is planned for the year 2023.
We encourage all new deployments to use Salt clients and Salt proxies exclusively, and to migrate existing traditional clients and proxies to Salt.
+
Be aware that when migrating from traditional clients to Salt minions you do not have to delete the registered clients before.
You can just register them as Salt minions and Salt will do the necessary steps with the traditional client.
If you already deleted the traditional client and the registration as Salt minion is not possible anymore, see
xref:installation-and-upgrade:troubleshooting.adoc[Troubleshooting].
====
