[[contact-methods-intro]]
= Client Management Methods
:description: Learn about client management techniques for SUSE Manager Server, which include YaST tools, push via SSH, and OSAD
:revdate: 2022-01-11
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Manager
:page-product-version: 4.3

There are a number of ways that the {productname} Server can communicate with clients.
Which one you use depends on the type of client, and your network architecture.

The {productname} daemon ([command]``rhnsd``) runs on traditional client systems and periodically connects with {productname} to check for new updates and notifications.
It does not apply to Salt clients.

Push via SSH and Push via Salt SSH are used in environments where clients cannot reach the {productname} Server directly.
In this environment, clients are located in a firewall-protected zone called a DMZ.
No system within the DMZ is authorized to open a connection to the internal network, including the {productname} Server.

OSAD is an alternative contact method between {productname} and traditional clients.
OSAD allows traditional clients to execute scheduled actions immediately.
It does not apply to Salt clients.
