[[contact-methods-osad]]
= OSAD


OSAD is an alternative contact method between {productname} and traditional clients.
By default, {productname} uses [systemitem]``rhnsd``, which contacts the server every four hours to execute scheduled actions.
OSAD allows traditional clients to execute scheduled actions immediately.

[NOTE]
====
Use OSAD in addition to [systemitem]``rhnsd``.
If you disable [systemitem]``rhnsd`` your client is shown as not checking in after 24 hours.
====

OSAD has several distinct components:

* The [systemitem]``osa-dispatcher`` service runs on the server, and uses database checks  to determine if clients need to be pinged, or if actions need to be executed.
* The [systemitem]``osad`` service runs on the client. It responds to pings from [systemitem]``osa-dispatcher`` and runs [command]``mgr_check`` to execute actions when directed to do so.
* The [systemitem]``jabberd`` service is a daemon that uses the [systemitem]``XMPP`` protocol for communication between the client and the server.
    The [systemitem]``jabberd`` service also handles authentication.
* The [command]``mgr_check`` tool runs on the client to execute actions.
    It is triggered by communication from the [systemitem]``osa-dispatcher`` service.

The [systemitem]``osa-dispatcher`` periodically runs a query to check when clients last showed network activity.
If it finds a client that has not shown activity recently, it uses [systemitem]``jabberd`` to ping all [systemitem]``osad`` instances running on all clients registered with your {productname} server.
The [systemitem]``osad`` instances respond to the ping using [systemitem]``jabberd``, which is running in the background on the server.
When the [systemitem]``osa-dispatcher`` receives the response, it marks the client as online.
If the [systemitem]``osa-dispatcher`` fails to receive a response within a certain period of time, it marks the client as offline.

When you schedule actions on an OSAD-enabled system, the task is carried out immediately.
The [systemitem]``osa-dispatcher`` periodically checks clients for actions that need to be executed.
If an outstanding action is found, it uses [systemitem]``jabberd`` to execute [command]``mgr_check`` on the client, which then executes the action.


OSAD clients use the fully qualified domain name (FQDN) of the server to communicate with the [systemitem]``osa-dispatcher`` service.

SSL is required for [systemitem]``osad`` communication.
If SSL certificates are not available, the daemon on your client systems fails to connect.
Make sure your firewall rules are set to allow the required ports.
For more information, see xref:installation-and-upgrade:ports.adoc[].


.Procedure: Enabling OSAD
. At the command prompt on the {productname} Server, as root, start the [systemitem]``osa-dispatcher`` service:
+
----
systemctl start osa-dispatcher
----
. On each client, install the [systemitem]``mgr-osad`` package from the [systemitem]``Tools`` child channel.
    The [systemitem]``mgr-osad`` package should be installed on clients only.
    If you install the [systemitem]``mgr-osad`` package on your {productname} Server, it conflicts with the [systemitem]``osa-dispatcher`` package.
. On each client, as root, start the [systemitem]``osad`` service:
+
----
systemctl start osad
----
+
Because [systemitem]``osad`` and [systemitem]``osa-dispatcher`` are run as services, you can use standard commands to manage them, including [command]``stop``, [command]``restart``, and [command]``status``.


Each OSAD component is configured using local configuration files.
We recommend you keep the default configuration parameters for all OSAD components.


[cols="1,1,1", options="header"]
|===

| Component                        | Location | Path to Configuration File
| [systemitem]``osa-dispatcher``   | Server   | [path]``/etc/rhn/rhn.conf`` Section: [systemitem]``OSA configuration``
| [systemitem]``osad``             | Client   | [path]``/etc/sysconfig/rhn/osad.conf``
| [systemitem]``osad`` log file    | Client   | [path]``/var/log/osad``
| [systemitem]``jabberd`` log file | Both     | [path]``/var/log/messages``
|===


.Troubleshooting OSAD

If your OSAD clients cannot connect to the server, or if the [systemitem]``jabberd`` service takes a lot of time responding to port 5552, it could be because you have exceeded the open file count.

Every client needs one always-open TCP connection to the server, which consumes a single file handler.
If the number of file handlers currently open exceeds the maximum number of files that [systemitem]``jabberd`` is allowed to use, [systemitem]``jabberd`` queues the requests, and refuses connections.

To resolve this issue, you can increase the file limits for [systemitem]``jabberd`` by editing the [path]``/etc/security/limits.conf`` configuration file and adding these lines:

----
jabber soft nofile 5100
jabber hard nofile 6000
----

Calculate the limits required for your environment by adding 100 to the number of clients for the soft limit, and 1000 to the current number of clients for the hard limit.

In the example above, we have assumed 500 current clients, so the soft limit is 5100, and the hard limit is 6000.

You also need to update the [systemitem]``max_fds`` parameter in the [path]``/etc/jabberd/c2s.xml`` file with your chosen hard limit:

----
<max_fds>6000</max_fds>
----
