[[contact-methods-salt]]
= Contact Methods for Salt Clients

In most cases, Salt clients are registered accurately with the default bootstrap methods.

If you need to use Salt clients in a disconnected setup, you can configure Push via Salt SSH.
In this environment, clients are located in a firewall-protected zone called DMZ.
For more information about Salt SSH contact method, see xref:client-configuration:contact-methods-saltssh.adoc[].

If you need to manually configure a Salt client to connect to the {productname} Server, edit the Salt client configuration file with the correct network details.
For more information about Salt minion configuration file contact method, see xref:client-configuration:registration-cli.adoc[].

[[onboarding-details]]
== Onboarding Details

Salt has its own database to keep the keys for the minions. This needs to be kept in sync with the {productname} database.
As soon as the key is accepted in Salt, the onboarding process in {productname} starts.
The onboarding process will look for existing systems in the {productname} database by searching for the ``minion_id`` and the ``machine-id``.
If nothing is found, the new system gets created.
In case an entry with the ``minion_id`` or the ``machine-id`` is found, that system will be migrated to match the new system.
In case there is a match for both entries, and they are not the same system, the onboarding will be aborted with an error.
In this case the administrator needs to resolve the conflict by removing at least one of the systems.
