[[contact-methods-intro]]
= Client Management Methods

There are a number of ways that the {productname} Server can communicate with clients.
Which one you use depends on the type of client, and your network architecture:

Salt::
is the default choice and recommended unless there are specific needs.
For more information, see xref:contact-methods-salt.adoc[].
Salt SSH::
is useful only if network restrictions make it impossible for clients to establish contact to the server.
This contact method has serious limitations.
For more information, see xref:contact-methods-saltssh.adoc[].
Salt Bundle::
is a single binary package containing Salt Minion, Python 3, required Python modules, and libraries.
Thus the connection method is independent from software installed on the client.
For more information, see xref:contact-methods-saltbundle.adoc[].

[NOTE]
====
The so-called traditional contact method is no longer supported with {productname} 5.0 and later.
Before upgrading from {productname} 4 to 5, traditional clients and thus traditional proxies have to be migrated to {salt} or replaced with {salt} proxies.
====
