[[contact-methods-salt]]
= Contact Methods for Salt Clients

The Salt contact method is the default choice and recommended unless there are specific needs.
For more information about Salt in general, see xref:specialized-guides:salt/salt-overview.adoc[].

ifeval::[{suma-content} == true]
The Salt Contact Method is the best scaling method.
All new {productname} features are supported.

The so-called traditional contact method is no longer supported with {productname} 5.0 and later.
Traditional clients and thus traditional proxies have to be migrated to {salt} or replaced with {salt} proxies.
endif::[]

Software updates are generally pushed from the server to the client.
Connections are initiated from the client.
This means you must open ports on the server, not on clients.
The Salt clients are also known as Salt minions.
{productname} Server installs a daemon on every client.

If you need to use Salt clients in a disconnected setup you can configure Push via Salt SSH as a contact method.
With this contact method, clients can be located in a firewall-protected zone called a DMZ.
For more information about Push via Salt SSH, see xref:client-configuration:contact-methods-saltssh.adoc[].



[[onboarding-details]]
== Onboarding Details

Salt has its own database to keep the keys for the minions. This needs to be kept in sync with the {productname} database.
As soon as the key is accepted in Salt, the onboarding process in {productname} starts.
The onboarding process will look for existing systems in the {productname} database by searching for the ``minion_id`` and the ``machine-id``.
If nothing is found, the new system gets created.
In case an entry with the ``minion_id`` or the ``machine-id`` is found, that system will be migrated to match the new system.
In case there is a match for both entries, and they are not the same system, the onboarding will be aborted with an error.
In this case the administrator needs to resolve the conflict by removing at least on of the systems.
