[[contact-methods-migrate-trad]]
= Migrate Traditional Clients to {salt} Clients

To migrate a system from a traditional to a {salt} client, the user can create a {salt} bootstrap script and re-register the client system with it.

This could be done by:

* generating a reactivation key for the client,
* creating a bootstrap script with a specific activation key, and
* running the bootstrap script to register the client, with the aforementioned reactivation key.



== Generate Reactivation Key

A reactivation key can be used to re-register the client and regain all {productname} settings.
For more information on how to create reactivation key, see xref:client-configuration:activation-keys.adoc#reactivation_keys[].



== Create Bootstrap Script

A bootstrap script can be created with the {webui} or from the command line.
For more information about creating bootstrap script, see xref:client-configuration:registration-bootstrap.adoc[], and for generating a suitable activation key in advance, see xref:client-configuration:activation-keys.adoc[].

Use the activation key you generating in advance when creating the bootstrap script.

When the bootstrap script is generated, it is stored on the server in the [path]``/srv/www/htdocs/pub/bootstrap`` directory.
Alternatively, you can access the bootstrap script over HTTPS.
Replace [literal]``<example.com>`` with the host name of the {productname} Server:

----
https://<example.com>/pub/bootstrap/bootstrap.sh
----

[IMPORTANT]
====
Bootstrap script will try to install [package]``venv-salt-minion`` for {salt} clients if it is available in the bootstrap repository, or [package]``salt-minion`` if there is no {salt} bundle in the bootstrap repository.
It is possible to avoid installing {salt} bundle and keep using [package]``salt-minion`` if you need it.

For more information, see xref:client-configuration:contact-methods-saltbundle.adoc[].
====



== Run Bootstrap Script

As the final step, run the bootstrap script to migrate and register clients.


.Procedure: Running the bootstrap script

. On the {productname} Server, sign in as root.
  At the command prompt, change to the bootstrap directory:
+

----
cd /srv/www/htdocs/pub/bootstrap/
----

. Run the following command to execute the bootstrap script on the client.
  Replace [systemitem]``EXAMPLE.COM`` with the hostname of your client, and [systemitem]``REACT_KEY`` with the reactivation key:
+

----
cat bootstrap-migrate-to-salt.sh | ssh root@EXAMPLE.COM REACTIVATION-KEY=REACT_KEY /bin/bash
----

. Alternatively, on the client, run the command:
+

----
curl -Sks https://server_hostname/pub/bootstrap/bootstrap-migrate-to-salt.sh | REACTIVATION-KEY=REACT_KEY /bin/bash
----
+

The script downloads the required dependencies.

. Make sure to accept the new {salt} key before looking for your new {salt} minion. You can open the {productname} {webui} and navigate to menu:Salt[Keys] to accept the client key

. When the script has finished running, you can check that your client is registered correctly by opening the {productname} {webui} and navigating to menu:Systems[Overview].
  Ensure the new client is listed with the Salt instead of the Management system type.

[WARNING]
====
When new packages or updates are installed on the client using {productname}, any end user license agreements (EULAs) are automatically accepted.
To review a package EULA, open the package detail page in the {webui}.
====


For more information about using bootstrap scripts, see
xref:client-configuration:registration-bootstrap.adoc[].
