[[custom-info]]
= Custom System Information

include::{localesdir}[]


You can include customized system information about your clients.
System information is defined as key:value pairs, which can be assigned to clients.
For example, you can define a key:value pair for a particular processor, then assign that key to all clients that have that processor installed.
Custom system information is categorized, and can be searched using the {productname} {webui}.

Before you begin, you need to create a key that allows you to store custom information.



.Procedure: Creating a Custom System Info Key
. In the {productname} {webui}, navigate to menu:Systems[Custom System Info], and click btn:[Create Key].
. In the [guimenu]``Key Label`` field, add a name for your key.
    Do not use spaces.
    For example, ``intel-x86_64-quadcore``.
. In the [guimenu]``Description`` field, provide any additional information required.
. Repeat for each key you require.

When you have created some custom system information keys, you can apply them to clients.



.Procedure: Applying Custom Info Keys to Clients
. In the {productname} {webui}, navigate to [guimenu]``Systems``, click the client to apply custom information to, and navigate to the menu:Details[Custom Info] tab.
. Click btn:[Create Value].
. Locate the value you want to apply, and click the key label.
. In the [guimenu]``Value`` field, provide any additional information.
. Click btn:[Update Key] to apply the custom information to the client.
