[[deleting.clients.webui]]
= Deleting Clients with the {webui}

Deleting clients with the {productname} {webui} works for both traditional and Salt clients.

.Procedure: Deleting a single client with the {webui}

. In the {productname} {webui}, navigate to menu:Systems
. Select the system to delete
. Click the btn:[Delete System] situated in the upper right of the screen 
. Confirm the deletion in the next screen by clicking btn:[Delete Profile]
. In the case of Salt clients {productname} will try to contact the client to remove any specific configuration created during registration. +
    If the client can't be contacted a popup message will be shown offering the option to either cancel or to delete without cleanup. +
    If btn:[Delete Profile Without Cleanup] is clicked the system will be removed from {productname} but any specific configuration won't be removed from the client.

.Procedure: Delete multiple clients with the {webui}

. In the {productname} {webui}, navigate to menu:Systems[System List] and check each client to add, this adds the clients to the system set manager.
. Navigate to menu:Systems[System Set Manager], and go to the [guimenu]``Misc`` tab, then go to the [guimenu]``Delete`` subtab.
. Click btn:[Confirm Deletion].
. If there are any Salt clients in the System Set Manager, a popup will be shown asking what to do in case of cleanup errors. There are three options:
    * `Cleanup and delete systems even in case of errors` - will remove the systems from {productname} but the configuration will remain on the Salt clients that can't be reached
    * `Delete systems without cleanup` - will remove the systems without trying to remove the configuration
    * `Only delete systems if cleanup is successful` - remove only those Salt systems that could be reached

[NOTE]
====
Cleanup of {productname} specific configuration is done only for Salt clients. For traditional clients there is no cleanup.
====     