[[delete.clients]]
= Client Deletion

// FIXME: where do we need to add warnings (suse clients only, all clients)

If you need to remove a client from your {productname} Server, you can use the {webui} to delete it.
You can also remove a client from the command line.
These procedures work for both traditional and Salt clients.

// can also be done manually.
// FIXME: Why Manual Cleanup is necessary sometimes.



[[delete.clients.webui]]
== Delete a Client with the {webui}

.Procedure: Deleting a Client
. In the {productname} {webui}, navigate to menu:Systems[System List] and select the client to delete.
. Click btn:[Delete System].
. Check the details and click btn:[Delete Profile] to confirm.
. For Salt clients, {productname} attempts to clean up additional configuration.
  If the client cannot be contacted, you are given the option to cancel the deletion, or delete the client without cleaning up the configuration files.


You can also delete multiple clients using the system set manager.
For more information about the system set manager, see xref:client-configuration:system-set-manager.adoc[].

[IMPORTANT]
====
It is not possible to automatically clean up a traditional client after deleting it.
You have to take care of this yourself.
Furthermore cleaning up a Salt minion does not remove Salt itself.
====

[NOTE]
====
Normally you migrate a traditional client to a Salt minion without deleting the client.
Salt automatically detects that you have a traditional client and does the necessary changes itself.
But if you already deleted the traditional client and want to register it as a Salt minion again, see
xref:administration:troubleshooting/tshoot-register-trad-as-salt-after-deletion.adoc[Troubleshooting Registering a traditional client as Salt minion after deleting it].
====



== Delete a Salt Client on the Command Line (with API Call)

.Procedure: Deleting a Client from the Server

. Delete the client with the FQDN (Fully Qualified Domain Name):
+
----
spacecmd system_delete FQDN
----

. Remove the Salt key with the FQDN:
+
----
salt-key -d FQDN
----

[NOTE]
====
For specific cases, the new registration of a deleted (unregistered) client might not be possible.
To solve this issue, some Salt files should be deleted on the {productname} Server (Salt master) before trying to re-register again:

----
rm /var/cache/salt/master/thin/version
rm /var/cache/salt/master/thin/thin.tgz
----
====




[[delete.clients.commandline]]
== Delete a Client from the Command Line


=== Salt Client

// Manual Registration Cleanup

NOTE: This process is only for {productname} clients, do not run it on the {productname} Server itself.

[NOTE]
====
You must not execute the following procedure on clients  running {rhel} and clones.
====

.Procedure: Salt Client

. Stop the salt-minion service:
+
SLES 12/15:
+
----
systemctl stop salt-minion
----
+
SLES 11:
+
----
rcsalt stop
----

. Remove the repositories and configuration files:
+
----
rm /etc/zypp/repos.d/susemanager\:channels.repo
rm -r /etc/sysconfig/rhn/
rm -r /etc/salt/
----

. Remove Client Packages:
+
----
zypper rm -u salt salt-minion python*-salt sle-manager-tools-release
----


.Procedure: Salt Bundle Client - Manual Registration Cleanup

To unregister, you could run: 

# systemctl stop venv-salt-minion; zypper rm -y venv-salt-minion; rm -rf /etc/zypp/{credentials,services,repos}.d/* /etc/venv-salt-minion/*

For information about the salt bundle, see: https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-saltbundle.html




Traditional Client - Manual Cleanup
NOTE: This process is only for SUSE Manager clients, do not run it on the SUSE Manager itself.
NOTE: This process should NOT be followed for clients running Red Hat OS.

Stop the osad service (If it is in use):
 
SLES 12: 
    systemctl stop osad

SLES 11:
    rcosad stop

In order to unregister a SUSE Manager client, several rpms must be removed. The following method should be tried first (in case there is no osad package, it should be omitted):

zypper rm -u spacewalksd spacewalk-check zypp-plugin-spacewalk spacewalk-client-tools osad python2-zypp-plugin-spacewalk python2-spacewalk-check python2-spacewalk-client-setup
 
  This will show the following:  

Refreshing service 'spacewalk'. 
Loading repository data...
Reading installed packages...
Resolving package dependencies...
 
The following packages are going to be REMOVED:
  spacewalk-check spacewalk-client-setup spacewalksd zypp
plugin-python osad
 
5 packages to remove.
After the operation, 301.0 KiB will be freed.
Continue? [y/n/?] (y):
 
The above rpm packages are client specific, and should be removed.
If this fails, they should be manually removed. The commands "rpm -e" should not be used unless the "zypper rm" command above failed.  

rpm -e spacewalk-client-setup spacewalksd spacewalk-check zypp-plugin-spacewalk osad python2-zypp-plugin-spacewalk python2-spacewalk-check python2-spacewalk-client-setup
 

On SLES 15 client remove below packages if installed:
rpm -e spacewalk-client-setup mgr-daemon spacewalk-check zypp-plugin-spacewalk mgr-osad python3-zypp-plugin-spacewalk python3-spacewalk-check python3-spacewalk-client-setup

After this is complete, the following file should be removed: /etc/sysconfig/rhn/systemid.
That file only exists on a client machine and is used to register itself with SUSE Manager.

rm /etc/sysconfig/rhn/systemid
 
Any configured spacewalk channels should be deleted with:
 

rm /etc/zypp/repos.d/spacewalk*
 
When this is done, the repositories should be refreshed on the server (zypper ref -s), and then listed (zypper lr), in order to make sure everything looks good.

If any repositories pointing to spacewalk still exist, remove them using the following:

zypper repos -d
zypper removerepo <ID of the repo in the output from previous command>
