[[package-management]]
= Package Management

Clients use packages to install, uninstall, and upgrade software.

To manage packages on a client, navigate to [guimenu]``Systems``, click the client to manage, and navigate to the menu:Systems[Software > Packages] subtab.
The options available in this section vary depending on the type of client you have selected, and its current channel subscriptions.



[IMPORTANT]
====
When packages are installed or upgraded, licenses or EULAs are automatically accepted.
====

Most package management actions can be added to action chains.
For more about action chains, see xref:reference:schedule/action-chains.adoc[].



== Compare Packages Using Profiles

You can compare the packages installed on a client with a stored profile, or with packages installed on another client.
When the comparison is made, you can choose to modify the selected client to match.

To compare packages against a profile, you need to have stored a profile.
Profiles are created from the packages on a currently installed client.
When the profile has been created, you can use it to install more clients with the same packages installed.



.Procedure: Creating a Stored Profile
. In the {productname} {webui}, navigate to [guimenu]``Systems``, click the client to base your profile off, and navigate to the menu:Systems[Software > Packages > Profiles] subtab.
. Click btn:[Create System Profile].
. Type a name and description for your profile and click btn:[Create Profile].



.Procedure: Comparing Client Packages
. In the {productname} {webui}, navigate to [guimenu]``Systems``, click the client to compare, and navigate to the menu:Systems[Software > Packages > Profiles] subtab.
    To compare with a stored profile, select the profile and click btn:[Compare].
. To compare with another client, select the client name and click btn:[Compare] to see a list of differences between the two clients.
