[[patch-management]]
= Patch Management

You can use custom patches within your organization to manage clients.
This allows you to issue patch alerts for packages in custom channels, schedule patch installation, and manage patches across organizations.

To use a custom patch, you need to create the patch, add packages to it and publish it.
When it is published, you can apply it to clients either singly, or with other patches.



.Procedure: Creating a Custom Patch
. Click menu:Main Menu[Patches > Manage Patches > Published]. Then on the [guimenu]``Patches Management`` page, click [guimenu]``Create Patch``.
. Enter a label for the patch in the [guimenu]``Advisory`` field, ideally following a naming convention adopted by your organization.
. Complete all remaining required fields, then click the btn:[Create Patch] button. View standard SUSE Alerts for examples of properly completed fields.



You can also create patches by cloning an existing one.
Cloning preserves package associations and simplifies issuing patches.



.Procedure: Cloning Patches
See all patches that are available for cloning by selecting the channel name in the [guimenu]``View patches potentially applicable to:`` field, and click btn:[View].
From the list, check the patch to clone, and click btn:[Clone Patch].
You need to confirm the details to perform the clone.

When cloning is complete, the cloned patch is listed in menu:Patches[Manage Patches > Unpublished].
You need to publish the patch to make it available to your organization.



.Prcoedure: Editing and Deleting Existing Patch Alerts
If you need to change an existing patch alert's details, you can do so from the  [guimenu]``Patches Management`` page.
make the changes in the appropriate fields of the [guimenu]``Details`` tab, and click the btn:[Update Patch] button.
To delete patches, select their check boxes on the [guimenu]``Patches Management`` page, click the btn:[Delete Patches] button, and confirm the action.
Deleting published patches might take a few minutes.



When you have created a patch, you can assign packages to it.

.Procedure: Assigning Packages to a Patch
. Select a patch, click the [guimenu]``Packages`` tab, then the [guimenu]``Add`` subtab.
. To associate packages with the patch being edited, select the channel from the [guimenu]``View`` drop-down box that contains the packages and click btn:[View]. Packages already associated with the patch being edited are not displayed. Selecting [guimenu]``All managed packages`` presents all available packages.
. After clicking btn:[View], the package list for the selected option appears. Note that the page header still lists the patch being edited.
. In the list, select the check boxes of the packages to be assigned to the edited patch and click btn:[Add Packages].
. A confirmation page appears with the packages listed. Click btn:[Confirm] to associate the packages with the patch. The [guimenu]``List/Remove`` subtab of the [guimenu]``Managed Patch Details`` page appears with the new packages listed.

When packages are assigned to a patch, the patch cache is updated to reflect the changes.
This update is delayed briefly so that users may finish editing a patch before all the changes are made available.
To initiate the changes to the cache manually, follow the directions to btn:[Commit the Changes Immediately] at the top of the page.


After adding packages to the patch, the patch needs to be published to be disseminated to affected systems.
Patch management distinguishes between published and unpublished patches.
Patches that have been created are considered unpublished until they are made available to clients within the organization.


.Procedure: Publishing Patches
. On the top navigation bar, click menu:Main Menu[Patches > Manage Patches > Unpublished] to see all the unpublished patches listed.
. Click the patch [guimenu]``Advisory`` name to open the patch details pages.
. On the patch details page, click btn:[Publish Patch]. A confirmation page appears that will ask you to select which channels you want to make the patch available in. Choose the relevant channels.
. At the bottom of the page, click btn:[Publish Patch]. The patch published will now appear on the [guimenu]``Published`` page of [guimenu]``Manage Patches``.


Patches include a list of updated packages.
To apply patches to a system, the system must be entitled.
The following rules apply to patches:

* Each package is a member of one or more channels. If a selected system is not subscribed to a channel containing the package, the update will not be installed on that system.
* If a newer version of the package is already installed on the system, the update will not be installed.
* If an older version of the package is installed, the package will be upgraded.

.Procedure: Applying All Applicable Patches
Apply all applicable patches to a system by clicking menu:Main Menu[Systems > Systems].
Click the name of an entitled system.
Then open the menu:System Details[Software > Patches] subtab.
When the relevant patch list appears, click btn:[Select All] then btn:[Apply Patches].
Only patches not scheduled, scheduled but failed, or canceled patches are listed.
Pending updates are excluded.


In addition, users with appropriate roles can apply patches using two other methods:

.Procedure: Applying a Single Patch to Multiple Clients
* To apply a specific patch to one or more systems, locate it in the patch list and click the number of systems affected, which takes you to the [guimenu]``Affected Systems`` page of the [guimenu]``Patch Details`` page. Select the individual systems to be updated and click the btn:[Apply Patches] button. Double-check the systems to be updated on the confirmation page, then click the btn:[Confirm] button.


.Procedure: Applying Multiple Patches to Multiple Clients
* To apply more than one patch to one or more systems, select the systems from the menu:Main Menu[Systems > Systems] list. Click the menu:Main Menu[Systems > System Set Manager > Overview], then click the [guimenu]``Systems`` tab. After ensuring the appropriate systems are selected, click the [guimenu]``Patches`` tab, select the patches to apply, and click the btn:[Apply Patches] button. Schedule a date and time for the patch to be applied. Default is the current date. Click the btn:[Confirm] button. You can follow the progress of the patch application via the [guimenu]``Pending Actions`` list. Refer to xref:reference:schedule/schedule-menu.adoc[Schedule] for more details.


[IMPORTANT]
====
If you use scheduled package installation, the packages or patches are installed via the configured contact method.
For more information, see xref:client-configuration:contact-methods-intro.adoc[].
====
