[[patch-management]]
= Patch Management

You can use custom patches within your organization to manage clients.
This allows you to issue patch alerts for packages in custom channels, schedule patch installation, and manage patches across organizations.



== Create Patches

To use a custom patch, you need to create the patch, add packages to it and add it to one or more channels.



.Procedure: Creating a Custom Patch
. In the {productname} {webui}, navigate to menu:Patches[Manage Patches], click btn:[Create Patch].
. In the ``Create Patch`` section, use these details:
+
* In the ``Synopsis`` field, type a short description of the patch.
* In the ``Advisory`` field, type a label for the patch.
    We recommend you devise a naming convention for your organization to make patch management easier.
* In the ``Advisory Release`` field, enter a release number for your patch.
    For example, if this is the first version of this patch, use ``1``.
* In the ``Advisory Type`` field, select the type of patch to use.
    For example, ``Bug Fix Advisory`` for a patch that fixes errors.
* If you selected an advisory type of ``Security Advisory``, in the ``Advisory Severity`` field, select the severity level to use.
* In the ``Product`` field, type the name of the product this patch refers to.
* OPTIONAL: In the ``Author`` field, type the name of the author of the patch.
* Complete the ``Topic``, ``Description``, and ``Solution`` fields with further information about the patch.
. OPTIONAL: In the ``Bugs`` section, specify the information of any related bugs, using these details:
+
* In the ``ID`` field, enter the bug number.
* In the ``Summary`` field, type a short description of the bug.
* In the ``Bugzilla URL`` field, type the address of the bug.
* In the ``Keywords`` field, type any keywords related to the bug.
    Use a comma between each keyword.
* Complete the ``References`` and ``Notes`` fields with further information about the bug.
* Select one or more channels to add the new patch to.
. Click btn:[Create Patch].


You can also create patches by cloning an existing one.
Cloning preserves package associations and simplifies issuing patches.



.Procedure: Cloning Patches
. In the {productname} {webui}, navigate to menu:Patches[Clone Patches].
. In the ``View patches potentially applicable to:`` field, select the software channel for the patch you want to clone.
. Select the patch or patches you want to clone, and click btn:[Clone Patches].
. Select one or more channels to add the cloned patch to.
. Confirm the details to begin the clone.



When you have created a patch, you can assign packages to it.

.Procedure: Assigning Packages to a Patch
. In the {productname} {webui}, navigate to menu:Patches[Manage Patches], and click the the advisory name of the patch to see the patch details.
. Navigate to the menu:Packages[Add] tab.
. In the ``Channel`` field, select the software channel that contains the packages you want to assign to the patch, and click btn:[View Packages].
    You can select ``All managed packages`` to see the available packages in all channels.
. Check the packages you want to include, and click btn:[Add Packages].
. Confirm the details of the packages, and click btn:[Confirm] to assign them to the patch.
. Navigate to the menu:Packages[List/Remove] tab to check that the packages have been assigned correctly.


When packages are assigned to a patch, the patch cache is updated to reflect the changes.
The cache update might take a couple of minutes.

If you need to change the details of an existing patch, you can do so from the  [guimenu]``Patches Management`` page.



.Procedure: Editing and Deleting Existing Patch Alerts
. In the {productname} {webui}, navigate to menu:Patches[Manage Patches].
. Click the advisory name of the patch to see the patch details.
. Make the changes as required, and click btn:[Update Patch].
. To delete a patch, select the patch in the [guimenu]``Patches Management`` page, and click btn:[Delete Patches].
    Deleting patches might take a few minutes.



== Apply Patches to Clients

When a patch is ready, you can apply it to clients either singly, or with other patches.

Each package within a patch is part of one or more channels.
If the client is not subscribed to the channel, the update is not installed.

If the client has a more recent version of a package already installed, the update is not installed.
If the client has an older version of the package installed, the package is upgraded.



.Procedure: Applying All Applicable Patches
. In the {productname} {webui}, navigate to menu:Systems[Overview] and select the client you want to update.
. Navigate to the menu:Software[Patches] tab.
. Click btn:[Select All] to select all applicable patches.
. Click btn:[Apply Patches] to update the client.



If you are signed in with Administrator privileges, you can also perform larger batch upgrades for clients.



.Procedure: Applying a Single Patch to Multiple Clients
. In the {productname} {webui}, navigate to menu:Patches[Patch List].
. Locate the patch you want to apply, and click the number under the ``Systems`` column for that patch.
. Select the clients you want to apply the patch to, and click btn:[Apply Patches].
. Confirm the list of clients to perform the update.



.Procedure: Applying Multiple Patches to Multiple Clients
. In the {productname} {webui}, navigate to menu:Systems[Overview] and check the clients you want to update to add them to the system set manager.
. Navigate to menu:Systems[System Set Manager] and naviagte to the [guimenu]``Patches`` tab.
. Select the patches you want to apply to the clients and click btn:[Apply Patches].
. Schedule a date and time for the update to occur, and click btn:[Confirm].
. To check the progress of the update, navigate to menu:Schedule[Pending Actions].



[IMPORTANT]
====
Scheduled package updates are installed using the contact method configured for each client.
For more information, see xref:client-configuration:contact-methods-intro.adoc[].
====
