[[power-management]]
= Power Management

You can power on, power off, and reboot clients using the {productname} {webui}.

This feature uses either the IPMI or Redfish protocol and is managed using a {cobbler} profile.
The selected client must have a power management controller supporting one of these protocols.

For Redfish, ensure you can establish a valid SSL connection between the client and the {productname} Server.
You must have trusted the certificate authority used to sign the SSL Server Certificate of the Redfish management controller.
The CA certificate must be in ``.pem`` format, and stored on the {productname} Server at [path]``/etc/pki/trust/anchors/``.
When you have saved the certificate, run [command]``update-ca-certificate``.


.Procedure: Enabling Power Management
. In the {productname} {webui}, navigate to menu:Systems[Systems List], select the client you want to manage, and navigate to the menu:Provisioning[Power Management] tab.
. In the [guimenu]``Type`` field, select the power management protocol to use.
. Complete the details for the power management server, and click the appropriate button for the action to take, or click btn:[Save only] to save the details without taking any action.

You can apply power management actions to multiple clients at the same time by adding them to the system set manager.
For more information about using the system set manager, see xref:client-configuration:system-set-manager.adoc[].



== Power Management and {cobbler}

The first time you use a power management feature, a {cobbler} system record is automatically created, if one does not yet exist for the client.
These automatically created system records are not bootable from the network, and include a reference to a dummy system image.
This is needed because {cobbler} does not currently support system records without profiles or images.

{cobbler} power management uses fence-agent tools to support protocols other than IPMI.
Only IPMI and Redfish protocols are supported by {productname}.
You can configure your client to use other protocols by adding the fence-agent names as a comma-separated list to the [option]``java.power_management.types`` configuration parameter in the [path]``rhn.conf`` configuration files.
