[[suse-registration-overview]]
= SUSE Client Registration

ifeval::[{suma-content} == true]
// SUSE Liberty Linux not available at Uyuni for now
You can register {sle} and {sleses} clients to your {productname} Server.
endif::[]

ifeval::[{uyuni-content} == true]
// SUSE Liberty Linux not available at Uyuni for now
You can register {sle} clients to your {productname} Server.
endif::[]

The method and details varies depending on the operating system of the client.

Before you start, ensure that the client has the date and time synchronized correctly with the {productname} Server.

You must also have created an activation key.
For more information about creating activation keys, see xref:client-configuration:activation-keys.adoc[].


If the client was registered to SCC, SMT, or RMT previously, remove such a registration with [command]``SUSEConnect`` before migrating the client to {productname} Server.
If you forget about removing the old registration first, it can happen that repositories not needed anymore getting automatically added to the client even after the client has been migrated to a newer version of a {suse} operating system using {productname}.

[IMPORTANT]
====
Do not register a {productname} Server to itself.
The {productname} Server must be managed individually or by using another separate {productname} Server.
For more information about using multiple servers, see xref:specialized-guides:large-deployments/hub-multi-server.adoc[].
====
