[[registering-clients-cli]]
= Register Clients on the Command Line


//== Manual Client Registration
== Introduction

{salt} clients are registered accurately with the default bootstrap methods in most cases.

However, you can use {salt} to register the client to the {productname} Server manually by editing the {salt} minion file on the client, and providing the fully qualified domain name (FQDN) of the server.

This method:
 
* uses ports 4505 and 4506 inbound to the server.
* requires no configuration on the {productname} Server aside from ensuring that these ports are open.
* requires that you have installed the [package]``venv-salt-minion`` (Salt bundle) or the [package]``salt-minion`` package on the Salt client before registration.
  Both use configuration files in different locations and filenames remain the same.
  The [literal]``systemd`` service filename is different.

[WARNING]
====
Bootstrapping this way will only work if you use the [package]``salt-minion`` being part of the client tools channels or of an official {suse} distributions.
====

== {salt} Bundle Configuration

{salt} Bundle ([package]``venv-salt-minion``)::

+

* [path]``/etc/venv-salt-minion/``
* [path]``/etc/venv-salt-minion/minion``
* [path]``/etc/venv-salt-minion/minion.d/NAME.conf``
* systemd service file: [path]``venv-salt-minion.service``

+

For more information about the Salt bundle, see xref:client-configuration:contact-methods-saltbundle.adoc[Salt Bundle].

.Procedure: Registering Clients with Salt Bundle Configuration File
. On the Salt client, open the [literal]``minion`` configuration file.
  The configuration file is either located at:

+

.Configuration File
[source, Shell]
----
/etc/venv-salt-minion/minion
----

+

or:

+

.Configuration File
[source, Shell]
----
/etc/venv-salt-minion/minion.d/NAME.conf
----
. In the file add or edit the FQDN of the {productname} Server or Proxy, and the activation key if any. Also add the other configuration parameters listed below.

+

.Configuration Parameters
[source, YAML]
----
master: SERVER.EXAMPLE.COM

grains:
  susemanager:
    activation_key: "<Activation_Key_Name>" <1>

server_id_use_crc: adler32
enable_legacy_startup_events: False <2> 
enable_fqdns_grains: False <3>
----
<1> Activation key Name
<2> Legacy events should be set to False
<3> fqdns Grains should be set to False

. Restart the [systemitem]``venv-salt-minion`` service:

+

[source, Shell]
----
systemctl restart venv-salt-minion
----

. On the {productname} Server, accept the new client key; replace [systemitem]``<client>`` with the name of your client:

+

----
salt-key -a '<client>'
----


== Client Configuration

Client ([package]``salt-minion``)::
+
* [path]``/etc/salt/``
* [path]``/etc/salt/minion``
* [path]``/etc/salt/minion.d/NAME.conf``
* systemd service file: [path]``salt-minion.service``

.Procedure: Registering Clients with Salt Minion Configuration File
. On the Salt client, open the [literal]``minion`` configuration file.
  The configuration file is either located at:

+

[source, Shell]
----
/etc/salt/minion
----

+

or:

+

[source,Shell]
----
/etc/salt/minion.d/NAME.conf
----

. In the file add or edit the FQDN of the {productname} Server or Proxy, and the activation key if any.
  Also add the other configuration parameters listed below.

+

[source, YAML]
----
master: SERVER.EXAMPLE.COM

grains:
  susemanager:
    activation_key: "<Activation_Key_Name>"

server_id_use_crc: adler32
enable_legacy_startup_events: False
enable_fqdns_grains: False
----

. Restart the [systemitem]``salt-minion`` service:

+

[source, Shell]
----
systemctl restart salt-minion
----

. On the {productname} Server, accept the new client key; replace [systemitem]``<client>`` with the name of your client:

+

[source,Shell]
----
salt-key -a '<client>'
----

For more information about the {salt} minion configuration file, see https://docs.saltproject.io/en/latest/ref/configuration/minion.html[Configuring the Salt Minion].

