[[registration-overview]]
= Client Registration

There are several ways to register clients to your {productname} Server.
This section covers the various available methods.
It also contains information specific to the operating system you intend to run on the client.

Before you begin, check that:

* The client has the date and time synchronized correctly with the {productname} Server before registration.
* You have created an activation key.
  For more information about creating activation keys, see xref:client-configuration:activation-keys.adoc[].


[IMPORTANT]
====
Do not register the {productname} Server base OS to {productname} itself.
The {productname} Server base OS must be managed individually or by using another separate {productname} Server.

To manage {productname} Server Containers, use the [literal]``mgradm`` tool.

====

ifeval::[{suma-content} == true]

[IMPORTANT]
====
After migrating from an older version of {productname} to a newer version, we strongly recommend re-generating the bootstrap scripts before onboarding new systems to prevent any potential issues.
====

endif::[]
