[[registration-methods-saltbundle]]
= Client Registration with Salt Bundle

The registration method with the Salt bundle is the recommended registration method as long as it covers your use case.
This section explains the advantages and limitations of the current implementation.
The Salt bundle is provided as the [package]``venv-salt-minion`` that consists of Salt, Python, and the Python modules Salt depends on.
Using the Salt bundle, in most cases it is no longer needed that the client provides the required Python version or any Python modules.
Bootstrapping with {webui} still requires Python to be installed on the client.

If you bootstrap new clients, registration with the Salt bundle is the default method.
You can switch existing clients to the Salt bundle method.
If you switch, the [package]``salt-minion`` package and its Python version and the Python modules will stay installed.

The Salt state [literal]``util.mgr_switch_to_venv_minion`` is available to switch from [package]``salt-minion`` to [package]``venv-salt-minion``.  It is recommended to switch to [package]``venv-salt-minion`` in two steps:

.Procedure: Switching with [literal]``util.mgr_switch_to_venv_minion`` state to [package]``venv-salt-minion``

. Apply [literal]``util.mgr_switch_to_venv_minion`` with no pillar specified first.
  This will result in the switch to [package]``venv-salt-minion`` with copying configuration files etc.
  It will not cleaning up the original [package]``salt-minion`` configurations and its packages.
. Apply [literal]``util.mgr_switch_to_venv_minion`` with [literal]``mgr_purge_non_venv_salt`` set to [literal]``True`` to remove [package]``salt-minion`` and with [literal]``mgr_purge_non_venv_salt_files`` set to [literal]``True`` to remove all the files related to [package]``salt-minion``.


On the other hand, it is also possible to avoid installing the Salt bundle and keep using [package]``salt-minion`` instead.
In this case specify one of these options:

* Execute [command]``mgr-bootstrap`` with  [option]``--no-bundle`` option.
* Set [literal]``AVOID_VENV_SALT_MINION`` to [literal]``1`` in the generated bootstrap script.
* For bootstrap state set the [literal]``mgr_avoid_venv_salt_minion`` pillar set to [literal]``True``.

