[[registration-methods]]
= Client Registration Methods

There are several ways to register clients to your {productname} Server.

* For only a few clients, we recommend that you register clients using the {productname} {webui}.
    For more information, see xref:client-configuration:registration-webui.adoc[].
* If you want more control over the process, or have to register many clients, we recommend that you create a bootstrap script.
    For more information, see xref:client-configuration:registration-bootstrap.adoc[].
* For even more control over the process, executing a single commands on the command line can be useful.
    For more information, see xref:client-configuration:registration-cli.adoc[].

The client must have the date and time synchronized correctly with the {productname} Server before registration.

You must create an activation key first, to use bootstrap script or command line method.
For more information about creating activation keys, see xref:client-configuration:activation-keys.adoc[].


[IMPORTANT]
====
Do not register the {productname} Server to itself.
The {productname} Server must be managed individually or by using another separate {productname} Server.
For more information about using multiple servers, see xref:specialized-guides:large-deployments/multi-server.adoc[].
====
