[[registering.clients.webui]]
= Register Clients with the {webui}

Registering clients with the {productname} {webui} works for Salt clients only.


.Procedure: Registering Clients with the {webui}

. In the {productname} {webui}, navigate to menu:Systems[Bootstrapping].
. In the [guimenu]``Host`` field, type the fully-qualified domain name (FQDN) of the client to be bootstrapped.
. In the [guimenu]``SSH Port`` field, type the SSH port number to use to connect and bootstrap the client.
By default, the SSH  port is [systemitem]``22``.
. In the [guimenu]``User`` field, type the username to log in to the client.
By default, the username is [systemitem]``root``.
. In the [guimenu]``Password`` field, type password to log in to the client.
. In the [guimenu]``Activation Key`` field, select the activation key that is associated with the software channel you want to use to bootstrap the client.
For more information, see xref:client-configuration:clients-and-activation-keys.adoc[].
. OPTIONAL: In the [guimenu]``Proxy`` field, select the proxy to register the client to.
. By default, the [guimenu]``Disable SSH Strict Key Host Checking`` checkbox is selected.
This allows the bootstrap process to automatically accept SSH host keys without requiring you to manually authenticate.
. OPTIONAL: Check the [guimenu]``Manage System Completely via SSH`` checkbox.
If you check this option, the client will be configured to use SSH for its connection to the server, and no other connection method will be configured.
. Click btn:[Bootstrap] to begin registration.

When the bootstrap process has completed, your client will be listed at menu:Systems[System List].


[WARNING]
====
When new packages or updates are installed on the client using {productname}, any end user license agreements (EULAs) are automatically accepted.
To review a package EULA, open the package details page in the {webui}.
====



== SLES{nbsp}11 SSL errors

SLES{nbsp}11 clients can sometimes have SSL errors which make some operations unusable, including package management and bootstrapping.
In this case, you will see an error like this:

----
Repository 'SLES11-SP4-SUSE-Manager-Tools x86_64' is invalid.
[|] Valid metadata not found at specified URL(s)
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'SLES11-SP4-SUSE-Manager-Tools x86_64' because of the above error.
Download (curl) error for 'www.example.com':
Error code: Unrecognized error
Error message: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
----

This occurs because Apache requires TLS{nbsp}v1.2, but older versions of SLES do not support this version of the TLS protocol.
To fix this error, you need to force Apache to accept a greater range of protocol versions.
Open the [path]``/etc/apache2/ssl-global.conf`` configuration file, locate the [systemitem]``SSLProtocol`` line, and update it to read:

----
SSLProtocol all -SSLv2 -SSLv3
----

This will need to be done manually on the server, and with a Salt state on the Proxy.
Restart the [systemitem]``apache`` service on each system after making the changes.