[[opensuse-registration-overview]]
= openSUSE Client Registration
:description: Learn how to register openSUSE and Leap Micro clients with your SUSE Manager Server, understanding different registration methods for various operating systems
:revdate: 2024-02-22
:page-revdate: {revdate}

You can register {opensuse} and {leapmicro} clients to your {productname} Server.
The method and details varies depending on the operating system of the client.

Before you start, ensure that the client has the date and time synchronized correctly with the {productname} Server.

You must also have created an activation key.
For more information about creating activation keys, see xref:client-configuration:activation-keys.adoc[].


[IMPORTANT]
====
Do not register a {productname} Server to itself.
The {productname} Server must be managed individually or by using another separate {productname} Server.
For more information about using multiple servers, see xref:specialized-guides:large-deployments/hub-multi-server.adoc[].
====
