[[repos]]
= Software Repositories


Completely supply innovative customer service with revolutionary manufactured products. Intrinsicly synergize enabled potentialities through enterprise-wide e-business. Uniquely administrate economically sound communities for best-of-breed leadership skills. Seamlessly transform customized systems and cooperative best practices. Synergistically negotiate flexible products whereas backend strategic theme areas.

Monotonectally extend emerging relationships through state of the art benefits. Globally fashion interactive web services for open-source ROI. Authoritatively coordinate functional methodologies rather than best-of-breed human capital. Enthusiastically expedite future-proof methodologies without virtual niches. Completely synthesize open-source services before professional partnerships.



== Local Repositories

You can configure local repositories on Salt clients, in order to provide packages that are not supplied by {productname} repositories.

Local repositories are disabled during onboarding.
After a client has completed onboarding, you can add local repositories to these locations:

[[local-repo-locations]]
[cols="1,1", options="header"]
.Local Repository Locations
|===
| Client Operating System | Local Repository Directory
| {sles} | [path]``/etc/zypp/repos.d``
| {opensuse} | [path]``/etc/zypp/repos.d``
| {sles} {es} | [path]``/etc/yum.repos.d/``
| {rhel} | [path]``/etc/yum.repos.d/``
| {centos} | [path]``/etc/yum.repos.d/``
| {ubuntu} | [path]``/etc/apt/sources.list.d/``
| {debian} | [path]``/etc/apt/sources.list.d/``
|===

For Salt clients, local repositories remain persistent, even when applying the highstate.
