[[repos]]
= Software Repositories

Repositories are used to collect software packages.
When you have access to a software repository, you can install any of the software that the repository provides.
You must have at least one repository associated with your software channels in {productname} to assign clients to the channel and install and update packages on the client.

Most default channels in {productname} are already associated with the correct repositories.
If you are creating custom channels, you need to associate a repository that you have access to, or that you have created yourself.

For more information about custom repositories and channels, see xref:administration:custom-channels.adoc[].



== Local Repository Locations

You can configure local repositories on clients, to provide packages that are not supplied by {productname} channels.

[WARNING]
====
In most cases, client systems do not require local repositories.
Local repositories can lead to problems knowing which packages are available on the client.
This can lead to installing unexpected packages.
====

Local repositories are disabled during onboarding.

Local repositories will be disabled each time a channel state is executed.
For example, when applying the highstate or performing a package action.

If local repositories should stay enabled after onboarding, the following pillar must be set for the affected client:

Edit the ``/srv/pillar/top.sls`` file:

----
base:
  'minionid':
    - localrepos
----

Edit the ``/srv/pillar/localrepos.sls`` file:

----
mgr_disable_local_repos: False
----

After a client has completed onboarding, you can add local repositories to these locations:

[[local-repo-locations]]
[cols="1,1", options="header"]
.Local Repository Locations
|===

ifeval::[{mlm-content} == true]
| Client Operating System | Local Repository Directory
| {sles} | [path]``/etc/zypp/repos.d``
| {opensuse} | [path]``/etc/zypp/repos.d``
| {sles} {es} | [path]``/etc/yum.repos.d/``
| {rhel} and similar derivatives | [path]``/etc/yum.repos.d/``
| {ubuntu} | [path]``/etc/apt/sources.list.d/``
| {debian} | [path]``/etc/apt/sources.list.d/``
endif::[]


// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{uyuni-content} == true]
| Client Operating System | Local Repository Directory
| {sles} | [path]``/etc/zypp/repos.d``
| {opensuse} | [path]``/etc/zypp/repos.d``
| {rhel} and similar derivatives | [path]``/etc/yum.repos.d/``
| {ubuntu} | [path]``/etc/apt/sources.list.d/``
| {debian} | [path]``/etc/apt/sources.list.d/``
endif::[]

|===
