[[supported-features]]
= Supported Clients and Features

{productname} is compatible with a range of client technologies.
You can install traditional or Salt clients, running {sle} or another Linux operating system, with a range of hardware options.

This section contains summary of supported client systems. For a detailed list of features available on each client, see the following pages.

include::snippets/traditional_client_warning.adoc[]


== Supported Client Systems

Supported operating systems for traditional and Salt clients are listed in this table.

The icons in this table indicate:

* {check} clients running this operating system are supported by {suse}
* {cross} clients running this operating system are not supported by {suse}
* {question} clients are under consideration, and may or may not be supported at a later date.

[NOTE]
====
Client operating system versions and SP levels must be under general support (normal or LTSS) to be supported with {productname}.
For details on supported product versions, see https://www.suse.com/lifecycle.
====


[IMPORTANT]
====
The operating system running on a client is supported by the organization that supplies the operating system.
====

// Table with the list of the supported systems
include::../../snippets/pages/supported-client-systems-snippet.adoc[]

[NOTE]
====
{debian} and {ubuntu} lists the {x86_64} architecture as amd64.
====



== Supported Tools Packages

The ``spacewalk-utils`` and ``spacewalk-utils-extras`` packages can provide additional services and features.
ifeval::[{suma-content} == true]
The ``spacewalk-utils`` package in {productname} is fully supported by {suse}, and contains these tools:
endif::[]

[[spacewalk-utils]]
[cols="1,1,1", options="header"]
.Spacewalk Utilities
|===

| Tool Name
| Description
| Supported?

| ``spacewalk-common-channels``
| Add channels not provided by {scc}
| {check}

| ``spacewalk-hostname-rename``
| Change the hostname of the {productname} Server
| {check}

| ``spacewalk-clone-by-date``
| Clone channels by a specific date
| {check}

| ``spacewalk-sync-setup``
| Set up ISS master and slave organization mappings
| {check}

| ``spacewalk-manage-channel-lifecycle``
| Manage channel lifecycles
| {check}

|===

ifeval::[{suma-content} == true]
The ``spacewalk-utils-extras`` package in {productname} has limited support by {suse}.
endif::[]
