[[system=locking]]
= System Locking

System locks are used to prevent actions from occurring on a client.
For example, a system lock will prevent a client from being updated or restarted.
This is useful for clients running production software, or to prevent accidental changes.
You can disable the system lock when you are ready to perform actions.

System locks are implemented differently on traditional and Salt clients.



== System Locks on Traditional Clients

When a traditional client is locked, no actions can be scheduled, and a padlock icon is displayed next to the name of the client in the menu:System[System List].

To lock a traditional client using the {productname} {webui}, navigate to the [guimenu]``System Details`` page for the client you want to lock.
Under [guimenu]``Lock Status``, click btn:[Lock this system].

The client will remain locked until you click btn:[Unlock this system].

//Something about requiring admin rights here maybe? --LKB 20200514

[IMPORTANT]
====
Automated patch updates can still be applied to system locked traditional clients.
To stop automated patch updates, navigate to the [guimenu]``System Details`` page for the client, and on the [guimenu]``Properties`` tab, uncheck [guimenu]``Auto Patch Update``.
====

//. All these webui things need to be checked, ref server is down right now. --LKB 20200514



== System Locks on Salt Clients

When a Salt client is locked, or put into blackout mode, no actions can be scheduled, and a yellow banner is displayed on the [guimenu]``System Details`` page.
You will be able to schedule actions for the locked client using the {webui} or the API, bu the actions will fail.

[NOTE]
====
The locking mechanism is not available for Salt SSH clients.
====

To lock a Salt client using the {productname} {webui}, navigate to the [guimenu]``System Details`` page for the client you want to lock.
Navigate to the [guimenu]``Formulas`` tab, enable the system lock formula, and apply the highstate.

The client will remain locked until you remove the system lock formula.

//. All these webui things need to be checked, ref server is down right now. --LKB 20200514

[NOTE]
====
The system lock formula is enabled by default if {caasp} is detected on the node.
====
