[[ssm]]
= System Set Manager

== Introduction

The system set manager (SSM) is used to perform actions on more than one client at a time.
SSM creates ephemeral sets of clients, making it useful for one-off actions that you need to apply to a number of clients.
If you want more permanent sets, consider using system groups instead.
For more information about system groups, see xref:client-configuration:system-groups.adoc[].

The actions available for use in SSM are listed in table.
The icons in this table indicate:

* {check} this action is available in SSM for this client type
* {cross} this action is not available in SSM for this client type
* {question} this action is under consideration for this client type, and may or may not be supported at a later date.


.Available SSM Actions
[cols="1,1", options="header"]
|===

| List systems              | {check}
| Install patches           | {check}
| Schedule patch updates    | {check}
| Upgrade packages          | {check}
| Install packages          | {check}
| Remove packages           | {check}
| Verify packages           | {cross}
| Create groups             | {check}
| Manage groups             | {check}
| Channel memberships       | {check}
| Channel subscriptions     | {cross}
| Deploy/diff channels      | {cross}
| Autoinstall clients       | {cross}
| Tag for snapshot          | {cross}
| Remote commands           | {cross}
| Power management          | {cross}
| Update system preferences | {check}
| Update hardware profiles  | {check}
| Update package profiles   | {check}
| Set/remove custom values  | {check}
| Reboot clients            | {check}
| Migrate clients to another organization | {check}
| Delete clients            | {check}
|===


You can select clients for the SSM in several ways:

* Navigate to menu:Systems[System List] and check the clients you want to work with.
* Navigate to menu:Systems[System Groups], and click btn:[Use in SSM] for the system group you want to work with.
* Navigate to menu:Systems[System Groups], check the group you want to work with, and click btn:[Work with Group].

When you have selected the clients you want to work with, navigate to menu:Systems[System Set Manager], or click the [guimenu]``systems selected`` icon in the top menu bar.


[NOTE]
====
The details in SSM might differ slightly from the details in other parts of the {productname} {webui}.
In SSM, all available updates are shown.
This allows you to upgrade to packages that might not be the latest version.
====



== Change Base Channels in SSM

You can use SSM to change the base channel of more than one client at the same time.

[IMPORTANT]
====
Changing the base channel significantly changes the packages and patches available to the affected clients.
Use with caution.
====



.Procedure: Using SSM to Change Base Channels for Multiple Clients

. In the {productname} {webui}, navigate to menu:Systems[System List], check the clients you want to work with, and navigate to menu:Systems[System Set Manager].
. Navigate to the [guimenu]``Channels`` subtab.
. Locate the current base channel in the list, and verify that the number shown in the [guimenu]``Systems`` column is correct.
    You can click the number in this column to see more details of the clients you are changing.
. Select the new base channel in the [guimenu]``Desired base Channel`` field, and click btn:[Next].
. For each child channel, select [guimenu]``No change``, [guimenu]``Subscribe``, or [guimenu]``Unsubscribe``, and click btn:[Next].
. Check the changes you are making, and choose a time for the action to occur.
. Click btn:[Confirm] to schedule the changes.
