[[system-locking]]
= System Locking

System locks are used to prevent actions from occurring on a client.
For example, a system lock prevents a client from being updated or restarted.
This is useful for clients running production software, or to prevent accidental changes.
You can disable the system lock when you are ready to perform actions.



== System Locks on Clients

When a client is locked, or put into blackout mode, no actions can be scheduled, execution commands are disabled, and a yellow banner is displayed on the [guimenu]``System Details`` page.
In this mode, actions can be scheduled for the locked client using the {webui} or the API, but the actions fail.


[NOTE]
====
The locking mechanism is not available for {salt} SSH clients.
====



.Procedure: System Locking a Client
. In the {productname} {webui}, navigate to the [guimenu]``System Details`` page for the client you want to lock.
. Navigate to the [guimenu]``Formulas`` tab, check the system lock formula, and click btn:[Save].
. Navigate to the menu:Formulas[System Lock] tab, check [guimenu]``Lock system``, and click btn:[Save].
    On this page, you can also enable specific Salt modules while the client is locked.
. When you have made your changes, you might need to apply the highstate.
    In this case, a banner in the {webui} notifies you.
    The client remains locked until you remove the system lock formula.

For more information about blackout mode in {salt}, see https://docs.saltstack.com/en/latest/topics/blackout/index.html.



== Package Locks

Package locking can be used on several clients, but different feature sets are available.
You must differentiate between {sle} and {opensuse} (zypp-based) versus {rhel} or {debian} clients.



=== Package Locks on Zypp-based Systems

Package locks are used to prevent unauthorized installation or upgrades to software packages.
When a package has been locked, it shows a padlock icon, indicating that it cannot be installed.
Any attempt to install a locked package is reported as an error in the event log.

Locked packages cannot be installed, upgraded, or removed, neither through the {productname} {webui}, nor directly on the client machine using a package manager.
Locked packages also indirectly lock any dependent packages.


.Procedure: Using Package Locks
. Navigate to the menu:Software[Packages > Lock] tab on the managed system to see a list of all available packages.
. Select the packages to lock, and click btn:[Request Lock].
  Pick date and time for the lock to activate.
  By default, the lock is activated as soon as possible.
  Note that the lock might not activate immediately.
. To remove a package lock, select the packages to unlock and click btn:[Request Unlock].
  Pick date and time as with activating the lock.



=== Package Locks on {rhel}- and {debian}-like Systems

[NOTE]
====
Some {rhel}- and {debian}-like systems have package locking available on clients.
====

On {rhel}- and {debian}-like systems, package locks are only used to prevent unauthorized upgrades or removals to software packages.
When a package has been locked, it shows a padlock icon, indicating that it cannot be changed.
Any attempt to change a locked package is reported as an error in the event log.

Locked packages cannot be upgraded or removed, neither through the {productname} {webui}, nor directly on the client machine using a package manager.
Locked packages also indirectly lock any dependent packages.


.Procedure: Using Package Locks
. On {rhel} 7 systems, install [package]``yum-plugin-versionlock``, and on {rhel} 8 or 9 systems, install [package]``python3-dnf-plugin-versionlock`` as [systemitem]``root``.
  On {debian} systems, the ``apt`` tool has the locking feature included.
. Navigate to the menu:Software[Packages > Lock] tab on the managed system to see a list of all available packages.
. Select the packages to lock, and click btn:[Request Lock].
  Pick date and time for the lock to activate.
  By default, the lock is activated as soon as possible.
  Note that the lock might not activate immediately.
. To remove a package lock, select the packages to unlock and click btn:[Request Unlock].
  Pick date and time as with activating the lock.
