[[vhm-caasp]]
= VHM and SUSE CaaS Platform

You can use a {productname} VHM to gather instances from {caasp}.

The VHM allows {productname} to obtain and report information about your virtual machines.
For more information on VHMs, see xref:client-configuration:vhm.adoc[].



== Register CaaSP Nodes

You can register each {caasp} node to {productname} using the same method as you would a Salt client.
For more information, see xref:client-configuration:registration-overview.adoc[].

We recommend that you create an activation key to associate {caasp} channels, and to onboard the associated nodes.
For more on activation keys, see xref:client-configuration:clients-and-activation-keys.adoc[].

If you are using ``cloud-init``, we recommended that you use a bootstrap script in the ``cloud-init`` configuration.
For more on bootstrapping, see xref:client-configuration:registration-bootstrap.adoc[].


When you have added the {caasp} nodes to {productname}, you will be able to:

* View the patch level status of each node.
* Perform configuration management operations against the nodes, including using Salt states.
* Assign different set of channels to clusters using channel staging and lifecycle management filters.

Updates related to {k8s} are managed using the ``skuba-update`` tool.
For more information, see https://documentation.suse.com/suse-caasp/4/html/caasp-admin/_cluster_updates.html.

[WARNING]
====
When using Salt or {productname} (either via UI or API) on any {caasp} nodes:

* Do not apply a patch (if the patch is marked as interactive)
* Do not mark a system to automatically install patches
* Do not perform an SP migration
* Do not reboot a node
* Do not issue any power management action via Cobbler
* Do not install a package if it breaks or conflicts the `patterns-caasp-Node-x.y`
* Do not remove a package if it breaks or conflicts or is one of the packages related with the `patterns-caasp-Node-x.y`
* Do not upgrade a package if it breaks or conflicts or is one of the packages related with the `patterns-caasp-Node-x.y`

{productname} will not stop you from issuing these operations.
Issuing those operation may render your {caasp} cluster unusable.
====
