[[vhm-azure]]
= Virtual Host Manager and Azure

// 2024-04-04 OM: It had been decided in the conversation with the mlm PO 
// that this Public Cloud related file can stay in the Uyuni books


You can use a virtual host manager (VHM) to gather instances from Microsoft Azure.

The VHM allows {productname} to obtain and report information about your virtual machines.
For more information on VHMs, see xref:client-configuration:vhm.adoc[].


== Prerequisites

The VHM you create needs to have the correct permissions assigned, in order for it to access the Azure VM.

Log in to your Azure account as the subscription administrator, and ensure that the Azure user account and application are in the correct groups.
The group that the application is in determines the role it has, and therefore the permissions.

== Create an Azure VHM
The Virtual Host Manager (VHM) runs on the {productname} Server.

Ensure you have installed the [systemitem]``virtual-host-gatherer-libcloud`` package on the {productname} Server.


.Procedure: Creating an Azure VHM

. In the {productname} {webui}, navigate to menu:Systems[Virtual Host Managers].
. Click btn:[Create] and select [guimenu]``Azure`` from the drop-down menu.
. In the [guimenu]``Add an Azure Virtual Host Manager`` section, use these parameters:
* In the [guimenu]``Label`` field, type a custom name for your VHM.
* In the [guimenu]``Subscription ID`` field, type the subscription ID found in [path]``Azure portal > Services > Subscriptions`` page.
* In the [guimenu]``Application ID`` field, type the application ID that you collected when you registered the application.
* In the [guimenu]``Tenant ID`` field, type the tenant ID provided by Azure that you collected when you registered the application.
* In the [guimenu]``Secret Key`` field, type the secret key associated with the Azure instance.
* In the [guimenu]``Zone`` field, type the zone your VM is located in. For example, for West Europe, enter [path]``westeurope``.
    This is required for subscription matching to work.
. Click btn:[Create] to save your changes and create the VHM.
. On the [guimenu]``Virtual Host Managers`` page, select the new VHM.
. On the [guimenu]``Properties`` page, click btn:[Refresh Data] to inventory the new VHM.

To see which objects and resources have been inventoried, navigate to menu:Systems[System List > Virtual Systems].


== Assigning permissions
// OM 2022-02-28: if the UI suggestion has been implemented (#1170298 via #1170514) we may eventually be able to remove this section
If the permissions are not set correctly, you might receive an error like this when you run [command]``virtual-host-gatherer``:

----
General error: [AuthorizationFailed] The client 'client_name' with object id 'object_ID' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/not-very-secret-subscription-id' or the scope is invalid. If access was recently granted, please refresh your credentials.
----

To determine the correct credentials, run this command at the prompt on the {productname} Server:

----
virtual-host-gatherer -i input_azure.json -o out_azure.json -vvv
----

The [path]``input_azure.json`` file should contain this information:

----
[
    {
        "id": "azure_vhm",
        "module": "Azure",
        "subscription_id": "subscription-id",
        "application_id": "application-id",
        "tenant_id": "tenant-id",
        "secret_key": "secret-key",
        "zone": "zone"
    }
]
----

== Azure UUID

Instances running on the Azure public cloud report this UUID to the {productname} Server:

----
13f56399-bd52-4150-9748-7190aae1ff21
----
