[[vhm-hce]]
= Virtual Host Manager and Google Compute Engine

// 2024-04-04 OM: It had been decided in the conversation with the mlm PO 
// that this Public Cloud related file can stay in the Uyuni books


You can use a virtual host manager (VHM) to gather instances from Google Compute Engine (GCE).

The VHM allows {productname} to obtain and report information about your virtual machines.
For more information on VHMs, see xref:client-configuration:vhm.adoc[].


== Prerequisites
The VHM you create needs to have the correct permissions assigned to access the GCE VM.

Log in to your Google Cloud Platform account as an administrator, and use the Cloud Identity and Access Management (IAM) tool to ensure that the service account has the appropriate roles.

== Create a GCE VHM

The Virtual Host Manager (VHM) runs on the {productname} Server.

To run a VHM, your {productname} Server needs to have port 443 open, to access the clients.

Ensure you have installed the [systemitem]``virtual-host-gatherer-libcloud`` package on the {productname} Server.

Before you begin, log in to the GCE panel, and download a certificate file.
Store this file locally on your {productname} Server, and take note of the path.

.Procedure: Creating a GCE VHM

. In the {productname} {webui}, navigate to menu:Systems[Virtual Host Managers].
. Click btn:[Create] and select [guimenu]``Google Compute Engine`` from the drop-down menu.
. In the [guimenu]``Add a Google Conpute Engine Virtual Host Manager`` section, use these parameters:
* In the [guimenu]``Label`` field, type a custom name for your VHM.
* In the [guimenu]``Service Account Email`` field, type the email address associated with your service account.
* In the [guimenu]``Cert Path`` field, type the local path on the {productname} Server to the key that you downloaded from the GCE panel.
* In the [guimenu]``Project ID`` field, type the project ID used by the GCE instance.
* In the [guimenu]``Zone`` field, type the zone your VM is located in.
    This is required for subscription matching to work.
. Click btn:[Create] to save your changes and create the VHM.
. On the [guimenu]``Virtual Host Managers`` page, select the new VHM.
. On the [guimenu]``Properties`` page, click btn:[Refresh Data] to inventory the new VHM.

To see which objects and resources have been inventoried, navigate to menu:Systems[System List > Virtual Systems].



== Assigning Permissions

If the permissions are not set correctly, you might receive an error like this when you run [command]``virtual-host-gatherer``:

----
ERROR: {'domain': 'global', 'reason': 'forbidden', 'message': "Required 'compute.zones.list' permission for 'projects/project-id'"}
ERROR: Could not connect to the Google Compute Engine Public Cloud using specified credentials.
----

To determine the correct credentials, run this command at the prompt on the {productname} Server:

----
virtual-host-gatherer -i input_google.json -o out_google.json -vvv
----

The [path]``input_google.json`` file should contain this information:

----
[
    {
        "id": "google_vhm",
        "module": "GoogleCE",
        "service_account_email": "mail@example.com",
        "cert_path": "secret-key",
        "project_id": "project-id",
        "zone": "zone"
    }
]
----



== GCE UUID

Instances running on the Google public cloud report this UUID to {productname} Server:

----
152986662232938449
----
