[[virtualization]]
= Virtualization

You can use {productname} to manage virtualized clients in addition to regular traditional or Salt clients.
In this type of installation, a virtual host is installed on the {productname} Server to manage any number of virtual guests.
If you choose to, you can install several virtual hosts to manage groups of guests.

The range of capabilities that virtualized clients have depends on the third-party virtualization provider you choose.

Xen and KVM hosts and guests can be managed directly in {productname}.
This enables you to autoinstall hosts and guests using {ay} or {kickstart}, and manage guests in the {webui}.


For VMWare, including VMWare vSphere, and Nutanix AHV, {productname} requires you to set up a virtual host manager (VHM) to control the VMs.
This gives you control over the hosts and guests, but in a more limited way than available with Xen and KVM; {productname} cannot create or edit VMs on VMWare vSphere or Nutanix AHV.

//So I looked it up in their docs: "VMWare vSphere is a suite of virtualization applications that includes ESXi and vCenter Server". So I think using "VMWare vSphere" implies ESXi and vCenter without having to spell them out. Happy to be proven wrong. --LKB 2019-07-10

Other third-party virtualization providers are not directly supported by {productname}.
However, if your provider allows you to export a JSON configuration file for the VM, you can upload that configuration file to {productname} and manage it with a VHM.

For more information about using VHMs to manage virtualization, see xref:client-configuration:vhm.adoc[].



== Manage Virtualized Hosts

Before you begin, ensure that the client you want to use as a virtualization host has the ``Virtualization Host`` system type assigned to it.
Both traditional and Salt clients can be used as virtual hosts.
Navigate to menu:Systems[Systems List] and click the name of the client to use as a virtualization host.
The system types are listed in the [guimenu]``System Properties`` section.
If the ``Virtualization Host`` system type is not listed, click btn:[Edit These Properties] to assign it.

When a client has the ``Virtualization Host`` system type, the [guimenu]``Virtualization`` tab is available in the System Details page for the client.
The [guimenu]``Virtualization`` tab allows you to create and manage virtual guests, and manage storage pools and virtual networks.



== Create Virtual Guests

You can add virtual guests to your virtualization hosts within the {productname} {webui}.



.Procedure: Creating a Virtual Guest
. In the {productname} {webui}, navigate to menu:Systems[Systems List], click the name of the virtualization host, and navigate to the [guimenu]``Virtualization`` tab.
. In the [guimenu]``General`` section, complete these details:
+
* In the [guimenu]``Guests`` subtab, click btn:[Create Guest].
* In the [guimenu]``Name`` field, type the name of the guest.
* In the [guimenu]``Hypervisor`` field, select the hypervisor to use.
* In the [guimenu]``Virtual Machine Type`` field, select either fully virtualized or para-virtualized.
* In the [guimenu]``Maximum Memory`` field, type the upper size limit for the guest disk, in MiB.
* In the [guimenu]``Virtual CPU count``, type the number of vCPUs for the guest.
* In the [guimenu]``Architecture`` field, select the emulated CPU architecture to use on the guest.
  By default, the architecture selected matches the virtual host.
* In the [guimenu]``Auto-installation Profile`` field, select the auto-installation tool to use to install the guest.
  Leave this field blank if you do not want to use auto-installation.
. In the [guimenu]``Disks`` section, complete the details of the virtual disk to use with the client.
  In the [guimenu]``Source template image URL`` field, ensure you type the path to an operating system image.
  If you do not do this, your guest is created with an empty disk.
. In the [guimenu]``Networks`` section, complete the details of the virtual network interface to use with the client.
  Leave the [guimenu]``MAC address`` field blank to generate a MAC address.
. In the [guimenu]``Graphics`` section, complete the details of the graphics driver to use with the client.
. Schedule a time for the guest to be created, and click btn:[Create] to create the guest.
. The new virtual guest starts as soon as it has successfully been created.


You can add virtual guests on a pacemaker cluster within the {productname} {webui}, too.

.Procedure: Creating a cluster managed Virtual Guest
. Follow the ``Creating a Virtual Guest`` procedure on one of the nodes of the cluster with the following additions:
+
* Ensure the [guimenu]``Define as a cluster resource`` field is checked.
* In the [guimenu]``Path to the cluster shared folder for VM definitions`` field, type the path to a folder shared by all cluster nodes where the guest configuration will be stored.
* Make sure every disk is located on a storage pool shared by all the cluster nodes.

Virtual Guests managed by a cluster can be live migrated.


ifeval::[{suma-content} == true]

== SUSE Support and VM Zones

Public cloud providers use regions to define the physical geographic location of the datacenter providing virtual machines.
For example, [systemitem]``US-East``, or [systemitem]``Asia``.

Regions are then further divided into zones.
For example, the [systemitem]``US-East`` region might contain zones called [systemitem]``us-east-2a`` and [systemitem]``us-east-2b``, among others.

{suse} uses the zone of a virtual machine to determine the appropriate subscription to provide.
If all of your VMs are provided by the same zone, you are within the terms and conditions of the ``1-2 Virtual Machines`` subscription.

If your VMs are provided by different zones, even if they are within the same region, you might not meet the conditions of the ``1-2 Virtual Machines`` subscription.
In this case, check your subscription carefully.

[NOTE]
====
For BYOS instances (bring your own subscription), all installed products are passed to the subscription matcher.
If your public cloud instances are PAYG (pay as you go), their base products are excluded from the subscription matcher counting.

The calculation about whether an instance is PAYG or BYOS is done at the time of registration or when a hardware refresh action is executed.
====

For more information, see https://www.suse.com/products/terms_and_conditions.pdf or contact {suse}.

endif::[]
