[[virt-xenkvm]]
= Virtualization with Xen and KVM

Xen and KVM virtualized clients can be managed directly in {productname}.


ifeval::[{suma-content} == true]

[WARNING]
====
Starting with {productname} 5.0, the libvirt management feature will be deprecated and subsequently removed in future versions.
If you still rely on VM management functionalities, we highly recommend considering alternatives like link:https://harvesterhci.io/[Harvester].
====

endif::[]

To begin, you need to set up a virtual host on your {productname} Server.
You can then set up autoinstallation using {ay} or {kickstart} for additional virtual hosts and for virtual guests.

This section also includes information about administering virtual guests after they have been installed.



[[virt-xenkvm-host]]
== Host setup

The way that you set up Xen or KVM on a VM host depends on operating system you want to use on its associated guests:

* For {suse} operating systems, see the SLES Virtualization Guide available from {sles-base-os-documentation}/book-virtualization.html.
* For {rhel} operating systems, refer to the Red Hat documentation for your version.

The [systemitem]``Virtualization Host`` formula will help you with initializing the host.
For more information, see xref:client-configuration:virt-xenkvm.adoc#virt-xenkvm-host-formula[].


=== Background Information

{productname} uses [systemitem]``libvirt`` to install and manage guests.
You must have the [package]``libvirt-daemon`` package installed on your host.
In most cases, the default settings are sufficient and you do not need to adjust them.
However, if you want to access the VNC console on your guests as a non-root user, you need to perform some configuration changes.
For more information about how to set up the VNC console, see the documentation for your operating system.

You need a bootstrap script on the {productname} Server.
The bootstrap script must include the activation key for your host.
We also recommend that you include your GPG key for additional security.
For more on creating a bootstrap script, see xref:client-configuration:registration-bootstrap.adoc[].

When the bootstrap script is ready, use it to register the host with the {productname} Server.
For more information about client registration, see xref:client-configuration:registration-overview.adoc[].



[[virt-xenkvm-host-formula]]
=== Initialize [systemitem]``Virtualization Host``

With the [systemitem]``Virtualization Host`` formula, initialize the host:

// CHECKIT: is the last step still needed?
.Procedure: Initializing [systemitem]``Virtualization Host``

. In the {productname} {webui}, navigate to the [guimenu]``System Details`` page for the host, and click the [guimenu]``Formulas`` tab.
. Select the [systemitem]``Virtualization Host`` formula, and click btn:[Save].
. Click the [systemitem]``Virtualization Host`` subtab.
. Check the settings, and click btn:[Save Formula].
. Apply the Highstate for the changes to take effect.
. Restart the [systemitem]``salt-minion`` service to activate the new configuration:

+
----
systemctl restart salt-minion
----



[[virt-xenkvm-autoinst]]
== Autoinstall VM Guests

You can use {ay} or {kickstart} to automatically install and register Xen and KVM guests.

You need an activation key for the VM host you want to register the guests to, and for each guest.
The activation key must have the [systemitem]``provisioning`` and [systemitem]``Virtualization Platform`` entitlements.
For more information about creating activation keys, see xref:client-configuration:activation-keys.adoc[].

If you want to automatically register the guests with {productname} after installation, you need to create a bootstrap script.
For more information about creating a bootstrap script, see xref:client-configuration:registration-bootstrap.adoc[].



=== Create an Autoinstallable Distribution

You need to create an autoinstallable distribution on the VM host to be able to autoinstall clients from {productname}.
The distribution can be made available from a mounted local or remote directory, or on a loop-mounted ISO image.

The configuration of the autoinstallable distribution differs depending on whether you are using a {rhel} or {suse} operating system on your guests.
The packages for a {rhel} installation are fetched from the associated base channel.
Packages for installing {suse} systems are fetched from the autoinstallable distribution.
Therefore, for {suse} systems, the autoinstallable distribution must be a complete installation source.

.Paths for Autoinstallable Distributions
[cols="1,1,1", options="header"]
|===

| Operating System Type | Kernel Location | [literal]``initrd`` Location
| {rhel} | [path]``images/pxeboot/vmlinuz``    | [path]``images/pxeboot/initrd.img``
| {suse} | [path]``boot/<arch>/loader/initrd`` | [path]``boot/<arch>/loader/linux``
|===

In all cases, ensure that the base channel matches the autoinstallable distribution.

Before you begin, ensure you have a installation media available to your VM Host.
It can be on a remote resource, a local directory, or a loop-mounted ISO image.
Additionally, ensure that all files and directories are world-readable.


.Procedure: Creating an Autoinstallable Distribution

. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > Distributions] and click btn:[Create Distribution].
. In the [guimenu]``Create Autoinstallable Distribution`` section, use these parameters:
* In the [guimenu]``Distribution Label`` section, type a unique name for the distribution.
    Use only letters, numbers, hyphens (``-``), periods  (``.``), and underscores (``_``), and ensure the name is longer than four characters.
* In the [guimenu]``Tree Path`` field, type an absolute path to the installation source.
* In the [guimenu]``Base Channel`` field, select the channel that matches the installation source.
    This channel is used as the package source for non-{suse} installations.
* In the [guimenu]``Installer Generation`` field, select the operating system version that matches the installation source.
* In the [guimenu]``Kernel Options`` field, type any options to be passed to the kernel when booting for the installation.
    The [option]``install=`` parameter and the [option]``self_update=0`` parameter are added by default.
* In the [guimenu]``Post Kernel Options`` section, type any options to  be passed to the kernel when booting the installed system for the first time.
. Click btn:[Create Autoinstallable Distribution] to save.

When you have created an autoinstallable distribution, you can edit it by navigating to  menu:Systems[Autoinstallation > Distributions] and selecting the distribution you want to edit.



=== Create and Upload an Autoinstallation Profile

Autoinstallation profiles contain all the installation and configuration data needed to install a system.
They can also contain scripts to be executed after the installation is complete.

{kickstart} profiles can be created using the {productname} {webui}, by navigating to menu:Systems[Autoinstallation > Profiles], clicking btn:[Create New Kickstart File], and following the prompts.

You can also create {ay} or {kickstart} autoinstallation profiles by hand.
{suse} provides templates of {ay} installation files that you can use as a starting point for your own custom files.
You will find them at https://github.com/SUSE/manager-build-profiles.

If you are using {ay} to install SLES, you also need to include this snippet:

----
<products config:type="list">
  <listentry>SLES</listentry>
</products>
----

* For more on {ay}, see xref:client-configuration:autoinst-profiles.adoc#autoyast[].
* For more on {kickstart}, see xref:client-configuration:autoinst-profiles.adoc#kickstart[], or refer to the Red Hat documentation for your installation.



.Procedure: Uploading an Autoinstallation Profile

. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > Profiles] and click btn:[Upload Kickstart/AutoYaST File].
. In the [guimenu]``Create Autoinstallation Profile`` section, use these parameters:
* In the [guimenu]``Label`` field, type a unique name for the profile.
    Use only letters, numbers, hyphens (``-``), periods  (``.``), and underscores (``_``), and ensure the name is longer than six characters.
* In the [guimenu]``Autoinstall Tree`` field, select the autoinstallable distribution you created earlier.
* In the [guimenu]``Virtualization Type`` field, select the relevant Guest type (for example, [parameter]``KVM Virtualized Guest``.
    Do not choose [guimenu]``Xen Virtualized Host`` here.
* OPTIONAL: If you want to manually create your autoinstallation profile, you can type it directly into the [guimenu]``File Contents`` field.
    If you have a file already created, leave the [guimenu]``File Contents`` field blank.
* In the [guimenu]``File to Upload`` field, click btn:[Choose File], and use the system dialog to select the file to upload.
    If the file is successfully uploaded, the filename is shown in the [guimenu]``File to Upload`` field.
* The contents of the uploaded file is shown in the [guimenu]``File Contents`` field.
    If you need to make edits, you can do so directly.
. Click btn:[Create] to save your changes and store the profile.

When you have created an autoinstallation profile, you can edit it by navigating to  menu:Systems[Autoinstallation > Profiles] and selecting the profile you want to edit.
Make the desired changes and save your settings by clicking btn:[Create].

[IMPORTANT]
====
If you change the [guimenu]``Virtualization Type`` of an existing {kickstart} profile, it might also modify the bootloader and partition options, potentially overwriting any custom settings.
Carefully review the [guimenu]``Partitioning`` tab to verify these settings before making changes.
====



=== Automatically Register Guests


When you install VM guests automatically, they are not registered to {productname}.
If you want your guests to be automatically registered as soon as they are installed, you can add a section to the autoinstallation profile that invokes a bootstrap script, and registers the guests.

This section gives instructions for adding a bootstrap script to an existing {ay} profile.

For more information about creating a bootstrap script, see xref:client-configuration:registration-bootstrap.adoc[].
For instructions on how to do this for {kickstart}, refer to the Red Hat documentation for your installation.

.Procedure: Adding a Bootstrap Script to an {ay} Profile

. Ensure your bootstrap script contains the activation key for the VM guests you want to register with it, and that is located on the host at [path]``/srv/www/htdocs/pub/bootstrap_vm_guests.sh``.
. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > Profiles], and select the {ay} profile to associate this script with.
. In the [guimenu]``File Contents`` field, add this snippet at the end of the file, immediately before the closing ``</profile>`` tag.
    Ensure you replace the example IP address [literal]``192.168.1.1`` in the snippet with the correct IP address for your {productname} Server:
+
----
<scripts>
  <init-scripts config:type="list">
    <script>
      <interpreter>shell</interpreter>
      <location>
        http://192.168.1.1/pub/bootstrap/bootstrap_vm_guests.sh
      </location>
    </script>
  </init-scripts>
</scripts>
----
+
. Click menu:Update[] to save your changes.

[IMPORTANT]
====
If your {ay} profile already contains a ``<scripts>`` section, do not add a second one.
Place the bootstrap snippet inside the existing ``<scripts>`` section.
====


=== Autoinstall VM Guests


When you have everything set up, you can start to autoinstall your VM guests.

[IMPORTANT]
====
Each VM host can only install one guest at a time.
If you are scheduling more than one autoinstallation, make sure you time them so that the next installation does not begin before the previous one has completed.
If a guest installation starts while another one is still running, the running installation is canceled.
====


. In the {productname} {webui}, navigate to menu:Systems[Overview], and select the VM host you want to install guests on.
. Navigate to the [guimenu]``Virtualization`` tab, and the [guimenu]``Provisioning`` subtab.
. Select the autoinstallation profile you want to use, and specify a unique name for the guest.
. Choose a proxy if applicable and enter a schedule.
. To change the guest's hardware profile and configuration options, click btn:[Advanced Options].
. Click btn:[Schedule Autoinstallation and Finish] to complete.



== Manage VM Guests

You can use the {productname} {webui} to manage your VM Guests, including actions like shutting down, restarting, and adjusting CPU, and memory allocations.

To do this, you need your Xen or KVM VM host registered to the {productname} Server, and have the [daemon]``libvirtd`` service running on the host.

In the {productname} {webui}, navigate to menu:Systems[System List], and click on the VM host for the guests you want to manage.
Navigate to the [guimenu]``Virtualization`` tab to see all guests registered to this host, and access the management functions.

For more information about managing VM guests using the {webui}, see xref:reference:systems/system-details/sd-virtualization.adoc[].
