[[retail-install-uyuni]]
= Install Uyuni Retail Server with openSUSE
:revdate: 2025-06-25
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

{productname} {smr} Server can be installed on openSUSE.

For general requirements, see xref:installation-and-upgrade:uyuni-install-requirements.adoc[].

[NOTE]
====
Další informace o nejnovější verzi a aktualizacích openSUSE Leap najdete na https://doc.opensuse.org/release-notes/.
====



== Nainstalujte Uyuni na openSUSE Leap


You install Uyuni as an add-on to openSUSE Leap.



.Procedure: Installing Uyuni on openSUSE Leap

. Jako základní systém nainstalujte openSUSE Leap se všemi dostupnými aktualizacemi Service Pack a aktualizacemi balíčků.
. Nakonfigurujte rozřešitelný (převoditelný na IP adresu) plně kvalifikovaný doménový název (FQDN) pomocí menu:yast[System > Network Settings > Hostname/DNS] (Systém > Nastavení sítě > Název hostitele/DNS).
. Nastavit proměnné, pro použití k vytvoření úložiště:
+
----
repo=repositories/systemsmanagement:/
repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
----
. Přidejte úložiště pro instalaci serverového softwaru {productname} jako [systemitem]``root``:
+
----
zypper ar https://download.opensuse.org/$repo uyuni-server-stable
----
. Refresh metadata from the repositories as [systemitem]``root``, and confirm the import of new GPG key into the keyring:
+
----
zypper ref
----
. Nainstalujte vzor pro server {productname} jako [systemitem]``root``:
+
----
zypper v patterns-uyuni_server
----
. Install the pattern for the {productname} {smr} product as [systemitem]``root``:
+
----
zypper in patterns-uyuni_retail
----
. Reboot the {productname} {smr} Server.


Continue with the server setup as described in xref:retail:retail-uyuni-server-setup.adoc[].
