[[autoinst-reinstall]]
= 登録済みシステムを再インストールする
:description: 登録済みのシステムを自動インストール可能なディストリビューションおよびプロファイルを使用して、インプレース再インストールのために構成します。
:revdate: 2024-02-19
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

インプレース再インストールは、ローカルクライアントシステムから開始されます。
したがって、クライアントがPXEでネットワークからブートできる必要はありません。

登録済みのクライアントをインプレースで再インストールするには、自動インストール可能なディストリビューションと自動インストールプロファイルを定義する必要があります。
詳細については、xref:client-configuration:autoinst-distributions.adoc[自動インストール可能なディストリビューション]およびxref:client-configuration:autoinst-profiles.adoc[自動インストールプロファイル]を参照してください。

自動インストールプロファイルと自動インストールのディストリビューションを定義したら、再インストールを実行できます。



.プロシージャ:登録済みのクライアントを再インストールする
. {productname} {webui}で、menu:システム[システムリスト]に移動し、再インストールするクライアントを選択し、menu:プロビジョニング[自動インストール> スケジュール]のサブタブに移動します。
. 作成した自動インストールプロファイルを選択し、必要に応じてプロキシを選択して、btn:[自動インストールをスケジュールしてから終了する]をクリックします。
. インストールの進行状況は、menu:プロビジョニング[自動インストール> セッションステータス]に移動するか、クライアント上で直接監視できます。
  クライアントが再起動し、ブートメニューで`reinstall-system`という新しい選択肢を選択します。

その後、インストールはHTTPプロトコルを通じて進められます。
