[[channels]]
= ソフトウェアチャンネル
:description: SUSE環境でソフトウェアチャネルを構成および管理し、互換性のあるパッケージをグループ化し、インストールと更新を効率化し、制御を維持します。
:revdate: 2024-12-12
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

チャンネルはソフトウェアパッケージをグループ化する方法です。
ソフトウェアパッケージはリポジトリによって提供され、リポジトリはチャネルに関連付けられています。
クライアントをソフトウェアチャネルに登録すると、そのクライアントは関連するソフトウェアをインストールおよび更新できます。

{productname}では、チャネルはベースチャネルと子チャネルに分かれています。
このようにチャネルを整理することで、各システムに互換性のあるパッケージのみがインストールされることが保証されます。
クライアントは、登録時にクライアントのオペレーティングシステムとアーキテクチャに基づいて割り当てられた1つのベースチャネルにのみ登録されている必要があります。
ベンダーが提供する有料チャネルの場合、関連するサブスクリプションを持っている必要があります。

ベースチャネルは、特定のオペレーティングシステムタイプ、バージョン、およびアーキテクチャ用に構築されたパッケージで構成されています。
例えば、{sles}{nbsp}15 {x86_64}ベースチャネルには、そのオペレーティングシステムとアーキテクチャに互換性のあるソフトウェアのみが含まれています。

子チャネルはベースチャネルに関連付けられており、ベースチャネルと互換性のあるパッケージのみを提供します。
システムは、そのベースチャネルの複数の子チャネルに登録できます。
システムがベースチャネルに割り当てられた場合、そのシステムは関連する子チャネルのみをインストールすることが可能です。
例えば、システムが{sles}{nbsp}15 `x86_64`ベースチャネルに割り当てられている場合、互換性のあるベースチャネルを通じて提供されるパッケージや、その関連する子チャネルのいずれかをインストールまたは更新できます。

{productname} {webui}では、menu:ソフトウェア[チャネルリスト> すべて]に移動することで、利用可能なチャネルをブラウズできます。
menu:ソフトウェア[管理> チャネル]に移動することで、チャネルを変更または新しいチャネルを作成できます。

カスタムチャネルを含むチャネルの使用については、xref:administration:channel-management.adoc[]を参照してください。

.ブートストラップ後のインストーラ更新チャンネルの処理
[IMPORTANT]
====
クライアントシステムがブートストラップされた後、**インストーラーの更新**チャネルは削除する必要があります。標準の更新チャネルには必要な更新がすでに含まれているため、このチャネルは冗長です。

さらに、移行中は、このチャンネルは不要であり、使用しないでください。
====

== {phub}で提供されるパッケージ


{phub}は{sle}製品の拡張機能で、{opensuse}コミュニティが提供する追加のオープンソースソフトウェアを提供しています。

[IMPORTANT]
====
{phub}のパッケージは{opensuse}のコミュニティによって提供されています。
それらは{suse}によってサポートされていません。
====

クライアントで{sle}オペレーティングシステムを使用している場合、これらの追加パッケージにアクセスするために{phub}拡張機能を有効にすることができます。
これにより、クライアントを登録できる{phub}チャネルが提供されます。

{phub}は多くのパッケージを提供しており、同期に時間がかかり、大量のディスクスペースを消費する可能性があります。
提供されるパッケージが必要でない限り、{phub}を有効にしないでください。

サポートされていないパッケージを意図せずにインストールまたは更新しないようにするために、最初にすべての{phub}パッケージを拒否するコンテンツライフサイクル管理戦略を実施することをお勧めします。
その後、必要な特定のパッケージを明示的に有効にすることができます。
コンテンツライフサイクル管理に関する詳細は、xref:administration:content-lifecycle.adoc[]を参照してください。



== AppStreamで提供されるパッケージ

{redhat}ベースのクライアントには、AppStreamを通じて追加のパッケージが利用可能です。
ほとんどの場合、AppStreamパッケージは必要なすべてのソフトウェアを確保するために必要です。



== EPELで提供されるパッケージ

{redhat}ベースのクライアントには、EPEL（エンタープライズLinuxのための追加パッケージ）を通じて追加のパッケージが利用可能です。
EPELは、追加のソフトウェアを提供するオプションのパッケージリポジトリです。

[IMPORTANT]
====
EPELのパッケージはFedoraコミュニティによって提供されています。
それらは{suse}によってサポートされていません。
====

クライアントで{redhat}オペレーティングシステムを使用している場合、これらの追加パッケージにアクセスするためにEPEL拡張機能を有効にすることができます。
これにより、クライアントを登録できるEPELチャネルが提供されます。

EPELは多くのパッケージを提供しており、同期に時間がかかり、大量のディスクスペースを消費する可能性があります。
EPELリポジトリは、提供されるパッケージが必要な場合を除いて、有効にしないでください。

サポートされていないパッケージを意図せずにインストールまたは更新しないようにするために、最初にすべてのEPELパッケージを拒否するコンテンツライフサイクル管理（CLM）戦略を実施することをお勧めします。
その後、必要な特定のパッケージを明示的に有効にすることができます。
コンテンツライフサイクル管理に関する詳細は、xref:administration:content-lifecycle.adoc[]を参照してください。



== {unifiedinstaller} クライアントの {sle} 更新チャネル

このチャネルは、{unifiedinstaller} によって、オペレーティングシステムをインストールする前に最新の状態に保たれるように使用されます。
すべての {sle} 製品は、インストール中にインストーラ更新チャネルにアクセスできる必要があります。

{sles} クライアントでは、更新を含む製品を追加すると、インストーラ更新チャネルがデフォルトで同期され、これらの製品チャネルで自動インストール可能なディストリビューションを作成するときに有効になります。

他のすべての {sle} バリアント、特に SAP 用の {sle} については、インストーラ更新チャネルを手動で追加する必要があります。
これを行うには、これらの {sle} バリアントのベースチャネルの下に適切な {sles} インストーラ更新チャネルをクローンします。
チャンネルがクローンされた後、これらの {sle} バリアントの自動インストール可能なディストリビューションを作成する際には、自動的に使用されます。
