[[client-upgrades]]
= クライアントのアップグレード
:description: YaSTツールを使用して、SUSE Multi-Linux Manager Web UIまたはContent Lifecycle Managerでクライアントをアップグレードする作業を自動化および実行します。
:revdate: 2024-11-29
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

クライアントは、基盤となるオペレーティングシステムのバージョン設定システムを使用し、定期的なアップグレードが必要です。

{scc}の登録クライアントが{suse}のオペレーティングシステムを使用している場合、{productname} {webui}内でアップグレードを実行できます。
サポートされている{sle}{nbsp}15のアップグレードパスについては、{sles-base-os-documentation}/cha-upgrade-paths.htmlを参照してください。

SLE{nbsp}12をSLE{nbsp}15にアップグレードするには、アップグレードは自動化されていますが、開始する前にいくつかの準備手順を行う必要があります。
詳細については、xref:client-configuration:client-upgrades-major.adoc[]を参照してください。

Content Lifecycle Managerを使用して、クライアントのアップグレードを自動化することもできます。
詳細については、xref:client-configuration:client-upgrades-lifecycle.adoc[]を参照してください。

サービスパックのアップグレード、openSUSE Leapのマイナーバージョンのアップグレード、またはopenSUSE Leapから{sle}への移行などの製品移行に関する詳細については、xref:client-configuration:client-upgrades-product-migration.adoc[]を参照してください。

ifeval::[{uyuni-content} == true]

未登録のopenSUSE Leapクライアントのアップグレードに関する詳細については、xref:client-configuration:client-upgrades-uyuni.adoc[]を参照してください。
endif::[]
