ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

ifndef::backend-pdf[]
[[client-cfg-overview]]
= クライアント設定ガイド
:description: 手動または自動による登録や、サポートされているLinuxシステムでの使用に合わせた設定の構成といった手順に従って、クライアントを構成してください。
:revdate: 2025-05-21
:page-revdate: {revdate}

// HTML Publication date 
**発行日:** {docdate}

== 序文


{productname}をインストールした後、最初のステップはクライアントの登録です。これらのクライアントの管理は、ワークフローの重要な部分になります。

{productname}は{sle}およびその他のLinux配布パッケージをサポートし、さまざまなハードウェアオプション間での互換性を提供します。

サポートされているクライアントと機能の完全なリストについては、xref:client-configuration:supported-features.adoc[サポートされているクライアントと機能]を参照してください。

このガイドでは、手動と自動両方のクライアント登録と設定について説明します。

== 著作権通知

ifeval::[{mlm-content} == true]
// HTML Copyright
Copyright © {copyrightdate} SUSE LLCおよび貢献者。All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]と題されたセクションに含まれています。
endif::[]

ifeval::[{uyuni-content} == true]
// HTML Copyright
Copyright © 2011–2025 Uyuni contributors.All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]と題されたセクションに含まれています。
endif::[]

== 商標
// HTML Trademarks
SUSEの商標については、 https://www.suse.com/company/legal/を参照してください。すべてのサードパーティの商標は、それぞれの所有者に属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。
本書のすべての情報は、細心の注意を払って編集されています。しかし、これは完全な正確性を保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。
endif::[]

ifdef::backend-pdf[]

<<<

:!sectnums:


[preface]
== 序文

クライアント設定ガイド |
{productname} {productnumber}

{productname}をインストールした後、最初のステップはクライアントの登録です。これらのクライアントの管理は、ワークフローの重要な部分になります。

{productname}は{sle}およびその他のLinux配布パッケージをサポートし、さまざまなハードウェアオプション間での互換性を提供します。

サポートされているクライアントと機能の完全なリストについては、xref:client-configuration:supported-features.adoc[サポートされているクライアントと機能]を参照してください。

このガイドでは、手動と自動両方のクライアント登録と設定について説明します。

// PDF Publication

**発行日:** {docdate}

ifeval::[{mlm-content} == true]
// PDF Copyright
Copyright © {copyrightdate} SUSE LLCおよび貢献者。All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]と題されたセクションに含まれています。
endif::[]

ifeval::[{uyuni-content} == true]
// PDF Copyright
Copyright © 2011–2025 Uyuni contributors.All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]と題されたセクションに含まれています。
endif::[]

// PDF Trademarks
SUSEの商標については、 https://www.suse.com/company/legal/を参照してください。すべてのサードパーティの商標は、それぞれの所有者に属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。
本書のすべての情報は、細心の注意を払って編集されています。しかし、これは完全な正確性を保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。

<<<

toc::[]

:sectnums:

endif::[]
