[[client-upgrades-major]]
= メジャーバージョンのアップグレード
:description: 準備したインストールメディアを使って、YaSTおよびAutoYaSTを使用し、クライアントをSUSE Linux Enterprise Server 12からSUSE Linux Enterprise Server 15にアップグレードします。
:revdate: 2026-07-21
:page-revdate: {revdate}

この方法は、{sles}{nbsp}12から{sles}{nbsp}15へのメジャーバージョンのアップグレードを対象としています。
アップグレードは、{yast}および{ay}によって制御され、Zypperは使用しません。

クライアントは、インストールされたオペレーティングシステムの最新のサービスパック（SP）が適用され、すべての最新の更新がインストールされている必要があります。
開始する前に、システムが最新の状態であり、すべての更新が正常にインストールされていることを確認してください。

[IMPORTANT]
====
この方法は、{sles}{nbsp}15から{sles}{nbsp}16へのアップグレードには適用されません。
{sles}{nbsp}15{nbsp}SP7から{sles}{nbsp}16.0へアップグレードする場合は、代わりに製品移行を使用してください。
詳細については、xref:client-configuration:client-upgrades-product-migration.adoc[]を参照してください。
====



== マイグレーションの準備


クライアントをSLE{nbsp}12からSLE{nbsp}15に移行する前に、次のことを行う必要があります:

. インストールメディアの準備
. 自動インストールのディストリビューションの宣言
. アクティベーションキーの作成
. 自動インストールプロファイルの作成



=== インストールメディアの準備

.プロシージャ:インストールメディアの準備
[role="procedure"]
_____
. コンテナホストで、インストールソースが含まれるISOイメージをダウンロードします。

. `mgradm`を使用して、ISOイメージからインストールデータをインポートします:
+
----
mgradm distribution copy <image_name>.iso <image_name>
----

. `mgradm`によって報告されたディストリビューションパスをメモしてください。
  ディストリビューションを{productname}に宣言する際に必要になります。
_____


[NOTE]
====
このイメージは、複数の自動インストールのディストリビューション用に使用できます。
====

詳細については、xref:client-configuration:autoinst-distributions.adoc[]を参照してください。



=== 自動インストールのディストリビューションを宣言する

.プロシージャ:自動インストールのディストリビューションを宣言する
[role="procedure"]
_____
. {productname} {webui}で、menu:システム[自動インストール> ディストリビューション]に移動します。
. `Create  Distribution`をクリックし、これらのフィールドに入力します。
+
`Distribution Label`フィールドに、自動インストールディストリビューションを識別するための名前を入力します。
  たとえば、`sles15sp6-x86_64`と指定します。
* `Tree Path`フィールドに、保存済みのインストールメディアへのパスを入力します。
* 一致する`Base Channel`を選択します。
  このチャンネルはインストールメディアと一致する必要があります。
* `Installer Generation`を選択します。
  このチャンネルはインストールメディアと一致する必要があります。
* オプション:このディストリビューションをブートするときに使用するカーネルオプションを指定します。
  カーネルオプションを提供する方法はいくつかあります。
  ここには、ディストリビューションに一般的なオプションのみを追加してください。
. btn:[自動インストール可能なディストリビューションを作成]をクリックします。
_____


=== アクティベーションキーの作成

古いSLE{nbsp}12ベースチャンネルから新しいSLE{nbsp}15チャンネルに切り替えるには、アクティベーションキーが必要です。


ifndef::backend-pdf[]
include::client-configuration:partial$snippet-creating-activation-key.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/snippet-creating-activation-key.adoc[]
endif::[]



=== 自動インストールプロファイルの作成

自動インストールプロファイルには、システムをインストールするために必要なすべてのインストールおよび設定データが含まれています。
インストールが完了した後に実行されるスクリプトも含めることができます。
手始めに使用できるスクリプトのサンプルは、 https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST.を参照してください。

有効な{ay}アップグレード設定については、 https://doc.opensuse.org/projects/autoyast/#CreateProfile-upgrade.を参照してください。


.プロシージャ:自動インストールプロファイルの作成
[role="procedure"]
_____
. {productname} {webui}で、menu:システム[自動インストール> プロファイル]に移動し、自動インストールプロファイルスクリプトをアップロードします。
+
手始めに使用できるスクリプトのサンプルは、以下を参照してください。
+
https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST.

. `Kernel Options`フィールドに、`autoupgrade=1`と入力します。
+
オプションとして、`Y2DEBUG=1`オプションも含めることができます。
デバッグ設定は必須ではありませんが、将来発生する可能性のある問題を調査するのに役立ちます。
+

[IMPORTANT]
====
Azureクラウドで実行されているクライアントは、`textmode=1 console=ttyS0`に`Kernel Options`を追加する必要があります。
====

. 自動インストールプロファイルを貼り付けるか、またはファイルアップロードフィールドを使用します。
. btn:[\+作成+]をクリックして保存します。
. アップロードしたプロファイルで変数を設定する必要がある場合、menu:システム[自動インストール> プロファイル]に移動し、編集するプロファイルを選択し、`Variables`タブに移動します。
+
次のフォーマットを使用して必要な変数を指定します。
+
----
<key>=<value>
----
_____



== 移行

自動インストールプロファイルで参照するチャンネルがすべて使用可能で完全に同期していることを開始前に確認してください。

ミラーリングの進行状況は`/var/log/rhn/reposync/<channel-label>.log`で監視できます。


.プロシージャ:移行
[role="procedure"]
_____
. {productname}サーバー{webui}で、`Systems`に移動し、アップグレードするクライアントを選択します。
. `Provisioning`タブに移動し、アップロードした自動インストールプロファイルを選択します。
. btn:[自動インストールをスケジュールしてから終了する]をクリックします。
  システムは必要なファイルをダウンロードし、ブートローダのエントリを変更し、再起動してアップグレードを開始します。
_____


クライアントが次回{productname}サーバーと同期すると、再インストールジョブを受け取ります。
再インストールジョブは新しいカーネルとinitrdパッケージを取得します。
また、新しいカーネルおよびinitrdパッケージへのポインタを含む、新しい`/boot/grub/menu.lst`（GRUB Legacy）または`/boot/grub2/grub.cfg`（GRUB 2）も書き込まれます。

クライアントが次回起動すると、grubを使用して新しいカーネルとそのinitrdを起動します。
このプロセス中にPXEブートは使用されません。

ジョブがフェッチされた約3分後に、クライアントは再起動するためにシャットダウンします。

[NOTE]
====
クライアントでは、移行が完了した後、`spacewalk/minion_script`スニペットを使用してクライアントを再登録します。
====
