[[clients-centos]]
= {centos}クライアントの登録
:description: SUSE Multi-Linux Managerで必要なソフトウェアリポジトリを追加することにより、x86-64およびAArch64を含むCentOSクライアントアーキテクチャを構成します
:revdate: 2025-03-10
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

このセクションでは、{centos}オペレーティングシステムを実行しているクライアントの登録について説明します。

ifeval::[{mlm-content} == true]

// Use list format: repository URLs / packages and metadata / version info
// Do we need to provide special info for uyuni users?
[IMPORTANT]
====
* {centos} リポジトリのURLは{scclongform}から入手できます。
* パッケージおよびメタデータは{suse}ではなくCentOSから提供されます。
* サポートされている製品については、xref:client-configuration:supported-features-centos.adoc[]のリリースノートとサポートテーブルを参照してください。
====
endif::[]

[IMPORTANT]
====

ifeval::[{mlm-content} == true]

{centos}クライアントは{centos}に基づいており、{sleses}、RES、{redhat}、または{es}とは無関係です。
endif::[]

{centos}ベースメディアリポジトリと{centos}インストールメディアへのアクセス管理、および{productname}サーバを{centos}コンテンツデリバリネットワークに接続する責任はあなたにあります。
====

[NOTE]
====
{centos}に{productname}クライアントを登録することは、`enforcing`のデフォルトのSELinux設定（`targeted`ポリシー付き）でテストされています。
{centos}クライアントを{productname}に登録するためにSELinuxを無効にする必要はありません。
====



== ソフトウェアチャンネルの追加


{centos}クライアントを{productname}サーバに登録する前に、必要なソフトウェアチャンネルを追加して同期する必要があります。

現在サポートされているアーキテクチャは、`x86_64`と`aarch64`です。
サポートされている製品とアーキテクチャの完全なリストについては、xref:client-configuration:supported-features.adoc[]を参照してください。

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]

ifeval::[{mlm-content} == true]

たとえば、`x86_64`アーキテクチャを使用する場合は、次の製品が必要です：

[[centos-channels-wizard]]
[cols="1,1", options="header"]
.CentOS製品 - WebUI
|===

| [OSのバージョン] | 製品名
| {centos} 7 | CentOS 7 x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]

または、コマンドプロンプトでチャンネルを追加できます。
このプロシージャで必要なチャンネルは次のとおりです。

[[centos-channels-MLM-cli]]
[cols="1,1", options="header"]
.CentOSチャンネル - CLI
|===

| [OSのバージョン] | ベースチャンネル
| {centos} 7 | centos7-x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_cli.adoc[]
endif::[]

endif::[]

ifeval::[{uyuni-content} == true]
このプロシージャで必要なチャンネルは次のとおりです。

[[centos-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.CentOSチャンネル - CLI
|===

| [OSのバージョン] | ベースチャンネル | クライアントチャンネル       | 更新/Appstreamチャンネル
| {centos} 7 | centos7      | centos7-uyuni-client | centos7-updates
|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli_multiarch.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli_multiarch.adoc[]
endif::[]

[NOTE]
====
`spacewalk-common-channels`が提供するクライアントツールチャネルは、{uyuni}から提供されており、{suse}からではありません。
====

endif::[]


モジュラー チャンネルを使用している場合は、クライアントで Python 3.6 モジュール ストリームを有効にする必要があります。
Python 3.6 を提供しない場合、`spacecmd`パッケージのインストールに失敗します。

[NOTE]
====
アップストリームと{productname}チャンネルの間でAppStreamチャンネルに利用可能なパッケージの数に不一致が見られるかもしれません。
異なる時点で追加された同じチャンネルを比較すると、異なる数が表示されることもあります。
これは、{centos} がリポジトリを管理する方法によるものです。新しいバージョンがリリースされると、{centos} は古いバージョンのパッケージを削除しますが、{productname} は年齢に関係なくすべてを保持します。
====


== 同期ステータスの確認

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]


ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]



== アクティベーションキーの作成

{centos} チャンネルと関連付けられているアクティベーションキーを作成する必要があります。

アクティベーションキーの詳細については、xref:client-configuration:activation-keys.adoc[]を参照してください。



== GPGキーの管理

クライアントは、ソフトウェアパッケージがインストールされる前に、その真正性を確認するためにGPGキーを使用します。
信頼できるソフトウェアのみがクライアントにインストールできます。

[IMPORTANT]
====
クライアントのセキュリティのために、GPGキーを信頼することは重要です。
どのキーが必要で信頼できるかを決定するのは管理者の仕事です。
GPG キーが信頼されていない場合、ソフトウェア チャンネルは使用できないため、クライアントにチャンネルを割り当てる決定はキーを信頼する決定に依存します。
====

GPG キーの詳細については、xref:client-configuration:gpg-keys.adoc[] を参照してください。



== クライアントの登録


[NOTE]
====
CentOS 7は、`/etc/yum.repos.d/CentOS-Base.repo`でURLが有効になっているため、オンボーディングに失敗します。その結果、`yum`がfastmirrorを使用してリポジトリを探そうとします。
これにより、起動が失敗し、次のエラーメッセージが表示されます。

----
Could not resolve host: mirrorlist.centos.org; Unknown error
----

この問題を回避するには、次のコマンドを使って`CentOS-Base.repo`ファイルを削除することができます。

[source,shell]
----
rm -f /etc/yum.repos.d/CentOS-Base.repo
----

または、ファイルを残す必要がある場合は、各URLセクションに`enabled=0`を追加できます。

どちらも場合も、再ブートストラップします。
====

ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]



ifeval::[{uyuni-content} == true]

== エラータの管理

[NOTE]
====
このセクションはコンテナ化されていない Uyuni にのみ適用され、{centos} 7 がサービス終了になった後に削除されます。
====

{centos} クライアントを更新するとき、パッケージには更新に関するメタデータが含まれていません。
この情報を取得するには、サードパーティのエラッタ サービスを使用できます。

[WARNING]
====

// ifeval::[{mlm-content} == true]
//
// The third-party errata service described here, CEFS, is provided and maintained by the community.
// It is not supported by {suse}.
//
// endif::[]

CEFS の著者は、役立つことを願って、正確性や最新性に保証はないものの、最善の努力に基づいてパッチやエラッタを提供します。
これは、パッチの日付が不正確である可能性があることを意味し、少なくとも1件のケースでは、公開されたデータが1か月以上古いことが示されました。
これらのケースについての詳細は、 https://github.com/stevemeier/cefs/issues/28#issuecomment-656579382および https://github.com/stevemeier/cefs/issues/28#issuecomment-656573607.を参照してください。

パッチデータに関する問題や遅延は、あなたの{productname}サーバに不正確なパッチ情報がインポートされる原因となる可能性があります。
これにより、レポート、監査、CVEの更新、またはその他のパッチ関連情報も不正確になる可能性があります。
セキュリティ関連の要件や認証基準に応じて、このサービスの使用の代替手段を検討してください。例えば、パッチデータを独立して検証することや、別のオペレーティングシステムを選択することなどです。
====




.プロシージャ:エラータサービスのインストール

. {productname}サーバー上で、コマンドプロンプトからルートとして、`sle-module-development-tools`モジュールを追加します。
+
----
SUSEConnect --product sle-module-development-tools/15.2/x86_64
----
. エラータサービスの依存関係をインストールします。
+
----
zypper in  perl-Text-Unidecode
----
. `/etc/rhn/rhn.conf`にこの行を追加または編集してください。
+
----
java.allow_adding_patches_via_api = centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras
----
. Tomcatを再起動します。
+
----
systemctl restart tomcat
----
. エラータスクリプト用のファイルを作成します。
+
----
touch /usr/local/bin/cent-errata.sh
----
. 新しいファイルを編集してこのスクリプトを含め、必要に応じてリポジトリの詳細を編集します。
    このスクリプトは、外部のエラータサービスからエラータの詳細をフェッチして展開し、詳細を発行します。
+
----
#!/bin/bash
mkdir -p /usr/local/centos
cd /usr/local/centos
rm *.xml
wget -c http://cefs.steve-meier.de/errata.latest.xml
wget -c https://www.redhat.com/security/data/oval/v2/RHEL7/rhel-7.oval.xml.bz2
bzip2 -d rhel-7.oval.xml.bz2
wget -c http://cefs.steve-meier.de/errata-import.tar
tar xvf errata-import.tar
chmod +x /usr/local/centos/errata-import.pl
export SPACEWALK_USER='<adminname>';export SPACEWALK_PASS='<password>'
/usr/local/centos/errata-import.pl --server '<servername>' \
--errata /usr/local/centos/errata.latest.xml  \
--include-channels=centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras \
--publish --rhsa-oval /usr/local/centos/rhel-7.oval.xml
----
. スクリプトを毎日実行するようcronジョブを設定します。
+
----
ln -s /usr/local/bin/cent-errata.sh /etc/cron.daily
----

このツールについての詳細は、 https://cefs.steve-meier.de/.を参照してください。

endif::[]
