[[configuration-management]]
= 設定管理
:description: SUSE Multi-Linux Manager と YaST ツールを使用して、クライアントの中央管理された設定ファイルを管理します。
:revdate: 2026-04-20
:page-revdate: {revdate}
:page-author: SUSE 製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


クライアントそれぞれを手動で設定するのではなく、設定ファイルおよびチャンネルを使用してクライアントの設定を管理できます。

設定パラメータはスクリプト化され、設定ファイルに保存されます。
{productname} {webui} を使用して設定ファイルを直接記述することも、他の場所に存在するファイルをアップロードまたはリンクすることもできます。

設定チャンネルは、設定ファイルを整理するために使用されます。
クライアントを設定チャンネルにサブスクライブし、必要に応じて設定ファイルをデプロイできます。

設定ファイルはバージョン管理されているため、設定を追加し、クライアントでテストし、必要に応じて以前のリビジョンにロールバックできます。
設定チャンネルを作成したら、さまざまな設定ファイル間や同じ設定ファイルのリビジョン間で比較を行うこともできます。

一元管理された設定ファイルはグローバル設定チャンネルによって提供されます。

次の表に、サポートされている機能を示します。各記号の意味は次のとおりです。

* {check} 機能は {suse} によってサポートされています。
* {cross} 機能は {suse} ではサポートされていません。
* {question} 機能は検討中であり、後日サポートされるかどうかは未定です。


.設定管理でサポートされる機能
[cols="1,1", options="header"]
|===

| 機能
| ステータス

| 設定チャンネル
| {check}

| 状態チャンネル
| {check}

| ファイルのデプロイ
| {check}

| ファイルの比較
| {question}

| ハイステートの適用
| {check}

| クライアントからのファイルインポート
| {cross}

| Jinja テンプレート
| {check}

|===



== 設定チャンネルの作成


=== 設定チャンネル。

新しい一元的な設定チャンネルを作成するには:

.プロシージャ:設定チャンネルの作成
[role=procedure]
____
. {productname} {webui} で、menu:設定[チャンネル] に移動し、btn:[設定チャンネルの作成] をクリックします。

. チャンネルの名前を入力します。

. チャンネルのラベルを入力します。
    このフィールドには、英字、数字、ハイフン(`-`)、およびアンダースコア(`_`)のみを含める必要があります。

. 他のチャンネルから区別できるようにチャンネルの説明を入力します。

. btn:[設定チャンネルの作成]をクリックして新しいチャンネルを作成します。
____



=== 状態チャンネル

状態チャンネルは、クライアント上の{salt}状態を使用します:

.プロシージャ:{salt}状態チャンネルの作成
[role=procedure]
____
. {productname} {webui} で、menu:設定[チャンネル] に移動し、btn:[状態チャンネルの作成] をクリックします。

. チャンネルの名前を入力します。

. チャンネルのラベルを入力します。
    このフィールドには、英字、数字、ハイフン(`-`)、およびアンダースコア(`_`)のみを含める必要があります。

. 他のチャンネルから区別できるようにチャンネルの説明を入力します。

. `SLS Contents`ファイルの`init.sls`を入力します。

. btn:[状態チャンネルの作成]をクリックして、新しいチャンネルを作成します。
____


== 設定ファイル、ディレクトリ、またはシンボリックリンクの追加

設定チャンネルを作成済みの場合、設定ファイル、ディレクトリ、またはシンボリックリンクを追加できます。

.プロシージャ:設定ファイル、ディレクトリ、またはシンボリックリンクの追加
[role=procedure]
____
. {productname} {webui}で、menu:設定[チャンネル]に移動し、設定ファイルを追加したい設定チャンネルの名前をクリックし、menu:ファイルの追加[ファイルの作成]サブタブに移動します。

. `File Type`フィールドで、テキストファイル、ディレクトリ、またはシンボリックリンクを作成するかどうかを選択します。
. `Filename/Path`フィールドで、ファイルをデプロイする場所への絶対パスを入力します。

. シンボリックリンクを作成する場合は、`Symbolic Link Target Filename/Path`フィールドにターゲットファイルとパスを入力します。

. `User name`フィールドにファイルの`Group name`と`Ownership`を入力し、`File Permissions Mode`を入力します。

. クライアントでSELinuxが有効になっている場合、`SELinux contexts`を設定して、必要なファイル属性（ユーザ、ロール、ファイルタイプなど）を有効にできます。
. 従来のマクロ区切り文字の代わりに、グレインまたはピラーのデータを使用してJinjaテンプレートを利用できます。

. `File Contents`テキストボックスに設定ファイルの内容を入力し、スクリプトドロップダウンボックスを使用して適切なスクリプト言語を選択します。

. btn:[設定ファイルの作成]をクリックします。

____


== クライアントを設定チャンネルにサブスクライブする

menu:システム[システムリスト]に移動し、サブスクライブしたいクライアントを選択し、`Configuration`タブに移動することで、個々のクライアントを設定チャンネルにサブスクライブできます。
複数のクライアントを設定チャンネルにサブスクライブするには、システムセットマネージャ（SSM）を使用できます。


.プロシージャ:複数のクライアントを設定チャンネルにサブスクライブする
[role=procedure]
____
. {productname} {webui}で、menu:システム[システム一覧]に移動し、作業したいクライアントを選択します。

. menu:システム[システムセットマネージャ]に移動し、menu:設定[チャンネルにサブスクライブ]サブタブに移動して、使用可能な設定チャンネルの一覧を表示します。

. オプション:`Systems currently subscribed`列の番号をクリックして、設定チャンネルに現在サブスクライブされているクライアントを表示します。

. サブスクライブしたい設定チャンネルを確認し、btn:[続行]をクリックします。

. 上下矢印を使用して設定チャンネルをランクします。
    設定の競合が設定チャンネルで発生した場合、一覧の上の方にあるチャンネルが優先されます。

. 選択したクライアントにチャンネルを適用する方法を決定します。
    btn:[最低優先度でサブスクライブ]をクリックして、新しいチャンネルを現在サブスクライブされているチャンネルよりも低い優先度で追加します。
    btn:[最高優先度でサブスクライブ]をクリックして、新しいチャンネルを現在サブスクライブされているチャンネルよりも高い優先度で追加します。
    btn:[既存のサブスクリプションを置き換える]をクリックして、既存のチャンネルを削除し、新しいチャンネルに置き換えます。

. btn:[サブスクリプションの適用]をクリックします。

____

[NOTE]
====
新しい設定チャンネルの優先度が既存のチャンネルと衝突する場合、重複するチャンネルは削除され、新しい優先度に従って置き換えられます。
クライアントの設定優先度がアクションによって再編成される場合、{webui}は変更を確認する必要があります。
====


== 設定ファイルの比較

システムセットマネージャ(SSM)を使用して、クライアントにデプロイされた設定ファイルと{productname}サーバに保存されている設定ファイルを比較することもできます。

.プロシージャ:設定ファイルの比較
[role=procedure]
____
. {productname} {webui}で、menu:システム[システム一覧]に移動し、比較したい設定ファイルにサブスクライブされているクライアントを選択します。

. menu:システム[システムセットマネージャ]に移動し、menu:設定[ファイルの比較]サブタブに移動して、使用可能な設定ファイルの一覧を表示します。

. オプション:`Systems`列の番号をクリックして、設定ファイルに現在サブスクライブされているクライアントを表示します。

. 比較する設定ファイルを確認し、btn:[ファイルの比較をスケジュール]をクリックします。
____


== クライアントでのJinjaテンプレート

{salt}クライアントでJinjaテンプレートが可能です。
Jinjaは、{salt}エンジンによってコンテンツが処理されるときのみ評価されます。
Jinjaは、ピラーまたはグレインから変数を提供します。
それらは{salt}によって管理されるファイル（例えば、`file.managed`経由）や{salt}ステートで使用できます。

[NOTE]
====
設定ファイルチャネルは、Jinja処理なしで静的ファイルを配信します。
状態チャネルファイルは、{salt}状態で参照されている場合にのみ適用されます。
====

詳細については、この例とともに https://docs.saltproject.io/salt/user-guide/en/latest/topics/jinja.htmlをご参照ください。

----
{% if grains.os_family == 'RedHat' %}
  {% set dns_cfg = '/etc/named.conf' %}
{% elif grains.os_family == 'Debian' %}
  {% set dns_cfg = '/etc/bind/named.conf' %}
{% else %}
  {% set dns_cfg = '/etc/named.conf' %}
{% endif %}
dns_conf:
  file.managed:
    - name: {{ dns_cfg }}
    - source: salt://dns/files/named.conf
    - template: jinja
----
