[[contact-methods-intro]]
= クライアントの接続メソッド
:description: SUSE Multi-Linux Managerを使用して、クライアントの通信ニーズに最適なSalt接続メソッドを構成およびデプロイする方法を学びます。
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

{productname}サーバーがクライアントと通信するための接続方法は3つあります。
それらは{salt}プロトコルに基づいています。

使用する{salt}接続メソッドは、クライアントのタイプおよびネットワークアーキテクチャによって決まります:

デフォルト::
特定のユーザーのニーズがない限り、推奨されます。
デフォルトでは、{salt}バンドルの実装がデプロイされます。
詳細については、xref:client-configuration:contact-methods-default.adoc[]を参照してください。

SSH Push::
ネットワーク制限によりクライアントがサーバーに接続できない場合にのみ有用です。
これは{salt}バンドルでのみサポートされています。
この接続方法には重大な制限があります。
詳細については、xref:client-configuration:contact-methods-saltssh.adoc[]を参照してください。

SSH Push (トンネル使用)::
SSHプッシュと同じですが、安全な通信トンネルを使用します。
詳細については、xref:client-configuration:contact-methods-saltssh-tunnel.adoc[]を参照してください。


{salt}通信ソフトウェアオプションの実装:

Salt Bundle (`venv-salt-minion`)::
は、{salt}ミニオン、Python 3、必須のPythonモジュール、およびライブラリが含まれている1つのバイナリパッケージです。
したがって、{salt}接続メソッドはクライアントにインストールされているソフトウェアに依存しません。

+

////
Using the {salt} Bundle is the default.
It is the only supported implementation for the SSH Push or SSH Push (with tunnel) contact method.
////

+

詳細については、xref:client-configuration:contact-methods-saltbundle.adoc[]を参照してください。

Salt Minion (`salt-minion`)::
は、クライアントシステムにインストールされている{salt}ソフトウェアであり、一般的に{productname}ではもはやサポートされていません。
必要に応じて、起動するためのみ{sle} 15クライアントおよび派生製品（{sle-micro}など）にインストールできます。
その後、起動中に`venv-salt-minion`に置き換えられます。



[IMPORTANT]
====
いわゆる従来の接続プロトコルは、{productname} 5.0以降ではサポートされなくなりました。
{productname} 4から5にアップグレードする前に、従来のプロキシを含む既存の従来のクライアントは、{salt}に移行するか、{salt}プロキシに置き換える必要があります。

従来の{productname} 4クライアントを{salt}クライアントに移行する方法についての詳細は、 https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.htmlを参照してください。
====
