[[package-management]]
= パッケージ管理
:description: SUSE Multi-Linux Managerのユーザーインターフェースを使用して、クライアント上のソフトウェアパッケージを構成および管理し、システムをナビゲートし、クライアントを選択し、ソフトウェアにアクセスします。
:revdate: 2024-11-21
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

クライアントは、パッケージを使用してソフトウェアをインストール、アンインストール、およびアップグレードします。

// available subtabs:
//     List / Remove
//     Upgrade
//     Install
//     Lock / Unlock
//     Profiles
//     Non Compliant


クライアント上のパッケージを管理するには、`Systems`に移動し、管理するクライアントをクリックし、menu:Systems[Software > パッケージ]のサブタブに移動します。
このセクションで利用可能なオプションは、選択したクライアントの種類、およびその現在のチャネルのサブスクリプションによって異なります。

ほとんどのパッケージ管理アクションは、アクションチェーンに追加できます。
アクションチェーンの詳細については、xref:reference:schedule/action-chains.adoc[]を参照してください。


[IMPORTANT]
==== 

パッケージをインストールまたはアップグレードするとき、ライセンスまたはEULAは自動的に受け入れられます。
====


== プロファイルを使用したパッケージの比較


クライアントにインストールされているパッケージを保存されたプロファイルや、別のクライアントにインストールされているパッケージと比較できます。
比較が行われると、選択したクライアントを一致させるために変更することを選択できます。

プロファイルに対してパッケージを比較するには、プロファイルを保存しておく必要があります。
プロファイルは、現在インストールされているクライアントのパッケージから作成されます。
プロファイルが作成されると、同じパッケージがインストールされた他のクライアントをインストールするために使用できます。


.プロシージャ:保存されたプロファイルの作成
. {productname} {webui}で、`Systems`に移動し、プロファイルの基にするクライアントをクリックし、menu:Systems[Software > パッケージ > プロファイル]のサブタブに移動します。
. btn:[システムプロファイルの作成]をクリックします。
. プロファイルの名前と説明を入力し、btn:[プロファイルの作成]をクリックします。


.プロシージャ:クライアントパッケージの比較
. {productname} {webui}で、`Systems`に移動し、比較するクライアントをクリックし、menu:Systems[Software > パッケージ > プロファイル]のサブタブに移動します。
    保存されたプロファイルと比較するには、プロファイルを選択し、btn:[比較]をクリックします。
. 別のクライアントと比較するには、クライアント名を選択し、btn:[比較]をクリックして、2つのクライアントの違いのリストを表示します。



[[package-management-orphaned-packages]]
== 孤立したパッケージ

孤立したパッケージは、{productname}によって同期されたパッケージであり、ソフトウェアチャンネルに関連付けられていません。
したがって、孤立したパッケージは通常、{productname}クライアントには利用できず、ユーザーは追加の手間なしにそのようなパッケージをインストールすることはできません。

次のいずれかのイベントの結果として、パッケージが孤立する可能性があります。

* 同期されたリポジトリはパッケージを削除します。
  デフォルトでは、{productname}はそのようなパッケージをチャンネルからリンク解除しますが、パッケージ自体は削除しません。
* リポジトリはパッケージを新しいバージョンに置き換えるので、以前のバージョンは削除されます。
* reposyncプロセスが中断されたので(たとえば、容量不足の例外が発生したため)、ダウンロードされたパッケージがチャンネルに関連付けられませんでした。
* ユーザはパッケージを手動でアップロードしましたが、どのチャンネルにも関連付けませんでした。

孤立したパッケージはユーザー環境にスペースを消費し、チャンネルに関連付けられていないため、クライアントに簡単に配布することはできません。
孤立したパッケージは、起動プロセスや顧客特有の手順など、特定のワークフローにおいて有用な場合があります。

{webui}で孤立したパッケージを表示するには、menu:ソフトウェア[管理> パッケージ> チャンネルのないパッケージを表示]をクリックします。

{productname}は定期的に孤立したパッケージを検索し、パッケージ組織IDを1に変更するTaskomaticジョブを実行します。
これは、Taskomaticジョブの実行後にのみ孤立したパッケージを削除できることを意味します。
削除できない孤立したパッケージに遭遇した場合は、24時間待ってから再度削除を試みてください。

// .Procedure: Deleting orphaned packages

孤立したパッケージの削除:

// * With the UI (FIXME is this possible?  How?

* 個々のパッケージを対象とするコマンドラインツールを使用する場合。例:
+
----
spacecmd package_remove zypper-1.14.52-150400.1.9.x86_64
----

* 孤立したパッケージすべてを一度に対象とするコマンドラインツールを使用する場合:
+
----
spacecmd package_removeorphans
----
