[[registration-sudo]]
= ルートアクセスとsudoの設定
:description: ルートSSHアクセスを許可しないシステムでソフトウェアをインストールおよび管理するために、パスワードなしのsudoアクセス権を持つ非ルートユーザーを設定します。
:revdate: 2026-08-31
:page-revdate: {revdate}

多くのオペレーティングシステム（{ubuntu}、{debian}、{raspberrypios}、{sle} 16など）では、デフォルトで`root`ユーザのSSHアクセスが無効になっているか、`root`パスワードが設定されずにインストールされます。
これらのクライアントをオンボードするには、必要なPythonおよびSalt minionバイナリに対してパスワードなしの`sudo`権限が設定された、通常の非特権ユーザを使用できます。

[IMPORTANT]
====
この設定は、クライアントの起動および登録にのみ必要です。
クライアントが正常に登録されると、{productname}エージェントは`root`権限で実行されるため、この一時的なパスワードなしの`sudo`アクセス権は不要になります。
セキュリティ上の理由から、登録完了後に`sudoers`ファイルからこれらの行を削除することをお勧めします。
====


== 非ルートユーザにsudoアクセス権を付与する

非ルートユーザを使用してクライアントをオンボードするには、クライアントシステム上の`sudoers`ファイルを編集して、特定のコマンドに対するパスワードなしの権限昇格を許可する必要があります。

.プロシージャ:パスワードなしのsudoアクセスの付与
[role="procedure"]
_____
. クライアントで、次のコマンドを実行して`sudoers`ファイルを編集してください:
+
----
sudo visudo
----
. ファイルの末尾に、次の行を追加します。`<user>`をクライアントを起動するユーザーの名前に置き換えてください。
+
----
<user>  ALL=NOPASSWD: /var/tmp/venv-salt-minion/bin/python
----
_____

[NOTE]
====
デフォルトのSalt Bundleではなく、従来の手動`salt-minion`登録セットアップを使用する古いオペレーティングシステム（{sle} 15など）では、権限昇格のために`/usr/bin/python3`が必要になる場合があります:
+
----
<user>  ALL=NOPASSWD: /usr/bin/python3, /var/tmp/venv-salt-minion/bin/python
----
====

[NOTE]
====
オペレーティングシステムの自己インストールバージョンでは、{webui}および起動するスクリプトが権限昇格ステップ中の対話型パスワード入力をサポートしていないため、パスワードなしの権限昇格が必要です。
クラウドインスタンスの場合、これは通常`cloud-init`によって自動的に処理され、デフォルトユーザのsudoersセットアップが行われます。
====
