[[registering-clients-cli]]
= コマンドラインでクライアントを登録する
:description: コマンドラインでSalt minionの設定ファイルを編集し、サービスを再起動してクライアントを登録します。
:revdate: 2026-08-20
:page-revdate: {revdate}


//== Manual Client Registration

== 概要


ほとんどの場合、{salt}クライアントはデフォルトの起動メソッドで正確に登録されます。

ただし、{salt}を使用してクライアントを{productname}サーバに手動で登録できます。そのためには、クライアントで{salt} minionファイルを編集し、サーバの完全修飾ドメイン名(FQDN)を指定します。

このメソッドでは:
 
* サーバで受信するポート4505および4506を使用します。
* {productname}サーバの設定は不要です。ただし、上記のポートが開いていることを確認する必要があります。
* 登録の前に、Saltクライアントに`venv-salt-minion`（Saltバンドル）、または{sle} 15以降の派生版の場合は`salt-minion` パッケージがインストール済みである必要があります。
  両者は異なる場所に設定ファイルを使用しますが、ファイル名は同じです。
  `systemd`サービスのファイル名は異なります。

[WARNING]
====
この方法で起動できるのは、`salt-minion`がクライアントツールチャンネルまたは公式の{suse}ディストリビューションの一部である場合のみです。
====

== {salt}バンドルの設定

{salt}バンドル (`venv-salt-minion`)::

+

* `/etc/venv-salt-minion/`
* `/etc/venv-salt-minion/minion`
* `/etc/venv-salt-minion/minion.d/NAME.conf`
* systemdサービスファイル: `venv-salt-minion.service`

+

Saltバンドルに関する詳細は、xref:client-configuration:contact-methods-saltbundle.adoc[Salt Bundle]を参照してください。

.プロシージャ:Saltバンドル設定ファイルでクライアントを登録する
[role=procedure]
_____
. Saltクライアントで`minion`の設定ファイルを開きます。
  設定ファイルは次の場所にあります:

+

.設定ファイル
[source, Shell]
----
/etc/venv-salt-minion/minion
----

+

または

+

.設定ファイル
[source, Shell]
----
/etc/venv-salt-minion/minion.d/NAME.conf
----
. ファイルに{productname}サーバまたはプロキシのFQDNと、必要に応じてアクティベーションキーを追加または編集します。以下に示す他の設定パラメータも追加してください。

+

.設定パラメータ
[source, YAML]
----
master: SERVER.EXAMPLE.COM

grains:
  susemanager:
    activation_key: "<Activation_Key_Name>"

server_id_use_crc: adler32
enable_legacy_startup_events: False
enable_fqdns_grains: False
----


. `venv-salt-minion`サービスを再起動します:

+

[source, Shell]
----
systemctl restart venv-salt-minion
----

. {productname}サーバで、新しいクライアントキーを受け入れます。`<client>`をクライアントの名前に置き換えます:

+

----
salt-key -a '<client>'
----
_____


// bsc#1275658
== クライアントの設定

[IMPORTANT]
====
通常の`salt-minion`は、一般的にサポートされていません。
このセクションは、{sle} 15またはその派生版の起動にのみ使用してください。起動中に`venv-salt-minion`に置き換えられます。
====

クライアント (`salt-minion`)::
+
* `/etc/salt/`
* `/etc/salt/minion`
* `/etc/salt/minion.d/NAME.conf`
* systemdサービスファイル: `salt-minion.service`

.プロシージャ:Salt Minion設定ファイルでクライアントを登録する
[role=procedure]
_____
. Saltクライアントで`minion`の設定ファイルを開きます。
  設定ファイルは次の場所にあります:

+

[source, Shell]
----
/etc/salt/minion
----

+

または

+

[source,Shell]
----
/etc/salt/minion.d/NAME.conf
----

. ファイルに{productname}サーバまたはプロキシのFQDNと、必要に応じてアクティベーションキーを追加または編集します。
  以下に示す他の設定パラメータも追加してください。

+

[source, YAML]
----
master: SERVER.EXAMPLE.COM

grains:
  susemanager:
    activation_key: "<Activation_Key_Name>"

server_id_use_crc: adler32
enable_legacy_startup_events: False
enable_fqdns_grains: False
----

. `salt-minion`サービスを再起動します:

+

[source, Shell]
----
systemctl restart salt-minion
----

. {productname}サーバで、新しいクライアントキーを受け入れます。`<client>`をクライアントの名前に置き換えます:

+

[source,Shell]
----
salt-key -a '<client>'
----
_____

{salt}minion設定ファイルに関する詳細は、 https://docs.saltproject.io/en/latest/ref/configuration/minion.html[Salt Minionの設定]を参照してください。
