[[registration-overview]]
= クライアントの登録
:description: 登録処理を開始する前に、アクティベーションキーを使用してクライアントを登録し、クライアントの日時がサーバーと同期されていることを確認してください。
:revdate: 2025-02-06
:page-revdate: {revdate}

クライアントを{productname}サーバに登録する方法は複数あります。
このセクションでは、利用可能なさまざまな方法について説明します。
また、クライアントで実行する予定のオペレーティングシステムに特有の情報も含まれています。

始める前に次の項目を確認してください。

* クライアントは、登録する前に{productname}サーバと日時が正しく同期されている必要があります。
* アクティベーションキーを作成しました。
  アクティベーションキーの作成に関する詳細は、xref:client-configuration:activation-keys.adoc[]を参照してください。


.ブートストラップ後のインストーラ更新チャンネルの処理
[IMPORTANT]
====
クライアントシステムがブートストラップされた後、**インストーラーの更新**チャネルは削除する必要があります。
標準の更新チャネルには必要な更新がすでに含まれているため、このチャネルは冗長です。

さらに、移行中は、このチャンネルは不要であり、使用しないでください。
====


[IMPORTANT]
====
{productname}サーバのベースOSを{productname}自体に登録しないでください。
{productname}サーバのベースOSは、個別に管理するか、別の{productname}サーバを使用して管理する必要があります。

{productname} サーバコンテナを管理するには、`mgradm` ツールを使用してください。

====

ifeval::[{mlm-content} == true]


[IMPORTANT]
====
旧バージョンの{productname}から新バージョンに移行した後は、新しいシステムをオンボーディングする前に、潜在的な問題を避けるために起動スクリプトを再生成することを強くお勧めします。
====

endif::[]
