[[repos]]
= ソフトウェアリポジトリ
:description: ソフトウェアリポジトリを構成して、SUSE® Multi-Linux Managerチャンネルおよびクライアントのローカルリポジトリからパッケージをインストールします。
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

リポジトリはパッケージを収集するために使用されます。
ソフトウェアリポジトリにアクセスできる場合、そのソフトウェアリポジトリが提供するソフトウェアをインストールすることができます。
クライアントをチャンネルに割り当て、クライアント上でパッケージをインストールおよび更新するには、{productname}のソフトウェアチャンネルに関連付けられたリポジトリが少なくとも1つ必要です。

{productname}のほとんどのデフォルトチャンネルは、すでに正しいリポジトリに関連付けられています。
カスタムチャンネルを作成する場合、アクセスできるリポジトリ、または自分で作成したリポジトリを関連付ける必要があります。

カスタムリポジトリおよびチャンネルに関する詳細は、xref:administration:custom-channels.adoc[]を参照してください。



== ローカルリポジトリの場所


クライアントでローカルリポジトリを設定して、{productname}チャンネルが提供しないパッケージを提供できます。

[WARNING]
====
ほとんどの場合、クライアントシステムはローカルリポジトリを必要としません。
ローカルリポジトリは、クライアント上で利用可能なパッケージを把握するのに問題を引き起こす可能性があります。
これにより、予期しないパッケージがインストールされる可能性があります。
====

ローカルリポジトリは、オンボーディング中に無効になります。

ローカルリポジトリは、チャンネルステートが実行されるたびに無効になります。
たとえば、ハイステートを適用する場合やパッケージアクションを実行する場合です。

オンボーディング後もローカルリポジトリを有効にしておく必要がある場合は、影響を受けるクライアントに対して次のpillarを設定する必要があります。

`/srv/pillar/top.sls`ファイルを編集してください:

----
base:
  'minionid':
    - localrepos
----

`/srv/pillar/localrepos.sls`ファイルを編集してください:

----
mgr_disable_local_repos: False
----

クライアントがオンボードを完了した後、ローカルリポジトリを次の場所に追加できます。

[[local-repo-locations]]
[cols="1,1", options="header"]
.ローカルリポジトリの場所
|===

ifeval::[{mlm-content} == true]
| クライアントオペレーティングシステム | ローカルリポジトリディレクトリ
| {sles} | `/etc/zypp/repos.d`
| {opensuse} | `/etc/zypp/repos.d`
| {sles} {es} | `/etc/yum.repos.d/`
| {rhel}および類似の派生物 | `/etc/yum.repos.d/`
| {ubuntu} | `/etc/apt/sources.list.d/`
| {debian} | `/etc/apt/sources.list.d/`
endif::[]


// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{uyuni-content} == true]
| クライアントオペレーティングシステム | ローカルリポジトリディレクトリ
| {sles} | `/etc/zypp/repos.d`
| {opensuse} | `/etc/zypp/repos.d`
| {rhel}および類似の派生物 | `/etc/yum.repos.d/`
| {ubuntu} | `/etc/apt/sources.list.d/`
| {debian} | `/etc/apt/sources.list.d/`
endif::[]

|===
