[[system-locking]]
= システムのロック
:description: システムロックを使用してクライアントでのアクションを防ぐ方法を学び、ソフトウェアパッケージのセキュリティ強化のためのパッケージロックの利点を発見してください。
:revdate: 2024-11-21
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

システムロックは、クライアントでのアクションを防ぐために使用されます。
例えば、システムロックはクライアントの更新や再起動を防ぎます。
これは、運用ソフトウェアを実行しているクライアントや、偶発的な変更を防ぐために便利です。
アクションを実行する準備ができたら、システムロックを無効にできます。



== クライアントのシステムのロック


クライアントがロックされている場合、またはブラックアウトモードに入っている場合、アクションのスケジュールはできず、実行コマンドが無効化され、`System Details`ページに黄色のバナーが表示されます。
このモードでは、ロックされたクライアントに対して{webui}またはAPIを使用してアクションをスケジュールできますが、アクションは失敗します。


[NOTE]
====
ロックメカニズムは{salt} SSHクライアントでは使用できません。
====



.プロシージャ:クライアントのシステムロック
. {productname} {webui}で、ロックしたいクライアントの`System Details`ページに移動します。
. `Formulas`タブに移動し、システムロックのフォーミュラにチェックを付け、btn:[保存]をクリックします。
. menu:Formulas[System Lock]タブに移動し、`Lock system`にチェックを付け、btn:[保存]をクリックします。
    このページでは、クライアントがロックされているときに特定のSaltモジュールを有効にすることもできます。
. 変更した場合、highstateを適用する必要がある場合があります。
    この場合、{webui}にバナーが表示されます。
    システムロックのフォーミュラを削除するまで、クライアントはロックされたままです。

{salt}のブラックアウトモードに関する詳細は、 https://docs.saltproject.io/en/latest/topics/blackout.を参照してください。



== パッケージのロック

パッケージロックは複数のクライアントで使用できますが、異なる機能セットが利用可能です。
{sle}と{opensuse}（zyppベース）と{rhel}または{debian}クライアントを区別する必要があります。



=== Zyppベースのシステムでのパッケージのロック

パッケージロックは、ソフトウェアパッケージへの不正なインストールやアップグレードを防ぐために使用されます。
パッケージがロックされると、インストールできないことを示す鍵のアイコンが表示されます。
ロックされたパッケージをインストールしようとすると、イベントログにエラーとして報告されます。

ロックされたパッケージは、{productname} {webui}を通じても、クライアントマシン上でパッケージマネージャを使用しても、インストール、アップグレード、または削除することはできません。
ロックされたパッケージは、依存するパッケージも間接的にロックします。


.プロシージャ:パッケージロックの使用
. 管理対象システムでmenu:ソフトウェア[パッケージ> ロック]タブに移動し、使用できるパッケージの一覧を表示します。
. ロックするパッケージを選択し、btn:[ロックをリクエスト]をクリックします。
  ロックが有効になる日付と時間を選択します。
  デフォルトでは、ロックはできるだけ早く有効になります。
  ロックがすぐに有効にならない場合があることに注意してください。
. パッケージロックを削除するには、ロック解除するパッケージを選択し、btn:[ロック解除をリクエスト]をクリックします。
  ロックを有効にする際と同様に、日付と時間を選択します。



=== {rhel}-および{debian}-のようなシステムにおけるパッケージロック

[NOTE]
====
一部の{rhel}-および{debian}-のようなシステムでは、クライアントでパッケージのロックを使用できます。
====

{rhel}-および{debian}-のようなシステムでは、パッケージロックはソフトウェアパッケージの不正なアップグレードや削除を防ぐためにのみ使用されます。
パッケージがロックされると、変更できないことを示す鍵のアイコンが表示されます。
ロックされたパッケージを変更しようとすると、イベントログにエラーとして報告されます。

ロックされたパッケージは、{productname} {webui}を通じても、クライアントマシン上でパッケージマネージャを使用しても、アップグレードまたは削除することはできません。
ロックされたパッケージは、依存するパッケージも間接的にロックします。


.プロシージャ:パッケージロックの使用
. {rhel} 7システムでは`yum-plugin-versionlock`をインストールし、{rhel} 8または9システムでは`python3-dnf-plugin-versionlock`を`root`としてインストールします。
  {debian}システムでは、`apt`ツールにロック機能が含まれています。
. 管理対象システムでmenu:ソフトウェア[パッケージ> ロック]タブに移動し、使用できるパッケージの一覧を表示します。
. ロックするパッケージを選択し、btn:[ロックをリクエスト]をクリックします。
  ロックが有効になる日付と時間を選択します。
  デフォルトでは、ロックはできるだけ早く有効になります。
  ロックがすぐに有効にならない場合があることに注意してください。
. パッケージロックを削除するには、ロック解除するパッケージを選択し、btn:[ロック解除をリクエスト]をクリックします。
  ロックを有効にする際と同様に、日付と時間を選択します。
