[[virt-vhm]]
= 仮想ホストマネージャ
:description: 仮想ホストマネージャーを使用して仮想化クライアントを収集および整理し、Taskomaticがデータを収集してクラウドインスタンスを管理できるようにします。
:revdate: 2026-08-06
:page-revdate: {revdate}

仮想ホストマネージャ(VHM)は、さまざまなクライアントの種類から情報を収集するために使用します。

VHMsは、プライベートまたはパブリッククラウドインスタンスを収集し、それらを仮想化グループに整理するために使用できます。
このように整理された仮想化クライアントを使用すると、Taskomaticはクライアントのデータを収集し、{productname} {webui}に表示します。
VHMsは、仮想化クライアントでサブスクリプションマッチングを使用することも可能です。

{productname}サーバー上にVHMを作成し、利用可能なパブリッククラウドインスタンスのインベントリを作成するために使用できます。
また、{kube}で作成されたクラスターを管理するためにVHMを使用することもできます。

* Amazon Web ServicesでVHMを使用する方法についての詳細は、xref:client-configuration:vhm-aws.adoc[]を参照してください。
* Microsoft AzureでVHMを使用する方法についての詳細は、xref:client-configuration:vhm-azure.adoc[]を参照してください。
* NutanixでVHMを使用する方法についての詳細は、xref:client-configuration:vhm-nutanix.adoc[]を参照してください。
* VMWare vSphereでVHMを使用する方法についての詳細は、xref:client-configuration:vhm-vmware.adoc[]を参照してください。
* 他のホストでVHMを使用する方法についての詳細は、xref:client-configuration:vhm-file.adoc[]を参照してください。


== ハイパーバイザーへの直接クエリ

ハイパーバイザー（KVMなど）として機能する登録済みの物理Linuxクライアントには、仮想ホストマネージャー（VHM）の設定は必要ありません。代わりに、登録済みの物理ホストに`Virtualization Host` アドオンシステムタイプが割り当てられている場合、{productname}は`libvirt`を使用してシステムに直接クエリを実行し、仮想マシンのデータを収集します。

[NOTE]
====
ハイパーバイザーがSaltバンドル（`venv-salt-minion`）を使用して管理されている場合は、必要なセットアップについてxref:client-configuration:contact-methods-saltbundle.adoc#contact-methods-saltbundle-virt[Saltバンドル内でのSaltの「virt」モジュールの可用性]を参照してください。
====

詳細については、xref:client-configuration:system-types.adoc[]を参照してください。
