= Public Cloud Listings
:availability: AWS & Azure
:sectnums!:
:lastupdate: October 2023
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

**Last updated:** {lastupdate}

== What is the {productname} {payg} listing on the cloud marketplaces?

By selecting the {productname} {payg} listing from the cloud marketplace, customers can deploy {productname} to their cloud environment with the advantage of having monthly billing via the cloud provider.

Customers still have the option of using {productname} {byos} ({byoslongform}), for which subscriptions and billing is handled directly by {suse}.


== Where do I find the {productname} {payg} listings?

The listings can be found in the {availability} Marketplaces. 
There are two listings:

On the {aws} Marketplace, you will find the following:

* {productname} Server Family (Non-EU and non-UK only)
* {productname} Server Family (EU and UK only)

On the {azure} Marketplace, you will find:

* {productname} with 24x7 Support
* {productname} with 24x7 Support (EMEA Orders Only)

For the purposes of this FAQ, we will refer to these listings as {productname} {payg}.


== Why are there 2 listings and which one should I use?

We have 2 listings for {productname}:

* **EU and UK only / EMEA Orders Only** 
* **non-EU and non-UK only**.

You should pick the listing that reflects in which country your {availability} account gets billed.


== Are these listings available in all countries?

The {productname} {payg} listing on the cloud is not available to purchase in all countries. 
In case it is not available in your country you can still use the {byos} option.

Your billing country is based on the {availability} Account ID used to do the deployment.


You can find out more about confirming your tax location as follows:

* For Amazon Web Services, it depends on the *tax address* of the account, see link:https://aws.amazon.com/tax-help/location[Tax help based on location]

* For Microsoft Azure, it depends on the *sold to* address of the account, see link:https://learn.microsoft.com/azure/cost-management-billing/manage/change-azure-account-profile[Azure account profile]

//* For Google Cloud, it depends on the *billing country* of the account, see link:https://support.google.com/cloudidentity/answer/3530790[Google support answer]

Please see the link at the end of this FAQ for a list of countries that can and cannot transact {productname} {payg} via the cloud marketplaces.


== My cloud account is in the USA, but I want to deploy {productname} {payg} in another region, a region that is in a country where I currently cannot transact, is this possible?

If your cloud provider account is billed to one of the allowed countries, it is possible to deploy {productname} in any region.


== Is this listing available in China?

It is not possible to transact/bill {productname} {payg} via {availability} Marketplaces in China. 
It is possible to deploy into regions in China.

This means you can deploy {productname} in a region in China if your billing is performed in a country that has the {payg} option available. 
Please see the addendum at the end of this FAQ for a list of countries that can and cannot transact {productname} {payg} via the cloud.


== Is there still a {byos} listing for {productname} in the marketplace?

Yes, for customers that wish to use an existing annual {productname} subscription, the {byos} {productname} listing is available.


== Is there a {payg} listing available for the {productname} Proxy Server?

If a {productname} Proxy is required as part of the architecture, it is suggested to use the containerized proxy.
See the SUSE documentation at:
link:https://documentation.suse.com[documentation.suse.com]

menu:Select[{productname} > {productname} {{productnumber}} > Installation and Upgrade guide > Installation > {productname} Proxy > Install Containerized Proxy] 

From the subscription point of view, {productname} Proxy is a managed client.


== The listing shows pricing information for {productname} node management and a separate price for monitoring. Do I need to subscribe twice if I need monitoring?

There is no need to subscribe twice. 
Subscribing to the listing in the cloud provider marketplace allow the {productname} {payg} instance to perform metered billing for {productname} usage.

If you onboard an instance and enable {productname} monitoring, there is a monthly charge for management and another charge for monitoring.
