= Billing - Products
:availability: AWS & Azure
:sectnums!:
:lastupdate: October 2023

== How do I migrate an existing {productname} {byos} instance to the {payg} - {payglongform} version?

Currently, it is *not possible* to migrate an existing instance to the {payg} version.

Customers can simply deploy a new {productname} {payg} instance from the Cloud Marketplace and re-onboard all instances using the standard process.

link:https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/client-config-overview.html[Client configuration overview]

== How do I get support?

It is simple to open a support case with SUSE for {productname} {payg}.

Create a ‘supportconfig’ via {productname} {payg} instance CLI and upload the output to the SUSE Customer Center (SCC) at the following link:

https://scc.suse.com/cloudsupport

Providing Marketplace billing is active, a support case will be opened.

== Are there any differences between the {productname} {payg} product on the Cloud Marketplaces compared to the versions I can run in my own data center?

The {productname} {payg} product available in the Cloud Marketplace is the same product, with similar functionality that you would run on-premises or with a manual installation.

The only exceptions being the ability to bill via the Cloud Marketplace and connect to the SUSE Update Infrastructure for {productname} product updates.

It is also worth checking the list of supported client operating systems to ensure your needs are met.

== Does the {productname} {payg} instance need to run 24/7?

It is recommended that the {productname} instance always remains active.

== How do I get fixes and updates for {productname} {payg}, do I need a subscription key?

{productname} {payg}, when deployed via the Cloud Marketplace will automatically connect to the SUSE Update Infrastructure, no separate {productname} Subscription Key is required.

Updates to the {productname} instance can be applied from those channels using standard SUSE tooling (i.e. zypper).

== Is the use of {productname} Hub supported with this listing?

Yes, {productname} Hub is recommended for customer with more than 10,000 managed clients. If the {productname} Hub instance has no connected clients, there will be no charge for the {productname} software components / Hub etc.

Billing will occur from the downstream {productname} {payg} instance, where managed instances are connected.

== Can I manage {byoslongform} - {byos} SLES instances in the Cloud with {productname} {payg}?

To manage BYOS instances, SCC credentials with entitlement to valid SLES or SLES for SAP subscriptions will be required. These credentials should be added to the {productname} configuration to enable this functionality.

== I have a hybrid setup; can I manage instances (workloads) outside of the cloud?

Yes, it is possible to manage instances, in the cloud, on premises or both.

To enable management of SUSE workloads in an on-premises data center, SCC credentials with entitlement to valid SLES or SLES for SAP subscriptions will be required.

These credentials should be added to the {productname} configuration to enable this functionality.

[NOTE]
====
 Egress data charges may apply when managing workloads outside of the Cloud Provider's network.
====

== Are there additional charges for using a {productname} Proxy?

With a hybrid landscape, egress data charges may apply when managing workloads outside of the Cloud Provider. To reduce these costs, SUSE recommend the use of the containerized proxy.

Please note: Whilst the SUSE Manger Proxy usage is included as part of the {productname} {payg} subscription, an LCM+ subscription will be billed if the proxy is also a managed workload, so in other words it counted as a managed client.

== Can I have a {productname} {payg} Server on premises and bill via the Cloud Marketplace.

No, to benefit from Cloud Marketplace billing, the {productname} {payg} instance must reside on the Cloud. Any {productname} instances on premises will require their own subscriptions.

== What client Operating Systems are Supported with {productname} {payg}?
Please refer to the product documentation for a full list of supported clients.
link:https://documentation.suse.com/suma/4.3/ja/suse-manager/specialized-guides/public-cloud-guide/payg/payg-overview.html[{payg} Overview]