[[ref-systems-menu]]
= Systems Menu
:revdate: 2025-05-20
:page-revdate: {revdate}

The `Systems` section allows you to manage your client systems.

The menu:Systems[] menu contains submenu entries in the left navigation bar and as its overview page displays the menu:Systems[System List > All] listing with all client systems registered to the {productname} Server.

This listing contains information about the clients, including available software updates, extra packages (otherwise often referenced as non-compliant packages), and the base channel they are subscribed to.














All the submenu entries:

* `System List`          - xref:reference:systems/systems-list.adoc[]
* `System Groups`	    - xref:reference:systems/system-groups.adoc[]
* `System Set Manager`   - xref:reference:systems/ssm-menu.adoc[]
* `Bootstrapping`	    - xref:reference:systems/bootstrapping.adoc[]
* `Proxy Configuration`  - xref:reference:systems/proxy-configuration.adoc[]
* `Advanced Search`	    - xref:reference:systems/advanced-search.adoc[]
* `Activation Keys`	    - xref:reference:systems/activation-keys.adoc[]
* `Stored Profiles`	    - xref:reference:systems/stored-profiles.adoc[]
* `Custom System Info`   - xref:reference:systems/custom-system-info.adoc[]
* `Autoinstallation`	    - xref:reference:systems/autoinst-menu.adoc[]
* `Virtual Host Managers` - xref:reference:systems/virtual-host-managers.adoc[]


Click the name of a client to go to that client system's `Details` overview page and all its tabs and subtabs.
For more information about the `System Details` overview page in the {webui}, see xref:reference:systems/system-details/sd-details.adoc[].


Check a client to add it to the system set manager.
For more information about the system set manager, see xref:client-configuration:system-set-manager.adoc[].

Click btn:[Add Systems] to go to menu:Systems[Bootstrapping].
For more about bootstrapping new clients, see xref:reference:systems/bootstrapping.adoc[].

ifeval::[{mlm-content} == true]

For more information about managing clients, see xref:client-configuration:client-config-overview.adoc[].
endif::[]

ifeval::[{uyuni-content} == true]

For more information about managing clients, see xref:client-configuration:uyuni-client-config-overview.adoc[].
endif::[]
