= {productname} Server Upgrade

Before running the upgrade command, it is recommended to to update the host operating system.
Updating the host operating system will also result in the update of the {productname} tooling such as the [literal]``mgradm`` tool.

.Procedure: Upgrading {productname} Server

. Refresh software repositories with [command]``zypper``:

+

[source,shell]
----
zypper ref
----

. Depending on the host operating system, proceed with these steps:

+

For a transactional system such as {sl-micro}: ::

+

--

Apply available updates with [command]``transactional-update``:

[source,shell]
----
transactional-update
----

--

+

For {sles}: ::

+

--

Update installed software with [command]``zypper``:

[source,shell]
----
zypper up
----

--

+

// FIXME / question
// Or rebooting only on SL Micro after transactional-update? If yes, I'll
// move it there.
+
. If updates were applied, [literal]``reboot``.

. The {productname} Server container can be updated using the following command:

+

[source,shell]
----
mgradm upgrade podman
----

+

This command will bring the status of the container up-to-date and restart the server.



.Upgrading to specific version
[NOTE]
====
If you do not specify the tag parameter, it will default to upgrading to the most recent version.
To upgrade to a specific version, provide the tag parameter with the desired image tag.
====

For more information on the upgrade command and its parameters, use the following command:

[source,shell]
----
mgradm upgrade podman -h
----


For air-gapped installations, first upgrade the container RPM packages, then run the [literal]``mgradm`` command.
