= {productname} Server Upgrade

// FIXME: Shouldn't we better say:
//        "... to upgrade the host operating system first."
//        or, maybe:
//        "... to upgrade the host operating system and especially the
//         [literal]``mgradm`` tool first."

Before running the upgrade command, it is recommended to upgrade the [literal]``mgradm`` tool first.

.Procedure: Upgrading Server
. Refresh software repository with [command]``zypper``:

+

[source,shell]
----
zypper ref
----

. Depending on the host operating system, proceed with these steps:

+

On a transactional system such as {sl-micro} or {leapmicro}::

+

--

.. Apply available updates with [command]``transactional-update``:

+

[source,shell]
----
transactional-update
----

--


On {sles} or {leap}::

+

--

.. Update installed software with [command]``zypper``:

+

[source,shell]
----
zypper up
----

--

+

. If updates were applied, [literal]``reboot``.


. The {productname} Server container can be updated using the following command:

+

[source,shell]
----
mgradm upgrade podman
----

+

This command will bring the status of the container up-to-date and restart the server.



.Upgrading to specific version
[NOTE]
====
If you do not specify the tag parameter, it will default to upgrading to the most recent version.
To upgrade to a specific version, provide the tag parameter with the desired image tag.
====

For more information on the upgrade command and its parameters, use the following command:

----
mgradm upgrade podman -h
----


For air-gapped installations, first upgrade the container RPM packages, then run the [literal]``mgradm`` command.
