= {productname} {leapmicro}에서의 서버 배포 {microversion}
:description: Podman을 사용하여 SUSE Multi-Linux Manager 서버를 컨테이너로 배포하고 Uyuni 유틸리티를 사용하는 방법을 배웁니다.
:revdate: 2025-07-09
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1
ifeval::[{mlm-content} == true]

:noindex:
endif::[]


== 배포 준비


이 섹션에서는 {productname} 서버를 설정 및 배포하는 전문 지식을 습득하게 됩니다.
이 프로세스에는 `Podman`, `Uyuni container utilities` 설치, 배포, 그리고 `mgrctl`을(를) 통해 컨테이너와의 상호 작용을 시작하는 과정이 포함됩니다.

[NOTE]
====
이 섹션에서는 물리적 머신에서 실행 중이든 가상 환경 내에서 실행 중이든 {leapmicro} {microversion} 호스트 서버를 이미 구성한 것으로 가정합니다.

https://download.opensuse.org/distribution/leap-micro/
====


== 컨테이너 호스트 일반 요구사항

일반 요구사항은 xref:installation-and-upgrade:general-requirements.adoc[일반 요구사항]을 참조하십시오.

{leapmicro} {microversion} 서버는 설치 미디어에서 설치해야 합니다. 

https://download.opensuse.org/distribution/leap-micro/

이 절차는 아래에 설명되어 있습니다.

[[installation-server-containers-requirements]]
== 컨테이너 호스트 요구사항

CPU, RAM 및 스토리지 요구 사항은 xref:installation-and-upgrade:hardware-requirements.adoc[하드웨어 요구사항]을 참조하십시오.


[IMPORTANT]
====
클라이언트가 FQDN 도메인 이름을 확인할 수 있도록 보장하려면, 컨테이너화된 서버와 호스트 머신들 모두 정상적으로 동작하는 DNS 서버에 연결되어야 합니다. 또한, 역 조회의 올바른 구성을 보장하는 것이 필수적입니다.
====


== 컨테이너와 함께 사용하기 위한 Uyuni 도구 설치


.절차 {leapmicro} {microversion}에 Uyuni 도구 설치하기
. 로컬 호스트에서 터미널 창을 열거나 {leapmicro} {microversion}을(를) 실행하는 가상 머신을 시작합니다.
. 루트로 로그인합니다.
. `transactional-update shell`을(를) 입력하십시오:
+
----
transactional-update shell
----
+
. 다음 리포지토리를 {leapmicro} {microversion} 서버에 추가하십시오:
+
----
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-$(arch)-Media1/ uyuni-server-stable
----
+
. 리포지토리 목록을 새로 고치고 키를 수락합니다.
+
----
zypper ref
----
+
. 컨테이너 도구를 설치합니다.
+
[source, shell]
----
zypper in mgradm mgrctl mgradm-bash-completion mgrctl-bash-completion uyuni-storage-setup-server
----
+
. 트랜잭션 셸을 종료합니다.
+
----
transactional update # exit
----
. 호스트를 재부팅합니다.

Uyuni 컨테이너 유틸리티에 대한 자세한 내용은 link:https://build.opensuse.org/repositories/systemsmanagement:Uyuni:Stable:ContainerUtils[Uyuni 컨테이너 유틸리티]를 참조하십시오.


== 사용자 정의 영구 스토리지 구성

이 단계는 선택 사항입니다.
그러나 인프라에 사용자 정의 영구 스토리지가 필요한 경우 `mgr-storage-server` 도구를 사용하십시오. 

* 자세한 내용은 `mgr-storage-server --help`을 참조하십시오.
자세한 내용은 [command]\``mgr-storage-server \--help``를 참조하십시오.  이 도구는 컨테이너 스토리지 및 데이터베이스 볼륨 생성을 간소화합니다.

다음 방법으로 명령 사용: 
----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----

예: 
----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----

[NOTE]
====
이 명령은 `/var/lib/containers/storage/volumes`에 영구 스토리지 볼륨을 생성합니다.

자세한 내용은 xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]을 참조하십시오.
====


== Podman을 사용하여 Uyuni 컨테이너 배포

=== `mgradm` 개요

{productname}은(는) `mgradm` 도구를 사용하여 컨테이너로 배포됩니다.
{productname} 서버를 컨테이너로 배포하는 방법은 두 가지가 있습니다. 
이 섹션에서는 기본 컨테이너 배포에 중점을 두겠습니다.

배포를 위해 사용자 정의 구성 파일을 사용하는 방법에 대한 정보는 xref:installation-and-upgrade:container-management/mgradm-yaml-custom-configuration.adoc[]을 참조하십시오.

자세한 내용은 명령줄에서 `mgradm --help`을(를) 실행하여 확인할 수 있습니다.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
endif::[]

.절차 Podman을 사용하여 Uyuni 컨테이너 배포
. 터미널에서 sudo 사용자 또는 루트로 다음 명령을 실행합니다.
+
[source, shell]
----
sudo mgradm install podman
----
+
[IMPORTANT]
====
컨테이너를 sudo 또는 루트 사용자로 배포해야 합니다. 이 단계를 놓치면 터미널에 다음과 같은 오류가 표시됩니다.

[source, shell]
----
INF Setting up uyuni network
9:58AM INF Enabling system service
9:58AM FTL Failed to open /etc/systemd/system/uyuni-server.service for writing error="open /etc/systemd/system/uyuni-server.service: permission denied"
----
====

. 배포가 완료될 때까지 기다립니다.
. 브라우저를 열고 서버 FQDN으로 이동합니다.

//In this section you learned how to deploy an {productname} Server container.



=== 영구 볼륨

많은 사용자가 영구 볼륨의 위치를 지정하기를 원할 것입니다.

[NOTE]
====
{productname}을(를) 테스트하는 경우에는 이러한 볼륨을 지정할 필요가 없습니다. `mgradm`은(는) 기본적으로 올바른 볼륨을 설정합니다.

볼륨 위치 지정은 일반적으로 대규모 프로덕션 배포에서 사용됩니다.
====

기본적으로 `podman`은(는) 볼륨을 `/var/lib/containers/storage/volumes/`에 저장합니다. 

이 경로 또는 그 안의 예상 볼륨 경로에 디스크를 마운트하여 볼륨에 대한 사용자 지정 저장소를 제공할 수 있습니다: `/var/lib/containers/storage/volumes/var-spacewalk`. 
이는 데이터베이스 및 패키지 미러에 특히 중요합니다. 

컨테이너의 모든 영구 볼륨 목록은 다음을 참조:

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]


