[[quickstart-publiccloud-clm]]
= Správa životního cyklu obsahu

Správa životního cyklu obsahu umožňuje přizpůsobit úložiště a otestovat balíčky před aktualizací produkčních klientů. To je zvláště užitečné, pokud potřebujete instalovat aktualizace během (časového) okna s omezenou údržbou.

Toho je dosaženo prostřednictvím řady prostředí, kterými se mohou vaše softwarové kanály během svého životního cyklu pohybovat. Většina životních cyklů prostředí zahrnuje alespoň testovací a produkční prostředí, ale můžete mít tolik prostředí, kolik potřebujete.

Když jste vytvořili svůj projekt, definovaná prostředí a připojené zdroje a filtry, můžete projekt poprvé sestavit. Další informace o správě životního cyklu obsahu najdete v dokumentu xref:administration:content-lifecycle.adoc[].

Když je váš projekt úspěšně vytvořen, musíte přidat nový kanál do aktivačního klíče. Další informace o vlastních kanálech najdete v dokumentu xref:administration:custom-channels.adoc[].



.Postup: Vytvoření projektu životního cyklu obsahu

Přejděte do menu:Lifecycle[Projects] (Životní cyklus [Projekty]), vytvořte projekt a přiřaďte mu štítek a název. Poté použijte btn:[Attach/Detach Sources] (Připojit/odpojit prostředky) k připojení základního kanálu a podřízených kanálů a nakonec vše uložte.

Nyní můžete použít btn:[Attach/Detach Filters] (Připojit/Odpojit filtry) a doladit, jaké balíčky zahrnout do výsledného kanálu. K dispozici je řada filtrů: název, datum, přehled, je-li nutný restart, či nikoli atd.

V tomto okamžiku můžete definovat svá prostředí kliknutím na btn:[Add Environment] (Přidat prostředí) v dialogovém okně [guimenu]``Environment Lifecycle`` (Prostředí životního cyklu). Testovací prostředí a provozní prostředí jsou obvykle minimum, které má většina zákazníků, ale možná budete potřebovat více. Pokračujte ve vytváření prostředí, dokud nebudete mít dokončena všechna prostředí pro životní cyklus svého produktu.

Posledním krokem je vytvoření projektu, což chvíli trvá.


Další informace o správě životního cyklu obsahu, včetně vypracovaných příkladů, najdete v dokumentu xref:administration:content-lifecycle.adoc[].
