[[quickstart-publiccloud-install]]
= Instalace

Veřejné cloudy poskytují {productname} v rámci modelu Bring Your Own Subscription (BYOS). To znamená, že předinstalují {productname}, takže nemusíte provádět žádné kroky instalace. Než se však budete moci přihlásit, je třeba server {productname} zaregistrovat u {scc}, abyste dostávali aktualizace.


Postupujte podle pokynů poskytovatelů cloudu k SSH do instance.

Nastavení spustíte tímto příkazem:

----
yast2 susemanager_setup
----

Postupujte podle pokynů a vyčkejte dokončení instalace.

Podrobné pokyny k nastavení {productname} nástrojem {yast} najdete na stránce xref:installation:server-setup.adoc[].

Zaregistrujte svou instanci u {scc} tímto příkazem jako root a zadejte registrační číslo a emailovou adresu, která je s ním spojena:

----
SUSEConnect -r <Registration_Number> -e <registered_email_address>
----

Registrační číslo můžete získat po přihlášení do {scc} ze svého prohlížeče.

Další informace o registraci {productname} u {scc} najdete na xref:installation:general-requirements.adoc [].

Po registraci jsou aktivovány všechny moduly {sle}. Musíte také aktivovat modul Public Cloud. Udělejte to z příkazového řádku ve vaší instanci:

----
SUSEConnect -p sle-module-public-cloud/15.2/x86_64
----

Další informace o aktivaci veřejných cloudů viz xref:installation:pubcloud-setup.adoc[].


Otevřete {productname} {webui} webovým prohlížečem z adresy tohoto typu:

----
https://<veřejná_IP>
----

Přihlaste se k účtu {productname} {webui} pomocí účtu správce. Uživatelské jméno a heslo se liší v závislosti na poskytovateli.

.Podrobnosti výchozího účtu správce
[cols="1,1,1", options="header"]
|===
| Poskytovatel          | Výchozí uživ.jméno | Výchozí heslo
| Amazon EC2            | ``admin``         | ``<ID-instance>``
| Google Compute Engine | ``admin``         | ``<ID-instance>``
| Microsoft Azure       | ``admin``         |``<název-instance>-suma``
|===


Když se poprvé přihlásíte k účtu správce, dostanete automaticky generovaný název organizace. Změňte to tak, že přejdete do menu:Admin[Organizations] (Správce [Organizací]) a upravíte název organizace.


[IMPORTANT]
====
Po prvním přihlášení k účtu správce změňte výchozí heslo, aby byl váš účet chráněn.
====

Další informace o nastavení serveru {productname} viz xref:installation:server-setup.adoc[].


Pomocí {productname} {webui} přidejte požadované softwarové produkty a naplánujte synchronizaci úložiště. Nejlepším způsobem je přejít do menu:Admin[Setup Wizard] (Správce[Průvodce nastavením]) a postupovat podle pokynů.

Další informace o průvodci nastavením viz xref:installation:setup-wizard.adoc[].


Máte-li v úmyslu zaregistrovat klienty {ubuntu} nebo {rhel}, musíte nastavit vlastní úložiště a kanály. Další informace viz příslušnou sekci xref:client-configuration:registration-overview.adoc[].


Chcete-li synchronizovat kanály, přejděte do menu:Software[Manage > Channels] (Software [Správa> Kanály]). Klikněte na každý kanál, který jste vytvořili, přejděte do záložky menu:Repositories[Sync] (Úložiště[Synchronizace]) a stiskněte btn:[Sync Now] (Synchronizuj teď). Na této obrazovce můžete také synchronizaci naplánovat.


[IMPORTANT]
====
Před zavedením klienta se ujistěte, že jsou synchronizovány všechny vybrané kanály pro daný produkt.

Synchronizace může někdy trvat několik hodin, zejména u kanálů openSUSE, SLES ES a RHEL.
====
