[[troubleshooting-]]
= 전체 디스크 이벤트 포함 컨테이너 문제 해결
:description: 컨테이너에서 디스크가 가득 찬 이벤트를 해결하려면 저장 매체의 크기를 조정하기 위해 다음 단계를 따르십시오.
:revdate: 2025-03-10
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1



////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

컨테이너의 영구 스토리지 매체로 마운트된 전용 디스크의 스토리지 공간이 부족할 경우 긴급 조치가 필요합니다.

스토리지 미디어 크기 조정 문제를 해결하려면 다음을 수행합니다.
컨테이너 호스트에서 모든 나열된 명령을 `root` 권한으로 실행하십시오.

.절차 저장 매체 크기 조정

. 디스크 크기를 늘리십시오.
  취해야 할 조치는 설치 시나리오에 따라 다릅니다.

. 디스크가 파티션된 경우(예: `/dev/vdb1` 디스크 `/dev/vdb`에 대해 이(가) 있는 경우) 다음 명령을 실행하십시오:

+

다음 명령을 실행합니다.

+

--
.. `parted /dev/vdb`
.. `(parted)` `print`
.. `(parted)` `resizepart NUMBER 100%` (여기서 `NUMBER`은(는) `print` 명령에 의해 표시된 파티션 번호입니다(예: `1`인 경우 `/dev/vdb1`))
.. `(parted)` `quit`
--

. 파일 시스템의 크기를 조정하십시오.
  예를 들어, XFS 파일 시스템의 경우 다음 명령을 실행하십시오:

+

[source,shell]
----
xfs_growfs /dev/vdb1
----

절차를 완료하면 XFS 파일 시스템이 디스크에서 사용 가능한 모든 공간을 사용하고 있어야 합니다.
