[[troubleshooting-btrfs]]
= BTRFS 크기 조정
:revdate: 2026-05-13
:page-revdate: {revdate}


== 에서 BTRFS LVM 파티션 크기 조정하기{sles}

{sles} 설치를 관리할 때, BTRFS 루트 파일 시스템은 파일, 캐시 또는 스냅샷으로 인해 가득 찰 수 있습니다.
스냅샷을 수동으로 제거하는 것은 권장되지 않으므로, 가장 좋은 방법은 파티션의 크기를 조정하는 것입니다.

[NOTE]
====
BTRFS 파티션의 크기를 조정하려면, 이 절차 동안 파티션이 마운트된 상태를 유지해야 합니다.
====

다음 단계는 새로운 디스크(예: `/dev/sdb`)를 볼륨 그룹에 추가하여 BTRFS LVM 파티션의 크기를 조정하는 방법을 설명합니다.

.절차 BTRFS LVM 파티션 크기 조정하기*
[role=procedure]
____
. 루트 파일 시스템 장치와 새 디스크를 식별하기 위해 `lsblk` 명령으로 디스크 정보를 확인합니다:

+

[source,bash]
----
lsblk
----

. 새로 추가된 디스크에 물리적 볼륨을 생성합니다:

+

[source,bash]
----
pvcreate /dev/sdb
----

. 루트 파일 시스템이 사용하는 현재 볼륨 그룹을 스캔합니다:

+

[source,bash]
----
vgscan
----

. 새로 생성된 물리적 볼륨으로 볼륨 그룹을 확장합니다:

+

[source,bash]
----
vgextend system /dev/sdb
----

. 확장된 볼륨 그룹을 사용하여 논리 볼륨을 확장합니다:

+

[source,bash]
----
lvextend -l +100%FREE /dev/system/root
----

. BTRFS 루트 파일 시스템의 크기를 조정합니다:

+

[source,bash]
----
btrfs filesystem resize max /
----

. 결과를 확인하여 시스템의 루트 파일 시스템이 새 용량으로 성공적으로 조정되었는지 확인합니다:

+

[source,bash]
----
lsblk
----
____





== 에서 BTRFS 루트 볼륨 크기 조정하기{sl-micro}

{sle-micro} 5.5 또는 {sl-micro} 6 설치를 관리할 때, BTRFS 루트 볼륨이 디스크 공간이 부족해져 크기 조정이 필요할 수 있습니다. 

표준 명령 `btrfs fi resize max /`를 사용하여 루트 볼륨의 크기를 조정하려고 하면 다음과 같은 오류가 발생합니다:

[source,bash]
----
ERROR: unable to resize '/': Read-only file system
----

이는 루트 볼륨이 {sle-micro} 시스템에서 읽기 전용으로 마운트되어 있기 때문에 발생합니다. 
작업을 온라인으로 성공적으로 완료하려면, 대신 읽기-쓰기 모드로 마운트된 `/.snapshots` 탑재 지점을 대상으로 해야 합니다.

[WARNING]
====
파티션 테이블에 대한 변경은 시스템에 손상을 초래할 수 있습니다. 

파티션 테이블에 변경을 가하기 전에 항상 완전한 백업을 확보해야 합니다.
====

다음 절차는 루트 파티션이 장치의 마지막 파티션인 단일 디스크의 크기를 조정하는 방법을 설명합니다(예: `/dev/sda3`). 
레이아웃에 추가 파티션이 포함되어 있는 경우, 작업이 더 복잡해질 수 있으며 {scclongform}에 지원을 요청해야 할 수 있습니다.

.절차 BTRFS 루트 볼륨 크기 조정
[role=procedure]
____
. 환경에 적합한 하이퍼바이저 또는 스토리지 도구를 사용하여 기존 디스크의 크기를 새 크기로 조정합니다.

. 크기를 조정할 장치를 다시 스캔합니다.
  예를 들어, `/dev/sda`를 다시 스캔하려면, 루트 사용자로 다음 명령을 실행합니다:

+

[source,bash]
----
echo 1 > /sys/block/sda/device/rescan
----

. 명령 `growpart`를 사용하여 루트 파티션의 크기를 조정합니다. 
  이 예에서는 `/dev/sda`에서 파티션 3의 크기를 조정합니다:

+

[source,bash]
----
growpart /dev/sda 3
----

. BTRFS 파일 시스템의 크기를 조정합니다. 
  읽기 전용 오류를 피하기 위해 `/.snapshots` 대신 `/`를 사용해야 합니다:

+

[source,bash]
----
btrfs fi resize max /.snapshots
----

. 파일 시스템을 확인하여 새 크기가 성공적으로 적용되었는지 확인합니다:

+

[source,bash]
----
btrfs fi show /
----
____
