[[troubleshooting-inactive-clients]]
= 비활성 클라이언트 문제 해결
:description: 비활성 클라이언트의 문제를 해결하려면 원인을 식별하고 SUSE Multi-Linux Manager 서버와의 연결 문제를 해결하십시오.
:revdate: 2025-01-08
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

Taskomatic 작업이 주기적으로 클라이언트에 핑을 보내 연결 상태를 확인합니다.
클라이언트가 24시간 이상 Taskomatic 점검에 응답하지 않으면 비활성으로 간주됩니다.
비활성 클라이언트 목록을 보려면 {webui}에서 menu:시스템[시스템 목록> 비활성]으로 이동하십시오.

클라이언트는 여러 이유로 비활성화될 수 있습니다.

* 클라이언트는 어떠한 {productname} 서비스도 이용할 권한이 없습니다.
* HTTPS 연결을 허용하지 않는 방화벽의 후방에 클라이언트가 위치합니다.
* 클라이언트가 잘못 구성된 프록시의 후방에 위치합니다.
* 클라이언트가 다른 {productname} 서버와 통신 중이거나 연결이 잘못 구성되었습니다.
* 클라이언트가 {productname} 서버와 통신할 수 있는 네트워크에 없습니다.
* 방화벽이 클라이언트와 {productname} 서버 간의 트래픽을 차단 중입니다.
* Taskomatic이 잘못 구성되었습니다.


서버에 대한 클라이언트 연결에 대한 자세한 내용은 xref:client-configuration:contact-methods-intro.adoc[]을 참조하십시오.

포트 구성에 대한 자세한 내용은 xref:installation-and-upgrade:network-requirements.adoc#ports[]을 참조하십시오.

방화벽 문제 해결에 대한 자세한 내용은 xref:administration:troubleshooting/tshoot-firewalls.adoc[]을 참조하십시오.
