[[troubleshooting-login-timeout]]
= 로그인 시간 제한 문제 해결
:description: rhn.conf 및 web.xml 파일을 조정하고 잠재적인 원인을 파악하여 SUSE Multi-Linux Manager 웹 UI 로그인 타임아웃을 문제 해결하고 구성하는 방법을 알아봅니다.
:revdate: 2025-07-16
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

기본적으로 {productname} {webui}는 사용자가 30{nbsp}분 후에 다시 로그인하도록 요구합니다.
환경에 따라 로그인 제한 시간 값을 조정할 수 있습니다.

값을 조정하려면 `rhn.conf`와 `web.xml` 모두에서 변경해야 합니다.
`/etc/rhn/rhn.conf`에는 초 단위로, `web.xml`에는 분 단위로 값을 설정해야 합니다.
두 값은 동일한 시간으로 설정해야 합니다.

예를 들어, 타임아웃 값을 한 시간으로 변경하려면 `rhn.conf`의 값을 3600초로, `web.xml`의 값을 60분으로 설정합니다.



.절차 {webui} 로그인 타임아웃 값 조정
. 컨테이너 호스트에서, 서버 컨테이너 내의 명령줄을 엽니다.

+

[source,shell]
----
mgrctl term
----

+

--

.. `/etc/rhn/rhn.conf`를 열고 새로운 타임아웃 값을 초 단위로 포함하도록 다음 라인을 추가하거나 편집합니다:

+

----
web.session_database_lifetime = <Timeout_Value_in_Seconds>
----

.. 파일을 저장한 후 닫습니다.

.. `/etc/tomcat/web.xml`를 열고 새로운 타임아웃 값을 분 단위로 포함하도록 다음 라인을 추가하거나 편집합니다:

+

[source,xml]
----
<session-timeout>Timeout_Value_in_Minutes</session-timeout>
----

.. 파일을 저장한 후 닫습니다.

--

+

. 컨테이너 호스트에서 서버를 다시 시작하여 새 구성을 강제 적용합니다.

+

[source,shell]
----
systemctl restart uyuni-server.service
----
