[[troubleshooting-remote-root-on-micro]]
= {sl-micro}에서 원격 루트 로그인
:description: SSH 구성 파일을 편집하여 PermitRootLogin yes로 설정하고 SSH 서비스를 다시 로드함으로써 SL Micro에서 암호 기반 원격 루트 사용자 로그인을 활성화하십시오.
:revdate: 2026-04-29
:page-revdate: {revdate}

보안을 강화하기 위해 {sl-micro} 6.2 및 이후 버전의 새 설치에서는 더 이상 비밀번호 기반 원격 루트 사용자 로그인을 허용하지 않으며, 이는 {sl-micro}에서 실행 중인 서버 및 프록시 컨테이너 호스트와 관리되는 {sl-micro} 클라이언트에 영향을 미칩니다.
또한, 비밀번호 기반 원격 루트 로그인이 있는 {sle-micro} 5.5 클라이언트는 6.1/6.2로 마이그레이션될 때 이 접근 권한을 갑자기 잃게 되며, 새로 구성해야 합니다.
자세한 내용은 SL Micro 릴리스 정보 6.2(https://documentation.suse.com/releasenotes/sle-micro/html/releasenotes_sle-micro_6.2/)를 참조하십시오.

{productname}의 구성 요소(예: {productname} 프록시)를 배포할 때, 기본적으로 비밀번호 기반 원격 루트 사용자 로그인이 필요합니다.
다음 단계에 따라 비밀번호 기반 원격 루트 로그인을 활성화할 수 있습니다.


.절차 {sl-micro}에서 비밀번호를 사용하여 SSH 루트 사용자 로그인을 활성화하십시오.
[role=procedure]
____

SSH 루트 로그인을 활성화하는 방법은 두 가지가 있습니다. 
둘 중 어느 방법이든 작동합니다; 귀하의 설정에 가장 적합한 방법을 선택하십시오.

.옵션 A: 사전 구성된 패키지 사용

. 클라이언트의 UI/API에서 패키지 `openssh-server-config-rootlogin`를 설치하십시오.

. 컨테이너 호스트를 재부팅해 UI 또는 터미널에서 새 구성을 활성화합니다.

.옵션 B: SSH 구성을 수동으로 편집

. 다음 내용이 포함된 드롭인 구성 `/etc/ssh/sshd_config.d/permit_root.conf` 파일을 추가하십시오:

+

----
PermitRootLogin yes
----

. SSH 서버 구성 재로드

+

[source,shell]
----
systemctl reload sshd
----

. SSH로 연결된 경우, 서버에서 연결을 끊기 전에 새 SSH 연결을 열어 SSH 서버가 정상적으로 작동하는지 확인합니다.

____

`transactional-update`에 대한 자세한 내용은 https://documentation.suse.com/sle-micro/6.2/html/Micro-transactional-updates/index.html.를 참조하십시오.
