[[troubleshooting-corrupt-repos]]
= 손상된 리포지토리 문제 해결
:description: 캐시 디렉토리에서 손상되었거나 오래된 리포지토리 메타데이터 파일을 제거하고 이를 재생성하여 클라이언트의 올바른 업데이트를 방해하는 문제를 해결하십시오.
:revdate: 2024-11-26
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

리포지토리 메타데이터 파일의 정보가 손상되거나 오래될 수 있습니다.
이로 인해 클라이언트 업데이트에 문제가 발생할 수 있습니다.
파일들을 제거하고 재생성하여 이 문제를 해결할 수 있습니다.
새 리포지토리 데이터 파일이 있으면 업데이트가 정상적으로 작동해야 합니다.

.절차 손상된 리포지토리 데이터 문제 해결하기
. 모든 파일을 `/var/cache/rhn/repodata/<channel-label>`에서 제거하십시오.
    채널 레이블을 모르는 경우 {productname} {webui}에서 menu:소프트웨어[채널> 채널 레이블]로 이동하여 찾을 수 있습니다.
. 컨테이너 호스트의 명령줄에서 다음 명령을 실행하여 컨테이너의 파일을 다시 생성합니다.
+
----
mgrctl exec -ti -- spacecmd softwarechannel_regenerateyumcache <channel-label>
----
