[[troubleshooting-customchannel]]
= 충돌하는 패키지가 포함된 사용자 정의 채널 문제 해결
:description: YaST 도구를 사용하여 사용자 정의 채널을 생성할 때 충돌을 피하는 방법을 배우고 원활한 설치 프로세스를 보장하십시오.
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

////
Cause: Conflicting packages in custom channel
Consequence: Creating bootstrap repo can fail
Fix: Separate trees from each other
Result: Clean and functional boostrap repo will be created
////

부트스트랩 리포지토리 생성과 같은 충돌하는 패키지 기능으로 사용자 정의 채널을 설정할 때 정의되지 않은 동작이 발생하고 클라이언트 등록이 실패할 수 있습니다.

예를 들어, 더 높은 버전 번호를 가진 충돌하는 패키지가 부팅 리포지토리에 포함될 수 있습니다.
이러한 패키지(예: `python3-zmq` 또는 `zeromq`)는 부팅 리포지토리 생성을 손상시키거나 클라이언트 부팅 중에 문제를 일으킬 수 있습니다.

사용자 정의 채널(예: EPEL 채널)이 상위 공급업체 채널 아래에 추가될 때 충돌하는 패키지와 관련된 문제는 직접 해결할 수 없습니다.
이를 해결하는 방법은 사용자 정의 채널을 공급업체 채널과 분리하는 것입니다.
사용자 정의 채널은 별도의 트리에서 생성되어야 합니다.
사용자 정의 채널이 하위 채널로 제공되어야 하는 경우, 이러한 환경은 콘텐츠 라이프사이클 관리(CLM)를 사용하여 생성할 수 있습니다.
CLM 프로젝트의 소스는 서로 다른 트리에서 추가할 수 있습니다.
이러한 접근 방식을 사용하면 사용자 정의 채널이 구축된 환경 내에서 상위 채널 아래에 유지됩니다.
그러나 공급업체 채널 트리는 사용자 정의 채널과 부팅 리포지토리 없이 유지됩니다.
그런 다음 클라이언트 등록이 올바르게 작동합니다.

충돌하는 패키지(salt, zeromq 등)가 포함된 사용자 정의 채널이 하위 채널로 생성되는 경우 다음 단계를 통해 문제를 방지할 수 있습니다:

.절차 사용자 정의 채널에서 패키지 충돌 방지

. 상위 채널에서 하위 채널로서 사용자 정의 채널을 제거하십시오.
  자세한 내용은 xref:administration:custom-channels.adoc#_manage_custom_channels[]을 참조하십시오.
. 별도의 트리에서 사용자 정의 채널을 생성하십시오.
  자세한 내용은 xref:administration:custom-channels.adoc#_creating_custom_channels_and_repositories[]을 참조하십시오.
. CLM(콘텐츠 라이프사이클 관리) 내에서 사용자 정의 채널을 하위 채널로 가져오려면:
+
* {productname} {webui}에서 menu:콘텐츠 라이프사이클[]로 이동하고 btn:[Create Project]를 클릭하십시오.
  `Name` 및 `Label`을(를) 입력하십시오.
* 프로젝트에 소스를 첨부하십시오.
  필요한 공급업체 채널과 사용자 정의 채널을 사용합니다. (CentOS8을 이용한 공유 예)
* 프로젝트에 환경을 추가합니다.  예를 들어, CentOS8을 사용합니다.
* 환경을 빌드하려면 btn:[빌드] 버튼을 클릭합니다.
  이 작업은 활성화 키와 연결되고 클라이언트를 부팅하는 데 사용할 수 있는 공급업체 및 사용자 정의 채널이 포함된 환경을 생성합니다.
. 중요한 알림: CLM 프로젝트에서는 문제를 일으키거나 충돌하는 패키지를 제외하는 필터를 추가하는 것이 권장됩니다.
  그렇지 않으면 클라이언트 업데이트 시 더 높은 버전 번호를 가진 충돌하는 패키지가 설치됩니다.
  필터링에 대한 자세한 내용은 xref:administration:content-lifecycle-examples.adoc#exclude-higher-kernel-version[]을 참조하십시오.
. CLM 환경(공급업체 및 사용자 정의 채널 포함)에 최신 패치를 적용하려면 프로젝트에서 btn:[빌드] 버튼을 클릭합니다.
  이는 환경을 다시 빌드하는 데 필요합니다.

* CLM에 대한 자세한 내용은 xref:administration:content-lifecycle.adoc[]을 참조하십시오.

ifeval::[{mlm-content} == true]

[NOTE]
====
EPEL을 {rhel} 클라이언트(또는 호환: {sll}, {centos}, {oracle} 등)에서 직접 사용하면 EPEL에서 {salt} 패키지가 설치되며, 이는 {productname}에서 제공하는 {salt} 패키지에서 사용할 수 있는 일부 기능이 누락됩니다. 
이는 부팅 리포지토리에 비 SUSE {salt} 패키지가 포함되기 때문에 특히 중요합니다. 
따라서 이는 지원되지 않는 시나리오입니다.

EPEL 리포지토리를 활성화해야 하는 경우 미리 EPEL에서 {salt} 패키지를 필터링해야 합니다(예: menu:소프트웨어[관리> 채널> EPEL> 패키지]에서 {salt} 패키지를 제거하여).
====
endif::[]
