[[troubleshooting-salt-clients-down-and-dns]]
= 문제 해결 다운 및 DNS 설정으로 표시된 Salt 클라이언트
:description: Salt 클라이언트의 DNS 설정을 확인하여 올바른 이름 해석이 이루어지도록 하고, FQDN 그레인 계산 중 발생할 수 있는 지연으로 인해 클라이언트가 다운된 것으로 보이지 않도록 하십시오.
:revdate: 2024-05-15
:page-revdate: {revdate}

Salt 클라이언트가 실행 중인 경우에도 패키지 새로 고침 또는 적용 상태 등의 작업이 실패로 표시되며 다음 메시지가 표시됩니다.

----
Minion is down or could not be contacted.
----

이 경우 작업을 다시 예약해 보십시오.
재예약이 성공하면 문제의 원인은 잘못된 DNS 구성일 수 있습니다.

[IMPORTANT]
====
Server 컨테이너 내부의 셸에 접근하려면 컨테이너 호스트에서 `mgrctl term`을(를) 실행합니다.
====

Salt 클라이언트가 재시작되거나 그레인이 새로 고쳐지면 클라이언트는 FQDN 그레인을 계산하며, 그레인이 처리될 때까지 응답하지 않습니다.
{productname} 서버에서 예약된 작업이 실행될 때, {productname} 서버는 실제 작업 전에 클라이언트가 실제로 실행되고 있는지 확인하고 작업을 트리거할 수 있도록 클라이언트에 `test.ping`을(를) 수행합니다.

기본적으로 {productname} 서버는 `test.ping` 명령의 응답을 받기 위해 5초를 기다립니다.
5초 이내에 응답이 수신되지 않으면 클라이언트가 다운되었거나 연락할 수 없다는 메시지와 함께 작업이 실패로 설정됩니다.

이 문제를 해결하려면 클라이언트에서 DNS 확인을 수정하여 FQDN을 확인하는 동안 클라이언트가 5초 동안 멈추지 않도록 하십시오.

이것이 불가능한 경우, `java.salt_presence_ping_timeout` 서버의 `/etc/rhn/rhn.conf` 파일에 있는 {productname} 값을 4보다 큰 값으로 늘려 보십시오.

예:

----
mgrctl term
vim /etc/rhn/rhn.conf
java.salt_presence_ping_timeout = 6
----

이후에 다음을 실행합니다.

----
mgradm restart
----

[NOTE]
====
이 값을 증가시키면 {productname} 서버가 미니언에 연결할 수 없거나 응답하지 않는지 확인하는 데 시간이 더 오래 걸릴 수 있으므로, {productname} 서버가 전반적으로 느려지거나 응답하지 않을 수 있습니다.
====
