[[troubleshooting-login-timeout]]
= ログインタイムアウトのトラブルシューティング
:revdate: 2025-07-16
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

デフォルトでは、{productname} {webui}はユーザに30分後に再度ログインするように要求します。 環境によっては、ログインタイムアウトの値を調整したい場合があります。

値を調整するには、[path]``rhn.conf``と [path]``web.xml``の両方で変更する必要があります。 [path]``/etc/rhn/rhn.conf``で秒単位の値、[path]``web.xml``で分単位の値を設定してください。 この 2つの値は同じ時間に等しくなる必要があります。

たとえば、タイムアウト値を1時間に変更するには、[path]``rhn.conf``の値を3600秒に設定し、[path]``web.xml``の値を60分に設定します。



.プロシージャ: {webui}ログインタイムアウト値の調整
. コンテナホストで、サーバコンテナ内でコマンドラインを開きます。

+

[source, shell]
----
mgrctl term
----

+

--

.. [path]``/etc/rhn/rhn.conf``を開いて、次の行を追加または編集して、秒単位の新しいタイムアウト値を含めます。

+

----
web.session_database_lifetime = <Timeout_Value_in_Seconds>
----

.. ファイルを保存して閉じます。

.. [path]``/etc/tomcat/web.xml``を開いて、次の行を追加または編集して、分単位の新しいタイムアウト値を含めます。

+

[source, xml]
----
<session-timeout>Timeout_Value_in_Minutes</session-timeout>
----

.. ファイルを保存して閉じます。

--

+

. コンテナホストでサーバを再起動して、新しい設定を適用します。

+

[source, shell]
----
systemctl restart uyuni-server.service
----
