[[troubleshooting-rpc-timeout]]
= RPC接続タイムアウトのトラブルシューティング
:revdate: 2022-10-18
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

RPC接続は、ネットワークが低速になったり、ネットワークリンクがダウンしたりするためにタイムアウトすることがあります。 その結果、パッケージのダウンロードやバッチジョブがハングしたり予想よりも時間がかかります。 設定ファイルを編集することで、RPC接続にかかる最大時間を調整できます。 ただし、これではネットワークの問題は解決されず、プロセスがハングするのではなく失敗します。


.プロシージャ: RPC接続タイムアウトの解決

. {productname}サーバで、[filename]``/etc/rhn/rhn.conf``ファイルを開いて、最大タイムアウト値(秒単位)を設定します。

+

----
server.timeout =`number`
----

+

{productname}プロキシで、[filename]``/etc/uyuni/proxy/config.yaml``ファイルを開いて、最大タイムアウト値(秒単位)を設定します。 変更を有効にするには、プロキシコンテナを再起動する必要があります。

+

----
timeout: `number`
----

+

. zypperを使用する{sles}クライアントで、[filename]``/etc/zypp/zypp.conf``ファイルを開いて、最大タイムアウト値(秒単位)を設定します。

+

----
## Valid values:  [0,3600]
## Default value: 180
download.transfer_timeout = 180
----

+

. yumを使用する{rhel}クライアントで、[filename]``/etc/yum.conf``ファイルを開いて、最大タイムアウト値(秒単位)を設定します。

+

----
timeout =`number`
----

[NOTE]
====
RPCタイムアウトを``180``秒未満に制限する場合は、完全に正常な操作が中断されるリスクがあります。
====
