[[troubleshooting-firewalls]]
= ファイアウォールのトラブルシューティング
:revdate: 2025-02-06
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step


Cause: User firewall is set to block outgoing traffic by dropping the packet request. During sync with {scc}, mlm waits for an answer on each URL until it times out, eventually causing the entire refresh of the product list to timeout. Applies only to third party (non-SUSE) products, as sync with {scc} needs to access locations other than {scc} to verify if the if the download location is valid.

Consequence: The sync to {scc} fails, and the third party products are not shown in the product list.

Fix: Configure the firewall to reject requests from mlm instead of drop (preferred), or configure a firewall on the server (if no ability to change firewall settings)

Result: Sync to {scc} is either able to reach the URLs required, or rejects the request so that the request fails rather than times out.
////

送信トラフィックをブロックするファイアウォールを使用している場合は、``REJECT``または``DROP``のいずれかのネットワーク要求を実行できます。 ``DROP``に設定されている場合、{scclongform}との同期がタイムアウトする可能性があります。

これは、同期プロセスが{scclongform}だけではなく、{suse}以外のクライアント用のパッケージを提供するサードパーティリポジトリにアクセスする必要があるために発生します。 {productname}サーバがこれらのリポジトリに到達して有効であることを確認しようとすると、ファイアウォールは要求をドロップし、同期はタイムアウトするまで応答を待ち続けます。

これが発生する場合、同期が失敗するまで長時間かかり、{suse}以外の製品が製品リストに表示されません。

この問題はさまざまな方法で修正できます。

最も簡単な方法は、{suse}以外のリポジトリで必要なURLへのアクセスを許可するようにファイアウォールを設定することです。 これにより、同期プロセスがURLに到達し、正常に完了することができます。

外部トラフィックを許可できない場合は、{productname}からの``REJECT``(``DROP``ではない)要求を行うようにファイアウォールを設定してください。 これにより、サードパーティURLへの要求が拒否されるため、同期はタイムアウトではなく早期に失敗し、製品はリストに表示されません。

ファイアウォールへの設定アクセス権がない場合は、代わりに{productname}サーバに別のファイアウォールを設定することを検討してください。
