[[troubleshooting-mass-machineID-duplication]]
= 大量のMachine_idの重複
:revdate: 2025-10-23
:page-revdate: {revdate}

{productname}を使用して仮想マシンを管理している場合は、仮想マシンのクローンを作成すると役立つ場合があります。 クローンとは、既存のディスクの正確なコピーであるプライマリディスクを使用する仮想マシンのことです。

仮想マシンのクローンを作成すると時間を大幅に節約できますが、ディスク上の識別情報が重複しているために問題が発生する可能性があります。

1方が他方のクローンである2つのマシンを登録しようとする場合、おそらく、{productname}でそれらを2つの別々のクライアントとして登録する必要があります。 ただし、元のクライアントとクローンのマシンIDが同じ場合、{productname}は両方のクライアントを1つのシステムとして登録し、2台目のマシンが登録されると、データが上書きされます。

これは、{productname}が2つの別のクライアントとして認識できるように、クローンのマシンIDを変更することで解決できます。 マシンIDの変更方法の詳細と手順については、xref:administration:troubleshooting/tshoot-registerclones.adoc[]を参照してください。

ただし、状況によっては、既存のマシンIDに依存する他のアプリケーションを妨害する可能性があるため、すべてのシステムでマシンIDを変更することは実行可能でも、実用的でもありません。このような場合、{productname}のコンテキストで使用するための偽のマシンIDを生成するオプションを利用できます。

.プロシージャ: 登録時における{productname}のマシンIDの生成
[role=procedure]
____

. ブートストラップスクリプトを作成します(すでにある場合はこのステップをスキップしてください)。 詳細については、xref:client-configuration:registration-bootstrap.adoc[]を参照してください。

. ファイルを開き、パラメータを変更します。

+

----
GENERATE_OWN_MACHINEID=1
----

. 厳密なブートスクラップの使用を開始すると、マシンIDが競合しなくなります。

____
