[[troubleshooting-remote-root-on-micro]]
= {sl-micro}へのリモートルートログイン
:revdate: 2025-06-17
:page-revdate: {revdate}

For enhanced security, new installations of {sl-micro} 6.1 and later do not allow password-based remote root login anymore, which affects server and proxy container hosts running on {sl-micro} and managed {sl-micro} clients. Also, {sle-micro} 5.5 clients with password-based remote root login which will when be migrated to 6.1/6.2 will suddenly lose this access and must be newly configured. For more information, see SL Micro Release Notes 6.1 (https://www.suse.com/releasenotes/x86_64/SL-Micro/6.1/index.html#jsc-SMO-405).

{productname}プロキシなどの{productname}コンポーネントを配備する際に、デフォルトで、パスワードベースのリモートルートログインが必要です。 パスワードベースのリモートルートログインは次のステップで有効化できます。


.プロシージャ: {sl-micro}でのパスワードを使用したSSHルートログインの有効化
[role=procedure]
____

SSHルートログインは2つの異なる方法で有効化できます。 どちらの方法でも機能します。セットアップに最適な方法を選択してください。

.オプションA: 事前設定されたパッケージを使用する

. クライアントのUI/APIからパッケージ[package]``openssh-server-config-rootlogin``をインストールします。

. UIまたは端末からコンテナホストを再起動して新しい設定を有効化します。

.オプションB: SSH設定を手動で編集する

. 次の内容を含むドロップイン設定[path]``/etc/ssh/sshd_config.d/permit_root.conf``ファイルを追加します。

+

----
PermitRootLogin yes
----

. SSHサーバ設定の再ロード

+

[source, shell]
----
systemctl reload sshd
----

. SSHを使用して接続している場合、サーバから切断する前に、新しいSSH接続を開いてSSHサーバが正しく機能していることを確認します。

____

[command]``transactional-update``の詳細については、link:https://documentation.suse.com/sle-micro/6.1/html/Micro-transactional-updates/[]を参照してください。
