[[troubleshooting-packages]]
= パッケージの不整合のトラブルシューティング
:revdate: 2025-02-06
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

クライアント上のパッケージがロックされている場合、{productname}サーバは適用可能なパッチのセットを正しく判断できない場合があります。 この場合、パッケージの更新は{webui}で使用できますが、クライアントには表示されず、クライアントを更新しようとすると失敗します。 パッケージのロックと除外リストをチェックして、クライアント上でパッケージがロックされているか除外されているかを判断します。

クライアント上で、パッケージのロックと除外リストをチェックして、パッケージがロックされているか、除外されているかを判断します。

// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{mlm-content} == true]

* 拡張サポートプラットフォームでは、[path]``/etc/yum.conf``をチェックして、``exclude=``を検索します。
endif::[]

* {sle}および{opensuse}では、[command]``zypper locks``コマンドを使用します。
