[[ref-schedule-maint-windows]]
= Maintenance Windows
:description: Configure maintenance window schedules with ease using existing iCal files or creating new ones, then assign them to clients via a user-friendly interface
:revdate: 2020-09-11
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

The menu:Schedule[Maintenance Windows] section allows you to manage your maintenance window schedules.
To create a maintenance schedule, you need to have an existing [path]``.ical`` file that contains the calendar.
Upload the calendar, create a new schedule, and assign the schedule to a client.
When a schedule is applied to a client, you are prevented from executing some actions outside of the specified period.

Navigate to menu:Schedule[Maintenance Windows > Schedules] to see a list of all current schedules.
Click btn:[Create] to create a new schedule.
Click btn:[Edit] to change the schedule.

Navigate to menu:Schedule[Maintenance Windows > Calendars] to see a list of all current calendars.
Click btn:[Create] to create a new calendar.
Click btn:[Edit] to change the calendar.

For more information about maintenance windows, see xref:administration:maintenance-windows.adoc[].
