[[ref-spacecmd-package]]
= package_

The following spacecmd functions are available for working with packages.



== package_details

Show the details of a software package.

[source]
--
usage: package_details PACKAGE ...
--



== package_listdependencies

List the dependencies for a package.

[source]
--
用法：package_listdependencies PACKAGE
--



== package_listerrata

List the errata that provide this package.

[source]
--
用法：package_listerrata PACKAGE ...
--



== package_listinstalledsystems

List the systems with a package installed.

[source]
--
用法：package_listinstalledsystems PACKAGE ...
--



== package_listorphans

List packages that are not in a channel.

[source]
--
用法：package_listorphans
--



== package_remove

Remove a package from SUSE Manager/Satellite

[source]
--
用法：package_remove PACKAGE ...
--



== package_removeorphans

Remove packages that are not in a channel.

[source]
--
用法：package_removeorphans
--



== package_search

Find packages that meet the given criteria.

[source]
--
用法：package_search NAME|QUERY
--

[source]
--
示例：package_search kernel
--

Advanced Search

[source]
--
可用字段：name、epoch、version、release、arch、description、summary

示例：name:kernel AND version:2.6.18 AND -description:devel
--
