= Server Upgrade from 5.0 to 5.2
:revdate: 2026-06-30
:page-revdate: {revdate}


[IMPORTANT]
====
{productname} 5.0 must be stopped before the upgrade.
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::installation-and-upgrade:partial$snippet-certificate-validators.adoc[leveloffset=+1]
include::installation-and-upgrade:partial$snippet-ssl-requirements.adoc[leveloffset=+1]
include::installation-and-upgrade:partial$snippet-version-number.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::../../../../../partials/snippet-certificate-validators.adoc[leveloffset=+1]
include::../../../../../partials/snippet-ssl-requirements.adoc[leveloffset=+1]
include::../../../../../partials/snippet-version-number.adoc[leveloffset=+1]
endif::[]

During a migration the server SSL certificate and CA chain are copied from the source server.


== {sle-micro} 5.5 to {sl-micro} 6.2



This document provides the tested procedure to upgrade a {sle-micro} 5.5 host deployed with {productname} 5.0 Server to {sl-micro} 6.2 and migrate to {productname} {productnumber}.


=== Prerequisites

* {productname} 5.0 is installed and running on {sle-micro} 5.5.
* System is registered and has active subscriptions with {scc}.


=== Distribution upgrade and server migration

.Procedure: Migration from {productname} 5.0 to {productname} {productnumber}
[role=procedure]
____

. Verify current product status.

+

[source,console]
----
SUSEConnect --status-text
----

+

Confirm:

* Base OS: `SUSE Linux Enterprise Micro 5.5`
* Extension: `SUSE Manager Server 5.0 Extension`

+

. Ensure the system is updated.

+

[source,console]
----
transactional-update patch
----

+

--

* If patches were applied, stop the server and then reboot the system before proceeding to migration:

+

[source,console]
----
mgradm stop
reboot
----

* If no updates were found, you can proceed directly to the migration step.

--

+

. Start the migration.

+

[source,console]
----
transactional-update migration --auto-agree-with-licenses --gpg-auto-import-keys
----

+

Follow the prompts and select the available migration to **SUSE Linux Micro 6.2** and **{productname} Server Extension {productnumber}**.

+

. Clean up the unused container images to free disk space:

+
[source,shell]
----
podman image prune -a
----

+

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-check-rpmnew-rpmsave.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-check-rpmnew-rpmsave.adoc[]
endif::[]

+

. Stop the server and then reboot to apply changes.

+

[source,console]
----
mgradm stop
reboot
----

+

. Perform post-reboot checks.

+

Verify {productname} extension and {productname} version:

+

[source,console]
----
SUSEConnect --status-text
mgradm --version
----

+

Expected output:

* Extension: `SUSE Multi-Linux Manager Server {productnumber} Extension`
* Version: referencing `5.2.0` or higher

+

. Verify PostgreSQL database version.

+

[source,console]
----
podman ps
----

+

Expected output:

* `server:5.2.0` or higher
* `server-postgresql:5.2.0` or higher

+

. Upgrade server containers.

+

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-ptf-loss-during-upgrade.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-ptf-loss-during-upgrade.adoc[]
endif::[]

+

[WARNING]
====
Before running `mgradm upgrade podman`, check whether `/etc/systemd/system/uyuni-server.service` contains explicit IPv6 port bindings in the form `-p [::]:PORT:PORT`.
These bindings are incompatible with netavark on {sl-micro} 6.2 and cause malformed nftables rules that prevent the web UI from being reachable after the upgrade.

If such lines are present, remove them before proceeding:

[source,diff]
----
  -p 80:80 \
- -p [::]:80:80 \
  -p 443:443 \
- -p [::]:443:443 \
----

Then reboot the host before continuing:

[source,bash]
----
systemctl reboot
----
====

+

[source,console]
----
mgradm start
mgradm upgrade podman
----

+

Follow the prompts to pull and configure the new 5.2.x containers.

+

. Verify running containers:

+

[source,console]
----
podman ps
----

+

You should see all the expected server containers are up and running.

. Clean up the unused container images to free disk space:

+
[source,shell]
----
podman image prune -a
----

+

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-check-rpmnew-rpmsave.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-check-rpmnew-rpmsave.adoc[]
endif::[]

____


=== Migration complete

The server host system is now running {sl-micro} 6.2 with updated {productname} {productnumber} Server packages.

If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-52.adoc[Proxy Migration 5.0 > 5.2] guide to upgrade the proxy host.

Validate your setup before resuming production operations.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]


== {sles} 15 SP6 to 15 SP7

This document provides the procedure to upgrade a {sles} 15 SP6 host deployed with {productname} 5.0 Server to {sles} 15 SP7 and migrate to {productname} {productnumber}.


=== Prerequisites

* {productname} 5.0 is installed and running on {sles} 15 SP6.
* System is registered and has active subscriptions with {scc}.


=== Distribution upgrade and server migration

.Procedure: Upgrade and Migrate {productname} on {sles} 15 SP6
[role=procedure]
____

. Verify current product status.

+

[source,console]
----
SUSEConnect --status-text
----

+

Confirm:

* Base OS: `SUSE Linux Enterprise Server 15 SP6`
* Extension: `SUSE Manager Server 5.0 Extension`

+

. Ensure the system is updated.

+

[source,console]
----
zypper patch
----

+

If patches were applied, stop the server and then reboot before proceeding:

+

[source,console]
----
mgradm stop
reboot
----

+

. Perform the migration to SP7 and {productname} {productnumber}.

+

[source,console]
----
zypper migration
----

+

Select to migrate to:

* `{sles} 15 SP7`
* `{productname} Server Extension {productnumber}`

+

. Stop the server and reboot.

+

[source,console]
----
mgradm stop
reboot
----

+

. Perform post-reboot checks.

+

Verify {productname} extension:

+

[source,console]
----
SUSEConnect --status-text
----

+

Expected output:

* Extension: `SUSE Multi-Linux Manager Server {productnumber} Extension`

+

. Verify {productname} version.

+

[source,console]
----
mgradm --version
----

+

Expected output:

* Version: referencing `5.2.0` or higher

+

. Upgrade server containers.

+

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-ptf-loss-during-upgrade.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-ptf-loss-during-upgrade.adoc[]
endif::[]

+

[source,console]
----
mgradm start
mgradm upgrade podman
----

+

Follow the prompts to pull and configure the new 5.2.x containers.


. Verify containers:

+

[source,console]
----
podman ps
----

+

Expected output:

* `server:5.2.0` or higher
* `server-postgresql:5.2.0` or higher

____


=== Migration complete

The server host system is now running {sles} 15 SP7 with updated {productname} {productnumber} Server packages.

If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-52.adoc[Proxy Migration 5.0 > 5.2] guide to upgrade the proxy host.

Validate your setup before resuming production operations.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]
