= Copyright Notice

Copyright (c) 2011 - 2024 SUSE LLC.
SUSE MANAGER LICENSE AGREEMENT
This software is a modular operating system comprised of numerous components that may be accompanied by separate license terms. The software is a collective work of SUSE; although SUSE does not own the copyright to every component of the software, SUSE owns the collective work copyright for the software.
This SUSE product includes materials licensed to SUSE under the GNU General Public License (GPL). The GPL requires that SUSE makes available certain source code that corresponds to the GPL-licensed material. The source code is available for download at https://www.suse.com/download-linux/source-code.html. Also, for up to three years from SUSE's distribution of the SUSE product, upon request SUSE will mail a copy of the source code. Requests should be sent by e-mail to sle_source_request@suse.com or as otherwise instructed at https://www.suse.com/download-linux/source-code.html. SUSE may charge a fee to recover its reasonable costs of distribution
