[[installation-zsystems]]
= {ibmz}へのインストール


このセクションの対象読者は、{ibmz}メインフレームを運用するz/VMシステムプログラマです。 {ibmz}オペレーティングプロトコルのトレーニングを受けたz/VMシステムプログラマを想定して、既存のメインフレームシステムに{productname}をインストールする手順を説明します。 このセクションは、{ibmz}で利用可能な多種類のハードウェア設定プロファイルを網羅していませんが、{ibmz}に{productname}サーバを正しく展開するために必要な手順および要件の基本的な概要を説明します。

このセクションでは、{sle}インストールメディアを使用して{susemgr}サーバをインストールする方法について説明します。 {scc}で{susemgr}製品を登録済みで、登録コードを取得している必要があります。

{scc}を使用して登録し、{scc}から組織の資格情報を取得し、インストールメディアを取得する方法については、xref:general-requirements.adoc[]を参照してください。



== システム要件

開始する前に、お使いの環境がベースシステム要件を満たしていることを確認してください。


.互換性のある{ibmz}システム:

* IBM zEnterprise System z196
* IBM zEnterprise System z114
* IBM zEnterprise EC12
* IBM zEnterprise EC12
* IBM zEnterprise BC12
* IBM z13
* LinuxOne Rockhopper
* LinuxOne Emperor


[cols="1,1", options="header"]
.ハードウェア要件
|===
| ハードウェア     | 推奨
| CPU          | 専用64ビットCPUコア数は4つ以上
 | RAM:         | テストサーバ:RAMは3{nbsp}GB以上で、スワップ容量は2{nbsp}GB
 |              | ベースインストール:16{nbsp}GB以上
 |              | 運用サーバ32{nbsp}GB以上
 | ディスク容量:  | ルートパーティション: 100{nbsp}GB以上
 |              | [path]``/var/lib/pgsql``: 50{nbsp}GB以上
 |              | [path]``/var/spacewalk``: 各SUSE製品では50{nbsp}GB以上、各Red Hat製品では360{nbsp}GB
|===

[IMPORTANT]
====
メモリは、お使いの環境に合わせて、使用可能なRAM、VDISK、およびスワップ間で分割する必要があります。 運用システムでは、インストールするクライアントの数に基づいてVDISK用の物理メモリの割合を評価する必要があります。
====

データベースストレージ用の追加ディスクが必要です。 [systemitem]``HYPERPAV``での使用が優先されるため、[systemitem]``zFCP``または[systemitem]``DASD``デバイスにすることをお勧めします。 データベースストレージディスクの要件を以下に示します。

* [path]``/var/lib/pgsql``では50{nbsp}GB以上
* [path]``/var/spacewalk``の各SUSE製品では50{nbsp}GB以上
* [path]``/var/spacewalk``の各Red Hat製品では360{nbsp}GB以上

[command]``yast2 susemanager_setup``を実行する前に、{productname}のディスクストレージが十分であることを確認する必要があります。 デフォルトでは、組み込みデータベース、パッチディレクトリなどの{productname}ファイルシステムはルートディレクトリに配置します。 インストール完了時に調整することもできますが、その調整は綿密に指定して監視することが重要です。 ストレージ管理およびディスク容量の調整については、{productname}管理ガイドのトラブルシューティングセクションを参照してください。

[WARNING]
====
{productname}のディスク容量が不足すると、データベースおよびファイル構造に深刻な影響が及ぶ可能性があります。 完全に復元するには、以前のバックアップを使用するか、新しい{productname}をインストールするしか方法がありません。 {suse}テクニカルサービスは、ディスク容量が少ないシステムにはサポートを提供できません。
====

.ネットワーク要件:

* OSA Express Ethernet(高速ギガビットEthernetを含む)
* HiperSocketsまたはGuest LAN
* 10{nbsp}GBE、VSWITCH
* RDMA over Converged Ethernet (RoCE)

次のインターフェイスはまだパッケージに含まれていますが、サポートは終了しています。

* CTCまたは仮想CTC
* IUCV用IPネットワークインターフェース

{productname}の実行元にするz/VMゲストは、初期インストール後に簡単には変更できないため、インストール開始前に静的IPアドレスおよびホスト名が必要です。 ホスト名は8文字未満にし、大文字を含めないでください。





== {ibmz}への{productname}のインストール

このセクションでは、{sle}ファミリの製品として{productname}をインストールする方法について説明します。 {ibmz}ハードウェアの製品展開の一般的な情報については、https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-zseries.htmlを参照してください。

.プロシージャ: DVDイメージから{susemgr}サーバにインストールする
[role=procedure]

. Unified Installerを使用してシステムを起動します。
    起動に失敗した場合、BIOSで起動順序を調整する必要がある場合があります。
. プロンプトが表示されたら、［[guimenu]``インストール``］を選択します。

xref:installation:install-server-unified.adoc[]の説明に従って続行します。

{productname}のインストールを終了するには、xref:installation:server-setup.adoc[]を参照してください。
