[[proxy-setup]]
= SUSE Managerのプロキシ設定

{productname}プロキシは追加の設定が必要です。

[NOTE]
.プロキシチェーン
====
Saltプロキシはチェーンで編成できます。 その場合、上流プロキシの名前が`parent`になります。
====

TCPポート`4505`および`4506`がプロキシで開いていることを確認してください。 プロキシは、これらのポートで{productname}サーバまたは親プロキシにアクセスできる必要があります。



[[at.manager.proxy.run.copycert]]
== サーバ証明書およびキーのコピー

プロキシは、SSL情報を{productname}サーバと共有します。 証明書およびそのキーを{productname}サーバまたは親プロキシからコピーします。

rootとして、{productname}サーバまたは親プロキシ(名前は[replaceable]``PARENT``)を使用してプロキシで次のコマンドを入力します。

----
mkdir -m 700 /root/ssl-build
cd /root/ssl-build
 scp root@PARENT:/root/ssl-build/RHN-ORG-PRIVATE-SSL-KEY .
 scp root@PARENT:/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT .
 scp root@PARENT:/root/ssl-build/rhn-ca-openssl.cnf .
----


[NOTE]
====
セキュリティチェーンを未加工のままにするには、{productname}プロキシの機能では、SSL証明書が{productname}サーバ証明書と同じCAによって署名されている必要があります。 プロキシとサーバで異なるCAによって署名されている証明書を使用することはサポートされていません。
====



[[at.manager.proxy.run.confproxy]]
== [command]``configure-proxy.sh``の実行

[command]``configure-proxy.sh``スクリプトは、{productname}プロキシの設定を終了処理します。

インタラクティブな[command]``configure-proxy.sh``スクリプトを実行します。 何も入力せずにkbd:[Enter]キーを押すと、スクリプトでは、``[]``記号で囲まれたデフォルト値を使用します。 次に、リクエストされた設定に関する情報を示します。

{productname} Parent（SUSE Managerの親）::{productname}の親は、別のプロキシまたは{productname}サーバを指定できます。

HTTPプロキシ::
HTTPプロキシでは、{productname}プロキシでWebにアクセスできます。 HTTPプロキシは、Webへの直接アクセスがファイアウォールによって禁止されている場合に必要です。

Traceback Email（トレースバックメール）::
問題を報告するメールアドレス。

Use SSL（SSLの使用）::
安全上の理由によって、``Y``を押します。

Do You Want to Import Existing Certificates?（既存の証明書をインポートしますか?）::
``N``と応答します。そうすることで、前に{productname}サーバからコピーした新しい証明書が使用されます。

組織::
次の質問は、プロキシのSSL証明書に使用する特性に関するものです。 プロキシがメインサーバと同じ組織ではない場合、サーバで使用された組織とこの組織が同じ場合があります。

組織単位::
ここのデフォルト値はプロキシのホスト名です。

市町村::
プロキシの証明書に添付する追加情報。

都道府県::
プロキシの証明書に添付する追加情報。

国コード::
［[guimenu]``国コード``］フィールドに{productname}のインストール中に設定した国コードを入力します。 たとえば、プロキシが米国にある場合に{productname}がドイツにあると、プロキシに`DE`と入力します。
+

[NOTE]
====
国コードは大文字2文字にする必要があります。 国コードの一覧はhttps://www.iso.org/obp/ui/#searchを参照してください。
====

Cname Aliases (Separated by Space)（Cnameエイリアス(スペース区切り)）::
プロキシにさまざまなDNS CNAMEエイリアスからアクセスできる場合、これを使用します。 それ以外の場合、空白のままにできます。

CA Password（CAパスワード）::
{productname}サーバの証明書に使用したパスワードを入力します。

Do You Want to Use an Existing SSH Key for Proxying SSH-Push Salt Minion?（SSH-Push Salt Minionのプロキシ処理に既存のSSHキーを使用しますか?）::
サーバでSSH-Push Saltクライアントに使用したSSHキーを再使用する場合、このオプションを使用します。

Create and Populate Configuration Channel rhn_proxy_config_1000010001?（設定チャンネルrhn_proxy_config_1000010001を作成および入力しますか?）::
デフォルトの``Y``を受け入れます。

SUSE Manager Username（SUSE Managerユーザ名）::
{productname}サーバで使用したユーザ名とパスワードを使用します。

CAキーやパブリック証明書などがない場合、スクリプトは、必要なファイルを統合するために実行する必要があるコマンドを出力します。 必須ファイルがコピーされると、[command]``configure-proxy.sh``を再実行します。 スクリプトの実行中にHTTPエラーが発生したら、このスクリプトを再実行します。

[command]``configure-proxy.sh``は、[systemitem]``squid``、[systemitem]``apache2``、[systemitem]``salt-broker``、[systemitem]``jabberd``など、{productname}プロキシで必要なサービスをアクティブ化します。

プロキシシステムおよびそのクライアントの状態をチェックするには、{webui}のプロキシシステムの詳細ページをクリックします(menu:システム[プロキシ]、<システム名>に移動)。 ［[guimenu]``接続``］サブタブおよび［[guimenu]``プロキシ``］サブタブにはさまざまな状態情報が表示されます。



[[proxy.pxe.setup]]
== PXEブートの有効化



[[proxy.pxe.sync]]
=== プロファイルとシステム情報を同期

プロキシでPXEブートを有効にするには、追加のソフトウェアをインストールし、{productname}プロキシと{productname}サーバの両方で設定する必要があります。

. {productname}プロキシで、[package]``susemanager-tftpsync-recv``パッケージをインストールします。
+

----
zypper in susemanager-tftpsync-recv
----

. {productname}プロキシで、[command]``configure-tftpsync.sh``設定スクリプトを実行し、要求された情報を入力します。
+

----
configure-tftpsync.sh
----
+

{productname}サーバおよびプロキシのホスト名とIPアドレスを入力する必要があります。 プロキシのtftpbootディレクトリへのパスも入力する必要があります。

. {productname}サーバで、[package]``susemanager-tftpsync``をインストールします。
+

----
zypper in susemanager-tftpsync
----

. {productname}サーバで、[command]``configure-tftpsync.sh``を実行します。
    設定が作成され、{productname}プロキシにアップロードされます。
+

----
configure-tftpsync.sh FQDN_of_Proxy
----

. {productname}サーバで初期同期を開始します。
+

----
cobbler sync
----
+

すぐに同期する必要があるCobbler内で変更した後にも実行できます。 それ以外の場合、Cobblerの同期は必要なときに自動的に実行されます。 Cobblerを利用した自動インストールの詳細については、xref:client-configuration:autoinst-intro.adoc[オペレーティングシステムのインストール]を参照してください。



[[proxy.pxe.dhcp]]
=== {productname}プロキシを使用したDHCP for PXEの設定

{productname}は、クライアントのプロビジョニングにCobblerを使用します。 PXE (tftp)は、デフォルトでインストールされ、アクティブ化されます。 クライアントは、DHCPを使用して{productname}プロキシでPXEブートを探すことができる必要があります。 プロビジョニングするクライアントが含まれているゾーンでこのDHCP設定を使用します。

----
next-server: <IP_Address_of_Proxy>
filename: "pxelinux.0"
----



[[replace-susemgrproxy]]
== {productname}プロキシの置き換え

プロキシは、接続されているクライアントの情報を保存しないため、いつでも置き換えることができます。 このプロセスは、再アクティベーションキーを使用して処理されます。そのため、プロキシの履歴が失われることはありません。 再アクティベーションキーを使用しない場合、置き換えプロキシが新しいプロキシになり、新しいIDが付きます。 置き換えプロキシは、その元のプロキシと同じ名前とIPアドレスにする必要があります。

従来のプロキシをSaltプロキシに変更するためにプロキシを再インストールすることもできます。


[IMPORTANT]
====
プロキシのインストール中、クライアントは、{productname}サーバにアクセスできなくなります。 プロキシを削除した後、システム一覧は一時的に正しくなくなります。 以前プロキシに接続したすべてのクライアントは、代わりにサーバに直接接続されているとして表示されます。 パッケージまたはパッチのインストールやリモートコマンドを実行するなど、クライアントでの最初の操作が成功した後、この情報は自動的に修正されます。 この処理には数時間かかる場合があります。
====



=== プロキシの置き換え

古いプロキシをシャットダウンし、置き換えを準備している間、インストール状態を保持します。 このシステムの再アクティベーションキーを作成し、その再アクティベーションキーを使用して新しいプロキシを登録します。 再アクティベーションキーを使用しない場合、新しいプロキシに対してすべてのクライアントを再登録する必要があります。



.プロシージャ: 従来のプロキシの置き換えとクライアントの登録状態の保持
. 移行を開始する前に、必要に応じて、古いプロキシからデータを保存します。 新しいプロキシからもアクセスできる一元管理場所に重要データやカスタムデータをコピーすることを検討してください。
. 古いプロキシをシャットダウンします。
. 新しい{productname}プロキシをインストールします。 インストール手順については、xref:install-proxy-unified.adoc[プロキシのインストール]を参照してください。
. {productname}の{webui}で、新しくインストールした{productname}プロキシを選択し、システム一覧から選択解除します。
. {webui}で、古いプロキシシステムの再アクティベーションキーを作成します。 古いプロキシの［[guimenu]``システムの詳細``］タブで［[guimenu]``再アクティベーション``］をクリックします。 ［[guimenu]``新しいキーの生成``］をクリックし、新しいキーをメモします。
. xref:installation:proxy-registration.adoc[]の記述に従って、ブートストラップスクリプトを使用して新しいプロキシを登録します。 ブートストラップスクリプトで、[systemitem]``REACTIVATION_KEY``パラメータを使用して再アクティベーションキーを設定します。
. 以前に作成したバックアップからプロキシデータを復元します。この手順のステップ1を参照してください。

Saltプロキシでは、新しいプロキシをブートストラップする前に、追加の手順を実行する必要があります。



.プロシージャ: Saltプロキシの置き換えとクライアントの登録状態の保持
. 移行を開始する前に、必要に応じて、古いプロキシからデータを保存します。 新しいプロキシからもアクセスできる一元管理場所に重要データやカスタムデータをコピーすることを検討してください。
. 古いプロキシをシャットダウンします。
. {webui}で、古いプロキシシステムの再アクティベーションキーを作成します。 古いプロキシの［[guimenu]``システムの詳細``］タブで［[guimenu]``再アクティベーション``］をクリックします。 ［[guimenu]``新しいキーの生成``］をクリックし、新しいキーをメモします。
. {webui}で、menu:Salt[キー]に移動し、古いプロキシに関連付けられているSaltキーを見つけ、btn:[delete]をクリックします。
. 新しい{productname}プロキシをインストールします。 インストール手順については、xref:install-proxy-unified.adoc[プロキシのインストール]を参照してください。
. xref:installation:proxy-registration.adoc[]の記述に従って、ブートストラップスクリプトを使用して新しいプロキシを登録します。 ブートストラップスクリプトで、[systemitem]``REACTIVATION_KEY``パラメータを使用して再アクティベーションキーを設定します。
. 以前に作成したバックアップからプロキシデータを復元します。この手順のステップ1を参照してください。

再アクティベーションキーの使用の詳細については、xref:client-configuration:activation-keys.adoc[]を参照してください。

新しいプロキシをインストールした後、次の操作を実行する必要があります。

* 一元的に保存されているデータを新しいプロキシシステムにコピーする
* その他の必要なソフトウェアをインストールする
* プロキシを自動インストールに使用する場合、TFTP同期を設定する



=== 従来のプロキシからSaltプロキシへの変更

従来のプロキシをSaltプロキシに切り替えるためにプロキシを再インストールできます。 このメソッドでは、再アクティベーションキーの代わりに、プロキシの登録に使用したアクティベーションキーと同じキーを再使用します。 つまり、クライアントを再登録する必要はありません。



.プロシージャ: 従来のプロキシをSaltプロキシに置き換える
. 移行を開始する前に、必要に応じて、古いプロキシからデータを保存します。 新しいプロキシからもアクセスできる一元管理場所に重要データやカスタムデータをコピーすることを検討してください。
. プロキシをシャットダウンします。
. 新しい{productname}プロキシをインストールし、置き換えるプロキシと同じIPアドレスがあることを確認します。 インストール手順については、xref:install-proxy-unified.adoc[プロキシのインストール]を参照してください。
. xref:installation:proxy-registration.adoc[]の記述に従って、ブートストラップスクリプトを使用してプロキシを登録します。 ブートストラップスクリプトで、[systemitem]``ACTIVATION_KEYS``パラメータを使用して、古いプロキシに使用したアクティベーションキーを設定します。

新しいプロキシをインストールした後、次の操作を実行する必要があります。

* 一元的に保存されているデータを新しいプロキシシステムにコピーする
* その他の必要なソフトウェアをインストールする
* プロキシを自動インストールに使用する場合、TFTP同期を設定する
