[[pubcloud-setup]]
= パブリッククラウドの設定

サインインする前に、{productname}サーバを{scc}で登録して、更新を受信する必要があります。

[IMPORTANT]
====
YaST {productname}の設定手順を実行する前にストレージデバイスを設定する必要があります。 詳細については、xref:installation:pubcloud-requirements.adoc[]を参照してください。
====

クラウドプロバイダの指示に従って、インスタンスに対してSSHを実行し、次のコマンドを実行して設定を開始します。

----
yast2 susemanager_setup
----

プロンプトに従い、設定が完了するのを待ちます。

{yast}で{productname}を設定する詳細な手順については、xref:installation:server-setup.adoc[]を参照してください。




== パブリッククラウドモジュールのアクティブ化

パブリッククラウドインスタンスで{productname}を使用するには、パブリッククラウドモジュールをアクティブ化する必要があります。



.プロシージャ: パブリッククラウドモジュールのアクティブ化
. {productname}サーバで、{yast}管理ツールを開き、menu:ソフトウェア[ソフトウェアリポジトリ]に移動します。
. ［btn:[追加]］をクリックし、［[guimenu]``Extensions and Modules from Registration Server（登録サーバの拡張機能とモジュール）``］を選択します。
. ［[guimenu]``Available extensions（利用できる拡張機能）``］フィールドで、［[guimenu]``Public Cloud Module``］を選択します。

コマンドラインを使用する場合、次のコマンドを使用してモジュールを追加できます。
----
SUSEConnect -p sle-module-public-cloud/15.2/x86_64
----

インストール手順を完了したら、必要なすべてのモジュールがあるかどうかを確認できます。 コマンドプロンプトで次のように入力します。

----
SUSEConnect --status-text
----

パブリッククラウドの{productname}サーバでは、必要なモジュールは以下のとおりです。

* {sles}ベースシステムモジュール
* Python 2 Module
* Server Applications Module
* Web and Scripting Module
* SUSE Managerサーバモジュール
* パブリッククラウドモジュール



== {webui}で設定を完了する

Webブラウザで{productname}の{webui}を開きます。次のようなアドレスを使用します。

----
https://<public_IP>
----

管理者アカウントで{productname}の{webui}にサインインします。 ユーザ名およびパスワードはプロバイダによって決まります。

.デフォルトの管理者アカウントの詳細
[cols="1,1,1", options="header"]
|===
| プロバイダ              | デフォルトのユーザ名  | デフォルトのパスワード
|Amazon EC2            | ``admin``         | ``<instance-ID>``
 | Google Compute Engine: | ``admin``         | ``<instance-ID>``
 | Microsoft Azure       | ``admin``         | ``<instance-name>-suma``
|===

パブリッククラウドインスタンスのWebコンソールまたはコマンドプロンプトからインスタンス名およびIDを受け取ることができます。

Amazon EC2:

----
ec2metadata --instance-id
----

Google Compute Engine:

----
gcemetadata --query instance --id
----

Microsoft Azure:

----
azuremetadata --compute --name
----


初めて管理者アカウントにサインインしたとき、自動生成された組織名が与えられます。 この名前を変更します。そのためには、menu:管理[組織]に移動し、組織名を編集します。


[IMPORTANT]
====
初めて管理者アカウントにサインインしたとき、デフォルトのパスワードを変更し、アカウントを保護します。
====

{productname}サーバの設定の詳細については、xref:installation:server-setup.adoc[]を参照してください。


{productname}の{webui}を使用して必要なソフトウェア製品を追加し、リポジトリの同期をスケジュールします。 これを実行する最適な方法は、menu:管理[セットアップウィザード]に移動し、プロンプトに従うことです。

セットアップウィザードの詳細については、xref:installation:setup-wizard.adoc[]を参照してください。


{ubuntu}クライアントまたは{rhel}クライアントを登録しようとしている場合、カスタムのリポジトリおよびチャンネルを設定する必要があります。 詳細については、xref:client-configuration:registration-overview.adoc[]の関連セクションを参照してください。


チャンネルを同期するには、menu:ソフトウェア[管理 > チャンネル]に移動します。 作成した各チャンネルをクリックし、menu:リポジトリ[同期]タブに移動し、［btn:[今すぐ同期]］をクリックします。 この画面から同期をスケジュールすることもできます。


[IMPORTANT]
====
クライアントをブートストラップする前に、その製品ですべての選択チャンネルが同期していることを確認してください。

同期には数時間かかる場合があります。特にopenSUSE、SLES ES、およびRHELの各チャンネルでは時間がかかります。
====


{productname}サーバを設定すると、クライアントの登録を開始できます。 パブリッククラウドでクライアントを登録する方法の詳細については、xref:client-configuration:clients-pubcloud.adoc[]を参照してください。
