[[setup-wizard]]
= セットアップウィザード

{productname}のインストールを完了したら、セットアップウィザードを使用して、最後の数ステップを実行できます。 セットアップウィザードを使用すると、HTTPプロキシ、組織の資格情報、および{suse}製品を設定できます。

セットアップウィザードは、{productname}の{webui}に初めてログインしたときにデフォルトで表示されます。 セットアップウィザードに直接アクセスできます。そのためには、menu:管理[セットアップウィザード]に移動します。



== HTTPプロキシの設定

{productname}は、プロキシを使用して{scc} (SCC)またはその他のリモートサーバに接続できます。 ［[guimenu]``HTTPプロキシ``］タブに移動し、プロキシを設定します。

プロキシのホスト名を指定する必要があります。 構文``<hostname>:<port>``を使用します。 例: ``<example.com>:8080``。

各フィールドをクリアしてプロキシの使用を無効にできます。


[IMPORTANT]
====
{productname}プロキシのユーザ名またはパスワードを選択するとき、``@``または``:``を含めないでください。 これらの文字は予約されています。
====



== 組織の資格情報の設定

{scc}アカウントは、組織の管理アカウントに関連付けられています。 {scc}のアクセス権を組織内のその他のユーザと共有できます。 ［[guimenu]``組織の資格情報``］タブに移動し、組織内のユーザに{scc}アカウントへのアクセス権を付与します。

［btn:[Add a new credential（新しい資格情報の追加）]］をクリックし、アクセス権が付与されるユーザのユーザ名およびパスワードを入力し、［btn:[保存]］をクリックします。 新しい資格情報カードは、アクセス権付が付与されるユーザに表示されます。 カード上の次のボタンを使用してアクセス権を編集または取り消します。

* 資格情報の検証状態を確認します(緑のチェックまたは赤のバツ印のアイコン)。
    SCCで資格情報を再確認するには、アイコンをクリックします。
* サーバ間の同期用のプライマリ資格情報を設定します(黄色の星印のアイコン)。
* 特定の資格情報と関係のあるサブスクリプションをリストします(リストアイコン)。
* 資格情報を編集します(鉛筆のアイコン)。
* 資格情報を削除します(ゴミ箱のアイコン)。



== 製品の設定


{suse}サブスクリプションがあると、ある範囲の製品にアクセスできます。 ［[guimenu]``製品``］タブに移動し、使用できる製品をブラウズし、{productname}と{scc}の同期を取ります。

フィルタを使用すると、説明またはアーキテクチャごとに製品を検索できます。

リストは、製品名ごとに整列されます。 各製品について、その製品で使用できるアーキテクチャを確認できます。 製品名の横にある矢印をクリックし、関連付けられているチャンネルおよび拡張機能を表示します。 ［btn:[チャンネル]］アイコンをクリックし、各製品に関連付けられているチャンネルの一覧を表示します。

{sle}{nbsp}15以上に基づく製品では、必要なパッケージのみ同期するのか推奨製品も含めるのかのどちらかを選択できます。 ［btn:[推奨を含める]］スイッチをオンに切り替えるとすべての製品が同期され、オフに切り替えると必要な製品のみが同期されます。

同期する製品をさらに調整できます。そのためには、個々の製品を選択または選択解除します。

選択を完了したら、［btn:[製品の追加]］、［btn:[更新]］をクリックして同期をスケジュールします。

各製品の同期の進捗は、製品名の横の進捗状況バーに表示されます。 選択した製品によっては、同期に最長数時間かかる場合があります。 同期が完了すると、新しい製品は{productname}で使用できるようになります。

同期に失敗する場合、サードパーティのGPGキーが原因である可能性があります。 製品同期のトラブルシューティングの詳細については、xref:administration:tshoot-sync.adoc[]を参照してください。
