[[proxy-register]]
= プロキシの登録

プロキシシステムは、ブートストラップスクリプトを使用してSaltクライアントとして登録されます。

アクティベーションキーを使用して、ソフトウェアチャンネルを設定する方法、およびインストールしたプロキシを{productname}クライアントとして登録する方法について、このプロシージャで説明します。

[IMPORTANT]
====
アクティベーションキー作成中に正しい子チャンネルを選択する前に、openSUSE Leapチャンネルをすべての必要な子チャンネルおよび{productname}プロキシチャンネルと正しく同期したことを確認してください。
====



[[proxy-register-procedure]]
.プロシージャ: プロキシの登録

. {productname}サーバで、[command]``spacewalk-common-channels``コマンドを使用してopenSUSE Leapチャンネルおよび{productname}プロキシチャンネルを作成します。
    [command]``spacewalk-common-channels``は[package]``spacewalk-utils``パッケージの一部です。
+
----
spacewalk-common-channels \
opensuse_leap15_2 \
 opensuse_leap15_2-non-oss \
 opensuse_leap15_2-non-oss-updates \
 opensuse_leap15_2-updates \
 opensuse_leap15_2-uyuni-client \
 uyuni-proxy-stable-leap-152
----
+
[systemitem]``uyuni-proxy-stable-leap-152``の代わりに、現在の開発バージョンである[systemitem]``uyuni-proxy-devel-leap``を試すこともできます。
+
詳細については、xref:client-configuration:clients-opensuse.adoc[]を参照してください。
+
. openSUSE Leapをベースチャンネルに指定し、その他のチャンネルを子チャンネルに指定して、アクティベーションキーを作成します。
    アクティベーションキーの詳細については、xref:client-configuration:activation-keys.adoc[]を参照してください。
. プロキシのブートストラップスクリプトを変更します。
    GPGキーを[systemitem]``ORG_GPG_KEY=``パラメータに追加します。 詳細については、xref:client-configuration:clients-opensuse.adoc[]を参照してください。 ブートストラップスクリプトの詳細については、xref:client-configuration:registration-bootstrap.adoc[]を参照してください。
+
. スクリプトを使用してクライアントをブートストラップします。
    詳細については、xref:client-configuration:registration-bootstrap.adoc[]を参照してください。
. menu:Salt[キー]に移動し、キーを受け入れます。
    キーを受け入れると、［[guimenu]``最近登録されたシステム``］セクションのmenu:システム[概要]に新しいプロキシが表示されます。
. menu:システムの詳細[ソフトウェア > ソフトウェアチャンネル]に移動し、プロキシチャンネルが選択されていることを確認します。

登録した{productname}プロキシを設定するには、xref:uyuni-proxy-setup.adoc[]を参照してください。
