[[actions]]
= 操作
:description: 使用 SUSE Multi-Linux Manager 配置客户端的重复性操作、远程命令和自动化任务，以执行高状态自动化和自定义状态。
:revdate: 2025-05-12
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

您可以通过多种不同的方式管理对客户端执行的操作：

* 可以安排自动重复性操作，以按照指定的日程安排将 Highstate 或任意一组自定义状态应用于客户端。
* 可以将重复性操作应用于单个客户端、系统组中的所有客户端或整个组织。
* 可以通过创建操作链来设置要按特定顺序执行的操作。
  ** 可以提前创建和编辑操作链，并将其安排为在适当的时间运行。
* 还可以在一个或多个客户端上执行远程命令。
  ** 使用远程命令可以向单个客户端或者与搜索词匹配的所有客户端发出命令。


[[recurring_actions]]
== 重复性操作


可以对单个客户端、系统组、组织中的所有客户端应用重复性操作。

目前，{productname} 支持将以下操作类型作为重复性操作：

- `Highstate:` 执行高阶状态。
- `Custom state:` 执行一组自定义状态。自定义状态可以是 {productname} 提供的内部状态，也可以是用户创建的配置通道。

有关配置通道的更多信息，请参见 xref:client-configuration:configuration-management.adoc[]。



.过程：升级创建新的重复性操作
. 要将重复性操作应用于单个客户端，请导航到 `Systems`，单击要为其配置日程安排的客户端，然后导航到 `Recurring Actions` 选项卡。
. 要将重复性操作应用于系统组，请导航到 menu:系统[系统组]，选择要为其配置日程安排的组，然后导航到 `Recurring Actions` 选项卡。
. 单击 btn:[创建]。
. 从 `Action Type` 下拉菜单中选择操作类型。
. 键入新日程安排的名称。
. 选择重复性操作的频率：
+
* `Hourly:` 输入每小时的分钟数。
    例如，`15` 在每小时的十五分钟时运行操作。
* `Daily:` 选择每天的时间。
    例如，`01:00` 在每天的 0100 时运行操作，时区为 {productname} 服务器。
* `Weekly:` 选择星期几和每天的时间，以便在每周的指定时间执行操作。
* `Monthly:` 选择每月的日期和每天的时间，以便在每月的指定时间执行操作。
* `Custom Quartz format:` 要查看更详细的选项，请输入自定义 Quartz 字符串。
    例如，要在每个月的每个星期六 02:15 运行重复性操作，请输入：
+
----
0 15 2 ? * 7
----
. 可选：将 `Test mode` 开关切换为打开，以在测试模式下运行日程安排。
. 对于类型为 `Custom state` 的操作，从可用状态列表中选择状态，然后单击 btn:[保存更改]。这只会保存当前的状态选择，而不会保存日程安排。
. 在下一个窗格中，拖放所选状态使其按执行顺序排列，然后单击 btn:[确认]。
. 单击 btn:[创建日程安排] 保存设置，并查看现有日程安排的完整列表。


组织管理员可以为组织内的所有客户端设置和编辑重复性操作。
导航到 menu:首页[我的组织> 重复性操作] 以查看适用于整个组织的所有重复性操作。

{productname} 管理员可以为所有组织中的所有客户端设置和编辑重复性操作。
导航到 menu:管理员[组织]，选择要管理的组织，然后导航到 menu:状态[重复性操作] 选项卡。



== 操作链

如果您需要对客户端执行多个有序操作，可以创建一个操作链以确保遵循该顺序。

默认情况下，大多数客户端在命令发出后立即执行操作。
在某些情况下，操作可能需要很长时间，这可能意味着后续发出的操作会失败。
例如，如果您指示客户端重启，然后发出第二个命令，第二个操作可能会失败，因为重启仍在进行中。
为了确保操作按正确顺序发生，请使用操作链。

[IMPORTANT]
====
对于事务更新系统，操作链会在单个快照内执行，直到进行重启操作。
这可能会产生某些限制。

ifeval::[{uyuni-content} == true]
有关更多信息，请参见 xref:client-configuration:clients-slemicro.adoc[] 和 xref:client-configuration:clients-opensuseleapmicro.adoc[]。
endif::[]

ifeval::[{mlm-content} == true]
有关更多信息，请参见 xref:client-configuration:clients-slemicro.adoc[]。
endif::[]
====

您可以在所有客户端上使用操作链。
操作链可以包含任意数量的这些操作，顺序不限：

* menu:系统详细信息[远程命令]
* menu:系统详细信息[计划系统重启]
* menu:系统详细信息[状态 > 高状态]
* menu:系统详细信息[软件 > 软件包 > 列出/去除]
* menu:系统详细信息[软件 > 软件包 > 安装]
* menu:系统详细信息[软件 > 软件包 > 升级]
* menu:系统详细信息[软件 > 补丁]
* menu:系统详细信息[软件 > 软件通道]
* menu:系统详细信息[配置]
* menu:图像[构建]



[NOTE]
====
操作链是用户特定的。
要在{webui}中查看操作链，您必须以创建操作链的相同用户身份登录。
====



.过程：升级创建新操作链
. 在{productname} {webui}中，导航到您想在操作链中执行的第一个操作。
  例如，导航到客户端的 `System Details`，然后单击 btn:[计划系统重启]。
. 选中 `Add to` 字段，然后选择要将操作添加到的操作链：
+
* 如果这是您的第一个操作链，请选择 `new action chain`。
* 如果该操作链已存在，请从列表中选择它。
* 如果您已有操作链，但想要创建一个新操作链，请键入新操作链的名称以创建该操作链。
. 确认操作。
    该操作不会立即执行，而是创建新的操作链，并在屏幕顶部显示一个确认此行为的蓝色条。
. 继续将操作添加到操作链，方法是选中 `Add to` 字段并选择要将操作添加到的操作链的名称。
. 添加完操作后，导航到menu:日程安排[操作链]并从列表中选择操作链。
. 通过将操作拖放到正确的位置来重新排列操作顺序。
    单击蓝色加号以查看要执行操作的客户端。
    单击btn:[保存]以保存更改。
. 安排操作链的运行时间，然后单击btn:[保存并安排]。
    如果您在不单击 btn:[保存] 或 btn:[保存并安排] 的情况下离开页面，将丢弃所有未保存的更改。

[NOTE]
====
如果操作链中的某个操作失败，操作链将会停止，且不再执行其他操作。
====

您可以通过导航到 menu:日程安排[待执行的操作] 来查看操作链中已安排的操作。



== 远程命令

请按照此过程通过 {salt} 运行远程命令。

在开始之前，请确保您的客户端已订阅适用于其安装操作系统的相应工具子频道。
有关订阅软件频道的更多信息，请参见 xref:client-configuration:channels.adoc[]。

[IMPORTANT]
====
//* For transactional update systems, consider that a remote command is run inside a single snapshot.
//  This can cause some limitations.

ifeval::[{uyuni-content} == true]
* 对于事务更新系统，需考虑到远程命令会在单个快照内运行。
  这可能会产生某些限制。
  有关更多信息，请参见 xref:client-configuration:clients-slemicro.adoc[] 和 xref:client-configuration:clients-opensuseleapmicro.adoc[]。
endif::[]

ifeval::[{mlm-content} == true]
* 对于事务更新系统，需考虑到远程命令会在单个快照内运行。
  这可能会产生某些限制。
  有关更多信息，请参见 xref:client-configuration:clients-slemicro.adoc[]。
endif::[]

* 远程命令从客户端的 `/tmp/` 目录运行。
  为确保远程命令准确运行，请勿使用 `noexec` 选项挂载 `/tmp`。
  有关更多信息，请参见 xref:administration:troubleshooting/tshoot-mounting-tmp-with-noexec.adoc[故障排除挂载 /tmp 时使用 noexec]。

* 从 `Remote Commands` 页面运行的所有命令在客户端上以 {rootuser} 的身份执行。
  可以使用通配符在任意数量的系统上运行命令。
  在发出命令之前，请始终格外小心检查您的命令。
====


.过程：升级在 Salt 客户端上运行远程命令
. 导航到 menu:Salt[远程命令]。
. 在第一个字段中的 `@` 符号之前，键入您要发出的命令。
. 在第二个字段中的 `@` 符号之后，键入您要在其上发出命令的客户端。
    您可以键入单个客户端的 `minion-id`，也可以使用通配符指定一系列客户端作为目标。
. 单击 btn:[查找目标] 查看指定为目标的客户端，并确认使用了正确的细节。
. 单击 btn:[运行命令] 向目标客户端发出命令。
