ifndef::backend-pdf[]
[[admin-overview]]
= 管理指南
:description: 通过本综合管理指南，学习如何维护、监控和自定义 SUSE Multi-Linux Manager 服务器
:revdate: 2025-05-21
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

// HTML Publication date 
**出版日期:** {docdate}

== 首选项


本指南将介绍维护、监控以及自定义 {productname} 服务器等管理任务。

== 版权声明

// HTML Copyright
版权所有 © {copyrightdate} SUSE LLC 和贡献者。保留所有权利。
根据 GNU 自由文档许可证 (GNU Free Documentation License) 版本 1.2 或（根据您的选择）版本 1.3 中的条款，在此授予您复制、分发和/或修改本文档的权限；本版权声明和许可证附带不可变部分。版本 1.2 的许可证副本包含在题为 xref:legal:license.adoc[GNU 自由文档许可证] 的部分。

== 商标
// HTML Trademarks
有关 SUSE 商标，请参见 https://www.suse.com/company/legal/ 。所有第三方商标均是其各自所有者的财产。商标符号（®、™ 等）代表 SUSE 及其关联公司的商标。星号 (*) 代表第三方商标。
本指南力求涵盖所有细节，但这并不确保本指南准确无误。SUSE LLC 及其附属公司、作者和译者对于可能出现的错误或由此造成的后果皆不承担责任。
endif::[]


ifdef::backend-pdf[]

<<<

:!sectnums:

[preface]
== 首选项

管理指南 +
{productname} {productnumber}

本指南将介绍维护、监控以及自定义 {productname} 服务器等管理任务。

// PDF Publication

**出版日期:** {docdate}



// PDF Copyright
版权所有 © {copyrightdate} SUSE LLC 和贡献者。保留所有权利。
根据 GNU 自由文档许可证 (GNU Free Documentation License) 版本 1.2 或（根据您的选择）版本 1.3 中的条款，在此授予您复制、分发和/或修改本文档的权限；本版权声明和许可证附带不可变部分。版本 1.2 的许可证副本包含在题为 xref:legal:license.adoc[GNU 自由文档许可证] 的部分。

// PDF Trademarks
有关 SUSE 商标，请参见 https://www.suse.com/company/legal/ 。所有第三方商标均是其各自所有者的财产。商标符号（®、™ 等）代表 SUSE 及其关联公司的商标。星号 (*) 代表第三方商标。
本指南力求涵盖所有细节，但这并不确保本指南准确无误。SUSE LLC 及其附属公司、作者和译者对于可能出现的错误或由此造成的后果皆不承担责任。

<<<

toc::[]

:sectnums:

endif::[]
