[[ansible-integration]]
= Ansible 集成
:description: 使用 SUSE Multi-Linux Manager 支持的功能配置 Ansible 控制节点，以进行清单检查、发现和执行。
:revdate: 2025-03-07
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

Ansible 是一个用于管理计算机客户端系统的工具。
有关更多信息，请参见 https://www.ansible.com.

{productname} 支持管理 Ansible 控制节点。
有关详细信息，请参见 xref:administration:ansible-setup-control-node.adoc#at.ansible.overview[]。

Ansible 控制节点的支持版本是 Ansible 11.3。
它应从操作系统供应商的官方软件库中获取。
例如，在 {sle} 15 SP6 和 SP7 上，Ansible 可通过 `Systems Management Module.` 获得。对于运行其他操作系统的 {sle} 控制节点，请使用与该发行版一起提供的 Ansible。

Ansible 软件也可用于 {productname} 代理和 {productname} {smr} 分支服务器。



[[at.ansible.overview]]
== 功能概述


{productname} 使系统管理员能够操作他们的 Ansible 控制节点。
支持的功能包括：

* 清单文件检查
* 发现剧本
* 执行剧本

更多信息：

* 清单是已管理 Ansible 节点的排序列表。 有关组织清单的更多信息，请参见 https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html.。
* 剧本是一种描述如何管理清单的方法。 有关剧本的更多信息，请参见 https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html.。



[[at.ansible.requirements]]
== 要求和基本配置

要使用 Ansible 功能，您需要将已存在的 Ansible 控制节点注册到 {productname} 服务器。
在 {webui} 中，在已注册系统的 menu:系统细节[属性] 页面上，您必须在 `Add-on System Types` 列表中启用 `Ansible Control Node` 系统类型。

// FIXME: check it!
启用 `Ansible Control Node` 系统类型可确保通过在 highstate 中添加 `ansible` 软件包，从而在系统上安装该软件包，并在 menu:系统细节[Ansible] 选项卡中激活 Ansible 功能。

作为下一步，配置 menu:系统细节[Ansible > 控制节点] 页面上 Ansible 剧本目录和清单文件的路径。
作为清单路径，您可以使用标准的 Ansible 清单路径 `/etc/ansible/hosts`。
作为剧本目录，您可以使用控制节点上存储剧本文件的任何目录。
剧本目录要么包含 `.yml` 文件，要么包含带有 `.yml` 文件的子目录。

有关安装和设置 Ansible 控制节点的信息，请参见 xref:administration:ansible-setup-control-node.adoc[]。



[[at.ansible.inventory-inspection]]
== 清单检查

定义清单路径后，您可以使用 {productname} 检查其中的内容。

.过程：升级从 {webui} 检查清单
. 在 {productname} {webui} 中，导航到 menu:系统细节[Ansible > 清单]。
. 单击某个清单路径，在控制节点上实时执行清单检查。



[[at.ansible.playbook-discovery]]
== 剧本发现

定义剧本目录后，您可以在 menu:系统细节[Ansible > 剧本] 页面上发现剧本。

与清单检查一样，剧本发现操作也是在控制节点上实时运行。



[[at.ansible.playbook-execution]]
== 剧本执行

您可以从 menu:系统细节[Ansible > 剧本] 页面安排剧本执行。
选择要执行的剧本后，您可以从 `Schedule Playbook Execution` 对话框的 `Inventory Path` 下拉菜单中选择执行所需的清单文件。
如果您未选择任何项目，将使用在控制节点中配置的默认清单。
下拉菜单中填充了您在清单路径中定义的清单以及在剧本目录中本地发现的清单。
这些在剧本细节中显示为 `Custom Inventory` 项。
您还可以输入任意清单路径。

您还可以将变量传递给剧本执行，以覆盖先前定义的变量。
要传递变量，请找到 [guimenu]``剧本内容`` 部分并单击 btn:[编辑变量]。
在 [guimenu]``编辑变量`` 对话框中，您可以以列表、字典、字符串或布尔数据类型的形式添加或编辑变量。
或者，单击 btn:[编辑 YAML]，直接以 YAML 格式编辑变量。单击 btn:[保存] 以将变量应用于剧本内容。

之后，您选择剧本执行的时间或选择一个操作链。
最终，{productname} 将剧本作为控制节点上的一个操作执行。
您可以在操作详情页面上查看操作结果。
