[[channel-management]]
= 通道管理
:description: 学习如何通过将软件包分组到基础通道和子通道中来配置和管理SUSE Multi-Linux Manager中的软件通道，并将客户端分配给基础通道。
:revdate: 2025-02-28
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

通道是将软件包分组的一种方法。

在{productname}中，通道被分为基础通道和子通道，基础通道按操作系统类型、版本和架构分组，子通道与其相关的基础通道兼容。
当客户端被分配到基础通道时，该系统只能安装相关的子通道。
以这种方式组织通道确保每个系统上仅安装兼容的软件包。

软件通道使用仓库提供软件包。
这些通道镜像{productname}中的仓库，软件包名称和其他数据存储在{productname}数据库中。
您可以将任意数量的仓库与通道关联。
然后，可以通过将客户端订阅到适当的通道来在客户端上安装这些仓库中的软件。

客户端只能分配到一个基础通道。
然后，客户端可以安装或更新与该基础通道及其任何子通道关联的仓库中的软件包。

{productname}提供了多个供应商通道，提供您运行{productname}所需的一切。
{productname}管理员和通道管理员拥有通道管理权限，使他们能够创建和管理自己的自定义通道。
如果您想在您的环境中使用自己的软件包，可以创建自定义通道。
自定义通道可以用作基础通道，或者您可以将它们与供应商基础通道关联。

有关创建自定义通道的更多信息，请参见xref:administration:custom-channels.adoc[]。



== 通道管理


默认情况下，任何用户都可以为系统订阅通道。
您可以使用{webui}对通道实施限制。

.过程：升级限制订阅者对通道的访问权限
. 在{productname} {webui}中，导航到menu:软件[通道列表]，并选择要编辑的通道。
. 找到`Per-User Subscription Restrictions`部分并勾选`Only selected users within your organization may subscribe to this channel`。
  点击 btn:[更新] 以保存更改。
. 导航到 `Subscribers` 选项卡，并根据需要选择或取消选择用户。



[[delete_channels]]
== 删除通道

可以从命令提示符删除供应商软件通道。

.过程：升级删除供应商通道
. 在 {productname} 服务器上，在命令提示符下以 root 身份列出可用的供应商通道，并记下您要删除的通道：
+
----
mgr-sync list channels
----
. 删除通道：
+
----
spacewalk-remove-channel -c <channel-name>
----

ifeval::[{mlm-content} == true]
* 有关手动删除通道的更多信息，请参见 xref:administration:removing-channels.adoc[]。
endif::[]

* 有关删除自定义通道的信息，请参见 xref:administration:custom-channels.adoc[]。
