[[patch-management]]
= 补丁管理
:description: 学习如何有效管理补丁，使用 SUSE Multi-Linux Manager 的功能来同步和传播收回的补丁跨通道。
:revdate: 2022-02-17
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

本章包含有关补丁管理的各个主题。


== 已收回补丁


当供应商发布新补丁时，可能会出现该补丁在某些测试未能发现的情形下产生不良副作用（影响安全性和稳定性）。当这种情况发生时（非常少见），供应商通常会发布补丁，这可能需要几个小时或几天，具体取决于该供应商内部的流程。

SUSE 引入了一个称为\\``已收回补丁``的新机制 (2021)，可以通过将此类补丁的建议状态设置为\``已收回``（而不是\\``最终``或\``稳定``）来近实时地撤消这些补丁。

[IMPORTANT]
====
当补丁的建议状态属性设置为 "收回" 时，该补丁被视为 "收回"。
当软件包属于 "收回" 补丁时，该软件包被视为 "收回"。
====

收回的补丁或软件包无法在具有 {productname} 的系统上安装。安装已撤回的软件包的唯一方法，是手动使用 `zypper install` 并指定确切的软件包版本。
例如：
----
zypper install vim-8.0.1568-5.14.1
----

补丁和软件包的收回状态通过 icon:times-circle[role="red"] 图标显示在 {webui} 中的 {productname} 上。例如，见：

* 通道中软件包的列表
* 通道中补丁的列表

当安装在系统上的补丁或软件包被收回时，icon:times-circle[role="red"] 图标也会显示在该系统的已安装软件包列表中。{productname} 不提供降级此类补丁或软件包的方法。


=== 通道克隆
使用克隆的通道时，必须小心将原始通道的已收回建议状态传播到克隆版本。

将供应商通道克隆到组织中时，也会克隆通道补丁。

当供应商在通道中收回补丁并且 {productname} 同步此通道（例如，通过夜间作业）时，"收回" 属性不会传播到克隆的补丁，并且订阅克隆通道的客户端看不到该属性。要将该属性传播到您的克隆通道，请使用以下方法之一：

* 补丁同步（menu:软件[管理> 克隆通道> 补丁> 同步]）。此功能允许您将克隆通道中补丁的属性与其原始补丁对齐。
* 内容生命周期管理。有关内容生命周期管理中克隆通道的更多信息，请参见 xref:client-configuration:channels.adoc[]。


=== 补丁共享

当您在组织中创建多个供应商通道克隆时，补丁不会被多次克隆，而是在克隆通道之间共享。因此，当您同步克隆补丁（无论是使用补丁同步功能还是使用上述内容生命周期管理）时，所有使用该克隆补丁的通道都会观察到该更改。

.示例：
. 考虑两个内容生命周期管理项目 `prj1` 和 `prj2`
. 这两个项目都有 2 个环境 `dev` 和 `test`
. 这两个项目都有一个设置为源通道的供应商通道
. 此场景中的所有通道（总共四个克隆的通道）与供应商通道的最新状态相一致
. 供应商收回源通道中的某个补丁，夜间作业将此补丁同步到您的 {productname}。
. 四个通道都看不到这种变化，因为它们使用的是补丁克隆版本，而不是直接使用该补丁。
. 在您同步补丁（构建这两个项目中的任何一个，或者对四个克隆通道中的任何一个使用补丁同步功能）后，由于补丁共享的原因，*所有*克隆的通道都会发现该补丁已收回。
