[[subscription-matching]]
= 订阅匹配
:description: 有效地使用 SUSE Multi-Linux Manager 中的订阅匹配功能配置和管理您的 SUSE 产品订阅，该功能提供了一个
:revdate: 2024-11-29
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

您的 {suse} 产品需要订阅，这些订阅由 {scclongform} ({scc}) 管理。{productname} 每晚运行报告，检查所有注册客户端的订阅状态与您的 {scc} 账户的匹配情况。
该报告提供有关哪些客户端消耗了哪些订阅、您剩余和可用的订阅数量，以及哪些客户端没有当前订阅的信息。

导航到 menu:审计[订阅匹配] 以查看报告。

`Subscriptions Report` 选项卡提供有关当前和即将到期的订阅的信息。

`Unmatched Products Report` 选项卡提供没有当前订阅的客户端列表。
这包括无法匹配的客户端，或当前未在 {productname} 注册的客户端。
该报告包括产品名称和仍未匹配的系统数量。

`Pins` 选项卡允许您将单个客户端与相关订阅关联。
如果订阅管理器未能成功自动将客户端与订阅关联，这一点尤其有用。

`Messages` 选项卡显示在匹配过程中由订阅匹配器生成的所有消息。
它们提供信息以帮助理解结果并改善匹配。

您还可以下载 .csv 格式的报告，或从 `/var/lib/spacewalk/subscription-matcher/` 目录中的命令提示符访问它们。

默认情况下，订阅匹配器每天在午夜运行。
要更改此设置，请导航至 menu:管理[任务计划] 并单击 `gatherer-matcher-default`。
根据需要更改计划，然后单击 btn:[更新计划]。

由于报告只能将当前客户端与当前订阅匹配，您可能会发现匹配情况会随时间变化。
同一客户端并不总是匹配同一订阅。
这可能是由于新客户端的注册或取消注册，或由于订阅的增加或到期。

订阅匹配器会自动尝试减少未匹配产品的数量，但受限于您账户中订阅的条款和条件。
然而，如果您有不完整的硬件信息、未知的虚拟机主机分配或在未知公有云中运行的客户端，匹配器可能会显示您没有足够的可用订阅。
始终确保您在 {productname} 中包含有关客户端的完整数据，以帮助确保准确性。


[IMPORTANT]
====
订阅匹配器并不总是准确地匹配客户端和订阅。
它并不打算替代审计。
====



== 将客户端关联到订阅



如果订阅匹配器没有自动将特定客户端与正确的订阅匹配，您可以手动固定它们。
当您创建一个固定时，订阅匹配器更倾向于将特定订阅与给定系统或系统组匹配。

然而，匹配器并不总是尊重固定。
这取决于订阅是否可用，以及该订阅是否可以应用于客户端。
此外，如果固定导致的匹配违反了订阅的条款和条件，或者如果匹配器检测到忽略固定后更准确的匹配，则会忽略固定。

要添加新固定，请单击 btn:[添加固定]，并选择要固定的客户端。

[IMPORTANT]
====
我们不建议定期使用固定，或对大量客户端使用。
订阅匹配器工具通常对大多数安装足够准确。
====
