== Prepare {sl-micro} {microversion} Host


=== Download the installation media

.Procedure: Downloading the installation media
[role=procedure]
____

. Locate the {sl-micro} {microversion} installation media at https://www.suse.com/download/sle-micro/, and download the appropriate media file.

. Prepare a DVD or USB flash drive with the downloaded [filename]``.iso`` image for installation.

____


=== Install {sl-micro} {microversion}

.Procedure: Installing {sl-micro} {microversion}
[role=procedure]
____

. Insert the DVD or USB flash drive (USB disk or key) containing the installation image for {sle-micro} {microversion}.

. Boot or reboot your system.

. Use the arrow keys to select [systemitem]``Installation``.

. Adjust Keyboard and language.

. Click the [systemitem]``checkbox`` to accept the license agreement.

. Click [systemitem]``Next`` to continue.

. Skip the registration. The {sl-micro} {microversion} entitlement is included within the {productname} entitlement.

. Click btn:[Next] to continue.

. On the [systemitem]``NTP Configuration`` page click btn:[Next].

. On the [systemitem]``Authentication for the System`` page enter a password for the root user.
  Click btn:[Next].

. On the [systemitem]``Installation Settings`` page click btn:[Install].

____

This concludes installation of {sl-micro} {microversion} and {productname} {productnumber} as an extension.
For more information about preparing your machines (virtual or physical), see the link:https://documentation.suse.com/sle-micro/6.1[{sl-micro} Deployment Guide].


=== Update the system

.Procedure: Updating the system
[role=procedure]
____
. Log in as *root*.

. Run **transactional-update**:

+

[source, shell]
----
transactional-update
----

. Reboot.

____


[IMPORTANT]
====
{sl-micro} is designed to update itself automatically by default and will reboot after applying updates.
However, this behavior is not desirable for the {productname} environment.
To prevent automatic updates on your server, {productname} disables the transactional-update timer during the bootstrap process.

If you prefer the {sl-micro} default behavior, enable the timer by running the following command:

[source, shell]
----
systemctl enable --now transactional-update.timer
----
====
