= SUSE Manager {payg} WebUI setup 


== Requirements

{productname} must be setup and running on AWS. For more information on finding and setting up {productname}, see: xref:public-cloud-guide/payg/payg-public-cloud-images.adoc[Public Cloud Images]


.The instance-flavor-check tool and {payg} schedule check 
[NOTE]
====
instance-flavor-check Tool::
The **instance-flavor-check** tool is an essential component that comes pre-installed by default. Its presence is crucial, as it determines the status of PAYG instances. When invoked, this tool identifies and categorizes the system as a PAYG instance. By default this tool is configured to run on a schedule named **update-payg-default**.

update-payg-default schedule task::
Navigate to the menu:Admin[Task Schedules] to find the **update-payg-default** task. By default, this task is set to run at 10-minute intervals. Its primary function is to monitor the presence of all running PAYG instances by executing the **instance-flavor-check tool**.
====


== Login to the Webui

.Procedure: Login

. Login to the SUSE Manager Server WebUI.
The username is **admin** the password will be the **Instance ID** on AWS EC2.

. Select menu:Admin[Setup Wizard].


== Configure the {payg} credentials and product list

[NOTE]
====
On a fresh server, the organization credentials table listed at menu:Admin[Setup Wizard > Organization Credentials] and the Products table listed under menu:Admin[Setup Wizard > Products] will be empty.
====

.Procedure: Adding PAYG Credentials and Refreshing the Product List

. Visit the menu:Admin[Setup Wizard > Pay-as-you-go] tab to view and manage {payg} credentials.

. After filling in the credentials, navigate to the menu:Admin[Products] tab and click btn:[Refresh].

. Once the refresh completes the following products are listed:
* SUSE Manager Proxy
* SUSE Manager Server
* Free products 

[IMPORTANT]
====
.Ubuntu and Debian
Ubuntu and Debian are not currently supported by our RMT servers; however, we have plans to introduce support for these platforms on cloud based services in the near future.

.Red Hat Linux Enterprise Clients
SUSE Manager offers support for Red Hat Linux Enterprise Clients, but it's important to note that content still needs to be added manually and isn't available through the cloud-based RMT service.

See: xref:client-configuration:registration-overview-redhat.adoc[Red Hat Client Registration]
====


== Adding additional {payg} SUSE products as clients

.Procedure: Deploying {payg} SUSE Linux Enterprise instances in AWS

. Search for the {sle} {payg} instance on AWS.

. Configure the instance as needed.

. Start the instance.

For more information on using {suse} products in the public cloud see: link:https://documentation.suse.com/sle-public-cloud/all/html/public-cloud/cha-intro.html[SUSE Linux Enterprise Public Cloud Guide]


.Procedure: Connecting {payg} SUSE Linux Enterprise instances to {productname}

. Return to the SUSE Manager Server WebUI.

. Navigate to menu:Admin[Setup Wizard > Pay-as-you-go] and click the btn:[+Add Pay-as-you-go] button.

. Add a description.

. Complete the instance SSH connection data:
  * Host: `URL of the machine`
  * SSH Port: `22`
  * User: `<user>`
  * Password: `<password>`
  * SSH Private Key

. Click btn:[Create] and wait for the sync to finish.

. Proceed to menu:Admin[Setup Wizard > Products] to access your {payg} SUSE Linux Enterprise products.

