= Initial Preparation and Configuration of the AWS Image

This section covers initial preparation and configuration of the image on {aws}.

.The IAM role
[IMPORTANT]
====
To ensure seamless operation, proper AWS permissions for the IAM role are essential. This role must be attached after the instance is launched; attaching it beforehand will result in a disconnection of {productname} after one hour. You can pre-create the role and then select it from the existing btn:[IAM role] dropdown during the instance configuration process.

A role can be assigned to a running instance through the following steps: menu:Actions[Security > Modify IAM-role].

For detailed information on IAM roles, see:  link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html[docs.aws.amazon.com/IAM]
====

.Procedure: Configuring your {productname} instance

. Select the AMI image and provide a meaningful **name** for your server.
  Review the details and pricing information provided. 

. You have the option to configure additional instance details in subsequent steps, such as storage, tags, security groups, and the required **IAM role**.

.. The image automatically suggests a **default CPU configuration**.

.. Choose an existing key pair or create a new one to grant access to the instance.

.. Your organization should provide the necessary security groups and network configuration.

.. If an IAM role has been previously created, you can attach it by selecting it from the Existing menu:IAM role[] dropdown. Otherwise, attach this role after the instance has been launched.

.. Create the following partitions

* **200 GB** for the root partition
 
* **500 GB** for spacewalk storage
 
* **80 GB** for the database. 
+
For more information see: xref:public-cloud-guide/payg/payg-aws-requirements.adoc[AWS requirements]

.. Follow the prompts from AWS to complete the configuration as needed.

. After reviewing your configuration click the btn:[Launch instance] dropdown.

. Click on the btn:[Launch Instances] button.

. You will be redirected to the **EC2** Dashboard.

. Verify that the instance has successfully launched by selecting menu:Instances[] on the left sidebar. The {productname} {payg} instance should be running in the main content area.

[NOTE] 
.Usage and Costs
====
Keep in mind that since this is a {payg} image, you will be billed according to your actual usage, including the number of systems you **manage** and **monitor** with this instance. It's essential to regularly track and review your usage to prevent unexpected costs and ensure alignment with your needs.
====

