= {payg} limitations

== Onboarded {byos} instances without SCC credentials

Valid SCC credentials are needed to manage {byoslongform} ({byos}) instances of SUSE products in {productname} {payg}. 
This applies to all SUSE products except {productname} Proxy {byos}. 
Without any SCC credentials, {productname} {payg} will not allow onboarding any of the mentioned {byos} instances.
The user will get an error.

There is a possibility that the user has valid SCC credentials set with already synced-up channels and the {byos} onboarded, but at some point decides to delete those credentials. 

In the scenario of having already onboarded {byos} instances but no SCC credentials set, the following restrictions apply:

* A warning message will be shown to the user to let them know that they will not be able to manage those instances.
* Non-compliant {byos} instances will not be able to be managed neither through {salt} or Salt-SSH. 
  This applies to individual server management, SSM and action-chains. 
  When dealing with several servers at once, as long as there is one non-compliant {byos} instance among them, the entire action/action-chain will be aborted for all servers.
* Non-compliant {byos} instances will not be able to access any repository hosted in {productname} {payg} as long as SCC credentials are not set. 
  {productname} {payg} will return ``HTTP 401 Unauthorized`` until the situation is amended, that is trying to install or upgrade packages using zypper from those machines directly will not work.
