[[client-cfg-autoinstallation-methods]]
= Introduction
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]

// PDF entities
ifdef::backend-pdf[]
include::../_partials/entities.adoc[]
endif::[]

.Autoinstallation Types: {ay} and Kickstart
[NOTE]
====
In the following section, {ay} and {ay} features apply for {sle} client systems only.

For {rhela} systems, use Kickstart and Kickstart features.
====

//TODO We need to add an alternative explanation for automating salt installations. This is what Salt was designed for. We should provide examples to clarify. The following admon comes acrross as "negative".

.Auto-Installing Salt Minions Currently Not Supported
[IMPORTANT]
====
This procedure will work for traditionally  managed systems (system type [systemitem]``management``).

Autoinstallation is not currently available for systems using Salt (system type [systemitem]``salt``).
====

{ay} and Kickstart configuration files allow administrators to create an environment for automating otherwise time-consuming system installations, such as multiple servers or workstations. {ay} files have to be uploaded to be managed with {productname}.
Kickstart files can be created, modified, and managed within the {productname} Web interface.

{productname} also features the Cobbler installation server.
For more information on Cobbler, see:

//TODO Add link to cobbler documentation.


pass:c[xref:FILENAME.adoc#advanced.topics.cobbler[]].

