[[ref-spacecmd-user]]
= user_

The following spacecmd functions are available managing users.

user_adddefaultgroup::
Add a default group to an user account.
+
----
usage: user_adddefaultgroup USER <GROUP ...>
----
user_addgroup::
Add a group to an user account.
+
----
usage: user_addgroup USER <GROUP ...>
----
user_addrole::
Add a role to an user account.
+
----
usage: user_addrole USER ROLE
----
user_create::
Create an user.
+
----
usage: user_create [options]

options:
  -u USERNAME
  -f FIRST_NAME
  -l LAST_NAME
  -e EMAIL
  -p PASSWORD
  --pam enable PAM authentication
----
user_delete::
Delete an user.
+
----
usage: user_delete NAME
----
user_details::
Show the details of an user.
+
----
usage: user_details USER ...
----
user_disable::
Disable an user account.
+
----
usage: user_disable NAME
----
user_enable::
Enable an user account.
+
----
usage: user_enable NAME
----
user_list::
List all users.
+
----
usage: user_list
----
user_listavailableroles::
List all available roles for users.
+
----
usage: user_listavailableroles
----
user_removedefaultgroup::
Remove a default group from an user account.
+
----
usage: user_removedefaultgroup USER <GROUP ...>
----
user_removegroup::
Remove a group to an user account.
+
----
usage: user_removegroup USER <GROUP ...>
----
user_removerole::
Remove a role from an user account.
+
----
usage: user_removerole USER ROLE
----
user_setemail::
Set an user accounts email field.
+
----
usage: user_setemail USER EMAIL
----
user_setfirstname::
Set an user accounts first name field.
+
----
usage: user_setfirstname USER FIRST_NAME
----
user_setlastname::
Set an user accounts last name field.
+
----
usage: user_setlastname USER LAST_NAME
----
user_setpassword::
Set an user accounts name prefix field.
+
----
usage: user_setpassword USER PASSWORD
----
user_setprefix::
Set an user accounts name prefix field.
+
----
usage: user_setprefix USER PREFIX
----