[[config-modules]]
= Configuration Modules

[IMPORTANT]
====
This feature is a technology preview.
====

You can use Salt execution and state modules to configure your {productname} Server.
These configuration modules can be used directly or using SLS files.
They are are especially useful if you have multiple {productname} Servers, for example in Hub installations, but they are also useful for smaller installations.

For more information about using Hub, see xref:large-deployments:multi-server.adoc[].

You can use configuration modules to configure:

* Organizations
* Users
* User permissions
* System groups

More configuration modules are planned to be released in the future.

* For more information about Salt execution modules and how to use them, see https://docs.saltstack.com/en/latest/topics/tutorials/modules.html.
* For more information about Salt state modules, see https://docs.saltstack.com/en/latest/topics/tutorials/starting_states.html.



== Install Configuration Modules

The Salt modules are available in the [path]``uyuni-config-modules`` package.
On the {productname} Server, at the command prompt, as root, use this command:

----
zypper in uyuni-config-modules
----

This package also installs detailed API descriptions, indications on pillar settings, and examples.
When you have installed the package, navigate to [path]``/usr/share/doc/packages/uyuni-config-modules/``.
