[[custom-states]]
= Custom Salt States

You can create your own custom Salt states with {productname} as centrally-managed configuration channels.
Custom states are stored as Salt state files on the {productname} Server with a ``.sls`` extension, in the [path]``/srv/susemanager/salt/`` directory.



== Create a New Custom Salt Channel

You can use the {productname} {webui} to create and edit custom Salt state files.
You must create a state channel first, with an initial state named ``init.sls``.
The ``init.sls`` file is used to reference all other state files within the channel.
The custom states that you create using the {webui} are stored on the {productname} Server in the the [path]``/srv/susemanager/salt/<organization>/`` directory.

After the channel is created with an ``init.sls`` file, you can write additional state files in the {webui}.
Alternatively, you can upload existing state files to use within your state channel, or import them from other channels or clients.



.Procedure: Creating a Custom Salt Channel and Initial State
. In the {productname} {webui}, navigate to menu:Configuration[Channels].
. Click btn:[Create State Channel].
. In the [guimenu]``Name`` field, type a name for your state.
. In the [guimenu]``Label`` field, type a label.
  Use alphanumeric characters, hyphens, and underscores.
  Do not use spaces.
. In the [guimenu]``Description`` field, type a short description of the configuration your state performs.
. In the [guimenu]``SLS Contents`` field, type the contents of your ``init.sls`` state.
  Ensure your file starts by specifying the source of the managed file, using this syntax:
+
----
file.managed:
  - source: salt://<org_name>/<channel_name>/etc/<filename>
----
+
 Example custom state files are given later in this section.
. Click btn:[Update Channel] to save your state.



.Procedure: Adding Additional Files to a Custom State Channel
. In the {productname} {webui}, navigate to menu:Configuration[Channels].
. Click the name of the channel you want to add files to.
. To create a new file, click btn:``Create configuration file`` and type the contents of the file.
. To upload an existing file, click btn:``Upload Configuration Files`` and select the file to upload.
. To copy an existing file, click btn:``Import a File from Another Channel or System`` and select the file to copy.



.Procedure: Editing a Custom Salt State
. In the {productname} {webui}, navigate to menu:Configuration[Channels].
. Click btn:[View/Edit <filename>.sls File].
. Make your changes to the file
. Click btn:[Update Configuration File] to save your state.

You can also manage revisions, compare the state to others in your organization, and download the ``.sls`` file from this dialog.



.Procedure: Assigning a Client to a Custom Salt State
. In the {productname} {webui}, navigate to menu:Configuration[Channels].
. Click the name of the state you want to assign a client to.
. Navigate to the menu:Systems[Target Systems] tab.
. Check the clients you want to assign.
. Click btn:[Subscribe systems].



== Example Custom State Files

This section contains some example custom state files.
Use these as a basis for writing your own custom states.



.Example: Initial State File

----
file.managed:
  - source: salt://example_org/example_channel/etc/motd
[
  FIXME: reference other file here somehow
]
----



.Example: Custom State File

----
install required packages:
  pkg.installed:
    - pkgs:
      - lsof
    - failhard: True
update packages:
  module.run:
    - name: pkg.upgrade
    - failhard: True
check if reboot is needed:
  salt.set_reboot_needed:
    - failhard: True
reboot:
   salt.reboot_if_needed:
     - failhard: True
----



== Custom State to Trust a GPG Key

By default, operating systems trust only their own GPG keys when they are installed, and do not trust keys provided by third party packages.
The clients can be successfully bootstrapped without the GPG key being trusted.
However, you cannot install new client tool packages or update them until the keys are trusted.

Salt clients are set to trust {suse} tools channels GPG keys when they are bootstrapped.
For all other clients and channels, you need to manually trust third party GPG keys.

If you are bootstrapping Salt clients from the {productname} {webui}, you can use a custom Salt state to trust the GPG key.



.Procedure: Trusting a GPG Key With a Custom Salt State
. On the {productname} Server, at the command prompt, check the contents of the [path]``/srv/www/htdocs/pub/`` directory.
  This directory contains all available public keys.
  Take a note of the key that applies to the channel assigned to the client you are registering.
. In the {productname} {webui}, navigate to menu:Configuration[Channels].
. Click btn:[Create State Channel].
. In the [guimenu]``Name`` field, type a name for your state.
  For example, ``GPG Key Trusts``
. In the [guimenu]``Label`` field, type a label.
  For example, ``GPG_Key_Trusts``
. In the [guimenu]``Description`` field, type a short description of the configuration your state performs.
  For example, ``Trusts GPG Keys for CentOS``.
. In the [guimenu]``SLS Contents`` field, create a state to retrieve the appropriate key from the {productname} Server and trust it on the client.
  For example FIXME:
+
----
cmd.run:
  - salt '*' gpg.import_key filename='/srv/www/htdocs/pub/centos8-gpg-pubkey-05B555B38483C65D.key'
  - salt '*' gpg.trust_key keyid='centos8-gpg-pubkey-05B555B38483C65D.key' trust_level='trusted'
----
+
. Click btn:[Update Channel] to save your state.
. Navigate to menu:Configuration[Channels] and click the name of the state you want to assign a client to.
. Navigate to the menu:Systems[Target Systems] tab and check the clients you want to assign.
. Click btn:[Subscribe systems].
 When the configuration file is next run on the client, the GPG key is trusted.

Alternatively, you manage your GPG keys from your own repository hosted on an external file management system.
