[[monitoring-formula]]
= Monitoring Formula

The monitoring services in {productname} are configured using formulas with forms.
The package is installed by default, and contains these formulas:

* Grafana
* Prometheus
* Prometheus Exporters


For more information about using monitoring, see xref:administration:monitoring.adoc[].


.Procedure: Configuring the Grafana Formula
. Navigate to the menu:Formulas[Grafana] tab, and set these parameters in the [guimenu]``Grafana`` section:
* Check the [guimenu]``Enabled`` box to enable Grafana visualizations.
* In the [guimenu]``Default admin user`` field, type the name of the default Grafana user.
* In the [guimenu]``Default admin password`` field, enter a password for the default user.
    Alternatively, click btn:[Generate new password] to generate a password and fill the field.
. For each Prometheus data source you want to use, in the menu:Datasources[Prometheus] section, click btn:[+], and set these parameters:
* In the [guimenu]``Datasource name`` field, type a name to identify the data source.
* In the [guimenu]``Prometheus URL`` field, type the location of the Prometheus server, and append port ``9090``.
    For example, ``http://example.com:9090``.
. In the [guimenu]``Dashboards`` section, check the dashboards you want to use:
* [guimenu]``Uyuni server dashboard``
* [guimenu]``Uyuni clients dashboard``
* [guimenu]``PostgreSQL dashboard``
* [guimenu]``Apache HTTPD dashboard``
* [guimenu]``Kubernetes cluster dashboard``
* [guimenu]``Kubernetes etcd dashboard``
* [guimenu]``Kubernetes namespaces dashboard``
. Click btn:[Save Formula] to save your configuration.



.Procedure: Configuring the Prometheus Formula
. Navigate to the menu:Formulas[Prometheus] tab, and set these parameters in the [guimenu]``Prometheus`` section:
* Check the [guimenu]``Enabled`` box to enable Prometheus monitoring.
* In the [guimenu]``Scrape interval`` field, type the frequency of data scraping, in seconds.
    For example, ``15`` will scrape data every fifteen seconds.
* In the [guimenu]``Evaluation interval`` field, type the FIXME, in seconds.
    For example, ``15`` will FIXME every fifteen seconds.
. In the [guimenu]``Uyuni Server`` section, set these parameters:
* Check the [guimenu]``Enabled`` box to enable monitoring on this server.
* Check the [guimenu]``Autodiscover clients`` box to enable Prometheus to automatically find and monitor new clients when they are added to the server.
* In the [guimenu]``Username`` field, type the user name of the Prometheus account on the server.
* In the [guimenu]``Password`` field, type the password of the Prometheus account on the server.
. In the [guimenu]``Alerting`` section, set these parameters:
* Check the [guimenu]``Enable local Alertmanager service`` box to enable the alert manager service.
* Check the [guimenu]``Use local Alertmanager`` box to use the local alert manager service.
. For each alert manager you want to use, in the menu:Alerting[Alertmanagers] section, click btn:[+], and set these parameters:
* In the [guimenu]``IP Address:Port`` field, type the location of the alert manager target, including the port number.
//For example, ``FIXME``.
. To use a rule file, in the menu:Alerting[Rule Files] section, click btn:[+], and set these parameters:
* In the [guimenu]``Rule Files`` field, type the location of the rule file you want to use.
//For example, ``FIXME``.
. To add a custom scrape configuration, in the [guimenu]``User defined scrape configurations`` section, click btn:[+], and set these parameters:
* In the [guimenu]``Job name`` field, type a unique job name for your configuration.
* In the [guimenu]``Files`` field, type the location pattern of file service discovery files you want to use.
  For more information, see the upstream documentation https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config.
. Click btn:[Save Formula] to save your configuration.




.Procedure: Configuring the Prometheus Exporters Formula
. Navigate to the menu:Formulas[Prometheus Exporters] tab, and set these parameters in the [guimenu]``Node Exporter`` section:
* Check the [guimenu]``Enabled`` box to enable the node exporter.
* In the [guimenu]``Arguments`` field, type any customized arguments for this exporter.
    For example, ``--web.listen-address=":9100"``.
. In the [guimenu]``Apache Exporter`` section:
* Check the [guimenu]``Enabled`` box to enable the Apache exporter.
* In the [guimenu]``Arguments`` field, type any customized arguments for this exporter.
    For example, ``--telemetry.address=":9117"``.
. In the [guimenu]``Postgres Exporter`` section:
* Check the [guimenu]``Enabled`` box to enable the PostreSQL exporter.
* In the [guimenu]``Data source Name`` field, type the name of the data source to use.
* In the [guimenu]``Arguments`` field, type any customized arguments for this exporter.
    For example, ``--web.listen-address=":9187"``.
. Click btn:[Save Formula] to save your configuration.



When you have completed and saved all the forms, apply the highstate.

For more information about using monitoring, see xref:administration:monitoring.adoc[].
