[[yomi-formula]]
= Yomi Formula

Yhe Yomi (yet one more installer) installer for {suse} and openSUSE operating systems is configured using formulas with forms.

The ``yomi-formula`` package provides these formulas:

* Yomi
* Yomi Storage
* Yomi Bootloader
* Yomi Software
* Yomi Services
* Yomi Users


.Procedure: Install the Yomi Formulas with Forms
. On the {productname} Server, at the command prompt, as root, install the ``yomi-formula`` package:
+
----
zypper in yomi-formula
----
. In the {susemgr} {webui}, open the details page for the Salt master, and navigate to the Formulas tab.
. Check the [guimenu]``Installer`` box, and click btn:[Save].
. Apply the highstate.



.Procedure: Configuring the Yomi Formula
. Navigate to the menu:Formulas[Yomi] tab, and set these parameters in the [guimenu]``General Configuration`` section:
* Check the [guimenu]``Events`` box to allow monitoring.
* In the [guimenu]``Reboot`` field, select [systemitem]``yes`` to instruct the client to reboot after installation.
* Check the [guimenu]``Snapper`` box if you are using the btrfs file system on the client.
* In the [guimenu]``Locale`` field, select the region and encoding for systemd to use on the client (for example: [systemitem]``en_US.utf8`` for American English and UTF-8).
* In the [guimenu]``Keymap`` field, select the appropriate keyboard layout (for example: [systemitem]``us`` for an American keyboard layout).
* In the [guimenu]``Timezone`` field, select the timezone for the client to use (for example: [guimenu]``America/New_York`` for EST).
* In the [guimenu]``Hostname`` field, enter the hostname for the client to use.
Leave this blank if you are using DHCP to provide the hostname.
* In the [guimenu]``Machine Id`` field, enter a machine identification number for the client.
Leave this blank to have systemd generate one automatically.
* In the [guimenu]``Target`` field, enter a systemd target unit.
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.



.Procedure: Configuring the Yomi Storage Formula
. Navigate to the menu:Formulas[Yomi Storage] tab, and set these parameters in the menu:Partitions[Config] section:
* In the [guimenu]``Labels`` field, select the default partition table type to use.
* In the [guimenu]``Initial Gap`` field, select the default amount of space to leave before each partition.
For example: [systemitem]``1{nbsp}MB``, or use [systemitem]``0`` to leave no space between partitions.
. For each device that you want to create, in the menu:Partitions[Devices] section, click btn:[+], and set these parameters:
* In the [guimenu]``Device`` field, type the mount point for the device.
For example, [systemitem]``/dev/sda``.
* In the [guimenu]``Label`` field, select the partition table type to use, if it is different from the default label you selected.
* In the [guimenu]``Initial Gap`` field, select the amount of space to leave before each partition, if it is different from the default space you specified.
. For each partition that you want to create, in the menu:Partitions[Devices > Partitions] section, click btn:[+], and set these parameters:
* In the [guimenu]``Partition Number`` field, enter a number for the partition.
The number you enter here is be appended to the device name to identify the partition.
For example, partition number [systemitem]``1`` on device [systemitem]``/dev/sda`` can be identified as [systemitem]``/dev/sda1``.
* In the [guimenu]``Partition Name`` field, enter a name for the partition.
Leave this blank if you have entered a partition number in the previous field.
* In the [guimenu]``Partition Size`` field, enter a size for the partition.
For example: [systemitem]``500{nbsp}MB``.
Use [systemitem]``rest`` to use all the remaining free space.
. For each file system that you want to create, in the [guimenu]``Filesystems`` section, click btn:[+], and set these parameters:
* In the [guimenu]``Partition`` field, select the partition to create the file system on.
For example, [systemitem]``/dev/sda1``.
* In the [guimenu]``Filesystem`` field, select the filesystem type to create.
* In the [guimenu]``Mountpoint`` field, type the mount point for the filesystem.
For example: [systemitem]``/`` for root.
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.

[[NOTE]]
====
If you want to use LVM or RAID on your devices, click btn:[+] in the appropriate sections, and complete the details for your environment.
====



.Procedure: Configuring the Yomi Bootloader Formula
. Navigate to the menu:Formulas[Yomi Bootloader] tab, and set these parameters in the [guimenu]``Bootloader`` section:
* In the [guimenu]``Device`` field, type the mount point for the bootloader.
For example, [systemitem]``/dev/sda``.
* In the [guimenu]``Timeout`` field, select the number of seconds grub will wait before booting the default image.
* In the [guimenu]``Kernel`` field, type any additional kernel parameters you want to use.
Any kernel parameters you add here will be appended to the [systemitem]``GRUB_CMDLINE_LINUX_DEFAULT`` line during boot.
* In the [guimenu]``Terminal`` field, type the terminal to use for both terminal input and output.
* In the [guimenu]``Serial Command`` field, type parameters for using the serial port.
Use this only if you are using the serial console as the default terminal.
* In the [guimenu]``Gfxmode`` field, type the resolution to use for the graphical terminal.
Use this only if you are using the graphical console as the default terminal.
* Check the [guimenu]``Theme`` box to use GRUB2 default branding package.
* Check the [guimenu]``Disable OS Prober`` box to disable using the OS prober to discover other installed operating systems.
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.



.Procedure: Configuring the Yomi Software Formula
. Navigate to the menu:Formulas[Yomi Software] tab, and set these parameters in the menu:Software[Configuration] section:
* Check the [guimenu]``Minimal`` box to use a minimal installation, which only installs packages listed as ``Required``.
. For each repository that you want to add, in the menu:Software[Repositories] section, click btn:[+], and set these parameters:
* In the [guimenu]``Repository Name`` field, type a name for the repository.
* In the [guimenu]``Repository URL`` field, type the location of the repository.
. To add packages from each repository, in the menu:Software[Packages] section, click btn:[+], and set these parameters:
* In the menu:Software[Packages] field, type the names of the packages to install, or type a pattern to search for the appropriate packages.
// For example, [systemitem]``FIXME``, to search for FIXME.
. In the menu:Software[Image] section, set these parameters:
* In the [guimenu]``Image URL`` field, type the location of the operating system ISO image to use.
* In the [guimenu]``Md5`` field, type the MD5 hash to use to verify the ISO.
. In the menu:SUSEConect[Config] section, set these parameters:
* In the [guimenu]``Registration Code`` field, type the registration code for the client you are installing.
You can obtain this code from {scc}.
* In the [guimenu]``Email`` field, type the administrator email address to use.
* In the [guimenu]``Url`` field, type the address of the registration server to use.
For example, use [systemitem]``https://scc/suse.com``, to register with {scc}.
* In the [guimenu]``Version`` field, type the version of the product you are registering.
. For each product that you want to register, in the menu:SUSEConnect[Products] section, click btn:[+], and set these parameters:
* In the [guimenu]``Product`` field, type each product you want to register.
For example, [systemitem]``<product_name>/1.1/x86``, for version 1.1 with {x86} architecture.
* In the menu:SUSEConnect[Packages] field, type the names of the packages to install, or type a pattern to search for the appropriate packages.
// For example, [systemitem]``FIXME``, to search for FIXME.
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.



.Procedure: Configuring the Yomi Services Formula
. Navigate to the menu:Formulas[Yomi Services] tab, and set these parameters:
* Check the [guimenu]``Install salt-minion`` box to install and configure the client as a Salt client.
. For each service you want to enable, in the menu:Services[Enabled] section, click btn:[+], and set these parameters:
* In the [guimenu]``Service`` field, type the name of the service to enable.
. For each service you want to disable, in the menu:Services[Disabled] section, click btn:[+], and set these parameters:
* In the [guimenu]``Service`` field, type the name of the service to disable.
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.

////
 Example content from Yomi chapter below this line. --LKB 2020-03-26






Yomi Users::

This form sets out the system users.
In this example, we have a single root user.
To provide a password, you must use the hashed version of the password, not the plain text.
This behavior is set to be changed in future versions of Yomi.

* User 1:
** Username: root
** Password Hash: $1$wYJUgpM5$RXMMeASDc035eX.NbYWFl0

////