[[salt.gs.guide.term.overview]]
= Salt Terminology
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]
// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]



Grains::
Grains provide information about the hardware of a minion.
For example, the operating system, IP addresses, network interfaces, memory, etc.
When running a Salt command from keep in mind any modules and functions called are run locally from the system being called.
Salt modules are stored on minions and master within the following directory:
+

----
/usr/lib/python2.7/site-packages/salt/
----
+
List all available grains with the [command]``grains.ls`` function:
+

----
salt '*' grains.ls
----
+
List collected grain system data by using the [command]``grains.ls`` function:
+

----
salt '*' grains.items
----
+
For more information on grains, see https://docs.saltstack.com/en/latest/topics/grains/.

States::
States are templates which place systems into a known configuration, for example which applications and services are installed and running on those systems.
States are a way for you to describe what each of your systems should look like.
Once written, states are applied to target systems automating the process of managing and maintaining a large numbers of systems into a known state.
For more information on states, see https://docs.saltstack.com/en/latest/topics/tutorials/starting_states.html.
+

[WARNING]
.Updating Salt
====
Do not update [package]#salt# itself using Salt states.
First update all other system packages using Salt states then update [package]#salt# as a separate stand-alone step from the {productname} {webui}.
====
+

Pillar::
Pillars unlike grains are created on the master.
Pillar files contain information about a minion or group of minions.
Pillars allow you to send confidential information to a targeted minion or group of minions.
Pillars are useful for sensitive data, configuration of minions, variables, and any arbitrary data which should be defined.
For more information on pillars, see https://docs.saltstack.com/en/latest/topics/tutorials/pillar.html.

Beacons::
Beacons allow an admin to use the event system in Salt to monitor non-Salt processes.
Minions may use beacons to hook into many types of system proceses for constant monitoring.
Once a targeted monitored activity occurs an event is sent on the Salt event bus that may be used to trigger a reactor.
+

.Enabling Beacons
IMPORTANT: To work with beacons on Salt minions the package python-pyinotify must be installed for SUSE systems.
For RES systems install python-inotify.
This package is not installed automatically during the salt minion package installation.
+

[NOTE]
.Peer Communication with salt-broker
====
The salt-broker acts like a switch and not like a hub, therefore Peer communication will only work for minions behind the same broker/Proxy.
For more information on Salt and peer communication see: https://docs.saltstack.com/en/latest/ref/peer.html
====

