[[uyuni-execution-modules]]
= {productname} Configuration Modules
== Introduction

{productname} provides a set of Salt execution and state modules to configure certain aspects of a {productname} server.

Those can either be used directly or via SLS files, and are especially useful in scenarios where multiple {productname} servers are employed, for example in Hub-based installations (see xref:large-deployments:multi-server.adoc[]). Nevertheless, they can also be employed with a single server.

At the time of writing, the following can be configured via Salt modules:

* organizations,
* users,
* user permissions,
* system groups.

Modules to cover more aspects may be released at a later date.

For more information in general about Salt execution modules and how to use them, please refer to https://docs.saltstack.com/en/latest/topics/tutorials/modules.html. For more information on Salt state modules, see see https://docs.saltstack.com/en/latest/topics/tutorials/starting_states.html.


[NOTE]
====
Salt modules described in this page are currently released as technology preview.
====

== Installation instructions

Salt modules are available in the optional `uyuni-config-modules` package. The package can be installed on the {productname} server with the following command:

`zypper in uyuni-config-modules`

== Usage

For detailed API descriptions, indications on Pillar settings and examples please refer to files in `/usr/share/doc/packages/uyuni-config-modules/` installed by the package above.
