[[troubleshooting-taskomatic]]
= Taskomatic 查错
:description: 了解如何排除和解决 Taskomatic 的问题，Taskomatic 是一个集中式储存库管理系统
:revdate: 2024-05-15
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////


储存库元数据重新生成是一个相对密集的过程，因此 Taskomatic 可能需要几分钟才能完成。
此外，如果 Taskomatic 崩溃，储存库元数据重新生成可能会被中断。

[IMPORTANT]
====
要在服务器容器内访问外壳，请在容器主机上运行 `mgrctl term`。
====

如果 Taskomatic 仍在运行，或者该处理已崩溃，软件包更新在 {webui} 中似乎可用，但在客户端上并未显示，尝试更新客户端会失败。
在这种情况下，`zypper ref`命令会显示类似这样的错误：

----
Valid metadata not found at specified URL
----

要纠正此问题，请确定 Taskomatic 是否仍在生成储存库元数据，或者是否可能发生了崩溃。
等待元数据重新生成完成，或在崩溃后重新启动 Taskomatic，以便正确进行客户端更新。



.过程：升级解决 Taskomatic 问题

. 在 {productname} 服务器上，检查 `/var/log/rhn/rhn_taskomatic_daemon.log` 文件，以确定是否有任何元数据重新生成处理仍在运行，或者是否发生了崩溃。
. 重启 Taskomatic：
+
----
service taskomatic restart
----
+
. 在 Taskomatic 日志文件中，可以通过查看如下所示的开始行和结束行来识别与元数据重新生成相关的部分：
+
----
<YYYY-DD-MM> <HH:MM:SS>,174 [Thread-584] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Generating new repository metadata for channel 'cloned-2018-q1-sles12-sp3-updates-x86_64'(sha256) 550 packages, 140 errata

...

<YYYY-DD-MM> <HH:MM:SS>,704 [Thread-584] INFO  com.redhat.rhn.taskomatic.task.repomd.RepositoryWriter - Repository metadata generation for 'cloned-2018-q1-sles12-sp3-updates-x86_64' finished in 4 seconds
----
