[[troubleshooting-firewalls]]
= 防火墙查错
:description: 配置您的防火墙以允许或拒绝来自 SUSE Multi-Linux Manager 服务器的请求，然后排查与第三方产品相关的任何问题
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step


Cause: User firewall is set to block outgoing traffic by dropping the packet request. During sync with {scc}, mlm waits for an answer on each URL until it times out, eventually causing the entire refresh of the product list to timeout. Applies only to third party (non-SUSE) products, as sync with {scc} needs to access locations other than {scc} to verify if the if the download location is valid.

Consequence: The sync to {scc} fails, and the third party products are not shown in the product list.

Fix: Configure the firewall to reject requests from mlm instead of drop (preferred), or configure a firewall on the server (if no ability to change firewall settings)

Result: Sync to {scc} is either able to reach the URLs required, or rejects the request so that the request fails rather than times out.
////

如果您使用的防火墙阻止外发流量，它可以阻止 `REJECT` 或 `DROP` 网络请求。
如果设置为 `DROP`，那么您可能会发现与 {scclongform} 的同步超时。

发生这种情况是因为同步需要访问提供非 {suse} 客户端软件包的第三方存储库，而不仅仅是 {scclongform}。
当 {productname} 服务器尝试访问这些存储库以检查其有效性时，防火墙会丢弃请求，且同步会继续等待响应，直到超时。

如果发生这种情况，同步将持续很长时间，然后失败，并且您的非 {suse} 产品不会显示在产品列表中。

可以通过多种不同的方法解决此问题。

最简单的方法是配置您的防火墙以允许访问非 {suse} 存储库所需的 URL。
这使得同步过程能够访问这些 URL 并成功完成。

如果不允许外部流量，请将您的防火墙配置为 `REJECT` 来自 {productname} 的请求，而不是 `DROP`。
这会拒绝对第三方 URL 的请求，从而使同步提前失败，而不是超时，并且产品不会显示在列表中。

如果您无权配置防火墙，可以考虑在 {productname} 服务器上单独设置一个防火墙。
