[[troubleshooting-login-timeout]]
= 登录超时查错
:description: 了解如何通过调整 rhn.conf 和 web.xml 文件来排除故障并配置 SUSE Multi-Linux Manager Web UI 登录超时，识别潜在原因
:revdate: 2025-07-16
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

默认情况下，{productname} {webui} 要求用户在 30{nbsp}分钟后重新登录。
根据您的环境，您可能希望调整登录超时值。

要调整该值，您需要在 `rhn.conf` 和 `web.xml` 中进行更改。
请确保将 `/etc/rhn/rhn.conf` 中的值设置为秒，将 `web.xml` 中的值设置为分钟。
这两个值必须等于相同的时间。

例如，要将超时值更改为一小时，请将 `rhn.conf` 中的值设置为 3600 秒，将 `web.xml` 中的值设置为 60 分钟。



.过程：升级调整 {webui} 登录超时值
. 在容器主机上，在服务器容器内打开命令行：

+

[source,shell]
----
mgrctl term
----

+

--

.. 打开 `/etc/rhn/rhn.conf` 并添加或编辑此行，以包含以秒为单位的新超时值：

+

----
web.session_database_lifetime = <Timeout_Value_in_Seconds>
----

.. 保存并关闭该文件。

.. 打开 `/etc/tomcat/web.xml` 并添加或编辑此行，以包含以分钟为单位的新超时值：

+

[source,xml]
----
<session-timeout>Timeout_Value_in_Minutes</session-timeout>
----

.. 保存并关闭该文件。

--

+

. 在容器主机上，重启服务器以强制应用新配置：

+

[source,shell]
----
systemctl restart uyuni-server.service
----
