[[troubleshooting-inactive-clients]]
= 非活动客户端查错
:description: 查找并修复导致客户端变为不活跃的问题，方法是检查连接设置、防火墙规则和 Taskomatic 配置。
:revdate: 2025-01-08
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

Taskomatic 任务定期向客户端发送 ping，以确保它们已连接。
如果客户端在 24 小时或更长时间内未响应 Taskomatic 检查，则被视为不活跃。
要查看 {webui} 中不活跃客户端的列表，请导航到 menu:系统[系统列表> 不活跃]。

客户端可能由于多种原因而进入非活动状态：

* 客户端没有权利享受任何 {productname} 服务。
* 客户端位于不允许 HTTPS 连接的防火墙后面。
* 客户端位于配置不当的代理后面。
* 客户端正在与其他 {productname} Server通信，或者连接配置不当。
* 客户端不在可以与 {productname} Server通信的网络中。
* 防火墙阻止了客户端与 {productname} Server之间的通信。
* Taskomatic 配置不当。


有关客户端与服务器连接的更多信息，请参见 xref:client-configuration:contact-methods-intro.adoc[]。

有关配置端口的更多信息，请参见 xref:installation-and-upgrade:network-requirements.adoc#ports[]。

有关故障排除防火墙的更多信息，请参见 xref:administration:troubleshooting/tshoot-firewalls.adoc[]。
