[[troubleshooting-not-enough-disk-space]]
= Troubleshooting Not Enough Disk Space
:revdate: 2022-10-18
:page-revdate: {revdate}

////

PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step

////


Před zahájením migrace zkontrolujte dostupné místo na disku. Doporučujeme umístit [path]``/var/spacewalk`` a [path]``/var/lib/pgsql`` na různé souborové systémy XFS.

Když nastavujete samostatný systém souborů, upravte [path]``/etc/fstab`` a odstraňte podsvazek [path]``/var/lib/pqsql``. Restartujte server, aby se změny provedly.

Chcete-li získat další informace o problémech při upgradu, zkontrolujte soubor protokolu migrace. Soubor protokolu se nachází na [path]``/var/log/rhn/migration.log`` v systému, který upgradujete.

