[[connect.payg.instances]]
= {payg} 인스턴스 연결
:revdate: 2025-07-14
:page-revdate: {revdate}

3곳의 주요 공용 클라우드 공급자(AWS, GCP 및 Azure)에서, SUSE:

* SLES, SLES for SAP 등을 위한 맞춤형 {payg} 제품 이미지를 제공합니다.
* {payg}(으)로 제공되는 제품을 위한 영역별 RMT 서버 미러링 리포지토리를 운영합니다.

이 설명서에서는 기존 {payg} 인스턴스를 {productname} 서버에 연결하는 방법을 설명하고 인스턴스에서 인증서 모음과 관련한 기본적인 정보를 제공합니다. 연결은 {productname} 서버가 클라우드 RMT 호스트에 연결할 수 있도록 인증 데이터를 추출하기 위해 수행됩니다. 그런 다음 {productname} 서버는 {scc} 조직 인증서로 아직 사용할 수 없는 RMT 호스트의 제품에 액세스할 수 있습니다.


{payg} 기능 사용 전 확인 사항:

* 원하는 리포지토리에 액세스할 수 있도록 올바른 SUSE 제품 이미지(예: SLES, SLES for SAP 또는 SLE HPC)에서 {payg} 인스턴스가 시작됩니다.

* {productname} 서버는 직접 또는 배스천을 통해 {payg} 인스턴스(이상적으로는 동일한 영역에 위치)에 연결됩니다.

* 기본 {scc} 계정이 필요합니다. menu:Admin[설정 마법사 > 조직 자격 증명]에 유효한 {scc} 자격 증명을 입력하십시오. 이 계정은 {payg} 인스턴스에 관계없이 부스트래핑을 위한 {productname} 클라이언트 도구에 액세스하는 데 필요합니다.

* If you bootstrap the {payg} instance to {productname}, it will disable its {payg} repositories then add repositories from where it mirrored the data from the RMT server. The final result will be {payg} instances acquiring the same repositories from the RMT servers but through the {productname} server itself. Of course repositories can still be setup primarily from SCC.



== {payg} 인스턴스 연결 중


[[proc-connecting-new-payg]]
.절차: 새 {payg} 인스턴스 연결
[role=procedure]
. {productname} {webui}에서 menu:관리[설치 마법사 > {payg}]으로 이동하고 btn:[{payg} 추가]를 클릭합니다.
. 페이지 섹션 [guimenu]``{payg} 연결 설명``으로 시작하십시오.
. [guimenu]``설명`` 필드에 설명을 추가합니다.
. [guimenu]``인스턴스 SSH 연결 데이터`` 페이지 섹션으로 이동합니다.
. [guimenu]``호스트`` 필드에 {productname}에서 연결할 인스턴스 DNS 또는 IP 주소를 입력합니다.
. [guimenu]``SSH 포트`` 필드에 포트 번호를 입력하거나 기본값 22를 사용합니다.
. [guimenu]``사용자`` 필드에 클라우드에 지정된 대로 사용자 이름을 입력합니다.
. [guimenu]``암호`` 필드에 암호를 입력합니다.
. [guimenu]``SSH 개인 키`` 필드에 인스턴스 키를 입력합니다.
. [guimenu]``SSH 개인 키 암호 문구`` 필드에 키 암호 문구를 입력합니다.

[IMPORTANT]
====
인증 키는 항상 PEM 형식이어야 합니다.
====

인스턴스에 직접 연결하지 않고 SSH 배스천을 통해 연결하는 경우 <<proc-adding-ssh-bastion-connection-data>>를 진행합니다.

그 외의 경우, <<proc-finishing-payg-connecting>>을 진행합니다.

[[proc-adding-ssh-bastion-connection-data]]
.절차: SSH 배스천 연결 데이터 추가
[role=procedure]
. [guimenu]``SSH 배스천 연결 데이터`` 페이지 섹션으로 이동합니다.
. [guimenu]``호스트`` 필드에 배스천 호스트 이름을 입력합니다.
. [guimenu]``SSH 포트`` 필드에 배스천 포트 번호를 입력합니다.
. [guimenu]``사용자`` 필드에 배스천 사용자 이름을 입력합니다.
. [guimenu]``암호`` 필드에 배스천 암호를 입력합니다.
. [guimenu]``SSH 개인 키`` 필드에 배스천 키를 입력합니다.
. [guimenu]``SSH 개인 키 암호 문구`` 필드에 배스천 키 암호 문구를 입력합니다.

Complete the setup process with <<proc-finishing-payg-connecting>>.

[[proc-finishing-payg-connecting]]
.절차: {payg} 연결 종료
[role=procedure]
. 새로운 {payg} 연결 데이터 추가를 완료하려면 btn:[만들기]를 클릭하십시오.
. {payg} 연결 데이터 [guimenu]``세부 정보`` 페이지로 돌아갑니다.
    업데이트된 연결 상태는 [guimenu]``정보`` 상단 섹션에 표시됩니다.
. 연결 상태는 [guimenu]``관리자 > 설정 마법사 > Pay-as-you-go`` 화면에도 표시됩니다.
. 인스턴스에 대한 인증 데이터가 올바르면, [guimenu]``상태`` 열에 "자격 증명이 업데이트됨" 메시지가 표시됩니다.

[IMPORTANT]
====
언제든 잘못된 데이터를 입력하면 새로 생성된 인스턴스가 [guimenu]``관리자 > 설정 마법사 > {payg}``에 표시되고 [guimenu]``상태`` 열에 오류 메시지가 표시됩니다.
====


서버에서 인증 데이터를 사용할 수 있게 되면 사용 가능한 제품 목록이 업데이트됩니다.

사용 가능한 제품은 {payg} 인스턴스에 설치된 것과 동일한 제품군 및 아키텍처의 모든 버전입니다. 예를 들어, 인스턴스에 {sles}{nbsp}15 SP1 제품이 설치되어 있으면 {sles}{nbsp}15 SP2, {sles}{nbsp}15 SP3, {sles}{nbsp}15 SP4 및 {sles}{nbsp}15 SP5가 [guimenu]``관리자 > 설정 마법사 > 제품``에 자동으로 표시됩니다.

제품이 사용 가능한 것으로 표시되면 사용자는 제품 이름 옆의 확인란을 선택하고 btn:[제품 추가]를 클릭하여 {productname}에 제품을 추가할 수 있습니다.

성공 메시지가 표시되면 [guimenu]``소프트웨어 > 채널 목록 > 전체``로 이동하여 {webui}에서 새로 추가된 채널을 확인할 수 있습니다.

각 채널의 동기화 진행 상황을 모니터링하려면 {productname} 서버의 [path]``/var/log/rhn/reposync`` 디렉토리에서 로그 파일을 확인하십시오.

[IMPORTANT]
====
제품이 {payg} 인스턴스와 {scc} 구독 중 하나에서 모두 제공되는 경우 제품 목록에 한 번만 나타납니다.

해당 제품에 속한 채널이 동기화되면 데이터는 Pay-As-You-Go 인스턴스가 아닌 SCC 구독에서 계속 가져올 수 있습니다.
====

== 인스턴스 자격 증명 수집 상태

{productname} 서버는 인스턴스에서 수집한 자격 증명을 사용하여 RMT 서버에 연결하고 reposync를 사용하여 패키지를 다운로드합니다. 이러한 자격 증명은 정의된 SSH 연결 데이터를 사용하여 taskomatic에 의해 10분마다 새로 고쳐집니다. RMT 서버에 대한 연결은 {payg} 인스턴스에서 수집된 마지막으로 알려진 인증 자격 증명을 항상 사용합니다.

수집한 {payg} 인스턴스 자격 증명의 상태는 [literal]``Status`` 열 또는 인스턴스 세부 정보 페이지에 표시됩니다. 인스턴스에 연결할 수 없으면 자격 증명 업데이트 프로세스가 실패합니다.

인스턴스에 연결할 수 없는 경우 자격 증명 업데이트 프로세스가 실패하고 새로 고침이 두 번 실패하면 자격 증명이 무효화됩니다. 자격 증명이 유효하지 않은 경우 채널 동기화가 실패합니다. 이를 방지하려면 연결된 인스턴스를 계속 실행합니다.

SSH 연결 데이터가 명시적으로 삭제된 경우를 제외하고, {payg} 인스턴스는 {productname} 서버에 연결된 상태를 유지합니다. 인스턴스에 대한 SSH 연결 데이터를 삭제하려면 <<proc-deleting-connection-data-to-instance>> 명령을 사용하십시오.
 

항상 {productname} 서버에서 {payg} 인스턴스에 액세스할 수 있는 것은 아닙니다.

* 인스턴스가 존재하지만 중지된 경우에는 마지막으로 알려진 자격 증명을 사용하여 인스턴스에 연결을 시도합니다.
    자격 증명 유효 기간은 클라우드 공급자에 따라 다릅니다.

* 인스턴스가 더 이상 존재하지 않지만 여전히 SUMA에 등록되어 있으면, 해당 자격 증명은 더 이상 유효하지 않으며 인증이 실패합니다.
    오류 메시지는 상태 열에 표시됩니다.
+
[WARNING]
====
오류 메시지는 인스턴스를 사용할 수 없다는 것만을 나타냅니다. 인스턴스 상태에 대한 자세한 진단은 클라우드 공급자에서 수행해야 합니다.
====

[IMPORTANT]
====
{payg} 인스턴스에서 다음 작업 또는 변경 사항이 발생하면 자격 증명이 작동하지 않게 됩니다.
* zypper 자격 증명 파일 제거
* 가져온 인증서 제거
* [path]``/etc/hosts``에서 클라우드 관련 항목 제거
====


== {payg} 시스템을 클라이언트로 등록

자격 증명을 수집하는 {payg} 인스턴스를 {salt} 클라이언트로 등록할 수 있습니다. 인스턴스에는 유효한 클라우드 연결이 등록되어 있어야 하며, 그렇지 않으면 채널에 액세스할 수 없습니다. 사용자가 클라우드 패키지를 제거하면 자격 증명 수집이 작동하지 않을 수 있습니다.

우선 {payg} 인스턴스를 설정하여 인증 데이터를 수집합니다. 그러면 채널을 동기화할 수 있습니다.

나머지 프로세스는 비퍼블릭 클라우드 클라이언트에서와 동일하며 채널 동기화, 자동 부트스트랩 스크립트 생성, 활성화 키 생성 및 등록 시작으로 구성됩니다.

클라이언트 등록에 대한 자세한 내용은 xref:client-configuration:registration-overview.adoc[]에서 확인할 수 있습니다.


== 문제 해결 

자격 증명 확인::
* 스크립트가 자격 증명 수집에 실패하면 로그 및 {webui}에 적절한 오류 메시지가 표시되어야 합니다.
* 자격 증명이 작동하지 않으면 [literal]``reposync``에 적절한 오류가 표시되어야 합니다.

[literal]``registercloudguest`` 설치::
* 공용 클라우드 업데이트 인프라에 대한 [literal]``registercloudguest`` 연결을 새로 고치거나 변경해도 자격 증명을 사용하는 데 방해가 되지 않아야 합니다.
* 클라우드 게스트 명령에 새 클라우드 연결이 등록되어 있지 않은 경우 [literal]``registercloudguest --clean``을 실행하면 문제가 발생할 수 있습니다.
