[[install-hardware-requirements]]
= 하드웨어 요구사항
:revdate: 2025-07-03
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

이 표에는 {x86_64}, {arm}, {ppc64le} 및 {s390x} 아키텍처에서 {productname} 서버 및 프록시에 대한 하드웨어 및 소프트웨어 요구사항이 간략하게 설명되어 있습니다.


[WARNING]
====
{ppc64le} 또는 {s390x} 아키텍처 기반 {productname} 설치는 네트워크 부팅 클라이언트에 보안 부팅을 사용할 수 없습니다. 이 제한은 두 아키텍처에서 shim 부트로더를 사용할 수 없기 때문에 발생합니다.
====

//For {ibmz} hardware requirements, see xref:installation-and-upgrade:install-ibmz.adoc[].

{productname} {smr} 하드웨어 요구사항은 xref:retail:retail-requirements.adoc[]을 참조하십시오.



[[server-hardware-requirements]]
== 서버 요구사항


{sl-micro} {microversion} 또는 {sles} {bci-mlm} 중 하나는 컨테이너 호스트의 운영 체제입니다.

다음에서 설치된 호스트 운영 체제인 {sles}는 관련이 있을 경우에만 명시적으로 언급합니다. 그렇지 않은 경우 {sl-micro} 또는 단순히 호스트 운영 체제로 표기합니다.

운영 체제로 {sl-micro}를 사용하는 컨테이너 호스트에는 디스크 여유 공간이 필요합니다.

* 기본 설치 시 최소 100GB
* 리포지토리 데이터용 공간 최소 130GB

선택한 소프트웨어의 규모에 따라 {sles}를 운영 체제로 사용하려면 상당히 많은 디스크 공간이 필요할 수 있습니다.

기본적으로 {productname} 서버 컨테이너는 미러링된 리포지토리(패키지 또는 제품), 데이터베이스 및 기타 데이터를 [path]``/var/lib/containers/storage/volumes/`` 디렉토리의 하위 디렉토리에 저장합니다. 이 디렉토리에 디스크 공간이 부족하면 리포지토리 동기화에 실패합니다. 미러링할 클라이언트와 리포지토리의 수와 종류에 따라 [path]``/var/lib/containers/storage/volumes/`` 디렉토리에 필요한 공간을 예측하십시오.

파일 시스템 및 파티셔닝 세부 정보에 대한 자세한 내용은 xref:installation-and-upgrade:hardware-requirements.adoc#install-hardware-requirements-storage[] 및 이 가이드의 설치 및 배포 섹션에 있는 세부 설치 지침을 참조하십시오.

[cols="1,3,2", options="header"]
.서버 하드웨어 요구사항
|===

| 하드웨어
| 세부 정보
| 권장

| CPU
| {x86_64}, {arm}, {ppc64le} 또는 {s390x}
| 최소 4개의 전용 64비트 CPU 코어

| RAM
| 최소
| 16GB

|
| 권장
| 32GB

| 디스크 공간
| [path]``/`` (루트 디렉토리)
| 40GB

|
| [path]``/var/lib/containers/storage/volumes``
| 최소 150GB(제품 수에 따라 다름)

|
| [path]``/var/lib/containers/storage/volumes/var-pgsql``
| 최소 50GB

| 스왑 공간
| 시스템은 추가 스왑 공간의 이점을 누릴 수 있습니다. {suse}는 스왑 파티션 대신 스왑 파일을 사용할 것을 권장합니다. 스왑 공간에 대한 자세한 내용은 see xref:installation-and-upgrade:hardware-requirements.adoc#installation-swap-space[]에서 확인할 수 있습니다.
| 8~12GB
|===

// |
// | [path]``/var/lib/containers/storage/volumes/var-cache``
// | Minimum 10 GB.
// Add 100 MB per {suse} product, 1 GB per {redhat} or other product.
// Consider to double the space if the server is used for Inter-Server Synchronization (ISS)
// 
// |
// | [path]``/var/lib/containers/storage/volumes/srv-www``
// | Minimum 100 GB
// 
// * Storage requirments should be calculated for the number of ISO distribution images, containers, and bootstrap repositories you will use.


기본적으로 이미지에는 40GB [literal]``/`` 파티션이 있습니다. {sl-micro} {microversion}의 클라우드 이미지에는 5GB [literal]``/`` 파티션만 있습니다. 두 파티션 모두 {productname}에서 완벽하게 작동합니다. 외부 스토리지가 [path]``/var/lib/containers/storage/volumes``에 마운트된 경우 {productname}은(는) [literal]``/`` 파티션에서 스토리지를 필요로 하거나 사용하지 않으며, 컨테이너 호스트가 직접 관리하도록 합니다.



////
// When uncommenting verify the details! (POWER)

ifeval::[{mlm-content} == true]
[cols="1,3,2", options="header"]
.Server Hardware Requirements for IBM POWER8 or higher processor–based server in Little Endian mode (ppc64le)
|===

| Hardware
| Details
| Recommendation

| CPU
|
| Minimum 4 dedicated cores

| RAM
| Minimum
| 16 GB

|
| Recommended
| 32 GB

| Disk Space
| [path]``/`` (root directory)
| Minimum 100 GB

|
| [path]``/var/lib/containers/storage/volumes/var-pgsql``
| Minimum 50 GB

|
| [path]``/var/lib/containers/storage/volumes/var-spacewalk``
| Minimum storage required: 100 GB (this will be verified by the implemented check)

* 50 GB for each {suse} product and Package Hub

* 360 GB for each {redhat} product

|
| [path]``/var/lib/containers/storage/volumes/var-cache``
| Minimum 10{nbsp}GB.
Add 100{nbsp}MB per {suse} product, 1{nbsp}GB per {redhat} or other product.
Double the space if the server is an ISS Master.

|
| [path]``/var/lib/containers/storage/volumes/srv-www``
| Minimum 100 GB

* Storage requirements should be calculated for the number of ISO distribution images, containers, and bootstrap repositories you will use.

|
| Swap space
| 3{nbsp}GB. Systems can benefit from additional swap space.   {suse} recommends using a swap file instead of a swap partition.  For more information about swap space, see xref:installation-and-upgrade:hardware-requirements.adoc#installation-swap-space[].

|===

endif::[]

// end POWER
////



[IMPORTANT]
====
{productname} 성능은 하드웨어 리소스, 네트워크 대역폭, 클라이언트와 서버 간 대기 시간 등에 따라 달라집니다.

사용 중인 환경과 다양한 배포에 따라 적절한 수의 프록시가 배치된 {productname} 서버의 최적 성능을 달성하려면 단일 서버당 10,000개의 클라이언트를 초과하지 않는 것이 좋습니다. 클라이언트가 10,000개를 초과하는 경우 허브 설정으로 이동하여 컨설팅을 포함하는 것이 매우 권장됩니다. 미세 조정 및 적절한 수의 프록시가 포함된 경우에도 클라이언트의 수가 그렇게 많으면 성능 문제가 발생할 수 있습니다.

대규모 클라이언트 관리에 대한 자세한 내용은 xref:specialized-guides:large-deployments/hub-multi-server.adoc[]에서 확인할 수 있습니다.
====


[[proxy-hardware-requirements]]
== 프록시 요구사항

{sl-micro} {microversion} 또는 {sles} {bci-mlm} 중 하나는 컨테이너 호스트의 운영 체제입니다.

[NOTE]
====
최소 요구 사항은 클라이언트가 1개인 프록시와 같은 빠른 테스트 설치에 적합합니다. 프로덕션 환경을 사용하려면 권장 값으로 시작하십시오.
====


[cols="1,3,2", options="header"]
.프록시 하드웨어 요구사항
|===

| 하드웨어
| 세부 정보
| 권장

| CPU
| {x86_64}, {arm}
| 최소 2개의 전용 64비트 CPU 코어

|
| 권장
| 최소값과 동일

| RAM
| 최소
| 2GB

|
| 권장
| 8GB

| 디스크 공간
| [path]``/`` (루트 디렉토리)
| 최소 40GB

|
| [path]``/var/lib/containers/storage/volumes``
| 최소 100GB

| 스왑 공간
| 시스템은 추가 스왑 공간의 이점을 누릴 수 있습니다.  {suse}는 스왑 파티션 대신 스왑 파일을 사용할 것을 권장합니다. 스왑 공간에 대한 자세한 내용은 xref:installation-and-upgrade:hardware-requirements.adoc#installation-swap-space[]에서 확인할 수 있습니다.
| 4~8GB

|===

기본적으로 {productname} 프록시 컨테이너는 [path]``/var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/`` 디렉토리에 패키지를 캐시합니다. 사용 가능한 공간이 충분하지 않으면 프록시는 사용하지 않는 오래된 패키지를 제거하고 최신 패키지로 바꿉니다.

이 동작의 결과:

* 프록시에 있는 [path]``/var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/`` 디렉토리의 크기가 클수록 프록시와 {productname} 서버 간의 트래픽이 감소합니다.
* 프록시에서 [path]``/var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/`` 디렉토리를 {productname} 서버의 [path]``/var/lib/containers/storage/volumes/var-spacewalk/``와 같은 크기로 설정하면 최초 동기화 이후 대량의 트래픽이 발생하는 것을 방지할 수 있습니다.
* [path]``/var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/`` 디렉토리의 크기는 프록시에 비해 {productname} 서버에서 더 작을 수 있습니다. 크기 예측에 대한 설명은 <<서버-하드웨어-요구사항>> 섹션에서 확인할 수 있습니다.

[NOTE]
====
일반적으로 {suse}는 캐시 디렉토리의 값을 사용 가능한 여유 공간의 약 80%로 조정할 것을 권장합니다. [option]``cache_dir`` 값은 서버에서 프록시 구성을 생성할 때 설정됩니다. 사용자는 [path]``squid.conf``에서 직접 옵션을 설정할 수 없습니다.
====



[[installation-swap-space]]
== 스왑 공간

작업 부하는 시스템마다 다릅니다. 작업 부하가 많거나 예측 불가능한 시스템은 총 RAM 용량과 무관하게 추가 스왑 공간을 활용하는 것이 좋습니다. 스왑은 사용 가능한 가장 빠른 저장소(예: SSD)에 배치하는 것이 권장됩니다. {suse}는 스왑 파티션 대신 스왑 파일을 사용할 것을 권장합니다.

크기 권장 사항은 위 표를 참조하십시오.

다음 셸 명령 조각은 8GiB 스왑 파일을 생성합니다.

[NOTE]
====
BtrFS 파일 시스템상의 스왑 파일은 해당 볼륨의 스냅샷 생성을 방해합니다. [path]``/var``은 다음 예시에서 이미 snapper 스냅샷에서 제외되어 있으므로, [path]``/var/swap``을 안전하게 사용할 수 있습니다.
====

[source, shell]
----
## setup swapfile at /var/swap
# run following as a root user

# 스왑 파일에 8GiB 할당
fallocate -l 8G /var/swap
# 스왑 파일에 대해 CoW(Copy-on-Write)가 비활성화되었는지 확인
chattr +C /var/swap
# 루트 액세스만 허용
chmod 600 /var/swap
# 할당된 파일을 기반으로 스왑 파일 생성
mkswap /var/swap
# 실행 중인 시스템에 대한 스왑 사용 활성화
swapon /var/swap
# 다음 부팅 시 스왑 활성화
echo "/var/swap swap swap defaults 0 0" >> /etc/fstab
----




[[installation-postgresql-requirements]]
== 데이터베이스 요구사항

{postgresql} 데이터베이스만 지원됩니다. 원격 {postgresql} 데이터베이스 또는 원격 파일 시스템(예: NFS)을 {postgresql} 데이터베이스와 함께 사용하는 기능은 지원되지 않습니다. 즉, {postgresql}은 {productname}에 대해 사용 가능한 가장 빠른 저장소 장치에 있어야 합니다.

[IMPORTANT]
====
잠재적인 성능 문제로 인해 {postgresql} 데이터베이스를 {productname}에서 원격으로 실행하는 것은 일반적으로 권장하지 않습니다. 이러한 환경은 많은 경우에 사용할 수 있고 안정적이지만, 문제가 발생하면 데이터가 손실될 위험이 항상 있습니다.

ifeval::[{mlm-content} == true]
그러한 경우 {suse}에서 지원을 제공하지 못할 수 있습니다.
endif::[]
====



[[install-hardware-requirements-storage]]
== 영구 스토리지 및 권한

컨테이너를 배포할 때 기본적으로 영구 볼륨이 생성됩니다.

하지만 볼륨을 하나 이상의 별도 스토리지 장치에 저장하는 것이 좋습니다. 이러한 설정은 프로덕션 환경에서 데이터 손실을 방지하는 데 도움이 됩니다. 이 작업은 컨테이너 배포 후에 수행할 수 있습니다.

스토리지 장치는 컨테이너를 처음 배포한 후에 설정하는 것이 가장 좋습니다. 자세한 내용은 xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[영구 컨테이너 볼륨]에서 확인할 수 있습니다.

모든 볼륨의 파일 시스템 형식으로는 XFS를 사용하는 것이 좋습니다. 리포지토리 저장소의 디스크 크기는 {productname}을(를) 사용하여 관리하는 배포 및 채널의 수에 따라 다릅니다. 필요한 예상 크기에 대한 설명은 이 섹션의 표를 참조하십시오.

[IMPORTANT]
====
NFS를 {cobbler} 또는 {postgresql} 스토리지로 사용하지 마십시오. NFS를 SELinux 환경에서도 사용하지 마십시오. 이러한 시나리오는 지원되지 않습니다.
====

{productname} 서버에서 이 명령을 사용하여 사용할 수 있는 모든 스토리지 장치를 찾습니다.

[source, shell]
----
hwinfo --disk | grep -E "장치 파일:"
----

[command]``lsblk`` 명령을 사용하여 각 장치의 이름 및 크기를 확인합니다.

장치의 이름과 함께 [command]``mgr-storage-server`` 명령을 사용하여 외부 디스크를 스토리지의 위치로 설정하고, 선택적으로 자체 디스크에 데이터베이스의 위치로 설정합니다.

[source, shell]
----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----

예:

[source, shell]
----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----

외부 저장소 볼륨은 [path]``/manager_storage`` 및 [path]``/pgsql_storage``에 마운트된 XFS 파티션으로 설정됩니다.

[NOTE]
====
이 명령은 [path]``/var/lib/containers/storage/volumes``에 영구 스토리지 볼륨을 생성합니다.

자세한 내용은 xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]에서 확인할 수 있습니다.
====

채널 데이터 및 데이터베이스 모두에서 동일한 스토리지 장치를 사용할 수 있습니다. 채널 리포지토리가 증가하여 스토리지가 가득 차 데이터베이스 무결성이 손상될 수 있으므로 이 방법은 권장되지 않습니다. 별도의 스토리지 장치를 사용하면 성능도 향상할 수 있습니다. 1개의 스토리지 장치를 사용하려면 단일 장치 이름 파라미터와 함께 [command]``mgr-storage-server``를 실행합니다.

프록시를 설치하는 경우에는 [command]``mgr-storage-proxy`` 명령에서 1개의 장치 이름 파라미터만 사용할 수 있고 외부 스토리지 위치는 Squid 캐시로 설정됩니다.



== 논리 볼륨 관리(LVM)


// container-deployment/mlm/server-deployment-vm-mlm.adoc etc.
모든 종류의 가상 머신(VM)에서는 일반적으로 LVM이 필요하지 않으며 권장되지 않습니다. 디스크 설정은 가상 환경에서 이뤄지고 볼륨을 위한 별도의 디스크를 사용하는 것이 가능하며 권장됩니다.

// container-deployment/mlm/server-deployment-mlm.adoc
다른 배포의 경우 볼륨에 대한 별도의 디스크도 권장됩니다.

{productname} 서버의 컨테이너 호스트에서 [command]``mgr-storage-server`` 명령은 [path]``/var/lib/containers/storage/volumes`` 디렉토리의 전체 내용을 별도의 디스크로 이동한 후 [path]``/var/lib/containers/storage/volumes``에 다시 마운트합니다.

선택 사항으로, 두 번째 장치 이름이 지정된 경우, [command]``mgr-storage-server``는 [path]``/var/lib/containers/storage/volumes/var-pgsql`` 데이터베이스 디렉토리의 컨텐트를 두 번째 별도 디스크로 이동한 후 이를 [path]``/var/lib/containers/storage/volumes/var-pgsql``에 다시 마운트합니다.

마찬가지로 {productname} 프록시의 컨테이너 호스트에서 [command]``mgr-storage-proxy`` 명령은 [path]``/var/lib/containers/storage/volumes`` 디렉토리의 전체 콘텐츠를 별도의 디스크로 이동하고 [path]``/var/lib/containers/storage/volumes``에 다시 마운트합니다.



////
// *** The following is commented, and can probably deleted ***

// When installation takes place on bare metal (on-premise), [command]``cockpit`` can be used to create an LVM setup.
// In such a case, the disk setup needs to be performed manually.

// With containers {productname} now has [path]``/var/lib/containers/storage/volumes`` as an extra disk.
////
