[[troubleshooting-rpc-timeout]]
= RPC 超时查错
:revdate: 2022-10-18
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

由于网络速度缓慢或网络链接断开，RPC 连接有时会超时。这会导致软件包下载或批处理作业挂起或运行时间超过预期。您可以通过编辑配置文件来调整 RPC 连接可以花费的最长时间。虽然这不能解决网络问题，但可以使进程失败而不是挂起。


.过程：解决 RPC 连接超时

. 在 {productname} Server 上，打开 [filename]``/etc/rhn/rhn.conf`` 文件并设置最大超时值（以秒为单位）：

+

----
server.timeout =`数字`
----

+

在 {productname} 代理上，打开 [filename]``/etc/uyuni/proxy/config.yaml`` 文件并设置最大超时值（以秒为单位）。必须重启代理容器，更改才能生效：

+

----
timeout: `number`
----

+

. 在使用 zypper 的 {sles} 客户端上，打开 [filename]``/etc/zypp/zypp.conf`` 文件并设置最大超时值（以秒为单位）：

+

----
## 有效值：[0,3600]
## 默认值：180
download.transfer_timeout = 180
----

+

. 在使用 yum 的 {rhel} 客户端上，打开 [filename]``/etc/yum.conf`` 文件并设置最大超时值（以秒为单位）：

+

----
timeout =`数字`
----

[NOTE]
====
如果您将 RPC 超时限制为小于 `180` 秒，可能会中止完全正常的操作。
====
