[[script-client-proxy]]
= 부트스트랩 스크립트로 클라이언트를 프록시에 등록
:description: SUSE Multi-Linux Manager 서버에서 mgr-bootstrap 명령줄 도구를 사용하여 생성한 부트스트랩 스크립트를 통해 클라이언트가 프록시 서버에 연결하도록 구성합니다.
:revdate: 2025-03-20
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


클라이언트는 부트스트랩 스크립트를 사용하여 {productname} 프록시를 통해 등록할 수 있습니다.
이는 클라이언트를 {productname} 서버에 직접 등록하는 것과 거의 동일한 방식으로 수행됩니다.

{productname} 서버 컨테이너에서 `mgr-bootstrap` 명령줄 도구를 사용하여 부팅 스크립트를 생성합니다. `mgr-bootstrap`는 프록시의 완전한 도메인 이름(FQDN), 활성화 키 또는 GPG 키와 같은 매개변수를 요구합니다.
프록시의 FQDN은 필수입니다.
다른 모든 매개변수는 특정 설정에 따라 다릅니다.


그런 다음 부트스트랩 스크립트는 클라이언트에 필요한 모든 정보를 배포합니다.



.절차 부트스트랩 스크립트를 사용하여 클라이언트를 프록시에 등록합니다.

. {webui}를 사용하여 {productname} 서버에서 클라이언트 활성화 키를 생성합니다.
  자세한 내용은 xref:client-configuration:activation-keys.adoc[]을 참조하십시오.
. 서버의 컨테이너 호스트의 컨테이너에서 터미널을 시작하십시오.

+

[source,shell]
----
mgrctl term
----

+

--
.. 컨테이너 내에서 부팅 스크립트를 생성하려면 `mgr-bootstrap` 명령을 다음 옵션과 함께 실행합니다:

+

[source,shell]
----
mgr-bootstrap --hostname=MLM_PROXY --activation-keys=ACTIVATION_KEY \
  --script bootstrap-MLM_PROXY.sh
----

+

`MLM_PROXY`를 프록시의 호스트 이름으로 바꿉니다.

+
`--script` 옵션을 사용하면 설명적인 이름으로 부팅 스크립트를 저장할 수 있습니다.
   필요한 경우 추가 명령줄 옵션을 사용하여 부트스트랩 스크립트를 사용자 정의합니다.
   사용 가능한 옵션을 보려면 명령줄에서 `mgr-bootstrap --help`를 입력하십시오.

.. 선택 사항: 출력된 부트스트랩 스크립트를 편집합니다.
--

. 부트스트랩 스크립트를 실행합니다.
  두 가지 옵션이 있습니다:

+

* 스크립트를 클라이언트로 전송하고 클라이언트에서 직접 실행합니다.
  또는 프록시가 서버에 요청을 전달하므로 클라이언트는 http://MLM_PROXY/pub/bootstrap-MLM_PROXY.sh.에서 다운로드할 수 있습니다. `MLM_PROXY`를 프록시의 호스트 이름으로 바꿉니다.

* 프록시에서 `ssh`로 스크립트를 실행합니다.
  `MLM_PROXY`를 프록시의 호스트 이름으로 바꾸고, ` <client.example.com>`를 클라이언트의 호스트 이름으로 바꿉니다:

+

[source,shell]
----
cat /srv/www/htdocs/pub/bootstrap/bootstrap-MLM_PROXY.sh | ssh root@<client.example.com> /bin/bash
----
