[[clients-sleses]]
= {sll} 클라이언트 등록하기
:description: SUSE Liberty Linux 클라이언트를 구성하고 등록하는 방법을 배우려면, 필요한 소프트웨어 채널을 추가하고 이를 SUSE Multi-Linux Manager 서버와 동기화해야 합니다.
:revdate: 2026-04-20
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

이 섹션에는 {sll} 운영 체제를 실행하는 클라이언트 등록에 대한 정보가 포함되어 있습니다. +
{sll} 클라이언트는 {rhel} 또는 {centos}를 기반으로 합니다.


[NOTE]
====
{sll} 클라이언트는 때때로 {sleses} (SLESES), Liberty, RES 또는 {redhat} {es}라고도 불립니다.
====

{suse}에서 제공하는 {sll} 소프트웨어 채널은 패키지에 대한 업데이트만 제공하며, 패키지 자체는 제공하지 않습니다.
{sll} 클라이언트를 등록하려면, 아래에 설명된 {sll} 제품을 등록하여 필요한 기본 채널을 생성한 다음, 필요한 {redhat} 또는 {centos} 패키지를 사용자 정의 자식 채널로 가져와야 합니다.
{redhat} 또는 {centos}에서 초기 패키지를 직접 받아야만 {sll} 소프트웨어 채널에서 제공하는 업데이트를 적용할 수 있습니다.

// FIXME!

ifeval::[{mlm-content} == true]

// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====
* {sll} 리포지토리 URL은 {scclongform}에서 확인할 수 있습니다.
* 패키지 및 메타데이터는 {suse}에서 제공됩니다.
* 지원되는 제품에 대해서는 지원 테이블 및 릴리스 노트를 참조하십시오.
====
endif::[]




[IMPORTANT]
====
사용자는 {redhat} 또는 {centos} 기본 미디어 리포지토리 및 설치 미디어에 대한 액세스를 확보할 책임이 있습니다.
====


ifeval::[{mlm-content} == true]

[IMPORTANT]
====
모든 {suse} 시스템에 대해 {sll}의 지원을 받아야 합니다.
====
endif::[]


ifeval::[{uyuni-content} == true]

[IMPORTANT]
====
{suse}은 {uyuni}에서 {sll} 시스템에 대한 지원을 제공하지 않습니다.
====
endif::[]



== 소프트웨어 채널 추가


{sll} 클라이언트의 경우, 일부 필수 패키지는 {rhel} 또는 {centos} 설치 미디어에 포함되어 있습니다.
{sll} 클라이언트를 등록하기 전에 이러한 패키지를 설치해야 합니다.

{sll} 제품은 {scclongform}에서 제공됩니다.
여기에는 클라이언트 도구 패키지도 포함됩니다.

{productname} 서버에 {sll} 클라이언트를 등록하기 전에 필요한 소프트웨어 채널을 추가하고 이 채널을 동기화해야 합니다.

하나는 {sll}용으로, 다른 하나는 클라이언트 도구용으로 두 가지 채널 세트를 선택해야 합니다.

올바른 {sll} 채널과 연결된 활성화 키가 필요합니다.
활성화 키에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]을 참조하십시오.

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]

이 절차에 필요한 제품은 다음과 같습니다.

[[es-channels-wizard]]
[cols="1,1", options="header"]
.ES 제품 - WebUI
|===

| 운영 체제 버전
| 제품 이름

| {sll} 10
| RHEL 또는 SLES ES 및 Liberty 10 x86_64

| {sll} 9.6 EMS
| SUSE Liberty Linux 9.6 EMS x86_64

| {sll} 9
| RHEL 또는 SLES ES 및 Liberty 9 x86_64

| {sll} 8
| RHEL 또는 SLES ES 또는 CentOS 8 Base 및 SUSE Linux Enterprise Server with Expanded Support 8 x86_64

| {sll} 7
| SUSE Linux Enterprise Server with Expanded Support 7 x86_64

| {sll} LTSS 7
| SUSE Linux Enterprise Server with Expanded Support LTSS 7 x86_64

| {sll} 오라클 7에 대한 LTSS
| SUSE Linux Enterprise Server with Expanded Support LTSS for Oracle 7 x86_64

|===


{productname}은 추가 소프트웨어가 포함된 도구 채널을 요구합니다.
이 절차는 다음과 같은 도구 채널을 생성합니다:

[[es-channels-tools]]
[cols="1,1,1", options="header"]
.ES 도구 채널
|===

| 운영 체제 버전 | 기본 채널                     | 도구 채널
| {sll} 10    | RHEL 및 Liberty 10 베이스         | x86_64용 ManagerTools-EL10-Pool 및 x86_64용 ManagerTools-EL10-Updates
| {sll} 9.6 EMS | RHEL 및 Liberty 9.6 EMS 베이스  | x86_64용 ManagerTools-EL9-Pool 및 x86_64용 ManagerTools-EL9-Updates
| {sll} 9     | RHEL 및 Liberty 9 베이스          | x86_64용 ManagerTools-EL9-Pool 및 x86_64용 ManagerTools-EL9-Updates
| {sll} 8     | RHEL 또는 SLES ES 또는 CentOS 8 베이스 | x86_64용 RES8-Manager-Tools-Pool 및 x86_64용 RES8-Manager-Tools-Updates
| {sll} 7     | RHEL Expanded Support 7          | RES7-SUSE-Manager-Tools x86_64
| {sll} LTSS 7 | RHEL Expanded Support LTSS 7 | x86_64 LBT7에 대한 RES-7-SUSE-Manager-Tools
| {sll} 오라클 7에 대한 LTSS | RHEL Expanded Support LTSS for Oracle 7 | x86_64 LBTOL7에 대한 RES-7-SUSE-Manager-Tools

|===


ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]


endif::[]

이 절차에 필요한 채널은 다음과 같습니다.

ifeval::[{mlm-content} == true]

[[es-channels-cli]]
[cols="1,1,1,1", options="header"]
.ES 채널 - CLI
|===

| 운영 체제 버전
| 기본 채널
| 클라이언트 채널
| 도구 채널

| {sll} 10
| el10-pool-x86_64
| -
| managertools-el10-pool-x86_64

| {sll} 9.6 EMS
| el9-pool-x86_64
| -
| managertools-el9-pool-x86_64

| {sll} 9
| el9-pool-x86_64
| -
| managertools-el9-pool-x86_64

| {sll} 8
| rhel8-pool-x86_64
| -
| managertools-el8-pool-x86_64

| {sll} 7
| rhel-x86_64-server-7
| -
| managertools-el7-pool-x86_64

| {sll} LTSS 7
| res-7-ltss-updates-x86_64
| -
| res-7-suse-manager-tools-x86_64-lbt7

| {sll} 오라클 7에 대한 LTSS
| res-7-ol-ltss-updates-x86_64
| -
| res-7-suse-manager-tools-x86_64-lbtol7

|===

ifeval::[{uyuni-content} == true]

[[es-channels-cli]]
[cols="1,1,1,1", options="header"]
.ES 채널 - CLI
|===

| 운영 체제 버전
| 기본 채널
| 클라이언트 채널
| 도구 채널

| {sll} 9
| el9-pool-x86_64
| -
| sll9-uyuni-client-x86_64

| {sll} 8
| rhel8-pool-x86_64
| -
| sll8-uyuni-client-x86_64

| {sll} 7
| rhel-x86_64-server-7
| -
| sll7-uyuni-client-x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli.adoc[]
endif::[]

endif::[]



[[add.base.media]]
=== 기본 미디어 추가

{sll} 소프트웨어 채널은 업데이트만 제공하며, 패키지는 제공하지 않습니다.
{sll} 클라이언트를 등록하려면 먼저 아래에 설명된 {sll} 제품을 등록하여 기본 채널을 생성한 다음, 필요한 Red Hat 또는 CentOS 패키지를 사용자 정의 자식 채널로 가져옵니다.
업데이트를 적용하기 전에 초기 패키지를 {redhat} 또는 {centos}에서 직접 받아야 합니다. {sll}
중요하게도 Red Hat 구독을 유지할 필요는 없지만, 마이그레이션 중 Red Hat에 대한 지속적인 지불 의무가 있는지 법무 부서에 문의하십시오.
필요한 모든 패키지를 확보하려면 최소 이미지나 {jeos} 이미지가 아닌 전체 DVD 이미지를 사용하십시오.

{productname} 사용자 정의 채널을 사용하여 {rhel} 또는 {centos} 미디어를 설정할 수 있습니다.
기본 미디어의 모든 패키지는 자식 채널로 미러링되어야 합니다.

채널의 이름을 자유롭게 선택할 수 있습니다.

ifndef::backend-pdf[]
include::client-configuration:partial$manual_channels.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_channels.adoc[]
endif::[]


[IMPORTANT]
====
{redhat} 10, 9 및 8 클라이언트의 경우 Base 및 AppStream 채널을 모두 추가하십시오.
두 채널의 패키지가 필요합니다.
두 채널을 추가하지 않으면 패키지가 누락되어 부팅 리포지토리를 생성할 수 없습니다.
====

모듈형 채널을 사용하는 경우 클라이언트에서 Python 3.6 모듈 스트림을 활성화해야 합니다.
Python 3.6을 제공하지 않으면 `spacecmd` 패키지 설치가 실패합니다.


.절차 사용자 정의 채널에 기본 미디어 추가(RHEL 7.0 예시)
[role=procedure]
____
[WARNING]
====
{redhat}의 원본 설치 미디어를 사용해야 합니다.
주 버전 릴리스를 사용해야 하며(예: `7`), 부 버전 릴리스(예: `7.9`)는 사용하지 않아야 합니다.
====
. 기본 미디어 이미지를 {productname} 서버 컨테이너 호스트의 `/tmp/` 디렉토리에 복사합니다.

. 기본 미디어 이미지를 {productname} 서버 컨테이너로 가져오려면 다음을 사용합니다:

+
----
mgradm distribution copy /tmp/rhel-server-7.0-x86_64-dvd.iso rhel-server-7.0
----

+
컨테이너 내의 목적지는 `/srv/www/distributions/rhel-server-7.0`입니다.

. 다음과 같이 패키지를 앞서 생성한 하위 채널로 임포트합니다.

+

[source,shell]
----
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-7.0/
----

____

버전 9 및 8 클라이언트의 경우 레이블 및 디렉토리를 적절하게 조정하고 추가로 기본 채널과 앱스트림 채널을 모두 동기화합니다.

[source,shell]
----
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-9.0/BaseOS
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-9.0/AppStream
----

또는:

[source,shell]
----
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-8.0/BaseOS
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-8.0/AppStream
----


==== 선택 사항: 콘텐츠 URL에서 기본 미디어 추가

또는 {redhat} CDN이나 {centos}가 제공하는 콘텐츠 URL에 대한 액세스 권한이 있는 경우 사용자 정의 리포지토리를 생성하여 패키지를 미러링할 수 있습니다.

이 절차에 필요한 상세 정보는 다음과 같습니다.

[[es-repos-manual]]
[cols="1,1", options="header"]
.ES 사용자 정의 리포지토리 설정
|===

| 옵션                 | 파라미터
| 리포지토리 URL         | {redhat} CDN이나 {centos}가 제공하는 콘텐츠 URL
| 서명된 메타데이터가 있습니까?   | 모든 {redhat} 엔터프라이즈 리포지토리의 선택을 해제하십시오.
| SSL CA 인증서     | `redhat-uep` ({redhat}만)
| SSL 클라이언트 인증서 | `Entitlement-Cert-date` ({redhat}만)
| SSL 클라이언트 키         | `Entitlement-Key-date` ({redhat}만)

|===

ifndef::backend-pdf[]
include::client-configuration:partial$manual_repos.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_repos.adoc[]
endif::[]

ifndef::backend-pdf[]
include::client-configuration:partial$manual_associate.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_associate.adoc[]
endif::[]


== 동기화 상태 확인

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]

[NOTE]
====
{sll} 채널은 매우 클 수 있습니다.
초기 채널 동기화는 때때로 몇 시간이 걸릴 수 있습니다.

초기 동기화가 완료되면, 작업하기 전에 채널을 복제하는 것이 좋습니다.
이것은 원본 동기화 데이터의 백업을 제공합니다.
====



== {sll} 클라이언트 등록

ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]



[[clients-sleses-el-migration]]
== Enterprise Linux (EL) 클라이언트를 {sll}로 마이그레이션

{rhel} 및 {centos}와 같은 Enterprise Linux (EL) 클라이언트가 {productname}에 이미 미니언으로 등록되어 있고 사용자가 이를 {sll}로 마이그레이션하려는 경우 재활성화 키를 사용하여 마이그레이션을 구동하는 활성화 키를 적용할 수 있습니다.

재활성화 키에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc#activation-keys-reactivation[]을 참조하십시오.

재활성화 키는 미니언별로 생성되며, {webui} 또는 API를 사용하여 생성할 수 있습니다.
자세한 내용은 https://documentation.suse.com/multi-linux-manager/5.1/api/suse-manager/api/system.html#apidoc-system-obtainReactivationKey-loggedInUser-sid.을 참조하십시오.

클라이언트를 다시 활성화하려면 사용자가 클라이언트에서 부팅 스크립트를 실행하고 재활성화 키를 환경 변수로 전달하면 됩니다.
예:

----
REACTIVATION_KEY=<KEY> ./bootstrap_liberate9.sh
----

다른 방법은 `/etc/venv-salt-minon/minion.d/susemanager.conf`(또는 `/etc/salt-minon/minion.d/susemanager.conf`)에 위치한 {salt} 클라이언트 구성 파일에 몇 가지 특수 플래그를 추가하는 것입니다 (이 내용을 기존 내용과 결합하십시오):

----
grains:
    susemanager:
        activation_key: "<KEY_ID>"
        management_key: "MINION_REACTIVATION_KEY"
----

`susemanager.conf` 파일을 변경한 후, {salt} 서버에서 `salt-minion` 서비스를 다시 시작해야 합니다.  기본적으로는:

----
systemctl restart venv-salt-minon
----

또는 레거시 {salt}의 경우:

----
systemctl restart salt-minon
----




=== `liberate` 공식

{sll} 공식을 사용하여 Enterprise Linux (EL) 클라이언트를 `liberate`로 마이그레이션합니다.
자세한 내용은 xref:specialized-guides:salt/salt-formula-liberate.adoc[]을 참조하십시오.
