[[client-upgrades]]
= 클라이언트 업그레이드
:description: 운영 체제의 버전 관리 시스템을 사용하여 클라이언트를 업그레이드하고, 제공된 업그레이드 경로 또는 자동화 방법을 따르십시오.
:revdate: 2026-07-08
:page-revdate: {revdate}

클라이언트는 자체 기본 운영 체제의 버전 관리 시스템을 사용하며 정기적인 업그레이드가 필요합니다.

{scc}개의 등록된 클라이언트가 {suse} 운영 체제를 사용하는 경우, {productname} {webui} 내에서 업그레이드를 수행할 수 있습니다.
지원되는 {sle}{nbsp}15 업그레이드 경로에 대한 내용은 {sles-base-os-documentation}/cha-upgrade-paths.html을 참조하십시오.

SLE{nbsp}12에서 SLE{nbsp}15로 클라이언트를 업그레이드하려면 업그레이드가 자동화되지만, 시작하기 전에 몇 가지 준비 단계를 수행해야 합니다.
자세한 내용은 xref:client-configuration:client-upgrades-major.adoc[]을 참조하십시오.

콘텐츠 라이프사이클 관리자를 사용하여 클라이언트 업그레이드를 자동화할 수도 있습니다.
자세한 내용은 xref:client-configuration:client-upgrades-lifecycle.adoc[]을 참조하십시오.

서비스 팩 업그레이드, {sles}{nbsp}15{nbsp}SP7에서 {sles}{nbsp}16.0으로의 메이저 버전 업그레이드, {leap}마이너 버전 업그레이드 또는 {leap}에서 {sle}(으)로의 마이그레이션과 같은 제품 마이그레이션에 관한 자세한 정보는 xref:client-configuration:client-upgrades-product-migration.adoc[]을(를) 참조하십시오.

ifeval::[{uyuni-content} == true]

등록되지 않은 {leap} 클라이언트 업그레이드에 대한 자세한 내용은 xref:client-configuration:client-upgrades-uyuni.adoc[]을(를) 참조하십시오.
endif::[]
