[[client-proxy]]
= 프록시에 클라이언트 등록
:description: 프록시 서버에서 클라이언트 등록을 웹 UI 등록, 명령줄 명령 또는 부팅 스크립트를 포함한 절차를 통해 구성합니다. 클라이언트 이동
:revdate: 2024-03-05
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


프록시 서버는 클라이언트를 위한 중개자 및 패키지 캐시 역할을 할 수 있습니다.
클라이언트를 프록시에 등록하는 것은 {productname} 서버에 직접 등록하는 것과 유사하지만 몇 가지 주요 차이점이 있습니다.

이 섹션에서는 {webui}, 명령줄의 명령 또는 부팅 스크립트를 사용하여 클라이언트를 프록시에 등록하는 방법에 대한 정보를 포함합니다.
하나의 {productname} 프록시에서 다른 프록시 또는 {productname} 서버로 클라이언트를 이동하는 절차도 있습니다.

{webui} 내에서 프록시 페이지는 클라이언트에 대한 정보를 표시합니다.
프록시에 연결된 클라이언트 목록은 menu:시스템[시스템 목록> 프록시]에서 프록시 이름을 클릭한 후, `Proxy` 탭의 `Details` 하위 탭을 선택하면 확인할 수 있습니다.

클라이언트의 체인으로 연결된 프록시 목록은 menu:시스템[전체]에서 클라이언트 이름을 클릭한 후, `Details` 탭의 `Connection` 하위 탭을 선택하면 확인할 수 있습니다.



== 프록시 간 클라이언트 이동


등록 프로세스를 반복할 필요 없이 프록시 간에 클라이언트({salt})와 {salt} SSH 푸시 클라이언트를 이동할 수 있습니다.

[IMPORTANT]
====
체인으로 연결된 프록시는 이동할 수 없습니다.
체인으로 연결된 프록시를 이동하는 대신, 새 프록시를 만들고 클라이언트를 이동한 다음 이전 프록시를 삭제하십시오.
====



.절차 프록시 간에 클라이언트 또는 {salt} SSH 푸시 클라이언트 이동

. {productname} {webui}에서, 프록시 간에 이동하려는 클라이언트의 `System Details` 페이지로 이동합니다.
. `Connection` 탭으로 이동합니다.
  그런 다음 `Change proxy` 링크를 따라 드롭다운 메뉴를 확인합니다.
. `New Proxy` 드롭다운 메뉴에서 클라이언트가 이동할 프록시를 선택하고 btn:[프록시 변경]을 클릭합니다.



.절차 SSM을 사용하여 프록시 간에 여러 클라이언트 또는 {salt} SSH 푸시 클라이언트 이동

. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 이동할 각 클라이언트의 확인란을 선택하면 클라이언트가 시스템 세트 관리자에 추가됩니다.
. menu:시스템[시스템 세트 관리자]로 이동하고 menu:기타[프록시] 탭으로 이동합니다.
. `New Proxy` 드롭다운 메뉴에서 클라이언트를 이동할 프록시를 선택한 후 btn:[프록시 변경]을 클릭합니다.

`system.changeProxy` API 호출을 통해서도 동일한 기능을 이용할 수 있습니다.



=== 배경 정보
이 함수의 효과는 일반 Salt 클라이언트와 Salt SSH 푸시 클라이언트 간에 다릅니다.


==== 기본 클라이언트

이 함수는 {salt} 상태 작업을 예약하여 `susemanager.conf` {salt} 클라이언트 구성 파일 내의 `master:` 설정을 새 프록시를 가리키도록 수정합니다.
그런 다음 이 함수는 {salt} 클라이언트를 재시작합니다.

[NOTE]
====
`master:` 파일을 수동으로 편집하여 `susemanager.conf`을(를) 변경하는 것도 동일한 효과를 내며 지원됩니다.
====

클라이언트가 다시 시작하고 새 프록시를 통해 다시 연결하면 서버는 데이터베이스에서 프록시 경로를 업데이트하고 채널 URL을 새로 고치는 다른 작업을 예약합니다.



==== {salt} SSH 푸시 클라이언트

이 함수는 데이터베이스에서 즉시 프록시 경로를 업데이트하며 채널 URL을 새로 고치는 새로운 작업이 예약됩니다.



== 프록시에서 서버로 클라이언트 이동

클라이언트를 프록시에서 서버로 이동하려면 프록시 목록에서 `None`을(를) 선택합니다.


