[[contact-methods-intro]]
= 클라이언트 연락 방법
:description: SUSE Multi-Linux Manager Server를 사용하여 클라이언트 통신 요구에 가장 적합한 Salt 통신 방식을 구성하고 배포하는 방법을 배우십시오.
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

{productname} 서버가 클라이언트와 통신할 수 있는 세 가지 통신 방식이 있습니다.
이들은 {salt} 프로토콜을 기반으로 합니다.

어떤 {salt} 통신 방식을 사용할지는 클라이언트 유형과 네트워크 아키텍처에 따라 달라집니다:

기본값::
특정 사용자 요구가 없는 한 권장됩니다.
기본적으로 {salt} 번들 구현이 배포됩니다.
자세한 내용은 xref:client-configuration:contact-methods-default.adoc[]을 참조하십시오.

SSH 푸시::
네트워크 제한으로 인해 클라이언트가 서버에 연결할 수 없는 경우에만 유용합니다.
이는 {salt} 번들에서만 지원됩니다.
이 통신 방식은 심각한 제한이 있습니다.
자세한 내용은 xref:client-configuration:contact-methods-saltssh.adoc[]을 참조하십시오.

SSH 푸시(터널 사용)::
SSH 푸시와 동일하지만 보안 통신 터널을 사용합니다.
자세한 내용은 xref:client-configuration:contact-methods-saltssh-tunnel.adoc[]을 참조하십시오.


{salt} 통신 소프트웨어 옵션의 구현:

Salt Bundle (`venv-salt-minion`)::
는 {salt} Minion, Python 3, 필수 Python 모듈 및 라이브러리가 포함된 단일 바이너리 패키지입니다.
따라서 {salt} 통신 방식은 클라이언트에 설치된 소프트웨어와 독립적입니다.

+

////
Using the {salt} Bundle is the default.
It is the only supported implementation for the SSH Push or SSH Push (with tunnel) contact method.
////

+

자세한 내용은 xref:client-configuration:contact-methods-saltbundle.adoc[]을 참조하십시오.

Salt 미니언 (`salt-minion`)::
는 클라이언트 시스템에 설치된 {salt} 소프트웨어이며, 일반적으로 {productname}와 더 이상 지원되지 않습니다.
필요한 경우, 부팅을 위해 {sle} 15 클라이언트 및 파생 제품(예: {sle-micro})에 설치할 수 있습니다.
그런 다음, 부팅 중에 `venv-salt-minion`(으)로 교체됩니다.



[IMPORTANT]
====
소위 전통적인 연락 프로토콜은 {productname} 5.0 이상에서 더 이상 지원되지 않습니다.
{productname} 4에서 5로 업그레이드하기 전에 기존의 전통적인 클라이언트와 전통적인 프록시를 {salt}로 마이그레이션하거나 {salt} 프록시로 교체해야 합니다.

전통 {productname} 4 클라이언트를 {salt} 클라이언트로 마이그레이션하는 방법에 대한 자세한 정보는 https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.html을 참조하십시오.
====
