[[contact-methods-salt]]
= 기본 연락 방법
:description: 이 프로세스를 사용하여 SUSE Multi-Linux Manager 서버의 Salt 연락처를 구성하고 관리하는 방법을 배우십시오.
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

특별한 필요가 없는 한 {salt} 프로토콜을 사용하는 기본 연락처 방법이 권장됩니다.
기본적으로 {salt} 번들 구현(`venv-salt-minion`)이 배포됩니다.
일반적인 {salt}에 대한 자세한 내용은 xref:specialized-guides:salt/salt-overview.adoc[]를 참조하십시오.

ifeval::[{mlm-content} == true]

기본 연락 방법 (`Default`)은 가장 좋은 확장 방법입니다.
모든 새로운 {productname} 기능이 지원됩니다.

[IMPORTANT]
====
소위 전통적인 연락 프로토콜은 {productname} 5.0 이상에서 더 이상 지원되지 않습니다.
{productname} 4에서 5로 업그레이드하기 전에 기존의 전통적인 클라이언트와 전통적인 프록시를 {salt}로 마이그레이션하거나 {salt} 프록시로 교체해야 합니다.

전통적인 {productname} 4 클라이언트를 {salt} 클라이언트로 마이그레이션하는 방법에 대한 자세한 내용은 https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.html를 참조하십시오.
====

endif::[]

소프트웨어 업데이트는 일반적으로 서버에서 클라이언트로 푸시됩니다.
연결은 클라이언트에서 시작됩니다.
이는 서버에서 포트를 열어야 함을 의미하며, 클라이언트에서는 열지 않아야 합니다.
{salt} 클라이언트는 {salt} 미니언으로도 알려져 있습니다.
{productname} 서버는 모든 클라이언트에 데몬을 설치합니다.

연결되지 않은 설정에서 {salt} 클라이언트를 사용해야 하는 경우 SSH Push를 연락 방법으로 구성할 수 있습니다.
이 연락 방법을 사용하면 클라이언트는 DMZ라고 하는 방화벽 보호 구역에 위치할 수 있습니다.
SSH Push에 대한 자세한 내용은 xref:client-configuration:contact-methods-saltssh.adoc[]를 참조하십시오.



[[onboarding-details]]
== 온보딩 정보


{salt}은 미니언의 키를 유지하기 위한 자체 데이터베이스를 가지고 있습니다. 이는 {productname} 데이터베이스와 동기화되어야 합니다.
키가 {salt}에서 수락되면 {productname}에서 온보딩 프로세스가 시작됩니다.

온보딩 프로세스는 {productname} 데이터베이스에서 `minion_id` 및 `machine-id`를 검색하여 기존 시스템을 찾습니다.
결과에 따라 다음과 같은 시나리오가 가능합니다:

* 아무것도 찾을 수 없으면 새 시스템이 생성됩니다.
* `minion_id` 또는 `machine-id`가 있는 항목을 찾으면 해당 시스템은 새 시스템과 일치하도록 마이그레이션됩니다.
* 두 항목이 모두 일치하지만 동일한 시스템이 아닌 경우 오류가 발생하고 온보딩이 중단됩니다.
* 이 경우 관리자는 시스템 중 하나 이상을 제거하여 충돌을 해결해야 합니다.
