[[custom-info]]
= 사용자 정의 시스템 정보
:description: 키-값 쌍을 사용하여 특정 머신에 할당할 수 있는 맞춤형 클라이언트 정보를 포함하는 방법을 배우십시오.
:revdate: 2024-03-05
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

클라이언트에 대한 사용자 정의 시스템 정보를 포함할 수 있습니다.
시스템 정보는 `key:value` 쌍으로 정의되며, 클라이언트에 할당할 수 있습니다.
예를 들어, 특정 프로세서에 대한 `key:value pair`을 정의한 다음, 해당 프로세서가 설치된 모든 클라이언트에 그 키를 할당할 수 있습니다.
사용자 정의 시스템 정보는 분류되며, {productname} {webui}를 사용하여 검색할 수 있습니다.

시작하기 전에 사용자 정의를 저장할 수 있게 허용하는 키를 생성해야 합니다.



.절차 사용자 정의 시스템 정보 키 생성
. {productname} {webui}에서 menu:시스템[사용자 정의 시스템 정보]로 이동한 후, btn:[키 생성]을 클릭합니다.
. `Key Label` 필드에 키의 이름을 입력합니다.
  공백을 사용하지 마십시오.
  예: `intel-x86_64-quadcore`.
. `Description` 필드에 필요한 추가 정보를 입력합니다.
. 필요한 각 키에 이 작업을 반복합니다.

정보는 {salt} pillar를 통해 제공됩니다.
다음과 같은 명령으로 이 정보를 검색할 수 있습니다:

----
salt $minionid pillar.get custom_info:key1
----

이 명령을 실행한 후의 출력은 다음과 같습니다.

----
$minionid:
    val1
----

사용자 정의 시스템 정보 키를 몇 개 생성했으면 이 키를 클라이언트에 적용할 수 있습니다.



.절차 클라이언트에 사용자 정의 정보 키 적용
. {productname} {webui}에서 `Systems`으로 이동하고, 사용자 정의 정보를 적용할 클라이언트를 클릭한 후, menu:세부정보[사용자 정의 정보] 탭으로 이동합니다.
. btn:[값 생성]을 클릭합니다.
. 적용하려는 값을 찾아 키 레이블을 클릭합니다.
. `Value` 필드에 추가 정보를 입력합니다.
. btn:[키 업데이트]를 클릭하여 사용자 정의 정보를 클라이언트에 적용합니다.

구성 관리에 대한 자세한 정보는 xref:client-configuration:configuration-management.adoc[]을(를) 참조하십시오.
