[[package-management]]
= 패키지 관리
:description: SUSE Multi-Linux Managers 사용자 인터페이스를 사용하여 클라이언트에서 소프트웨어 패키지를 구성하고 관리하며 시스템을 탐색하고 클라이언트를 선택하고 소프트웨어에 접근합니다.
:revdate: 2024-11-21
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

클라이언트는 패키지를 사용해 소프트웨어를 설치, 제거 및 업그레이드합니다.

// available subtabs:
//     List / Remove
//     Upgrade
//     Install
//     Lock / Unlock
//     Profiles
//     Non Compliant


클라이언트에서 패키지를 관리하려면 `Systems`으로 이동하고 관리할 클라이언트를 클릭한 다음 menu:시스템[소프트웨어 > 패키지] 하위 탭으로 이동합니다.
이 섹션에서 사용할 수 있는 옵션은 선택한 클라이언트의 유형과 현재 채널 구독에 따라 다릅니다.

대부분의 패키지 관리 작업은 작업 체인에 추가할 수 있습니다.
작업 체인에 대한 자세한 내용은 xref:reference:schedule/action-chains.adoc[]을 참조하십시오.


[IMPORTANT]
==== 

패키지가 설치되거나 업그레이드되면 라이선스 또는 EULA가 자동으로 수락됩니다.
====


== 프로파일을 사용한 패키지 비교


저장된 프로파일 또는 다른 클라이언트에 설치된 패키지와 클라이언트에 설치된 패키지를 비교할 수 있습니다.
비교가 이루어지면 선택한 클라이언트를 일치하도록 수정할 수 있습니다.

프로파일에 대해 패키지를 비교하려면 프로파일을 저장해야 합니다.
프로파일은 현재 설치된 클라이언트의 패키지에서 생성됩니다.
프로파일이 생성되면 동일한 패키지가 설치된 더 많은 클라이언트를 설치하는 데 사용할 수 있습니다.


.절차 저장 프로파일 생성
. {productname} {webui}에서 `Systems`으로 이동하고 프로파일을 기반으로 할 클라이언트를 클릭한 다음 menu:시스템[소프트웨어> 패키지> 프로파일] 하위 탭으로 이동합니다.
. btn:[시스템 프로파일 생성]을 클릭합니다.
. 프로파일 이름 및 설명을 입력하고 btn:[프로파일 생성]을 클릭합니다.


.절차 클라이언트 패키지 비교
. {productname} {webui}에서 `Systems`으로 이동하고 비교할 클라이언트를 클릭한 다음 menu:시스템[소프트웨어> 패키지> 프로파일] 하위 탭으로 이동합니다.
    저장된 프로파일과 비교하려면 프로파일을 선택하고 btn:[비교]을 클릭하십시오.
. 다른 클라이언트와 비교하려면 클라이언트 이름을 선택하고 btn:[비교]를 클릭하여 두 클라이언트 간의 차이점 목록을 확인합니다.



[[package-management-orphaned-packages]]
== 독립 패키지

고아 패키지는 {productname}에 의해 동기화되지만 소프트웨어 채널과 연결되지 않은 패키지입니다.
따라서 고아 패키지는 일반적으로 {productname} 클라이언트에서 사용할 수 없으며 사용자는 추가 노력이 없이는 이러한 패키지를 설치할 수 없습니다.

패키지는 다음 이벤트 중 하나로 인해 독립 패키지가 될 수 있습니다.

* 동기화된 리포지토리는 패키지를 제거합니다.
  기본적으로, {productname}은 해당 패키지를 채널에서 연결 해제하지만, 패키지는 제거하지 않습니다.
* 리포지토리는 패키지를 최신 버전으로 대체하므로 이전 버전이 제거됩니다.
* (공간 부족 예외 사항 등으로 인해) 재동기화 프로세스가 중단되었으며, 따라서 다운로드한 패키지가 채널에 연결되지 않았습니다.
* 사용자가 패키지를 수동으로 업로드했지만 채널과 연결하지 않았습니다.

고아 패키지는 사용자 환경에서 공간을 차지하며, 채널과 연결되어 있지 않기 때문에 클라이언트에게 쉽게 배포할 수 없습니다.
고아 패키지는 부팅이나 고객 특정 절차와 같은 특정 작업 흐름에서 의미가 있을 수 있습니다.

{webui}에서 menu:소프트웨어[관리> 패키지> 채널이 없는 패키지 보기]를 클릭하여 고아 패키지를 볼 수 있습니다.

{productname}은 주기적으로 고아 패키지를 검색하고 패키지 조직 ID를 1로 수정하는 작업을 실행합니다.
이는 작업 실행 후에만 고아 패키지를 삭제할 수 있음을 의미합니다.
삭제할 수 없는 고아 패키지를 발견하면 24시간 기다렸다가 다시 삭제를 시도하십시오.

// .Procedure: Deleting orphaned packages

독립 패키지 삭제:

// * With the UI (FIXME is this possible?  How?

* 개별 패키지를 대상으로 명령줄 도구를 사용하여 작업할 수 있습니다. 예:
+
----
spacecmd package_remove zypper-1.14.52-150400.1.9.x86_64
----

* 모든 독립 패키지를 한 번에 대상으로 지정하는 명령 줄 도구 사용:
+
----
spacecmd package_removeorphans
----
