[[registration-sudo]]
= 루트 액세스 및 sudo 구성
:description: 루트 SSH 액세스를 허용하지 않는 시스템에서 소프트웨어를 설치 및 관리할 수 있도록 암호 없는 sudo 액세스 권한을 가진 비루트 사용자를 구성하십시오.
:revdate: 2026-08-31
:page-revdate: {revdate}

많은 운영 체제({ubuntu}, {debian}, {raspberrypios}, {sle} 16 등)는 기본적으로 `root` 사용자에 대한 SSH 액세스를 비활성화하거나 `root` 암호를 구성하지 않은 상태로 설치됩니다.
이러한 클라이언트를 온보딩하려면, 필요한 Python 및 Salt 미니언 바이너리에 대해 암호 없는 `sudo` 권한이 구성된 일반 사용자를 사용할 수 있습니다.

[IMPORTANT]
====
이 구성은 클라이언트를 부팅하고 등록하는 경우에만 필요합니다.
클라이언트가 성공적으로 등록되면 {productname} 에이전트가 `root` 권한으로 실행되며, 이 임시 암호 없는 `sudo` 액세스는 더 이상 필요하지 않습니다.
보안상의 이유로 등록이 완료된 후 `sudoers` 파일에서 이러한 줄을 제거하는 것이 좋습니다.
====


== 비루트 사용자에게 sudo 액세스 권한 부여

비루트 사용자를 사용하여 클라이언트를 온보딩하려면 클라이언트 시스템의 `sudoers` 파일을 편집하여 특정 명령에 대한 암호 없는 권한 상승을 허용해야 합니다.

.절차 암호 없는 sudo 액세스 권한 부여
[role="procedure"]
_____
. 클라이언트에서 `sudoers` 파일을 편집하려면 다음을 실행하십시오:
+
----
sudo visudo
----
. 파일 끝부분에 다음 줄을 추가합니다. `<user>`을(를) 클라이언트를 부팅하는 사용자의 이름으로 교체하십시오:
+
----
<user>  ALL=NOPASSWD: /var/tmp/venv-salt-minion/bin/python
----
_____

[NOTE]
====
기본 Salt 번들 대신 레거시 수동 `salt-minion` 등록 설정을 사용하는 이전 운영 체제({sle} 15 등)의 경우, 권한 상승을 위해 `/usr/bin/python3`이(가) 여전히 필요할 수 있습니다:
+
----
<user>  ALL=NOPASSWD: /usr/bin/python3, /var/tmp/venv-salt-minion/bin/python
----
====

[NOTE]
====
자체 설치된 운영 체제 버전은 {webui} 및 부팅 스크립트가 권한 상승 단계에서 대화형 암호 입력을 지원하지 않으므로 암호 없는 권한 상승이 필요합니다.
클라우드 인스턴스의 경우, 이는 일반적으로 기본 사용자에 대한 sudoers 구성을 설정하는 `cloud-init`에 의해 자동으로 처리됩니다.
====
