[[registration-overview]]
= 클라이언트 등록
:description: SUSE Multi-Linux Manager 서버에서 클라이언트를 효과적으로 등록하는 방법을 다양한 등록 방식 및 운영 체제별 특성을 고려하여 알아보십시오.
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

클라이언트를 {productname} 서버에 등록하는 방법이 몇 가지 있습니다.
이 섹션에서는 사용 가능한 다양한 방법을 다룹니다.
또한 클라이언트에서 실행할 운영 체제에 대한 특정 정보가 포함되어 있습니다.

시작하기 전에 다음 사항을 확인하십시오.

* 클라이언트는 등록 전에 날짜 및 시간을 {productname} 서버와 정확하게 동기화한 상태이어야 합니다.
* 활성화 키를 생성했습니다.
  활성화 키 생성에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]을 참조하십시오.


.부트스트래핑 후 설치 프로그램 업데이트 채널 처리
[IMPORTANT]
====
클라이언트 시스템이 부팅된 후에는 **Installer Updates** 채널을 제거해야 합니다. 
표준 업데이트 채널에는 이미 필요한 업데이트가 포함되어 있어 이 채널은 중복됩니다.

또한, 이 채널은 마이그레이션 중에 필요하지 않으므로 사용하지 않아야 합니다.
====


[IMPORTANT]
====
{productname} 서버의 기본 운영 체제를 {productname} 자체에 등록하지 마십시오.
{productname} 서버의 기본 운영 체제는 개별적으로 관리하거나 별도의 {productname} 서버를 사용하여 관리해야 합니다.

{productname} 서버 컨테이너를 관리하려면 `mgradm` 도구를 사용하십시오.

====

ifeval::[{mlm-content} == true]


[IMPORTANT]
====
{productname}의 이전 버전에서 최신 버전으로 마이그레이션한 후에는 잠재적인 문제를 방지하기 위해 새 시스템을 온보딩하기 전에 부트스트랩 스크립트를 다시 생성하는 것이 적극 권장됩니다.
====

endif::[]
