[[registering.clients.webui]]
= {webui}로 클라이언트 등록
:description: 웹 UI에서 시스템 부트스트래핑으로 이동하여 지정된 세부정보와 선택한 인증 방법으로 클라이언트를 등록합니다.
:revdate: 2025-07-09
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

== 소개


클라이언트를 부팅하는 것은 {webui}을 사용하여 xref:specialized-guides:salt/salt-ssh.adoc[Salt SSH]로 클라이언트에서 부팅 프로세스를 실행하는 것입니다.
Salt SSH는 포함된 Python 인터프리터와 함께 Salt 번들을 사용합니다.
따라서 클라이언트에 다른 Python 인터프리터를 설치할 필요가 없습니다.

Salt 번들은 부팅 리포지토리와 함께 제공됩니다. 따라서 클라이언트의 부팅 프로세스를 시작하기 전에 부팅 리포지토리를 생성해야 합니다.
셸 스크립트는 클라이언트의 운영 체제를 감지하고 적절한 부팅 리포지토리에서 Salt 번들을 배포하며, 부팅 스크립트와 동일한 논리를 사용합니다.

자세한 내용은 xref:client-configuration:bootstrap-repository.adoc#_prepare_to_create_a_bootstrap_repository[부팅 리포지토리 생성 준비]를 참조하십시오.

[IMPORTANT]
====
{productname} 서버를 자체적으로 등록하지 마십시오.
{productname} 서버는 개별적으로 관리하거나 별도의 {productname} 서버를 사용하여 관리해야 합니다.
여러 서버 사용에 대한 자세한 내용은 xref:specialized-guides:large-deployments/hub-multi-server.adoc[]을 참조하십시오.
====

== {webui}로 클라이언트 등록

.절차 {webui}로 클라이언트 등록

. {productname} {webui}에서 menu:시스템[부팅]으로 이동합니다.
. `Host` 필드에 부팅할 클라이언트의 정규화된 도메인 이름(FQDN)을 입력합니다.
. `SSH Port` 필드에서 클라이언트를 연결하고 부팅하는 데 사용할 SSH 포트 번호를 입력합니다.
    기본적으로 SSH 포트는 `22`입니다.
. `User` 필드에서 클라이언트에 로그인할 사용자 이름을 입력합니다.
    기본적으로 사용자 이름은 `root`입니다.
. `Authentication` 방법을 선택하십시오:
.. SSH 키를 사용하여 클라이언트를 부팅하려면 `Authentication` 필드에서 `SSH Private Key`를 확인하고 클라이언트에 로그인할 때 사용할 SSH 개인 키를 업로드하십시오.
    SSH 개인 키에 암호 구문이 필요한 경우 `SSH Private Key Passphrase` 필드에 입력하거나 암호 구문이 필요하지 않은 경우 이 필드를 공백으로 두십시오.
.. 비밀번호로 클라이언트를 부팅하려면 `Authentication` 필드에서 `Password`를 확인하고 비밀번호를 입력하여 클라이언트에 로그인하십시오.
. `Activation Key` 필드에서 클라이언트를 부팅하는 데 사용할 소프트웨어 채널과 연결된 활성화 키를 선택합니다.
    자세한 내용은 xref:client-configuration:activation-keys.adoc[]을 참조하십시오.
. 선택 사항: `Proxy` 필드에서 클라이언트를 등록할 프록시를 선택합니다.
. 기본적으로 `Disable SSH Strict Key Host Checking` 확인란이 선택되어 있습니다.
    따라서 사용자가 수동으로 인증할 필요 없이 부트스트랩 프로세스가 자동으로 SSH 호스트 키를 수락할 수 있습니다.
. 선택 사항: `Manage System Completely via SSH` 확인란을 선택합니다.
    이 옵션을 선택하면 서버에 연결하기 위해 SSH를 사용하도록 클라이언트가 구성되고 다른 연락 방법은 구성되지 않습니다.
+
연락 방법에 대한 자세한 정보는 xref:client-configuration:contact-methods-intro.adoc[]을 참조하십시오.
. btn:[부팅]을 클릭하여 등록을 시작합니다.
. 부팅 프로세스가 완료되면 클라이언트가 menu:시스템[시스템 목록]에 나열됩니다.


[IMPORTANT]
====
* SSH 개인 키는 부팅 프로세스 동안에만 저장됩니다.
  부팅이 완료되면 {productname} 서버에서 삭제됩니다.
* 클라이언트에서 {productname}을 사용하여 새 패키지나 업데이트가 설치되면 모든 최종 사용자 사용권 계약(EULA)이 자동으로 수락됩니다.
  패키지 최종 사용자 사용권 계약을 검토하려면 {webui}에서 패키지 세부정보 페이지를 엽니다.
====


== 로컬 할당 리포지토리 처리

{productname}에 의해 제공되지 않는 클라이언트에 직접 할당된 리포지토리는 일반적인 사용 사례가 아닙니다.
문제를 일으킬 수 있습니다.
따라서 Salt를 통한 부팅은 부팅 프로세스 시작 시 모든 로컬 리포지토리를 비활성화합니다.

나중에 Highstate 또는 패키지 설치를 실행할 때처럼 채널 상태를 사용할 때마다 로컬에 할당된 모든 리포지토리가 다시 비활성화됩니다.

클라이언트에서 사용되는 모든 소프트웨어 패키지는 {productname}에 의해 제공되는 채널에서 나와야 합니다.
사용자 정의 채널 생성에 대한 자세한 정보는 `Custom Channels`를 xref:administration:custom-channels.adoc[]에서 참조하십시오.
