[[repos]]
= 소프트웨어 리포지토리
:description: SUSE Multi-Linux Manager 채널과 클라이언트의 로컬 리포지토리에서 패키지를 설치하기 위해 소프트웨어 리포지토리를 구성합니다.
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

리포지토리는 소프트웨어 패키지를 수집하는 데 사용됩니다.
소프트웨어 리포지토리에 접근할 수 있는 경우, 해당 리포지토리가 제공하는 소프트웨어를 설치할 수 있습니다.
클라이언트를 채널에 할당하고 클라이언트에서 패키지를 설치 및 업데이트하려면 {productname}의 소프트웨어 채널과 연결된 리포지토리가 최소한 하나 있어야 합니다.

{productname}의 대부분의 기본 채널은 이미 올바른 리포지토리와 연결되어 있습니다.
사용자 정의 채널을 생성하는 경우, 접근할 수 있는 리포지토리 또는 직접 생성한 리포지토리와 연결해야 합니다.

사용자 정의 리포지토리 및 채널에 대한 자세한 내용은 xref:administration:custom-channels.adoc[]을 참조하십시오.



== 로컬 리포지토리 위치


클라이언트에서 로컬 리포지토리를 구성하여 {productname} 채널이 공급하지 않는 패키지를 제공할 수 있습니다.

[WARNING]
====
대부분의 경우, 클라이언트 시스템은 로컬 리포지토리를 필요로 하지 않습니다.
로컬 리포지토리는 클라이언트에서 사용 가능한 패키지를 파악하는 데 문제를 일으킬 수 있습니다.
이로 인해 예상치 못한 패키지가 설치될 수 있습니다.
====

온보딩 중에는 로컬 리포지토리가 비활성화됩니다.

채널 상태가 실행될 때마다 로컬 리포지토리는 비활성화됩니다.
예를 들어, 하이 스테이트를 적용하거나 패키지 작업을 수행할 때입니다.

온보딩 후에도 로컬 리포지토리를 계속 사용하도록 설정해야 하는 경우 해당 클라이언트에 대해 다음 열을 설정해야 합니다.

`/srv/pillar/top.sls` 파일을 편집하세요:

----
base:
  'minionid':
    - localrepos
----

`/srv/pillar/localrepos.sls` 파일을 편집하세요:

----
mgr_disable_local_repos: False
----

클라이언트가 온보딩을 완료하고 나면 다음 위치에 로컬 리포지토리를 추가할 수 있습니다.

[[local-repo-locations]]
[cols="1,1", options="header"]
.로컬 리포지토리 위치
|===

ifeval::[{mlm-content} == true]
| 클라이언트 운영 체제 | 로컬 리포지토리 디렉토리
| {sles} | `/etc/zypp/repos.d`
| {opensuse} | `/etc/zypp/repos.d`
| {sles} {es} | `/etc/yum.repos.d/`
| {rhel} 및 유사 파생물 | `/etc/yum.repos.d/`
| {ubuntu} | `/etc/apt/sources.list.d/`
| {debian} | `/etc/apt/sources.list.d/`
endif::[]


// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{uyuni-content} == true]
| 클라이언트 운영 체제 | 로컬 리포지토리 디렉토리
| {sles} | `/etc/zypp/repos.d`
| {opensuse} | `/etc/zypp/repos.d`
| {rhel} 및 유사 파생물 | `/etc/yum.repos.d/`
| {ubuntu} | `/etc/apt/sources.list.d/`
| {debian} | `/etc/apt/sources.list.d/`
endif::[]

|===
