[[vhm-azure]]
= 가상 호스트 관리자 및 Azure
:description: Azure에 대한 가상 호스트 관리자를 구성하고 SUSE Multi-Linux Manager를 사용하여 Microsoft Azure에서 인스턴스를 수집합니다.
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

// 2024-04-04 OM: It had been decided in the conversation with the mlm PO 
// that this Public Cloud related file can stay in the Uyuni books


가상 호스트 관리자(VHM)을 사용하여 Microsoft Azure에서 인스턴스를 수집할 수 있습니다.

VHM은 {productname}이(가) 가상 머신에 대한 정보를 얻고 보고할 수 있도록 합니다.
VHM에 대한 자세한 내용은 xref:client-configuration:vhm.adoc[]를 참조하십시오.


== 전제 조건


사용자가 생성하는 VHM은 Azure VM에 액세스하려면 올바른 권한이 할당되어 있어야 합니다.

구독 관리자 자격으로 Azure 계정에 로그인하고 Azure 사용자 계정과 응용 프로그램이 올바른 그룹에 있는지 확인하십시오.
응용 프로그램이 속한 그룹은 응용 프로그램의 역할을 결정하며, 따라서 권한도 결정합니다.

== Azure VHM 생성
가상 호스트 관리자(VHM)는 {productname} 서버에서 실행됩니다.

`virtual-host-gatherer-libcloud` 패키지를 {productname} 서버에 설치했는지 확인하십시오.


.절차 Azure VHM 생성

. {productname} {webui}에서 menu:Systems[Virtual Host Managers]로 이동합니다.
. btn:[Create]를 클릭하고 드롭다운 메뉴에서 `Azure`를 선택합니다.
. `Add an Azure Virtual Host Manager` 섹션에서 다음 매개변수를 사용합니다.
* `Label` 필드에 VHM의 사용자 지정 이름을 입력합니다.
* `Subscription ID` 필드에 `Azure portal > Services > Subscriptions` 페이지에서 찾은 구독 ID를 입력합니다.
* `Application ID` 필드에 응용 프로그램 등록 시 수집한 응용 프로그램 ID를 입력합니다.
* `Tenant ID` 필드에 응용 프로그램 등록 시 수집한 Azure에서 제공한 테넌트 ID를 입력합니다.
* `Secret Key` 필드에 Azure 인스턴스에 연결된 비밀 키를 입력합니다.
* `Zone` 필드에 VM이 있는 영역을 입력합니다. 예를 들어, West Europe의 경우 `westeurope`를 입력합니다.
    이 키는 작업과 일치하는 등록을 위해 필요합니다.
. btn:[Create]를 클릭하여 변경 사항을 저장하고 VHM을 생성합니다.
. `Virtual Host Managers` 페이지에서 새 VHM을 선택합니다.
. `Properties` 페이지에서 btn:[데이터 새로 고침]을 클릭하여 새 VHM을 목록에 추가합니다.

어떤 객체 및 리소스가 목록에 포함되었는지 확인하려면 menu:시스템[시스템 목록> 가상 시스템]으로 이동하십시오.


== 권한 할당
// OM 2022-02-28: if the UI suggestion has been implemented (#1170298 via #1170514) we may eventually be able to remove this section
권한이 올바르게 설정되지 않으면 `virtual-host-gatherer`를 실행할 때 다음과 같은 오류가 발생할 수 있습니다.

----
General error: [AuthorizationFailed] The client 'client_name' with object id 'object_ID' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/not-very-secret-subscription-id' or the scope is invalid. If access was recently granted, please refresh your credentials.
----

올바른 자격 증명을 확인하려면 {productname} 서버의 프롬프트에서 다음 명령을 실행하십시오.

----
virtual-host-gatherer -i input_azure.json -o out_azure.json -vvv
----

`input_azure.json` 파일에는 다음 정보가 포함되어야 합니다.

----
[
    {
        "id": "azure_vhm",
        "module": "Azure",
        "subscription_id": "subscription-id",
        "application_id": "application-id",
        "tenant_id": "tenant-id",
        "secret_key": "secret-key",
        "zone": "zone"
    }
]
----

== Azure UUID

Azure 공용 클라우드에서 실행되는 인스턴스는 이 UUID를 {productname} 서버에 보고합니다.

----
13f56399-bd52-4150-9748-7190aae1ff21
----
