[[quickstart-sap-server]]
= Prepare Server

// This section needs cleanup for containers!!!

Before you start you need to deploy the {productname} Server.
The method for deploying the {productname} Server varies depending on your hardware and environment.

{productname} is deployed using the `mgradm` command.
During the deployment process, when you are prompted for which product to install, select {productname} Server.
For more information about deploying the {productname} Server, see xref:installation-and-upgrade:container-deployment/suma/server-deployment-suma.adoc[].

You need to do some configuration to set up the {productname} {webui}.
In your browser, navigate to the URL of the server, and configure your administration access to the {webui}.

Now you can use the {webui} to prepare software channels and activation keys for your clients.

On the {productname} Server, add the appropriate SAP channels:
From the {webui}, add [systemitem]``SUSE Linux Enterprise Server 15 for SAP``.

Synchronize the {productname} Server with the {SCC}.
You can do this using the {webui}.
Add the new channel to your activation key.

To check if a channel has finished synchronizing navigate to menu:Admin[Setup Wizard] and select the [guimenu]``Products`` tab.
This dialog displays a completion bar for each product when they are being synchronized.


[NOTE]
====
Software channels can be very large.
The initial channel synchronization can sometimes take up to several hours.

When the initial synchronization is complete, we recommended you clone the channel before you work with it.
This gives you a backup of the original synchronization data.
====
