[[quickstart-sap-setup]]
= Preparing Clients

Your SAP cluster requires several client systems.
Prepare your clients on physical or virtual hardware, and ensure you have {sles}{nbsp}15 for SAP installation media ready.
You cannot create an SAP cluster without the {sles} SAP extension, as it provides tooling specific to SAP.

One of the key features of SAP is high availability of the cluster.
Every component within an SAP cluster has redundancy and failover protection.
When you are preparing your clients, ensure you have enough hardware and infrastructure to allow for this.
For more information about hardware requirements, see https://documentation.suse.com/sles-sap/15-SP2/html/SLES-SAP-quick/cha-plan.html#sec-hardware[].

For more information about the clients you need to set up for an SAP cluster, see https://documentation.suse.com/sbp/all[].



== Register Clients to the {SCC}

Each client within your SAP cluster must be registered with the {scc}.
To obtain your registration code, navigate to https://scc.suse.com/login in your web browser.
Log in to your SCC account, or follow the prompts to create a new account.
Click the btn:[Subscriptions] tab to see the registration code.
When you install {sles}{nbsp}15 for SAP the {unifiedinstaller} prompts you for the code.

For more information about registering {productname} with {scc}, see xref:installation-and-upgrade:general-requirements.adoc[].



== Configure the Clients for Clustering

Every client system must have all the other client systems listed in their [path]``/etc/hosts`` file.
Open the [path]``/etc/hosts`` file on each client, and add the hostname for each of the other clients.



== Create a Shared Storage Device

Each of the clients needs to be able to access a shared disk.
The shared disk can be physical hardware connected by ethernet, or you can set up a virtual disk and access it with iSCSI.

If you use a virtual disk, consider hosting it on a separate system.
Do not use a client machine to host the shared storage disk.



== Download the SAP Installation Software

Download the SAP installation media and save a copy on each client.
The software that you require differs depending on your environment.
For example, if you are using HANA, you need the SAP HANA platform.
If you are using Netweaver, you need different packages.
These software packages are provided by SAP, not by {suse}.

Ensure you have saved the installation software in the same file system location on each client.
Alternatively, save it to a shared NFS drive.



== Configure Clients to Use Latest ``module.run``

Each client needs to be configured to use the latest version of ``module.run``.
On each of the client machines, open the ``/etc/salt/minion`` configuration file and add or edit this line:

----
use_superseded:
  - module.run
----

Restart the ``salt-minion`` process to enable the changes:

----
systemctl restart salt-minion
----


== Install Additional Disks for HANA


For the clients that are going to run the HANA database, you require an additional storage device.
This device is used to store files required by HANA, which are located in the [path]``/hana/`` directory.

We recommend that this storage device be at least 20{nbsp}GB.
For some installations, you might require more, and it is possible to use multiple disks to provide this storage.
For comprehensive hardware requirements, see https://documentation.suse.com/sbp/all[].



== Register Clients to the Server

First of all, make sure you have an activation key that is associated with the ``SLE-Product-SLES_SAP15`` base channel.
For more information about activation keys, see xref:client-configuration:activation-keys.adoc[].

In the {productname} {webui}, navigate to menu:Systems[Bootstrapping].
Fill in the appropriate details, and make sure you check the [guimenu]``Manage System Completely via SSH`` checkbox.
In the [guimenu]``Activation Key`` field, select the SLES for SAP activation key.

For more information about registering, see xref:client-configuration:registration-webui.adoc[].
