[[installation-proxy-containers]]
= {productname} 在 {leapmicro} {microversion} 上部署代理
:description: 使用逐步指南为 openSUSE Leap Micro 6.1 配置 SUSE Multi-Linux Manager 5.1 代理部署
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1
ifeval::[{mlm-content} == true]

:noindex:
endif::[]


本指南概述了 {productname} {productnumber} 代理的部署过程。
本指南假设您已经成功部署了 {productname} {productnumber} 服务器。
要成功完成部署，请执行以下操作：


.清单：代理部署
. 查看硬件要求。
+
// . Synchronize the {leapmicro} {microversion} parent channel and the Proxy extension child channel on the server.
. 在裸机上安装 {leapmicro} {microversion}。
+
// . Create a {salt} activation key.
. 将代理作为 {salt} 受控端启动。
. 生成代理配置。
. 将服务器中的代理配置传输到代理
. 使用代理配置将 {salt} 受控端作为代理注册到 {productname}。


.代理容器主机支持的操作系统
[NOTE]
====
容器主机支持的操作系统为 {leapmicro} {microversion}。

容器主机:: 容器主机是配备有容器引擎（如 Podman）的服务器，允许其管理和部署容器。这些容器包含应用程序及其基本部分，如库，但不包含完整的操作系统，从而使其轻量化。此设置确保应用程序在不同环境中以相同方式运行。容器主机提供这些容器所需的资源，如 CPU、内存和存储。
====


== 代理的硬件要求


下表列出了部署 {productname} 代理所需的硬件要求。

[cols="1,3,2", options="header"]
.代理硬件要求
|===

| 硬件
| 细节
| 推荐

| CPU
| {x86_64}、{arm}
| 最少 2 个专用 64 位 CPU 核心

| RAM
| 最低
| 2 GB

|
| 推荐
| 8 GB

| 磁盘空间
| `/`（根目录）
| 最少 40 GB

|
| `/var/lib/containers/storage/volumes`
| 至少 100 GB，存储要求应根据您将使用的 .iso 映像、容器和引导储存库的数量进行计算。

|===



== 容器主机要求

有关一般要求，请参见 xref:installation-and-upgrade:general-requirements.adoc[一般要求]。

应从安装介质安装 {leapmicro} {microversion} 服务器。
下面介绍此过程。



[[installation-proxy-containers-requirements]]
== 容器主机要求

有关 CPU、RAM 和存储要求，请参见 xref:installation-and-upgrade:hardware-requirements.adoc[硬件要求]。


[IMPORTANT]
====
为了确保客户端能够解析 FQDN 域名，容器化服务器和主机机器必须连接到功能正常的 DNS 服务器。此外，确保反向查找的正确配置也是至关重要的。
====


== 安装用于容器的 Uyuni 工具


.过程：升级在 {leapmicro} {microversion} 上安装 Uyuni 工具
. 在本地主机上打开终端窗口，或启动一个运行 {leapmicro} {microversion} 的虚拟机。

. 以 root 身份登录。

. 输入 `transactional-update shell`：
+
----
transactional-update shell
----

. 将以下储存库添加到您的 {leapmicro} {microversion} 服务器：
+

----
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Proxy-POOL-$(arch)-Media1/ uyuni-proxy-stable
----

. 刷新储存库列表并接受密钥：
+
----
zypper ref
----

. 安装容器工具：
+

[source, shell]
----
zypper in mgrpxy mgrpxy-bash-completion uyuni-storage-setup-proxy
----
+
[NOTE]
====
或者，您可以安装 `mgrpxy-zsh-completion` 或 `mgrpxy-fish-completion`。
====

. 退出事务外壳：
+
----
transactional update # exit
----

. 重引导主机。

////
// In master, we had already this reduced variant:

----
transactional-update
----

. Reboot the system.
. Log in as root.
. Install the container utilities:
+

[source, shell]
----
transactional-update pkg install mgrpxy mgrpxy-bash-completion uyuni-storage-setup-proxy
----
+

[NOTE]
====
Alternatively you may install `mgrpxy-zsh-completion` or `mgrpxy-fish-completion`.
====

////

有关 Uyuni 容器工具的更多信息，请参见 link:https://build.opensuse.org/repositories/systemsmanagement:Uyuni:Stable:ContainerUtils[Uyuni 容器工具]。


== 配置自定义永久性存储

该步骤可选。
但是，如果您的基础设施需要自定义的永久性存储，请使用 `mgr-storage-proxy` 工具。

* 有关详细信息，请访问 `mgr-storage-proxy --help`。
此工具可以简化容器存储和 Squid 缓存卷的创建。

如下所示使用命令：

----
mgr-storage-proxy <storage-disk-device>
----

例如：

----
mgr-storage-proxy /dev/nvme1n1
----


[NOTE]
====
此命令将在 `/var/lib/containers/storage/volumes` 处创建持久存储卷。

有关详细信息，请参见

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]
====


== 将代理主机作为受控端进行引导

.任务：引导代理主机
. 选择 menu:系统[启动]。
. 填写代理主机的相关字段。
. 从下拉列表中选择上一步骤中创建的激活密钥。
. 点击 btn:[+ 启动]。
. 等待启动过程成功完成。
  检查 menu:Salt[] 菜单，确认 {salt} 受控端密钥已列出并被接受。
. 重引导代理主机。
. 从 menu:系统[] 列表中选择主机，并在所有事件完成后触发第二次重启，以完成入职流程。


.任务：更新代理主机
. 从 menu:系统[] 列表中选择主机，并应用所有补丁以将其更新。
. 重引导代理主机。



// FIXME 2024-12-10, ke: use the snippet also here (see MLM equiv)
[[proxy-setup-containers-generate-config]]
== 生成代理配置

{productname} 代理的配置归档由 {productname} 服务器生成。
每个额外的代理都需要自己的配置归档。

[IMPORTANT]
====
在生成此代理配置之前，{productname} 代理的容器主机必须作为 Salt 受控端注册到 {productname} 服务器。
====


您将执行以下任务：

.过程：升级
. 生成代理配置文件。
. 将配置传输到代理。
. 使用 `mgrpxy` 命令启动代理。

[[proc-proxy-containers-setup-webui]]
.任务：使用 Web UI 生成代理容器配置

. 在 {webui} 中，导航到 menu:系统[代理配置] 并填写所需数据：
. 在 `Proxy FQDN` 字段中，输入代理的完全限定的域名。
. 在 `Parent FQDN` 字段中，输入 {productname} 服务器或另一个 {productname} 代理的完全限定的域名。
. 在 `Proxy SSH port` 字段中，输入 {productname} 代理上 SSH 服务侦听的 SSH 端口。建议保持默认值 8022。
. 在 `Max Squid cache size [MB]` 字段中，输入 Squid 缓存允许的最大大小。通常，这一数值不应超过容器可用存储空间的 60%。
. 在 `SSL certificate` 选择列表中选择是否为 {productname} 代理生成新的服务器证书或使用现有证书。
您可以将生成的证书视为 {productname} 内置（自签名）证书。
+
然后根据所做的选择提供用于生成新证书的签名 CA 证书的路径，或者要用作代理证书的现有证书及其密钥的路径。
+
在服务器上生成的 CA 证书存储在 `/var/lib/containers/storage/volumes/root/ssl-build` 目录中。
+
有关现有或自定义证书以及企业和中间证书概念的更多信息，请参见 xref:administration:ssl-certs-imported.adoc[]。

. 单击 btn:[生成] 以在 {productname} 服务器中注册新代理 FQDN，并生成包含容器主机详细信息的配置归档。
. 片刻之后，您将看到一个可供下载的文件。请将此文件保存在本地。


[[proxy-deploy-containers-transfer-config]]
== 传输代理配置

{webui} 生成一个配置归档。
该归档需要在代理容器主机上可供使用。


.任务：复制代理配置
. 将服务器容器中的文件复制到服务器主机操作系统：
+
----
mgrctl cp server:/root/config.tar.gz .
----

. 接下来，将服务器主机操作系统中的文件复制到代理主机：
+
----
scp config.tar.gz <proxy-FQDN>:/root
----

. 使用以下命令安装代理：
+ 

----
mgrpxy install podman config.tar.gz
----



[[proxy-deploy-containers-transfer-start]]
== 启动 {productname}{productnumber} 代理。

现在可以使用 `mgrpxy` 命令启动容器：

[[proc-install-containers-setup-start]]
.任务：启动并检查代理状态

. 调用以下命令启动代理：
+

----
mgrpxy start
----

. 调用以下命令检查容器状态：
+

----
mgrpxy status
----
+

应该会显示五个 {productname} 代理容器，并且它们应该属于 `proxy-pod` 容器 Pod：

* proxy-salt-broker
* proxy-httpd
* proxy-tftpd
* proxy-squid
* proxy-ssh



=== 为服务使用自定义容器映像

默认情况下，{productname} 代理套件设置为对其每个服务使用相同的映像版本和注册表路径。
但是，可以使用以`-tag`和`-image`结尾的安装参数覆盖特定服务的默认值。

例如，可以按如下方式使用此命令：

----
mgrpxy install podman --httpd-tag 0.1.0 --httpd-image registry.opensuse.org/uyuni/proxy-httpd /path/to/config.tar.gz
----

它会在重启httpd服务之前调整其配置文件，其中`registry.opensuse.org/uyuni/proxy-httpds`是要使用的镜像，`0.1.0`是版本标签。

要重置为默认值，请再次运行 install 命令但不要指定这些参数：

----
mgrpxy install podman /path/to/config.tar.gz
----

此命令首先将所有服务的配置重置为全局默认值，然后重新装载配置。
