[[proxy-conversion-from-client-uyuni]]
= 从客户端转换为代理
:description: 通过配置现有客户端系统作为代理，使用 Web UI 配置 SUSE Multi-Linux Manager Proxy
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

== 概览

本章描述了如何使用 {webui} 将客户端系统转换为 {productname} 代理。

本文假定代理主机系统已完成引导，且已订阅基础操作系统通道。

有关客户端入驻的信息，请参见 xref:client-configuration:registration-overview.adoc[]。

== 要求

开始转换前，请确保满足以下要求。


=== 客户端

- 已在 {productname} 中完成入驻。
- 可通过网络访问


== 部署准备工作

进行代理转换前，请完成以下准备工作，以免转换过程中出现中断。

=== SSL 证书

为确保代理与其他组件之间的通信安全，需要具备有效的 SSL 证书。

您需要准备：

* 为 {productname} 服务器证书签名的证书颁发机构 (CA) 的公共证书。
* 为代理创建激活密钥
* 附加到代理证书的其他信息。

[NOTE]
====
如果您的 CA 使用中间证书链，还必须包含所有中间证书。
====

如果不使用第三方证书，可以在 {productname} 容器内使用 `rhn-ssl-tool` 生成证书。

.生成 \{productname} Proxy 配置存档文件

. 在 {productname} 服务器主机上运行：
+
[source,shell]
----
mgrctl exec -ti -- rhn-ssl-tool --gen-server \
  --set-hostname="<PROXY-FQDN>" \
  --dir="/root/ssl-build"
----
+
有关其他参数的更多信息，请参见 xref:administration:ssl-certs-selfsigned.adoc[]。
+

. 将证书传输到 {productname} 服务器主机。
+
[source,shell]
----
mgrctl cp server:/root/ssl-build/<PROXY-FQDN>/server.crt /root/proxycert.pem
mgrctl cp server:/root/ssl-build/<PROXY-FQDN>/server.key /root/proxykey.pem
mgrctl cp server:/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT /root/rootca.pem
----
+
[NOTE]
====
如需确认证书和密钥文件的具体生成目录，可以执行以下命令列出相关目录：
----
mgrctl exec -ti -- ls -ltd /root/ssl-build/*/
----
====

. 从 {productname} 服务器主机传输证书
+

[source,shell]
----
scp <UYUNI-FQDN>:/root/proxycert.pem ./
scp <UYUNI-FQDN>:/root/proxykey.pem ./
scp <UYUNI-FQDN>:/root/rootca.pem ./
----

=== 部署准备工作

==== 安装 `mgrpxy`

必须从与您的系统匹配的储存库安装 `mgrpxy` 工具。从以下选项中选择适当的储存库：

https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/

.示例（适用于 openSUSE Leap Micro 5.5）：
[source,shell]
----
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/openSUSE_Leap_Micro_5.5/ uyuni-containerutils
zypper ref
zypper in mgrpxy
----

==== 部署容器映像

建议将容器镜像作为 RPM 包部署。请确保在客户端上安装以下软件包：

[source,shell]
----
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/containerfile/ uyuni-proxy-images
zypper ref
zypper in uyuni-proxy-httpd-image \
           uyuni-proxy-salt-broker-image \
           uyuni-proxy-squid-image \
           uyuni-proxy-ssh-image \
           uyuni-proxy-tftpd-image
----

有关隔离部署的详细信息，请参见 xref:installation-and-upgrade:container-deployment/mlm/proxy-air-gapped-deployment-mlm.adoc[]。

[NOTE]
====
对于事务性服务器，请将上述命令包裹在 transactional-update 外壳会话中执行，以确保操作的原子性和持久性：

[source,shell]
----
transactional-update shell
# (run zypper commands here)
exit
----

这能确保在事务性环境中正确应用更改。
====

== 升级代理

. 导航至客户端的 `Overview` 页面。
. 单击按钮 btn:[转换为代理]。
+
生成代理配置
+
此页面稍后可从 `Details` > `Proxy` > `Configuration` 选项卡访问。

. 在 {webui} 中，导航到 menu:代理[配置] 并填写所需数据：

+
.过程：升级配置代理
.. 在 `Parent FQDN` 字段中，输入父服务器或代理的完全限定的域名。
.. 在 `Proxy SSH port` 字段中，输入 {productname} 代理上 SSH 服务侦听的 SSH 端口。建议保持默认值：8022.
.. 在 `Max Squid cache size` 字段中，输入允许的最大 Squid 缓存大小（以 GB 为单位）。
.. 在 `Proxy admin email` 字段中，输入管理员的电子邮件地址。
.. 在 `Certificates` 部分，提供在准备步骤中获取的 {productname} 代理的证书。

.. 在 `Source` 部分，选择以下两个选项之一：`RPM` 或 `Registry`。
+
* 对于隔离的或受限环境，建议使用 `RPM` 选项。
* 如果可连接容器映像仓库，则可使用 `Registry` 选项。 +
如果选择此选项，系统会提示您从两个子选项中选择：`Simple` 或 `Advanced`。
+
** 如果选择 `Simple`，请在 `Registry URL` 和 `Containers Tag` 字段中提供值。
*** 对于 `Registry URL`，请使用：`registry.opensuse.org/uyuni`。
*** 从下拉列表中选择标记。

** 如果选择 `Advanced`，表单会显示一个额外的部分：
*** 对于每个单独的容器 URL 字段，请使用仓库：`registry.opensuse.org/uyuni` 后跟相应的后缀，例如 `_proxy-httpd_` 或 `_salt-broker_`。
*** 从下拉列表中选择标记。

. 填写完所有字段后，单击btn:[应用]以应用配置并调度代理安装任务。

== 执行迁移

查看客户端的事件历史记录，确认任务执行成功。

（可选）访问代理的 HTTP 端点，验证其是否显示欢迎页面。
