[[troubleshooting-remote-root-on-micro]]
= {sl-micro}의 원격 루트 로그인
:revdate: 2025-06-17
:page-revdate: {revdate}

For enhanced security, new installations of {sl-micro} 6.1 and later do not allow password-based remote root login anymore, which affects server and proxy container hosts running on {sl-micro} and managed {sl-micro} clients. Also, {sle-micro} 5.5 clients with password-based remote root login which will when be migrated to 6.1/6.2 will suddenly lose this access and must be newly configured. For more information, see SL Micro Release Notes 6.1 (https://www.suse.com/releasenotes/x86_64/SL-Micro/6.1/index.html#jsc-SMO-405).

While deploying components of {productname} such as a {productname} Proxy, by default, password-based remote root login is required. You can enable password-based remote root login with the following steps.


.Procedure: Enable SSH root login with a password on {sl-micro}
[role=procedure]
____

두 가지 방법으로 SSH 루트 로그인을 활성화할 수 있습니다. 두 가지 방법 중 가장 적합한 방법을 선택하면 됩니다.

.옵션 A: 사전 구성 패키지 사용

. 클라이언트의 UI/API에서 [package]``openssh-server-config-rootlogin`` 패키지를 설치합니다.

. 컨테이너 호스트를 재부팅해 UI 또는 터미널에서 새 구성을 활성화합니다.

.옵션 B: SSH 구성을 수작업으로 편집

. 내용이 다음과 같은 드롭인 구성 파일 [path]``/etc/ssh/sshd_config.d/permit_root.conf``를 추가합니다.

+

----
PermitRootLogin yes
----

. SSH 서버 구성 재로드

+

[source, shell]
----
systemctl reload sshd
----

. SSH로 연결된 경우, 서버에서 연결을 끊기 전에 새 SSH 연결을 열어 SSH 서버가 정상적으로 작동하는지 확인합니다.

____

[command]``transactional-update``에 대한 자세한 내용은 https://documentation.suse.com/sle-micro/6.1/html/Micro-transactional-updates/[]에서 확인할 수 있습니다.
