[[troubleshooting-]]
= 전체 디스크 이벤트 포함 컨테이너 문제 해결
:revdate: 2025-03-10
:page-revdate: {revdate}



////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

컨테이너의 영구 스토리지 매체로 마운트된 전용 디스크의 스토리지 공간이 부족할 경우 긴급 조치가 필요합니다.

스토리지 미디어 크기 조정 문제를 해결하려면 다음을 수행합니다. 컨테이너 호스트에서 나열된 모든 명령을 [literal]``root`` 권한으로 실행합니다.

.절차: 스토리지 매체 크기 조정

. 디스크 크기를 늘리십시오. 수행해야 할 작업은 설치 환경에 따라 다릅니다.

. 디스크를 분할한 경우(예: 디스크 [path]``/dev/vdb1``에 [path]``/dev/vdb``가 있는 경우) 다음 명령을 실행합니다.

+

다음 명령을 실행합니다.

+

--
.. [command]``parted /dev/vdb``
.. [literal]``(parted)`` [command]``print``
.. [literal]``(parted)`` [command]``resizepart NUMBER 100%``에서 [literal]``NUMBER``는 [command]``print`` 명령으로 표시되는 파티션 번호(예: [literal]``/dev/vdb1``인 경우 [literal]``1``)입니다.
.. [literal]``(parted)`` [command]``quit``
--

. 파일 시스템 크기를 조정합니다. 예를 들어, XFS 파일 시스템의 경우 다음 명령을 실행합니다.

+

[source, shell]
----
xfs_growfs /dev/vdb1
----

절차를 완료하면 XFS 파일 시스템이 디스크에서 사용 가능한 모든 공간을 사용하고 있어야 합니다.
