[[troubleshooting-packages]]
= 패키지 불일치 문제 해결
:revdate: 2025-02-06
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

클라이언트의 패키지가 잠긴 경우 {productname} 서버가 적용 가능한 패치 집합을 올바르게 결정하지 못할 수 있습니다. 이 경우 {webui}에서 패키지 업데이트를 사용할 수 있지만, 클라이언트에는 표시되지 않으며 클라이언트 업데이트 시도가 실패합니다. 패키지 잠금 및 제외 목록을 확인하여 클라이언트에서 패키지가 잠겨 있는지 또는 제외되는지 확인합니다.

클라이언트에서 패키지 잠금 및 제외 목록을 확인하여 패키지가 잠긴 상태인지 또는 제외되었는지 확인합니다.

// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{mlm-content} == true]

* 확장 지원 플랫폼에서 [path]``/etc/yum.conf``를 확인하고 ``exclude=``를 검색합니다.
endif::[]

* {sle} 및 {opensuse}에서 [command]``zypper locks`` 명령을 사용합니다.
