[[troubleshooting-mass-machineID-duplication]]
= 대량 Machine_id 중복
:revdate: 2025-10-23
:page-revdate: {revdate}

{productname}를 사용하여 가상 머신을 관리하는 경우 VM의 클론을 생성하는 것이 유용할 수 있습니다. 클론은 기존 디스크의 복사본인 기본 디스크를 사용하는 VM입니다.

VM을 복제하면 시간을 크게 절약할 수 있지만, 디스크에 중복된 식별 정보가 있으면 문제가 발생할 수 있습니다.

두 대의 컴퓨터를 등록하려고 할 때 한 컴퓨터가 다른 컴퓨터의 복제본인 경우, {productname}은(는) 이를 별개의 두 클라이언트로 등록하고자 할 수 있습니다. 그러나 원본 클라이언트와 복제본 모두의 컴퓨터 ID가 동일한 경우, {productname}은(는) 두 클라이언트를 하나의 시스템으로 등록하며, 두 번째 컴퓨터가 등록되면 데이터가 덮어써집니다.

이 문제는 복제본의 머신 ID를 변경하여 {productname}이(가) 두 개의 서로 다른 클라이언트로 인식하도록 하면 해결할 수 있습니다. 머신 ID 변경 방법에 대한 자세한 정보와 지침은 xref:administration:troubleshooting/tshoot-registerclones.adoc[]에서 확인할 수 있습니다.

하지만 일부 경우에는 기존 머신 ID에 의존하는 다른 애플리케이션에 장애를 유발할 수 있으므로, 모든 시스템에서 머신 ID를 변경할 수 없으며 이것이 실용적이지도 않습니다. 이러한 경우 {productname} 환경에서 사용하기 위해 가짜 머신 ID를 생성할 수 있는 옵션이 제공됩니다.

.절차: {productname}의 등록 시점에 머신 ID 생성
[role=procedure]
____

. 부트스트랩 스크립트를 생성합니다(이미 있는 경우 이 단계를 건너뜀). 자세한 내용은 xref:client-configuration:registration-bootstrap.adoc[]에서 확인할 수 있습니다.

. 파일을 열고 파라미터를 변경합니다.

+

----
GENERATE_OWN_MACHINEID=1
----

. 부트스트랩을 엄격하게 사용하면 머신 ID가 더 이상 충돌하지 않습니다.

____
