[[tshoot-hostname-rename]]
= {productname} 서버 이름 변경 문제 해결
:revdate: 2025-02-18
:page-revdate: {revdate}

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

////
Showing my working. --LKB 2020-06-22

Cause: Renaming the hostname
Consequence: Changes not picked up by db, clients and proxies
Fix: Use the [command]``spacewalk-hostname-rename`` script to update the settings in the PostgreSQL database and the internal structures of {productname}.
Result: Renaming is successfully propagated
////

{productname} 서버의 호스트 이름을 로컬로 변경하면 {productname} 설치가 제대로 작동하지 않습니다. 왜냐하면 데이터베이스에서 변경사항이 적용되지 않아 변경 사항이 클라이언트와 프록시로 전파되지 않기 때문입니다.



== 서버 이름 변경

{productname} 서버의 호스트 이름을 변경해야 하는 경우 [command]``mgradm server rename`` 명령을 사용하여 변경할 수 있습니다. 이 명령은 PostgreSQL 데이터베이스의 설정 및 {productname}의 내부 구조를 업데이트합니다.



=== 서버 구성

이 명령에는 필수 파라미터가 없지만, 컨테이너 호스트의 호스트 이름이 아닌 경우 새 호스트 이름을 지정할 수 있습니다.


새 호스트 이름과 일치하도록 SSL 인증서를 생성해야 하는 경우 SSL CA 비밀번호를 제공해야 합니다. 이 작업은 구성 파일을 사용하여 안전하게 수행할 수 있습니다.

.절차: SSL CA 비밀번호의 구성 파일 준비
[role=procedure]
____
. 다음과 같이 [path]``config.yaml`` 파일을 작성합니다.

+

[source, shell]
----
ssl:
  password: "<CA PASSWORD>"
----
____

이 파일은 다음 절차에서 사용됩니다.

.절차: {productname} 서버 이름 변경
[role=procedure]
____
. DNS 서버에서 로컬 및 원격으로 시스템 수준에서 서버의 네트워크 설정을 변경합니다.
    역방향 이름 확인을 위한 구성 설정도 제공해야 합니다. 네트워크 설정 변경은 다른 시스템의 이름을 변경할 때와 동일한 방식으로 수행됩니다.

. 새 네트워크 구성을 사용하고 호스트 이름이 변경되었는지 확인하려면 {productname} 서버를 재부팅합니다.

. 컨테이너 호스트에서 명령줄을 통해 다음 명령을 실행하십시오. SSL CA 비밀번호를 저장하기 위해 파일을 생성한 경우 [command]``-c config.yaml``을 추가합니다.

+

[source, shell]
----
mgradm server rename
----

+

새 호스트 이름이 확인되지 않으면 명령이 실패합니다.

____

서버 컨테이너의 재시작 중에도 이름 바꾸기 절차가 수행됩니다. 다음 명령을 실행하면 로그를 확인할 수 있습니다.

[source, shell]
----
mgrctl exec -ti -- journalctl -u uyuni-update-config
----

서버 컨테이너를 재시작할 때 이 명령은 모든 {salt} 클라이언트의 열 데이터의 새로 고침을 트리거합니다: 실행 시간은 등록된 클라이언트 수에 따라 달라집니다.


=== 직접 관리 클라이언트 재구성

*클라이언트가 {productname} 프록시를 통해 관리되는 경우 이 절차를 건너뜁니다.*

다음 절차에 따라 직접 관리 클라이언트가 새 호스트 이름과 IP 주소를 인식하도록 재구성합니다.

.절차: 직접 관리 클라이언트 재구성
[role=procedure]
____
. 모든 클라이언트의 {salt} 클라이언트 구성 파일에서 새 {salt} 마스터({productname} 서버)의 이름을 지정합니다. 파일 이름은 [path]``/etc/venv-salt-minion/minion.d/susemanager.conf`` 또는 {salt} 번들을 사용하지 않는 경우 [path]``/etc/salt-minion/minion.d/susemanager.conf``입니다.

+

----
master: <new_hostname>
----

. 모든 클라이언트에서 {salt} 서비스를 다시 시작합니다. 다음 중 하나를 실행합니다.

+

[source, shell]
----
systemctl restart venv-salt-minion
----

+

또는 {salt} 번들을 사용하지 않는 경우에는 다음을 실행합니다.

+

[source, shell]
----
systemctl restart salt-minion
----

____


=== ClientcConnection with applying high state

마지막으로 호스트 이름을 {salt} 클라이언트 구성에 완전히 전파하려면 highstate를 적용합니다. highstate를 적용하면 리포지토리 URL의 호스트 이름이 업데이트됩니다.



== 프록시 재구성

모든 프록시를 다시 구성해야 합니다. 새 서버 인증서와 키를 프록시에 복사해야 합니다. 자세한 내용은 xref:installation-and-upgrade:install-proxy.adoc[]에서 확인할 수 있습니다.


[IMPORTANT]
====
프록시를 통해 PXE 부팅을 사용하는 경우 프록시의 구성 설정을 확인해야 합니다. 컨테이너화되지 않은 {productname} 프록시 4.3을 통해 PXE 부팅을 사용하는 경우, [systemitem]``tftpsync``를 재구성해야 합니다.

컨테이너 호스트에서 다음을 실행합니다.

[source, shell]
----
mgrctl exec -ti -- configure-tftpsync.sh
----

====
