[[public-cloud-requirements]]
= Public Cloud Requirements

// Deprecated. See Quick Start: Public Cloud Guide instead. --LKB 2021-01-13

You can run {productname} Server on a public cloud instance from a third-party provider such as Amazon EC2, or Microsoft Azure.

This section details the requirements for using {productname} on a public cloud instance.

[NOTE]
====
Public clouds provide {productname} under a Bring Your Own Subscription (BYOS) model.
This means that you must have {suse} product entitlements to use {productname}.
For more information about public cloud entitlements, see xref:installation:pubcloud-setup.adoc[].
====

Depending on the public cloud framework you are using, you can locate the {productname} images by searching for the  keywords ``suse``, ``manager``, ``proxy``, or ``BYOS``.


== Instance Requirements

Select a public cloud instance type that meets the hardware requirements in xref:installation:hardware-requirements.adoc[].

Before you begin, here are some other considerations:

* The {productname} setup procedure performs a forward-confirmed reverse DNS lookup.
    This must succeed in order for the setup procedure to complete and for {productname} to operate as expected.
    It is important to perform hostname and IP configuration before you set up {productname}.
* {productname} Server and Proxy instances need to run in a network configuration that provides you control over DNS entries, but cannot be accessed from the internet at large.
* Within this network configuration DNS resolution must be provided: `hostname -f` must return the fully qualified domain name (FQDN).
* DNS resolution is also important for connecting clients.
* DNS is dependent on the cloud framework you choose.
    Refer to the cloud provider documentation for detailed instructions.
* We recommend that you locate software repositories, the server database, and the proxy squid cache on an external virtual disk.
    This prevents data loss if the instance is unexpectedly terminated.
    This section includes instructions for setting up an external virtual disk.


[NOTE]
====
If you are attempting to bootstrap traditional clients, check that you can resolve the host name of the server while you are logged in to the client.
You might need to add the FQDN of the server to [path]``/etc/hosts`` local resolution file on the client.
Check using the [command]``hostname -f`` command with the local IP address of the server.
====



== Network Requirements

When you use {productname} on a public cloud, you must use a restricted network.
We recommend using a VPC private subnet with an appropriate firewall setting.
Only machines in your specified IP ranges must be able to access the instance.

[WARNING]
====
When you run {productname} on public clouds, you must apply security measures to limit access to the instance.
A world-accessible {productname} instance violates the terms of the {productname} EULA, and is not supported by {suse}.
====

To access the {productname} {webui}, allow HTTPS when configuring the network access controls.



== Separate Storage Volumes

We recommend that the repositories and the database for {productname} are stored on separate storage devices to the root volume.
This will help to avoid data loss.
Do not use logical volume management (LVM) for public cloud installations.

You must set up the storage devices before you run the YaST {productname} setup procedure.

Provision your disk devices in the public cloud environment, according the cloud provider's documentation.
The size of the disk for repositories storage is dependent on the number of distributions and channels you intend to manage with {productname}.
When you attach the virtual disks, they will appear in your instance as Unix device nodes.
The names of the device nodes will vary depending on your provider, and the instance type selected.

For more information about setting up storage volumes and partitions, including recommended minimum sizes, see xref:installation:hardware-requirements.adoc[].
