== 生成代理配置


{productname} 代理的配置归档由 {productname} 服务器生成。每个附加代理都需要自身的配置归档。

对于容器化 {productname} 代理，您必须构建新的代理配置文件，然后重新部署容器以使更改生效。此流程适用于更新设置（包括 SSL 证书）。

//[NOTE]
//====
//2 GB represents the default proxy squid cache size.
//This will need to be adjusted for your environment.
//====

[IMPORTANT]
====
对于 Podman 部署，在生成此代理配置之前，必须将 {productname} 代理的容器主机作为客户端注册到 {productname} 服务器。
====

如果使用代理 FQDN 生成非注册客户端的代理容器配置（如 Kubernetes 用例中那样），系统列表中将出现一个新的系统项。此新项将显示在之前输入的“代理 FQDN”值下方并属于[literal]``外部``系统类型。

[NOTE]
====
Peripheral servers are always using third-party SSL certificates. If the hub server has generated the certificates for the peripheral server, it needs to generate the certificate of each proxy too.

On the hub server, run the following command.

[source, shell]
----
mgrctl exec -ti -- rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="COUNTRY" \
  --set-state="STATE" --set-city="CITY" --set-org="ORGANIZATION" \
  --set-org-unit="ORGANIZATION UNIT" --set-email="name@example.com" \
  --set-hostname=PROXY --set-cname="proxy.example.com"
----

需要使用的文件包括：

. [litteral]``/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT``（作为根 CA 证书）
. [litteral]``/root/ssl-build/<hostname>/server.crt``（作为代理证书）和
. [litteral]``/root/ssl-build/<hostname>/server.key``（作为代理证书的密钥）。
====

// tag::generate-proxy-config-section[]
=== 使用 {webui} 生成代理配置

.过程：使用 {webui} 生成代理容器配置
[role=procedure]
_____

. 在 {webui} 中，导航到menu:系统[代理配置]，然后填写所需数据：

. 在[guimenu]``代理 FQDN``字段中，键入代理的完全限定域名。

. 在[guimenu]``父 FQDN``字段中，键入 {productname} 服务器或另一个 {productname} 代理的完全限定域名。

. 在[guimenu]``代理 SSH 端口``字段中，键入 SSH 服务在 {productname} 代理上监听的 SSH 端口。建议保留默认值 8022。

. In the [guimenu]``Max Squid cache size [MB]`` field type maximal allowed size for Squid cache. Recommended is to use at most 80% of available storage for the containers.

+

[NOTE]
====
2 GB 表示默认的代理 squid 缓存大小。需要根据您的环境调整此大小。
====

+

在 [guimenu]``SSH 证书``选择列表中，选择应为 {productname} 代理生成新服务器证书还是使用现有证书。您可以考虑作为 {productname} 内置（自我签名）证书生成的证书。

+

然后根据所做的选择提供用于生成新证书的签名 CA 证书的路径，或者要用作代理证书的现有证书及其密钥的路径。

+

服务器生成的 CA 证书存储在 [path]``/var/lib/containers/storage/volumes/root/_data/ssl-build`` 目录中。

+

有关现有或自定义证书的详细信息以及企业和中间证书的概念，请参见 xref:administration:ssl-certs-imported.adoc[]。

. 单击 btn:[生成] 以在 {productname} 服务器中注册新代理 FQDN，并生成包含容器主机细节的配置归档 ([filename]``config.tar.gz``)。

. 片刻之后，系统会显示文件可供下载。请将此文件保存在本地。

_____


=== 使用 [literal]``spacecmd`` 和自我签名证书生成代理配置

可以使用 [literal]``spacecmd`` 生成代理配置。

.过程：使用 spacecmd 和自我签名证书生成代理配置
[role=procedure]
_____

. 通过 SSH 连接到您的容器主机。

. 执行以下命令（替换其中的服务器和代理 FQDN）：

+

----
mgrctl exec -ti 'spacecmd proxy_container_config_generate_cert -- dev-pxy.example.com dev-srv.example.com 2048 email@example.com -o /tmp/config.tar.gz'
----

. 从服务器容器复制生成的配置：

+

----
mgrctl cp server:/tmp/config.tar.gz
----

_____



=== 使用 [literal]``spacecmd`` 和自定义证书生成代理配置

可以使用 [literal]``spacecmd`` 为自定义证书（而不是默认的自我签名证书）生成代理配置。

.过程：使用 spacecmd 和自定义证书生成代理配置
[role=procedure]
_____

. 通过 SSH 连接到您的服务器容器主机。

. Execute the following commands, replacing the Server and Proxy FQDN:

+
----
for f in ca.crt proxy.crt proxy.key; do
  mgrctl cp $f server:/tmp/$f
done
mgrctl exec -ti 'spacecmd proxy_container_config -- -p 8022 pxy.example.com srv.example.com 2048 email@example.com /tmp/ca.crt /tmp/proxy.crt /tmp/proxy.key -o /tmp/config.tar.gz'
----

+
. 如果您的设置使用中间 CA，请同时复制该证书，并在命令中通过 `-i` 选项（可根据需要多次提供）包含该证书：

+
----
mgrctl cp intermediateCA.pem server:/tmp/intermediateCA.pem
mgrctl exec -ti 'spacecmd proxy_container_config -- -p 8022 -i /tmp/intermediateCA.pem pxy.example.com srv.example.com 2048 email@example.com /tmp/ca.crt /tmp/proxy.crt /tmp/proxy.key -o /tmp/config.tar.gz'
----

. 从服务器容器复制生成的配置：
+
----
mgrctl cp server:/tmp/config.tar.gz
----

_____

// end::generate-proxy-config-section[]
