== 准备 {sl-micro} {microversion} 主机


=== 下载安装媒体

.过程：下载安装媒体
[role=procedure]
____

. 访问 link:https://www.suse.com/download/sle-micro/[]，找到 {sl-micro} {microversion} 的安装媒体，并下载相应媒体文件。

. 将下载下来的 [filename]``.iso`` 映像放入一个 DVD 或 USB 闪存盘以进行安装。

____


=== 安装 {sl-micro} {microversion}

.过程：安装 {sl-micro} {microversion}
[role=procedure]
____

. 插入包含 {sle-micro} {microversion} 安装映像的 DVD 或 USB 闪存盘（USB 磁盘或密钥）。

. 引导或重引导您的系统。

. 使用箭头键选择[systemitem]``安装``。

. 调整键盘和语言。

. 单击[systemitem]``复选框``接受许可协议。

. 单击[systemitem]``下一步``继续。

. 选择注册方法。在本示例中，我们将在 {scclongform} 中注册服务器。

+

[NOTE]
====
{productname} {productnumber} 容器会安装为扩展。根据以下列出的所需特定扩展，您还需要有各个扩展的 {scclongform} 注册代码。

* {productname} {productnumber} 服务器
* {productname} {productnumber} 代理
* {productname} {productnumber} 零售分支服务器
====

+

[IMPORTANT]
====
{sl-micro} {microversion} 权利包含在 {productname} 权利中，因此不需要单独的注册代码。
====

. 输入您的 {scclongform} 电子邮件地址。

. 输入您的 {sl-micro} {microversion} 注册代码。

. 单击[systemitem]``下一步``继续。

. 要安装代理，请选中 {productname} {productnumber} 代理扩展；要安装服务器，请选中 {productname} {productnumber} 服务器扩展对应的``复选框``。

. 单击[systemitem]``下一步``继续。

. 输入您的 {productname} {productnumber} 扩展注册代码。

. 单击 btn:[下一步] 继续。

. 在 [systemitem]``NTP 配置``页面上，单击 btn:[下一步]。

. 在[systemitem]``系统身份验证``页面上，输入 root 用户的口令。单击 btn:[下一步]。

. 在[systemitem]``安装设置``页面上单击 btn:[安装]。

____

至此，{sl-micro} {microversion} 及 {productname} {productnumber} 扩展的安装已完成。有关虚拟机或物理机准备工作的详细信息，请参见 link:https://documentation.suse.com/sle-micro/6.1[{sl-micro} 部署指南]。



=== 从命令行注册（可选）

如果您在安装 {sl-micro} {microversion} 期间已将 {productname} {productnumber} 添加为扩展，则可以跳过此过程。不过，您也可以选择在安装 {sl-micro} {microversion} 期间单击 btn:[跳过注册] 按钮来跳过注册。本节提供了在安装 {sl-micro} {microversion} 后注册产品的步骤。

[NOTE]
====
以下步骤将注册 {x86_64} 体系结构的 {productname} {productnumber} 扩展，因此需要提供适用于 {x86_64} 体系结构的注册代码。要注册 {arm} 或 {s390x} 体系结构，请使用正确的注册代码。
====

.过程：从命令行注册
[role=procedure]
____
. 运行以下命令列出可用扩展：

+

----
transactional-update --quiet register --list-extensions
----

. 从可用扩展列表中选择一个要安装的扩展：

+

.. 如果要安装服务器，请使用您的 {productname} Server Extension {productnumber} x86_64 注册代码运行以下命令：

+

----
transactional-update register -p Multi-Linux-Manager-Server/5.1/x86_64 -r <reg_code>
----

.. 如果要安装代理，请使用您的 {productname} Proxy Extension {productnumber} x86_64 注册代码运行以下命令：

+

----
transactional-update register -p Multi-Linux-Manager-Proxy/5.1/x86_64 -r <reg_code>
----

. 重引导。


____


=== 更新系统

.过程：更新系统
[role=procedure]
____
. 以 *root* 身份登录。

. 运行 **transactional-update**：

+

[source, shell]
----
transactional-update
----

. 重引导。

____


[IMPORTANT]
====
{sl-micro} 设计为默认自动更新，并会在应用更新后重引导。但是，这种行为对于 {productname} 环境而言是不利的。为了防止服务器自动更新，{productname} 会在引导过程中禁用 transactional-update 计时器。

如果您希望保留 {sl-micro} 的默认行为，请运行以下命令来启用计时器：

[source, shell]
----
systemctl enable --now transactional-update.timer
----
====
