[[compliance-as-code]]
= Compliance as code

This document provides insight on running compliance as code remediation using an Ansible Playbook.

For more infomation about running compliance as code remediation using a bash script, see xref:openscap.adoc#remediation[Remediation].

//Procedure: Installing the SCAP security guide package
include::snippets/install_scap_security_guide_package.adoc[]


== Run remediation using an Ansible playbook

An Ansible control node is required.
For more information, see xref:ansible-setup-control-node.adoc[].

The following procedure will guide you through running remediation using an Ansible Playbook.

.Procedure: Run remediation using an Ansible playbook
. From the control node system menu select menu:Ansible[Playbooks].
  Expand the folder tab, then select a playbook.

. Click the playbook.

. To run the playbook, select the OS **Inventory Path** for the client, for example:
+
----
/etc/ansible/sles15
----
. Click btn:[Schedule].

. Check the status of the scheduled event under the [guimenu]``Events`` tab.
