[[compliance-as-code]]
= Compliance as code

This document provides insight on running compliance as code remediation's using two distinct methods with {productname}.

.Remediation Methods

* Use an Ansible Playbook
* Use a bash script

== Run remediation's using an Ansible playbook

The following procedure will guide you through running remediation's using an Ansible Playbook.

Requirements:

* Have an available Ansible control node for more information see: xref:setup-ansible-control-node.adoc[].

.Procedure: Run remediation's using an Ansible playbook
. From the control node system menu select menu:Ansible[Playbooks]. Expand the folder tab, then select a playbook.

. Click on the desired playbook.

. To run the playbook, select the correct OS **Inventory Path** for the client and then click **Schedule**.
+
.Example
[example]
----
/etc/ansible/sles15
----
+

. Check the status of the scheduled event under **Events** tab.

== Run remediation's using a bash script

Install the **scap-security-guide** package on all your target systems, as described in: xref:setup-ansible-control-node.adoc[]. Packages, channels and scripts are different for each Operating system and distribution. Examples are listed below in the section <<scripts-for-os-types>>".

=== Run the bash script on single systems as a remote command

Option 1: Run Bash Script as Remote Command (for single systems)

. From menu:System[Overview] tab, select your instance. Then in menu:Details[Remote Commands], write a simple bash script.

. Click on *Schedule*.
+

.Example
[example]
----
#!/bin/bash
chmod +x -R /usr/share/scap-security-guide/bash
/usr/share/scap-security-guide/bash/sle15-script-standard.sh
----
+

[NOTE]
====
Folder and script names change between distribution and version: some examples are listed in the section <<scripts-for-os-types>>.
====


=== Run the bash script using System Set Manager on multiple systems

. Once a system group has been created click **System Groups**, select **Use in SSM** from the table.

. From the **System Set Manager**, under menu:Misc[Remote Command], write a bash script similar to the following:
+

.Example
[example]
----
#!/bin/bash
chmod +x -R /usr/share/scap-security-guide/bash
/usr/share/scap-security-guide/bash/sle15-script-standard.sh
----

. Click on *Schedule*.

[[scripts-for-os-types]]
== Example remediation bash scripts






