[[compliance-as-code]]
= Compliance as Code
:revdate: 2025-06-12
:page-revdate: {revdate}

This document provides insight on running compliance as code remediation using an Ansible Playbook.

For more infomation about running compliance as code remediation using a bash script, see xref:administration:openscap.adoc#remediation[Remediation].

//Procedure: Installing the SCAP security guide package
ifndef::backend-pdf[]
include::administration:partial$install_scap_security_guide_package.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/install_scap_security_guide_package.adoc[]
endif::[]


== Remediation Using an Ansible Playbook


An Ansible control node is required.
For more information, see xref:administration:ansible-setup-control-node.adoc[].

The following procedure will guide you through running remediation using an Ansible playbook.

.Procedure: Run Remediation Using an Ansible Playbook

. From the control node system menu select menu:Ansible[Playbooks], and click a playbook, for example:

+

[source,shell]
----
sle15-playbook-stig.yml
----

. To run the playbook, select the [guimenu]``Inventory Path`` for the clients, for example:

+

[source,shell]
----
/etc/ansible/sles15
----

+

Click btn:[Schedule].

. Check the status of the scheduled event under the [guimenu]``Events`` tab.



In case playbooks are in a different directory, you can follow the link to [guimenu]``Setup Ansible Control Node`` to find out how to add it.
