[[auditing]]
= Auditing

In {productname}, you can keep track of your clients through a series of auditing tasks.
You can check that your clients are up to date with all public security patches (CVEs), perform subscription matching, and use OpenSCAP to check for specification compliance.

In the {productname} {webui}, navigate to [guimenu]``Audit`` to perform auditing tasks.



// This will probably need to be broken into sub-sections. --LKB 20200205


== CVE Audits

A CVE (common vulnerabilities and exposures) is a fix for a publicly known security vulnerability.

[IMPORTANT]
====
You must apply CVEs to your clients as soon as they become available.
====

Each CVE contains an identification number, a description of the vulnerability, and links to further information.
CVE identification numbers use the form ``CVE-YEAR-XXXX``.

In the {productname} {webui}, navigate to menu:Audit[CVE Audit] to see a list of all clients and their current patch status.

By default, the CVE data is updated at 2300 every day.
We recommend that before you begin a CVE audit you refresh the data to ensure you have the latest patches.



.Procedure: Updating CVE Data
. In the {productname} {webui}, navigate to menu:Admin[Task Schedules] and select the ``cve-server-channels-default`` schedule.
. Click btn:[cve-server-channels-bunch].
. Click btn:[Single Run Schedule] to schedule the task.
Allow the task to complete before continuing with the CVE audit.



.Procedure: Verifying Patch Status
. In the {productname} {webui}, navigate to menu:Audit[CVE Audit].
. OPTIONAL: To check the patch status for a particular CVE, type the CVE identifier in the [guimenu]``CVE Number`` field.
. Select the patch statuses you want to look for, or leave all statuses checked to look for all.
. Click btn:[Audit Servers] to check all systems, or click btn:[Audit Images] to check all images.

For more information about the patch status icons used on this page, see xref:reference:audit/audit-cve-audit.adoc[].


For each system, the [guimenu]``Next Action`` column provides information about what you need to do to address vulnerabilities.
If applicable, a list of candidate channels or patches is also given.
You can also assign systems to a [guimenu]``System Set`` for further batch processing.


You can use the {productname} API to verify the patch status of your clients.
Use the `audit.listSystemsByPatchStatus` API method.
For more information about this method, see the {productname} API Guide.






[[cve-tips]]
== CVE Tips

Audit results are only correct if the assignment of channels to systems did not change since the last scheduled refresh (normally at 11:00 PM every night).
If a CVE audit is needed and channels were assigned or unassigned to any system during the day, a manual run is recommended.
For more information, see <<cve-maintenance>>.

Systems are called "`affected`", "`not affected`" or "`patched`" not in an absolute sense, but based on information available to {productname}.
This implies that concepts such as "`being affected by a vulnerability`" have particular meanings in this context.
The following definitions apply:

System affected by a certain vulnerability:::
A system which has an installed package with version lower than the version of the same package in a relevant patch marked for the vulnerability.

System not affected by a certain vulnerability:::
A system which has no installed package that is also in a relevant patch marked for the vulnerability.

System patched for a certain vulnerability:::
A system which has an installed package with version equal to or greater than the version of the same package in a relevant patch marked for the vulnerability.

Relevant patch:::
A patch known by {productname} in a relevant channel.

Relevant channel:::
A channel managed by {productname}, which is either assigned to the system, the original of a cloned channel which is assigned to the system, a channel linked to a product which is installed on the system or a past or future service pack channel for the system.

A notable consequence of the above definitions is that results can be incorrect in cases of unmanaged channels, unmanaged packages, or non-compliant systems.
