[[auth-methods]]
= Authentication With Single Sign-On (SSO)

{productname} supports single sign-on (SSO) by implementing the Security Assertion Markup Language (SAML){nbsp}2 protocol.

Single sign-on is an authentication process that allows a user to access multiple applications with one set of credentials.
SAML is an XML-based standard for exchanging authentication and authorization data.
A SAML identity service provider (IdP) provides authentication and authorization services to service providers (SP), such as {productname}.
{productname} exposes three endpoints which must be enabled for single sign-on.

SSO in {productname} supports:

* Log in with SSO.
* Log out with service provider-initiated single logout (SLO), and Identity service provider single logout service (SLS).
* Assertion and nameId encryption.
* Assertion signatures.
* Message signatures with AuthNRequest, LogoutRequest, and LogoutResponses.
* Enable an Assertion consumer service endpoint.
* Enable a single logout service endpoint.
* Publish the SP metadata (which can be signed).

SSO in {productname} does not support:

* Product choosing and implementation for the identity service provider (IdP).
* SAML support for other products (check with the respective product documentation).



== Prerequisites

Before you begin, you need to have configured an external identity service provider with these parameters.
Check your IdP documentation for instructions.

You will need these endpoints:

* Assertion consumer service (or ACS): an endpoint to accept SAML messages to establish a session into the Service Provider.
The endpoint for ACS in {productname} is: https://example.com/rhn/manager/sso/acs
* Single logout service (or SLS): an endpoint to initiate a logout request from the IdP.
The endpoint for SLS in {productname} is: https://example.com/rhn/manager/sso/sls
* Metadata: an endpoint to retrieve {productname} metadata for SAML.
The endpoint for metadata in {productname} is: https://example.com/rhn/manager/sso/metadata


[IMPORTANT]
====
Your IdP must have a SAML:Attribute containing the username of the IdP user domain, called `uid`.
The `uid` attribute passed in the SAML:Attribute must be created in the {productname} user base before you activate single sign-on.
====

After the authentication with the IdP using the user `orgadmin` is successful, you will be logged in into {productname} as the `orgadmin` user, provided that the `orgadmin` user exists in {productname}.



== Enable SSO

[NOTE]
====
Using SSO is mutually exclusive with other types of authentication: it is either enabled or disabled.
SSO is disabled by default.
====

.Procedure: Enabling SSO

. If your users do not yet exist in {productname}, create them first.
. Edit `/etc/rhn/rhn.conf` and add this line at the end of the file:
+
----
java.sso = true
----
. Find the parameters you want to customize in `/usr/share/rhn/config-defaults/rhn_java_sso.conf`.
Insert the parameters you want to customize into `/etc/rhn/rhn.conf` and prefix them with `java.sso.`.
For example, in `/usr/share/rhn/config-defaults/rhn_java_sso.conf` find:
+
----
onelogin.saml2.sp.assertion_consumer_service.url = https://YOUR-PRODUCT-HOSTNAME-OR-IP/rhn/manager/sso/acs
----
+
To customize it, create the corresponding option in ``/etc/rhn/rhn.conf`` by prefixing the option name with ``java.sso.``:
+
----
java.sso.onelogin.saml2.sp.assertion_consumer_service.url = https://YOUR-PRODUCT-HOSTNAME-OR-IP/rhn/manager/sso/acs
----
+
To find all the occurrences you need to change, search in the file for the placeholders [literal]``YOUR-PRODUCT`` and [literal]``YOUR-IDP-ENTITY``.
Every parameter comes with a brief explanation of what it is meant for.
. Restart the spacewalk service to pick up the changes:
+
----
spacewalk-service restart
----

When you visit the {productname} URL, you will be redirected to the IdP for SSO where you will be requested to authenticate.
Upon successful authentication, you will be redirected to the {productname} {webui}, logged in as the authenticated user.
If you encounter problems with logging in using SSO, check the {productname} logs for more information.



== Example SSO Implementation

In this example, SSO is implemented by exposing three endpoints with {productname}, and using Keycloak as the identity service provider (IdP).

Start by setting up the {productname} Server, and the Keycloak IdP.
Then you can add the endpoints as clients, and create users.


[WARNING]
====
This example is provided for illustrative purposes only.
{suse} does not recommend or support third-party identity service providers, and is not affiliated with Keycloak.
For Keycloak support, see https://www.keycloak.org/.
====



.Procedure: Setting Up the {productname} Server

. On the {productname} Server, open the configuration file at ``/etc/rhn/rhn.conf`` and locate and edit these parameters.
Replace ``FQDN`` with the fully-qualified domain name of your {productname} installation:
+
----
java.sso.onelogin.saml2.sp.entityid = <FQDN>/rhn/manager/sso/metadata
java.sso.onelogin.saml2.sp.assertion_consumer_service.url = <FQDN>/rhn/manager/sso/acs
java.sso.onelogin.saml2.sp.single_logout_service.url = <FQDN>/rhn/manager/sso/sls
----
. In the configuration file, determine the three endpoints to expose:
+
----
java.sso.onelogin.saml2.idp.entityid
java.sso.onelogin.saml2.idp.single_sign_on_service.url
java.sso.onelogin.saml2.idp.single_logout_service.url
----
. In the IdP metadata, locate the public x509 certificate.
It uses this format:
``<IdP_Address>/auth/realms/<Your_Realm>/protocol/saml/descriptor``.
In the configuration file, specify the public x509 certificate of the IdP.:
+
----
java.sso.onelogin.saml2.idp.x509cert
----


When you have prepared the {productname} Server, you can install Keycloak.
You can install Keycloak directly on your machine, or run it in a container.
In this example, we run Keycloak in a Docker container.
For more information about installing Keycloak, see the Keycloak documentation at https://www.keycloak.org/getting-started/getting-started-docker.



.Procedure: Setting Up the Identity Service Provider
. Install KeyCloak in a Docker container, according to the Keycloak documentation.
. Run the container using the ``-td`` argument to ensure the process remains running:
+
----
docker run -td --name=idp -p 8080:8080 -e KEYCLOAK_USER=<user> -e KEYCLOAK_PASSWORD=<password> quay.io/keycloak/keycloak:9.0.2
----
. Log in as a privileged user, and use the Keycloak {webui} to create a realm using these details:
+
* In the ``Name`` field, enter a name for the realm.
For example, ``SUMA``.
* Toggle the ``Enabled`` switch to ``On``.
* In the ``Endpoints`` field, type ``SAML 2.0 Identity Provider Metadata``.
This endpoint is ``<IdP_Address>/auth/realms/<Realm_Name>/protocol/saml/descriptor`` which describes the endpoints and certificate in the {productname} configuration file.
// Probably needs more explanation here. --LKB 20200415



.Procedure: Adding Endpoints as Clients

Clients
A client is a Service Provider, in that case our SUMA Server. So we will need to know the endpoints exposed by our server, to create the client in KeyCloak.

As Client ID we must add our SUMA metadata endpoint (java.sso.onelogin.saml2.sp.entityid)
The protocol used is "saml"
We enable the "Include AuthnStatement" switch
We enable the "Sign Assertions" switch and configure bellow options as our SUMA config file has specified.

￼




Finally, we add the two SUMA endpoints:
Assertion Consumer Service (java.sso.onelogin.saml2.sp.assertion_consumer_service.url)
Logout Service (java.sso.onelogin.saml2.sp.single_logout_service.url)
￼


.Procedure: Configuring Client Scope and Mappers

Configure the Client's scopes and Mappers
Be sure you have assigned the "role_list" as client scope, as we it is the one used when we will create our users mapping the ones from SUSE Manager.

￼



As mapper, we need to add a user attribute mapper, this "uid" SAML Attribute is expected by our SUSE Manager SSO contract.

￼

Users
On that section, we will map the users store in our SUSE Manager Server. Let's create the example users "admin":

In "Details" tab, you can fill in with details that doesn't need to match with SUSE Manager "admin" user:
￼￼


In "Attributes" tab, we must add a "uid" attribute which must match with the username of SUSE Manager:
￼
Finally, In "Credentials" tab, you can set the same password that you are using in SUSE Manager for your user.




To test that your configuration is correct ...


Your setup must be ready now. Be sure you restarted your SUMA Server after add the configuration values and navigate to your SUSE Manager Server FQDN.

You will be redirected to the Login Page of the IdP:
￼

After log in, the IdP will redirect you to SUSE Manager's Home Page, authenticated with "admin" user:
￼

You can now try to log out:
￼

And re-check going to your SUMA Server FQDN, that you are redirected to the Login Page of the IdP.