[[auth-methods]]
= Authentication With Single Sign-On (SSO)

{productname} supports single sign-on (SSO) by implementing the Security Assertion Markup Language (SAML){nbsp}2 protocol.

Single sign-on is an authentication process that allows a user to access multiple applications with one set of credentials.
SAML is an XML-based standard for exchanging authentication and authorization data.
A SAML identity service provider (IdP) provides authentication and authorization services to service providers (SP), such as {productname}.
{productname} exposes three endpoints which must be enabled for single sign-on.

SSO in {productname} supports:

* Log in with SSO.
* Log out with service provider-initiated single logout (SLO), and Identity service provider single logout service (SLS).
* Assertion and nameId encryption.
* Assertion signatures.
* Message signatures with AuthNRequest, LogoutRequest, and LogoutResponses.
* Enable an Assertion consumer service endpoint.
* Enable a single logout service endpoint.
* Publish the SP metadata (which can be signed).

SSO in {productname} does not support:

* Product choosing and implementation for the identity service provider (IdP).
* SAML support for other products (check with the respective product documentation).



== Prerequisites

Before you begin, you need to have configured an external identity service provider with these parameters.
Check your IdP documentation for instructions.

You will need these endpoints:

* Assertion consumer service (or ACS): an endpoint to accept SAML messages to establish a session into the Service Provider.
The endpoint for ACS in {productname} is: https://example.com/rhn/manager/sso/acs
* Single logout service (or SLS): an endpoint to initiate a logout request from the IdP.
The endpoint for SLS in {productname} is: https://example.com/rhn/manager/sso/sls
* Metadata: an endpoint to retrieve {productname} metadata for SAML.
The endpoint for metadata in {productname} is: https://example.com/rhn/manager/sso/metadata


[IMPORTANT]
====
Your IdP must have a SAML:Attribute containing the username of the IdP user domain, called ``uid``.
The ``uid`` attribute passed in the SAML:Attribute must be created in the {productname} user base before you activate single sign-on.
====

After the authentication with the IdP using the user ``orgadmin`` is successful, you will be logged in into {productname} as the ``orgadmin`` user, provided that the ``orgadmin`` user exists in {productname}.



== Enable SSO

[NOTE]
====
Using SSO is mutually exclusive with other types of authentication: it is either enabled or disabled.
SSO is disabled by default.
====

.Procedure: Enabling SSO

. If your users do not yet exist in {productname}, create them first.
. Edit [path]``/etc/rhn/rhn.conf`` and add this line at the end of the file:
+
----
java.sso = true
----
. Find the parameters you want to customize in [path]``/usr/share/rhn/config-defaults/rhn_java_sso.conf``.
Insert the parameters you want to customize into [path]``/etc/rhn/rhn.conf`` and prefix them with [literal]``java.sso``.
For example, in [path]``/usr/share/rhn/config-defaults/rhn_java_sso.conf`` find:
+
----
onelogin.saml2.sp.assertion_consumer_service.url = https://YOUR-PRODUCT-HOSTNAME-OR-IP/rhn/manager/sso/acs
----
+
To customize it, create the corresponding option in [path]``/etc/rhn/rhn.conf`` by prefixing the option name with ``java.sso.``:
+
----
java.sso.onelogin.saml2.sp.assertion_consumer_service.url = https://YOUR-PRODUCT-HOSTNAME-OR-IP/rhn/manager/sso/acs
----
+
To find all the occurrences you need to change, search in the file for the placeholders [literal]``YOUR-PRODUCT`` and [literal]``YOUR-IDP-ENTITY``.
Every parameter comes with a brief explanation of what it is meant for.
. Restart the spacewalk service to pick up the changes:
+
----
spacewalk-service restart
----

When you visit the {productname} URL, you will be redirected to the IdP for SSO where you will be requested to authenticate.
Upon successful authentication, you will be redirected to the {productname} {webui}, logged in as the authenticated user.
If you encounter problems with logging in using SSO, check the {productname} logs for more information.



== Example SSO Implementation

In this example, SSO is implemented by exposing three endpoints with {productname}, and using Keycloak as the identity service provider (IdP).

Start by setting up the {productname} Server, and the Keycloak IdP.
Then you can add the endpoints as clients, and create users.


[WARNING]
====
This example is provided for illustrative purposes only.
{suse} does not recommend or support third-party identity service providers, and is not affiliated with Keycloak.
For Keycloak support, see https://www.keycloak.org/.
====



.Procedure: Setting Up the {productname} Server
. On the {productname} Server, open the [path]``/etc/rhn/rhn.conf`` configuration file and edit these parameters.
Replace ``<FQDN>`` with the fully-qualified domain name of your {productname} installation:
+
----
java.sso.onelogin.saml2.sp.entityid = <FQDN>/rhn/manager/sso/metadata
java.sso.onelogin.saml2.sp.assertion_consumer_service.url = <FQDN>/rhn/manager/sso/acs
java.sso.onelogin.saml2.sp.single_logout_service.url = <FQDN>/rhn/manager/sso/sls
----
. In the configuration file, determine the three endpoints to expose:
+
----
java.sso.onelogin.saml2.idp.entityid
java.sso.onelogin.saml2.idp.single_sign_on_service.url
java.sso.onelogin.saml2.idp.single_logout_service.url
----
. In the IdP metadata, locate the public x509 certificate.
It uses this format:
``<IdP_Address>/auth/realms/<Your_Realm>/protocol/saml/descriptor``.
In the configuration file, specify the public x509 certificate of the IdP:
+
----
java.sso.onelogin.saml2.idp.x509cert
----


When you have prepared the {productname} Server, you can install Keycloak.
You can install Keycloak directly on your machine, or run it in a container.
In this example, we run Keycloak in a Docker container.
For more information about installing Keycloak, see the Keycloak documentation at https://www.keycloak.org/getting-started/getting-started-docker.



.Procedure: Setting Up the Identity Service Provider
. Install Keycloak in a Docker container, according to the Keycloak documentation.
. Run the container using the ``-td`` argument to ensure the process remains running:
+
----
docker run -td --name=idp -p 8080:8080 -e KEYCLOAK_USER=<user> -e KEYCLOAK_PASSWORD=<password> quay.io/keycloak/keycloak:9.0.2
----
. Sign in the Keycloak {webui} as a privileged user, and create a realm using these details:
+
* In the ``Name`` field, enter a name for the realm.
For example, ``SUMA``.
* Toggle the ``Enabled`` switch to ``On``.
* In the ``Endpoints`` field, type ``SAML 2.0 Identity Provider Metadata``.
This endpoint is ``<IdP_Address>/auth/realms/<Realm_Name>/protocol/saml/descriptor`` which describes the endpoints and certificate in the {productname} configuration file.
// Probably needs more explanation here. --LKB 20200415



When you have Keycloak running and set up, you can add the endpoints.
Keycloak refers to endpoints as clients.



.Procedure: Adding Endpoints as Clients
. In the Keycloak {webui}, create a new client using these details:
+
* In the ``Client ID`` field, enter the endpoint specified in the server configuration file as ``java.sso.onelogin.saml2.idp.entityid``.
For example, ``https://<FQDN>/rhn/manager/sso/metadata``.
* In the ``Client Protocol`` field, select ``SAML``.
* Toggle the ``Include AuthnStatement`` switch to ``On``.
* Toggle the ``Sign Assertions`` switch to ``On``.
* In the ``Signature Algorithm`` field, select ``RSA_SHA1``.
* In the ``SAML Signature Key Name`` field, select the key.
* In the ``Canonicalization Method`` field, select ``Exclusive``.
. In the ``Fine Grain SAML Endpoint Configuration`` section, add the two endpoints using these details:
+
* In both the ``Assertion Consumer Service`` fields, enter the endpoint specified in the server configuration file as ``java.sso.onelogin.saml2.sp.assertion_consumer_service.url``.
For example, ``https://<FQDN>/rhn/manager/sso/acs``.
* In both the ``Logout Service`` fields, enter the endpoint specified in the server configuration file as ``java.sso.onelogin.saml2.sp.single_logout_service.url``.
For example, ``https://<FQDN>/rhn/manager/sso/sls``.



When you have added the endpoints as clients, you can configure the client scope, and map the users between Keycloak and {productname}.



.Procedure: Configuring Client Scope and Mappers
. In the Keycloak {webui}, navigate to the menu:Clients[Client Scopes] tab and assign ``role_list`` as the default client scope.
. Navigate to the menu:Clients[Mappers] tab and add a user attribute ``Uid`` mapper, using the default values.
This SAML attribute is expected by {productname}.
. Navigate to the menu:Users[Admin] section and create an administrative user.
This user does not need to match the {productname} administrative user.
. Navigate to the menu:Users[Role Mappings] tab, add a ``uid`` attribute with a value that matches the username of the {productname} administrative user.
. Navigate to the menu:Users[Credentials] tab, and set the same password as used by the {productname} administrative user.
. Save your changes.



When you have completed configuration, you can test that the installation is working as expected.
Restart the {productname} Server to pick up your changes, and navigate to the {productname} {webui}.
If your installation is working correctly, you are redirected to the Keycloak SSO page, where you can authenticate successfully.
