[[backup-restore]]
= Backup and Restore
:revdate: 2025-08-11
:page-revdate: {revdate}

This chapter contains information on the files you need to back up.
With the built-in backup and restore solution ([command]``mgradm backup``) you create {productname} backups.
Information about restoring from your backups in the case of a system failure completes this chapter.

Because {productname} relies on a database as well as the installed program and configurations, it is important to back up all components of your installation.

Back up your {productname} installation regularly to prevent data loss and enable quick recovery.

[IMPORTANT]
====
Regardless of the backup method you use, you must have available at least three times the amount of space your current installation uses.
Running out of space can result in backups failing, so check this often.
====



[[backup-restore-old]]
== Disable old method with smdba

Skip this section if you installed {productname} {productnumber} from scratch.

[NOTE]
====
With the advent of the built-in solution, the old method with the [command]``smdba`` backup tool is deprecated.
If you migrated from an old system with [command]``smdba`` to the new solution, you must disable the old funtionality and remove the old backup archives.
====

Either disable [command]``smdba`` before migrating (recommended) or later on the migrated {productname} {productnumber} system.


.Procedure: Disabling old method with installed smdba before migration
[role=procedure]
____
This procedure only works when smdba is still installed.

ifeval::[{mlm-content} == true]
. Commands are different on SUSE Manager 4.3 (non-containerized installation) or SUSE Manager 5.0 (containerized installation)
present (so 5.0 or on 4.3 before migration):

+

--

SUSE Manager 4.3::
On the command line, as root, execute:

+

[source,shell]
----
smdba backup-hot --enable=off
----

SUSE Manager 5.0::
On the command line of the container host, as root, execute:

+

[source,shell]
----
mgrctl exec -- smdba backup-hot --enable=off
----
--

endif::[]


ifeval::[{uyuni-content} == true]
. On the command line of the container host, as root, execute:

+

[source,shell]
----
mgrctl exec -- smdba backup-hot --enable=off
----

endif::[]
+

--
This will change [option]``archive_command`` in [path]``/var/lib/pgsql/data/postgresql.conf`` as follows:

----
archive_command = '/bin/true'
----

--

____


Now your old system is ready to be migrated to {productname} {productnumber}.


.Procedure: Disabling old method on {productname} {productnumber} after migration
[role=procedure]
____

Use this procedure after migration, when smdba is no longer available.

. On the container host, as root, edit [path]``/var/lib/containers/storage/volumes/var-pgsql/_data/postgresql.conf`` and set these options:

+

----
archive_mode = off
archive_command = '/bin/true'
----

. Restart the container:

+

[source,shell]
----
mgradm restart
----

____


[[backup-product]]
== Back up {productname}

The most comprehensive method for backing up your {productname} installation is to use [command]``mgradm backup create`` command.
This can save you time in administering your backup, and can be faster to reinstall and re-synchronize in the case of failure.
However, this method requires significant disk space and could take a long time to perform the backup.

[command]``mgradm backup create`` command performs backup to a directory.
This directory can be both local or mounted remote storage.

[command]``mgradm backup create`` command allows various customizations of the content of the backup.
For all available options, see [command]``mgradm backup create --help``.


=== Full Backup of {productname}

A full backup of the {productname} consists of backing up the following components:

- {productname} volumes
- database volumes
- podman network configuration
- podman secrets
- {productname} systemd services
- {productname} container images

[WARNING]
====
The {productname} service is automatically stopped during creation of a full backup.
====

.Procedure: Creating Full Backup with [command]``mgradm backup create``
[role=procedure]
____

. On the container host, as root, create backup with:

+

[source,shell]
----
mgradm backup create $path
----

+

Replace [literal]``$path`` by the path to the backup location.

____


=== Partial Backup of {productname}

[command]``mgradm backup create`` tool allows creating partial backups.
It is possible to skip individual or all volumes, skip database backup and images.

Particularly when database backup is skipped, backup is created without stopping {productname} services and can act as a one phase in two phase backup procedure.

[WARNING]
====
Partial backup cannot guarantee backup/restore consistency.
====

.Procedure: Creating partial backup by skipping database backup
[role=procedure]
____

. On the container host, as root, create backup with:

+

[source, shell]
----
mgradm backup create --skipdatabase $path
----

Replace [literal]``$path`` by the path to the backup location.

____

.Procedure: Creating partial backup by skipping a volume
[role=procedure]
____

. On the container host, as root, create backup with:

+
[source, shell]
----
mgradm backup create --skipvolumes $volumes $path
----
Replace [literal]``$path`` by the path to the backup location.

+

Replace [literal]``$volumes`` by the name of the volume name to be excluded from the backup, or by a comma separated list of volumes to be excluded.

+
Use [literal]``all`` to skip all volumes, except database volumes.

____


=== Backing up extra volumes

[command]``mgradm backup`` command uses internal list of {productname} volumes.
If additional volumes were configured during the installation, or additional volumes should be added to the backup, they need to be specified using [command]``--extravolumes $volumes``.

.Procedure: Creating backup with additional custom volume
[role=procedure]
____

. On the container host, as root, create backup with:

+
[source, shell]
----
mgradm backup create --extravolumes $volume $path
----

+

Replace [literal]``$path`` by the path to the backup location.

+

Replace [literal]``$volumes`` by the name of the volume name to be included in the backup. or by a comma separated list of volumes to be included.

____


=== Perform a manual database backup

.Procedure: Performing a manual database backup
[role=procedure]
____

. Allocate permanent storage space for your backup.

. At the command prompt of the {productname} container host, as root, use:

+
[source,shell]
----
mgradm backup create --skipvolumes all --skipconfig --skipimages $path
----
____


[[restore-product]]
== Restore {productname} from the existing backup

Restoring {productname} from the existing backup will enumerate backup for volumes, images and configuration to restore. Unlike in backup create scenario, restore operation is not using an internal volume list, but automatically detect every volume or image present in the backup.

After the list of items to restore is gathered, presence and integrity check is performed. Presence check ensures backup restore will not accidentally overwrite existing volumes, image or configurations. Integrity check is done by computing backup items checksums.

After both checks are successful, actual backup restore is performed.

[IMPORTANT]
====
{productname} services are not automatically started after backup restore is finished.
====

.Procedure: Restoring from an existing backup
[role=procedure]
____

. On the container host, as root, re-deploy the {productname} Server with:

+
[source,shell]
----
mgradm backup restore $path
mgradm start
----

+

Replace [literal]``$path`` by the path to the backup location.

____

Verification of the backup can be a time-consuming operation. 
If backup integrity is ensured by other means, verification can be skipped by using [command]``--skipverify`` option.

If for some reason it is needed to skip restoring a volume present in the backup, [command]``--skipvolumes $volumes`` option can be used.


=== Recommended steps after restoring a backup

.Procedure: Recommended steps after {productname} restore
[role=procedure]
____

. Re-synchronize your {productname} repositories using either the {productname} {webui}, or with the [command]``mgr-sync`` tool at the command prompt in the container.
  You can choose to re-register your product, or skip the registration and SSL certificate generation sections.

. On the container host, check whether you need to restore [path]``/var/lib/containers/storage/volumes/var-spacewalk/_data/packages/``.
  If [path]``/var/lib/containers/storage/volumes/var-spacewalk/_data/packages/`` was not in your backup, you need to restore it.
  If the source repository is available, you can restore [path]``/var/lib/containers/storage/volumes/var-spacewalk/_data/packages/`` with a complete channel synchronization:

+
[source,shell]
----
mgrctl exec -ti -- mgr-sync refresh --refresh-channels
----

. Schedule the re-creation of search indexes next time the [command]``rhn-search`` service is started.
This command produces only debug messages, it does not produce error messages.
On the container host, enter:

+
[source,shell]
----
mgrctl exec -ti -- rhn-search cleanindex
----
____

