[[backup-restore]]
= Backup and Restore

Back up your {productname} installation regularly, to prevent data loss.
Because {productname} relies on a database as well as the installed program and configurations, it is important to back up all components of your installation.
This chapter contains information on the files you need to back up, and introduces the [command]``smdba`` tool to manage database backups.
It also contains information about restoring from your backups in the case of a system failure.


[IMPORTANT]
====
Regardless of the backup method you use, you must have available at least three times the amount of space your current installation uses.
Running out of space can result in backups failing, so check this often.
====



[[backup-restore-product]]
== Back up {productname}

The most comprehensive method for backing up your {productname} installation is to back up the relevant files and directories.
This can save you time in administering your backup, and can be faster to reinstall and re-synchronize in the case of failure.
However, this method requires significant disk space and could take a long time to perform the backup.

[NOTE]
====
If you want to back up only the required files and directories, use the following list.
To make this process simpler, and more comprehensive, we recommend backing up the entire [path]``/etc`` and [path]``/root`` directories, not just the ones specified here.
Some files only exist if you are actually using the related {susemgr} feature.
====


* [path]``/etc/cobbler/``
* [path]``/etc/dhcp.conf``
* [path]``/etc/fstab`` and any ISO mount points you require.
+
If your UUID has changed, ensure you have updated the ``fstab`` entries  accordingly.
* [path]``/etc/rhn/``
* [path]``/etc/salt``
* [path]``/etc/sudoers``
* [path]``/etc/sysconfig/rhn/``
* [path]``/root/.gnupg/``
* [path]``/root/.ssh``
+
This file exists if you are using an SSH tunnel or SSH [command]``push``.
You also need to have saved a copy of the ``id-susemanager`` key.
* [path]``/root/ssl-build/``
* [path]``/srv/formula_metadata``
* [path]``/srv/pillar``
* [path]``/srv/salt``
* [path]``/srv/susemanager``
* [path]``/srv/tftpboot/``
* [path]``/srv/www/cobbler``
* [path]``/srv/www/htdocs/pub/``
* [path]``/srv/www/os-images``
* [path]``/var/cache/rhn``
* [path]``/var/cache/salt``
* [path]``/var/lib/cobbler/``
* [path]``/var/lib/cobbler/templates/`` (before version 4.0 it is [path]``/var/lib/rhn/kickstarts/``)
* [path]``/var/lib/Kiwi``
* [path]``/var/lib/rhn/``
* [path]``/var/run/pgsql/``
* [path]``/var/lib/salt/``
* [path]``/var/run/salt/``
* [path]``/var/spacewalk/``
* Any directories containing custom data such as scripts, Kickstart or AutoYaST profiles, and custom RPMs.

[IMPORTANT]
====
You also need to back up your database, which you can do with the [command]``smdba`` tool.
====



.Procedure: Restoring from a Manual Backup
. Re-deploy the {productname} Server with ``mgradm install podman``.

. Re-synchronize your {productname} repositories using either the {productname} {webui}, or with the [command]``mgr-sync`` tool at the command prompt.
  You can choose to re-register your product, or skip the registration and SSL certificate generation sections.
. Re-install the [path]``/var/lib/containers/storage/volumes/root/ssl-build/rhn-org-httpd-ssl-key-pair-MACHINE_NAME-VER-REL.noarch.rpm`` package.
. Schedule the re-creation of search indexes next time the [command]``rhn-search`` service is started.
  This command produces only debug messages, it does not produce error messages:
+

----
rhn-search cleanindex
----

. Check whether you need to restore [path]``/var/lib/containers/storage/volumes/var-spacewalk/_data/packages/``.
  If [path]``/var/lib/containers/storage/volumes/var-spacewalk/_data/packages/`` was not in your backup, you need to restore it.
  If the source repository is available, you can restore [path]``/var/lib/containers/storage/volumes/var-spacewalk/_data/packages/` with a complete channel synchronization:
+

----
mgr-sync refresh --refresh-channels
----



[[backup.smdba.admin]]
== Administering the Database with smdba

The [command]``smdba`` tool is used for managing a local PostgreSQL database.
It allows you to back up and restore your database, and manage backups.
It can also be used to check the status of your database, and perform administration tasks, such as restarting.
For more information about the [command]``smdba``  tool, see xref:reference:cli-smdba[].


The [command]``smdba`` tool works with local PostgreSQL databases only, it does not work with remotely accessed databases, or Oracle databases.

[IMPORTANT]
====
The [command]``smdba`` tool requires [command]``sudo`` access, to execute system changes.
Ensure you have enabled [command]``sudo`` access for the [username]``admin`` user before you begin, by checking the [path]``/etc/sudoers`` file for this line:

----
admin   ALL=(postgres) /usr/bin/smdba
----

====

Check the runtime status of your database with:

----
smdba db-status
----

This command returns either ``online`` or ``offline``, for example:

----
Checking database core...       online
----

Starting and stopping the database can be performed with:

----
smdba db-start
----

And:

----
smdba db-stop
----



[[backup.smdba.backup]]
== Database Backup with smdba

The [command]``smdba`` tool performs a continuous archiving backup.
This backup method combines a log of every change made to the database during the current session, with a series of more traditional backup files.
When a crash occurs, the database state is first restored from the most recent backup file on disk, then the log of the current session is replayed exactly, to bring the database back to a current state.
A continuous archiving backup with [command]``smdba`` is performed with the database running, so there is no need for downtime.

This method of backing up is stable and generally creates consistent snapshots, however it can take up a lot of storage space.
Ensure you have at least three times the current database size of space available for backups.
You can check your current database size by navigating to [path]``/var/lib/pgsql/`` and running [command]``df -h``.

The [command]``smdba`` tool also manages your archives, keeping only the most recent backup, and the current archive of logs.
The log files can only be a maximum file size of 16{nbsp}MB, so a new log file is created when the files reach this size.
Every time you create a new backup, previous backups are purged to release disk space.
We recommend you use [command]``cron`` to schedule your [command]``smdba`` backups to ensure that your storage is managed effectively, and you always have a backup ready in case of failure.



=== Perform a Manual Database Backup

The [command]``smdba`` tool can be run directly from the command line.
We recommend you run a manual database backup immediately after installation, or if you have made any significant changes to your configuration.

[NOTE]
====
When [command]``smdba`` is run for the first time, or if you have changed the location of the backup, it needs to restart your database before performing the archive.
This results in a small amount of downtime.
Regular database backups do not require any downtime.
====

.Procedure: Performing a Manual Database Backup
. Allocate permanent storage space for your backup.
  This example uses a directory located at [path]``/var/spacewalk/``.
  This becomes a permanent target for your backup, so ensure it remains accessible by your server at all times.
. In your backup location, create a directory for the backup:
+
As root:
+
----
install -d -o postgres -g postgres -m 700 /var/spacewalk/db-backup
----
. Ensure you have the correct permissions set on the backup location:
+
----
chown postgres:postgres /var/spacewalk/db-backup
----
+
. To create a backup for the first time, run the [command]``smdba backup-hot`` command with the [option]``enable`` option set.
  This creates the backup in the specified directory, and, if necessary, restart the database:
+
----
smdba backup-hot --enable=on --backup-dir=/var/spacewalk/db-backup
----
+
This command produces debug messages and finishes sucessfully with the output:
+
----
INFO: Finished
----
+
. Check that the backup files exist in the [path]``/var/spacewalk/db-backup`` directory, to ensure that your backup has been successful.



[[smdba.automatic.backup.with.cron]]
=== Scheduling Automatic Backups

You do not need to shut down your system to perform a database backup with [command]``smdba``.
However, because it is a large operation, database performance can slow down while the backup is running.
We recommend you schedule regular database backups for a low-traffic period, to minimize disruption.

[IMPORTANT]
====
Ensure you have at least three times the current database size of space available for backups.
You can check your current database size by navigating to [path]``/var/lib/pgsql/`` and running [command]``df -h``.
====

.Procedure: Scheduling Automatic Backups
. Create a directory for the backup, and set the appropriate permissions (as root):
+
----
install -d -m 700 -o postgres -g postgres /var/spacewalk/db-backup
----
. Open [path]``/etc/cron.d/db-backup-mgr``, or create it if it does not exist, and add the following line to create the cron job:
+
----
0 2 * * * root /usr/bin/smdba backup-hot --enable=on --backup-dir=/var/spacewalk/db-backup
----
. Check the backup directory regularly to ensure the backups are working as expected.



[[backup.smdba.restore]]
== Restore from Backup

The [command]``smdba`` tool can be used to restore from backup in the case of failure.



.Procedure: Restoring from Backup
. Shut down the database:
+
----
smdba db-stop
----
. Start the restore process and wait for it to complete:
+
----
smdba backup-restore start
----
. Restart the database:
+
----
smdba db-start
----
. Check if there are differences between the RPMs and the database.
+
----
spacewalk-data-fsck
----



[[config-smdb.archivelog]]
== Archive Log Settings

Archive logging allows the database management tool [command]``smdba`` to perform hot backups.
In {productname} with an embedded database, archive logging is enabled by default.

PostgreSQL maintains a limited number of archive logs.
Using the default configuration, approximately 64 files with a size of 16 MiB are stored.

// FIXME: Use sle 15 channels as an example
Creating a user and syncing the channels:

* SLES12-SP2-Pool-x86_64
* SLES12-SP2-Updates-x86_64
* SLE-Manager-Tools12-Pool-x86_64-SP2
* SLE-Manager-Tools12-Updates-x86_64-SP2

PostgreSQL generates an additional roughly 1 GB of data.
So it is important to think about a backup strategy and create a backups in a regular way.

Archive logs are stored at [path]``/var/lib/pgsql/data/pg_xlog/`` (postgresql).



[[config-smdb.spaces]]
== Retrieve an Overview of Occupied Database Space

Database administrators may use the subcommand [command]``space-overview`` to get a report about occupied table spaces, for example:

----
smdba space-overview
----

outputs:

----
SUSE Manager Database Control. Version 1.5.2
Copyright (c) 2012 by SUSE Linux Products GmbH

Tablespace  | Size (Mb) | Avail (Mb) | Use %
------------+-----------+------------+------
postgres    | 7         | 49168      | 0.013
susemanager | 776       | 48399      | 1.602
----

The [command]``smdba`` command is available for PostgreSQL.
For a more detailed report, use the [command]``space-tables`` subcommand.
It lists the table and its size, for example:

----
smdba space-tables
----

outputs:

----
SUSE Manager Database Control. Version 1.5.2
Copyright (c) 2012 by SUSE Linux Products GmbH

Table                                 | Size
--------------------------------------+-----------
public.all_primary_keys               | 0 bytes
public.all_tab_columns                | 0 bytes
public.allserverkeywordsincereboot    | 0 bytes
public.dblink_pkey_results            | 0 bytes
public.dual                           | 8192 bytes
public.evr_t                          | 0 bytes
public.log                            | 32 kB
...
----



== Move the Database

It is possible to move the database to another location.
For example, if database storage space is running low.



.Procedure: Moving the Database
. The default storage location for {productname} is [path]``/var/lib/pgsql/``. If you would like to move it, for example to [path]``/storage/postgres/``, proceed as follows.

. At the command prompt, as root, stop the running database:
+
----
rcpostgresql stop
----
+
Shut down the running spacewalk services:
+
----
spacewalk-service stop
----
. Copy the current working directory structure with [command]``cp`` using the [option]``-a, --archive`` option.
    For example:
+
----
cp --archive /var/lib/pgsql/ /storage/postgres/
----
+
This command copies the contents of [path]``/var/lib/pgsql/``
to [path]``/storage/postgres/pgsql/``.
+
IMPORTANT: The contents of the [path]``/var/lib/pgsql`` directory needs to remain the same, otherwise the {productname} database may malfunction.
You also should ensure that there is enough available disk space.
+
. Mount the new database directory:
+
----
mount /storage/postgres/pgsql
----
. Make sure ownership is `postgres:postgres` and not `root:root` by changing to the new directory and running these commands:
+
----
cd /storage/postgres/pgsql/
ls -l
----
+
Outputs:
+
----
total 8
drwxr-x---  4 postgres postgres   47 Jun  2 14:35 ./
----
. Add the new database mount location to your servers fstab by editing  [path]``etc/fstab``.
. Start the database with:
+
----
rcpostgresql start
----
. Start the spacewalk services:
+
----
spacewalk-service start
----


[[config-smdb.recover-root]]
== Recover From a Crashed Root Partition

If your root partition has crashed, you can restart the {productname} Server with some additional steps.
This section assumes you have setup your server using separate partitions for the database and for channels, mounted at [path]``/var/lib/pgsql`` and [path]``/var/spacewalk/``.



[IMPORTANT]
====
After a new installation of a system most users and groups get different IDs.
Most backup systems store the names instead of the IDs and will restore the files with the correct ownership and permissions.
But if you mount existing partitions, you must align the ownership to the new system.
====

.Procedure: Recovering from a Crashed Root Partition
. Install {productname}.
  Do not mount the [path]``/var/spacewalk`` and [path]``/var/lib/pgsql`` partitions.
  Wait for the installation to complete before going on to the next step.

. Shut down the database:
+

----
rcpostgresql stop
----

. Shut down the services:
+

----
spacewalk-service stop
----

. Mount [path]``/var/spacewalk`` and [path]``/var/lib/pgsql`` partitions.

. Restore the directories listed in <<backup-restore-product>>.

. Start the database:
+

----
rcpostgresql start
----

. Start the spacewalk services:
+

----
spacewalk-service start
----


{productname} should now operate normally without loss of your database or synchronized channels.



== Database Connection Information

You can set information for connecting to the {productname} database by adding or editing these variable in [path]``/etc/rhn/rhn.conf``:

----
db_backend = postgresql
db_user = susemanager
db_password = susemanager
db_name = susemanager
db_host = localhost
db_port = 5432
db_ssl_enabled =
----
