[[content-lifecycle-examples]]
= Content Lifecycle Management Examples

This section contains some common examples of how you can use content lifecycle management.
Use these examples to build your own personalized implementation.



[#create-proj-for-patch-cycle]
== Creating a Project for a Monthly Patch Cycle

An example project for a monthly patch cycle consists of:

* Creating a `By Date` filter
* Adding the filter to the project
* Applying the filter to a new project build
* Excluding a patch from the project
* Including a patch in the project



[#create-a-filter]
=== Creating a `By Date` filter

The ``By Date`` filter excludes all patches released after a specified date.
This filter is useful for your content lifecycle projects that follow a monthly patch cycle.


.Procedure: Creating the ``By Date`` Filter
. In the {productname} {webui}, navigate to menu:Content Lifecycle[Filters] and click btn:[Create Filter].
. In the [guimenu]``Filter Name`` field, type a name for your filter.
    For example, [systemitem]``Exclude patches by date``.
. In the [guimenu]``Filter Type`` field, select [guimenu]``Patch (Issue date)``.
. In the [guimenu]``Matcher`` field, [guimenu]``later or equal`` is autoselected.
. Select the date and time.
. Click btn:[Save].



[#add-filter-to-proj]
=== Adding the Filter to the Project

.Procedure: Adding a Filter to a Project
. In the {productname} {webui}, navigate to menu:Content Lifecycle[Projects] and select a project from the list.
. Click btn:[Attach/Detach Filters] link to see all available filters
. Select the new [guimenu]``Exclude patches by date`` filter.
. Click btn:[Save].



[#apply-filter-to-project-build]
=== Applying the Filter to a New Project Build

The new filter is added to your filter list, but it still needs to be applied to the project.
To apply the filter you need to build the first environment.

.Procedure: Using the Filter
. Click btn:[Build] to build the first environment.
. OPTIONAL: Add a message.
    You can use messages to help track the build history.
. Check that the filter has worked correctly by using the new channels on a test server.
. Click btn:[Promote] to move the content to the next environment.
    The build takes longer if you have a large number of filters, or they are very complex.



[#exclude-a-patch]
=== Excluding a Patch from the Project

Tests may help you discover issues.
When an issue is found, exclude the problem patch released before the `by date` filter.

.Procedure: Excluding a Patch

. In the {productname} {webui}, navigate to menu:Content Lifecycle[Filters] and click btn:[Create Filter].
. In the [guimenu]``Filter Name`` field, enter a name for the filter.
    For example, [systemitem]``Exclude openjdk patch``.
. In the [guimenu]``Filter Type`` field, select [guimenu]``Patch (Advisory Name)``.
. In the [guimenu]``Matcher`` field, select [guimenu]``equals``.
. In the [guimenu]``Advisory Name`` field, type a name for the advisory.
    For example, [systemitem]``SUSE-15-2019-1807``.
. Click btn:[Save].
. Navigate to menu:Content Lifecycle[Projects] and select your project.
. Click btn:[Attach/Detach Filters] link, select [guimenu]``Exclude openjdk patch``, and click btn:[Save].

When you rebuild the project with the btn:[Build] button, the new filter is used together with the [guimenu]``by date`` filter we added before.



[#include-a-patch]
=== Including a Patch in the Project

In this example, you have received a security alert.
An important security patch was released several days after the first of the month you are currently working on.
The name of the new patch is ``SUSE-15-2019-2071``.
You need to include this new patch into your environment.

[IMPORTANT]
====
The [guimenu]``Allow`` filters rule overrides the exclude function of the [guimenu]``Deny`` filter rule.
For more information, see xref:administration:content-lifecycle.adoc[].
====

.Procedure: Including a Patch in a Project
. In the {productname} {webui}, navigate to menu:Content Lifecycle[Filters] and click btn:[Create Filter].
. In the [guimenu]``Filter Name`` field, type a name for the filter.
    For example, [systemitem]``Include kernel security fix``.
. In the [guimenu]``Filter Type`` field, select [guimenu]``Patch (Advisory Name)``.
. In the [guimenu]``Matcher`` field, select [guimenu]``equals``.
. In the [guimenu]``Advisory Name`` field, type [guimenu]``SUSE-15-2019-2071``, and check [guimenu]``Allow``.
. Click btn:[Save] to store the filter.
. Navigate to menu:Content Lifecycle[Projects] and select your project from the list.
. Click btn:[Attach/Detach Filters], and select [guimenu]``Include kernel security patch``.
. Click btn:[Save].
. Click btn:[Build] to rebuild the environment.



[#update-a-patch-cycle]
== Update an Existing Monthly Patch Cycle

When a monthly patch cycle is complete, you can update the patch cycle for the next month.

.Procedure: Updating a Monthly Patch Cycle
. In the [guimenu]``by date`` field, change the date of the filter to the next month.
    Alternatively, create a new filter and change the assignment to the project.
. Check if the exclude filter for ``SUSE-15-2019-1807`` can be detached from the project.
    There may be a new patch available to fix this issue.
. Detach the ``allow`` filter you added previously.
    The patch is included by default.
. Rebuild the project to create a new environment with patches for the next month.



[#enhance-project-with-livepatching]
== Enhance a Project with Live Patching

This section covers setting up filters to create environments for live patching.

[IMPORTANT]
====
When you are preparing to use live patching, there are some important considerations

* Only ever use one kernel version on your systems.
    The live patching packages are installed with a specific kernel.
* Live patching updates are shipped as one patch.
* Each kernel patch that begins a new series of live patching kernels displays the ``required reboot`` flag.
    These kernel patches come with live patching tools.
    When you have installed them, you need to reboot the system at least once before the next year.
* Only install live patch updates that match the installed kernel version.
* Live patches are provided as stand-alone patches.
    You must exclude all regular kernel patches with higher kernel version than the currently installed one.
====



[#exclude-higher-kernel-version]
=== Exclude Packages with a Higher Kernel Version

In this example you update your systems with the ``SUSE-15-2019-1244`` patch.
This patch contains ``kernel-default-4.12.14-150.17.1-x86_64``.

You need to exclude all patches which contain a higher version of [package]``kernel-default`` and [package]``kernel-default-base``.

.Procedure: Excluding Packages with a Higher Kernel Version
. In the {productname} {webui}, navigate to menu:Content Lifecycle[Filters], and click btn:[Create Filter].
. In the [guimenu]``Filter Name`` field, type a name for your filter.
    For example, [systemitem]``Exclude kernel greater than 4.12.14-150.17.1``.
. In the [guimenu]``Filter Type`` field, select [guimenu]``Patch (Contains Package)``.
. In the [guimenu]``Matcher`` field, select [guimenu]``version greater than``.
. In the [guimenu]``Package Name`` field, type [systemitem]``kernel-default``.
. Leave the the [guimenu]``Epoch`` field empty.
. In the [guimenu]``Version`` field, type [systemitem]``4.12.14``.
. In the [guimenu]``Release`` field, type [systemitem]``150.17.1``.
. Click btn:[Save] to store the filter.
. Navigate to menu:Content Lifecycle[Projects] and select your project.
. Click btn:[Attach/Detach Filters].
. Select [guimenu]``Exclude kernel greater than 4.12.14-150.17.1``, and click btn:[Save].

You need to repeat this procedure for the [package]``kernel-default-base`` package.


When you click btn:[Build], a new environment is created.
The new environment contains all the kernel patches up to the version you installed.

[NOTE]
====
All kernel patches with higher kernel versions are removed.
Live patching kernels remain available as long as they are not the first in a series.
====

This procedure can be automated using a filter template.
For more information on how to apply a live patching filter template, see xref:administration:content-lifecycle.adoc#filter-templates[].



[#switch-kernel-version-for-live-patching]
== Switch to a New Kernel Version for Live Patching

Live Patching for a specific kernel version is only available for one year.
After one year you must update the kernel on your systems.
Execute these environment changes:

.Procedure: Switch to a New Kernel Version
. Decide which kernel version to upgrade to.
    For example: `4.12.14-150.32.1`
. Create a new kernel version Filter.
. Detach the previous filter **Exclude kernel greater than 4.12.14-150.17.1** and attach the new filter.

Click btn:[Build] to rebuild the environment.
The new environment contains all kernel patches up to the new kernel version you selected.
Systems using these channels have the kernel update available for installation.
You need to reboot systems after they have performed the upgrade.
The new kernel remains valid for one year.
All packages installed during the year match the current live patching kernel filter.



[#appstream-filters]
== AppStream Filters

In a content lifecycle management project, you can use the AppStream filter to transform modular repositories into regular repositories.
It does this by keeping the packages in the repository and stripping away the module metadata.
The resulting repository can be used in {productname} in the same way as a regular repository.

[NOTE]
====

ifeval::[{uyuni-content} == true]
AppStream repositories are natively supported throughout the {webui}.
endif::[]

ifeval::[{suma-content} == true]
Since {productname} 5.0, AppStream repositories are natively supported throughout the {webui}.
endif::[]

Therefore, this process is not mandatory to work with AppStream repositories.
====

The AppStream filter selects a single module stream to be included in the target repository.
You can add multiple filters to select multiple module streams.

If you do not use an AppStream filter in your CLM project, the module metadata in the modular sources remains intact, and the target repositories contain the same module metadata.
As long as at least one AppStream filter is enabled in the CLM project, all target repositories are transformed into regular repositories.

In some cases, you might wish to build regular repositories without having to include packages from any module.
To do so, add an AppStream filter using the matcher [parameter]``none (disable modularity)``.
This will disable all the modules in the target repository.
This is especially useful for {rhel}{nbsp}9 clients, where the default versions of most modules are already included in the AppStream repository as regular packages.

To use the AppStream filter, you need a CLM project with a modular repository such as ``{rhel} AppStreams``.
Ensure that you included the module you need as a source before you begin.



.Procedure: Using AppStream Filters
. In the {productname} {webui}, navigate to your {rhel}{nbsp}8 or 9 CLM project.
    Ensure that you have included the AppStream channels for your project.
. Click btn:[Create Filter] and use these parameters:
+
* In the [guimenu]``Filter Name`` field, type a name for the new filter.
* In the [guimenu]``Filter Type`` field, select [parameter]``Module (Stream)``.
* In the [guimenu]``Matcher`` field, select [parameter]``equals``.
* In the [guimenu]``Module Name`` field, type a module name.
    For example, [parameter]``postgresql``.
* In the [guimenu]``Stream`` field, type the name of the desired stream.
    For example, [parameter]``10``.
    If you leave this field blank, the default stream for the module is selected.
. Click btn:[Save] to create the new filter.
. Navigate to menu:Content Lifecycle[Projects] and select your project.
. Click btn:[Attach/Detach Filters], select your new AppStream filter, and click btn:[Save].


You can use the browse function in the ``Create/Edit Filter`` form to select a module from a list of available module streams for a modular channel.

.Procedure: Browsing Available Module Streams
. In the {productname} {webui}, navigate to your {rhel}{nbsp}8 or 9 CLM project.
    Ensure that you have included the AppStream channels for your project.
. Click btn:[Create Filter] and use these parameters:
+
* In the [guimenu]``Filter Name`` field, type a name for the new filter.
* In the [guimenu]``Filter Type`` field, select [parameter]``Module (Stream)``.
* In the [guimenu]``Matcher`` field, select [parameter]``equals``.
. Click ``Browse available modules`` to see all modular channels.
. Select a channel to browse the modules and streams:
+
* In the [guimenu]``Module Name`` field, start typing a module name to search, or select from the list.
* In the [guimenu]``Stream`` field, start typing a stream name to search, or select from the list.


[NOTE]
====
Channel selection is only for browsing modules.
The selected channel is not be saved with the filter, and does not affect the CLM process in any way.
====

You can create additional AppStream filters for any other module stream to be included in the target repository.
Any module streams that the selected stream depends on is automatically included.

[NOTE]
====
Be careful not to specify conflicting, incompatible, or missing
module streams.
For example, selecting two streams from the same module is
invalid.
====

.Procedure: Disabling Modularity
. In the {productname} {webui}, navigate to your {rhel}{nbsp}8 or 9 CLM project.
    Ensure that you have included the AppStream channels for your project.
. Click btn:[Create Filter] and use these parameters:
+
* In the [guimenu]``Filter Name`` field, type a name for the new filter.
* In the [guimenu]``Filter Type`` field, select [parameter]``Module (Stream)``.
* In the [guimenu]``Matcher`` field, select [parameter]``none (disable modularity)``.
. Click btn:[Save] to create the new filter.
. Navigate to menu:Content Lifecycle[Projects] and select your project.
. Click btn:[Attach/Detach Filters], select your new AppStream filter, and click btn:[Save].

This will effectively remove the module metadata from the target repository, excluding any package that belongs to a module.

When you build your CLM project using the btn:[Build] button in the {webui}, the target repository is a regular repository without any modules, that contains packages from the selected module streams.

[NOTE]
====
Disabling modularity altogether in {rhel}{nbsp}8 projects might result in a faulty environment as some modules are essential for healthy operation in {rhel}{nbsp}8.
====
