[[custom-ssl]]
= Using a Custom SSL Certificate
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]

// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]



The following section will guide you through using a custom certificate with {productname} {productnumber} and {susemgrproxy} {productnumber}.




[[bp.cert.custom.req]]
== Prerequisites


The following list provides requirements for using a custom certificate.

* A Certificate Authority (CA) SSL public certificate file
* A Web server SSL private key file
* A Web server SSL public certificate file
* Key and Certificate files must be in PEM format


.Hostname and SSL Keys
[IMPORTANT]
====
The hostname of the web server's SSL keys and relevant certificate files must match the hostname of the machine which they will be deployed on.
====

.Intermediate Certificates
[TIP]
====
In case you want to use CAs with intermediate certificates, merge the intermediate and root CA certificates into one file.
It is important that the intermediate certificate comes first within the combined file.
====




[[bp.cert.custom.setup]]
== Setup


After completing {yast}
firstboot procedures, export your current environment variables and point them to the correct SSL files to be imported.
Running these commands will make the default certificate obsolete after executing the [command]``yast2 susemanagersetup`` command.
For more information on {yast}
 firstboot, see https://www.suse.com/documentation/suse-manager-3/singlehtml/suse_manager21/book_susemanager_install/book_susemanager_install.html#sec.manager.inst.setup.
[[bp.cert.custom.setup.proc]]


[[bp.cert.custom.setup.proc.export]]
. Export the environment variables and point to the SSL files to be imported:
+

----
export CA_CERT=`path_to_CA_certificate_file`export SERVER_KEY=`path_to_web_server_key`export SERVER_CERT=`path_to_web_server_certificate`
----
. Execute {productname} setup with
+

----
yast2 susemanagersetup
----
+
Proceed with the default setup.
Upon reaching the Certificate Setup window during {yast}
installation, fill in random values, as these will be overridden with the values specified in <<bp.cert.custom.setup.proc.export>>.
+
.Shell Requirements
NOTE: Make sure that you execute [command]``yast2
      susemanagersetup`` from within the same shell the environment variables were exported from.
+



[[bp.cert.custom.proxy]]
== Using a Custom Certificate with {susemgrproxy}


After completing the installation with yast found in <<advanced.topics.proxy.quickstart>> continue with a modified <<at.manager.proxy.run.confproxy>> procedure:

[[bp.cert.custom.proxy.proc]]

. Execute [command]``configure-proxy.sh``.
. When prompted with:
+

----
Do you want to import existing certificates?
----
+
Answer with kbd:[y]
.
. Continue by following the script prompts.
