[[hostname-rename]]
= Rename {productname} Server

It is possible to rename a {productname} Server.
You first must change the network settings of the server locally and remotely.
Then use the [command]``spacewalk-hostname-rename`` script to update the settings in the PostgreSQL database and the internal structures of {productname}.

The [command]``spacewalk-hostname-rename`` script is part of the [package]``spacewalk-utils`` package.

The only mandatory parameter for the script is the newly configured IP address of the {productname} Server.



.Procedure: Renaming {productname} Server
. Change the network settings of the server on the system level locally and remotely at the DNS server.
This part of the procedure is similar to the actions to take if you want to rename any other regular system.
+
[NOTE]
====
You must also provide configuration settings for reverse name resolution.
====
. Restart your network configuration to make the {productname} server use the new hostname.
If the server does not use the new name, the script will not complete.
After rebooting the server will use the new name.
. Run the script [command]``spacewalk-hostname-rename`` script with the public IP address of the server.
. Some other actions are needed to make your landscape aware of the new hostname and IP address.
Change all Salt clients to point to the new master, and with a re-activation key re-register the traditional clients (if there are any).
