[[hostname-rename]]
= Rename Hostname

With the [command]``spacewalk-hostname-rename`` script it is possible to rename the hostname of the {productname} Server.
The [command]``spacewalk-hostname-rename`` script is part of the [package]``spacewalk-utils`` package.

The only mandatory parameter for the script is the newly configured IP address of the {productname} Server.
It is the best to proceed as follows: 

. Adjust the hostname in advance.
It is important to configure it locally, and at the DNS server for DNS resolution.
You must also provide configuration settings for reverse name resolution.
. Restart your network configuration to make the {productname} server use the new hostname.
If the server does not use the new name, the renaming script will complain.
After rebooting the server will use the new name.
. Run the script [command]``spacewalk-hostname-rename`` script with the public IP address of the server.
. Some other actions are needed to make your landscape aware of the new hostname and IP address.
Change all Salt clients to point to the new master, and with a re-activation key re-register the traditional clients (if there are any).

