[[hostname-rename]]
= Rename {productname} Server

It is possible to rename a {productname} Server.
Begin by changing the network settings of the server locally and remotely.
Then use the [command]``spacewalk-hostname-rename`` script to update the settings in the PostgreSQL database and the internal structures of {productname}.

The [command]``spacewalk-hostname-rename`` script is part of the [package]``spacewalk-utils`` package.

The only mandatory parameter for the script is the newly configured IP address of the {productname} Server.



.Procedure: Renaming {productname} Server
. Change the network settings of the server on the system level locally and remotely at the DNS server.
Provide configuration settings for reverse name resolution, too.
Changing network settings is done in the same way as with renaming any other system.
. Restart your network configuration to make the {productname} Server uses the new hostname.
. Reboot the {productname} Server to ensure the hostname has changed.
If the server is not using the new name, the script will fail.
. Run the script [command]``spacewalk-hostname-rename`` script with the public IP address of the server.
. Some other actions are needed to make your environment aware of the new hostname and IP address.
Re-configure your clients.
For background information, see xref:client-configuration:registration-cli.adoc[].
+
In the Salt minion configuration file [path]``/etc/salt/minion``, you must make sure to specify the name of the new Salt master ({productname} Server):
+
----
master: <new_hostname>
----
+
Traditional clients have the [path]``/etc/sysconfig/rhn/up2date`` configuration file that must be changed.
With a re-activation key you can re-register traditional clients (if there are any).
. OPTIONAL: If you use PXE boot through a {productname} Proxy, you must check the configuration settings of the proxy.
On the proxy, run the [command]``configure-tftpsync.sh`` setup script and enter the requested information.
For more information, see xref:installation:proxy-setup.adoc[].
