[[iss]]
= Inter-Server Synchronization - Version 1

ifeval::[{suma-content} == true]

[WARNING]
====
Starting with {productname} 5.0, the Inter-Server Synchronization (Version 1) feature will be deprecated and subsequently removed in future versions.
====

endif::[]


If you have more than one {productname} installation, you need to ensure that they stay aligned on content and permissions.
Inter-Server Synchronization (ISS) allows you to connect two or more {productname} Servers and keep them up-to-date.

To set up ISS version 1, you need to define one {productname} Server as a master, with the other as a slave.
If conflicting configurations exist, the system prioritizes the master configuration.


[NOTE]
====
ISS Masters are masters only because they have slaves attached to them.
This means that you need to set up the ISS Master first, by defining its slaves.
You can then set up the ISS Slaves, by attaching them to a master.
====



.Procedure: Setting up an ISS Master

. In the {productname} {webui}, navigate to menu:Admin[ISS Configuration > Master Setup], and click btn:[Add new slave].
. In the [guimenu]``Edit Slave Details`` dialog, provide these details for the ISS Master's first slave:
* In the [guimenu]``Slave Fully Qualified Domain Name`` field, enter the FQDN of the ISS Slave.
    For example: [systemitem]``server2.example.com``.
* Check the [guimenu]``Allow Slave to Sync?`` checkbox to enable the slave to synchronize with the master.
* Check the [guimenu]``Sync All Orgs to Slave?`` checkbox to synchronize all organizations to this slave.
. Click btn:[Create] to add the ISS slave.
. In the [guimenu]``Allow Export of the Selected Organizations`` section, check the organizations you want to allow this slave to export to the master, and click btn:[Allow Orgs].



Before you set up the ISS Slave, you need to ensure you have the appropriate CA certificate.



.Procedure: Copying the Master CA Certificate to an ISS Slave
. On the ISS Master, locate the CA Certificate at ``/srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT`` and create a copy that can be transferred to the ISS Slave.
. On the ISS Slave, save the CA certificate file to the ``/etc/pki/trust/anchors/`` directory.


When you have copied the certificate, you can set up the ISS Slave.



.Procedure: Setting up an ISS Slave

. In the {productname} {webui}, navigate to menu:Admin[ISS Configuration > Slave Setup], and click btn:[Add new master].
. In the [guimenu]``Details for new Master`` dialog, provide these details for the server to use as the ISS master:
* In the [guimenu]``Master Fully Qualified Domain Name`` field, enter the FQDN of the ISS Master for this slave.
    For example: ``server1.example.com``.
* In the [guimenu]``Filename of this Master's CA Certificate`` field, enter the absolute path to the CA certificate on the ISS master.
    This should be ``/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT``.
. Click btn:[Add new master] to add the ISS Slave to this master.



.Procedure: Completing ISS Setup
. At the command prompt on the ISS Slave, synchronize with the ISS Master:
+
----
mgr-inter-sync
----
. OPTIONAL: To synchronize a single channel, use this command:
+
----
mgr-inter-sync -c <channel-name>
----
. In the {productname} {webui}, navigate to menu:Admin[ISS Configuration > Configure Master-to-Slave Mappings] and select the organizations you want to synchronize.
