[[iss]]
= Inter-Server Synchronization - Version 2

If you have more than one {productname} installation, for example,
in a Hub deployment scenario, you will need to copy content between servers.
Inter-Server Synchronization (ISS) allows you to export data from one server (source)
and import it on another (target) server.



[NOTE]
====
With the new ISS implementation we removed the master/slave notion.
Content can be exported and imported in any direction between any {productname} server.
====

== Install ISS Packages

In order to use ISS you need to install one additional package both in source and target servers.
The package is available on the product repository with the name:

----
inter-server-sync
----

== Content Synchronization


.Procedure: Export data on source server
. In the {productname} source server command line call the ISS export command and follow the instructions
+
----
inter-server-sync export -h
----



The export procedure will create an output directory with all the needed data for the import procedure



.Procedure: Copy export directory to target server
. Content from {productname} source server needs to be synchronized to target server. Example command:
+
----
rsync -r <PATH_EXPORTED_DIR> root@<Target_server>:~/
----


After all content get copied you can start importing it.



.Procedure: Import data on target server
. In the {productname} source server command line call the ISS import command and follow the instructions
+
----
inter-server-sync import -h
----
