[[security-master-fingerprint]]
= Set up a Client to Master Validation Fingerprint


In highly secure network configurations you may wish to ensure your {salt} clients are connecting a specific master.
To set up validatfrom client to master start by entering the master's fingerprint within the configuration file:

* [path]``/etc/salt/minion.d/custom.conf`` in cases of using classic {salt} minion in your client, or
* [path]``/etc/venv-salt-minion/minion.d/custom.conf`` in case of using {salt} Bundle in your client

and follow the procedure:

[IMPORTANT]
====
To access a shell inside the Server container run [literal]``mgrctl term`` on the container host.
====

.Procedure: Adding Master's Fingerprint to Client
. On the master, at the command prompt, as root, use this command to find the ``master.pub`` fingerprint:
+

----
salt-key -F master
----
+

On your client, open the [path]``/etc/salt/minion`` or [path]``/etc/venv-salt-minion/minion.d/custom.conf`` configuration file.
Uncomment the following line and enter the master's fingerprint replacing the example fingerprint:
+

----
master_finger: 'ba:30:65:2a:d6:9e:20:4f:d8:b2:f3:a7:d4:65:11:13'
----

. Restart the salt-minion service:
+

----
# systemctl restart salt-minion
----

In case of using {salt} Bundle, instead of [literal]``salt-minion`` use [literal]``venv-salt-minion``.
For more information about {salt} Bundle, see xref:client-configuration:contact-methods-saltbundle.adoc[].

For information on configuring security from a client, see https://docs.saltstack.com/en/latest/ref/configuration/minion.html.
