[[ch-openscap]]
= System Security with OpenSCAP


{productname} uses OpenSCAP to audit clients.
It allows you to schedule and view compliance scans for any client.


== About SCAP

The Security Certification and Authorization Package (SCAP) is a standardized compliance checking solution for enterprise-level Linux infrastructures.
It is a line of specifications maintained by the National Institute of Standards and Technology (NIST) for maintaining system security for enterprise systems.

SCAP was created to provide a standardized approach to maintaining system security, and the standards that are used continually change to meet the needs of the community and enterprise businesses.
New specifications are governed by NIST's SCAP Release cycle to provide a consistent and repeatable revision work flow.
For more information, see http://scap.nist.gov/timeline.html.

{productname} uses OpenSCAP to implement the SCAP specifications.
OpenSCAP is an auditing tool that utilizes the Extensible Configuration Checklist Description Format (XCCDF).
XCCDF is a standard way of expressing checklist content and defines security checklists.
It also combines with other specifications such as Common Platform Enumeration (CPE), Common Configuration Enumeration (CCE), and Open Vulnerability and Assessment Language (OVAL), to create a SCAP-expressed checklist that can be processed by SCAP-validated products.

OpenSCAP verifies the presence of patches by using content produced by the {suse} Security Team.
OpenSCAP  checks system security configuration settings and examines systems for signs of compromise by using rules based on standards and specifications.
For more information about the {suse} Security Team, see  https://www.suse.com/support/security.



== Prepare Clients for an SCAP Scan

Before you begin, you need to prepare your client systems for SCAP scanning.

[NOTE]
====
OpenSCAP auditing is not available on Salt clients that use the SSH contact method.
====

[IMPORTANT]
====
Scanning clients can consume a lot of memory and compute power on the client being scanned.
For {redhat} clients, ensure you have at least 2{nbsp}GB of RAM available on each client to be scanned.
====

For traditional and Salt clients, install the OpenSCAP scanner and the SCAP Security Guide (content) packages before you begin.
Depending on the operating system, these packages are included either on the base operating system, or in the {productname} Client Tools.

The table below lists the packages you need depending on your client operating system:

.OpenSCAP packages
[%header,cols=3]
|===
| Operating system | Scanner | Content
| SLES | openscap-utils | scap-security-guide
| openSUSE | openscap-utils | scap-security-guide
| RHEL | openscap-utils | scap-security-guide-redhat
| CentOS | openscap-utils | scap-security-guide-redhat
| Oracle Linux | openscap-utils | scap-security-guide-redhat
| Ubuntu | libopenscap8 | scap-security-guide-ubuntu
| Debian | libopenscap8 | scap-security-guide-debian
|===

RHEL 7 and compatible systems provide a [package]``scap-security-guide`` package, which contains outdated contents.
You are advised to use the [package]``scap-security-guide-redhat`` package you will find in the {productname} Client Tools.


[IMPORTANT]
====
{suse} provides the [package]``scap-security-guide`` package for different openscap profiles.
In the current version of [package]``scap-security-guide``, {suse} supports the following profiles:

* DISA STIG profile for {sles} 12 and 15
* PCI-DSS profile for {sles} 12 and 15
* HIPAA profile for {sles} 12 and 15

Other profiles, like the CIS profile, are community supplied and not officially supported by {suse}.

For Non-{suse} OSs, note that the included profiles are community supplied and not officially supported by {suse}SUSE.
====

== OpenSCAP Content Files

OpenSCAP uses SCAP content files to define test rules.
These content files are created based on the XCCDF or OVAL standards.
In addition to the SCAP Security Guide, you can download publicly available content files and customize it to your requirements.
You can install the SCAP Security Guide package for default content file templates.
Alternatively, if you are familiar with XCCDF or OVAL, you can create your own content files.


[WARNING]
====
We recommend you use templates to create your SCAP content files.
If you create and use your own custom content files, you do so at your own risk.
If your system becomes damaged through the use of custom content files, you might not be supported by {suse}.
====

When you have created your content files, you need to transfer the file to the client.
You can do this in the same way as you move any other file, using physical storage media, or across a network with Salt (for example, https://docs.saltproject.io/en/latest/ref/cli/salt-cp.html[salt-cp] or the https://docs.saltproject.io/en/latest/ref/file_server/index.html[Salt File Server]), [command]``ftp`` or [command]``scp``.

We recommend that you create a package to distribute content files to clients that you are managing with {productname}.
Packages can be signed and verified to ensure their integrity.
For more information, see xref:administration:custom-channels.adoc[].



== Find OpenSCAP profiles

Different operating systems make available different OpenSCAP content files and profiles. One content file may contain more than one profile.

On RPM-based operating systems, use this command to determine the location of the available SCAP files:

----
rpm -ql <scap-security-guide-package-name-from-table>
----

On DEB-based operating systems, use this command to determine the location of the available SCAP files:

----
dpkg -L <scap-security-guide-package-name-from-table>
----

When you have identified one SCAP content file that suits your needs, list profiles available on the client:

----
oscap info ./usr/share/xml/scap/ssg/content/ssg-sle15-ds-1.2.xml
Document type: Source Data Stream
Imported: 2021-03-24T18:14:45

Stream: scap_org.open-scap_datastream_from_xccdf_ssg-sle15-xccdf-1.2.xml
Generated: (null)
Version: 1.2
Checklists:
        Ref-Id: scap_org.open-scap_cref_ssg-sle15-xccdf-1.2.xml
                Status: draft
                Generated: 2021-03-24
                Resolved: true
                Profiles:
                        Title: CIS SUSE Linux Enterprise 15 Benchmark
                                Id: xccdf_org.ssgproject.content_profile_cis
                        Title: Standard System Security Profile for SUSE Linux Enterprise 15
                                Id: xccdf_org.ssgproject.content_profile_standard
                        Title: DISA STIG for SUSE Linux Enterprise 15
                                Id: xccdf_org.ssgproject.content_profile_stig
                Referenced check files:
                        ssg-sle15-oval.xml
                                system: http://oval.mitre.org/XMLSchema/oval-definitions-5
                        ssg-sle15-ocil.xml
                                system: http://scap.nist.gov/schema/ocil/2
                        https://ftp.suse.com/pub/projects/security/oval/suse.linux.enterprise.15.xml
                                system: http://oval.mitre.org/XMLSchema/oval-definitions-5
Checks:
        Ref-Id: scap_org.open-scap_cref_ssg-sle15-oval.xml
        Ref-Id: scap_org.open-scap_cref_ssg-sle15-ocil.xml
        Ref-Id: scap_org.open-scap_cref_ssg-sle15-cpe-oval.xml
Dictionaries:
        Ref-Id: scap_org.open-scap_cref_ssg-sle15-cpe-dictionary.xml
----


Take a note of the file paths and profiles for performing the scan.



== Perform an Audit Scan

When you have installed or transferred your content files, you can perform audit scans.
Audit scans can be triggered using the {productname} {webui}.
You can also use the {productname} API to schedule regular scans.

.Procedure: Running an Audit Scan from the {webui}
. In the {productname} {webui}, navigate to menu:Systems[Systems List] and select the client you want to scan.
. Navigate to the [guimenu]``Audit`` tab, and the [guimenu]``Schedule`` subtab.
. In the [guimenu]``Path to XCCDF Document`` field, enter the parameters for the SCAP template and profile you want to use on the client.
  For example:
----
  Command: /usr/bin/oscap xccdf eval
  Command-line arguments: --profile xccdf_org.ssgproject.content_profile_standard
  Path to XCCDF document: /usr/share/xml/scap/ssg/content/ssg-sle15-ds-1.2.xml
----

. The scan runs at the client's next scheduled synchronization.


[[IMPORTANT]]
====
The XCCDF content file is validated before it is run on the remote system.
If the content file includes invalid arguments, the test fails.
====


.Procedure: Running an Audit Scan from the API
. Before you begin, ensure that the client to be scanned has Python and XML-RPC libraries installed.
. Choose an existing script or create a script for scheduling a system scan through ``system.scap.scheduleXccdfScan``.
  For example:
+
----
#!/usr/bin/python
client = xmlrpclib.Server('https://server.example.com/rpc/api')
key = client.auth.login('username', 'password')
client.system.scap.scheduleXccdfScan(key, <1000010001>,
    '<path_to_xccdf_file.xml>',
    '--profile <profile_name>')
----
+
In this example:
* ``<1000010001>`` is the system ID (sid).
* ``<path_to_xccdf_file.xml>`` is the path to the content file location on the client.
  For example, [path]``/usr/share/xml/scap/ssg/content/ssg-sle15-ds-1.2.xml``.
* ``<profile_name>`` is an additional argument for the [command]``oscap`` command.
  For example, use ``united_states_government_configuration_baseline`` (USGCB).
. Run the script on the client you want to scan, from the command prompt.



== Scan Results


Information about the scans you have run is in the {productname} {webui}.
Navigate to to menu:Audit[OpenSCAP > All Scans] for a table of results.
For more information about the data in this table, see xref:reference:audit/openscap-all-scans.adoc[].

To ensure that detailed information about scans is available, you need to enable it on the client.
In the {productname} {webui}, navigate to menu:Admin[Organizations] and click on the organization the client is a part of.
Navigate to the [guimenu]``Configuration`` tab, and check the [guimenu]``Enable Upload of Detailed SCAP Files`` option.
When enabled, this generates an additional HTML file on every scan, which contains extra information.
The results show an extra line similar to this:

----
Detailed Results: xccdf-report.html xccdf-results.xml scap-yast2sec-oval.xml.result.xml
----


To retrieve scan information from the command line, use the [command]``spacewalk-report`` command:

----
spacewalk-report system-history-scap
spacewalk-report scap-scan
spacewalk-report scap-scan-results
----


You can also use the {productname} API to view results, with the ``system.scap`` handler.



== Remediation

Remediation bash scripts and Ansible playbooks are provided in the same SCAP Security Guide packages to harden the client systems. For example:

.bash scripts
----
/usr/share/scap-security-guide/bash/sle15-script-cis.sh
/usr/share/scap-security-guide/bash/sle15-script-standard.sh
/usr/share/scap-security-guide/bash/sle15-script-stig.sh
----

.Ansible playbooks
----
/usr/share/scap-security-guide/ansible/sle15-playbook-cis.yml
/usr/share/scap-security-guide/ansible/sle15-playbook-standard.yml
/usr/share/scap-security-guide/ansible/sle15-playbook-stig.yml
----

You can run them using remote commands or with Ansible, after enabling Ansible in the client system.


////
Old content that has come across from the Reference Guide starts here. Pretty much all of this now exists in the right locations, but I'm leaving it here for posterity on the chance that there is yelling. --LKB 2020-08-05

[[sm-audit-page]]
= Systems Audit Page

To display a system's audit page, click menu:Systems[system_name > Audit].
Use this page to schedule and view compliance scans for a particular system.
Scans are performed by the OpenSCAP tool, which implements NIST's standard Security Content Automation Protocol (SCAP).
Before you scan a system, make sure that the SCAP content is prepared and all prerequisites in
xref:reference:audit/audit-openscap-overview.adoc#s1-openscap-suma-prerq[Prerequisites for Using OpenSCAP in {productname}] are met.

== List Scans

This subtab lists a summary of all scans completed on the system.
The following columns are displayed:

XCCDF Test Result::
The scan test result name, which provides a link to the detailed results of the scan.

Completed::
The exact time the scan finished.

Compliance::
The unweighted pass/fail ratio of compliance based on the Standard used.

P::
Number of checks that passed.

F::
Number of checks that failed.

E::
Number of errors that occurred during the scan.

U::
Unknown.

N::
Not applicable to the machine.

K::
Not checked.

S::
Not Selected.

I::
Informational.

X::
Fixed.

Total::
Total number of checks.


Each entry starts with an icon indicating the results of a comparison to a previous similar scan.
The icons indicate the following:

* "RHN List Checked" Icon -- no difference between the compared scans.
* "RHN List Alert" Icon -- arbitrary differences between the compared scans.
* "RHN List Error" Icon -- major differences between the compared scans. Either there are more failures than the previous scan or less passes
* "RHN List Check In" Icon -- no comparable scan was found, therefore, no comparison was made.


To find out what has changed between two scans in more detail, select the ones you are interested in and click menu:Compare Selected Scans[]
.
To delete scans that are no longer relevant, select those and click on menu:Remove Selected Scans[]
.
Scan results can also be downloaded in CSV format.

== Scan Details


The Scan Details page contains the results of a single scan.
The page is divided into two sections:

Details of the XCCDF Scan::
This section displays various details about the scan, including:
** File System Path: the path to the XCCDF file used for the scan.
** Command-line Arguments: any additional command-line arguments that were used.
** Profile Identifier: the profile identifier used for the scan.
** Profile Title: the title of the profile used for the scan.
** Scan's Error output: any errors encountered during the scan.

XCCDF Rule Results::
The rule results provide the full list of XCCDF rule identifiers, identifying tags, and the result for each of these rule checks.
This list can be filtered by a specific result.


[[sm-audit-schedule]]
== Schedule Audit

Use the Schedule New XCCDF Scan page to schedule new scans for specific machines.
Scans occur at the system's next scheduled check-in that occurs after the date and time specified.
The following fields can be configured:

Command-line Arguments:::
Optional arguments to the [command]``oscap`` command, either:
** ``--profile PROFILE``: Specifies a particular profile from the XCCDF document.
+
Profiles are determined by the Profile tag in the XCCDF XML file.
Use the [command]``oscap`` command to see a list of profiles within a given XCCDF file, for example:
+

----
# oscap info /usr/local/share/scap/dist_sles12_scap-sles12-oval.xml
Document type: XCCDF Checklist
Checklist version: 1.1
Status: draft
Generated: 2015-12-12
Imported: 2016-02-15T22:09:33
Resolved: false
Profiles: SLES12-Default
----
+
If not specified, the default profile is used.
Some early versions of OpenSCAP in require that you use the `--profile` option or the scan fails.
** ``--skip-valid``: Do not validate input and output files. You can use this option to bypass the file validation process if you do not have well-formed XCCDF content.

Path to XCCDF Document:::
This is a required field.
The path parameter points to the XCCDF content location on the client system.
For example: [path]``/usr/local/share/scap/dist_sles12_scap-sles12-oval.xml``
+

WARNING: The XCCDF content is validated before it is run on the remote system.
Specifying invalid arguments can cause [command]``spacewalk-oscap`` to fail to validate or run.
Due to security concerns, the [command]``oscap xccdf eval`` command only accepts a limited set of parameters.
+

For information about how to schedule scans using the {webui}, refer to:
xref:reference:audit/audit-openscap-overview.adoc#pro-os-suma-audit-scans-webui[Procedure: Scans via the Web Interface]

////
