[[recurring-actions]]
= Recurring Actions

You can schedule automated recurring highstate actions for Salt clients.
Recurring highstate actions apply the highstate to clients on a specified schedule.
You can apply recurring action to individual clients, to all clients in a system group, or to an entire organization.


[IMPORTANT]
====
Recurring actions can only be used with Salt clients.
You cannot schedule recurring actions on traditional clients.
====



.Procedure: Creating a New Recurring Action
. To apply a recurring action to an individual client, navigate to [guimenu]``Systems``, click the client to configure schedules for, and navigate to the menu:States[Recurring States] tab.
. To apply a recurring action to a system group, navigate to menu:Systems[System Groups], select the group to configure schedules for, and navigate to menu:States[Recurring States] tab.
. Click btn:[Create].
. Type a name for the new schedule.
. Choose the frequency of the recurring action:
+
* [guimenu]``Hourly:`` Type the minute of each hour.
For example, [parameter]``15`` will run the action at fifteen minutes past every hour.
* [guimenu]``Daily:`` Select the time of each day.
For example, [parameter]``01:00`` will run the action at 0100 every day, in the timezone of the {productname} Server.
* [guimenu]``Weekly:`` Select the day of the week and the time of the day, to execute the action every week at the specified time.
* [guimenu]``Monthly:`` Select the day of the month and the time of the day, to execute the action every month at the specified time.
* [guimenu]``Custom Quartz format:`` For more detailed options, enter a custom quartz string.
For example, to run a recurring action at 0215 every Saturday of every month, enter:
+
----
0 15 2 ? * 7
----
. OPTIONAL: Toggle the [guimenu]``Test mode`` switch on to run the schedule in test mode.
. Click btn:[Create Schedule] to save, and see the complete list of existing schedules.



== Recurring Actions in Organizations


Organization Administrators can set and edit recurring actions for all clients in the organization.
Navigate to menu:Home[My Organization > Recurring States] to see all recurring actions that apply to the entire organization.

{productname} Administrators can set and edit recurring actions for all clients in all organizations.
Navigate to menu:Admin[Organizations], select the organization to manage, and navigate to the menu:States[Recurring States] tab.

[NOTE]
====
Recurring actions can only be used with Salt clients.
Traditional clients in your group or organization are ignored.
====



== Action Chains

If you need to perform a number of sequential actions on your clients, you can create an action chain to automate them.
Action chains can include any number of these actions, in any order:

* menu:System Details[Remote Command]
* menu:System Details[Schedule System Reboot]
* menu:System Details[States > Highstate]
* menu:System Details[Software > Packages > List/Remove]
* menu:System Details[Software > Packages > Install]
* menu:System Details[Software > Packages > Upgrade]
* menu:System Details[Software > Patches]
* menu:System Details[Software > Software Channels]
* menu:System Details[Configuration]
* menu:Images[Build]



.Procedure: Creating a New Action Chain
. In the {productname} {webui}, navigate to the first action you want to perform in the action chain.
For example, navigate to [guimenu]``System Details`` for a client, and click btn:[Schedule System Reboot].
. Check the [guimenu]``Add to`` field and select ``new action chain``.
. Confirm the action.
This will not perform the action immediately, it will instead create the new action chain, and a blue bar confirming this appears at the top of the screen.
. Continue adding actions to your action chain by checking the [guimenu]``Add to`` field and selecting the name of the action chain to add them to.
. When you have finished adding actions, navigate to menu:Schedule[Action Chains] and selecting the action chain from the list.
. Re-order actions by dragging them and dropping them into the correct position.
Click the blue plus sign to see the clients an action will be performed on.
Click btn:[Save] to save your changes.
. Schedule a time for your action chain to run, and click btn:[Save and Schedule].
If you leave the page without clicking either btn:[Save] or btn:[Save and Schedule] all unsaved changes will be discarded.

[NOTE]
====
If one action in an action chain fails, the action chain stops, and no further actions are executed.
====

You can see scheduled actions from action chains by navigating to menu:Schedule[Pending Actions].