[[workflow-removing-channel]]
= Removing Channel


This chapter describes how to manually remove {suse} provided channels from {productname} and to clean up end-of-life products, to reclaim space or for other purposes.




[[preparing-to-remove-channel]]
== Prepare to Remove a Channel

Before removing a channel, you must identify the label for the channel to be removed.
It can be done with {webui} or on the command line.

[IMPORTANT]
====
* Be careful not to remove channels that systems are currently subscribed to, or that you are planning on subscribing a system to.
* If there are systems that are currently subscribed to a channel that you want to delete, do not remove the channel until those systems are upgraded or unsubscribed.
====


=== Identify Channel Labels

.Procedure: Identifying Channel Labels Using {webui}
[role=procedure]
. In the {productname} {webui}, in the sidebar navigate to menu:Software[Channel List > All].
. This page displays the [label]``Channel Name``.
  If you select the link for a channel name, you will see the field for [literal]``Channel Label``.
. Identify the channel, and child channels, to be removed.


.Procedure: Identifying Channel Labels Using the Command Line
[role=procedure]

. You can get a list of channels by running the following command on the {productname} container host:
+
----
mgrctl exec -ti -- spacewalk-remove-channel -l
----


===  Verify Channel System Subscriptions

.Procedure: Verifying Channel System Subscriptions Using {webui}

. In the {productname} {webui}, in the sidebar navigate to menu:Software[Channel List > All].
. Locate [literal]``Systems`` column on the right.
. Check the [literal]``Systems`` column for the channel, or any child channels, that you want to remove.


.Procedure: Verifying Channel System Subscriptions Using the Command Line

. Run the following command on the {productname} container host:
+
----
mgrctl exec -ti -- 'spacecmd -- softwarechannel_listsystems <Channel Label>'
----


[[removing-channel]]
== Remove Channel

A channel, with its metadata, can be removed with command line tools only.

For actually removing packages from the filesystem, see <<cleaning-up-channel-packages>>.



=== Remove a Child Channel

.Procedure: Removing a Child Channel Using the Command Line

. To remove an individual channel run the following command on the {productname} container host:
+
----
mgrctl exec -ti -- spacewalk-remove-channel -c channel-label
----
+
. To remove multiple channels at the same time, use [literal]``-c`` flag for each channel, followed by the [literal]``channel-label``.
  For example:
+
----
mgrctl exec -ti -- spacewalk-remove-channel -c channel-label1 -c channel-label2
----


=== Remove a Parent and All the Child Channels

.Procedure: Removing a Parent and All the Child Channels
. To remove a parent channel with all of the child channels run a command such as:
+
----
mgrctl exec -ti -- spacewalk-remove-channel -a sles12-sp5-pool-x86_64
----


// Initially part of the file handed over by the SME, but this step is not directly related to the removal of channels.
//[[cleaning-up-channel-packages]]
//=== Cleaning up channel packages

//==== Running the synchronization

//.Procedure: Running the synchronization
//. After removing a channel, run the command ``spacewalk-repo-sync`` on all remaining channels, or wait for the operation to complete automatically.
//. Alternatively, for all currently added channels running the following command:
//+
//----
//mgr-sync refresh --refresh-channels
//----



== Remove Packages from the Database and the Filesystem

To finally gain space remove the packages from the database and filesystem.



=== Remove Packages from the Database Using {webui}

.Procedure: Removing Packages from the Database Using {webui}
. After removing the channel, you need to delete the packages from the database using the {webui}.
. In the {productname} {webui}, navigate to menu:SUSEManager[Software > Manage > Packages].
. Select [literal]``Package in no channel``, and delete the packages.
