[[ssl-certs-import]]
= Import SSL Certificates

//By default, {productname} uses a self-signed certificate.
//For additional security, you can import a custom certificate, signed by a third party certificate authority (CA).

This section covers how to configure SSL certificate for new {productname} installation, and how to replace existing certificates.

Before you begin, ensure you have:

* A certificate authority (CA) SSL public certificate.
  If you are using a CA chain, all intermediate CAs must also be available.
* An SSL server private key
* An SSL server certificate

All files must be in PEM format.

The host name of the SSL server certificate must match the fully qualified host name of the machine you deploy them on.
You can set the host names in the ``X509v3 Subject Alternative Name`` section of the certificate.
You can also list multiple host names if your environment requires it.

Third-party authorities commonly use intermediate CAs to sign requested server certificates.
In this case, all CAs in the chain are required to be available.
If there is no extra parameter or option available to specify intermediate CAs, take care that all CAs (Root CA and intermediate CAs) are stored in one file.



== Import Certificates for New Installations

By default, {productname} uses a self-signed certificate.
After you have completed the initial setup, you can replace the default certificate with an imported certificate.



.Procedure: Import Certificates on a New {productname} Server

. Install the {productname} Server according to the instructions in xref:installation-and-upgrade:install-intro.adoc[].
. Complete the initial setup according to xref:installation-and-upgrade:server-setup.adoc[].
. At the command prompt, point the SSL environment variables to the certificate file locations:
+
----
export CA_CERT=<path_to_CA_certificates_file>
export SERVER_KEY=<path_to_web_server_key>
export SERVER_CERT=<path_to_web_server_certificate>
----
. Complete {productname} setup:
+
----
yast susemanager_setup
----
+
When you are prompted for certificate details during setup, fill in random values.
The values are overridden by the values you specified at the command prompt.

[NOTE]
====
Execute the [command]``yast susemanager_setup`` command from the same shell you exported the environment variables from.
====



== Import Certificates for New Proxy Installations

By default, {productname} Proxy uses a self-signed certificate.
After you have completed the initial setup, you can replace the default certificate with an imported certificate.




.Procedure: Import Certificates on a New {productname} Proxy

. Install the {productname} Proxy according to the instructions in xref:installation-and-upgrade:install-intro.adoc[].
. Complete the initial setup according to xref:installation-and-upgrade:proxy-setup.adoc[].
. At the command prompt, run:
+
----
configure-proxy.sh
----
. At the ``Do you want to import existing certificates?`` prompt, type kbd:[y].
. Follow the prompts to complete setup.


[NOTE]
====
Use the same certificate authority to sign all server certificates for servers and proxies.
Certificates signed with different CAs do not match.
====



== Replace Certificates

You can replace active certificates on your {productname} installation with a new certificate.
To replace the certificates, you can replace the installed CA certificate with the new CA, and then update the database.



.Procedure: Replacing Existing Certificates

. On the {productname} Server, at the command prompt, call the command `mgr-ssl-cert-setup` and provide the certificates as parameters:
+
----
mgr-ssl-cert-setup --root-ca-file=<Path_to_Root_CA_Certificate> --server-cert-file=<Server_Cert_File> --server-key-file=<Server_Key_File>
----


Intermediate CAs can either be available in the file which is specified with `--root-ca-file` or specified as extra options with `--intermediate-ca-file`.
The `--intermediate-ca-file` option can be specified multiple times.
This command performs a number of tests on the provided files to test if they are valid and can be used for the requested use case.

. Restart services to pick up the changes:
+
----
spacewalk-service stop
systemctl restart postgresql.service
spacewalk-service start
----

. Update the database with the new CA:
+
----
/usr/bin/rhn-ssl-dbstore --ca-cert=<Path_to_Root_CA_Certificate>
----

If you are using a proxy, you need to generate a server certificate RPM for each proxy, using their host names and cnames.
You should use `mgr-ssl-cert-setup` also on a {productname} Proxy to replace the certificates.
Because the {productname} Proxy does not have a postgreSQL database, only [command]``spacewalk-service restart`` is sufficient.

If the Root CA was changed, it needs to get deployed to all the clients connected to {productname}.



.Procedure: Deploying the Root CA on Salt Clients

. In the {productname} {webui}, navigate to menu:Systems[Overview].
. Check all your Salt Clients to add them to the system set manager.
. Navigate to menu:Systems[System Set Manager > Overview].
. In the [guimenu]``States`` field, click btn:[Apply] to apply the system states.
. In the [guimenu]``Highstate`` page, click btn:[Apply Highstate] to propagate the changes to the clients.



=== Extra handling of traditional Clients

Traditional Clients are deprecated and should be replaced with Salt Client.

If the CA needs to be replaced when there are still traditional managed clients connected to {productname} some extra steps are required.

Important is, that the clients do not get disconnected when the new CA is activated on the {productname} Server and Proxies.
Deploy the 'old' and the 'new' Root CA certificates to the affected clients and trust them.
Use a configuration channel to deploy the certificte files to the clients and the remote command feature to regenerate the trust store.

After the new certificates are activated on the {productname} Server and Proxies, test if the connections are working and actions can still be scheduled on the clients.
If this is the case, the 'old' Root CA can be removed from clients.

