[[subscription-matching]]
= Subscription Matching


Your {suse} products require subscriptions, which are managed by the {scc} (SCC).
{productname} runs a nightly report checking the subscription status of all your registered clients against your SCC account.
The report gives you information about which clients consume which subscriptions, how many subscriptions you have remaining and available to use, and which clients do not have a current subscription.

Navigate to menu:Audit[Subscription Matching] to see the report.

The [guimenu]``Subscriptions Report`` tab gives information about current and expiring subscriptions.

The [guimenu]``Unmatched Products Report`` tab gives a list of clients that do not have a current subscription.
This includes clients that could not be matched, or that are not currently registered with {productname}.
The report includes product names and the number of systems that remain unmatched.

The [guimenu]``Pins`` tab allows you to associate individual clients to the relevant subscription.
This is especially useful if the subscription manager is not automatically associating clients to subscriptions successfully.

The [guimenu]``Messages`` tab shows any errors that occurred during the matching process.

You can also download the reports in .csv format, or access them from that command prompt in the [path]``/var/lib/spacewalk/subscription-matcher/`` directory.

By default, the subscription matcher runs daily, at midnight.
To change this, navigate to menu:Admin[Task Schedules] and click ``gatherer-matcher-default``.
Change the schedule as required, and click btn:``Update Schedule``.


[IMPORTANT]
====
The subscription matcher will not always match clients and subscriptions accurately.
It is not intended to be a replacement for auditing.
====



== Pin Clients to Subscriptions


If the subscription matcher is not automatically matching a particular client with the correct subscription, you can manually pin them.
When you have created a pin, the subscription matcher favors matching a specific subscription with a given system or group of systems.

However, the matcher will not always respect a pin.
It depends on the subscription being available, and whether or not the subscription can be applied to the client.

To add a new pin, click btn:[Add a Pin], and select the client to pin.
