[[support]]
= Support

When you manage systems in {productname} where you are entitled for support from {suse}, you can get the support data like [command]``supportconfig`` or [command]``sosreport``.
You will get the data from the managed client and upload it directly to SUSE Global Technical Support.

== Create a service request number

Before handing over the support data to Global Technical Support, you need to generate a service request number first.

To create a service request, go to https://scc.suse.com/support/requests and follow the instructions on the screen.
Write down the service request number.

[NOTE]
====
**Privacy statement**

{suse} treats system reports as confidential data.
For details about the {suse} privacy commitment, see https://www.suse.com/company/policies/privacy/.
====


== Collect and upload support data from {productname} to {suse}

.Procedure: Collecting support data and uploading with the {productname} {webui}


. In the {productname} {webui}, navigate to menu:Systems[System List > All] and select the client which support data should be added to the case.
. Then navigate to the [guimenu]``Details`` tab and select the [guimenu]``Support`` sub-tab.
. In the field [literal]``Support Case Number`` enter the service request number created above.
. In the field [literal]``Upload Region`` select option [literal]``EU`` or [literal]``US`` depending on the server where you want to upload your data.
. In the field [literal]``Command-line Arguments`` you can optionally enter options for tool which is used to collect the data from the target system.
  Which tool will be used can be found in the tip below this field.
. In the field [literal]``Earliest`` select the time of running this action.
. Click button btn:[Schedule].
  The action is scheduled and will be executed defined time. It will collect the data from the client and upload it directly to the upload server.


[NOTE]
====
Supported Products where support data can be collected:

- {productname} Proxy
- {productname} Server when it is registered as Peripheral Server in a Hub Scenario
- all {sles} and {opensuse} clients
- SUSE Liberty and compatible clients
- Ubuntu clients
- Debian clients
====


[NOTE]
====
To upload the support data from the main {productname} Server please still use [command]``mgradm support config`` from the container host.
====
