[[tls-certs-monitoring]]
= TLS Certificates for Monitoring

By default, {productname} does not provide any certificates for securing monitoring configuration.
For providing security, you can import custom certificates, self-signed or signed by a third party certificate authority (CA).

This section demonstrates how to generate client/server certificates for Prometheus and Node exporter minions self-signed with SUSE Manager CA.

The host name of the TLS keys and certificates must match the fully qualified host name of the machine you deploy them on.
You can set the host names in the ``X509v3 Subject Alternative Name`` section of the certificate.
You can also list multiple host names if your environment requires it.


== Generate client/server keys and certificates for monitoring

To generate TLS keys and certificates for use with Prometheus server and node exporters you can follow these instructions:

.Procedure: Create TLS keys and certificates

. On the {productname} Server, change to the ``ssl-build`` directory:
+
----
cd /root/ssl-build
----
. Create private key:
+
----
openssl genrsa -out server.key 2048
----
. Create Certificate Signing Request (CSR) using the private Key.
  An example OpenSSL configuration can be found below.
  Please ensure that the set-cname parameter is the fully qualified domain name of your SUSE Manager Server.
+
----
openssl req -sha256 -text -config rhn-minion-openssl.cnf
    -new -key server.key -out server.csr
----
. Create and sign certificate with CA:
+
----
openssl ca -extensions req_server_x509_extensions -outdir ./
    -config rhn-ca-openssl.cnf -in server.csr -batch
    -cert RHN-ORG-TRUSTED-SSL-CERT -keyfile RHN-ORG-PRIVATE-SSL-KEY
    -days 365 -md sha256 -out server.crt
----


=== Example for OpenSSL configuration file

The example of the OpenSSL configuration file ``rhn-minion-openssl.cnf`` used before can be found here.
Ensure that the CN and alt_names parameters are the fully qualified domain names of your minion.
You can also list multiple host names if your environment requires it.
+
----
[ req ]
default_bits            = 2048
distinguished_name      = req_distinguished_name
prompt                  = no
x509_extensions         = req_server_x509_extensions
req_extensions          = v3_req

[ req_distinguished_name ]
C                       = DE
ST                      = Bayern
L                       = Nuernberg
O                       = SUSE
OU                      = SUSE
CN                      = minion.tf.local
emailAddress            = galaxy-noise@suse.de


[ req_server_x509_extensions ]
basicConstraints = CA:false
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
nsCertType = server
nsComment               = "OpenSSL Generated Server Certificate"
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid, issuer:always

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName          = @alt_names

[alt_names]
DNS.1 = minion.tf.local
----
