[[troubleshooting-register-clones]]
= Troubleshooting Registering Cloned Clients

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

Sometimes a cloned client (either traditional or Salt) will use the same machine ID as the system they are a clone of.
This results in {productname} only recognizing one system, rather than two different systems.
This can be resolved by changing the machine ID of the  cloned system, so that {productname} recognizes them as two different clients.

[NOTE]
====
Each step in this section is performed on the cloned system.
This procedure does not manipulate the original system, which will still be registered to {productname}.
The cloned virtual machine should have a different UUID from the original (the UUID is generated by your hypervisor) or SUSE Manager will overwrite the original system data with the new one.
====

.Procedure: Resolving Duplicate Machine IDs in Cloned Salt Clients

. For {slsa}{nbsp}12: If your machines have the same machine IDs then delete the file on each client and recreate it:
+
----
# rm /etc/machine-id
# rm /var/lib/dbus/machine-id
# dbus-uuidgen --ensure
# systemd-machine-id-setup
----

. For {slsa}{nbsp}11: As there is no systemd machine ID, generate one from dbus:
+
----
# rm /var/lib/dbus/machine-id
# dbus-uuidgen --ensure
----
. If your machines still have the same minion ID then delete the minion_id file on each client (FQDN will be used when it is regenerated on client restart):
+
----
# rm /etc/salt/minion_id
----
. Delete accepted keys from the Onboarding page and the system profile from {productname}, and restart the client with:
+
----
# service salt-minion restart
----
. Re-register the clients.
Each client will now have a different [path]``/etc/machine-id`` and should now be correctly displayed on the System Overview page.


.Procedure: Resolving Duplicate Machine IDs in Cloned Traditional Clients

. On the cloned machine, change the hostname and IP addresses, and make sure [path]``/etc/hosts`` contains the changes you made and the correct host entries.
. Stop the rhnsd daemon, on {rhnminrelease6} and {sle} 11 with:
+
----
# /etc/init.d/rhnsd stop
----
+
or, on newer systemd-based systems, with:
+
----
# service rhnsd stop
----
. Stop osad with:
+
----
# /etc/init.d/osad stop
----
+
or:
+
----
# service osad stop
----
+
or:
+
----
# rcosad stop
----
. Remove the osad authentication configuration file and the system ID:
+
----
# rm -f /etc/sysconfig/rhn/{osad-auth.conf,systemid}
----
. Delete the files containing the machine IDs:
+
* {slsa}{nbsp}12:
+
----
# rm /etc/machine-id
# rm /var/lib/dbus/machine-id
# dbus-uuidgen --ensure
# systemd-machine-id-setup
----
* {slsa}{nbsp}11:
+
----
# suse_register -E
----
* {slsa}{nbsp}10:
+
----
# rm -rf /etc/{zmd,zypp}
# rm -rf /var/lib/zypp/!(db)
# rm -rf /var/lib/zmd/
----
. Remove the credential files:
* {slsa} clients:
+
----
# rm -f /etc/zypp/credentials.d/{SCCcredentials,NCCcredentials}
----
* {rhel} clients:
+
----
# rm  -f /etc/NCCcredentials
----
. Re-run the bootstrap script.
You should now see the cloned system in SUSE Manager without overwriting the system it was cloned from.
