[[troubleshooting-regtradrhel]]
= Troubleshooting Registering Traditional Red Hat Clients

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

////
Cause: Traditional RHEL 7 and SLES-ES 7 clients require some unsigned packages in order to work properly with {productname}, so custom channels for these client types usually unset the gpgcheck flag.
However, the rhnplugin.conf file overrides this setting, and enables the GPG check.
Consequence: When traditional RHEL 7 or SLES-ES 7 clients are registered, the client will not install unsigned packages from the custom channel, even if the gpgcheck is disabled in the custom channel.
Fix: Edit the /etc/yum/pluginconf.d/rhnplugin.conf file to disable the GPG check.
Result: Unsigned packages can be installed as required, and the clients will work as expected.
////

Traditional {rhel}{nbsp}7 and SLES {es}{nbsp}7 clients require some unsigned packages to work properly with {productname}, so custom channels for these client types usually unset the ``gpgcheck`` flag.
However, the ``rhnplugin.conf`` file overrides this setting, and enables the GPG check.

This means that when traditional {rhel}{nbsp}7 and SLES {es}{nbsp}7 clients are registered, the client will not install unsigned packages from the custom channel, even if the ``gpgcheck`` is disabled in the custom channel.

To resolve the problem, edit the ``/etc/yum/pluginconf.d/rhnplugin.conf`` file and disable the GPG check to enable installation of unsigned packages, and allow the clients to work as expected.
