[[troubleshooting-notifications]]
= Troubleshooting Notifications

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////



The default lifetime of notification messages is 30 days, after which messages are deleted from the database, regardless of read status.
To change this value, add or edit this line in [path]``/etc/rhn/rhn.conf``:

----
java.notifications_lifetime = 30
----

All notification types are enabled by default.
To disable a notification type, add or edit this line in [path]``/etc/rhn/rhn.conf``:

----
java.notifications_type_disabled = OnboardingFailed,ChannelSyncFailed,ChannelSyncFinished
----
