[[upgrade-troubleshooting]]
= Troubleshooting

This section contains some common problems you might encounter with {productname} upgrades, and solutions to resolving them.

To get more information about an upgrade problem, check the migration log file.
The log file is located at [path]``/var/log/rhn/migration.log`` on the system you are upgrading.


////

PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step

////



== Schema Upgrade Fails

If the schema upgrade fails, the database version check and all the other spacewalk services do not start.
Run [command]``spacewalk-service start`` for more information and hints how to proceed.

You can also run the version check directly:

----
systemctl status uyuni-check-database.service
----

or

----
journalctl -u uyuni-check-database.service
----

These commands print debug information if you do not want to run the more general [command]``spacewalk-service`` command.
