[[troubleshooting-package-sync]]
= Troubleshooting Package Synchronization

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

{productname} does not automatically trust third party GPG keys.
If package synchronization fails, it could be because of an untrusted GPG key.
You can find out if this is the case by opening [path]``/var/log/rhn/reposync`` and looking for an error like this:

----
['/usr/bin/spacewalk-repo-sync', '--channel', 'sle-12-sp1-ga-desktop-
nvidia-driver-x86_64', '--type', 'yum', '--non-interactive']
ChannelException: The GPG key for this repository is not part of the keyring.
Please run spacewalk-repo-sync in interactive mode to import it.
----

To resolve the problem, you need to import the GPG key to {productname}.
For more on importing GPG keys, see xref:administration:repo-metadata.adoc[].
