[[users]]
= Users

{productname} Administrators can add new users, grant permissions, and deactivate or delete users.
If you are managing a large number of users, you can assign users to system groups to manage permissions at a group level.
You can also change the system defaults for the {webui}, including language and theme defaults.


[NOTE]
====
The [guimenu]``Users`` menu is only available if you are logged in with the {productname} administrator account.
====


To manage {productname} users, navigate to menu:Users[User List > All] to see all users in your {productname} Server.
Each user in the list shows the username, real name, assigned roles, the date the user last signed in, and the current status of the user.
Click btn:[Create User] to create a new user account.
Click the username to go to the [guimenu]``User Details`` page.

To add new users to your organization, click btn:[Create User], complete the details for the new user, and click btn:[Create Login].


[[users.password.requirments]]
== Password requirements

{productname} is shipped with a selection of default values.

To ensure that all new user passwords adhere to the organization's security standards, {productname} administrator has the option to enforce the password creation rules.

In the {webui}, navigate to menu:Admin[Manager Configuration > Password Policy] to define the password requirements.
Use a combination of the following fields:

Min Password Length::
Use this field to define the minimal length of password.

Max Password Length::
Use this field to define the maximum length of password.

Require Digits::
Use this field to specify whether the password must include the digits (0-9).

Require Lowercase Characters::
Use this field to specify whether the password must include the lowercase characters (a-z).

Require Uppercase Characters::
Use this field to specify whether the password must include the uppercase characters (A-Z).

Restrict Consecutive Characters::
Use this field to specify whether the restricted consecutive characters.

Require Special Characters::
Use this field to specify whether the passoerd must include special characters.

Allowed Special Characters::
This field is enable only of the [literal]``Require Special Characters`` is selected.
Use it to specify which special characters are allowed, for example [literal]``!@#$%&*``, and others.

Restrict Character Occurences::
Use this field to specify restricted character occurences.

Max Character Occurences::
Use this field to specify maximum character occurences.

Use button [button]``Save`` to save any of the changed password settings.

Use button [button]``Reset`` to change any settings to the default ones.

[NOTE]
====
{productname} is shipped with the following default values:

* Min Password Length: 4
* Max Password Length: 32
* Require Uppercase Characters: checked
====


== Deactivate and Delete Accounts

You can deactivate or delete user accounts if they are no longer required.
Deactivated user accounts can be reactivated at any time.
Deleted user accounts are not visible, and cannot be retrieved.

Users can deactivate their own accounts.
However, if users have an administrator role, the role must be removed before the account can be deactivated.

Deactivated users cannot log in to the {productname} {webui} or schedule any actions.
Actions scheduled by a user prior to their deactivation remain in the action queue.
Deactivated users can be reactivated by {productname} administrators.



== Administrator Roles

Users can hold multiple administrator roles, and there can  be more than one user holding any administrator role at any time.
There must always be at least one active {productname} Administrator.

To change a user's administrator roles, except for the {productname} Administrator role, navigate to menu:Users[User List > All], select the user to change, and check or uncheck the administrator roles as required.

To change a user's {productname} Administrator role, navigate to menu:Admin[Users] and check or uncheck [guimenu]``{productname} Admin?`` as required.


[cols="1,1", options="header"]
.User Administrator Role Permissions
|===
| Role Name | Description
| System Group User | Standard role associated with all users.
| {productname} Administrator | Can perform all functions, including changing privileges of other users.
| Organization Administrator | Manages activation keys, configurations, channels, and system groups.
| Activation Key Administrator | Manages activation keys.
| Image Administrator | Manages image profiles, builds, and stores.
| Configuration Administrator | Manages system configuration.
| Channel Administrator | Manages software channels, including making channels globally subscribable, and creating new channels.
| System Group Administrator | Manages systems groups, including creating and deleting system groups, adding clients to existing groups, and managing user access to groups.
|===



== User Permissions and Systems

If you have created system groups to manage your clients, you can assign groups to users for them to manage.

To assign a user to a system group, navigate to menu:Users[User List], click the username to edit, and go to the [guimenu]``System Groups`` tab.
Check the groups to assign, and click btn:[Update Defaults].

You can also select one or more default system groups for a user.
When the user registers a new client, it is assigned to the chosen system group by default.
This allows the user to immediately access the newly registered client.

// I really don't understand what this is. Need a sentence or two to explain it.  --LKB 2020-04-29
To manage external groups, navigate to menu:Users[System Group Configuration], and go to the [guimenu]``External Authentication`` tab.
Click btn:[Create External Group] to create a new external group.
Give the group a name, and assign it to the appropriate system group.

For more information about system groups, see xref:reference:systems/system-groups.adoc[].


To see the individual clients a user can administer, navigate to menu:Users[User List], click the username to edit, and go to the [guimenu]``Systems`` tab.
To carry out bulk tasks, you can select clients from the list to add them to the system set manager.

For more information about the system set manager, see xref:client-configuration:system-set-manager.adoc[].



== Users and Channel Permissions

You can assign users to software channels within your organization either as a subscriber that consumes content from channels, or as an administrator, who can manage the channels themselves.

To subscribe a user to a channel, navigate to menu:Users[User List], click the username to edit, and go to the menu:Channel Permissions[Subscription] tab.
Check the channels to assign, and click btn:[Update Permissions].

To grant a user channel management permissions, navigate to menu:Users[User List], click the username to edit, and go to the menu:Channel Permissions[Management] tab.
Check the channels to assign, and click btn:[Update Permissions].

Some channels in the list might not be subscribable.
This is usually because of the users administrator status, or the channels global settings.



== User Default Language

When you create a new user, you can choose which language to use for the {webui}.
After a user has been created, you can change the language by navigating to menu:Home[My Preferences].

The default language is set in the ``rhn.conf`` configuration file.
To change the default language, open the [path]``/etc/rhn/rhn.conf`` file and add or edit this line:

----
web.locale = <LANGCODE>
----

If the parameter is not set, the default language is ``en_US``.

These languages are available in {productname}:

ifeval::[{mlm-content} == true]

[[langcodes-mlm]]
.Available Language Codes
[cols="1,1,1", options="header"]
|===
| Language code | Language   | Dialect
| ``en_US``     | English    | United States
| ``zh_CN``     | Chinese    | Mainland, Simplified
|===
endif::[]

ifeval::[{uyuni-content} == true]

[[langcodes-uyuni]]
.Available Language Codes
[cols="1,1,1", options="header"]
|===
| Language code | Language   | Dialect
| ``bn_IN``     | Bangla     | India
| ``ca``        | Catalan    |
| ``de``        | German     |
| ``en_US``     | English    | United States
| ``es``        | Spanish    |
| ``fr``        | French     |
| ``gu``        | Gujarati   |
| ``hi``        | Hindi      |
| ``it``        | Italian    |
| ``ja``        | Japanese   |
| ``ko``        | Korean     |
| ``pa``        | Punjabi    |
| ``pt``        | Portuguese |
| ``pt_BR``     | Portuguese | Brazil
| ``ru``        | Russian    |
| ``ta``        | Tamil      |
| ``zh_CN``     | Chinese    | Mainland, Simplified
| ``zh_TW``     | Chinese    | Taiwan, Traditional
|===


[IMPORTANT]
====
Translations in {uyuni} are provided by the community, and could be incorrect or incomplete.
Where a translation is not available, the {webui} defaults to English (``en_US``).
====

endif::[]



=== User Default Interface Theme

By default, the {productname} {webui} uses the theme appropriate to the product you have installed.
You can change the theme to reflect the {uyuni} or {susemgr} colors.
The {susemgr} theme also has a dark option available.

You can change the default theme in the ``rhn.conf`` configuration file.
To change the default theme, open the [path]``/etc/rhn/rhn.conf`` file and add or edit this line:

----
web.theme_default = <THEME>
----

[[webui-themes]]
.Available WebUI Themes
[cols="1,1,1", options="header"]
|===
| Theme Name     | Colors    | Style
| ``suse-light`` | {susemgr} | Light
| ``suse-dark``  | {susemgr} | Dark
| ``uyuni``      | {uyuni}   | Light
|===
