
= Deploying {productname} as a container
// remove this attribute at publishing time
:uyuni-content: true

The process of installing {productname} server was changed in version {productnumber}. 
{productname} is now deployed as a container.


ifeval::[{uyuni-content} == true]
== Requirements for deployment

You should already have your own server. This should be either {tumbleweed} or {opensuse} {opensuse-version}

* A server (This can be physical, or a virtual machine)
* Podman
* Uyuni container utilities


== Installing Podman on openSUSE Leap {opensuse-version} and {tumbleweed}

To install Podman on either {opensuse} {opensuse-version}, follow these steps:

. Open a terminal window.

. Update the package manager's repository information to ensure you have the latest package information:
+

[source,shell]
----
sudo zypper refresh
----

. Install Podman by running the following command:
+

[source,shell]
----
sudo zypper -y install podman
----

. Zypper will download and install Podman along with its dependencies.

. Once the installation is complete, verify that Podman is installed by running:
+

[source,shell]
----
podman --version
----
+

This command should display the installed version of Podman.
You should now have Podman successfully installed on your openSUSE Leap 15.5 system, and you can start using it to manage containers on your system.



== Installing Uyuni tools for use with containers

=== {opensuse} {opensuse-version}

. Add the following repository to your {opensuse} {opensuse-version} server and accept the key.
+

----
sudo zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/ContainerUtils/openSUSE_Leap_15.5/systemsmanagement:Uyuni:Master:ContainerUtils.repo
----

. Install tools:
+

----
sudo zypper in mgradm mgrctl mgradm-bash-completion mgrctl-bash-completion netavark
----



=== {opensuse} {tumbleweed}

. Add the following repository to your {opensuse} {tumbleweed} server and accept the key.
+

----
sudo zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/ContainerUtils/openSUSE_Tumbleweed/systemsmanagement:Uyuni:Master:ContainerUtils.repo
----

. Install tools:
+

----
sudo zypper in mgradm mgrctl mgradm-bash-completion mgrctl-bash-completion netavark
----


== Deploying an Uyuni container with Podman

=== mgradm overview

{productname} is deployed as a container using the **mgradm** tool.
You should have installed the tools in previous steps.

There are two paths for deploying an {productname} server as a container:

. **Beginner:** Running the **mgradm** command will prompt for basic server variables during the deployment.

. **Intermediate:** You may also create a custom **mgradm.yaml** file for use by the mgradm tool during deployment.

[NOTE]
====
 **mgradm** will prompt for basic variables if are not provided using command line parameters or a configuration file. 
 For security, **using command line parameters to specify passwords should be avoided**: use the configuration file with proper permissions instead.
====

=== Persistent volumes

Many users will want to specify locations for their persistent volumes.

[NOTE]
====
If you are just testing our {productname} you do not need to specify these names. mgradm will setup the correct volumes by default.

Specifiying volume locations will generally be used for larger deployments.
====

By default **Podman** stores its volumes in `/var/lib/containers/storage/volumes/`. 

You can provide custom storage for the volumes by mounting disks on this path or the expected volume path inside it such as: `/var/lib/containers/storage/volumes/var-spacewalk`. This is especially important for the database and package mirrors. 

For a list of all persistent volumes in the container see,  xref:installation-and-upgrade:container-deployment/persistent-container-volumes.adoc[Persistent container volumes]




== Managing containers with the mgrctl tool

mgrctl tool for using the container





endif::[]