== Transfer the Proxy Configuration

The {webui} generates a configuration archive.
This archive needs to be made available on the proxy container host.

[NOTE]
====
On {sl-micro} you must allow SSH root login with a password first:

. On the proxy host, start a transactional shell:

+

[source,shell]
----
transactional-update shell
----

+

--

.. In [path]``/usr/etc/ssh/sshd_config`` file, set:

+

----
PermitRootLogin yes
PasswordAuthentication yes
----

.. Leave the shell with [command]``exit`` to save the new configuration.

--

+

. Reboot the proxy host to activate the new configuartion:

+

[source,shell]
----
transactional-update reboot
----

For mor information about [command]``transactional-update``, see https://documentation.suse.com/sle-micro/6.1/html/Micro-transactional-updates/.

====

.Procedure: Copying the Proxy Configuration

. If not already done, copy the configuration archive ([literal]``config.tar.gz``) generated in the previous step from the server container to the server host:
+
----
mgrctl cp server:/root/config.tar.gz .
----

. If not already done, copy the files from the server host to the proxy host:
+
----
scp config.tar.gz <proxy-FQDN>:/root
----

. On the proxy host, install the Proxy with:
+

----
mgrpxy install podman config.tar.gz
----
