ifndef::backend-pdf[]
[[admin-overview]]
= 管理ガイド
:description: SUSE Multi-Linux Managerサーバの保守、監視、カスタマイズ方法をこの包括的な管理ガイドで学びましょう
:revdate: 2025-05-21
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューション文書チーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

// HTML Publication date 
**発行日:** {docdate}

== 序文


このガイドでは、{productname}サーバの保守、監視、カスタマイズなどの管理タスクについて説明します。

== 著作権通知

// HTML Copyright
Copyright © {copyrightdate} SUSE LLCおよび貢献者。All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]セクションに含まれています。

== 商標
// HTML Trademarks
SUSEの商標については、 https://www.suse.com/company/legal/を参照してください。すべてのサードパーティの商標は、それぞれの所有者に属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。
本書のすべての情報は、細心の注意を払って編集されています。しかし、これが完全な正確性を保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。
endif::[]


ifdef::backend-pdf[]

<<<

:!sectnums:

[preface]
== 序文

管理ガイド +
{productname} {productnumber}

このガイドでは、{productname}サーバの保守、監視、カスタマイズなどの管理タスクについて説明します。

// PDF Publication

**発行日:** {docdate}



// PDF Copyright
Copyright © {copyrightdate} SUSE LLCおよび貢献者。All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]セクションに含まれています。

// PDF Trademarks
SUSEの商標については、 https://www.suse.com/company/legal/を参照してください。すべてのサードパーティの商標は、それぞれの所有者に属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。
本書のすべての情報は、細心の注意を払って編集されています。しかし、これが完全な正確性を保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。

<<<

toc::[]

:sectnums:

endif::[]
