[[auth-methods-pam]]
= PAMによる認証
:description: SUSE Multi-Linux ManagerでSSSDを設定し、PAMを使用してネットワークベースの認証システムを統合して、安全にユーザー管理を行ってください。
:revdate: 2025-01-08
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

{productname}は、SSSDを使用してプラガブル認証モジュール（PAM）を利用したネットワークベースの認証システムをサポートしています。
PAMは、{productname}を集中認証メカニズムと統合するためのライブラリのスイートであり、複数のパスワードを記憶する必要を排除します。{productname}は、LDAP、Kerberos、およびその他のネットワークベースの認証プロトコルをサポートしています。


== SSSDの設定


.プロシージャ:SSSDの設定
. {productname} {webui}で、menu:ユーザー[ユーザーの作成]に移動し、新しいまたは既存のユーザーがPAMで認証できるようにします。
+
[NOTE]
====
ユーザー名には、英数字に加えて、`-`, `_`, `.`および`@`が許可されています。
====
. チェックボックス`Pluggable Authentication Modules (PAM)`にチェックを入れてください。
. サーバコンテナ内でSSSDを設定します。
  {productname}コンテナホストのコマンドプロンプトで、ルートとしてサーバコンテナに入ります：
+

----
mgrctl term
----

. コンテナ内で次の手順を実行します。
+
.. ご使用の設定に合わせて`/etc/sssd/sssd.conf`を編集してください。
   例については、xref:administration:auth-methods-pam.adoc#auth-methods-pam-ad[]を参照してください。
.. 実行したら、コンテナを終了します。
+
----
exit
----
. 次のコマンドを使用して{productname}を再起動します：
+
----
mgradm restart
----



[IMPORTANT]
====
{productname} {webui}でのパスワードの変更は、{productname}サーバー上のローカルパスワードのみを変更します。
そのユーザーに対してPAMが有効になっている場合、ローカルパスワードはまったく使用されない可能性があります。
上記の例では、たとえばKerberosパスワードは変更されません。
これらのユーザーのパスワードを変更するには、ネットワークサービスのパスワード変更メカニズムを使用してください。
====


PAM設定に関する詳細情報は、{sles}セキュリティガイドを参照してください。セキュリティガイドには、他のネットワークベースの認証方法にも適用できる一般的な例が含まれています。
また、Active Directory（AD）サービスの設定方法についても説明しています。
詳細については、{sles-base-os-documentation}/part-auth.htmlを参照してください。



[[auth-methods-pam-ad]]
=== LDAPとActive Directoryの統合例

Active DirectoryとのLDAP統合については、次の例を使用できます。

コードスニペットで、環境に応じて次のプレースホルダを変更します。

`$domain`::
ドメイン名
`$ad_server`::
ADサーバーのFQDNは、`$domain``$uyuni-hostname`から自動検出されない場合に指定してください:
このADクライアントが認識されるべきマシンの名前。
設定されていない場合は、`uyuni-server.mgr.internal`になります。


`/etc/sssd/sssd.conf`のサンプルスニペット：

----
[sssd]
config_file_version = 2
services = nss, pam
domains = $domain

[nss]

[pam]

[domain/$domain]
id_provider = ad
chpass_provider = ad
access_provider = ad
auth_provider = ad

ad_domain = $domain
ad_server = $ad_server
ad_hostname = $uyuni-hostname

ad_gpo_map_network = +susemanager

krb5_keytab = FILE:/etc/rhn/krb5.conf.d/krb5.keytab
krb5_ccname_template = FILE:/tmp/krb5cc_%{uid}
----
