[[content-staging]]
= コンテンツのステージング
:description: 組織全体でコンテンツステージングを管理するには、salt.content.staging.advanceやsalt.content.staging.windowなどのパラメータを設定します。
:revdate: 2025-01-13
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメントチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


ステージングは、クライアントがパッケージをインストールする前に事前にダウンロードするために使用されます。
これにより、パッケージのインストールがスケジュールされるとすぐに開始でき、メンテナンスウィンドウに必要な時間を短縮できます。


== コンテンツステージングの有効化


組織全体でコンテンツステージングを管理できます。
{productname} {webui}で、menu:管理者[組織]に移動して、利用可能な組織のリストを表示します。
組織の名前をクリックし、`Enable Staging Contents`ボックスにチェックを入れて、この組織のクライアントがパッケージデータをステージングできるようにします。

[NOTE]
====
組織を作成および管理するためには、{productname}の管理者としてログインしている必要があります。
====

`/etc/sysconfig/rhn/up2date`を編集し、次の行を追加または編集して、コマンドプロンプトでステージングを有効にすることもできます。

----
stagingContent=1
stagingContentWindow=24
----


`stagingContentWindow`パラメータは時間単位で表される時間値であり、ダウンロードが開始される時期を決定します。
これは、スケジュールされたインストールまたは更新の時間の前の時間数です。
この例では、コンテンツはインストール時間の24時間前にダウンロードされます。
ダウンロードの開始時間は、システムの選択された連絡方法によって異なります。

次回アクションがスケジュールされると、パッケージは自動的にダウンロードされますが、インストールはされません。
スケジュールされた時間に、ステージングされたパッケージがインストールされます。



== コンテンツステージングの設定

コンテンツステージングを設定するために使用される次の2つのパラメータがあります。

* `salt_content_staging_advance`は、コンテンツステージングウィンドウが開くまでの事前時間（時間単位）です。
    これは、インストールが開始されるまでの時間数で、この時間に達するとパッケージのダウンロードを開始できます。
* `salt_content_staging_window`は、コンテンツステージングウィンドウの期間（時間単位）です。
    これは、インストールが開始されるまでにクライアントがパッケージをステージングする必要がある時間数です。

例えば、`salt_content_staging_advance`が6時間に設定され、`salt_content_staging_window`が2時間に設定されている場合、ステージングウィンドウはインストール時間の6時間前に開き、2時間開いたままになります。
インストールが開始されるまでの4時間は、パッケージはダウンロードされません。

`salt_content_staging_advance`と`salt_content_staging_window`の両方に同じ値を設定すると、インストールが開始されるまで、パッケージをダウンロードできるようになります。

`/usr/share/rhn/config-defaults/rhn_java.conf`でコンテンツステージングパラメータを設定します。

デフォルト値:

* `salt_content_staging_advance: 8 hours`
* `salt_content_staging_window: 8 hours`


[NOTE]
====
これらのパラメータを正しく機能させるには、コンテンツステージングを有効にする必要があります。
====
