[[infra-maintenance]]
= インフラストラクチャ保守タスク
:description: SUSE Multi-Linux Managerインフラストラクチャを最新の更新プログラム、サービスパック、パッケージで常に最新の状態に保ってください。
:revdate: 2025-05-27
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションのドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

スケジュールされたダウンタイム期間で作業する場合、{productname}サーバーのクリティカルなダウンタイムの前、最中、後に行う必要があるすべてのことを思い出すのが難しいかもしれません。
インターサーバー同期スレーブサーバーや{productname}プロキシなどの{productname}サーバー関連システムも影響を受けるため、考慮する必要があります。

{suse}は、常に{productname}インフラストラクチャを最新の状態に保つことを推奨します。
これにはサーバー、プロキシ、ビルドホストが含まれます。
{productname}サーバーを最新の状態に保たないと、必要なときに環境の一部を更新できない場合があります。

このセクションには、ダウンタイム期間のチェックリストと、各ステップの実行に関する詳細情報へのリンクが含まれています。



== サーバ


.プロシージャ:サーバーチェック
[role=procedure]
____
. 最新の更新を適用します。

. 必要に応じて、最新のサービスパックにアップグレードします。

. `podman ps`を実行し、必要なすべてのサービスが稼働しているかどうかを確認します。
____

{sles} {bci-mlm}では、パッケージマネージャーを使用して更新をインストールできます。

* {yast}の使用に関する情報は、{sles-base-os-documentation}/cha-onlineupdate-you.htmlを参照してください。
* zypperの使用に関する情報は、{sles-base-os-documentation}/cha-sw-cl.html#sec-zypperを参照してください。

{sl-micro} {microversion}では、`transactional-update`コマンドを使用して更新をインストールできます。
`transactional-update`の使用方法については、 https://documentation.suse.com/sle-micro/6.1/html/Micro-transactional-updates/transactional-updates.html.を参照してください。


デフォルトでは、{productname}サーバーに対していくつかの更新チャネルが構成され、有効になっています。
新しいパッケージと更新されたパッケージは自動的に利用可能になります。


ifeval::[{mlm-content} == true]

{susemgr}を最新の状態に保つには、{scclongform}に直接接続するか、{rmtool}（RMT）を使用してください。
RMTを切断された環境のローカルインストールソースとして使用できます。

endif::[]


ifeval::[{mlm-content} == true]

次のコマンドを使用して、更新チャンネルがご使用のシステムで使用できることを確認できます。

----
zypper lr
----

出力は次のようになります。

----
Name                                                   | Enabled | GPG Check | Refresh
-------------------------------------------------------+---------+-----------+--------
SLE-Module-Basesystem15-SP7-Pool                       | Yes     | (r ) Yes  | No
SLE-Module-Basesystem15-SP7-Updates                    | Yes     | (r ) Yes  | Yes
SLE-Module-Containers15-SP7-Pool                       | Yes     | (r ) Yes  | No
SLE-Module-Containers15-SP7-Updates                    | Yes     | (r ) Yes  | Yes
SLE-Module-Python3-15-SP7-Pool                         | Yes     | (r ) Yes  | No
SLE-Module-Python3-15-SP7-Updates                      | Yes     | (r ) Yes  | Yes
SLE-Product-SLES15-SP7-Pool                            | Yes     | (r ) Yes  | No
SLE-Product-SLES15-SP7-Updates                         | Yes     | (r ) Yes  | Yes
SUSE-Multi-Linux-Manager-Server-SLE-5.1-Pool           | Yes     | (r ) Yes  | No
SUSE-Multi-Linux-Manager-Server-SLE-5.1-Updates        | Yes     | (r ) Yes  | Yes
SLE-Module-Server-Applications15-SP7-Pool              | Yes     | (r ) Yes  | No
SLE-Module-Server-Applications15-SP7-Updates           | Yes     | (r ) Yes  | Yes
SLE-Module-Systems-Management-15-SP7-Pool              | Yes     | (r ) Yes  | No
SLE-Module-Systems-Management-15-SP7-Updates           | Yes     | (r ) Yes  | Yes
----

endif::[]


ifeval::[{mlm-content} == true]

{productname}は新しいパッケージを提供するためにメンテナンス更新（MU）をリリースします。
メンテナンス更新は新しいバージョン番号で示されます。
例えば、メジャーリリース5.1は、MUがリリースされると5.1.1に更新されます。

{webui}のナビゲーションバーの下部を見て、実行中のバージョンを確認できます。
また、`api.getVersion()` XMLRPC APIコールを使用してバージョン番号を取得することもできます。

endif::[]



=== クライアントツール

サーバーが更新された際には、クライアント上のいくつかのツールも更新することを検討してください。
`venv-salt-minion`、`zypper`、およびクライアント上の他の関連管理パッケージを更新することは厳密な要件ではありませんが、一般的にはベストプラクティスです。
例えば、サーバのメンテナンス更新は、新しいメジャーSaltバージョンを導入する可能性があります。
その後、Saltクライアントは動作し続けますが、後で問題が発生する可能性があります。
これを避けるために、{suse}は`venv-salt-minion`が常に安全に更新されることを確認します。



== サーバ間同期スレーブサーバ

インターサーバー同期スレーブサーバーを使用している場合は、{productname}サーバの更新が完了した後で更新してください。

詳細については、xref:specialized-guides:large-deployments/iss_v2.adoc[Inter-Server Synchronization - Version 2]を参照してください。



== モニタリングサーバ

Prometheusにモニタリングサーバを使用している場合は、{productname}サーバの更新が完了した後で更新してください。

モニタリングに関する詳細は、xref:administration:monitoring.adoc[]を参照してください。



== プロキシ

プロキシは、{productname}サーバの更新が完了したらすぐに更新する必要があります。

一般的に、異なるバージョンのサーバに接続されたプロキシを実行することはサポートされていません。
唯一の例外は、更新の期間中であり、その際にはサーバが最初に更新されることが期待されるため、プロキシは一時的に前のバージョンを実行することができます。


[WARNING]
====
常に、最初にサーバをアップグレードしてから任意のプロキシをアップグレードしてください。
====
