[[workflow-removing-channel]]
= チャンネルの削除
:description: SUSE Multi-Linux ManagerからSUSE提供のチャンネルを削除し、コマンドラインツールを使用してサービス終了製品をクリーンアップします。
:revdate: 2025-01-23
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


この章では、{suse}で提供されているチャンネルを{productname}から手動で削除し、サービス終了製品をクリーンアップして、空き領域を確保する方法や他の目的について説明します。




[[preparing-to-remove-channel]]
== チャンネルの削除の準備


チャンネルを削除する前に、削除するチャンネルのラベルを特定する必要があります。
{webui}を使用するか、コマンドラインで行うことができます。

[IMPORTANT]
====
* システムが現在サブスクライブしているチャンネルや、サブスクライブする予定のチャンネルを削除しないように注意してください。
* 削除するチャンネルを現在サブスクライブしているシステムがある場合は、そのシステムをアップグレードするか、サブスクリプションを解除するまで、そのチャンネルを削除しないでください。
====


=== チャンネルのラベルの特定

.プロシージャ:{webui}を使用したチャンネルラベルの特定
[role=procedure]
. {productname} {webui}で、menu:ソフトウェア[チャンネルリスト> すべて]に移動します。
. このページには`Channel Name`が表示されます。
  チャンネル名のリンクを選択すると、`Channel Label`のフィールドが表示されます。
. 削除するチャンネルと子チャンネルを特定します。


.プロシージャ:コマンドラインを使用したチャンネルラベルの特定
[role=procedure]

. {productname}コンテナホストで次のコマンドを実行して、チャンネルのリストを取得できます。
+
----
mgrctl exec -ti -- spacewalk-remove-channel -l
----


===  システムのチャンネルのサブスクリプションの確認

.プロシージャ:{webui}を使用したシステムのチャンネルのサブスクリプションの確認

. {productname} {webui}で、menu:ソフトウェア[チャンネルリスト> すべて]に移動します。
. 右側の`Systems`列を探してください。
. 削除したいチャンネルやその子チャンネルについては、`Systems`列を確認してください。


.プロシージャ:コマンドラインを使用したシステムのチャンネルのサブスクリプションの確認

. {productname}コンテナホストで次のコマンドを実行します。
+
----
mgrctl exec -ti -- 'spacecmd -- softwarechannel_listsystems <Channel Label>'
----


[[removing-channel]]
== チャンネルの削除

チャンネルは、そのメタデータとともに、コマンドラインツールのみで削除できます。
`spacewalk-remove-channel`コマンドは、他のチャンネルから参照されていない場合、パッケージを自動的に削除します。
これにより、データベースからメタデータが削除され、ストレージメディアからファイルが削除されます。



=== 子チャンネルの削除

.プロシージャ:コマンドラインを使用した子チャンネルの削除

. 個々のチャンネルを削除するには、{productname}コンテナホストで次のコマンドを実行します。
+
----
mgrctl exec -ti -- spacewalk-remove-channel -c channel-label
----
+
. 複数のチャンネルを同時に削除するには、各チャンネルに対して`-c`フラグを使用し、その後に`channel-label`を付けます。
  例:
+
----
mgrctl exec -ti -- spacewalk-remove-channel -c channel-label1 -c channel-label2
----


=== 親チャンネルとそのすべての子チャンネルの削除

.プロシージャ:親チャンネルとそのすべての子チャンネルの削除
. 親チャンネルとすべての子チャンネルを削除するには、`spacewalk-remove-channel`を`-a`オプションと共に実行し、`parent-channel-label`を`sles12-sp5-pool-x86_64`のようなチャンネルラベルに置き換えます。
+
----
mgrctl exec -ti -- spacewalk-remove-channel -a parent-channel-label
----

