[[configure-autosync-channel]]
= 自動チャネル同期の設定
:description: アップストリームリポジトリからのチャンネル更新タイミングを制御するために、自動チャンネル同期を設定し、APIを使用してそのステータスを確認できるようにします。
:revdate: 2026-05-08
:page-revdate: {revdate}

デフォルトでは、クライアントが最新のコンテンツや更新に確実にアクセスできるように、チャネルはアップストリームリポジトリと自動的に同期されます。
ただし、特定のチャネルについては、この自動同期を無効にしたい場合があります。

本章では、チャネルの自動同期を無効にする方法を説明します。




[[get-channel-sync-satus]]
== チャネルの同期ステータスの確認

チャネルが自動同期されるように設定されているかどうかを確認するには、APIを呼び出します。

APIを使用してチャネルの同期ステータスを確認するには、次のコマンドを使用します。
`<Channel_Label>`を、確認するチャネルの実際のラベルに置き換えてください。

[source,console]
----
spacecmd api -- --args "<Channel_Label>" channel.software.isAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  true
]
----

自動同期が有効な場合は`true`が、無効な場合は`false`が返されます。

この情報は、{webui}でも確認できます。
同期ステータスを確認するには、チャネル詳細ページに移動し、`Automatic Repository Synchronization`フィールドを探します。


[[set-channel-sync-satus]]
== チャネルの自動同期をスキップするように設定する

チャネルの自動同期を有効または無効にするには、API呼び出し`channel.software.setAutoSync`を使用できます。

APIを使用してチャネルの自動同期をスキップするように設定する例を以下に示します（`<Channel_Label>`を更新対象のチャネルの実際のラベルに置き換えてください）。

[source,console]
----
spacecmd api -- --args '["<Channel_Label>", false]' channel.software.setAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  false
]
----

自動同期を再度有効にするには、2番目のパラメータを`true`に設定します。

[source,console]
----
spacecmd api -- --args '["<Channel_Label>", true]' channel.software.setAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  true
]
----


[[manual-channel-sync]]
== チャネルを手動で同期する

チャネルの自動同期を無効にした場合でも、必要に応じて手動で同期できます。

[IMPORTANT]
====
サーバコンテナ内でステップを実行する前に、`mgrctl term`を使用してください。
====

チャネルを手動で同期するには、コマンドを使用できます（`<Channel_Label>`を同期するチャネルの実際のラベルに置き換えてください）。

[source,console]
----
spacewalk-repo-sync -c <Channel_Label>
----
