[[subscription-matching]]
= サブスクリプションマッチング
:description: SUSE Multi-Linux Managerのサブスクリプションマッチング機能を使用して、SUSE製品のサブスクリプションを効果的に構成および管理します。これは、
:revdate: 2024-11-29
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

あなたの{suse}製品にはサブスクリプションが必要であり、それは{scclongform}（{scc}）によって管理されています。{productname}は、登録されたすべてのクライアントのサブスクリプションステータスをあなたの{scc}アカウントに対して確認する夜間レポートを実行します。
このレポートは、どのクライアントがどのサブスクリプションを消費しているか、残りのサブスクリプションの数と使用可能なサブスクリプションの数、現在のサブスクリプションを持っていないクライアントを示します。

レポートを見るには、menu:監査[サブスクリプションマッチング]に移動してください。

`Subscriptions Report`タブには、現在のサブスクリプションおよび期限切れが近いサブスクリプションに関する情報が表示されます。

`Unmatched Products Report`タブには、現在のサブスクリプションがないクライアントのリストが表示されます。
これには、マッチできなかったクライアントや、現在{productname}に登録されていないクライアントが含まれます。
レポートには、製品名と未マッチのシステムの数が含まれます。

`Pins`タブでは、個々のクライアントを関連するサブスクリプションに関連付けることができます。
これは、サブスクリプションマネージャーがクライアントをサブスクリプションに自動的に関連付けられない場合に特に便利です。

`Messages`タブには、マッチング処理中にサブスクリプションマッチャーによって生成されたすべてのメッセージが表示されます。
これらは、結果を理解し、マッチングを改善するための情報を提供します。

レポートは、.csv形式でダウンロードすることもでき、また、`/var/lib/spacewalk/subscription-matcher/`ディレクトリ内のコマンドプロンプトからアクセスすることも可能です。

デフォルトでは、サブスクリプションマッチャーは毎日、真夜中に実行されます。
これを変更するには、menu:管理[タスクスケジュール]に移動し、`gatherer-matcher-default`をクリックします。
必要に応じてスケジュールを変更し、btn:[スケジュールを更新]をクリックします。

レポートは、現在のクライアントと現在のサブスクリプションのみをマッチングできるため、マッチが時間とともに変わることがあります。
同じクライアントが常に同じサブスクリプションにマッチするわけではありません。
これは、新しいクライアントが登録されたり、未登録であったり、サブスクリプションの追加や期限切れによるものです。

サブスクリプションマッチャーは、アカウント内のサブスクリプションの利用規約に制限されて、未マッチの製品の数を自動的に減らそうとします。
ただし、ハードウェア情報が不完全であったり、未知の仮想マシンホストの割り当てがあったり、未知のパブリッククラウドでクライアントが稼働している場合、マッチャーは利用可能なサブスクリプションが不足していると表示することがあります。
常に、{productname}に含まれるクライアントに関する完全なデータを持っていることを確認し、正確性を確保してください。


[IMPORTANT]
====
サブスクリプションマッチャーは、クライアントとサブスクリプションを常に正確にマッチさせるわけではありません。
これは、監査の代替として意図されているわけではありません。
====



== クライアントをサブスクリプションにピン設定する



サブスクリプションマッチャーが特定のクライアントを正しいサブスクリプションに自動的にマッチさせない場合、手動でピンを設定することができます。
ピンを作成すると、サブスクリプションマッチャーは特定のサブスクリプションを特定のシステムまたはシステムのグループにマッチさせることを優先します。

ただし、マッチャーは常にピンを尊重するわけではありません。
それは、サブスクリプションが利用可能であるかどうか、またそのサブスクリプションがクライアントに適用できるかどうかに依存します。
さらに、ピンがサブスクリプションの利用規約に違反するマッチを引き起こす場合や、ピンを無視した場合により正確なマッチが検出される場合、ピンは無視されます。

新しいピンを追加するには、btn:[ピンの追加]をクリックし、ピンを設定するクライアントを選択します。

[IMPORTANT]
====
定期的にピンを使用したり、大量のクライアントに対して使用することはお勧めしません。
サブスクリプションマッチャーツールは、一般的にほとんどのインストールに対して十分に正確です。
====
