= Available Documentation
ifdef::env-github,backend-html5,backend-docbook5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:linkattrs:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:productname: Uyuni
:susemgr: SUSE Manager
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:saltversion: 2018.3.0
:webui: WebUI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:

:icons: font
:experimental:
:sourcedir: .
:imagesdir: images

The following manuals are available on this product:

ifdef::env-github,backend-html5[]
<<book_mgr_getting_started.adoc#book.suma.getting-started, SUSE Manager Getting Started>>::
endif::[]
ifndef::env-github,backend-html5[]
<<book.suma.getting-started>>::
endif::[]
Lists installation scenarios and example topologies for different {productname} setups.
Guides you step by step through the installation, setup and basic configuration of {productname}.
Also contains detailed information about {productname} maintenance and troubleshooting.

ifdef::env-github,backend-html5[]
<<book_suma_reference_manual.adoc#book.suma.reference.manual, Reference>>::
endif::[]
ifndef::env-github,backend-html5[]
<<book.suma.reference.manual>>::
endif::[]
Reference documentation that covers the Web interface to {productname} ({webui}).

ifdef::env-github,backend-html5[]
<<book_mgr_best_practices.adoc#book.suma.best.practices, Best Practices>>::
endif::[]
ifndef::env-github,backend-html5[]
<<book.suma.best.practices>>::
endif::[]
Best practices on selected topics.

ifdef::env-github,backend-html5[]
<<book_suma_advanced_topics.adoc#book.suma.advanced.topics, Advanced Topics>>::
endif::[]
ifndef::env-github,backend-html5[]
<<book.suma.advanced.topics>>::
endif::[]
A collection of advanced topics not covered under the Best Practices Guide.

// Add docmentation develop link once dev docs are up on gh-pages. Latest docs will always be develop.
HTML versions of the product manuals can be found in the installed system under [path]``/usr/share/doc/manual``.
Find the latest documentation updates at http://www.suse.com/documentation/suse-manager/[Latest Docmentation,window="_blank"] where you can download PDF or HTML versions of the manuals for your product.

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]
