[[quickstart.chapt.overview.requirements]]
= Introduction
:zseries: z Systems
:ppc: POWER
:ppc64le: IBM Power PC
:ipf : Itanium
:x86: x86
:x86_64: x86_64
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
:productname: Uyuni SUSE Manager
:susemgr: SUSE Manager
:productname: Uyuni Uyuni
:susemgrproxy: {productname} Proxy
:productnumber: 3.2
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
:doctype: book
:sectnums:
:sectlinks:
:icons: font
:experimental:

Testing 3

This Getting Started Guide provides guidance on setting up {productname} server with KVM.
You will learn the fundamentals of managing both traditional and Salt clients.

This guide is intended for system administrators.


include::_common-documents/common_version_info.adoc[leveloffset=1]


[[quickstart.sect.introduction]]
== Introduction to {productname}

{productname} is a solution for organizations that require absolute control over maintenance and package deployment on their servers.
It lets you manage large sets of Linux systems and keep them up to date, with automated software management, asset management, and system provisioning.
{productname} allows you to maintain a high level of security while effectively managing system life-cycle requirements.

{productname} uses _Salt_ to provide event-driven configuration and management control.
The Salt-master orchestrates thousands of Salt-minions ({productname} Clients) using remote execution.

{productname} is fully compatible with Red Hat Satellite Server and offers seamless management of both {sle} and {rhel} client systems.

{productname} can be integrated with your network infrastructure in multiple ways.
This book will guide you through an initial proof-of-concept setup, using these steps:

. Install an operating system (either JeOS or {slsa}) for use with {productname}
. Install {productname} Server
. Register {productname} with {scc}
. Perform initial setup of your {productname} Server
. Register a traditional client
. Register a Salt minion



[[quickstart.sect.prereq]]
== Prerequisites for Installation

Before you begin your installation, ensure you have fulfilled these prerequisites:

* Current {scc} organization credentials
* Access to installation media for your chosen operating system
* Your environment meets the hardware and networking requirements
* You understand the supported client operating systems


This section contains more information on each of these prerequisites.

[NOTE]
====
{productname} {productnumber} is based on {slsa} {sles-version} {sp-version} as the host operating system.
====


[[quickstart.sect.prereq.scc]]
=== Obtaining your SUSE Customer Center Credentials

You will need to create an account with {scc} before you install {sls} and {productname}.
To obtain your {scc} credentials:

[[creating.scc.account.mgr]]
.Procedure: Obtaining Your SCC Organization Credentials
. Open a browser and direct it to https://scc.suse.com/login.
. If you have not done so, create an account now.
. Log in to your new SCC account.
. Under the btn:[Management tools] widget select btn:[Manage Users].
. Click the btn:[Organization Credentials] tab.
. Record your login information for use during {productname} setup.



[[quickstart.sect.prereq.installmedia]]
=== Obtaining Installation Media

This book describes installation methods for both {jeos} and {sls}.
The {jeos} image provides the quickest installation and setup, and is suitable for a test or proof of concept installation.
Alternatively, {sls} provides a more robust installation, which requires a larger initial download.
Choose your preferred operating system based on the type of environment you want to install, and the amount of bandwidth and time you have available.

You can find installation images for {jeos} and {slsa} in your {scc} account.
Log in, then navigate to the URL for your chosen operating system:

* https://www.suse.com/products/server/jeos/[JeOS - Media Download]
* https://www.suse.com/products/server/download/[SUSE Linux Enterprise Server - Media Download]



[[quickstart.sect.prereq.hardware]]
=== Hardware Requirements

This table outlines hardware and software requirements on {x86_64} and {ppc64le} architecture.
For installation on {zseries}, see:

ifdef::env-github,backend-html5[]
* <<advanced_topics_suma3_zsystems.adoc#at-zsystems, {productname} and {zseries}>>
endif::[]
ifndef::env-github[]
* <<art.suma.install.zsystems>>
endif::[]

[cols="1,1", options="header"]
.Hardware Requirements for {x86_64} Architecture
|===
| Hardware                 | Recommended
| CPU                      | Multi-core 64-bit CPU
| RAM:                     | _Test Server_ Minimum 8{nbsp}GB
|                          | _Base Installation_ Minimum 16{nbsp}GB
|                          | _Production Server_ Minimum 32{nbsp}GB
| Disk Space:              | [path]``/`` _(root) The default JeOS root partition size of 24 GB is sufficient for this guide_
|                          | [path]``/var/lib/pgsql`` Minimum 50{nbsp}GB
|                          | [path]``/var/spacewalk`` Minimum 50{nbsp}GB per SUSE product and 250{nbsp}GB per Red Hat product
|===

[cols="1,1", options="header"]
.Hardware Requirements for IBM POWER8 or POWER9 Architecture
|===
| Hardware                 | Recommended
| CPU                      | Minimum 4 dedicated cores
| RAM:                     | _Test Server_ Minimum 8{nbsp}GB
|                          | _Base Installation_ Minimum 16{nbsp}GB
|                          | _Production Server_ Minimum 32{nbsp}GB
| Disk Space:              | [path]``/`` Minimum 100{nbsp}GB
|                          | [path]``/var/lib/pgsql`` Minimum 50{nbsp}GB
|                          | [path]``/var/spacewalk`` Minimum 50{nbsp}GB per SUSE product and 250{nbsp}GB per Red Hat product
|===



[[quickstart.sect.prereq.network]]
=== Network Requirements

This section details the networking and port requirements for {productname}.


Fully Qualified Domain Name (FQDN):: The {productname} server must resolve its FQDN correctly or cookies will not work properly on the WebUI.
For more information about configuring the hostname and DNS, see https://www.suse.com/documentation/sles-12/book_sle_admin/data/sec_basicnet_yast.html#sec_basicnet_yast_change_host[SUSE Linux Enterprise Server Documentation - Configuring Host Name and DNS]

Hostname and IP Address:: To ensure that the {productname} domain name can be resolved by its clients, both server and client machines must be connected to a working DNS server.
For more information about setting up a DNS server, see https://www.suse.com/documentation/sles-12/book_sle_admin/data/cha_dns.html[SUSE Linux Enterprise Server Documentation - The Domain Name System]

Using a Proxy When Installing from {sle} Media:: If you are on an internal network and do not have access to {scc}, you can set up and use a proxy during installation.
For more information about configuring a proxy for access to {scc} during a {sle} installation, see https://www.suse.com/documentation/sled-12/singlehtml/book_sle_deployment/book_sle_deployment.html#sec.i.yast2.start.parameters.proxy[SUSE Linux Enterprise Server Documentation -  Using a Proxy During Installation]


.Naming Your Server
[IMPORTANT]
====
The hostname of {productname} must not contain uppercase letters as this may cause _jabberd_ to fail.
Choose the hostname of your {productname} server carefully.
Although changing the server name is possible, it is a complex process and unsupported.
====


In a production environment, {productname} server and its clients should always use a firewall.
This table gives an overview of required ports, to be used when you are setting up your firewall rules.


[[tab.install.ports.server1]]
.Required Server Ports
[cols="1,1,1", options="header"]
|===
| Port | Protocol | Description
| 22   | TCP      | SSH
| 67   | UDP      | DHCP
| 69   | UDP      | TFTP, used to support PXE services
| 80   | TCP      | HTTP, used in some bootstrap cases
| 123  | UDP      | NTP time service
| 443  | TCP      | HTTPS, used for {webui}, client, Proxy server, and API traffic
| 4505 | TCP      | Salt, used by the Salt-master to accept communication requests from minions
| 4506 | TCP      | Salt, used by the Salt-master to accept communication requests from minions
| 5222 | TCP      | XMPP client, used for communications with the [systemitem]``osad`` daemon on traditional client systems
| 5269 | TCP      | XMPP server, used for pushing actions to {susemgrproxy}
|===

For more information on disconnected setup and port configuration, see:

ifndef::env-github[]
* <<disconnect-setup>>
endif::[]
ifdef::env-github[]
* <<bp_chap_choosing_dist_scheme.adoc#bp-dist-scheme, Disconnected Setup>>
endif::[]

ifdef::env-github[]
* <<advanced_topics_ports.adoc#at-ports, Firewall Ports>>
endif::[]
ifndef::env-github[]
* <<advanced.topics.app.ports.server>>
endif::[]


[[quickstart.sect.prereq.clientos]]
=== Supported Client Systems

Supported operating systems for traditional and Salt clients are listed in this table.

[[mgr.supported.clients]]
[cols="1,1,1,1", options="header"]
.Supported Client Systems
|===
| Operating Systems                                    | Architecture                                 | Traditional Clients | Salt Clients
| {sle} 11 SP4                                         | {x86}, {x86}_64, {ipf}, IBM {ppc}, {zseries} | Supported           | Supported
| {sle} 12 SP3                                         | {x86}_64, IBM {ppc} ({ppc64le}), {zseries}, ARM | Supported         | Supported
| {sle} 15                                             | {x86}_64, IBM {ppc} ({ppc64le}), {zseries}, ARM | Supported         | Supported
|_Latest minor release {rhnminrelease6}_               | {x86}, {x86}_64                              | Supported           | Supported
|_Latest minor release {rhnminrelease7}_               | {x86}_64                                     | Supported           | Supported
| Open Enterprise Server 2015, 2015 SP1, 2018          | {x86}_64                                     | Supported           | Supported
|===


.Supported Versions and SP Levels
[NOTE]
====
Client operating system versions and SP levels must be under general support (normal or LTSS) to be supported with {productname}.
For details on supported product versions, see https://www.suse.com/lifecycle.
====
