[[installation-client-requirements]]
= Supported Client Systems

Supported operating systems for traditional and Salt clients are listed in this table.

In this table, {check} indicates that clients running the operating system are supported by {suse}, and {cross} indicates that it is not supported.
Fields marked as {question} are under consideration, and may or may not be supported at a later date.

[NOTE]
====
For {suse} operating systems, the version and SP level must be under general support (normal or LTSS) to be supported with {productname}.
For details on supported product versions, see https://www.suse.com/lifecycle.
For non-{suse} operating systems, including {rhel}, {centos}, and {oracle}, only the latest available version is under general support.
====



[[mgr.supported.clients]]
[cols="1,1,1,1", options="header"]
.Supported Client Systems
|===

| Operating System
| Architecture
| Traditional Clients
| Salt Clients

| {sle} 15
| {x86_64}, {ppc64le}, {ibmz}, ARM
| {check}
| {check}

| {sle} 12
| {x86_64}, {ppc64le}, {ibmz}, ARM
| {check}
| {check}

| {sle} 11
| {x86}, {x86_64}, {ppc64}, {ibmz}
| {check}
| {check}

| {sles}-ES 8
| {x86_64}
| {check}
| {check}

| {sles}-ES 7
| {x86_64}
| {check}
| {check}

| {sles} for SAP
| {x86_64}, {ppc64le}
| {check}
| {check}

| {rhel} 8
| {x86_64}
| {cross}
| {check}

| {rhel} 7
| {x86_64}
| {check}
| {check}

| CentOS 8
| {x86_64}
| {cross}
| {check}

| CentOS 7
| {x86_64}
| {check}
| {check}

| {oracle}{nbsp}8
| {x86_64}
| {cross}
| {check}

| {oracle}{nbsp}7
| {x86_64}
| {check}
| {check}

| {opensuse} Leap 15
| {x86_64}
| {cross}
| {check}

| {ubuntu} 20.04
| {x86_64}
| {cross}
| {check}

| {ubuntu} 18.04
| {x86_64}
| {cross}
| {check}

|===

[NOTE]
====
{rhel} 6, {oracle} 6, CentOS 6, {sles}-ES 6, and {ubuntu} 16.04 are end-of-life upstream and no longer supported by {suse} as client operating systems. SUSE Manager Client Tools for these operating systems are still provided from SCC for convenience.
====

When you are setting up your client hardware, you need to ensure you have enough for the operating system and for the workload you want to perform on the client, with these additions for {productname}:


[[clients.hw.reqs]]
[cols="1,1", options="header"]
.Client Additional Hardware Requirements
|===
| Hardware               | Additional Size Required
| RAM                    | 512{nbsp}MB
| Disk Space:            | 200{nbsp}MB
|===
