[[install-hardware-requirements]]
= Hardware Requirements

This table outlines hardware and software requirements for the {productname} Server and Proxy, on {x86_64} and {ppc64le} architecture.

For {ibmz} hardware requirements, see xref:installation:install-ibmz.adoc[].

For {smr} hardware requirements, see xref:retail:retail-requirements.adoc[].



== Server Hardware Requirements

[cols="1,1,1", options="header"]
.Server Hardware Requirements for {x86_64} Architecture
|===

| Hardware
| Details
| Recommendation

| CPU
| -
| Minimum 4 dedicated 64-bit CPU cores

| RAM
| Test Server
| Minimum 8{nbsp}GB

|
| Base Installation
| Minimum 16{nbsp}GB

|
| Production Server
| Minimum 32{nbsp}GB

| Disk Space
| [path]``/`` (root directory)
| Minimum 24{nbsp}GB

|
| [path]``/var/lib/pgsql``
| Minimum 50{nbsp}GB

|
| [path]``/var/spacewalk``
| Minimum 50{nbsp}GB per {suse} product and 360{nbsp}GB per Red Hat product

|
| [path]``/var/cache``
| Minimum 10{nbsp}GB.
Add 100{nbsp}MB per {suse} product, 1{nbsp}GB per Red Hat or other product.
Double the space if the server is an ISS Master.

|
| Swap space
| 3{nbsp}GB

|===

[cols="1,1,1", options="header"]
.Server Hardware Requirements for IBM POWER8 or POWER9 Architecture
|===

| Hardware
| Details
| Recommendation

| CPU
|
| Minimum 4 dedicated cores

| RAM
| Test Server
| Minimum 8{nbsp}GB

|
| Base Installation
| Minimum 16{nbsp}GB

|
| Production Server
| Minimum 32{nbsp}GB

| Disk Space
| [path]``/`` (root directory)
| Minimum 100{nbsp}GB

|
| [path]``/var/lib/pgsql``
| Minimum 50{nbsp}GB

|
| [path]``/var/spacewalk``
| Minimum 50{nbsp}GB per SUSE product and 360{nbsp}GB per Red Hat product

|
| [path]``/var/cache``
| Minimum 10{nbsp}GB.
Add 100{nbsp}MB per {suse} product, 1{nbsp}GB per Red Hat or other product.
Double the space if the server is an ISS Master.

|
| Swap space
| 3{nbsp}GB

|===



== Proxy Hardware Requirements

[cols="1,1,1", options="header"]
.Proxy Hardware Requirements
|===

| Hardware
| Details
| Recommendation

| CPU
|
| Minimum 2 dedicated 64-bit CPU cores

| RAM
| Test Server
| Minimum 2{nbsp}GB

|
| Production Server
| Minimum 8{nbsp}GB

| Disk Space
| [path]``/`` (root directory)
| Minimum 24{nbsp}GB

|
| [path]``/srv``
| Minimum 100{nbsp}GB

|
| [path]``/var/cache`` (Squid)
| Minimum 100{nbsp}GB

|===


{productname} Server stores packages in the [path]``/var/spacewalk/`` directory.
Repository synchronization fails if this directory runs out of disk space.
You can estimate how much space the [path]``/var/spacewalk/`` directory requires based on the number and type of clients and repositories you plan to mirror.

{productname} Proxy caches packages in the [path]``/var/cache/`` directory.
If there is not enough space available in [path]``/var/cache/``, the proxy will remove old, unused packages and replace them with newer packages.

As a result of this behavior:

* The larger [path]``/var/cache/`` directory is on the {productname} Proxy, the less traffic there will be between it and the {productname} Server.
* By making the [path]``/var/cache/`` directory on the {productname} Proxy the same size as [path]``/var/spacewalk/`` in the {productname} Server, you avoid a large amount of traffic after the first synchronization.
* The [path]``/var/cache/`` directory can be small on the {productname} Server compared to {productname} Proxy. See estimation hints in the Server Hardware Requirements section.
