[[install-uyuni]]
= Install Uyuni Server with openSUSE

{productname} Server can be installed on openSUSE.

For requirements, see xref:installation:uyuni-install-requirements.adoc[].



== Install Uyuni on openSUSE Leap 15.1

.Procedure: Installing openSUSE Leap 15.1 with Uyuni

. As the base system, install openSUSE Leap 15.1 with all available package updates applied.

. Configure a resolvable fully quallified domain name (FQDN) with menu:yast[System > Netwok Settings > Hostname/DNS].

. Add the repository for installing the {productname} Server software as [systemitem]``root``:
+

// variable assignment to avoid overlong lines
+
----
repo=repositories/systemsmanagement:/
repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-4.0-POOL-x86_64-Media1/
zypper ar https://download.opensuse.org/$repo uyuni-server-stable
----

. Refresh metadata from the repositories as [systemitem]``root``:
+

----
zypper ref
----

. Install the pattern for the {productname} Server as [systemitem]``root``:
+

----
zypper in patterns-uyuni_server
----

. Reboot.

* For more information about the stable version of {productname}, see https://www.uyuni-project.org/pages/stable-version.html.
* For more information about the development version of {productname}, see https://www.uyuni-project.org/pages/devel-version.html.

When this installation is complete, you can continue with {productname} setup.
For more information, see xref:installation:uyuni-server-setup.adoc[].
