[[install-proxy-uyuni]]
= Install {productname} Proxy with {opensuse}

{productname} Proxy can be installed on {opensuse}.



== Install {productname} Proxy on {opensuse} Leap 15.1

.Procedure: Installing {opensuse} Leap 15.1 with Uyuni

. As the base system, install {opensuse} Leap 15.1 with all available package updates applied.

. Configure a resolvable fully quallified domain name (FQDN) with menu:yast[System > Netwok Settings > Hostname/DNS].

. Add the repository for installing the {productname} Proxy software as [systemitem]``root``:
+

// variable assignment to avoid overlong lines
// https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Proxy-4.0-POOL-x86_64-Media1/
+
----
repo=repositories/systemsmanagement:/
repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Proxy-4.0-POOL-x86_64-Media1/
zypper ar https://download.opensuse.org/$repo uyuni-proxy-stable
----

. Refresh metadata from the repositories as [systemitem]``root``:
+

----
zypper ref
----

. Install the pattern for the {productname} Server as [systemitem]``root``:
+

----
zypper in patterns-uyuni_proxy
----

. Reboot.

* For more information about the stable version of {productname}, see https://www.uyuni-project.org/pages/stable-version.html.
* For more information about the development version of {productname}, see https://www.uyuni-project.org/pages/devel-version.html.

When this installation is complete, you can continue with {productname} setup.
For more information, see xref:installation:uyuni-proxy-registration.adoc[].
