[[installation-intro]]
= Introduction
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]

// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]



{productname} is a solution for organizations that require absolute control over maintenance and package deployment on their servers.
It lets you manage large sets of Linux systems and keep them up to date, with automated software management, asset management, and system provisioning.
{productname} allows you to maintain a high level of security while effectively managing system life-cycle requirements.

{productname} uses _Salt_ to provide event-driven configuration and management control.
The Salt-master orchestrates thousands of Salt-minions ({productname} Clients) using remote execution.

{productname} is fully compatible with Red Hat Satellite Server and offers seamless management of both {sle} and {rhel} client systems.

{productname} can be integrated with your network infrastructure in multiple ways.
This book will guide you through an initial proof-of-concept setup, using these steps:

. Install an operating system (either JeOS or {slsa}) for use with {productname}
. Install {productname} Server
. Register {productname} with {scc}
. Perform initial setup of your {productname} Server
. Register a traditional client
. Register a Salt minion

The book also contains a section about getting started with Salt.
