[[webui-setup]]
= Web Interface Setup

// Move the Navigation chapter from the Ref Guide into this document. LKB 2020-02-20

To use the {productname} {webui}, navigate to your {productname} URL in a browser.
Sign in to the {webui} using your {productname} Administration account.

While you are using the {webui}, click the icon:question-circle[role="blue"] icon to access the documentation for that section.

The first time you sign in to the {webui}, complete the setup wizard to set your user preferences.
You can access the setup wizard at any time by navigating to menu:Admin[Setup Wizard].

After the initial setup is complete, signing in will take you the menu:Home[Overview] section.
This section contains summary panes that provide important information about your systems.

The [guimenu]``Tasks`` pane provides shortcuts to the most common {webui} tasks.

The [guimenu]``Inactive Systems`` pane shows any clients that have stopped checking in to the {productname} Server.
You will need to check these clients.

The [guimenu]``Most Critical Systems`` pane shows any clients that require software updates.
Click the name of a client in the list to be taken to the menu:Systems[System Details] section for that client.
From this page, you can apply any required updates.

The [guimenu]``Recently Scheduled Actions`` pane shows all recent actions that have been run, and their status.
Click the label of an action to see more detail.

The [guimenu]``Relevant Security Patches`` pane shows all available security patches that need to be applied to your clients.
It is critical that you apply security patches as soon as possible to keep your clients secure.

The [guimenu]``System Groups`` pane shows any system groups you have created, and if the clients in those groups are fully updated.

The [guimenu]``Recently Registered Systems`` pane shows all clients registered in the past thirty days.
Click the name of a client in the list to be taken to the menu:Systems[System Details] section for that client.
