[[ref-admin-wizard]]
= 설치 마법사
:revdate: 2025-01-20
:page-revdate: {revdate}

The menu:Admin[Setup Wizard] section helps you configure {productname}. It is the default page when you use the {productname} {webui} for the first time.

[[setup-wizard-options]]
.Setup Wizard Options
[cols="1,1", options="header"]
|===
| Option             | Description
| HTTP Proxy         | Configure an HTTP proxy connection.
| Organization Credentials   | Configure an organization for accessing {scclongform}.
| Products      | View product entitlements and subscribe to product channels.
|===

== Configure the HTTP Proxy


{productname} can connect to the {scclongform} (SCC) or other remote servers using a proxy. Navigate to the [guimenu]``HTTP Proxy`` tab to configure the proxy.

You will need to provide the hostname of the proxy. Use the syntax ``<hostname>:<port>``. For example: ``example.com:8080``.

You can disable use of the proxy by clearing the fields.

[IMPORTANT]
====
When choosing a username or password for your {productname} Proxy, ensure it does not contain an ``@`` or ``:`` character. These characters are reserved.
====

== Configure Organization Credentials

Your {scclongform} account is associated with the administration account of your organization. You can share your {scclongform} access with other users within your organization. Navigate to the [guimenu]``Organization Credentials`` tab to grant users within your organization access to your {scclongform} account.

Click btn:[Add a new credential], enter the username and password of the user to grant access to, and click btn:[Save]. A new credential card is shown for the user you have granted access to. Use these buttons on the card to edit or revoke access:

* Check credential validation status (green tick or red cross icon).
    SCC로 인증서를 다시 확인하려면 아이콘을 클릭합니다.
* 서버 간 동기화를 위한 기본 인증서를 설정합니다(노란색 별 모양 아이콘).
* 특정 인증서에 연결된 서브스크립션이 나열됩니다(목록 아이콘).
* 인증서를 편집합니다(연필 아이콘).
* Delete the credential (trash can icon).



== Configure Products

Your {suse} subscription entitles you to access a range of products. Navigate to the [guimenu]``Products`` tab to browse the products available to you and synchronize {productname} with {scclongform}.

Filters help you search for products by description or architecture.

The list is organized by product name showing products on top which have a subscription. Freely available products appear at the end of the list. For each product, you can see the architecture it can be used on. Click the arrow next to the product name to see associated channels and extensions. Click the btn:[Channels] icon to see the complete list of channels associated with each product.

For products based on {sle}{nbsp}15 and above, you can choose to only synchronize required packages, or to also include recommended products. Toggle the btn:[include recommended] switch on to synchronize all products, and toggle the switch off to synchronize only required products.

You can further refine which products you want to synchronize by selecting or deselecting individual product.

When you have completed your selection, click btn:[Add products], and click btn:[Refresh] to schedule the synchronization.

Synchronization progress for each product is shown in a progress bar next to the product name. Depending on the products you have chosen, synchronization can take up to several hours. New products will be available for you to use in {productname} when synchronization is complete.

If your synchronization fails, it could be because of a third party GPG key or your company firewall blocking access to the download server. Please check the notification details for the error. For more information about troubleshooting product synchronization, see xref:administration:troubleshooting/tshoot-sync.adoc[].


