[[retail-install-uyuni]]
= Install Uyuni Retail Server with openSUSE

{productname} {smr} Server can be installed on openSUSE.

For general requirements, see xref:installation:uyuni-install-requirements.adoc[].

[NOTE]
====
有关 openSUSE Leap 最新版本和更新的详细信息，请参见 https://doc.opensuse.org/release-notes/。
====



== 在 openSUSE Leap 上安装 Uyuni

You install Uyuni as an add-on to openSUSE Leap.



.Procedure: Installing Uyuni on openSUSE Leap

. 安装应用了所有可用服务包和软件包更新的 openSUSE Leap 作为基础系统。
. 通过 menu:yast[系统 > 网络设置 > 主机名/DNS] 配置一个可解析的完全限定域名 (FQDN)。
. 设置用于创建储存库的变量：
+
----
repo=repositories/systemsmanagement:/
repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
----
. 以 [systemitem]``root`` 身份添加用于安装 {productname} Server 软件的储存库：
+
----
zypper ar https://download.opensuse.org/$repo uyuni-server-stable
----
. Refresh metadata from the repositories as [systemitem]``root``, and confirm the import of new GPG key into the keyring:
+
----
zypper ref
----
. 以 [systemitem]``root`` 身份安装 {productname} Server 的模式：
+
----
zypper in patterns-uyuni_server
----
. Install the {productname} related packages:
+
----
zypper in bind-formula \
	  branch-network-formula \
	  dhcpd-formula \
	  image-sync-formula \
	  pxe-formula \
	  saltboot-formula \
	  susemanager-retail-tools \
	  tftpd-formula \
	  vsftpd-formula

----
. Reboot the client.


When the installation is complete, you can continue with {productname} setup. For more information, see xref:retail:retail-uyuni-server-setup.adoc[].
