[[lsd-hub-auth]]
= Hub Authentication Modes

Hub supports three different authentication modes:

* Manual mode (default): API credentials must be explicitly provided for each server.
* Relay mode: the credentials used to authenticate with the Hub are also used to authenticate to each server.
You must provide a list of servers to connect to.
* Auto-connect mode: Credentials are reused for each server, and any server you have access to is automatically connected.



== Authentication Examples

This section provides examples of each authentication method.



.Example: Manual Authentication


In manual mode, credentials have to be explicitly provided for each {productname} Server before you can connect to it.

A typical workflow for manual authentication is:

. Credentials for the Hub are passed to the ``login`` method, and a session key for the Hub is returned (``hubKey``).
. The server IDs are obtained using the session key, and all the peripheral servers are attached to the Hub using the ``hub.listServerIds`` method.
. Credentials for each peripheral server are provided to the ``attachToServers`` method.
This performs authentications against each server's XMLRPC API endpoint.
. A ``multicast`` call is performed on a set of servers.
This is defined by ``serverIds``, which contains the IDs of the servers to target.
In the background, ``system.list_system`` is called on each server's XMLRPC API
. Hub aggregates the results and returns the response in the form of a ``map``.
The map has two entries:
+
* ``Successful``: list of responses for those clients where the call succeeded.
* ``Failed``: list of responses for those clients where the call failed.

[NOTE]
====
If you want to call a method on just one {productname} Server, then Hub API also provides a ``unicast`` namespace.
In this case, the response will be a single value and not a map, in the same way as if you called that {productname} server's API directly.
====


.Example Python Script for Manual Authentication:

----
#!/usr/bin/python
import xmlrpclib

HUB_URL = "http://localhost:8888/hub/rpc/api"
HUB_LOGIN = "admin"
HUB_PASSWORD = "admin"

client = xmlrpclib.Server(HUB_URL, verbose=0)

hubKey = client.hub.login(HUB_LOGIN, HUB_PASSWORD)

#Get the server Ids
serverIds = client.hub.listServerIds(hubKey)

# authenticate those servers(each server with it's own credentials)
usernames = ["admin" for s in serverIds]
passwords = ["admin" for s in serverIds]
client.hub.attachToServers(hubKey, serverIds, usernames, passwords)

# perform the needed operation
systemsPerServer = client.multicast.system.list_systems(hubKey, serverIds)
successfulResponses = systemsPerServer["Successful"]["Responses"]
failedResponses = systemsPerServer["Failed"]["Responses"]

for system in successfulResponses:
  print (system)

#logout
client.auth.logout(hubKey)
----



.Example: Relay Authentication


The Relay authentication mode is a convenient method where the same credentials used to login into the Hub API are used to login into the APIs of the peripheral Servers the user wants to work with. It is thus assumed that the credentials are valid in each Server and correspond to a user with appropriate permissions.
After login, it is still necessary to to call `attachToServers` method to define the subset of Servers that will be targeted in subsequent calls.

In the following example:

* Credentials for the hub are passed to the `loginWithAuthRelayMode` method, a session key for the HUB API is returned (`hubKey`)
* Using the session key from the previous step, {productname} Server IDs are obtained for all the peripheral servers attached to the Hub via the `hub.listServerIds` method
* Call to `attachToServers` is made, same credentials as used for logging into hub will be further passed against each of the Servers' XMLRPC API endpoints for authentication
* A `multicast` call is performed on a set of Servers(`serverIds` contains all IDs of the servers to target). Behind the scenes, `system.list_system` is called on each {productname} server's XMLRPC API
* Hub will aggregate the results and return the response in form of a `map`. This map has two entries:
- `Successful`: contains a list of responses for those clients where the call was successful.
- `Failed`: contains a list of responses for those clients where the call failed.

[NOTE]
====
If you want to call a method on just one {productname} Server, then Hub API also provides a more convenient `unicast` namespace. In this case, the response will be a single value and not a map, just as if the user called that {productname} server's API directly.
====

* User logs out



[source,python]
----
#!/usr/bin/python
import xmlrpclib


HUB_URL = "http://localhost:8888/hub/rpc/api"
HUB_LOGIN = "admin"
HUB_PASSWORD = "admin"

client = xmlrpclib.Server(HUB_URL, verbose=0)

hubKey = client.hub.loginWithAuthRelayMode(HUB_LOGIN, HUB_PASSWORD)

#Get the server Ids
serverIds = client.hub.listServerIds(hubKey)

#authenticate those servers(same credentials will be used as of hub to authenticate)
client.hub.attachToServers(hubKey, serverIds)

# perform the needed operation
systemsPerServer = client.multicast.system.list_systems(hubKey, serverIds)
successfulResponses = systemsPerServer["Successful"]["Responses"]
failedResponses = systemsPerServer["Failed"]["Responses"]

for system in successfulResponses:
  print (system)

#logout
client.auth.logout(hubKey)
----



.Example: Auto-Connect Authentication


The autoconnect mode is a convenience mechanism that, similarly to the relay mode, uses the same credentials to perform a login into the Hub and peripheral Server APIs.
Differently from relay mode, there is no need to use the `attachToServers` method, as it is assumed the user wants to connect to all peripheral Servers under his control, and the Hub XMLRPC API will in fact log in to them all at Hub login time.

In the following example:

* Credentials for the hub are passed to the `loginWithAutoconnectMode` method, a session key for the HUB API is returned (`hubKey`)
* A `multicast` call is performed on a set of Servers(`serverIds` contains all IDs of the servers to target). Behind the scenes, `system.list_system` is called on each {productname} server's XMLRPC API
* Hub will aggregate the results and return the response in form of a `map`. This map has two entries:
- `Successful`: contains a list of responses for those clients where the call was successful.
- `Failed`: contains a list of responses for those clients where the call failed.

[NOTE]
====
If you want to call a method on just one {productname} Server, then Hub API also provides a more convenient `unicast` namespace. In this case, the response will be a single value and not a map, just as if the user called that {productname} server's API directly.
====

* User logs out


[source,python]
----
#!/usr/bin/python
import xmlrpclib


HUB_URL = "http://localhost:8888/hub/rpc/api"
HUB_LOGIN = "admin"
HUB_PASSWORD = "admin"

client = xmlrpclib.Server(HUB_URL, verbose=0)

hubKey = client.hub.loginWithAutoconnectMode(HUB_LOGIN, HUB_PASSWORD)

#Get the server Ids
serverIds = client.hub.listServerIds(hubKey)

# perform the needed operation
systemsPerServer = client.multicast.system.list_systems(hubKey, serverIds)
successfulResponses = systemsPerServer["Successful"]["Responses"]
failedResponses = systemsPerServer["Failed"]["Responses"]

for system in successfulResponses:
  print (system)

#logout
client.auth.logout(hubKey)
----