[[lsd-hub-namespaces]]
= Hub Namespaces

Hub supports 3 different namespaces.

[[name-spaces]]
[cols="1,1,1", options="header"]
.Namespaces
|===
| Name      | Description  | Example
| hub       | to target the Hub itself. | `client.hub.login(login, password)`
| unicast   | to target a single Server registered in the Hub | `client.unicast.system.list_systems(hubKey, serverId)`
| multicast | to target multiple Servers | `client.multicast.system.list_systems(hubKey, [serverId1, serverId2], [], [])`
|===

* all XMLRPC API methods available in a single Server are exposed by the namespaces above.
Generally speaking, they accept the same parameters and return the same values with the exceptions described below.
* the `hubKey` can be obtained via 3 different login methods.
For more detail, see authentication modes.
* individual Server IDs can be obtained via `client.hub.listServerIds(hubKey)` (see examples section)
* the `unicast` namespace assumes all methods receive hubKey and serverId as their first two parameters, then any other parameter as specified by the regular Server API.
* the `multicast` namespace assumes all methods receive hubKey, a list of Server IDs, then lists of per-Server parameters as specified by the regular Server API.
Return value will be an array, indexed per Server, of the results of individual Server calls.