[[lsd-hub-install]]
= Hub Installation

Before you begin, you need to install the ``hub-xmlrpc-api`` package, and configure the Hub Server to use the API.



.Procedure: Installing and Configuring the Hub XMLRPC API
. On the Hub Server, or on a host that has access to all peripheral servers' XMLRPC APIs, install the ``hub-xmlrpc-api`` package.
The package is available in the {productname} {productnumber} repositories.
. OPTIONAL: the Hub XMLRPC API service does not start on installation. You can set it up to start automatically with systemd, by executing the following commands
---
sudo systemctl enable hub-xmlrpc-api.service
sudo systemctl start hub-xmlrpc-api.service
---
. OPTIONAL: Check that these parameters in the [path]``/etc/hub/hub.conf`` configuration file are correct:
*  ``HUB_API_URL``: URL to the Hub Server XMLRPC API endpoint. 
Use the default value if you are installing `hub-xmlrpc-api` on the Hub Server.
* ``HUB_CONNECT_TIMEOUT``: the maximum number of seconds to wait for a response when connecting to a Server. 
Use the default value in most cases.
* ``HUB_REQUEST_TIMEOUT``: the maximum number of seconds to wait for a response when calling a Server method. 
Use the default value in most cases.
* ``HUB_CONNECT_USING_SSL``: use HTTPS instead of HTTP for communicating with peripheral Servers. 
Recommended for a secure environment.

[NOTE]
====
In order to use https to connect to peripheral Servers, in addition to setting ``HUB_CONNECT_USING_SSL`` flag to true, SSL certificates for all the peripheral Servers need to be installed on the machine where the hub-xmlrpc-api service runs. This can be achieved by copying the ``RHN-ORG-TRUSTED-SSL-CERT`` certificate file from each peripheral Server's pub directory (http://<server-url>/pub/) to /etc/pki/trust/anchors/ and then running the ``update-ca-certificates`` command.
====

Restart services to pick up any configuration changes.
