[[lsd-hub-namespaces]]
= Hub Namespaces

Hub supports several different namespaces:

[[name-spaces]]
[cols="1,1,1", options="header"]
.Namespaces
|===
| Name      | Description  | Example
| hub       | Targets the Hub Server | ``client.hub.login(login, password)``
| unicast   | Targets a peripheral server | ``client.unicast.system.list_systems(hubKey, serverId)``
| multicast | Targets multiple servers | ``client.multicast.system.list_systems(hubKey, [<serverId1>, <serverId2>], [], [])``
|===

All XMLRPC API methods available in a single server are exposed by these namespaces.
In most cases, the namespaces accept the same parameters and return the same values, with some exceptions:

* You can obtain ``hubKey`` using different authentication methods.
For more information, see xref:large-deployments:hub-auth.adoc[].
* Individual server IDs can be obtained using ``client.hub.listServerIds(hubKey)``.
* The ``unicast`` namespace assumes all methods receive ``hubKey`` and ``serverId`` as their first two parameters.
All other parameters are received as specified by the server API.
* The ``multicast`` namespace assumes all methods receive ``hubKey``, a list of server IDs, then lists of per-server parameters, as specified by the server API.
The return value of the ``multicast`` namespace is an array, indexed by server, of the results of individual server calls.