[[quickstart-sap-clients]]
= Configure Clients

{productname} uses formulas with forms to configure your SAP clients.
There are two formulas with forms that you need to use: one to configure the HANA database, and one to configure the clients into a cluster.

The formulas are provided by packages that you can download from your package manager.
You need to install the formulas on the {productname} master client.
When you have installed the package, you can use the {productname} {webui} to enable and configure the formulas.
As you go through the formula configuration process, you will be able to provide the details of the clients that contain your SAP cluster, to set them up appropriately.


[IMPORTANT]
====
The order that you enable and configure the formulas is important.
You must enable, configure, and apply the HANA formula first.
Then you can enable, configure, and apply the cluster formula.
If you perform these steps in the wrong order, your SAP installation will fail.
====


To install the SAP formulas, you need the SAP formulas package, which you can download from FIXME.
On the {productname} Server, at the command prompt, as root:

----
zypper addrepo FIXME
zypper ref
----

You can then use your package manager to install the ``saphanabootstrap-formula`` and ``habootstrap-formula`` packages with this command:

----
zypper in saphanabootstrap-formula habootstrap-formula
----

When the installation is complete, restart services:

----
systemctl restart salt-master.service
----



== Enable and Configure the HANA Formula

In the {productname} {webui}, navigate to menu:Systems[System List] and click the client to use as the {productname} master.

Navigate to the [guimenu]``Formulas`` tab and check the ``FIXME`` formula in the list.
Click btn:``Save`` and apply the highstate to save the changes.

When the formula is applied, you can navigate to the menu:Formulas[HANA] tab, and complete the details in the form.
Make sure you ... FIXME

When you have completed all the details, click btn:``Save`` and apply the highstate.
When the highstate is complete, you can go on to apply the cluster formula.



== Enable and Configure the Cluster

In the {productname} {webui}, navigate to menu:Systems[System List] and click the ``FIXME`` client.
This is the FIXME.
Navigate to the [guimenu]``Formulas`` tab and check the ``FIXME`` formula in the list.
Click btn:``Save`` and apply the highstate to save the changes.

When the formula is applied, you can navigate to the menu:Formulas[Cluster] tab, and complete the details in the form.
Make sure you ... FIXME

Make sure that you provide the passwords for all the other clients you want included in the cluster.
Alternatively, you need to ensure that all of the clients can connect to each other directly using SSH.

When you have completed all the details, click btn:``Save`` and apply the highstate.
When the highstate is complete, your SAP cluster is ready to use.
