[[quickstart-sap-server]]
= Prepare Server

Before you start you need to install the {productname} Server.
The method for installing the {productname} Server will vary depending on your hardware and environment.

For more information about installing the {productname} Server, see xref:installation:install-intro.adoc[].



You need access to {sles}{nbsp}15 for SAP installation media.
You will not be able to create an SAP cluster without the {sles} SAP extension, as it provides tooling specific to SAP.



.Procedure: Preparing Installation Media
. On the {productname} Server, create a local directory for the SLE{nbsp}15 for SAP installation media:
+
----
mkdir -p /srv/images/sle15-sap
----
. Download an ISO image with the installation sources, and mount the ISO image on your server:
+
----
mount -o loop DVD1.iso /mnt/
----
. Copy everything from the mounted ISO to your local filesystem:
+
----
cp -r /mnt/* /srv/images/sle15-sap
----
. When the copy is complete, unmount the ISO image:
+
----
umount /mnt
----

[NOTE]
====
This image is the unified installer and can be used for multiple autoinstallation distributions.
====


Configure the {productname} {webui} to make it easier to install and manage your SAP cluster.
When you have administration access to the {webui}, you can prepare bootstrap repositories and activation keys for your clients.

When you select a product for synchronization, the bootstrap repository is automatically created as soon as all mandatory channels are fully mirrored.

// I can't see SAP channels in spacewalk-common-channels. Possibly needs to be created using spacewalk-utils? Custom channels?


On the {productname} Server, add the appropriate SAP channels:
From the {webui}, add [systemitem]``SUSE Linux Enterprise Server 15 for SAP``.

Synchronize the {productname} Server with the {SCC}.
You can do this using the {webui}.
Add the new channel to your activation key.

To check if a channel has finished synchronizing navigate to menu:Admin[Setup Wizard] and select the [guimenu]``Products`` tab.
This dialog displays a completion bar for each product when they are being synchronized.


[NOTE]
====
Software channels can be very large.
The initial channel synchronization can sometimes take up to 24 hours.

When the initial synchronization is complete, we recommended you clone the channel before you work with it.
This gives you a backup of the original synchronization data.
====


Activation keys are used with all clients to ensure that your clients have the correct software entitlements, are connecting to the appropriate channels, and are subscribed to the relevant groups.
Each activation key is bound to an organization, which you can set when you create the key.



.Procedure: Creating an Activation Key
. In the {productname} {webui}, as an administrator, navigate to menu:Systems[Activation Keys].
. Click the btn:[Create Key] button.
. On the [guimenu]``Activation Key Details`` page, in the [guimenu]``Description`` field, enter a name for the activation key.
. In the [guimenu]``Key`` field, enter the distribution and service pack associated with the key.
For example, ``SLES15-SP2`` for {sles}{nbsp}15{nbsp}SP2.
. In the [guimenu]``Base Channels`` drop-down box, select the appropriate base software channel, and allow the relevant child channels to populate.
For more information, see xref:reference:admin/setup-wizard.adoc#vle.webui.admin.wizard.products[] and xref:administration:custom-channels.adoc[].
. Select the child channels you need (for example, the mandatory {susemgr} tools and updates channels).
. We recommend you leave the [guimenu]``Contact Method`` set to [guimenu]``Default``.
. We recommend you leave the [guimenu]``Universal Default`` setting unchecked.
. Click btn:[Create Activation Key] to create the activation key.
. Check the [guimenu]``Configuration File Deployment`` check box to enable configuration management for this key, and click btn:[Update Activation Key] to save this change.

[NOTE]
====
The [guimenu]``Configuration File Deployment`` check box does not appear until after you have created the activation key.
Ensure you go back and check the box if you need to enable configuration management.
====

For more on activation keys, see xref:client-configuration:clients-and-activation-keys.adoc[].
