[[quickstart-sap-setup]]
= Setting Up

Your SAP cluster requires several client systems.
Prepare your clients on physical or virtual hardware, and ensure you have {sles}{nbsp}15 for SAP installation media ready on your {productname} Server.
You will not be able to create an SAP cluster without the {sles} SAP extension, as it provides tooling specific to SAP.

One of the key features of SAP is high availability of the cluster.
Every component within an SAP cluster has redundancy and failover protection.
When you are preparing your clients, ensure you have enough hardware and infrastructure to allow for this.



.Procedure: Registering Clients with the {webui}

. In the {productname} {webui}, navigate to menu:Systems[Bootstrapping].
. In the [guimenu]``Host`` field, type the fully-qualified domain name (FQDN) of the client to be bootstrapped.
. In the [guimenu]``SSH Port`` field, type the SSH port number to use to connect and bootstrap the client.
By default, the SSH  port is [systemitem]``22``.
. In the [guimenu]``User`` field, type the username to log in to the client.
By default, the username is [systemitem]``root``.
. In the [guimenu]``Password`` field, type password to log in to the client.
. In the [guimenu]``Activation Key`` field, select the activation key that is associated with the software channel you want to use to bootstrap the client.
For more information, see xref:client-configuration:clients-and-activation-keys.adoc[].
. OPTIONAL: In the [guimenu]``Proxy`` field, select the proxy to register the client to.
. By default, the [guimenu]``Disable SSH Strict Key Host Checking`` checkbox is selected.
This allows the bootstrap process to automatically accept SSH host keys without requiring you to manually authenticate.
. OPTIONAL: Check the [guimenu]``Manage System Completely via SSH`` checkbox.
If you check this option, the client will be configured to use SSH for its connection to the server, and no other connection method will be configured.
. Click btn:[Bootstrap] to begin registration.

When the bootstrap process has completed, your client will be listed at menu:Systems[System List].


[WARNING]
====
When new packages or updates are installed on the client using {productname}, any end user license agreements (EULAs) are automatically accepted.
To review a package EULA, open the package details page in the {webui}.
====


// Extra client config goes here.
