[[client-upgrades-uyuni]]
= Upgrade Uyuni Clients

. At the command prompt on the {productname} Server, as root, use the [command]``spacewalk-common-channels`` command to add the appropriate channels.
+
----
spacewalk-common-channels \
opensuse_leap15_2 \
opensuse_leap15_2-non-oss \
opensuse_leap15_2-non-oss-updates \
opensuse_leap15_2-updates \
opensuse_leap15_2-uyuni-client
----

. Fully synchronize all channels with [command]``spacewalk-repo-sync``. In case of already defined repository URLs, continue with xref:upgrade:proxy-uyuni.adoc#uyuni-202007-channeldupes[].
+

. In the {productname} Server {webui}, navigate to menu:Software[Manage > Channels] and click the [systemitem]`` Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)`` channel name.

. In the upper right corner, click btn:[Manage Channel].

. Click the [guimenu]``Repositories`` tab, and select [systemitem]``External - Uyuni Client Tools for openSUSE Leap 15.1 (x86_64)``.

. Click btn:[Update Repositories].

. Navigate to menu:Repositories[Sync] subtab, and click btn:[Sync Now].

. Do the same with [systemitem]``openSUSE Leap 15.2 (x86_64)`` and [systemitem]``External - openSUSE Leap 15.1 (x86_64)``.

Unfold [systemitem]``openSUSE Leap 15.2 (x86_64)`` to see all child channels populated with packages.



== Upgrade the Client

To upgrade a client you replace the software repositories and update the software, and finally reboot the client.



.Procedure: Updating the Client


. In the {productname} Server {webui}, navigate to menu:Systems[] and click the name of the client.
. Click menu:Software[Software Channels], and as the base channel select the openSUSE Leap {opensuse-version} channel that is listed in the [systemitem]``Customs Channels`` list.
. In the [guimenu]``Child Channels`` pane, select the {opensuse-version} child channels.
. Click btn:[Next], and [guimenu]``Confirm Software Channel Change`` with btn:[Confirm].
. Click menu:Software[Packages > Upgrade], and select all the packages to be updated on the client, and then apply the selection. Click btn:[Upgrade Packages], check the details, and click btn:[Confirm] to complete the update.
+
+
+
. Reboot the client.

If you need to update many clients, you can create an action chain of this command sequence on the {productname} Server. You can use the action chain to perform updates on multiple clients at the same time.




