[[client-proxy]]
= Register Clients to a Proxy



Proxy servers can act as a broker and package cache for both Salt and traditional clients. Registering clients to a proxy is similar to registering them directly to the {productname} Server, with a few key differences.

These sections contain information on registering Salt clients to a proxy using the {webui}, commands on the command line, or a bootstrap script. There is also information on registering traditional clients using a bootstrap script.


Within the {webui}, proxy pages show information about both Salt and traditional clients. You can see a list of clients that are connected to a proxy by clicking the name of the proxy in menu:Systems[System List > Proxy], then select the [guimenu]``Proxy`` subtab of the [guimenu]``Details`` tab.

A list of chained proxies for a Salt client can be seen by clicking the name of the client in menu:Systems[All], then select the [guimenu]``Connection`` subtab of the [guimenu]``Details`` tab.

If you decide to move any of your clients between proxies or the server you need to repeat the registration process from the beginning.
