= Proxy Migration from 5.1 to 5.2
:revdate: 2026-02-17
:page-revdate: {revdate}

== 概要


This document provides the tested and validated procedures for migrating the **host operating system** and the **proxy extension** in environments managed by **{productname}**, specifically targeting systems deployed with **{productname} Proxy 5.1**.

対象となるアップグレードシナリオは次のとおりです。

* Migrating from **SL Micro 6.1** to **SL Micro 6.2**
* Updating **SLES 15 SP7** with the new **{productname} Proxy Extension {productnumber}**
* Upgrading the **{productname} Proxy Extension** from **version 5.1** to **version {productnumber}**

[IMPORTANT]
====
Before migrating the proxy, it is required to first migrate the {productname} 5.1 Server to {productname} {productnumber}.
====


== {sl-micro} 6.1 to {sl-micro} 6.2

This section provides the tested procedure to upgrade a {sl-micro} 6.1 host deployed with {productname} 5.1 Proxy to {sl-micro} 6.2 with {productname} {productnumber} Proxy.


=== 前提条件

* {productname} 5.1 Proxy is installed and running on {sl-micro} 6.1.
* プロキシシステムが{productname}サーバに登録されている。


=== ディストリビューションのアップグレードとプロキシの移行

.Procedure: Migrate {productname} 5.1 Proxy to {productname} {productnumber} Proxy
[role=procedure]
____

. システムと{productname}ツールのバージョンを確認します。

+

[source, console]
----
cat /etc/os-release
mgrpxy --version
----

+

確認:

* Operating System: [literal]``SL Micro 6.1``
* Tools version: [literal]``mgrpxy version 5.1.x`` or higher

+

. 実行中のコンテナを確認します。

+

[source, console]
----
podman ps
----

+

以下のコンテナが実行されていることを確認します。

- `proxy-squid`
- `proxy-ssh`
- `proxy-httpd`
- `proxy-tftpd`
- `proxy-salt-broker`

+

. {productname}サーバの新しいプロキシ製品を同期します。 詳細については、xref:client-configuration:products.adoc[]を参照してください。

+

Web UIを使用して同期します。

* [literal]``SL Micro 6.2``
* [literal]``{productname} Proxy Extension {productnumber}``

+

. プロキシ製品の移行を実行します。 詳細については、xref:client-configuration:client-upgrades-product-migration.adoc[]を参照してください。

+

プロキシシステムに移動し、menu:システム[概要] > menu:ソフトウェア[製品移行]を選択します。

+

移行元

* [literal]``SL Micro 6.1`` + [literal]``SUSE Multi-Linux Manager Proxy 5.1 Extension``

+

移行先

* [literal]``SL Micro 6.2`` + [literal]``{productname} Proxy Extension {productnumber}``

+

[IMPORTANT]
====
必要であることが確認されていない限り、プロンプトが表示されたときにオプションのチャンネルを**選択しないでください**。
====

+

[NOTE]
====
実際の移行を実行する前に、まず予行演習を実行することをお勧めします。
====

+

. 移行アクションを監視します。

+

{webui}のmenu:システム[詳細 > イベント]タブでプロセスを追跡できます。

+

. After the upgrade completes, stop the proxy container and then reboot the system.

+

[source, console]
----
mgrpxy stop
reboot
----

+

. 再起動後のチェックを実行します。

+

アップグレードされたOSと{productname}拡張機能を確認します。

+

[source, console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

. {productname}ツールのバージョンを確認します。

+

[source, console]
----
mgrpxy --version
----

+

予想される出力:

- `mgrpxy version 5.2.0` or higher

+

. Install the new proxy container images as RPM packages if they are not pulled from the registry.

+

[source, shell]
----
transactional-update pkg install suse-multi-linux-manager-5.2-<arch>-proxy*
----

+

. プロキシを再起動します。

. プロキシコンテナをアップグレードして再起動します。

+

[source, console]
----
mgrpxy upgrade podman
mgrpxy stop
mgrpxy start
----

+

. プロキシコンテナが動作していることを確認します。

+

[source, console]
----
podman ps
----

+

すべての予期されるプロキシコンテナが稼働中である必要があります。

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

____


=== 移行の完了

The proxy host system is now running {sl-micro} 6.2 with updated {productname} {productnumber} Proxy packages and synchronized product channels.


== {sles} 15 SP7

This section provides the procedure to update a {sles} 15 SP7 host deployed with {productname} 5.1 Proxy to {productname} {productnumber} Proxy.


=== 前提条件

* {productname} Proxy 5.1 is installed and running on {sles} 15 SP7.
* プロキシシステムが{productname}サーバに登録されている。


=== Proxy component update

.Procedure: Update {productname} Proxy components on {sles} 15 SP7
[role=procedure]
____

. オペレーティングシステムと{productname}ツールのバージョンを確認します。

+

[source, console]
----
cat /etc/os-release
mgrpxy --version
----

+

確認:

* Operating System: [literal]``SUSE Linux Enterprise Server 15 SP7``
* Tools version: [literal]``mgrpxy version 5.1.x`` or higher


+

. 実行中のプロキシコンテナを一覧表示します。

+

[source, console]
----
podman ps
----

+

以下のコンテナが実行されていることを確認します。

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

+

. Synchronize the new Products in {productname} Server using the Web UI.

+

For more information, see xref:client-configuration:products.adoc[].

+

Synchronize:

* [literal]``{productname} Proxy Extension {productnumber}``

+

. Perform proxy product migration.

+

For more information, see xref:client-configuration:client-upgrades-product-migration.adoc[].

+

プロキシシステムに移動し、menu:システム[概要] > menu:ソフトウェア[製品移行]を選択します。

+

Migrate from:

* [literal]``{sles} 15 SP7`` + [literal]``SUSE Multi-Linux Manager Proxy 5.1 Extension``

+

to:

* [literal]``{sles} 15 SP7`` + [literal]``{productname} Proxy Extension {productnumber}``

+

[IMPORTANT]
====
必要であることが確認されていない限り、プロンプトが表示されたときにオプションのチャンネルを**選択しないでください**。
====

+

[NOTE]
====
実際の移行を実行する前に、まず予行演習を実行することをお勧めします。
====

+

. 移行アクションを監視します。

+

You can follow the process under menu:Systems[Details > Events] in the {webui}.

+

. After the upgrade completes, stop the proxy container and then reboot the system.

+

[source, console]
----
mgrpxy stop
reboot
----

+

. 再起動後のチェックを実行します。

+

Verify the OS and {productname} extension version:

+

[source, console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

. {productname}ツールのバージョンを確認します。

+

[source, console]
----
mgrpxy --version
----

+

予想される出力:

- `mgrpxy version 5.2.0` or higher

+

. Install the new proxy container images as RPM packages if they are not pulled from the registry.

+

[source, shell]
----
zypper install suse-multi-linux-manager-5.2-<arch>-proxy*
----

+

. プロキシを再起動します。

. プロキシコンテナをアップグレードして再起動します。

+

[source, console]
----
mgrpxy upgrade podman
mgrpxy stop
mgrpxy start
----

+

. プロキシコンテナが動作していることを確認します。

+

[source, console]
----
podman ps
----

+

すべての予期されるプロキシコンテナが稼働中である必要があります。

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

____


=== 移行の完了

プロキシホストシステムは現在、更新された {productname} {productnumber}プロキシパッケージと、同期された製品チャンネルを備えた{sles} 15 SP7を実行しています。
