
= {productname} Documentation
:revdate: 2025-04-30
:page-revdate: {revdate}

ifeval::[{mlm-content} == true]

[.currentrel]**Version: {productnumber}**
endif::[]

ifeval::[{uyuni-content} == true]

[.currentrel]**Version: {productnumber}**

endif::[]

ifeval::[{mlm-content} == true]

[IMPORTANT]
====
We are currently in the process of updating and enhancing the [.currentrel]**{productnumber}** documentation. Please note that this documentation is currently in **draft** form and should be considered a work in progress (WIP).

The final release of version 5.1 is expected mid 2025. Until then, content may evolve, and certain sections may be incomplete or subject to change.

Your Feedback Matters: We welcome and appreciate your feedback. If you encounter unclear information, gaps in coverage, or have suggestions for improvement, please let us know. Your input is invaluable in helping us deliver accurate and useful documentation.

📬 Submit feedback: https://github.com/uyuni-project/uyuni-docs/issues
====
endif::[]

ifeval::[{uyuni-content} == true]

[IMPORTANT]
====
We are currently in the process of enhancing the [.currentrel]**{productnumber}** documentation.

**We Value Your Input:** Your feedback is crucial to us! 
If you find any aspects of the documentation unclear or notice missing information, please do not hesitate to reach out. 
We appreciate your questions and suggestions, which are vital in helping us improve.


フィードバックのお送り先: https://github.com/uyuni-project/uyuni-docs/issues
====
endif::[]


== {productname} とは？


// [#salt.gloss] may be used to create a tooltip for a glossary term: see branding/supplemental-ui/mlm/mlmcom/partials/footer-scripts.hbs

{productname} はサーバに対するメンテナンスやパッケージ配備を制御したい組織向けのソリューションです。自動化されたソフトウェア管理やアセット管理、そしてシステムのプロビジョニング機能を利用することで、多数の Linux システムを管理して最新の状態に維持することができます。また、システムのライフサイクル要件を効率的に管理しながら、高いレベルのセキュリティを実現することができます。

{productname} では {salt} と呼ばれる仕組みで、イベント駆動型の設定や管理制御を提供しています。{salt} マスターは数万もの {salt} クライアント ({productname} クライアント) をリモート実行の仕組みで制御します。

{productname} は {sle}、{opensuse}、{rhel}、{centos}、{oracle}、{ubuntu}、{debian}、{amazon}、{almalinux}、および {raspberrypios} の各クライアントシステムを区別無く管理する機能を提供します。もちろんオンプレミスだけでなく、パブリッククラウドやプライベートクラウド、ハイブリッドクラウドからマルチクラウド環境まで、どの環境にも対応します。



// MLM index content

ifeval::[{mlm-content} == true]
== 利用可能なドキュメンテーション

The following documentation for {productname} version {productnumber} is available in PDF format for easy download and reference.


Download the complete set of PDFs icon:caret-right[] icon:file-archive[link="../suse-multi-linux-manager-docs_en-pdf.zip"]

[TIP]
====
{productname} documentation is available in several locations and formats. For the most up-to-date version of this documentation, see link:https://documentation.suse.com/[SUSE Multi-Linux Manager].
====

endif::[]


//Uyuni Index content

ifeval::[{uyuni-content} == true]
== 利用可能なドキュメンテーション

The following documentation for {productname} version {productnumber} is available in PDF format for easy download and reference.

Download the complete set of PDFs icon:caret-right[] icon:file-archive[link="../uyuni-docs_en-pdf.zip"]
endif::[]
