[[tftpd-formula]]
= TFTPd Formula
:description: Configure the TFTP service on the SUSE Multi-Linux Manager for Retail branch server by setting up the TFTPd formula with internal network address, TFTP base
:revdate: 2025-06-12
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

The TFTPd formula is used to configure the TFTP service on the {productname} {smr} branch server.

[IMPORTANT]
====
The formula is used only for connecting {productname} Proxy 4.3. with {productname} Server {productnumber}.
Do not use this formula if you want to connect {productname} Proxy {productnumber}.
====

.Procedure: Configuring TFTP

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``Tftpd`` formula, and click btn:[Save].
. Navigate to the menu:Formulas[Tftpd] tab, and set these parameters:
* In the [guimenu]``Internal Network Address`` field, enter the IP address of the branch server (for example: [systemitem]``192.168.1.5``).
* In the [guimenu]``TFTP Base Directory`` field, enter the path to the {saltboot} directory (for example, [systemitem]``/srv/saltboot``).
* In the [guimenu]``Run TFTP Under User`` field, enter [systemitem]``saltboot``.
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.
