ifeval::[{mlm-content} == true]

:noindex:
endif::[]

ifndef::backend-pdf[]
[[uyuni-common-workflows-overview]]
= Common workflows
:revdate: 2025-05-21
:page-revdate: {revdate}

// HTML Publication date 
**Publication Date:** {docdate}

== Preface


The {productname} Common Workflows Guide provides step-by-step instructions for the most frequently used workflows to install, manage, and configure clients with {productname}.

Each workflow in this guide has a clear objective and includes detailed steps to help you achieve it efficiently.

Designed for both routine and advanced tasks, this guide not only explains the actions you take but also highlights the available options at each stage.

Throughout this guide, each routine task is referred to as a Workflow.

endif::[]

// PDF PREFACE PAGE
ifdef::backend-pdf[]

<<<

[preface]
== Preface

Common Workflows +
{productname} {productnumber}

The {productname} Common Workflows Guide provides step-by-step instructions for the most frequently used workflows to install, manage, and configure clients with {productname}.

Each workflow in this guide has a clear objective and includes detailed steps to help you achieve it efficiently.

Designed for both routine and advanced tasks, this guide not only explains the actions you take but also highlights the available options at each stage.

Throughout this guide, each routine task is referred to as a Workflow.

// PDF Publication

**Publication Date:** {docdate}

// PDF Copyright Space

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

<<<

toc::[]

endif::[]
