[[installation-general-requirements]]
= Requisitos generales
:revdate: 2025-02-20
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

Antes de empezar la instalación, asegúrese de tener:

. A {scclongform} account. This account gives you access to organization credentials and registration keys for {productname} Server, Proxy and Retail Branch Server.
. Supported Browsers for {productname} {webui}.
. SSL certificates for your environment. By default {productname} {productnumber} uses a self-signed certificate.

[NOTE]
====
The {sl-micro} {microversion} entitlement is included within the {productname} entitlement, so it does not require a separate registration key.
====

The following section contains more information on these requirements.


[[install.scc-register]]
== {scclongform} Account and Credentials


Create an account with {scclongform} prior to deployment of {productname} {productnumber}.

[[creating.scc.account.mgr]]
.Procedure: Obtain Your Organization Credentials
. Navigate to https://scc.suse.com/login in your web browser.
. Log in to your {scc} account, or follow the prompts to create a new account.
. Si no lo ha hecho todavía, clique btn:[Conectarse a una organización] y teclee o busque su organización.
. Click btn:[Manage my Organizations] and select your organization from the list by clicking the organization name.
. Click the btn:[Users] tab, and then select the btn:[Organization Credentials] sub-tab.
. Guarde su información de acceso para uso durante la configuración de {productname}.

Depending on your organization's setup, you might also need to activate your subscription, using the btn:[Activate Subscriptions] menu from the left navigation bar.

For more information about using {scc}, see https://scc.suse.com/docs/help.



[[installation-general-supportedbrowsers]]
== Supported Browsers for {productname} {webui}

To use the {webui} to manage your {productname} environment, you must run an up to date web browser.

{productname} is supported on:

* Latest Firefox browser shipped with {sles}
* Latest Chrome browser on all operating systems
* Latest Edge browser shipped with Windows

Windows Internet Explorer is not supported. The {productname} {webui} will not render correctly under Windows Internet Explorer.



== SSL Certificates

{productname} uses SSL certificates to ensure that clients are registered to the correct server. By default, {productname} uses a self-signed certificate. If you have certificates signed by a third-party CA, you can import them to your {productname} installation.

* For more on self-signed certificates, see xref:administration:ssl-certs-selfsigned.adoc[].
* For more on imported certificates, see xref:administration:ssl-certs-imported.adoc[].





