Operating systems either trust their own GPG keys directly or at least ship them installed with the minimal system.
But third party packages signed by a different GPG key need manual handling.
The clients can be successfully bootstrapped without the GPG key being trusted.
However, you cannot install new client tool packages or update them until the keys are trusted.

Salt clients use now GPG key information entered for a software channel to manage the trusted keys.
When a software channel with GPG key information is assigned to a client, the key gets trusted as soon as the channel is refreshed or the first package gets installed from this channel.

[NOTE]
====
If you are bootstrapping Salt clients from the {productname} {webui}, you can use a Salt state to trust the key.
For more information on custom Salt states, see xref:salt:custom-states.adoc[].
====



.Procedure: Trusting GPG Keys on Clients Using a Bootstrap Script
. On the {productname} Server, at the command prompt, check the contents of the [path]``/srv/www/htdocs/pub/`` directory.
  This directory contains all available public keys.
  Take a note of the key that applies to the channel assigned to the client you are registering.
. Open the relevant bootstrap script, locate the [systemitem]``ORG_GPG_KEY=`` parameter and add the required key.
  For example:
+
----
uyuni-gpg-pubkey-0d20833e.key
----
+
You do not need to delete any previously stored keys.

[IMPORTANT]
====
Trusting a GPG key is important for security on clients. 
It is the task of the admin to decide which keys are needed and can be trusted.
Trusting the key is done manually,  either by writing a Salt state or adding the keys to the bootstrap script.
====
