By default, operating systems trust only their own GPG keys when they are installed, and do not trust keys provided by third party packages.
The clients can be successfully bootstrapped without the GPG key being trusted.
However, you cannot install new client tool packages or update them until the keys are trusted.

Salt clients are set to trust {suse} tools channels GPG keys when they are bootstrapped.
For all other clients and channels, you need to manually trust third party GPG keys.



.Procedure: Trusting GPG Keys on Clients
. On the {productname} Server, at the command prompt, check the contents of the [path]``/srv/www/htdocs/pub/`` directory.
  This directory contains all available public keys.
  Take a note of the key that applies to the channel assigned to the client you are registering.
. Open the relevant bootstrap script, locate the [systemitem]``ORG_GPG_KEY=`` parameter and add the required key.
  For example:
+
----
uyuni-gpg-pubkey-0d20833e.key
----
+
You do not need to delete any previously stored keys.
. If you are bootstrapping clients from the {productname} {webui}, you need to use a Salt state to trust the key.
  Create the Salt state and assign it to the organization.
  You can then use an activation key and configuration channels to deploy the key to the clients.
