= Proxy Upgrade from 5.0 to 5.2
:revdate: 2026-06-30
:page-revdate: {revdate}

== Introduction


This document provides the tested and validated procedures for migrating both the **host operating system** and the **proxy extension** in environments managed by **{productname}**, specifically targeting systems deployed with **{productname} Proxy 5.0**.

The upgrade scenarios covered include:

* Migrating from **SUSE Linux Enterprise Micro (SLE Micro) 5.5** to **SL Micro 6.2**
* Migrating from **SUSE Linux Enterprise Server (SLES) 15 SP6** to **SLES 15 SP7**
* Upgrading the **{productname} Proxy Extension** from **version 5.0** to **version {productnumber}**

[IMPORTANT]
====
Before migrating the proxy, it is required to first migrate the SUSE Manager 5.0 Server to {productname} {productnumber}.
====


== {sle-micro} 5.5 to {sl-micro} 6.2

This section provides the tested procedure to upgrade a {sle-micro} 5.5 host deployed with {productname} 5.0 Proxy to {sl-micro} 6.2 with {productname} {productnumber} Proxy.


=== Prerequisites

* {productname} 5.0 Proxy is installed and running on {sle-micro} 5.5.
* Proxy system is registered with the {productname} Server.


=== Distribution upgrade and proxy migration

.Procedure: Migrate {productname} 5.0 Proxy to {productname} {productnumber} Proxy
[role=procedure]
____

. Verify System and {productname} Tools version.

+

[source,console]
----
cat /etc/os-release
mgrpxy --version
----

+

Confirm:

* Operating System: `SLE Micro 5.5`
* Tools version: `mgrpxy version 0.1.29` or higher

+

. Check running containers.

+

[source,console]
----
podman ps
----

+

Ensure the following containers are running:

- `proxy-squid`
- `proxy-ssh`
- `proxy-httpd`
- `proxy-tftpd`
- `proxy-salt-broker`

+

. Synchronize the new Proxy Products in {productname} Server.
  For more information, see xref:client-configuration:products.adoc[].

+

Use the Web UI to synchronize:

* `SL Micro 6.2`
* `{productname} Proxy Extension {productnumber}`

+

. Perform proxy product migration.
  For more information, see xref:client-configuration:client-upgrades-product-migration.adoc[].

+

Navigate to the proxy system and select menu:Systems[Overview] > menu:Software[Product Migration].

+

Migrate from

* `SLE Micro 5.5` + `SUSE Manager Proxy 5.0 Extension`

+

to

* `SL Micro 6.2` + `{productname} Proxy Extension {productnumber}`

+

[IMPORTANT]
====
**Do not select** optional channels when prompted, unless you have confirmed they are required.
====

+

[NOTE]
====
It is recommended to do a dry-run first before performing the actual migration.
====

+

. Monitor the migration action.

+

You can follow the process under menu:Systems[Details > Events] tab in the {webui}.

+

. After the upgrade completes, stop the proxy container and then reboot the system.

+

[source,console]
----
reboot
mgrpxy stop
----

+

. Perform post-reboot checks. 

+

Verify upgraded OS and {productname} extension:

+

[source,console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

. Verify {productname} tools version.

+

[source,console]
----
mgrpxy --version
----

+

Expected output:

- `mgrpxy version 5.2` or higher

+

. Enable Root SSH Access (_if required_).
  SL Micro 6.2 disables root login via SSH by default.
  Edit `/etc/ssh/sshd_config.d/sshd.conf`:

+

[source,console]
----
PermitRootLogin yes
----

+

Restart the service:

+

[source,shell]
----
systemctl restart sshd
----

+

For more information, see xref:administration:troubleshooting/tshoot-remote-root-on-micro.adoc[].


. Install the new proxy container images as RPM packages.

+

[source,shell]
----
transactional-update pkg install suse-multi-linux-manager-5.2-<arch>-proxy*
----

. Reboot the Proxy.

. Upgrade proxy containers and restart them.

+

[source,console]
----
mgrpxy upgrade podman
mgrpxy stop
mgrpxy start
----

+

For air-gapped installations, first upgrade the container RPM packages, then run the `mgrpxy upgrade podman` command.

+

Or, those running on a Kubernetes cluster can update using:

+

[source,shell]
----
mgrpxy upgrade kubernetes
----

+

. Clean up the unused container images to free disk space:

+
[source,shell]
----
podman image prune -a
----

+

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-check-rpmnew-rpmsave.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-check-rpmnew-rpmsave.adoc[]
endif::[]

+

. Confirm proxy containers are operational.

+

[source,console]
----
podman ps
----

+

All expected proxy containers should be up and running:

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

____


ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-version-number.adoc[leveloffset=+1]
include::installation-and-upgrade:partial$snippet-tag-containers.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-version-number.adoc[leveloffset=+1]
include::../../../../../partials/snippet-tag-containers.adoc[leveloffset=+1]
endif::[]



=== Migration complete

The proxy host system is now running {sl-micro} 6.2 with updated {productname} {productnumber} Proxy packages and synchronized product channels.


== {sles} 15 SP6 to 15 SP7

This section provides the procedure to upgrade a {sles} SP6 host deployed with {productname} 5.0 Proxy to {sles} {sp-version} with {productname} {productnumber} Proxy.


=== Prerequisites

* {productname} Proxy 5.0 is installed and running on {sles} 15 SP6.
* Proxy system is registered with the {productname} Server.


=== Distribution upgrade and proxy migration

.Procedure: Update {productname} Proxy components on {sles} 15 SP6
[role=procedure]
____

. Verify operating system and {productname} tools version.

+

[source,console]
----
cat /etc/os-release
mgrpxy --version
----

+

Confirm:

* Operating System: `SUSE Linux Enterprise Server 15 SP6`
* Tools version: `mgrpxy version 0.1.29` or higher


+

. List running proxy containers.

+

[source,console]
----
podman ps
----

+

Ensure the following containers are running:

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

+

. Synchronize the new Products in {productname} Server using the Web UI.

+

For more information, see xref:client-configuration:products.adoc[].

+

Synchronize:

* `{sles} {sp-version}`
* `{productname} Proxy Extension {productnumber}`

+

. Perform proxy product migration.

+

For more information, see xref:client-configuration:client-upgrades-product-migration.adoc[].

+

Navigate to the proxy system and select menu:Systems[Overview] > menu:Software[Product Migration].

+

Migrate from:

* `{sles} 15 SP6` + `SUSE Manager Proxy 5.0 Extension`

+

to:

* `{sles} {sp-version}` + `{productname} Proxy Extension {productnumber}`

+

[IMPORTANT]
====
**Do not select** optional channels when prompted, unless you have confirmed they are required.
====

+

[NOTE]
====
It is recommended to do a dry-run first before performing the actual migration.
====

+

. Monitor the migration action.

+

You can follow the process under menu:Systems[Details > Events] in the {webui}.

+

. After the upgrade completes, stop the proxy container and then reboot the system.

+

[source,console]
----
mgrpxy stop
reboot
----

+

. Perform post-reboot checks. 

+

Verify the OS and {productname} extension version:

+

[source,console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

. Verify {productname} tools version.

+

[source,console]
----
mgrpxy --version
----

+

Expected output:

- `mgrpxy version 5.2` or higher

+

. Install the new proxy container images as RPM packages.

+

[source,shell]
----
zypper install suse-multi-linux-manager-5.2-<arch>-proxy*
----

+

. Reboot the Proxy.

. Upgrade proxy containers and restart them.

+

[source,console]
----
mgrpxy upgrade podman
mgrpxy stop
mgrpxy start
----

+

For air-gapped installations, first upgrade the container RPM packages, then run the `mgrpxy upgrade podman` command.

+

Or, those running on a Kubernetes cluster can update using:

+

[source,shell]
----
mgrpxy upgrade kubernetes
----

+

. Clean up the unused container images to free disk space:

+
[source,shell]
----
podman image prune -a
----

+

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-check-rpmnew-rpmsave.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-check-rpmnew-rpmsave.adoc[]
endif::[]

+

. Confirm proxy containers are operational.

+

[source,console]
----
podman ps
----

+

All expected proxy containers should be up and running:

- `proxy-salt-broker`
- `proxy-httpd`
- `proxy-squid`
- `proxy-tftpd`
- `proxy-ssh`

____


ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-version-number.adoc[leveloffset=+1]
include::installation-and-upgrade:partial$snippet-tag-containers.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-version-number.adoc[leveloffset=+1]
include::../../../../../partials/snippet-tag-containers.adoc[leveloffset=+1]
endif::[]



=== Migration complete

The proxy host system is now running {sles} {sp-version} with updated {productname} {productnumber} Proxy packages and synchronized product channels.
