[[connect.payg.instances]]
= {payg}インスタンスの接続
:revdate: 2025-07-14
:page-revdate: {revdate}

大手パブリッククラウドプロバイダ3社(AWS、GCP、Azure)では、SUSEは、

* SLES、SLES for SAPなどのカスタマイズされた{payg}製品イメージを提供します。
* {payg}として利用可能な製品のリポジトリをミラーリングするリージョンごとのRMTサーバを運用します

このドキュメントでは、既存の{payg}インスタンスを{productname}サーバに接続する方法について説明し、インスタンスからの資格情報の収集に関する基本的な情報を提供します。 この接続の目的は、認証データを抽出して、{productname}サーバがクラウドRMTホストに接続できるようにすることです。 これにより、{productname}サーバは{scc}組織資格情報ではまだ利用できないRMTホスト上の製品にアクセスできるようになります。


{payg}機能を使用する前に、以下のことを確認してください。

* {payg}インスタンスが正しいSUSE製品イメージ(例: SLES、SLES for SAP、SLE HPC)から起動され、目的のリポジトリにアクセスできる

* {productname}サーバが直接または要塞経由で{payg}インスタンス(理想的には同じリージョン内)に接続できる

* 基本的な{scc}アカウントが必要です。有効な{scc}資格情報をmenu:管理[セットアップウィザード > 組織の資格情報]に入力します。 このアカウントは、{payg}インスタンスに関係なく、ブーストラッピング用の{productname}クライアントツールにアクセスするために必要です。

* If you bootstrap the {payg} instance to {productname}, it will disable its {payg} repositories then add repositories from where it mirrored the data from the RMT server. The final result will be {payg} instances acquiring the same repositories from the RMT servers but through the {productname} server itself. Of course repositories can still be setup primarily from SCC.



== {payg}インスタンスを接続する


[[proc-connecting-new-payg]]
.プロシージャ: 新しい{payg}インスタンスを接続する
[role=procedure]
. {productname}の{webui}で、menu:管理[セットアップウィザード > {payg}]に移動し、btn:[{payg}の追加]をクリックします。
. ページセクション［[guimenu]``{payg}の接続の説明``］から始めます。
. ［[guimenu]``説明``］フィールドに、説明を追加します。
. ページセクション［[guimenu]``インスタンスSSH接続データ``］に移動します。
. ［[guimenu]``ホスト``］フィールドに、{productname}から接続するインスタンスのDNSまたはIPアドレスを入力します。
. ［[guimenu]``SSHポート``］フィールドに、ポート番号を入力するか、デフォルト値22を使用します。
. ［[guimenu]``ユーザ``］フィールドに、クラウドで指定されているユーザ名を入力します。
. ［[guimenu]``パスワード``］フィールドに、パスワードを入力します。
. ［[guimenu]``SSH機密鍵``］フィールドに、インスタンスキーを入力します。
. ［[guimenu]``SSH機密鍵のパスフレーズ``］フィールドに、キーパスフレーズを入力します。

[IMPORTANT]
====
認証キーは常にPEM形式である必要があります。
====

インスタンスに直接接続していないが、SSH要塞を介して接続している場合は、<<proc-adding-ssh-bastion-connection-data>>に進みます。

それ以外の場合は、<<proc-finishing-payg-connecting>>に進みます。

[[proc-adding-ssh-bastion-connection-data]]
.プロシージャ: SSH要塞接続データを追加する
[role=procedure]
. ページセクション［[guimenu]``要塞SSH接続データ``］に移動します。
. ［[guimenu]``ホスト``］フィールドに、要塞のホスト名を入力します。
. ［[guimenu]``SSHポート``］フィールドに、要塞のポート番号を入力します。
. ［[guimenu]``ユーザ``］フィールドに、要塞のユーザ名を入力します。
. ［[guimenu]``パスワード``］フィールドに、要塞のパスワードを入力します。
. ［[guimenu]``SSH機密鍵``］フィールドに、要塞キーを入力します。
. ［[guimenu]``SSH機密鍵のパスフレーズ``］フィールドに、要塞キーのパスフレーズを入力します。

Complete the setup process with <<proc-finishing-payg-connecting>>.

[[proc-finishing-payg-connecting]]
.プロシージャ: {payg}の接続を完了する
[role=procedure]
. 新しい{payg}接続データの追加を完了するには、btn:[作成]をクリックします。
. {payg}接続データの［[guimenu]``詳細``］ページに戻ります。
    更新された接続ステータスは、［[guimenu]``情報``］という名前の上部セクションに表示されます。
. 接続ステータスは、［ [guimenu]``管理 > セットアップウィザード > Pay-as-you-go``］画面にも表示されます。
. インスタンスの認証データが正しい場合、［[guimenu]``ステータス``］列に「資格情報が正常に更新されました」と表示されます。

[IMPORTANT]
====
いずれかの時点で無効なデータが入力されると、新しく作成されたインスタンスが［[guimenu]``管理 > セットアップウィザード > {payg}``］に表示され、［[guimenu]``ステータス``］列にエラーメッセージが表示されます。
====


サーバで認証データが利用可能になるとすぐに、利用可能な製品のリストが更新されます。

利用可能な製品は、{payg}インスタンスにインストールされているものと同じ製品ファミリおよびアーキテクチャのすべてのバージョンです。たとえば、インスタンスに{sles}{nbsp}15 SP1製品がインストールされている場合、{sles}{nbsp}15 SP2、{sles}{nbsp}15 SP3、{sles}{nbsp}15 SP4、および{sles}{nbsp}15 SP5が［[guimenu]``管理 > セットアップウィザード > 製品``］に自動的に表示されます。

製品が利用可能として表示されたら、ユーザは、製品名の横にあるチェックボックスを選択しbtn:[製品の追加]をクリックして、{productname}に製品を追加できます。

成功メッセージの後、［[guimenu]``ソフトウェア > チャンネル一覧 > すべて``］に移動して、{webui}で新しく追加されたチャンネルを確認できます。

各チャンネルの同期の進行状況を監視するには、{productname}サーバの [path]``/var/log/rhn/reposync``ディレクトリにあるログファイルを確認します。

[IMPORTANT]
====
{payg}インスタンスと{scc}サブスクリプションの1つによって製品が提供されている場合、その製品は製品リストに1回のみ表示されます。

その製品に属するチャンネルが同期されている場合でも、データはSCCサブスクリプションからのものであり、従量課金制インスタンスからのものではない可能性があります。
====

== インスタンス資格情報収集ステータス

{productname}サーバは、インスタンスから収集された資格情報を使用してRMTサーバに接続し、reposyncを使用してパッケージをダウンロードします。これらの資格情報は、taskomaticにより、定義されたSSH接続データを使用して10分ごとに更新されます。RMTサーバへの接続では、常に{payg}インスタンスから収集された最新の既知の認証資格情報が使用されます。

{payg}インスタンスの資格情報収集のステータスは、［[literal]``ステータス``］列またはインスタンスの詳細ページに表示されます。インスタンスに到達できない場合、資格情報の更新プロセスは失敗します。

インスタンスに到達できない場合、資格情報の更新プロセスは失敗し、2回目に更新が失敗すると資格情報は無効になります。資格情報が無効な場合、チャンネルの同期は失敗します。これを避けるには、接続されているインスタンスの実行状態を維持します。

{payg}インスタンスは、SSH接続データが明示的に削除されない限り、{productname}サーバに接続されたままになります。インスタンスへのSSH接続データを削除するには、<<proc-deleting-connection-data-to-instance>>を使用します。
 

{payg}インスタンスは、{productname}サーバから常にアクセスできるとは限りません。

* インスタンスが存在するが停止している場合は、最新の既知の資格情報を使用してインスタンスへの接続が試行されます。
    資格情報が有効である期間は、クラウドプロバイダによって異なります。

* インスタンスが存在しなくなったが、SUMAに登録されている場合、その資格情報は無効になり、認証は失敗します。
    エラーメッセージは［ステータス］列に表示されます。
+
[WARNING]
====
エラーメッセージは、インスタンスが使用できないことを示すだけです。インスタンスのステータスに関する詳細な診断は、クラウドプロバイダで実行する必要があります。
====

[IMPORTANT]
====
{payg}インスタンスで次のアクションまたは変更を行うと、資格情報が機能しなくなります。
* zypper資格情報ファイルの削除
* インポートした証明書の削除
* [path]``/etc/hosts``からのクラウド固有エントリの削除
====


== {payg}システムをクライアントとして登録する

資格情報を{salt}クライアントとして収集する場所から{payg}インスタンスを登録できます。 インスタンスには有効なクラウド接続が登録されている必要があります。登録されていないとチャンネルにアクセスできません。 ユーザがクラウドパッケージを削除すると、資格情報の収集が機能しなくなる場合があります。

最初に{payg}インスタンスを設定して、認証データを収集し、チャンネルを同期できるようにします。

残りのプロセスは、パブリッククラウド以外のクライアントの場合と同じで、チャンネルの同期、ブートストラップスクリプトの自動作成、アクティベーションキーの作成、および登録の開始で構成されます。

クライアントの登録の詳細については、xref:client-configuration:registration-overview.adoc[]を参照してください。


== トラブルシューティング 

資格情報の確認::
* スクリプトが資格情報の収集に失敗した場合、ログと{webui}に適切なエラーメッセージが表示されます。
* 資格情報が機能しない場合は、[literal]``reposync``に適切なエラーが表示されます。

[literal]``registercloudguest``を使用する::
* パブリッククラウド更新インフラストラクチャへの[literal]``registercloudguest``接続を更新または変更しても、資格情報の使用に支障はありません。
* cloudguestコマンドを使用して新しいクラウド接続が登録されていない場合、[literal]``registercloudguest --clean``を実行すると問題が発生します。
