[[installation-general-requirements]]
= 一般的な要件
:revdate: 2025-02-20
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

インストールを始める前に、次の項目を確認してください。

. {scclongform}アカウント。このアカウントにより、組織の資格情報と、{productname}サーバ、プロキシ、およびRetail Branch Serverの登録キーにアクセスできます。
. {productname} {webui}でサポートされるブラウザ。
. 環境のSSL証明書。デフォルトでは、{productname} {productnumber}は自己署名証明書を使用します。

[NOTE]
====
{sl-micro} {microversion}エンタイトルメントは、{productname}エンタイトルメント内に含まれているため、別途登録キーは必要ありません。
====

次のセクションでは、これらの要件について詳しく説明します。


[[install.scc-register]]
== {scclongform}アカウントと資格情報


{productname} {productnumber}を配備する前に、{scclongform}でアカウントを作成します。

[[creating.scc.account.mgr]]
.プロシージャ: 組織の資格情報を取得する
. Webブラウザで https://scc.suse.com/login[]にアクセスします。
. {scc}アカウントにログインするか、またはプロンプトに従い新しいアカウントを作成します。
. まだ組織に接続していない場合、btn:[組織に接続する]をクリックし、組織を入力または検索します。
. btn:[組織を管理する]をクリックし、組織名をクリックして一覧から組織を選択します。
. btn:[ユーザ]タブをクリックし、btn:[組織の資格情報]サブタブを選択します。
. {productname}の設定中に使用するログイン情報をメモします。

組織の設定によっては、左側のナビゲーションバーからbtn:[サブスクリプションをアクティブ化する]メニューを使用してサブスクリプションをアクティブ化する必要が生じる場合もあります。

{scc}の使用の詳細については、link:https://scc.suse.com/docs/help[]を参照してください。



[[installation-general-supportedbrowsers]]
== {productname} {webui}でサポートされているブラウザ

{webui}を使用して{productname}環境を管理するには、最新のWebブラウザを実行する必要があります。

{productname}は以下のブラウザでサポートされています。

* {sles}に付属する最新のFirefoxブラウザ
* あらゆるオペレーティングシステム上の最新のChromeブラウザ
* Windowsに付属する最新のEdgeブラウザ

Windows Internet Explorerはサポートされていません。{productname}の{webui}はWindows Internet Explorerでは正しくレンダリングされません。



== SSL証明書

{productname}は、SSL証明書を使用して、クライアントが正しいサーバに登録されていることを確認します。デフォルトでは、{productname}は自己署名証明書を使用します。サードパーティCAによって署名された証明書がある場合、それを{productname}インストール環境にインポートできます。

* 自己署名証明書の詳細については、xref:administration:ssl-certs-selfsigned.adoc[]を参照してください。
* インポートした証明書の詳細については、xref:administration:ssl-certs-imported.adoc[]を参照してください。





