ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

ifndef::backend-pdf[]
[[installation-and-upgrade-overview]]
= インストール、配備、およびアップグレード
:revdate: 2025-05-21
:page-revdate: {revdate}

// HTML Publication date 
**発行日:** {docdate}

== 序文 


このガイドでは、{productname}サーバおよびプロキシを配備、アップグレード、管理するための包括的な手順を段階的に説明します。

以下のセクションで構成されています。

* **要件:** スムーズなセットアップを確実に行うために必要なハードウェア、ソフトウェア、およびネットワークの前提条件を概説します。
* **配備とインストール:** {productname}をコンテナとして配備し、初期設定を完了する手順を説明します。
* **アップグレードと移行:** ダウンタイムを最小限に抑えながら{productname}をアップグレードおよび移行するプロセスを詳細に説明します。
* **基本的なサーバ管理:** 基本的なサーバ操作をカバーし、{productname}を効率的に開始するのに役立ちます。 

== 著作権通知

ifeval::[{mlm-content} == true]
// HTML Copyright
Copyright © {copyrightdate} SUSE LLC and contributors. All rights reserved. この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]セクションに含まれています。
endif::[]

ifeval::[{uyuni-content} == true]
// HTML Copyright
Copyright © 2011–2025 Uyuni contributors. All rights reserved. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].
endif::[]

== 商標
// HTML Trademarks
SUSEの商標については、link:https://www.suse.com/company/legal/[]を参照してください。その他の第三者のすべての商標は、各社の所有に帰属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。本書のすべての情報は、細心の注意を払って編集されています。しかし、このことは絶対に正確であることを保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。
endif::[]

ifdef::backend-pdf[]

<<<

:!sectnums:

[preface]
== 序文

Installation, Deployment and Upgrade | {productname} {productnumber}

このガイドでは、{productname}サーバおよびプロキシを配備、アップグレード、管理するための包括的な手順を段階的に説明します。

以下のセクションで構成されています。

* **要件:** スムーズなセットアップを確実に行うために必要なハードウェア、ソフトウェア、およびネットワークの前提条件を概説します。
* **配備とインストール:** {productname}をコンテナとして配備し、初期設定を完了する手順を説明します。
* **アップグレードと移行:** ダウンタイムを最小限に抑えながら{productname}をアップグレードおよび移行するプロセスを詳細に説明します。
* **基本的なサーバ管理:** 基本的なサーバ操作をカバーし、{productname}を効率的に開始するのに役立ちます。 

// PDF Publication

**発行日:** {docdate}

ifeval::[{mlm-content} == true]
// PDF Copyright
Copyright © {copyrightdate} SUSE LLC and contributors. All rights reserved. この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]セクションに含まれています。
endif::[]

ifeval::[{uyuni-content} == true]
// PDF Copyright
Copyright © 2011–2025 Uyuni contributors. All rights reserved. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].
endif::[]

// PDF Trademarks
SUSEの商標については、link:https://www.suse.com/company/legal/[]を参照してください。その他の第三者のすべての商標は、各社の所有に帰属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。本書のすべての情報は、細心の注意を払って編集されています。しかし、このことは絶対に正確であることを保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。

<<<

toc::[]

:sectnums:

endif::[]
