[[install-pubcloud-requirements]]
= パブリッククラウドの要件
:revdate: 2025-02-06
:page-revdate: {revdate}

このセクションは、パブリッククラウドインフラストラクチャに{productname}をインストールする要件について説明します。Amazon EC2、Google Compute Engine、およびMicrosoft Azureではテストを実施済みですが、若干の差異はあってもその他のプロバイダにも当てはまるはずです。

始める前に、考慮事項を次に示します。

* {productname}設定プロシージャは、正引きで確認された逆引きDNS参照を実行します。設定プロシージャが完了して{productname}が期待どおりに動作するためには、この参照が成功する必要があります。{productname}を設定する前に、ホスト名とIPの設定を実行することが重要です。
* {productname}サーバとプロキシのインスタンスは、DNSエントリを介した制御を提供するネットワーク設定で実行する必要がありますが、大規模インターネットからはアクセスできません。
* このネットワーク設定内では、DNSの解決を提供する必要があります。``hostname -f``は、完全修飾ドメイン名(FQDN)を返す必要があります。
* DNSの解決は、クライアントを接続するためにも重要です。
* DNSは、選択したクラウドフレームワークに依存しています。詳細な手順については、クラウドプロバイダのドキュメントを参照してください。
* ソフトウェアリポジトリ、サーバデータベース、およびプロキシsquidキャッシュは外部仮想ディスクに配置することをお勧めします。こうすることによって、インスタンスが予期せずに終了した場合のデータ損失が防止されます。このセクションでは、外部仮想ディスクの設定方法の手順について説明します。



== ネットワーク要件


パブリッククラウドで{productname}を使用する場合は、制限付きのネットワークを使用する必要があります。適切なファイアウォール設定でVPCプライベートサブネットを使用することをお勧めします。指定したIP範囲にあるマシンのみがインスタンスにアクセスできる必要があります。

[WARNING]
====
パブリッククラウド上で{productname}を実行するということは、堅牢なセキュリティ対策を実装することを意味します。インスタンスへのアクセスを制限、フィルタ、監視、監査することが不可欠です。{SUSE} は、適切な境界セキュリティが欠如しているグローバルにアクセス可能な{productname}インスタンスを使用しないことを強くお勧めします。
====

{productname}の{webui}にアクセスするには、ネットワークアクセス制御を設定するときにHTTPSを許可します。そうすると、{productname}の{webui}にアクセスできます。

EC2およびAzureでは、新しいセキュリティグループを作成し、HTTPSの着信および受信のルールを追加します。GCEでは、［``ファイアウォール``］セクションで［``HTTPSトラフィックを許可する``］ボックスにチェックを付けます。



== ストレージボリュームの準備

リポジトリと{productname}のデータベースは、ルートボリュームとは別のストレージデバイスに保存することをお勧めします。こうするとデータの損失が防止され、パフォーマンスが向上する可能性があります。

{productname}コンテナはデフォルトのストレージの場所を利用します。これらの場所は、カスタムストレージ用の配備前に設定する必要があります。詳細については、xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[永続コンテナのボリューム]を参照してください

[IMPORTANT]
====
パブリッククラウドへのインストールでは論理ボリューム管理(LVM)を使用しないでください。
====


リポジトリストレージのディスクのサイズは、{productname}で管理するディストリビューションおよびチャンネルの数によって決まります。仮想ディスクを接続すると、Unixデバイスノードとしてインスタンスに表示されます。デバイスノードの名前は、選択インスタンスの種類とプロバイダによって異なります。

{productname}サーバのルートボリュームが100{nbsp}GB以上であることを確認してください。500{nbsp}GB以上のストレージディスクを追加し、可能な場合にはSSDストレージを選択します。{productname}サーバのクラウドイメージは、スクリプトを使用して、インスタンス起動時にこの個別ボリュームを割り当てます。

インスタンスを起動すると、{productname}サーバにログインし、次のコマンドを使用して、利用可能なすべてのストレージデバイスを検索できます。

----
hwinfo --disk | grep -E "デバイスファイル:"
----

選択したデバイスがわからない場合、[command]``lsblk``コマンドを使用して、各デバイスの名前およびサイズを確認します。 探している仮想ディスクのサイズと一致している名前を選択します。

[command]``mgr-storage-server``コマンドを使用して外部ディスクを設定できます。設定すると、XFSパーティションが``/manager_storage``にマウントされ、データベースおよびリポジトリの場所として使用されます。

----
/usr/bin/mgr-storage-server <devicename>
----

ifeval::[{mlm-content} == true]
ストレージボリュームおよびパーティションの設定(推奨最小サイズを含む)の詳細については、xref:installation-and-upgrade:hardware-requirements.adoc[]を参照してください。
endif::[]
