== {sles} {bci-mlm} 호스트를 준비합니다.


대안으로, {productname}을 {sles} {bci-mlm}에 배포할 수 있습니다.

다음 절차에서는 설치 과정의 주요 단계를 설명합니다.


=== {productname} 확장 프로그램을 {sles}에 설치합니다.

.절차 {productname} 확장 프로그램을 {sles}에 설치하는 중입니다.
[role=procedure]
____

. {sles} {bci-mlm} `.iso`를 https://www.suse.com/download/sles/.에서 찾아 다운로드합니다.

. 호스트 운영 체제({sles} {bci-mlm}) 및 확장 프로그램 모두에 대한 활성화 코드가 반드시 있어야 합니다.

. {sles} {bci-mlm}의 설치를 시작합니다.

  .. `Language, keyboard and product selection`에서 설치할 제품을 선택합니다.

  .. `License agreement`에서 계약서를 읽고 `I Agree to the License Terms`을(를) 확인합니다.

. 등록 방법을 선택합니다. 이 예제에서는 SUSE 고객 센터에 서버를 등록합니다.

. {scclongform} 이메일 주소를 입력합니다.

. {sles} {bci-mlm}에 대한 활성화 코드를 입력합니다.

. 계속하려면 `Next`을(를) 클릭합니다.

+

[IMPORTANT]
====
{sles} {bci-mlm}에 대해 유효한 {sles} 구독 및 해당 활성화 코드가 필요합니다. 이 화면에서 제공해야 합니다.
아래에 {productname} 확장 프로그램 활성화 코드를 입력해야 합니다.
====

. 화면 `Extensions and Modules Selection`에서 다음 사항을 확인합니다:

+

  * 서버를 설치하려면 {productname} 서버 확장 프로그램을 선택하고, 프록시를 설치하려면 {productname} 프록시 확장 프로그램을 선택합니다.
  * Basesystem 모듈
  * 컨테이너 모듈

. 계속하려면 `Next`을(를) 클릭합니다.

. {productname} {productnumber} 확장 프로그램 활성화 코드를 입력합니다.

. 계속하려면 btn:[다음]을 클릭합니다.

. 설치를 완료합니다.

. 설치가 완료되면 새로 설치된 서버에 루트 권한으로 로그인합니다.

. 시스템 업데이트(선택 사항, 설치 중에 시스템이 업데이트를 다운로드하도록 설정되지 않은 경우):

+

[source,shell]
----
zypper up
----

. 재부팅합니다.

____


=== 선택 사항: 명령줄에서 등록

{sles} 설치 중에 {productname} {productnumber}를 확장 프로그램으로 추가한 경우 이 절차를 건너뛸 수 있습니다.

그러나 선택적으로 {sles} 설치 중에 btn:[등록 건너뛰기] 버튼을 선택하여 등록을 건너뛸 수 있습니다.
이 섹션에서는 {sles} 설치 후 제품 등록 단계에 대해 설명합니다.

[NOTE]
====
다음 단계는 {x86_64} 아키텍처에 대한 활성화 코드가 필요하므로 {productname} {productnumber} 확장을 {x86_64} 아키텍처로 등록합니다.

{arm} 또는 {s390x} 아키텍처를 등록하려면 올바른 활성화 코드를 사용하십시오.
====


.절차 명령줄에서 등록
[role=procedure]
____

. 다음 명령을 실행하여 타이머를 비활성화할 수 있습니다.

+

[source,shell]
----
SUSEConnect --list-extensions
----

+

. 다음 명령을 실행하여 타이머를 비활성화할 수 있습니다.

+

* 서버를 설치하는 경우, {productname} 서버 확장 프로그램 {productnumber} x86_64 활성화 코드를 사용하십시오.

+

예를 들어 {sle} 15 SP7의 경우 다음 명령을 사용하십시오:

+

[source,shell]
----
SUSEConnect -r <regcode>
SUSEConnect -p sle-module-containers/15.7/x86_64
SUSEConnect -p Multi-Linux-Manager-Server-SLE/5.1/x86_64 -r <regcode>
----

+

* 프록시를 설치하는 경우, {productname} 프록시 확장 프로그램 {productnumber} x86_64 활성화 코드를 다음 명령과 함께 사용하십시오.

+

----
SUSEConnect -p Multi-Linux-Manager-Proxy-SLE/5.1/x86_64 -r <regcode>
----

____



=== `podman`을(를) 설치하고 활성화합니다.

.절차 `podman` 설치 중
[role=procedure]
____

. 컨테이너 호스트에서 \``root``로 로그인합니다.

+

* 서버를 재부팅합니다.

+

[source,shell]
----
zypper in podman
zypper in -t product Multi-Linux-Manager-Server-SLE
----

* 프록시에서:

+

[source,shell]
----
zypper in podman
zypper in -t product Multi-Linux-Manager-Proxy-SLE
----

+

[IMPORTANT]
====
패키지 `podman`이(가) 설치되어 있는지 확인하십시오.
또한, 서버 `mgradm` 및 `mgradm-bash-completion` 또는 프록시에서 `mgrpxy` 및 `mgrpxy-bash-completion`도 설치해야 합니다.
====

+

. 시스템을 재부팅하거나 다음 명령을 실행하여 podman 서비스 시작:

+

[source, shell]
----
systemctl enable --now podman.service
----

____
