= Distribution Upgrade and Server Migration from 5.0 to 5.2
:revdate: 2026-02-09
:page-revdate: {revdate}


[IMPORTANT]
====
* {productname} 5.0 must be stopped before the upgrade.
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::installation-and-upgrade:partial$snippet-ssl-requirements.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::../../../../../partials/snippet-ssl-requirements.adoc[leveloffset=+1]
endif::[]

During a migration the server SSL certificate and CA chain are copied from the source server, meaning that only the database certificates are required

[NOTE]
====
{productname} 5.0 peripheral servers are always using third-party SSL certificates.
If the hub server has generated the certificates for the peripheral server, it needs to generate the certificate for the peripheral database too.

On the hub server, run the following command for each of the peripheral server to migrate.

[source,shell]
----
mgrctl exec -ti -- rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="COUNTRY" \
  --set-state="STATE" --set-city="CITY" --set-org="ORGANIZATION" \
  --set-org-unit="ORGANIZATION UNIT" --set-email="name@example.com" \
  --set-hostname=<hostname>-reportdb --set-cname="example.com" --set-cname=db --set-cname=reportdb
----

The files to use will be inside the server container and need to be copied to the new peripheral server host:

. [litteral]``/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT`` as the root CA,
. [litteral]``/root/ssl-build/<hostname>-reportdb/server.crt`` as the db certificate and
. [litteral]``/root/ssl-build/<hostname>-reportdb/server.key`` as the db certificate's key.
====


== {sle-micro} 5.5 to {sl-micro} 6.2



This document provides the tested procedure to upgrade a {sle-micro} 5.5 host deployed with {productname} 5.0 Server to {sl-micro} 6.2 and migrate to {productname} {productnumber}.


=== Prerequisites

* {productname} 5.0 is installed and running on {sle-micro} 5.5.
* System is registered and has active subscriptions with {scc}.


=== Distribution upgrade and server migration

.Procedure: Migration from {productname} 5.0 to {productname} {productnumber}
[role=procedure]
____

. Verify current product status.

+

[source,console]
----
SUSEConnect --status-text
----

+

Confirm:

* Base OS: `SUSE Linux Enterprise Micro 5.5`
* Extension: `SUSE Manager Server 5.0 Extension`

+

. Ensure the system is updated.

+

[source,console]
----
transactional-update patch
----

+

--

* If patches were applied, stop the server and then reboot the system before proceeding to migration:

+

[source,console]
----
mgradm stop
reboot
----

* If no updates were found, you can proceed directly to the migration step.

--

+

. Start the migration.

+

[source,console]
----
transactional-update migration --auto-agree-with-licenses --gpg-auto-import-keys
----

+

Follow the prompts and select the available migration to **SUSE Linux Micro 6.2** and **{productname} Server Extension {productnumber}**.

+

. Stop the server and then reboot to apply changes.

+

[source,console]
----
mgradm stop
reboot
----

+

. Perform post-reboot checks.

+

Verify {productname} extension and {productname} version:

+

[source,console]
----
SUSEConnect --status-text
mgradm --version
----

+

Expected output:

* Extension: [literal]``SUSE Multi-Linux Manager Server {productnumber} Extension``
* Version: referencing [literal]``5.2.0`` or higher

+

. Verify PostgreSQL database version.

+

[source,console]
----
podman ps
----

+

Expected output:

* [literal]``server:5.2.0`` or higher
* [literal]``server-postgresql:5.2.0`` or higher

+

. Verify running containers:

+

[source,console]
----
podman ps
----

+

You should see all the expected server containers are up and running.

____


=== Migration complete

The server host system is now running {sl-micro} 6.2 with updated {productname} {productnumber} Server packages.

If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-52.adoc[Proxy Migration 5.0 > 5.2] guide to upgrade the proxy host.

Validate your setup before resuming production operations.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]


== {sles} 15 SP6 to 15 SP7

This document provides the procedure to upgrade a {sles} 15 SP6 host deployed with {productname} 5.0 Server to {sles} 15 SP7 and migrate to {productname} {productnumber}.


=== Prerequisites

* {productname} 5.0 is installed and running on {sles} 15 SP6.
* System is registered and has active subscriptions with {scc}.


=== Distribution upgrade and server migration

.Procedure: Upgrade and Migrate {productname} on {sles} 15 SP6
[role=procedure]
____

. Verify current product status.

+

[source,console]
----
SUSEConnect --status-text
----

+

Confirm:

* Base OS: `SUSE Linux Enterprise Server 15 SP6`
* Extension: `SUSE Manager Server 5.0 Extension`

+

. Ensure the system is updated.

+

[source,console]
----
zypper patch
----

+

If patches were applied, stop the server and then reboot before proceeding:

+

[source,console]
----
mgradm stop
reboot
----

+

. Perform the migration to SP7 and {productname} {productnumber}.

+

[source,console]
----
zypper migration
----

+

Select to migrate to:

* `{sles} 15 SP7`
* `{productname} Server Extension {productnumber}`

+

. Stop the server and reboot.

+

[source,console]
----
mgradm stop
reboot
----

+

. Perform post-reboot checks.

+

Verify {productname} extension:

+

[source,console]
----
SUSEConnect --status-text
----

+

Expected output:

* Extension: [literal]``SUSE Multi-Linux Manager Server {productnumber} Extension``

+

. Verify {productname} version.

+

[source,console]
----
mgradm --version
----

+

Expected output:

* Version: referencing [literal]``5.2.0`` or higher

+

. Verify containers:

+

[source,console]
----
podman ps
----

+

Expected output:

* [literal]``server:5.2.0`` or higher
* [literal]``server-postgresql:5.2.0`` or higher

____


=== Migration complete

The server host system is now running {sles} 15 SP7 with updated {productname} {productnumber} Server packages.

If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-52.adoc[Proxy Migration 5.0 > 5.2] guide to upgrade the proxy host.

Validate your setup before resuming production operations.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]
