= Distribution Upgrade and Server Migration
:revdate: 2025-10-19
:page-revdate: {revdate}

[NOTE]
====
* {productname} 5.0 must be stopped before upgrade.
* {productname} 5.0 is not supported on top of {sl-micro} 6.1 & {sles} 15 SP7 as host OS.
====

include::../../../snippet-hardened-tmpdir.adoc[leveloffset=+2]

== Client Tools Rebranding

{productname} {productnumber} introduces a rebranded set of client tools for all supported operating systems. This transition is seamless, and users performing a new product synchronization should only notice the updated channel names.

Channels named `SUSE Manager Client Tools for XYZ`, used by clients previously registered with {productname} 4.3 or 5.0, are no longer available in version 5.1 and will no longer receive updates in 5.1.

Although the legacy channels remain assigned to existing clients after migration, the corresponding repositories have been removed.

To ensure continued updates, users must:

- Mirror the new `SUSE Multi-Linux Manager Client Tools for XYZ` channels for the relevant products and assign them to the appropriate clients.
- Unassign the outdated `SUSE Manager Client Tools for XYZ` channels.

This also means that any CLM projects based on the old client tools must be adjusted accordingly.

For more information see the example workflow under xref:common-workflows:workflow-switch-to-new-client-tools-channels.adoc[].



== {sle-micro} 5.5 to {sl-micro} 6.1



This document provides the tested procedure to upgrade a {sle-micro} 5.5 host deployed with {productname} 5.0 Server to {sl-micro} 6.1 and migrate to {productname} {productnumber}.

=== Prerequisites

* {productname} 5.0 is installed and running on {sle-micro} 5.5.
* System is registered and has active subscriptions with {scc}.

=== Distribution Upgrade and Server Migration

.Procedure: Migration from {productname} 5.0 to {productname} {productnumber}
[role=procedure]
_____

. Verify Current Product Status

+

[source,console]
----
SUSEConnect --status-text
----

+

Confirm:

- Base OS: `SUSE Linux Enterprise Micro 5.5`
- Extension: `SUSE Manager Server 5.0 Extension`

+

. Ensure system is updated

+

[source,console]
----
transactional-update patch
----

+

--

* If patches were applied, stop the server and then reboot the system before proceeding to migration:

+

[source,console]
----
mgradm stop
reboot
----

* If no updates were found, you can proceed directly to the migration step.

--

+

. Start the migration:

+

[source,console]
----
transactional-update migration --auto-agree-with-licenses --gpg-auto-import-keys
----

+

Follow the prompts and select the available migration to **SUSE Linux Micro 6.1** and **{productname} Server Extension 5.1**.

+

. Stop the server and then reboot to apply changes:

+

[source,console]
----
mgradm stop
reboot
----

+

. Post-Reboot checks:

+

Verify upgraded OS and {productname} extension:
+

[source,console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

You should see:

- `PRETTY_NAME="SUSE Linux Micro 6.1"`
- `SUSE Multi-Linux Manager Server 5.1 Extension`

+

. Enable Root SSH Access (_if required_).
SL Micro 6.1 disables root login via SSH by default.
Edit `/etc/ssh/sshd_config.d/sshd.conf`:

+

[source,console]
----
PermitRootLogin yes
----

+

And restart the service:

+

[source,shell]
----
systemctl restart sshd
----

+

For more information, see xref:administration:troubleshooting/tshoot-remote-root-on-micro.adoc[].

+

. Verify {productname} Tools

+

[source,console]
----
mgradm --version
----

+

Expected output:

+

- Version `5.1.11` or higher
- References `5.1.0` or higher

. Upgrade server containers

+

[source,console]
----
mgradm upgrade podman
----

+

Follow the prompts to pull and configure the new 5.1.0 containers.


. Check running containers:

+

[source,console]
----
podman ps
----

+

You should see:

- `server:5.1.0` or higher
- `server-postgresql:5.1.0` or higher

_____


[NOTE]
====
* Errors for missing services like `uyuni-db` or `saline` during upgrade can be ignored if not installed previously.
====

=== Migration Complete

The system is now running {productname} 5.1 on SL Micro 6.1.
Validate your setup before resuming production operations.
If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-51.adoc[] guide to upgrade the proxy host.



include::../../../snippet-database-backup-volume.adoc[leveloffset=+2]



== {sles} 15 SP6 to 15 SP7

This document provides the tested procedure to upgrade a SUSE Linux Enterprise Server 15 SP6 host deployed with SUSE Multi-Linux Manager 5.0 Server to SUSE Linux Enterprise Server 15 SP7 with SUSE Multi-Linux Manager 5.1.

=== Prerequisites

* SUSE Multi-Linux Manager 5.0 is installed and running on SUSE Linux Enterprise Server 15 SP6.
* The system is registered and has valid subscriptions in SUSE Customer Center (SCC).
* Ensure backups are created before proceeding.



=== Distribution Upgrade and Server Migration

.Procedure:  Migration from {productname} 5.0 to {productname} {productnumber}
[role=procedure]
_____

. Verify current product status

+

[source,console]
----
SUSEConnect --status-text
----

+

Confirm:

+

- Base OS: `SUSE Linux Enterprise Server 15 SP6`
- Extension: `SUSE Manager Server 5.0 Extension`

+

. Apply all system patches

+

[source,console]
----
zypper patch
----

+

. Stop the server, and then reboot if the update stack was updated:

+

[source,console]
----
mgradm stop
reboot
----

+

. Launch the Zypper migration tool

+

[source,console]
----
zypper migration
----

+
Zypper will show the possible migration targets with detailed summaries.
+

. Select the appropriate target, and follow the prompts to complete the migration.

. After the migration completes, stop the server and then reboot the system:

+

[source,console]
----
mgradm stop
reboot
----

+

. Post-Reboot checks:

+

Verify upgraded OS and {productname} extension:
+

[source,console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

You should see:

- `VERSION="15-SP7"`
- `SUSE Multi-Linux Manager Server 5.1 Extension for SLE`

+

. Verify {productname} Tools version

+

[source,console]
----
mgradm --version
----

+

Expected output:

- Version `5.1.11` or higher
- Image tag `5.1.0` or higher

+

. Upgrade server containers

+

[source,console]
----
mgradm upgrade podman
----

+

Follow prompts to pull the new container images and reconfigure the environment.

+

. Check running containers

+

[source,console]
----
podman ps
----

+

Expected containers:

- `server:5.1.0` or higher
- `server-postgresql:5.1.0` or higher

_____

=== Migration Complete

The system is now running {productname} 5.1 on SUSE Linux Enterprise Server 15 SP7.
Validate your setup before resuming production operations.
If you have a {productname} 5.0 proxy connected to this server, proceed with xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-51.adoc[].



include::../../../snippet-database-backup-volume.adoc[leveloffset=+2]

