[[retail-install-uyuni]]
= Install Uyuni Retail Server with openSUSE

{productname} {smr} Server can be installed on openSUSE.

For general requirements, see xref:installation:uyuni-install-requirements.adoc[].

[NOTE]
====
openSUSE Leap의 최신 버전 및 업데이트에 대한 자세한 내용은 https://doc.opensuse.org/release-notes/를 참조하십시오.
====



== openSUSE Leap에 Uyuni 설치

You install Uyuni as an add-on to openSUSE Leap.



.Procedure: Installing Uyuni on openSUSE Leap

. 사용할 수 있는 모든 서비스 팩 및 패키지 업데이트를 적용하여 openSUSE Leap을 기본 시스템으로 설치합니다.
. menu:yast[ 시스템 > 네트워크 설정 > 호스트 이름/DNS]를 통해 확인 가능한 FQDN(정규화된 도메인 이름)을 구성합니다.
. 리포지토리를 생성하기 위해 사용할 변수를 설정합니다.
+
----
repo=repositories/systemsmanagement:/
repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
----
. [systemitem]``루트``로 {productname} 서버 소프트웨어를 설치하기 위한 리포지토리를 추가합니다.
+
----
zypper ar https://download.opensuse.org/$repo uyuni-server-stable
----
. Refresh metadata from the repositories as [systemitem]``root``, and confirm the import of new GPG key into the keyring:
+
----
zypper ref
----
. [systemitem]``루트``로 {productname} 서버에 대한 패턴을 설치합니다.
+
----
zypper in patterns-uyuni_server
----
. Install the {productname} related packages:
+
----
zypper in bind-formula \
	  branch-network-formula \
	  dhcpd-formula \
	  image-sync-formula \
	  pxe-formula \
	  saltboot-formula \
	  susemanager-retail-tools \
	  tftpd-formula \
	  vsftpd-formula

----
. Reboot the client.


When the installation is complete, you can continue with {productname} setup. For more information, see xref:retail:retail-uyuni-server-setup.adoc[].
