ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

ifndef::backend-pdf[]
[[retail-overview]]
= Retail Guide
:revdate: 2025-05-21
:page-revdate: {revdate}

// HTML Publication date 
**게시 날짜:** {docdate}

== 서문


{productname} {smr} {productnumber} is an **open-source infrastructure management solution**, specifically **optimized for the retail industry**. Built on the same technology as {productname}, it has been tailored to meet the unique operational needs of retail organizations.

Designed for **retail environments**, {productname} {smr} supports **point-of-service (POS) terminals**, allowing businesses to manage transactions, promotions, and customer loyalty programs. Beyond retail, it can also be used in **educational institutions** to maintain student computers, as well as in **banks and hospitals** for self-service kiosks.

{productname} {smr} is suited for deployments that include **servers, workstations, point-of-service terminals, and other connected devices**. It enables administrators to **install, configure, and update software across their infrastructure**, while streamlining **deployment and provisioning** of POS machines.

This guide provides a **comprehensive overview** of {productname} {smr}, covering its **initial installation and setup**.

For complete documentation, refer to the **{productname} documentation suite** at https://documentation.suse.com/.

For more details on managing your {productname} {smr} environment or seeking assistance, see xref:retail:retail-next.adoc[]


== 저작권 고지

ifeval::[{mlm-content} == true]
// HTML Copyright
Copyright © {copyrightdate} SUSE LLC and contributors. All rights reserved. 복사, 배포 및/또는 수정할 수 있는 권한은 GNU 자유 문서 라이선스 버전 1.2 또는 (사용자의 선택에 따라) 버전 1.3의 조건에 따라 부여됩니다. 불변 섹션은 본 저작권 고지 및 라이선스입니다. 라이선스 버전 1.2의 사본은 xref:legal:license.adoc[GNU 자유 문서 라이선스]라는 제목의 섹션에 포함되어 있습니다.
endif::[]

ifeval::[{uyuni-content} == true]
// HTML Copyright
Copyright © 2011–2025 Uyuni contributors. All rights reserved. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].
endif::[]

== 상표
// HTML Trademarks
SUSE 상표에 대해서는 https://www.suse.com/company/legal/[]을 참조하십시오. 모든 제3자 상표는 해당 소유자의 자산입니다. 상표 기호(®, ™ 등)는 SUSE 및 그 계열사의 상표를 나타냅니다. 별표(*)는 타사 상표를 나타냅니다. 본 문서의 모든 정보는 세심한 주의를 기울여 편집되었습니다. 하지만 이는 완벽하게 정확함을 보장하지 않습니다. SUSE LLC, 그 계열사, 작성자 및 번역자는 발생할 수 있는 오류나 그로 인한 결과에 대해 책임을 지지 않습니다.
endif::[]

// PDF PREFACE PAGE
ifdef::backend-pdf[]

<<<

:!sectnums:
// Required for preface section of pdf
[preface]
== 서문

Retail | {productname} {productnumber}

{productname} {smr} {productnumber} is an **open-source infrastructure management solution**, specifically **optimized for the retail industry**. Built on the same technology as {productname}, it has been tailored to meet the unique operational needs of retail organizations.

Designed for **retail environments**, {productname} {smr} supports **point-of-service (POS) terminals**, allowing businesses to manage transactions, promotions, and customer loyalty programs. Beyond retail, it can also be used in **educational institutions** to maintain student computers, as well as in **banks and hospitals** for self-service kiosks.

{productname} {smr} is suited for deployments that include **servers, workstations, point-of-service terminals, and other connected devices**. It enables administrators to **install, configure, and update software across their infrastructure**, while streamlining **deployment and provisioning** of POS machines.

This guide provides a **comprehensive overview** of {productname} {smr}, covering its **initial installation and setup**.

ifeval::[{mlm-content} == true] For complete documentation, refer to the **{productname} documentation suite** at https://documentation.suse.com/. endif::[]

For more details on managing your {productname} {smr} environment or seeking assistance, see xref:retail:retail-next.adoc[].

// PDF Publication

**게시 날짜:** {docdate}

// PDF Copyright
Copyright © 2006–2025 SUSE LLC and contributors. All rights reserved. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].

// PDF Trademarks
SUSE 상표에 대해서는 https://www.suse.com/company/legal/[]을 참조하십시오. 모든 제3자 상표는 해당 소유자의 자산입니다. 상표 기호(®, ™ 등)는 SUSE 및 그 계열사의 상표를 나타냅니다. 별표(*)는 타사 상표를 나타냅니다. 본 문서의 모든 정보는 세심한 주의를 기울여 편집되었습니다. 하지만 이는 완벽하게 정확함을 보장하지 않습니다. SUSE LLC, 그 계열사, 작성자 및 번역자는 발생할 수 있는 오류나 그로 인한 결과에 대해 책임을 지지 않습니다.

<<<

toc::[]

:sectnums:

endif::[]
