[[autoinst-profiles]]
= 自動インストールプロファイル
:revdate: 2025-07-08
:page-revdate: {revdate}

{productname}内では、インストールするクライアントのオペレーティングシステムに応じて、2つの異なる種類のプロファイルを使用できます。

* {sle}クライアントまたは{opensuse}クライアントの場合、{ay}を使用します。
* {rhel}クライアントの場合、{kickstart}を使用します。

自動インストールプロファイルによって、オペレーティングシステムをインストールする方法が決定されます。 たとえば、インストーラに渡す追加のカーネルパラメータを指定できます。

プロファイルの最も重要な部分は、**自動インストールファイル**です。 インストールを手動で実行する場合、パーティション設定、ネットワーク情報、ユーザの詳細などの情報をインストーラに提供する必要があります。 自動インストールファイルは、スクリプト形式でこの情報を提供する方法です。 このタイプのファイルは、**回答ファイル**と呼ばれることもあります。

異なるオペレーティングシステムでクライアントをインストールする場合、{ay}プロファイルと{kickstart}プロファイルの両方を使用できます。

* プロファイルを宣言する方法については、xref:client-configuration:autoinst-profiles.adoc#declare-profile[プロファイルを宣言する]を参照してください。
* {ay}プロファイルについては、xref:client-configuration:autoinst-profiles.adoc#autoyast[{ay}プロファイル]を参照してください。
* {kickstart}プロファイルについては、xref:client-configuration:autoinst-profiles.adoc#kickstart[Kickstartプロファイル]を参照してください。

プロファイルに含まれる自動インストールファイルには、変数とコードスニペットを格納できます。 変数とコードスニペットについては、xref:client-configuration:autoinst-profiles.adoc#templates-syntax[テンプレートの構文]を参照してください。



[[declare-profile]]
== プロファイルを宣言する


自動インストールファイルとディストリビューションの準備ができたら、プロファイルを作成して、{productname}サーバで自動インストールを管理できます。プロファイルにより、選択したこのディストリビューションのインストール方法が決定されます。プロファイルを作成する1つの方法は{ay}ファイルまたは{kickstart}ファイルをアップロードする方法です。または、{kickstart}のみの場合、{webui}ウィザードを使用できます。



.プロシージャ: アップロードによる自動インストールプロファイルの作成

. {productname}の{webui}で、menu:システム[自動インストール > プロファイル]に移動します。

. btn:[キックスタート/{ay}ファイルをアップロード]をクリックします。

. ［[guimenu]``ラベル``］フィールドにプロファイルの名前を入力します。 スペースは使用しません。

. ［[guimenu]``自動インストールツリー``］フィールドで、このプロファイルに使用する自動インストールのディストリビューションを選択します。

. ［[guimenu]``仮想化タイプ``］フィールドで、このプロファイルに使用する仮想化の種類を選択します。または、このプロファイルを使用して新しい仮想マシンを作成しない場合には［``なし``］を選択します。

. 自動インストールファイルの内容を［[guimenu]``ファイルの内容``］フィールドにコピーするか、または［[guimenu]``アップロードするファイル``］フィールドを使用してファイルを直接アップロードします。
+

ここに記載する詳細については、xref:client-configuration:autoinst-profiles.adoc#autoyast[{ay}プロファイル]またはxref:client-configuration:autoinst-profiles.adoc#kickstart[Kickstartプロファイル]を参照してください。

. btn:[作成]をクリックしてプロファイルを作成します。



.プロシージャ: ウィザードで{kickstart}プロファイルを作成する

. {productname}の{webui}で、menu:システム[自動インストール > プロファイル]に移動します。

. btn:[キックスタートプロファイルを作成]をクリックします。

. ［[guimenu]``ラベル``］フィールドにプロファイルの名前を入力します。 スペースは使用しません。

. ［[guimenu]``ベースチャンネル``］フィールドで、このプロファイルに使用するベースチャンネルを選択します。このフィールドは利用できるディストリビューションから入力されます。 必要なベースチャンネルが利用できない場合、ディストリビューションを正しく作成したことを確認してください。

. ［[guimenu]``仮想化タイプ``］フィールドで、このプロファイルに使用する仮想化の種類を選択します。または、仮想化しない場合には［``なし``］を選択します。

. btn:[次へ]をクリックします。

. ［[guimenu]``配信ファイルの場所``］で、{productname}サーバにインストールするインストールメディアへのパスを入力します。

. btn:[次へ]をクリックします。

. クライアントのrootユーザのパスワードを入力します。

. btn:[完了]をクリックします。

. 新しいプロファイルの詳細を確認し、必要に応じてカスタマイズします。

自動インストールプロファイルを作成している場合、［[guimenu]``このベースチャンネルに最新のツリーを常に使用します``］にチェックを付けることができます。 この設定では、指定ベースチャンネルに関連付けられた最新ディストリビューションを{productname}で自動選択できます。 新しいディストリビューションを後で追加する場合、{productname}は、最後に作成または変更されたディストリビューションを使用します。

[guimenu]``仮想化の種類``を変更すると、通常、プロファイルのブートローダおよびパーティションオプションを変更する必要があります。 この操作を実行すると、カスタマイズが上書きされます。 新しい設定または変更した設定を保存前に確認します。そのためには、［[guimenu]``パーティション設定``］タブに移動します。

ディストリビューションとプロファイルのカーネルオプションは統合されます。

自動インストールプロファイルの詳細および設定を変更できます。そのためには、menu:システム[自動インストール > プロファイル]に移動し、編集するプロファイルの名前をクリックします。 または、menu:システム[システム一覧]に移動し、プロビジョニングするクライアントを選択し、menu:プロビジョニング[自動インストール]サブタブに移動します。



[[autoyast]]
== {ay}プロファイル

{ay}プロファイルは、プロファイルを識別する[guimenu]``ラベル``、自動インストールのディストリビューションをポイントする[guimenu]``自動インストールツリー``、さまざまなオプション、最も重要な{ay}インストールファイルで構成されます。

{ay}インストールファイルは、{ay}インストーラに指示を与えるXMLファイルです。{ay}では、「制御ファイル」と呼ばれます。 {ay}インストールファイルの構文の詳細については、link:https://doc.opensuse.org/projects/autoyast/#cha-configuration-installation-options[]を参照してください。

{suse}には、独自のカスタムファイルの雛形として使用できる{ay}インストールファイルのテンプレートが用意されています。 このテンプレートは、link:https://github.com/SUSE/manager-build-profiles[]の[path]``AutoYast``ディレクトリにあります。 各プロファイルを使用するにはその前に、一部の変数を設定する必要があります。 スクリプトに含まれている[path]``README``ファイルを確認して、必要な変数を判別してください。 {ay}スクリプトで変数を使用する方法の詳細については、xref:client-configuration:autoinst-profiles#variables[変数]を参照してください。

[IMPORTANT]
====
提供されている{ay}テンプレートでは、ユーザパスワードは設定されません。 rootアカウントやその他のユーザアカウントとパスワード、またはその他の認証手段の設定を検討してください。 {ay}プロファイル内のユーザアカウントの詳細については、link:https://doc.opensuse.org/projects/autoyast/#Configuration-Security-users-and-groups[]を参照してください。
====

{productname}でインストールするための{ay}インストールファイルで、最も重要なセクションを次に示します。

* ``<add-on>``を使用すると、子チャンネルをインストールに追加できます。例については、link:https://doc.opensuse.org/projects/autoyast/#Software-Selections-additional[]を参照してください。
+
* ``<general>$SNIPPET('spacewalk/sles_no_signature_checks')</general>``は、署名のチェックを無効にします。

* ``<software>``によって、{unifiedinstaller}に製品を指定できます。
** 「<software>」の例については、link:https://doc.opensuse.org/projects/autoyast/#CreateProfile-Software[]を参照してください。
+
* ``<init-scripts config:type="list">$SNIPPET('spacewalk/minion_script ')</init-scripts>``は、クライアントをSaltクライアントとして{productname}に登録できるようにします。
+
* ``<pre-scripts config:type="list">$SNIPPET('spacewalk/root_ca')</pre-scripts>`` will copy and deploy the server SSL CA certificate on the new machine.
+
``<add-on><add_on_products config:type="list">$SNIPPET('spacewalk/autoyast_channels')</add_on_products></add-on>`` automatically adds all the channels of the selected distribution as sources. For more information about {ay}, see https://doc.opensuse.org/projects/autoyast/.

{ay}に代わる{salt}ベースの最近のプロファイルには、Yomiがあります。Yomiについては、xref:specialized-guides:salt/salt-yomi.adoc[Yomiを使用してインストールする]を参照してください。



[[kickstart]]
== キックスタートプロファイル

{kickstart}プロファイルには、多数の設定オプションがあります。 プロファイルを作成するには、プロファイルをアップロードするか、専用のウィザードを使用します。

{kickstart}プロファイルでは、ファイル保持一覧を使用できます。 {kickstart}で再インストールするクライアントにあるカスタム設定ファイルが多数ある場合、リストにしてこれらのファイルを保存し、そのリストを{kickstart}プロファイルに関連付けることができます。



.プロシージャ: ファイル保持一覧の作成

. {productname}の{webui}で、menu:システム[自動インストール > ファイル保持]に移動し、btn:[ファイル保持一覧の作成]をクリックします。

. 適切なラベルを入力し、保存するすべてのファイルおよびディレクトリへの絶対パスをリストします。

. btn:[一覧の作成]をクリックします。

. {kickstart}プロファイルにファイル保持一覧を含めます。

. menu:システム[自動インストール > プロファイル]に移動して編集するプロファイルを選択し、menu:システムの詳細[ファイル保持]サブタブに移動して、含めるファイル保持一覧を選択します。

[NOTE]
====
ファイル保持一覧の合計サイズは1{nbsp}MBに制限されています。 [path]``/dev/hda1``や[path]``/dev/sda1``などの特殊なデバイスは保持できません。 ファイル名とディレクトリ名のみ使用できます。正規表現のワイルドカードは使用できません。
====

Kickstartの詳細については、Red Hatのドキュメントを参照してください。



[[templates-syntax]]
== テンプレートの構文

インストールファイルの一部は、インストール中に置き換えられます。 変数は単一の値に置き換えられ、コードスニペットはテキストのセクション全体に置き換えられます。 エスケープされた記号やセクションは置き換えられません。

{cobbler}はCheetahと呼ばれるテンプレートエンジンを使用して、このような置き換えを実行できます。このメカニズムにより、システムごとにプロファイルを手動で作成する必要なく、多数のシステムを再インストールできます。

自動インストールの変数やコードスニペットは、{productname}　{webui}内で作成できます。 プロファイル内の［[guimenu]``自動インストールファイル``］タブでは、置き換えの結果を確認できます。

* 変数については、xref:client-configuration:autoinst-profiles#variables[変数]を参照してください。
* コードスニペットについては、xref:client-configuration:autoinst-profiles#code-snippets[コードスニペット]を参照してください。
* エスケープ記号またはテキストブロックについては、xref:client-configuration:autoinst-profiles#escaping[エスケープ]を参照してください。



[[variables]]
=== 変数

自動インストールの変数は、{kickstart}プロファイルおよび{ay}プロファイルに値を代入するために使用できます。 変数を定義するには、プロファイルから［[guimenu]``変数``］サブタブに移動し、テキストボックスで[replaceable]``name=value``ペアを作成します。

たとえば、クライアントのIPアドレスを格納する変数と、ゲートウェイのアドレスを格納する変数を作成できます。 次に、作成した変数は、同じプロファイルからインストールされるすべてのクライアントに対して定義できます。 このためには、［[guimenu]``変数``］テキストボックスに次の行を追加します。

----
ipaddr=192.168.0.28
gateway=192.168.0.1
----

変数を使用するには、プロファイルで値の前に[option]``$``記号を付けて値を代入します。 たとえば、{kickstart}ファイルの［[option]``ネットワーク``］部分は次のようになることがあります。

----
network --bootproto=static --device=eth0 --onboot=on --ip=$ipaddr \
  --gateway=$gateway
----

[option]``$ipaddr``は``192.168.0.28``に解決され、[option]``$gateway``は``192.168.0.1``に解決されます。

インストールファイルでは、変数は階層的に使用します。 システム変数はプロファイル変数より優先され、プロファイル変数はディストリビューション変数より優先されます。



[[code-snippets]]
=== コードスニペット

{productname}には、多数の定義済みコードスニペットが付属しています。menu:システム[自動インストール > 自動インストールスニペット]に移動し、既存のスニペットの一覧を表示します。

自動インストールファイルの[option]``$SNIPPET()``マクロに挿入してスニペットを使用します。 たとえば、{kickstart}では次のようになります。

----
$SNIPPET('spacewalk/redhat_register_using_salt')
----

または、{ay}では次のようになります。

----
<init-scripts config:type="list">
  $SNIPPET('spacewalk/minion_script')
</init-scripts>
----

このマクロは{cobbler}によって解析され、スニペットの内容に置き換えられます。独自のコードスニペットを保存して、後で自動インストールファイルで使用することもできます。btn:[スニペットの作成]をクリックして、新しいコードスニペットを作成します。

この例では、一般的なハードドライブのパーティション設定の{kickstart}スニペットが設定されます。

----
clearpart --all
part /boot --fstype ext3 --size=150 --asprimary
part / --fstype ext3 --size=40000 --asprimary
part swap --recommended

part pv.00 --size=1 --grow

volgroup vg00 pv.00
logvol /var --name=var vgname=vg00 --fstype ext3 --size=5000
----

たとえば、次のようにスニペットを使用します。

----
$SNIPPET('my_partition')
----



[[escaping]]
=== エスケープ

自動インストールファイルには、``$(example)``のようなシェルスクリプト変数が含まれています。コンテンツはバックスラッシュ(円記号)でエスケープする必要があります``\$(example)``。 ``$``記号をエスケープすると、テンプレートエンジンは記号を内部変数として評価しなくなります。

// FIXME 2023-09-12, ke: "#raw" or "#end raw"?
コードフラグメントやスクリプトなどのテキストブロックは、``\#raw``ディレクティブおよび``\#end raw``ディレクティブで囲むことによってエスケープできます。 次に例を示します。

// FIXME 2023-09-12, ke: "#raw" or "#end raw"?
----
#raw
#!/bin/bash
for i in {0..2}; do
 echo "$i - Hello World!"
done
#end raw
----

``#``記号の後にスペースがある行はコメントとして扱われるため、評価されません。 次に例を示します。

----
# start some section (this is a comment)
echo "Hello, world"
# end some section (this is a comment)
----
