[[autoinstallation]]
= オペレーティングシステムのインストール
:revdate: 2025-05-20
:page-revdate: {revdate}

一般に、すでに動作しているクライアントを登録します。 {productname}に登録する直前にコンピュータに手動でインストールするか、環境に{productname}を追加する前にインストールされた既存のシステムを使用できます。

または、{productname}を使用して、1回の手順でオペレーティングシステムをインストールして{productname}に登録することもできます。 この方法では一部または全部が自動化されているため、インストーラの質問に答える時間を節約することができます。これは、特にインストールと登録が必要な多くのクライアントがある場合に役立ちます。

{productname}からオペレーティングシステムをインストールするには次のような複数の方法があります。

* 登録済みのクライアントでインプレースインストールを行う
* PXEブートを使用してネットワークを通じてインストールする
* インストール用CD-ROMまたはUSBメモリを準備し、そのメディアでコンピュータをブートする
* {productname} {smr}ソリューションの一部としてインストールする。

インプレースでの再インストール方法は、以前のオペレーティングシステムがクライアントにすでにインストールされており、クライアントが{productname}にすでに登録されていることを前提としています。

インプレースインストール方法については、xref:client-configuration:autoinst-reinstall.adoc[登録済みシステムを再インストールする]を参照してください。

ネットワークブートによるインストール方法は、フォーマットされていないコンピュータで動作します。 ただし、これは次のような特定のネットワーク構成のみで実行できます。

* {productname}サーバまたはそのプロキシのいずれかが、インストール対象のコンピュータと同じローカルネットワーク上にあるか、経路にあるすべてのルータを中継できるDHCPリレーに対応している。
* 新しいDHCPサーバをセットアップするか、既存のDHCPサーバを設定することができる。
* インストール対象のクライアントがPXEブートに対応しており、PXEブートを実行するように設定することができる。

//For information about the network boot method, see xref:client-configuration:autoinst-pxeboot.adoc[Install via the Network].

リムーバブルメディアを使用する方法では、このようなネットワーク上の制約を受けません。 しかし、この方法はコンピュータがCD-ROMまたはUSBメモリを読み取ることができ、各メディアからブートできることを前提としています。 また、クライアントコンピュータに対する物理的なアクセスも必要です。

リムーバブルメディアを使用する方法については、xref:client-configuration:autoinst-cdrom.adoc[CD-ROMまたはUSBメモリを使用してインストールする]を参照してください。

ifeval::[{mlm-content} == true]

{productname} {smr}アプローチについては、xref:retail:retail-overview.adoc[リテールガイド]を参照してください。
endif::[]

ifeval::[{uyuni-content} == true]

{productname} {smr}アプローチについては、xref:retail:uyuni-retail-overview.adoc[リテールガイド]を参照してください。
endif::[]

[NOTE]
====
{ubuntu}クライアントと{debian}クライアントの自動インストールはサポートされていません。 これらのオペレーティングシステムは、手動でインストールする必要があります。
====

{productname}の自動インストール機能は、{cobbler}という名前のソフトウェアによって実行されます。{cobbler}の詳細については、link:https://cobbler.readthedocs.io[]を参照してください。

[NOTE]
====
{suse}は、{productname} {webui}または{productname} APIで使用できる{cobbler}の機能のみをサポートしています。 Cobblerがサポートする唯一のコマンドラインコマンドは[command]``buildiso``です。 ここにはサポートされている機能のみが記載されています。
====
