[[channels]]
= ソフトウェアチャンネル

チャンネルは、ソフトウェアパッケージをグループ化する方法です。 ソフトウェアパッケージはリポジトリによって提供され、リポジトリはチャンネルに関連付けられています。 クライアントをソフトウェアチャンネルにサブスクライブすると、クライアントは、これに関連付けられたソフトウェアをインストールし、更新できます。

{productname}では、チャンネルはベースチャンネルと子チャンネルに分割されます。 この方法でチャンネルを編成すると、互換性のあるパッケージのみが各システムにインストールされるようになります。 クライアントは、1つのベースチャンネルのみをサブスクライブして、登録中にクライアントのオペレーティングシステムおよびアーキテクチャに基づいて割り当てる必要があります。 ベンダによって提供される有料チャンネルでは、関連づけされたサブスクリプションを持っている必要があります。

ベースチャンネルは、特定のオペレーティングシステムの種類、バージョン、およびアーキテクチャのために構築されたパッケージから構成されています。 たとえば、{sles}{nbsp}15 {x86_64}のベースチャンネルには、そのオペレーティングシステムおよびアーキテクチャと互換性のあるソフトウェアのみが含まれています。

子チャンネルはベースチャンネルに関連付けられていて、ベースチャンネルと互換性のあるパッケージのみを提供します。 システムは、ベースチャンネルの複数の子チャンネルにサブスクライブできます。 システムがベースチャンネルに割り当てられている場合、そのシステムは関連する子チャンネルをインストールできます。 たとえば、システムが{sles}{nbsp}15 `x86_64`ベースチャンネルに割り当てられている場合、互換性のあるベースチャンネルまたは関連する子チャンネルのいずれかから利用できるパッケージのみインストールまたは更新できます。

{productname}の{webui}で、menu:ソフトウェア[チャンネル一覧 > すべて]に移動して、利用できるチャンネルをブラウズできます。 menu:ソフトウェア[管理 > チャンネル]に移動して、チャンネルを変更又は新しいチャンネルを作成できます。

Saltクライアントでは、パッケージをインストールできるチャンネルにサブスクライブした後、highstateを適用する必要があります。

カスタムチャンネルなどチャンネルを使用する方法の詳細については、xref:administration:channel-management.adoc[]を参照してください。



== {phub}で提供されるパッケージ

{phub}は{sle}製品の拡張機能で、{opensuse}コミュニティで提供する追加オープンソースソフトウェアを提供しています。

[IMPORTANT]
====
{phub}のパッケージは、{opensuse}コミュニティによって提供されます。 パッケージは{suse}ではサポートされていません。
====

クライアントで{sle}オペレーティングシステムを使用している場合、{phub}拡張機能を有効にして、これらの追加パッケージにアクセスできます。 アクセスすると、クライアントのサブスクライブ先にできる{phub}チャンネルが提供されます。

{phub}は多数のパッケージを提供しており、大量のディスク容量を使用してパッケージの同期に長時間かかる場合があります。 提供するパッケージが必要でない場合、{phub}を有効にしないでください。

サポートされていないパッケージを誤ってインストールまたは更新しないためには、最初にすべての{phub}パッケージを拒否するコンテンツライフサイクル管理戦略の実装をお勧めします。 その後、必要なパッケージを明示的に有効にできます。 コンテンツライフサイクル管理の詳細については、xref:administration:content-lifecycle.adoc[]を参照してください。



== AppStreamで提供されるパッケージ

{redhat}ベースのクライアントの場合、AppStreamから追加パッケージを利用できます。 ほとんどの場合、AppStreamパッケージでは、必要なソフトウェアをすべて持っていることを確認する必要があります。

{productname}の{webui}でAppStreamパッケージを管理している場合、パッケージの更新に関して相反する推奨事項が表示される場合があります。 これは、{productname}でモジュールのメタデータを正しく解釈できないことが原因です。 コンテンツライフサイクル管理(CLM)のAppStreamフィルタを使用して、AppStreamリポジトリを非モジュール型リポジトリに変換して、一部の更新操作で使用できます。 CLM AppStreamフィルタの詳細については、xref:administration:content-lifecycle-examples.adoc[]を参照してください。



== EPELで提供されるパッケージ

{redhat}ベースのクライアントの場合、EPEL(エンタープライズ版Linux用の追加パッケージ)から追加パッケージを利用できます EPELはオプションのパッケージリポジトリで、追加ソフトウェアが提供されます。

[IMPORTANT]
====
EPELのパッケージは、Fedoraコミュニティによって提供されます。 このパッケージは{suse}ではサポートされていません。
====

クライアントで{redhat}オペレーティングシステムを使用している場合、EPEL拡張機能を有効にして、これらの追加パッケージにアクセスできます。 アクセスすると、クライアントのサブスクライブ先にできるEPELチャンネルが提供されます。

EPELは多数のパッケージを提供しており、大量のディスク容量を使用してパッケージの同期に長時間かかる場合があります。 提供するパッケージが必要でない場合、EPELリポジトリを有効にしないでください。

サポートされていないパッケージを誤ってインストールまたは更新しないためには、最初にすべてのEPELパッケージを拒否するコンテンツライフサイクル管理(CLM)戦略の実装をお勧めします。 その後、必要なパッケージを明示的に有効にできます。 コンテンツライフサイクル管理の詳細については、xref:administration:content-lifecycle.adoc[]を参照してください。



== {sle}クライアントのUnified Installer更新チャンネル

このチャンネルは、オペレーティングシステムをインストールする前に、Unified Installerが最新であることを確認するためにUnified Installerで使用されます。 すべての{sle}製品は、インストール中にインストーラ更新チャンネルにアクセスできる必要があります。

For {sles} clients the installer updates channel is synchronized by default when you add a product that contains them, and are enabled when you create an autoinstallable distribution with these product channels.

For all other {sle} variants, including {sle} for SAP, you must add the installer updates channel manually. To do this, clone the appropriate {sles} installer updates channel below the base channel of these {sle} variants. When creating an autoinstallable distribution for these {sle} variants after the channel was cloned, it is used automatically.
