ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

ifndef::backend-pdf[]
[[client-cfg-overview]]
= クライアント設定ガイド
:revdate: 2025-05-21
:page-revdate: {revdate}

// HTML Publication date 
**発行日:** {docdate}

== 序文


{productname}インストール後の最初のステップは、クライアントの登録です。これらのクライアントの管理は、ワークフローの重要な部分となります。

{productname}は{sle}およびその他のLinuxディストリビューションをサポートし、さまざまなハードウェアオプション間での互換性を提供します。

サポートされているクライアントおよび機能の一覧については、xref:client-configuration:supported-features.adoc[サポートされているクライアントと機能]を参照してください。

このガイドでは、手動と自動両方のクライアント登録と設定について説明します。

== 著作権通知

ifeval::[{mlm-content} == true]
// HTML Copyright
Copyright © {copyrightdate} SUSE LLC and contributors. All rights reserved. この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]セクションに含まれています。
endif::[]

ifeval::[{uyuni-content} == true]
// HTML Copyright
Copyright © 2011–2025 Uyuni contributors. All rights reserved. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].
endif::[]

== 商標
// HTML Trademarks
SUSEの商標については、link:https://www.suse.com/company/legal/[]を参照してください。その他の第三者のすべての商標は、各社の所有に帰属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。本書のすべての情報は、細心の注意を払って編集されています。しかし、このことは絶対に正確であることを保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。
endif::[]

ifdef::backend-pdf[]

<<<

:!sectnums:


[preface]
== 序文

Client Configuration Guide | {productname} {productnumber}

{productname}インストール後の最初のステップは、クライアントの登録です。これらのクライアントの管理は、ワークフローの重要な部分となります。

{productname}は{sle}およびその他のLinuxディストリビューションをサポートし、さまざまなハードウェアオプション間での互換性を提供します。

サポートされているクライアントおよび機能の一覧については、xref:client-configuration:supported-features.adoc[サポートされているクライアントと機能]を参照してください。

このガイドでは、手動と自動両方のクライアント登録と設定について説明します。

// PDF Publication

**発行日:** {docdate}

ifeval::[{mlm-content} == true]
// PDF Copyright
Copyright © {copyrightdate} SUSE LLC and contributors. All rights reserved. この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]セクションに含まれています。
endif::[]

ifeval::[{uyuni-content} == true]
// PDF Copyright
Copyright © 2011–2025 Uyuni contributors. All rights reserved. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].
endif::[]

// PDF Trademarks
SUSEの商標については、link:https://www.suse.com/company/legal/[]を参照してください。その他の第三者のすべての商標は、各社の所有に帰属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。本書のすべての情報は、細心の注意を払って編集されています。しかし、このことは絶対に正確であることを保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。

<<<

toc::[]

:sectnums:

endif::[]
