[[clients-oracle]]
= {oracle}クライアントの登録

このセクションでは、{oracle}オペレーティングシステムを実行している従来のクライアントおよびSaltクライアントの登録について説明します。

ifeval::[{suma-content} == true]
[IMPORTANT]
====
{oracle}リポジトリのURLは{scc}で使用できますが、パッケージおよびメタデータは{suse}ではなくOracleから提供されます。 {oracle}ベースメディアリポジトリはhttps://yum.oracle.com/から無料でダウンロードできます。
====
endif::[]


[IMPORTANT]
====
従来のクライアントは{oracle}{nbsp}8では使用できません。 {oracle}{nbsp}8クライアントはSaltクライアントとしてのみサポートされます。
====


== ソフトウェアチャンネルの追加

{oracle}クライアントを{productname}サーバに登録する前に、必要なソフトウェアチャンネルを追加して同期する必要があります。

ifeval::[{suma-content} == true]

このプロシージャで必要な製品は次のとおりです。

[[oracle-channels-wizard]]
[cols="1,1", options="header"]
.Oracle製品 - WebUI
|===
| OSバージョン | 製品名
|{oracle} 6 | Oracle Linux 6 x86_64
 | {oracle} 7 | Oracle Linux 7 x86_64
 | {oracle} 8 | Oracle Linux 8 x86_64
|===

include::snippets/addchannels_vendor_webui.adoc[]

または、コマンドプロンプトでチャンネルを追加できます。 このプロシージャで必要なチャンネルは次のとおりです。

[[oracle-channels-suma-cli]]
[cols="1,1", options="header"]
.Oracleチャンネル - CLI
|===
| OSバージョン | ベースチャンネル
|{oracle} 6 | oraclelinux6-x86_64
 | {oracle} 7 | oraclelinux7-x86_64
 | {oracle} 8 | oraclelinux8-x86_64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]
このプロシージャで必要なチャンネルは次のとおりです。

[[oracle-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.Oracleチャンネル - CLI
|===

| OSバージョン
|ベースチャンネル
 | クライアントチャンネル
 | チャンネルの更新
 
 | {oracle} 6
 | oraclelinux6
 | oraclelinux6-uyuni-client
 | -
 
 | {oracle} 7
 | oraclelinux7
 | oraclelinux7-uyuni-client
 | -
 
 | {oracle} 8
 | oraclelinux8
 | oraclelinux8-uyuni-client
 | oraclelinux8-appstream

|===

include::snippets/addchannels_novendor_cli.adoc[]

[NOTE]
====
[command]``spacewalk-common-channels``によって提供されるクライアントツールのチャンネルの提供元は{uyuni}です。{suse}ではありません。
====

endif::[]

[IMPORTANT]
====
{oracle} 8クライアントでは、ベースチャンネルとAppStreamチャンネルの両方を追加します。 両方のチャンネルのパッケージが必要です。 両方のチャンネルを追加しないと、パッケージ不足のためブートストラップリポジトリを作成できません。
====


include::snippets/appstream_admon.adoc[]



== 同期ステータスの確認

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]



== アクティベーションキーの作成

{oracle}チャンネルと関連付けられているアクティベーションキーを作成する必要があります。

アクティベーションキーの詳細については、xref:client-configuration:activation-keys.adoc[]を参照してください。




== クライアントでGPGキーを信頼する

include::snippets/trust_gpg.adoc[]




== クライアントの登録

{oracle}クライアントは、その他すべてのクライアントと同じ方法で登録されます。 詳細については、xref:client-configuration:registration-overview.adoc[]を参照してください。


[WARNING]
====
{oracle}{nbsp}6クライアントを登録して使用するには、{productname}サーバを設定して旧式のSSL暗号化をサポートする必要があります。 このエラーを解決する方法については、``古いクライアントの登録``をxref:client-configuration:tshoot-clients.adoc[]で参照してください。
====
