[[clients-sle]]
= {sle}クライアントの登録

このセクションでは、次の{sle}オペレーティングシステムを実行しているクライアントの登録について説明します。

* {sles}{nbsp}15{nbsp}SP1
* {sles}{nbsp}15{nbsp}SP2


{sles} for SAP、{sle} Desktop、{sle} HPC、{sle} Real Timeなど、すべての{sle}製品を準備するには、この章の手順に従ってください。 また、古い{sle}バージョンやサービスパックの手順にも使用できます。



== ソフトウェアチャンネルの追加

{sle}クライアントを{productname}サーバに登録する前に、必要なソフトウェアチャンネルを追加して同期する必要があります。

このプロシージャで必要な製品は次のとおりです。

[[sle-channels-wizard]]
[cols="1,1", options="header"]
.SLE製品 - WebUI
|===

| OSバージョン
|製品名
 
 | {sles} 15 SP1
 | SUSE Linux Enterprise Server 15 SP1 x86_64
 
 | {sles} 15 SP2
 | SUSE Linux Enterprise Server 15 SP2 x86_64


|===

include::snippets/addchannels_vendor_webui.adoc[]

または、コマンドプロンプトでチャンネルを追加できます。 このプロシージャで必要なチャンネルは次のとおりです。

[[sle-channels-cli]]
[cols="1,1", options="header"]
.SLE製品 - CLI
|===

| OSバージョン
|ベースチャンネル
 
 | {sles} 15 SP1
 | sle-product-sles15-sp1-pool-x86_64
 
 | {sles} 15 SP2
 | sle-product-sles15-sp2-pool-x86_64


|===

include::snippets/addchannels_vendor_cli.adoc[]



ifeval::[{uyuni-content} == true]

クライアントツールを追加するには、コマンドプロンプトからこれらのチャンネルを追加します。

[[sle-tools-channels-cli]]
[cols="1,1", options="header"]
.SUSE Linux Enterprise Channels - CLI
|===

| OSバージョン
|クライアントチャンネル
 
 | {sles} 15 SP1
 | sles15-sp1-uyuni-client
 
 
 | {sles} 15 SP2
 | sles15-sp2-uyuni-client

|===

include::snippets/addchannels_novendor_cli.adoc[]

endif::[]



== 同期ステータスの確認

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]

include::snippets/check_sync_cli.adoc[]

[IMPORTANT]
====
{sle}チャンネルは非常に大きいことがあります。 同期に数時間かかる場合があります。
====



ifeval::[{uyuni-content} == true]
== クライアントでGPGキーを信頼する

include::snippets/trust_gpg.adoc[]

[NOTE]
====
{sles}{nbsp}15と{sles}{nbsp}12クライアントの両方で同じGPGキーを使用します。 正しいキーは``sle12-gpg-pubkey-39db7c82.key``と呼ばれます。
====

endif::[]



== クライアントの登録

{sle}クライアントを登録するには、ブートストラップリポジトリが必要です。 デフォルトでは、ブートストラップリポジトリは自動的に作成され、すべての同期製品に対して毎日再生成されます。 次のコマンドを使用して、コマンドプロンプトからブートストラップリポジトリを手動で作成できます。

----
mgr-create-bootstrap-repo
----

クライアントの登録については、xref:client-configuration:registration-overview.adoc[]を参照してください。
