[[client-upgrades-uyuni]]
= Uyuniクライアントのアップグレード
:revdate: 2025-02-26
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

このセクションでは、例としてopenSUSE Leapを使用します。

== アップグレードの準備


.プロシージャ: クライアントのアップグレードの準備
. {productname} サーバのコマンドプロンプトで root になり、[command]``spacewalk-common-channels`` コマンドを特定のチャンネルに対して実行します。
+
----
spacewalk-common-channels \
opensuse_leap15_4\
opensuse_leap15_4-non-oss \
opensuse_leap15_4-non-oss-updates \
opensuse_leap15_4-updates \
opensuse_leap15_4-uyuni-client
----

. すべてのチャンネルを[command]``spacewalk-repo-sync``で完全に同期します。
+
// These are custom channels.
// For more information, see xref:client-configuration:clients-opensuse.adoc[].

. {productname}サーバの{webui}で、menu:ソフトウェア[管理 > チャンネル]に移動し、[systemitem]``Uyuni Client Tools for openSUSE Leap 15.4 (x86_64)``チャンネル名をクリックします。

. 右上隅のbtn:[チャンネルの管理]をクリックします。

. ［[guimenu]``リポジトリ``］タブをクリックし、［[systemitem]``External - Uyuni Client Tools for openSUSE Leap 15.3 (x86_64)``］を選択します。

. btn:[Update Repositories]（リポジトリの更新）をクリックします。

. menu:リポジトリ[同期]サブタブに移動し、btn:[今すぐ同期]をクリックします。

. [systemitem]``openSUSE Leap 15.4 (x86_64)``および[systemitem]``External - openSUSE Leap 15.3 (x86_64)``で同じ操作をします。

[systemitem]``openSUSE Leap 15.4 (x86_64)``を展開し、パッケージが入力されているすべての子チャンネルを表示します。



== アップグレード

クライアントをアップグレードするには、ソフトウェアリポジトリを置き換え、ソフトウェアを更新し、最後にクライアントを再起動します。



.プロシージャ: クライアントのアップグレード

. {productname}サーバの{webui}で、menu:システム[]に移動し、クライアントの名前をクリックします。
. menu:ソフトウェア[ソフトウェアチャンネル]をクリックし、[systemitem]``カスタムチャンネル``一覧にリストされているopenSUSE Leap {opensuse-version}チャンネルをベースチャンネルとして選択します。
. ［[guimenu]``子チャンネル``］ペインで、{opensuse-version}子チャンネルを選択します。
. btn:[次へ]、［[guimenu]``ソフトウェアチャンネルの変更確認``］、btn:[確認]をクリックします。
. menu:ソフトウェア[パッケージ > アップグレード]をクリックし、クライアントで更新するパッケージをすべて選択してから、選択を適用します。 btn:[パッケージのアップグレード]をクリックし、詳細を確認し、btn:[確認]をクリックして更新を終了します。
. クライアントを再起動します。

多数のクライアントを更新する必要がある場合、{productname}サーバでこのコマンドシーケンスのアクションチェーンを作成できます。 アクションチェーンを使用して、複数のクライアントで同時に更新を実行できます。


////
. Assign the new channels to the clients instead of the old channels.

. Update all the packages.  This can either be done with the {webui} or better run [command]``zypper dup`` manually on the command line local on the systems or remotely as a Salt command.
////

////
I think the better way to document this is if giving it a try. Create an Uyuni server, sync Leap 15.1 (spacewalk-common-channels), create a Leap 15.1, onboard it, sync Leap 15.2 (spacewalk-common-channels), and then try to adjust the channels and trying to upgrade. I recommend you use VMs and take snapshots of the VMs so you can repeat steps as needed.
////

////
But for now you need to create and mirror at least the target channels with spacewalk-common-channels.

You adjust the channels for the client and best is to call "zypper dup". Either from the commandline on that system or using remote command.
////
