[[script-client-proxy]]
= ブートストラップスクリプトを使用して登録する(Saltと従来版)


ブートストラップスクリプトを使用して{productname}を介してSaltクライアントおよび従来のクライアントを登録できます。 これは、{productname}サーバでクライアントを登録する方法とほぼ同じです。 相違点は、コマンドラインツールを使用して{productname}プロキシにブートストラップスクリプトを作成することです。 その後、ブートストラップスクリプトは、必要な情報をクライアントにすべて展開します。 ブートストラップスクリプトには、アクティベーションキーまたはGPGキーなどのパラメータが必要です。 これらのパラメータはそれぞれの設定によって決まります。



.プロシージャ: ブートストラップスクリプトを使用してクライアントをプロキシに登録する

. {webui}を使用して{productname}サーバにクライアントアクティベーションキーを作成します。
    詳細については、xref:client-configuration:activation-keys.adoc[]を参照してください。
. プロキシで、[command]``mgr-bootstrap``コマンドラインツールを{rootuser}として実行します。
    必要に応じて、追加のコマンドラインスイッチを使用して。ブートストラップスクリプトを調整します。 Saltクライアントではなく従来のクライアントをインストールするには、[command]``--traditional``スイッチを使用してください。
+
使用できるオプションを表示するには、コマンドラインに[command]``mgr-bootstrap --help``と入力します。
+
----
mgr-bootstrap --activation-keys=key-string
----
+
. オプション: 結果として得られたブートストラップスクリプトを編集します。
. クライアントで直接ブートストラップスクリプトを実行するか、または[command]``ssh``を使用してプロキシからブートストラップスクリプトを実行します。 [systemitem]``<bootstrap>``をブートストラップスクリプトの名前に置き換え、[systemitem]`` <client.example.com>``をクライアントのホスト名に置き換えます。
+
----
cat <bootstrap> | ssh root@<client.example.com> /bin/bash
----

