[[salt-client-proxy]]
= {webui}を使用してクライアントをプロキシに登録する

{webui}を使用してSaltクライアントを{productname}プロキシに登録できます。


[NOTE]
====
SLE以外のクライアント全般およびバージョン15より前のバージョンのSLEクライアントではブートストラップリポジトリが必要です。 ブートストラップリポジトリには、クライアントにSaltをインストールするためのパッケージ、Saltまたは従来のクライアントを登録するためのパッケージが用意されています。 ブートストラップリポジトリの作成については、xref:client-configuration:bootstrap-repository.adoc[]を参照してください。
====


.プロシージャ: {webui}を使用してクライアントをプロキシに登録する

. {productname}の{webui}で、menu:システム[ブートストラップ]に移動します。
. ［[guimenu]``ホスト``］フィールドに、ブートストラップするクライアントの完全修飾ドメイン名(FQDN)を入力します。
. ［[guimenu]``SSHポート``］フィールドに、クライアントを接続してブートストラップするために使用するSSHポート番号を入力します。
    デフォルトでは、SSHポートは[systemitem]``22``です。
. ［[guimenu]``ユーザ``］フィールドに、クライアントにログインするユーザ名を入力します。
    デフォルトでは、ユーザ名は[systemitem]``root``です。
. ［[guimenu]``Authentication Method（認証メソッド）``］フィールドで、クライアントのブートストラップに使用する認証メソッドを選択します。
+
* パスワード認証の場合、［[guimenu]``パスワード``］フィールドに、パスワードを入力してクライアントにログインします。
* SSH秘密鍵認証の場合、秘密鍵と関連パスフレーズを入力します。
    ブートストラッププロセスの実行が完了するまでの間のみ、この鍵は保存されます。
. ［[guimenu]``アクティベーションキー``］フィールドで、クライアントのブートストラップに使用するソフトウェアチャンネルに関連付けられているアクティベーションキーを選択します。
. ［[guimenu]``プロキシ``］フィールドで、登録先にするプロキシサーバを選択します。
. デフォルトでは、［[guimenu]``Disable SSH Strict Key Host Checking（SSH厳格キーホストの確認を無効にする）``］チェックボックスにチェックが付いています。
    このチェックボックスにチェックが付いていると、ブートストラッププロセスは、手動認証なしでSSHホストキーを自動的に受け入れます。
. オプション: ［[guimenu]``Manage System Completely via SSH（SSHでシステムを完全に管理する）``］チェックボックスにチェックを付けます。
    このオプションにチェックを付けると、サーバへの接続にSSHを使用するようにクライアントは設定され、その他の接続方法は設定されません。
. ［btn:[ブートストラップ]］をクリックして、登録を開始します。

ブートストラッププロセスが完了したら、クライアントは［menu:システム[システム一覧]］にリストされます。



