[[contact-methods-saltbundle]]
= Salt Bundle
:revdate: 2025-07-14
:page-revdate: {revdate}

== Salt Bundleの概要


Salt Bundleは、{salt} Minion、Python 3、必須のPythonモジュール、およびライブラリが含まれている1つのバイナリパッケージです。

Salt BundleはPython 3に付属していて、Saltを実行するためのすべての要件です。したがって、Salt Bundleは、システムソフトウェアとしてクライアントにインストールされているPythonバージョンを使用しません。Salt Bundleは、指定の{salt}バージョンの要件を満たさないクライアントにインストールできます。

{productname} {salt} Master以外の{salt} Masterに接続されている{salt} Minionを実行するシステムでSalt Bundleを使用することもできます。



== Salt Bundleを使用してクライアントをMinionとして登録する

Salt Bundleを使用した登録方法は推奨の登録方法です。 このセクションでは、現在の実装の利点と制約について説明します。

Salt Bundleは、{salt}、Python 3、およびPythonモジュール{salt}が依存している[package]``venv-salt-minion``パッケージとして提供されます。

{webui}を使用したブートストラップもSalt Bundleを使用しているため、{webui}を使用したブートストラップはPythonに依存しません。 Salt Bundleを使用すると、クライアントがPythonインタープリターまたはモジュールを提供する必要がなくなります。

新しいクライアントをブートストラップする場合、Salt Bundleを使用した登録がデフォルトの方法です。 既存のクライアントをSalt Bundleの方式に切り替えることができます。 切り替える場合、[package]``salt-minion``パッケージおよびその依存関係はインストールされたままになります。



[[contact-methods-saltbundle-using]]
=== {salt} Minionを使用した{salt} Bundleの使用

{salt} Bundleは、{productname}サーバ以外の{salt} Masterによって管理されている{salt} Minionと同時に使用できます。Salt Bundleが、{productname}サーバがSalt Bundleの設定ファイルを管理するクライアントにインストールされる場合、[literal]``salt-minion``の設定ファイルは管理されません。詳細については、xref:client-configuration:registration-cli.adoc#_salt_bundle_configuration[Salt Bundleの設定]を参照してください。

[IMPORTANT]
====
* {productname}サーバ以外の{salt} Masterによって管理されている{salt} Minionを使用してクライアントをブートストラップするには、ブートストラップスクリプトを生成するときに[command]``mgr-bootstrap`` [option]``--force-bundle``を使用するか、またはブートストラップスクリプトで[option]``FORCE_VENV_SALT_MINION``を``1``に設定することをお勧めします。
* {webui} [literal]``mgr_force_venv_salt_minion``を[literal]``true``に設定してブートストラップする場合、pillarをグローバルに指定できます。 詳細については、xref:specialized-guides:salt/salt-states-and-pillars.adoc[]を参照してください。
====


=== {salt} MinionからSalt Bundleへの切り替え

[package]``salt-minion``から[package]``venv-salt-minion``に切り替えるために{salt}状態[literal]``util.mgr_switch_to_venv_minion``を使用できます。移行プロセスのトラブルを回避するために、[package]``venv-salt-minion``への切り替えは2ステップで実行することをお勧めします。

.プロシージャ: [literal]``util.mgr_switch_to_venv_minion``を使用して状態を[package]``venv-salt-minion``に切り替える

. まず、pillarを指定せずに[literal]``util.mgr_switch_to_venv_minion``を適用します。 [package]``venv-salt-minion``に切り替わり、設定ファイルなどがコピーされます。 元の[package]``salt-minion``の設定およびそのパッケージはクリーンアップされません。
+
----
salt <minion_id> state.apply util.mgr_switch_to_venv_minion
----
[literal]``util.mgr_switch_to_venv_minion``を適用し、[literal]``mgr_purge_non_venv_salt``を[literal]``True``に設定して[package]``salt-minion``を削除し、[literal]``mgr_purge_non_venv_salt_files``を[literal]``True``に設定して[package]``salt-minion``に関するすべてのファイルを削除します。 この2番目の手順によって、最初の手順が処理されたことが保証され、古い設定ファイルおよび古くなった[package]``salt-minion``パッケージが削除されます。
+
----
salt <minion_id> state.apply util.mgr_switch_to_venv_minion pillar='{"mgr_purge_non_venv_salt_files": True, "mgr_purge_non_venv_salt": True}'
----


=== 追加の懸念事項

//[WARNING]
//====
* 最初の手順をスキップして2番目の手順のみを実行すると、クライアント側でコマンドを実行するために使用される[systemitem]``salt-minion``を停止する必要があるため、状態適用プロセスは失敗する可能性があります。
//====

* Salt Bundleのインストールを回避して代わりに[package]``salt-minion``の使用を続けることも可能です。 この場合、次のいずれかのオプションを指定します。

** [option]``--no-bundle``オプションを指定して[command]``mgr-bootstrap``を実行します。
** 生成されたブートストラップスクリプトで[literal]``AVOID_VENV_SALT_MINION``を[literal]``1``に設定します。
** ブートストラップ状態の場合、[path]``/srv/pillar/salt_bundle_config.sls``の[literal]``mgr_avoid_venv_salt_minion`` pillarを[literal]``True``に設定します。


== Salt BundleによるSSH Push

Salt Bundleは、クライアントに対してSSH Pushアクションを実行するときにも使用されます。

シェルスクリプトは、{salt}コマンドを実行する前に[package]``venv-salt-minion``をインストールせずにSalt Bundleをターゲットシステムに配備します。Salt Bundleには{salt}のコードベース全体が含まれているため、[literal]``salt-thin``は配備されません。SSH Push ({webui}を使用するブートストラップを含む)は、バンドル内でPython 3インタープリターを使用します。ターゲットシステムには他のPythonインタープリターがインストールされている必要はありません。

Bundleを使用して配備されたPython 3は、クライアントでSSH Pushセッションを処理するために使用されるため、SSH Push ({webui}を使用したブートストラップを含む)は、システムにインストールされているPythonに依存しません。

``salt-thin``の使用はフォールバック方法として有効にできますが、クライアントにPython 3をインストールする必要があります。この方法は、推奨もサポートもされておらず、開発目的でのみ存在しています。[path]``/etc/rhn/rhn.conf``設定ファイルで[option]``web.ssh_use_salt_thin``を``true``に設定します。

[IMPORTANT]
====
* ブートストラップリポジトリは、{webui}を使用してクライアントをブートストラップする前に作成済みである必要があります。SSH Pushは、検出したターゲットオペレーティングシステムに基づいてブートストラップリポジトリから取得されたSalt Bundleを使用しています。詳細については、xref:client-configuration:bootstrap-repository.adoc#_prepare_to_create_a_bootstrap_repository[]を参照してください。

* SSH Pushは、[path]``/var/tmp``を使用して、Salt Bundleを配備し、バンドルされたPythonを使用してクライアント上で{salt}コマンドを実行しています。したがって、[option]``noexec``オプションを指定して[path]``/var/tmp``をマウントしないでください。ブートストラッププロセスがクライアントに到達するためにSSH Pushを使用しているため、[path]``/var/tmp``が[option]``noexec``オプションでマウントされたクライアントを{webui}でブートストラップすることはできません。
====



== [literal]``pip``を使用したPythonパッケージによるSalt Bundleの拡張

Salt Bundleには[literal]``pip``が含まれており、バンドルされている{salt} Minionの機能を追加のPythonパッケージで拡張できます。

デフォルトで、[command]``salt <minion_id> pip.install <package-name>``は、[literal]``<package_name>``で指定されたPythonパッケージを[path]``/var/lib/venv-salt-minion/local``にインストールします。

[NOTE]
====
必要に応じて、[literal]``venv-salt-minion.service``の環境変数[literal]``VENV_PIP_TARGET``を設定することで、パス[path]``/var/lib/venv-salt-minion/local``を上書きできます。 サービスにはsystemdのドロップイン設定ファイルを使用することをお勧めします。 設定ファイル[path]``/etc/systemd/system/venv-salt-minion.service.d/10-pip-destination.conf``で実行できます。
----
[Service]
Environment=VENV_PIP_TARGET=/new/path/local/venv-salt-minion/pip
----
====

[IMPORTANT]
====
[literal]``pip``を使用してインストールしたPythonパッケージは、Salt Bundleの更新時に変更されません。更新後にこのようなパッケージが使用可能で機能するようにするために、Salt Bundleの更新後に適用される{salt}の状態でパッケージをインストールすることをお勧めします。
====
