[[contact-methods-intro]]
= クライアントの接続メソッド
:revdate: 2024-09-27
:page-revdate: {revdate}

{productname}サーバがクライアントと通信する接続メソッドは3つあります。これらは{salt}プロトコルに基づきます。

使用する{salt}接続メソッドは、クライアントのタイプおよびネットワークアーキテクチャによって決まります。

デフォルト::
特別なユーザニーズがない限り、この接続メソッドを推奨します。 デフォルトでは、{salt}バンドル実装が配備されます。 詳細については、xref:client-configuration:contact-methods-default.adoc[]を参照してください。

SSH Push::
ネットワークの制限のためにクライアントがサーバとの接続を確立できない場合にのみ有用です。{salt} Bundleでのみサポートされます。この接続メソッドには重大な制限があります。詳細については、xref:client-configuration:contact-methods-saltssh.adoc[]を参照してください。

SSH Push (トンネル使用)::
SSH Pushと同じですが、セキュリティ保護された通信トンネルを使用します。詳細については、xref:client-configuration:contact-methods-saltssh-tunnel.adoc[]を参照してください。


{salt}通信ソフトウェアのオプションの実装:

Salt Bundle ([package]``venv-salt-minion``)::
{salt} Minion、Python 3、必須のPythonモジュール、およびライブラリが含まれている1つのバイナリパッケージです。 したがって、{salt}接続メソッドは、クライアントにインストールされているソフトウェアからは独立しています。

+

////
Using the {salt} Bundle is the default.
It is the only supported implementation for the SSH Push or SSH Push (with tunnel) contact method.
////

+

詳細については、xref:client-configuration:contact-methods-saltbundle.adoc[]を参照してください。

Salt Minion ([package]``salt-minion``)::
クライアントシステムにインストールされている{salt}ソフトウェアであり、一般的には{productname}でサポートされなくなりました。 必要に応じて{sle} 15クライアントおよび派生製品({sle-micro}など)にブートストラップのみの目的でインストールできます。 その後、ブートストラップ中に[package]``venv-salt-minion``に置き換えられます。



[IMPORTANT]
====
いわゆる従来の接続プロトコルは、{productname} 5.0以降ではサポートされなくなりました。{productname} 4から5にアップグレードする前に、従来のプロキシを含む既存の従来のクライアントを{salt}に移行するか、{salt}プロキシで置き換える必要があります。

従来の{productname} 4クライアントから{salt}クライアントへの移行の詳細については、link:https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.html[]を参照してください。
====
