[[custom-info]]
= カスタムシステム情報

クライアントに関してカスタマイズしたシステム情報を含めることができます。 システム情報は「キー:値」ペアで定義され、クライアントに割り当てることができます。 たとえば、特定のプロセッサに対して「キー:値」ペアを定義してから、そのプロセッサがインストールされているすべてのクライアントにそのキーを割り当てることができます。 カスタムシステム情報は分類され、{productname}の{webui}を使用して検索できます。

始める前に、カスタム情報を保存できるキーを作成する必要があります。



.Procedure: Creating a Custom System Information Key
. {productname}の{webui}で、menu:システム[カスタムシステム情報]に移動し、［btn:[キーの作成]］をクリックします。
. ［[guimenu]``キーラベル``］フィールドにキーの名前を入力します。
    スペースは使用しません。 たとえば、``intel-x86_64-quadcore``です。
. ［[guimenu]``説明``］フィールドに必要な追加情報を入力します。
. 必要な各キーで操作を繰り返します。

For traditional clients, this information is stored in the {productname} database. For Salt clients, this information is stored in a Salt pillar.

カスタムシステム情報キーを作成するとき、キーをクライアントに適用できます。



.Procedure: Applying Custom Information Keys to Clients
. {productname}の{webui}で、［[guimenu]``システム``］に移動し、カスタム情報を適用するクライアントをクリックし、menu:詳細[カスタム情報]タブに移動します。
. ［btn:[値の作成]］をクリックします。
. 適用する値を見つけ、キーラベルをクリックします。
. ［[guimenu]``値``］フィールドに追加情報を入力します。
. ［btn:[キーの更新]］をクリックしてカスタム情報をクライアントに適用します。

For more information about configuration management, see xref:client-configuration:configuration-management.adoc[].
