[[package-management]]
= パッケージ管理
:revdate: 2024-11-21
:page-revdate: {revdate}

クライアントは、パッケージを使用してソフトウェアをインストール、アンインストール、およびアップグレードします。

// available subtabs:
//     List / Remove
//     Upgrade
//     Install
//     Lock / Unlock
//     Profiles
//     Non Compliant


クライアントでパッケージを管理するには、［[guimenu]``システム``］に移動し、管理するクライアントをクリックし、menu:システム[ソフトウェア > パッケージ]サブタブに移動します。 このセクションで使用できるオプションは、選択したクライアントのタイプ、および現在のチャンネルのサブスクリプションによって異なります。

ほとんどのパッケージ管理アクションは、アクションチェーンに追加できます。 アクションチェーンの詳細については、xref:reference:schedule/action-chains.adoc[]を参照してください。


[IMPORTANT]
==== 

パッケージをインストールまたはアップグレードするとき、ライセンスまたはEULAは自動的に受け入れられます。
====


== プロファイルを使用したパッケージの比較


保存されているプロファイルでクライアントにインストールされたパッケージを比較できます。または別のクライアントにインストールされたパッケージと比較できます。 比較を実行するとき、選択したクライアントを一致するように変更できます。

パッケージをプロファイルと比較するには、プロファイルを保存済みである必要があります。 プロファイルは、現在インストールされているクライアントのパッケージから作成されます。 プロファイルを作成したら使用して、同じインストール済みパッケージで別のクライアントをインストールできます。


.プロシージャ: 保存されているプロファイルの作成
. {productname}の{webui}で、［[guimenu]``システム``］に移動し、プロファイルのベースになっているクライアントをクリックし、menu:システム[ソフトウェア > パッケージ > プロファイル]サブタブに移動します。
. btn:[システムプロファイルの作成]をクリックします。
. プロファイルの名前と説明を入力し、btn:[プロファイルの作成]をクリックします。


.プロシージャ: クライアントパッケージの比較
. {productname}の{webui}で、［[guimenu]``システム``］に移動し、比較するクライアントをクリックし、menu:システム[ソフトウェア > パッケージ > プロファイル]サブタブに移動します。
    保存されているプロファイルを比較するには、プロファイルを選択し、btn:[比較]をクリックします。
. 別のクライアントと比較するには、クライアント名を選択し、btn:[比較]をクリックし、2つのクライアントの差異一覧を表示します。



[[package-management-orphaned-packages]]
== 孤立したパッケージ

孤立したパッケージとは、{productname}によって同期され、ソフトウェアチャンネルに関連付けられていないパッケージです。 したがって、孤立したパッケージは通常、{productname}クライアントでは利用できず、ユーザは追加の作業を行わずにそのようなパッケージをインストールすることはできません。

次のいずれかのイベントの結果として、パッケージが孤立する可能性があります。

* 同期されたリポジトリはパッケージを削除します。 デフォルトでは、{productname}はそのようなパッケージをチャンネルからリンク解除しますが、パッケージは削除しません。
* リポジトリはパッケージを新しいバージョンに置き換えるので、以前のバージョンは削除されます。
* reposyncプロセスが中断されたので(たとえば、容量不足の例外が発生したため)、ダウンロードされたパッケージがチャンネルに関連付けられませんでした。
* ユーザはパッケージを手動でアップロードしましたが、どのチャンネルにも関連付けませんでした。

孤立したパッケージはユーザ環境で容量を消費し、チャンネルに関連付けられていないためクライアントに簡単に配布できません。 孤立したパッケージは、ブートストラップや顧客固有の手順のような特定のワークフローでは意味を持つ場合があります。

{webui}で孤立したパッケージを表示するには、menu:ソフトウェア[Manage > Packages > view Packages in no channel](管理 > パッケージ > チャンネルのないパッケージを表示)をクリックします。

{productname}は、孤立したパッケージを検索しパッケージ組織IDを1に変更する、taskomaticジョブを定期的に実行します。 つまり、孤立したパッケージはtaskomaticジョブの実行後にのみ削除できます。 削除できない孤立したパッケージが発生した場合は、24時間待ってから再度削除を試みてください。

// .Procedure: Deleting orphaned packages

孤立したパッケージの削除:

// * With the UI (FIXME is this possible?  How?

* 個々のパッケージを対象とするコマンドラインツールを使用する場合。 例:
+
----
spacecmd package_remove zypper-1.14.52-150400.1.9.x86_64
----

* 孤立したパッケージすべてを一度に対象とするコマンドラインツールを使用する場合:
+
----
spacecmd package_removeorphans
----
