[[suse-registration-overview]]
= SUSEクライアントの登録
:revdate: 2025-02-06
:page-revdate: {revdate}

ifeval::[{mlm-content} == true]

// SUSE Liberty Linux not available at Uyuni for now
{sle}および{sleses}クライアントを{productname}サーバに登録できます。
endif::[]

ifeval::[{uyuni-content} == true]

// SUSE Liberty Linux not available at Uyuni for now
{sle}クライアントを{productname}サーバに登録できます。
endif::[]


新しいクライアントを{productname}サーバに登録するには、まず{webui}またはコマンドラインツールを使用して、新しいクライアントのオペレーティングシステムとアーキテクチャのソフトウェアチャンネルを同期します。

ifeval::[{uyuni-content} == true]

次に、コマンドラインツールを使用して、新しく追加されたオペレーティングシステムのクライアントツールリポジトリを同期します。
endif::[]

そのメソッドおよび詳細は、クライアントのオペレーティングシステムによって異なります。 これについては、次のセクションで説明します。



== 準備手順または確認事項


始める前に、クライアントで{productname}サーバと日時が正しく同期していることを確認してください。

アクティベーションキーを作成済みである必要もあります。 アクティベーションキーの作成の詳細については、xref:client-configuration:activation-keys.adoc[]を参照してください。



[IMPORTANT]
====
{productname}サーバをこのサーバ自体に登録しないでください。{productname}サーバは個別に管理するか、別の{productname}サーバを使用して管理する必要があります。複数のサーバを使用する方法の詳細については、xref:specialized-guides:large-deployments/hub-multi-server.adoc[]を参照してください。
====



[[suse-registration-overview-check]]
== 以前の登録ステータスの確認

クライアントが以前にSCC、SMT、またはRMTに登録されていた場合は、クライアントを{productname}サーバに移行する前に、[command]``SUSEConnect``を使用してそのような登録を削除します。 まず古い登録を削除することを忘れないでください。 削除しないと、クライアントが{productname}で{suse}オペレーティングシステムの新しいバージョンに移行された後に、不要になったリポジトリがクライアントに追加されます。

{sle} 12または15クライアントを登録解除するには、クライアント上でrootとして次のコマンドを実行します。

----
SUSEConnect --de-register
SUSEConnect --cleanup
----

詳細なクリーンアップコマンドおよび検証手順の詳細については、link:https://www.suse.com/de-de/support/kb/doc/?id=000019054[]を参照してください。
