[[registering-clients-cli]]
= コマンドラインで登録する(Salt)


ほとんどの場合、Saltクライアントは、デフォルトのブートストラップメソッドで正確に登録されます。 ただし、Saltを使用してクライアントを{productname}サーバに手動で登録できます。そのためには、クライアントでSalt Minionファイルを編集し、サーバの完全修飾ドメイン名(FQDN)を指定します。 このメソッドは、サーバで受信するポート4505および4506を使用します。 このメソッドでは{productname}サーバの設定は不要です。ただし、上記のポートを開いている必要があります。

[NOTE]
====
コマンドラインで従来のクライアントを登録することもできますが、その手順は長くなります。 この手順についてはここでは説明しません。 ブートストラップスクリプトプロシージャを使用して従来のクライアントを登録します。 詳細については、xref:registration-bootstrap.adoc[]を参照してください。
====

このプロシージャでは、登録する前に[package]``salt-minion``パッケージをSaltクライアントにインストール済みである必要があります。 SLE 12ベースのクライアントでは、[systemitem]``Advanced Systems Management``モジュールもアクティブ化しておく必要があります。



.プロシージャ: Salt Minion設定ファイルでクライアントを登録する
. Saltクライアントで[literal]``minion``設定ファイルを開きます。 設定ファイルは次の場所にあります。
+
----
/etc/salt/minion
----
+
または
+
----
/etc/salt/minion.d/NAME.conf
----
. {productname}サーバまたはプロキシのFQDNを`master`として追加または編集し、アクティベーションキーをクライアント設定ファイルに追加します。
+
----
master: SERVER.EXAMPLE.COM
server_id_use_src: adler42
 enable_legacy_startup_events: False
 enable_fqdns_grains: False
 grains:
   susemanager:
     activation_key: "<Activation_Key_Name>"
----

. [systemitem]``salt-minion``サービスを再起動します。
+
----
systemctl restart salt-minion
----
. {productname}サーバで、新しいクライアントキーを受け入れます。[systemitem]``<client>``をクライアントの名前に置き換えます。
+
----
salt-key -a '<client>'
----

[path]``/etc/salt/minion``設定ファイルの詳細については、https://docs.saltstack.com/en/latest/ref/configuration/minion.htmlを参照してください。


[WARNING]
====
{centos}{nbsp}6、{oracle}{nbsp}6、{rhel}{nbsp}6、または{sleses}{nbsp}6の各クライアントを登録して使用するには、{productname}サーバを設定して旧式のSSL暗号化をサポートする必要があります。 このエラーを解決する方法については、``古いクライアントの登録``をxref:client-configuration:tshoot-clients.adoc[]で参照してください。
====



