[[repos]]
= ソフトウェアリポジトリ
:revdate: 2025-02-06
:page-revdate: {revdate}

リポジトリはソフトウェアパッケージを収集するために使用されます。 ソフトウェアリポジトリにアクセスできる場合、リポジトリが提供するソフトウェアをインストールできます。 1つ以上のリポジトリを{productname}のソフトウェアチャンネルに関連付け、クライアントをそのチャンネルに割り当て、クライアントのパッケージにインストールして更新する必要があります。

{productname}のほとんどのデフォルトチャンネルは、正しいリポジトリに関連付けられています。 カスタムチャンネルを作成している場合、アクセスできるリポジトリまたは自分で作成したリポジトリを関連付ける必要があります。

カスタムリポジトリおよびチャンネルの詳細については、xref:administration:custom-channels.adoc[]を参照してください。



== ローカルリポジトリの場所


クライアントでローカルリポジトリを設定して、{productname}チャンネルが提供しないパッケージを提供できます。

[WARNING]
====
ほとんどの場合、クライアントシステムはローカルリポジトリを必要としません。 ローカルリポジトリを使用すると、クライアントで使用できるパッケージがどれかという問題が発生する可能性があります。 この問題が発生すると、予期しないパッケージがインストールされる場合があります。
====

ローカルリポジトリは、オンボーディング中に無効になります。

チャンネル状態が実行されるたびにローカルリポジトリが無効になります。たとえば、highstateを適用したり、パッケージアクションを実行したりする場合などです。

オンボーディング後もローカルリポジトリを有効にしておく必要がある場合は、影響を受けるクライアントに対して次のpillarを設定する必要があります。

``/srv/pillar/top.sls``ファイルを編集します。

----
base:
  'minionid':
    - localrepos
----

``/srv/pillar/localrepos.sls``ファイルを編集します。

----
mgr_disable_local_repos: False
----

クライアントがオンボードを完了した後、ローカルリポジトリを次の場所に追加できます。

[[local-repo-locations]]
[cols="1,1", options="header"]
.ローカルリポジトリの場所
|===
ifeval::[{mlm-content} == true]
| Client Operating System | Local Repository Directory

| {sles} | [path]``/etc/zypp/repos.d``
| {opensuse} | [path]``/etc/zypp/repos.d``
| {sles} {es} | [path]``/etc/yum.repos.d/``
| {rhel} and similar derivatives | [path]``/etc/yum.repos.d/``
| {ubuntu} | [path]``/etc/apt/sources.list.d/``
| {debian} | [path]``/etc/apt/sources.list.d/``
endif::[]


// SUSE Liberty Linux not available at Uyuni for now

ifeval::[{uyuni-content} == true]
| {sles} | [path]``/etc/zypp/repos.d`` | {opensuse} | [path]``/etc/zypp/repos.d`` | {rhel} and similar derivatives | [path]``/etc/yum.repos.d/`` | {ubuntu} | [path]``/etc/apt/sources.list.d/`` | {debian} | [path]``/etc/apt/sources.list.d/``
endif::[]

|===
