[[snapshots]]
= 設定のスナップショット

スナップショットは、設定時点でのクライアントのパッケージプロファイル、設定ファイル、および{productname}設定を記録します。 古いスナップショットにロールバックして、前の設定に戻すことができます。

[NOTE]
====
スナップショットは、従来のクライアントでのみサポートされます。 Saltクライアントでは、この機能をサポートしていません。
====

スナップショットは、一部のアクション実行後に自動的に取得されます。 いつでもスナップショットを手動で取得することもできます。 クライアントで元に戻せないかもしれないアクションを実行する前に、その時点のスナップショットがあることを確認することをお勧めします。

スナップショットはデフォルトで有効になっています。 自動スナップショットは無効にできます。そのためには、[path]``rhn.conf``設定ファイルの[parameter]``enable_snapshots=0``を設定します。

スナップショットを管理するには、menu:システム[システム一覧]に移動して、管理するクライアントを選択します。 選択したクライアントで現在のスナップショットをすべて一覧表示するには、menu:プロビジョニング[スナップショット]タブに移動します。 スナップショットに記録された変更の詳細を表示するには、スナップショットの名前をクリックします。 menu:プロビジョニング[スナップショット]タブでサブタブを使用して、選択したスナップショットにロールバックした変更を表示できます。

* グループメンバシップ
* チャンネルサブスクリプション
* インストールしたパッケージ
* 設定チャンネルのサブスクリプション
* 設定ファイル
* スナップショットタグ


[IMPORTANT]
====
スナップショットを使用して、クライアントに対するほとんどの変更をロールバックできますが、すべてではありません。 たとえば、複数の更新はロールバックできません。また、サービスパックの移行はロールバックできません。 クライアントをアップグレードする前に、必ずバックアップを取ってください。
====



== スナップショットタグ

スナップショットタグを使用すると、わかりやすい説明をスナップショットに追加できます。 タグを使用して、動作したことがわかっている最後の設定、成功したアップグレードなどスナップショットに関する追加情報を記録できます。

スナップショットタグを管理するには、menu:システム[システム一覧]に移動して、管理するクライアントを選択します。 選択したクライアントで現在のスナップショットタグをすべて一覧表示するには、menu:プロビジョニング[スナップショットタグ]タブに移動します。 ［[guimenu]``システムタグの作成``］をクリックし、説明を入力し、［btn:[現在のスナップショットにタグ付け]］ボタンをクリックします。



== 大規模インストールのスナップショット

{productname}で保持できるスナップショットの上限数はありません。 つまり、クライアント、パッケージ、チャンネル、および設定変更を追加すると、スナップショットを保存するデータベースが大きくなります。

数千のクライアントを含む大規模インストールがある場合、古いスナップショットを定期的に削除するように、{productname} APIを使用して、繰り返しスケジュールに繰り返しクリーンアップスクリプトを使用できます。 または、この機能を無効にできます。そのためには、[parameter]``enable_snapshots=0``([path]``rhn.conf``設定ファイル内)を設定します。
