[[kubernetes]]
= VHMとKubernetes

仮想ホストマネージャ(VHM)を使用して、{kube}クラスタを管理できます。

VHMを使用すると、{productname}は、クラスタに関する情報を取得して報告できます。 VHMの詳細については、xref:client-configuration:vhm.adoc[]を参照してください。


{kube}で{productname}を使用するには、{productname}サーバがコンテナ管理用に設定されていて、必要なすべてのチャンネルがあり、登録されているコンテナビルドホストが利用できる必要があります。


次の要件もあります。

* 1つ以上の{kube}または{caasp}のクラスタをネットワーク上で使用できる。
* [systemitem]``virtual-host-gatherer-Kubernetes``パッケージが{productname}サーバにインストールされている。
* {kube}バージョン1.5.0以上または{caasp}。
* コンテナビルドホストにDockerバージョン1.12以上がある。



== {kube} VHMの作成

{kube}クラスタは、{productname}にVHMとして登録されています。

{kube}クラスタを登録して認可する``kubeconfig``ファイルが必要です。 {kube}のコマンドラインツールである``kubectl``を使用して``kubeconfig``ファイルを取得できます。

{caasp}を使用している場合、Velumインターフェースからファイルをダウンロードできます。



.プロシージャ: {kube} VHMの作成
. {productname}の{webui}で、menu:システム[仮想ホストマネージャ]に移動します。
. ［btn:[作成]］をクリックし、［[guimenu]``Kubernetesクラスタ``］を選択します。
. ［[guimenu]``Add a Kubernetes Virtual Host Manager（Kubernetes仮想ホストマネージャの追加）``］セクションで、次のパラメータを使用します。
* ［[guimenu]``ラベル``］フィールドにVHMのカスタム名を入力します。
* {kube}クラスタに必要データが含まれている[path]``kubeconfig``ファイルを選択します。
. ［[guimenu]``コンテキスト``］フィールドで、クラスタに適切なコンテキストを選択します。
    これは[path]``kubeconfig``ファイルで指定されています。
. ［btn:[作成]］をクリックします。



.プロシージャ: クラスタのノードを表示する
. {productname}の{webui}で、menu:システム[仮想ホストマネージャ]に移動します。
. {kube}クラスタを選択します。
. ［btn:[Schedule refresh data（データの更新をスケジュールする）]］をクリックしてノードのデータを更新します。

ノードのデータの更新には数分かかる場合があります。 更新された情報を表示するには、ブラウザウィンドウを更新する必要がある場合があります。

接続および認証の問題は[path]``gatherer.log``にログされます。


[NOTE]
====
登録中にはノードのデータは更新されません。 データを表示するにはデータを手動で更新する必要があります。
====



== イメージランタイムデータの取得

{productname}の{webui}で{kube}イメージに関するランタイムデータを表示できます。そのためには、menu:イメージ[イメージリスト]に移動します。

イメージリストの表には、3つの列があります。

* [guimenu]``リビジョン``:
+
{productname}によってビルドされたイメージをリビルドするたびに、または外部でビルドされたイメージをインポートするたびに増加するシーケンス番号。
* [guimenu]``ランタイム``:
+
登録されたクラスタの各イメージにおける実行中インスタンスの全般的な状態。
* [guimenu]``インスタンス``:
+
{productname}で登録されているすべてのクラスタでこのイメージを実行しているインスタンスの数。 数値の横のポップアップアイコンをクリックして数値の内訳を表示できます。

［[guimenu]``ランタイム``］列には、次の状態メッセージのいずれかが表示されます。

* ``全てのインスタンスがSUSE Managerと同期できています``:
+
実行中のすべてのインスタンスが{productname}によって追跡されているイメージの同じビルドを実行しています。
* ``古いインスタンスが見つかりました``:
+
インスタンスの一部が古いビルドのインスタンスを実行しています。 イメージを再展開する必要があるかもしれません。
* ``情報無し``:
+
{productname}に含まれているイメージデータとインスタンスイメージのチェックサムが一致していません。 イメージを再展開する必要があるかもしれません。



.プロシージャ: イメージのビルド
. {productname}の{webui}で、menu:イメージ[ストア]に移動します。
. ［btn:[作成]］をクリックしてイメージストアを作成します。
. menu:イメージ[プロファイル]に移動します。
. ［btn:[作成]］をクリックしてイメージプロファイルを作成します。
    {kube}への展開に適したdockerファイルを使用する必要があります。
. menu:イメージ[ビルド]に移動して、新しいプロファイルでイメージをビルドします。
. イメージを登録済みの{kube}クラスタのいずれかに展開します。
    この操作は[command]``kubectl``ツールを使用して実行できます。

更新データは、menu:イメージ[イメージリスト]にあるイメージリストに表示されます。



.プロシージャ: 以前展開したイメージのインポート
. {productname}の{webui}で、menu:イメージ[イメージストア]に移動します。
. インポートするイメージを所有しているレジストリがない場合、追加します。
. menu:イメージ[イメージリスト]に移動し、［btn:[インポート]］をクリックします。
. 各フィールドに入力し、作成したイメージストアを選択し、［btn:[インポート]］をクリックします。

インポートしたデータは、menu:イメージ[イメージリスト]にあるイメージリストに表示されます。



.プロシージャ: 以前展開したイメージの再ビルド

. {productname}の{webui}で、menu:イメージ[イメージリスト]に移動し、再ビルドするイメージが含まれている行を探し、［btn:[詳細]］をクリックします。
. ［[guimenu]``ビルド状態``］セクションに移動し、［btn:[再ビルド]］をクリックします。
    再ビルドの完了には少し時間がかかります。

再ビルドが正常に完了すると、menu:イメージ[イメージリスト]のイメージリストでイメージのランタイム状態が更新されます。 インスタンスが前のビルドのインスタンスを実行していることをこれは示しています。

[NOTE]
====
再ビルドできるのは、元々{productname}でビルドされたイメージのみです。 インポートしたイメージは再ビルドできません。
====



.プロシージャ: 追加のランタイムデータの取得
. {productname}の{webui}で、menu:イメージ[イメージリスト]に移動し、実行中のインスタンスが含まれている行を探し、［btn:[詳細]］をクリックします。
. ［[guimenu]``概要``］タブに移動します。
    ［[guimenu]``イメージの情報``］セクションには、［[guimenu]``ランタイム``］フィールドと［[guimenu]``インスタンス``］フィールドにデータがあります。
. ［[guimenu]``ランタイム``］タブに移動します。
    このセクションには、登録されているすべてのクラスタでこのイメージを実行している{kube}ポッドに関する情報が含まれています。 このセクションの情報を次に示します。
+
* ポッドの名前。
* ポッドがあるネームスペース。
* 指定されているポッドのコンテナのランタイム状態。



== パーミッションと証明書


[IMPORTANT]
====
{productname}では[path]``kubeconfig``ファイルにすべての証明書データが埋め込まれている場合、このファイルのみ使用できます。
====

{productname}からのAPIコールは次のとおりです。

* ``GET /api/v1/pods``
* ``GET /api/v1/nodes``

{productname}の最小推奨パーミッションは次のとおりです。

* すべてのノードをリストするClusterRole:
+
----
resources: ["nodes"]
verbs: ["list"]
----
* すべてのネームスペースのポッドをリストするClusterRole(ロールのバインドはネームスペースを制限してはいけません):
+
----
resources: ["pods"]
verbs: ["list"]
----

``/pods``が403の応答を返した場合、{productname}はクラスタ全体を無視します。

RBAC認証の操作方法の詳細については、https://kubernetes.io/docs/admin/authorization/rbac/を参照してください。
