[[virt-file]]
= その他のサードパーティプロバイダを使用した仮想化

Xen、KVMまたはVMware以外のサードパーティ仮想化プロバイダを使用する場合、JSON設定ファイルを{productname}にインポートできます。

同様に、APIへの直接アクセスを提供しないVMWareインストール環境の場合、ファイルベースのVHMが基本的な管理機能を提供します。

[NOTE]
====
このオプションは、[command]``virtual-host-gatherer``ツールを使用して作成されたファイルをインポートするためのものです。 手動で作成したファイル用には設計されていません。
====



.プロシージャ: JSONファイルのエクスポートとインポート

. VMネットワークで[command]``virtual-host-gatherer``を実行してJSON設定ファイルをエクスポートします。
. 生成されたファイルを{productname}サーバからアクセスできる場所に保存します。
. {productname}の{webui}で、menu:システム[仮想ホストマネージャ]に移動します。
. ［btn:[作成]］をクリックし、［[guimenu]``ファイルベース``］を選択します。
. ［[guimenu]``Add a file-based Virtual Host Manager（ファイルベースの仮想ホストマネージャの追加）``］セクションで、次のパラメータを使用します。
* ［[guimenu]``ラベル``］フィールドにVHMのカスタム名を入力します。
* ［[guimenu]``Url``］フィールドに、エクスポートするJSON設定フィルへのパスを入力します。
. ［btn:[作成]］をクリックして変更を保存し、VHMを作成します。
. ［[guimenu]``仮想ホストマネージャ``］ページで、新しいVHMを選択します。
. ［[guimenu]``プロパティ``］ページで、［btn:[データの更新]］をクリックし、新しいVHMを評価します。



.例: エクスポートするJSON設定ファイル

----
{
    "examplevhost": {
         "10.11.12.13": {
             "cpuArch": "x86_64",
             "cpuDescription": "AMD Opteron(tm) Processor 4386",
             "cpuMhz": 3092.212727,
             "cpuVendor": "amd",
             "hostIdentifier": "'vim.HostSystem:host-182'",
             "name": "11.11.12.13",
             "os": "VMware ESXi",
             "osVersion": "5.5.0",
             "ramMb": 65512,
             "totalCpuCores": 16,
             "totalCpuSockets": 2,
             "totalCpuThreads": 16,
             "type": "vmware",
             "vms": {
                 "vCenter": "564d6d90-459c-2256-8f39-3cb2bd24b7b0"
             }
         },
         "10.11.12.14": {
             "cpuArch": "x86_64",
             "cpuDescription": "AMD Opteron(tm) Processor 4386",
             "cpuMhz": 3092.212639,
             "cpuVendor": "amd",
             "hostIdentifier": "'vim.HostSystem:host-183'",
             "name": "10.11.12.14",
             "os": "VMware ESXi",
             "osVersion": "5.5.0",
             "ramMb": 65512,
             "totalCpuCores": 16,
             "totalCpuSockets": 2,
             "totalCpuThreads": 16,
             "type": "vmware",
             "vms": {
                 "49737e0a-c9e6-4ceb-aef8-6a9452f67cb5":  "4230c60f-3f98-2a65-f7c3-600b26b79c22",
                 "5a2e4e63-a957-426b-bfa8-4169302e4fdb":  "42307b15-1618-0595-01f2-427ffcddd88e",
                 "NSX-gateway": "4230d43e-aafe-38ba-5a9e-3cb67c03a16a",
                 "NSX-l3gateway":  "4230b00f-0b21-0e9d-dfde-6c7b06909d5f",
                 "NSX-service": "4230e924-b714-198b-348b-25de01482fd9"
             }
         }
     }
 }
----

詳細については、{productname}サーバの[command]``virtual-host-gatherer``の関数リファレンスを参照してください。

----
man virtual-host-gatherer
----


このパッケージの`README`ファイルには、ハイパーバイザの「種類」などに関する背景情報が記載されています。

----
/usr/share/doc/packages/virtual-host-gatherer/README.md
----

この関数リファレンスおよび`README`ファイルには、設定ファイルのサンプルも含まれています。
