[[vhm-caasp]]
= VHMおよび{caasp}

仮想ホストマネージャ(VHM)を使用して、{caasp}クラスタを管理できます。 VHMを使用すると、{productname}は、クラスタに関する情報を取得して報告できます。 VHMの詳細については、xref:client-configuration:vhm.adoc[]を参照してください。


[NOTE]
====
VHMを使用せず、{productname}を使用して{caasp}クラスタを直接管理することもできます。 詳細については、xref:client-configuration:virt-clusters.adoc[]を参照してください。
====



== CaaSPノードのオンボード

Saltクライアントのメソッドと同じメソッドを使用して各{caasp}ノードを{productname}に登録できます。 詳細については、xref:client-configuration:registration-overview.adoc[]を参照してください。

アクティベーションキーを作成して{caasp}チャンネルを関連付け、関連するノードをオンボードすることをお勧めします。 アクティベーションキーの詳細については、xref:client-configuration:activation-keys.adoc[]を参照してください。

``cloud-init``を使用している場合、``cloud-init``設定でブートストラップスクリプトを使用することをお勧めします。 ブートストラップの詳細については、xref:client-configuration:registration-bootstrap.adoc[]を参照してください。

{caasp}ノードを{productname}に追加済みの場合、登録されたシステムは、システムのロックのSalt式を自動的に適用して、意図しないアクションがクライアントで実行されないようにします。 システムがロックされると{webui}は警告を表示します。{webui}またはAPIを使用してアクションをスケジュールできますが、そのアクションは失敗します。 システムのロックの詳細については、xref:client-configuration:system-locking.adoc[]を参照してください。

システムのロック式が自動的に適用されないようにできます。そのためには、設定ファイルを編集します。 [path]``/etc/rhn/rhn.conf``を開き、ファイルの末尾に次の行を追加します。

次の行を[path]``/etc/rhn/rhn.conf``ファイルの末尾に追加します。

----
java.automatic_system_lock_cluster_nodes = false
----

spacewalkサービスを再起動して変更を取得します。

----
spacewalk-service restart
----

{kube}に関する更新は、``skuba-update``ツールを使用して管理されます。 詳細については、https://documentation.suse.com/suse-caasp/4/html/caasp-adminを参照してください。


[WARNING]
====
任意の{caasp}ノードでSaltまたは{productname}を(UIまたはAPIから)使用する場合:

* パッチを適用しないでください(パッチがインタラクティブとマークされている場合)
* パッチを自動的にインストールするようにシステムをマークしないでください
* Do not perform a product migration
* ノードを再起動しないでください
* Cobblerを介して電源管理アクションを発行しないでください
* `patterns-caasp-Node-x.y`に違反または競合している場合、パッケージをインストールしないでください
* `patterns-caasp-Node-x.y`に違反または競合している場合、あるいは`patterns-caasp-Node-x.y`に関連するパッケージの1つである場合、パッケージを削除しないでください
* `patterns-caasp-Node-x.y`に違反または競合している場合、あるいは`patterns-caasp-Node-x.y`に関連するパッケージの1つである場合、パッケージをアップグレードしないでください

これらの操作を実行すると、{caasp}クラスタを使用できなくなる可能性があります。 {productname}は、システムがロックされていない場合、これらの操作の実行を阻止しません。
====

== {caasp}{nbsp}4ノードの自動インストールプロファイル

{caasp}{nbsp}4は、ノードの自動インストールに使用できるAutoYaSTプロファイルを提供します。 このプロファイルは``patterns-caasp-Management``パッケージに入っています。 プロファイルの詳細については、https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-deployment/#_autoyast_preparationを参照してください。

{productname}を使用するようにカスタマイズされた、{caasp}{nbsp}4テンプレートに基づいているスクリプトのサンプルは、https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST/CaaSP-autoinstallを参照してください。

== {productname}で{caasp}クラスタを管理する

{productname}を使用して、1つまたは複数の既存の{caasp}クラスタを管理できます。

[NOTE]
====
現在{caasp}{nbsp}4のみがサポートされています。
====


開始前に、{caasp}クラスタがインストール済みであることを確認してください。

=== 管理ノードの選択

{caasp}クラスタを管理するには、クラスタの管理ノードとしてクライアントを選択する必要があります。 管理ノードはクラスタの一部にはできません。また、管理ノードでは、開始する前に{caasp}チャンネルが関連付けられている必要があります。 クラスタの種類がすべて同じであれば、複数のクラスタに対して1つの管理ノードを使用できます。



.プロシージャ: 管理ノードの選択
. {productname}の{webui}で、menu:システム[システム一覧]に移動し、管理ノードとして選択するクライアントの名前をクリックします。
. menu:式[設定]タブに移動し、``CaaSP管理ノード``式にチェックを付けます。
. ［btn:[保存]］をクリックし、highstateを適用します。


[NOTE]
====
highstateが完了するまで、管理ノードを使用できません。
====


menu:クラスタ[概要]に移動して、既知のクラスタを一覧表示します。 このリストには、既存のすべてのクラスタ、クラスタの種類、および関連付けられている管理ノードが表示されます。 ノードが{productname}に登録されている場合、クラスタ内のノードも表示されます。 クラスタ内のノードでは、``skuba``および{kube} APIの追加情報が表示されます。情報には、ロール、情報、更新があるかどうかが含まれています。

ノードにあるデータの詳細については、https://documentation.suse.com/suse-caasp/4/html/caasp-admin/_cluster_updates.htmlを参照してください。

クラスタから管理ノードに設定を準備する必要があります。

. ``skuba``設定ディレクトリをクラスタから管理ノードにコピーします。
    これは、クラスタをブートストラップした後に``skuba``サービスが作成したディレクトリです。{productname}の{webui}でクラスタを追加するために、新しいファイルの場所をメモします。

. 認証方法を提供します。これを実現する方法は2つあります。環境に最適なメソッドを選択します。
クラスタノードへのアクセスに使用しパスワードのない秘密SSH鍵を{productname}サーバにコピーし、ファイルの場所をメモします。 現在のキー、および今後使用するクライアントのキーが必要です。
  * ``ssh-agent``ソケットを使用して、クラスタを設定するときにソケットへのパスを指定できます。{caasp}で``ssh-agent``を使用する方法は2つあります。

    ** ``ssh-agent``をローカルで使用する方法
    *** ssh-agentをローカルで起動します: ``eval $(ssh-agent)``
    *** SSHキーを追加します: ``ssh-add <key>``
    *** エージェントにアクセスするために使用するソケットは``$SSH_AGENT``環境変数にあります。

    ** `ssh-agent`を別のマシンから管理ノードに転送します。

      *** ソースマシンから: ``ssh -A <management node>``。ソケットのパスは``$SSH_AGENT``環境変数にもあります。

[NOTE]
====
``ssh-agent``メソッドを使用している場合、ソケットのパスは、新しい``ssh-agent```が開始されるまたは新しい``ssh -A``接続が開始されるたびに変更されます。 ``ssh-agent``ソケットのパスは、{productname}の{webui}からいつでも更新できます。 ソケットのパスは、SSHアクセスを必要とするクラスタアクション開始時にも上書きできます。
====


=== クラスタの管理

{productname}でクラスタを管理するには、{webui}でクラスタを追加します。



.プロシージャ: 既存のクラスタの追加
. {productname}の{webui}で、menu:クラスタ[概要]に移動し、btn:[FIXME]をクリックします。
. クラスタの種類などクラスタに関する情報を提供するプロンプトに従い、関連付ける管理ノードを選択します。
. クラスタの``skuba``設定ファイルへのパスを入力します。
. 使用するパスワードのないSSHキーを入力します。または``ssh-agent``ソケットを使用します。
. クラスタの名前、ラベル、および説明を入力します。
. btn:[FIXME]をクリックします。


{productname}を使用して管理するクラスタでは、対応するシステムグループが作成されます。 デフォルトでは、システムグループは、``クラスタ<cluster_name>``と呼ばれています。 システムグループを更新し、ノードの一覧を更新します。 {productname}が認識しているノードのみ表示されます。


{productname}からクラスタを削除できます。そのためには、menu:クラスタ[概要]に移動し、削除するクラスタのチェックを外し、［btn:[クラスタの削除]］をクリックします。


[IMPORTANT]
====
クラスタを削除すると、{productname}からそのクラスタが削除されます。クラスタノードは削除されません。 クラスタ上で実行中のワークロードは中断されないままです。
====



=== ノードの管理

{productname}で作成したクラスタがある場合、そのクラスタ内のノードを管理できます。

新しいノードをクラスタに追加する前に、パスワードのないSSH、または転送している``ssh-agent``ソケットを使用して、追加するノードに管理ノードからアクセスできることを確認してください。

追加するノードが{productname}に登録されていて、{caasp}チャンネルが割り当てられていることも確認する必要があります。


.プロシージャ: ノードをクラスタに追加する
. {productname}の{webui}で、menu:クラスタ[概要]に移動し、［btn:[ノードの参加]］をクリックします。
. 追加するノードを使用可能ノードの一覧から選択します。
    使用可能ノードの一覧には、{productname}に登録されていて、管理ノードではなく、クラスタの一部ではないノードのみが含まれます。
. プロンプトに従って、追加するノードの{caasp}パラメータを入力します。
. オプション: 追加するノードに対してのみ有効なカスタム``ssh-agent``ソケットを指定します。
. ［btn:[保存]］をクリックして、ノードを追加するアクションをスケジュールします。
    このアクション中、{productname}は、スワップを無効にして参加するノードを準備し、その後ノードをクラスタに追加します。



.プロシージャ: クラスタからノードを削除する
. {productname}の{webui}で、menu:クラスタ[概要]に移動し、削除するノードのチェックを外し、［btn:[ノードの削除]］をクリックします。
. プロンプトに従って、削除するノードのパラメータを定義します。
. オプション: 削除するノードに対してのみ有効なカスタム``ssh-agent``ソケットを指定します。
. ［btn:[保存]］をクリックして、ノードを削除するアクションをスケジュールします。

ノードの削除の詳細については、https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_permanent_removalを参照してください。



==== クラスタのアップグレード

クラスタに使用可能な更新がある場合、{productname}を使用して、更新をスケジュールして管理できます。

{productname}は、まずすべての制御プレーンをアップグレードし、次にワーカをアップグレードします。 詳細については、https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_cluster_updatesを参照してください。


.プロシージャ: クラスタのアップグレード
. {productname}の{webui}で、menu:クラスタ[概要]に移動し、アップグレードするクラスタをクリックします。
. オプション: アップグレードするためにカスタマイズできる{caasp}パラメータはありません。
    ただし、アップグレードするノードに対してのみ有効なカスタム``ssh-agent``ソケットを指定できます。
. ［btn:[保存]］をクリックして、クラスタをアップグレードするアクションをスケジュールします。


[NOTE]
====
{productname}は``skuba``とのみやり取りし、クラスタをアップグレードします。 設定変更などその他の必要なアクションは{productname}では実行されません。
====


アップグレードの詳細については、https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4を参照してください。
