[[virt-caasp]]
= クラスタ

{productname}を使用して、{caasp}クラスタを直接管理できます。 {productname}で登録したクラスタを管理します。そのためには、{webui}でmenu:クラスタ[概要]に移動します。



== 自動インストールプロファイル

{caasp}{nbsp}4は、ノードの自動インストールに使用できるAutoYaSTプロファイルを提供します。 このプロファイルは``patterns-caasp-Management``パッケージに入っています。




{productname}を使用して、1つまたは複数の既存の{caasp}クラスタを管理できます。

[NOTE]
====
現在{caasp}{nbsp}4のみがサポートされています。
====


開始前に、{caasp}クラスタがインストール済みであることを確認してください。



== 管理ノードの選択

{caasp}クラスタを管理するには、クラスタの管理ノードとしてクライアントを選択する必要があります。 管理ノードはクラスタの一部にはできません。また、管理ノードでは、開始する前に{caasp}チャンネルが関連付けられている必要があります。 クラスタの種類がすべて同じであれば、複数のクラスタに対して1つの管理ノードを使用できます。



.プロシージャ: 管理ノードの選択
. {productname}の{webui}で、menu:システム[システム一覧]に移動し、管理ノードとして選択するクライアントの名前をクリックします。
. menu:式[設定]タブに移動し、``CaaSP管理ノード``式にチェックを付けます。
. ［btn:[保存]］をクリックし、highstateを適用します。


[NOTE]
====
highstateが完了するまで、管理ノードを使用しないでください。
====


menu:クラスタ[概要]に移動して、既知のクラスタを一覧表示します。 このリストには、既存のすべてのクラスタ、クラスタの種類、および関連付けられている管理ノードが表示されます。 ノードが{productname}に登録されている場合、クラスタ内のノードも表示されます。 クラスタ内のノードでは、``skuba``および{kube} APIの追加情報が表示されます。情報には、ロール、情報、更新があるかどうかが含まれています。




.プロシージャ: 管理ノードの設定
. ``skuba``設定ディレクトリをクラスタから管理ノードにコピーします。
    これは、クラスタをブートストラップした後に``skuba``サービスが作成したディレクトリです。 {productname}の{webui}でクラスタを追加するために、新しいファイルの場所をメモします。
. 認証方法を提供します。

{caasp}クラスタを認証する方法は2つあります。環境に最適なメソッドを選択します。

* クラスタノードへのアクセスに使用しパスワードのない秘密SSH鍵を{productname}サーバにコピーし、ファイルの場所をメモします。
    現在のキーおよび今後使用するクライアントのキーが必要です。
* ``ssh-agent``ソケットを使用して、クラスタを設定するときにソケットへのパスを指定できます。

{caasp}で``ssh-agent``を使用する方法は2つあります。 ``ssh-agent``をローカルで使用できます。また、`ssh-agent`を他のマシンから管理ノードに転送できます。



.プロシージャ: ローカルでssh-agentを使用する
. 管理ノードのコマンドプロンプトで、``ssh-agent``サービスを起動します。
+
----
eval $(ssh-agent)
----
. SSHキーを追加します。
+
----
ssh-add <key>
----
. エージェントにアクセスするために使用するソケットは``$SSH_AUTH_SOCK``環境変数にあります。



.プロシージャ: ssh-agentを管理ノードに転送する
. ``ssh-agent``を提供するシステムのコマンドプロンプトで、SSHの転送を有効にし、管理ノードのホスト名を指定します。
+
----
ssh -A <management node>
----
. エージェントにアクセスするために使用するソケットは``$SSH_AUTH_SOCK``環境変数にあります。


[NOTE]
====
``ssh-agent``メソッドを使用している場合、ソケットのパスは、新しい``ssh-agent```が開始されるまたは新しい``ssh -A``接続が開始されるたびに変更されます。 ``ssh-agent``ソケットのパスは、{productname}の{webui}からいつでも更新できます。 ソケットのパスは、SSHアクセスを必要とするクラスタアクション開始時にも上書きできます。
====



== クラスタの管理

{productname}でクラスタを管理するには、{webui}でクラスタを追加します。



.プロシージャ: 既存のクラスタの追加
. {productname}の{webui}で、menu:クラスタ[概要]に移動し、［btn:[追加]］をクリックします。
. クラスタの種類などクラスタに関する情報を提供するプロンプトに従い、関連付ける管理ノードを選択します。
. クラスタの``skuba``設定ファイルへのパスを入力します。
. 使用するパスワードのないSSHキーを入力します。または``ssh-agent``ソケットへのパスを提供します。
. クラスタの名前、ラベル、および説明を入力します。
. ［btn:[追加]］をクリックします。


{productname}を使用して管理するクラスタでは、対応するシステムグループが作成されます。 デフォルトでは、システムグループは、``クラスタ<cluster_name>``と呼ばれています。 システムグループを更新し、ノードの一覧を更新します。 {productname}が認識しているノードのみ表示されます。


{productname}からクラスタを削除できます。そのためには、menu:クラスタ[概要]に移動し、削除するクラスタのチェックを外し、［btn:[クラスタの削除]］をクリックします。


[IMPORTANT]
====
クラスタを削除すると、{productname}からそのクラスタが削除されます。クラスタノードは削除されません。 クラスタ上で実行中のワークロードは中断されないままです。
====



== ノードの管理

{productname}で作成したクラスタがある場合、そのクラスタ内のノードを管理できます。

新しいノードをクラスタに追加する前に、パスワードのないSSH、または転送している``ssh-agent``ソケットを使用して、追加するノードに管理ノードからアクセスできることを確認してください。

追加するノードが{productname}に登録されていて、{caasp}チャンネルが割り当てられていることも確認する必要があります。

ノードをクラスタに追加する前に、手動設定が必要な場合があります。 システムが{caasp}ノード専用でありスワップがオフになっていることを確認してください。 詳細については、https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-deployment/#_disabling_swapを参照してください。



.プロシージャ: ノードをクラスタに追加する
. {productname}の{webui}で、menu:クラスタ[概要]に移動し、［btn:[ノードの参加]］をクリックします。
. 追加するノードを使用可能ノードの一覧から選択します。
    使用可能ノードの一覧には、{productname}に登録されていて、管理ノードではなく、クラスタの一部ではないノードのみが含まれます。
. プロンプトに従って、追加するノードの{caasp}パラメータを入力します。
. オプション: 追加するノードに対してのみ有効なカスタム``ssh-agent``ソケットを指定します。
. ［btn:[保存]］をクリックして、ノードを{caasp}クラスタに追加するアクションをスケジュールします。



.プロシージャ: クラスタからノードを削除する
. {productname}の{webui}で、menu:クラスタ[概要]に移動し、削除するノードのチェックを外し、［btn:[ノードの削除]］をクリックします。
. プロンプトに従って、削除するノードのパラメータを定義します。
. オプション: 削除するノードに対してのみ有効なカスタム``ssh-agent``ソケットを指定します。
. ［btn:[保存]］をクリックして、ノードを削除するアクションをスケジュールします。

ノードの削除の詳細については、https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_permanent_removalを参照してください。



== クラスタのアップグレード

クラスタに使用可能な更新がある場合、{productname}を使用して、更新をスケジュールして管理できます。

{productname}は、まずすべての制御プレーンをアップグレードし、次にワーカをアップグレードします。 詳細については、https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_cluster_updatesを参照してください。


.プロシージャ: クラスタのアップグレード
. {productname}の{webui}で、menu:クラスタ[概要]に移動し、アップグレードするクラスタをクリックします。
. オプション: アップグレードするためにカスタマイズできる{caasp}パラメータはありません。
    ただし、アップグレードするノードに対してのみ有効なカスタム``ssh-agent``ソケットを指定できます。
. ［btn:[保存]］をクリックして、クラスタをアップグレードするアクションをスケジュールします。


[NOTE]
====
{productname}は``skuba``とのみやり取りし、クラスタをアップグレードします。 設定変更などその他の必要なアクションは{productname}では実行されません。
====


アップグレードの詳細については、https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4を参照してください。
