[[autoinstallation]]
= 操作系统安装
:revdate: 2025-05-20
:page-revdate: {revdate}

通常，您注册的是已经在运行的客户端。您可能是在将这些计算机注册到 {productname} 之前手动安装了它们，也可能它们是在您将 {productname} 添加到您的环境之前就已安装的现有系统。

您也可以使用 {productname} 一次性完成安装操作系统和将其注册到 {productname} 的操作。此方法部分或完全自动化，因此可为您节省回答安装程序问题的时间，特别适合您有许多客户端需要安装和注册的情况。

可通过多种方法从 {productname} 安装操作系统：

* 在已注册的客户端上就地安装；
* 使用 PXE 引导通过网络安装；
* 准备好安装 CD-ROM 或 USB 密钥，然后前往目标计算机并从该媒体引导；
* 作为 {productname} {smr} 解决方案的一部分安装。

就地安装方法假设客户端上已经安装了以前的操作系统，并且客户端已注册到 {productname}。

有关就地安装方法的信息，请参见 xref:client-configuration:autoinst-reinstall.adoc[重新安装已注册系统]。

网络引导安装方法适用于未格式化的计算机。不过，该方法只能在特定网络配置中执行：

* {productname} 服务器（或其代理之一）与您要安装的计算机位于同一本地网络中，或者您具有可用于跨越两者之间的所有路由器的 DHCP 中继；
* 您能够设置新的 DHCP 服务器或配置现有的 DHCP 服务器；
* 要安装的客户端能够使用 PXE 引导，并且您可以如此配置它们。

//For information about the network boot method, see xref:client-configuration:autoinst-pxeboot.adoc[Install via the Network].

可移动媒体方法可让您绕过这些网络约束。但是，该方法假设计算机能够读取 CD-ROM 或 USB 密钥，并从它们引导。它还需要对客户端计算机进行物理访问。

有关可移动媒体方法的信息，请参见 xref:client-configuration:autoinst-cdrom.adoc[通过 CD-ROM 或 USB 密钥安装]。

ifeval::[{mlm-content} == true]

有关 {productname} {smr} 方法的信息，请参见 xref:retail:retail-overview.adoc[Retail 指南]。
endif::[]

ifeval::[{uyuni-content} == true]

有关 {productname} {smr} 方法的信息，请参见 xref:retail:uyuni-retail-overview.adoc[零售指南]。
endif::[]

[NOTE]
====
不支持自动安装 {ubuntu} 和 {debian} 客户端。必须手动安装这些操作系统。
====

{productname} 的自动安装功能基于名为 {cobbler} 的软件运行。有关 {cobbler} 的详细信息，请访问 https://cobbler.readthedocs.io[]。

[NOTE]
====
{suse} 仅支持 {productname} {webui} 中或通过 {productname} API 提供的 {cobbler} 功能。Cobbler 支持的唯一一个命令行命令为 [command]``buildiso``。本文中所述的仅为支持的功能。
====
