[[autoinst-profiles]]
= 自动安装配置文件

An autoinstallation profile determines how the operating system will be installed. For example, you can specify additional kernel parameters to be passed to the installer.

The most important part of the profile is the "autoinstallation file". When you perform an installation manually, you must provide information to the installer, such as partitioning and networking information and user details. The autoinstallation file is a method of providing this information in a scripted form. This type of file is sometimes also referred to as an "answers file".

Within {productname}, you can use two different types of profiles, depending on the operating system of the clients you want to install:

* 对于 {sle} 客户端，请使用 {ay}。
* 对于 {rhel} 客户端，请使用 {kickstart}。

You can use both {ay} and {kickstart} profiles if you want to install clients with different operating systems.

For information about how to declare profiles, see xref:client-configuration:autoinst-profiles.adoc#declare-profile[Declare the Profile]

For information about {ay} profiles, see xref:client-configuration:autoinst-profiles.adoc#autoyast[AutoYast Profiles].

For information about {kickstart} profiles, see xref:client-configuration:autoinst-profiles.adoc#kickstart[Kickstart Profiles].

The autoinstallation file contained in the profile can include variables and code snippets. For information about variables and code snippets, see xref:client-configuration:autoinst-profiles.adoc#templates-syntax[Templates Syntax].


[[declare-profile]]
== Declare the Profile

When you have prepared an autoinstallation file and distribution, you can create profiles to manage autoinstallation on your {productname} Server. For a given distribution, the profile will determine how to install this distribution.

One way to create a profile is to upload an {ay} or {kickstart} file. Alternatively, for {kickstart} only, you can use the {webui} wizard.



.过程：通过上载创建自动安装配置文件
. 在 {productname} {webui} 中，导航到menu:系统[自动安装 > 配置文件]。
. 单击 btn:[上载 Kickstart/Autoyast 文件]。
. In the [guimenu]``Label`` field, type a name for the profile. Do not use spaces.
. In the [guimenu]``Autoinstall Tree`` field, select the autoinstallable distribution to use for this profile.
. In the [guimenu]``Virtualization Type`` field, select the type of virtualization to use for this profile, or select ``None`` if you do not want to use this profile to create a new virtual machine.
. Copy the contents of your autoinstallation file into the [guimenu]``File Contents`` field, or upload the file directly using the [guimenu]``File to Upload`` field. For more information about the details to include here, see xref:client-configuration:autoinst-profiles.adoc#autoyast[AutoYast Profiles] or xref:client-configuration:autoinst-profiles.adoc#kickstart[Kickstart Profiles].
. 单击 btn:[创建] 以创建配置文件。



.过程：通过向导创建 {kickstart} 配置文件
. 在 {productname} {webui} 中，导航到menu:系统[自动安装 > 配置文件]。
. 单击 btn:[创建 Kickstart 配置文件]。
. In the [guimenu]``Label`` field, type a name for the profile. Do not use spaces.
. 在[guimenu]``基础频道``字段中，选择要用于此配置文件的基础频道。
    系统会根据可用的发行套件填充此字段。 如果您需要的基础频道不可用，请检查您是否正确创建了发行套件。
. 在[guimenu]``虚拟化类型``字段中，选择要用于此配置文件的虚拟化类型，或选择``无``（表示不进行虚拟化）。
. 单击 btn:[下一步]。
. 在[guimenu]``发行套件文件位置``中，键入 {productname} 服务器上安装的安装媒体的路径。
. 单击 btn:[下一步]。
. 提供客户端上 root 用户的口令。
. 单击 btn:[完成]。
. 查看新配置文件的细节，并视需要进行自定义。

创建自动安装配置文件时，您可以选中[guimenu]``始终为此基础频道使用最新的树``。 此设置可让 {productname} 自动提取与指定基础频道关联的最新发行套件。 如果您以后添加新发行套件，{productname} 会使用最近创建或修改的发行套件。

更改虚拟化类型通常需要更改配置文件加载程序和分区选项。 这会重写您的自定义设置。 请在保存前导航到[guimenu]``分区``选项卡校验新的或更改后的设置。

The kernel options from the distribution and the profile are combined.

You can change the details and settings of your autoinstallation profiles by navigating to menu:Systems[Autoinstallation > Profiles] and clicking the name of the profile you want to edit. Alternatively, navigate to menu:Systems[System List], select the client you want to provision, and navigate to the menu:Provisioning[Autoinstallation] subtab.


[[autoyast]]
== AutoYast Profiles

An {ay} profile consists of a [guimenu]``Label`` that identifies the profile, an [guimenu]``Autoinstall Tree`` that points to an autoinstallable distribution, various options, and, most importantly, an {ay} installation file.

The {ay} installation file is an XML file that give directions to the {ay} installer. {ay} calls it a "control file". For the full syntax of {ay} installation files, see https://doc.opensuse.org/projects/autoyast/#cha-configuration-installation-options.

{suse} provides templates of {ay} installation files that you can use as a starting point for your own custom files. You will find them at https://github.com/SUSE/manager-build-profiles in the directory named [path]``AutoYast``. Each of these profiles requires you to set some variables before you use it. Check the [path]``README`` file included with the script to determine which variables you need. For more information about using variables in {ay} scripts, see xref:client-configuration:autoinst-profiles#variables[Variables].

Here are the most important sections in the {ay} installation file for installing with SUSE Manager:
* ``<add-on>`` section allows to add child channels to the installation
* ``<general>$SNIPPET('spacewalk/sles_no_signature_checks')</general>` disables signature checks
* ``<software>`` allows to specify the correct product for the Unified Installer
* ``<init-scripts config:type="list">$SNIPPET('spacewalk/minion_script')</init-scripts>`` allows the client to register to {productname} as a Salt minion.

有关 {ay} 的详细信息，请参见 https://doc.opensuse.org/projects/autoyast/。

A more recent, Salt-based alternative to AutoYast, is Yomi. For information about Yomi, see xref:salt:yomi.adoc[Install with Yomi].


[[kickstart]]
== Kickstart 配置文件

{kickstart} profiles offer a large number of configuration options. To create these profiles, you can upload them, or use a dedicated wizard.

{kickstart} profiles allow you to use file preservation lists. If you have many custom configuration files located on a client you want to reinstall with {kickstart}, you can save them as a list, and associate that list with the {kickstart} profile.



.Procedure: Creating a File Preservation List
. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > File Preservation] and click btn:[Create File Preservation List].
. Enter a suitable label, and list absolute paths to all files and directories you want to save.
. Click btn:[Create List].
. Include the file preservation list in your {kickstart} profile. Navigate to menu:Systems[Autoinstallation > Profiles] and select the profile you want to edit, go to the menu:System Details[File Preservation] subtab, and select the file preservation list to include.

[NOTE]
====
File preservation lists are limited to a total size of 1{nbsp}MB. Special devices like [path]``/dev/hda1`` and [path]``/dev/sda1`` cannot be preserved. Only use file and directory names, you cannot use regular expression wildcards.
====

For more information about Kickstart, see the Red Hat documentation.


[[templates-syntax]]
== Templates Syntax

Parts of your installation file are replaced during the installation. Variables are replaced with single values, and code snippets are replaced with whole sections of text. Escaped symbols or sections are not replaced.

A template engine called Cheetah allows Cobbler to do these replacements. This mechanism allows you to reinstall large numbers of systems, without having to manually create profiles for each of them.

You can create autoinstallation variables and code snippets within the {productname} {webui}. Within a profile, the [guimenu]``Autoinstallation File`` tab allows you to see the result of the substitutions.

For information about variables, see xref:client-configuration:autoinst-profiles#variables[Variables]. For information about code snippets, see xref:client-configuration:autoinst-profiles#code-snippets[Code Snippets]. For information about escaping symbols or whole sections, see xref:client-configuration:autoinst-profiles#variables[Escaping].


[[variables]]
=== 变量

Autoinstallation variables can be used to substitute values into {kickstart} and {ay} profiles. To define a variable, from the profile, navigate to the [guimenu]``Variables`` subtab, and create a [replaceable]``name=value`` pair in the text box.

For example, you could create a variable that holds the IP address of the client, and another that holds the address of its gateway. Those variables can then be defined for all the clients installed from the same profile. To do that, add these lines to the [guimenu]``Variables`` text box:
----
ipaddr=192.168.0.28
gateway=192.168.0.1
----

To use the variable, prepend a [option]``$`` sign in the profile to substitute the value. For example, the [option]``network`` part of a {kickstart} file may look like the following:
----
network --bootproto=static --device=eth0 --onboot=on --ip=$ipaddr \
  --gateway=$gateway
----

The [option]``$ipaddr`` is resolved to ``192.168.0.28``, and the [option]``$gateway`` to ``192.168.0.1``.

In installation files, variables use a hierarchy. System variables take precedence over profile variables, which in turn take precedence over distribution variables.


[[code-snippets]]
=== 代码段

{productname} comes with a large number of predefined code snippets. Navigate to menu:Systems[Autoinstallation > Autoinstallation Snippets] to see the list of existing snippets.

Use a snippet by inserting the [option]``$SNIPPET()`` macro in your autoinstallation file. For example, in {kickstart}:
----
$SNIPPET('spacewalk/rhel_register_script')
----

Or, in {ay}:
----
<init-scripts config:type="list">
  $SNIPPET('spacewalk/sles_register_script')
</init-scripts>
----

The macro is parsed by Cobbler and substituted with the contents of the snippet. You can also store your own code snippets to use in autoinstallation files later on. Click btn:[Create Snippet] to create a new code snippet.

This example sets up a {kickstart} snippet for a common hard drive partition configuration:
----
clearpart --all
part /boot --fstype ext3 --size=150 --asprimary
part / --fstype ext3 --size=40000 --asprimary
part swap --recommended

part pv.00 --size=1 --grow

volgroup vg00 pv.00
logvol /var --name=var vgname=vg00 --fstype ext3 --size=5000
----

Use the snippet with, for example:
----
$SNIPPET('my_partition')
----


[[escaping]]
=== Escaping

If the autoinstallation file contains shell script variables like ``$(example)``, the content needs to be escaped with a backslash: ``\$(example)``. Escaping the ``$`` symbol prevents the templating engine from evaluating the symbol as an internal variable.

Long scripts or strings can be escaped by wrapping them with the ``\#raw`` and ``\#end`` directives. For example:
----
#raw
#!/bin/bash
for i in {0..2}; do
 echo "$i - Hello World!"
done
#end raw
----

Any line with a ``#`` symbol followed by a whitespace is treated as a comment and is therefore not evaluated. For example:
----
# start some section（此为注释）
echo "Hello, world"
# end some section（此为注释）
----
