[[channels]]
= 软件通道
:revdate: 2024-12-12
:page-revdate: {revdate}

通道是一种用于对软件包分组的方法。软件包由储存库提供，而储存库与通道关联。客户端订阅软件通道后，便可安装并更新与其关联的任何软件。

在 {productname} 中，通道分为基础通道和子通道。以此方式组织通道可确保每个系统上只安装兼容的软件包。客户端只能订阅一个基础通道，该通道是在注册期间根据客户端操作系统和体系结构指派的。对于供应商提供的付费通道，您必须具有关联的订阅。

基础通道中包含为特定操作系统类型、版本和体系结构构建的软件包。例如，{sles}{nbsp}15 {x86_64} 基础通道中仅包含与该操作系统和体系结构兼容的软件。

子通道与基础通道关联，仅提供与基础通道兼容的软件包。一个系统可订阅其基础通道的多个子通道。将系统指派到基础通道后，该系统便只能安装相关的子通道。例如，如果将系统指派到 {sles}{nbsp}15 `x86_64` 基础通道，那么便只能安装或更新通过兼容基础通道或它的任何关联子通道提供的软件包。

在 {productname} {webui} 中，您可以导航到menu:软件[通道列表 > 所有]来浏览可用通道。您可以通过导航到menu:软件[管理 > 通道]修改或创建新通道。

有关使用通道（包括自定义通道）的详细信息，请参见 xref:administration:channel-management.adoc[]。

.引导后处理安装程序更新通道
[IMPORTANT]
====
客户端系统引导完成后，应立即去除**安装程序更新**通道。标准更新通道已经包含必要的更新，因此该通道是多余的。

此外，在迁移期间，该通道也不是必需的，不应使用。
====

== 通过 {phub} 提供的软件包


{phub} 是 {sle} 产品的扩展，用于提供额外的开源软件（由 {opensuse} 社区提供）。

[IMPORTANT]
====
{phub} 中的软件包由 {opensuse} 社区提供。{suse} 不会为这些软件包提供支持。
====

如果您在客户端上使用的是 {sle} 操作系统，则可启用 {phub} 扩展来访问这些额外的软件包。这样会提供 {phub} 通道，您可以为客户端订阅这些通道。

{phub} 提供了大量软件包，可能需要花很长时间进行同步，并会占用大量磁盘空间。除非您确实需要 {phub} 提供的软件包，否则请不要启用它。

为了避免无意间安装或更新不支持的软件包，建议您实施一开始会拒绝所有 {phub} 软件包的内容生命周期管理策略。然后，您可以显式启用所需的特定软件包。有关内容生命周期管理的详细信息，请参见 xref:administration:content-lifecycle.adoc[]。



== 通过 AppStream 提供的软件包

对于基于 {redhat} 的客户端，通过 AppStream 来提供额外的软件包。大多数情况下都需要 AppStream 软件包来确保您已拥有所有必需的软件。



== 通过 EPEL 提供的软件包

对于基于 {redhat} 的客户端，通过 EPEL 提供额外的软件包（适用于企业版 Linux 的额外软件包）。EPEL 是可选软件包储存库，用于提供额外的软件。

[IMPORTANT]
====
EPEL 中的软件包由 Fedora 社区提供。{suse} 不会为这些软件包提供支持。
====

如果您在客户端上使用的是 {redhat} 操作系统，则可启用 EPEL 扩展来访问这些额外的软件包。这样会提供 EPEL 通道，您可以为客户端订阅这些通道。

EPEL 提供了大量软件包，可能需要花很长时间进行同步，并会占用大量磁盘空间。除非您确实需要 EPEL 提供的软件包，否则请不要启用 EPEL 储存库。

为了避免无意间安装或更新不支持的软件包，建议您实施一开始会拒绝所有 EPEL 软件包的内容生命周期管理 (CLM) 策略。然后，您可以显式启用所需的特定软件包。有关内容生命周期管理的详细信息，请参见 xref:administration:content-lifecycle.adoc[]。



== {sle} 客户端的 {unifiedinstaller} 更新通道

{unifiedinstaller} 使用此通道来确保其在安装操作系统前是最新的。所有 {sle} 产品在安装期间都应能够访问安装程序更新通道。

对于 {sles} 客户端，默认会在您添加包含安装程序更新通道的产品时对这些通道进行同步，并会在您创建包含这些产品通道的可自动安装发行套件时予以启用。

对于所有其他 {sle} 变体，包括 {sle} for SAP，您必须手动添加安装程序更新通道。要完成此操作，请克隆这些 {sle} 变体的基础通道下的相应 {sles} 安装程序更新通道。克隆通道后，为这些 {sle} 变体创建可自动安装的发行套件时，会自动使用相应通道。
