[[client-upgrades-uyuni]]
= 升级 Uyuni 客户端

. 在 {productname} Server 上的命令提示符下，以 root 身份使用 [command]``spacewalk-common-channels`` 命令添加相应的频道：
+
----
spacewalk-common-channels \
opensuse_leap15_2 \
opensuse_leap15_2-non-oss \
opensuse_leap15_2-non-oss-updates \
opensuse_leap15_2-updates \
opensuse_leap15_2-uyuni-client
----

. 使用 [command]``spacewalk-repo-sync`` 完全同步所有频道。 对于已定义的储存库 URL，继续 xref:upgrade:proxy- uyuni.adoc#uyuni-202007-channeldupes[]。
+

. 在 {productname} 服务器 {webui} 中，导航到menu:软件[管理 > 频道]，然后单击 [systemitem]``Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)`` 频道名称。

. 在右上角单击 btn:[管理频道]。

. 单击[guimenu]``储存库``选项卡，然后选择[systemitem]``外部 - Uyuni Client Tools for openSUSE Leap 15.1 (x86_64)``。

. 单击 btn:[更新储存库]。

. 导航到menu:储存库[同步]子选项卡，然后单击 btn:[立即同步]。

. 对 [systemitem]``openSUSE Leap 15.2 (x86_64)`` 和[systemitem]``外部 - openSUSE Leap 15.1 (x86_64)`` 执行相同的操作。

展开 [systemitem]``openSUSE Leap 15.2 (x86_64)`` 以查看填充了软件包的所有子频道。



== 升级客户端

要升级客户端，您需要替换软件储存库，然后更新软件，最后重引导客户端。



.过程：更新客户端


. 在 {productname} 服务器 {webui} 中，导航到menu:系统[]，然后单击客户端的名称。
. 单击menu:软件[软件频道]，选择[systemitem]``自定义频道``列表中所列的 openSUSE Leap {opensuse-version} 频道作为基础频道。
. 在[guimenu]``子频道``窗格中，选择 {opensuse-version} 子频道。
. 单击 btn:[下一步]，然后单击 [guimenu]````btn:[确认] 以确认软件频道更改。
. 单击menu:软件[软件包 > 升级]，选择客户端上要更新的所有软件包，然后应用选择。 单击 btn:[升级软件包]，查看细节，然后单击 btn:[确认] 以完成更新。
+
+
+
. 重引导客户端。

如果需要更新许多客户端，可以在 {productname} 服务器上创建由此命令序列组成的操作链。 您可以使用操作链同时对多个客户端执行更新。




