[[clients-centos]]
= 注册 {centos} 客户端

本节包含有关注册运行 {centos} 操作系统的传统客户端和 Salt 客户端的信息。

[IMPORTANT]
====
{centos} 客户端基于 {centos}，与 {sleses}、RES、{redhat} 或 {es} 不相关。 您需负责安排对 {centos} 基础媒体储存库和 {centos} 安装媒体的访问权限，以及将 {productname} 服务器连接到 {centos} 内容分发网络。
====

[NOTE]
====
传统客户端不适用于 {centos}{nbsp}8。 仅当 {centos}{nbsp}8 客户端为 Salt 客户端时才受支持。
====

[NOTE]
====
我们已使用``针对性``策略并采用默认的 ``enforcing`` SELinux 配置对将 {centos} 客户端注册到 {productname} 的过程进行了测试。 将 {centos} 客户端注册到 {productname} 时，您无需禁用 SELinux。
====



== 添加软件频道

将 {centos} 客户端注册到您的 {productname} 服务器之前，您需要添加所需的软件频道，并同步这些频道。

ifeval::[{suma-content} == true]

此过程所需的产品包括：

[[centos-channels-wizard]]
[cols="1,1", options="header"]
.CentOS 产品 - WebUI
|===
| 操作系统版本 | 产品名称
| {centos} 6 | CentOS 6 x86_64
| {centos} 7 | CentOS 7 x86_64
| {centos} 8 | CentOS 8 x86_64
|===

[NOTE]
====
{centos} 6 is now at end-of-life, and the ISO images provided in the repository are out of date. Bootstrapping new {centos} 6 clients using these packages will fail. If you need to bootstrap new {centos} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_vendor_webui.adoc[]

或者，您也可以在命令提示符处添加频道。 此过程所需的频道包括：

[[centos-channels-suma-cli]]
[cols="1,1", options="header"]
.CentOS 频道 - CLI
|===
| 操作系统版本 | 基础频道
| {centos} 6 | centos6-x86_64
| {centos} 7 | centos7-x86_64
| {centos} 8 | centos8-x86_64
|===

[NOTE]
====
{centos} 6 is now at end-of-life, and the ISO images provided in the repository are out of date. Bootstrapping new {centos} 6 clients using these packages will fail. If you need to bootstrap new {centos} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]
此过程所需的频道包括：

[[centos-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.CentOS 频道 - CLI
|===
| OS Version | Base Channel | Client Channel       | Updates/Appstream Channel
| {centos} 6 | centos6      | centos6-uyuni-client | centos6-updates
| {centos} 7 | centos7      | centos7-uyuni-client | centos7-updates
| {centos} 8 | centos8      | centos8-uyuni-client | centos8-appstream
|===

[NOTE]
====
{centos} 6 is now at end-of-life, and the ISO images provided in the repository are out of date. Bootstrapping new {centos} 6 clients using these packages will fail. If you need to bootstrap new {centos} 6 clients, follow the troubleshooting procedure in xref:client-configuration:tshoot-clients.adoc[].
====

include::snippets/addchannels_novendor_cli_multiarch.adoc[]

[NOTE]
====
[command]``spacewalk-common-channels`` 提供的客户端工具频道来自 {uyuni} 而非 {suse}。
====

endif::[]


[IMPORTANT]
====
对于 {centos} 8 客户端，请添加基础频道和 AppStream 频道。 您需要来自这两个频道的软件包。 如果未添加这两个频道，将会因缺少软件包而无法创建引导储存库。
====


[NOTE]
====
您可能会发现 AppStream 频道中提供的软件包数量在上游频道和 {productname} 频道之间存在一定的差异。 如果您对在不同时间添加的同一频道进行比较，会发现其数量也不相同。 这是由 {centos} 管理其储存库的方式所致。 当有新版本发布时，{centos} 会去除软件包的较旧版本，而 {productname} 则会保留所有版本，无论新旧与否。
====


include::snippets/appstream_admon.adoc[]


== 检查同步状态

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]


include::snippets/check_sync_cli.adoc[]



== 创建激活密钥

您需要创建与您的 {centos} 频道关联的激活密钥。

有关激活密钥的详细信息，请参见 xref:client-configuration: activation-keys.adoc[]。



ifeval::[{uyuni-content} == true]

== 在客户端上信任 GPG 密钥

include::snippets/trust_gpg.adoc[]

endif::[]



== 注册客户端

{centos} 客户端的注册方式与所有其他客户端的注册方式相同。 有关详细信息，请参见 xref:client-configuration:registration-overview.adoc[]。


[WARNING]
====
要注册和使用 {centos}{nbsp}6 客户端，您需要配置 {productname} 服务器以支持较旧类型的 SSL 加密。 有关如何解决此错误的详细信息，请参见 xref:client-configuration:tshoot-clients.adoc[] 中的``注册较旧的客户端``。
====



== 管理勘误

当您更新 {centos} 客户端时，软件包不包含有关更新的元数据。 您可以使用第三方勘误服务来获取此信息。

[WARNING]
====

ifeval::[{suma-content} == true]

本文介绍的第三方勘误服务 CEFS 由社区提供和维护， 不受 {suse} 支持。

endif::[]

CEFS 的作者会按照尽力而为的原则提供补丁或勘误，希望它们有用，但无法保证其正确性或及时性。 这意味着补丁日期可能不正确，且至少在一种情况下所显示的发布数据滞后一个多月。 有关这些情况的详细信息，请参见 https://github.com/stevemeier/cefs/issues/28#issuecomment-656579382 和 https://github.com/stevemeier/cefs/issues/28#issuecomment-656573607。

任何有关补丁数据的问题或滞后都可能导致将不可靠的补丁信息导入到您的 {productname} 服务器中， 进而导致报告、审计、CVE 更新或其他与补丁相关的信息也不正确。 请考虑使用其他方案来替代此服务，例如独立校验补丁数据或选择其他操作系统，具体取决于您的安全相关要求和认证准则。
====




.过程：安装勘误服务

. 在 {productname} 服务器上的命令提示符处，以 root 身份添加 ``sle-module-development-tools`` 模块：
+
----
SUSEConnect --product sle-module-development-tools/15.2/x86_64
----
. 安装勘误服务依赖项：
+
----
zypper in  perl-Text-Unidecode
----
. 在 [path]``/etc/rhn/rhn.conf`` 中添加或编辑下面一行：
+
----
java.allow_adding_patches_via_api = centos7-updates-x86_64,centos7-x86_64,centos7-extras-x86_64
----
. 重启动 Tomcat：
----
systemctl restart tomcat
----
. 为勘误脚本创建一个文件：
+
----
touch /usr/local/bin/cent-errata.sh
----
. 编辑新文件以包含此脚本，并视需要编辑储存库细节。
    此脚本会从外部勘误服务提取勘误细节，将其解压缩，然后发布这些细节：
+
----
#!/bin/bash
mkdir -p /usr/local/centos
cd /usr/local/centos
rm *.xml
wget -c http://cefs.steve-meier.de/errata.latest.xml
#wget -c https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml
wget -c https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml
wget -c http://cefs.steve-meier.de/errata-import.tar
tar xvf errata-import.tar
chmod +x /usr/local/centos/errata-import.pl
export SPACEWALK_USER='<adminname>';export SPACEWALK_PASS='<password>'
/usr/local/centos/errata-import.pl --server '<servername>' \
--errata /usr/local/centos/errata.latest.xml  \
--include-channels=centos7-updates-x86_64,centos7-x86_64,centos7-extras-x86_64 \
--publish --rhsa-oval /usr/local/centos/com.redhat.rhsa-RHEL7.xml
----
. 设置 cron 作业以每日运行该脚本：
+
----
ln -s /usr/local/bin/cent-errata.sh /etc/cron.daily
----

有关此工具的详细信息，请参见 https://cefs.steve-meier.de/。
