[[client-proxy]]
= 将客户端注册到代理
:revdate: 2024-03-05
:page-revdate: {revdate}


代理服务器可充当客户端的中介和软件包缓存。将客户端注册到代理与将其直接注册到 {productname} 服务器的过程类似，主要差异只有几处。

以下章节包含有关使用 {webui}、命令行命令或引导脚本将客户端注册到代理的信息，以及有关将客户端从一个 {productname} 代理移至另一个代理或 {productname} 服务器的过程。

在 {webui} 中，代理页面会显示有关客户端的信息。可以在menu:系统[系统列表 > 代理]中单击代理的名称，然后选择[guimenu]``细节``选项卡的[guimenu]``代理``子选项卡，以查看连接到代理的客户端列表。

在menu:系统[所有]中单击某个客户端的名称，然后选择[guimenu]``细节``选项卡的[guimenu]``连接``子选项卡，可以查看该客户端关联的代理列表。



== 在代理之间移动客户端


无需重复注册过程，即可在代理之间移动 {salt} 客户端和 {salt} SSH 推送客户端。

[IMPORTANT]
====
链式代理无法移动。您应创建新代理，移动客户端，然后删除旧代理，而不是移动链式代理。
====



.过程：在代理之间移动客户端或 {salt} SSH 推送客户端

. 在 {productname} {webui} 中，导航到要在代理之间移动的客户端的[guimenu]``系统细节``页面。
. 导航到[guimenu]``连接``选项卡，然后单击[guimenu]``更改代理``链接，您会看到下拉菜单。
. 在[guimenu]``新代理``下拉菜单中，选择要移动到的目标代理，然后单击 btn:[更改代理]。



.过程：使用 SSM 在代理之间移动多个客户端或 {salt} SSH 推送客户端

. 在 {productname} {webui} 中，导航到menu:系统[系统列表]，然后选中要移动的每个客户端，如此会将这些客户端添加到系统集管理器中。
. 导航到menu:系统[系统集管理器]，然后转到menu:其他[代理]选项卡。
. 在[guimenu]``新代理``下拉菜单中，选择要将客户端移动到的目标代理，然后单击 btn:[更改代理]。

通过调用 [systemitem]``system.changeProxy`` 也能使用该功能。



=== 背景信息
此功能对常规 Salt 客户端与 Salt SSH Push 客户端的作用有所不同。


==== 默认客户端

该功能会安排一项 {salt} 状态操作，该操作会修改 [path]``susemanager.conf`` {salt} 配置文件中的 [literal]``master:`` 设置，使其指向新代理。然后该功能会重启 {salt} 客户端。

[NOTE]
====
通过手动编辑 [path]``susemanager.conf`` 文件来更改 [literal]``master:`` 也有同样的效果，并且系统也支持这种方式。
====

当客户端重启并通过新代理重新连接时，服务器会在数据库中更新代理路径，并安排另一项操作来刷新通道 URL。



==== {salt} SSH 推送客户端

该功能会立即在数据库中更新代理路径并安排新操作来刷新通道 URL。



== 将客户端从代理移到服务器

如果您要将客户端从代理移到服务器，请从代理列表中选择[literal]``无``。


