[[salt-client-proxy]]
= 使用 {webui} 将客户端注册到代理

您可以使用 {webui} 将 Salt 客户端注册到 {productname} 代理。


[NOTE]
====
通常的非 SLE 客户端和早于版本 15 的 SLE 客户端都需要引导储存库。 引导储存库提供用于在客户端上安装 Salt 的软件包，以及用于注册 Salt 客户端或传统客户端的软件包。 有关如何创建引导储存库的信息，请参见 xref:client- configuration:bootstrap-repository.adoc[]。
====


.过程：使用 {webui} 将客户端注册到代理

. 在 {productname} {webui} 中，导航到menu:系统[引导]。
. 在[guimenu]``主机``字段中，键入要引导的客户端的完全限定域名 (FQDN)。
. 在 [guimenu]``SSH 端口``字段中，键入用于连接和引导客户端的 SSH 端口号。
    SSH 端口默认为 [systemitem]``22``。
. 在[guimenu]``用户``字段中，键入用于登录客户端的用户名。
    用户名默认为 [systemitem]``root``。
. 在[guimenu]``身份验证方法``字段中，选择用于引导客户端的身份验证方法。
+
* 如果选择的是口令身份验证，请在[guimenu]``口令``字段中，键入用于登录客户端的口令。
* 如果选择的是 SSH 私用密钥身份验证，请输入私用密钥和关联的通行口令。
    该密钥的储存期截止到引导过程完成。
. 在[guimenu]``激活密钥``字段中，选择与您要用于引导客户端的软件频道关联的激活密钥。
. 在[guimenu]``代理``字段中，选择要注册到的代理服务器。
. 默认会选中[guimenu]``禁用 SSH 严格密钥主机检查`` 复选框。
    如此可让引导过程自动接受 SSH 主机密钥，而无需您手动进行身份验证。
. 可选：选中[guimenu]``完全通过 SSH 管理系统`` 复选框。
    如果您选中此选项，客户端将会配置为使用 SSH 来连接服务器，且不再配置其他连接方法。
. 单击 btn:[Bootstrap] 开始注册。

引导过程完成时,您的客户端即会列在menu:系统[系统列表]中。



