[[clients-almalinux]]
= Registering {almalinux} Clients

This section contains information about registering Salt clients running {almalinux} operating systems.

[NOTE]
====
Traditional clients are not available on {almalinux}{nbsp}8. {almalinux}{nbsp}8 clients are only supported as Salt clients.
====

[NOTE]
====
Registering {almalinux} clients to {productname} is tested with the default SELinux configuration of ``enforcing`` with a ``targeted`` policy. You do not need to disable SELinux to register {almalinux} clients to {productname}.
====

== 添加软件频道

Before you can register {almalinux} clients to your {productname} Server, you need to add the required software channels, and synchronize them.

ifeval::[{suma-content} == true]

此过程所需的产品包括：

[[almalinux-channels-wizard]]
[cols="1,1", options="header"]
.CentOS 产品 - WebUI
|===
| OS Version | Product Name
| {almalinux} 8 | {almalinux} 8 x86_64
|===

include::snippets/addchannels_vendor_webui.adoc[]

或者，您也可以在命令提示符处添加频道。 此过程所需的频道包括：

[[almalinux-channels-suma-cli]]
[cols="1,1", options="header"]
.CentOS 频道 - CLI
|===
| OS Version | Base Channel
| {almalinux} 8 | almalinux8-x86_64
|===

include::snippets/addchannels_vendor_cli.adoc[]

endif::[]

ifeval::[{uyuni-content} == true]
此过程所需的频道包括：

[[almalinux-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.CentOS 频道 - CLI
|===
| OS Version | Base Channel | Client Channel       | AppStream Channel
| {almalinux} 8 | almalinux8      | almalinux8-uyuni-client | almalinux8-appstream
|===

include::snippets/addchannels_novendor_cli_multiarch.adoc[]

[NOTE]
====
[command]``spacewalk-common-channels`` 提供的客户端工具频道来自 {uyuni} 而非 {suse}。
====

endif::[]


[IMPORTANT]
====
For {almalinux} 8 clients, add both the Base and AppStream channels. You require packages from both channels. If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====


[NOTE]
====
You might notice some disparity in the number of packages available in the AppStream channel between upstream and the {productname} channel. You might also see different numbers if you compare the same channel added at a different point in time. This is due to the way that {almalinux} manages their repositories. {almalinux} removes older version of packages when a new version is released, while {productname} keeps all of them, regardless of age.
====


include::snippets/appstream_admon.adoc[]


== 检查同步状态

ifeval::[{suma-content} == true]

include::snippets/check_sync_webui_suma.adoc[]

endif::[]


ifeval::[{uyuni-content} == true]

include::snippets/check_sync_webui_uyuni.adoc[]

endif::[]


include::snippets/check_sync_cli.adoc[]



== 创建激活密钥

You need to create an activation key that is associated with your {almalinux} channels.

有关激活密钥的详细信息，请参见 xref:client-configuration: activation-keys.adoc[]。



ifeval::[{uyuni-content} == true]

== 在客户端上信任 GPG 密钥

include::snippets/trust_gpg.adoc[]

endif::[]



== 注册客户端

{almalinux} clients are registered in the same way as all other clients. For more information, see xref:client-configuration:registration-overview.adoc[].


== 管理勘误

When you update {almalinux} clients, the packages include metadata about the updates.
