[[clients-centos]]
= 注册 {centos} 客户端
:revdate: 2025-03-10
:page-revdate: {revdate}

本节包含有关注册运行 {centos} 操作系统的客户端的信息。

ifeval::[{mlm-content} == true]

// Use list format: repository URLs / packages and metadata / version info
// Do we need to provide special info for uyuni users?
[IMPORTANT]
====
* {centos} 储存库 URL 可从 {scclongform} 获取。
* 软件包和元数据由 CentOS 而不是 {suse} 提供。
* 有关支持的产品，请参见版本说明和 xref:client-configuration:supported-features-centos.adoc[] 中的支持表格。
====
endif::[]

[IMPORTANT]
====

ifeval::[{mlm-content} == true]

{centos} 客户端基于 {centos}，与 {sleses}、RES、{redhat} 或 {es} 不相关。
endif::[]

您需负责安排对 {centos} 基础媒体储存库和 {centos} 安装媒体的访问权限，以及将 {productname} 服务器连接到 {centos} 内容分发网络。
====

[NOTE]
====
我们已使用``针对性``策略并采用默认的 ``enforcing`` SELinux 配置对将 {centos} 客户端注册到 {productname} 的过程进行了测试。将 {centos} 客户端注册到 {productname} 时，您无需禁用 SELinux。
====



== 添加软件通道


将 {centos} 客户端注册到您的 {productname} 服务器之前，您需要添加所需的软件通道，并同步这些通道。

当前支持的系统结构为 `x86_64` 和 `aarch64`。有关支持的产品和体系结构的完整列表，请参见 xref:client-configuration:supported-features.adoc[]。

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]

ifeval::[{mlm-content} == true]

例如，使用 `x86_64` 体系结构时，您需要如下产品：

[[centos-channels-wizard]]
[cols="1,1", options="header"]
.CentOS 产品 - WebUI
|===

| 操作系统版本 | 产品名称
| {centos} 7 | CentOS 7 x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]

或者，您也可以在命令提示符处添加通道。此过程所需的通道包括：

[[centos-channels-MLM-cli]]
[cols="1,1", options="header"]
.CentOS 通道 - CLI
|===

| 操作系统版本 | 基础通道
| {centos} 7 | centos7-x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_cli.adoc[]
endif::[]

endif::[]

ifeval::[{uyuni-content} == true]
此过程所需的通道包括：

[[centos-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.CentOS 通道 - CLI
|===

| 操作系统版本 | 基础通道 | 客户端通道       | 更新/Appstream 通道
| {centos} 7 | centos7      | centos7-uyuni-client | centos7-updates
|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli_multiarch.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli_multiarch.adoc[]
endif::[]

[NOTE]
====
[command]``spacewalk-common-channels`` 提供的客户端工具通道来自 {uyuni} 而非 {suse}。
====

endif::[]


如果您使用的是模块化通道，则必须在客户端上启用 Python 3.6 模块流。如果不提供 Python 3.6，[package]``spacecmd`` 软件包安装将会失败。

[NOTE]
====
您可能会发现 AppStream 通道中提供的软件包数量在上游通道和 {productname} 通道之间存在一定的差异。如果您对在不同时间添加的同一通道进行比较，会发现其数量也不相同。这是由 {centos} 管理其储存库的方式所致。当有新版本发布时，{centos} 会去除软件包的较旧版本，而 {productname} 则会保留所有版本，无论新旧与否。
====


== 检查同步状态

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]


ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]



== 创建激活密钥

您需要创建与您的 {centos} 通道关联的激活密钥。

有关激活密钥的详细信息，请参见 xref:client-configuration:activation-keys.adoc[]。



== 管理 GPG 密钥

安装软件包之前，客户端会使用 GPG 密钥检查这些软件包的真实性。只有可信软件才能安装在客户端上。

[IMPORTANT]
====
信任 GPG 密钥对于客户端的安全非常重要。由管理员来决定需要哪些密钥，可以信任哪些密钥。这是因为如果不信任 GPG 密钥，便无法使用软件通道，是否将通道指派给客户端取决于是否信任密钥。
====

有关 GPG 密钥的详细信息，请参见 xref:client-configuration:gpg-keys.adoc[]。



== 注册客户端


[NOTE]
====
CentOS 7 初始配置将会失败，原因是 [path]``/etc/yum.repos.d/CentOS-Base.repo`` 中启用了相关 URL，导致 [command]``yum`` 尝试通过 fastmirror 查找储存库。这会使引导过程失败，并出现如下错误消息：

----
无法解析主机：mirrorlist.centos.org；未知错误
----

要解决此问题，您可以通过以下命令去除 [path]``CentOS-Base.repo`` 文件：

[source, shell]
----
rm -f /etc/yum.repos.d/CentOS-Base.repo
----

如果需要保留该文件，则可在每个 URL 部分添加 [literal]``enabled=0``。

无论选择哪种方式，之后都需重新执行引导流程。
====

ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]



ifeval::[{uyuni-content} == true]

== 管理勘误

[NOTE]
====
本节仅适用于非容器化 Uyuni，在 {centos} 7 生命周期结束后将被去除。
====

当您更新 {centos} 客户端时，软件包不包含有关更新的元数据。您可以使用第三方勘误服务来获取此信息。

[WARNING]
====

// ifeval::[{mlm-content} == true]
//
// The third-party errata service described here, CEFS, is provided and maintained by the community.
// It is not supported by {suse}.
//
// endif::[]

CEFS 的作者会按照尽力而为的原则提供补丁或勘误，希望它们有用，但无法保证其正确性或及时性。这意味着补丁日期可能不正确，且至少在一种情况下所显示的发布数据滞后一个多月。有关这些情况的详细信息，请参见 https://github.com/stevemeier/cefs/issues/28#issuecomment-656579382 和 https://github.com/stevemeier/cefs/issues/28#issuecomment-656573607[]。

任何有关补丁数据的问题或滞后都可能导致将不可靠的补丁信息导入到您的 {productname} 服务器中， 进而导致报告、审计、CVE 更新或其他与补丁相关的信息也不正确。请考虑使用其他方案来替代此服务，例如独立校验补丁数据或选择其他操作系统，具体取决于您的安全相关要求和认证准则。
====




.过程：安装勘误服务

. 在 {productname} 服务器上的命令提示符处，以 root 身份添加 ``sle-module-development-tools`` 模块：
+
----
SUSEConnect --product sle-module-development-tools/15.2/x86_64
----
. 安装勘误服务依赖项：
+
----
zypper in  perl-Text-Unidecode
----
. 在 [path]``/etc/rhn/rhn.conf`` 中添加或编辑下面一行：
+
----
java.allow_adding_patches_via_api = centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras
----
. 重启 Tomcat：
+
----
systemctl restart tomcat
----
. 为勘误脚本创建一个文件：
+
----
touch /usr/local/bin/cent-errata.sh
----
. 编辑新文件以包含此脚本，并视需要编辑储存库细节。
    此脚本会从外部勘误服务提取勘误细节，将其解压缩，然后发布这些细节：
+
----
#!/bin/bash
mkdir -p /usr/local/centos
cd /usr/local/centos
rm *.xml
wget -c http://cefs.steve-meier.de/errata.latest.xml
wget -c https://www.redhat.com/security/data/oval/v2/RHEL7/rhel-7.oval.xml.bz2
bzip2 -d rhel-7.oval.xml.bz2
wget -c http://cefs.steve-meier.de/errata-import.tar
tar xvf errata-import.tar
chmod +x /usr/local/centos/errata-import.pl
export SPACEWALK_USER='<adminname>';export SPACEWALK_PASS='<password>'
/usr/local/centos/errata-import.pl --server '<servername>' \
--errata /usr/local/centos/errata.latest.xml  \
--include-channels=centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras \
--publish --rhsa-oval /usr/local/centos/rhel-7.oval.xml
----
. 设置 cron 作业以每日运行该脚本：
+
----
ln -s /usr/local/bin/cent-errata.sh /etc/cron.daily
----

有关此工具的详细信息，请参见 https://cefs.steve-meier.de/[]。

endif::[]
