[[clients-sleses]]
= 注册 {sll} 客户端
:revdate: 2026-03-09
:page-revdate: {revdate}

本节包含有关注册运行 {sll} 操作系统的客户端的信息。{sll} 客户端基于 {rhel} 或 {centos}。


[NOTE]
====
{sll} 客户端有时也称为 {sleses} (SLESES)、Liberty、RES 或 {redhat} {es}。
====

{suse} 提供的 {sll} 软件通道只提供软件包更新，不提供软件包本身。要注册 {sll} 客户端，您需要注册（下面列出的）{sll} 产品以创建必需的基础通道，然后导入任何所需的 {redhat} 或 {centos} 软件包作为自定义子通道。您必须直接从 {redhat} 或 {centos} 获取初始软件包，然后才能应用 {sll} 软件通道提供的更新。

// FIXME!

ifeval::[{mlm-content} == true]

// Use list format: repository URLs / packages and metadata / version info
[IMPORTANT]
====
* {sll} 储存库 URL 可从 {scclongform} 获取
* 软件包和元数据由 {suse} 提供
* 有关支持的产品，请参见支持表格和版本说明
====
endif::[]


[IMPORTANT]
====
您需负责安排对 {redhat} 或 {centos} 基础媒体储存库和安装媒体的访问权限。
====


ifeval::[{mlm-content} == true]

[IMPORTANT]
====
对于您的所有 {sll} 系统，您均须从 {suse} 获取支持。
====
endif::[]


ifeval::[{uyuni-content} == true]

[IMPORTANT]
====
对于 {uyuni} 上的 {sll} 系统，{suse} 不提供支持。
====
endif::[]



== 添加软件通道


对于 {sll} 客户端，所需的一些软件包包含在 {rhel} 或 {centos} 安装媒体中。您必须安装这些软件包才能注册 {sll} 客户端。

{sll} 产品由 {scclongform} 提供，其中还包含客户端工具软件包。

将 {sll} 客户端注册到您的 {productname} 服务器之前，您需要添加所需的软件通道，并同步这些通道。

您需要选择两组不同的通道，一组通道用于提供 {sll}，另一组通道用于提供客户端工具。

您需要与适当 {sll} 通道关联的激活密钥。有关激活密钥的详细信息，请参见 xref:client-configuration:activation-keys.adoc[]。

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]

此过程所需的产品包括：

[[es-channels-wizard]]
[cols="1,1", options="header"]
.ES 产品 - WebUI
|===

| OS Version
| Product Name

| {sll} 10
| RHEL or SLES ES and Liberty 10 x86_64

| {sll} 9
| RHEL or SLES ES and Liberty 9 x86_64

| {sll} 8
| RHEL or SLES ES or CentOS 8 Base and SUSE Linux Enterprise Server with Expanded Support 8 x86_64

| {sll} 7
| SUSE Linux Enterprise Server with Expanded Support 7 x86_64

| {sll} LTSS 7
| SUSE Linux Enterprise Server with Expanded Support LTSS 7 x86_64

| {sll} LTSS for Oracle 7
| SUSE Linux Enterprise Server with Expanded Support LTSS for Oracle 7 x86_64

|===


{productname} 需要包含其他软件的工具通道。此过程将创建以下工具通道：

[[es-channels-tools]]
[cols="1,1,1", options="header"]
.ES 工具通道
|===

| OS Version | Base Channel                     | Tools Channel
| {sll} 10    | RHEL and Liberty 10 Base         | ManagerTools-EL10-Pool for x86_64 and ManagerTools-EL10-Updates for x86_64
| {sll} 9     | RHEL and Liberty 9 Base          | ManagerTools-EL9-Pool for x86_64 and ManagerTools-EL9-Updates for x86_64
| {sll} 8     | RHEL or SLES ES or CentOS 8 Base | RES8-Manager-Tools-Pool for x86_64 and RES8-Manager-Tools-Updates for x86_64
| {sll} 7     | RHEL Expanded Support 7          | RES7-SUSE-Manager-Tools x86_64
| {sll} LTSS 7 | RHEL Expanded Support LTSS 7 | RES-7-SUSE-Manager-Tools for x86_64 LBT7
| {sll} LTSS for Oracle 7 | RHEL Expanded Support LTSS for Oracle 7 | RES-7-SUSE-Manager-Tools for x86_64 LBTOL7

|===


ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]


endif::[]

此过程所需的通道包括：

ifeval::[{mlm-content} == true]

[[es-channels-cli]]
[cols="1,1,1,1", options="header"]
.ES 通道 - CLI
|===

| OS Version
| Base Channel
| Client Channel
| Tools Channel

| {sll} 10
| el10-pool-x86_64
| -
| managertools-el10-pool-x86_64

| {sll} 9
| el9-pool-x86_64
| -
| managertools-el9-pool-x86_64

| {sll} 8
| rhel8-pool-x86_64
| -
| managertools-el8-pool-x86_64

| {sll} 7
| rhel-x86_64-server-7
| -
| managertools-el7-pool-x86_64

| {sll} LTSS 7
| res-7-ltss-updates-x86_64
| -
| res-7-suse-manager-tools-x86_64-lbt7

| {sll} LTSS for Oracle 7
| res-7-ol-ltss-updates-x86_64
| -
| res-7-suse-manager-tools-x86_64-lbtol7

|===

ifeval::[{uyuni-content} == true]

[[es-channels-cli]]
[cols="1,1,1,1", options="header"]
.ES 通道 - CLI
|===

| 操作系统版本
| 基础通道
| 客户端通道
| 工具通道

| {sll} 9
| el9-pool-x86_64
| -
| sll9-uyuni-client-x86_64

| {sll} 8
| rhel8-pool-x86_64
| -
| sll8-uyuni-client-x86_64

| {sll} 7
| rhel-x86_64-server-7
| -
| sll7-uyuni-client-x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli.adoc[]
endif::[]

endif::[]



[[add.base.media]]
=== Add base media

{sll} 软件通道只提供更新，不提供软件包本身。要注册 {sll} 客户端，请先注册（下面列出的）{sll} 产品以创建基础通道，然后导入必要的 Red Hat 或 CentOS 软件包作为自定义子通道。必须直接从 {redhat} 或 {centos} 获取初始软件包，然后才能应用 {sll} 提供的更新。重要的是，您无需维持 Red Hat 订阅，但需要咨询法律部门以确定迁移期间是否存在任何需要向 Red Hat 付款的义务。为了确保您拥有所需的全部软件包，请使用完整的 DVD 映像，而非极简或 {jeos} 映像。

您可以使用 {productname} 自定义通道设置 {rhel} 或 {centos} 媒体。基础媒体上的所有软件包都必须镜像到一个子通道。

您可以自由选择通道名称。

ifndef::backend-pdf[]
include::client-configuration:partial$manual_channels.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_channels.adoc[]
endif::[]


[IMPORTANT]
====
For {redhat} 10, 9 and 8 clients, add both the Base and AppStream channels. You require packages from both channels. If you do not add both channels, you cannot create the bootstrap repository, due to missing packages.
====

如果您使用的是模块化通道，则必须在客户端上启用 Python 3.6 模块流。如果不提供 Python 3.6，[package]``spacecmd`` 软件包安装将会失败。


.Procedure: Adding base media to custom channels (RHEL 7.0 example)
[role=procedure]
____
[WARNING]
====
You must use the original installation media from {redhat}. You must use a major version release (for example `7`), not a minor release (for example `7.9`).
====
. 将基础媒体映像复制到 {productname} 服务器容器主机上的 [path]``/tmp/`` 目录中。

. 要将基础媒体映像添加到 {productname} 服务器容器，请使用：

+
----
mgradm distribution copy /tmp/rhel-server-7.0-x86_64-dvd.iso rhel-server-7.0
----

+
The destination in the container will be [path]``/srv/www/distributions/rhel-server-7.0``.

. 将软件包导入您之前创建的子通道：

+

[source, shell]
----
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-7.0/
----

____

对于版本 9 和 8 客户端，请相应调整标签和目录，此外还需同步基础通道和 AppStream 通道：

[source, shell]
----
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-9.0/BaseOS
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-9.0/AppStream
----

或：

[source, shell]
----
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-8.0/BaseOS
mgrctl exec -- spacewalk-repo-sync -c <channel-label> -u file:///srv/www/distributions/rhel-server-8.0/AppStream
----


==== OPTIONAL: Add base media from a content URL

或者，如果您可以访问 {redhat} CDN 或 {centos} 提供的内容 URL，则可以创建自定义储存库以镜像软件包。

此过程所需的细节包括：

[[es-repos-manual]]
[cols="1,1", options="header"]
.ES 自定义储存库设置
|===

| 选项                 | 参数
| 储存库 URL         | {redhat} CDN 或 {centos} 提供的内容 URL
| 包含已签名的元数据？   | 取消选中所有 {redhat} Enterprise 储存库
| SSL CA 证书     | [systemitem]``redhat-uep``（仅适用于 {redhat}）
| SSL 客户端证书 | [systemitem]``Entitlement-Cert-date``（仅适用于 {redhat}）
| SSL 客户端密钥         | ``Entitlement-Key-date``（仅适用于 {redhat}）

|===

ifndef::backend-pdf[]
include::client-configuration:partial$manual_repos.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_repos.adoc[]
endif::[]

ifndef::backend-pdf[]
include::client-configuration:partial$manual_associate.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/manual_associate.adoc[]
endif::[]


== 检查同步状态

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]

[NOTE]
====
{sll} 通道可能会非常大。有时，初始通道同步所需的时间可能会长达数小时。

初始同步完成后，建议您克隆通道后再加以使用。这样您便拥有一份原始同步数据的备份。
====



== Register {sll} clients

ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]



[[clients-sleses-el-migration]]
== 将 Enterprise Linux (EL) 客户端迁移到 {sll}

如果某个 Enterprise Linux (EL) 客户端（例如 {rhel} 和 {centos}）已在 {productname} 上注册为受控端，而用户想要将其迁移到 {sll}，则可以使用重新激活密钥来应用用于驱动迁移的激活密钥。

有关重新激活密钥的详细信息，请参见 xref:client-configuration:activation-keys.adoc#activation-keys-reactivation[]。

重新激活密钥按受控端分配，可以通过 {webui} 或使用 API 来生成。有关详细信息，请参见 link:https://documentation.suse.com/multi-linux-manager/5.1/api/suse-manager/api/system.html#apidoc-system-obtainReactivationKey-loggedInUser-sid[]。

要重新激活客户端，用户可以在客户端上运行引导脚本，并以环境变量的形式传递重新激活密钥。例如：

----
REACTIVATION_KEY=<KEY> ./bootstrap_liberate9.sh
----

另一种方法是向位于 [path]``/etc/venv-salt-minon/minion.d/susemanager.conf``（或 [path]``/etc/salt-minon/minion.d/susemanager.conf``） 的 {salt} 客户端配置文件添加一些特殊标志，即以下内容（将此内容与现有的内容合并）：

----
grains:
    susemanager:
        activation_key: "<KEY_ID>"
        management_key: "MINION_REACTIVATION_KEY"
----

更改 [path]``susemanager.conf`` 文件后，需要在 {salt} 服务器上重启 [systemitem]``salt-minion`` 服务。默认可运行以下命令来执行该操作：

----
systemctl restart venv-salt-minon
----

对于旧版 {salt}，请运行以下命令：

----
systemctl restart salt-minon
----




=== [systemitem]``liberate`` 公式

您可以使用 [systemitem]``liberate`` 公式将 Enterprise Linux (EL) 客户端迁移到 {sll}。有关详细信息，请参见 xref:specialized-guides:salt/salt-formula-liberate.adoc[]。
