[[contact-methods-intro]]
= 客户端联系方法
:revdate: 2024-09-27
:page-revdate: {revdate}

{productname} 服务器可以使用三种联系方法来与客户端通信。这些方法基于 {salt} 协议。

使用哪种 {salt} 联系方法取决于客户端类型以及网络体系结构：

默认::
除非用户有特殊需求，否则建议使用此方法。默认会部署 {salt} 捆绑包实现。有关详细信息，请参见 xref:client-configuration:contact-methods-default.adoc[]。

SSH 推送::
仅当由于网络限制而导致客户端无法与服务器建立联系时才有用。只能通过 {salt} 捆绑包支持此方法。此联系方法有严重的限制。有关详细信息，请参见 xref:client-configuration:contact-methods-saltssh.adoc[]。

SSH 推送（使用隧道）::
与 SSH 推送相同，但使用安全通信隧道。有关详细信息，请参见 xref:client-configuration:contact-methods-saltssh-tunnel.adoc[]。


{salt} 通信软件实现选项：

Salt 捆绑包 ([package]``venv-salt-minion``)::
是单个二进制软件包，包含 {salt} 受控端、Python 3、所需的 Python 模块和库。因此，{salt} 联系方法独立于客户端上安装的软件。

+

////
Using the {salt} Bundle is the default.
It is the only supported implementation for the SSH Push or SSH Push (with tunnel) contact method.
////

+

有关详细信息，请参见 xref:client-configuration:contact-methods-saltbundle.adoc[]。

Salt 受控端 ([package]``salt-minion``)::
是客户端系统上安装的 {salt} 软件，通常已不再受 {productname} 支持。如果有需要，您可仅在 {sle} 15 客户端及其衍生系统（如 {sle-micro}）上安装该软件以完成引导。引导过程中它会被替换为 [package]``venv-salt-minion``。



[IMPORTANT]
====
{productname} 5.0 及更高版本不再支持所谓的传统联系协议。在从 {productname} 4 升级到 5 之前，必须将所有现有的传统客户端（包括传统代理）迁移到 {salt}，或将其替换为 {salt} 代理。

有关将传统 {productname} 4 客户端迁移到 {salt} 客户端的详细信息，请参见 https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.html
====
