[[package-management]]
= 软件包管理

客户端使用软件包来安装、卸装和升级软件。

要管理客户端上的软件包，请导航到[guimenu]``系统``，单击要管理的客户端，然后导航到menu:系统[软件 > 软件包]子选项卡。 此部分提供的选项取决于您选择的客户端类型及其当前的频道订阅。


[IMPORTANT]
====
安装或升级软件包时，将自动接受许可证或 EULA。
====

大多数软件包管理操作都可以添加到操作链中。 有关操作链的详细信息，请参见 xref:reference:schedule/action-chains.adoc[]。



== 校验软件包

您可以检查客户端上安装的软件包是否与作为其安装源的数据库的当前状态匹配。 系统会对安装的软件包的元数据与数据库中的信息（包括文件校验和、文件大小、权限、拥有者、组和类型）进行比较。

.过程：校验安装的软件包
. 在 {productname} {webui} 中，导航到[guimenu]``系统``，单击安装了软件包的客户端，然后导航到menu:系统[软件 > 软件包 > 校验]子选项卡。
. 选择要校验的软件包，然后单击 btn:[校验所选软件包]。
. 校验完成后，导航到menu:系统[事件 > 历史记录]查看结果。



== 比较软件包

您可以将某个客户端上安装的软件包与储存的配置文件进行比较，或者与其他客户端上安装的软件包进行比较。 比较时，您可以选择修改选定要匹配的客户端。

将软件包与某个配置文件进行比较之前，您需要先储存一个配置文件。 配置文件基于当前安装的客户端上的软件包创建。 如果已创建配置文件，您可以使用它安装更多客户端，这些客户端中均会安装相同的软件包。



.过程：创建储存的配置文件
. 在 {productname} {webui} 中，导航到[guimenu]``系统``，单击配置文件要基于的客户端，然后导航到menu:系统[软件 > 软件包 > 配置文件]子选项卡。
. 单击 btn:[创建系统配置文件]。
. 键入您的配置文件的名称和说明，然后单击 btn:[创建配置文件]。



.过程：比较客户端软件包
. 在 {productname} {webui} 中，导航到[guimenu]``系统``，单击要比较的客户端，然后导航到menu:系统[软件 > 安装包 > 配置文件]子选项卡。
    要与储存的配置文件进行比较，请选择该配置文件，然后单击 btn:[比较]。
. 要与其他客户端进行比较，请选择客户端名称，然后单击 btn:[比较] 查看两个客户端之间的差别的列表。
. 选中要在所选客户端上安装的软件包，取消选中要去除的软件包，然后单击 btn:[将软件包同步到]。
