[[package-management]]
= 软件包管理
:revdate: 2024-11-21
:page-revdate: {revdate}

客户端使用软件包来安装、卸装和升级软件。

// available subtabs:
//     List / Remove
//     Upgrade
//     Install
//     Lock / Unlock
//     Profiles
//     Non Compliant


要管理客户端上的软件包，请导航到[guimenu]``系统``，单击要管理的客户端，然后导航到menu:系统[软件 > 软件包]子选项卡。此部分提供的选项取决于您选择的客户端类型及其当前的通道订阅。

大多数软件包管理操作都可以添加到操作链中。有关操作链的详细信息，请参见 xref:reference:schedule/action-chains.adoc[]。


[IMPORTANT]
==== 

安装或升级软件包时，将自动接受许可证或 EULA。
====


== 使用配置文件比较软件包


您可以将某个客户端上安装的软件包与存储的配置文件进行比较，或者与其他客户端上安装的软件包进行比较。比较时，您可以选择修改选定要匹配的客户端。

将软件包与某个配置文件进行比较之前，您需要先存储一个配置文件。配置文件基于当前安装的客户端上的软件包创建。如果已创建配置文件，您可以使用它安装更多客户端，这些客户端中均会安装相同的软件包。


.过程：创建存储的配置文件
. 在 {productname} {webui} 中，导航到[guimenu]``系统``，单击配置文件要基于的客户端，然后导航到menu:系统[软件 > 软件包 > 配置文件]子选项卡。
. 单击 btn:[创建系统配置文件]。
. 键入您的配置文件的名称和说明，然后单击 btn:[创建配置文件]。


.过程：比较客户端软件包
. 在 {productname} {webui} 中，导航到[guimenu]``系统``，单击要比较的客户端，然后导航到menu:系统[软件 > 安装包 > 配置文件]子选项卡。
    要与存储的配置文件进行比较，请选择该配置文件，然后单击 btn:[比较]。
. 要与其他客户端进行比较，请选择客户端名称，然后单击 btn:[比较] 查看两个客户端之间的差别的列表。



[[package-management-orphaned-packages]]
== 孤立的软件包

孤立的软件包是指 {productname} 已同步但与任何软件通道均不关联的软件包。因此，孤立的软件包通常无法用于 {productname} 客户端，如果不采取额外的措施，用户将无法安装此类软件包。

软件包可能会由于以下事件而变为孤立状态：

* 已同步的储存库去除了某个软件包。默认情况下，{productname} 会将该软件包与相应通道解除关联，但不会去除该软件包。
* 储存库使用新版本取代了某个软件包，因而去除了之前的版本。
* 储存库同步流程被中断（例如，由于发生空间用尽异常），因此下载的软件包与任何通道都不关联。
* 用户手动上载了软件包，但未将其与任何通道关联。

孤立的软件包会消耗用户环境中的空间，并且无法轻松分发给客户端，因为它们与任何通道均不关联。孤立的软件包可能对特定的工作负载（例如引导或特定于客户的过程）有用。

您可以在 {webui} 中单击menu:软件[管理 > 软件包 > 查看不属于任何通道的软件包]，来查看孤立的软件包。

{productname} 会定期运行 taskomatic 作业，以搜索孤立的软件包并将此类软件包的组织 ID 修改为 1。这意味着只有在 taskomatic 作业执行后，您才能删除孤立的软件包。如果您遇到无法删除的孤立软件包，请等待 24 个小时，然后再次尝试删除。

// .Procedure: Deleting orphaned packages

删除孤立的软件包：

// * With the UI (FIXME is this possible?  How?

* 使用针对单个软件包的命令行工具。例如：
+
----
spacecmd package_remove zypper-1.14.52-150400.1.9.x86_64
----

* 使用同时针对所有孤立软件包的命令行工具：
+
----
spacecmd package_removeorphans
----
