[[registering.clients.webui]]
= 使用 {webui} 注册客户端

使用 {productname} {webui} 注册客户端仅适用于 Salt 客户端。


[IMPORTANT]
====
请不要将 {productname} 服务器注册到其自身。必须单独管理 {productname} 服务器，或者使用另一个独立的 {productname} 服务器来管理它。有关使用多个服务器的详细信息，请参见 xref:large-deployments:multi-server.adoc[]。
====



.过程：使用 {webui} 注册客户端

. 在 {productname} {webui} 中，导航到menu:系统[引导]。
. 在[guimenu]``主机``字段中，键入要引导的客户端的完全限定域名 (FQDN)。
. 在 [guimenu]``SSH 端口``字段中，键入用于连接和引导客户端的 SSH 端口号。
    SSH 端口默认为 [systemitem]``22``。
. 在[guimenu]``用户``字段中，键入用于登录客户端的用户名。
    用户名默认为 [systemitem]``root``。
. 要使用 SSH 引导客户端，请在[guimenu]``身份验证``字段中选中 [guimenu]``SSH 私用密钥``，并上载用于登录客户端的 SSH 私用密钥。
    如果您的 SSH 私用密钥需要通行口令，请在 [guimenu]``SSH 私用密钥通行口令``字段中键入通行口令。如果不需要，则将该字段留空。
. 要使用口令引导客户端，请在[guimenu]``身份验证``字段中选中[guimenu]``口令``，并键入用于登录客户端的口令。
. 在[guimenu]``激活密钥``字段中，选择与您要用于引导客户端的软件频道关联的激活密钥。
    有关详细信息，请参见 xref:client-configuration:activation-keys.adoc[]。
. 可选：在[guimenu]``代理``字段中，选择要将客户端注册到的代理。
. 默认会选中[guimenu]``禁用 SSH 严格密钥主机检查`` 复选框。
    如此可让引导过程自动接受 SSH 主机密钥，而无需您手动进行身份验证。
. 可选：选中[guimenu]``完全通过 SSH 管理系统`` 复选框。
    如果您选中此选项，客户端将会配置为使用 SSH 来连接服务器，且不再配置其他连接方法。
. 单击 btn:[Bootstrap] 开始注册。

引导过程完成时,您的客户端即会列在menu:系统[系统列表]中。


[IMPORTANT]
====
SSH 私用密钥仅在引导过程期间储存， 引导完成后，将会立即从 {productname} 服务器删除。
====


[WARNING]
====
使用 {productname} 在客户端上安装新的软件包或更新时，会自动接受所有最终用户许可协议 (EULA)。 要查看软件包 EULA，请打开 {webui} 中的软件包细节页面。
====


[WARNING]
====
To register and use {centos}{nbsp}6, {oracle}{nbsp}6, {rhel}{nbsp}6, or {sleses}{nbsp}6 clients, you need to configure the {productname} Server to support older types of SSL encryption. For more information, see ``Registering Older Clients`` at xref:client-configuration:tshoot-clients.adoc[].
====
