[[snapshots]]
= 配置快照

快照用于记录客户端在指定时间点的软件包配置文件、配置文件和 {productname} 设置。 您可以通过回滚到较旧的快照来恢复之前的配置设置。

[NOTE]
====
快照仅在传统客户端上受支持。 Salt 客户端不支持此功能。
====

当某些操作发生后，系统会自动捕获快照。 您也可以随时手动截取快照。 建议您在对客户端执行任何可能造成破坏的操作之前，确保您拥有当前快照。

快照默认处于启用状态。 您可以通过在 [path]``rhn.conf`` 配置文件中设置 [parameter]``enable_snapshots=0`` 来禁用自动快照功能。

要管理您的快照，请导航到menu:系统[系统列表]，然后选择要管理的客户端。 导航到menu:置备[快照]选项卡，以查看所选客户端的所有当前快照的列表。 单击快照的名称可查看有关该快照中所记录的更改的详细信息。 您可以使用menu:置备[快照]选项卡中的子选项卡查看回滚到所选快照的以下相关更改：

* 组成员资格
* 频道订阅
* 安装的软件包
* 配置频道订阅
* 配置文件
* 快照标记


[IMPORTANT]
====
您可以使用快照回滚对客户端所做的大多数更改，但无法回滚所有更改。 例如，您无法回滚多个更新，也无法回滚服务包迁移。 在客户端上执行升级之前，请始终确保您已进行备份。
====



== 快照标记

快照标记可用来为快照添加有意义的说明。 您可以使用快照标记记录有关快照的额外信息，例如已知的最近一次可正常工作的配置或成功的升级。

要管理您的快照标记，请导航到menu:系统[系统列表]，然后选择要管理的客户端。 导航到menu:置备[快照标记]选项卡，以查看所选客户端的所有当前快照标记的列表。 单击[guimenu]``创建系统标记``，输入说明，然后单击 btn:[标记当前快照] 按钮。



== 大型安装上的快照

{productname} 可保留的快照没有数量上限。 这意味着随着您不断添加更多的客户端、软件包、频道和配置更改，储存快照的数据库会逐渐增大。

对于具有数千个客户端的大型安装，您可以使用 {productname} API 定期创建定期清理脚本，以确保定期删除旧快照。 或者，您可以通过在 [path]``rhn.conf`` 配置文件中设置 [parameter]``enable_snapshots=0`` 来禁用该功能。
