[[system-groups]]
= 系统组

通过系统组，您可以更轻松地管理大量客户端。 组可用于对客户端执行批量操作，例如应用更新、配置频道、Salt 状态或公式。

您可以采用任何适合环境的方式来对客户端分组。 例如，可以按客户端上安装的操作系统、所在的实际位置或所处理的工作负载类型来组织客户端。 客户端可以划分到任意数量的组中，因此您可以采用不同的方式来定义组。

对客户端分组后，您可以在一个或多个组中的所有客户端上或不同组之间的交集客户端上执行更新。 例如，您可以为所有 Salt 客户端定义一个组，为所有 SLES 客户端定义另一个组。 然后，您可以在所有 Salt 客户端上执行更新，或使用两个组的交集来更新所有 Salt SLES 客户端。



== 创建组

在使用组对客户端分组之前，需要先创建一些组。



.过程：创建新系统组
. 在 {productname} {webui} 中，导航到menu:系统[系统组]。
. 单击 btn:[创建组]。
. 指定新组的名称和说明。
. 单击 btn:[创建组] 以保存组。
. 对需要创建的每个组重复以上步骤。



== 将客户端添加到组

您可以向组中添加单个客户端，也可以同时添加多个客户端。



.过程：将单个客户端添加到组
. 在 {productname} {webui} 中，导航到menu:系统[系统列表]，然后单击要添加的客户端的名称。
. 导航到menu:组[加入]选项卡。
. 选中要加入的组，然后单击 btn:[加入所选的组]。



.过程：将多个客户端添加到组
. 在 {productname} {webui} 中，导航到menu:系统[系统列表]，然后单击要向其添加客户端的组的名称。
. 导航到[guimenu]``目标系统``选项卡。
. 选中要添加的客户端，然后单击 btn:[添加系统]。



.过程：使用 SSM 将多个客户端添加到组
. 在 {productname} {webui} 中，导航到menu:系统[系统列表]，然后选中要添加的每个客户端，这会将这些客户端添加到系统集管理器中。
. 导航到menu:系统[系统集管理器]，然后转到[guimenu]``组``选项卡。
. 找到要加入的组并选中[guimenu]``添加``。
. 单击 btn:[更改成员资格]。
. 单击 btn:[确认] 将客户端加入所选的组。

有关系统集管理器的详细信息，请参见 xref:client- configuration:system-set-manager.adoc[]。



您可以导航到menu:系统[系统组]并单击某个组的名称，然后导航到[guimenu]``系统``选项卡，以查看该组中有哪些客户端。 或者，您可以导航到menu:系统[虚拟化 > 系统分组]查看系统组的图形表示。



== 使用组

将客户端分组后，您便可以使用组来管理更新。 对于 Salt 客户端，您还可以向组中的所有客户端应用状态和公式。

在 {productname} {webui} 中，导航到menu:系统[系统组]。 如果组中的任何客户端有可用更新，列表会显示相应图标。 单击图标可查看有关可用更新的详细信息，并向客户端应用更新。

您也可以同时使用多个组。 选择要使用的多个组，然后单击 btn:[使用并集] 以选择每个选定组中的每个客户端。

或者，您也可以使用多个组的交集。 选择两个或更多组，然后单击 btn:[使用交集] 以仅选择所有选定组中都存在的那些客户端。 例如，您可以将所有 Salt 客户端分为一组，将所有 SLES 客户端分为另一组。 这两个组的交集就是所有 Salt SLES 客户端。
