[[ref-systems-sd-channels]]
= 소프트웨어 채널
:revdate: 2023-09-18
:page-revdate: {revdate}

The menu:Systems[Software > Software Channels] section allows you to manage the software channels on the current client. For more information about software channels, see xref:client-configuration:channels.adoc[].

The menu:Systems[Software > Software Channels] subtab is split into sections:



== 기본 채널


This section shows the base channel the current client is subscribed to, as well as any other available base channels.

Click the chain icon next to a base channel to see more information about the channel. Change the base channel subscription by selecting the new base channel, and click btn:[Next] to schedule the change.

The child channels associated with the base channel are populated in the [guimenu]``Child Channels`` section. Mandatory child channels are pre-selected. Toggle the [guimienu]``include recommended`` switch to also select recommended child channels.



[NOTE]
====
기본적으로 복제된 제조업체 채널은 원래 제조업체 채널과 일치하며 종속성을 자동으로 선택합니다. [path]``/etc/rhn/rhn.conf``에 다음 옵션을 추가하여 복제된 채널에 대한 자동 선택을 비활성화할 수 있습니다.
----
java.cloned_channel_auto_selection = false
----
====

In general, channel pre-selection is necessary to avoid problems with missing dependencies for a given channel but it only works flawlessly for vendor channels. For cloned channels, {productname} relies on the channel label to define dependencies and use it in auto selection. This heuristic sometimes lead to either selecting unnecessary child channels or overlooking some essential ones. Users should exercise caution and pay attention in such case that correct channels are selected.

For Salt clients, apply the highstate after changing software channels.



== 하위 채널

This section shows the software product and child channels associated with the currently selected base channel.

Hover over the information icon next to the channel name to see channel requirements. Click the chain icon next to a base channel to see more information about the channel.

Child channels are can be either recommended or mandatory. Mandatory child channels must be installed for the selected client to use the associated base channel. Recommended child channels should be installed to provide additional packages. All other child channels are optional.

Check the child channels you want to install, and click btn:[Next] to schedule the change.
