[[retail-migration-from-43]]
= Migrating from {productbranch} 4.3
:revdate: 2025-11-12
:page-revdate: {revdate}

This guide describes a procedure how to migrate one or more {productbranch} Servers from {susemgr} Branch Server 4.3 to the {productbranch} 5.1

== Overview

* Synchronize {productbranch} channels
* Backup existing {productname} {smr} 4.3 Branch Server Proxy
* Validate branch objects were created
* Migrate Branch Server Proxy host
* Validate proxy functionality

== Backup existing {productbranch} 4.3

{productname} {smr} 5.1.2 includes automated backup-migration procedure for both kinds of {productproxy} variants. This procedure collects all required data and uploads them to the {productname} Server. For {productbranch} this tool also creates and migrates {saltboot} related entities.

There are multiple ways how to initiate {productbranch} 4.3 migration:

* API call [literal]``mgrctl api post proxy.backup id=$proxyid``
* {salt} call [literal]``salt $proxy proxy.backup``

[IMPORTANT]
====
{productbranch} can still be used after backup step as before, however because some formulas were disabled by the backup/migration step, next highstate or image-sync state application will not work properly.

Migrate the server host as soon as possible after backup step is performed.
====

== Validate branch objects were created for migrated branches

Backup/migration step will create new Saltboot objects:

- [literal]``Saltboot Group`` formula with settings from the original formulas is assigned to the branch group.
- New cobbler profile is created for the branch group:
+
[code]
====
# mgrctl exec -- cobbler profile report --name $branchid:S:$orgid:$orgname
====
- New cobbler systems are created for all assigned terminals:
+
[code]
====
# mgrctl exec -- cobbler system find --kernel-options "MINION_ID_PREFIX=$branchid"
====

== Migrate {productbranch} host

Create and use AutoYAST profiles to migrate or reinstall proxy host.

=== Prepare autoinstallation distribution based on {sles} 15 SP7

- Download or obtain {sles} 15 SP7 installation ISO to the server host
- Use [literal]``mgradm distribution copy $path_to_the_iso`` to copy installation files to the container
- Register the autoinstallation distribution, see see xref:client-configuration:autoinst-distributions.adoc[].

=== Prepare autoinstallation profile

For more information, see xref:client-configuration:autoinst-profiles.adoc[].

- Create an autoinstallation profile based previously created distribution.
As a profile use profile provided at https://github.com/SUSE/manager-build-profiles/blob/master/AutoYaST/SUSE%20Multi-Linux%20Manager%20Proxy/MLM_RBS-51-SLES-Upgrade.xml
- Once profile is created, switch to [menuitem]``Variables`` tab and fill in required variables:
+
[code]
====
org='organization_id'
distrotree='autoinstallation_distribution_label_from_previous_step'
channel_prefix='clm_channel_prefix' or blank for SCC channels
registration_key='activation_key_for_post_upgrade'
====
- In tab [menuitem]``Autoinstallation File`` you can see complete rendered profile for additional inspection

=== Provision autoinstallation of the proxy

Schedule an autoinstallation on the old {susemgr} Branch Server 4.3 using the profile created in previous step.

- Use Web UI interface [menuitem]``Provisioning`` tab at the [menuitem]``System`` view of migrating branch server
// TODO add API call option

== Validate proxy functionality

After migration is finished and salt is started first time, backed up proxy configuration is automatically deployed during [literal]``Hardware refresh`` step.

After finishing all onboarding steps, validate required proxy functionality