[[retail-install-setup]]
= Setting up

When you have installed the [guimenu]``SUSE Manager for Retail Server`` and the [guimenu]``SUSE Manager Retail Branch Server``, you need to set up your environment by following these steps:

. Install the build host and register it to {susemgr}
. Configure the build host
. Create the required system group

These are the branch server setup steps:

// already done:
// . Install the branch server and register it to {susemgr}
. Assign and configure branch server formulas
. Synchronize images to the branch servers

Each procedure is detailed in this section.



== Create Required System Groups

{smr} requires system groups for terminals and servers.
Manually create these system groups during installation:

* [systemitem]``TERMINALS``
* [systemitem]``SERVERS``

Additionally, you will need to create a system group for each branch server, and each terminal hardware type in your environment.

You can create system groups using the {susemgr} {webui}.
Navigate to menu:Systems[System Groups] and click btn:[Create System Group].

For more information about system groups, see xref:reference:systems/system-groups.adoc[].


== Assign and Configure Branch Server Formulas

Before you configure the branch server, ensure you have decided on networking topology, and know the Salt ID of the branch server.

The branch server can be configured automatically using the [command]``retail_branch_init`` command, as shown in this section.
If you prefer to manually configure the branch server, you can do so using formulas.
For more information about formulas, see xref:retail:retail-formulas-intro.adoc[].

.Procedure: Configuring Branch Server Formulas With a Helper Script

. Branch server configuration is performed using the [command]``retail_branch_init`` command:
+
----
retail_branch_init <branch_server_salt_id>
----
+
This command will configure branch server formulas with recommended values.
You can use the [command]``retail_branch_init --help`` command for additional options.
. Verify that your changes have been configured correctly by checking the {susemgr} {webui} branch server system formulas.
. Apply highstate on the branch server.
You can do this through the {webui}, or by running this command:
+
----
salt <branch_server_salt_id> state.apply
----


== Synchronize Images to the Branch Server

The OS image you use on the {susemgr} server must be synchronized for use on the branch server.
You can do this with the Salt [command]``image-sync`` tool.

.Procedure: Synchronizing Images to the Branch Server

. On the {susemgr} server, run this command:
+
----
salt <branch_server_salt_id> state.apply image-sync
----
. The image details will be transferred to [path]``/srv/saltboot`` on the branch server.



== Terminals Based on SLES{nbsp}11 SP{nbsp}3

POS Terminals based on {sles}{nbsp}11 SP{nbsp}3 can be deployed in much the same way as other terminals, with a few differences.

* You must use the SLES{nbsp}11 template
* SLES{nbsp}11 images need to be activated with the [systemitem]``SLES11 SP3 i586`` and [systemitem]``SLEPOS 11 SP3 i586`` channels

[IMPORTANT]
====
Ensure that SLES{nbsp}11 images are built on the SLES{nbsp}11 build host, and SLES{nbsp}12 images are built on the SLES{nbsp}12 build host.
Building on the incorrect build host will cause your build to fail.
====

[WARNING]
====
If you are building images for SLES{nbsp}11 using profiles from an HTTPS git repository that uses TLS 1.0 or greater, it will fail.
SLES{nbsp}11 does not support later versions of TLS.
You will need to clone the repository locally in order to use it for building.
====
