ifndef::backend-pdf[]
[[retail-overview]]
= Retail Guide

// HTML Publication date 
**Publication Date:** {docdate}

== Preface

{productname} {smr} {productnumber} is an **open-source infrastructure management solution**, specifically **optimized for the retail industry**. 
Built on the same technology as {productname}, it has been tailored to meet the unique operational needs of retail organizations.  

Designed for **retail environments**, {productname} {smr} supports **point-of-service (POS) terminals**, allowing businesses to manage transactions, promotions, and customer loyalty programs. 
Beyond retail, it can also be used in **educational institutions** to maintain student computers, as well as in **banks and hospitals** for self-service kiosks.  

{productname} {smr} is suited for deployments that include **servers, workstations, point-of-service terminals, and other connected devices**. 
It enables administrators to **install, configure, and update software across their infrastructure**, while streamlining **deployment and provisioning** of POS machines.  

This guide provides a **comprehensive overview** of {productname} {smr}, covering its **initial installation and setup**.  

ifeval::[{suma-content} == true]  
For complete documentation, refer to the **{productname} documentation suite** at https://documentation.suse.com/.  
endif::[]  

ifeval::[{uyuni-content} == true]  
For additional guidance, refer to the **{productname} documentation suite** at https://www.uyuni-project.org/uyuni-docs.  
endif::[]  

For more details on managing your {productname} {smr} environment or seeking assistance, see xref:retail:retail-next.adoc[]  


== Copyright Notice

// HTML Copyright
Copyright © {copyrightdate} SUSE LLC and contributors. All rights reserved.
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright
notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].

== Trademarks
// HTML Trademarks
For SUSE trademarks, see https://www.suse.com/company/legal/ . All third-party trademarks are the property
of their respective owners. Trademark symbols (®, ™ etc.) denote trademarks of SUSE and its affiliates. Asterisks
(*) denote third-party trademarks.
All information found in this book has been compiled with utmost attention to detail. However, this does not
guarantee complete accuracy. Neither SUSE LLC, its affiliates, the authors nor the translators shall be held liable
for possible errors or the consequences thereof.
endif::[]

// PDF PREFACE PAGE
ifdef::backend-pdf[]

<<<
// Required for preface section of pdf
[preface]
== Preface

Retail +
{productname} {productnumber}

{productname} {smr} {productnumber} is an **open-source infrastructure management solution**, specifically **optimized for the retail industry**. 
Built on the same technology as {productname}, it has been tailored to meet the unique operational needs of retail organizations.  

Designed for **retail environments**, {productname} {smr} supports **point-of-service (POS) terminals**, allowing businesses to manage transactions, promotions, and customer loyalty programs. 
Beyond retail, it can also be used in **educational institutions** to maintain student computers, as well as in **banks and hospitals** for self-service kiosks.  

{productname} {smr} is suited for deployments that include **servers, workstations, point-of-service terminals, and other connected devices**. 
It enables administrators to **install, configure, and update software across their infrastructure**, while streamlining **deployment and provisioning** of POS machines.  

This guide provides a **comprehensive overview** of {productname} {smr}, covering its **initial installation and setup**.  

ifeval::[{suma-content} == true]  
For complete documentation, refer to the **{productname} documentation suite** at https://documentation.suse.com/.  
endif::[]  

ifeval::[{uyuni-content} == true]  
For additional guidance, refer to the **{productname} documentation suite** at https://www.uyuni-project.org/uyuni-docs.  
endif::[]  

For more details on managing your {productname} {smr} environment or seeking assistance, see xref:retail:retail-next.adoc[]. 

// PDF Publication

**Publication Date:** {docdate}

// PDF Copyright Space

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

// PDF Copyright
Copyright © 2006–2025 SUSE LLC and contributors. All rights reserved.
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright
notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].

// PDF Trademarks
For SUSE trademarks, see https://www.suse.com/company/legal/ . All third-party trademarks are the property
of their respective owners. Trademark symbols (®, ™ etc.) denote trademarks of SUSE and its affiliates. Asterisks
(*) denote third-party trademarks.
All information found in this book has been compiled with utmost attention to detail. However, this does not
guarantee complete accuracy. Neither SUSE LLC, its affiliates, the authors nor the translators shall be held liable
for possible errors or the consequences thereof.

<<<

toc::[]

endif::[]