[[retail-server-setup]]
= Retail Uyuni Server Setup

This section covers {productname} {smr} Server setup, using these procedures:

* Set up {productname} with {yast}
* Create the main administration account
* Add Software Channels
* Check Synchronization Status
* Trust GPG Keys on Clients
* Register the Branch Server and Terminals as Clients



[[retail-server-setup-yast]]
== Set up {productname} with {yast}

This section guides you through {productname} setup procedures.

.Procedure: {productname} Setup
. On the {productname} Server, at the command prompt, as root, start {yast}:
+
----
yast2
----

. Navigate to menu:Network Services[Uyuni Setup] to begin set up.

. From the introduction screen, select menu:Uyuni Setup[Set up Uyuni from scratch] and click btn:[Next] to continue.

. Type an email address to receive status notifications and click btn:[Next] to continue.
  {productname} can sometimes send a large volume of notification emails.
  You can disable email notifications in the {webui} after setup, if you need to.

. Type your certificate information and provide a password.
  Passwords must be at at least seven characters in length, and must not contain spaces, single or double quotation marks (``'`` or ``"``), exclamation marks (``!``), or dollar signs (``$``).
  Always store your passwords in a secure location.
  You must have the certificate password to set up the {productname} Proxy.
+
  Click btn:[Next] to continue.

. Navigate to menu:Uyuni Setup[Database Settings] screen, type a database username and password, and click btn:[Next] to continue.
  Passwords must be at at least seven characters in length, and must not contain spaces, single or double quotation marks (``'`` or ``"``), exclamation marks (``!``), or dollar signs (``$``).
  Always store your passwords in a secure location.
+
  Click btn:[Next] to continue.

. Click btn:[Yes] to begin the setup process.

. When setup is complete, click btn:[Next] to continue.
  Take note of the address to access the {productname} {webui}.

. Click btn:[Finish] to complete {productname} setup.



== Create the Main Administration Account

This section covers how to create your organization's main administration account for {productname}.

[WARNING]
====
The main administration account has the highest authority within {productname}.
Ensure you keep access information for this account secure.
We recommend that you create lower level administration accounts for organizations and groups.
Do not share the main administration access details.
====


.Procedure: Setting Up the Main Administration Account

. In your web browser, enter the address for the {productname} {webui}.
  This address was provided after you completed setup.
  For more information, see xref:retail:retail-uyuni-server-setup.adoc#retail-server-setup-yast[].

. Sign in to the {webui}, navigate to the menu:Create Organization[Organization Name] field, and enter your organization name.

. In the menu:Create Organization[Desired Login] and menu:Create Organization[Desired Password] fields, enter your username and password.

. Complete the ``Account Information`` fields, including an email for system notifications.

. Click btn:[Create Organization] to finish creating your administration account.

When you have completed the {productname} {webui} setup, you are taken to the menu:Home[Overview] page.



////
// Old text, to be superseded by the standard phrases above.
Before you begin, ensure you have access to the ``opensuse_leap15_2`` parent channel.

// Use [command]``spacewalk-common-channels`` to obtain all needed channels:

.Procedure: Synchronizing Software Channels

. On the {productname} Server, at the command prompt, as root, register the parent channel:
+
----
spacewalk-common-channels opensuse_leap15_2
----

. Enable the child channels:
+
----
spacewalk-common-channels opensuse_leap15_2-updates
spacewalk-common-channels uyuni-proxy-stable-leap-152
spacewalk-common-channels opensuse_leap15_2-uyuni-client
----
+
  If registration is successful, this message is shown:
+
----
# Base channel 'openSUSE Leap {opensuse-version} (x86_64)' - exists
----

. Synchronize all repositories, which will take a lot of time to finish:
+
----
spacewalk-repo-sync -c opensuse_leap15_2-x86_64
spacewalk-repo-sync -c opensuse_leap15_2-x86_64-updates
spacewalk-repo-sync -c opensuse_leap15_2-uyuni-client-x86_64
spacewalk-repo-sync -c uyuni-proxy-stable-leap-152-x86_64
----

// Trouble shooting:
If you do not enable the ``opensuse_leap15_2`` parent channel first, you will see the following error:

----
# ERROR: opensuse_leap15_2-x86_64 could not be found at the server
# ERROR: opensuse_leap15_2-uyuni-client-x86_64: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: User 1 does not have access to channel opensuse_leap15_2-x86_64 or the channel does not exist
----
////

////
FIXME, ke: we should think about this later:

Next we need to adapt kiwi profile for Leap {opensuse-version}, it is possible to simply modify JeOS7 for SLE15SP2 by
dropping few SLE specific packages and directives:

         <bootsplash-theme>SLE</bootsplash-theme>
         <bootloader-theme>SLE</bootloader-theme>
         <package name="grub2-branding-SLE" bootinclude="true"/>
         <package name="SUSEConnect"/>
         <package name="suse-build-key"/>
         <package name="plymouth-branding-SLE"/>
         <package name="sles-release"/>
         <package name="rhn-org-trusted-ssl-cert-osimage"/>

Side note: I plan to publish modified profile somewhere, but I haven't decided where yet as it is uyuni and
feature without support.

Then it is possible to build the image using modified kiwi profile and deploy it to terminal as usual (there is
nothing specific for Uuyni).

The rest of things ({saltboot} formula and formula for image syncing works just the same way as MLM.)

Only thing that behaves differently is naming of terminals, for some reason dashes are used instead of
HWTYPE (for example). But fortunately it has no impact on (at least basic) functionality of terminal.
////
