[[retail-install-uyuni]]
= Install Uyuni Retail Server with openSUSE

{productname} {smr} Server can be installed on openSUSE.

For general requirements, see xref:installation:uyuni-install-requirements.adoc[].

[NOTE]
====
For more information about the latest version and updates of openSUSE Leap, see https://doc.opensuse.org/release-notes/.
====



== Install Uyuni on openSUSE Leap

You install Uyuni as an add-on to openSUSE Leap.



.Procedure: Installing Uyuni on openSUSE Leap

. As the base system, install openSUSE Leap with all available service packs and package updates applied.
. Configure a resolvable fully qualified domain name (FQDN) with menu:yast[System > Network Settings > Hostname/DNS].
. Set variables to use to create repository:
+
----
repo=repositories/systemsmanagement:/
repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
----
. Add the repository for installing the {productname} Server software as [systemitem]``root``:
+
----
zypper ar https://download.opensuse.org/$repo uyuni-server-stable
----
. Refresh metadata from the repositories as [systemitem]``root``, and confirm the import of new GPG key into the keyring:
+
----
zypper ref
----
. Install the pattern for the {productname} Server as [systemitem]``root``:
+
----
zypper in patterns-uyuni_server
----
. Install the {productname} related packages:
+
----
zypper in bind-formula \
	  branch-network-formula \
	  dhcpd-formula \
	  image-sync-formula \
	  pxe-formula \
	  saltboot-formula \
	  susemanager-retail-tools \
	  tftpd-formula \
	  vsftpd-formula

----
. Reboot the {productname} {smr} Server.

// yast2 susemanager_setup

When the installation is complete, you can continue with {productname} setup.
For more information, see xref:retail:retail-uyuni-server-setup.adoc[].
