[[retail-best-practices]]
= Best Practices

== Deploying New Images

This file describes how to deploy a new image on selected terminals first, test it, and then deploy it to all terminals.

The hardware type (HWTYPE) group is used for booting new terminals, while already deployed terminals can
be moved to any group that provides the Saltboot formula. This flexibility allows for testing new images
or configurations. Follow these steps to ensure a smooth deployment process:

* Build New Image

  * Use Image Sync formula to synchronize the image to all Branch Servers

* Create a Test Group

  * Name the group, for example, "TEST:POSVendor-Terminal". Name can be chosen freely.
  * Add the Saltboot formula to this group, replicating the configuration from the original HWTYPE group, except for the image version. Use the name and version of the new image.

* Move Selected Terminals

  * Identify the terminals you want to test the new image on.
  * Transfer these terminals from the HWTYPE:POSVendor-Terminal group to the newly created TEST:POSVendor-Terminal group. It is recommended to use System Set Manager for this task.

* Reboot Terminals

  * Power on the selected POS terminals. They should boot the new image.

* Verify and Evaluate

  * Monitor the terminals in the TEST:POSVendor-Terminal group.
  * Check if the new image performs as expected and if there are any issues or errors encountered.

* Update HWTYPE Group

  * Once you have confirmed that the new image works correctly, it's time to update the HWTYPE group.
  * Modify the image version in the HWTYPE:POSVendor-Terminal group to match the tested and approved version.
  * This ensures that all other terminals receive the new image.

=== Controlling Image Versions

By default, saltboot formula selects the specified image name and version, or selects the highest one if version is not specified.

There are multiple methods to control the image version within the HWTYPE and TEST groups:

* Specify Exact Version

  * In both the HWTYPE and TEST groups, explicitly specify the exact version of the image to be deployed.
  * Make sure that the specified image version is already synchronized.

* Mark New Image as ``Inactive``

  * In the HWTYPE group, do not specify the image version.
  * Mark the new image as ``inactive`` after building and before synchronizing it to Branch Server.
  * The ``inactive` flag ensures, that the image is not auto-selected when the image version is not specified.
  * After testing, remove the ``inactive`` flag so the image can be auto-selected in HWTYPE group.
  * The ``inactive`` flag can be accessed through the API, see xref:retail-image-pillar.adoc[Image Pillar]

*  Utilize ``Freeze Image`` Flag:

  * In the HWTYPE group, omit the image version
  * Before synchronizing the new image, set the ``Freeze Image`` flag in Saltboot Formula in HWTYPE group. This ensures that the already deployed terminals in this group will keep the old image.
  * Synchronize and test the new image in the TEST group
  * Reset the ``Freeze Image`` flag in HWTYPE group, so the terminals in this group will be updated to the new image too.

[WARNING]
====
Do not use the whitelist in Image Sync formula to control which terminal boots which image. It does not provide the required granularity and does not work with containerized Branch Server.
====

