[[retail-server-setup]]
= Retail Uyuni Server Setup

This section covers {productname} Server setup, using these procedures:

* Start {productname} setup with {yast}
* Create the main administration account with the {productname} {webui}
* Name your base organization and add login credentials
* Synchronize the OpenSUSE Leap channel
+
// ^^^ CHECKIT



[[retail-server-setup-yast]]
== Set up {productname} with {yast}

This section will guide you through {productname} setup procedures.

.Procedure: {productname} Setup
. Log in to the {productname} Server and start {yast}.

. In {yast}, navigate to menu:Network Services[Uyuni Setup] to begin the setup.

. From the introduction screen select menu:Uyuni Setup[Set up Uyuni from scratch] and click btn:[Next] to continue.

. Enter an email address to receive status notifications and click btn:[Next] to continue.
{productname} can sometimes send a large volume of notification emails.
You can disable email notifications in the {webui} after setup, if you need to.

. Enter your certificate information and a password.
Passwords must be at at least seven characters in length, and must not contain spaces, single or double quotation marks (``'`` or ``"``), exclamation marks (``!``), or dollar signs (``$``).
Always store your passwords in a secure location.
+

[IMPORTANT]
====
You must have the certificate password to set up a {productname} Proxy Server.
====

. Click btn:[Next] to continue.

. From the menu:Uyuni Setup[Database Settings] screen, enter a database user and password and click btn:[Next] to continue.
Passwords must be at at least seven characters in length, and must not contain spaces, single or double quotation marks (``'`` or ``"``), exclamation marks (``!``), or dollar signs (``$``).
Always store your passwords in a secure location.

. Click btn:[Next] to continue.

. Click btn:[Yes] to run setup when prompted.

. When setup is complete, click btn:[Next] to continue.
You will see the address of the {productname} {webui}.

. Click btn:[Finish] to complete {productname} setup.



== Create the Main Administration Account

This section covers how to create your organization's main administration account for {productname}.

[WARNING]
====
The main administration account has the highest authority within {productname}.
Ensure you keep access information for this account secure.

We recommend that you create lower level administration accounts for organizations and groups.
Do not share the main administration access details.
====


.Procedure: Setting Up the Main Administration Account

. In your web browser, enter the address for the {productname} {webui}.
This address was provided after you completed setup.
For more information, see xref:retail:retail-uyuni-server-setup.adoc#retail-server-setup-yast[].

. Sign in to the {webui}, navigate to the menu:Create Organization[Organization Name] field, and enter your organization name.

. In the menu:Create Organization[Desired Login] and menu:Create Organization[Desired Password] fields, enter your username and password.

. Fill in the Account Information fields including an email for system notifications.

. Click btn:[Create Organization] to finish creating your administration account.

When you have completed the {productname} {webui} setup, you are taken to the menu:Home[Overview] page.



== Synchronize the OpenSUSE Leap Channel

Use [command]``spacewalk-common-channels`` to obtain all needed channels:

.Procedure:
. First the OpenSUSE Leap that is the parrent channel for all the following channels needed:
+
----
spacewalk-common-channels opensuse_leap15_2
----
+
If you do not enable opensuse_leap15_2 first, you will see the following error:
+
----
# ERROR: opensuse_leap15_2-x86_64 could not be found at the server
# ERROR: opensuse_leap15_2-uyuni-client-x86_64: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: User 1 does not have access to channel opensuse_leap15_2-x86_64 or the channel does not exist
----

. Enable the child channels:
+
----
spacewalk-common-channels opensuse_leap15_2-updates
spacewalk-common-channels uyuni-proxy-stable-leap-152
spacewalk-common-channels opensuse_leap15_2-uyuni-client
----
+
If everything is successfully finished, you will see this message:
+
----
# Base channel 'openSUSE Leap 15.2 (x86_64)' - exists
----

. Synchronize all repositories, which will take a lot of time to finish:
+
----
spacewalk-repo-sync -c opensuse_leap15_2-x86_64
spacewalk-repo-sync -c opensuse_leap15_2-x86_64-updates
spacewalk-repo-sync -c opensuse_leap15_2-uyuni-client-x86_64
spacewalk-repo-sync -c uyuni-proxy-stable-leap-152-x86_64
----



// FIXME Starting from here, everything is preliminary
// Feedback provided by Lukas
== Create Activation Key for a Proxy (Branch Server) and the Retail Terminals

For more information about creating activation keys, see xref:client-configuration:activation-keys.adoc[].

The activation key for a proxy (branch server) must contain these child channels:

* openSUSE Leap 15.2 Updates (x86_64)
* Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)
* Uyuni Proxy Stable for openSUSE Leap 15.2 (x86_64)

The activation key for retail terminals based on openSUSE Leap 15.2 must contain these child channels:

* openSUSE Leap 15.2 Updates (x86_64)
* Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)




== Bootstrapping

Bootstrap repositories are created automatically.
If something is missing, run the [command]``mgr-create-boostrap-repo`` manually.



=== Proxy

The proxy can be bootstrapped using the {webui}, or at the command prompt.
Ensure you use the activation key you created for the proxy.

For more information about proxies, see xref:installation:uyuni-proxy-registration.adoc[].
For more information about activation keys, see xref:client-configuration:activation-keys.adoc[].


[NOTE]
====
This proxy is going to be used as a retail branch server.
====



.Procedure: Uyuni Proxy specific steps
. Check  that the ``Uyuni Proxy Stable for openSUSE Leap 15.2 (x86_64)`` channel is assigned to the proxy on the system profile page.

. At the command prompt on the proxy, as root, install the proxy pattern:
+

----
zypper in -t pattern uyuni_proxy
----

. Finalize the proxy setup:
+
----
configure-proxy.sh
----
+
[command]``configure-proxy.sh`` is an interactive script.
For more information, see xref:installation:uyuni-proxy-setup.adoc#uyuni-proxy-setup-confproxy[].

. OPTIONAL: If you want to use the same system also as a build host, navigate to the client's system profile and check [systemitem]``OS Image Build Host`` as a [guimenu]``Add-On System Types``.

. Configure the proxy to run as a branch server.
For example, enter such a network configuration :
+
// we'd better go for example.org
+
----
retail_branch_init vm155237.qa.prv.suse.net --dedicated-nic eth1 \
    --branch-ip 192.168.7.5 \
    --netmask 255.255.255.0 \
    --dyn-range 192.168.7.100 192.168.7.200 \
    --server-name uyunibranch --server-domain branch.org \
    --branch-prefix uyuni
----

////
FIXME, ke: we should think about this later:

Next we need to adapt kiwi profile for Leap 15.2, it is possible to simply modify JeOS7 for SLE15SP2 by
dropping few SLE specific packages and directives:

         <bootsplash-theme>SLE</bootsplash-theme>
         <bootloader-theme>SLE</bootloader-theme>
         <package name="grub2-branding-SLE" bootinclude="true"/>
         <package name="SUSEConnect"/>
         <package name="suse-build-key"/>
         <package name="plymouth-branding-SLE"/>
         <package name="sles-release"/>
         <package name="rhn-org-trusted-ssl-cert-osimage"/>

Side note: I plan to publish modified profile somewhere, but I haven't decided where yet as it is uyuni and
feature without support.

Then it is possible to build the image using modified kiwi profile and deploy it to terminal as usual (there is
nothing specific for Uuyni).

The rest of things (saltboot formula and formula for image syncing works just the same way as SUMA.)

Only thing that behaves differently is naming of terminals, for some reason dashes are used instead of
HWTYPE (for example). But fortunately it has no impact on (at least basic) functionality of terminal.
////
