[[retail-server-setup]]
= Retail Uyuni Server Setup

This section covers {productname} Server setup, using these procedures:

* Start {productname} setup with {yast}
* Create the main administration account with the {productname} {webui}
* Name your base organization and add login credentials
* Synchronize the OpenSUSE Leap channel
+
// ^^^ CHECKIT



[[retail-server-setup-yast]]
== Set up {productname} with {yast}

This section will guide you through {productname} setup procedures.

.Procedure: {productname} Setup
. Log in to the {productname} Server and start {yast}.

. In {yast}, navigate to menu:Network Services[Uyuni Setup] to begin the setup.

. From the introduction screen select menu:Uyuni Setup[Set up Uyuni from scratch] and click btn:[Next] to continue.

. Enter an email address to receive status notifications and click btn:[Next] to continue.
{productname} can sometimes send a large volume of notification emails.
You can disable email notifications in the {webui} after setup, if you need to.

. Enter your certificate information and a password.
Passwords must be at at least seven characters in length, and must not contain spaces, single or double quotation marks (``'`` or ``"``), exclamation marks (``!``), or dollar signs (``$``).
Always store your passwords in a secure location.
+

[IMPORTANT]
====
You must have the certificate password to set up a {productname} Proxy Server.
====

. Click btn:[Next] to continue.

. From the menu:Uyuni Setup[Database Settings] screen, enter a database user and password and click btn:[Next] to continue.
Passwords must be at at least seven characters in length, and must not contain spaces, single or double quotation marks (``'`` or ``"``), exclamation marks (``!``), or dollar signs (``$``).
Always store your passwords in a secure location.

. Click btn:[Next] to continue.

. Click btn:[Yes] to run setup when prompted.

. When setup is complete, click btn:[Next] to continue.
You will see the address of the {productname} {webui}.

. Click btn:[Finish] to complete {productname} setup.



== Create the Main Administration Account

This section covers how to create your organization's main administration account for {productname}.

[WARNING]
====
The main administration account has the highest authority within {productname}.
Ensure you keep access information for this account secure.

We recommend that you create lower level administration accounts for organizations and groups.
Do not share the main administration access details.
====


.Procedure: Setting Up the Main Administration Account

. In your web browser, enter the address for the {productname} {webui}.
This address was provided after you completed setup.
For more information, see xref:uyuni-server-setup.adoc#retail-server-setup-yast[].

. Sign in to the {webui}, navigate to the menu:Create Organization[Organization Name] field, and enter your organization name.

. In the menu:Create Organization[Desired Login] and menu:Create Organization[Desired Password] fields, enter your username and password.

. Fill in the Account Information fields including an email for system notifications.

. Click btn:[Create Organization] to finish creating your administration account.

When you have completed the {productname} {webui} setup, you are taken to the menu:Home[Overview] page.



== Synchronize the OpenSUSE Leap Channel

Use [command]``spacewalk-common-channels`` to obtain all needed channels:

.Procedure:
. First the OpenSUSE Leap that is the parrent channel for all the following channels needed:
+
----
spacewalk-common-channels opensuse_leap15_2
----
+
If you do not enable opensuse_leap15_2 first, you will see the following error:
+
----
# ERROR: opensuse_leap15_2-x86_64 could not be found at the server
# ERROR: opensuse_leap15_2-uyuni-client-x86_64: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: User 1 does not have access to channel opensuse_leap15_2-x86_64 or the channel does not exist
----

. Enable the child channels:
+
----
spacewalk-common-channels opensuse_leap15_2-updates
spacewalk-common-channels uyuni-proxy-stable-leap-152
spacewalk-common-channels opensuse_leap15_2-uyuni-client
----
+
If everything is successfully finished, you will see this message:
+
----
# Base channel 'openSUSE Leap 15.2 (x86_64)' - exists
----

. Synchronize all repositories, which will take a lot of time to finish:
+
----
spacewalk-repo-sync -c opensuse_leap15_2-x86_64
spacewalk-repo-sync -c opensuse_leap15_2-x86_64-updates
spacewalk-repo-sync -c opensuse_leap15_2-uyuni-client-x86_64
spacewalk-repo-sync -c uyuni-proxy-stable-leap-152-x86_64
----
