[[retail-formulas]]
= Formulas
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]

// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]


Formulas are pre-written Salt states, that are used to configure your {smr} installation.

This section lists the primary formulas shipped with {smr} and their configuration options.

All the formulas in this section must be accurately configured for your {smr} installation to function correctly. If you are unsure of the correct formula configuration details, run the [command]``retail_branch_init`` command before you begin to create the recommended formula configuration. You can then manually edit the formulas as required.


.State and formula name collisions
[IMPORTANT]
====
If a formula uses the same name as an existing Salt state, the two names will collide, and could result in the formula being used instead of the state.
Always check the names of states and formulas to avoid name collisions.
====

Most formulas can be updated using the {susemgr} {webui}.
Once you have made changes to your formula, ensure you apply the highstate to propagate your changes to the appropriate services.


// We should ensure these are in alphabetical order. LKB

[[retail.sect.formulas.bind]]
== Bind Formula

The Bind formula is used to configure the Domain Name System (DNS) on the branch server.
POS terminals will use the DNS on the branch server for name resolution of saltboot specific hostnames.

When you are configuring the bind formula for a branch server with a dedicated internal network, check that you are using the same fully qualified domain name (FQDN) on both the external and internal branch networks.
If the FQDN does not match on both networks, the branch server will not be recognized as a proxy server.

[NOTE]
====
The following procedure outlines a standard configuration with two zones.
Adjust it to suit your own environment.
====

Zone 1 is a regular domain zone.
Its main purpose is to resolve saltboot hostnames such as TFTP, FTP, or Salt.
It can also resolve the terminal names if configured.

Zone 2 is the reverse zone of Zone 1.
Its main purpose is to resolve IP addresses back to hostnames.
Zone 2 is primarily needed for the correct determination of the FQDNs of the branch.


.Procedure: Configuring Bind with Two Zones

. Check the [systemitem]``Bind`` formula, and click [btn]``Save``.
. Navigate to the menu:Formulas[Bind] tab, and set these parameters for Zone 1:
* In the [guimenu]``Config`` section, select [systemitem]``Include Forwarders``.
* In the [guimenu]``Name`` field, enter the domain name of your branch network (for example: [systemitem]``branch1.example.org``).
* In the [guimenu]``Type`` field, select [systemitem]``master``.
. Click [btn]``Add item`` to save your changes.
. Set these parameters for Zone 2:
* In the [guimenu]``Name`` field, use the reverse zone for the configured IP range (for example: [systemitem]``1.168.192.in-addr.arpa``).
* In the [guimenu]``Type`` field, select [systemitem]``master``
. In the [guimenu]``Available Zones`` section, use these parameters for Zone 1:
* In the [guimenu]``Name`` field, enter the domain name of your branch network (for example: [systemitem]``branch1.example.org``).
* In the [guimenu]``File`` field, type the name of your configuration file.
. In the [guimenu]``Start of Authority (SOA)`` section, use these parameters for Zone 1:
* In the [guimenu]``Nameserver (Ns)`` field, use the FQDN of the  branch server (for example: [systemitem]``branchserver.branch1.example.org``).
* In the [guimenu]``Contact`` field, use the email address for the domain administrator.
* Keep all other fields as their default values.
. In the [guimenu]``Records`` section, in subsection [guimenu]``A``, click btn:[Add Item] and use these parameters to set up an A record for Zone 1:
* In the [guimenu]``Hostname`` field, use the hostname of the branch server (for example: [systemitem]``branchserver``).
* In the [guimenu]``IP`` field, use the IP address of the branch server (for example, [systemitem]``192.168.1.1``).
. In the [guimenu]``Records`` section, subsection [guimenu]``NS``, click btn:[Add Item] and use these parameters to set up an NS record for Zone 1:
* In the input box, use the hostname of the branch server (for example: [systemitem]``branchserver``).
. In the [guimenu]``Records`` section, subsection [guimenu]``CNAME``, click on btn:[Add Item] and add the hostname of the branch server in each of these fields:
* [systemitem]``tftp``
* [systemitem]``ftp``
* [systemitem]``dns``
* [systemitem]``dhcp``
* [systemitem]``salt``.  The [systemitem]`salt` CNAME should be the FQDN of the branch server's external interface for proxy functionality to work correctly.
. Set up Zone 2 using the same parameters as for Zone 1, but ensure you use the reverse details:
* The same SOA section as Zone 1.
* Empty A and CNAME records.
*  Additionally, configure in Zone 2:
** `Generate Reverse` field by the network IP address set in branch server network formula (for example, [systemitem]``192.168.1.1/24``).
** `For Zones` should specify the domain name of your branch network (for example, [systemitem]``branch1.example.org``).
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.


[IMPORTANT]
====
Reverse name resolution on terminals might not work for networks that are inside one of these IPv4 private address ranges:

* [systemitem]``10.0.0.0/8``
* [systemitem]``172.16.0.0/12``
* [systemitem]``192.168.0.0/16``

If you encounter this problem, go to the [guimenu]``Options`` section of the Bind formula, and click btn:[Add item]:
* In the [guimenu]``Options`` field, enter [systemitem]``empty-zones-enable``.
* In the [guimenu]``Value`` field, select [systemitem]``No``.
====



[[retail.sect.formulas.branch-network]]
== Branch Network Formula

The branch network formula is used to configure the networking services required by the branch server, including DHCP, DNS, TFTP, PXE, and FTP.

The branch server can be configured to use networking in many different ways.
The most common ways provide either a dedicated or shared LAN for terminals.



=== Set up a branch server with a dedicated LAN

In this configuration, the branch server requires at least two network interfaces: one acts as a WAN to communicate with the {susemgr} server, and the other one acts as an isolated LAN to communicate with terminals.

This configuration allows for the branch server to provide DHCP, DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.


.Procedure: Setting up a branch server with a dedicated LAN

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` checked
* In the [guimenu]``NIC`` field, enter the name of the network device that is connected to the internal LAN.
* In the [guimenu]``IP`` field, enter the static IP address to be assigned to the branch server on the internal LAN.
* In the [guimenu]``Netmask`` field, enter the network mask of the internal LAN.
. Check [guimenu]``Enable Route`` if you want the branch server to route traffic from internal LAN to WAN.
* Check [guimenu]``Enable NAT`` if you want the branch server to convert addresses from internal LAN to WAN.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click btn:[Save] to save your changes.
. Apply the highstate.



=== Set up a branch server with a shared network

In this configuration, the branch server has only one network interface card, which is used to connect to the {susemgr} server as well as the terminals.

This configuration allows for the branch server to provide DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.
Optionally, the branch server can also provide DHCP services in this configuration.

[NOTE]
====
If DHCP services are not provided by the branch server, ensure that your external DHCP configuration is set correctly:
* The [systemitem]``next-server`` option must point to the branch server for PXE boot to work
* The [systemitem]``filename`` option must correctly identify the network boot program (by default, this is [path]``/boot/pxelinux``)
* The [systemitem]``domain-name-servers`` option must point to the branch server for correct host name resolution
====


.Procedure: Setting up a branch server with a shared network

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` unchecked
* Select which services to enable on the branch server’s firewall.
Ensure you include DNS, TFTP and FTP services.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click btn:[Save] to save your changes.
. Apply the highstate.



[[retail.sect.formulas.dhcpd]]
== DHCPd Formula

The DHCPd formula is used to configure the DHCP service on the branch server.


.Procedure: Configuring DHCP

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the Formulas tab.
. Select the [guimenu]``Dhcpd`` formula, and click btn:[Save].
. Navigate to the menu:Formulas[Dhcpd] tab, and set these parameters:
* In the [guimenu]``Domain Name`` field, enter the domain name for the branch server (for example: [systemitem]``branch1.example.com``).
* In the [guimenu]``Domain Name Server`` field, enter either the IP address or resolvable FQDN of the branch DNS server (for example: [systemitem]``192.168.1.1``).
* In the [guimenu]``Listen Interfaces`` field, enter the name of the network interface used to connect to the local branch network (for example: [systemitem]``eth1``).
. Navigate to the [guimenu]``Network Configuration (subnet)`` section, and use these parameters for Network1:
* In the [guimenu]``Network IP`` field, enter the IP address of the branch server network (for example: [systemitem]``192.168.1.0``).
* In the [guimenu]``Netmask`` field, enter the network mask of the branch server network (for example: [systemitem]``255.255.255.0``).
* In the [guimenu]``Domain Name`` field, enter the domain name for the branch server network (for example: [guimenu]``branch1.example.com``).
. In the [guimenu]``Dynamic IP Range`` section, use these parameters to configure the IP range to be served by the DHCP service:
* In the first input box, set the lower bound of the IP range (for example: [systemitem]``192.168.1.51``).
* In the second input box, set the upper bound of the IP range (for example: [systemitem]``192.168.1.151``).
. In the [guimenu]``Broadcast Address`` field, enter the broadcast IP address for the branch network (for example: [systemitem]``192.168.1.255``).
. In the [guimenu]``Routers`` field, enter the IP address to be used by routers in the branch server network (for example: [systemitem]``192.168.1.1``).
. In the [guimenu]``Next Server`` field, enter the hostname or IP address of the branch server (for example: [systemitem]``192.168.1.1``).
. In the [guimenu]``Filename`` field, keep the default value of [systemitem]``/boot/pxelinux.0``.
. Click btn:[Save Formula] to save your configuration
. Apply the highstate.



[[retail.sect.formulas.pxe]]
== PXE Formula

The PXE formula is used to configure PXE booting on the branch server.


.Procedure: Configuring PXE booting
. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``Pxe`` formula, and click [btn]``Save``.
. Navigate to the menu:Formulas[Pxe] tab, and set these parameters:
* In the [guimenu]``Kernel filename`` field, keep the default value.
* In the [guimenu]``Initrd filename`` field, keep the default value.
* In the [guimenu]``Kernel commandline parameters`` field, keep the default value.
* In the [guimenu]``PXE root directory`` field, enter the path to the saltboot directory (for example, [systemitem]``/srv/saltboot``).
* In the [guimenu]``Branch id`` field, type a name to use as a branch identifier (for example: [systemitem]``Branch0001``).
Use only alphanumeric characters for the branch identifier.
. Click [btn]``Save Formula`` to save your configuration
. Apply the highstate.


[[retail.sect.formulas.saltboot]]
== Saltboot Formula

The Saltboot formula is used to configure disk images and partitioning for the selected hardware type.

[IMPORTANT]
====
Saltboot formula is meant to be used as a group formula. Enable and configure saltboot formula for hardware type groups.
====

.Procedure: Configuring the hardware type group with saltboot

. Open the details page for your new hardware type group, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``saltboot-formula`` and click btn:[Save].
. Navigate to the new menu:Formulas[Saltboot] tab.
. In the [guimenu]``Disk 1`` section, set these parameters:
* In the [guimenu]``Disk symbolic ID`` field, enter a custom name for the disk (for example, [systemitem]``disk1``).
* In the [guimenu]``Device type`` field, select [systemitem]``DISK``.
* In the [guimenu]``Disk device`` field, select the device that corresponds to the device name on the target machine (for example, [path]``/dev/sda``).
* In the [guimenu]``RAID level`` field, leave it empty.
* In the [guimenu]``Disk Label`` field, select [systemitem]``gpt``.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 1``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p1``).
* In the [guimenu]``Partition size`` field, specify a size for the partition in Mebibytes (MiB).
* In the [guimenu]``Device mount point`` field, select a location to mount the partition (for example, [path]``/data``).
* In the [guimenu]``Filesystem format`` field, select your preferred format (for example, [systemitem]``xfs``).
* In the [guimenu]``OS Image to deploy`` field, leave it empty.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, leave it empty.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 2``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p2``).
* In the [guimenu]``Partition size`` field, specify a size for the partition in Mebibytes (MiB).
* In the [guimenu]``Device mount point`` field, leave it empty.
* In the [guimenu]``Filesystem format`` field, select [systemitem]``swap``.
* In the [guimenu]``OS Image to deploy`` field, leave it empty.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, select [systemitem]``swap``.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 3``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p3``).
* In the [guimenu]``Partition size`` field, leave it empty.
This will ensure the partition uses up all remaining space.
* In the [guimenu]``Device mount point`` field, select [systemitem]``/``.
* In the [guimenu]``Filesystem format`` field, leave it empty.
* In the [guimenu]``OS Image to deploy`` field, enter the name of the image to deploy.
* In the [guimenu]``Image version`` field, leave it empty.
This will ensure you use the latest available version.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, leave it empty.
. Click btn:[Save Formula] to save your formula.





[[retail.sect.formulas.tftpd]]
== TFTPd Formula

The TFTPd formula is used to configure the TFTP service on the branch server.


.Procedure: Configuring TFTP

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``Tftpd`` formula, and click btn:[Save].
. Navigate to the menu:Formulas[Tftpd] tab, and set these parameters:
* In the [guimenu]``Internal Network Address`` field, enter the IP address of the branch server (for example: [systemitem]``192.168.1.1``).
* In the [guimenu]``TFTP Base Directory`` field, enter the path to the saltboot directory (for example, [systemitem]``/srv/saltboot``).
* In the [guimenu]``Run TFTP Under User`` field, enter [systemitem]``saltboot``.
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.



[[retail.sect.formulas.vsftpd]]
== VsFTPd Formula

The VsFTPd formula is used to configure the FTP service on the branch server.


.Procedure: Configuring VsFTPd

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``Vsftpd`` formula, and click btn:[Save].
. Navigate to the menu:Formulas[Vsftpd] tab, and set these parameters:
* In the [guimenu]``Internal Network Address``, enter IP address of branch server (for example: [systemitem]``192.168.1.1``).
* All other fields can retain their default values.
. Click btn:[Save Formula] to save your configuration
. Apply the highstate.
