[[organizations]]
= 组织
:revdate: 2022-01-13
:page-revdate: {revdate}


组织用于管理 {productname} 中的用户访问权限和许可权限。

对于大多数环境而言，一个组织便已足够。但是，较复杂的环境可能需要多个组织。您可以为企业中的每个物理位置或不同的业务职能创建一个组织。

创建组织后，可以创建用户并将其指派到组织。然后，可以在组织级别指派权限，这些权限默认将应用于指派到组织的每个用户。

您还可以为新组织配置身份验证方法，包括 PAM 和单点登录。有关身份验证的详细信息，请参见 xref:administration:auth-methods.adoc[]。

[NOTE]
====
您必须以 {productname} 管理员身份登录才能创建和管理组织。
====



.过程：创建新组织
. 在 {productname} {webui} 中，导航到menu:管理[组织]，然后单击 btn:[创建组织]。
. 在[guimenu]``创建组织``对话框中填写以下字段：
* 在[guimenu]``组织名称``字段中，键入新组织的名称。
    该名称的长度应为 3 到 128 个字符。
* 在[guimenu]``要使用的登录名``字段中，键入要用于组织管理员的登录名。
    这必须是一个新的管理员帐户，您无法使用现有的管理员帐户（包括当前使用的登录帐户）登录到新组织。
* 在[guimenu]``要使用的口令``字段中，键入新组织管理员的口令。
    在[guimenu]``确认口令``字段中再次键入该口令以确认。口令强度由口令字段下方的彩色条指示。
* 在[guimenu]``电子邮件``字段中，键入新组织管理员的电子邮件地址。
* 在[guimenu]``名字``字段中选择一种称呼，然后键入新组织管理员的名字。
* 在[guimenu]``姓氏``字段中，键入新组织管理员的姓氏。
. 单击 btn:[创建组织]。



== 管理组织


在 {productname} {webui} 中，导航到menu:管理[组织]可查看可用组织的列表。单击某个组织的名称可对其进行管理。

在menu:管理[组织]部分，可以访问相应的选项卡来管理组织的用户、信任、配置和状态。

[NOTE]
====
组织只能由其管理员管理。要管理组织，请确保以您要更改的组织的正确管理员身份登录。
====



=== 组织用户

导航到[guimenu]``用户``选项卡可查看与组织关联的所有用户的列表及其角色。单击某个用户名会转到[guimenu]``用户``菜单，可在其中添加、更改或删除用户。



=== 可信组织

导航到[guimenu]``信任``选项卡可添加或去除受信任组织。在组织之间建立信任可让它们相互共享内容，这样您也可以在不同的组织之间切换客户端。



=== 配置组织

导航到[guimenu]``配置``选项卡可以管理组织的配置。这包括使用暂存内容和使用 SCAP 文件。

有关内容暂存的详细信息，请参见 xref:administration:content-staging.adoc[]。

有关 OpenSCAP 的详细信息，请参见 xref:reference:audit/audit-openscap-overview.adoc[]。



== 管理状态


导航到[guimenu]``状态``选项卡可以管理组织中所有客户端的 Salt 状态。使用状态可以定义全局安全策略，或者将公共管理员用户添加到所有客户端。

有关 Salt 状态的详细信息，请参见 xref:specialized-guides:salt/salt-states-and-pillars.adoc[]。



=== 管理配置通道

可以选择要在整个组织中应用哪些配置通道。可以在 {productname} {webui} 中导航到menu:配置[通道]来创建配置通道。使用 {productname} {webui} 将配置通道应用于您的组织。

.过程：将配置通道应用于组织
. 在 {productname} {webui} 中，导航到menu:首页[我的组织 > 配置通道]。
. 使用搜索功能按名称查找通道。
. 选中要应用的通道，然后单击 btn:[保存更改]。
    这会将更改保存到数据库，但不会将其应用于通道。
. 单击 btn:[应用] 以应用更改。
    随即会安排将更改应用于组织中的所有客户端的任务。
