[[ref-scap-tailoring-files-list]]
= Tailoring Files
:revdate: 2026-04-08
:page-revdate: {revdate}


The menu:Audit[Tailoring Files] section displays the SCAP tailoring files available in your organization.
Tailoring files allow you to customize XCCDF profiles by enabling, disabling, or modifying specific rules without changing the original SCAP content.

Click btn:[Create] to upload a new tailoring file.
For more information about uploading tailoring files, see <<ref-scap-tailoring-file-upload>>.

Each row in the list provides btn:[Edit] and btn:[Delete] action buttons.
Use btn:[Edit] to modify the name, description, or replace the uploaded tailoring file.
Use btn:[Delete] to remove the tailoring file entry.
A confirmation dialog is displayed before deletion.

You can filter the list using the search bar, which searches across the label and file name fields.


[[scap-tailoring-files-list-columns]]
[cols="1,1", options="header"]
.Tailoring Files List Columns
|===
| Column             | Description
| Label              | The display name of the tailoring file.
| Tailoring File Name | The file name of the uploaded tailoring file.
| Actions            | Available actions: Edit and Delete.
|===



[[ref-scap-tailoring-file-upload]]
== Upload Tailoring File

The menu:Audit[Tailoring Files > Create] page allows you to upload a new tailoring file.

.Upload Tailoring File Fields
[cols="1,1,1", options="header"]
|===
| Field          | Required | Description
| Name           | Yes      | A display name for the tailoring file.
| Description    | No       | A brief description of the tailoring file.
| Tailoring File | Yes      | The tailoring XML file (``.xml``) to upload.
|===

Click btn:[Upload] to save the new tailoring file.



[[ref-scap-tailoring-file-edit]]
== Edit Tailoring File

The menu:Audit[Tailoring Files > Edit] page allows you to update an existing tailoring file entry.
You can change the name, description, or upload a replacement file.
If you do not upload a new file, the existing file is retained.

Click btn:[Update] to save the changes.
