[[ref.webui.audit.subscription]]
= Subscription Matching

The menu:Audit[Subscription Matching] section provides reports that match your currently installed clients to your existing product subscriptions.
Subscription matching reports provide information about clients that do not have a subscription, and subscription start and end dates.


[[subscription-matching-options]]
[cols="1,1", options="header"]
.Bootstrap Script Options
|===
| Column          | Description
| Part Number     | Identifier of the matched product
| Description     | Description of the matched product
| Policy          | The type of subscription matched to the product
| Matched/Total   | The number of clients currently using the subscription, of the total available.
If the subscription is fully matched, the quantity column value is highlighted.
| Start Date      | Start date of the subscription
| End Date        | End date of the subscription
|===


Table entries are highlighted if they are due to expire within three months.
Table entries that have already expired are shown in grayscale.

For more information about subscription matching, see xref:administration:subscription-matching.adoc[].
