[[script-client-proxy]]
= Registering with a Bootstrap Script (Salt and Traditional)


Registering clients (either traditional or Salt) via {susemgrproxy} with a
bootstrap script is done almost the same way as registering clients directly
with the {productname} Server.  The difference is that you create the
bootstrap script on the {susemgrproxy} with a command line tool.  The
bootstrap script then deploys all necessary information to the clients.  The
bootstrap script requires some parameters (such as activation keys or GPG
keys) that depend on your specific setup.



.Procedure: Registering Clients to a Proxy with a Bootstrap Script

. Create a client activation key on the {productname} server using the
  {webui}.  For more information, see
  xref:client-configuration:activation-keys.adoc[].
. On the proxy, execute the [command]``mgr-bootstrap`` command line tool as
  {rootuser}.  If needed, use the additional command line switches to tune
  your bootstrap script.  To install a traditional client instead of a Salt
  client, ensure you use the [command]``--traditional`` switch.
+
To view available options type [command]``mgr-bootstrap --help`` from the
command line:
+
----
# mgr-bootstrap --activation-keys=key-string
----
+
. Optional: edit the resulting bootstrap script.
. Execute the bootstrap script on the clients.
