[[virt-vhm]]
= Virtual Host Managers
:revdate: 2026-08-03
:page-revdate: {revdate}

Virtual Host Managers (VHMs) are used to gather information from a range of client types.

VHMs can be used to collect private or public cloud instances and organize them into virtualization groups.
With your virtualized clients organized this way, Taskomatic collects data on the clients for display in the {productname} {webui}.
VHMs also allow you to use subscription matching on your virtualized clients.

You can create a VHM on your {productname} Server, and use it to inventory available public cloud instances.
You can also use a VHM to manage clusters created with {kube}.

* For more information on using a VHM with Amazon Web Services, see xref:client-configuration:vhm-aws.adoc[].
* For more information on using a VHM with Microsoft Azure, see xref:client-configuration:vhm-azure.adoc[].
* For more information on using a VHM with Nutanix, see xref:client-configuration:vhm-nutanix.adoc[].
* For more information on using a VHM with VMWare vSphere, see xref:client-configuration:vhm-vmware.adoc[].
* For more information on using a VHM with other hosts, see xref:client-configuration:vhm-file.adoc[].


== Direct Hypervisor Querying

Registered physical Linux clients acting as hypervisors (such as KVM) do not require a Virtual Host Manager (VHM) configuration. Instead, if a registered physical host has the `Virtualization Host` add-on system type assigned, {productname} queries the system directly using `libvirt` to gather virtual machine data.

For more information, see xref:client-configuration:system-types.adoc[].
