[[salt.formulas]]
= Salt Formulas

Formulas are collections of Salt States that contain generic parameter fields.
Formulas allow for reliable reproduction of a specific configuration.
Some formulas are supplied by {suse}, or you can install formulas from RPM packages or an external git repository.

Formulas work best for large, non-trivial, configurations.
For smaller tasks, use a state rather than a formula.
Formulas and states both act as a kind of configuration documentation.
When you have written and stored the configuration, they provide a snapshot of your infrastructure.

Formula data can be managed using the XMLRPC API.

You can use the {productname} {webui} to apply {productname} formulas.
The most commonly used formulas are documented in this section.

Alternatively, you can use pre-written formulas as a starting point for your own custom formulas.
Pre-written formulas are available from https://github.com/saltstack-formulas.

For more information on custom formulas, see xref:specialized-guides:salt/salt-formulas-custom.adoc[].
