[[yomi-formula]]
= Yomi Formula

The Yomi (yet one more installer) installer for {suse} and openSUSE operating systems is configured using formulas with forms.

The ``yomi-formula`` package provides these formulas:

* Yomi
* Yomi Storage
* Yomi Bootloader
* Yomi Software
* Yomi Services
* Yomi Users



.Procedure: Install the Yomi Formulas with Forms
. On the {productname} Server, at the command prompt, as root, install the ``yomi-formula`` package:
+
----
zypper in yomi-formula
----
. Restart services:
+
----
systemctl restart salt-master.service
----

When the formula package is installed, you need to install the PXE Yomi image on the client, boot the client you want to provision, and enable the Yomi formulas on the client.
For more information on preparing Yomi clients for provisioning, see xref:specialized-guides:salt/salt-yomi.adoc[].



.Procedure: Configuring the Yomi Formula
. Navigate to the menu:Formulas[Yomi] tab, and set these parameters in the [guimenu]``General Configuration`` section:
* Check the [guimenu]``Events`` box to allow monitoring.
* In the [guimenu]``Reboot`` field, select ``yes`` to instruct the client to reboot after installation.
* Check the [guimenu]``Snapper`` box if you are using the btrfs file system on the client.
* In the [guimenu]``Locale`` field, select the region and encoding for systemd to use on the client.
    For example: ``en_US.utf8`` for US English and UTF-8.
* In the [guimenu]``Keymap`` field, select the appropriate keyboard layout.
    For example: ``us`` for a US keyboard layout.
* In the [guimenu]``Timezone`` field, select the timezone for the client to use.
    For example: [guimenu]``America/New_York`` for EST.
* In the [guimenu]``Hostname`` field, enter the hostname for the client to use.
    Leave this blank if you are using DHCP to provide the hostname.
* In the [guimenu]``Machine Id`` field, enter a machine identification number for the client.
    Leave this blank to have systemd generate one automatically.
* In the [guimenu]``Target`` field, enter a systemd target unit.
. Click btn:[Save Formula] to save your configuration.



.Procedure: Configuring the Yomi Storage Formula
. Navigate to the menu:Formulas[Yomi Storage] tab, and set these parameters in the menu:Partitions[Config] section:
* In the [guimenu]``Labels`` field, select the default partition table type to use.
* In the [guimenu]``Initial Gap`` field, select the default amount of space to leave before the first partition.
    For example: ``1{nbsp}MB``, or use ``0`` to leave no space between partitions.
. For each device that you want to configure, in the menu:Partitions[Devices] section, click btn:[+], and set these parameters:
* In the [guimenu]``Device`` field, type the mount point for the device.
    For example, ``/dev/sda``.
* In the [guimenu]``Label`` field, select the partition table type to use, if it is different from the default label you selected.
* In the [guimenu]``Initial Gap`` field, select the amount of space to leave before the first partition, if it is different from the default space you specified.
. For each partition that you want to create, in the menu:Partitions[Devices > Partitions] section, click btn:[+], and set these parameters:
* In the [guimenu]``Partition Number`` field, enter a number for the partition.
    The number you enter here is appended to the device name to identify the partition.
    For example, partition number ``1`` on device ``/dev/sda`` can be identified as ``/dev/sda1``.
* In the [guimenu]``Partition Name`` field, enter a name for the partition.
    Leave this blank if you have entered a partition number in the previous field.
* In the [guimenu]``Partition Size`` field, enter a size for the partition.
    For example: ``500{nbsp}MB``.
    Use ``rest`` to use all the remaining free space.
. For each file system that you want to create, in the [guimenu]``Filesystems`` section, click btn:[+], and set these parameters:
* In the [guimenu]``Partition`` field, select the partition to create the file system on.
    For example, ``/dev/sda1``.
* In the [guimenu]``Filesystem`` field, select the file system type to create.
* In the [guimenu]``Mountpoint`` field, type the mount point for the file system.
    For example: ``/`` for root.
. Click btn:[Save Formula] to save your configuration.


[NOTE]
====
If you want to use LVM or RAID on your devices, click btn:[+] in the appropriate sections, and complete the details for your environment.
====



.Procedure: Configuring the Yomi Bootloader Formula
. Navigate to the menu:Formulas[Yomi Bootloader] tab, and set these parameters in the [guimenu]``Bootloader`` section:
* In the [guimenu]``Device`` field, type the path for the bootloader.
    For example, ``/dev/sda``.
* In the [guimenu]``Timeout`` field, select the number of seconds grub will wait before booting the default menu entry.
* In the [guimenu]``Kernel`` field, type any additional kernel parameters you want to use.
    Any kernel parameters you add here will be appended to the ``GRUB_CMDLINE_LINUX_DEFAULT`` line during boot.
* In the [guimenu]``Terminal`` field, type the terminal to use for both terminal input and output.
* In the [guimenu]``Serial Command`` field, type parameters for using the serial port.
    Use this only if you are using the serial console as the default terminal.
* In the [guimenu]``Gfxmode`` field, type the resolution to use for the graphical terminal.
    Use this only if you are using the graphical console as the default terminal.
* Check the [guimenu]``Theme`` box to use GRUB2 default branding package.
* Check the [guimenu]``Disable OS Prober`` box to disable using the OS prober to discover other installed operating systems.
. Click btn:[Save Formula] to save your configuration.



.Procedure: Configuring the Yomi Software Formula
. Navigate to the menu:Formulas[Yomi Software] tab, and set these parameters in the menu:Software[Configuration] section:
* Check the [guimenu]``Minimal`` box to use a minimal installation, which only installs packages listed as ``Required``.
. For each repository that you want to add, in the menu:Software[Repositories] section, click btn:[+], and set these parameters:
* In the [guimenu]``Repository Name`` field, type a name for the repository.
* In the [guimenu]``Repository URL`` field, type the location of the repository.
. To add packages from each repository, in the menu:Software[Packages] section, click btn:[+], and set these parameters:
* In the menu:Software[Packages] field, type the names of the packages to install, or type a pattern to search for the appropriate packages.
    For example, ``pattern:enhanced_base glibc-locale``, or ``kernel-default``.
. In the menu:Software[Image] section, set these parameters:
* In the [guimenu]``Image URL`` field, type the location of the operating system ISO image to use.
* In the [guimenu]``Md5`` field, type the MD5 hash to use to verify the ISO.
. In the menu:SUSEConect[Config] section, set these parameters:
* In the [guimenu]``Registration Code`` field, type the registration code for the client you are installing.
    You can obtain this code from {scclongform}.
* In the [guimenu]``Email`` field, type the administrator email address to use.
* In the [guimenu]``Url`` field, type the address of the registration server to use.
    For example, use ``https://scc.suse.com``, to register with {scclongform}.
* In the [guimenu]``Version`` field, type the version of the product you are registering.
. For each product that you want to register, in the menu:SUSEConnect[Products] section, click btn:[+], and set these parameters:
* In the [guimenu]``Product`` field, type each product you want to register.
    For example, ``<product_name>/1.1/x86``, for version 1.1 with {x86} architecture.
* In the menu:SUSEConnect[Packages] field, type the names of the packages to install, or type a pattern to search for the appropriate packages.
    For example, ``pattern:enhanced_base glibc-locale``, or ``kernel-default``.
. Click btn:[Save Formula] to save your configuration.




.Procedure: Configuring the Yomi Services Formula
. Navigate to the menu:Formulas[Yomi Services] tab, and set these parameters:
* Check the [guimenu]``Install salt-minion`` box to install and configure the client as a Salt client.
. For each service you want to enable, in the menu:Services[Enabled] section, click btn:[+], and set these parameters:
* In the [guimenu]``Service`` field, type the name of the service to enable.
    For example, ``salt-minion``.
. For each service you want to disable, in the menu:Services[Disabled] section, click btn:[+], and set these parameters:
* In the [guimenu]``Service`` field, type the name of the service to disable.
. Click btn:[Save Formula] to save your configuration.




.Procedure: Configuring the Yomi Users Formula
. Navigate to the menu:Formulas[Yomi Users] tab.
. For each user you want to create, in the [guimenu]``Users`` section, click btn:[+], and set these parameters:
* In the [guimenu]``Username`` field, type the name of the new user.
* In the [guimenu]``Password Hash`` field, type the hashed version of the password to use.
. To add a certificate for each user, in the menu:Users[Certificates] section, click btn:[+], and add the certificate to the [guimenu]``Certificate`` field.
. Click btn:[Save Formula] to save your configuration.


When you have completed and saved all the forms, apply the highstate.


For more information about using Yomi, see xref:specialized-guides:salt/salt-yomi.adoc[].
