// FIXME: where appropriate, use the "Confirm with" expression.

[[liberate-formula]]
= Liberate Formula

The liberate formula migrates systems from EL clients such as {almalinux}, {centos} 7, {oracle} 9, {rocky} 9, or even {rhel} 9 to {sll}.
With this formula the conversion will take place during the client onboarding on {productname}.



[NOTE]
====

The Liberate Formula comes preinstalled within the server container.
====


== Configure {productname}



To provide all the software channels for {sll} on the {productname} Server, proceed as follows.



.Procedure: Providing SUSE Customer Center credentials

. Sign in to {scc} at https://scc.suse.com.

. Navigate to [guimenu]``My Organization``, and select your organization.

. Navigate to menu:Users[Organization Credentials] and take note of your organization username and password.

. In the {productname} {webui}, navigate to menu:Admin[Setup Wizard > Organization Credentials] to add the credentials to your {productname} Server.

. Click btn:[Add new credential], and enter the {scc} username and password noted in a previous step.


.Procedure: Synchronizing the SLL/SLES-ES channels:

. In the {productname} {webui}, navigate to menu:Admin[Setup Wizard > Products]
. Select the {sll} Channels that you will use:
+

* EL7: `SUSE Linux Enterprise Server with Expanded Support 7 x86_64`
* EL8: `RHEL or SLES ES or CentOS 8 Base`
* EL9: `RHEL and Liberty 9 Base`

. Click the top right button btn:[Add products].


Initial sychronization can take considerable time. You can check progress by accessing the server machine via SSH and monitoring the logs using:

----
tail -f /var/log/rhn/reposync/*
----


.Procedure: Creating one Activation Key per {sll} parent channel

. Note: Activation Keys are the way to register systems and automatically assign them to the required software and configuration channels corresponding to them.
. In the {productname} {webui}, navigate to menu:Systems[Activation Keys], and click the top right button btn:[Create key].
. In the [guimenu]``Activation Key`` dialog, set the fields:
+
Description::
Enter some text describing the activation key.
Key::
Enter the identifier of the key.  For example [literal``sll9-default`` for EL 9 systems.
Note: Keys will have a numeric prefix depending on the organization, so that they are unique.
Usage::
Leave blank.
Base Channel::
Select one base channel:
+

* EL7: `RHEL x86_64 Server 7`
* EL8: `RHEL8-Pool for x86_64`
* EL9: `EL9-Pool for x86_64`

Child Channel::
Include all child channels.

Add-On system type::
Leave all blank.
Contact Method::
Default
Universal Default::
Leave unchecked.

. Click btn:[Create Activation Key].



== Add Liberate formula and assign it to activation keys

When installed, the formula can be assigned to an Activation Key by creating a System Group:

.Procedure: Assigning system group and assigning liberate formula

. In the {productname} {webui}, navigate to menu:Systems[System Groups], and click the btn:[Create Group] button in top right corner.

. In the dialog, fill in the following data:
+

Name::
liberate
Description::
Systems to be converted to SUSE Liberty Linux

. From the `liberate` System Group page, navigate go to the  [guimenu]``Formulas`` tab.

. Select the [guimenu]``Liberate`` formula, and click btn:[Save].
  A new tab called `Liberate` will appear.

. On the [guimenu]``Liberate`` tab, you see the [option]``Reinstall all packages after conversion`` option.
  Keep it checked if you want to reinstall all the packages during the migration.
  This way you ensure all the packages will have {suse} signatures and no previous package will be kept.
  If you do not want to change the state of your system during the migration, uncheck this option and click the btn:[Save Formula] button.
  In this case, you can re-install the packages later.

Now a system group exists that has assigned the [guimenu]``Liberate`` formula.
This formula will be applied only once to migrate the system to {sll}, even if you run it multiple times.
With the next procedure, assign the system group to the Activation Key.


.Procedure: Assigning the system group to the Activation Key

. In the {productname} {webui}, navigate to menu:Systems[Activation Keys].

. Select the Activation Key, for example [literal]``sll9-default`` for the EL 9 systems.

. From the Activation Key page navigate to the menu:Groups[Join] tab, select the [literal]``liberate`` group, and click the btn:[Join Selected Groups] button.
  The group will be assigned to the Activation Key

.Procedure: Applying migrate directly during registration

. From the Activation Key page, navigate to the [guimenu]``Details`` tab.

. Navigate to the [guimenu]``Configuration File Deployment`` section, and checkb the [option]``Deploy configuration files to systems on registration``option.

. Click btn:[Update Activation Key].

When you register a system with this key it will perform the migration automatically.



== Register a new system and proceed to the migration

There are two ways to onboard (or register) a new client with the Activation Key:

xref:client-configuration:registration-webui.adoc[]::
This is intended for a one-off registration or for testing purposes.

xref:client-configuration:registration-bootstrap.adoc[]::
This is intended to be used for mass registration.


== For already registered clients

Software channels, system group membership, and formulas can be assigned to any already registered client.
This method makes use of the bootstrap script mentioned above.

.Procedure: Creating an Reactivation key

. In the {productname} {webui}, open the System Details page of any registered client you want to migrate to {sll}.

. Click the [guimenu]`Reactivation` tab.
  If there is already a key listed, you can use it.
  If not, click btn:[Generate New Key], and copy the entire key.
  The key will start with [literal]``re-``.

. SSH into this client and set the environment variable to be the key that you copied:
+
----
export REACTIVATION_KEY=re-xxxxxxxxxxxxxx
----

. Run the bootstrap script from xref:client-configuration:registration-bootstrap.adoc[], and the system will re-register using the same profile as before, but with the newly assigned {sll} context.

////
## Version testing status

| OS version  | Status  |
| ----------- | ------- |
| Rhel 9      | Working |
| Rocky 9     | Working |
| Alma 9      | Working |
| Oracle 9    | Working |
| Rhel 8      | Working |
| Rocky 8     | Working |
| Alma 8      | Working |
| Oracle 8    | Working |
| Rhel 7      | Not Tested |
| CentOS 7    | Working |
| Oracle 7    | Working |
////
