[[confidential_computing]]
= Confidential Computing
:revdate: 2025-07-17
:page-revdate: {revdate}

{CoCo} is a technology which allows protection of data in use by using hardware-based Trusted Execution Environment (TEE), the type of environments that provide increased level of security for data integrity, data confidentiality, and code integrity.


== {CoCo} with {productname}


The trustworthiness of the TEE is checked with the attestation process.
{productname} can be used as an attestation server for the systems registered to it.
It generates a report page for the systems which run in this mode.
These systems need to be attested and checked on regular base.
The history of the past checks is also stored and available per request.

{CoCo} Attestation depends on the used hardware and environment where the attested systems are running on.

[IMPORTANT]
====
{CoCo} Attestation is only available when {productname} is running on {x86_64} architecture.
====



== Requirements

{CoCo} can be set up in an environment with the following characteristics:

* Attested system (virtual machine) is bootstrapped to {productname} and runs on one of the following systems:
** {sle} 15 SP6
** {sle} 15 SP7
** {sle} 16
** {leap} 15 SP6
** {leap} 15 SP7
** {leap} 16

* Hardware must have one of the following CPUs:
** `AMD EPYC Milan`
** `AMD EPYC Genoa`
** `AMD EPYC Bergamo`
** `AMD EPYC Siena`
** `AMD EPYC Turin`
** `IBM z16`
** `IBM z17`
* BIOS must be configured to allow {CoCo} attestation
* Host OS and the virtualization software (KVM and libvirt) must support {CoCo}

* For information about required URLs when performing confidential computing attestation for IBM, see see xref:installation-and-upgrade:network-requirements.adoc#required-urls[Required URLs].

== Limitations

Secure boot is attested. 
However, currently KVM secure boot and AMD attestation tool `snpguest` are not working together. 


== Use {CoCo} in {productname}

[IMPORTANT]
====
For the exact steps for setting up and configuring {CoCo} on your host, refer to the OS Vendor documentation.
====

.Procedure: Enabling Attestation Container During the {productname} Installation
[role=procedure]
. The attestation container is enabled during the installation of {productname} with `mgradm install podman`.
. Add the following to file `mgradm.yaml`.
//I need full path to this file.
+
----
coco:
    replicas: 1
----


.Procedure: Enabling Attestation Container After the {productname} Installation
[role=procedure]
. To enable the attestation container after the installation, use the command line parameter `mgradm`.
. Run the command
+
----
mgradm scale uyuni-server-attestation --replicas 1
----
// (PLACEHOLDER): In the future instead of number 1, it should be possible to allow more then one container replica.


.Procedure: Disabling Attestation Container After the {productname} Installation
[role=procedure]
. To disable the already enabled attestation container, run the command:
+
----
mgradm scale uyuni-server-attestation --replicas 0
----


.Procedure: Enabling Attestation
[role=procedure]
. For the selected system, go to tab menu:Audit[Confidential Computing > Settings].
. Enable the attestation by selecting the toggle button.
. In the field `Environment Type` select the correct option from the drop-down list.
. If the field `Environment Type` is set to one of the `IBM z-series` CPU values, two more settings are required, `Host Key Document` and `Secure Execution Header`.

+

[NOTE]
====
`Host Key Document` is a public key certificate of the IBM hypervisor server instance where the attested system is going to run.

`Secure Execution Header` is a binary file needed to build the IBM secure VM image of the attested system.

Both files should be requested by the administrator creating the attested system VM running on the IBM hypervisor.
====

+

[IMPORTANT]
====
`Host Key Document` and `Secure Execution Header` are not security sensitive, therefore it is safe to store them on the {productname} server.
====

+

. Click button btn:[Save] to save the changes.

.Procedure: Scheduling New Attestation
[role=procedure]
. For the selected system, go to tab menu:Audit[Confidential Computing > List Attestations].
. Click btn:[Schedule Attestation].
  The new form opens.
. In the field `Earliest` select the time of running the attestation.
. If needed, add the newly created attestation to the action chain by selecting `Add to` option.
. Click button btn:[Schedule] to save and schedule the new attestation execution.

.Procedure: Viewing Attestation Reports from System Details
[role=procedure]
. For the selected system, go to tab menu:Audit[Confidential Computing > List Attestations].
. Find and select the report you want to view.
. After clicking the selected attestation report tab `Overview` will open.
.. If the selected CPU is `AMD` you will be shown additional tabs `SEV-SNP` and `Secure boot`.
.. If the selected CPU is `IBM` you will be shown additional tab `IBM SELPVATTEST`.


.Procedure: Viewing Attestation Reports from Audit
[role=procedure]
. From the navigation bar, select menu:Audit[Confidential Computing].
. The list of all attestations will be shown in the main panel.
+
. Find and select the report you want to view.



=== Report Statuses

Attestation reports can have one of the following statuses:

Pending::
This is the default status of the scheduled attestation.
The report is still not available, either because the process has not yet started or completed.

Successful::
When the scheduled attestation creates a report which can be viewed, the status of the process is `Successful`.

Failed::
When the scheduled fails and does not create a report as a result, the status of the process is `Failed`.



== Related Topics

For more information about {CoCo}, see https://www.fortanix.com/platform/confidential-computing-manager/what-is-confidential-computing[here].
