[[configure-autosync-channel]]
= Configure Automatic Channels Synchronization
:description: Configure Automatic Channels Synchronization explains how to check and change automatic synchronization settings for a channel so users can control
:revdate: 2026-10-07
:page-revdate: {revdate}

By default, channels are automatically synchronized with the upstream repositories to ensure that clients have access to the latest content and updates.
However, in some cases, you may want to disable this automatic synchronization for specific channels.

This chapter explains how to disable automatic synchronization for a channel.




[[get-channel-sync-satus]]
== Verify channel synchronization status using the API

To check if a channel is set to be automatically synchronized you can call an API.

To check the synchronization status of a channel using the API, use the following command.
Replace `<Channel_Label>` with the actual label of the channel you want to check

[source,console]
----
spacecmd api -- --args "<Channel_Label>" channel.software.isAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  true
]
----

The command will return `true` if automatic synchronization is enabled, or `false` if it is disabled.

This information is also available in the {webui}.
To check the synchronization status, navigate to the channel details page and look for the field `Automatic Repository Synchronization`.


[[automatic-channels-sync-status]]
== Verify automatic channels synchronization status

You can also generate anoverview table for all configured software channels at once.

This script logs in, queries the `channel.software.isAutoSync` status for each channel retrieved by `softwarechannel_list`, and formats the output into a table.

[source,console]
----
spacecmd -q login

printf "%-70s | %s\n" "CHANNEL" "AUTO-SYNC"
printf "%s\n" "----------------------------------------------------------------------+-----------"

for I in $(spacecmd -q softwarechannel_list) ; do
    STATUS=$(spacecmd -q api -- --args "$I" channel.software.isAutoSync | tr -d '[] \n\r')
    printf "%-70s | %s\n" "$I" "$STATUS"
done
----

[NOTE]
====
This loop will also print the synchronization status for Content Lifecycle Management (CLM) channels.
====


[[set-channel-sync-satus]]
== Set a channel to skip automatic synchronization

To enable or disable automatic synchronization for a channel, you can use the API call `channel.software.setAutoSync`.

Here is an example of how to set a channel to skip automatic synchronization using the API (replace `<Channel_Label>` with the actual label of the channel you want to update):

[source,console]
----
spacecmd api -- --args '["<Channel_Label>", false]' channel.software.setAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  false
]
----

To re-enable automatic synchronization, set the second parameter to `true`:

[source,console]
----
spacecmd api -- --args '["<Channel_Label>", true]' channel.software.setAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  true
]
----


[[manual-channel-sync]]
== Manually synchronize a channel

Even if you have disabled automatic synchronization for a channel, you can still manually synchronize it whenever needed.

[IMPORTANT]
====
Use `mgrctl term` before running steps inside the server container.
====

To manually synchronize a channel, you can use the command(replace `<Channel_Label>` with the actual label of the channel you want to synchronize):

[source,console]
----
spacewalk-repo-sync -c <Channel_Label>
----
