[[ansible-integration]]
= Ansible 통합
:description: SUSE Multi-Linux Managers의 지원 기능을 사용하여 인벤토리 검사, 검색 및 실행을 위한 Ansible 제어 노드를 구성합니다.
:revdate: 2025-03-07
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

Ansible은 컴퓨터 클라이언트 시스템을 관리하는 도구입니다.
자세한 내용은 https://www.ansible.com.을 참조하십시오.

{productname}은 Ansible 제어 노드를 관리하는 것을 지원합니다.
자세한 내용은 xref:administration:ansible-setup-control-node.adoc#at.ansible.overview[]을 참조하십시오.

Ansible Control Node의 지원 버전은 Ansible 11.3입니다.
운영 체제 공급자의 공식 저장소에서 얻어야 합니다.
예를 들어, {sle} 15 SP6 및 SP7에서는 Ansible이 `Systems Management Module.`를 통해 제공됩니다. +
{sle} 이외의 운영 체제를 실행하는 제어 노드의 경우, 해당 배포판과 함께 제공되는 Ansible을 사용하십시오.

Ansible 소프트웨어는 {productname} 프록시 및 {productname} {smr} 브랜치 서버에서도 사용할 수 있습니다.



[[at.ansible.overview]]
== 기능 개요


{productname}은 시스템 관리자가 Ansible 제어 노드를 운영할 수 있도록 합니다.
지원되는 기능은 다음과 같습니다.

* 인벤토리 파일 검사
* 플레이북 검색
* 플레이북 실행

자세한 내용은 다음을 참조하십시오.

* 인벤토리는 관리되는 Ansible 노드의 정렬된 목록입니다.  인벤토리를 구성하는 방법에 대한 자세한 내용은 https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html.을 참조하십시오.
* 플레이북은 인벤토리를 관리하는 방법을 설명하는 방법입니다.  플레이북에 대한 자세한 내용은 https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html.을 참조하십시오.



[[at.ansible.requirements]]
== 요구사항 및 기본 구성

Ansible 기능을 사용하려면 이미 존재하는 Ansible 제어 노드를 {productname} 서버에 등록해야 합니다.
{webui}의 등록된 시스템 menu:시스템 세부 사항[속성] 페이지에서 `Ansible Control Node` 목록의 `Add-on System Types` 시스템 유형을 활성화해야 합니다.

// FIXME: check it!
`Ansible Control Node` 시스템 유형을 활성화하면 highstate에 추가되어 `ansible` 패키지가 시스템에 설치되고, menu:시스템 세부 사항[Ansible] 탭에서 Ansible 기능이 활성화됩니다.

다음 단계로, menu:시스템 세부 사항[Ansible > 제어 노드] 페이지에서 Ansible 플레이북 디렉토리 및 인벤토리 파일의 경로를 구성합니다.
인벤토리 경로로 표준 Ansible 인벤토리 경로 `/etc/ansible/hosts`를 사용할 수 있습니다.
플레이북 디렉토리로서, 플레이북 파일이 저장된 제어 노드의 모든 디렉토리를 사용할 수 있습니다.
플레이북 디렉토리는 `.yml` 파일 또는 `.yml` 파일이 있는 하위 디렉토리를 포함합니다.

Ansible 제어 노드를 설치하고 설정하려면 xref:administration:ansible-setup-control-node.adoc[]을 참조하십시오.



[[at.ansible.inventory-inspection]]
== 인벤토리 검사

인벤토리 경로를 정의한 후에는 {productname}를 사용하여 내용을 검사할 수 있습니다.

.절차 {webui}에서 인벤토리를 검사합니다.
. {productname} {webui}에서 menu:시스템 세부 사항[Ansible > 인벤토리]로 이동합니다.
. 인벤토리 경로를 클릭하면 제어 노드에서 실시간으로 인벤토리 검사를 실행할 수 있습니다.



[[at.ansible.playbook-discovery]]
== 플레이북 검색

플레이북 디렉토리를 정의한 후에는 menu:시스템 세부 사항[Ansible > 플레이북] 페이지에서 플레이북을 검색할 수 있습니다.

인벤토리 검사와 마찬가지로 플레이북 검색 작업은 제어 노드에서 실시간으로 실행됩니다.



[[at.ansible.playbook-execution]]
== 플레이북 실행

menu:시스템 세부 사항[Ansible > 플레이북] 페이지에서 플레이북 실행을 예약할 수 있습니다.
실행하려는 플레이북을 선택한 후 `Inventory Path` 대화 상자의 `Schedule Playbook Execution` 드롭다운 메뉴에서 실행을 위한 인벤토리 파일을 선택할 수 있습니다.
항목을 선택하지 않으면, 제어 노드에 구성된 기본 인벤토리가 사용됩니다.
드롭다운 메뉴는 인벤토리 경로에 정의한 인벤토리와 플레이북 디렉토리에서 로컬로 발견된 인벤토리로 채워집니다.
이 항목들은 플레이북 세부 사항에 `Custom Inventory` 항목으로 표시됩니다.
임의의 인벤토리 경로를 입력할 수도 있습니다.

이전에 정의된 변수를 재정의하기 위해 플레이북 실행에 변수를 전달할 수도 있습니다. 
변수를 전달하려면 [guimenu]``플레이북 콘텐츠`` 섹션을 찾아 btn:[변수 편집]을 클릭하십시오.
[guimenu]``변수 편집`` 대화 상자에서 변수를 목록, 사전, 문자열 또는 부울로 추가하거나 편집할 수 있습니다.
또는 btn:[YAML 편집]을 클릭하여 YAML로 변수를 직접 편집할 수 있습니다. btn:[저장]을 클릭하여 플레이북 콘텐츠에 변수를 적용하십시오.

그 후, 플레이북 실행 시간을 선택하거나 작업 체인을 선택합니다.
결국, {productname}은 제어 노드에서 작업으로서 플레이북을 실행합니다.
작업 세부 사항 페이지에서 작업 결과를 확인할 수 있습니다.
