[[channel-management]]
= 채널 관리
:description: SUSE Multi-Linux Manager에서 소프트웨어 채널을 구성하고 관리하는 방법을 배우고, 패키지를 기본 채널과 하위 채널로 그룹화하고 클라이언트를 기본 채널에 할당합니다.
:revdate: 2025-02-28
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

채널은 소프트웨어 패키지를 그룹화하는 방법입니다.

{productname}에서 채널은 기본 채널과 하위 채널로 그룹화되며, 기본 채널은 운영 체제 유형, 버전 및 아키텍처에 따라 그룹화되고, 하위 채널은 관련 기본 채널과 호환됩니다.
클라이언트가 기본 채널에 할당되면 해당 시스템은 관련 하위 채널을 설치할 수 있습니다.
이와 같은 방식으로 채널을 구성하면 각 시스템에 호환되는 패키지만 설치됩니다.

소프트웨어 채널은 패키지를 제공하기 위해 리포지토리를 사용합니다.
채널은 {productname}의 리포지토리를 미러링하며, 패키지 이름 및 기타 데이터는 {productname} 데이터베이스에 저장됩니다.
채널에 연결된 리포지토리는 아무 개수나 가질 수 있습니다.
그 리포지토리의 소프트웨어는 클라이언트를 적절한 채널에 구독시킴으로써 설치할 수 있습니다.

클라이언트는 기본 채널에만 할당될 수 있습니다.
그런 다음 클라이언트는 해당 기본 채널 및 그 하위 채널과 연결된 리포지토리에서 패키지를 설치하거나 업데이트할 수 있습니다.

{productname}은 {productname}를 실행하는 데 필요한 모든 것을 제공하는 여러 공급업체 채널을 제공합니다.
{productname} 관리자 및 채널 관리자는 채널 관리 권한을 가지고 있어, 자신만의 사용자 정의 채널을 생성하고 관리할 수 있는 능력을 부여받습니다.
환경에서 자신의 패키지를 사용하려면 사용자 정의 채널을 생성할 수 있습니다.
사용자 정의 채널은 기본 채널로 사용할 수 있으며, 공급업체 기본 채널과 연결할 수도 있습니다.

사용자 정의 채널 생성에 대한 자세한 내용은 xref:administration:custom-channels.adoc[]을 참조하십시오.



== 채널 관리


기본적으로 모든 사용자는 시스템에 채널을 구독할 수 있습니다.
{webui}을 사용하여 채널에 대한 제한을 구현할 수 있습니다.

.절차 채널에 대한 구독자 액세스 제한
. {productname} {webui}에서 menu:소프트웨어[채널 목록]으로 이동하여 편집할 채널을 선택합니다.
. `Per-User Subscription Restrictions` 섹션을 찾아서 `Only selected users within your organization may subscribe to this channel`을(를) 확인하세요.
  btn:[업데이트]를 클릭하여 변경 사항을 저장합니다.
. `Subscribers` 탭으로 이동하여 필요에 따라 사용자를 선택하거나 선택을 해제하세요.



[[delete_channels]]
== 채널 삭제

명령 프롬프트에서 벤더 소프트웨어 채널을 삭제할 수 있습니다.

.절차 공급업체 채널 삭제
. {productname} 서버의 명령 프롬프트에서 루트 사용자로, 사용 가능한 공급업체 채널을 나열하고 삭제할 채널을 기록합니다:
+
----
mgr-sync list channels
----
. 채널을 삭제합니다.
+
----
spacewalk-remove-channel -c <channel-name>
----

ifeval::[{mlm-content} == true]
* 채널을 수동으로 삭제하는 방법에 대한 자세한 내용은 xref:administration:removing-channels.adoc[]을 참조하십시오.
endif::[]

* 사용자 정의 채널을 삭제하는 방법에 대한 정보는 xref:administration:custom-channels.adoc[]을 참조하십시오.
