[[content-staging]]
= 컨텐트 스테이징
:description: 조직 전체에서 salt.content.staging.advance 및 salt.content.staging.window와 같은 매개변수를 구성하여 콘텐츠 스테이징을 관리하십시오.
:revdate: 2025-01-13
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


스테이징은 클라이언트가 설치되기 전에 패키지를 미리 다운로드하는 데 사용됩니다.
이렇게 하면 패키지 설치가 예약되자마자 시작될 수 있어 유지 관리 창에 필요한 시간을 줄일 수 있습니다.


== 컨텐트 스테이징 활성화


조직 전체에서 콘텐츠 스테이징을 관리할 수 있습니다.
{productname} {webui}에서 menu:관리자[조직]으로 이동하여 사용 가능한 조직 목록을 확인합니다.
조직 이름을 클릭하고 `Enable Staging Contents` 상자를 체크하여 이 조직의 클라이언트가 패키지 데이터를 스테이징할 수 있도록 허용하십시오.

[NOTE]
====
조직을 만들고 관리하려면 {productname} 관리자로 로그인해야 합니다.
====

명령 프롬프트에서 `/etc/sysconfig/rhn/up2date`를 편집하고 다음 행을 추가 또는 편집하여 스테이징을 활성화할 수도 있습니다:

----
stagingContent=1
stagingContentWindow=24
----


`stagingContentWindow` 매개변수는 시간으로 표현된 값이며 다운로드 시작 시간을 결정합니다.
이는 예약된 설치 또는 업데이트 시간 이전의 시간 수입니다.
이 예에서 콘텐츠는 설치 시간 24시간 전에 다운로드됩니다.
다운로드 시작 시간은 시스템에 대한 선택된 연락 방법에 따라 다릅니다.

다음 번에 작업이 예약되면 패키지가 자동으로 다운로드되지만 설치되지는 않습니다.
예약된 시간에 스테이징된 패키지가 설치됩니다.



== 컨텐트 스테이징 구성

컨텐트 스테이징을 구성하는 데 사용되는 파라미터 두 개:

* `salt_content_staging_advance`은 콘텐츠 스테이징 창이 열리기 전의 여유 시간(시간 단위)입니다.
    패키지를 다운로드할 수 있는 설치 시작 전 시간입니다.
* `salt_content_staging_window`은(는) 콘텐츠 스테이징 창의 지속 시간(시간 단위)입니다.
    클라이언트가 설치를 시작하기 전에 패키지를 준비하는 데 드는 시간입니다.

예를 들어, `salt_content_staging_advance`이(가) 6시간으로 설정되고 `salt_content_staging_window`가 2시간으로 설정된 경우, 스테이징 창은 설치 시간 6시간 전에 열리고 2시간 동안 유지됩니다.
설치가 시작될 때까지 남은 4시간 동안은 패키지가 다운로드되지 않습니다.

`salt_content_staging_advance`과(와) `salt_content_staging_window`에 동일한 값을 설정하면, 설치가 시작될 때까지 패키지를 다운로드할 수 있습니다.

`/usr/share/rhn/config-defaults/rhn_java.conf`에서 콘텐츠 스테이징 매개변수를 구성하십시오.

다음은 기본값입니다.

* `salt_content_staging_advance: 8 hours`
* `salt_content_staging_window: 8 hours`


[NOTE]
====
이러한 파라미터가 올바르게 작동하려면 컨텐트 스테이징을 활성화해야 합니다.
====
