[[content-lifecycle-examples]]
= 컨텐트 라이프싸이클 관리 예제
:description: 콘텐츠 라이프사이클 관리 예제를 사용하여 패치 사이클 구현에 대한 개인화된 접근 방식을 구축하는 방법을 배우십시오.
:revdate: 2025-01-30
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

이 섹션에는 콘텐츠 라이프사이클 관리를 사용하는 몇 가지 일반적인 예가 포함되어 있습니다.
이 예제를 사용하여 자신만의 개인화된 구현을 구축하십시오.



[#create-proj-for-patch-cycle]
== 월간 패치 주기에 대한 프로젝트 생성

월간 패치 주기에 대한 예제 프로젝트는 다음으로 구성됩니다.

* `By Date` 필터 생성
* 프로젝트에 필터 추가
* 새 프로젝트 빌드에 필터 적용
* 프로젝트에서 패치 제외
* 프로젝트에 패치 포함



[#create-a-filter]
=== `By Date` 필터 생성

`By Date` 필터는 지정된 날짜 이후에 릴리스된 모든 패치를 제외합니다.
이 필터는 월별 패치 주기를 따르는 콘텐츠 라이프사이클 프로젝트에 유용합니다.


.절차 `By Date` 필터 생성
[role=procedure]
____
. {productname} {webui}에서 menu:콘텐츠 라이프사이클[필터]로 이동하여 btn:[필터 생성]을 클릭합니다.

. `Filter Name` 필드에 필터 이름을 입력합니다.
    예를 들어, `Exclude patches by date`.

. `Filter Type` 필드에서 `Patch (Issue date)`을(를) 선택합니다.

. `Matcher` 필드에서 `later or equal`이(가) 자동으로 선택됩니다.

. 날짜 및 시간을 선택합니다.

. btn:[저장]을 클릭합니다.

____


[#add-filter-to-proj]
=== 프로젝트에 필터 추가

.절차 프로젝트에 필터 추가
[role=procedure]
____
. {productname} {webui}에서 menu:콘텐츠 라이프사이클[프로젝트]로 이동하여 목록에서 프로젝트를 선택합니다.

. 사용 가능한 모든 필터를 보려면 btn:[필터 연결/해제] 링크를 클릭합니다.

. 새 `Exclude patches by date` 필터를 선택합니다.

. btn:[저장]을 클릭합니다.
____



[#apply-filter-to-project-build]
=== 새 프로젝트 빌드에 필터 적용

새 필터가 필터 목록에 추가되지만, 여전히 프로젝트에 적용해야 합니다.
필터를 적용하려면 첫 번째 환경을 구축해야 합니다.

.절차 필터 사용
[role=procedure]
____
. btn:[빌드]를 클릭하여 첫 번째 환경을 빌드합니다.

. 선택 사항: 메시지를 추가합니다.
    메시지를 사용하여 빌드 기록을 추적할 수 있습니다.

. 테스트 서버에서 새 채널을 사용하여 필터가 올바르게 작동했는지 확인합니다.

. btn:[승격]을 클릭하여 콘텐츠를 다음 환경으로 이동합니다.
    필터 수가 많거나 매우 복잡한 경우 빌드 시간이 더 오래 걸립니다.

____


[#exclude-a-patch]
=== 프로젝트에서 패치 제외

테스트는 문제를 발견하는 데 도움이 될 수 있습니다.
문제가 발견되면 `by date` 필터 이전에 릴리스된 문제 패치를 제외합니다.

.절차 패치 제외하기
[role=procedure]
____
. {productname} {webui}에서 menu:콘텐츠 라이프사이클[필터]로 이동하여 btn:[필터 생성]을 클릭합니다.

. `Filter Name` 필드에 필터 이름을 입력합니다.
    예를 들어, `Exclude openjdk patch`.

. `Filter Type` 필드에서 `Patch (Advisory Name)`을(를) 선택합니다.

. `Matcher` 필드에서 `equals`을(를) 선택합니다.

. `Advisory Name` 필드에 권고 이름을 입력합니다.
    예를 들어, `SUSE-15-2019-1807`.

. btn:[저장]을 클릭합니다.

. menu:콘텐츠 라이프사이클[프로젝트]로 이동하여 프로젝트를 선택합니다.

. btn:[필터 연결/해제] 링크를 클릭하고 `Exclude openjdk patch`을(를) 선택한 다음 btn:[저장]을(를) 클릭합니다.

____

btn:[빌드] 버튼으로 프로젝트를 다시 빌드하면 이전에 추가한 `by date` 필터와 함께 새 필터가 사용됩니다.



[#include-a-patch]
=== 프로젝트에 패치 포함

이 예제에서는 보안 경고를 받았습니다.
중요한 보안 패치가 현재 작업 중인 월의 첫 번째 날 이후 며칠 후에 릴리스되었습니다.
새 패치의 이름은 `SUSE-15-2019-2071`입니다.
이 새 패치를 환경에 포함해야 합니다.

[IMPORTANT]
====
`Allow` 필터 규칙은 `Deny` 필터 규칙의 제외 기능을 재정의합니다.
자세한 내용은 xref:administration:content-lifecycle.adoc[]을 참조하십시오.
====

.절차 프로젝트에 패치 포함
[role=procedure]
____
. {productname} {webui}에서 menu:콘텐츠 라이프사이클[필터]로 이동하여 btn:[필터 생성]을 클릭합니다.

. `Filter Name` 필드에 필터 이름을 입력합니다.
    예를 들어, `Include kernel security fix`.

. `Filter Type` 필드에서 `Patch (Advisory Name)`을(를) 선택합니다.

. `Matcher` 필드에서 `equals`을(를) 선택합니다.

. `Advisory Name` 필드에 `SUSE-15-2019-2071`을(를) 입력하고 `Allow`을(를) 선택합니다.

. btn:[저장]을 클릭하여 필터를 저장합니다.

. menu:콘텐츠 라이프사이클[프로젝트]로 이동하고 목록에서 프로젝트를 선택합니다.

. btn:[필터 연결/해제]를 클릭하고 `Include kernel security patch`을(를) 선택합니다.

. btn:[저장]을 클릭합니다.

. btn:[빌드]를 클릭하여 환경을 다시 빌드합니다.

____


[#update-a-patch-cycle]
== 기존 월간 패치 주기 업데이트

월간 패치 주기가 완료되면 다음 달의 패치 주기를 업데이트할 수 있습니다.

.절차 월간 패치 주기 업데이트하기
[role=procedure]
____
. `by date` 필드에서 필터 날짜를 다음 달로 변경합니다.
    또는 새 필터를 생성하고 프로젝트에 대한 할당을 변경합니다.

. `SUSE-15-2019-1807`에 대한 제외 필터를 프로젝트에서 연결 해제할 수 있는지 확인합니다.
    이 문제를 해결하기 위해 사용할 수 있는 새 패치가 있을 수 있습니다.

. 이전에 추가한 `allow` 필터의 연결을 해제합니다.
    패치는 기본적으로 포함되어 있습니다.

. 프로젝트를 다시 빌드하여 다음 달에 대한 패치가 포함된 새 환경을 생성합니다.

____


[#enhance-project-with-livepatching]
== 라이브 패치로 프로젝트 향상

이 섹션에서는 라이브 패치를 위한 환경을 생성하기 위한 필터 설정에 대해 설명합니다.

[IMPORTANT]
====
라이브 패치 사용을 준비할 때 고려해야 하는 몇 가지 중요한 사항이 있습니다.

* 시스템에서 하나의 커널 버전만 사용해야 합니다.
    라이브 패치 패키지는 특정 커널과 함께 설치됩니다.
* 라이브 패치 업데이트는 단일 패치로 제공됩니다.
* 새로운 라이브 패치 커널 시리즈를 시작하는 각 커널 패치에는 `required reboot` 플래그가 표시됩니다.
    이 커널 패치는 라이브 패치 도구와 함께 제공됩니다.
    설치한 후에는 다음 해 이전에 시스템을 최소한 한 번 재부팅해야 합니다.
* 설치된 커널 버전과 일치하는 라이브 패치 업데이트만 설치해야 합니다.
* 라이브 패치는 독립 실행형 패치로 제공됩니다.
    현재 설치된 커널 버전보다 높은 커널 버전이 포함된 모든 일반 커널 패치는 제외되어야 합니다.
====



[#exclude-higher-kernel-version]
=== 상위 커널 버전 패키지 제외

이 예제에서는 `SUSE-15-2019-1244` 패치로 시스템을 업데이트합니다.
이 패치에는 `kernel-default-4.12.14-150.17.1-x86_64`이(가) 포함되어 있습니다.

`kernel-default` 및 `kernel-default-base`의 상위 버전이 포함된 모든 패치를 제외해야 합니다.

.절차 상위 커널 버전 패키지 제외
[role=procedure]
____
. {productname} {webui}에서 menu:콘텐츠 라이프사이클[필터]로 이동한 후 btn:[필터 생성]을 클릭합니다.

. `Filter Name` 필드에 필터 이름을 입력합니다.
    예를 들어, `Exclude kernel greater than 4.12.14-150.17.1`.

. `Filter Type` 필드에서 `Patch (Contains Package)`을(를) 선택합니다.

. `Matcher` 필드에서 `version greater than`을(를) 선택합니다.

. `Package Name` 필드에 `kernel-default`을(를) 입력합니다.

. `Epoch` 필드를 비워 둡니다.

. `Version` 필드에 `4.12.14`을(를) 입력합니다.

. `Release` 필드에 `150.17.1`을(를) 입력합니다.

. btn:[저장]을 클릭하여 필터를 저장합니다.

. menu:콘텐츠 라이프사이클[프로젝트]로 이동하여 프로젝트를 선택합니다.

. btn:[필터 연결/해제]를 클릭합니다.

. `Exclude kernel greater than 4.12.14-150.17.1`을(를) 선택하고 btn:[저장]을(를) 클릭합니다.

____

`kernel-default-base` 패키지에 대해 이 절차를 반복해야 합니다.


btn:[빌드]를 클릭하면 새로운 환경이 생성됩니다.
새로운 환경은 설치한 버전까지의 모든 커널 패치를 포함합니다.

[NOTE]
====
더 높은 커널 버전의 모든 커널 패치는 제거됩니다.
라이브 패치 커널은 시리즈의 첫 번째가 아닌 한 계속 사용할 수 있습니다.
====

이 절차는 필터 템플릿을 사용하여 자동화할 수 있습니다.
라이브 패치 필터 템플릿을 적용하는 방법에 대한 자세한 내용은 xref:administration:content-lifecycle.adoc#filter-templates[]을 참조하십시오.



[#switch-kernel-version-for-live-patching]
== 라이브 패치를 위한 새 커널 버전으로 전환

특정 커널 버전에 대한 라이브 패치는 1년 동안만 가능합니다.
1년 후에는 시스템의 커널을 업데이트해야 합니다.
다음 환경 변경을 실행하십시오:

.절차 새 커널 버전으로 전환
[role=procedure]
____
. 업그레이드할 커널 버전을 결정합니다.
    예: `4.12.14-150.32.1`

. 새 커널 버전 필터를 생성합니다.

. 기존 커널과 연결된 모든 이전 라이브 패칭 필터를 분리합니다.

. 새 커널 버전 필터를 연결합니다.

. btn:[빌드]를 클릭하여 환경을 다시 빌드합니다.

+

[IMPORTANT]
====
빌드가 완료되면 즉시 해당 필터 2개를 다시 연결해야 합니다. 이러한 필터들은 다음과 같습니다.

* `reboot_suggested` 키워드가 포함된 패치를 거부합니다.

* `installhint(reboot-needed)` 이름을 제공하는 패키지가 포함된 패치를 거부합니다.
====

____

새 환경에는 선택한 새 커널 버전까지의 모든 커널 패치가 포함되어 있습니다.
업그레이드를 수행한 후 시스템을 재부팅해야 합니다.
새 커널은 1년 동안 유효합니다.
1년 동안 설치된 모든 패키지는 현재 라이브 패치 커널 필터와 일치합니다.



[#appstream-filters]
== AppStream 필터

콘텐츠 라이프사이클 관리 프로젝트에서 AppStream 필터를 사용하여 모듈 리포지토리를 일반 리포지토리로 변환할 수 있습니다.
이는 리포지토리의 패키지를 유지하고 모듈 메타데이터를 제거함으로써 수행됩니다.
결과 리포지토리는 일반 리포지토리와 동일한 방식으로 {productname}에서 사용할 수 있습니다.

[NOTE]
====

ifeval::[{uyuni-content} == true]
AppStream 리포지토리는 {webui} 전체에서 기본적으로 지원됩니다.
endif::[]

ifeval::[{suma-content} == true]
{productname} 5.0부터 AppStream 리포지토리는 {webui} 전체에서 기본적으로 지원됩니다.
endif::[]

그러므로 이 프로세스는 AppStream 리포지토리 작업에서 반드시 필요한 프로세스가 아닙니다.
====

AppStream 필터는 대상 리포지토리에 포함될 단일 모듈 스트림을 선택합니다.
여러 모듈 스트림을 선택하기 위해 여러 필터를 추가할 수 있습니다.

CLM 프로젝트에서 AppStream 필터를 사용하지 않으면 모듈 소스의 모듈 메타데이터가 그대로 유지되며, 대상 리포지토리는 동일한 모듈 메타데이터를 포함합니다.
CLM 프로젝트에서 최소한 하나의 AppStream 필터가 활성화되어 있는 한, 모든 대상 리포지토리는 일반 리포지토리로 변환됩니다.

경우에 따라 모듈의 패키지를 포함하지 않고 일반 리포지토리를 구축하고 싶을 수 있습니다.
이렇게 하려면 AppStream 필터에 matcher(`none (disable modularity)`)를 추가하십시오.
이렇게 하면 대상 리포지토리의 모든 모듈이 비활성화됩니다.
이는 특히 {rhel}{nbsp}9 클라이언트에 유용하며, 대부분의 모듈의 기본 버전이 이미 AppStream 리포지토리에 일반 패키지로 포함되어 있습니다.

AppStream 필터를 사용하려면 `{rhel} AppStreams`와 같은 모듈형 리포지토리가 있는 CLM 프로젝트가 필요합니다.
시작하기 전에 필요한 모듈을 소스로 포함했는지 확인하십시오.


.절차 AppStream 필터 사용하기
[role=procedure]
____
. {productname} {webui}에서 {rhel}{nbsp}8 또는 9 CLM 프로젝트로 이동합니다.
    프로젝트에 AppStream 채널을 포함했는지 확인합니다.

. btn:[필터 생성]를 클릭하고 다음 파라미터를 사용합니다:

+

* `Filter Name` 필드에 새 필터의 이름을 입력합니다.

* `Filter Type` 필드에서 `Module (Stream)`을(를) 선택합니다.

* `Matcher` 필드에서 `equals`을(를) 선택합니다.

* `Module Name` 필드에 모듈 이름을 입력합니다.
    예를 들어, `postgresql`.

* `Stream` 필드에 원하는 스트림의 이름을 입력합니다.
    예를 들어, `10`.
    이 필드를 비워 두면 모듈의 기본 스트림이 선택됩니다.

. 새 필터를 생성하려면 btn:[저장]을 클릭합니다.

. menu:콘텐츠 라이프사이클[프로젝트]로 이동하여 프로젝트를 선택합니다.

. btn:[필터 연결/해제]를 클릭하고 새 AppStream 필터를 선택한 후 btn:[저장]을 클릭합니다.

____

`Create/Edit Filter` 양식의 찾아보기 기능을 사용하여 모듈형 채널을 위해 사용할 수 있는 모듈 스트림 목록에서 모듈을 선택할 수 있습니다.


.절차 사용 가능한 모듈 스트림 찾아보기
[role=procedure]
____
. {productname} {webui}에서 {rhel}{nbsp}8 또는 9 CLM 프로젝트로 이동합니다.
    프로젝트에 AppStream 채널을 포함했는지 확인합니다.

. btn:[필터 생성]를 클릭하고 다음 파라미터를 사용합니다:

+

* `Filter Name` 필드에 새 필터의 이름을 입력합니다.

* `Filter Type` 필드에서 `Module (Stream)`을(를) 선택합니다.

* `Matcher` 필드에서 `equals`을(를) 선택합니다.

. 모든 모듈형 채널을 보려면 `Browse available modules`을(를) 클릭합니다.

. 모듈 및 스트림을 탐색할 채널을 선택합니다.

+

* `Module Name` 필드에서 검색할 모듈 이름을 입력하거나 목록에서 선택합니다.

* `Stream` 필드에서 검색할 스트림 이름을 입력하거나 목록에서 선택합니다.

____

[NOTE]
====
채널 선택은 모듈을 탐색하는 용도만을 위한 것입니다.
선택한 채널은 필터와 함께 저장되지 않으며, CLM 프로세스에 어떠한 방식으로도 영향을 미치지 않습니다.
====

대상 리포지토리에 포함될 다른 모듈 스트림에 대한 추가 AppStream 필터를 생성할 수 있습니다.
선택한 스트림에 의존하는 모든 모듈 스트림은 자동으로 포함됩니다.

[NOTE]
====
상충되거나 호환되지 않거나 누락된 모듈 스트림을 지정하지 않도록 주의하십시오.
예를 들어, 동일한 모듈에서 두 개의 스트림을 선택하는 것은 유효하지 않습니다.
====

.절차 모듈성 비활성화
[role=procedure]
____
. {productname} {webui}에서 {rhel}{nbsp}8 또는 9 CLM 프로젝트로 이동합니다.
    프로젝트에 AppStream 채널을 포함했는지 확인합니다.

. btn:[필터 생성]를 클릭하고 다음 파라미터를 사용합니다:

+

* `Filter Name` 필드에 새 필터의 이름을 입력합니다.

* `Filter Type` 필드에서 `Module (Stream)`을(를) 선택합니다.

* `Matcher` 필드에서 `none (disable modularity)`을(를) 선택합니다.

. 새 필터를 생성하려면 btn:[저장]을 클릭합니다.

. menu:콘텐츠 라이프사이클[프로젝트]로 이동하여 프로젝트를 선택합니다.

. btn:[필터 연결/해제]를 클릭하고 새 AppStream 필터를 선택한 후 btn:[저장]을 클릭합니다.

____

이 작업을 수행하면 대상 리포지토리에서 모듈 메타데이터가 효과적으로 제거됩니다. 단, 모듈에 속한 패키지는 제외입니다.

btn:[빌드] 버튼을 사용하여 {webui}에서 CLM 프로젝트를 빌드할 때, 대상 리포지토리는 선택한 모듈 스트림의 패키지를 포함하는 모듈이 없는 일반 리포지토리입니다.

[NOTE]
====
{rhel}{nbsp}8 프로젝트에서 모듈성을 완전히 비활성화하면 {rhel}{nbsp}8에서 정상적인 작동을 위해 일부 모듈이 필수적이므로 잘못된 환경이 구성될 수 있습니다.
====
