[[infra-maintenance]]
= 인프라 유지보수 작업
:description: SUSE Multi-Linux Manager 인프라를 최신 업데이트, 서비스 팩 및 패키지로 최신 상태로 유지하십시오.
:revdate: 2025-05-27
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

예정된 작동 중지 시간 기간이 있는 경우, {productname} 서버의 중요한 작동 중지 시간 전에, 도중에 및 후에 해야 할 모든 일을 기억하기 어려울 수 있습니다.
{productname} Inter-Server Synchronization Slave Servers 또는 {productname} 프록시와 같은 서버 관련 시스템도 영향을 받으며 고려해야 합니다.

{suse}은 항상 {productname} 인프라를 업데이트 상태로 유지할 것을 권장합니다.
여기에는 서버, 프록시 및 빌드 호스트가 포함됩니다.
{productname} 서버를 업데이트하지 않으면 필요할 때 환경의 일부를 업데이트하지 못할 수 있습니다.

이 섹션에는 각 단계를 수행하는 추가 정보 링크와 작동 중지 시간 기간에 실행하는 검사 목록이 포함되어 있습니다.



== 서버


.절차 서버 점검
[role=procedure]
____
. 최신 업데이트를 적용합니다.

. 필요한 경우, 최신 서비스 팩으로 업그레이드합니다.

. `podman ps`를 실행하고 필요한 모든 서비스가 실행 중인지 확인하십시오.
____

{sles} {bci-mlm}에서 패키지 관리자를 사용하여 업데이트를 설치할 수 있습니다:

* {yast} 사용에 대한 정보는 {sles-base-os-documentation}/cha-onlineupdate-you.html을 참조하십시오.
* zypper 사용에 대한 정보는 {sles-base-os-documentation}/cha-sw-cl.html#sec-zypper을 참조하십시오.

{sl-micro} {microversion}에서 `transactional-update` 명령을 사용하여 업데이트를 설치할 수 있습니다.
`transactional-update` 사용에 대한 자세한 내용은 https://documentation.suse.com/sle-micro/6.1/html/Micro-transactional-updates/transactional-updates.html.를 참조하십시오.


기본적으로 여러 업데이트 채널이 {productname} 서버에 대해 구성되고 활성화되어 있습니다.
새로운 패키지와 업데이트된 패키지가 자동으로 제공됩니다.


ifeval::[{mlm-content} == true]

{susemgr}을 최신 상태로 유지하려면 {scclongform}에 직접 연결하거나 {rmtool} (RMT)를 사용하십시오.
RMT를 사용하여 연결되지 않은 환경의 로컬 설치 소스로 사용할 수 있습니다.

endif::[]


ifeval::[{mlm-content} == true]

시스템에서 업데이트 채널을 사용할 수 있는지 확인할 수 있는 명령은 다음과 같습니다.

----
zypper lr
----

다음과 유사한 형태로 출력됩니다.

----
Name                                                   | Enabled | GPG Check | Refresh
-------------------------------------------------------+---------+-----------+--------
SLE-Module-Basesystem15-SP7-Pool                       | Yes     | (r ) Yes  | No
SLE-Module-Basesystem15-SP7-Updates                    | Yes     | (r ) Yes  | Yes
SLE-Module-Containers15-SP7-Pool                       | Yes     | (r ) Yes  | No
SLE-Module-Containers15-SP7-Updates                    | Yes     | (r ) Yes  | Yes
SLE-Module-Python3-15-SP7-Pool                         | Yes     | (r ) Yes  | No
SLE-Module-Python3-15-SP7-Updates                      | Yes     | (r ) Yes  | Yes
SLE-Product-SLES15-SP7-Pool                            | Yes     | (r ) Yes  | No
SLE-Product-SLES15-SP7-Updates                         | Yes     | (r ) Yes  | Yes
SUSE-Multi-Linux-Manager-Server-SLE-5.1-Pool           | Yes     | (r ) Yes  | No
SUSE-Multi-Linux-Manager-Server-SLE-5.1-Updates        | Yes     | (r ) Yes  | Yes
SLE-Module-Server-Applications15-SP7-Pool              | Yes     | (r ) Yes  | No
SLE-Module-Server-Applications15-SP7-Updates           | Yes     | (r ) Yes  | Yes
SLE-Module-Systems-Management-15-SP7-Pool              | Yes     | (r ) Yes  | No
SLE-Module-Systems-Management-15-SP7-Updates           | Yes     | (r ) Yes  | Yes
----

endif::[]


ifeval::[{mlm-content} == true]

{productname}은 최신 패키지를 제공하기 위해 유지 관리 업데이트(MU)를 릴리스합니다.
유지 관리 업데이트는 새로운 버전 번호로 표시됩니다.
예를 들어, 주요 릴리스 5.1은 MU가 릴리스될 때 5.1.1로 증가합니다.

현재 실행 중인 버전은 {webui}의 탐색 바 하단에서 확인할 수 있습니다.
또한 `api.getVersion()` XMLRPC API 호출로 버전 번호를 가져올 수 있습니다.

endif::[]



=== 클라이언트 도구

서버가 업데이트되면 클라이언트의 일부 도구도 업데이트하는 것을 고려하십시오.
클라이언트에서 `venv-salt-minion`, `zypper` 및 기타 관련 관리 패키지를 업데이트하는 일은 엄격히 요구되지는 않지만, 일반적으로 권장되는 모범 사례입니다.
예를 들어, 서버의 유지 관리 업데이트는 주요 새로운 Salt 버전을 도입할 수 있습니다.
그런 다음 Salt 클라이언트는 계속 작동하지만 나중에 문제가 발생할 수 있습니다.
이를 피하기 위해 {suse}는 `venv-salt-minion`가 항상 안전하게 업데이트되도록 합니다.



== 서버 간 동기화 슬레이브 서버

서버 간 동기화 슬레이브 서버를 사용 중인 경우, {productname} 서버 업데이트가 완료된 후에 해당 서버를 업데이트하십시오.

자세한 내용은 xref:specialized-guides:large-deployments/iss_v2.adoc[Inter-Server Synchronization - Version 2]를 참조하십시오.



== 모니터링 서버

Prometheus용 모니터링 서버를 사용 중인 경우, {productname} 서버 업데이트가 완료된 후 해당 서버를 업데이트하십시오.

모니터링에 대한 자세한 내용은 xref:administration:monitoring.adoc[]을 참조하십시오.



== 프록시

프록시는 {productname} 서버 업데이트가 완료되는 즉시 업데이트해야 합니다.

일반적으로 다른 버전의 서버에 연결된 프록시를 실행하는 것은 지원되지 않습니다.
유일한 예외는 업데이트 기간 동안 서버가 먼저 업데이트될 것으로 예상되므로 프록시가 이전 버전을 일시적으로 실행할 수 있습니다.


[WARNING]
====
항상 서버를 먼저 업그레이드한 다음 프록시를 업그레이드하십시오.
====
