[[live-patching-channel-setup]]
= 라이브 패치를 위한 채널 설정
:description: 클라이언트를 위해 Spacewalk의 콘텐츠 라이프사이클 관리 기능 또는 다른 방법을 사용하여 라이브 패치 채널을 설정하고 관리합니다.
:revdate: 2025-06-30
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

전체 커널 패키지를 업데이트할 때마다 재부팅이 필요합니다.
따라서 라이브 패치를 사용하는 클라이언트는 할당된 채널에 최신 커널이 없도록 하는 것이 중요합니다.
라이브 패치를 사용하는 클라이언트는 라이브 패치 채널에서 실행 중인 커널에 대한 업데이트를 받습니다.

라이브 패치를 위한 채널을 관리하는 두 가지 방법이 있습니다.

콘텐츠 라이프사이클 관리를 사용하여 제품 트리를 복제하고 실행 중인 커널보다 최신 커널 버전을 제거합니다.
이 절차는 xref:administration:content-lifecycle-examples.adoc#enhance-project-with-livepatching[]에서 설명되어 있습니다.
이것이 권장되는 솔루션입니다.

대안으로 `spacewalk-manage-channel-lifecycle` 도구를 사용하십시오.
이 절차는 더 수동적이며 명령줄 도구와 {webui}가 필요합니다.
이 절차는 SLES{nbsp}15 SP5에 대해 이 섹션에서 설명되지만, SLE{nbsp}12 SP4 이상에서도 작동합니다.



== 라이브 패치에 spacewalk-manage-channel-lifecycle 사용


[IMPORTANT]
====
spacewalk-manage-channel-lifecycle는 더 이상 사용되지 않으며 곧 출시될 버전에서 제거될 예정입니다. 사용자는 지원되고 기능이 풍부한 콘텐츠 라이프사이클 관리(CLM) API로 전환할 것을 권장합니다.
====

복제된 벤더 채널은 개발용일 경우 `dev`로, `testing` 또는 프로덕션용일 경우 `prod`로 접두사를 붙여야 합니다.
이 절차에서는 `dev` 복제된 채널을 생성한 다음 채널을 `testing`로 승격합니다.



.절차 라이브 패치 채널 복제하기

. 클라이언트의 명령 프롬프트에서 루트 권한으로 현재 패키지 채널 트리를 가져옵니다.
+

[subs=attributes]
----
# spacewalk-manage-channel-lifecycle --list-channels
Spacewalk Username: admin
Spacewalk Password:
Channel tree:

 1. sles15-{sp-vert}-pool-x86_64
      \__ sle-live-patching15-pool-x86_64-{sp-vert}
      \__ sle-live-patching15-updates-x86_64-{sp-vert}
      \__ sle-manager-tools15-pool-x86_64-{sp-vert}
      \__ sle-manager-tools15-updates-x86_64-{sp-vert}
      \__ sles15-{sp-vert}-updates-x86_64
----

. `spacewalk-manage-channel` 명령과 `init` 인수를 사용하여 원래 벤더 채널의 새 개발 복제본을 자동으로 생성합니다:
+
[subs=attributes]
----
spacewalk-manage-channel-lifecycle --init -c sles15-{sp-vert}-pool-x86_64
----
[subs=attributes]
. `dev-sles15-{sp-vert}-updates-x86_64`이(가) 채널 목록에 있는지 확인합니다.

생성한 `dev` 복제된 채널을 확인하고 재부팅이 필요한 커널 업데이트를 제거합니다.



.절차 복제된 채널에서 비라이브 커널 패치 제거하기
. menu:시스템[시스템 목록]에서 클라이언트를 선택하고 `Kernel` 필드에 표시된 버전을 기록하여 현재 커널 버전을 확인합니다.
. {productname} {webui}에서 menu:시스템[개요]에서 클라이언트를 선택하고 menu:소프트웨어[관리> 채널] 탭으로 이동하여 `dev-sles15-{sp-vert}-updates-x86_64`를 선택합니다.
      `Patches` 탭으로 이동하여 btn:[패치 나열/제거]를 클릭합니다.
. 검색 창에 `kernel`을(를) 입력하고 현재 클라이언트에서 사용하는 커널과 일치하는 커널 버전을 찾습니다.
. 현재 설치된 커널 버전보다 최신 커널 버전을 모두 제거합니다.

귀하의 채널은 이제 라이브 패치용으로 설정되었으며, `testing`(으)로 승격할 수 있습니다.
이 절차에서는 라이브 패치 하위 채널을 클라이언트에 추가하여 적용할 준비를 합니다.



.절차 라이브 패치 채널 승격
. 클라이언트의 명령 프롬프트에서 `root` 명령을 사용하여 `dev-sles15-{sp-vert}-pool-x86_64` 채널을 새 `testing` 채널로 승격하고 복제합니다:
+
[subs=attributes]
----
# spacewalk-manage-channel-lifecycle --promote -c dev-sles15-{sp-vert}-pool-x86_64
----
. {productname} {webui}에서 menu:시스템[개요]에서 클라이언트를 선택하고 menu:소프트웨어[소프트웨어 채널] 탭으로 이동합니다.
. 새 `test-sles15-{sp-vert}-pool-x86_64` 사용자 정의 채널을 확인하여 기본 채널을 변경하고 해당하는 라이브 패치 하위 채널을 모두 확인합니다.
. btn:[다음]을 클릭하고 세부 사항이 올바른지 확인한 후 btn:[확인]을 클릭하여 변경 사항을 저장합니다.

이제 사용할 수 있는 CVE 패치를 선택하여 볼 수 있으며, 라이브 패치를 사용하여 이러한 중요한 커널 업데이트를 적용할 수 있습니다.
