[[organizations]]
= 조직
:description: SUSE Multi-Linux Manager에서 사용자 액세스, 권한 및 인증 방법을 관리하기 위해 조직을 구성하는 방법을 배우십시오.
:revdate: 2022-01-13
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


조직은 {productname} 내에서 사용자 액세스 및 권한을 관리하기 위한 용도로 사용됩니다.

대부분의 환경에서는 단일 조직이면 충분합니다.
그러나 더 복잡한 환경에서는 여러 조직이 필요할 수 있습니다.
비즈니스 내 각 물리적 위치 또는 다양한 비즈니스 기능에 대해 조직을 두고 싶을 수 있습니다.

조직을 생성한 후에는 사용자를 생성하여 조직에 할당할 수 있습니다.
그런 다음 조직 수준에서 권한을 할당할 수 있으며, 이는 기본적으로 조직에 할당된 모든 사용자에게 적용됩니다.

새 조직에 대해 PAM 및 싱글 사인온을 포함한 인증 방법을 구성할 수도 있습니다.
인증에 대한 자세한 내용은 xref:administration:auth-methods.adoc[]을 참조하십시오.

[NOTE]
====
조직을 만들고 관리하려면 {productname} 관리자로 로그인해야 합니다.
====



.절차 새 조직 생성
. {productname} {webui}에서 menu:관리자[조직]으로 이동한 후 btn:[조직 생성]을 클릭합니다.
. `Create Organization` 대화 상자에서 다음 필드를 작성합니다.
* `Organization Name` 필드에 새 조직의 이름을 입력합니다.
    이름은 3~128자 사이여야 합니다.
* `Desired Login` 필드에 조직 관리자가 사용할 로그인 이름을 입력합니다.
    새 관리자 계정이어야 하며, 현재 로그인한 조직을 포함하여 기존 관리자 계정을 사용해서는 새 조직에 로그인할 수 없습니다.
* `Desired Password` 필드에 새 조직 관리자의 비밀번호를 입력합니다.
    `Confirm Password` 필드에 비밀번호를 다시 입력하여 확인합니다.
    비밀번호 강도는 비밀번호 필드 아래의 색상 막대로 표시됩니다.
* `Email` 필드에 새 조직 관리자의 이메일 주소를 입력합니다.
* `First Name` 필드에서 인사말을 선택하고 새 조직 관리자의 이름을 입력합니다.
* `Last Name` 필드에 새 조직 관리자의 성을 입력합니다.
. btn:[조직 생성]을 클릭합니다.



== 조직 관리


{productname} {webui}에서 menu:관리자[조직]으로 이동하여 사용 가능한 조직 목록을 확인합니다.
조직의 이름을 클릭하여 관리합니다.

menu:관리자[조직] 섹션에서 조직의 사용자, 신뢰, 구성 및 상태를 관리할 수 있는 탭에 액세스할 수 있습니다.

[NOTE]
====
조직은 해당 관리자만 관리할 수 있습니다.
조직을 관리하려면 변경하려는 조직의 올바른 관리자 계정으로 로그인해야 합니다.
====



=== 조직 사용자

`Users` 탭으로 이동하여 조직과 관련된 모든 사용자 목록과 그들의 역할을 확인합니다.
사용자 이름을 클릭하면 `Users` 메뉴로 이동하여 사용자를 추가, 변경 또는 삭제할 수 있습니다.



=== 신뢰할 수 있는 조직

`Trusts` 탭으로 이동하여 신뢰할 수 있는 조직을 추가하거나 제거합니다.
조직 간의 신뢰를 설정하면 콘텐츠를 공유할 수 있으며, 클라이언트를 한 조직에서 다른 조직으로 전송할 수 있는 기능을 제공합니다.



=== 조직 구성

`Configuration` 탭으로 이동하여 조직의 구성을 관리합니다.
여기에는 단계적 콘텐츠 사용 및 SCAP 파일 사용이 포함됩니다.

콘텐츠 스테이징에 대한 자세한 내용은 xref:administration:content-staging.adoc[]을 참조하십시오.

OpenSCAP에 대한 자세한 내용은 xref:reference:audit/audit-openscap-overview.adoc[]을 참조하십시오.



== 상태 관리


`States` 탭으로 이동하여 조직의 모든 클라이언트에 대한 Salt 상태를 관리합니다.
상태를 사용하면 전역 보안 정책을 정의하거나 모든 클라이언트에 공통 관리자 사용자를 추가할 수 있습니다.

Salt 상태에 대한 자세한 내용은 xref:specialized-guides:salt/salt-states-and-pillars.adoc[]을 참조하십시오.



=== 설정 채널 관리

조직 전반에 적용할 구성 채널을 선택할 수 있습니다.
구성 채널은 {productname} {webui}에서 menu:구성[채널]로 이동하여 생성할 수 있습니다.
조직에 구성 채널을 적용할 때는 {productname} {webui}을 사용합니다.

.절차 조직에 구성 채널 적용
. {productname} {webui}에서 menu:홈[내 조직> 구성 채널]으로 이동합니다.
. 검색 기능을 사용하여 이름으로 채널을 찾습니다.
. 적용할 채널을 확인하고 btn:[변경사항 저장]을 클릭합니다.
    이 작업을 수행하면 변경 사항이 데이터베이스에 저장되지만, 채널에는 적용되지 않습니다.
. btn:[적용]을 클릭하여 변경사항을 적용합니다.
    이 작업을 수행하면 조직 내의 모든 클라이언트에 변경사항을 적용하는 작업이 예약됩니다.
