[[patch-management]]
= 패치 관리
:description: SUSE Multi-Linux Managers의 기능을 사용하여 패치를 효과적으로 관리하고 철회된 패치를 채널 간에 동기화하고 전파하는 방법을 배우십시오.
:revdate: 2022-02-17
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

이 장에는 패치 관리와 관련된 다양한 항목이 포함되어 있습니다.


== 철회된 패치


벤더가 새로운 패치를 출시할 때, 테스트에서 식별되지 않은 일부 시나리오에서 패치가 바람직하지 않은 부작용(보안, 안정성)을 초래할 수 있습니다. 이런 일이 발생하면(매우 드물게), 벤더는 일반적으로 새로운 패치를 출시하며, 이는 벤더의 내부 프로세스에 따라 몇 시간 또는 며칠이 걸릴 수 있습니다. 

SUSE는 권고 상태를 ("최종" 또는 "안정" 대신) "철회"로 설정하여 이러한 패치를 거의 즉시 취소하는 "철회된 패치"라는 새로운 메커니즘(2021년)을 도입했습니다.

[IMPORTANT]
====
패치는 그 권고 상태 속성이 "철회됨"으로 설정될 때 "철회된" 상태가 됩니다.
패키지는 "철회된" 패치에 속할 때 "철회된" 상태가 됩니다.
====

철회된 패치 또는 패키지는 {productname}이 있는 시스템에 설치할 수 없습니다. 철회된 패키지를 설치하는 유일한 방법은 `zypper install`를 사용하여 수동으로 설치하고 정확한 패키지 버전을 지정하는 것입니다.
예:
----
zypper install vim-8.0.1568-5.14.1
----

패치 및 패키지의 철회된 상태는 icon:times-circle[role="red"]의 {webui} 내에 있는 {productname} 아이콘으로 표시됩니다. 예를 들어, 다음을 참조하십시오:

* 채널 내 패키지 목록
* 채널 내 패치 목록

시스템에 설치된 패치 또는 패키지가 철회되면 해당 시스템의 설치된 패키지 목록에 icon:times-circle[role="red"] 아이콘도 표시됩니다. {productname}는 이러한 패치 또는 패키지를 다운그레이드할 수 있는 방법을 제공하지 않습니다.


=== 채널 클론
복제된 채널을 사용하는 경우에는 철회된 권고 상태가 원래 채널에서 클론으로 전파되는 것에 주의해야 합니다.

벤더 채널을 조직에 복제하면 채널 패치도 복제됩니다.

벤더가 채널의 패치를 철회하고 {productname}가 이 채널을 동기화하면(예: 야간 작업을 통해), "철회됨" 특성은 복제된 패치로 전파되지 않으며 복제된 채널에 가입한 클라이언트에게 표시되지 않습니다. 복제된 채널에 특성을 전파하려면 다음 방법 중 하나를 사용하십시오:

* 패치 동기화 (menu:소프트웨어[관리> 복제된 채널> 패치> 동기화]). 이 기능은 복제된 채널의 패치 속성을 원본과 일치시킬 수 있도록 합니다.
* 컨텐트 라이프사이클 관리. 컨텐트 라이프사이클 관리의 맥락에서 복제된 채널에 대한 자세한 내용은 xref:client-configuration:channels.adoc[]을 참조하십시오.


=== 패치 공유

조직에서 여러 벤더 채널 복제본을 생성할 때, 패치는 여러 번 복제되지 않고 복제된 채널 간에 공유됩니다. 결과적으로, 복제된 패치를 동기화할 때(패치 동기화 기능을 사용하거나 위에서 언급한 컨텐트 라이프사이클 관리를 사용하여), 복제된 패치를 사용하는 모든 채널이 해당 변경 사항을 확인할 수 있습니다.

.예:
. 두 개의 콘텐츠 라이프사이클 관리 프로젝트 `prj1`와 `prj2`를 고려하십시오.
. 두 프로젝트 모두 `dev`와 `test`라는 두 환경을 갖추고 있습니다.
. 이러한 두 프로젝트에는 벤더 채널이 소스 채널로 설정되어 있습니다.
. 이 시나리오의 모든 채널(복제된 채널 총 네 개)은 벤더 채널의 최신 상태에 맞춰 정렬됩니다.
. 벤더는 소스 채널에서 패치를 철회하고 야간 작업 중에 귀하의 {productname}에 동기화합니다.
. 채널 네 개 모두 패치 클론을 사용하고 패치를 직접 사용하지 않으므로 이 변경사항을 볼 수 없습니다.
. 패치를 동기화하는 즉시(이 두 프로젝트 중 하나를 빌드하거나 네 개의 복제된 채널 중 어느 하나에서 패치 동기화 기능을 사용하는 경우), 패치 공유로 인해 복제된 채널 *ALL*이 패치가 철회된 것으로 표시됩니다.
