[[ptfs]]
= {productname}에서 PTF 사용하기
:description: SUSE Multi-Linux Manager를 위한 상세 절차와 단계별 지침을 사용하여 프로그램 임시 수정(PTF)을 구성하고 배포합니다.
:revdate: 2024-11-29
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서 팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


SUSE는 현재 지원되는 모든 솔루션에 대한 임시 수정을 고객에게 직접 제공합니다.
이 PTF(프로그램 임시 수정)는 이제 {productname}에서 동기화할 수 있는 리포지토리로 제공됩니다.


== PTF 패키지에 대해 알아보기


PTF 패키지는 프록시 패키지를 통해 설치되며 `ptf-xxxxxx`이라는 이름이 지정됩니다. 여기서 xxxxxx는 번호이며 패키지 이름의 일부입니다. 버전이 아닙니다.

이는 소프트웨어에 수정 사항을 포함하는 패키지의 정확한 버전에 따라 달라집니다. 
이러한 유형의 패키지는:

* 실수로 설치할 수 없습니다(즉, zypper 업데이트에서 절대로 설치를 제안하지 않음).
* 실수로 제거할 수 없습니다(즉, 사용자가 zypper 명령 줄에서 명시적으로 지정하는 경우를 제외하고 최신 패키지 버전이 PTF 버전을 대체하지 않음).
* 최신 버전이 PTF에서 이전에 해결한 특정 문제를 해결하는 것으로 알려진 경우에만 업데이트됩니다.
* 시스템에 이미 설치된 패키지만 업데이트합니다(즉, 소프트웨어가 여러 패키지로 분할된 경우 PTF는 현재 시스템에 설치된 패키지만 교체).

패키지의 정확한 ID는 영향을 받는 서비스를 배포/재시작하는 방법에 대한 지침과 함께 지원 사례 조사 과정에서 SUSE 지원이 제공합니다.


== PTF 패키지 설치

[NOTE]
====
현재 PTF 패키지는 SLE 12 및 SLE 15 기반 시스템에서만 지원됩니다.
다른 버전이나 운영 체제는 이 기능을 지원하지 않으며 해당 페이지는 표시되지 않습니다.
====

[IMPORTANT]
====
{productname}을(를) 통해 PTF 채널에 액세스하려면 L3 지원팀에 요청해야 합니다.
====

.절차 명령 줄을 사용한 PTF 리포지토리 활성화 및 동기화

. 콘솔에서 `mgr-sync refresh`을(를) 입력합니다.
. `mgr-sync list channel`을(를) 입력하고 {scc} 계정 이름과 `ptfs`이(가) 이름에 포함된 채널을 찾으십시오.
  예를 들어, `a123456-sles-15.3-ptfs-x86_64`.
. `mgr-sync add channel <label>`을(를) 사용하여 PTF 채널을 활성화합니다.

이제 이 채널을 사용할 수 있으며 동일한 기본 채널을 사용하는 모든 시스템에 추가할 수 있습니다.

PTF 패키지는 명시적으로 설치해야 하며, 시스템을 업데이트할 때 자동으로 선택되지 않습니다.
SUSE 고객 지원팀은 특정 문제를 해결하기 위한 PTF 번호를 제공합니다. 
이 번호로 프록시 패키지를 PTF 목록에서 식별할 수 있습니다.
{productname} {webui}에서 설치 가능한 PTF가 있는 모든 시스템에는 이를 나열하는 페이지가 있습니다.


.절차 {productname} {webui}를 통해 PTF 리포지토리 활성화 및 동기화

. {productname} {webui}에서 menu:관리자[설정 마법사> 제품]으로 이동하여 PTF 리포지토리를 활성화할 제품을 찾습니다.
. 제품 동기화 상태 옆에 있는 btn:[제품 채널 표시]를 클릭합니다.
. 제품에 대한 필수 및 선택 채널을 나열하는 팝업이 표시되어야 합니다.
. 선택적 채널 목록에서 {scc} 계정 이름으로 시작하고 `ptfs`가 포함된 채널을 찾습니다.
  예 `a123456-sles-15.3-ptfs-x86_64`.
. 채널 이름 옆의 확인란을 사용하여 채널을 선택하고 btn:[확인]을 클릭하여 동기화를 예약합니다.

제품이 설치되어 있어야 제품에 옵션 채널을 추가할 수 있습니다.


.절차 PTF 패키지 설치

. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 PTF를 설치할 클라이언트를 선택합니다.
. menu:시스템[소프트웨어> 패키지> 소프트웨어 채널]로 이동하여 `PTF channel`을(를) 선택합니다.
. btn:[다음]을 클릭하고 btn:[확인]으로 `Confirm Software Channel Change`합니다.
. 채널 할당이 완료되었는지 확인하려면 menu:시스템[이벤트> 이력]으로 이동하여 결과를 확인합니다.
. menu:시스템[소프트웨어> PTFs> 설치] 하위 탭으로 이동합니다.
. 설치할 PTF 패키지를 선택합니다.
. btn:[PTF 설치]를 클릭하고 btn:[확인]으로 `Confirm Program Temporary Fixes (PTFs) Installation`합니다.
. PTF 설치 결과를 확인하려면 menu:시스템[이벤트> 이력]으로 이동합니다.


API를 사용하여 PTF를 설치해야 하는 경우 일반 `system.schedulePackageInstall` API를 프록시 패키지 이름과 함께 사용할 수 있습니다.


== PTF 설치 후

보고된 문제를 해결하는 PTF가 확인되면, 업데이트된 패키지는 추적되어 향후 유지보수 업데이트에 포함된 후 업데이트 리포지토리에 정기 유지보수 업데이트로 널리 배포됩니다.

이 수정이 포함된 정기 업데이트가 출시되면, 계정별 PTF 리포지토리에 업데이트된 PTF 버전도 출시됩니다. 
업데이트된 PTF는 엄격한 종속성을 제거하고 업데이트를 다시 설치할 수 있도록 합니다.

PTF를 수정이 포함된 유지보수 업데이트로 교체하면 표준 패키지 업데이트 또는 패치 설치를 통해 자동으로 수행됩니다.



== 패키지의 패치 버전 제거

PTF를 제거하고 패치되지 않은 버전의 패키지를 시스템에 설치해야 하는 경우, 간단한 패키지 제거를 사용할 수 없습니다. 
PTF 패키지는 표준 패키지 목록 페이지에서 선택할 수 없습니다.


.절차 PTF 패키지 제거하기

. {productname} {webui}에서 menu:시스템[시스템 목록]으로 이동하여 PTF를 제거할 클라이언트를 선택합니다.
. menu:시스템[소프트웨어> PTFs> 목록/제거] 하위 탭으로 이동합니다.
. 제거할 ptf 패키지를 선택합니다.
. btn:[PTF 제거]를 클릭하고 `Confirm Program Temporary Fixes (PTFs) Removal` 페이지에서 btn:[확인]을 클릭합니다.
. 결과를 보려면 menu:시스템[이벤트> 이력]으로 이동합니다.


[NOTE]
====
PTF를 제거하려면 클라이언트 시스템에 `libzypp` 및 `zypper`의 특별한 버전이 설치되어 있어야 합니다.
`zypper --help`이(가) 지원되는지 확인하려면 `removeptf`을(를) 확인하십시오.
이 조건이 충족되면 `List/Remove` 탭이 표시됩니다.
====

API를 사용하여 PTF를 제거해야 하는 경우 일반 `system.schedulePackageRemove` API를 프록시 패키지 이름과 함께 사용할 수 있습니다.


== 클라이언트에서 패키지의 패치 버전 제거

클라이언트에서 콘솔을 사용하여 PTF를 직접 제거해야 하는 경우 특별한 명령 `zypper removeptf`을(를) 사용해야 합니다.
다른 모든 방법은 오류를 발생시키거나 시스템에서 중요한 패키지를 제거하여 시스템을 사용할 수 없게 만들 수 있는 원치 않는 동작을 초래할 수 있습니다.
