[[configure-autosync-channel]]
= 자동 채널 동기화 구성
:description: 자동 채널 동기화를 구성하여 채널이 업스트림 저장소에서 언제 업데이트되는지 제어하고, API를 통해 상태를 확인할 수 있도록 하세요.
:revdate: 2026-05-08
:page-revdate: {revdate}

기본적으로 채널은 업스트림 리포지토리와 자동으로 동기화되어 클라이언트가 최신 콘텐츠 및 업데이트에 액세스할 수 있도록 합니다.
그러나 경우에 따라 특정 채널에 대해 이 자동 동기화를 비활성화할 수 있습니다.

이 장에서는 채널에 대한 자동 동기화를 비활성화하는 방법을 설명합니다.




[[get-channel-sync-satus]]
== 채널 동기화 상태 확인

채널이 자동으로 동기화되도록 설정되었는지 확인하려면 사용자가 API를 호출할 수 있습니다.

API를 사용하여 채널의 동기화 상태를 확인하려면 다음 명령을 사용하십시오.
`<Channel_Label>`을 확인하려는 채널의 실제 레이블로 바꾸십시오.

[source,console]
----
spacecmd api -- --args "<Channel_Label>" channel.software.isAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  true
]
----

자동 동기화가 활성화된 경우 명령은 `true`을(를) 반환하고, 비활성화된 경우 `false`을(를) 반환합니다.

이 정보는 {webui}에서도 확인할 수 있습니다.
동기화 상태를 확인하려면 채널 세부 정보 페이지로 이동하여 `Automatic Repository Synchronization` 필드를 찾으십시오.


[[set-channel-sync-satus]]
== 채널이 자동 동기화를 건너뛰도록 설정

채널의 자동 동기화를 활성화하거나 비활성화하려면 `channel.software.setAutoSync` API 호출을 사용할 수 있습니다.

다음은 API를 사용하여 채널이 자동 동기화를 건너뛰도록 설정하는 예입니다 (`<Channel_Label>`을(를) 업데이트할 채널의 실제 레이블로 바꾸십시오).

[source,console]
----
spacecmd api -- --args '["<Channel_Label>", false]' channel.software.setAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  false
]
----

자동 동기화를 다시 활성화하려면 두 번째 매개변수를 `true`(으)로 설정하십시오.

[source,console]
----
spacecmd api -- --args '["<Channel_Label>", true]' channel.software.setAutoSync
INFO: Connected to http://localhost/rpc/api as admin
[
  true
]
----


[[manual-channel-sync]]
== 채널 수동 동기화

채널의 자동 동기화를 비활성화한 경우에도 필요할 때 언제든지 수동으로 동기화할 수 있습니다.

[IMPORTANT]
====
서버 컨테이너 내에서 단계를 실행하기 전에 `mgrctl term`을(를) 사용하십시오.
====

채널을 수동으로 동기화하려면 명령을 사용할 수 있습니다 (`<Channel_Label>`을 동기화하려는 채널의 실제 레이블로 바꾸십시오).

[source,console]
----
spacewalk-repo-sync -c <Channel_Label>
----
