[[channels]]
= 软件通道
:description: 在 SUSE 环境中配置和管理软件通道，以分组兼容的软件包，确保简化的安装和更新，并保持控制
:revdate: 2024-12-12
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

通道是将软件包分组的一种方法。
软件包由储存库提供，储存库与通道相关联。
将客户端订阅到软件通道允许客户端安装和更新与之相关的任何软件。

在 {productname} 中，通道分为基础通道和子通道。
以这种方式组织通道确保每个系统上仅安装兼容的软件包。
客户端必须仅订阅一个基础通道，该通道在注册时根据客户端的操作系统和架构分配。
对于供应商提供的付费通道，您必须拥有相关的订阅。

基础通道由为特定操作系统类型、版本和架构构建的软件包组成。
例如，{sles}{nbsp}15 {x86_64} 基础通道仅包含与该操作系统和架构兼容的软件。

子通道与基础通道相关联，仅提供与基础通道兼容的软件包。
一个系统可以订阅其基础通道的多个子通道。
当系统被分配到基础通道时，该系统只能安装相关的子通道。
例如，如果系统被分配到 {sles}{nbsp}15 `x86_64` 基础通道，则它们只能安装或更新通过兼容基础通道或其任何相关子通道提供的软件包。

在 {productname} {webui} 中，您可以通过导航到 menu:软件[通道列表> 全部] 来浏览可用的通道。
您可以通过导航到 menu:软件[管理> 通道] 来修改或创建新通道。

有关使用通道的更多信息，包括自定义通道，请参见 xref:administration:channel-management.adoc[]。

.引导后处理安装程序更新通道
[IMPORTANT]
====
一旦客户端系统已启动，**安装程序更新** 通道应被去除。标准更新通道已经包含必要的更新，使该通道变得多余。

此外，在迁移期间，该通道也不是必需的，不应使用。
====

== 通过 {phub} 提供的软件包


{phub} 是 {sle} 产品的扩展，提供由 {opensuse} 社区提供的额外开源软件。

[IMPORTANT]
====
{phub}中的软件包由{opensuse}社区提供。
它们不受{suse}的支持。
====

如果您在客户端上使用{sle}操作系统，可以启用{phub}扩展以访问这些额外的软件包。
这提供了{phub}通道，您可以将客户端订阅到这些通道。

{phub}提供了大量软件包，这可能需要很长时间进行同步，并消耗大量磁盘空间。
除非您需要它提供的软件包，否则请不要启用{phub}。

为了避免无意中安装或更新不受支持的软件包，我们建议您实施内容生命周期管理策略，初始时拒绝所有{phub}软件包。
然后，您可以明确启用所需的特定软件包。
有关内容生命周期管理的更多信息，请参见xref:administration:content-lifecycle.adoc[]。



== 通过 AppStream 提供的软件包

对于基于{redhat}的客户端，可以通过AppStream获得额外的软件包。
在大多数情况下，AppStream软件包是确保您拥有所需所有软件的必要条件。



== 通过 EPEL 提供的软件包

对于基于{redhat}的客户端，可以通过EPEL（企业Linux的额外软件包）获得额外的软件包。
EPEL是一个可选的软件包储存库，提供额外的软件。

[IMPORTANT]
====
EPEL中的软件包由Fedora社区提供。
它们不受{suse}的支持。
====

如果您在客户端上使用{redhat}操作系统，可以启用EPEL扩展以访问这些额外的软件包。
这提供了EPEL通道，您可以将客户端订阅到这些通道。

EPEL提供了大量软件包，这可能需要很长时间进行同步，并消耗大量磁盘空间。
除非您需要它提供的软件包，否则请不要启用EPEL储存库。

为了避免无意中安装或更新不受支持的软件包，我们建议您实施内容生命周期管理（CLM）策略，初始时拒绝所有EPEL软件包。
然后，您可以明确启用所需的特定软件包。
有关内容生命周期管理的更多信息，请参见 xref:administration:content-lifecycle.adoc[]。



== 在 {sle} 客户端上的 {unifiedinstaller} 更新通道

此通道由 {unifiedinstaller} 使用，以确保在安装操作系统之前保持最新。
所有 {sle} 产品在安装期间应能够访问安装程序更新通道。

对于 {sles} 客户端，默认情况下，当您添加包含它们的产品时，安装程序更新通道会进行同步，并在您创建包含这些产品通道的可自动安装发行版时启用。

对于所有其他 {sle} 变体，包括用于 SAP 的 {sle}，您必须手动添加安装程序更新通道。
为此，请在这些 {sle} 变体的基础通道下克隆适当的 {sles} 安装程序更新通道。
在克隆通道后，为这些 {sle} 变体创建可自动安装的发行版时，将自动使用该通道。
