[[client-upgrades-clm]]
= 使用内容生命周期管理器升级
:description: 使用内容生命周期管理器的自动化处理升级您的 SUSE Linux Enterprise Server 客户端
:revdate: 2024-11-21
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

如果您需要管理的 {sles} 客户端有很多，可以使用内容生命周期管理器自动执行就地升级。



== 准备升级


升级客户端之前，需要完成以下准备工作：

* 创建内容生命周期项目
* 创建激活密钥
* 创建可自动安装的发行套件
* 创建自动安装配置文件

.过程：升级创建内容生命周期项目
. 为您的发行套件创建内容生命周期项目。
+
有关更多信息，请参见 xref:administration:content-lifecycle.adoc[]。

. 务必为您的项目选择简短的非描述性名称。

. 添加您的发行套件所需的所有源通道模块。

. 视需要添加过滤器，并至少设置一个环境。



.过程：升级创建激活密钥
. 为您的发行套件创建激活密钥。
+
有关更多信息，请参见 xref:client-configuration:activation-keys.adoc[]。

. 确保您的激活密钥包含所有过滤出的项目通道。



.过程：升级创建可自动安装的发行套件

. 为要迁移的每个基础通道创建可自动安装的发行套件。
+
有关详细信息，请参见 xref:client-configuration:autoinst-distributions.adoc[]。

. 为您的发行套件指定一个标签来表示内容生命周期项目的名称。

. 在`Installer Generation`字段中，选择您正在使用的SLES版本。



.过程：升级创建自动安装配置文件

. 为要升级到的每个目标发行套件和服务包创建自动安装配置文件。
+
有关更多信息，请参见 xref:client-configuration:autoinst-profiles.adoc[]。

. 您可以在配置文件中使用变量来区分不同的生命周期环境。


有关自动安装控制文件的示例，请参见 https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST.

在自动安装配置文件中使用以下变量来实现自动就地升级：



.示例：在自动安装控制文件中使用的变量
----
registration_key=1-15sp1-demo-test
org=1
channel_prefix=15sp1-demo-test
distro_label=15sp1-demo-test
----



.示例：在自动安装控制文件中使用的项
----
 <listentry>
     <ask_on_error config:type="boolean">true</ask_on_error>
     <media_url>https://$redhat_management_server/ks/dist/child/$channel_prefix-sle-module-web-scripting15-sp1-pool-x86_64/$distro_label</media_url>
     <name>$channel_prefix SLE-Module-Web-Scripting15-SP1 Pool for x86_64 </name>
     <product>Web Scripting Module 15 SP1 x86_64 Pool</product>
</listentry>
----



== 升级

准备好要升级的服务器后，您便可置备客户端。

.过程：升级置备客户端

. 在 {productname} {webui} 中，导航到 menu:系统[系统列表]，选择您要置备的客户端，以将其添加到系统集管理器中。

. 导航到 menu:系统[系统集管理器> 概述]，然后单击 `Provisioning` 选项卡。

. 选择要使用的自动安装配置文件。


对于能够使用 PXE 引导的客户端，迁移将在您置备它们后自动进行。
对于所有其他客户端，您可以使用 {cobbler} 执行升级。



.过程：升级使用 {cobbler} 升级客户端
. 在命令提示符处，以 root 身份运行以下命令，以访问容器内的外壳：
+
----
mgrctl term
----
. 检查可用的 {cobbler} 控制文件：
+
----
cobbler profile list
----
. 使用您选择的配置文件和发行套件构建 ISO 文件：
+
----
cobbler buildiso --iso=/tmp/SLE_15-sp1.iso --profiles=SLE_15-sp1:1:Example --distro=SLE_15-sp1
----


// FIXME: 2024-05-06, ke: Do we want to use /tmp here within the container?

有关使用 CD-ROM 置备客户端的更多信息，请参见 xref:client-configuration:autoinst-cdrom.adoc[]。
