[[clients-centos]]
= 注册 {centos} 客户端
:description: 通过在 SUSE Multi-Linux Manager 中添加所需的储存库，配置 CentOS 客户端架构，包括 x86-64 和 AArch64
:revdate: 2025-03-10
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

本节包含有关注册运行 {centos} 操作系统的客户端的信息。

ifeval::[{mlm-content} == true]

// Use list format: repository URLs / packages and metadata / version info
// Do we need to provide special info for uyuni users?
[IMPORTANT]
====
* {centos} 储存库 URL 可从 {scclongform} 获取。
* 软件包和元数据由 CentOS 提供，而不是 {suse}。
* 有关支持的产品，请参见 xref:client-configuration:supported-features-centos.adoc[] 的版本说明和支持表。
====
endif::[]

[IMPORTANT]
====

ifeval::[{mlm-content} == true]

{centos} 客户端基于 {centos}，与 {sleses}、RES、{redhat} 或 {es} 无关。
endif::[]

您需负责安排对 {centos} 基础媒体储存库和 {centos} 安装媒体的访问权限，以及将 {productname} 服务器连接到 {centos} 内容分发网络。
====

[NOTE]
====
将 {centos} 客户端注册到 {productname} 的测试是在 `enforcing` 的默认 SELinux 配置下进行的，使用 `targeted` 策略。
您无需禁用 SELinux 即可将 {centos} 客户端注册到 {productname}。
====



== 添加软件通道


在将 {centos} 客户端注册到您的 {productname} 服务器之前，您需要添加所需的软件通道，并同步这些通道。

目前支持的架构有：`x86_64` 和 `aarch64`。
有关支持的产品和架构的完整列表，请参见 xref:client-configuration:supported-features.adoc[]。

ifndef::backend-pdf[]
include::client-configuration:partial$arch-other-note.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/arch-other-note.adoc[]
endif::[]

ifeval::[{mlm-content} == true]

例如，使用 `x86_64` 架构时，您需要如下产品：

[[centos-channels-wizard]]
[cols="1,1", options="header"]
.CentOS 产品 - WebUI
|===

| 操作系统版本 | 产品名称
| {centos} 7 | CentOS 7 x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_webui.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_webui.adoc[]
endif::[]

或者，您也可以在命令提示符处添加通道。
此过程所需的通道包括：

[[centos-channels-MLM-cli]]
[cols="1,1", options="header"]
.CentOS 通道 - CLI
|===

| 操作系统版本 | 基础通道
| {centos} 7 | centos7-x86_64

|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_vendor_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_vendor_cli.adoc[]
endif::[]

endif::[]

ifeval::[{uyuni-content} == true]
此过程所需的通道包括：

[[centos-channels-uyuni-cli]]
[cols="1,1,1,1", options="header"]
.CentOS 通道 - CLI
|===

| 操作系统版本 | 基础通道 | 客户端通道       | 更新/Appstream 通道
| {centos} 7 | centos7      | centos7-uyuni-client | centos7-updates
|===

ifndef::backend-pdf[]
include::client-configuration:partial$addchannels_novendor_cli_multiarch.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/addchannels_novendor_cli_multiarch.adoc[]
endif::[]

[NOTE]
====
`spacewalk-common-channels` 提供的客户端工具频道源自 {uyuni}，而非 {suse}。
====

endif::[]


如果您使用的是模块化通道，您必须在客户端上启用 Python 3.6 模块流。
如果您不提供 Python 3.6，`spacecmd` 软件包的安装将失败。

[NOTE]
====
您可能会注意到上游和 {productname} 通道之间的应用流通道中可用软件包数量存在差异。
如果您在不同时间点比较同一通道，您也可能会看到不同的数字。
这是由于 {centos} 管理其储存库的方式。{centos} 在发布新版本时会删除旧版本的软件包，而 {productname} 则会保留所有版本，无论其年龄。
====


== 检查同步状态

ifeval::[{mlm-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_mlm.adoc[]
endif::[]

endif::[]


ifeval::[{uyuni-content} == true]

ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_webui_uyuni.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_webui_uyuni.adoc[]
endif::[]

endif::[]


ifndef::backend-pdf[]
include::client-configuration:partial$check_sync_cli.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/check_sync_cli.adoc[]
endif::[]



== 创建激活密钥

您需要创建与您的 {centos} 通道关联的激活密钥。

有关激活密钥的更多信息，请参见 xref:client-configuration:activation-keys.adoc[]。



== 管理 GPG 密钥

客户端使用 GPG 密钥在安装软件包之前检查其真实性。
只有受信任的软件包才能在客户端上安装。

[IMPORTANT]
====
信任 GPG 密钥对客户端的安全性至关重要。
决定需要哪些密钥并可以信任哪些密钥是管理员的任务。
由于在 GPG 密钥未被信任时无法使用软件通道，因此是否将通道分配给客户端取决于是否信任该密钥。
====

有关 GPG 密钥的更多信息，请参见 xref:client-configuration:gpg-keys.adoc[]。



== 注册客户端


[NOTE]
====
CentOS 7 将无法接入，原因是 `/etc/yum.repos.d/CentOS-Base.repo` 中启用了 URL，导致 `yum` 尝试通过 fastmirror 查找仓库。
这将导致启动失败，并出现如下错误消息：

----
Could not resolve host: mirrorlist.centos.org; Unknown error
----

要解决此问题，您可以通过以下命令去除 `CentOS-Base.repo` 文件：

[source,shell]
----
rm -f /etc/yum.repos.d/CentOS-Base.repo
----

或者，如果需要保留该文件，则可在每个 URL 部分添加 `enabled=0`。

无论选择哪种方式，之后都需重新执行引导流程。
====

ifndef::backend-pdf[]
include::client-configuration:partial$create_bootstrap_repo_register.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../partials/create_bootstrap_repo_register.adoc[]
endif::[]



ifeval::[{uyuni-content} == true]

== 管理勘误

[NOTE]
====
本节仅适用于非容器化 Uyuni，在 {centos} 7 终止服务后将被去除。
====

当您更新 {centos} 客户端时，软件包不包含有关更新的元数据。
您可以使用第三方勘误服务来获取此信息。

[WARNING]
====

// ifeval::[{mlm-content} == true]
//
// The third-party errata service described here, CEFS, is provided and maintained by the community.
// It is not supported by {suse}.
//
// endif::[]

CEFS 的作者提供补丁或勘误，尽力而为，希望它们有用，但不保证正确性或时效性。
这可能意味着补丁日期可能不正确，并且在至少一个案例中，发布的数据被证明超过一个月未更新。
有关这些案例的更多信息，请参见 https://github.com/stevemeier/cefs/issues/28#issuecomment-656579382 和 https://github.com/stevemeier/cefs/issues/28#issuecomment-656573607.。

补丁数据的任何问题或延迟可能导致不可靠的补丁信息被导入到您的 {productname} 服务器。
这将导致报告、审计、CVE 更新或其他与补丁相关的信息也不正确。
请考虑使用此服务的替代方案，例如独立验证补丁数据，或根据您的安全相关要求和认证标准选择不同的操作系统。
====




.过程：升级安装勘误服务

. 在 {productname} 服务器上，从命令提示符处以 root 用户身份添加 `sle-module-development-tools` 模块：
+
----
SUSEConnect --product sle-module-development-tools/15.2/x86_64
----
. 安装勘误服务依赖项：
+
----
zypper in  perl-Text-Unidecode
----
. 在 `/etc/rhn/rhn.conf` 中添加或编辑此行：
+
----
java.allow_adding_patches_via_api = centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras
----
. 重启 Tomcat：
+
----
systemctl restart tomcat
----
. 为勘误脚本创建一个文件：
+
----
touch /usr/local/bin/cent-errata.sh
----
. 编辑新文件以包含此脚本，并视需要编辑储存库细节。
    此脚本会从外部勘误服务提取勘误细节，将其解压缩，然后发布这些细节：
+
----
#!/bin/bash
mkdir -p /usr/local/centos
cd /usr/local/centos
rm *.xml
wget -c http://cefs.steve-meier.de/errata.latest.xml
wget -c https://www.redhat.com/security/data/oval/v2/RHEL7/rhel-7.oval.xml.bz2
bzip2 -d rhel-7.oval.xml.bz2
wget -c http://cefs.steve-meier.de/errata-import.tar
tar xvf errata-import.tar
chmod +x /usr/local/centos/errata-import.pl
export SPACEWALK_USER='<adminname>';export SPACEWALK_PASS='<password>'
/usr/local/centos/errata-import.pl --server '<servername>' \
--errata /usr/local/centos/errata.latest.xml  \
--include-channels=centos7-x86_64-updates,centos7-x86_64,centos7-x86_64-extras \
--publish --rhsa-oval /usr/local/centos/rhel-7.oval.xml
----
. 设置 cron 作业以每日运行该脚本：
+
----
ln -s /usr/local/bin/cent-errata.sh /etc/cron.daily
----

有关此工具的更多信息，请参见 https://cefs.steve-meier.de/.。

endif::[]
