[[client-upgrades-uyuni]]
= 升级 Uyuni 客户端
:description: 通过添加通道、同步存储库和升级软件包来配置 Uyuni 客户端；确保所有更改成功同步
:revdate: 2025-02-26
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

在本节中，我们以 openSUSE Leap 为例。

== 准备升级


.过程：升级准备客户端升级
. 在 {productname} 服务器的命令提示符处，以 root 用户身份，使用 `spacewalk-common-channels` 命令添加相应的通道。
+
----
spacewalk-common-channels \
opensuse_leap15_4 \
opensuse_leap15_4-non-oss \
opensuse_leap15_4-non-oss-updates \
opensuse_leap15_4-updates \
opensuse_leap15_4-uyuni-client
----

. 将所有通道与 `spacewalk-repo-sync` 完全同步。
+
// These are custom channels.
// For more information, see xref:client-configuration:clients-opensuse.adoc[].

. 在 {productname} 服务器 {webui} 中，导航到 menu:软件[管理 > 通道] 并单击 `Uyuni Client Tools for openSUSE Leap 15.4 (x86_64)` 通道名称。

. 在右上角单击 btn:[管理通道]。

. 单击 `Repositories` 选项卡，然后选择 `External - Uyuni Client Tools for openSUSE Leap 15.3 (x86_64)`。

. 单击 btn:[更新存储库]。

. 导航到 menu:存储库[同步] 子选项卡，并单击 btn:[立即同步]。

. 对 `openSUSE Leap 15.4 (x86_64)` 和 `External - openSUSE Leap 15.3 (x86_64)` 执行相同的操作。

展开 `openSUSE Leap 15.4 (x86_64)` 以查看所有填充了软件包的子通道。



== 升级

要升级客户端，您需要替换软件储存库，然后更新软件，最后重引导客户端。



.过程：升级升级客户端

. 在 {productname} 服务器 {webui} 中，导航到 menu:系统[]，并单击客户端的名称。
. 单击 menu:软件[软件通道]，并将基础通道选择为在 `Customs Channels` 列表中列出的 openSUSE Leap {opensuse-version} 通道。
. 在 `Child Channels` 窗格中，选择 {opensuse-version} 子通道。
. 单击 btn:[下一步]，然后 `Confirm Software Channel Change` 在 btn:[确认] 中。
. 单击 menu:软件[软件包 > 升级]，选择要在客户端上更新的所有软件包，然后应用选择。
  单击 btn:[升级软件包]，检查详细信息，然后单击 btn:[确认] 以完成更新。
. 重引导客户端。

如果您需要更新多个客户端，可以在 {productname} 服务器上创建此命令序列的操作链。
您可以使用操作链同时对多个客户端执行更新。


////
. Assign the new channels to the clients instead of the old channels.

. Update all the packages.  This can either be done with the {webui} or better run `zypper dup` manually on the command line local on the systems or remotely as a Salt command.
////

////
I think the better way to document this is if giving it a try. Create an Uyuni server, sync Leap 15.1 (spacewalk-common-channels), create a Leap 15.1, onboard it, sync Leap 15.2 (spacewalk-common-channels), and then try to adjust the channels and trying to upgrade. I recommend you use VMs and take snapshots of the VMs so you can repeat steps as needed.
////

////
But for now you need to create and mirror at least the target channels with spacewalk-common-channels.

You adjust the channels for the client and best is to call "zypper dup". Either from the commandline on that system or using remote command.
////
