[[package-management]]
= 软件包管理
:description: 使用SUSE Multi-Linux Manager用户界面配置和管理客户端上的软件包，通过导航系统、选择客户端以及访问软件。
:revdate: 2024-11-21
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

客户端使用软件包来安装、卸装和升级软件。

// available subtabs:
//     List / Remove
//     Upgrade
//     Install
//     Lock / Unlock
//     Profiles
//     Non Compliant


要管理客户端上的软件包，请导航到 `Systems`，单击要管理的客户端，然后导航到 menu:系统[软件 > 软件包] 子选项卡。
本节中可用的选项取决于您所选择的客户端类型及其当前的频道订阅。

大多数软件包管理操作可以添加到操作链中。
有关操作链的更多信息，请参见 xref:reference:schedule/action-chains.adoc[]。


[IMPORTANT]
==== 

安装或升级软件包时，将自动接受许可证或 EULA。
====


== 使用配置文件比较软件包


您可以将客户端上安装的软件包与存储的控制文件进行比较，或与另一个客户端上安装的软件包进行比较。
进行比较时，您可以选择修改所选客户端以匹配。

要将软件包与控制文件进行比较，您需要存储一个控制文件。
控制文件是从当前安装的客户端上的软件包创建的。
创建控制文件后，您可以使用它来安装更多具有相同软件包的客户端。


.过程：升级创建存储的控制文件
. 在 {productname} {webui} 中，导航到 `Systems`，单击用作基准的客户端，然后导航到 menu:系统[软件 > 软件包 > 控制文件] 子选项卡。
. 单击 btn:[创建系统控制文件]。
. 键入您的控制文件的名称和说明，然后单击 btn:[创建控制文件]。


.过程：升级比较客户端软件包
. 在 {productname} {webui} 中，导航到 `Systems`，单击要比较的客户端，然后导航到 menu:系统[软件 > 软件包 > 控制文件] 子选项卡。
    要与存储的控制文件进行比较，请选择该控制文件并单击 btn:[比较]。
. 要与其他客户端进行比较，请选择客户端名称并单击 btn:[比较] 以查看两个客户端之间差异的列表。



[[package-management-orphaned-packages]]
== 孤立的软件包

孤立的软件包是由 {productname} 同步的，但未与软件频道关联的软件包。
因此，孤立的软件包通常对 {productname} 客户端不可用，用户无法在没有额外努力的情况下安装此类软件包。

软件包可能会由于以下事件而变为孤立状态：

* 同步的储存库会删除一个软件包。
  默认情况下，{productname} 会将该软件包从通道中取消链接，但不会删除该软件包。
* 储存库使用新版本取代了某个软件包，因而去除了之前的版本。
* 储存库同步流程被中断（例如，由于发生空间用尽异常），因此下载的软件包与任何通道都不关联。
* 用户手动上载了软件包，但未将其与任何通道关联。

孤立的软件包占用用户环境的空间，并且由于未与通道关联，无法轻易分发给客户端。
孤立的软件包在特定工作流程中可能是有意义的，例如启动或客户特定的程序。

您可以在 {webui} 中通过单击 menu:软件[管理> 软件包> 查看不在任何通道中的软件包] 来查看孤立的软件包。

{productname} 定期运行一个 Taskomatic 作业，搜索孤立的软件包并将软件包组织 ID 修改为 1。
这意味着您只能在任务自动化作业执行后删除孤立的软件包。
如果您遇到无法删除的孤立软件包，请等待 24 小时再尝试删除。

// .Procedure: Deleting orphaned packages

删除孤立的软件包：

// * With the UI (FIXME is this possible?  How?

* 使用针对单个软件包的命令行工具。例如：
+
----
spacecmd package_remove zypper-1.14.52-150400.1.9.x86_64
----

* 使用同时针对所有孤立软件包的命令行工具：
+
----
spacecmd package_removeorphans
----
