[[power-management]]
= 电源管理
:description: 使用支持 IPMI 和 Redfish 协议的 SUSE Multi-Linux Manager Web UI 配置客户端的电源管理，该 UI 由 Cobbler 控制文件管理。
:revdate: 2024-11-21
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

== 简介


您可以使用 {productname} {webui} 打开、关闭和重启客户端。

此功能使用 IPMI 或 Redfish 协议，并通过 {cobbler} 控制文件进行管理。
所选客户端必须具有支持这些协议之一的电源管理控制器。

对于 Redfish，请确保您可以在客户端和 {productname} 服务器之间建立有效的 SSL 连接。
您必须信任用于签署 Redfish 管理控制器的 SSL 服务器证书的证书颁发机构。
CA 证书必须采用 `.pem` 格式，并存储在 {productname} 服务器的 `/etc/pki/trust/anchors/` 上。
保存证书后，运行 `update-ca-certificate`。


.过程：升级启用电源管理
. 在 {productname} {webui} 中，导航到 menu:系统[系统列表]，选择您要管理的客户端，然后导航到 menu:配置[电源管理] 选项卡。
. 在 `Type` 字段中，选择要使用的电源管理协议。
. 填写电源管理服务器的详细信息，然后单击要执行的操作的相应按钮，或者单击 btn:[仅保存] 以保存详细信息而不执行任何操作。

您可以通过将多个客户端添加到系统集管理器来同时应用电源管理操作。
有关使用系统集管理器的更多信息，请参见 xref:client-configuration:system-set-manager.adoc[]。



== 电源管理和 {cobbler}

第一次使用电源管理功能时，如果客户端尚不存在，则会自动创建一个 {cobbler} 系统记录。
这些自动创建的系统记录无法通过网络启动，并包含对虚拟系统映像的引用。
这是必要的，因为 {cobbler} 当前不支持没有控制文件或映像的系统记录。

{cobbler} 电源管理使用 fence-agent 工具来支持除 IPMI 之外的协议。
仅支持 {productname} 的 IPMI 和 Redfish 协议。
您可以在 `rhn.conf` 配置文件中，通过将 fence-agent 名称以逗号分隔的列表形式添加到 `java.power_management.types` 配置参数中，配置您的客户端使用其他协议。
