[[system-locking]]
= 系统锁定
:description: 学习如何使用系统锁定防止客户端发生操作，并了解软件包锁定提升软件包安全性的好处。
:revdate: 2024-11-21
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

系统锁定用于防止客户端发生操作。
例如，系统锁定可以防止客户端被更新或重启。
这对于运行生产软件的客户端非常有用，或者可以防止意外更改。
当您准备执行操作时，可以禁用系统锁定。



== 客户端上的系统锁


当客户端被锁定或进入黑屏模式时，无法安排任何操作，执行命令被禁用，并且在 `System Details` 页面上显示黄色横幅。
在此模式下，可以使用{webui}或API为锁定的客户端安排操作，但操作会失败。


[NOTE]
====
锁定机制不适用于{salt} SSH客户端。
====



.过程：升级客户端系统锁定
. 在 {productname} {webui} 中，导航到您想要锁定的客户端的 `System Details` 页面。
. 导航到 `Formulas` 选项卡，选中系统锁定公式，然后单击 btn:[保存]。
. 导航到 menu:公式[系统锁定] 选项卡，选中 `Lock system`，然后单击 btn:[保存]。
    在此页面上，您也可以在客户端处于锁定状态时启用特定的 Salt 模块。
. 进行更改后，您可能需要应用 highstate。
    在这种情况下，{webui}中的横幅会通知您。
    客户端保持锁定状态，直到您去除系统锁定公式。

有关{salt}中黑屏模式的更多信息，请参见 https://docs.saltproject.io/en/latest/topics/blackout.。



== 软件包锁

软件包锁定可以在多个客户端上使用，但提供的功能集不同。
您必须区分{sle}和{opensuse}（基于zypp）与{rhel}或{debian}客户端。



=== 基于 Zypp 的系统上的软件包锁

软件包锁定用于防止未经授权的安装或升级软件包。
当软件包被锁定时，会显示一个挂锁图标，表示无法安装。
任何尝试安装锁定软件包的行为都会在事件日志中报告为错误。

锁定的软件包无法通过 {productname} {webui} 安装、升级或去除，也无法通过客户端机器上的软件包管理器直接进行操作。
锁定的软件包也会间接锁定任何依赖的软件包。


.过程：升级使用软件包锁定
. 在受管系统上导航到 menu:软件[软件包> 锁定]选项卡以查看所有可用软件包的列表。
. 选择要锁定的软件包，然后单击 btn:[请求锁定]。
  选择锁定生效的日期和时间。
  默认情况下，锁定会尽快生效。
  请注意，锁定可能不会立即生效。
. 要去除软件包锁，请选择要解锁的软件包，然后单击 btn:[请求解锁]。
  选择日期和时间，与激活锁定时相同。



=== 在 {rhel}- 和 {debian}- 类似系统上的软件包锁定

[NOTE]
====
一些 {rhel}- 和 {debian}- 类似系统在客户端上提供软件包锁定功能。
====

在 {rhel}- 和 {debian}- 类似系统上，软件包锁定仅用于防止对软件包进行未经授权的升级或去除。
当软件包被锁定时，会显示一个挂锁图标，表示该软件包无法更改。
任何尝试更改锁定软件包的行为都会在事件日志中报告为错误。

锁定的软件包无法升级或去除，也无法通过 {productname} {webui} 进行操作，也无法通过客户端机器上的软件包管理器直接进行操作。
锁定的软件包也会间接锁定任何依赖的软件包。


.过程：升级使用软件包锁定
. 在 {rhel} 的 7 个系统上安装 `yum-plugin-versionlock`，在 {rhel} 的 8 或 9 个系统上将 `python3-dnf-plugin-versionlock` 安装为 `root`。
  在 {debian} 系统上，`apt` 工具包含锁定功能。
. 在受管系统上导航到 menu:软件[软件包> 锁定]选项卡以查看所有可用软件包的列表。
. 选择要锁定的软件包，然后单击 btn:[请求锁定]。
  选择锁定生效的日期和时间。
  默认情况下，锁定会尽快生效。
  请注意，锁定可能不会立即生效。
. 要去除软件包锁，请选择要解锁的软件包，然后单击 btn:[请求解锁]。
  选择日期和时间，与激活锁定时相同。
