== {sles} {bci-mlm} 호스트 준비


또는 {productname}을(를) {sles} {bci-mlm}에 배포할 수 있습니다.

다음 절차에서는 설치 과정의 주요 단계를 설명합니다.


=== {sles}에 {productname} 확장 설치

.절차: {sles}에 {productname} 확장 설치
[role=procedure]
____

. https://www.suse.com/download/sles/[]에서 {sles} {bci-mlm} [literal]``.iso``를 찾아 다운로드합니다.

. {sles} {bci-mlm} 설치를 시작합니다.

.. On the [literal]``Language, keyboard and product selection`` select the product to install.

.. [literal]``라이선스 계약``에서 계약서를 읽고 [guimenu]``라이선스 약관에 동의합니다``에 체크 표시합니다.

. Skip the registration.

. [systemitem]``다음``을 클릭하여 계속합니다.

+

[IMPORTANT]
====
Please note that for {sles} {bci-mlm}, you are required to have a valid {sles} subscription configured on the server.
====

. In the screen [literal]``Extensions and Modules Selection`` check the following:

+

  * Basesystem Module
  * Containers Module

. btn:[다음]을 클릭하여 계속합니다.

. 설치를 완료합니다.

. When the installation completes, log in to the newly installed server as root.

. Update the System (optional, if the system was not set to download updates during install):

+

[source, shell]
----
zypper up
----

. 재부팅합니다.

____
