[[ref-users-details]]
= User Details

The [guimenu]``User Details`` section provides additional details about the user account, and allows you to manage permissions for the user.
You can also deactivate or delete users from this section.

For more information about managing users, see xref:administration:users.adoc[].

The [guimenu]``User Details`` section is split into tabs:



== Details

This tab allows you to change the name and password of the user account, and provides information about the various permissions the user has assigned.

Use this section to assign or remove administrator roles, except for the {productname} Administrator.
To change a user's {productname} Administrator role, navigate to menu:Admin[Users] and check or uncheck [guimenu]``{productname} Admin?`` as required.



== System Groups

This tab shows the system groups the user is assigned to.
Check or uncheck system groups as required.



== Systems

This tab shows the clients the user is able to administer.
Use system groups to modify client access levels.

Select multiple systems from this page to add them to the system set manager (SSM).
For more information about SSM, see xref:client-configuration:system-set-manager.adoc[].



== Channel Permissions

This tab shows the channel permissions for the user.

The [guimenu]``Subscription`` subtab shows channels that the user has subscription permissions for.
The [guimenu]``Management`` subtab shows channels that the user has management permissions for.

Check channels in the list to grant permissions.



== User Preferences

This tab is used to configure preference settings for users.


[[user-preferences]]
.User Preferences
[cols="1,1,1", options="header"]
|===
| Option                | Description   | Default
| Email Notification    | Receive email for client and Taskomatic notifications, including a daily summary email. | Checked
| {productname} List Page Size | Maximum number of items that can appear in a list on a single page. | 25 entries
| "Overview" Start Page | Select the information panes to display on the menu:Home[Overview] page. | All checked
| Time Zone             | Set your local timezone. | System timezone
| CSV Files             | Select whether to use comma or semi-colon delimiters when producing downloadable CSV files. | Comma
|===



== Addresses

This tab shows the mailing addresses associated with the user.
Click btn:[Fill in this address] to set a mailing address.
Click btn:[Edit this address] to change an existing mailing address.