[[quickstart-publiccloud-clients]]
= Register Clients

When you have your {productname} Server set up, you are ready to start registering clients.



.Procedure: Registering Clients with the {webui}

. In the {productname} {webui}, navigate to menu:Systems[Bootstrapping].
. In the [guimenu]``Host`` field, type the fully-qualified domain name (FQDN) of the client to be bootstrapped.
. In the [guimenu]``SSH Port`` field, type the SSH port number to use to connect and bootstrap the client.
By default, the SSH  port is [systemitem]``22``.
. In the [guimenu]``User`` field, type the username to log in to the client.
By default, the username is [systemitem]``root``.
. In the [guimenu]``Password`` field, type password to log in to the client.
. In the [guimenu]``Activation Key`` field, select the activation key that is associated with the software channel you want to use to bootstrap the client.
For more information, see xref:client-configuration:clients-and-activation-keys.adoc[].
. OPTIONAL: In the [guimenu]``Proxy`` field, select the proxy to register the client to.
. By default, the [guimenu]``Disable SSH Strict Key Host Checking`` checkbox is selected.
This allows the bootstrap process to automatically accept SSH host keys without requiring you to manually authenticate.
. OPTIONAL: Check the [guimenu]``Manage System Completely via SSH`` checkbox.
If you check this option, the client will be configured to use SSH for its connection to the server, and no other connection method will be configured.
. Click btn:[Bootstrap] to begin registration.

When the bootstrap process has completed, your client will be listed at menu:Systems[System List].


* If you want more control over the process, have to register many clients, or are registering traditional clients, we recommend that you create a bootstrap script.
For more information, see xref:client-configuration:registration-bootstrap.adoc[].
* For Salt clients and even more control over the process, executing single commands on the command line can be useful.
For more information, see xref:client-configuration:registration-cli.adoc[].



== Activation Keys

Activation keys are used with traditional and Salt clients to ensure that your clients have the correct software entitlements, are connecting to the appropriate channels, and are subscribed to the relevant groups.
Each activation key is bound to an organization, which you can set when you create the key.

.Procedure: Creating an Activation Key
. In the {productname} {webui}, as an administrator, navigate to menu:Systems[Activation Keys].
. Click the btn:[Create Key] button.
. On the [guimenu]``Activation Key Details`` page, in the [guimenu]``Description`` field, enter a name for the activation key.
. In the [guimenu]``Key`` field, enter the distribution and service pack associated with the key.
For example, ``SLES12-SP4`` for {sles}{nbsp}12{nbsp}SP4.
+
[IMPORTANT]
====
Do not use commas in the [guimenu]``Key`` field for any {suse} products.
However, you *must* use commas for Red Hat Products.
For more information, see xref:reference:systems/activation-keys.adoc[].
====
+
. In the [guimenu]``Base Channels`` drop-down box, select the appropriate base software channel, and allow the relevant child channels to populate.
For more information, see xref:reference:admin/setup-wizard.adoc#vle.webui.admin.wizard.products[] and xref:administration:custom-channels.adoc[].
. Select the child channels you need (for example, the mandatory {susemgr} tools and updates channels).
. We recommend you leave the [guimenu]``Contact Method`` set to [guimenu]``Default``.
. We recommend you leave the [guimenu]``Universal Default`` setting unchecked.
. Click btn:[Create Activation Key] to create the activation key.
. Check the [guimenu]``Configuration File Deployment`` check box to enable configuration management for this key, and click btn:[Update Activation Key] to save this change.

[NOTE]
====
The [guimenu]``Configuration File Deployment`` check box does not appear until after you have created the activation key.
Ensure you go back and check the box if you need to enable configuration management.
====

For more on activation keys, see xref:client-configuration:clients-and-activation-keys.adoc[].



== System Set Manager

To make managing large sets of clients easier, add them to the system set manager (SSM).

System Set Manager (SSM) is used to administrate groups of systems, rather than performing actions on one system at a time.
It works for both Salt and traditional clients.

For a complete list of the tasks that you can perform with the SSM, see xref:reference:systems/ssm-menu.adoc[].

You need to select which systems or system group you want to work with before you can use SSM to perform operations.

You can access SSM in three different ways:

* Navigate to menu:Systems[System List], select systems you want to work with, and navigate to menu:Systems[System Set Manager].
* Navigate to menu:Systems[System Groups], and click btn:[Use in SSM] for the system group you want to work with.
* Navigate to menu:Systems[System Groups], select the group you want to work with, and click btn:[Work with Group].

For more on SSM, see xref:client-configuration:using-ssm.adoc[].