[[quickstart-publiccloud-install]]
= Installation

Public Cloud providers pre-install {productname}, so you do not need to perform any installation steps.
However, {productname} Server needs to be registered with {scc} to receive updates before you can sign in.


Follow the cloud providers instructions to SSH into the instance.

Run this command to start set up:

----
yast2 susemanager_setup
----

Follow the prompts, and wait for the setup to finish.

For detailed instructions on setting up {productname} with {yast}, see xref:installation:server-setup.adoc[].

Register your instance with {scc}, using this command:

----
sudo SUSEConnect -r <Registration_Number>
----

You can get your registration number by logging in to {scc} from your browser.

When you have registered, all {sle} modules will be activated.
You will also need to activate the Public Cloud module.
Do this from the command prompt on your instance:

----
SUSEConnect -p sle-module-public-cloud/15.1/x86_64
----

For more information on activating public clouds, see xref:installation:pubcloud-setup.adoc[].


Log in to the {productname} {webui} with a web browser, using an address like this:

----
https://<public_IP>
----

Log in to the {productname} {webui} with the administrator account.
The username and password varies depending on your provider.

.Default Administrator Account Details
[cols="1,1,1", options="header"]
|===
| Provider              | Default Username  | Default Password
| Amazon EC2            | ``admin``         | ``<instance-ID>``
| Google Compute Engine | ``admin``         | ``<instance-ID>``
| Microsoft Azure       | ``admin``         |``<instance-name>-suma``
|===

[IMPORTANT]
====
When you have logged in to the administrator account for the first time, change the default password to protect your account.
====


Add the required software products to your client, and schedule a repository synchronization.



.Procedure: Adding the openSUSE Channels

. At the command prompt on the {productname} Server, as root, install the [systemitem]``spacewalk-utils`` package:
+
----
zypper in spacewalk-utils
----
. Add the openSUSE channels.
+
----
spacewalk-common-channels \
opensuse_leap15_1 \
opensuse_leap15_1-non-oss \
opensuse_leap15_1-non-oss-updates \
opensuse_leap15_1-updates \
opensuse_leap15_1-uyuni-client
----

. Synchronize the new custom channels.

[IMPORTANT]
====
You need all the new channels fully synchronized before bootstrapping any openSUSE client.
openSUSE channels can be very large.
Synchronization can sometimes take several hours.
====

To synchronize, navigate to menu:Software[Manage > Channels], and for each channel you created, click it and:

. Navigate to the [guimenu]``Repositories`` tab.
. Navigate to the [guimenu]``Sync`` sub-tab, and click btn:[Sync Now] to begin synchronization immediately.

You can also schedule synchronization from this screen.

endif::[]


If you are using {ubuntu} or {rhel} clients, you will need to set up custom repositories and channels.
For more information, see xref:client-configuration:non-suse-clients.adoc[].
