[[quickstart-publiccloud-install]]
= Installation

Public Cloud providers pre-install {productname}, so you do not need to perform any installation steps.
However, {productname} Server needs to be registered with {scc} to receive updates before you can log in.

For detailed instructions on registering {productname} to {scc}, see xref:installation:server-setup.adoc[].

When you have registered, all {sle} modules will be activated.
You will also need to activate the public cloud module.
For more information on activating public clouds, see xref:modules/installation/pages/pubcloud-setup.adoc[].

An administrator account is created by default.
The username and password varies depending on your provider.

.Default Administrator Account Details
[cols="1,1,1", options="header"]
|===
| Provider              | Default Username  | Default Password
| Amazon EC2            | ``admin``         | ``<instance-ID>``
| Google Compute Engine | ``admin``         | ``<instance-ID>``
| Microsoft Azure       | ``admin``         |``<instance-name>``-suma
|===

[IMPORTANT]
====
When you have logged in to the administrator account for the first time, change the default password to protect your account.
====
