[[quickstart-publiccloud-setup]]
= Setting Up

We have tested these instructions on Amazon EC2, Google Compute Engine, and Microsoft Azure, but they should work on other providers as well, with some variation.

You need to start by logging in to your chosen public cloud provider, and launching a {productname} instance.

Depending on the public cloud you are using, you can usually locate the {productname} Server images by searching for ``suse manager``.
In EC2, you need to search within the Community AMIs.
In GCE and Azure, search the marketplace.

As you prepare your new instance, pay attention to these settings:

For hardware, select an instance with at least:

* 32{nbsp}GB RAM
* 8 cores

For more information about hardware requirements, see xref:installation:hardware-requirements.adoc[].

For network security and access settings, you need to enable HTTPS access.
This allows you to access the {productname} {webui}.

In EC2 and Azure, create a new security group, and add inbound and outbound rules for HTTPS.
In GCE, check the ``Allow HTTPS traffic`` box under the ``Firewall`` section.

[WARNING]
====
When running {productname} on public clouds, make sure you apply security measures to limit access to the right people.
A world-accessible {productname} would give access to your infrastructure to anyone, and could breach your {suse} support agreement.
====

For storage settings, ensure the root volume of the {productname} Server is 100{nbsp}GB or larger.
Add an additional storage disk of 500{nbsp}GB or more, and choose SSD storage if you can.
The cloud images for {productname} Server use a script to assign this separate volume when your instance is launched.
The name of the device node varies depending on your provider, and the instance type you selected.

When you launch your instance, you can log in to the {productname} Server and use this command to find all available storage devices:

----
hwinfo --disk | grep -E "Device File:"
----

If you are not sure which device to choose, use the [command]``lsblk`` command to see the name and size of each device.
Choose the name that matches with the size of the virtual disk you are looking for.

You can set up the external disk with the [command]``suma-storage`` command.
This creates an XFS partition mounted at ``/manager_storage`` and uses it as the location for the database and repositories:

----
/usr/bin/suma-storage <devicename>
----

For more information about setting up a public cloud instance, see xref:installation:pubcloud-requirements.adoc[].
