[[installation-proxy-containers-k3s]]
= {productname} {productnumber}  Proxy Deployment on K3s
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]


[[installation-proxy-containers-k3s-k3s]]
== Installing K3s

[NOTE]
====
{productname} Proxy is supported on K3s running on top of {sle-micro} in a single node cluster.
If you need to deploy it in any other Kubernetes environment, please contact support for evaluation.
====

On the container host machine, install [literal]``K3s`` (replace [literal]``<K3S_HOST_FQDN>`` with the FQDN of your K3s host):

----
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san=<K3S_HOST_FQDN>" sh -
----

[[installation-proxy-containers-k3s-helm]]
== Installing Tools

The installation requires the [literal]``mgrpxy`` and [literal]``helm`` packages.

The [literal]``mgrpxy`` and ``helm`` packages are available in the {productname} Proxy product repositories.

. To install it run:
+
----
transactional-update pkg install helm mgrpxy
----

. Reboot

include::../generate_proxy_config.adoc[tags=generate-proxy-config-section]


[[installation-proxy-containers-k3s-deploy]]
== Deploying the {productname} Proxy Helm Chart

To configure the storage of the volumes to be used by the {productname} Proxy pod, define persistent volumes for the following claims.
If you do not customize the storage configuration, K3s will automatically create the storage volumes for you.

The persistent volume claims are named:

* [literal]``squid-cache-pv-claim``
* [literal]``package-cache-pv-claim``
* [literal]``tftp-boot-pv-claim``

Create the configuration for the {productname} Proxy as documented in xref:installation-and-upgrade:container-deployment/suma/proxy-deployment-suma.adoc[].
Copy the configuration [literal]``tar.gz`` file and then install:

----
mgrpxy install kubernetes /path/to/config.tar.gz
----

For more information see link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[] (kubernetes) or link:https://rancher.com/docs/k3s/latest/en/storage/[] (K3s) documentation.
