[[installation-proxy-containers]]
= {productname} {productnumber} Proxy Deployment
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]


This guide outlines the deployment process for the {productname} {productnumber} Proxy.
This guide presumes you have already successfully deployed a {productname} {productnumber} Server.

[IMPORTANT]
====
{sle-micro} is only supported as regular minion ([systemitem]``default`` contact method) for the time being.
We are working on managing it as Salt SSH client ([systemitem]``salt-ssh`` contact method), too.
====


To successfully deploy, you will perform the following actions:


// Add certificate tasks item
.Procedure: Deploying Proxy
. Review hardware requirements.
. Synchronize the {sle-micro} {microversion} parent channel and the proxy extension child channel on the server.
. Install {sle-micro} {microversion} on a bare-metal machine.
. During the installation, register {sle-micro} {microversion} along with the {productname} Proxy extension.
. Create a {salt} activation key.
. Bootstrap the proxy as a client with the [systemitem]``default`` connection method.
. Generate a proxy configuration.
. Transfer the proxy configuration from server to proxy.
. Use the proxy configuration to register the client as a proxy with {productname}.


.Supported operating system for the Proxy Container Host
[NOTE]
====
The supported operating system for the container host are {sle-micro} {microversion} and {sles} {bci-suma}.

Container host::
A container host is a server equipped with a container engine like Podman, which lets it manage and deploy containers.
These containers hold applications and their essential parts, such as libraries, but not a full operating system, making them lightweight.
This setup ensures applications run the same way in different environments.
The container host supplies the necessary resources such as CPU, memory, and storage for these containers.
====


== Hardware Requirements for the Proxy


For more information about hardware requirements for deploying {productname} Proxy, see xref:installation-and-upgrade:hardware-requirements.adoc#proxy-hardware-requirements[].



== Synchronize the Parent and Proxy Extension Child Channels

This section presumes that you have already entered your organization credentials under the menu:Admin[Setup Wizard -> Organization Credentials] in the server's {webui}.
Products are listed on the menu:Admin[Setup Wizard -> Products] page.
This channel must be fully synchronized on the server, with the child channel [systemitem]``Proxy`` as an extension option selected.


.Procedure: Synchronizing the Proxy Parent Channel and Proxy Extension
. In the {productname} {webui} select menu:Admin[Products].
. From the products page enter {sle-micro} in the filter field.
. Next use the drop-down to select the required architecture.
  For this example {x86_64}.
. In the [systemitem]``Product Description`` field select the {sle-micro} {microversion} checkbox then use the drop-down to select the [systemitem]``SUSE Manager Proxy Extension 5.0 x86_64`` extension.
. Click the btn:[Add products] button.
. Wait for the synchronization to complete.



== Deploy {productname} Proxy on {sle-micro} {microversion}

.Procedure: Downloading the Installation Media
. Locate the {sle-micro} {microversion} installation media at https://www.suse.com/download/sle-micro/.
. You will need an account with {scclongform} and must be logged in to download the ISO.
. Download [filename]``SLE-Micro-5.5-DVD-x86_64-GM-Media1.iso``.
. Prepare a USB flash disk or DVD for installation.
. Insert a DVD or a bootable USB stick containing the installation image for {sle-micro} {microversion}.
. Boot or reboot your system.


For detailed documentation on preparing your machines OS (virtual or physical), see link:https://documentation.suse.com/sle-micro/5.5/html/SLE-Micro-all/book-deployment-slemicro.html[{sle-micro} {microversion} Deployment Guide].


.Procedure: Installing {sle-micro} {microversion}
. Use the arrow keys to select [systemitem]``Installation``.
. Adjust Keyboard and language.
  Click the [systemitem]``checkbox`` to accept the license agreement.
. Click [systemitem]``Next`` to continue.
. Select your registration method.
  For this example, we will register the proxy with {scclongform}.
. Enter your {scclongform} Email address.
. Enter your registration code for {sle-micro} {microversion}.
. Click [systemitem]``Next`` to continue.
. On the [systemitem]``Extension and Module Selection`` page uncheck the **Hide Development Versions** checkbox.
. Select the {productname} {productnumber} Proxy extension [systemitem]``Checkbox``.
. Click [systemitem]``Next`` to continue.
. Enter your {productname} {productnumber} Proxy extension registration code.
. Click btn:[Next] to continue.
. On the [systemitem]``NTP Configuration`` page click btn:[Next].
. On the [systemitem]``Authentication for the System`` page enter a password for the root user.
  Click btn:[Next].
. On the [systemitem]``Installation Settings`` page click btn:[Install].

This finalizes installation of {sle-micro} {microversion} and {productname} {productnumber} Proxy as an extension.



=== Update the System


.Procedure: Updating the System
. Log in as *root*.
. Run **transactional-update**:

+

[source, shell]
----
transactional-update
----

. Reboot the system.
. Log in as root.
. Install the container utilities:

+

[source, shell]
----
transactional-update pkg install mgrpxy mgrpxy-bash-completion
----

+

Alternatively you may install [systemitem]``mgrpxy-zsh-completion`` or [systemitem]``mgrpxy-fish-completion``.

+

. Reboot the system.

== Deploy {productname} Proxy on {sles} {bci-suma}

Alternatively, you can install {productname} Proxy on {sles} {bci-suma}.
The following procedure describes the main steps of the installation process.

.Procedure: Installing {productname} Proxy on {sles} {bci-suma}
. Locate and download {sles} {bci-suma} [literal]``.iso`` at https://www.suse.com/download/sles/.
. Make sure that the {scc} code you plan to use has the Extensions enabled.
. Start the installation of {sles} {bci-suma}.
  .. On the [literal]``Language, keyboard and product selection`` select the product to install.
  .. On the [literal]``License agreement`` read the agreement and check [guimenu]``I Agree to the License Terms``.
. Select the registration method.
. In the screen [literal]``Extensions and Modules Selection`` check the following:
  * {productname} Proxy Extension
  * Basesystem Module
  * Containers Module
. Complete the installation.
. When the installation completes, log in to the newly installed server as root.
. As root, run

+

[source,shell]
----
zypper install podman mgrpxy mgrpxy-bash-completion
----

== Configure Custom Persistent Storage

This step is optional.
However, if custom persistent storage is required for your infrastructure, use the [command]``mgr-storage-proxy`` tool.
This tool simplifies creating the container storage and Squid cache volumes.

Use the command in the following manner:

[source,shell]
----
mgr-storage-proxy <storage-disk-device>
----

For example:

[source, shell]
----
mgr-storage-proxy /dev/nvme1n1
----

For more information, type:

[source, shell]
----
mgr-storage-proxy --help
----


[NOTE]
====
This command will create the persistent storage volumes at [path]``/var/lib/containers/storage/volumes``.

For more information, see

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]
====

include::../actkey-bootstrap-proxy-suma.adoc[]

include::../generate_proxy_config.adoc[]

include::../transfer_proxy_config.adoc[]



[[proxy-setup-containers-transfer-start]]
== Start the {productname} Proxy

Container can now be started with the [literal]`mgrpxy` command:

[[proc-setup-containers-setup-start]]
.Procedure: Starting and Checking Proxy Status

. Start the proxy by calling:

+

----
mgrpxy start
----

. Check container status by calling:

+

----
mgrpxy status
----

+

Five {productname} Proxy containers should be present and should be part of the [literal]``proxy-pod`` container pod:

* proxy-salt-broker
* proxy-httpd
* proxy-tftpd
* proxy-squid
* proxy-ssh



== Use a Custom Container Image for a Service

By default, the {productname} Proxy suite is configured to use the same image version and registry path for each of its services.
However, it is possible to override the default values for a specific service using the install parameters ending with [literal]``-tag`` and [literal]``-image``.

For example:

[source, shell]
----
mgrpxy install podman --httpd-tag 0.1.0 --httpd-image registry.opensuse.org/uyuni/proxy-httpd /path/to/config.tar.gz
----

It adjusts the configuration file for the httpd service, where [path]``registry.opensuse.org/uyuni/proxy-httpds`` is the image to use and [literal]``0.1.0`` is the version tag, before restarting it.

To reset the values to defaults, run the install command again without those parameters:

[source, shell]
----
mgrpxy install podman /path/to/config.tar.gz
----

This command first resets the configuration of all services to the global defaults and then reloads it.

