= Proxy Migration
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]


In {productname} 4.3, the proxy can be deployed using three different methods: RPM based, containerized running on podman or k3s.

In {productname} {productnumber}, management of the containerized proxy running with podman was re-designed and made simpler with the [command]``mgrpxy`` tool.
At the same time, RPM based support was removed, and only the containerized version running with podman or k3s is supported.

This section describes migrating from Proxy 4.3 using the [command]``mgrpxy`` tool.

[IMPORTANT]
====
An in-place migration from {productname} 4.3 to {productnumber} is unsupported.
The host operating system has changed from {sles} 15 SP4 to {sle-micro} {microversion} or {sles} {bci-suma}.

The traditional contact protocol is no longer supported in {productname} 5.0 and later.
Before migrating from {productname} 4.3 to {productnumber}, any existing traditional clients including the traditional proxies must be migrated to {salt}.

For more information about migrating to {salt} clients, see https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.html
====



== Deploy a New {productname} Proxy

Because in-place migration is not supported, the users must deploy a new {productname} proxy with a new FQDN.

For more information about installing {productname} Proxy, see xref:installation-and-upgrade:install-proxy.adoc[].

== Migrate Clients to the New Proxy

[IMPORTANT]
====
Before migrating the clients, ensure that the new proxy is already deployed and fully functional.
====

.Procedure: Migrating Client Between Proxies
. Log in to the {productname} Server {webui}.
. From the left navigation, select menu:Systems[Systems List].
. Navigate to the old 4.3 proxy page, and click the [guimenu]``Proxy`` tab.
. Select all systems to "SSM".
. From the left navigation, select menu:Systems[System Set Manager].
. Select the sub-menu menu:Misc[Proxy].
. From the drop-down select the new proxy to migrate to.
. Click btn:[Change Proxy].

All selected clients will now be migrated to the new proxy.
You can check the schedule progress to verify if all clients were successfully migrated.


After a few minutes, the clients will start to show up the new connection path.
When all clients have the connection path under the new proxy, the old 4.3 proxy system is not needed anymore and can be removed.
