[[install-vm-vmware]]
= {productname} {productnumber} Server Deployment as a Virtual Machine - VMware
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

This chapter provides the required Virtual Machine settings for deployment of {productname} {productnumber} as an Image.
VMware will be used as a sandbox for this installation.


// FIXME: make this and later sections a snippet or move it to a general
//        intro for both, KVM and VMware
== Available Images

[IMPORTANT]
====
The preferred method for deploying {productname} {productnumber} Server is to use one of the following available images.
All tools are included in these images greatly simplifying deployment.
====

Images for {productname} {productnumber} are available at link:https://www.suse.com/download/suse-manager/[{productname} {productnumber} VM images].

[NOTE]
====
For more information on preparing raw images, see:

* link:https://documentation.suse.com/en-us/sle-micro/5.5/single-html/SLE-Micro-deployment/#sec-raw-preparation[]
* link:https://documentation.suse.com/en-us/sle-micro/5.5/single-html/SLE-Micro-deployment/#cha-images-procedure[]

For additional information on the self install images, see:

* link:https://documentation.suse.com/en-us/sle-micro/5.5/single-html/SLE-Micro-deployment/#cha-selfinstal-procedure[]
====

.Available Server Images
[cols="3, 3", options="header"]
|===
| Architecture | Image Format

| aarch64| qcow2, vmdk

| x86_64  | qcow2, vmdk, raw, Self Installer

| ppc64le | raw, Self Installer

| s390x * | qcow2, raw
|===

__* Two storage options are available for s390x: CDL DASD and FBA.__





[[quickstart.sect.vmware.settings]]
== {productname} Virtual Machine Settings - VMware

This sections describes VMware configurations, focusing on the creation of an extra virtual disk essential for the {productname} storage partition within VMware environments.

.Procedure: Creating the VMware Virtual Machine

. Download {productname} Server [filename]``.vmdk`` file then transfer a copy to your VMware storage.

. Make a copy of uploaded [filename]``.vmdk`` file using VMware web interface.
  This will convert provided [filename]``.vmdk`` file to the format suitable for vSpere hypervisor.

. Create and name a new virtual machine based on the Guest OS Family [systemitem]``Linux`` and Guest OS Version {sle} 15 (64-bit).

. Add an additional [systemitem]``Hard Disk 2`` of 500 GB (or more).

. Configure RAM and number of CPUs (at least 16 GB RAM and 4 CPUs).

. Set the network adapter as required.

. Power on the VM, and follow firstboot dialogs (keyboard layout, license agreement, time zone, password for root).

. When installation completes log in as root.

. Proceed to the next section.



[[minimal.susemgr.prep]]
== Register {sl-micro} and {productname} {productnumber} Server

Before starting obtain your SUSE Manager Registration Code from SUSE Customer Center - https://scc.suse.com.

[NOTE]
====
The {sl-micro} {microversion} entitlement is included within the {productname} entitlement, so it does not require a separate registration code.
====

.Procedure: Registering {sl-micro} and {productname} {productnumber}
. Boot the virtual machine.
. Log in as `root`.
. Register {sl-micro} with SCC.
+

----
transactional-update register -r <REGCODE> -e <your_email>
----

. Reboot.

. Register {productname} {productnumber} with {scc}.
+

----
transactional-update register -p SUSE-Manager-Server/5.0/x86_64 -r <REGCODE>
----

. Reboot
. Update the system:
+

----
transactional-update
----

. If updates were applied reboot.

. This step is optional.
  However, if custom persistent storage is required for your infrastructure, use the [command]``mgr-storage-server`` tool.
** For more information, see [command]``mgr-storage-server --help``.
This tool simplifies creating the container storage and database volumes.

** Use the command in the following manner:
+

----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----
+
For example:
+
----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----
+
[NOTE]
====
This command will create the persistent storage volumes at [path]``/var/lib/containers/storage/volumes``.

For more information, see

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]
====
. Run the following command to deploy {productname}:
+

----
mgradm install podman <FQDN>
----
