= Migrating the {productname} Server to a Containerized Environment
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

// container host = new server = new server machine with the {productname} {productnumber} Server container(s)
// old server = {productname} 4.3 Server

// We need to figure out which SUMA versions prior to the container release can or should be migrated. Something like any version prior to yyyy.mm and later than.

To migrate a {productname} 4.3 Server to a container, you require a new machine with {sle-micro} 5.5 and [literal]``mgradm`` installed.


[IMPORTANT]
====
An in-place migration from {productname} 4.3 to 5.0 will remain unsupported because of the change of the underlying operating system from {sles} 15 SP4 to {sle-micro} {microversion}.

The traditional contact protocol is no longer supported in {productname} 5.0 and later.
Before migrating from {productname} 4.3 to {productnumber}, any existing traditional clients including the traditional proxies must be migrated to {salt}.

For more information about migrating traditional {productname} 4.3 clients to {salt} clients, see https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-migrate-traditional.html.
====



[IMPORTANT]
====
Self trusted GPG keys are not migrated.
GPG keys that are trusted in the RPM database only are not migrated.
Thus synchronizing channels with [command]``spacewalk-repo-sync`` can fail.

The administrator must migrate these keys manually from the 4.3 installation to the container host after the actual server migration.

1. Copy the keys from the 4.3 server to the container host of the new server.
2. Later, add each key to the migrated server with the command [command]``mgradm gpg add <PATH_TO_KEY_FILE>``.
====

The current migration procedure does not include functionality for renaming hostnames.
As a result, the fully qualified domain name (FQDN) of the new server will remain the same as that of the old server.
Additionally, the IP address must remain unchanged to ensure that the clients can contact the server.
After the migration, it will be necessary to manually update the DHCP and DNS records to point to the new server.


== Initial Preparation on the Old 4.3 Server



.Procedure: Initial preparation on the 4.3 server
. Stop the {productname} services:
+

----
spacewalk-service stop
----

. Stop the PostgreSQL service:
+

----
systemctl stop postgresql
----


== Prepare the SSH Connection

[IMPORTANT]
====
You need to have {sle-micro} 5.5 with [literal]``mgradm`` installed.
Do not pre-install {productname} on this server.
The migration process will take care of the server installation.
====

.Procedure: Preparing the SSH connection

. Ensure that for [systemitem]``root`` an SSH key exists on the new {productnumber} server.
  If a key does not exist, create it with:
+

----
ssh-keygen -t rsa
----

. The SSH configuration and agent should be ready on the new server for a passwordless connection to the 4.3 server.
+

[NOTE]
====
To establish a passwordless connection, the migration script relies on an SSH agent running on the new server.
If the agent is not active yet, initiate it by running [command]``eval $(ssh-agent)``.
Then add the SSH key to the running agent with [command]``ssh-add`` followed by the path to the private key.
You will be prompted to enter the password for the private key during this process.
====

. Copy the public SSH key to the {productname} 4.3 Server ([literal]``<oldserver.fqdn>``) with [command]``ssh-copy-id``.
  Replace [literal]``<oldserver.fqdn>`` with the FQDN of the 4.3 server:
+

----
ssh-copy-id <old server.fqdn>
----
+

The SSH key will be copied into the old server's [path]``~/.ssh/authorized_keys`` file.
For more information, see the [literal]``ssh-copy-id`` manpage.
+

// . This step is optional:
//   The migration script only uses the 4.3 server's FQDN in the SSH command.
//   This means that every other configuration required to connect, needs to be defined in the [path]``~/.ssh/config`` file.

. Establish an SSH connection from the new server to the old {productname} Server to check that no password is needed.
  Also there must not by any problem with the host fingerprint.
  In case of trouble, remove old fingerprints from the [path]``~/.ssh/known_hosts`` file.
  Then try again.
  The fingerprint will be stored in the local [path]``~/.ssh/known_hosts`` file.



== Perform the Migration

[IMPORTANT]
====
When planning your migration from {productname} 4.3 to {productname} 5.0, ensure that your target instance meets or exceeds the specifications of the old setup.
This includes, but is not limited to, [literal]``Memory (RAM)``, [literal]``CPU Cores``, [literal]``Storage``, and [literal]``Network Bandwidth``.
====

.Procedure: Performing the Migration
. This step is optional.
If custom persistent storage is required for your infrastructure, use the [command]``mgr-storage-server`` tool.
** For more information, see [command]``mgr-storage-server --help``.
This tool simplifies creating the container storage and database volumes.

** Use the command in the following manner:
+

----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----
+
For example:
+
----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----
+
[NOTE]
====
This command will create the persistent storage volumes at [path]``/var/lib/containers/storage/volumes``.

For more information, see xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[].
====
. Execute the following command to install a new {productname} server.
  Replace [literal]``<oldserver.fqdn>`` with the FQDN of the 4.3 server:
+

----
mgradm migrate podman <oldserver.fqdn>
----

. Migrate trusted SSL CA certificates.


[IMPORTANT]
====
Trusted SSL CA certificates that were installed as part of an RPM and stored on {productname} 4.3 in the [path]``/usr/share/pki/trust/anchors/`` directory will not be migrated.
Because {suse} does not install RPM packages in the container, the administrator must migrate these certificate files manually from the 4.3 installation after migration:


. Copy the file from the 4.3 server to the new server.
   For example, as [path]``/local/ca.file``.

. Copy the file into the container with:
+

----
mgradm cp /local/ca.file server:/etc/pki/trust/anchors/
----
====


[IMPORTANT]
====
After successfully running the [command]``mgradm migrate`` command, the {salt} setup on all clients will still point to the old 4.3 server.

To redirect them to the {productnumber} server, it is required to rename the new server at the infrastructure level (DHCP and DNS) to use the same Fully Qualified Domain Name and IP address as 4.3 server.
====

// uncomment when kubernetes support is added
//----
//mgradm migrate kubernetes <oldserver.fqdn>
//----
