[[lsd-hub-api]]
= Using the Hub XMLRPC API
:description: Connect to the XMLRPC API service on port 2830 using any compliant client library, managing logs saved in `/var/log/hub/hub-xmlrpc-api.log`, which are rotated
:revdate: 2026-05-21
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

The Hub XMLRPC API allows you to perform operations across multiple peripheral servers from a single endpoint.
The Hub connects to these peripheral servers using the connection details established via xref:specialized-guides:large-deployments/hub-online-sync.adoc[Hub Online Synchronization].
Ensure that your peripheral servers are correctly registered to the hub before attempting to use the XMLRPC API.

When XMLRPC API is running, connect to it through server FQDN at the location `/hub/rpc/api` using any XMLRPC-compliant client libraries.
For examples, see xref:specialized-guides:large-deployments/hub-auth.adoc[].

Logs are saved in ``/var/log/hub/hub-xmlrpc-api.log``.
Logs are rotated weekly, or when the log file size reaches the specified limit.
By default, the log file size limit is 10{nbsp}MB.
