[[connect.payg.instances]]
= {payg}インスタンスに接続する
:description: クラウドインスタンスをSUSE Multi-Linux Managerに接続して、追加の製品とリポジトリにアクセスします
:revdate: 2026-05-06
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

主要なパブリッククラウドプロバイダー（AWS、Azure）において、SUSEは：

* SLES、SLES for SAPなどのカスタマイズされた{payg}製品イメージを提供します
* として利用可能な製品のリポジトリをミラーリングするリージョンごとのRMTサーバを運用します{payg}

この文書では、既存の{payg}インスタンスを{productname}サーバに接続する方法を説明し、インスタンスからの認証情報収集に関する基本情報を提供します。
この接続の目的は、認証データを抽出し、{productname}サーバがクラウドRMTホストに接続できるようにすることです。
その後、{productname}サーバは、{scc}組織の認証情報で既に利用可能でないRMTホスト上の製品にアクセスできます。


{payg}機能を使用する前に、以下のことを確認してください：

* {payg}インスタンスが正しいSUSE製品イメージ（例：SLES、SLES for SAP、またはSLE HPC）から起動され、目的のリポジトリにアクセスできる

* {productname}サーバが直接またはバスチオン経由で{payg}インスタンス（理想的には同じリージョン内）に接続できる

* 基本的な{scc}アカウントが必要です。menu:Admin[セットアップウィザード> 組織の認証情報]に有効な{scc}認証情報を入力してください。このアカウントは、{payg}インスタンスに関係なく、起動するための{productname}クライアントツールにアクセスするために必要です。

* {payg}インスタンスを{productname}に起動すると、その{payg}リポジトリが無効になり、RMTサーバからデータをミラーリングした場所からリポジトリが追加されます。最終的な結果は、{payg}インスタンスが{productname}サーバ自体を通じてRMTサーバから同じリポジトリを取得することになります。もちろん、リポジトリは主にSCCから設定することもできます。



== {payg}インスタンスに接続する


[[proc-connecting-new-payg]]
.プロシージャ:新しい{payg}インスタンスに接続する
[role=procedure]
. {productname} {webui}で、menu:Admin[セットアップウィザード> {payg}]に移動し、btn:[追加する{payg}]をクリックします。
. `{payg} connection Description`ページセクションから開始します。
. `Description`フィールドに、説明を追加します。
. `Instance SSH connection data`ページセクションに移動します。
. `Host`フィールドに、{productname}から接続するインスタンスのDNSまたはIPアドレスを入力します。
. `SSH Port`フィールドに、ポート番号を入力するか、デフォルト値22を使用します。
. `User`フィールドに、クラウドで指定されているユーザー名を入力します。
. `Password`フィールドに、パスワードを入力します。
. `SSH Private Key`フィールドに、インスタンスのキーを入力します。
. `SSH Private Key Passphrase`フィールドに、キーのパスフレーズを入力します。

[IMPORTANT]
====
認証キーは常にPEM形式である必要があります。
====

インスタンスに直接接続していない場合、SSHバスティオン経由で接続する場合は、<<proc-adding-ssh-bastion-connection-data>>を進めてください。

問題がなければ、<<proc-finishing-payg-connecting>>に進みます。

[[proc-adding-ssh-bastion-connection-data]]
.プロシージャ:SSHバスティオン接続データの追加
[role=procedure]
. `Bastion SSH connection data`ページセクションに移動します。
. `Host`フィールドに、バスティオンのホスト名を入力します。
. `SSH Port`フィールドに、バスティオンのポート番号を入力します。
. `User`フィールドに、バスティオンのユーザー名を入力します。
. `Password`フィールドに、バスティオンのパスワードを入力します。
. `SSH Private Key`フィールドに、バスティオンのキーを入力します。
. `SSH Private Key Passphrase`フィールドに、バスティオンのキーのパスフレーズを入力します。

<<proc-finishing-payg-connecting>>でセットアッププロセスを完了します。

[[proc-finishing-payg-connecting]]
.プロシージャ:{payg}の接続を完了する
[role=procedure]
. 新しい{payg}接続データの追加を完了するには、btn:[作成]をクリックしてください。
. {payg}接続データ `Details` ページに戻ります。
    更新された接続ステータスは、`Information`という名前の上部セクションに表示されます。
. 接続ステータスは、`Admin > Setup Wizard > Pay-as-you-go`画面にも表示されます。
. インスタンスの認証データが正しい場合、`Status`列に「資格情報が正常に更新されました」と表示されます。

[IMPORTANT]
====
いずれかの時点で無効なデータが入力されると、新しく作成されたインスタンスが`Admin > Setup Wizard > {payg}`に表示され、`Status`列にエラーメッセージが表示されます。
====


サーバで認証データが利用可能になるとすぐに、利用可能な製品のリストが更新されます。

利用可能な製品は、{payg}インスタンスにインストールされているものと同じ製品ファミリーおよびアーキテクチャのすべてのバージョンです。
たとえば、インスタンスに{sles}{nbsp}15 SP1製品がインストールされている場合、{sles}{nbsp}15 SP2、{sles}{nbsp}15 SP3、{sles}{nbsp}15 SP4、{sles}{nbsp}15 SP5が自動的に`Admin > Setup Wizard > Products`に表示されます。

製品が利用可能として表示されたら、ユーザーは製品名の横にあるチェックボックスを選択し、をクリックして{productname}に製品を追加できます。

成功メッセージの後、{webui}で新しく追加されたチャンネルを確認するには、`Software > Channel List > All`に移動します。

各チャンネルのsyncの進行状況を監視するには、`/var/log/rhn/reposync`ディレクトリにあるログファイルを{productname}サーバで確認します。

[IMPORTANT]
====
製品が{payg}インスタンスと{scc}サブスクリプションの両方によって提供されている場合、その製品は製品リストに1回のみ表示されます。

その製品に属するチャンネルが同期されている場合でも、データはSCCサブスクリプションからのものであり、従量課金制インスタンスからのものではない可能性があります。
====

== インスタンス資格情報収集ステータス

{productname}サーバは、インスタンスから収集された資格情報を使用してRMTサーバに接続し、reposyncを使用してパッケージをダウンロードします。
これらの資格情報は、Taskomaticによって、定義されたSSH接続データを使用して10分ごとに更新されます。RMTサーバへの接続は、常に{payg}インスタンスから収集された最後の既知の認証資格情報を使用します。

{payg}インスタンスの資格情報収集のステータスは、`Status`列またはインスタンスの詳細ページに表示されます。
インスタンスにアクセスできない場合、資格情報の更新プロセスは失敗します。

インスタンスにアクセスできない場合、資格情報の更新プロセスは失敗し、2回目の更新が失敗した後に資格情報は無効になります。
資格情報が無効な場合、チャンネルの同期は失敗します。
接続されたインスタンスを実行し続けることで、これを回避できます。

{payg}インスタンスは、SSH接続データが明示的に削除されない限り、{productname}サーバに接続されたままです。
インスタンスへのSSH接続データを削除するには、<<proc-deleting-connection-data-to-instance>>を使用してください。
 

{payg}インスタンスは、{productname}サーバから常にアクセスできるとは限りません。

* インスタンスが存在するが停止している場合は、最新の既知の資格情報を使用してインスタンスへの接続が試行されます。
    資格情報が有効である期間は、クラウドプロバイダによって異なります。

* インスタンスが存在しなくなったが、SUMAに登録されている場合、その資格情報は無効になり、認証は失敗します。
    エラーメッセージは［ステータス］列に表示されます。
+
[WARNING]
====
エラーメッセージは、インスタンスが利用できないことを示すだけです。
インスタンスの状態に関するさらなる診断は、クラウドプロバイダーで行う必要があります。
====

[IMPORTANT]
====
{payg}インスタンスで以下のいずれかのアクションまたは変更が行われると、資格情報が無効になります： +
* zypper資格情報ファイルの削除 +
* インポートされた証明書の削除 +
* `/etc/hosts`からクラウド特有のエントリの削除
====


== {payg}システムをクライアントとして登録する

資格情報を収集する場所から{payg}インスタンスを{salt}クライアントとして登録できます。
インスタンスには有効なクラウド接続が登録されている必要があります。そうでないと、チャンネルにアクセスできません。
ユーザーがクラウドパッケージを削除すると、資格情報の収集が機能しなくなる可能性があります。

最初に {payg} インスタンスを設定して認証データを収集し、チャンネルを同期できるようにするためです。

残りのプロセスは、パブリッククラウド以外のクライアントの場合と同じで、チャンネルの同期、ブートストラップスクリプトの自動作成、アクティベーションキーの作成、および登録の開始で構成されます。

クライアントの登録に関する詳細は、xref:client-configuration:registration-overview.adoc[] を参照してください。


== トラブルシューティング 

資格情報の確認::
* スクリプトが資格情報の収集に失敗した場合、ログおよび {webui} に適切なエラーメッセージを提供する必要があります。
* 資格情報が機能しない場合は、`reposync`に適切なエラーが表示されます。

`registercloudguest`の使用::
* パブリッククラウド更新インフラストラクチャへの`registercloudguest`接続を更新または変更しても、資格情報の使用に支障はありません。
* cloud guestコマンドを使用して新しいクラウド接続が登録されていない場合、`registercloudguest --clean`を実行すると問題が発生します。
