[[install-hardware-requirements]]
= ハードウェア要件
:description: アーキテクチャやストレージのニーズなどの要因を考慮し、SUSE Multi-Linux Managerサーバおよびプロキシのハードウェア要件を構成する方法を学びます。
:revdate: 2025-07-03
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

以下の表は、{productname}サーバーおよびプロキシのハードウェアおよびソフトウェア要件を、{x86_64}、{arm}、{ppc64le}、および{s390x}アーキテクチャごとに示しています。


[WARNING]
====
{productname}の{ppc64le}または{s390x}アーキテクチャに基づくインストールでは、ネットワークブート用クライアントでセキュアブートを使用することはできません。
この制限は、両方のアーキテクチャで shim ブートローダーが利用できないために存在します。
====

//For {ibmz} hardware requirements, see xref:installation-and-upgrade:install-ibmz.adoc[].

{productname} {smr}のハードウェア要件については、xref:retail:retail-requirements.adoc[]を参照してください。



[[server-hardware-requirements]]
== サーバ要件


{sl-micro} {microversion}または{sles} {bci-mlm}のいずれかがコンテナホストのオペレーティングシステムです。

以下では、インストールされたホストオペレーティングシステムとして{sles}が重要な場合にのみ明示的に言及されます。
そうでない場合は、{sl-micro}または単にホストオペレーティングシステムと記述します。

オペレーティングシステムとして{sl-micro}を使用するコンテナホストには、次の空きディスク容量が必要です：

* ベースインストール用に100GB以上
* およびリポジトリデータ用に130GB以上

選択したソフトウェアの量によっては、オペレーティングシステムとして{sles}を使用する場合、ディスク容量がかなり必要になる場合があります。

デフォルトでは、{productname} サーバーコンテナはミラーされたリポジトリ（パッケージまたは製品）、データベース、その他のデータを `/var/lib/containers/storage/volumes/` ディレクトリのサブディレクトリに保存します。
このディレクトリのディスク容量が不足すると、リポジトリの同期が失敗します。
ミラーリングする予定のクライアントやリポジトリの数や種類に基づいて、`/var/lib/containers/storage/volumes/` ディレクトリに必要なスペースを見積もってください。

ファイルシステムおよびパーティショニングの詳細については、xref:installation-and-upgrade:hardware-requirements.adoc#install-hardware-requirements-storage[]およびこのガイドのインストールおよびデプロイメントセクションの詳細なインストール手順を参照してください。

[cols="1,3,2", options="header"]
.サーバハードウェアの要件
|===

| ハードウェア
| 詳細
| 推奨

| CPU
| {x86_64}、{arm}、{ppc64le}または{s390x}
| 最小4つの専用64ビットCPUコア

| RAM
| 最小
| 16GB

|
| 推奨
| 32GB

| ディスク領域
| `/`（ルートディレクトリ）
| 40 GB

|
| `/var/lib/containers/storage/volumes`
| 最小150GB（製品の数に応じて）

|
| `/var/lib/containers/storage/volumes/var-pgsql`
| 最低50GB

| スワップ容量
| システムは追加のスワップスペースの恩恵を受けることができます。{suse}はスワップパーティションの代わりにスワップファイルを使用することを推奨します。 スワップスペースに関する詳細については、xref:installation-and-upgrade:hardware-requirements.adoc#installation-swap-space[]を参照してください。
| 8～12 GB
|===

// |
// | `/var/lib/containers/storage/volumes/var-cache`
// | Minimum 10 GB.
// Add 100 MB per {suse} product, 1 GB per {redhat} or other product.
// Consider to double the space if the server is used for Inter-Server Synchronization (ISS)
// 
// |
// | `/var/lib/containers/storage/volumes/srv-www`
// | Minimum 100 GB
// 
// * Storage requirments should be calculated for the number of ISO distribution images, containers, and bootstrap repositories you will use.


デフォルトでは、イメージには40 GBの `/` パーティションがあります。
{sl-micro} {microversion}のクラウドイメージには、5 GBの `/` パーティションのみがあります。
どちらも{productname}で問題なく動作します。
外部ストレージが `/var/lib/containers/storage/volumes` にマウントされている限り、{productname} は `/` パーティション上のストレージを必要とせず、その管理はコンテナホスト自体に任せられます。



////
// When uncommenting verify the details! (POWER)

ifeval::[{mlm-content} == true]
[cols="1,3,2", options="header"]
.Server Hardware Requirements for IBM POWER8 or higher processor–based server in Little Endian mode (ppc64le)
|===

| Hardware
| Details
| Recommendation

| CPU
|
| Minimum 4 dedicated cores

| RAM
| Minimum
| 16 GB

|
| Recommended
| 32 GB

| Disk Space
| `/` (root directory)
| Minimum 100 GB

|
| `/var/lib/containers/storage/volumes/var-pgsql`
| Minimum 50 GB

|
| `/var/lib/containers/storage/volumes/var-spacewalk`
| Minimum storage required: 100 GB (this will be verified by the implemented check)

* 50 GB for each {suse} product and Package Hub

* 360 GB for each {redhat} product

|
| `/var/lib/containers/storage/volumes/var-cache`
| Minimum 10{nbsp}GB.
Add 100{nbsp}MB per {suse} product, 1{nbsp}GB per {redhat} or other product.
Double the space if the server is an ISS Master.

|
| `/var/lib/containers/storage/volumes/srv-www`
| Minimum 100 GB

* Storage requirements should be calculated for the number of ISO distribution images, containers, and bootstrap repositories you will use.

|
| Swap space
| 3{nbsp}GB. Systems can benefit from additional swap space.   {suse} recommends using a swap file instead of a swap partition.  For more information about swap space, see xref:installation-and-upgrade:hardware-requirements.adoc#installation-swap-space[].

|===

endif::[]

// end POWER
////



[IMPORTANT]
====
{productname}のパフォーマンスは、ハードウェアリソース、ネットワーク帯域幅、クライアントとサーバ間の遅延などによって異なります。

使用中の経験と異なるデプロイメントに基づいて、適切な数のプロキシを持つ{productname}サーバの最適なパフォーマンスのためのアドバイスは、単一のサーバあたり10,000クライアントを超えないことです。
10,000クライアントを超える場合は、Hubセットアップに移行し、コンサルタントに相談することを強くお勧めします。
微調整と適切な数のプロキシがあっても、そのような大量のクライアントはパフォーマンスの問題を引き起こす可能性があります。

大量のクライアントを管理する方法についての詳細は、xref:specialized-guides:large-deployments/hub-multi-server.adoc[]を参照してください。
====


[[proxy-hardware-requirements]]
== プロキシ要件

{sl-micro} {microversion}または{sles} {bci-mlm}のいずれかがコンテナホストのオペレーティングシステムです。

[NOTE]
====
最低要件は、クライアントが1つのプロキシなど、テスト用の簡易的なインストールに適しています。
本番環境を使用する場合は、推奨値から始めてください。
====


[cols="1,3,2", options="header"]
.プロキシのハードウェア要件
|===

| ハードウェア
| 詳細
| 推奨

| CPU
| {x86_64}、{arm}
| 最低2つの専用64ビットCPUコア

|
| 推奨
| 最低値と同じです

| RAM
| 最小
| 2GB

|
| 推奨
| 8GB

| ディスク領域
| `/`（ルートディレクトリ）
| 最低40GB

|
| `/var/lib/containers/storage/volumes`
| 最低100 GB

| スワップ容量
| システムは追加のスワップスペースの恩恵を受けることができます。{suse}はスワップパーティションの代わりにスワップファイルを使用することを推奨します。 スワップスペースに関する詳細については、xref:installation-and-upgrade:hardware-requirements.adoc#installation-swap-space[]を参照してください。
| 4～8 GB

|===

デフォルトでは、{productname} プロキシコンテナはパッケージを `/var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/` ディレクトリにキャッシュします。
十分な空き容量がない場合、プロキシは古い未使用のパッケージを削除し、新しいパッケージと置き換えます。

この動作の結果は以下のとおりです。

* プロキシ上の `/var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/` ディレクトリの容量が大きいほど、プロキシと {productname} サーバー間のトラフィックが減少します。
* プロキシ上の `/var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/` ディレクトリを `/var/lib/containers/storage/volumes/var-spacewalk/` サーバー上の {productname} と同じサイズにすることで、最初の同期後に大量のトラフィックが発生するのを防ぐことができます。
* {productname} サーバー上の `/var/lib/containers/storage/volumes/uyuni-proxy-squid-cache/` ディレクトリは、プロキシ上のものと比べて小さくても問題ありません。
  サイズ推定のガイドについては、<<server-hardware-requirements>>セクションを参照してください。

[NOTE]
====
一般的に、{suse}はキャッシュディレクトリの値を利用可能な空き容量の約80 %に調整することを推奨します。
`cache_dir` の値は、サーバーでプロキシ設定を生成する際に設定されます。
`squid.conf` でオプションを直接設定することはできません。
====



[[installation-swap-space]]
== スワップ容量

ワークロードはシステムごとに異なります。
重いまたは予測不可能なワークロードを持つシステムは、総RAMに関係なく追加のスワップスペースの恩恵を受けることができます。
スワップは、最も速いストレージ（例えば、SSD）に配置することが推奨されます。{suse}はスワップパーティションの代わりにスワップファイルを使用することを推奨します。

サイズの推奨事項については、上記の表を参照してください。

以下のシェルコマンドスニペットは8GiBスワップファイルを作成します。

[NOTE]
====
BtrFSファイルシステム上のスワップファイルは、そのボリュームのスナップショット作成を妨げます。以下の例の `/var` はすでにsnapperスナップショットから除外されているため、`/var/swap` を安全に使用できます。
====

[source,shell]
----
## setup swapfile at /var/swap
# run following as a root user

# allocate 8GiB for swap file
fallocate -l 8G /var/swap
# ensure CoW is disabled for the swap file
chattr +C /var/swap
# allow only root access
chmod 600 /var/swap
# make swap file based on allocated file
mkswap /var/swap
# activate swap use for the running system
swapon /var/swap
# activate swap during the next boots
echo "/var/swap swap swap defaults 0 0" >> /etc/fstab
----




[[installation-postgresql-requirements]]
== データベースの要件

{postgresql}は唯一のサポートされているデータベースです。
リモート{postgresql}データベースやリモートファイルシステム（NFSなど）を{postgresql}データベースと一緒に使用することはサポートされていません。
言い換えれば、{postgresql}は{productname}のために最も速いストレージデバイス上にあるべきです。

[IMPORTANT]
====
パフォーマンスの問題の可能性があるため、{postgresql}データベースを{productname}からリモートで実行することは推奨されません。
そのような環境は可能であり、多くの場合安定していますが、何かがうまくいかない場合にはデータ損失のリスクが常に存在します。

ifeval::[{mlm-content} == true]
このような場合、{suse}は支援を提供できないことがあります。
endif::[]
====



[[install-hardware-requirements-storage]]
== 永続ストレージとパーミッション

永続ボリュームは、コンテナの配備時にデフォルトで作成されます。

ただし、ボリュームは1つ以上の別のストレージデバイスに保存することが推奨されます。
そのようなセットアップは、運用環境でのデータ損失を避けるのに役立ちます。
これはコンテナのデプロイ後に行うことができます。

ストレージデバイスは、コンテナを最初にデプロイした後にセットアップするのが最適です。
詳細については、xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[Persistent Container Volumes]を参照してください。

すべてのボリュームに対して、ファイルシステムタイプとしてXFSを使用することをお勧めします。
リポジトリストレージ用のディスクのサイズは、{productname}で管理する予定のディストリビューションとチャネルの数に依存します。
このセクションの表を参照して、必要なサイズを見積もるガイドを確認してください。

[IMPORTANT]
====
{cobbler}または{postgresql}ストレージにNFSを使用しないでください。また、SELinux環境でのNFSも使用しないでください。
これらのシナリオはサポートされていません。
====

{productname}サーバで、次のコマンドを使用して、利用できるすべてのストレージデバイスを検索します：

[source, shell]
----
hwinfo --disk | grep -E "Device File:"
----

`lsblk` コマンドを使用して、各デバイスの名前とサイズを表示します。

`mgr-storage-server` コマンドにデバイス名を指定して実行することで、外部ディスクをストレージの配置先として、さらに必要に応じて専用ディスク上にデータベース用として設定できます。

[source, shell]
----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----

例:

[source, shell]
----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----

外部ストレージボリュームは、`/manager_storage` および `/pgsql_storage` にマウントされたXFSパーティションとして設定されます。

[NOTE]
====
このコマンドは、`/var/lib/containers/storage/volumes`に永続ストレージボリュームを作成します。

詳細については、xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]を参照してください。
====

チャネルデータとデータベースの両方に同じストレージデバイスを使用することは可能です。
これは推奨されません。なぜなら、チャネルリポジトリが増加するとストレージが満杯になり、データベースの整合性にリスクをもたらす可能性があるからです。
別々のストレージデバイスを使用することで、パフォーマンスが向上する可能性もあります。
単一のストレージデバイスを使用したい場合は、`mgr-storage-server` を単一のデバイス名パラメータで実行してください。

プロキシをインストールしている場合、`mgr-storage-proxy` コマンドはデバイス名パラメータを1つだけ取り、外部ストレージの場所をSquidキャッシュとして設定します。



== 論理ボリューム管理(LVM)


// container-deployment/mlm/server-deployment-vm-mlm.adoc etc.
すべての種類の仮想マシン（VM）に対して、LVMは一般的に必要なく、推奨されません。
ディスクのセットアップは仮想であり、ボリューム用の別のディスクが可能であり、推奨されます。

// container-deployment/mlm/server-deployment-mlm.adoc
その他の配備については、ボリュームごとに個別のディスクも推奨されます。

{productname} サーバーのコンテナホスト上で、`mgr-storage-server` コマンドは `/var/lib/containers/storage/volumes` ディレクトリの全内容を別のディスクに移動し、`/var/lib/containers/storage/volumes` に再マウントします。

オプションとして、2つ目のデバイス名が指定された場合、`mgr-storage-server` は `/var/lib/containers/storage/volumes/var-pgsql` データベースディレクトリのコンテンツを別の2台目のディスクに移動し、`/var/lib/containers/storage/volumes/var-pgsql` に再マウントします。

同様に、{productname} プロキシのコンテナホスト上で、`mgr-storage-proxy` コマンドは `/var/lib/containers/storage/volumes` ディレクトリの全コンテンツを別のディスクに移動し、それを `/var/lib/containers/storage/volumes` に再マウントします。



////
// *** The following is commented, and can probably deleted ***

// When installation takes place on bare metal (on-premise), `cockpit` can be used to create an LVM setup.
// In such a case, the disk setup needs to be performed manually.

// With containers {productname} now has `/var/lib/containers/storage/volumes` as an extra disk.
////
