ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

ifndef::backend-pdf[]
[[installation-and-upgrade-overview]]
= インストール、配備、およびアップグレード
:description: サーバーおよびプロキシをインストール、デプロイし、アップグレードする方法について、要件、設定、移行、管理に関する手順とガイダンスを順を追って説明します。
:revdate: 2026-09-08
:page-revdate: {revdate}

// HTML Publication date 
**発行日:** {docdate}

== 序文 


このガイドでは、{productname}サーバおよびプロキシをデプロイ、アップグレード、管理するための包括的な手順を段階的に説明します。

以下のセクションで構成されています。

* **要件:**スムーズなセットアップを確実に行うために必要なハードウェア、ソフトウェア、およびネットワークの前提条件を概説します。
* **デプロイメントとインストール:**{productname}をコンテナとしてデプロイし、初期設定を完了する手順を案内します。
* **アップグレードと移行:**ダウンタイムを最小限に抑えながら、{productname}のアップグレードおよび移行のプロセスを詳述します。
* **基本的なサーバ管理:**基本的なサーバ操作をカバーし、{productname}を効率的に始める手助けをします。

include::installation-and-upgrade:partial$snippet-upgrade-terminology-mlm.adoc[]

== 著作権通知

ifeval::[{mlm-content} == true]
// HTML Copyright
Copyright © {copyrightdate} SUSE LLCおよび貢献者。All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]と題されたセクションに含まれています。
endif::[]

ifeval::[{uyuni-content} == true]
// HTML Copyright
Copyright © 2011–2025 Uyuni contributors.All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]と題されたセクションに含まれています。
endif::[]

== 商標
// HTML Trademarks
SUSEの商標については、 https://www.suse.com/company/legal/を参照してください。すべてのサードパーティの商標は、それぞれの所有者に属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。
本書のすべての情報は、細心の注意を払って編集されています。しかし、これは完全な正確性を保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。
endif::[]

ifdef::backend-pdf[]

<<<

:!sectnums:

[preface]
== 序文

インストール、デプロイメント、およびアップグレード | {productname} {productnumber}

このガイドでは、{productname}サーバおよびプロキシをデプロイ、アップグレード、管理するための包括的な手順を段階的に説明します。

以下のセクションで構成されています。

* **要件:**スムーズなセットアップを確実に行うために必要なハードウェア、ソフトウェア、およびネットワークの前提条件を概説します。
* **デプロイメントとインストール:**{productname}をコンテナとしてデプロイし、初期設定を完了する手順を案内します。
* **アップグレードと移行:**ダウンタイムを最小限に抑えながら、{productname}のアップグレードおよび移行のプロセスを詳述します。
* **基本的なサーバ管理:**基本的なサーバ操作をカバーし、{productname}を効率的に始める手助けをします。

// PDF Publication

**発行日:** {docdate}

ifeval::[{mlm-content} == true]
// PDF Copyright
Copyright © {copyrightdate} SUSE LLCおよび貢献者。All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]と題されたセクションに含まれています。
endif::[]

ifeval::[{uyuni-content} == true]
// PDF Copyright
Copyright © 2011–2025 Uyuni contributors.All rights reserved.
この文書は、GNUフリー文書ライセンスのバージョン1.2または(オプションとして)バージョン1.3の条項に従って、複製、頒布、および/または改変が許可されています。ただし、この著作権表示およびライセンスは変更せずに記載すること。ライセンスバージョン1.2のコピーは、xref:legal:license.adoc[GNUフリー文書ライセンス]と題されたセクションに含まれています。
endif::[]

// PDF Trademarks
SUSEの商標については、 https://www.suse.com/company/legal/を参照してください。すべてのサードパーティの商標は、それぞれの所有者に属します。商標記号(®、™など)は、SUSEおよび関連会社の商標を示します。アスタリスク(*)は、第三者の商標を示します。
本書のすべての情報は、細心の注意を払って編集されています。しかし、これは完全な正確性を保証するものではありません。SUSE LLC、その関係者、著者、翻訳者のいずれも誤りまたはその結果に対して一切責任を負いかねます。

<<<

include::../partials/snippet-upgrade-terminology-mlm.adoc[]

<<<

toc::[]

:sectnums:

endif::[]
