[[install-pubcloud-requirements]]
= パブリッククラウドの要件
:description: これらのテスト済みの要件を使用して、パブリッククラウドインフラストラクチャ上でSUSE Multi-Linux Managerのセキュアなセットアップを行ってください。
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

このセクションでは、パブリッククラウドインフラストラクチャ上に{productname}をインストールするための要件を提供します。
これらの手順は、Amazon EC2、Google Compute Engine、およびMicrosoft Azureでテスト済みですが、他のプロバイダーでもいくつかの変動はあるものの動作するはずです。

始める前に、考慮事項を次に示します。

* {productname}のセットアップ手順は、前方確認された逆DNSルックアップを実行します。
  これが成功しなければ、セットアップ手順は完了せず、{productname}は期待通りに動作しません。
  {productname}を設定する前に、ホスト名とIPの設定を行うことが重要です。
* {productname}サーバおよびプロキシのインスタンスは、DNSエントリの制御が可能なネットワーク設定で実行する必要がありますが、インターネット全体からのアクセスはできません。
* このネットワーク設定内では、DNSの解決を提供する必要があります。`hostname -f`は、完全修飾ドメイン名(FQDN)を返す必要があります。
* DNSの解決は、クライアントを接続するためにも重要です。
* DNSは、選択したパブリッククラウドフレームワークに依存します。
  詳細な手順については、クラウドプロバイダーのドキュメントを参照してください。
* ソフトウェアリポジトリ、サーバーデータベース、およびプロキシのSquidキャッシュを外部仮想ディスクに配置することをお勧めします。
  これにより、インスタンスが予期せず終了した場合でもデータ損失を防ぐことができます。
  このセクションには、外部仮想ディスクの設定手順が含まれています。



== ネットワーク要件


パブリッククラウド上で{productname}を使用する場合、制限されたネットワークを使用する必要があります。
適切なファイアウォール設定を持つVPCプライベートサブネットの使用をお勧めします。
指定したIP範囲内のマシンのみがインスタンスにアクセスできる必要があります。

[WARNING]
====
パブリッククラウド上で{productname}を実行することは、堅牢なセキュリティ対策を実施することを意味します。インスタンスへのアクセスを制限、フィルタリング、監視、および監査することが不可欠です。{SUSE}は、十分な周辺セキュリティが備わっていない、グローバルにアクセス可能な{productname}インスタンスの使用を強く控えることを推奨します。
====

{productname} {webui}にアクセスするには、ネットワークアクセス制御を設定する際にHTTPSを許可してください。
これにより、{productname} {webui}にアクセスできます。

EC2およびAzureでは、新しいセキュリティグループを作成し、HTTPSのためのインバウンドおよびアウトバウンドルールを追加します。
GCEでは、`Firewall`セクションの下にある`Allow HTTPS traffic`ボックスにチェックを入れます。



== ストレージボリュームの準備

{productname}のリポジトリとデータベースは、ルートボリュームとは別のストレージデバイスに保存することをお勧めします。
これにより、データ損失を避け、パフォーマンスを向上させる可能性があります。

{productname}コンテナは、デフォルトのストレージ場所を利用します。これらの場所は、カスタムストレージのためにデプロイ前に設定する必要があります。
詳細については、xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[永続コンテナボリューム]を参照してください。

[IMPORTANT]
====
パブリッククラウドへのインストールでは論理ボリューム管理(LVM)を使用しないでください。
====


リポジトリストレージのディスクサイズは、{productname}で管理する予定の配布数およびチャネル数に依存します。
仮想ディスクを接続すると、それらはインスタンス上でUNIXデバイスノードとして表示されます。
デバイスノードの名前は、プロバイダーおよび選択したインスタンスタイプによって異なります。

{productname}サーバのルートボリュームが100{nbsp}GB以上であることを確認してください。
500{nbsp}GB以上の追加のストレージディスクを追加し、可能であればSSDストレージを選択してください。
{productname}サーバのクラウドイメージは、インスタンスが起動されるときにこの別のボリュームを割り当てるスクリプトを使用します。

インスタンスを起動すると、{productname}サーバにログインし、次のコマンドを使用して、利用可能なすべてのストレージデバイスを検索できます。

----
hwinfo --disk | grep -E "Device File:"
----

どのデバイスを選択するか不明な場合は、`lsblk`コマンドを使用して、各デバイスの名前とサイズを確認してください。
探している仮想ディスクのサイズに一致する名前を選択してください。

`mgr-storage-server`コマンドを使用して、外部ディスクをセットアップできます。
これにより、`/manager_storage`にマウントされたXFSパーティションが作成され、データベースとリポジトリの場所として使用されます。

----
/usr/bin/mgr-storage-server <devicename>
----

ifeval::[{mlm-content} == true]
ストレージボリュームおよびパーティションの設定(推奨最小サイズを含む)の詳細については、xref:installation-and-upgrade:hardware-requirements.adoc[]を参照してください。
endif::[]
