[[client-upgrades-uyuni]]
= Upgrade Uyuni Clients
:revdate: 2025-02-26
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

In this section, we use openSUSE Leap as an example.

== Příprava upgradu


.Procedure: Preparing the Client Upgrade
. At the command prompt on the {productname} Server, as root, use the [command]``spacewalk-common-channels`` command to add the appropriate channels.
+
----
spacewalk-common-channels \
opensuse_leap15_4 \
opensuse_leap15_4-non-oss \
opensuse_leap15_4-non-oss-updates \
opensuse_leap15_4-updates \
opensuse_leap15_4-uyuni-client
----

. Fully synchronize all channels with [command]``spacewalk-repo-sync``.
+
// These are custom channels.
// For more information, see xref:client-configuration:clients-opensuse.adoc[].

. In the {productname} Server {webui}, navigate to menu:Software[Manage > Channels] and click the [systemitem]``Uyuni Client Tools for openSUSE Leap 15.4 (x86_64)`` channel name.

. V pravém horním rohu stiskněte btn:[Manage Channel] (Správa kanálu).

. Click the [guimenu]``Repositories`` tab, and select [systemitem]``External - Uyuni Client Tools for openSUSE Leap 15.3 (x86_64)``.

. Stiskněte btn:[Update Repositories] (Aktualizovat úložiště).

. Přejděte do podzáložky, menu:Repositories[Sync] (Úložiště[Synchronizace]) a stiskněte btn:[Sync Now] (Synchronizuj teď).

. Do the same with [systemitem]``openSUSE Leap 15.4 (x86_64)`` and [systemitem]``External - openSUSE Leap 15.3 (x86_64)``.

Unfold [systemitem]``openSUSE Leap 15.4 (x86_64)`` to see all child channels populated with packages.



== Upgrade (povýšení verze)

To upgrade a client you replace the software repositories and update the software, and finally reboot the client.



.Procedure: Upgrading the Client

. In the {productname} Server {webui}, navigate to menu:Systems[] and click the name of the client.
. Klikněte na menu:Software[Software Channels] (Software [Softwarové kanály]) a jako základní kanál vyberte kanál openSUSE Leap {opensuse-version}, který je uveden v seznamu [systemitem]``Customs Channels`` (Zákaznické kanály).
. V podokně [guimenu]``Child Channels`` (Podřízené kanály) vyberte podřízené kanály pro {opensuse-version}.
. Stiskněte btn:[Next] (Další) a [guimenu]``Confirm Software Channel Change`` (Potvrdit změnu softwarového kanálu) tlačítkem btn:[Confirm] (Potvrdit).
. Click menu:Software[Packages > Upgrade], and select all the packages to be updated on the client, and then apply the selection. Click btn:[Upgrade Packages], check the details, and click btn:[Confirm] to complete the update.
. Reboot the client.

If you need to update many clients, you can create an action chain of this command sequence on the {productname} Server. You can use the action chain to perform updates on multiple clients at the same time.


////
. Assign the new channels to the clients instead of the old channels.

. Update all the packages.  This can either be done with the {webui} or better run [command]``zypper dup`` manually on the command line local on the systems or remotely as a Salt command.
////

////
I think the better way to document this is if giving it a try. Create an Uyuni server, sync Leap 15.1 (spacewalk-common-channels), create a Leap 15.1, onboard it, sync Leap 15.2 (spacewalk-common-channels), and then try to adjust the channels and trying to upgrade. I recommend you use VMs and take snapshots of the VMs so you can repeat steps as needed.
////

////
But for now you need to create and mirror at least the target channels with spacewalk-common-channels.

You adjust the channels for the client and best is to call "zypper dup". Either from the commandline on that system or using remote command.
////
