[[clients-pubcloud]]
= Registering clients on a public cloud

When you have your {productname} Server set up, you are ready to start registering clients.



== Prepare on-demand images

An instance started from an on-demand image provided by {suse} is automatically registered, and the update infrastructure and {sle} modules are activated. To use your on-demand image as a {productname} client, you need to disable this automation before you begin.



.Procedure: Preparing on-demand images
. Log in to the on-demand instance.
. At the command prompt, as root, remove the registration data and repositories:
+
----
registercloudguest --clean
----
. Remove the ``cloud-regionsrv-client`` package:
+
----
zypper rm cloud-regionsrv-client
----
. Remove additional packages specific to your cloud provider:
+
* Amazon EC2:
+
----
zypper rm regionServiceClientConfigEC2 regionServiceCertsEC2
----
+
* Google Compute Engine:
+
----
zypper rm cloud-regionsrv-client-plugin-gce regionServiceClientConfigGCE regionServiceCertsGCE
----
+
* Microsoft Azure:
+
----
zypper rm regionServiceClientConfigAzure regionServiceCertsAzure
----

For instructions on registering {productname} to {scc}, see xref:installation:server-setup.adoc[].



== Registrovat klienty

In the {productname} {webui}, navigate to menu:Systems[Bootstrapping], then fill in the ``Host``, ``SSH Port``, ``User``, and ``Password`` fields. Make sure you use stable FQDNs for the ``Host`` field, or {productname} cannot find your host when your Public Cloud gives you a different short-lived FQDNS.

[NOTE]
====
Pokoušíte-li se zavést tradiční klienty, zkontrolujte, zda můžete při přihlášení ke klientovi vyřešit název hostitele serveru. Možná budete muset přidat plně kvalifikovaný název domény serveru do souboru lokálního řešení [cesta]``/etc/hosts`` v klientovi. Zkontrolujte to příkazem [command]``název hostitele -f`` s místní IP adresou serveru.
====

Public cloud images usually do not allow SSH login with username and password, but only SSH with a certificate. If you want to use bootstrap from the {webui}, you need to enable SSH login with username and SSH key. You can do this by navigating to menu:Systems[Bootstrapping] and changing the authentication method.

If your cloud provider is Microsoft Azure, you can log in with username and password. To do this, you need to allow the AzureUser to run commands as root without a password. To do this, open the [path]``/etc/sudoers.d/waagent`` file, and add or edit this line:

----
AzureUser ALL=(ALL) NOPASSWD: ALL
----

[WARNING]
====
Allowing the AzureUser to run commands as root without a password carries a security risk. Use this method for testing only. Do not do this for production systems.
====

When the bootstrap process has completed successfully, your client is listed at menu:Systems[System List].

* If you want more control over the process, have to register many clients, or are registering traditional clients, create a bootstrap script. For more information, see xref:client-configuration:registration-bootstrap.adoc[].
* For Salt clients and even more control over the process, executing single commands on the command line can be useful. For more information, see xref:client-configuration:registration-cli.adoc[].
* If you are attempting to register clients that are cloned from each other, you need to do some extra configuration to prevent them from over-writing each other. For more information about registering clones, see xref:administration:tshoot-registerclones.adoc[].



== Activation keys

Aktivační klíče se používají u tradičních klientů a klientů Salt, aby bylo zajištěno, že vaši klienti mají správná softwarová oprávnění, připojují se k příslušným kanálům a jsou přihlášeni k odběru příslušných skupin. Každý aktivační klíč je vázán na organizaci, kterou můžete nastavit při vytváření klíče.

For more on activation keys, see xref:client-configuration:activation-keys.adoc[].
