[[client-upgrades-uyuni]]
= Upgrade Uyuni Clients

. At the command prompt on the {productname} Server, as root, use the [command]``spacewalk-common-channels`` command to add the appropriate channels.
+
----
spacewalk-common-channels \
opensuse_leap15_2 \
opensuse_leap15_2-non-oss \
opensuse_leap15_2-non-oss-updates \
opensuse_leap15_2-updates \
opensuse_leap15_2-uyuni-client
----

. Fully synchronize all channels with [command]``spacewalk-repo-sync``. In case of already defined repository URLs, continue with xref:upgrade:proxy-uyuni.adoc#uyuni-202007-channeldupes[].
+

. Na {productname} Server {webui} přejděte do menu:Software[Manage > Channels] (Software [Správa > Kanály]) a klikněte na název kanálu [systemitem]``Uyuni Client Tools for openSUSE Leap 15.2 (x86_64)``.

. V pravém horním rohu stiskněte btn:[Manage Channel] (Správa kanálu).

. Click the [guimenu]``Repositories`` tab, and select [systemitem]``External - Uyuni Client Tools for openSUSE Leap 15.1 (x86_64)``.

. Stiskněte btn:[Update Repositories] (Aktualizovat úložiště).

. Přejděte do podzáložky, menu:Repositories[Sync] (Úložiště[Synchronizace]) a stiskněte btn:[Sync Now] (Synchronizuj teď).

. Do the same with [systemitem]``openSUSE Leap 15.2 (x86_64)`` and [systemitem]``External - openSUSE Leap 15.1 (x86_64)``.

Unfold [systemitem]``openSUSE Leap 15.2 (x86_64)`` to see all child channels populated with packages.



== Upgrade the Client

To upgrade a client you replace the software repositories and update the software, and finally reboot the client.



.Procedure: Updating the Client


. In the {productname} Server {webui}, navigate to menu:Systems[] and click the name of the client.
. Klikněte na menu:Software[Software Channels] (Software [Softwarové kanály]) a jako základní kanál vyberte kanál openSUSE Leap {opensuse-version}, který je uveden v seznamu [systemitem]``Customs Channels`` (Zákaznické kanály).
. V podokně [guimenu]``Child Channels`` (Podřízené kanály) vyberte podřízené kanály pro {opensuse-version}.
. Stiskněte btn:[Next] (Další) a [guimenu]``Confirm Software Channel Change`` (Potvrdit změnu softwarového kanálu) tlačítkem btn:[Confirm] (Potvrdit).
. Click menu:Software[Packages > Upgrade], and select all the packages to be updated on the client, and then apply the selection. Click btn:[Upgrade Packages], check the details, and click btn:[Confirm] to complete the update.
+
+
+
. Reboot the client.

If you need to update many clients, you can create an action chain of this command sequence on the {productname} Server. You can use the action chain to perform updates on multiple clients at the same time.




