== {sl-micro} {microversion}ホストを準備します。


=== インストールメディアのダウンロード

.プロシージャ:インストールメディアのダウンロード
[role=procedure]
____

. https://www.suse.com/download/sle-micro/,にある{sl-micro} {microversion}インストールメディアを見つけて、適切なメディアファイルをダウンロードします。

. インストール用にダウンロードした`.iso`イメージを含むDVDまたはUSB フラッシュ ドライブを準備します。

____


=== {sl-micro} {microversion}をインストールします。

マシン（仮想または物理）の準備に関する詳細は、link:https://documentation.suse.com/sle-micro/6.1[{sl-micro}デプロイメントガイド]を参照してください。

.プロシージャ:{sl-micro} {microversion}をインストール中です。
[role=procedure]
____

. {sle-micro} {microversion}のインストールイメージを含むDVDまたはUSBフラッシュ ドライブ（USBディスクまたはキー）を挿入します。

. システムをブートまたは再起動します。

. 矢印キーを使用して`Installation`を選択します。

. キーボードと言語を調整します。

. `checkbox`をクリックして、ライセンス契約を受け入れます。

. `Next`をクリックして続行します。

. プロキシの登録{sl-micro} {microversion}エンタイトルメントは{productname}エンタイトルメント内に含まれているため、別途登録コードは必要ありません。

. 継続するにはbtn:[次へ]をクリックしてください。

. `NTP Configuration`ページで、btn:[Next]をクリックします。

. `Authentication for the System`ページで、ルートユーザのパスワードを入力します。
  btn:[次へ]をクリックします。

. `Installation Settings`ページで、btn:[Install]をクリックします。

____

これで{sl-micro} {microversion}と{productname} {productnumber}の拡張機能のインストールが完了しました。


=== システムの更新

.プロシージャ:システムの更新
[role=procedure]
____
. *ルート*としてログインします。

. **transactional-update**を実行します。

+

[source, shell]
----
transactional-update
----

. 再起動します。

____


[IMPORTANT]
====
{sl-micro}はデフォルトで自動的に更新されるように設計されており、更新を適用した後に再起動します。
しかし、この動作は{productname}環境では望ましくありません。
サーバーで自動更新を防ぐために、{productname}は起動プロセス中にトランザクション更新タイマーを無効にします。

{sl-micro}のデフォルトの動作を使用したい場合は、次のコマンドを実行してタイマーを有効にします。

[source, shell]
----
systemctl enable --now transactional-update.timer
----
====
