== {sl-micro} {microversion}ホストを準備します。


=== インストールメディアのダウンロード

.プロシージャ:インストールメディアのダウンロード
[role=procedure]
____

. https://www.suse.com/download/sle-micro/,にある{sl-micro} {microversion}インストールメディアを見つけて、適切なメディアファイルをダウンロードします。

. インストール用にダウンロードした`.iso` イメージを含むDVDまたはUSBフラッシュ ドライブを準備します。

____


=== {sl-micro} {microversion}をインストールします。

.プロシージャ:{sl-micro} {microversion}をインストール中です。
[role=procedure]
____

. {sle-micro} {microversion}のインストールイメージを含むDVDまたはUSBフラッシュ ドライブ（USBディスクまたはキー）を挿入します。

. システムをブートまたは再起動します。

. 矢印キーを使用して`Installation`を選択します。

. キーボードと言語を調整します。

. `checkbox`をクリックして、ライセンス契約を受け入れます。

. `Next`をクリックして続行します。

. 登録方法を選択します。
  この例では、{scclongform}でサーバーを登録します。

+

[NOTE]
====
{productname} {productnumber}コンテナは拡張機能としてインストールされます。
以下のリストから必要な特定の拡張機能に応じて、各々に追加の{scclongform}登録コードが必要になります。

* {productname} {productnumber}サーバー
* {productname} {productnumber}プロキシ
* {productname} {productnumber}小売支店サーバー
====

+

[IMPORTANT]
====
{sl-micro} {microversion}エンタイトルメントは{productname}エンタイトルメント内に含まれているため、別途登録コードは必要ありません。
====

. {scclongform}の電子メールアドレスを入力してください。

. {sl-micro} {microversion}の登録コードを入力してください。

. `Next`をクリックして続行します。

. プロキシをインストールするには、{productname} {productnumber}プロキシ拡張機能を選択します。サーバーをインストールするには、{productname} {productnumber}サーバー拡張機能 `Checkbox`を選択します。

. `Next`をクリックして続行します。

. {productname} {productnumber}拡張機能の登録コードを入力します。

. 継続するにはbtn:[次へ]をクリックしてください。

. `NTP Configuration`ページで、btn:[次へ]をクリックします。

. `Authentication for the System`ページで、ルートユーザのパスワードを入力します。
  btn:[次へ]をクリックします。

. `Installation Settings`ページで、btn:[インストール]をクリックします。

____

これで{sl-micro} {microversion}と{productname} {productnumber}の拡張機能のインストールが完了しました。
マシン（仮想または物理）の準備に関する詳細は、link:https://documentation.suse.com/sle-micro/6.1[{sl-micro}デプロイメントガイド]を参照してください。


=== オプション:コマンドラインからの登録

{sl-micro} {microversion}のインストール中に{productname} {productnumber}を拡張機能として追加した場合、この手順をスキップできます。
ただし、オプションとして{sl-micro} {microversion}のインストール中にbtn:[登録をスキップ]ボタンを選択することで登録をスキップできます。
このセクションでは、{sl-micro} {microversion}のインストール後に製品を登録する手順を提供します。

[NOTE]
====
以下の手順では、{productname} {productnumber}拡張機能を{x86_64}アーキテクチャで登録するため、{x86_64}アーキテクチャの登録コードが必要です。
{arm}または{s390x}アーキテクチャを登録するには、正しい登録コードを使用してください。
====

.プロシージャ:コマンドラインからの登録
[role=procedure]
____
. 次のコマンドで利用可能な拡張機能を一覧表示します。

+

----
transactional-update --quiet register --list-extensions
----

. 利用可能な拡張機能のリストから、インストールしたい拡張機能を選択します。

+

.. サーバーをインストールする場合は、次のコマンドで{productname}サーバー拡張機能{productnumber} x86_64の登録コードを使用します。

+

----
transactional-update register -p Multi-Linux-Manager-Server/5.1/x86_64 -r <reg_code>
----

.. プロキシをインストールする場合は、次のコマンドで{productname}プロキシ拡張機能{productnumber} x86_64の登録コードを使用します。

+

----
transactional-update register -p Multi-Linux-Manager-Proxy/5.1/x86_64 -r <reg_code>
----

. 再起動します。


____


=== システムの更新

.プロシージャ:システムの更新
[role=procedure]
____
. *ルート*としてログインします。

. **transactional-update**を実行します。

+

[source, shell]
----
transactional-update
----

. 再起動します。

____


[IMPORTANT]
====
{sl-micro}はデフォルトで自動的に更新されるように設計されており、更新を適用した後に再起動します。
しかし、この動作は{productname}環境では望ましくありません。
サーバーで自動更新を防ぐために、{productname}は起動プロセス中にトランザクション更新タイマーを無効にします。

{sl-micro}のデフォルトの動作を使用したい場合は、次のコマンドを実行してタイマーを有効にします。

[source, shell]
----
systemctl enable --now transactional-update.timer
----
====
