#!/bin/bash

# Execute from the ./l10n-weblate directory !!!

# Set default sorting order
export LC_COLLATE=C

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for GUIDE in `for I in *.cfg; do basename $I .cfg; done`; do
    cd $CURRENT_DIR/.. && \
    { grep -v "\[type: asciidoc\]" l10n-weblate/$GUIDE.cfg && find  modules/$GUIDE/ -type f -name "*.adoc" ! -name "*.pdf.en.adoc" | grep -v \.pdf\.en\.adoc | grep -v gfdl | sort | while read line; do echo "[type: asciidoc] $line \$lang:translations/\$lang/$line"; done } > l10n-weblate/$GUIDE.cfg.tmp && mv l10n-weblate/$GUIDE.cfg.tmp l10n-weblate/$GUIDE.cfg && \
    cd $CURRENT_DIR
done
