[[upgrade-troubleshooting]]
= Troubleshooting

This section contains some common problems you might encounter with {productname} upgrades, and solutions to resolving them.

To get more information about an upgrade problem, check the migration log file.
The log file is located at [path]``/var/log/rhn/migration.log`` on the system you are upgrading.


////

PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step

////


== Retrying to Set up the Target System

If you need to retry setting up the target system, follow these steps:

. Delete [path]``/root/.MANAGER_SETUP_COMPLETE``.
. Stop PostgreSQL and remove [path]``/var/lib/pgsql/data``.
. Set the target system hostname to match the source system hostname.
. Check the [path]``/etc/hosts`` file, and correct it if necessary.
. Check [path]``/etc/setup_env.sh`` on the target system, and ensure the database name is set:
+
----
MANAGER_DB_NAME='susemanager'
----
. Reboot the target system.
. Run [command]``mgr-setup`` again.

