[[ref-software-channel-list]]
= Channel List Menu

include::{localesdir-ref}[]


The menu:Software[Channel List] section allows you to view and manage software channels and packages on your clients.

For more information about software channels, see xref:client-configuration:channels.adoc[].

The menu:Software[Channel List > All] section displays a list of all software channels that are available to your organization.

Each software channel in the list shows a channel name, a provider, the number of packages and patches in the channel, and the number of clients currently subscribed to the channel.
Click the plus sign next to the name of a parent channel to expand the entry and see all the related child channels.
Click the channel name to see more information about the channel.

Within the menu:Software[Channel List] section you can select which subset of channels you would like to see by navigating to tabs, or the sub-menu items.

[[channel-list-filters]]
[cols="1,1", options="header"]
.Channel List Filters
|===
| Filter      | Description
| All         | All channels available to your organization.
| SUSE        | Channels provided by {suse}.
| Popular     | Channels most subscribed to by clients in your organization.
| My Channels | Software channels that belong to your organization, including custom channels.
| Shared      | Channels shared with others in the organizational trust.
| Retired     | Channels that have reached end-of-life and no longer receive updates.
|===

For more information about software channels, see xref:client-configuration:channels.adoc[].