[[actions]]
= アクション
:revdate: 2025-05-12
:page-revdate: {revdate}

クライアントに対するアクションは、さまざまな方法で管理することができます。

* 自動化された定期的なアクションをスケジュールして、指定されたスケジュールでクライアントにhighstateまたは任意のカスタム状態のセットを適用できます。
* 個々のクライアント、システムグループ内のすべてのクライアント、または組織全体に定期的なアクションを適用できます。
* 動作チェーンを作成することにより、特定の順序で実行されるアクションを設定できます。
  ** 動作チェーンは事前に作成および編集でき、適切な時間に実行するようにスケジュールできます。
* また、1つ以上のクライアントに対してリモートコマンドを実行することもできます。
  ** リモートコマンドを使用すると、個々のクライアント、または検索語に一致するすべてのクライアントにコマンドを発行できます。


[[recurring_actions]]
== 定期的なアクション


個々のクライアント、システムグループ、または組織内のすべてのクライアントに定期的なアクションを適用することができます。

現在、{productname}は、次のアクションタイプを定期的なアクションとしてサポートしています。

- [parameter]``Highstate:`` highstateを実行します。
- [parameter]``カスタム状態:`` カスタム状態のセットを実行します。カスタム状態には、{productname}によって提供される内部状態、またはユーザによって作成された設定チャンネルのいずれかを指定できます。

設定チャンネルの詳細については、xref:client-configuration:configuration-management.adoc[]を参照してください。



.プロシージャ: 新しい定期的なアクションを作成する
. 個々のクライアントに定期的なアクションを適用するには、［[guimenu]``システム``］に移動し、クライアントをクリックしてスケジュールを設定し、［[guimenu]``定期的なアクション``］タブに移動します。
. システムグループに定期的なアクションを適用するには、menu:システム[システムグループ]に移動し、スケジュールを設定するグループを選択して、［[guimenu]``定期的なアクション``］タブに移動します。
. btn:[作成]をクリックします。
. ［[guimenu]``動作タイプ``］ドロップダウンから動作タイプを選択します。
. 新しいスケジュールの名前を入力します。
. 定期的なアクションの頻度を選択します。
+
* [guimenu]``毎時:`` 各時間の分を入力します。
    たとえば、[parameter]``15``は毎時15分にアクションを実行します。
* [guimenu]``毎日:`` 毎日の時間を選択します。
    たとえば、[parameter]``01:00``は、{productname}サーバのタイムゾーンで、毎日0100にアクションを実行します。
* [guimenu]``毎週:`` 指定した時刻に毎週アクションを実行する曜日と時刻を選択します。
* [guimenu]``毎月:`` 指定した時刻に毎月アクションを実行する日付と時刻を選択します。
* [guimenu]``独自のクォーツ書式:`` 詳細オプションについては、独自のクォーツ文字列を入力します。
    たとえば、毎月毎週土曜日の0215に定期的なアクションを実行するには、次のように入力します。
+
----
0 15 2 ? * 7
----
. オプション: ［[guimenu]``テストモード``］スイッチを オンに切り替えて、テストモードでスケジュールを実行します。
. [parameter]``カスタム状態``タイプのアクションの場合は、利用可能な状態のリストから状態を選択し、btn:[変更点の保存]をクリックします。これにより、現在の状態選択のみが保存され、スケジュールは保存されません。
. 次のペインで、選択した状態をドラッグアンドドロップして実行順序に配置し、btn:[確認]をクリックします。
. btn:[スケジュールの作成]をクリックして保存し、既存のスケジュールの完全なリストを表示します。


組織管理者は、組織内のすべてのクライアントに定期的なアクションを設定および編集できます。menu:ホーム[組織 > 定期的なアクション]に移動して、組織全体に適用されるすべての定期的なアクションを表示します。

{productname}管理者は、すべての組織のすべてのクライアントの定期的なアクションを設定および編集できます。menu:管理[組織]に移動し、管理する組織を選択して、menu:状態[定期的なアクション]タブに移動します。



== 動作チェーン

クライアントに対して多数の連続動作を実行する必要がある場合は、順序を確実に反映するための動作チェーンを作成できます。

デフォルトでは、ほとんどのクライアントはコマンドが発行されるとすぐに動作を実行します。 場合によっては、動作に時間がかかることがあります。これは、その後に実行された動作が失敗することを意味します。 たとえば、クライアントに再起動を指示してから2番目のコマンドを発行すると、再起動がまだ行われているため、2番目の動作が失敗する可能性があります。 アクションが正しい順序で実行されるようにするには、動作チェーンを使用します。

[IMPORTANT]
====
トランザクション更新システムの場合、動作チェーンは、再起動動作があるまで単一スナップショット内で実行されます。 これによりいくつかの制限が発生する可能性があります。

ifeval::[{uyuni-content} == true]
詳細については、xref:client-configuration:clients-slemicro.adoc[]およびxref:client-configuration:clients-opensuseleapmicro.adoc[]を参照してください。
endif::[]

ifeval::[{mlm-content} == true]
詳細については、xref:client-configuration:clients-slemicro.adoc[]を参照してください。
endif::[]
====

動作チェーンは、すべてのクライアントで使用できます。動作チェーンには、次の動作を任意の数、任意の順序で含めることができます。

* menu:システムの詳細[リモートコマンド]
* menu:システムの詳細[システムの再起動をスケジュール]
* menu:システムの詳細[状態 > highstate]
* menu:システムの詳細[ソフトウェア > パッケージ > 一覧表示/削除]
* menu:システムの詳細[ソフトウェア > パッケージ > インストール]
* menu:システムの詳細[ソフトウェア > パッケージ > アップグレード]
* menu:システムの詳細[ソフトウェア > パッチ]
* menu:システムの詳細[ソフトウェア > ソフトウェアチャンネル]
* menu:システムの詳細[設定]
* menu:イメージ[ビルド]



[NOTE]
====
動作チェーンはユーザ固有です。 {webui}で動作チェーンを表示するには、動作チェーンを作成した同じユーザとしてサインインする必要があります。
====



.プロシージャ: 新しい動作チェーンの作成
. {productname} {webui}で、動作チェーンで実行する最初の動作に移動します。 たとえば、クライアントの［[guimenu]``システムの詳細``］に移動し、btn:[システムの再起動をスケジュール]をクリックします。
. ［[guimenu]``以下に追加``］フィールドをオンにし、追加する動作チェーンを選択します。
+
* これが最初の動作チェーンの場合は、［``新しい動作チェーン``］を選択します。
* 動作チェーンがすでに存在する場合は、リストから選択します。
* 既存の動作チェーンがすでにあるが、新しい動作チェーンを作成する場合は、作成する新しい動作チェーンの名前の入力を開始します。
. 動作を確認します。
    動作はすぐには実行されず、新しい動作チェーンが作成され、これを確認する青いバーが画面の上部に表示されます。
. ［[guimenu]``以下に追加``］フィールドをオンにし、追加する動作チェーンの名前を選択して、動作チェーンに動作の追加を続行します。
. 動作を追加し終えたら、menu:スケジュール[動作チェーン]に移動して、リストから動作チェーンを選択します。
. 動作をドラッグして正しい位置にドロップすることで、動作の順序を変更します。
    青いプラス記号をクリックして、動作が実行されるクライアントを表示します。 btn:[保存]をクリックして、変更を保存します。
. 実行する動作チェーンの時刻をスケジュールし、btn:[保存とスケジュール]をクリックします。
    btn:[保存]またはbtn:[保存とスケジュール]のいずれかをクリックせずにページを離れる場合、未保存の変更はすべて破棄されます。

[NOTE]
====
動作チェーン内の1つの動作が失敗すると、動作チェーンが停止し、これ以上の動作は実行されません。
====

menu:スケジュール[待機中の動作]に移動して、動作チェーンからスケジュール済みの動作を確認できます。



== リモートコマンド

このプロシージャを使用して、{salt}を介してリモートコマンドを実行します。

開始する前に、インストールされているオペレーティングシステムに適したツールの子チャンネルにクライアントがサブスクライブされていることを確認してください。 ソフトウェアチャンネルへのサブスクライブの詳細については、xref:client-configuration:channels.adoc[]を参照してください。

[IMPORTANT]
====
//* For transactional update systems, consider that a remote command is run inside a single snapshot.
//  This can cause some limitations.

ifeval::[{uyuni-content} == true]
* トランザクション更新システムの場合、リモートコマンドが単一スナップショット内で実行されることを考慮します。これによりいくつかの制限が発生する可能性があります。詳細については、xref:client-configuration:clients-slemicro.adoc[]およびxref:client-configuration:clients-opensuseleapmicro.adoc[]を参照してください。
endif::[]

ifeval::[{mlm-content} == true]
* トランザクション更新システムの場合、リモートコマンドが単一スナップショット内で実行されることを考慮します。これによりいくつかの制限が発生する可能性があります。詳細については、xref:client-configuration:clients-slemicro.adoc[]を参照してください。
endif::[]

* リモートコマンドはクライアントの[path]``/tmp/``ディレクトリから実行されます。リモートコマンドが正確に機能するようにするには、[parameter]``noexec``オプションを指定して``/tmp``をマウントしないでください 。詳細については、xref:administration:troubleshooting/tshoot-mounting-tmp-with-noexec.adoc[noexecで/tmpをマウントする場合のトラブルシューティング]を参照してください。

* ［[guimenu]``リモートコマンド``］ページから実行されるすべてのコマンドは、クライアント上で{rootuser}として実行されます。 ワイルドカードを使用して、任意の数のシステムでコマンドを実行できます。 コマンドを発行する前に、必ず十分注意してコマンドを確認してください。
====


.Procedure: Running Remote Commands on Clients
. menu:Salt[リモートコマンド]に移動します。
. 最初のフィールドで、``@``記号の前に、発行するコマンドを入力します。
. 2番目のフィールドで、``@``記号の後に、コマンドを発行するクライアントを入力します。
    個々のクライアントの``minion-id``を入力することも、ワイルドカードを使用してクライアントの範囲をターゲットにすることもできます。
. btn:[ターゲットの検索]をクリックして、ターゲットにしたクライアントを確認し、正しい詳細情報を使用していることを確認します。
. btn:[コマンドの実行]をクリックして、ターゲットクライアントにコマンドを発行します。
