[[channel-management]]
= チャンネル管理
:revdate: 2025-02-28
:page-revdate: {revdate}

チャンネルはソフトウェアパッケージをグループ化する方法です。

{productname}では、チャンネルはベースチャンネルと子チャンネルにグループ化され、ベースチャンネルはオペレーティングシステムのタイプ、バージョン、およびアーキテクチャ別にグループ化され、子チャンネルは関連するベースチャンネルと互換性があります。 クライアントがベースチャンネルに割り当てられている場合、そのシステムでは関連する子チャンネルのみをインストールできます。 この方法でチャンネルを編成すると、互換性のあるパッケージのみが各システムにインストールされます。

ソフトウェアチャンネルは、リポジトリを使用してパッケージを提供します。 チャンネルはリポジトリを{productname}にミラーリングし、パッケージ名やその他のデータは{productname}データベースに保存されます。 1つのチャンネルに関連付けられたリポジトリはいくつでも持つことができます。 これらのリポジトリのソフトウェアは、クライアントを適切なチャンネルにサブスクライブすることでクライアントにインストールできます。

クライアントはベースチャンネルにのみ割り当てることができます。 その後、クライアントは、そのベースチャンネルとその子チャンネルのいずれかに関連付けられたリポジトリからパッケージをインストールまたは更新できます。

{productname}には、{productname}を実行するために必要なすべてのものを提供する、複数のベンダチャンネルが用意されています。 {productname}の管理者とチャンネル管理者には、チャンネル管理権限があり、これにより、独自のカスタムチャンネルを作成して管理することができます。 環境で独自のパッケージを使用する場合は、カスタムチャンネルを作成できます。 カスタムチャンネルはベースチャンネルとして使用することも、ベンダベースチャンネルに関連付けることもできます。

カスタムチャンネルの作成の詳細については、xref:administration:custom-channels.adoc[]を参照してください。



== チャンネル管理


デフォルトでは、すべてのユーザがシステムにチャンネルをサブスクライブできます。 {webui}を使用してチャンネルに制限を実装できます。

.プロシージャ: チャンネルへのサブスクライバアクセスの制限
. {productname} {webui}で、menu:ソフトウェア[チャンネルリスト]に移動して、編集するチャンネルを選択します。
. ［[guimenu]``ユーザごとのサブスクリプション制限``］セクションを見つけて、［[guimenu]``この組織内の指定されたユーザのみがこのチャンネルにサブスクライブできます``］をオンにします。 btn:[更新]をクリックして、変更を保存します。
. ［[guimenu]``サブスクライバ``］タブに移動して、必要に応じてユーザを選択または選択解除します。



[[delete_channels]]
== チャンネルの削除

コマンドプロンプトからベンダソフトウェアチャンネルを削除できます。

.プロシージャ: ベンダチャンネルを削除する
. {productname}サーバのコマンドプロンプトで、rootとして、使用できるベンダチャンネルを一覧にし、削除するチャンネルをメモします。
+
----
mgr-sync list チャンネル
----
. チャンネルを削除します。
+
----
spacewalk-remove-channel -c <channel-name>
----

ifeval::[{mlm-content} == true]
* チャンネルを手動で削除する方法の詳細については、xref:administration:removing-channels.adoc[]を参照してください。
endif::[]

* カスタムチャンネルの削除については、xref:administration:custom-channels.adoc[]を参照してください。
