[[content-staging]]
= コンテンツのステージング
:revdate: 2025-01-13
:page-revdate: {revdate}


ステージングは、クライアントがインストール前にパッケージを事前にダウンロードするために使用されます。 これにより、パッケージのインストールをスケジュールされたらすぐに開始できるため、メンテナンスウィンドウに必要な時間を短縮できます。


== コンテンツステージングの有効化


組織全体のコンテンツステージングを管理できます。 {productname} {webui}で、menu:管理[組織]に移動して、使用可能な組織のリストを表示します。 組織の名前をクリックし、［[guimenu]``ステージングコンテンツの有効化``］ ボックスをオンにして、この組織のクライアントがパッケージデータをステージングできるようにします。

[NOTE]
====
組織を作成および管理するには、{productname}管理者としてログインする必要があります。
====

[path]``/etc/sysconfig/rhn/up2date``を編集し、次の行を追加または編集して、コマンドプロンプトでステージングを有効にすることもできます。

----
stagingContent=1
stagingContentWindow=24
----


``stagingContentWindow``パラメータは時間単位で表される時間値で、ダウンロードの開始時間を決定します。 これは、スケジュールされたインストールまたは更新時間までの時間数です。 この例では、インストール時間の24時間前にコンテンツがダウンロードされます。 ダウンロードの開始時間は、システムで選択した連絡方法によって異なります。

次回、アクションがスケジュールされると、パッケージは自動的にダウンロードされますが、インストールはされません。 スケジュールされた時間に、ステージングされたパッケージがインストールされます。



== コンテンツステージングの設定

コンテンツステージングを設定するために使用される次の2つのパラメータがあります。

* [parameter]``salt_content_staging_advance``は、コンテンツステージングウィンドウが開くまでの時間です(時間単位)。
    これは、インストールが開始されるまでの時間数で、この時間に達するとパッケージのダウンロードを開始できます。
* [parameter]``salt_content_staging_window``は、コンテンツステージングウィンドウの期間(時間単位)です。
    これは、インストールが開始されるまでにクライアントがパッケージをステージングする必要がある時間数です。

たとえば [parameter]``salt_content_staging_advance``が6時間に設定されていて、[parameter]``salt_content_staging_window``が2時間に設定されている場合、ステージングウィンドウはインストール時間の6時間前に開き、2時間開いたままになります。 インストールが開始されるまで、残りの4時間以内にパッケージはダウンロードされません。

[parameter]``salt_content_staging_advance``および[parameter]``salt_content_staging_window``の両方に同じ値を設定する場合、インストールが開始されるまでパッケージをダウンロードできます。

[path]``/usr/share/rhn/config-defaults/rhn_java.conf``で、コンテンツステージングパラメータを設定します。

デフォルト値:

* [path]``salt_content_staging_advance: 8 hours``
* [path]``salt_content_staging_window: 8 hours``


[NOTE]
====
これらのパラメータを正しく機能させるには、コンテンツステージングを有効にする必要があります。
====
