[[content-lifecycle-examples]]
= コンテンツライフサイクル管理の例
:revdate: 2025-01-30
:page-revdate: {revdate}

このセクションでは、コンテンツライフサイクル管理の使用方法の一般的な例をいくつか示します。 これらの例を使用して、独自にカスタマイズされた実装を構築します。



[#create-proj-for-patch-cycle]
== 月次パッチサイクルのプロジェクトの作成

月次パッチサイクルのプロジェクト例は、以下で構成されます。

* `By Date`（日付別）フィルタの作成
* プロジェクトへのフィルタの追加
* 新しいプロジェクトビルドへのフィルタの適用
* プロジェクトからのパッチの除外
* プロジェクトにパッチを含める



[#create-a-filter]
=== `By Date`（日付別）フィルタの作成

指定した日付以降にリリースされたすべてのパッチは``By Date``（日付別）フィルタによって除外されます。 このフィルタは、月次パッチサイクルに従うコンテンツライフサイクルプロジェクトに役立ちます。


.プロシージャ: ``By Date``（日付別）フィルタの作成
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[フィルタ]に移動して、btn:[Create Filter]（フィルタの作成）をクリックします。

. ［[guimenu]``フィルタ名``］フィールドに、フィルタの名前を入力します。
    たとえば、[systemitem]``Exclude patches by date``（日付別にパッチを除外する）。

. ［[guimenu]``フィルタタイプ``］フィールドで、［[guimenu]``Patch (Issue date)``］（パッチ(発行日)）を選択します。

. ［ [guimenu]``マッチャー``］フィールドでは、［[guimenu]``later or equal``］（それ以降）が自動選択されます。

. 日時を選択します。

. btn:[保存]をクリックします。

____


[#add-filter-to-proj]
=== プロジェクトへのフィルタの追加

.プロシージャ: プロジェクトへのフィルタの追加
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[プロジェクト]に移動して、リストからプロジェクトを選択します。

. btn:[フィルタの割り当て／取り外し]リンクをクリックして、すべての使用可能なフィルタを表示します

. 新しい［ [guimenu]``Exclude patches by date``］（日付別にパッチを除外する）を選択します。

. btn:[保存]をクリックします。
____



[#apply-filter-to-project-build]
=== 新しいプロジェクトビルドへのフィルタの適用

新しいフィルタがフィルタリストに追加されますが、プロジェクトに適用する必要があります。 フィルタを適用するには、最初の環境を構築する必要があります。

.プロシージャ: フィルタの使用
[role=procedure]
____
. btn:[ビルド]をクリックして、最初の環境を構築します。

. オプション: メッセージを追加します。
    メッセージを使用して、ビルド履歴を追跡できます。

. テストサーバで新しいチャンネルを使用して、フィルタが正しく機能していることを確認します。

. btn:[Promote]（プロモート）をクリックして、次の環境にコンテンツを移動します。
    多数のフィルタがある場合、または非常に複雑な場合は、ビルドに時間がかかります。

____


[#exclude-a-patch]
=== プロジェクトからのパッチの除外

テストは、問題を発見するのに役立つ場合があります。 問題が見つかった場合は、`by date`（日付別）フィルタの前にリリースされた問題のパッチを除外します。

.プロシージャ: パッチの除外
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[フィルタ]に移動して、btn:[Create Filter]（フィルタの作成）をクリックします。

. ［ [guimenu]``フィルタ名``］フィールドに、フィルタの名前を入力します。
    たとえば、［[systemitem]``Exclude openjdk patch``］（openjdkパッチの除外）。

. ［[guimenu]``フィルタタイプ``］フィールドで、［[guimenu]``Patch (Advisory Name)``］（パッチ(アドバイザリ名)）を選択します。

. ［ [guimenu]``マッチャー``］フィールドで、［[guimenu]``等しい``］を選択します。

. ［[guimenu]``アドバイザリ名``］フィールドに、アドバイザリの名前を入力します。
    たとえば、[systemitem]``SUSE-15-2019-1807``。

. btn:[保存]をクリックします。

. menu:コンテンツライフサイクル[プロジェクト]に移動して、プロジェクトを選択します。

. btn:[フィルタの割り当て／取り外し]リンクをクリックして、［[guimenu]``Exclude openjdk patch``］（openjdkパッチの除外）を選択し、btn:[保存]をクリックします。

____

btn:[ビルド]ボタンを使用してプロジェクトを再構築すると、新しいフィルタが、以前に追加した［ [guimenu]``by date``］（日付別）フィルタとともに使用されます。



[#include-a-patch]
=== プロジェクトにパッチを含める

この例では、セキュリティアラートを受信しています。 重要なセキュリティパッチが、現在作業している月の最初の日から数日後にリリースされました。 新しいパッチの名前は``SUSE-15-2019-2071``です。 この新しいパッチを環境に含める必要があります。

[IMPORTANT]
====
［[guimenu]``許可``］フィルタ規則は、［[guimenu]``拒否``］フィルタ規則の除外機能を上書きします。 詳細については、xref:administration:content-lifecycle.adoc[]を参照してください。
====

.プロシージャ: プロジェクトにパッチを含める
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[フィルタ]に移動して、btn:[Create Filter]（フィルタの作成）をクリックします。

. ［[guimenu]``フィルタ名``］フィールドに、フィルタの名前を入力します。
    たとえば、[systemitem]``Include kernel security fix``（カーネルセキュリティ修正を含める）。

. ［[guimenu]``フィルタタイプ``］フィールドで、［[guimenu]``Patch (Advisory Name)``］（パッチ(アドバイザリ名)）を選択します。

. ［ [guimenu]``マッチャー``］フィールドで、［[guimenu]``等しい``］を選択します。

. ［ [guimenu]``アドバイザリ名``］フィールドに、「[guimenu]``SUSE-15-2019-2071``」と入力し、［[guimenu]``許可``］をオンにします。

. btn:[保存]をクリックして、フィルタを保存します。

. menu:コンテンツライフサイクル[プロジェクト]に移動して、リストからプロジェクトを選択します。

. btn:[フィルタの割り当て／取り外し]をクリックして、［[guimenu]``Include kernel security patch``］（カーネルセキュリティパッチを含める）を選択します。

. btn:[保存]をクリックします。

. btn:[ビルド]をクリックして、環境を再構築します。

____


[#update-a-patch-cycle]
== 既存の月次パッチサイクルの更新

月次パッチサイクルが完了すると、次の月のパッチサイクルを更新できます。

.プロシージャ: 月次パッチサイクルの更新
[role=procedure]
____
. ［[guimenu]``by date``］（日付別）フィールドで、フィルタの日付を次の月に変更します。
    または、新しいフィルタを作成して、プロジェクトへの割り当てを変更します。

. ``SUSE-15-2019-1807``の除外フィルタをプロジェクトから取り外すことができるかどうか確認します。
    この問題を解決するために使用できる新しいパッチがある場合があります。

. 以前に追加した［``許可``］フィルタを取り外します。
    パッチはデフォルトで含まれています。

. プロジェクトを再構築して、来月のパッチを適用した新しい環境を作成します。

____


[#enhance-project-with-livepatching]
== ライブパッチ処理でプロジェクトを強化

このセクションでは、ライブパッチ処理用の環境を作成するためのフィルタの設定について説明します。

[IMPORTANT]
====
ライブパッチ処理を使用する準備をしている場合には、いくつかの重要な考慮事項があります。

* システムでカーネルバージョンを1つだけ使用してください。
    ライブパッチ処理パッケージは、特定のカーネルとともにインストールされます。
* ライブパッチ処理の更新は、1つのパッチとして出荷されます。
* 新しいシリーズのライブパッチ処理カーネルを開始するカーネルパッチごとに、``要再起動``フラグが表示されます。
    これらのカーネルパッチには、ライブパッチ処理ツールが付属しています。 それらをインストールしたら、翌年になる前に少なくとも1回システムを再起動する必要があります。
* インストール済みカーネルバージョンに一致するライブパッチ更新のみをインストールします。
* ライブパッチは、スタンドアロンパッチとして提供されます。
    現在インストールされているカーネルバージョンよりも新しいカーネルバージョンの通常のカーネルパッチをすべて除外する必要があります。
====



[#exclude-higher-kernel-version]
=== より新しいカーネルバージョンのパッケージを除外する

この例では、``SUSE-15-2019-1244``パッチでシステムを更新します。 このパッチには、``kernel-default-4.12.14-150.17.1-x86_64``が含まれています。

より新しいバージョンの[package]``kernel-default``と[package]``kernel-default-base``を含むすべてのパッチを除外する必要があります。

.プロシージャ: より新しいカーネルバージョンのパッケージを除外する
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[フィルタ]に移動して、btn:[Create Filter]（フィルタの作成）をクリックします。

. ［[guimenu]``フィルタ名``］フィールドに、フィルタの名前を入力します。
    たとえば、[systemitem]``Exclude kernel greater than 4.12.14-150.17.1``（4.12.14-150.17.1より新しいカーネルを除外する）。

. ［[guimenu]``フィルタタイプ``］フィールドで、［[guimenu]``Patch (Contains Package)``］（パッチ(パッケージを含む)）を選択します。

. ［[guimenu]``マッチャー``］フィールドで、［[guimenu]``version greater than``］（指定したものより新しいバージョン）を選択します。

. ［[guimenu]``パッケージ名``］フィールドに、「[systemitem]``kernel-default``」と入力します。

. Leave the [guimenu]``Epoch`` field empty.

. ［[guimenu]``バージョン``］フィールドに、「[systemitem]``4.12.14``」と入力します。

. ［[guimenu]``リリース``］フィールドに、「 [systemitem]``150.17.1``」と入力します。

. btn:[保存]をクリックして、フィルタを保存します。

. menu:コンテンツライフサイクル[プロジェクト]に移動して、プロジェクトを選択します。

. btn:[フィルタの割り当て／取り外し]をクリックします。

. ［[guimenu]``Exclude kernel greater than 4.12.14-150.17.1``］（4.12.14-150.17.1より新しいカーネルを除外する）を選択して、btn:[保存]をクリックします。

____

[package]``kernel-default-base``パッケージについても、この手順を繰り返す必要があります。


btn:[ビルド]をクリックすると、新しい環境が作成されます。 新しい環境には、インストールしたバージョンまでのすべてのカーネルパッチが含まれています。

[NOTE]
====
より新しいカーネルバージョンのすべてのカーネルパッチは削除されます。 ライブパッチ処理カーネルは、シリーズの最初でない限り、引き続き使用できます。
====

このプロシージャはフィルタテンプレートを使用して自動化できます。 ライブパッチ処理フィルタテンプレートの適用方法の詳細については、xref:administration:content-lifecycle.adoc#filter-templates[]を参照してください。



[#switch-kernel-version-for-live-patching]
== ライブパッチ処理用の新しいカーネルバージョンに切り替える

特定のカーネルバージョン用のライブパッチ処理は、1年間のみ利用できます。 1年後、システムのカーネルを更新する必要があります。 以下の環境変更を実行します。

.プロシージャ: 新しいカーネルバージョンに切り替える
[role=procedure]
____
. アップグレードするカーネルバージョンを決定します。
    例: `4.12.14-150.32.1`

. 新しいカーネルバージョンフィルタを作成します。

. 古いカーネルに関連付けられているすべての以前のライブパッチ処理フィルタを取り外します。

. 新しいカーネルバージョンフィルタを割り当てます。

. btn:[ビルド]をクリックして、環境を再構築します。

+

[IMPORTANT]
====
ビルドが完了したら、以下の処理を実行する2つのフィルタを直ちに再度割り当てる必要があります。

* ``reboot_suggested``キーワードを含むパッチを拒否する

* ``installhint(reboot-needed)``という名前を提供するパッケージを含むパッチを拒否する
====

____

新しい環境には、選択した新しいカーネルバージョンまでのすべてのカーネルパッチが含まれています。 アップグレードを実行した後で、システムを再起動する必要があります。 新しいカーネルは1年間有効です。 その年にインストールされたすべてのパッケージは、現在のライブパッチ処理カーネルフィルタと一致します。



[#appstream-filters]
== AppStreamフィルタ

コンテンツライフサイクル管理プロジェクトでは、AppStreamフィルタを使用して、モジュラーリポジトリを通常のリポジトリに変換できます。これはパッケージをリポジトリに保持し、モジュールのメタデータを削除することにより行われます 。その結果作成されたリポジトリは、通常のリポジトリと同じ方法で{productname}で使用できます。

[NOTE]
====

ifeval::[{uyuni-content} == true]
AppStreamリポジトリは{webui}全体でネイティブにサポートされています。
endif::[]

ifeval::[{suma-content} == true]
{productname} 5.0から、AppStreamリポジトリは{webui}全体でネイティブにサポートされています。
endif::[]

したがって、このプロセスはAppStreamリポジトリを操作するために必須ではありません。
====

AppStreamフィルタはターゲットリポジトリに含める単一のモジュールストリームを選択します。 複数のフィルタを追加して、複数のモジュールストリームを選択できます。

CLMプロジェクトでAppStreamフィルタを使用しない場合は、モジュラーソースのモジュールメタデータは未加工のままで、ターゲットリポジトリには同じモジュールメタデータが含まれます。 CLMプロジェクトで少なくとも1つのAppStreamフィルタが有効になっている限り、すべてのターゲットリポジトリが通常のリポジトリに変換されます。

場合によっては、どのモジュールのパッケージも含めずに通常のリポジトリを構築したい場合があります。 これを行うには、マッチャー [parameter]``なし (モジュール化を無効にする)``を使用して AppStreamフィルタを追加します。 これにより、ターゲットリポジトリ内のすべてのモジュールが無効になります。 これは、ほとんどのモジュールのデフォルトバージョンが通常のパッケージとしてAppStreamリポジトリにすでに含まれている、{rhel}{nbsp}9のクライアントに特に役立ちます。

AppStreamフィルタを使用するには、``{rhel} AppStreams``などのモジュラーリポジトリを含むCLMプロジェクトが必要です。 開始する前に、必要なモジュールがソースとして含まれていることを確認してください。


.プロシージャ: AppStreamフィルタの使用
[role=procedure]
____
. {productname} {webui}で、{rhel}{nbsp}8または9 CLMプロジェクトに移動します。
    プロジェクトにAppStreamチャンネルが含まれていることを確認します。

. btn:[Create Filter] (フィルタの作成)をクリックし、次のパラメータを使用します。

+

* ［[guimenu]``フィルタ名``］フィールドには、新しいフィルタの名前を入力します。

* ［[guimenu]``フィルタタイプ``］フィールドで、［[parameter]``Module (Stream)``］（モジュール(ストリーム)）を選択します。

* ［ [guimenu]``マッチャー``］フィールドで、［[parameter]``等しい``］を選択します。

* ［[guimenu]``モジュール名``］フィールドに、モジュール名を入力します。
    たとえば、[parameter]``postgresql``。

* ［[guimenu]``ストリーム``］フィールドに、目的のストリームの名前を入力します。
    たとえば、[parameter]``10``。 このフィールドを空のままにする場合、モジュールのデフォルトのストリームが選択されます。

. btn:[保存]をクリックして、新しいフィルタを作成します。

. menu:コンテンツライフサイクル[プロジェクト]に移動して、プロジェクトを選択します。

. btn:[フィルタの割り当て／取り外し]をクリックし、新しいAppStreamフィルタを選択して、btn:[保存]をクリックします。

____

［``Create/Edit Filter``］（フィルタの作成/編集）フォームのブラウズ機能を使用して、モジュラーチャンネルで使用可能なモジュールストリームのリストからモジュールを選択できます。


.プロシージャ: 使用可能なモジュールストリームのブラウズ
[role=procedure]
____
. {productname} {webui}で、{rhel}{nbsp}8または9 CLMプロジェクトに移動します。
    プロジェクトにAppStreamチャンネルが含まれていることを確認します。

. btn:[Create Filter] (フィルタの作成)をクリックし、次のパラメータを使用します。

+

* ［[guimenu]``フィルタ名``］フィールドには、新しいフィルタの名前を入力します。

* ［[guimenu]``フィルタタイプ``］フィールドで、［[parameter]``Module (Stream)``］（モジュール(ストリーム)）を選択します。

* ［ [guimenu]``マッチャー``］フィールドで、［[parameter]``等しい``］を選択します。

. ［``Browse available modules``］（使用可能なモジュールをブラウズ）をクリックして、すべてのモジュラーチャンネルを表示します。

. モジュールとストリームをブラウズするチャンネルを選択します。

+

* ［[guimenu]``モジュール名``］フィールドで、検索するモジュール名の入力を開始するか、リストから選択します。

* ［[guimenu]``ストリーム``］フィールドで、検索するストリーム名の入力を開始するか、リストから選択します。

____

[NOTE]
====
チャンネル選択はモジュールのブラウズのみを目的としています。 選択したチャンネルはフィルタとともに保存されず、CLMプロセスには影響しません。
====

ターゲットリポジトリに含める他のモジュールストリーム用に追加のAppStreamフィルタを作成できます。 選択したストリームが依存するモジュールストリームは自動的に含まれます。

[NOTE]
====
競合する、互換性のない、または欠落しているモジュールストリームを指定しないように注意してください。 たとえば、同じモジュールから2つのストリームを選択すると無効になります。
====

.プロシージャ: モジュール化の無効化
[role=procedure]
____
. {productname} {webui}で、{rhel}{nbsp}8または9 CLMプロジェクトに移動します。
    プロジェクトにAppStreamチャンネルが含まれていることを確認します。

. btn:[Create Filter] (フィルタの作成)をクリックし、次のパラメータを使用します。

+

* ［[guimenu]``フィルタ名``］フィールドには、新しいフィルタの名前を入力します。

* ［[guimenu]``フィルタタイプ``］フィールドで、［[parameter]``Module (Stream)``］（モジュール(ストリーム)）を選択します。

* ［[guimenu]``マッチャー``］フィールドで、［[parameter]``なし (モジュール化を無効にする)``］を選択します。

. btn:[保存]をクリックして、新しいフィルタを作成します。

. menu:コンテンツライフサイクル[プロジェクト]に移動して、プロジェクトを選択します。

. btn:[フィルタの割り当て／取り外し]をクリックし、新しいAppStreamフィルタを選択して、btn:[保存]をクリックします。

____

これにより、モジュールに属するパッケージを除いて、モジュールのメタデータがターゲットリポジトリから効率的に削除されます。

{webui}のbtn:[ビルド]ボタンを使用してCLMプロジェクトを構築する場合、ターゲットリポジトリは、選択したモジュールストリームからのパッケージを含む、モジュールを含まない通常のリポジトリです。

[NOTE]
====
{rhel}{nbsp}8のプロジェクトでモジュール化を完全に無効にすると、一部のモジュールが {rhel}{nbsp}8での正常な動作に不可欠であるため、環境に不具合が生じる可能性があります。
====
