[[content-lifecycle]]
= コンテンツライフサイクル管理
:revdate: 2025-02-05
:page-revdate: {revdate}

コンテンツライフサイクル管理では運用クライアントを更新する前にパッケージをカスタマイズおよびテストできます。 これは、限られたメンテナンスウィンドウ中に更新を適用する必要がある場合に特に役立ちます。

コンテンツライフサイクル管理では、ソフトウェアチャンネルをソースとして選択し、必要に応じて環境に合わせて調整して、運用クライアントにインストールする前に徹底的にテストすることがでます。

ベンダチャンネルを直接変更することはできませんが、パッケージとカスタムパッチを追加または削除することで、それらのチャンネルのクローンを作成し、クローンを変更することができます。 これらのクローンチャンネルをテストクライアントに割り当てて、クライアントが期待どおりに動作することを確認できます。

[NOTE]
====
デフォルトでは、クローンベンダチャンネルは元のベンダチャンネルと一致し、依存関係を自動的に選択します。 [path]``/etc/rhn/rhn.conf``に次のオプションを追加することにより、クローンチャンネルの自動選択を無効にできます。

----
java.cloned_channel_auto_selection = false
----
====

次に、すべてのテストに合格すると、クローンチャンネルを運用サーバにプロモートできます。

これは、ソフトウェアチャンネルがライフサイクルで移動できる一連の環境を通じて実現されます。 ほとんどの環境ライフサイクルには、少なくともテスト環境と運用環境が含まれていますが、必要な数の環境を持つことができます。

このセクションでは、基本的なコンテンツライフサイクル手順、および使用可能なフィルタについて説明します。 より具体的な例については、xref:administration:content-lifecycle-examples.adoc[]を参照してください。



== コンテンツライフサイクルプロジェクトの作成


コンテンツライフサイクルを設定するには、プロジェクトから開始する必要があります。 プロジェクトでは、ソフトウェアチャンネルソース、パッケージの検索に使用されるフィルタ、およびビルド環境について定義します。

.プロシージャ: コンテンツライフサイクルプロジェクトの作成
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[プロジェクト]に移動し、btn:[プロジェクトの作成]をクリックします。

. ［[guimenu]``ラベル``］フィールドに、プロジェクトのラベルを入力します。
    ［[guimenu]``ラベル``］フィールドには、小文字、数字、ピリオド、ハイフン、およびアンダースコアのみを入力できます。

. ［ [guimenu]``名前``］フィールドに、プロジェクトのわかりやすい名前を入力します。

. btn:[作成]ボタンをクリックして、プロジェクトを作成し、プロジェクトページに戻ります。

. btn:[Attach/Detach Sources]（ソースの割り当て/取り外し）をクリックします。

. ［[guimenu]``ソース``］ダイアログで、ソースタイプを選択し、プロジェクトの ベースチャンネルを選択します。
    チャンネルが必須か推奨されるかに関する情報を含め、選択したベースチャンネルで使用可能な子チャンネルが表示されます。

. 必要な子チャンネルをオンにし、btn:[保存]をクリックして、プロジェクトページに戻ります。
    選択したソフトウェアチャンネルが表示されているはずです。

. btn:[フィルタの割り当て／取り外し]をクリックします。

. ［[guimenu]``フィルタ``］ダイアログで、プロジェクトに割り当てるフィルタを選択します。
    新しいフィルタを作成するには、btn:[新しいフィルタの作成]をクリックします。

. btn:[環境の追加]をクリックします。

. ［[guimenu]``環境ライフサイクル``］ダイアログで、最初の環境に、名前、ラベル、および説明を付けて、btn:[保存]をクリックします。
    ［[guimenu]``ラベル``］フィールドには、小文字、数字、ピリオド、ハイフン、およびアンダースコアのみを入力できます。

. ライフサイクルのすべての環境が完了するまで、環境の作成を続行します。
    作成時に［[guimenu]``前に挿入``］フィールドで環境を選択することで、ライフサイクルの環境の順序を選択できます。

____


== フィルタタイプ

{productname}では、プロジェクトの構築に使用するコンテンツを制御するために、さまざまなタイプのフィルタを作成できます。 フィルタを使用すると、ビルドに含めるパッケージまたはビルドから除外するパッケージを選択できます。 たとえば、すべてのカーネルパッケージを除外したり、一部のパッケージの特定のリリースのみを含めることができます。

サポートされているフィルタは次のとおりです。

* パッケージのフィルタリング
** by name（名前別）
** by name, epoch, version, release, and architecture（名前、エポック、バージョン、リリース、およびアーキテクチャ別）
** by provided name（指定された名前別）
* パッチフィルタリング
** by advisory name（アドバイザリ名別）
** by advisory type（アドバイザリタイプ別）
** by synopsis（概要別）
** by keyword（キーワード別）
** by date（日付別）
** by affected package（影響を受けるパッケージ別）
* モジュール
** by stream（ストリーム別）


[NOTE]
====
パッケージの依存は、コンテンツのフィルタリング中には解決されません。
====


フィルタで使用できるマッチャーは複数あります。 使用できるマッチャーは、選択したフィルタ タイプによって異なります。

使用できるマッチャーは次のとおりです。

* 含む
* 一致（正規表現の形式を取る必要があります）
* 等しい
* 新しい
* 新しいか等しい
* 古いか等しい
* 古い
* 新しいか等しい



=== フィルタの ``rule``パラメータ

各フィルタには``許可``または``拒否``のいずれかに設定できる``rule``パラメータがあります。 フィルタは次のように処理されます。

* パッケージまたはパッチが``拒否``フィルタを満たす場合は、結果から除外されます。
* パッケージまたはパッチが``許可``フィルタを満たす場合は、結果に含まれます（``拒否``フィルタによって除外された場合でも）。パッケージに対する``許可``フィルタはパッケージフィルタでのみ動作し、パッチに対する``許可``フィルタはパッチフィルタでのみ動作します。つまり、パッケージフィルタでは、パッチフィルタで除外されたパッケージを再び追加することはできません。また、パッケージフィルタで除外されたパッチを再び追加することもできません。

この動作は、一般的な ``拒否`` フィルタを使用して多数のパッケージまたはパッチを除外し、特定の ``許可`` フィルタで特定のパッケージまたはパッチを「チェリーピック」する場合に役立ちます。

[NOTE]
====
コンテンツフィルタは組織内でグローバルなものであり、プロジェクト間で共有できます。
====

[NOTE]
====
プロジェクトにすでに構築されたソースが含まれている場合、環境を追加すると、既存のコンテンツが自動的に入力されます。 コンテンツは、サイクルの以前の環境から引き出されます（存在していた場合）。 以前の環境がない場合は、プロジェクトソースが再度構築されるまで空のままになります。
====



[#filter-templates]
== フィルタテンプレート

いくつかの一般的なシナリオでフィルタの作成を支援するため、{productname}にはフィルタテンプレートが用意されています。 これらのテンプレートを適用すると、特定のユースケースに合わせてカスタマイズされた一連のフィルタを事前に作成できます。

このセクションでは、使用可能なテンプレートとその使用方法について説明します。



=== {suse}製品に基づくライブパッチ処理

ライブパッチ処理を含むプロジェクトでは、ライブパッチパッケージのみがクライアントに更新として提供されるように、定期的な将来のカーネルパッケージを除外する必要があります。 一方で、システムの整合性を維持するために、すでにインストールされている通常のカーネルパッケージを含める必要があります。

このテンプレートを適用すると、この動作を実現するために必要な3つのフィルタが作成されます。

* ベースカーネルバージョンと同じ``kernel-default``パッケージを含むパッチを許可する
* ``reboot_suggested``キーワードを含むパッチを拒否する
* ``installhint(reboot-needed)``という名前を提供するパッケージを含むパッチを拒否する


ライブパッチ処理プロジェクトの設定方法の詳細については、xref:administration:content-lifecycle-examples.adoc#exclude-higher-kernel-version[]を参照してください。

.プロシージャ: テンプレートの適用
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[フィルタ]に移動して、btn:[Create Filter]（フィルタの作成）をクリックします。

. ダイアログで、btn:[テンプレートを使用する]をクリックします。それに応じて入力が変更されます。

. ［[guimenu]``プレフィクス``］フィールドに名前のプレフィクスを入力します。 この値は、テンプレートによって作成された個々のフィルタの名前の前に追加されます。 テンプレートがプロジェクトのコンテキストで適用されている場合、このフィールドにはプロジェクトラベルが事前に入力されます。

. ［[guimenu]``テンプレート``］フィールドで、［[guimenu]``SUSE製品に基づくライブパッチ処理``］を選択します。

. ［[guimenu]``製品``］フィールドで、ライブパッチ処理を設定する製品を選択します。

. ［[guimenu]``カーネル``］フィールドで、選択した製品で使用可能なバージョンのリストからカーネルバージョンを選択します。以降の通常のカーネルパッチを拒否するフィルタは、このバージョンに基づきます。

. btn:[保存]をクリックして、フィルタを作成します。

. menu:コンテンツライフサイクル[プロジェクト]に移動して、プロジェクトを選択します。

. btn:[フィルタの割り当て／取り外し]をクリックします。

. 指定したプレフィクスを持つフィルタを3つ選択し、btn:[保存]をクリックします。

____


=== システムに基づくライブパッチ処理

特定の登録済みシステムにインストールされているカーネルバージョンに基づいてライブパッチ処理プロジェクトを設定する場合、「システムに基づくライブパッチ処理」テンプレートを使用できます。

このテンプレートを適用すると、この動作を実現するために必要な3つのフィルタが作成されます。

* ベースカーネルバージョンと同じ``kernel-default``パッケージを含むパッチを許可する
* ``reboot_suggested``キーワードを含むパッチを拒否する
* ``installhint(reboot-needed)``という名前を提供するパッケージを含むパッチを拒否する

ライブパッチ処理プロジェクトの設定方法の詳細については、xref:administration:content-lifecycle-examples.adoc#exclude-higher-kernel-version[]を参照してください。


.プロシージャ: テンプレートの適用
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[フィルタ]に移動して、btn:[Create Filter]（フィルタの作成）をクリックします。

. ダイアログで、btn:[テンプレートを使用する]をクリックします。 それに応じて入力が変更されます。

. ［[guimenu]``プレフィクス``］フィールドに、名前のプレフィクスを入力します。 この値はテンプレートによって作成されたすべてのフィルタの名前の前に追加されます。 テンプレートがプロジェクトのコンテキストで適用されている場合は、このフィールドにはプロジェクトラベルが事前に入力されます。

. ［[guimenu]``テンプレート``］フィールドで、［[guimenu]``固有のシステムに基づくライブパッチ処理``］を選択します。

. ［[guimenu]``システム``］フィールドで、リストからシステムを選択するか、システム名の入力を開始して、オプションを絞り込みます。

. ［[guimenu]``カーネル``］フィールドで、選択したシステムにインストールされているバージョンのリストからカーネルバージョンを選択します。 以降の通常のカーネルパッチを拒否するフィルタは、このバージョンに基づきます。

. btn:[保存]をクリックして、フィルタを作成します。

. menu:コンテンツライフサイクル[プロジェクト]に移動して、プロジェクトを選択します。

. btn:[フィルタの割り当て／取り外し]をクリックします。

. 指定したプレフィクスを持つフィルタを3つ選択し、btn:[保存]をクリックします。

____


=== デフォルトのAppStreamモジュール

プロジェクトに含まれているモジュラーリポジトリですべてのモジュールを使用できるようにする場合は、このフィルタテンプレートを使用してモジュールを自動的に追加できます。

このテンプレートを適用すると、モジュールごとにAppStreamフィルタとそのデフォルトストリームが作成されます。

このプロセスがプロジェクトのページから実行された場合、フィルタは自動的にプロジェクトに追加されます。追加されない場合は、作成されたフィルタをmenu:コンテンツライフサイクル[フィルタ]に一覧表示し、必要に応じて任意のプロジェクトに追加できます。

個々のフィルタを編集して別のモジュールストリームを選択したり、ターゲットリポジトリからそのモジュールを除外するために完全に削除したりできます。

[IMPORTANT]
====
すべてのモジュールストリームが相互に互換性があるわけではないため、個々のストリームを変更すると、モジュール間依存関係を正常に解決できない可能性があります。 この場合、プロジェクトの詳細ページのフィルタペインに問題を説明するエラーが表示され、すべてのモジュールの選択が互換性を持つようになるまでビルドボタンは無効になります。
====

[IMPORTANT]
====
{rhel}{nbsp}9以降、モジュールには定義済みのデフォルトストリームがありません。 したがって、{rhel}{nbsp}9のソースでこのテンプレートを使用しても効果はありません。
====

AppStreamリポジトリをコンテンツライフサイクル管理で設定する方法の詳細については、xref:administration:content-lifecycle-examples.adoc#appstream-filters[]を参照してください。

.プロシージャ: テンプレートの適用
[role=procedure]
____
. {productname}の{webui}で、menu:Content Lifecycle[Projects]に移動し、プロジェクトを選択します。

. ［[guimenu]``フィルタ``］セクションで、btn:[フィルタの割り当て／取り外し]をクリックし、btn:[新しいフィルタの作成]をクリックします。

. ダイアログで、btn:[テンプレートを使用する]をクリックします。 それに応じて入力が変更されます。

. ［[guimenu]``プレフィクス``］フィールドに、名前のプレフィクスを入力します。 この値はテンプレートによって作成されたすべてのフィルタの名前の前に追加されます。 テンプレートがプロジェクトのコンテキストで適用されている場合は、このフィールドにはプロジェクトラベルが事前に入力されます。

. ［[guimenu]``テンプレート``］フィールドで、［[guimenu]``デフォルトのAppStreamモジュール``］を選択します。

. ［[guimenu]``チャンネル``］フィールドで、モジュールを取得するモジュラーチャンネルを選択します。このドロップダウンには、モジュラーチャンネルのみが表示されます。

. btn:[保存]をクリックして、フィルタを作成します。

. ［[guimenu]``フィルタ``］セクションまでスクロールして、新しく割り当てられたAppStreamフィルタを確認します。

. 個々のフィルタを編集/削除して、ニーズに合わせてプロジェクトを調整できます。

____


== コンテンツライフサイクルプロジェクトの構築

プロジェクトを作成し、環境を定義し、ソースとフィルタを割り当てたら、初めてプロジェクトを構築できます。

構築によって、割り当てられたソースにフィルタが適用され、プロジェクトの最初の環境にそれらが複製されます。


複数のコンテンツプロジェクトのソースとして同じベンダチャンネルを使用できます。 この場合、{productname}はクローンチャンネルごとに新しいパッチクローンを作成しません。 代わりに、1つのパッチクローンがすべてのクローンチャンネル間で共有されます。 これにより、パッチが撤回された場合やパッチ内のパッケージが変更された場合など、ベンダがパッチを変更すると問題が発生する可能性があります。 コンテンツプロジェクトの1つを構築すると、コンテンツプロジェクトの他の環境や組織内の他のコンテンツプロジェクトチャンネルにチャンネルがある場合でも、クローンパッチを共有するすべてのチャンネルがデフォルトでオリジナルと同期されます。 この動作は、組織の設定で自動パッチ同期をオフにすることで変更できます。 パッチを共有しているすべてのチャンネルのパッチを後で手動で同期するには、menu:ソフトウェア[管理 > チャンネル]に移動し、同期するチャンネルをクリックして、［[guimenu]``同期``］サブタブに移動します。 パッチを手動で同期しても、パッチを共有するすべての組織チャンネルに影響します。


.プロシージャ: コンテンツライフサイクルプロジェクトの構築
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[プロジェクト]に移動し、構築するプロジェクトを選択します。

+

[NOTE]
====
プロジェクトを構築する前に、利用可能な環境があることを確認してください。
====

. 割り当てられたソースとフィルタを確認し、btn:[ビルド]をクリックします。

. このビルドの変更または更新を説明するバージョンメッセージを提供します。

. ［ [guimenu]``環境ライフサイクル`` ］セクションでビルドの進行状況を監視できます。

____

ビルドが完了すると、環境バージョンが1つ増え、ソフトウェアチャンネルなどのビルドソースをクライアントに割り当てることができます。



== 環境のプロモート

プロジェクトが構築されると、構築されたソースを順次、環境にプロモートできます。

.プロシージャ: 環境のプロモート
[role=procedure]
____
. {productname} {webui}で、menu:コンテンツライフサイクル[プロジェクト]に移動し、作業するプロジェクトを選択します。

. ［[guimenu]``環境ライフサイクル``］セクションで、後継環境にプロモートする環境を見つけ、btn:[Promote]（プロモート）をクリックします。

. ［ [guimenu]``環境ライフサイクル`` ］セクションでビルドの進行状況を監視できます。

____


== 環境にクライアントを割り当てる

コンテンツライフサイクルプロジェクトを構築およびプロモートすると、{productname}はソフトウェアチャンネルのツリーを作成します。 クライアントを環境に追加するには、クライアントの［[guimenu]``システムの詳細``］ページのmenu:ソフトウェア[ソフトウェアチャンネル]を使用して、ベースソフトウェアチャンネルと子ソフトウェアチャンネルをクライアントに割り当てます。

[NOTE]
====
新たに追加されたクローンチャンネルはクライアントに自動的に割り当てられません。 ソースを追加またはプロモートする場合は、チャンネル割り当てを手動で確認して更新する必要があります。

自動割り当ては、今後のバージョンで{productname}に追加される予定です。
====
