[[custom-channel]]
= カスタムチャンネル
:revdate: 2025-02-28
:page-revdate: {revdate}

カスタムチャンネルを使用すると、クライアントを更新するために使用できる、独自のソフトウェアパッケージとリポジトリを作成できます。 また、環境内でサードパーティベンダが提供するソフトウェアを使用することもできます。

このセクションでは、カスタムチャンネルを作成、管理、および削除する方法について詳細に説明します。 カスタムチャンネルを作成および管理できるようにするには、管理者権限が必要です。


== カスタムチャンネルおよびリポジトリの作成


カスタムチャンネルを作成する前に、関連付けるベースチャンネルと、コンテンツに使用するリポジトリを決定します。

クライアントシステムにインストールする必要があるカスタムソフトウェアパッケージがある場合は、カスタム子チャンネルを作成して管理できます。 システムにチャンネルを割り当てる前に、{productname} {webui}でチャンネルを作成し、パッケージのリポジトリを作成する必要があります。

[IMPORTANT]
====
クライアントシステムと互換性のないパッケージを含む子チャンネルを作成しないでください。
====

ベンダによって提供されたパッケージを使用する場合は、ベースチャンネルとしてベンダチャンネルを選択できます。 または［``なし``］を選択して、カスタムチャンネルをベースチャンネルにします。


.プロシージャ: カスタムチャンネルの作成
[role=procedure]
____
. {productname} {webui}で、menu:ソフトウェア[管理 > チャンネル]に移動して、btn:[チャンネルの作成]をクリックします。

. ［[guimenu]``ソフトウェアチャンネルの作成``］ページで、チャンネルに名前(たとえば、[systemitem]``My Tools SLES 15 SP1 x86_64``)、およびラベル(たとえば、[systemitem]``my-tools-sles15sp1-x86_64``)を付けます。
    ラベルにはスペースまたは大文字を含めないでください。

. ［[guimenu]``親チャンネル``］ドロップダウンで、関連するベースチャンネル(たとえば、[systemitem]``SLE-Product-SLES15-SP1-Pool for x86_64``)を選択します。
    パッケージに互換性のある親チャンネルを選択していることを確認します。

. ［[guimenu]``アーキテクチャ``］ドロップダウンで、適切なハードウェアアーキテクチャ(たとえば、[systemitem]``x86_64``)を選択します。

. ご使用の環境に応じて、連絡先の詳細、チャンネルアクセス制御、およびGPGフィールドに追加情報を入力します。

. btn:[チャンネルの作成]をクリックします。
____

カスタムチャンネルでは、追加のセキュリティ設定が必要になる場合があります。 多くのサードパーティベンダは、GPGを使用してパッケージをセキュリティ保護しています。 カスタムチャンネルでGPGで保護されたパッケージを使用する場合は、メタデータの署名に使用されたGPGキーを信頼する必要があります。 次に、［[guimenu]``メタデータは署名されていますか？``］チェックボックスをオンにして、パッケージメタデータを信頼できるGPGキーと照合します。

リモートチャンネルおよびリポジトリがGPGキーで署名されている場合、これらのGPGキーをインポートして信頼することができます。 たとえば、{productname}サーバのコマンドラインから[command]``spacewalk-repo-sync``を実行します。

----
/usr/bin/spacewalk-repo-sync -c <channellabelname> -t yum
----

このコマンドとプロシージャは、一時的なGPGキーの同期専用です。 キーを永続的に保存するには、後述のこのセクションを参照してください。

基盤となる[command]``zypper``コールは、利用可能な場合はキーをインポートします。 {webui}はこの機能を提供していません。

これは、ミラーするリポジトリが特別な方法で設定されていて、署名の横のリポジトリに「キー」が提供されている場合にのみ機能します 。 これは、Open Build Service (OBS)によって生成されたすべてのリポジトリに該当します。 その他のリポジトリについては、以下で詳述する特別な準備ステップが必要です。


[IMPORTANT]
====
デフォルトでは、新しいチャンネルを作成する際に［``GPGチェックの有効化``］フィールドがオンになっています。 チャンネルにカスタムパッケージとアプリケーションを追加する場合は、このフィールドをオフにして、署名されていないパッケージをインストールできるようにしてください。 パッケージが信頼されていないソースからのものである場合、GPGチェックを無効にするとセキュリティリスクが生じます。
====

リポジトリが有効なソフトウェアリポジトリである場合は、{webui}を使用して{productname}に追加することのみできます。 必要なリポジトリメタデータが使用できることを事前に確認してください。 これに関しては、[command]``createrepo``や[command]``reprepro``などのツールが便利です。 [command]``mgrpush``はリポジトリを作成せずに単一のRPMをチャンネルにプッシュするのに役立ちます。

* [literal]``createrepo_c``の詳細については、[link]``https://manpages.opensuse.org/Leap-15.6/createrepo_c/``を参照してください

* [literal]``reprepro``の詳細については、[link]``https://manpages.opensuse.org/Leap-15.6/reprepro/``を参照してください


.プロシージャ: ソフトウェアリポジトリの追加
[role=procedure]
____
. {productname} {webui}で、menu:ソフトウェア[管理 > リポジトリ]に移動し、btn:[リポジトリの作成]をクリックします。

. ［[guimenu]``リポジトリの作成``］ページで、リポジトリにラベル(たとえば、[systemitem]``my-tools-sles15sp1-x86_64-repo``)を付けます。

. ［[guimenu]``リポジトリURL``］フィールドに、[path]``repodata``ファイル(たとえば、[systemitem]``file:///opt/mytools/``)を含むディレクトリへのパスを指定します。 このフィールドでは、任意の有効なアドレス指定プロトコルを使用できます。

. ［[guimenu]``メタデータは署名されていますか？``］チェックボックスをオフにします。

. オプション: リポジトリでクライアント証明書認証が必要な場合は、SSLフィールドに入力します。

. btn:[リポジトリの作成]をクリックします。
____

先に示したプロシージャは、ミラーリングするリポジトリが署名の横にあるリポジトリに「キー」を提供する場合にのみ機能します。これはOBSによって生成されたすべてのリポジトリに該当しますが、通常、OBSによって提供されていないオペレーティングシステムの他のリポジトリには該当しません。

使用するリポジトリにGPGキーがない場合は、自分でGPGキーを指定し、GPGキーをキーリングに手動でインポートできます。[command]``gpg``コマンドラインツールを使用して[path]``/var/lib/spacewalk/gpgdir``キーリングにキーをインポートすると、永続的に保存されます。chroot環境が消去されても、キーは保持されます。
// Not sure how it is possible to import the key into the RPM DB which is used for syncing.


.プロシージャ: GPGキーを使用してソフトウェアリポジトリを作成する
[role=procedure]
____
. コンテナホストで、キーをキーリングにインポートするコマンドは次のとおりです。

+

[source, shell]
----
mgradm gpg add /path/to/gpg.key
----

. 詳細については、xref:client-configuration:autoinst-owngpgkey.adoc[]を参照してください。
____

[NOTE]
====
``uyuni_suite``、``uyuni_component``、および``uyuni_arch``のクエリパラメータを使用して、Debianの非フラットリポジトリを追加します。
====

``uyuni_suite``::
必須です。 Debianのドキュメントでは、これは[literal]``distribution``とも呼ばれています。 このパラメータでは、aptソースを指定します。 このパラメータを指定しない場合は、元のアプローチが使用されます。 パラメータの末尾が``/``の場合、リポジトリはフラットとして識別されます。

``uyuni_component``::
オプションです。このパラメータは1つのコンポーネントのみを指定できます。コンポーネントを一覧にすることはできません。aptソースエントリでは複数のコンポーネントを指定できますが、Uyuniでは指定できません。代わりに、コンポーネントごとに個別のリポジトリを作成する必要があります。

``uyuni_arch``::
オプションです。 省略すると、データベースからチャンネルのSQLクエリを使用してアーキテクチャ名が計算されます。 チャンネルのアーキテクチャと一致しない場合は、明示的に``uyuni_arch``を指定します(アーキテクチャの命名があいまいな場合があります)。

ここにいくつかの例があります。

[[debian-nonflat-repo]]
[cols="1,1", options="header"]
.Debian非フラットリポジトリマッピング
|===
| タイプ            | ソース行 / URL
| apt ソース行  | ``deb https://pkg.jenkins.io/debian-stable binary/``
| URLマッピング      | ``https://pkg.jenkins.io/debian-stable?uyuni_suite=binary/``
| {nbsp}           |
| aptソース行  | ``deb https://deb.debian.org/debian/dists stable main``
| URLマッピング      | ``https://deb.debian.org/debian/dists?uyuni_suite=stable&uyuni_component=main``
|===


[NOTE]
====
Debianリポジトリ定義フォーマットに関する情報はこちらをご覧ください。この情報は、link:https://wiki.debian.org/DebianRepository/Format#Overview[]に基づいています。

リポジトリ定義フォーマットは次のとおりです。

----
deb uri suite [コンポーネント1] [コンポーネント2] [...]
----

例:

----
deb https://deb.debian.org/debian/dists stable main
----

または

----
deb https://pkg.jenkins.io/debian-stable binary/
----

``スイート``と``コンポーネント``のペアごとに、仕様ではベースURL ``+ suite + component``に基づいて計算される個別のURLを定義しています。
====



.プロシージャ: リポジトリをチャンネルに割り当てる
[role=procedure]
____
. menu:ソフトウェア[管理 > チャンネル]に移動して、新たに作成されたカスタムチャンネルの名前をクリックし、新しいリポジトリをカスタムチャンネルに割り当てます。

. ［[guimenu]``リポジトリ``］タブに移動し、チャンネルに割り当てるリポジトリがオンになっていることを確認し、btn:[リポジトリの保存]をクリックします。

. デフォルトでは、同期プロセスはすぐに開始されます。
____

チャンネルの同期の詳細については、xref:administration:custom-channels.adoc#custom-channel-sync[]を参照してください。



.プロシージャ: アクティベーションキーへのカスタムチャンネルの追加
[role=procedure]
____
. {productname} {webui}で、menu:システム[アクティベーションキー]に移動して、カスタムチャンネルを追加するキーを選択します。

. ［[guiemnu]``詳細``］タブの［[guimenu]``子チャンネル``］リストで、関連付けるチャンネルを選択します。
    必要に応じて、複数のチャンネルを選択できます。

. btn:[アクティベーションキーの更新]をクリックします。
____


[[custom-channel-sync]]
== カスタムチャンネル同期

重要な更新を見逃さないようにするため、{suse}では、カスタムチャンネルをリモートリポジトリの変更に合わせて最新の状態に保つことをお勧めします。

デフォルトでは、作成したすべてのカスタムチャンネルに対して同期が自動的に行われます。特に、次のことが発生します。

* UIから、または[command]``spacewalk-common-channels``を使用して、リポジトリをチャンネルに追加した後
* 毎日のタスク``mgr-sync-refresh-default``の一部として、すべてのカスタムおよびベンダチャンネルを同期します。

このデフォルトの動作を無効にするには、[path]``/etc/rhn/rhn.conf``に以下を設定します。

----
java.unify_custom_channel_management = 0
----

このプロパティをオフにすると、同期は自動的に実行されません。カスタムチャンネルを最新の状態に保つには、次の操作を行う必要があります。

* ［[guimenu]``同期``］ タブに移動し、btn:[今すぐ同期]をクリックして手動で同期し、
* ［[guimenu]``リポジトリ``］タブから自動同期スケジュールを設定します。

プロセス開始時には、チャンネルの同期が終了したかどうかを確認するいくつかの方法があります。

* {productname}の{webui}で、menu:管理[セットアップウィザード]に移動し、［[guimenu]``製品``］タブを選択します。
    このダイアログには、同期中の各製品の完了バーが表示されます。
* {productname}の{webui}で、menu:ソフトウェア[管理 > チャンネル]に移動し、リポジトリに関連付けられているチャンネルをクリックします。
    menu:リポジトリ[同期]タブに移動します。リポジトリ名の横に［[guimenu]``同期状態``］が表示されます。
* コマンドプロンプトで同期ログファイルを確認します。
+
----
tail -f /var/log/rhn/reposync/<channel-label>.log
----
+
同期の進行中に各子チャンネルは独自のログを生成します。 同期が完了したことを確認するには、ベースチャンネルと子チャンネルのログファイルをすべて確認する必要があります。

次のカスタムチャンネル同期オプションが利用できます。

リポジトリから削除されたチャンネル内のパッケージを保持する::
これにより、[literal]``strict``モードがオフになります。
エラータを同期しない::
パッチを同期しません。
最新パッケージのみ同期する::
最新のパッケージバージョンのみを同期します。
キックスタート可能なツリーの作成::
このオプションは、{kickstart}による自動インストール用にディレクトリツリーを準備します。
エラーが発生したら終了する::
エラーが発生した場合、同期を停止します。

これらのオプションはチャンネルごとに永続的に保存されます。btn:[今すぐ同期]ボタンをクリックした場合も、同期を実行する前にチャンネルオプションが保存されます。



== カスタムチャンネルへのパッケージとパッチの追加

既存のチャンネルからクローンを作成せずに新しいカスタムチャンネルを作成する場合、そのチャンネルにはパッケージやパッチは含まれません。 {productname} {webui}を使用して、必要なパッケージとパッチを追加できます。

カスタムチャンネルには、クローンまたはカスタムのパッケージまたはパッチのみを含めることができ、チャンネルの基本アーキテクチャに一致する必要があります。 カスタムチャンネルに追加されたパッチは、チャンネルに存在するパッケージに適用する必要があります。


.プロシージャ: カスタムチャンネルへのパッケージの追加
[role=procedure]
____
. {productname} {webui}で、menu:ソフトウェア[管理 > チャンネル]に移動して、［[guimenu]``パッケージ``］タブに移動します。

. オプション: ［[guimenu]``一覧表示/削除``］タブに移動して、現在チャンネル内にあるすべてのパッケージを表示します。

. ［[guimenu]``追加``］タブに移動して、チャンネルに新しいパッケージを追加します。

. パッケージを提供する親チャンネルを選択し、btn:[パッケージの表示]をクリックして、リストに入力します。

. カスタムチャンネルに追加するパッケージをオンにして、btn:[パッケージの追加]をクリックします。

. 選択に問題がなければ、btn:[追加の確認]をクリックして、チャンネルにパッケージを追加します。

. オプション: menu:ソフトウェア[管理 > チャンネル]に移動し、menu:パッケージ[比較]タブに移動して、現在のチャンネルのパッケージを別のチャンネルのパッケージと比較できます。
    2つのチャンネルを同じにするには、btn:[違いをマージする]ボタンをクリックし、競合を解決します。
____


.プロシージャ: カスタムチャンネルへのパッチの追加
[role=procedure]
____
. {productname} {webui}で、menu:ソフトウェア[管理 > チャンネル]に移動して、［[guimenu]``パッチ``］タブに移動します。

. オプション: ［[guimenu]``一覧表示/削除``］タブに移動して、現在チャンネル内のすべてのパッチを表示します。

. ［ [guimenu]``追加``］タブに移動し、追加するパッチの種類を選択して、チャンネルに新しいパッチを追加します。

. パッチを提供する親チャンネルを選択し、btn:[関連付けられたパッチの表示]をクリックして、リストに入力します。

. カスタムチャンネルに追加するパッチをオンにして、btn:[確認]をクリックします。

. 選択に問題がなければ、btn:[確認]をクリックして、チャンネルにパッチを追加します。
____


== カスタムチャンネルの管理

{productname}管理者とチャンネル管理者は任意のチャンネルを変更または削除できます。

チャンネルを変更または削除する権限を他のユーザに付与するには、menu:ソフトウェア[管理 > チャンネル]に移動して、編集するチャンネルを選択します。 ［ [guimenu]``マネージャ``］タブに移動して、権限を付与するユーザをオンにします。 btn:[更新]をクリックして、変更を保存します。


[IMPORTANT]
====
一連のクライアントに割り当てられているチャンネルを削除すると、削除されたチャンネルに関連付けられているすべてのクライアントのチャンネル状態が直ちに更新されます。 これは、変更がリポジトリファイルに正確に反映されるようにするためです。
====

{webui}を使用して{productname}チャンネルを削除することはできません。 カスタムチャンネルのみを削除できます。


.プロシージャ: カスタムチャンネルの削除
[role=procedure]
____
. {productname} {webui}で、menu:ソフトウェア[管理 > チャンネル]に移動して、削除するチャンネルを選択します。

. btn:[ソフトウェアチャンネルの削除]をクリックします。

. ［[guimenu]``チャンネルの削除``］ページで、削除するチャンネルの詳細を確認し、［[guimenu]``システムのサブスクライブを中止``］チェックボックスをオンにして、まだサブスクライブされている可能性のあるシステムからカスタムチャンネルを削除します。

. btn:[チャンネルの削除]をクリックします。
____

チャンネルを削除しても、削除されたチャンネルの一部であるパッケージは自動的に削除されません。 チャンネルが削除されたパッケージを更新することはできません。

{productname} {webui}で、チャンネルに関連付けられていないパッケージを削除できます。 menu:ソフトウェア[管理 > パッケージ]に移動して、削除するパッケージをオンにして、btn:[パッケージの削除]をクリックします。
