[[security-master-fingerprint]]
= クライアントをマスター検証指紋に設定する
:revdate: 2024-12-12
:page-revdate: {revdate}


高度に安全なネットワーク設定では、{salt}クライアントが特定のマスターに接続していることを確認したい場合があります。クライアントからマスターへの検証を設定するには、{salt} Minionの設定ファイル内にマスターの指紋を入力します。

* クライアントで{salt} Minionを使用している場合、[path]``/etc/salt/minion.d/custom.conf``
* クライアントで{salt} Bundleを使用している場合、[path]``/etc/venv-salt-minion/minion.d/custom.conf``

その後、次のプロシージャに従います。

[IMPORTANT]
====
サーバコンテナ内でシェルにアクセスするには、コンテナホストで[literal]``mgrctl term``を実行します。
====

.プロシージャ: マスターの指紋をクライアントに追加する
. マスターのコマンドプロンプトで、rootとして、次のコマンドを使用して、``master.pub``の指紋を見つけます。
+

----
salt-key -F master
----
+

クライアントで、[path]``/etc/salt/minion.d/custom.conf``または[path]``/etc/venv-salt-minion/minion.d/custom.conf``設定ファイルを開きます。次の行を、指紋の例を置き換えてマスターの指紋に追加します。
+

----
master_finger: 'ba:30:65:2a:d6:9e:20:4f:d8:b2:f3:a7:d4:65:11:13'
----

. サービスを再起動します。salt-minionの場合は、次のコマンドを実行します。
+

----
systemctl restart salt-minion
----
+ 
. または、venv-salt-minionの場合は、次のコマンドを実行します。
+

----
systemctl restart venv-salt-minion
----

{salt} Bundleの詳細については、xref:client-configuration:contact-methods-saltbundle.adoc[]を参照してください。

クライアントからのセキュリティの設定については、link:https://docs.saltproject.io/en/latest/ref/configuration/minion.html[]を参照してください。
