[[organizations]]
= 組織
:revdate: 2022-01-13
:page-revdate: {revdate}


組織は、{productname}内でユーザのアクセスと許可を管理するために使用されます。

ほとんどの環境では、単一の組織で十分です。 ただし、より複雑な環境では、複数の組織が必要な場合があります。 ビジネス内の物理的な場所ごとに、またはさまざまなビジネス機能ごとに組織を設定したい場合があります。

組織を作成したら、ユーザを作成して組織に割り当てることができます。 次に、組織レベルで許可を割り当てることができます 。 この許可は、組織に割り当てられたすべてのユーザにデフォルトで適用されます。

PAMやシングルサインオンなど、新しい組織の認証方法を設定することもできます。 認証の詳細については、xref:administration:auth-methods.adoc[]を参照してください。

[NOTE]
====
組織を作成および管理するには、{productname}管理者としてログインする必要があります。
====



.プロシージャ: 新しい組織の作成
. {productname} {webui}で、menu:管理[組織]に移動して、btn:[組織の作成]をクリックします。
. ［[guimenu]``組織の作成``］ダイアログで、次のフィールドに入力します。
* ［[guimenu]``Organization Name``］（組織名）フィールドに、新しい組織の名前を入力します。
    名前は3～128文字である必要があります。
* ［[guimenu]``希望のログイン``］フィールドに、組織の管理者に使用するログイン名を入力します。
    これは新しい管理者アカウントである必要があります。現在サインインしている組織を含め、既存の管理者アカウントを使用して、新しい組織にサインインすることはできません。
* ［[guimenu]``希望のパスワード``］フィールドに、新しい組織の管理者のパスワードを入力します。
    ［[guimenu]``パスワードの確認``］フィールドにパスワードを再度入力して確認します。 パスワードの強度はパスワードフィールドの下の色付きバーで示されます。
* ［[guimenu]``電子メール`` ］フィールドに、新しい組織の管理者の電子メールアドレスを入力します。
* ［[guimenu]``ファーストネーム(名)``］フィールドで、挨拶文を選択し、新しい組織の管理者の名前を入力します。
* ［[guimenu]``ラストネーム(姓)``］フィールドに、新しい組織の管理者の姓を入力します。
. btn:[組織の作成]をクリックします。



== 組織の管理


{productname} {webui}で、menu:管理[組織]に移動して、利用可能な組織のリストを表示します。 管理する組織の名前をクリックします。

menu:管理[組織]セクションから、組織のユーザ、信頼、設定、および状態を管理するタブにアクセスできます。

[NOTE]
====
組織を管理できるのは管理者のみです。 組織を管理するには、変更する組織の正しい管理者としてサインインしていることを確認してください。
====



=== 組織ユーザ

［[guimenu]``ユーザ``］タブに移動して、組織に関連付けられているすべてのユーザとそのロールのリストを表示します。 ユーザ名をクリックすると、ユーザを追加、変更、または削除する［[guimenu]``ユーザ``］メニューに移動します。



=== 組織の作成

［[guimenu]``信頼``］タブに移動して、信頼されている組織を追加または削除します。 組織間で信頼を確立することにより、それらの組織間でコンテンツを共有し、ある組織から別の組織にクライアントを転送できるようになります。



=== 組織の設定

［[guimenu]``設定``］タブに移動し、組織の設定を管理します。 これには、ステージングされたコンテンツの使用、および SCAPファイルの使用が含まれます。

コンテンツステージングの詳細については、xref:administration:content-staging.adoc[]を参照してください。

OpenSCAPの詳細については、xref:reference:audit/audit-openscap-overview.adoc[]を参照してください。



== 状態の管理


［[guimenu]``状態``］タブに移動して、組織のすべてのクライアントのSalt状態を管理します。 状態を使用すると、グローバルセキュリティポリシーを定義したり、すべてのクライアントに共通の管理ユーザを追加したりできます。

Salt状態の情報については、xref:specialized-guides:salt/salt-states-and-pillars.adoc[]を参照してください。



=== 設定チャンネルの管理

組織全体に適用する設定チャンネルを選択できます。 設定チャンネルは、{productname} {webui}でmenu:設定[チャンネル]に移動して作成できます。 {productname} {webui}を使用して組織に設定チャンネルを適用します。

.プロシージャ: 組織への設定チャンネルの適用
. {productname} {webui}で、menu:ホーム[所属企業/組織 > 設定チャンネル]に移動します。
. 検索機能を使用して、名前でチャンネルを見つけます。
. 適用するチャンネルをオンにし、btn:[変更点の保存]をクリックします。
    これにより、データベースに保存されますが、チャンネルに変更は適用されません。
. btn:[適用]をクリックして変更を適用します。
    これにより、組織内のすべてのクライアントに変更が適用されるようにタスクがスケジュールされます。
