[[patch-management]]
= パッチ管理
:revdate: 2022-02-17
:page-revdate: {revdate}

この章では、パッチ管理に関連するさまざまなトピックについて説明します。


== 撤回されたパッチ


ベンダから新しいパッチがリリースされると、テストで特定されなかったいくつかのシナリオでは、パッチに望ましくない副作用(セキュリティ、安定性)が生じる可能性があります。 これが発生すると(非常にまれ)、ベンダは通常、新しいパッチをリリースします。このパッチには、そのベンダが実施している内部プロセスによっては、数時間または数日かかる場合があります。

SUSEでは、「撤回されたパッチ」と呼ばれる新しいメカニズム(2021年)を導入し、このようなパッチのアドバイザリステータスを(「最終」または「安定」ではなく)「撤回」に設定することで、ほぼ即座にこのようなパッチを取り消します。

[IMPORTANT]
====
アドバイザリステータス属性が「撤回」に設定されている場合、パッチは「撤回」されています。パッケージが「撤回された」パッチに属している場合、そのパッケージは「撤回」されています。
====

撤回されたパッチまたはパッケージは、{productname}のシステムにはインストールできません。 撤回されたパッケージをインストールする唯一の方法は、[literal]``zypper install``を使用して手動で実行し、正確なパッケージバージョンを指定することです。 例:
----
zypper install vim-8.0.1568-5.14.1
----

パッチおよびパッケージの撤回ステータスは、{productname}の{webui}のicon:times-circle[role="red"]アイコンで示されます。たとえば、以下を参照してください。

* チャンネルのパッケージのリスト
* チャンネルのパッチのリスト

システムにインストールされているパッチまたはパッケージが撤回されると、そのシステムのインストール済みパッケージリストにicon:times-circle[role="red"]アイコンも表示されます。{productname}では、このようなパッチまたはパッケージをダウングレードする方法は提供されていません。


=== チャンネルクローン
複製されたチャンネルを使用する場合は、元のチャンネルからクローンへの撤回されたアドバイザリステータスの伝播に注意する必要があります。

ベンダチャンネルを組織に複製すると、チャンネルパッチも複製されます。

ベンダがチャンネル内のパッチを撤回し、{productname}がこのチャンネルを同期する(たとえば、夜間ジョブと同期する)と、「撤回」属性はクローンパッチに伝播されず、クローンチャンネルにサブスクライブされたクライアントによって監視されません。 属性をクローンチャンネルに伝播するには、次のいずれかの方法を使用します。

* パッチ同期(menu:ソフトウェア[管理 > cloned channel （クローンチャンネル） > パッチ > 同期])。この機能を使用すると、クローンチャンネルのパッチの属性をオリジナルに合わせることができます。
* コンテンツライフサイクル管理。コンテンツライフサイクル管理のコンテキストでのクローンチャンネルの詳細については、xref:client-configuration:channels.adoc[]を参照してください。


=== パッチの共有

組織内で複数のベンダチャンネルのクローンを作成する場合、パッチは複数回複製されるのではなく、クローンチャンネル間で共有されます。 その結果、(パッチ同期機能または先述のコンテンツライフサイクル管理を使用して)複製されたパッチを同期すると、複製されたパッチを使用するすべてのチャンネルでその変更が確認されます。

.例:
. 2つのコンテンツライフサイクル管理プロジェクト[literal]``prj1``と[literal]``prj2``を検討します。
. これらのプロジェクトの両方に2つの環境 [literal]``dev``と[literal]``test``があります。
. これらのプロジェクトの両方にソースチャンネルとして設定されたベンダチャンネルがあります。
. このシナリオのすべてのチャンネル(合計4つのクローンチャンネル)は、ベンダチャンネルの最新の状態に合わせて調整されます。
. ベンダがソースチャンネル内のパッチを撤回し、夜間ジョブがそのパッチを{productname}に同期します。
. 4つのチャンネルのいずれも、パッチを直接使用するのではなく、パッチクローンを使用しているため、この変更を認識しません。
. パッチを同期するとすぐに(これら2つのプロジェクトのいずれかを構築するか、または4つのクローンチャンネルのいずれかでパッチ同期機能を使用する)、パッチの共有により、**すべて**のクローンチャンネルがそのパッチを撤回されたものと認識します。
