[[ptfs]]
= {productname}のPTFsの使用
:revdate: 2024-11-29
:page-revdate: {revdate}


SUSEでは、お客様に直接出荷される現在サポートされているすべてのソリューションに対して一時的な修正を提供しています。 これらのPTFs (プログラムの一時的な修正)は、{productname}で同期できるリポジトリとして利用できるようになりました。


== PTFパッケージについて


PTFパッケージはプロキシパッケージを介してインストールされ、``ptf-xxxxxx``という名前が付けられます。ここで、xxxxxxはパッケージのバージョンではなく、パッケージの番号と名前の一部です。

これらは、ソフトウェアに修正が含まれていることがわかっている正しいバージョンのパッケージに依存します。このタイプのパッケージは次のとおりです。

* 誤ってインストールすることはできません(つまり、zypper更新はインストールを推奨しません)。
* 誤って削除することはできません(つまり、ユーザがzypperコマンドラインで明示的に指定しない限り、新しいパッケージバージョンはPTFバージョンに置き換わりません)。
* PTFによって以前に解決された特定の問題に新しいバージョンが対処することがわかっている場合にのみ更新されます。
* システムにすでにインストールされているパッケージのみを更新します(つまり、ソフトウェアが複数のパッケージに分割されている場合、PTFは現在システムにインストールされているパッケージのみを置き換えます)。

サポートケース調査の過程で、パッケージの正しいIDと、影響を受けるサービスの配備/再起動方法についての指示がSUSEサポートによって提供されます。


== PTFパッケージのインストール

[NOTE]
====
PTFパッケージは現在、SLE 12およびSLE 15ベースのシステムでのみサポートされています。他のバージョンまたはオペレーティングシステムにはこの機能がないため、ページは表示されません。
====

[IMPORTANT]
====
{productname}を介してPTFチャンネルにアクセスするには、L3サポートから要求する必要があります。
====

.プロシージャ: コマンドラインを使用してPTFリポジトリを有効にし、同期する

. コンソールで、[command]``mgr-sync refresh``と入力します。
. 「[command]``mgr-sync list channel``」と入力し、{scc}アカウント名とその名前の``ptfs``で始まるチャンネルを探します。 例: `a123456-sles-15.3-ptfs-x86_64`。
. [command]``mgr-sync add channel <label>``を使用してPTFチャンネルを有効にします。

このチャンネルは現在使用可能になり、同じベースチャンネルを使用しているすべてのシステムに追加できます。

PTFパッケージは、システムの更新時に自動的には選択されないため、明示的にインストールする必要があります。SUSEカスタマーサポートは、特定の問題を修正するためのPTF番号を提供しています。この番号を使用して、PTFリストでプロキシパッケージを特定できます。{productname}の{webui}には、インストールできるPTFが提供されているすべてのシステム用に、PTFを一覧にしたページがあります。


.プロシージャ: {productname}の{webui}を使用したPTFリポジトリの有効化および同期

. {productname}の{webui}で、menu:管理[セットアップウィザード > 製品]に移動し、PTFリポジトリを有効にする製品を探します。
. 製品同期ステータスの横にあるbtn:[製品チャンネルの表示]をクリックします。
. 製品の必須チャンネルとオプションチャンネルを一覧表示したポップアップが表示されます。
. オプションのチャンネルリストで、自分の{scc}アカウント名と``ptfs``で名前が始まるチャンネルを探します。 例: `a123456-sles-15.3-ptfs-x86_64`。
. チャンネル名の横にあるチェックボックスを使用してチャンネルを選択し、btn:[確認]をクリックして同期をスケジュールします。

オプションチャンネルを追加できるようにするには、製品をインストールする必要があることに注意してください。


.プロシージャ: PTFパッケージのインストール

. {productname} {webui}で、menu:システム[システム一覧]に移動して、PTFをインストールするクライアントを選択します。
. menu:システム[ソフトウェア > パッケージ > ソフトウェアチャンネル]に移動し、[systemitem]``PTF channel``（PTFチャンネル）を選択します。
. btn:[次へ]、［[guimenu]``ソフトウェアチャンネルの変更確認``］、btn:[確認]をクリックします。
. チャンネルの割り当てが完了しているかどうかを確認するには、menu:システム[Events > History (イベント > 履歴)]に移動して結果を確認します。
. menu:システム[ソフトウェア > PTFs > インストール]サブタブに移動します。
. インストールするPTFパッケージを選択します。
. btn:[PTFのインストール]、［[guimenu]``Program Temporary Fixes (PTFs)インストールの確認``］、btn:[確認]をクリックします。
. PTFのインストール結果を確認するには、menu:システム[Events > History (イベント > 履歴)]に移動します。


APIを使用してPTFをインストールする必要がある場合は、プロキシパッケージ名とともに通常の[systemitem]``system.schedulePackageInstall`` APIを使用できます。


== PTFのインストール後

PTFを確認して報告された問題に対処すると、更新されたパッケージは、通常のメンテナンス更新として更新リポジトリで広く配布される前に、今後のメンテナンス更新に含める対象として追跡されます。

この修正を含む定期的な更新がリリースされると、PTFの更新バージョンもアカウント固有のPTFリポジトリにリリースされます。 更新されたPTFにより厳密な依存関係が削除され、更新を再度インストールできるようになります。

PTFの修正を含む保守更新の置き換えは、標準のパッケージ更新またはパッチのインストールによって自動的に行われます。



== パッチ適用済みバージョンのパッケージの削除

PTFをアンインストールする必要があり、パッチが適用されていないバージョンのパッケージをシステムにインストールする必要がある場合、単純なパッケージ削除は使用できません。 PTFパッケージは、標準パッケージリストページでは選択できません。


.プロシージャ: PTFパッケージの削除

. {productname} {webui}で、menu:システム[システム一覧]に移動して、PTFを削除するクライアントを選択します。
. menu:システム[ソフトウェア > PTFs > 一覧表示/削除]サブタブに移動します。
. 削除するPTFパッケージを選択します。
. btn:[PTFsの削除]をクリックし、［[guimenu]``Program Temporary Fixes (PTFs)削除の確認``］ページで、btn:[確認]をクリックします。
. 結果を確認するには、menu:システム[イベント > 履歴]に移動します。


[NOTE]
====
PTFを削除するには、特別なバージョンの[literal]``libzypp``と[literal]``zypper``をクライアントシステムにインストールする必要があります。[command]``removeptf``がサポートされているかどうかを確認するには、[command]``zypper --help``を確認します。［``List/Remove (リスト/削除)``］タブは、この条件を満たしている場合にのみ表示されます。
====

APIを使用してPTFを削除する必要がある場合は、プロキシパッケージ名とともに通常の[systemitem]``system.schedulePackageRemove`` APIを使用できます。


== クライアント上のパッチ適用済みバージョンのパッケージを削除する

コンソールを使用してPTFをクライアント上で直接削除する必要がある場合、特別なコマンド``zypper removeptf``を使用する必要があります。他の方法はすべて、エラーになるか、重要なパッケージがシステムから削除されてシステムが使用不能になるなどの望まない動作を招く可能性があります。
