[[ssl-certs-hsts]]
= HTTP Strict Transport Security
:revdate: 2024-07-31
:page-revdate: {revdate}

HTTP Strict Transport Security (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security[HSTS])は、プロトコルダウングレード攻撃やクッキーハイジャックなどの中間者攻撃からWebサイトを保護するのに役立つポリシーメカニズムです。

{productname}では、HSTSはデフォルトで有効になっています。 サーバ上で無効にする必要がある場合は、次のプロシージャに従います。



.プロシージャ: サーバでHSTSを無効にする
[role=procedure]
_____
. サーバコンテナホストで、 rootとして次のコマンドを実行し、設定[literal]``max-age=0``を含む新しい設定ファイルを作成します。

+

[source, shell]
----
mgrctl exec -- \
  echo 'Header always set Strict-Transport-Security "max-age=0; includeSubDomains"' \
  > /etc/apache2/conf.d/zz-spacewalk-www-hsts.conf
----

. 次のコマンドでApacheを再起動します。

+

[source, shell]
----
mgrctl exec -- systemctl restart apache2
----

_____

プロキシ上で無効にする必要がある場合は、次のプロシージャに従います。

.プロシージャ: プロキシでHSTSを無効にする
[role=procedure]
_____
. サーバコンテナホストで、 rootとして次のコマンドを実行し、設定[literal]``max-age=0``を含む新しい設定ファイルを作成します。

+

[source, shell]
----
echo 'Header always set Strict-Transport-Security "max-age=0; includeSubDomains' \
  > /etc/uyuni/custom-httpd.conf
----

. 次のコマンドを実行します。

+

[source, shell]
----
mgrpxy install podman --tuning-httpd /etc/uyuni/custom-httpd.conf config.tar.gz
----

_____


[WARNING]
====
新しい設定ファイルに[literal]``<filename>.conf``という名前を付ける場合は、適切なタイミングでロードされるようにしてください。 たとえば、[literal]``spacewalk-www.conf``で定義されたものを上書きするには、新しいファイルがアルファベット順でこのファイルの後にある必要があります。 Apacheがファイルをロードする方法の詳細については、``https://httpd.apache.org/docs``を参照してください。
====


[IMPORTANT]
====
{productname}で生成されたデフォルトのSSL証明書または自己署名証明書を使用してHSTSを有効にすると、このような証明書に署名するために使用されたCAがブラウザによって信頼されていない限り、ブラウザはHTTPSでの接続を拒否します。 {productname}で生成されたSSL証明書を使用している場合は、``http://<SERVER-HOSTNAME>/pub/RHN-ORG-TRUSTED-SSL-CERT``にあるファイルをすべてのユーザのブラウザにインポートすることでこの証明書を信頼することができます。
====
