[[subscription-matching]]
= サブスクリプションマッチング
:revdate: 2024-11-29
:page-revdate: {revdate}

{suse}製品には{scclongform} ({scc})によって管理されるサブスクリプションが必要です。 {productname}は、{scc}アカウントに対して登録済みの全クライアントのサブスクリプションステータスをチェックする夜間レポートを実行します。 このレポートには、どのクライアントがどのサブスクリプションを使用しているか、残りのサブスクリプション数と使用できるサブスクリプション数、および現在のサブスクリプションがないクライアントに関する情報が表示されます。

menu:監査[サブスクリプションマッチング]に移動して、レポートを表示します。

［[guimenu]``Subscriptions Report``］（サブスクリプションレポート）タブには、現在のサブスクリプションと期限切れサブスクリプションに関する情報が表示されます。

［[guimenu]``Unmatched Products Report``］（一致しない製品レポート）タブには、現在のサブスクリプションがないクライアントのリストが表示されます。 これには、一致できなかったクライアント、{productname}に現在登録されていないクライアントが含まれます。 このレポートには、製品名とまだ一致していないシステムの数が含まれます。

［[guimenu]``ピン``］タブでは、関連するサブスクリプションに個々のクライアントを関連付けることができます。 これは、サブスクリプションマネージャがクライアントをサブスクリプションに自動的に正常に関連付けない場合に特に役立ちます。

［[guimenu]``メッセージ``］タブには、マッチングプロセス中にサブスクリプションマッチャーによって生成されたすべてのメッセージが表示されます。 これらは、結果を理解し、マッチングを改善するのに役立つ情報を提供します。

レポートは.csv形式でダウンロードすることも、コマンドプロンプトから[path]``/var/lib/spacewalk/subscription-matcher/``ディレクトリでアクセスすることもできます。

デフォルトでは、サブスクリプションマッチャーは毎日午前0時に実行されます。 これを変更するには、menu:管理[タスクスケジュール]に移動し、［``gatherer-matcher-default``］をクリックします。 必要に応じてスケジュールを変更し、btn:[スケジュールの更新]をクリックします。

レポートは現在のクライアントと現在のサブスクリプションしか一致させることができないため、一致が時間の経過とともに変化することがあります。 同じクライアントが常に同じサブスクリプションと一致するわけではありません。 これは、新規クライアントの登録または登録解除、もしくはサブスクリプションの追加または期限切れが原因である可能性があります。

サブスクリプションマッチャーは、アカウント内のサブスクリプションの条項によって制限される、不一致の製品数を自動的に減らそうとします。 ただし、不完全なハードウェア情報、不明な仮想マシンホストの割り当て、または不明なパブリッククラウドで実行されているクライアントがある場合は、利用可能なサブスクリプションが十分でないことがマッチャーに表示されることがあります。 正確性を確保するために、常に{productname}に含まれるクライアントに関する完全なデータがあることを確認してください。


[IMPORTANT]
====
サブスクリプションマッチャーは、常にクライアントとサブスクリプションを正確に一致させるとは限りません。 これは監査に代わるものではありません。
====



== クライアントをサブスクリプションにピン設定する



サブスクリプションマッチャーが特定のクライアントと正しいサブスクリプションを自動的に一致させない場合は、それらを手動でピン設定することができます。 ピンを作成すると、サブスクリプションマッチャーは特定のサブスクリプションを特定のシステムまたはシステムのグループと一致させることを優先します。

ただし、マッチャーは常にピンを尊重するわけではありません。 これは、利用可能なサブスクリプション、およびサブスクリプションをクライアントに適用できるかどうかによって異なります。 さらに、サブスクリプションの条項に違反する一致が発生した場合、またはピンが無視された場合にマッチャーがより正確な一致を検出した場合、ピンは無視されます。

新しいピンを追加するには、btn:[ピンの追加]をクリックし、ピンを設定するクライアントを選択します。

[IMPORTANT]
====
定期的に、または多数のクライアントにピンの設定を使用することはお勧めしません。 Subscription Matcherツールは、一般的にほとんどのインストールに十分な精度があります。
====
