[[ref-spacecmd-errata]]
= errata_

The following spacecmd commands are available for use with errata data.



== errata_apply

Apply an patch to all affected systems.

[source]
--
usage: errata_apply ERRATA|search:XXX ...
--



== errata_delete

Delete an patch.

[source]
--
使用方法: errata_delete エラータ|search:XXX ...
--



== errata_details

Show the details of an patch.

[source]
--
使用方法: errata_details エラータ|search:XXX ...
--



== errata_findbycve

List errata addressing a CVE.

[source]
--
使用方法: errata_findbycve CVE-YYYY-NNNN ...
--



== errata_list

List all patches.

[source]
--
使用方法: errata_list
--



== errata_listaffectedsystems

List of systems affected by an patch.

[source]
--
使用方法: errata_listaffectedsystems エラータ|search:XXX ...
--



== errata_listcves

List of CVEs addressed by an patch.

[source]
--
使用方法: errata_listcves エラータ|search:XXX ...
--



== errata_publish

Publish a patch to a channel.

[source]
--
使用方法: errata_publish エラータ|search:XXX <チャンネル ...>
--



== errata_search

List patches that meet user provided criteria

[source]
--
例: errata_search CVE|RHSA|RHBA|RHEA|CLA ...

例:
> errata_search CVE-2009:1674
> errata_search RHSA-2009:1674
--



== errata_summary

Print a summary of all errata.

[source]
--
使用方法: errata_summary
--
