[[ref-spacecmd-kickstart]]
= kickstart_

The following spacecmd functions are available for use with kickstart.

== kickstart_addactivationkeys

Add activation keys to a Kickstart profile.

[source]
--
使用方法: kickstart_addactivationkeys プロファイル <キー ...>
--



== kickstart_addchildchannels

Add a child channels to a Kickstart profile.

[source]
--
使用方法: kickstart_addchildchannels プロファイル <チャンネル ...>
--



== kickstart_addcryptokeys

Add cryptography keys to a Kickstart profile.

[source]
--
使用方法: kickstart_addcryptokeys プロファイル <鍵 ...>
--



== kickstart_addfilepreservations

Add file preservations to a Kickstart profile.

[source]
--
使用方法: kickstart_addfilepreservations プロファイル <ファイルリスト ...>
--



== kickstart_addoption

Set an option for a Kickstart profile.

[source]
--
使用方法: kickstart_addoption プロファイル キー [値]
--



== kickstart_addpackages

Add packages to a Kickstart profile.

[source]
--
使用方法: kickstart_addpackages プロファイル <パッケージ ...>
--



== kickstart_addscript

Add a script to a Kickstart profile.

[source]
--
usage: kickstart_addscript PROFILE [options]

options:
  -p PROFILE
  -e EXECUTION_TIME ['pre', 'post']
  -i INTERPRETER
  -f FILE
  -c execute in a chroot environment
  -t ENABLING_TEMPLATING
--



== kickstart_addvariable

Add a variable to a Kickstart profile.

[source]
--
使用方法: kickstart_addvariable プロファイル キー 値
--


== kickstart_clone

Clone a Kickstart profile.

[source]
--
usage: kickstart_clone [options]

options:
  -n NAME
  -c CLONE_NAME
--



== kickstart_create

Create a Kickstart profile.

[source]
--
usage: kickstart_create [options]

options:
  -n NAME
  -d DISTRIBUTION
  -p ROOT_PASSWORD
  -v VIRT_TYPE ['none', 'para_host', 'qemu', 'xenfv', 'xenpv']
--



== kickstart_delete

Delete kickstart profiles.

[source]
--
usage: kickstart_delete PROFILE usage: kickstart_delete PROFILE1 PROFILE2 usage: kickstart_delete "PROF*"
--



== kickstart_details

Show the details of a Kickstart profile.

[source]
--
使用方法: kickstart_details プロファイル
--



== kickstart_diff

List differences between two kickstart files.

[source]
--
使用方法: kickstart_diff 比較元チャンネル 比較先チャンネル
--



== kickstart_disableconfigmanagement

Disable configuration management on a Kickstart profile.

[source]
--
使用方法: kickstart_disableconfigmanagement プロファイル
--



== kickstart_disableremotecommands

Disable remote commands on a Kickstart profile.

[source]
--
使用方法: kickstart_disableremotecommands プロファイル
--



== kickstart_enableconfigmanagement

Enable configuration management on a Kickstart profile.

[source]
--
使用方法: kickstart_enableconfigmanagement プロファイル
--



== kickstart_enablelogging

Enable logging for a Kickstart profile.

[source]
--
使用方法: kickstart_enablelogging プロファイル
--



== kickstart_enableremotecommands
Enable remote commands on a Kickstart profile.

[source]
--
使用方法: kickstart_enableremotecommands プロファイル
--



== kickstart_export

Export kickstart profiles to json formatted file.

[source]
--
usage: kickstart_export <KSPROFILE>... [options]
options:
    -f outfile.json : specify an output filename, defaults to <KSPROFILE>.json
                      if exporting a single kickstart, profiles.json for multiple
                      kickstarts, or ks_all.json if no KSPROFILE specified
                      e.g (export ALL)

Note : KSPROFILE list is optional, default is to export ALL
--



== kickstart_getcontents

Show the contents of a Kickstart profile as they would be presented to a client.

[source]
--
使用方法: kickstart_getcontents ラベル
--



== kickstart_getsoftwaredetails

Gets kickstart profile software details.

[source]
--
usage: kickstart_getsoftwaredetails KS_LABEL usage: kickstart_getsoftwaredetails KS_LABEL KS_LABEL2 ...
--



== kickstart_getupdatetype

Get the update type for a kickstart profiles.

[source]
--
usage: kickstart_getupdatetype PROFILE usage: kickstart_getupdatetype PROFILE1 PROFILE2 usage: kickstart_getupdatetype "PROF*"
--



== kickstart_import

Import a Kickstart profile from a file.

[source]
--
usage: kickstart_import [options]

options:
  -f FILE
  -n NAME
  -d DISTRIBUTION
  -v VIRT_TYPE ['none', 'para_host', 'qemu', 'xenfv', 'xenpv']
--



== kickstart_import_raw

Import a raw Kickstart or autoyast profile from a file.

[source]
--
usage: kickstart_import_raw [options]

options:
  -f FILE
  -n NAME
  -d DISTRIBUTION
  -v VIRT_TYPE ['none', 'para_host', 'qemu', 'xenfv', 'xenpv']
--



== kickstart_importjson

Import kickstart profiles from json file.

[source]
--
使用方法: kickstart_import <JSON_ファイル...>
--



== kickstart_list

List the available Kickstart profiles.

[source]
--
使用方法: kickstart_list
--



== kickstart_listactivationkeys

List the activation keys associated with a Kickstart profile.

[source]
--
使用方法: kickstart_listactivationkeys プロファイル
--



== kickstart_listchildchannels

List the child channels of a Kickstart profile.

[source]
--
使用方法: kickstart_listchildchannels プロファイル
--



== kickstart_listcryptokeys

List the crypto keys associated with a Kickstart profile.

[source]
--
使用方法: kickstart_listcryptokeys プロファイル
--



== kickstart_listcustomoptions

List the custom options of a Kickstart profile.

[source]
--
使用方法: kickstart_listcustomoptions プロファイル
--



== kickstart_listoptions

List the options of a Kickstart profile.

[source]
--
使用方法: kickstart_listoptions プロファイル
--



== kickstart_listpackages

List the packages for a Kickstart profile.

[source]
--
使用方法: kickstart_listpackages プロファイル
--



== kickstart_listscripts

List the scripts for a Kickstart profile.

[source]
--
使用方法: kickstart_listscripts プロファイル
--



== kickstart_listvariables

List the variables of a Kickstart profile.

[source]
--
使用方法: kickstart_listvariables プロファイル
--



== kickstart_removeactivationkeys

Remove activation keys from a Kickstart profile.

[source]
--
使用方法: kickstart_removeactivationkeys プロファイル <キー ...>
--



== kickstart_removechildchannels

Remove child channels from a Kickstart profile.

[source]
--
使用方法: kickstart_removechildchannels プロファイル <チャンネル ...>
--



== kickstart_removecryptokeys

Remove crypto keys from a Kickstart profile.

[source]
--
使用方法: kickstart_removecryptokeys プロファイル <鍵 ...>
--



== kickstart_removefilepreservations

Remove file preservations from a Kickstart profile.

[source]
--
使用方法: kickstart_removefilepreservations プロファイル <ファイル ...>
--



== kickstart_removeoptions

Remove options from a Kickstart profile.

[source]
--
使用方法: kickstart_removeoptions プロファイル <オプション ...>
--



== kickstart_removepackages

Remove packages from a Kickstart profile.

[source]
--
使用方法: kickstart_removepackages プロファイル <パッケージ ...>
--



== kickstart_removescript

Add a script to a Kickstart profile.

[source]
--
使用方法: kickstart_removescript プロファイル [ID]
--



== kickstart_removevariables

Remove variables from a Kickstart profile.

[source]
--
使用方法: kickstart_removevariables プロファイル <キー ...>
--



== kickstart_rename

Rename a Kickstart profile

[source]
--
使用方法: kickstart_rename 変更前の名前 変更後の名前
--



== kickstart_setcustomoptions

Set custom options for a Kickstart profile.

[source]
--
使用方法: kickstart_setcustomoptions プロファイル
--



== kickstart_setdistribution

Set the distribution for a Kickstart profile.

[source]
--
使用方法: kickstart_setdistribution プロファイル ディストリビューション
--



== kickstart_setlocale

Set the locale for a Kickstart profile.

[source]
--
使用方法: kickstart_setlocale プロファイル ロケール
--



== kickstart_setpartitions

Set the partitioning scheme for a Kickstart profile.

[source]
--
使用方法: kickstart_setpartitions プロファイル
--



== kickstart_setselinux

Set the SELinux mode for a Kickstart profile.

[source]
--
使用方法: kickstart_setselinux プロファイル モード
--



== kickstartsetupdatetype

Set the update type for a kickstart profiles.

[source]
--
usage: kickstartsetupdatetype [options] KS_LABEL

options:
    -u UPDATE_TYPE ['red_hat', 'all', 'none']
--



== kickstart_updatevariable

Update a variable in a Kickstart profile.

[source]
--
使用方法: kickstart_updatevariable プロファイル キー 値
--
