= レガシプロキシからコンテナへの移行
:description: SUSE Multi-Linux Managerのコンテナ化されたプロキシを、SUSE Multi-Linux Manager 5.1の新しいコンテナ化されたプロキシに移行してください。
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

コンテナ化されたプロキシは、現在一連のsystemdサービスによって管理されています。
コンテナ化されたプロキシを管理するには、`mgrpxy`ツールを使用してください。

このセクションでは、`mgrpxy`ツールを使用して従来の`systemd`プロキシから移行する方法を説明します。

[IMPORTANT]
====
{productname}の以前のリリースから{productnumber}へのインプレース移行は、HostOSが{leap}から{leapmicro}に変更されたため、サポートされません。

従来のコンタクトプロトコルは、{productname} {productnumber}以降ではサポートされなくなりました。
以前の{productname}リリースから{productnumber}に移行する前に、従来のプロキシを含む既存の従来のクライアントを{salt}に移行する必要があります。
====



== Systemdを使用したレガシプロキシからコンテナ化されたプロキシへの移行


=== プロキシ設定の生成

.プロシージャ:プロキシ設定の生成
. {productname}サーバー{webui}にログインします。
. 左側のナビゲーションからmenu:システム[プロキシの設定]を選択します。
. プロキシのFQDNを入力してください。元のプロキシホストと同じFQDNを使用してください。
. サーバのFQDNを入力します。
. プロキシのポート番号を入力してください。__デフォルトのポート8022の使用をお勧めします。__
. 証明書と秘密鍵は、`/var/lib/containers/storage/volumes/root/_data/ssl-build/`のサーバーコンテナホストにあります。
  * RHN-ORG-TRUSTED-SSL-CERT
  * RHN-ORG-PRIVATE-SSL-KEY
. 次のコマンドを使用して証明書と鍵をマシンにコピーします。
+

----
scp root@uyuni-server-example.com:/root/ssl-build/RHN-ORG-PRIVATE-SSL-KEY .
scp root@uyuni-server-example.com:/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT .
----

. btn:[ファイルを選択]を選択し、ローカルマシンを参照して証明書を選択します。
. btn:[ファイルを選択]を選択し、ローカルマシンを参照して秘密鍵を選択します。
. CAのパスワードを入力します。
. btn:[生成]をクリックします。


=== 新しいホストへのプロキシ設定の転送

.プロシージャ:プロキシ設定の転送
. サーバから、プロキシ設定が含まれる、生成されたtar.gzファイルを新しいプロキシホストに転送します。
+
----
scp config.tar.gz <uyuni-proxy-FQDN>:/root/
----

. 次のステップを実行する前に、レガシプロキシを無効にします。
+
----
spacewalk-proxy stop
----
. 次のコマンドを使用して新しいプロキシを配備します。
+ 
----
systemctl start uyuni-proxy-pod
----
. 次のコマンドを使用して新しいプロキシを有効にします。
+ 
----
systemctl enable --now uyuni-proxy-pod
----
. `podman ps`を実行して、すべてのコンテナが存在していて実行されていることを確認します:
+
----
proxy-salt-broker
proxy-httpd
proxy-tftpd
proxy-squid
proxy-ssh
----



== {productname}プロキシを{productname} {productnumber}コンテナ化されたプロキシに移行します。

.プロシージャ:{productname}コンテナ化されたプロキシを{productname} {productnumber}新しいコンテナ化されたプロキシに移行します。
. 新しいマシンを起動し、{leapmicro} {microversion}のインストールを開始します。
. インストールを完了します。
. システムを更新します。
+
----
transactional-update --continue
----
. `mgrpxy`をインストールします。オプションで`mgrpxy-bash-completion`もインストールできます。
+
----
transactional-update pkg install mgrpxy mgrpxy-bash-completion 
----
+
. 再起動します。

. `tar.gz`プロキシ設定をホストにコピーします。



== {webui}を使用したパッケージのインストール

`mgrpxy`パッケージおよび`mgrpxy-bash-completion`パッケージは、Minionが起動されてサーバに登録された後にWeb UI経由でインストールすることもできます。

.プロシージャ:{webui}を使用したパッケージのインストール
. インストール後、{sle-micro}{microversion}親チャンネルとプロキシの子チャンネルが、menu:管理[セットアップウィザード -> 製品]ページから追加および同期されていることを確認します。
. {webui}で、menu:システム[アクティベーションキー]に移動し、同期された{sle-micro} {microversion}チャンネルにリンクされたアクティベーションキーを作成します。
. menu:システム[ブートストラップ]ページを使用して、システムをMinionとしてブートストラップします。
. 新しいマシンがオンボーディングされてシステムリストに表示されたら、システムを選択して、menu:システムの詳細[パッケージのインストール]ページに移動します。
. `mgrpxy`パッケージと`mgrpxy-bash-completion`パッケージをインストールします。
. システムを再起動します。


== `spacecmd`と自己署名証明書を使用したプロキシ設定の生成

spacecmdを使用してプロキシ設定を生成できます。

.プロシージャ:`spacecmd`と自己署名証明書を使用したプロキシ設定の生成
. SSHでコンテナホストに接続します。
. 次のコマンドを実行してサーバとプロキシFQDNを置き換えます。
+
----
mgrctl exec -ti 'spacecmd proxy_container_config_generate_cert -- dev-pxy.example.com dev-srv.example.com 2048 email@example.com -o /tmp/config.tar.gz'
----
. 生成された設定をプロキシにコピーします。
+
----
mgrctl cp server:/tmp/config.tar.gz .
----
. 次のコマンドを使用してプロキシを配備します。
+ 
----
mgrpxy install podman config.tar.gz
----


== `spacecmd`とカスタム証明書を使用したプロキシ設定の生成

デフォルトの自己署名証明書ではなく`spacecmd`カスタム証明書に対してを使用して、プロキシ設定を生成できます。

[NOTE]
====
2 GBはデフォルトのプロキシキャッシュサイズ（Squid）を表します。
これはあなたの環境に合わせて調整する必要があります。
====

.プロシージャ:`spacecmd`とカスタム証明書を使用したプロキシ設定の生成
. サーバコンテナホストにSSHで接続します。
. 次のコマンドを実行してサーバとプロキシFQDNを置き換えます。
+
----
for f in ca.crt proxy.crt proxy.key; do
  mgrctl cp $f server:/tmp/$f
done
mgrctl exec -ti 'spacecmd proxy_container_config -- -p 8022 pxy.example.com srv.example.com 2048 email@example.com /tmp/ca.crt /tmp/proxy.crt /tmp/proxy.key -o /tmp/config.tar.gz'
----
. 生成された設定をプロキシにコピーします。
+
----
mgrctl cp server:/tmp/config.tar.gz .
----
. 次のコマンドを使用してプロキシを配備します。
+ 
----
mgrpxy install podman config.tar.gz
----
