[[connect.payg.instances]]
= Connect {payg} instance

In the three major public cloud providers (AWS, GCP and Azure), SUSE:

* provides customized {payg} product images for SLES, SLES for SAP, etc.
* operates per-region RMT Servers mirroring repositories for products available as {payg}

This document describes how to connect existing {payg} instance to {productname} server, and gives basic information about credentials collection from the instance.
The goal of the connection is to extract authentication data so {productname} server is able to connect to cloud RMT host.

Before using {payg} feature make sure that: 

* {productname} server is deployed in the same region as the {payg} instance
* valid {scc} credentials are entered in menu:Admin[Setup Wizard > Organization Credentials], even they provide only limited access to products


== Connecting {payg} instance

[[proc-connecting-new-payg]]
.Procedure: Connecting new {payg}  instance
[role=procedure]
. In the {productname} {webui}, navigate  to menu:Admin[Setup Wizard > {payg}], and click btn:[Add {payg}].
. In the menu:Add new {payg} data[Description], add the description.
. In the menu:Add new {payg} data[Hostname], enter the instance DNS or IP address to connect from {productname}.
. In the menu:Add new {payg} data[Port], enter 22.
. In the menu:Add new {payg} data[Username], add the actual username as specified in the cloud.
. In the menu:Add new {payg} data[Password], enter the password.
. In the menu:Add new {payg} data[Key], add the correct instance key.
. In the menu:Add new {payg} data[Key Password], add key passphrase.
. Click btn:[Create] to add new {payg} connection data.

[IMPORTANT]
====
Authentication keys must always be in PEM format.
====

If you are not connecting directly to the cloud, but via SSH bastion, proceed with <<proc-adding-ssh-bastion-connection-data>>.

Otherwise, continue with <<proc-finishing-payg-connecting>>.

[[proc-adding-ssh-bastion-connection-data]]
.Procedure: Adding SSH bastion connection data
[role=procedure]
. In the menu:Add new {payg} data[Bastion Hostame], add the bastion hostname.
. In the menu:Add new {payg} data[Bastion Port], add the bastion port number.
. In the menu:Add new {payg} data[Bastion Username], add bastion the username.
. In the menu:Add new {payg} data[Bastion Password], add bastion password.
. In the menu:Add new {payg} data[Bastion Key], add bastion key.
. In the menu:Add new {payg} data[Bastion Key Password], add bastion key password.

Complete the setup process with with <<proc-finishing-payg-connecting>>.

[[proc-finishing-payg-connecting]]
.Procedure: Finishing {payg} connecting
[role=procedure]
. To complete adding new {payg} connection data, click btn:[Create].
. You will return to [guimenu]``Admin > Setup Wizard > Pay-as-you-go`` screen.
. If the authentication data for the instance are correct, the column Status will soon show "Credentials successfully updated".

[IMPORTANT]
====
If the invalid data are entered at any point, the newly created instance will be shown in [guimenu]``Admin > Setup Wizard > {payg}``, with column Status displaying error message.
====


As soon as the authentication data is available on the server, a list of available products is updated.

Available products are all versions of the same product family and architecture as the one installed in the {payg} instance. 
For example, if the instance has the {slsa}{nbsp}15 SP1 product installed, {slsa}{nbsp}15 SP2 and {slsa}{nbsp}15 SP3 will be automatically added and shown in [guimenu]``Admin > Setup Wizard > Products``. 

Once the products are shown as available, the user can add a product to {productname} by selecting the checkbox next to the product name and clicking btn:[Add product].

To monitor the progress of channel syncing in the {webui}, navigate to [guimenu]``Software > Channel List > All``. 

To monitor the syncing progress of each channel, check the log files in the [path]``/var/log/rhn/reposync`` directory on the {productname} server.


=== Deleting the instance

The following procedure describes how to delete SSH connection data to the instance.

[[proc-deleting-connection-data-to-instance]]
.Procedure: Deleting conenction data to instance
[role=procedure]
. Go to [guimenu]``Admin > Setup Wizard > {payg}``
. Find the instance on the list of existing instances
. Click on the instance details
. Select btn:[Delete] and confirm your selection
. You will be returned to the list of instances and the one that was just deleted will no longer be shown



== Instance credential collect status

{productname} server uses instance credentails to connect to the RMT server and to download the packages using reposync.
These credentials are refreshed every 10 minutes by taskomatic using the defined SSH connection data. Connection to RMT server always uses the last known authentication credentials collected from the {payg} instance.

Up-to date status of the {payg} instance is shown in the column Status or on the instance details page.
When the instance is not reachable, the reposync will fail.

{payg} instance remains connected to {productname} server unless it is explicitly deleted.
To delete the SSH connection datato the instance, use <<proc-deleting-connection-data-to-instance>>. 
 

{payg} instance may not be accessible from the {productname} server at all times.

. If the instance exists, but is stopped, the last known credentials will be used to try to connect to the instance. 
    How long the credentials remain available depends on the cloud provider.

. If the instance no longer exists, but is still registered with SUMA, its credentials are no longer valid and the authentication will fail.
    The error message is shown in the column Status. 
+
[WARNING]
====
The error message only indicates that the instance is not available. 
Further diagnostics about the status of the instance needs to be done on the cloud provider. 
====
