[[containerized-proxy-setup-without-internet]]
= Containerized proxy deployment without an internet connection

It is possible to deploy containerized {productname} Proxy in an environment without an internet connection.
In such case, the images are copied to an internal registry, or saved to a tar file.

This procedure allows re-use of the existing minion FQDN to create a configuration to start a containerized proxy.
The user should first register the minion to suse manager server, and then re-use the same FQDN in a generation.


Make sure the default port is set up to `8022` for virtualized proxy when creating configuration using [literal]`spacecmd`.
The product that is installed in that machine will be SUSE Manager Proxy and will not have the needed packages.
Changing the base channel to have the SUSE Manager client tools can lead to package conflicts and port conflicts.


[IMPORTANT]
====
This procedure applies to {salt} proxies only.
====

[[from.suma.to.internal.reg.without.ssl]]
== Copy images from suse manager registry to internal registry without SSL configured

[NOTE]
====
If you want to copy the images to a registry with SSL, remove the property [literal]`--dest-tls-verify=false`.
====

. In a machine with access to "registry.suse.com" (CONFIRM: what machine - SUMA server?) install [literal]`skopeo` by using the command
+
----
zypper in skopeo (can be suse manager server)
----
+
. Copy images between registries:
+
----
for image in httpd proxy-salt-broker squid ssh tftpd; do
    skopeo copy --dest-tls-verify=false docker://registry.suse.com/suse/manager/4.3/proxy-$image:latest docker://m43-registry.tf.local/4.3/proxy-$image
done
----

If the registry is unsecured (not configured with SSL), on the containerized proxy VM edit [literal]`/etc/containers/registries.conf` and add the regitry domain to the section [literal]`insecure list`.


[[air-gapped-solution-for-podman]]
Air gapped solution for podman

. Before starting the pod.
. On a machine with internet access
+
----
for image in httpd salt-broker squid ssh tftpd; do
    podman pull registry.suse.com/suse/manager/4.3/proxy-$image
done
podman pull k8s.gcr.io/pause

podman save -m -o proxy-images.tar \
    k8s.gcr.io/pause \
    registry.suse.com/suse/manager/4.3/proxy-httpd \
    registry.suse.com/suse/manager/4.3/proxy-salt-broker \
    registry.suse.com/suse/manager/4.3/proxy-squid registry.suse.com/suse/manager/4.3/proxy-ssh \
    registry.suse.com/suse/manager/4.3/proxy-tftpd
----
+
. Transfer the [literal`proxy-images.tar` to the air gapped proxy and run this command and start the pod:
+
----
podman load -i proxy-images.tar
----
