[[db-migration-xy]]
= Database Migration to Latest Version

This section covers upgrading the PostgreSQL database to the latest version.
If you are already using PostgreSQL 14, you do not need to perform this migration.

If you want to upgrade to the latest {productname} version, you must be using PostgreSQL version 13 or 14, depending on the underlying operating system:

* If you are running SLES 15 SP4, use PostgreSQL 14.
* If you are running {opensuse} Leap 15.4, use PostgreSQL 14.


[[db-migration-xy-prepare]]
== Prepare to Upgrade

Before you begin the upgrade, prepare your existing {productname} Server and create a database backup.

PostgreSQL stores data at [path]``/var/lib/pgsql/data/``.


.Procedure: Preparing to Upgrade
. Check the active PostgreSQL version:
+
----
psql --version
----
+
//If you are using PostgreSQL{nbsp}10 or 12, you can upgrade to PostgreSQL{nbsp}13.
//If you are already using PostgreSQL version 13, you do not need to perform this migration.
. Check the active smdba version:
+
----
rpm -q smdba
----
+
PostgreSQL{nbsp}14 requires ``smdba`` version 1.7.6 or later.
. Perform a database backup.
  For more information on backing up, see xref:administration:backup-restore.adoc[].


[[db-migration-xy-upgrade]]
== Upgrade PostgreSQL

[WARNING]
====
Always create a database backup before performing a migration.
====

PostgreSQL upgrades can be performed in two ways: a regular upgrade, or a fast upgrade:

A regular upgrade creates a complete copy of the database, so you need double the existing database size of space available.
Regular upgrades can take a considerable amount of time, depending on the size of the database and the speed of the storage system.

A fast upgrade only takes a few minutes, and uses almost no additional disk space.
However, if a fast upgrade fails, you must restore the database from the backup.
A fast upgrade reduces the risk of running out of disk space, but increases the
risk of data lose when a backup does not exist or cannot be replayed.
A regular upgrade will copy the database files instead of creating hard links between the files.

PostgreSQL stores data at [path]``/var/lib/pgsql/data/``.


.Procedure: Performing a Regular Upgrade
. Perform a database backup.
  For more information on backing up, see xref:administration:backup-restore.adoc[].
. Start the upgrade.
  Run the script:
+
----
/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
  The old directory is renamed to [path]``/var/lib/pgsql/data-pg12`` or [path]``/var/lib/pgsql/data-pg10``, depending on the version you started from.

The [path]``pg-migrate-x-to-y.sh`` script performs these operations:

* Stop spacewalk services
* Shut down the running database
* Check if the latest PostgreSQL is installed and install it if necessary
* Switch from previous version of PostgreSQL{nbsp} to the latest as the new default
* Initiate the database migration
* Create a PostgreSQL configuration file tuned for use by {productname}
* Start the database and spacewalk services

[NOTE]
====
If the upgrade fails, the migration script will attempt to restore the database to its original state.
====


.Procedure: Performing a Fast PostgreSQL Upgrade
. Perform a database backup.
  Without a verified database backup, you must not initiate a fast upgrade.
  For more information on backing up, see xref:administration:backup-restore.adoc[].
. Start the upgrade.
  Run the script.
+
----
/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh -f
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
  The old directory is renamed to [path]``/var/lib/pgsql/data-pg12`` or [path]``/var/lib/pgsql/data-pg10``, depending on the version you started from.
