[[db-migration-xy]]
= Database Migration to Latest Version

This section covers upgrading the {postgresql} database to the latest version.
If you are already using {postgresql} 14 or deployed {productname} as a container, you do not need to perform this migration.

If you want to upgrade to the latest {productname} version, you must be using {postgresql} version 13, 14, or 16 depending on the underlying operating system:

ifeval::[{suma-content} == true]

* If you are running {sles} 15 SP3, use {postgresql} 13.
* If you are running {sles} 15 SP4, use {postgresql} 14.
* If you are running {productname} as a container (5.0 or later), you use {postgresql} supplied with the container (version 16).

If you migrate from {productname} 4.3 to {productname} 5.0 or later as a container, the {postgresql} database migration takes place automatically as part of the {productname} migration.
For more information, see xref:installation-and-upgrade:container-deployment/suma/migrate-43-50.adoc[].

endif::[]

ifeval::[{uyuni-content} == true]

* If you are running {opensuse} Leap 15.3, use {postgresql} 13.
* If you are running {opensuse} Leap 15.4, use {postgresql} 14.
* If you are running {opensuse} Leap 15.5, use {postgresql} 14.
* If you are running {productname} as a container (2024.03 or later), you use {postgresql} supplied with the container (version 16).

endif::[]

If {productname} runs as a container, the database is stored in a persistent volume.

ifeval::[{suma-content} == true]

// 2024-04-16, ke: Thus far, this file is not available in uyuni
For more information, see xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[].

endif::[]



[[db-migration-xy-prepare]]
== Prepare to Upgrade

Before you begin the upgrade, prepare your existing {productname} Server and create a database backup.

{postgresql} stores data at [path]``/var/lib/pgsql/data/``.


.Procedure: Preparing to Upgrade
. Check the active {postgresql} version:
+
----
psql --version
----
+
//If you are using PostgreSQL{nbsp}10 or 12, you can upgrade to PostgreSQL{nbsp}13.
//If you are already using PostgreSQL version 13, you do not need to perform this migration.
. Check the active smdba version:
+
----
rpm -q smdba
----
+
{postgresql}{nbsp}14 requires [package]``smdba`` version 1.7.6 or later.
. Perform a database backup.
  For more information on backing up, see xref:administration:backup-restore.adoc[].


[[db-migration-xy-upgrade]]
== Upgrade {postgresql}

[WARNING]
====
Always create a database backup before performing a migration.
====

{postgresql} upgrades can be performed in two ways: a regular upgrade, or a fast upgrade:

A regular upgrade creates a complete copy of the database, so you need double the existing database size of space available.
Regular upgrades can take a considerable amount of time, depending on the size of the database and the speed of the storage system.

A fast upgrade only takes a few minutes, and uses almost no additional disk space.
However, if a fast upgrade fails, you must restore the database from the backup.
A fast upgrade reduces the risk of running out of disk space, but increases the
risk of data lose when a backup does not exist or cannot be replayed.
A regular upgrade will copy the database files instead of creating hard links between the files.

PostgreSQL stores data at [path]``/var/lib/pgsql/data/``.

[NOTE]
====
Before running the DB upgrade make sure that the {postgresql} user exists on the system.
The [path]``/etc/passwd`` entry  should look as follows:

----
postgres:x:26:26:PostgreSQL Server:/var/lib/pgsql:/bin/bash
----
====



.Procedure: Performing a Regular Upgrade
. Perform a database backup.
  For more information on backing up, see xref:administration:backup-restore.adoc[].
. Start the upgrade.
  Run the script:
+
----
/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
  The old directory, for example, is renamed to [path]``/var/lib/pgsql/data-pg14`` or [path]``/var/lib/pgsql/data-pg12``, depending on the version you started from.

The [path]``pg-migrate-x-to-y.sh`` script performs these operations:

* Stop spacewalk services
* Shut down the running database
* Check if the latest {postgresql} is installed and install it if necessary
* Switch from previous version of {postgresql} to the latest as the new default
* Initiate the database migration
* Create a {postgresql} configuration file tuned for use by {productname}
* Start the database and spacewalk services

[NOTE]
====
If the upgrade fails, the migration script will attempt to restore the database to its original state.
====


.Procedure: Performing a Fast {postgresql} Upgrade
. Perform a database backup.
  Without a verified database backup, you must not initiate a fast upgrade.
  For more information on backing up, see xref:administration:backup-restore.adoc[].
. Start the upgrade.
  Run the script.
+
----
/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh -f
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
  The old directory is renamed to [path]``/var/lib/pgsql/data-pg14`` or [path]``/var/lib/pgsql/data-pg12``, depending on the version you started from.
