[[installation-general-requirements]]
= General Requirements

Before you begin installation, ensure that you have:

* Current {scc} organization credentials
* Environment meets the hardware and networking requirements
* Any required SSL certificates for your environment

This section contains more information on each of these requirements.

For a complete list of supported clients and features, see xref:client-configuration:supported-features.adoc[].


.Base operating system for {productname} {productnumber} containerized Server
[IMPORTANT]
====
For {productname} {productnumber}, the base operating system of the container is {sles} {bci-suma}.
You can find these keys in your {scc} account.

{productname} comes with a maintenance lifecycle of two years.
For more information, see link:https://www.suse.com/lifecycle/[].

Long Term Service Pack Support (LTSS) for {sles-version} cannot be added to {productname}.
It is also not possible to use SLES for SAP as a base for {productname} to increase the lifecycle of the underlying operating system.
====


ifeval::[{suma-content} == true]
.Supported operating system for the Container Host
[NOTE]
====
The supported operating system for the container host is {micro} {microversion}.
====
endif::[]


ifeval::[{uyuni-content} == true]
.Supported operating system for the Container Host
[NOTE]
====
The supported operating system for the container host is {leapmicro} {microversion}.
====
endif::[]



[[install.scc-register]]
== Obtain Your SUSE Customer Center Credentials

Create an account with {scc} before installation of {sles} and {productname}.

[[creating.scc.account.mgr]]
.Procedure: Obtaining Your SCC Organization Credentials
. Navigate to https://scc.suse.com/login in your Web browser.
. Log in to your SCC account, or follow the prompts to create a new account.
. If you have not yet done so, click btn:[Connect to an Organization] and type or search for your organization.
. Click btn:[Manage my Organizations] and select your organization from the list by clicking on the organization name.
. Click the btn:[Organization] tab, and then select the btn:[Organization Credentials] tab.
. Record your login information for use during {productname} setup.

Depending on your organization's setup, you might also need to activate your subscription, using the btn:[Activate Subscriptions] menu.

For more information about using SCC, see https://scc.suse.com/docs/help.



[[installation-general-supportedbrowsers]]
== Supported Browsers for the {susemgr} {webui}

In order to use the {webui} to manage your {susemgr} environment, you will need to ensure you are running an up to date web browser.

{susemgr} is supported on:

* Latest Firefox browser shipped with {sles}
* Latest Chrome browser on all operating systems
* Latest Edge browser shipped with Windows

Windows Internet Explorer is not supported.
The {productname} {webui} will not render correctly under Windows Internet Explorer.



== SSL Certificates

{productname} uses SSL certificates to ensure that clients are registered to the correct server.
By default, {productname} uses a self-signed certificate.
If you have certificates signed by a third-party CA, you can import them to your {productname} installation.

* For more on self-signed certificates, see xref:administration:ssl-certs-selfsigned.adoc[].
* For more on imported certificates, see xref:administration:ssl-certs-imported.adoc[].
