[[installation-network-requirements]]
= Network Requirements

This section details the networking and port requirements for {productname}.

== Fully Qualified Domain Name (FQDN)
The {productname} server must resolve its FQDN correctly.
If the FQDN cannot be resolved, it can cause serious problems in a number of different components.
+
For more information about configuring the hostname and DNS, see {sles-base-os-documentation}/cha-network.html#sec-network-yast-change-host.

== Hostname and IP Address
To ensure that the {productname} domain name can be resolved by its clients, both server and client machines must be connected to a working DNS server.
You also need to ensure that reverse lookups are correctly configured.
+
For more information about setting up a DNS server, see {sles-base-os-documentation}/cha-dns.html.

== Offline Deployment
If you are on an internal network and do not have access to {scc}, you can use an xref:installation-and-upgrade/container-management/offline-deployment.adoc[Offline Deployment].


In a production environment, the {productname} Server and clients should always use a firewall.
For a comprehensive list of the required ports, see xref:installation-and-upgrade:ports.adoc[].


For more information on disconnected setup and port configuration, see xref:administration:disconnected-setup.adoc[].
