[[proxy-package-uyuni]]
= Proxy - Minor Upgrade
:description: Learn to update your SUSE Manager Proxy with minimal downtime and ensure high system availability during maintenance windows
:revdate: 2024-08-02
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Manager
:page-product-version: 5.0
ifeval::[{suma-content} == true]
:noindex:
endif::[]

Before you perform any proxy update, schedule a maintenance window.
The clients registered to {productname} through the proxy will not be able to connect to {productname} while the update is in progress.
For more information about maintenance windows, see xref:administration:maintenance-windows.adoc[].

[NOTE]
====
Minor proxy upgrades do not include a version upgrade of the operating system.
For more information, see the {productname} {productnumber} release notes.
====



== Upgrade the Proxy

To update a proxy you first stop the proxy service, then update the software and finally restart the proxy service.



.Procedure: Updating the {productname} Proxy
. On the {productname} Proxy, stop the proxy service:
+
----
spacewalk-proxy stop
----
. In the {productname} Server {webui}, navigate to menu:Systems[Proxy] and click the name of the proxy.
. Select all the packages to be updated on the proxy, and then apply the selection.
. On the {productname} Proxy, start the proxy service:
+
----
spacewalk-proxy start
----

If you need to update many proxies, you can create an action chain of this command sequence on the {productname} Server.
You can use the action chain to perform updates on multiple proxies at the same time.
