[[update.suse.manager.proxy]]
= Upgrade the Proxy

{productname} Proxies are managed in the same way as clients.

ifeval::[{suma-content} == true]
Maintenance updates (MU) can be installed on the {productname} Proxy in the same way as other clients.
MU updates require a restart of the proxy service.
endif::[]

Before you perform any proxy update, schedule a maintenance window.
The clients registered to {productname} through the proxy will not be able to connect to {productname} while the update is in progress.
For more information about maintenance windows, see xref:administration:maintenance-windows.adoc[].

ifeval::[{suma-content} == true]
{productname} uses an [literal]``X.Y.Z`` versioning schema.
To determine which upgrade procedure you need, look at which part of the version number is changing.


Major Version Upgrade (X Upgrade)::
Upgrading to the next major version.
For example, upgrading from 3.2 to 4.0 or to 4.1.
This type of upgrade does not apply to 4.3.
See xref:installation-and-upgrade:proxy-x.adoc[].

Minor Version Upgrade (Y Upgrade)::
Upgrading to the next minor version.
This is often referred to as a service pack (SP) migration.
For example, upgrading from 4.1 to 4.3 or from 4.2 to 4.3.
See xref:installation-and-upgrade:proxy-y-z.adoc[].

Patch Level Upgrade (Z Upgrade)::
Upgrading within the same minor version.
This is often referred to as a maintenance update.
For example, upgrading from 4.3.0 to 4.3.1.
See xref:installation-and-upgrade:proxy-y-z.adoc[].
endif::[]


ifeval::[{uyuni-content} == true]
[IMPORTANT]
====
The upgrade procedure to {productnumber} can either be a major or a minor upgrade.
For more information, see the {productname} {productnumber} release notes.
====

Major Upgrade::
See xref:installation-and-upgrade:proxy-uyuni.adoc[].

Minor Upgrade::
See xref:installation-and-upgrade:proxy-minor-uyuni.adoc[].
endif::[]
