[[server-minor-upgrade]]
= Server - Minor Upgrade
:description: Perform a minor upgrade of your SUSE Manager Server with the latest bug fixes and feature improvements, learning the process in this tutorial
:revdate: 2024-08-02
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Manager
:page-product-version: 5.0
ifeval::[{suma-content} == true]
:noindex:
endif::[]

Several times a year, the {productname} team releases minor upgrades of the {productname} Server.
These updates address bug fixes and feature improvements, and sometimes include new features.

[IMPORTANT]
====
Some additional manual steps might be required, and this information is only available in the release notes.
For more information about such a major upgrade, see xref:installation-and-upgrade:server-major-upgrade-uyuni.adoc[].

For information about your upgrade, see the release notes at https://www.uyuni-project.org/pages/stable-version.html.
====

Performing a minor upgrade is similar to installing operating system package updates.

.Procedure: Updating Packages on the {productname} Server

By default, several update repositories are configured and enabled for the {productname} Server.
New and updated packages become available automatically.

It is recommended you make a backup of the server before upgrading.
For more information about backing up {productname}, see xref:administration:backup-restore.adoc[].


. On the {productname} Server, at the command prompt, as root, stop the spacewalk services:
+

----
spacewalk-service stop
----
+

. Refresh software repositories:
+

----
zypper ref
----
+

// Zypper list-patches or patch doesn't update Uyuni
. Update new packages: (Repeat this if prompted by zypper)
+

----
zypper up
----
[NOTE]
====
Uyuni is different from SUSE Manager in this step.
SUSE Manager uses [command]``zypper patch``, but Uyuni requires [command]``zypper up``.
====
+

. If zypper reports that the Uyuni package will not be upgraded, run the command manually:
+

----
zypper install Uyuni-Server-release
----
+

. Restart the spacewalk services:
+
----
spacewalk-service start
----
+
Reboot the server if a patch update recommends rebooting.

[NOTE]
====
By default, zypper refreshes the repository every ten minutes (see ``repo.refresh.delay`` in [path]``/etc/zypp/zypp.conf``).
If ``autorefresh`` is disabled, run [command]``zypper ref`` to refresh all repositories.
====

// We can remove  the version info when 4.1 / 2020.07 is released
[NOTE]
====

ifeval::[{suma-content} == true]
Starting with {productname} 4.1, [command]``spacewalk-schema-upgrade`` is not needed anymore.
endif::[]

ifeval::[{uyuni-content} == true]
Starting with {productname} 2020.04 [command]``spacewalk-schema-upgrade`` is not needed anymore.
endif::[]

The schema upgrade is run automatically when the spacewalk service is started with [command]``spacewalk-service start``.

====

[IMPORTANT]
====
Services affected by a package update are not automatically restarted after an update.
You need to restart these services manually to avoid potential failures.
Use [command]``zypper ps`` to check for applications that are using old code and require restarting.
====
