[[server-major-upgrade]]
= Server - Major Upgrade

When {productname} core components are upgraded to new major versions, you need to perform a major upgrade on the {productname} Server.
This is the case if a version upgrade of PostgreSQL, Salt, or openSUSE Leap is needed.
openSUSE Leap is the underlying base operating system (OS).

[IMPORTANT]
====
Some additional manual steps might be required, and this information is only available in the release notes.
For important extra information about your upgrade, see the release notes at:

https://www.uyuni-project.org/pages/stable-version.html.
====

[IMPORTANT]
====
You will not be able to fix issues that arise during the migration.
Ensure you have created a backup before you start the migration.
For more information about backing up {productname}, see xref:administration:backup-restore.adoc[].
If you are running {productname} Server on a virtual machine, we recommend that you create a snapshot before you start.
====

[IMPORTANT]
====
Before the upgrade, ensure that storage requirements are met.
For more information, see xref:uyuni-install-requirements.adoc[].
The migration procedure can fill the root partition if there is not enough space available due to the service pack migration and the download of new software packages.
It is the same for the [path]``/var/lib/pgsql`` when upgrading PostgreSQL.
It takes a copy of the old database, thus be sure to have at least enough space available to cope with a copy of the database.
====

The [command]``server-migrator.sh`` script migrates {productname} Server to the latest version.
It also upgrades the underlying operating system to version {opensuse-version}.
The script is part of the [package]``susemanager`` package.

.Procedure: Migrating the {productname} Server
. Before running the [command]``server-migrator.sh`` script, check whether the most recent version of the [package]``susemanager`` package is installed:
+
----
zypper ref
zypper up susemanager
----
. Run the [command]``/usr/lib/susemanager/bin/server-migrator.sh`` script to upgrade the base OS and {productname} Server.

////
//   At the moment 2023.09, not needed
. To migrate the database to the latest database version run the migrate script:
+
----
/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh
----
+
For more information about PostgreSQL database migration, see xref:db-migration-xy.adoc[].
////

[IMPORTANT]
====
After the migration is complete, manually reboot the {productname} Server:
====
