[server-minor-upgrade]
= Server - Minor Upgrade

Several times a year, the {productname} team releases minor upgrades of the {productname} Server.
These updates address bug fixes and feature improvements, and sometimes include new features.

[IMPORTANT]
====
Some additional manual steps might be required, and this information is only available in the release notes.
For important extra information about your upgrade, see the release notes at https://www.uyuni-project.org/pages/stable-version.html.
====

Performing a minor upgrade is similar to installing operating system package updates.

.Procedure: Updating Packages on the {productname} Server

By default, several update repositories are configured and enabled for the {productname} Server.
New and updated packages become available automatically.

It is recommended you make a backup of the server before upgrading.
For more information about backing up {productname}, see xref:administration:backup-restore.adoc[].


. On the {productname} Server, at the command prompt, as root, stop the spacewalk services:
+

----
spacewalk-service stop
----
+

. Refresh software repositories:
+

----
zypper ref
----
+

// Zypper list-patches or patch doesn't update Uyuni
. Update new packages: (Repeat this if prompted by zypper)
+

----
zypper up 
----
+

. If zypper reports that the Uyuni package won't be upgraded, run the command manually:
+

----
zypper install Uyuni-Server-release
----
+

. Restart the spacewalk services:
+
----
spacewalk-service start
----
+
Reboot the server if a patch update recommends rebooting.

[NOTE]
====
By default, zypper refreshes the repository every ten minutes (see ``repo.refresh.delay`` in [path]``/etc/zypp/zypp.conf``).
If ``autorefresh`` is disabled, run [command]``zypper ref`` to refresh all repositories.
====

// We can remove  the version info when 4.1 / 2020.07 is released
[NOTE]
====

ifeval::[{suma-content} == true]
Starting with {productname} 4.1, [command]``spacewalk-schema-upgrade`` is not needed anymore.
endif::[]

ifeval::[{uyuni-content} == true]
Starting with {productname} 2020.04 [command]``spacewalk-schema-upgrade`` is not needed anymore.
endif::[]

The schema upgrade is run automatically when the spacewalk service is started with [command]``spacewalk-service start``.

====

[IMPORTANT]
====
Services affected by a package update are not automatically restarted after an update.
You need to restart these services manually to avoid potential failures.
Use [command]``zypper ps`` to check for applications that are using old code and require restarting.
====
