[[upgrade-overview]]
= Upgrade Guide Overview

**Updated:** {docdate}

{productname} has three main components, all of which need regular updates.
This guide covers updating the {productname} Server, Proxy, and clients, as well as some underlying components, such as the database.

It is possible to automate some of the upgrades, but others need to be performed manually.

[NOTE]
====
This guide is not intended to be read cover to cover.
Instead, navigate to the component you want to upgrade, then identify the versions you are upgrading from and to.
====

ifeval::[{suma-content} == true]
{productname} uses an [literal]``X.Y.Z`` versioning schema.
To determine which upgrade procedure you need, look at which part of the version number is changing.

Major Version Upgrade (X Upgrade)::
Upgrading to the next major version.
For example, upgrading from 3.2 to 4.1.
This type of upgrade does not apply to 4.3.

Minor Version Upgrade (Y Upgrade)::
Upgrading to the next minor version.
This is often referred to as a product migration, service pack migration, or SP migration.
For example, upgrading from 4.2 to 4.3.

Patch Level Upgrade (Z Upgrade)::
Upgrading within the same minor version.
This is often referred to as a maintenance update.
For example, upgrading from 4.1.2 to 4.1.8 or from 4.3.0 to 4.3.1.

If you are upgrading the {productname} Server, see xref:installation-and-upgrade:server-intro.adoc[].

endif::[]

ifeval::[{uyuni-content} == true]
{productname} uses an [literal]``YYYY.MM`` versioning schema suitable for rolling releases.
If you are upgrading the {productname} Server, see xref:installation-and-upgrade:server-intro-uyuni.adoc[].
endif::[]

If you are upgrading the {productname} Proxy, see xref:installation-and-upgrade:proxy-intro.adoc[].

If you are upgrading clients, see xref:client-configuration:client-upgrades.adoc[].

ifeval::[{suma-content} == true]
In addition to upgrading the server, you need to upgrade other underlying technologies, including the database.
For more information about upgrading the database, see xref:installation-and-upgrade:db-intro.adoc[].
endif::[]
