
= Dokumentácia {productname}
:revdate: 2025-04-30
:page-revdate: {revdate}

ifeval::[{mlm-content} == true]

[.currentrel]**Verzia: {productnumber}**
endif::[]

ifeval::[{uyuni-content} == true]

[.currentrel]**Verzia: {productnumber}**

endif::[]

ifeval::[{mlm-content} == true]

[IMPORTANT]
====
V súčasnosti prebieha proces aktualizácie a vylepšovania [.currentrel]**{productnumber}** documentation. Vezmite prosím na vedomie, že táto dokumentácia je v súčasnosti vo forme **návrhu** a mala by sa považovať za work in progress (WIP).

Finálne vydanie verzie 5.1 sa očakáva v polovici roka 2025. Dovtedy sa obsah môže vyvíjať a niektoré časti môžu byť neúplné alebo podliehať zmenám.

Na vašej odozve záleží: Vítame a oceňujeme vašu odozvu. Ak narazíte na nejasné informácie, medzery v obsahu alebo máte návrhy na zlepšenie, prosím, dajte nám vedieť. Vaše podnety sú neoceniteľné, pretože nám pomáhajú poskytovať presnú a užitočnú dokumentáciu.

📬 Odoslať spätnú väzbu: https://github.com/uyuni-project/uyuni-docs/issues
====
endif::[]

ifeval::[{uyuni-content} == true]

[IMPORTANT]
====
V súčasnosti prebieha proces vylepšovania dokumentácie [.currentrel]**{productnumber}**.

**Vážime si vaše pripomienky:** Vaša spätná väzba je pre nás veľmi dôležitá!
Ak sa vám zdajú niektoré časti dokumentácie nejasné alebo ste si všimli chýbajúce informácie, neváhajte sa na nás obrátiť.
Vážime si vaše otázky a návrhy, ktoré nám pomáhajú zlepšovať sa.


Odoslanie spätnej väzby: https://github.com/uyuni-project/uyuni-docs/issues
====
endif::[]


== Čo je {productname}?


// [#salt.gloss] may be used to create a tooltip for a glossary term: see branding/supplemental-ui/mlm/mlmcom/partials/footer-scripts.hbs

{productname} je riešenie pre organizácie, ktoré vyžadujú spoľahlivú kontrolu nad údržbou a nasadzovaním balíkov na svojich serveroch. Umožňuje spravovať veľké sady linuxových systémov a udržiavať ich v aktuálnom stave pomocou automatizovanej správy softvéru, správy prostriedkov a poskytovania systémov. Tiež umožňuje zachovať vysokú úroveň bezpečnosti a zároveň efektívne riadiť požiadavky na životný cyklus systému.

{productname} používa {salt} na poskytovanie udalosťami riadenej konfigurácie a riadenia správy. Salt-master riadi desiatky tisíc klientov {salt} (klienti {productname}) pomocou vzdialeného spúšťania.

{productname} ponúka bezproblémovú správu klientskych systémov {sle}, {opensuse}, {rhel}, {centos}, {oracle}, {ubuntu}, {debian}, {amazon}, {almalinux} a {raspberrypios}. Môžu byť on-premise alebo vo verejnom cloude, súkromnom cloude, hybridnom cloude alebo dokonca vo viaccloudových prostrediach.



// MLM index content

ifeval::[{mlm-content} == true]
== Dostupná dokumentácia

Nasledujúca dokumentácia pre {productname} verzia {productnumber} je k dispozícii vo formáte PDF na jednoduché stiahnutie a odkaz.


Stiahnuť kompletnú sadu súborov PDF icon:caret-right[] icon:file-archive[link="../suse-multi-linux-manager-docs_en-pdf.zip"]

[TIP]
====
Dokumentácia {productname} je k dispozícii na viacerých miestach a vo viacerých formátoch. Najnovšiu verziu tejto dokumentácie nájdete na link:https://documentation.suse.com/[SUSE Multi-Linux Manager].
====

endif::[]


//Uyuni Index content

ifeval::[{uyuni-content} == true]
== Dostupná dokumentácia

Nasledujúca dokumentácia pre {productname} verzia {productnumber} je k dispozícii vo formáte PDF na jednoduché stiahnutie a odkaz.

Stiahnuť kompletnú sadu súborov PDF icon:caret-right[] icon:file-archive[link="../uyuni-docs_en-pdf.zip"]
endif::[]
