[[quickstart-uyuni-install-proxy]]
= Deploy {productname} Proxy 
ifeval::[{suma-content} == true]
:noindex:
endif::[]

{productname} Proxy can be installed as a server extension on openSUSE Leap.
The proxy is installed in the same way as a client, but is designated as a proxy server during installation.
This is achieved by adding the {uyuni} Proxy pattern, and executing the proxy setup script.

* For more information about the stable version of {productname}, see https://www.uyuni-project.org/pages/stable-version.html.
* For more information about the development version of {productname}, see https://www.uyuni-project.org/pages/devel-version.html.




== Mirror {productname} Proxy software

The {productname} Proxy software is available from https://download.opensuse.org.
You can synchronize the proxy software to your {productname} Server.
This process is also known as mirroring.



.Procedure: Mirroring {productname} Proxy software
. On the {productname} Server, create openSUSE Leap and the {productname} Proxy channels with the [command]``spacewalk-common-channels`` command.
  [command]``spacewalk-common-channels`` is part of the [package]``spacewalk-utils`` package:
+
----
spacewalk-common-channels \
opensuse_leap15_5 \
opensuse_leap15_5-non-oss \
opensuse_leap15_5-non-oss-updates \
opensuse_leap15_5-updates \
opensuse_leap15_5-backports-updates \
opensuse_leap15_5-sle-updates \
opensuse_leap15_5-uyuni-client \
uyuni-proxy-stable-leap-155
----
+
Instead of the [systemitem]``uyuni-proxy-stable-leap-155`` version you can also try the latest development version, called [systemitem]``uyuni-proxy-devel-leap``.
For more information, see xref:client-configuration:clients-opensuseleap.adoc[].



== Register the openSUSE Leap system

Begin by installing openSUSE Leap on a physical or virtual machine.
To ensure that the proxy is accessible across the network, you must have a resolvable fully qualified domain name (FQDN) on the openSUSE Leap system before you begin the installation.
You can configure an FQDN with {yast} by navigating to menu:System[Network Settings > Hostname/DNS].

When you have installed openSUSE Leap on the proxy and configured the FQDN, you can prepare the {productname} Server, and register the openSUSE Leap system as a client.



.Procedure: Registering the openSUSE Leap system
. On the {productname} Server, create an activation key with openSUSE Leap as a base channel and the proxy and the other channels as child channels.
  For more information about activation keys, see xref:client-configuration:activation-keys.adoc[].
. Modify a bootstrap script for the proxy.
  Ensure you add the GPG key for {uyuni} to the [systemitem]``ORG_GPG_KEY=`` parameter.
  For example:
+
----
ORG_GPG_KEY=uyuni-gpg-pubkey-0d20833e.key
----
  ** For more information, see xref:client-configuration:clients-opensuseleap.adoc[].
. Bootstrap the client using the script.
  ** For more information, see xref:client-configuration:registration-bootstrap.adoc[].
. Navigate to menu:Salt[Keys] and accept the key.
  When the key is accepted, the new proxy will show in menu:Systems[Overview] in the [guimenu]``Recently Registered Systems`` section.
. Navigate to menu:System Details[Software > Software Channels], and check that the proxy channel is selected.




== Install Uyuni Proxy on openSUSE Leap

On the client, use the [command]``zypper`` command line tool or on the {productname} Server, the {webui} to install the proxy software on openSUSE Leap.



.Procedure: Installing Uyuni Proxy on openSUSE Leap
. Install the pattern for the {productname} Proxy.
  You can do this either on the client or on the server.
* For the client, use [command]``zypper``
+
----
zypper in patterns-uyuni_proxy
----
* Alternatively, on the {productname} Server, use the {webui}.
  Navigate to the details tab of the client, click menu:Software[Packages > Install], and schedule [package]``patterns-uyuni_proxy`` for installation.
. Reboot the client.



== Prepare the Proxy

Before you begin, ensure that the proxy pattern is installed correctly.
// FIXME: there might be a better way to check it:
To verify a successful installation, on the {productname} Server, select the [package]``pattern_uyuni_proxy`` package for installation.

The salt-broker service is automatically started after installation is complete.
This service forwards the Salt interactions to the {productname} Server.

[NOTE]
====
It is possible to arrange Salt proxies in a chain.
In this case, the upstream proxy is named `parent`.
====

Make sure the TCP ports `4505` and `4506` are open on the proxy.
The proxy must be able to reach the {productname} Server or a parent proxy on these ports.

The proxy shares some SSL information with the {productname} Server.
You need to copy the certificate and its key from the {productname} Server or the parent proxy to the proxy you are setting up.



.Procedure: Copying the Server Certificate and Key
. On the proxy you are setting up, at the command prompt, as root, create a directory for the certificate and key:
+
----
mkdir -m 700 /root/ssl-build
cd /root/ssl-build
----
. Copy the certificate and the key from the source to the new directory.
  In this example, the source location is called ``PARENT``.
  Replace this with the correct path:
+
----
scp root@<PARENT>:/root/ssl-build/RHN-ORG-PRIVATE-SSL-KEY .
scp root@<PARENT>:/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT .
scp root@<PARENT>:/root/ssl-build/rhn-ca-openssl.cnf .
----


[NOTE]
====
To keep the security chain intact, the {productname} Proxy functionality requires the SSL certificate to be signed by the same CA as the {productname} Server certificate.
Using certificates signed by different CAs for proxies and server is not supported.
For more information on how {productname} handles certificates, see xref:administration:ssl-certs.adoc[].
====



== Set Up the Proxy

When you have prepared the proxy, use the supplied interactive [command]``configure-proxy.sh`` script to complete the proxy setup.



.Procedure: Setting up the Proxy
.  On the proxy you are setting up, at the command prompt, as root, execute the setup script:
+
----
configure-proxy.sh
----
. Follow the prompts to set up the proxy.
  Leave a field blank and type kbd:[Enter] to use the default values shown between square brackets.

More information about the settings set by the script:

{productname} Parent::
the {productname} parent can be either another proxy or a server.

HTTP Proxy::
A HTTP proxy enables your {productname} Proxy to access the Web.
This is needed if direct access to the Web is prohibited by a firewall.

Traceback Email::
An email address where to report problems.

Do You Want to Import Existing Certificates?::
Answer ``N``.
This ensures using the new certificates that were copied previously from the {productname} server.

Organization::
The next questions are about the characteristics to use for the SSL certificate of the proxy.
The organization might be the same organization that was used on the server, unless of course your proxy is not in the same organization as your main server.

Organization Unit::
The default value here is the proxy's hostname.

City::
Further information attached to the proxy's certificate.

State::
Further information attached to the proxy's certificate.

Country Code::
In the [guimenu]``country code`` field, enter the country code set during the {productname} installation.
For example, if your proxy is in the US and your {productname} is in DE, enter `DE` for the proxy.
+

[NOTE]
====
The country code must be two upper case letters.
For a complete list of country codes, see https://www.iso.org/obp/ui/#search.
====

Cname Aliases (Separated by Space)::
Use this if your proxy can be accessed through various DNS CNAME aliases.
Otherwise it can be left empty.

CA Password::
Enter the password that was used for the certificate of your {productname} Server.

Do You Want to Use an Existing SSH Key for Proxying SSH-Push Salt Minion?::
Use this option if you want to reuse a SSH key that was used for SSH-Push Salt clients on the server.

Create and Populate Configuration Channel rhn_proxy_config_1000010001?::
Accept default ``Y``.

SUSE Manager Username::
Use same user name and password as on the {productname} server.

If parts are missing, such as CA key and public certificate, the script prints commands that you must execute to integrate the needed files.
When the mandatory files are copied, run [command]``configure-proxy.sh`` again.
If you receive an HTTP error during script execution, run the script again.

[command]``configure-proxy.sh`` activates services required by {productname} Proxy, such as [systemitem]``squid``, [systemitem]``apache2``, [systemitem]``salt-broker``, and [systemitem]``jabberd``.

To check the status of the proxy system and its clients, click the proxy system's details page on the {webui} (menu:Systems[System List > Proxy], then the system name).
[guimenu]``Connection`` and [guimenu]``Proxy`` subtabs display various status information.

If you want to PXE boot your clients from your {productname} Proxy, you also need to synchronize the TFTP data from the {productname} Server.
//For more information about this synchronization, see xref:client-configuration:autoinst-pxeboot.adoc[].



.Procedure: Synchronizing Profiles and System Information
. On the proxy, at the command prompt, as root, install the [package]``susemanager-tftpsync-recv`` package:
+
----
zypper in susemanager-tftpsync-recv
----
. On the proxy, run the [command]``configure-tftpsync.sh`` setup script and enter the requested information:
+
----
configure-tftpsync.sh
----
+
You need to provide the hostname and IP address of the {productname} Server and the proxy.
You also need to enter the path to the ``tftpboot`` directory on the proxy.
. On the server, at the command prompt, as root, install [package]``susemanager-tftpsync``:
+
----
zypper in susemanager-tftpsync
----
. On the server, run [command]``configure-tftpsync.sh`` setup script and enter the requested information:
+
----
configure-tftpsync.sh
----
. Run the script again with the fully qualified domain name of the proxy you are setting up.
  This creates the configuration, and uploads it to the {productname} Proxy:
+
----
configure-tftpsync.sh FQDN_of_Proxy
----
. On the server, start an initial synchronization:
+
----
cobbler sync
----
+
You can also synchronize after a change within {cobbler} that needs to be synchronized immediately.
Otherwise {cobbler} synchronization will run automatically when needed.
//For more information about PXE booting, see xref:client-configuration:autoinst-pxeboot.adoc[Install via the Network].



== Configure DHCP for PXE through Proxy

{productname} uses {cobbler} for client provisioning.
PXE (tftp) is installed and activated by default.
Clients must be able to find the PXE boot on the {productname} Proxy using DHCP.
Use this DHCP configuration for the zone which contains the clients to be provisioned:

----
next-server: <IP_Address_of_Proxy>
filename: "pxelinux.0"
----



== Reinstalling a Proxy

A proxy does not contain any information about the clients that are connected to it.
Therefore, a proxy can be replaced by a new one at any time.
The replacement proxy must have the same name and IP address as its predecessor.

Proxy systems are registered as Salt clients using a bootstrap script.

This procedure describes software channel setup and registering the installed proxy with an activation key as the {productname} client.

[IMPORTANT]
====
Before you can select the correct child channels while creating the activation key, ensure you have properly synchronized the openSUSE Leap channel with all the needed child channels and the {productname} Proxy channel.
====



== More Information

For more information about the {uyuni} project, and to download the source, see https://www.uyuni-project.org/.

For more {uyuni} product documentation, see https://www.uyuni-project.org/uyuni-docs/uyuni/index.html.

To raise an issue or propose a change to the documentation, use the links under the ``Resources`` menu on the documentation site.
