[[aws-server-setup]]
= Server Setup
:description: Configure storage for your container and database using the mgr-storage-server tool or mgr-storage-proxy
:revdate: 2025-02-26
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

.Procedure: Log in and Update the System
. SSH into your {AWS} instance.

. Switch to the root user and update the system.
+

----
sudo -i
transactional-update
----

. Reboot the system.

. Configure storage with the `mgr-storage-server` tool or in the case of the proxy use [command]``mgr-storage-proxy``. 
** For more information, see [command]``mgr-storage-server --help`` or [command]``mgr-storage-proxy --help``.

This tool simplifies creating the container storage and database volumes.

.Procedure
. Format the command in the following manner: 
+

----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----
+
For example: 
+
----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----
+

[NOTE]
====
This command will create the following persistent storage volumes at [path]``/var/lib/containers/storage/volumes``:

For more information, see xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[].
====

. Run `mgradm install podman <FQDN>` as root.















