= {productname} 代理隔离的部署
:description: 在高安全环境中使用 SUSE Multi-Linux Manager 工具配置和部署安全的隔离的系统
:revdate: 2025-04-28
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

== 什么是隔离的部署？


隔离部署是指任何网络系统的设置和操作，该系统与不安全的网络（尤其是互联网）物理隔离。
这种类型的部署通常用于高安全性环境，如军事设施、金融系统、关键基础设施，以及处理敏感数据并必须保护免受外部威胁的任何地方。

[NOTE]
====
目前，仅在 {sl-micro} 上提供隔离部署功能。
====


== 通过虚拟机部署

建议的安装方法是使用所提供的 {productname} 虚拟机映像选项，因为所需的全部工具和容器映像都已预先加载并且随时可用。

有关安装 {productname} 代理虚拟机的更多信息，请参见 xref:container-deployment/mlm/proxy-deployment-vm-mlm.adoc[将代理作为虚拟机部署]。

要升级 {productname} 代理，用户应遵循 xref:container-management/updating-proxy-containers.adoc[代理升级] 中定义的程序。


== 在 {productname} 上部署 {sl-micro}

{productname} 还以 RPM 的形式提供了所有所需的容器映像，可在系统上安装。

.过程：升级在隔离环境中，于 {productname} 上安装 {sl-micro}。
[role=procedure]
____
. 安装 {sl-micro}。

. 在 {productname} 服务器上将代理主机操作系统作为客户端启动。

. 更新系统。

. 安装工具软件包和映像包（将 $ARCH$ 替换为正确的体系结构）

+

[source,shell]
----
transactional-update pkg install mgrpxy* mgrctl* suse-multi-linux-manager-5.1-$ARCH$-proxy-*
----

. 重引导。

. 使用 mgrpxy 部署 {productname}。
____


有关在 {productname} 上安装 {sl-micro} 代理的更多详细信息，请参见 xref:container-deployment/mlm/proxy-deployment-mlm.adoc[将代理作为虚拟机部署]。

要升级 {productname} 代理，用户应遵循 xref:container-management/updating-proxy-containers.adoc[代理升级] 中定义的程序。


== 可用映像

一些公式，如 Bind 和 DHCP (Kea)，也使用容器。
如果您计划在隔离环境中使用它们，您需要拉取它们的映像，将其保存到存档中，并在您的 {productname} 代理或其他管理系统上加载它们。

这些映像可从 `registry.suse.com` 获取。

.过程：升级为隔离环境获取公式映像
[role=procedure]
____
. 在能够访问互联网的系统上，拉取所需映像。

+

[source,shell]
----
podman pull registry.suse.com/suse/bind:latest
podman pull registry.suse.com/suse/kea:2.6
----

. 从归档中加载映像：

+

[source,shell]
----
podman save -m -o formula-images.tar registry.suse.com/suse/bind:latest registry.suse.com/suse/kea:2.6
----

. 将 `formula-images.tar` 文件传输到您的隔离系统。

. 从归档中加载映像：

+

[source,shell]
----
podman load -i formula-images.tar
----
____
