= {productname} Proxy Air-gapped Deployment
:revdate: 2025-04-28
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

== What is air-gapped deployment?


Air-gapped deployment refers to the setup and operation of any networked system that is physically isolated from insecure networks, especially the internet.
This type of deployment is commonly used in high-security environments such as military installations, financial systems, critical infrastructure, and anywhere sensitive data is handled and must be protected from external threats.

[NOTE]
====
At the moment, air-gapped deployment is available only on {sl-micro}.
====


== Deploy with Virtual Machine

The recommended installation method is using the provided {productname} Virtual Machine Image option, since all the needed tools and container images are pre-loaded and will work out of the box.

For more information about installing {productname} Proxy Virtual Machine, see xref:container-deployment/mlm/proxy-deployment-vm-mlm.adoc[Deploy Proxy as a Virtual Machine].

To upgrade {productname} Proxy, users should follow the procedures defined in xref:container-management/updating-proxy-containers.adoc[Proxy Upgrade].


== Deploy {productname} on {sl-micro}

{productname} also provides all the needed container images in RPM's that can be installed on the system.

.Procedure: Install {productname} on {sl-micro} in Air-gapped
. Install {sl-micro}.
. Bootstrap the Proxy Host OS as a Client on {productname} Server.
. Update the system.
. Install tools packages and image packages (replace $ARCH$ with the correct architecture)

+

[source,shell]
----
transactional-update pkg install mgrpxy* mgrctl* suse-multi-linux-manager-5.1-$ARCH$-proxy-*
----

. Reboot.

. Deploy {productname} with mgrpxy.


For more detailed information about installing {productname} Proxy on {sl-micro}, see xref:container-deployment/mlm/proxy-deployment-mlm.adoc[Deploy Proxy as a Virtual Machine].

To upgrade {productname} Proxy, users should follow the procedures defined in xref:container-management/updating-proxy-containers.adoc[Proxy Upgrade].

== Formula Images

Some formulas, like Bind and DHCP (Kea), also use containers. If you plan to use them in an air-gapped environment, you need to pull their images, save them to an archive, and load them on your {productname} Proxy or another managed system.

The images are available from `registry.suse.com`.

.Procedure: Getting Formula Images for Air-Gapped Environments
. On a system with Internet access, pull the required images.
+
[source,shell]
----
podman pull registry.suse.com/suse/bind:latest
podman pull registry.suse.com/suse/kea:2.6
----
. Save the images to a TAR archive:
+
[source,shell]
----
podman save -o formula-images.tar registry.suse.com/suse/bind:latest registry.suse.com/suse/kea:2.6
----
. Transfer the `formula-images.tar` file to your air-gapped system.
. Load the images on the air-gapped system:
+
[source,shell]
----
podman load -i formula-images.tar
----
