[[installation-proxy-containers]]
= {productname} {productnumber} Proxy Deployment
:revdate: 2025-06-26
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]


This guide outlines the deployment process for the {productname} {productnumber} Proxy container on {sl-micro} {microversion} or {sles} {bci-mlm}.
This guide presumes you have already successfully deployed a {productname} {productnumber} Server.

[IMPORTANT]
====
{sl-micro} is only supported as regular minion ([systemitem]``default`` contact method) for the time being.
We are working on managing it as Salt SSH client ([systemitem]``salt-ssh`` contact method), too.
====


To successfully deploy, you will perform the following actions:


// Add certificate tasks item
.Procedure: Deploying Proxy
[role=procedure]
_____
. Review hardware requirements.

. Synchronize the {sl-micro} {microversion} or {sles} {bci-mlm} parent channel and the proxy extension child channel on the server.

. Install {sl-micro} or {sles} on a bare-metal machine.

. Create a {salt} activation key with Proxy Extension.

. Bootstrap the proxy as a client with the [systemitem]``default`` connection method.

. Generate a proxy configuration.

. Transfer the proxy configuration from server to proxy.

. Install packages on the proxy.

. Use the proxy configuration to register the client as a proxy with {productname}.

_____


.Supported operating system for the Proxy Container Host
[NOTE]
====
The supported operating system for the container host are {sl-micro} {microversion} and {sles} {bci-mlm}.

Container host::
A container host is a server equipped with a container engine like Podman, which lets it manage and deploy containers.
These containers hold applications and their essential parts, such as libraries, but not a full operating system, making them lightweight.
This setup ensures applications run the same way in different environments.
The container host supplies the necessary resources such as CPU, memory, and storage for these containers.
====


== Hardware Requirements for the Proxy


For more information about hardware requirements for deploying {productname} Proxy, see xref:installation-and-upgrade:hardware-requirements.adoc#proxy-hardware-requirements[].



== Synchronize the Parent and Proxy Extension Child Channels

This section presumes that you have already entered your organization credentials under the menu:Admin[Setup Wizard > Organization Credentials] in the server's {webui}.
Products are listed on the menu:Admin[Setup Wizard > Products] page.
This channel must be fully synchronized on the server, with the child channel [systemitem]``Proxy`` as an extension option selected.


.Procedure: Synchronizing the Parent Channel and Proxy Extension
[role=procedure]
_____

. In the {productname} {webui} select menu:Admin[Products].

. From the products page enter {sl-micro} or {sles} in the filter field.

. Next use the drop-down to select the required architecture.
  For this example {x86_64}.

. In the [systemitem]``Product Description`` field select the {sl-micro} {microversion} or {sles} {bci-mlm} checkbox then use the drop-down to select the [systemitem]``{productname} Proxy Extension 5.1 x86_64`` extension.

. Click the btn:[Add products] button.

. Wait for the synchronization to complete.

_____


[[deploy-mlm-proxy-host]]
==  Prepare {productname} Proxy Host

In the following subsections, you either prepare the proxy host with {sle-micro} or {sles}.

[[deploy-mlm-proxy-micro]]
ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-prepare-micro-proxy-host.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-prepare-micro-proxy-host.adoc[leveloffset=+1]
endif::[]

To continue with deployment, see xref:installation-and-upgrade:container-deployment/mlm/proxy-deployment-mlm.adoc#deploy-mlm-proxy-persistent-storage[].



[[deploy-mlm-proxy-sles]]
ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-prepare-sles-proxy-host.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-prepare-sles-proxy-host.adoc[leveloffset=+1]
endif::[]

To continue with deployment, see xref:installation-and-upgrade:container-deployment/mlm/proxy-deployment-mlm.adoc#deploy-mlm-proxy-persistent-storage[].



[[deploy-mlm-proxy-persistent-storage]]
== Configure Custom Persistent Storage

Configuring persistent storage is optional, but it is the only way to avoid serious trouble with container full disk conditions.
If custom persistent storage is required for your infrastructure, use the [command]``mgr-storage-proxy`` tool.

* For more information, see [command]``mgr-storage-proxy --help``.
This tool simplifies creating the container storage and Squid cache volumes.

Use the command in the following manner:

[source,shell]
----
mgr-storage-proxy <storage-disk-device>
----

For example:

[source, shell]
----
mgr-storage-proxy /dev/nvme1n1
----



[NOTE]
====
This command will create the persistent storage volumes at [path]``/var/lib/containers/storage/volumes``.

For more information, see

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]
====

// Snippet for creating activation key only
ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-actkey-bootstrap-proxy-mlm.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-actkey-bootstrap-proxy-mlm.adoc[]
endif::[]

// (New) Snippet for bootsrapping the proxy
ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-bootstrap-proxy-client.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-bootstrap-proxy-client.adoc[]
endif::[]

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-generate_proxy_config.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-generate_proxy_config.adoc[]
endif::[]

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-transfer_proxy_config.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-transfer_proxy_config.adoc[]
endif::[]

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-ensure-proxy-prerequisites.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../partials/snippet-ensure-proxy-prerequisites.adoc[]
endif::[]



[[proxy-setup-containers-transfer-start]]
== Start the {productname} Proxy

Container can now be started with the [literal]`mgrpxy` command:

[[proc-setup-containers-setup-start]]
.Procedure: Starting and Checking Proxy Status
[role=procedure]
_____

. Start the proxy by calling:

+

----
mgrpxy start
----

. Check container status by calling:

+

----
mgrpxy status
----

+

Five {productname} Proxy containers should be present and should be part of the [literal]``proxy-pod`` container pod:

* proxy-salt-broker
* proxy-httpd
* proxy-tftpd
* proxy-squid
* proxy-ssh

_____


== Use a Custom Container Image for a Service

By default, the {productname} Proxy suite is configured to use the same image version and registry path for each of its services.
However, it is possible to override the default values for a specific service using the install parameters ending with [literal]``-tag`` and [literal]``-image``.

For example:

[source, shell]
----
mgrpxy install podman --httpd-tag 0.1.0 --httpd-image registry.opensuse.org/uyuni/proxy-httpd /path/to/config.tar.gz
----

It adjusts the configuration file for the httpd service, where [path]``registry.opensuse.org/uyuni/proxy-httpds`` is the image to use and [literal]``0.1.0`` is the version tag, before restarting it.

To reset the values to defaults, run the install command again without those parameters:

[source,shell]
----
mgrpxy install podman /path/to/config.tar.gz
----

This command first resets the configuration of all services to the global defaults and then reloads it.
