= {productname} Proxy Air-gapped Deployment
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

== What is air-gapped deployment?

Air-gapped deployment refers to the setup and operation of any networked system that is physically isolated from insecure networks, especially the internet.
This type of deployment is commonly used in high-security environments such as military installations, financial systems, critical infrastructure, and anywhere sensitive data is handled and must be protected from external threats.

== Deploy with Virtual Machine

The recommended installation method is using the provided {productname} Virtual Machine Image option, since all the needed tools and container images are pre-loaded and will work out of the box.

For more information about installing {productname} Proxy Virtual Machine, see xref:container-deployment/mlm/proxy-deployment-vm-mlm.adoc[Deploy Proxy as a Virtual Machine].

To upgrade {productname} Proxy, users should follow the procedures defined in xref:container-management/updating-proxy-containers.adoc[Proxy Upgrade].


== Deploy {productname} on {sl-micro}

{productname} also provides all the needed container images in RPM's that can be installed on the system.

.Procedure: Install {productname} on {sl-micro} in Air-gapped
. Install {sl-micro}.
. Bootstrap the Proxy Host OS as a Client on {productname} Server.
. Update the system.
. Install tools packages and image packages (replace $ARCH$ with the correct architecture)

+

[source,shell]
----
transactional-update pkg install mgrpxy* mgrctl* suse-manager-5.0-$ARCH$-proxy-*
----

. Reboot.

. Deploy {productname} with mgrpxy.


For more detailed information about installing {productname} Proxy on {sl-micro}, see xref:container-deployment/mlm/proxy-deployment-mlm.adoc[Deploy Proxy as a Virtual Machine].

To upgrade {productname} Proxy, users should follow the procedures defined in xref:container-management/updating-proxy-containers.adoc[Proxy Upgrade].
