= {productname} Server Air-gapped Deployment
ifeval::[{uyuni-content} == true]
:noindex:
endif::[]

== What is Air-gapped Deployment?

Air-gapped deployment refers to the setup and operation of any networked system that is physically isolated from insecure networks, especially the internet.
This type of deployment is commonly used in high-security environments such as military installations, financial systems, critical infrastructure, and anywhere sensitive data is handled and must be protected from external threats.



== Deployments

{productname} supports two deployment variants.



=== Deploy with Virtual Machine

The recommended installation method is using the provided {productname} Virtual Machine Image option, since all the needed tools and container images are pre-loaded and will work out of the box.

For more information about installing {productname} Server Virtual Machine, see xref:container-deployment/mlm/server-deployment-vm-mlm.adoc[Deploy Server as a Virtual Machine].

To upgrade {productname} Server, users should upgrade all packages in the system and follow the procedures defined in xref:container-management/updating-server-containers.adoc[Server Upgrade].


=== Deploy {productname} on {sl-micro}

{productname} also provides all the needed container images in RPM's that can be installed on the system.

[NOTE]
====
User should make the needed RPM available on the internal network. That can be done by using a second {productname} Server or an RMT server.
====

.Procedure: Install {productname} on {sl-micro} in Air-gapped
. Install {sl-micro}
. Update the system
. Install tools packages and image packages (replace $ARCH$ with the correct architecture)
+
[source,shell]
----
transactional-update pkg install mgradm* mgrctl* suse-manager-5.0-$ARCH$-server-*
----
+
. Reboot.
. Deploy {productname} with [command]``mgradm``.


For more detailed information about installing {productname} Server on {sl-micro}, see xref:container-deployment/mlm/server-deployment-mlm.adoc[Deploy Server as a Virtual Machine].

To upgrade {productname} Server, users should upgrade all packages in the system and follow the procedures defined in xref:container-management/updating-server-containers.adoc[Server Upgrade].
