[[installation-client-requirements]]
= Podporované klientské systémy

V této tabulce jsou uvedeny podporované operační systémy pro tradiční klienty a klienty Salt.

V této tabulce označuje {check}, že klienti s tímto operačním systémem jsou podporováni {suse}, a {cross} označuje, že nejsou podporováni. Označení {question} značí, že klient je posuzován a později může nebo nemusí být podporován.

[NOTE]
====
Verze operačního systému {suse} klienta a úroveň SP musí být pod obecnou podporou (normální nebo LTSS), aby platila podpora produktu {productname}. Podrobnosti o podporovaných verzích produktů viz https://www.suse.com/lifecycle. U jiných operačních systémů než {suse}, včetně {rhel}, {centos} a {oracle}, je obecně podporována pouze nejnovější dostupná verze.
====



[[mgr.supported.clients]]
[cols="1,1,1,1", options="header"]
.Podporované klientské systémy
|===

| Operační systém
| Architektura
| Tradiční klienty
| Klienty Salt

| {sle} 15
| {x86_64}, {ppc64le}, {ibmz}, ARM
| {check}
| {check}

| {sle} 12
| {x86_64}, {ppc64le}, {ibmz}, ARM
| {check}
| {check}

| {sle} 11
| {x86}, {x86_64}, {ppc64}, {ibmz}
| {check}
| {check}

| {sles}-ES 8
| {x86_64}
| {check}
| {check}

| {sles}-ES 7
| {x86_64}
| {check}
| {check}

| {sles}-ES 6
| {x86}, {x86_64}
| {check}
| {check}

| {sles} pro SAP
| {x86_64}, {ppc64le}
| {check}
| {check}

| {rhel} 8
| {x86_64}
| {cross}
| {check}

| {rhel} 7
| {x86_64}
| {check}
| {check}

| CentOS 8
| {x86_64}
| {cross}
| {check}

| CentOS 7
| {x86_64}
| {check}
| {check}

| {oracle}{nbsp}8
| {x86_64}
| {cross}
| {check}

| {oracle}{nbsp}7
| {x86_64}
| {check}
| {check}

| {opensuse} Leap 15
| {x86_64}
| {cross}
| {check}

| {ubuntu} 20.04
| {x86_64}
| {cross}
| {check}

| {ubuntu} 18.04
| {x86_64}
| {cross}
| {check}

|===

[NOTE]
====
{rhel} 6, {oracle} 6, CentOS 6, {sles}-ES 6, and {ubuntu} 16.04 končí životnost a nebudou nadále podporovány {suse} jako operační systémy klientů. SUSE Manager Client Tools (klientské nástroje Správce SUSE) však SCC stále dodává i pro tyto operační systémy.
====

Když nastavujete klientský hardware, musíte se ujistit, že máte dostatek prostředků pro operační systém a pracovní vytížení, které chcete na klientovi provádět, plus tyto doplňky pro produkt {productname}:


[[clients.hw.reqs]]
[cols="1,1", options="header"]
.Další hardwarové požadavky na klienta
|===
| Hardware               | Požadovaná další velikost
| RAM                    | 512{nbsp}MB
| Prostor na disku:    | 200{nbsp}MB
|===
