[[installation-general-requirements]]
= Obecné požadavky

Před zahájením instalace se ujistěte, že máte:

* Aktuální pověření organizace {scc}
* Přístup k instalačnímu médiu
* Prostředí splňuje hardwarové a síťové požadavky
* Jakékoli požadované certifikáty SSL pro vaše prostředí

Tato část obsahuje další informace o každém z těchto požadavků.

Úplný seznam podporovaných klientů a funkcí viz xref:client-configuration:supported-features.adoc[].


[IMPORTANT]
====
{productname} {productnumber} je založen na SLES {sles-version} {sp-version} jako hostitelském operačním systému. {productname} přichází s životním cyklem údržby dva roky. Další informace najdete na https: //www.suse.com/lifecycle/ [].

Dlouhodobou podporu Service Pack (LTSS) pro {sles-version} nelze přidat do {productname}. Také není možné použít SLES pro SAP jako základ pro {productname} ke zvýšení životního cyklu základního operačního systému.
====



[[install.scc-register]]
== Získejte pověření zákaznického centra SUSE

Před instalací {sles} a {productname} si vytvořte účet u {scc}.

[[creating.scc.account.mgr]]
.Postup: Získání pověření organizace SCC
. Ve svém webovém prohlížeči přejděte na https://scc.suse.com/login.
. Přihlaste se ke svému účtu SCC nebo podle pokynů vytvořte nový účet.
. Pokud jste tak dosud neučinili, klikněte na btn:[Connect to an Organization] (Připojit k organizaci) a zadejte nebo vyhledejte svou organizaci.
. Klikněte na btn:[Manage my Organizations] (Spravovat mé organizace) a vyberte svou organizaci ze seznamu kliknutím na název organizace.
. Klikněte na kartu btn: [Organization] (Organizace) a poté vyberte kartu btn: [Organization Credentials] (Pověření organizace).
. Zaznamenejte si své přihlašovací údaje pro použití během instalace produktu {productname}.

V závislosti na nastavení vaší organizace možná budete muset aktivovat předplatné pomocí menu btn: [Activate Subscriptions] (Aktivovat předplatné).

Další informace o použití SCC viz https://scc.suse.com/docs/help.


[[install.media]]
== Jednotný instalátor

Server a proxy {susemgr} je nainstalován Jednotným instalátorem {sle}.

ifeval::[{suma-content} == true]
Potřebujete pouze platný registrační kód pro {productname}. Pro SLES {nbsp}{sles-version} {sp-version} nepotřebujete samostatný kód.
endif::[]

Pokud ještě nemáte Jednotný instalátor, získáte ho z https://download.suse.com.

Přímý odkaz na {sle} {sles-version} {sp-version} potřebný k instalaci Správce SUSE: https://www.suse.com/download/suse-manager.

U novější verze nebo jiné architektury, například {ibmz}, vyberte příslušnou položku. Jednotným instalátorem můžete nainstalovat mnoho základních produktů založených na SLE, jako jsou SLES, SLES pro SAP nebo {susemgr}.



[[installation-general-supportedbrowsers]]
== Podporované prohlížeče pro {susemgr} {webui}

Abyste mohli ke správě svého prostředí {susemgr} používat {webui}, musíte se ujistit, že používáte aktuální webový prohlížeč.

{susemgr} podporuje:

* Nejnovější prohlížeč Firefox dodávaný se {sles}
* Nejnovější prohlížeč Chrome ve všech operačních systémech
* Nejnovější prohlížeč Edge dodávaný s Windows

Windows Internet Explorer není podporován. {productname} {webui} se nebude v prohlížeči Windows Internet Explorer správně vykreslovat.



== SSL certifikáty

{productname} používá certifikáty SSL, aby byli klienti registrováni na správném serveru. Ve výchozím nastavení používá {productname} certifikát podepsaný sám sebou. Pokud máte certifikáty podepsané certifikační autoritou třetí strany, můžete je importovat do své instalace produktu {productname}.

* Další informace o certifikátech podepsaných samy sebou najdete v dokumentu xref:administration:ssl-certs-selfsigned.adoc[].
* Další informace o importovaných certifikátech najdete na stránce xref:administration:ssl-certs-imported.adoc[].
