[[install-uyuni]]
= Instalujte server Uyuni s openSUSE

Server {productname} lze nainstalovat na openSUSE.

Požadavky najdete na xref:installation:uyuni-install-requirements.adoc[].

[NOTE]
====
Další informace o nejnovější verzi a aktualizacích openSUSE Leap najdete na https://doc.opensuse.org/release-notes/.
====



== Nainstalujte Uyuni na openSUSE Leap

.Postup: Instalace openSUSE Leap s Uyuni

. Jako základní systém nainstalujte openSUSE Leap se všemi dostupnými aktualizacemi Service Pack a aktualizacemi balíčků.
. Nakonfigurujte rozřešitelný (převoditelný na IP adresu) plně kvalifikovaný doménový název (FQDN) pomocí menu:yast[System > Network Settings > Hostname/DNS] (Systém > Nastavení sítě > Název hostitele/DNS).
. Nastavit proměnné, pro použití k vytvoření úložiště:
+
----
repo=repositories/systemsmanagement:/
repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
----
. Přidejte úložiště pro instalaci serverového softwaru {productname} jako [systemitem]``root``:
+
----
zypper ar https://download.opensuse.org/$repo uyuni-server-stable
----
. Obnovit metadata z úložišť jako [systemitem]``root``:
+
----
zypper ref
----
. Nainstalujte vzor pro server {productname} jako [systemitem]``root``:
+
----
zypper v patterns-uyuni_server
----
. Rebootujte.


* Další informace o stabilní verzi produktu {productname} najdete na adrese https://www.uyuni-project.org/pages/stable-version.html.
* Další informace o vývojové verzi {productname} najdete na adrese https://www.uyuni-project.org/pages/devel-version.html.

Po dokončení instalace můžete pokračovat v instalaci produktu {productname}. Další informace viz xref:installation:uyuni-server-setup.adoc[].
