[[install-pubcloud-requirements]]
= Požadavky na veřejný cloud

Tato sekce obsahuje požadavky na instalaci {productname} do infrastruktury veřejného cloudu. Tento návod jsme testovali na Amazon EC2, Google Compute Engine a Microsoft Azure, ale měl by s nějakými variacemi fungovat i pro jiné poskytovatele.

Několik úvah, než začnete:

* Procedura nastavení {productname} si předem zjišťuje, zda uspěje reverzní vyhledávání DNS. To musí proběhnout úspěšně, aby bylo dokončeno nastavení a aby produkt {productname} fungoval podle očekávání. Před nastavením produktu {productname} je důležité provést konfiguraci názvu hostitele a adresy IP.
* Instance serveru a proxy {productname} musí běžet v síťové konfiguraci, v níž můžete ovládat položky DNS, ale nelze k nim přistupovat z obecného internetu.
* V rámci této konfigurace sítě musí být poskytnuto rozlišení DNS: `hostname -f` musí vrátit plně kvalifikovaný doménový název (FQDN).
* Rozřešení DNS je také důležité pro připojení klientů.
* DNS závisí na Vámi zvoleném cloudovém rámci. Podrobné pokyny najdete v dokumentaci poskytovatele cloudu.
* Doporučujeme vyhledat úložiště softwaru, databázi serveru a mezipaměť proxy squid na externím virtuálním disku. To zabrání ztrátě dat, pokud je instance neočekávaně ukončena. Tato část obsahuje pokyny pro nastavení externího virtuálního disku.


[NOTE]
====
Pokoušíte-li se zavést tradiční klienty, zkontrolujte, zda můžete při přihlášení ke klientovi vyřešit název hostitele serveru. Možná budete muset přidat plně kvalifikovaný název domény serveru do souboru lokálního řešení [cesta]``/etc/hosts`` v klientovi. Zkontrolujte to příkazem [command]``název hostitele -f`` s místní IP adresou serveru.
====



== Požadavky na síť

Když používáte {productname} na veřejném cloudu, musíte použít neveřejnou síť. Doporučujeme použít soukromou podsíť VPC s příslušným nastavením brány firewall. K instanci musí mít přístup pouze stroje ve vašich zadaných rozsazích IP adres.

[WARNING]
====
Když spustíte {productname} na veřejných cloudech, musíte omezit přístup k instanci pomocí bezpečnostních opatření. Světově dostupná instance {productname} porušuje podmínky smlouvy EULA {productname} a {suse} ji nepodporuje.
====

Chcete-li získat přístup k {productname} {webui}, povolte HTTPS při konfiguraci řízení přístupu k síti. To Vám umožní dostat se k {productname} {webui}.

V EC2 a Azure vytvořte novou skupinu zabezpečení a přidejte příchozí a odchozí pravidla pro HTTPS. V GCE zkontrolujte možnost ``Allow HTTPS traffic`` v sekci ``Firewall``.



== Připravte svazky úložiště

Doporučujeme, aby úložiště a databáze produktu {productname} byly uloženy na samostatných paměťových zařízeních do kořenového svazku. To pomůže vyhnout se ztrátě dat. Nepoužívejte správu logických svazků (LVM) pro veřejné cloudové instalace.

Před vlastní instalací YaST {productname} musíte nastavit paměťová zařízení.

Velikost disku pro paměti úložišť závisí na počtu distribucí a kanálů, které chcete spravovat v {productname}. Když připojíte virtuální disky, zobrazí se ve vaší instanci jako uzly zařízení Unix. Názvy uzlů zařízení se budou lišit v závislosti na poskytovateli a vybraném typu instance.

Ujistěte se, že kořenový svazek serveru {productname} je aspoň 100{nbsp}GB. Přidejte další úložný disk aspoň 500{nbsp}GB a zvolte pokud možno SSD. Cloudové obrazy {productname} Serveru používají skript pro přiřazení tohoto samostatného svazku při spouštění Vaší instance.

Po spuštění své instance se můžete přihlásit k {productname} Serveru a vyhledat všechna dostupná úložná zařízení příkazem:

----
hwinfo --disk | grep -E "Device File:"
----

Pokud si nejste jisti, které zařízení zvolíte, použijte příkaz [command]``lsblk`` pro zobrazení názvu a velikosti každého zařízení. Vyberte název, který odpovídá velikosti virtuálního disku, který hledáte.

Externí disk nastavíte příkazem [command]``suma-storage``. Tím se vytvoří oddíl XFS připojený k ``/manager_storage`` a použije se pro umístění databáze a úložišť:

----
/usr/bin/suma-storage <název_zařízení>
----

Další údaje o nastavení paměťových svazků a jejich oddílů, včetně doporučených minimálních velikostí, najdete v dokumentu xref:installation:hardware-requirements.adoc[].
