[[setup-wizard]]
= Průvodce nastavením

Po dokončení instalace produktu {productname} můžete použít průvodce nastavením k dokončení posledních několika kroků. Průvodce nastavením umožňuje konfigurovat proxy HTTP, pověření organizace a produkty {suse}.

Průvodce nastavením se ve výchozím nastavení zobrazí při prvním přihlášení k {productname} {webui}. K průvodci nastavením můžete přejít přímo z menu:Admin[Setup Wizard] (Správce [Průvodce nastavením]).



== Nakonfigurujte HTTP Proxy

{productname} se může připojit k {scc} (SCC) nebo jiným vzdáleným serverům pomocí proxy. Přejděte na kartu [guimenu]``HTTP Proxy`` a nakonfigurujte proxy.

Budete muset zadat název hostitele serveru proxy. Použijte syntaxi ``<hostname>:<port>``. Například: ``<priklad.com>:8080``.

Vymazáním polí můžete zakázat použití serveru proxy.


[IMPORTANT]
====
Při výběru uživatelského jména nebo hesla pro váš server {productname} se ujistěte, že neobsahuje znak ``@`` nebo ``:``. Tyto znaky jsou vyhrazeny.
====



== Konfigurace pověření organizace

Váš účet {scc} je přidružen k účtu správy vaší organizace. Svůj přístup {scc} můžete sdílet s ostatními uživateli ve vaší organizaci. Přejděte na kartu [guimenu]``Organization Credentials`` (Pověření organizace) a udělte uživatelům ve vaší organizaci přístup k vašemu účtu {scc}.

Stiskněte btn:[Add a new credential] (Přidat nové pověření), zadejte uživatelské jméno a heslo uživatele, kterému chcete udělit přístup, a stiskněte btn:[Save] (Uložit). U uživatele, kterému jste udělili přístup, se zobrazí nová přihlašovací karta. Pomocí těchto tlačítek na kartě můžete upravit nebo zrušit přístup:

* Zkontrolujte stav ověření pověření (ikona zeleného zaškrtnutí nebo červeného křížku).
    Chcete-li znovu zkontrolovat pověření u SCC, klikněte na ikonu.
* Nastavte primární pověření pro synchronizaci mezi servery (ikona žluté hvězdičky).
* Ukázat seznam předplatných souvisejících s určitým pověřením (ikona seznamu).
* Upravit pověření (ikona tužky).
* Odstranit pověření (ikona koše).



== Konfigurovat produkty


Vaše předplatné {suse} vás opravňuje k přístupu k řadě produktů. Přejděte na kartu [guimenu]``Produkty`` a procházejte produkty, které máte k dispozici, a synchronizujte {productname} s {scc}.

Filtry vám pomohou vyhledat produkty podle popisu nebo architektury.

Seznam je uspořádán podle názvu produktu. U každého produktu můžete vidět architekturu, na které lze použít. Kliknutím na šipku vedle názvu produktu zobrazíte přidružené kanály a rozšíření. Kliknutím na ikonu btn:[Channels] (Kanály) zobrazíte kompletní seznam kanálů přidružených ke každému produktu.

U produktů založených na {sle}{nbsp}15 a vyšších můžete zvolit synchronizaci pouze požadovaných balíčků nebo zahrnutí také doporučených produktů. Přepnutím přepínače btn:[include recommended] (zahrnout doporučené) synchronizujete všechny produkty a přepnutím přepínače synchronizujete pouze požadované produkty.

Výběrem nebo zrušením výběru jednotlivých produktů můžete dále upřesnit, které produkty chcete synchronizovat.

Po dokončení výběru klepněte na btn:[Add products] (Přidat produkty) a klepněte na btn:[Refresh] (Obnovit), abyste naplánovali synchronizaci.

Průběh synchronizace pro každý produkt se zobrazuje v liště postupu vedle názvu produktu. V závislosti na produktech, které jste si vybrali, může synchronizace trvat až několik hodin. Až bude synchronizace dokončena, v {productname} budete moci používat nové produkty.

Selže-li Vaše synchronizace, může to být kvůli GPG klíči třetí strany. Další informace o řešení potíží se synchronizací produktu najdete v xref:administration:tshoot-sync.adoc[].
