[[webui-setup]]
= Nastavení webového rozhraní

Chcete-li použít {productname} {webui}, přejděte v prohlížeči na URL adresu {productname}. Přihlaste se k {webui} účtem správy {productname}.

Když jste ve {webui}, kliknutím ikony icon:question-circle[role="blue"] otevřete dokumentaci pro příslušnou sekci.

Při prvním přihlášení na {webui} dokončíte průvodce nastavením uživatelských preferencí. Průvodce nastavením můžete kdykoli otevřít v menu:Admin[Setup Wizard] (Správce[Průvodce nastavením]).

Je-li počáteční nastavení dokončeno (a při dalším přihlášení ihned), přejdete do menu:Home[Overview] (Domů[Přehled]). Tato část obsahuje souhrnná podokna (panely), která podávají důležité informace o vašich systémech.

Panel [guimenu]``Tasks`` (Úkoly) obsahuje zástupce nejběžnějších úkolů {webui}.

Podokno [guimenu]``Inactive Systems`` (Neaktivní systémy) zobrazuje všechny klienty, kteří se přestali přihlašovat na server {productname}. Budete muset tyto klienty zkontrolovat.

Panel [guimenu]``Most Critical Systems`` (Nejkritičtější systémy) zobrazuje všechny klienty, kteří vyžadují aktualizace softwaru. Kliknutím na název klienta v seznamu přejdete do menu:Systems[System Details] (Systémy[Podrobnosti]) pro daný klient. Na této stránce můžete použít všechny požadované aktualizace.

Podokno [guimenu]``Recently Scheduled Actions`` (Naposledy naplánované akce) zobrazuje všechny poslední spuštěné akce a jejich stav. Kliknutím na štítek akce zobrazíte další podrobnosti.

Podokno [guimenu]``Relevant Security Patches`` (Související bezpečnostní opravy) zobrazuje všechny dostupné opravy zabezpečení, které je třeba na klienty použít. Je nezbytné, abyste co nejdříve použili bezpečnostní záplaty a zajistili tak bezpečnost svých klientů.

Panel [guimenu]``System Groups`` (Skupiny systému) zobrazuje všechny skupiny systému, které jste pro něj vytvořili, a zda jsou klienty v těchto skupinách plně aktualizovány.

Panel [guimenu]``Recently Registered Systems`` (Nedávno registrované systémy) zobrazuje všechny klienty registrované za posledních třicet dní. Kliknutím na jméno klienta v seznamu přejdete do menu:Systems[System Details] (Systémy[Podrobnosti]) daného klienta.



== Navigace ve webovém rozhraní


{productname} {webui} používá některé standardní prvky jako pomoc při navigaci. Používáte-li {webui}, kliknutím na ikonu icon:question-circle[role="blue"] otevřete dokumentaci pro příslušnou sekci.



=== Horní navigační lišta

Horní navigační lišta umožňuje přístup k funkcím platným pro celý systém.

Oznámení::
Ikona zvonku upozornění zobrazuje v kruhu počet nepřečtených upozornění. Klepnutím na ikonu upozornění přejděte do menu:Home[Notification Messages] (Domů [Oznámení]).

Přehled - popis::
Kliknutím na ikonu oka zobrazíte běžně používané ikony pro právě aktivní sekci {webui}.

Vyhledávání::
Kliknutím na ikonu lupy otevřete vyhledávací pole. Můžete vyhledávat systémy (klienty), balíčky, opravy nebo dokumentaci. Stisknutím btn:[Search] (Hledat) přejděte na příslušnou stránku [guimenu]``Advanced Search`` (Rozšířené vyhledávání) a zobrazte si výsledky hledání.

Vybrané systémy::
Ikona vybraných systémů zobrazuje v kruhu počet aktuálně vybraných systémů. Kliknutím na ikonu vybraných systémů přejděte do menu:Systems[System Set Manager > Overview] (Systémy [Správce sady systémů> Přehled]). Kliknutím na ikonu mazací gumy zrušíte výběr všech systémů. Další informace o správci systémové sady viz xref:client-configuration:system-set-manager.adoc[].

Uživatelský účet::
Zobrazí se ikona uživatelského účtu se jménem aktuálně přihlášeného uživatele. Kliknutím na ikonu uživatelského účtu přejděte do menu:Home[User Account > My Account] (Domů[Uživatelský účet> Můj účet]).

Organizace::
Zobrazí se ikona organizace s názvem aktuálně aktivní organizace. Kliknutím na ikonu organizace přejděte do menu:Home[My Organization > Configuration] (Domů[Moje organizace> Konfigurace]).

Předvolby::
Kliknutím na ikonu ozubených kol přejdete do menu:Home[My Preferences] (Domů[Moje předvolby]).

Odhlásit se::
Kliknutím na ikonu ukončení odhlásíte aktuálního uživatele a vrátíte se na přihlašovací obrazovku.


[NOTE]
====
Přidáte-li distribuci, nově synchronizujete kanály nebo zaregistrujete systém u {productname} Serveru, může trvat několik minut, než bude indexován a zobrazen ve výsledcích vyhledávání. Potřebujete-li vynutit nové sestavení vyhledávacího indexu, zadejte na příkazovém řádku tento příkaz:

----
rhn-search cleanindex
----
====



=== Levá navigační lišta

Levá navigační lišta je hlavní menu {productname} {webui}.

Rozšířit::
Když kliknete na ikonu nebo na šipku dolů u položky menu, rozšíří se tato část stromu menu, ale nenačte se stránka.

Sbalení::
Chcete-li sbalit otevřenou část systému nabídek, klikněte na šipku nahoru u položky nabídky.

Automatické zavedení::
Kliknete-li na název položky menu, automaticky se načte a zobrazí první dostupná stránka této položky menu.

Vyhledávání::
Zadejte vyhledávací řetězec do pole [guimenu]``Search page`` (Stránka hledání), abyste našli položku ve stromu menu. Dostupné položky menu závisí na rolích uživatele.

[IMPORTANT]
====
Do těchto sekcí mají přístup pouze správci {productname}:

* [guimenu]``Images`` (Obrazy)
* [guimenu]``Users`` (Uživatelé)
* [guimenu]``Admin`` (Správce)
====



=== Tabulky

Mnoho sekcí uvádí informace v tabulkách. Většinu tabulek můžete procházet kliknutím na šipky "zpět" a "vpřed", umístěné nad a pod pravou stranou tabulky. Výchozí počet položek zobrazených na každé stránce můžete změnit v menu:Home[My Preferences] (Domů[Moje předvolby]).

Obsah ve většině tabulek můžete filtrovat pomocí vyhledávacího panelu v horní části tabulky. Položky tabulky seřadíte kliknutím na záhlaví sloupce, podle kterého chcete seřadit. Opětovným kliknutím na záhlaví sloupce řazení obrátíte.



=== Ikony upozornění na opravu

Opravy jsou reprezentovány třemi hlavními ikonami, v závislosti na typu opravy. Ikony jsou podle závažnosti opravy zbarveny buď zeleně, žlutě nebo červeně.

icon:shield-alt[role="none"] Ikona štítu je bezpečnostní varování. Červený štít je bezpečnostní upozornění s nejvyšší prioritou.

icon:bug[role="none"] Ikona brouka je upozornění na opravu chyby.

image:spacewalk-icon-enhancement.svg[Enhancement Alert,scaledwidth=1.4em] Ikona čtverců je upozornění na vylepšení.

Některé další ikony se používají k poskytnutí dalších informací:

icon:sync[role="none"] Ikona šipek v kruhu naznačuje, že aplikace opravy bude vyžadovat restart.

icon:archive[role="none"] Ikona archivní krabice označuje, že oprava bude mít vliv na správu balíčků.



=== Přizpůsobení rozhraní

{scc} (SCC) udržuje sbírku úložišť, která obsahují balíčky, software a aktualizace pro všechny podporované podnikové klientské systémy. Tato úložiště jsou uspořádána do kanálů, z nichž každý poskytuje software specifický pro distribuci, vydání a architekturu. Po synchronizaci se SCC mohou klienti dostávat aktualizace, být rozděleni do skupin a přiřazeni ke konkrétním softwarovým kanálům produktu.

Informace o změně výchozího motivu viz xref:administration:users.adoc[].



=== Hodnota časového limitu požadavku

Používáte-li {webui}, odesíláte žádosti na {productname} Server. V některých případech mohou tyto požadavky trvat dlouho nebo zcela selhat. Ve výchozím nastavení vyprší časový limit požadavků po 30 sekundách a na {webui} se zobrazí zpráva s odkazem na opětovné odeslání požadavku.

Výchozí hodnotu časového limitu můžete změnit v konfiguračním souboru ``etc/rhn/rhn.conf`` úpravou parametru ``web.spa.timeout``. Po změně tohoto parametru restartujte službu tomcat. Změna tohoto nastavení na vyšší číslo by mohla být užitečná, máte-li pomalé připojení k internetu nebo provádíte-li pravidelné akce na mnoha klientech najednou.
