= Distribution Upgrade and Server Migration from 5.0 to 5.2
:revdate: 2026-02-09
:page-revdate: {revdate}


[IMPORTANT]
====
* 升级前必须停止 {productname} 5.0。
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::installation-and-upgrade:partial$snippet-ssl-requirements.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::../../../../../partials/snippet-ssl-requirements.adoc[leveloffset=+1]
endif::[]

迁移过程中，会从源服务器复制服务器 SSL 证书和 CA 链，这意味着您只需准备数据库证书即可

[NOTE]
====
{productname} 5.0 peripheral servers are always using third-party SSL certificates. If the hub server has generated the certificates for the peripheral server, it needs to generate the certificate for the peripheral database too.

On the hub server, run the following command for each of the peripheral server to migrate.

[source, shell]
----
mgrctl exec -ti -- rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="COUNTRY" \
  --set-state="STATE" --set-city="CITY" --set-org="ORGANIZATION" \
  --set-org-unit="ORGANIZATION UNIT" --set-email="name@example.com" \
  --set-hostname=<hostname>-reportdb --set-cname="example.com" --set-cname=db --set-cname=reportdb
----

要使用的文件位于服务器容器内，需要复制到新的外围服务器主机上：

. [litteral]``/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT``（作为根 CA 证书）
. [litteral]``/root/ssl-build/<hostname>-reportdb/server.crt`` as the db certificate and
. [litteral]``/root/ssl-build/<hostname>-reportdb/server.key`` as the db certificate's key.
====


== {sle-micro} 5.5 to {sl-micro} 6.2



This document provides the tested procedure to upgrade a {sle-micro} 5.5 host deployed with {productname} 5.0 Server to {sl-micro} 6.2 and migrate to {productname} {productnumber}.


=== 先决条件

* {productname} 5.0 已在 {sle-micro} 5.5 上安装并运行。
* 系统已注册到 {scc} 且拥有有效的订阅。


=== 发行套件升级和服务器迁移

.过程：从 {productname} 5.0 迁移到 {productname} {productnumber}
[role=procedure]
____

. 校验当前产品状态。

+

[source, console]
----
SUSEConnect --status-text
----

+

确认以下信息：

* 基础操作系统：`SUSE Linux Enterprise Micro 5.5`
* 扩展：`SUSE Manager Server 5.0 Extension`

+

. 确保系统已更新。

+

[source, console]
----
transactional-update patch
----

+

--

* 如果已应用补丁，请在继续迁移前停止服务器，然后重引导系统：

+

[source, console]
----
mgradm stop
reboot
----

* 如果未发现更新，可直接进入迁移步骤。

--

+

. 启动迁移流程。

+

[source, console]
----
transactional-update migration --auto-agree-with-licenses --gpg-auto-import-keys
----

+

Follow the prompts and select the available migration to **SUSE Linux Micro 6.2** and **{productname} Server Extension {productnumber}**.

+

. 停止服务器后重引导，使更改生效。

+

[source, console]
----
mgradm stop
reboot
----

+

. 执行重引导后的检查。

+

Verify {productname} extension and {productname} version:

+

[source, console]
----
SUSEConnect --status-text
mgradm --version
----

+

预期输出：

* Extension: [literal]``SUSE Multi-Linux Manager Server {productnumber} Extension``
* Version: referencing [literal]``5.2.0`` or higher

+

. Verify PostgreSQL database version.

+

[source, console]
----
podman ps
----

+

预期输出：

* [literal]``server:5.2.0`` or higher
* [literal]``server-postgresql:5.2.0`` or higher

+

. Verify running containers:

+

[source, console]
----
podman ps
----

+

You should see all the expected server containers are up and running.

____


=== 迁移完成

The server host system is now running {sl-micro} 6.2 with updated {productname} {productnumber} Server packages.

If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-52.adoc[Proxy Migration 5.0 > 5.2] guide to upgrade the proxy host.

Validate your setup before resuming production operations.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]


== 从 {sles} 15 SP6 升级到 15 SP7

This document provides the procedure to upgrade a {sles} 15 SP6 host deployed with {productname} 5.0 Server to {sles} 15 SP7 and migrate to {productname} {productnumber}.


=== 先决条件

* {productname} 5.0 is installed and running on {sles} 15 SP6.
* 系统已注册到 {scc} 且拥有有效的订阅。


=== 发行套件升级和服务器迁移

.Procedure: Upgrade and Migrate {productname} on {sles} 15 SP6
[role=procedure]
____

. 校验当前产品状态。

+

[source, console]
----
SUSEConnect --status-text
----

+

确认以下信息：

* Base OS: `SUSE Linux Enterprise Server 15 SP6`
* 扩展：`SUSE Manager Server 5.0 Extension`

+

. 确保系统已更新。

+

[source, console]
----
zypper patch
----

+

If patches were applied, stop the server and then reboot before proceeding:

+

[source, console]
----
mgradm stop
reboot
----

+

. Perform the migration to SP7 and {productname} {productnumber}.

+

[source, console]
----
zypper migration
----

+

Select to migrate to:

* `{sles} 15 SP7`
* `{productname} Server Extension {productnumber}`

+

. Stop the server and reboot.

+

[source, console]
----
mgradm stop
reboot
----

+

. 执行重引导后的检查。

+

Verify {productname} extension:

+

[source, console]
----
SUSEConnect --status-text
----

+

预期输出：

* Extension: [literal]``SUSE Multi-Linux Manager Server {productnumber} Extension``

+

. Verify {productname} version.

+

[source, console]
----
mgradm --version
----

+

预期输出：

* Version: referencing [literal]``5.2.0`` or higher

+

. Verify containers:

+

[source, console]
----
podman ps
----

+

预期输出：

* [literal]``server:5.2.0`` or higher
* [literal]``server-postgresql:5.2.0`` or higher

____


=== 迁移完成

The server host system is now running {sles} 15 SP7 with updated {productname} {productnumber} Server packages.

If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-52.adoc[Proxy Migration 5.0 > 5.2] guide to upgrade the proxy host.

Validate your setup before resuming production operations.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]
