[[uyuni-install-requirements]]
= Requirements

The following table specifies the minimum requirements.
// In this table, replace ``version`` with the version of the product you are using.

[cols="1,1", options="header"]
.Software and Hardware Requirements
|===
| Software and Hardware  | Recommended
| Operating System:      | openSUSE Leap 15.2: Clean installation, up-to-date
| CPU:                   | Minimum 4 dedicated 64-bit CPU cores ({x86_64})
| RAM:                   | _Test Server_ Minimum 8{nbsp}GB
|                        | _Base Installation_ Minimum 16{nbsp}GB
|                        | _Production Server_ Minimum 32{nbsp}GB
| Disk Space:            | Disk space depends on your channel requirements, at least 100 GB
|                        | 50 GB per SUSE or openSUSE product and 360 GB per Red Hat product
| Swap space:            | 3{nbsp}GB
|===



////
HTML content from https://github.com/uyuni-project/uyuni-project.github.io/blob/master/pages/stable-version.html
--LKB 2021-01-05

  <h4><a href="#serversetup">Server Setup</a></h4>
            <div class="subpage-content-push-right">
            </br>
            <h5>Hardware and Software Requirements</h5>
                <!-- STRUCTURE EXAMPLE START -->

                <table class="table table-bordered  table-hover table-sm">
                    <thead class="table-primary">
                    <tr>

                        <th scope="col">Requirement</th>
                        <th scope="col">Description</th>

                    </tr>
                    </thead>
                    <tbody >
                    <tr>

                        <td>openSUSE Leap 15.2</td>
                        <td>Clean installation, up-to-date</td>

                    </tr>
                    <tr>

                        <td>Multi-core CPU</td>
                        <td>x86_64</td>

                    </tr>

                    <tr>

                        <td>8GB RAM <strong>*</strong></td>
                        <td>Sufficient for testing purposes</td>

                    </tr>

                    <tr>

                        <td >100GB Disk Space <strong>**</strong></td>
                        <td>Disk space depends on your channel requirements</td>

                    </tr>

                    </tbody>
                </table>

                <p>* <i>32GB of RAM recommended for a production environment (16GB for a base installation)</i></p>
                <p>**<i>50GB per SUSE/openSUSE product and 360GB per Red Hat Product</i></p>

                </br>
                <h5>Quickstart Installation Instructions</h5>

                <p>Please note Uyuni requires FQDNs for the Server, Proxy and clients, so usage of a properly-configured DNS server is mandatory for client updates to work.</p>
                <p>If you want to install Uyuni in lab mode, for testing, you may be interested in how to easily make use of libvirt's included dnsmasq DNS and DHCP server: <a href="https://github.com/uyuni-project/uyuni/wiki/Libvirt-DNS-and-DHCP-without-Avahi">Libvirt DNS and DCHP without Avahi</a>.</p>

                <p>1. Update openSUSE Leap 15.2:</p>
                <code>$ sudo zypper update</code>

                <p>2. Configure a resolvable fully quallified domain name with <strong>Yast2 > System > Netwok Settings > Hostname/DNS</strong></p>

                <p>3. Add the repository for the server:</p>
                <code>$ sudo zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/ uyuni-server-stable</code>

                <p>4. Refresh metadata from the repositories:</p>
                <code>$ sudo zypper ref</code>

                <p>5. Install the pattern for the Uyuni server:</p>
                <code>$ sudo zypper in patterns-uyuni_server</code>

                <p>6. Run <strong>Yast2</strong> and navigate to <strong>Network Services > Uyuni Setup</strong></p>

                <p>7. Follow the setup assistant</p>

                Once the setup assistant is ready, you will be able to access the WebUI at <code>https://&lt;FQDN>/</code>

                <p>From that point you can start working with the Uyuni Server.</p>

                <!-- STRUCTURE EXAMPLE END -->

            </div>

            <h4><a href="#proxysetup">Proxy Setup</a></h4>
            <div class="subpage-content-push-right">
            </br>
            <h5>Hardware and Software Requirements</h5>
                <!-- STRUCTURE EXAMPLE START -->

                <table class="table table-bordered  table-hover table-sm">
                    <thead class="table-primary">
                    <tr>

                        <th scope="col">Requirement</th>
                        <th scope="col">Description</th>

                    </tr>
                    </thead>
                    <tbody >
                    <tr>

                        <td>openSUSE Leap 15.2</td>
                        <td>Clean installation, up-to-date</td>

                    </tr>
                    <tr>

                        <td>Multi-core CPU</td>
                        <td>x86_64</td>

                    </tr>

                    <tr>

                        <td>2GB RAM <strong>*</strong></td>
                        <td>Minimum for testing and production</td>

                    </tr>

                    <tr>

                        <td >50GB Disk Space <strong>**</strong></td>
                        <td>Disk space depends on your channel requirements</td>

                    </tr>

                    </tbody>
                </table>
                <p>**<i>50GB per SUSE/openSUSE product and 360GB per Red Hat Product to be mirrored by the proxy</i></p>

                </br>
////
