[[install-uyuni]]
= Install Uyuni Server with openSUSE

{productname} Server can be installed on openSUSE.

For requirements, see xref:installation:uyuni-install-requirements.adoc[].

[NOTE]
====
For more information about the latest version and updates of openSUSE Leap, see https://doc.opensuse.org/release-notes/.
====



== Install Uyuni on openSUSE Leap

.Procedure: Installing openSUSE Leap with Uyuni

. As the base system, install openSUSE Leap with all available service packs and package updates applied.
. Configure a resolvable fully qualified domain name (FQDN) with menu:yast[System > Network Settings > Hostname/DNS].
. Set variables to use to create repository:
+
----
repo=repositories/systemsmanagement:/
repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
----
. Add the repository for installing the {productname} Server software as [systemitem]``root``:
+
----
zypper ar https://download.opensuse.org/$repo uyuni-server-stable
----
. Refresh metadata from the repositories as [systemitem]``root``:
+
----
zypper ref
----
. Install the pattern for the {productname} Server as [systemitem]``root``:
+
----
zypper in patterns-uyuni_server
----
. Reboot.


* For more information about the stable version of {productname}, see https://www.uyuni-project.org/pages/stable-version.html.
* For more information about the development version of {productname}, see https://www.uyuni-project.org/pages/devel-version.html.

When the installation is complete, you can continue with {productname} setup.
For more information, see xref:installation:uyuni-server-setup.adoc[].


////
HTML content from https://github.com/uyuni-project/uyuni-project.github.io/blob/master/pages/stable-version.html
--LKB 2021-01-05

                <h5>Quickstart Installation Instructions</h5>

                <p>Installation of Uyuni Proxy is done via the Uyuni Server web interface.</p>
                <p>See the <strong>Installation Guide</strong> for step-by-step instructions for installing and configuring Uyuni Proxy.</p>
                <p>The repository for the Proxy is <a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Proxy-POOL-x86_64-Media1/">https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Proxy-POOL-x86_64-Media1/</a>

            </div>
            <!-- end subpage-content-push -->

            <h4>Client Tools</h4>
            <div class="subpage-content-push-right">
            </br>
            <p>Each supported Operating System has a repository, for all supported architectures:</p>
            <ul>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/">openSUSE Leap 15.* (x86_64)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/SLE12-Uyuni-Client-Tools/SLE_12/">SLE12 (x86_64, pcc64le. s390x, aarch64)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/SLE15-Uyuni-Client-Tools/SLE_15/">SLE15 (x86_64, pcc64le. s390x, aarch64)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/">RHEL, CentOS, Oracle Linux and SLES ES 6 (i686, x86_64)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/">RHEL, CentOS, Oracle Linux and SLES ES 7 (x86_64, ppc64le)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS8-Uyuni-Client-Tools/CentOS_8/">RHEL, CentOS, Oracle Linux and SLES ES 8 (x86_64, ppc64le)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1604-Uyuni-Client-Tools/xUbuntu_16.04/">Ubuntu 16.04 (x86_64)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/">Ubuntu 18.04 (x86_64)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/xUbuntu_20.04/">Ubuntu 20.04 (x86_64)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Debian9-Uyuni-Client-Tools/Debian_9/">Debian 9 (x86_64, aarch64, armv7l, i586)</a></li>
                <li><a href="https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Debian10-Uyuni-Client-Tools/Debian_10/">Debian 10 (x86_64, aarch64, armv7l, i586)</a></li>
            <ul>
            </div>

            <h4>Reporting Bugs</h4>
            <p> Submit bugs to the issues tab located at our <a href="https://github.com/uyuni-project/uyuni/issues">Github repository</a>.</p>

            <div class="alert alert-warning" role="alert">
                Verify that a duplicate of the issue does not already exist! </div>

        </div>

////