[[install-vm-vmware]]
= {productname} {productnumber}サーバの仮想マシンとしての配備 - VMware
:revdate: 2025-07-09
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

この章では、{productname} {productnumber} をイメージとして配備するために必要な仮想マシン設定について説明します。このインストールでは、VMwareをサンドボックスとして使用します。


// FIXME: make this and later sections a snippet or move it to a general
//        intro for both, KVM and VMware
== 利用可能なイメージ


[IMPORTANT]
====
{productname} {productnumber}サーバを配備する際に推奨される方法は、利用可能な次のイメージの1つを使用することです。これらのイメージにはすべてのツールが含まれており、配備が大幅に容易になります。
====

{productname} {productnumber}のイメージはlink:https://www.suse.com/download/suse-manager/[{productname} {productnumber} VM images]で入手できます。

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-warn-images-sl-micro.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-warn-images-sl-micro.adoc[]
endif::[]

[NOTE]
====
生イメージの準備の詳細については、link:https://documentation.suse.com/sle-micro/6.1/html/Micro-deployment-raw-images-virtual-machines/index.html#deployment-preparing-configuration-device[]を参照してください。
// For the 5.0 backport:
// For more information on preparing raw images, see link:https://documentation.suse.com/en-us/sle-micro/5.5/single-html/SLE-Micro-deployment/#sec-raw-preparation[].

セルフインストールイメージの詳細については、link:https://documentation.suse.com/sle-micro/6.1/html/Micro-deployment-selfinstall-images/index.html[]を参照してください。
====

.利用可能なサーバイメージ
[cols="3, 3", options="header"]
|===
| アーキテクチャ | イメージの形式

| aarch64| qcow2、vmdk

| x86_64  | qcow2、vmdk、raw、セルフインストーラ

| ppc64le | raw、セルフインストーラ

| s390x * | qcow2、raw
|===

__* s390xでは、CDL DASDとFBAの2つのストレージオプションが利用可能です。__





[[quickstart.sect.vmware.settings]]
== {productname} 仮想マシン設定 - VMware

このセクションでは、VMware環境内の{productname}ストレージパーティションに不可欠な追加の仮想ディスクの作成に重点を置いて、 VMware設定について説明します。

.プロシージャ: VMware仮想マシンを作成する

. {productname} Server [filename]``.vmdk``ファイルをダウンロードし、コピーをVMwareストレージに移動します。

. VMware Webインタフェースを使用して、アップロードされた[filename]``.vmdk``ファイルのコピーを作成します。 これにより、提供された[filename]``.vmdk``ファイルがvSphereハイパーバイザーに適した形式に変換されます。

. ゲストOSファミリ[systemitem]``Linux``およびゲストOSバージョン{sle} 15 (64ビット)に基づいて、新しい仮想マシンを作成し、名前を付けます。

+

. 500GB以上の[systemitem]``Hard Disk 2``を追加します。

. RAMおよびCPU数を最小値で設定します。*)

. 必要に応じてネットワークアダプタを設定します。

. VMの電源を入れ、firstbootダイアログ(キーボードレイアウト、ライセンス契約、タイムゾーン、rootのパスワード)に従います。

. インストールが完了したら、rootとしてログインします。

. 次のセクションに進みます。

*) 最小値については、xref:installation-and-upgrade:hardware-requirements.adoc#proxy-hardware-requirements[]を参照してください。


[[minimal.susemgr.prep]]
== {sl-micro}および{productname} {productnumber}サーバの登録

開始する前に、{scclongform} (link:https://scc.suse.com[])から{productname}登録コードを入手してください。

[NOTE]
====
{sl-micro} {microversion}エンタイトルメントは、{productname}エンタイトルメント内に含まれているため、別途登録コードは必要ありません。
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
endif::[]

.プロシージャ: {sl-micro}および{productname} {productnumber}を登録する
. 仮想マシンをブートします。
. ``root``としてログインします。
. {scc}で{sl-micro}を登録します。
+

----
transactional-update register -r <REGCODE> -e <your_email>
----

. 再起動します。

. {scclongform}で{productname} {productnumber}を登録します。
+

----
transactional-update register -p Multi-Linux-Manager-Server/5.1/x86_64 -r <REGCODE>
----

. 再起動
. システムを更新します。
+

----
transactional-update
----

. 更新が適用されていた場合は再起動します。

. このステップはオプションです。ただし、ご使用のインフラストラクチャでカスタム永続ストレージが必要な場合は、[command]``mgr-storage-server``ツールを使用します。

+

詳細については、[command]``mgr-storage-server --help``を参照してください。このツールを使用すると、コンテナストレージとデータベースボリュームの作成が容易になります。次のようにコマンドを使用します。

+

----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----

+
例:
+

----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----

+
[NOTE]
====
このコマンドは、[path]``/var/lib/containers/storage/volumes``に永続ストレージを作成します。

詳細については、以下を参照してください。

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-step-deploy-podman-certs.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-step-deploy-podman-certs.adoc[]
endif::[]
