[[ref-config-overview]]
= Configuration Overview

The menu:Configuration[Overview] section is a dashboard that contains a summary of the configuration files that are managed by your organization in {productname}.
There are different panes listing files that are managed centrally in configuration channels and files that are managed locally with individual system profiles.

For more information about managing configuration files, see xref:client-configuration:configuration-management.adoc[].

Configuration Summary::
Provides quick information about your configuration files.
Click the blue text to the right to display:
+
* Systems with managed configuration files
* Configuration channels
* Centrally managed configuration files
* Locally managed configuration files


Configuration Actions::
[guimenu]``Configuration Actions`` offers direct access to the most common configuration management tasks:
+
* View clients with managed configuration files
* View all managed configuration files
* View all managed configuration channels
* Create a new configuration channel
* Enable configuration management on clients


Recently Modified Configuration Files::
The list shows which files have changed when and to which channel they belong.
If no files have been changed, no list appears.
+
////
Filename	Configuration Channel	Modified
/etc/jabberd/sm.xml 	rhn_proxy_config_1000010000 	19 weeks ago
/etc/jabberd/c2s.xml 	rhn_proxy_config_1000010000 	19 weeks ago
////
+
[[config-recentfiles-list-columns]]
[cols="1,1", options="header"]
.Recently Modified Configuration Files Columns
|===
| Column               | Description
| Filename 	       | Absolute filename of the configuration file.
| Configuration Channel | Name of the configuration channel.
| Modified              | The time and date the file was modified.
|===
+
Click the name of a file to see its [guimenu]``Details`` page.
Click the channel name to see its [guimenu]``Channel Details`` page.

Recently Scheduled Configuration File Deployments::
Each scheduled action is listed along with the status of the action.
Any scheduled configuration task, from enabling configuration management on a system to deploying a specific configuration file, is displayed.
Here you can quickly assess if all tasks have been successfully carried out or fix any problems.
+
// FIXME: add missing status variants
+
[[config-scheduledfiles-list-columns]]
[cols="1,1", options="header"]
.Scheduled Configuration File Deployments Columns
|===
| Column               | Description
| System	       | Host name of the system where you want to deploy the configuration file.
| Files to be Deployed | Number of files to be deployed.
| Scheduled By	       | The user who scheduled the job.
| Scheduled For	       | The time and date the file deployment will happen.
| Status    	       | Status of the deployment: ``Queued``
|===
+
Clicking the blue status text displays the menu:System Details[Schedule] page for the specified system.
