[[ref-config-channels]]
= Channels

{productname} manages both central and local configuration channels and files.
Central configuration management allows you to deploy configuration files to multiple systems, by using state channels.
When you create a state channel, you can create or upload custom {salt} states.
For more information about custom states, see xref:specialized-guides:salt/salt-custom-states.adoc[].

Click the name of the configuration channel to see the details page for that channel.
If you click the number of files in the channel, you are taken to the [guimenu]``List/Remove Files`` page of that channel.
If you click the number of systems subscribed to the configuration channel, you are taken to the menu:Configuration Channel Details[Systems > Subscribed Systems] page for that channel.



[[config-config-channels-channel-details]]
== Configuration Channel Details

Overview::
The [guimenu]``Overview`` page of the [guimenu]``Configuration Channel Details``
page is divided into several panels:

Channel Properties [Management]:::
Edit the name, label, and description of the channel by clicking btn:[Edit Properties].

Channel Information:::
Provides status information for the contents of the channel.

Configuration Actions:::
Provides access to the most common configuration tasks.
For Salt clients, there is a link to edit the [path]``init.sls`` file.
+
This panel allows you to deploy, compare, and add and create files.
Some action are only availalble if you have files created and clients assigned to configuration channels.
////
Complete(?) list of:
Configuration Actions

    Deploy Files
    Deploy all configuration files to all subscribed systems
    Deploy selected configuration files to all subscribed systems
    Deploy all configuration files to selected subscribed systems
    Deploy selected configuration files to selected subscribed systems
    Compare Files
    Compare all files in channel to files on all subscribed systems
    Add/Create Files
    Create Configuration File or Directory
    Upload Configuration Files
    Import a File from Another Channel or System
////

List/Remove Files::
This page only appears if there are files in the configuration channel.
You can remove files or copy the latest versions into a set of local overrides or into other central configuration channels.
Check the box next to files you want to manipulate, then click the action button at the bottom.

Add Files::
The [guimenu]``Add Files`` page has three subtabs of its own, which allow you to [guimenu]``Upload``, [guimenu]``Import``, or [guimenu]``Create`` configuration files to be included in the channel.

Upload File:::
To upload a file into the configuration channel, browse for the file on your local system, populate all fields, and click the btn:[Upload Configuration File] button.
The [guimenu]``Filename/Path`` field is the absolute path where the file will be deployed.
+
You can set the [guimenu]``Ownership`` via the [guimenu]``user name`` and [guimenu]``group name`` and the [guimenu]``Permissions`` of the file when it is deployed.
+
If the client has SELinux enabled, you can configure [guimenu]``SELinux contexts`` to enable the required file attributes (such as user, role, and file type).
+
If the configuration file includes a macro (a variable in a configuration file), enter the symbol that marks the beginning and end of the macro.
For more information on using macros, see xref:reference:configuration/files-locally-managed.adoc#s3-sm-file-macros[].
+
Import Files:::
To import files from other configuration channels, including any locally managed channels, check the box to the left of any file you want to import.
Then click btn:[Import Configuration Files].
+
[NOTE]
====
A sandbox icon (image:spacewalk-icon-sandbox.svg[]) indicates that the listed file is currently located in a local sandbox.
Files in a system's sandbox are considered experimental and could be unstable.
Use caution when selecting them for a central configuration channel.
====
+

Create File:::
Create a configuration file, directory, or symbolic link to be included in the configuration channel.

Deploy Files::
This page only appears when there are files in the channel and a system is subscribed to the channel.
Deploy all files by clicking the btn:[Deploy All Files] button or check selected files and click the btn:[Deploy Selected Files] button.
Select to which systems the files should be applied.
All systems subscribed to this channel are listed.
If you want to apply the file to a different system, subscribe it to the channel first.
To deploy the files, click btn:[Confirm & Deploy to Selected Systems].

Systems::
Manage systems subscribed to the configuration channel with two subtabs:

Subscribed Systems:::
All systems subscribed to the current channel are displayed.
Click the name of a system to see the [guimenu]``System Details`` page.
To unsubscribe a system from the configuration channel, check the box to the left of the system name and click btn:[Unsubscribe systems].

Target Systems:::
This subtab displays a list of systems enabled for configuration management but not yet subscribed to the channel.
To add a system to the configuration channel, check the box to the left of the system name and click btn:[Subscribe systems].
