[[ref-config-local]]
= Locally Managed Configuration Files
:description: Configure locally stored configuration files on individual systems with higher priority than centrally managed files, including those in the sandbox or deployed
:revdate: 2021-04-23
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

Locally managed configuration files apply to only one system.
They may be files in the system's sandbox or files that can be deployed to the system at any time.
Local files have higher priority than centrally managed files.
If a system is subscribed to a configuration channel with a given file and additionally has a locally managed version of that file, the locally managed version will be deployed.

The list of all local (override) configuration files for your systems includes the local configuration channels and the sandbox channel for each Provisioning-entitled system.

Click the [guimenu]``Path`` of the file to see its [guimenu]``Config File Details``.
Click the name of the system to which it belongs to see its menu:System Details[Configuration > Overview] page.

For more information about configuration management, see xref:client-configuration:configuration-management.adoc[].
