[[uyuni-install-requirements]]
= Obecné požadavky
:revdate: 2025-10-08
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

The following tables specify the minimum server and proxy requirements.

[IMPORTANT]
====
Do not use NFS for storage because it does not support SELinux file labeling.
====

// In this table, replace ``version`` with the version of the product you are using.
== Server Requirements


[cols="1,1,1", options="header"]
.Server Requirements for {x86_64} Architecture
|===

| Software and Hardware
| Details
| Recommendation

| {tumbleweed}
| Clean installation, up-to-date
| {tumbleweed}

| CPU
| -
| Minimum 4 dedicated 64-bit CPU cores ({x86_64})

| RAM
| Test or Base Installation
| Minimum 16{nbsp}GB

|
| Production Server
| Minimum 32{nbsp}GB

| Disk Space
| [path]``/`` (root directory)
| Minimum 40{nbsp}GB

|
| [path]``/var/lib/pgsql``
| Minimum 50{nbsp}GB

|
| [path]``/var/spacewalk``
| Minimum storage required: 100{nbsp}GB (this will be verified by the implemented check)

* 50{nbsp}GB for each {suse} product and Package Hub
  
360{nbsp}GB for each {redhat} product

|
| [path]``/var/cache``
| Minimum 10{nbsp}GB.
Add 100{nbsp}MB per {suse} product, 1{nbsp}GB per {redhat} or other product.
Double the space if the server is an ISS Master.

|
| Swap space
| 3{nbsp}GB
|===



== Proxy Requirements

[cols="3*", options="header"]
.Proxy Requirements
|===
| Software and Hardware
| Details
| Recommendation

| {tumbleweed}
| Clean installation, up-to-date
| {tumbleweed}

| CPU
|
| Minimum 2 dedicated 64-bit CPU cores

| RAM
| Test Server
| Minimum 2{nbsp}GB

|
| Production Server
| Minimum 8{nbsp}GB

| Disk Space
| [path]``/`` (root directory)
| Minimum 40{nbsp}GB

|
| [path]``/srv``
| Minimum 100{nbsp}GB

|
| [path]``/var/cache`` (Squid)
| Minimum 100{nbsp}GB
|===


{productname} Proxy ukládá balíčky do adresáře [path]``/var/cache/``. Není-li v [path]``/var/cache/`` k dispozici dostatek místa, proxy server odebere staré a nepoužívané balíčky a nahradí je novějšími.

V důsledku tohoto chování:

* Čím větší adresář [path]``/var/cache/`` je na proxy serveru, tím menší provoz bude mezi ním a provozním serverem {productname}.

* Vytvořením adresáře [cesta] ``/var/cache/`` na serveru proxy o stejné velikosti jako [cesta]``/var/spacewalk/`` na serveru {productname} se vyhnete velkému provozu po první synchronizaci.

* Adresář [path]``/var/cache/`` může být na serveru {productname} menší než na proxy.
    Průvodce odhadem velikosti najdete v části <<server-hardware-requirements>> (hardwarové požadavky na server).
