== {sl-micro}および{productname} {productnumber}プロキシの登録

ifeval::[{uyuni-content} == true]
:noindex:
endif::[]
// Before starting obtain your SUSE Manager Registration Code from SUSE Customer Center - https://scc.suse.com.

.プロシージャ: {sl-micro}および{productname} {productnumber}プロキシを登録する
. 仮想マシンをブートします。
. ``root``としてログインします。
. SCCで{sl-micro}を登録します。
+

----
transactional-update register -r <REGCODE> -e <your_email>
----

. 再起動します。

. {scclongform}で{productname} {productnumber}プロキシを登録します。
+

----
transactional-update register -p Multi-Linux-Manager-Proxy/5.1/x86_64 -r <REGCODE>
----

. 再起動します。

. システムを更新します。
+

----
transactional-update
----

. 更新が適用されていた場合は再起動します。

. このステップはオプションです。ただし、ご使用のインフラストラクチャにカスタム永続ストレージが必要な場合は、[command]``mgr-storage-proxy``ツールを使用します。
詳細については、[command]``mgr-storage-proxy --help``を参照してください。このツールを使用すると、コンテナボリュームの作成が容易になります。

** このコマンドは次のように使用します。
+

----
mgr-storage-proxy <storage-disk-device>
----
+
例:
+
----
mgr-storage-proxy /dev/nvme1n1
----
+
[NOTE]
====
このコマンドは、[path]``/var/lib/containers/storage/volumes``にある永続ストレージボリュームを指定されたストレージデバイスに移動します。

詳細については、以下を参照してください。

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]
====
