== {sl-micro} {microversion}ホストの準備


=== インストールメディアのダウンロード

.プロシージャ: インストールメディアのダウンロード
[role=procedure]
____

. link:https://www.suse.com/download/sle-micro/[]で{sl-micro} {microversion}のインストールメディアを見つけて、適切なメディアファイルをダウンロードします。

. インストール用のDVDまたはUSBフラッシュドライブ(ダウンロードした[filename]``.iso``イメージを含む)を準備します。

____


=== {sl-micro} {microversion}のインストール

.プロシージャ: {sl-micro} {microversion}のインストール
[role=procedure]
____

. {sle-micro} {microversion}のインストールイメージを含むDVDまたはUSBフラッシュドライブ(USBディスクまたはキー)を挿入します。

. システムをブートまたは再起動します。

. 矢印キーを使用して[systemitem]``インストール``を選択します。

. キーボードと言語を調整します。

. [systemitem]``チェックボックス``をクリックしてライセンス契約に同意します。

. [systemitem]``次へ``をクリックして続行します。

. Skip the registration. The {sl-micro} {microversion} entitlement is included within the {productname} entitlement.

. btn:[次へ]をクリックして続行します。

. [systemitem]``NTP設定``ページで、btn:[次へ]をクリックします。

. [systemitem]``Authentication for the System (システムの認証)``ページで、rootユーザのパスワードを入力します。btn:[次へ]をクリックします。

. [systemitem]``インストール設定``ページで、btn:[インストール]をクリックします。

____

これで、{sl-micro} {microversion}と拡張機能としての{productname} {productnumber}のインストールは完了です。マシン(仮想または物理)の準備の詳細については、link:https://documentation.suse.com/sle-micro/6.1[{sl-micro}配備ガイド]を参照してください。


=== システムの更新

.プロシージャ: システムの更新
[role=procedure]
____
. **root**としてログインします。

. **transactional-update**を実行します。

+

[source, shell]
----
transactional-update
----

. 再起動します。

____


[IMPORTANT]
====
{sl-micro}はデフォルトで自己更新するように設計されており、更新を適用すると再起動します。ただし、{productname}環境ではこの動作は望ましくありません。サーバの自動更新を防ぐには、{productname}でブートストラッププロセス中にtransactional-updateのタイマを無効にします。

{sl-micro}のデフォルトの動作を使用したい場合は、次のコマンドを実行してタイマを有効にします。

[source, shell]
----
systemctl enable --now transactional-update.timer
----
====
