package generate

// Atomic file writes.
//
// The PDF matrix builds books in parallel, and several books of the same
// language regenerate identical shared files (entities.adoc in particular).
// A plain os.WriteFile truncates before it writes, so a concurrent
// asciidoctor-pdf can read a half-written file. Writing to a temporary file in
// the same directory and renaming it into place makes every write atomic with
// respect to other processes: a reader sees either the previous complete file
// or the new complete one. Nothing here is fsynced, so this says nothing about
// what survives a crash — these are all regenerated by 'task gen'.

import (
	"fmt"
	"os"
	"path/filepath"
)

// atomicWriteFile writes data to path via a temporary file and a rename.
// The temporary file lives in the destination directory so the rename stays
// within one filesystem.
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	base := filepath.Base(path)

	// Not os.CreateTemp: it creates the file 0600 and would need a chmod to
	// perm afterwards, which ignores the umask that the os.WriteFile this
	// replaces would have applied. O_CREATE|O_EXCL with perm keeps the mode
	// the caller would otherwise have got.
	var (
		tmp     *os.File
		tmpName string
		err     error
	)
	for i := 0; tmp == nil && i < 100; i++ {
		tmpName = filepath.Join(dir, fmt.Sprintf(".%s.tmp%d-%d", base, os.Getpid(), i))
		tmp, err = os.OpenFile(tmpName, os.O_WRONLY|os.O_CREATE|os.O_EXCL, perm)
		if err != nil && !os.IsExist(err) {
			return fmt.Errorf("create temp file in %s: %w", dir, err)
		}
	}
	if tmp == nil {
		return fmt.Errorf("create temp file in %s: %w", dir, err)
	}

	// Disarmed by clearing tmpName once the rename has taken the file away.
	defer func() {
		if tmpName != "" {
			tmp.Close()
			os.Remove(tmpName)
		}
	}()

	if _, err := tmp.Write(data); err != nil {
		return fmt.Errorf("write %s: %w", tmpName, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close %s: %w", tmpName, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename %s -> %s: %w", tmpName, path, err)
	}
	tmpName = ""
	return nil
}
