package generate

// siteYMLTemplate is the Go text/template for per-output site.yml files.
// It replaces site.yml.j2 + site.yml.common.j2.
const siteYMLTemplate = `# Generated by docbuild — do not edit by hand.
# Source: config.yml  output: {{.Output}}  lang: {{.Lang.Code}}
content:
  sources:
  - url: {{.RepoRoot}}
    start_path: {{.StartPath}}
    branches:
    - HEAD
output:
  dir: {{.OutputDir}}
runtime:
  cache_dir: {{.RepoRoot}}/.cache/antora
site:
  title: {{.Out.Site.Title}}
  url: {{.SiteURL}}
  start_page: {{.Out.Site.StartPage}}
antora:
  extensions:
{{- range .Cfg.Antora.Extensions}}
    - '{{.}}'
{{- end}}
asciidoc:
  extensions:
{{- range .Cfg.AsciidocExtensions}}
    - '{{.}}'
{{- end}}
  attributes:
    page-lang: {{.Lang.Code}}
{{- range $k, $v := .Cfg.Asciidoc}}
    {{$k}}: {{$v}}
{{- end}}
{{- range $k, $v := .P.Asciidoc.Attributes}}
    {{$k}}: {{$v}}
{{- end}}
ui:
  bundle:
    url: {{.BundleURL}}
    snapshot: true
  supplemental_files: {{.SupplementalFiles}}
`

// antoraYMLTemplate is the Go text/template for antora.yml.
// It replaces antora.yml.j2.
const antoraYMLTemplate = `# Generated by docbuild — do not edit by hand.
# Source: config.yml  product: {{.Product}}  lang: {{.Lang.Code}}
name: {{.P.Antora.Name}}
title: {{.P.Antora.Title}}
version: ~
start_page: ROOT:index.adoc
nav:
  - {{.ContentDir}}/ROOT/nav.adoc
{{- range .P.Sections}}
  - {{$.ContentDir}}/{{.}}/nav-{{.}}-guide.adoc
{{- end}}
`

// entitiesTemplate is the Go text/template for translations/{lang}/branding/pdf/entities.adoc.
// It replaces entities.adoc.j2 + entities.specific.adoc.j2.
// The file is self-contained: product attributes and locale attributes are inlined,
// so asciidoctor-pdf does not need to resolve any external includes.
const entitiesTemplate = `// Generated by docbuild — do not edit by hand.
// Source: config.yml  product: {{.Product}}  lang: {{.Lang.Code}}
// Product attributes
{{- range $k, $v := .P.Asciidoc.Attributes}}
:{{$k}}: {{$v}}
{{- end}}
// Shared attributes
{{- range $k, $v := .Cfg.Asciidoc}}
:{{$k}}: {{$v}}
{{- end}}
// Page-lang for Handlebars html element
:lang: {{.Lang.Code}}
// Locale attributes (from branding/locale/attributes-{{.Lang.Code}}.adoc)
{{.LocaleAttrs}}
`
