[[proxy-uyuni-upgrade]]
= 프록시 - 업그레이드 절차

프록시를 업데이트하기 전, 유지보수 기간을 예약합니다. 프록시를 통해 {productname}에 등록된 클라이언트는 업데이트를 진행하는 동안 {productname}에 연결할 수 없습니다. 유지보수 기간에 대한 자세한 정보는 xref:administration:maintenance-windows.adoc[]을 참조하십시오.



== 준비

준비 단계로 openSUSE Leap {opensuse-version} 채널을 서버에 추가합니다.

.절차: 명령 프롬프트에 소프트웨어 채널 추가
. {productname} 서버의 명령 프롬프트에서 root로 [command]``spacewalk-common-channels`` 명령을 사용하여 적절한 채널을 추가합니다.
+
----
spacewalk-common-channels opensuse_leap15_2 \
opensuse_leap15_2-non-oss \
 opensuse_leap15_2-non-oss-updates \
 opensuse_leap15_2-updates \
 opensuse_leap15_2-uyuni-client \
 uyuni-proxy-stable-leap-152
----
. [command]``spacewalk-repo-sync``를 사용하여 모든 채널을 완전히 동기화합니다. 이미 리포지토리 URL을 정의한 경우, <<uyuni-202007-channeldupes>>을 진행합니다.



[[uyuni-202007-channeldupes]]
== 중복 리포지토리 URL 문제 해결


[command]``spacewalk-common-channels``을 사용하여 {productname}에서 URL이 동일한 리포지토리를 2개 이상 추가(openSUSE Leap 15.0, 15.1 및 15.2용 클라이언트 도구)하면 다음 오류가 표시됩니다.

----
오류: opensuse_leap15_2-uyuni-client-x86_64:
redstone.xmlrpc.XmlRpcFault: 특정 URL을 갖는 정의된 리포지토리가 이미 존재합니다. 해당 리포지토리를 다시 사용하십시오.
----

15.1 리포지토리를 15.2 채널에 할당하여 해결:

.절차: 15.1 리포지토리를 15.2 채널에 할당:

. {productname} 서버 {webui}에서 menu:소프트웨어[관리 > 채널]로 이동하여 [systemitem]`` Uyuni Client Tools for openSUSE Leap 15.2(x86_64)`` 채널 이름을 클릭합니다.

. 오른쪽 상단에서 btn:[채널 관리]를 클릭합니다.

. [guimenu]``리포지토리`` 탭으로 이동하여 [systemitem]``External - Uyuni Client Tools for openSUSE Leap 15.1(x86_64)``을 선택합니다.

. btn:[리포지토리 업데이트]를 클릭합니다.

. menu:리포지토리[동기화] 하위 탭으로 이동하여 btn:[지금 동기화]를 클릭합니다.

. [systemitem]``Uyuni Proxy Stable for openSUSE Leap 15.2(x86_64)`` 및 [systemitem]``External - Uyuni Proxy Stable for openSUSE Leap 15.1(x86_64)``에서도 동일한 절차를 수행합니다.

[systemitem]``openSUSE Leap 15.2(x86_64)`` 채널을 펼쳐 패키지로 채워진 하위 채널을 확인합니다.



== 프록시 업그레이드

프록시를 업그레이드하려면 먼저 프록시 서비스를 중지한 후 소프트웨어 리포지토리를 바꾸고 소프트웨어를 업데이트한 후 마지막으로 프록시 서비스를 재시작합니다.



.절차: {productname} 프록시 업데이트

. {productname} 서버 {webui}에서 프록시 시스템의 상세 정보 페이지로 이동하여 [guimenu]``재활성`` 하위 탭을 클릭합니다.

. btn:[새 키 생성]을 클릭하여 재활성 키를 생성합니다.
+

. {productname} 프록시에서 프록시 서비스를 중지합니다.
+
----
spacewalk-proxy stop
----

. {productname} 서버 {webui}에서 menu:시스템[프록시]로 이동하여 프록시의 이름을 클릭합니다.
. menu:소프트웨어[소프트웨어 채널]을 클릭하고 [systemitem]``Customs Channels`` 목록에 나열된 openSUSE Leap {opensuse-version} 채널을 기본 채널로 선택합니다.
. [guimenu]``하위 채널`` 창에서 {opensuse-version} 하위 채널을 선택합니다.
. btn:[다음]을 클릭한 후 [guimenu]``소프트웨어 채널 변경 확인``을 클릭하여 btn:[확인]합니다.
. menu:소프트웨어[패키지 > 업그레이드]를 클릭하고 프록시에서 업데이트할 모든 패키지를 선택한 후 선택 사항을 적용합니다.
. [command]``rhnreg_ks`` 명령줄 유틸리티를 사용하여 재활성화 키로 다시 등록합니다. 동일한 ID, 이력 및 그룹으로 시스템이 다시 등록됩니다.
+
. {productname} 프록시에서 프록시 서비스를 시작합니다.
+
----
spacewalk-proxy start
----

여러 프록시를 업데이트해야 할 경우 {productname} 서버에서 이 명령 시퀀스의 작업 체인을 생성할 수 있습니다. 작업 체인을 사용하여 여러 프록시에서 동시에 업데이트를 수행할 수 있습니다.
