[[proxy-uyuni-ay]]
= 프록시 - AutoYaST를 사용한 업그레이드


{productname} 프록시는 하나의 주 버전에서 다음 버전으로 업그레이드할 수 있습니다. 업그레이드 프로세스는 자동화되지만, 몇 가지 준비 단계를 수행한 후 업그레이드할 수 있습니다.

{productname} 서버 업그레이드를 완료한 후 시작해야 합니다.

기존 시스템에서는 모든 최신 업데이트가 적용된 {productname} 프록시가 실행 중이어야 합니다. 시작하기 전, 시스템이 최신 상태이고 모든 업데이트가 설치되었는지 확인하십시오.



== 업그레이드 준비

프록시를 업데이트하기 전, 자동 설치 배포 및 자동 설치 프로파일이 필요합니다. 배포판은 openSUSE Leap{nbsp}{opensuse-version} 기반이어야 합니다.

.절차: 설치 미디어 준비
. {productname} 서버에서 다음과 같이 openSUSE Leap{nbsp}{opensuse-version} 설치 미디어용 로컬 디렉토리를 생성합니다.
+
----
mkdir -p /srv/images/opensuse152
----
. 설치 원본과 함께 ISO 이미지를 다운로드하고 서버에 ISO 이미지를 마운트합니다.
+
----
mount -o loop DVD1.iso /mnt/
----
. 마운트한 ISO의 모든 항목을 로컬 파일 시스템에 복사합니다.
+
----
cp -r /mnt/* /srv/images/opensuse152
----
. 복사가 완료되면 ISO 이미지를 마운트 해제합니다.
+
----
umount /mnt
----


.절차: 명령 프롬프트에 소프트웨어 채널 추가
. {productname} 서버의 명령 프롬프트에서 root로 [command]``spacewalk-common-channels`` 명령을 사용하여 적절한 채널을 추가합니다.
+
----
spacewalk-common-channels opensuse_leap15_2 \
opensuse_leap15_2-non-oss \
 opensuse_leap15_2-non-oss-updates \
 opensuse_leap15_2-updates \
 opensuse_leap15_2-uyuni-client \
 uyuni-proxy-stable-leap-152
----
. [command]``spacewalk-repo-sync``을 사용하여 모든 채널을 완전히 동기화합니다.




.절차: 자동 설치 배포판 생성
. {productname} {webui}에서 menu:시스템[자동 설치 > 배포판]으로 이동한 후 btn:[배포 생성]을 클릭합니다.
. [guimenu]``자동 설치 가능한 배포판 생성`` 섹션에서 파라미터를 다음과 같이 적용합니다.
* [guimenu]``배포판 레이블`` 섹션에 배포판의 고유 이름을 입력합니다.
    이름에는 문자, 숫자, 하이픈, 마침표 및 밑줄만 사용해야 하며 5자 이상이어야 합니다. 예를 들어, ``proxy_152-x86_64``일 수 있습니다.
* [guimenu]``트리 경로`` 필드에 설치 원본의 절대 경로를 입력합니다.
    예를 들어, [path]``/srv/images/opensuse152``일 수 있습니다.
* [guimenu]``기본 채널`` 필드에서 [systemitem]``openSUSE Leap 15.2(x86_64)``를 선택합니다.
* [guimenu]``설치 프로그램 생성`` 필드에서 [systemitem]``SUSE Linux``를 선택합니다.
* [guimenu]``커널 옵션`` 필드에 설치를 부팅할 때 커널로 전달될 옵션을 입력합니다.
    [option]``install=`` 파라미터와 [option]``self_update=0 pt.options=self_update``파라미터가 기본적으로 추가됩니다.
* [guimenu]``커널 후 옵션`` 섹션에 처음으로 설치된 시스템을 부팅할 때 커널로 전달될 옵션을 입력합니다.
. btn:[자동 설치 가능한 배포판 생성]을 클릭하여 저장합니다.


자동 설치 가능한 배포판을 생성한 후 menu:시스템[자동 설치 > 배포판]으로 이동하여 편집할 배포판을 선택하고 편집할 수 있습니다.



== 자동 설치 프로파일 생성

자동 설치 프로파일에는 시스템을 설치하기 위해 필요한 모든 설치와 구성 데이터가 포함되어 있습니다. 또한 설치 완료 후 실행될 스크립트도 포함되어 있습니다. 예를 들어 시작 지점으로 사용할 수 있는 스크립트는 https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST를 참조하십시오. 올바른 AutoYaST 업그레이드 설정은 https://doc.opensuse.org/projects/autoyast/#CreateProfile-upgrade를 참조하십시오.



.절차: 자동 설치 프로파일 생성
. {productname} {webui}에서 menu:시스템[자동 설치 > 프로파일]로 이동하여 자동 설치 프로파일 스크립트를 업로드합니다.
    예를 들어 시작 지점으로 사용할 수 있는 스크립트는 https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST를 참조하십시오.
. ``커널 옵션`` 필드에 ``autoupgrade=1``을 입력합니다.
    선택 사항으로 ``Y2DEBUG=1`` 옵션도 포함할 수 있습니다. 디버그 설정은 필요하지 않지만, 발생 가능한 향후 문제를 조사하는 데 유용할 수 있습니다.
. 자동 설치 프로파일을 붙여넣거나 파일 업로드 필드를 사용합니다.
. btn:[생성]을 클릭하여 저장합니다.
. 업로드한 프로파일에 변수를 설정해야 하면, menu:시스템[자동 설치 > 프로파일]로 이동하여 편집할 프로파일을 선택하고 [guimenu]``변수`` 탭으로 이동합니다.
    다음 형식을 사용하여 필수 변수를 지정합니다.
+
----
<key>=<value>
----

[NOTE]
====
Salt를 사용하여 등록된 프록시의 경우 업그레이드를 완료한 후 ``spacewalk/minion_script`` 코드 조각을 사용하여 프록시를 다시 등록합니다.
====



== 업그레이드

시작하기 전, 자동 설치 프로파일에서 참조된 모든 채널을 사용할 수 있고 완전히 동기화되었는지 확인합니다.



.절차: 업그레이드
. {productname} 서버 {webui}에서 menu:시스템[시스템 목록]으로 이동하여 프록시를 선택한 후 [guimenu]``프로비저닝`` 탭으로 이동하고 업로드한 자동 설치 프로파일을 선택합니다.
. btn:[자동 설치 스케줄링 후 완료]를 클릭합니다.
    시스템이 필수 파일을 다운로드하고 부트로더 항목을 변경한 후 재부팅되어 업그레이드가 시작됩니다.



== 정리

{productname} 프록시의 업그레이드가 완료된 후 원래 할당된 채널이 표시됩니다. 마이그레이션 후 정리하면 올바른 채널이 표시됩니다.


[WARNING]
====
프록시에 사용할 수 있는 업데이트가 있다고 서버가 알림을 제공하면 정리가 완료되기 전에 업데이트를 적용하지 마십시오.
====



.절차: 정리
. {productname} 서버 {webui}에서 [guimenu]``시스템 목록``으로 이동하여 프록시를 선택한 후 menu:소프트웨어[소프트웨어 채널] 하위 탭으로 이동합니다.
. 기존 채널을 삭제합니다.
. [guimenu]``기본 채널`` 필드에서 `openSUSE Leap 15.2(x86_64)``를 선택합니다.
. [guimenu]``하위 채널`` 필드에서 모든 권장 채널을 선택합니다.
