[[server-z]]
= 서버 - 패치 수준 업그레이드(Z 업그레이드)

이 업데이트 절차는 단순한 패키지 업데이트 또는 일관적인 마이크로 업데이트를 다루며, 유지보수 업데이트(MU)라고 합니다. MU 중에 사용자는 서비스를 중지하고 패키지를 업데이트하며 스크립트를 실행하여 데이터베이스를 업데이트하고 서비스를 재시작합니다.

Example: [literal]``4.2.0`` → [literal]``4.2.1``.

즉, 먼저 사용자는 설치된 모든 패키지의 최신 버전이 설치되어 있는지 확인합니다. 그런 다음에 데이터베이스 스키마를 업그레이드할 수 있습니다.



.절차: {productname} 서버에서 패키지 업데이트

기본적으로 여러 업데이트 채널은 {productname} 서버를 위해 구성 및 활성화됩니다. 새 패키지와 업데이트된 패키지는 자동으로 제공됩니다.

. {productname} 서버의 명령 프롬프트에서 root로 Spacewalk 서비스를 중지합니다.
+
----
spacewalk-service stop
----
. 사용할 수 있는 패치를 나열합니다.
+
----
zypper list-patches
----
. 사용할 수 있는 모든 패치를 적용합니다.
+
----
zypper patch
----
+
이 명령은 패치에만 적용됩니다.
  적용되지 않은 모든 패치를 적용하려면 [command]``zypper up``을 대신 사용합니다.
. Spacewalk 서비스를 재시작합니다.
+
----
spacewalk-service start
----

[NOTE]
====
기본적으로 zypper는 10분마다 리포지토리를 새로 고칩니다([path]``/etc/zypp/zypp.conf``의 ``repo.refresh.delay`` 참조). ``autorefresh``가 비활성화되면 [command]``zypper ref``를 실행하여 모든 리포지토리를 새로 고칩니다.
====

[NOTE]
====
명령 [command]``spacewalk-schema-upgrade``는 더 이상 필요하지 않습니다. [command]``spacewalk-service start`` 중에 자동으로 실행됩니다.
====

[IMPORTANT]
====
패키지 업데이트의 영향을 받는 서비스는 업데이트 후에 자동으로 재시작되지 않습니다. 장애가 발생하지 않도록 하려면 이러한 서비스를 수동으로 재시작해야 합니다. 기존 코드를 사용하고 재시작해야 하는 애플리케이션을 확인하려면 [command]``zypper ps``를 사용합니다.
====

패치 업데이트에서 재부팅이 권장되면 서버를 재시작합니다.
