[[upgrade-troubleshooting]]
= 문제 해결

이 섹션에서는 {productname} 업그레이드와 관련하여 발생할 수 있는 몇 가지 일반적인 문제와 이를 해결하기 위한 해결 방법을 설명합니다.

업그레이드 문제에 대한 자세한 정보는 마이그레이션 로그 파일을 확인하십시오. 로그 파일은 업그레이드 중인 시스템의 [path]``/var/log/rhn/migration.log``에 있습니다.





== 디스크 공간 부족

사용할 수 있는 디스크 공간을 확인한 후 마이그레이션을 시작하십시오. 별도의 XFS 파일 시스템에서 [path]``/var/spacewalk`` 및 [path]``/var/lib/pgsql``을 찾는 것이 좋습니다.

별도의 파일 시스템을 설정하는 경우에는 [path]``/etc/fstab``을 편집하고 [path]``/var/lib/pqsql`` 하위 볼륨을 제거하십시오. 서버를 재부팅하여 변경 사항을 적용하십시오.



== 대상 시스템 설정 재시도

대상 시스템을 다시 설정해야 하는 경우 다음 단계를 따르십시오.

. [path]``/root/.MANAGER_SETUP_COMPLETE``을 삭제합니다.
. PostgreSQL을 중지하고 [path]``/var/lib/pgsql/data``를 제거합니다.
. 원본 시스템 호스트 이름과 일치하도록 대상 시스템 호스트 이름을 설정합니다.
. [path]``/etc/hosts`` 파일을 확인하여 필요한 경우 수정합니다.
. 대상 시스템에서 [path]``/etc/setup_env.sh``를 확인하여 데이터베이스 이름이 설정되어 있는지 확인합니다.
+
----
MANAGER_DB_NAME='susemanager'
----
. 대상 시스템을 재부팅합니다.
. [command]``mgr-setup``을 다시 실행합니다.



== 스키마 업그레이드 실패

스키마 업그레이드에 실패하면 데이터베이스 버전 확인 및 기타 모든 Spacewalk 서비스가 시작되지 않습니다. 자세한 정보와 진행 방법에 대한 힌트를 확인하려면 [command]``spacewalk-service start``를 실행하십시오.

또한 다음을 통해 버전 확인을 직접 실행할 수도 있습니다.

----
systemctl status uyuni-check-database.service
----

또는

----
journalctl -u uyuni-check-database.service
----

더 일반적인 [command]``spacewalk-service`` 명령을 실행하지 않으려는 경우 이 명령을 통해 디버그 정보를 출력할 수 있습니다.



== {webui} 로드 실패

가끔 마이그레이션 후에 {webui}가 로드되지 않을 수 있습니다. 이 문제는 새 시스템의 호스트 이름 및 IP 주소가 기존 시스템과 동일한 경우 주로 브라우저 캐싱에 의해 발생합니다. 이러한 중복으로 일부 브라우저에서 혼동이 발생할 수 있습니다.

캐시를 지우고 페이지를 다시 로드하면 이 문제가 해결됩니다. 대부분의 브라우저에서는 kbd:[Ctrl+F5]를 눌러 이 문제를 빠르게 해결할 수 있습니다.
