[[upgrade-overview]]
= 업그레이드 가이드 개요

**업데이트 날짜:** {docdate}

{productname}에는 3개의 주요 구성 요소가 있으며, 이러한 구성 요소에는 모두 일반 업데이트가 필요합니다. 이 가이드에서는 {productname} 서버, 프록시 및 클라이언트와 함께 일부 기본 구성 요소(예: 데이터베이스)의 업데이트에 대해 설명합니다.

일부 업데이트를 자동화할 수 있지만, 수동으로 수행해야 하는 업데이트도 있습니다.

[NOTE]
====
이 가이드를 처음부터 끝까지 읽을 필요는 없습니다. 대신, 업그레이드할 구성 요소로 이동한 다음 업그레이드 대상 버전을 확인하십시오.
====

ifeval::[{suma-content} == true]
{productname}는 [literal]``X.Y.Z`` 버전 관리 스키마를 사용합니다. 필요한 업그레이드 절차는 변경되는 버전 번호를 확인하여 결정할 수 있습니다.

주 버전 업그레이드(X 업그레이드)::
다음 주 버전으로 업그레이드합니다. 예를 들어 3.2에서 4.1로 업그레이드합니다. 이러한 유형의 업그레이드는 4.2에 적용되지 않습니다.

부 버전 업그레이드(Y 업그레이드)::
다음 부 버전으로 업그레이드합니다. 이를 종종 제품 마이그레이션, 서비스 팩 마이그레이션 또는 SP 마이그레이션이라고 합니다. 예를 들어, 4.1에서 4.2로의 업그레이드가 해당합니다.

패치 수준 업그레이드(Z 업그레이드)::
동일한 부 버전으로 업그레이드합니다. 이를 유지보수 업데이트라고 합니다. 예를 들어, 4.1.2에서 4.1.8로 또는 4.2.0에서 4.2.1로의 업그레이드가 이에 해당합니다.

{productname} 서버를 업그레이드하려면, xref:upgrade:server-intro.adoc[]을 참조하십시오.
endif::[]
ifeval::[{uyuni-content} == true]
{productname}에서는 롤링 릴리스에 적합한 [literal]``YYYY.MM`` 버전 관리 스키마를 사용합니다. {productname} 서버를 업그레이드하는 경우 xref:upgrade:server-intro-uyuni.adoc[]을 참조하십시오.
endif::[]

{productname} 프록시를 업그레이드하려면, xref:upgrade:proxy-intro.adoc[]을 참조하십시오.

클라이언트를 업그레이드하려면 xref:upgrade:client-intro.adoc[]를 참조하십시오.

서버 업그레이드 외에도 데이터베이스와 같은 기타 기본 기술도 업그레이드해야 합니다. 데이터베이스 업그레이드에 대한 자세한 정보는 xref:upgrade:db-intro.adoc[]를 참조하십시오.
