= [command]\``mgradm``을 사용하여 사용자 지정 YAML 구성 및 배포
:description: 특정 예제 형식으로 사용자 지정 mgradm.yaml 파일을 만드는 방법을 배우고, 배포 시 mgradm 도구와 함께 비밀번호를 안전하게 보호하면서 사용하는 방법을 알아보세요.
:revdate: 2024-11-19
:page-revdate: {revdate}
:page-author: SUSE 제품 및 솔루션 문서팀
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

사용자 지정 `mgradm.yaml` 파일을 생성할 수 있으며, `mgradm` 도구가 배포 시 이를 활용할 수 있습니다.
모든 `mgradm` 인수에는 대응하는 YAML 항목이 있습니다.
예를 들어, `mgradm` 인수 `--ssl-db-ca-intermediate`은(는) `mgradm.yaml` 파일에 다음과 같이 지정할 수 있습니다:

[source, yaml]
ssl:
  db:
    ca:
      intermediate: /path/to/ca-intermediate.crt

[IMPORTANT]
====
`mgradm`명령 매개변수 또는 `mgradm.yaml` 구성 파일을 통해 기본 변수가 제공되지 않은 경우, 이(가) 해당 변수를 입력하라는 메시지를 표시합니다.

보안을 위해 **비밀번호를 지정하기 위해 명령줄 매개변수를 사용하는 것은 피해야 합니다**. 
대신 적절한 권한이 설정된 구성 파일을 사용하십시오.
====

.절차 사용자 지정 구성 파일을 사용하여 Podman으로 {productname} 컨테이너를 배포하기
. 다음 예제와 유사하게 `mgradm.yaml`이라는 이름의 구성 파일을 준비하십시오:
+
[source, yaml]
....
# Database password. Randomly generated by default
db:
  password: MySuperSecretDBPass

# Password for the CA certificate
ssl:
  password: MySuperSecretSSLPassword

# Your SUSE Customer Center credentials
scc: 
  user: ccUsername
  password: ccPassword

# Organization name
organization: YourOrganization

# Email address sending the notifications
emailFrom: notifications@example.com

# Administrators account details
admin:
  password: MySuperSecretAdminPass
  login: LoginName
  firstName: Admin
  lastName: Admin
  email: email@example.com
....

. 터미널에서 루트 사용자로 다음 명령을 실행하십시오.
  서버의 FQDN을 입력하는 것은 선택 사항입니다.
+
[source, shell]
----
mgradm -c mgradm.yaml install podman <FQDN>
----
+
[IMPORTANT]
====
컨테이너를 sudo 또는 루트 사용자로 배포해야 합니다.
이 단계를 놓치면 터미널에 다음 오류가 표시됩니다.

[source, shell]
----
INF Setting up uyuni network
9:58AM INF Enabling system service
9:58AM FTL Failed to open /etc/systemd/system/uyuni-server.service for writing error="open /etc/systemd/system/uyuni-server.service: permission denied"
----
====

. 배포가 완료될 때까지 기다립니다.

. 브라우저를 열고 서버의 FQDN 또는 IP 주소로 이동합니다.

//In this section you learned how to deploy an {productname} {productnumber} Server container using a custom YAML configuration.
