[[client-migration]]
= Client - X Upgrade

Your clients must have the latest available SLE{nbsp}12 Service Pack, with all the latest updates applied.
Before you start, ensure that the system is up to date and all updates have been installed successfully.

The upgrade is controlled by {yast} and {ay}, it does not use Zypper.


=== Prepare to Migrate

Before you can migrate your client from SLE{nbsp}12 to SLE{nbsp}15, you need to make these preparations:

. Prepare installation media
. Create an auto-installation distribution
. Create an activation key
. Upload an {ay} profile


.Procedure: Preparing Installation Media
. On the {productname} Server, create a local directory for the SLE{nbsp}15 installation media.
. Download an ISO image with the installation sources, and mount the ISO image on your server:
+
----
mkdir /mnt/sle15
mount -o loop DVD1.iso /mnt/sle15
----

.Procedure: Creating an Autoinstallation Distribution

. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > Distributions] and click btn:[Create Distribution].
. In the [guimenu]``Create Autoinstallable Distribution`` section, use these parameters:
* In the [guimenu]``Distribution Label`` section, type a unique name for the distribution.
Use only letters, numbers, hyphens, periods, and underscores, and ensure the name is longer than four characters.
* In the [guimenu]``Tree Path`` field, type an absolute path to the installation source.
For example, [path]``/mnt/sle15``.
* In the [guimenu]``Base Channel`` field, select [systemitem]``SLE-Product-SLES15-Pool for x86_64``.
* In the [guimenu]``Installer Generation`` field, select [systemitem]``SUSE Linux Enterprise 15``.
* In the [guimenu]``Kernel Options`` field, type any options to be passed to the kernel when booting for the installation.
The [option]``install=`` parameter and the [option]``self_update=0 pt.options=self_update`` parameter are added by default.
* In the [guimenu]``Post Kernel Options`` section, type any options to  be passed to the kernel when booting the installed system for the first time.
. Click btn:[Create Autoinstallable Distribution] to save.



.Procedure: Creating an Activation Key

In order to switch from the old SLE{nbsp}12{nbsp}SP4 base channel to the new SLE{nbsp}15 channel, you need an activation key.

. In the {productname} Server {webui}, navigate to menu:Systems[Activation Keys] and click [guimenu]``Create Key``.
. Enter a description for your key.
. Enter a key or leave it blank to generate an automatic key.
. OPTIONAL: If you want to limit the usage, enter your value in the [guimenu]``Usage`` text field.
. Select the [systemitem]``SLE-Product-SLES15-Pool for x86_64`` base channel.
. OPTIONAL: Select any [guimenu]``Add-On System Types``.
For more information, see https://documentation.suse.com/sles/15-SP1/html/SLES-all/art-modules.html.
. Click btn:[Create Activation Key].
. Click the [guimenu]``Child Channels`` tab and select the required channels.
. Click btn:[Update Key].



.Procedure: Uploading an {ay} Profile

Create an {ay} profile.
For more information about {ay}, see xref:client-configuration:client-automating-installation.adoc[].

. In the {productname} Server {webui}, navigate to menu:Systems[Autoinstallation] and click [guimenu]``Upload Kickstart/Autoyast File``.
. Paste the XML content in the text area or select the file to upload and click btn:[Create].
. Navigate to the [guimenu]``Details`` tab.
. In the [guimenu]``Kernel Options`` field, select [systemitem]``autoupgrade=1`` and click btn:[Update].
. Navigate to the [guimenu]``Variable`` tab.
. In the [guimenu]``registration_key=`` field, enter the activation key, and click btn:[Update Variables].



=== Migration

Before you begin the migration, make sure that the migration target channels are completely mirrored.
For the upgrade to {sle} 15, at least the [systemitem]``SLE-Product-SLES15-Pool`` base channel with the [systemitem]``SLE-Manager-Tools15-Pool`` child channel for your architecture is required.
The matching update channels such as [systemitem]``SLE-Manager-Tools15-Updates`` and [systemitem]``SLE-Product-SLES15-Updates`` are recommended.

// TODO: Check this:
You can monitor the mirroring progress in [path]``/var/log/rhn/reposync/sles15-pool-x86_64.log``.



.Procedure: Migrating
. In the {productname} Server {webui}, navigate to [guimenu]``Systems`` and select the client to be upgraded.
. Navigate to menu:System Details[Provisioning > Autoinstallation > Schedule], and select the {ay} profile you uploaded.
. Click btn:[Schedule Autoinstallation and Finish].

Next time the client synchronizes with the {productname} Server, it will receive a re-installation job.
The re-installation job fetches the new kernel and initrd packages.
It will also write a new [path]``/boot/grub/menu.lst``, containing pointers to the new kernel and initrd packages.

When the client next boots, it will use grub to boot the new kernel with its initrd.
PXE booting is not used during this process.

Approximately three minutes after the job was fetched, the client will go down for reboot.



== SP Mass Migration

If you want to migrate a large number of clients to the next SP version, you can use {productname} API calls.



.Procedure: SP Mass Migration
. You need to know to which migration target you want to migrate.
List available migration targets:
+
----
spacecmd api -- system.listMigrationTargets -A 1000010001
----
+
Create a list of system IDs you want to migrate.
. For each system ID, call [systemitem]``listMigrationTarget`` and check that it is an available target.
+
* If the system ID is an available target, call [systemitem]``system.scheduleSPMigration``.
* If it is not an available target, skip the system.

Adapt this template for your environment:

----
target = '[....]'
basechannel = 'channel-label'
system_ids = [1, 2, 3]

session = auth.login(user, pass)
for system in system_ids
  if system.listMigrationTargets(session, system).ident == target
    system.scheduleSPMigration(session, system, target, basechannel, [], False, <now>)
  else
    print "Cannot migrate to requested target -- skipping system"
  endif
endfor
----
