[[db-migration-12]]
= Database Migration from Version 10 to 12

This section covers upgrading the PostgreSQL database from version{nbsp}10 to version{nbsp}12.
If you are already using PostgreSQL 12, you do not need to perform this migration.
If you are using an older version, such as version 9.6,  see xref:upgrade:db-migration.adoc[].

If you want to upgrade to the latest {productname} version, you must be using PostgreSQL version 12.
You migrate to PostgreSQL 12 after you upgraded your {productname} Server to version{nbsp}4.1.



////
== Background Information


* {productname} 3.1.4, SLES 12 SP3, Postgres 9.6
* {productname} 3.1.11, SLES 12 SP3, Postgres 9.6
* {productname} 3.2.10, SLES 12 SP3, Postgres 9.6
* {productname} 3.2.10, SLES 12 SP3, Postgres 10
* {productname} 3.2.10, SLES 12 SP4, Postgres 10
* {productname} 4.0.0, SLES 15 SP1, Postgres 10
* {productname} 4.1.0, SLES 15 SP2, Postgres 12

////
.Procedure: Migrating PostgreSQL 10 to 12

. On an upgraded {productname} Server 4.1 system check whether spacewalk services are already running:
+
----
systemctl status uyuni-check-database.service
----
+
or
+
----
journalctl -u uyuni-check-database.servicespacewalk-service start
----
+
If spacewalk services are already running, no further action is required.
If you see an error message, proceed with the following steps.

. Stop spacewalk services:
+
----
spacewalk-service stop
----

. Install pending patches:
+
----
zypper patch
----

. Start spacewalk services:
+
----
spacewalk-service start
----
+

[NOTE]
====
Running the the database schema upgrade
([command]``spacewalk-schema-upgrade``) is not needed anymore.
The [command]``spacewalk-service start`` command will run 
====



////
== Background Information

* {productname} 3.1.4, SLES 12 SP3, Postgres 9.6
* {productname} 3.1.11, SLES 12 SP3, Postgres 9.6
* {productname} 3.2.10, SLES 12 SP3, Postgres 9.6
* {productname} 3.2.10, SLES 12 SP3, Postgres 10
* {productname} 3.2.10, SLES 12 SP4, Postgres 10
* {productname} 4.0.0, SLES 15 SP1, Postgres 10
* {productname} 4.1.0, SLES 15 SP2, Postgres 12

////


// FIXME?!?
// For updating the database first, see db-migration.adoc

