[[proxy-x]]
= Proxy - Major Version Upgrade (X Upgrade)

{localesdir} 



{productname} Proxy can be upgraded from one major version to the next.
The upgrade process is automated, but you will need to do some preparation steps before you can upgrade.

You will need to complete the {productname} Server migration before you start.

The system must be running {productname} Proxy{nbsp}3.2 with all the latest updates applied.
Before you start, ensure that the system is up to date and all updates have been installed successfully.



== Prepare to Migrate

Before you can update your proxy, you will need an autoinstallation distribution, and an autoinstallation profile.
The distribution must be based on {sle}{nbsp}15 SP2, because {productname}{nbsp}4.1 is part of the {sle}{nbsp}15 SP2 product family.


.Procedure: Preparing Installation Media
. On the {productname} Server, create a local directory for the SLE{nbsp}15{nbsp}SP2 installation media:
+
----
mkdir -p /srv/images/sle15sp2
----
. Download an ISO image with the installation sources, and mount the ISO image on your server:
+
----
mount -o loop DVD1.iso /mnt/
----
. Copy everything from the mounted ISO to your local file system:
+
----
cp -r /mnt/* /srv/images/sle15sp2
----
. When the copy is complete, unmount the ISO image:
+
----
umount /mnt
----

[NOTE]
====
This image is the unified installer and can be used for multiple autoinstallation distributions.
====

.Procedure: Creating an Autoinstallation Distribution
. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > Distributions] and click btn:[Create Distribution].
. In the [guimenu]``Create Autoinstallable Distribution`` section, use these parameters:
* In the [guimenu]``Distribution Label`` section, type a unique name for the distribution.
    Use only letters, numbers, hyphens, periods, and underscores, and ensure the name is longer than four characters.
    For example, ``proxy_41-x86_64``.
* In the [guimenu]``Tree Path`` field, type an absolute path to the installation source.
    For example, [path]``/srv/images/sle15sp2``.
* In the [guimenu]``Base Channel`` field, select [systemitem]``SLE-Product-SUSE-Manager-Proxy-4.1-Pool for x86_64``.
* In the [guimenu]``Installer Generation`` field, select [systemitem]``SUSE Linux Enterprise 15``.
* In the [guimenu]``Kernel Options`` field, type any options to be passed to the kernel when booting for the installation.
    The [option]``install=`` parameter and the [option]``self_update=0 pt.options=self_update`` parameter are added by default.
* In the [guimenu]``Post Kernel Options`` section, type any options to  be passed to the kernel when booting the installed system for the first time.
. Click btn:[Create Autoinstallable Distribution] to save.


When you have created an autoinstallable distribution, you can edit it by navigating to  menu:Systems[Autoinstallation > Distributions] and selecting the distribution you want to edit.



== Create an Autoinstallation Profile

Autoinstallation profiles contain all the installation and configuration data needed to install a system.
They can also contain scripts to be executed after the installation is complete.
For example scripts that you can use as a starting point, see https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST.
For valid AutoYaST upgrade settings, see https://doc.opensuse.org/projects/autoyast/#CreateProfile-upgrade.


.Procedure: Creating an Autoinstallation Profile
. In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > Profiles] and upload your autoinstallation profile script.
    For example scripts that you can use as a starting point, see https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST.
. In the ``Kernel Options`` field, type ``autoupgrade=1``.
    Optionally, you can also include the ``Y2DEBUG=1`` option.
    The debug setting is not required but can help with investigating any future problems you might encounter.
. Paste the autoinstallation profile or use the file upload field.
. Click btn:[Create] to save.
. When the uploaded profile requires variables to be set, navigate to menu:Systems[Autoinstallation > Profiles], select the profile to edit, and navigate to the [guimenu]``Variables`` tab.
    Specify the required variables, using this format:
+
----
<key>=<value>
----

[NOTE]
====
For proxies that were registered using Salt, use the ``spacewalk/minion_script`` snippet to register the proxy again after migration has completed.
====



== Migration

Before you begin, check that all the channels referenced in the autoinstallation profile are available and fully synchronized.



.Procedure: Migrating
. On the {productname} Server {webui}, navigate to menu:Systems[System List], select the proxy, navigate to the [guimenu]``Provisioning`` tab, and select the autoinstallation profile you uploaded.
. Click btn:[Schedule Autoinstallation and Finish].
    The system will download the required files, change the bootloader entries, reboot, and start the upgrade.



== Clean Up

When the {productname} Proxy has finished upgrading, it shows the originally assigned channels.
Cleaning up after the migration ensures the correct channels are shown.


[WARNING]
====
If the server reports that there are updates available for the proxy, do not apply them before completing the cleanup.
====



.Procedure: Cleaning Up
. On the {productname} Server {webui}, navigate to the [guimenu]``System List``, select the proxy, and navigate to the menu:Software[Software Channels] subtab.
. Clear the old channels.
. In the [guimenu]``Base Channel`` field, select `SLE-Product-SUSE-Manager-Proxy-4.1-Pool for x86_64`.
. In the [guimenu]``Child Channels`` field, select all the recommended channels.
