[[proxy-uyuni-upgrade]]
= Proxy - Upgrade Procedure

Before you perform any proxy update, schedule a maintenance window.
The clients registered to {productname} through the proxy will not be able to connect to {productname} while the update is in progress.
For more information about maintenance windows, see xref:administration:maintenance-windows.adoc[].

== Preparation

As a preparation step, add the openSUSE Leap {opensuse-version} channels to the server.

.Procedure: Adding Software Channels at the Command Prompt
. At the command prompt on the {productname} Server, as root, use the [command]``spacewalk-common-channels`` command to add the appropriate channels:
+
----
spacewalk-common-channels opensuse_leap15_3 \
opensuse_leap15_3-non-oss \
opensuse_leap15_3-non-oss-updates \
opensuse_leap15_3-updates \
opensuse_leap15_3-backports-update \
opensuse_leap15_3-sle-updates \
opensuse_leap15_3-uyuni-client \
uyuni-proxy-stable-leap-153
----
. Fully synchronize all channels with [command]``spacewalk-repo-sync``.

== Upgrade the Proxy

To upgrade a proxy you first stop the proxy service, then you replace the software repositories and update the software, and finally you restart the proxy service.



.Procedure: Updating the {productname} Proxy

. In the {productname} Server {webui}, navigate to proxy system's  details page, click the [guimenu]``Reactivation`` subtab.

. Click btn:[Generate New Key] to generate a reactivation key.
+
////
With a system profile specific activation key, this system can be re-registered using the 'rhnreg_ks' command-line utility. The system will be re-registered with the same id, history, groups, and channels (unless the system's base channel changes).
Key: 	  re-1-1008b9843d44dac77f0a856f207cc2c6
////

. On the {productname} Proxy, stop the proxy service:
+
----
spacewalk-proxy stop
----

. In the {productname} Server {webui}, navigate to menu:Systems[Proxy] and click the name of the proxy.
. Click menu:Software[Software Channels], and as the base channel select the openSUSE Leap {opensuse-version} channel that is listed in the [systemitem]``Customs Channels`` list.
. In the [guimenu]``Child Channels`` pane, select the {opensuse-version} child channels.
. Click btn:[Next], and [guimenu]``Confirm Software Channel Change`` with btn:[Confirm].
. Click menu:Software[Packages > Upgrade], and select all the packages to be updated on the proxy, and then apply the selection.
. Re-register with the reactivation key using the [command]``rhnreg_ks`` command-line utility.
  The system is re-registered with the same ID, history, and groups.
+
// and channels (unless the system's base channel changes).
. On the {productname} Proxy, start the proxy service:
+
----
spacewalk-proxy start
----

If you need to update many proxies, you can create an action chain of this command sequence on the {productname} Server.
You can use the action chain to perform updates on multiple proxies at the same time.
