[[server-y-zypper]]
= Server - Minor Version Upgrade with Zypper


To perform the upgrade with Zypper, use the Zypper migration tool.



.Procedure: Upgrading with Zypper

. From the command prompt, as root, ensure the spacewalk services are not running:
+
----
spacewalk-service stop
----
+ 
. Launch the Zypper migration tool:
+
----
zypper migration
----
Zypper will show the possible migration targets with detailed summaries.
. Select the appropriate target, and follow the prompts to complete the migration.
. Reboot the server.
. When rebooted the {productname} spacewalk services are not running until you have migrated the PostgreSQL database to version{nbsp}13.
. Log in on the text console as root.
  If you are upgrading from 4.0 or 4.1 to 4.2, run the database migration script:
+
----
/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh
----
. Ensure the spacewalk services are running:
+
----
spacewalk-service start
----
+
[NOTE]
====
[command]``spacewalk-schema-upgrade`` is not needed anymore.
It will be run during [command]``spacewalk-service start`` automatically.
====

If the process fails, check these issues first:

* If Zypper does not have the migration tool available, install the [package]``zypper-migration-plugin`` package.
* If there are older updates available, Zypper will notify you and ask to install them first.
    You must install all updates before performing the upgrade.
