[[server-y-zypper]]
= Server - Minor Version Upgrade with Zypper


To perform the upgrade with Zypper, use the Zypper migration tool.


[NOTE]
====
Before upgrading from {productname} 4.0 to 4.1, ensure you do not have any unpublished patches.
Check for unpublished patches by navigating to menu:Patches[Manage Patches > Unpublished].
You must publish or delete them before you upgrade.

For more information, see https://www.suse.com/releasenotes/x86_64/SUSE-MANAGER/4.1/index.html#_dropped_features.
====



.Procedure: Upgrading with Zypper
. From the command prompt, as root, launch the Zypper migration tool:
+
----
zypper migration
----
Zypper will show the possible migration targets with detailed summaries.
. Select the appropriate target, and follow the prompts to complete the migration.
. Reboot the server.
. When rebooted the spacewalk services are not running until you have migrated the PostgreSQL database to version{nbsp}12.
. Log in on the text console as root, and run the database migration script:
+
----
/usr/lib/susemanager/bin/pg-migrate-10-to-12.sh
----
. Ensure the spacewalk services are running:
+
----
spacewalk-service start
----
+
[NOTE]
====
[command]``spacewalk-schema-upgrade`` is not needed anymore.
It will be run during [command]``spacewalk-service start`` automatically.
====

If the process fails, check these issues first:

* If Zypper does not have the migration tool available, install the [package]``zypper-migration-plugin`` package.
* If there are older updates available, Zypper will notify you and ask to install them first.
    You must install all updates before performing the upgrade.
