[server-major-upgrade]
= Server - Major Upgrade

When {productname} core components are upgraded to new major versions, you need to perform a major upgrade on the {productname} Server.
This is the case if a version upgrade of PostgreSQL, Salt, or openSUSE Leap is needed.
openSUSE Leap is the underlying base operating system (OS).

[IMPORTANT]
====
Some additional manual steps might be required, and this information is only available in the release notes.
For important extra information about your upgrade, see the release notes at:

https://www.uyuni-project.org/pages/stable-version.html.
====


The [command]``server-migrator.sh`` script migrates {productname} Server to the latest version.
It also upgrades the underlying operating system to version {opensuse-version}.
The script is part of the [package]``susemanager`` package.


The version of PostgreSQL you are using depends on the underlying operating system.
{opensuse}{nbsp}Leap{nbsp}15.2 uses PostgreSQL{nbsp}12, so this is the version used by {uyuni} on that operating system.
{opensuse}{nbsp}Leap{nbsp}15.3 is expected to have PostgreSQL{nbsp}13.



.Procedure: Migrating the {productname} Server
. Before running the [command]``server-migrator.sh`` script, check whether the most recent version of the [package]``susemanager`` package is installed:
+
----
zypper ref
zypper up susemanager
----
. Run the [command]``/usr/lib/susemanager/bin/server-migrator.sh`` script to upgrade the base OS and {productname} Server.
. To migrate the database to PostgreSQL 12 run the migrate script:
+
----
/usr/lib/susemanager/bin/pg-migrate-10-to-12.sh
----
+
For more information about PostgreSQL database migration, see xref:db-migration-12.adoc[].
. To migrate the database to PostgreSQL 13 from PostgreSQL 12 run the migration script:
+
----
/usr/lib/susemanager/bin/pg-migrate-12-to-13.sh
----
+
For more information about PostgreSQL database migration, see xref:db-migration-13.adoc[].
. To migrate the database to PostgreSQL 13 from PostgreSQL 10 run the migration script:
+
----
/usr/lib/susemanager/bin/pg-migrate-10-to-13.sh
----
+
For more information about PostgreSQL database migration, see xref:db-migration-13.adoc[].
. After the migration is complete, manually reboot the {productname} Server:
+
----
shutdown -r now
----


[IMPORTANT]
====
You will not be able to fix issues that arise during the migration.
Ensure you have created a backup before you start the migration.
If you are running {productname} Server on a virtual machine, we recommend that you create a snapshot before you start.
====
