[server-major-upgrade]
= Server - Major Upgrade

When {productname} core components are upgraded to new major versions, you need to perform a major upgrade on the {productname} Server.
This is the case if a version upgrade of PostgreSQL, Salt, or openSUSE Leap is needed.
openSUSE Leap is the underlying base operating system (OS).

[IMPORTANT]
====
Some additional manual steps might be required, and this information is only available in the release notes.
For important extra information about your upgrade, see the release notes at https://www.uyuni-project.org/pages/stable-version.html.
====


.Procedure: Migrating the {productname} Server

The [command]``server-migrator.sh`` script migrates {productname} Server to the latest version.
It also upgrades the underlying operating system to version {opensuse-version}.
The script is part of the [package]``susemanager`` package.

. Before running the [command]``server-migrator.sh`` script, check whether the most recent version of the [package]``susemanager`` package is installed:
+
----
zypper ref
zypper up susemanager
----

. Run the [command]``/usr/lib/susemanager/bin/server-migrator.sh`` script to upgrade the base OS and {productname} Server.
// During migration the script will stop the spacewalk services.

. After the migration is complete, you will need to manually reboot the {productname} Server.

[IMPORTANT]
====
You will not be able to fix issues that arise during the migration.
Ensure you have created a backup before you start the migration.
If you are running {productname} Server on a virtual machine, we recommend that you create a snapshot before you start.
====
