[[update.suse.manager]]
= Updating the {productname} Server



This section provides information on performing regular updates and running a [command]``spacewalk-schema-upgrade`` on your PostgreSQL database.

.Procedure: Updating {productname}
. As the root user, stop Spacewalk services:
+

----
spacewalk-service stop
----
. Apply the latest patches:
+

----
zypper patch
----
. You will be informed if a new database schema was included in the latest patch. Ensure the database service is running:
+

----
rcpostgresql start
----
. Perform the upgrade:
+

----
spacewalk-schema-upgrade
----

. Restart Spacewalk services:
+

----
spacewalk-service start
----
+

[IMPORTANT]
.Restart of Services and Applications
====
Services affected by a package update are not automatically restarted after an update.
You need to restart these services manually to avoid potential failures.

You may use [command]``zypper ps`` to check for any applications which may be using old code.
Restart these applications.
====


