[[upgrade-script-examples]]
= Sample Autoinstallation Scripts


This section contains example autoinstallation scripts.

If you use these profiles, check which variables they use.
When the uploaded profile requires variables to be set, navigate to menu:Systems[Autoinstallation > Profiles], select the profile to edit, and navigate to the [guimenu]``Variables`` tab.
Specify the required variables, using this format:

----
<key>=<value>
----

For all installations, the ``$redhat_management_server`` variable will be set automatically and does not need to be defined.

These examples use the ``$distrotree`` variable, which must be defined as the distribution label used with this profile.
Set the variable to the same value that you selected in ``Autoinstall Tree`` in the [guimenu]``Details`` tab.
Example:

----
distrotree=sles_sap15sp2-x86_64
----

when the distribution label is [systemitem]``sles_sap15sp2-x86_64``.


== Upgrading from SLES{nbsp}12{nbsp}SPn to SLES{nbsp}15{nbsp}SP2

Use this script as the basis for an upgrade from SLES{nbsp}12{nbsp}SPn to SLES{nbsp}15{nbsp}SP2.
Check the official product documentation to find the supported upgrade paths.

.Example: Script for Upgrading from SLES{nbsp}12{nbsp}SPn to SLES{nbsp}15{nbsp}SP2

You can find the AutoYaST file at https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST/


== Upgrading a {productname} Proxy from 3.2 to 4.1

Use this script as the basis for an upgrade from {productname} Proxy 3.2 to {productname} Proxy 4.1.

.Example: Script for Upgrading from {productname} Proxy 3.2 to {productname} Proxy 4.1

You can find the AutoYaST file at https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST/



== Upgrading an SAP Client from SLE{nbsp}12 to SLE{nbsp}15{nbsp}SP2

Use this script as the basis for an upgrade from SLE{nbsp}12{nbsp}SPn to SLE{nbsp}15 SP2.
Check the official product documentation to find the supported upgrade paths.

.Example: Script for Upgrading an SAP Client from SLE{nbsp}12{nbsp}SP4 to SLE{nbsp}15 SP2


You can find the AutoYaST file at https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST/
