[[upgrade-overview]]
= Introduction

**Publication Date:** {docdate}

{productname} has three main components, all of which need regular updates.
This guide covers updating the {productname} Server, Proxy, and clients, as well as some underlying components, such as the database.

It is possible to automate some of the upgrades, but others need to be performed manually.

[NOTE]
====
This guide is not intended to be read cover to cover.
Instead, navigate to the component you want to upgrade, then identify the versions you are upgrading from and to.
====


{productname} uses an [literal]``X.Y.Z`` versioning schema.
The update procedure you need depends on which version you are upgrading from and to:

* X: If you are migrating the server from a major version to the next major version, see xref:migrate-3x-4x.adoc[].
* Y: If you are upgrading the server within the same major version (service pack migration), see xref:upgrade:migrate-4x-4x.adoc[].
* Z: If you are updating the server within the same minor version (maintenance update), see xref:server-update.adoc[].


In addition to updating the operating of the server, you are also likely to need to update other underlying technologies, including the database.
For more information about updating the database, see xref:db-migration.adoc[].

If you are updating the {productname} Proxy, see xref:proxy-update.adoc[] and xref:proxy-migration.adoc[].

If you are updating clients, see See xref:client-migration.adoc[].
