[[ref-cli-bootstrap]]
= Bootstrapping Command Line Tools
:description: Learn how to create and manage a bootstrapping command-line environment using the `mgr-create-bootstrap-repo` tool on your SUSE Manager Server
:revdate: 2020-10-15
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Manager
:page-product-version: 4.3

The ``mgr-create-bootstrap-repo`` tool allows you to create a bootstrap repository.

Use the ``mgr-create-bootstrap-repo`` command on the {productname} Server to create a new bootstrap repository.
The ``-l`` option lists all available repositories:

----
mgr-create-bootstrap-repo -l
----

Give the repository name to create the bootstrap repository you require:

----
mgr-create-bootstrap-repo <repo-name>
----

You can also create a new bootstrap repository from a custom channel, with the ``--with-custom-channels`` option:

----
mgr-create-bootstrap-repo --with-custom-channels
----

If you create a bootstrap repository that contains custom channels, and later attempt to rebuild with the ``mgr-create-bootstrap-repo`` command, the custom channel information will remain in the bootstrap repository.
To remove custom channel information from your bootstrap repository, use the [code]``--flush`` option when you rebuild:

----
mgr-create-bootstrap-repo --flush
----
