[[ref-cli-bootstrap]]
= Bootstrapping Command Line Tools

The `mgr-create-bootstrap-repo` tools allows you to create a bootstrap repository.


[[at.clitools.createbootstraprepo]]
== Creating a Bootstrap Repository (mgr-create-bootstrap-repo)


The [code]``mgr-create-bootstrap-repo`` command is used on the {productname} Server to create a new bootstrap repository.

Use the [code]``-l`` option to list all available repositories:

----
# mgr-create-bootstrap-repo -l
----

You can then invoke the command with the appropriate repository name to create the bootstrap repository you require, for example:

----
# mgr-create-bootstrap-repo SLE-version-x86_64
----


[[at.clitools.createbootstraprepo.customchannels]]
=== Creating a Bootstrap Repository with Custom Channels

Custom channels are channels that have been created to manage any custom packages that an organization might require.
To create a new bootstrap repository from a custom channel, use the [code]``mgr-create-bootstrap-repo`` command with the [code]``with-custom-channels`` option:

----
# mgr-create-bootstrap-repo --with-custom-channels
----

.Flushing a Bootstrap Repository to Remove Custom Channels
[NOTE]
====
If you create a bootstrap repository that contains custom channels, and later attempt to rebuild with the [code]``mgr-create-bootstrap-repo`` command, the custom channel information will remain in the bootstrap repository.
If you want to remove custom channel information from your bootstrap repository, you will need to use the [code]``flush`` option when you rebuild:

----
# mgr-create-bootstrap-repo --flush
----
====
