[[ref-cli]]
= Command Line Tools

There are several command line tools available in {productname}.
Every action that can be completed using the {webui} can be performed at a command prompt instead.
Additionally, there are some actions that can only be performed at the command prompt.

Manage package and channel synchronization with:

* ``spacewalk-repo-sync``
* ``mgr-sync``

Manage bootstrapping with:

* ``mgr-create-bootstrap-repo``

Manage the database with:

* ``smdba``


Some of these command line tools are installed by default.
To install a command line tool, you can use the {productname} {webui}, or use your package manager at the command prompt.



.Procedure: Installing Command Line Tools with the WebUI
. In the {productname} {webui}, navigate to menu:Systems[System List], select the client to install the tool on, and navigate to the menu:Software[Packages > Install] sub-tab.
. Use the search tool to search for the command line tool you want to install.
. Check the package to install, and click btn:[Install Selected Packages].
. Click btn:[Confirm] to begin installation.



.Procedure: Installing Command Line Tools from the Command Prompt
// I tried this on my test install, and it worked on the client, but not the server. What's the server version? --LKB 2020-10-08
// On the server, either api/spacewalk or salt probablycan be used, I think --ke 2023-11-28
. On the client that you want to install the packages on, at the command prompt, as root, use zypper to install the package:
+
----
zypper in <CLI_TOOL_NAME>
----
