ifndef::backend-pdf[]
[[reference-guide-overview]]
= Reference

// HTML Publication date 
**Publication Date:** {docdate}

== Preface

This document is divided into several sections:  

- **{webui} Reference:** Organized to mirror the structure of the {productname} {webui}, this section allows you to quickly find relevant information while navigating the interface.  
- **spacecmd Reference:** A comprehensive guide to the [command]``spacecmd`` command-line interface. It includes an **alphabetized list** of all available commands along with their correct usage.  
- **Command Line Tools:** An overview of the various **command-line utilities** available in {productname}, helping you streamline administrative tasks. 

== Copyright Notice

// HTML Copyright
Copyright © {copyrightdate} SUSE LLC and contributors. All rights reserved.
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright
notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].

== Trademarks
// HTML Trademarks
For SUSE trademarks, see https://www.suse.com/company/legal/ . All third-party trademarks are the property
of their respective owners. Trademark symbols (®, ™ etc.) denote trademarks of SUSE and its affiliates. Asterisks
(*) denote third-party trademarks.
All information found in this book has been compiled with utmost attention to detail. However, this does not
guarantee complete accuracy. Neither SUSE LLC, its affiliates, the authors nor the translators shall be held liable
for possible errors or the consequences thereof.
endif::[]

ifdef::backend-pdf[]


<<<

[preface]
== Preface

Reference +
{productname} {productnumber}

This document is divided into several sections:  

- **{webui} Reference:** Organized to mirror the structure of the {productname} {webui}, this section allows you to quickly find relevant information while navigating the interface.  
- **spacecmd Reference:** A comprehensive guide to the [command]``spacecmd`` command-line interface. It includes an **alphabetized list** of all available commands along with their correct usage.  
- **Command Line Tools:** An overview of the various **command-line utilities** available in {productname}, helping you streamline administrative tasks. 

// PDF Publication

**Publication Date:** {docdate}

// PDF Copyright Space

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +


// PDF Copyright
Copyright © {copyrightdate} SUSE LLC and contributors. All rights reserved.
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright
notice and license. A copy of the license version 1.2 is included in the section entitled xref:legal:license.adoc[GNU Free Documentation License].

// PDF Trademarks
For SUSE trademarks, see https://www.suse.com/company/legal/ . All third-party trademarks are the property
of their respective owners. Trademark symbols (®, ™ etc.) denote trademarks of SUSE and its affiliates. Asterisks
(*) denote third-party trademarks.
All information found in this book has been compiled with utmost attention to detail. However, this does not
guarantee complete accuracy. Neither SUSE LLC, its affiliates, the authors nor the translators shall be held liable
for possible errors or the consequences thereof.

<<<

toc::[]

endif::[]