ifeval::[{mlm-content} == true]
:noindex:
endif::[]

ifndef::backend-pdf[]
[[uyuni-reference-guide-overview]]
= Reference Giide

// HTML Publication date 
**Publication Date:** {docdate}

== Preface

This document is divided into several sections:  

- **{webui} Reference:** Organized to mirror the structure of the {productname} {webui}, this section allows you to quickly find relevant information while navigating the interface.  
- **spacecmd Reference:** A comprehensive guide to the [command]``spacecmd`` command-line interface. It includes an **alphabetized list** of all available commands along with their correct usage.  
- **Command Line Tools:** An overview of the various **command-line utilities** available in {productname}, helping you streamline administrative tasks. 

endif::[]

ifdef::backend-pdf[]


<<<

[preface]
== Preface

Reference +
{productname} {productnumber}

This document is divided into several sections:  

- **{webui} Reference:** Organized to mirror the structure of the {productname} {webui}, this section allows you to quickly find relevant information while navigating the interface.  
- **spacecmd Reference:** A comprehensive guide to the [command]``spacecmd`` command-line interface. It includes an **alphabetized list** of all available commands along with their correct usage.  
- **Command Line Tools:** An overview of the various **command-line utilities** available in {productname}, helping you streamline administrative tasks. 

// PDF Publication

**Publication Date:** {docdate}

// PDF Copyright Space

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

<<<

toc::[]

endif::[]
