[[installation-general-requirements]]
= Requisitos generales

Antes de empezar la instalación, asegúrese de tener:

* Credenciales actualizadas de la organización en {scc}
* Acceso al soporte de instalación
* Entorno que cumple con los requisios de hardware y red
* Any required SSL certificates for your environment

Esta sección contiene más información de cada uno de estos requisitos.

Para una lista complea de clientes y características soporados, vea
xref:client-configuration:supported-features.adoc[].


[IMPORTANT]
====
{productname} {productnumber} se basa en SLES {sles-version} {sp-version}
como sistema operativo huésped. El ciclo de mantenimiento de {productname}
es de dos años. Para más información, vea
link:https://www.suse.com/lifecycle/[].

No se puede agregar Paquetes de Servicio de Larga Duración (LTSS) para
{sles-version} a {productname}. Tampco es posible usar SLES for SAP como
base para {productname} para incrementar el ciclo de vida del sistema
operativo subyacente.
====



[[install.scc-register]]
== Obtener sus credenciales de SUSE Customer Center

Cree una cuenta en {scc} antes de instalar {sles} y {productname}.

[[creating.scc.account.mgr]]
.Procedimiento: Obtener sus credenciales de organización de SCC
. Navegue a https://scc.suse.com/login con su navegador web.
. Acceda a su cuenta de SCC, o siga las indicaciones para crear una nueva
  cuenta.
. Si no lo ha hecho todavía, clique btn:[Conectarse a una organización] y
  teclee o busque su organización.
. Clique btn:[Gestionar mis organizaciones] y seleccione una organización de
  la lista clicando en el nombre de la organización.
. Clique la pestaña btn:[Organización] y seleccione la pestaña
  btn:[Credenciales de la organización].
. Guarde su información de acceso para uso durante la configuración de
  {productname}.

Depending on your organization's setup, you might also need to activate your
subscription, using the btn:[Activate Subscriptions] menu.



[[install.media]]
== Obtain the Unified Installer

{susemgr} Server and Proxy can be installed with the {sle} Unified
Installer.

ifeval::[{suma-content} == true]
You only require a valid registration code for {productname}.  You do not
require a separate code for SLES{nbsp}{sles-version} {sp-version}.
endif::[]

If not already done, download the {sle} Unified Installer from
https://download.suse.com/index.jsp.  Direct link to {sle} {sles-version}
{sp-version}, required to install SUSE Manager 4.1:
https://download.suse.com/index.jsp?product_id=&search=Search&families=22609&version=68287.
For a later version or a different architecture, such as {ibmz}, select the
respective item.  With the Unified Installer you can install many SLE-based
base products such as SLES, SLES for SAP Applications, or {susemgr}.



[[installation-general-supportedbrowsers]]
== Supported Browsers for the {susemgr} {webui}

In order to use the {webui} to manage your {susemgr} environment, you will
need to ensure you are running an up to date web browser.

{susemgr} is supported on:

* Latest Firefox browser shipped with {sles}
* Latest Chrome browser on all operating systems
* Latest Edge browser shipped with Windows

Windows Internet Explorer is not supported.  The {productname} {webui} will
not render correctly under Windows Internet Explorer.



== Partition Permissions

When you create disk partitions for the {productname} Server and Proxy,
ensure you set the permissions correctly.

For [path]``/var/lib/pgsql``:

* Owner: Read, Write, Execute
* Group: Read, Execute
* User: None

For [path]``/var/spacewalk``:

* Owner: Read, Write, Execute
* Group: Read, Write, Execute
* User: Read, Execute

Check the permissions with this command:

----
ls -l /var/lib/pgsql /var/spacewalk
----

The output should look like this:

----
drwxr-x--- 1 postgres postgres /var/lib/pgsql
drwxrwxr-x 1 wwwrun   www      /var/spacewalk
----

If required, change the permissions with these commands:

----
chmod 750 /var/lib/pgsql
chmod 775 /var/spacewalk
----

And owners with:

----
chown postgres:postgres /var/lib/pgsql
chown wwwrun:www /var/spacewalk
----



== SSL Certificates

{productname} uses SSL certificates to ensure that clients are registered to
the correct server.  By default, {productname} uses a self-signed
certificate.  If you have certificates signed by a third-party CA, you can
import them to your {productname} installation.

* For more on self-signed certificates, see
  xref:administration:ssl-certs-selfsigned.adoc[].
* For more on imported certificates, see
  xref:administration:ssl-certs-imported.adoc[].
