[[public-cloud-requirements]]
= Public Cloud Requirements

You can run {productname} Server on a public cloud instance from a
third-party provider such as Amazon EC2, or Microsoft Azure.

This section details the requirements for using {productname} on a public
cloud instance.

[NOTE]
====
Public clouds provide {productname} under a Bring Your Own Subscription
(BYOS) model.  This means that you must register instances with the {scc}.
For more information about registering {productname} with {scc}, see
xref:installation:general-requirements.adoc[].
====

Depending on the public cloud framework you are using, you can locate the
{productname} images by searching for the keywords ``suse``, ``manager``,
``proxy``, or ``BYOS``.


== Instance Requirements

Select a public cloud instance type that meets the hardware requirements in
xref:installation:hardware-requirements.adoc[].

Before you begin, here are some other considerations:

* The {productname} setup procedure performs a forward-confirmed reverse DNS
  lookup.  This must succeed in order for the setup procedure to complete and
  for {productname} to operate as expected.  It is important to perform
  hostname and IP configuration before you set up {productname}.
* {productname} Server and Proxy instances need to run in a network
  configuration that provides you control over DNS entries, but cannot be
  accessed from the internet at large.
* Within this network configuration DNS resolution must be provided: `hostname
  -f` must return the fully-qualified domain name (FQDN).
* DNS resolution is also important for connecting clients.
* DNS is dependent on the cloud framework you choose.  Refer to the cloud
  provider documentation for detailed instructions.
* We recommend that you locate software repositories, the server database, and
  the proxy squid cache on an external virtual disk.  This prevents data loss
  if the instance is unexpectedly terminated.  This section includes
  instructions for setting up an external virtual disk.


[NOTE]
====
If you are attempting to bootstrap traditional clients, check that you can
resolve the host name of the server while you are logged in to the client.
You might need to add the FQDN of the server to [path]``/etc/hosts`` local
resolution file on the client.  Check using the [command]``hostname -f``
command with the local IP address of the server.
====



== Network Requirements

When you use {productname} on a public cloud, you must use a restricted
network.  We recommend using a VPC private subnet with an appropriate
firewall setting.  Only machines in your specified IP ranges must be able to
access the instance.

[WARNING]
====
When you run {productname} on public clouds, you must apply security
measures to limit access to the instance.  A world-accessible {productname}
instance violates the terms of the {productname} EULA, and is not supported
by {suse}.
====

To access the {productname} {webui}, allow HTTPS when configuring the
network access controls.



== Separate Storage Volumes

We recommend that the repositories and the database for {productname} are
stored on separate storage devices.  This will help to avoid data loss in
cases when the {productname} instance is terminated.  You must set up the
storage devices before you run the YaST {productname} setup procedure.

Provision two disk devices in the public cloud environment, according the
cloud provider's documentation.  The size of the disk for repositories
storage is dependent on the number of distributions and channels you intend
to manage with {productname}.  For recommended minimum sizes for the
database volume ([path]``/var/lig/pgsql``) and channel volume
([path]``/var/lib/spacewalk``), see
xref:installation:hardware-requirements.adoc[].

When you attach the virtual disks, they will appear in your instance as Unix
device nodes.  The names of the device nodes will vary depending on your
provider, and the instance type selected.

On your {productname} Server, use this command to find all available storage
devices:

----
hwinfo --disk | grep -E "Device File:"
----

Use the [command]``lsblk`` command to see the name and size of each device.
Choose the name that matches with the size of the virtual disk you are
looking for.

Use the [command]``suma-storage`` command with the device names to set up
the external disks as the locations for the database and repositories:

----
suma-storage <channel_devicename> [<database_devicename>]
----

The external storage volumes are set up as XFS partitions mounted at
[path]``/manager_storage`` and [path]``/pgsql_storage``.

It is possible to use the same storage device for both channel data and
database.  This is not recommended, as growing channel repositories might
fill up the storage, which poses a risk to database integrity.  Using
separate storage devices may also increase performance.  If you want to use
a single storage device, run [command]``suma-storage`` with a single device
name parameter.

If you are installing a proxy, the [command]``suma-storage`` command only
takes a single device name parameter and will set up the external storage
location as the Squid cache.
