[[install-vm-vmware]]
= {productname} {productnumber} 서버를 가상 머신으로 배포 - VMware
:revdate: 2025-07-09
:page-revdate: {revdate}
ifeval::[{uyuni-content} == true]

:noindex:
endif::[]

이 장에서는 {productname} {productnumber}을(를) 이미지로 배포하는 데 필요한 가상 머신 설정을 제공합니다. 이 설치에는 VMware가 샌드박스로 사용됩니다.


// FIXME: make this and later sections a snippet or move it to a general
//        intro for both, KVM and VMware
== 사용 가능한 이미지


[IMPORTANT]
====
{productname} {productnumber} 서버의 배포를 위해 선호되는 방법은 다음 사용 가능한 이미지 중 하나를 사용하는 것입니다. 이러한 이미지에는 배포를 크게 간소화하는 모든 도구가 포함되어 있습니다.
====

{productname} {productnumber}에 대한 이미지는 link:https://www.suse.com/download/suse-manager/[{productname} {productnumber} VM 이미지]에서 제공됩니다.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-warn-images-sl-micro.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-warn-images-sl-micro.adoc[]
endif::[]

[NOTE]
====
Raw 이미지 준비에 대한 자세한 내용은 https://documentation.suse.com/sle-micro/6.1/html/Micro-deployment-raw-images-virtual-machines/index.html#deployment-preparing-configuration-device[]에서 확인할 수 있습니다.
// For the 5.0 backport:
// For more information on preparing raw images, see link:https://documentation.suse.com/en-us/sle-micro/5.5/single-html/SLE-Micro-deployment/#sec-raw-preparation[].

이미지 자체 설치에 대한 자세한 내용은 https://documentation.suse.com/sle-micro/6.1/html/Micro-deployment-selfinstall-images/index.html[]에서 확인할 수 있습니다.
====

.사용할 수 있는 서버 이미지
[cols="3, 3", options="header"]
|===
| 아키텍처 | 이미지 형식

| aarch64| qcow2, vmdk

| x86_64  | qcow2, vmdk, 원시, 자체 설치 프로그램

| ppc64le | 원시, 자체 설치 프로그램

| s390x * | qcow2, 원시
|===

__* s390x용으로 사용할 수 있는 2개의 스토리지 옵션: CDL DASD 및 FBA.__





[[quickstart.sect.vmware.settings]]
== {productname} 가상 머신 설정 - VMware

이 섹션에서는 VMware 환경 내 {productname} 스토리지 파티션에 필수인 추가 가상 디스크 생성을 중심으로 VMware 구성을 설명합니다.

.절차: VMware 가상 머신 생성

. {productname} 서버 [filename]``.vmdk`` 파일을 다운로드한 다음 사본을 VMware 스토리지로 전송합니다.

. VMware 웹 인터페이스를 사용하여 업로드된 [filename]``.vmdk`` 파일의 사본을 만듭니다. 이렇게 하면 제공된 [filename]``.vmdk`` 파일이 vSphere 하이퍼바이저에 적합한 형식으로 변환됩니다.

. 게스트 OS 제품군 [systemitem]``Linux`` 및 게스트 OS 버전 {sle} 15(64비트)를 기반으로 새 가상 시스템을 생성하고 이름을 지정합니다.

+

. 500GB(또는 그 이상)의 추가적인 [systemitem]``Hard Disk 2``를 추가합니다.

. RAM 및 CPU 수를 최솟값으로 구성합니다. *)

. 필요에 따라 네트워크 어댑터를 설정합니다.

. VM의 전원을 켜고 최초 부팅 대화 상자(키보드 레이아웃, 사용권 계약, 표준 시간대, 루트 비밀번호)를 따릅니다.

. 설치가 완료되면 루트로 로그인합니다.

. 다음 섹션을 진행합니다.

*) 최소 값은 xref:installation-and-upgrade:hardware-requirements.adoc#proxy-hardware-requirements[]에서 확인할 수 있습니다.


[[minimal.susemgr.prep]]
== {sl-micro} 및 {productname} {productnumber} 서버 등록

시작하기 전에 {scclongform} - https://scc.suse.com[]에서 {productname} 등록 코드를 받으십시오.

[NOTE]
====
{sl-micro} {microversion} 권한은 {productname} 권한 내에 포함되어 있으므로 별도의 등록 코드가 필요하지 않습니다.
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
endif::[]

.절차: {sl-micro} 및 {productname} {productnumber} 등록
. 가상 머신을 부팅합니다.
. **`root`** 로 로그인합니다.
. {scc}를 사용하여 {sl-micro}을(를) 등록합니다.
+

----
transactional-update register -r <REGCODE> -e <your_email>
----

. 재부팅합니다.

. {scclongform}을(를) 사용하여 {productname} {productnumber}을(를) 등록합니다.
+

----
transactional-update register -p Multi-Linux-Manager-Server/5.1/x86_64 -r <REGCODE>
----

. 재부팅
. 시스템 업데이트:
+

----
transactional-update
----

. 업데이트가 적용된 경우 재부팅합니다.

. 이 단계는 선택 사항입니다. 그러나 인프라에 사용자 정의 영구 스토리지가 필요한 경우 [command]``mgr-storage-server`` 도구를 사용하십시오.

+

자세한 내용은 [command]``mgr-storage-server --help``를 참조하십시오. 이 도구는 컨테이너 스토리지 및 데이터베이스 볼륨 생성을 간소화합니다. 이 명령은 다음 방법으로 사용하십시오.

+

----
mgr-storage-server <storage-disk-device> [<database-disk-device>]
----

+
예:
+

----
mgr-storage-server /dev/nvme1n1 /dev/nvme2n1
----

+
[NOTE]
====
이 명령은 [path]``/var/lib/containers/storage/volumes``에 영구 스토리지 볼륨을 생성합니다.

자세한 내용은 다음을 참조하십시오.

* xref:installation-and-upgrade:container-management/persistent-container-volumes.adoc[]
* xref:administration:troubleshooting/tshoot-container-full-disk.adoc[]
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-step-deploy-podman-certs.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../partials/snippet-step-deploy-podman-certs.adoc[]
endif::[]
