[[install-hardware-requirements]]
= 하드웨어 요구사항

ifeval::[{suma-content} == true]
이 표는 {x86_64} 및 {ppc64le} 아키텍처의 {productname} 서버 및 프록시에 대한 하드웨어와 소프트웨어 요구사항을 설명합니다.
endif::[]

ifeval::[{uyuni-content} == true]
이 표는 {x86_64} 아키텍처의 {productname} 서버 및 프록시에 대한 하드웨어와 소프트웨어 요구사항을 설명합니다.
endif::[]

ifeval::[{suma-content} == true]
{ibmz} 하드웨어 요구사항은 xref:installation:install-ibmz.adoc[]를 참조하십시오.
endif::[]

{productname} {smr} 하드웨어 요구사항은 xref:retail:retail-requirements.adoc[]을 참조하십시오.



[[server-hardware-requirements]]
== 서버 하드웨어 요구사항

{productname} 서버는 [path]``/var/spacewalk/`` 디렉토리에 패키지를 저장합니다. 이 디렉토리의 공간이 부족하면 리포지토리를 동기화할 수 없습니다. [path]``/var/spacewalk/`` 디렉토리에 필요한 공간은 미러링할 클라이언트 및 리포지토리에 따라 예상할 수 있습니다.



[cols="1,1,1", options="header"]
.{x86_64} 아키텍처에 대한 서버 하드웨어 요구사항
|===

| 하드웨어
| 세부 정보
 | 권장
 
 | CPU
 | -
 | 최소 4개의 전용 64비트 CPU 코어
 
 | RAM
 | 테스트 서버
 | 최소 8GB
 
 |
 | 기본 설치
 | 최소 16GB
 
 |
 | 프로덕션 서버
 | 최소 32GB
 
 | 디스크 공간
 | [path]``/``(루트 디렉토리)
 | 최소 24GB
 
 |
 | [path]``/var/lib/pgsql``
 | 최소 50GB
 
 |
 | [path]``/var/spacewalk``
 | {suse} 제품당 최소 50GB 및 Red Hat 제품당 360GB
 
 |
 | [path]``/var/cache``
 | 최소 10GB
 {suse} 제품당 100MB, Red Hat 또는 기타 제품당 1GB 추가.
 서버가 ISS Master인 경우 두 배의 공간.
 
 |
 | 스왑 공간
 | 3GB

|===


서버 간 동기화(ISS)에 대한 자세한 내용은 xref:administration:iss.adoc[]을 참조하십시오.



ifeval::[{suma-content} == true]
[cols="1,1,1", options="header"]
.IBM POWER8 또는 POWER9 아키텍처에 대한 서버 하드웨어 요구사항
|===

| 하드웨어
| 세부 정보
 | 권장
 
 | CPU
 |
 | 최소 4개의 전용 코어
 
 | RAM
 | 테스트 서버
 | 최소 8GB
 
 |
 | 기본 설치
 | 최소 16GB
 
 |
 | 프로덕션 서버
 | 최소 32GB
 
 | 디스크 공간
 | [path]``/``(루트 디렉토리)
 | 최소 100GB
 
 |
 | [path]``/var/lib/pgsql``
 | 최소 50GB
 
 |
 | [path]``/var/spacewalk``
 | SUSE 제품당 최소 50GB 및 Red Hat 제품당 360GB
 
 |
 | [path]``/var/cache``
 | 최소 10GB
 {suse} 제품당 100MB, Red Hat 또는 기타 제품당 1GB 추가.
 서버가 ISS Master인 경우 두 배의 공간.
 
 |
 | 스왑 공간
 | 3GB

|===



endif::[]




== 프록시 하드웨어 요구사항

[cols="1,1,1", options="header"]
.프록시 하드웨어 요구사항
|===

| 하드웨어
| 세부 정보
 | 권장
 
 | CPU
 |
 | 최소 2개의 전용 64비트 CPU 코어
 
 | RAM
 | 테스트 서버
 | 최소 2GB
 
 |
 | 프로덕션 서버
 | 최소 8GB
 
 | 디스크 공간
 | [path]``/``(루트 디렉토리)
 | 최소 24GB
 
 |
 | [path]``/srv``
 | 최소 100GB
 
 |
 | [path]``/var/cache``(Squid)
 | 최소 100GB

|===


{productname} 프록시는 [path]``/var/cache/`` 디렉토리에 패키지를 캐시합니다. [path]``/var/cache/``의 공간이 부족한 경우 프록시는 사용되지 않는 오래된 패키지를 제거한 후 새 패키지로 교체합니다.

이 동작의 결과:

* 프록시에서 [path]``/var/cache/`` 디렉토리에 더 많은 공간이 확보되고 프록시와 {productname} 서버 간의 트래픽이 감소합니다.
* 프록시에서 [path]``/var/cache/`` 디렉토리의 크기와 {productname} 서버에서 [path]``/var/spacewalk/`` 의 크기를 동일하게 설정하면, 최초 동기화 후 대규모 트래픽이 발생하는 것을 방지할 수 있습니다.
* {productname} 서버의 [path]``/var/cache/`` 디렉토리는 프록시에 비해 작을 수 있습니다.
    크기 예상에 대한 설명은 <<server-hardware-requirements>> 섹션을 참조하십시오.



== 저장소 장치 및 권한

{productname}용 리포지토리와 데이터베이스는 별도의 저장소 장치에 저장하는 것이 좋습니다. 이를 통해 데이터 손실을 방지할 수 있습니다. 저장소 장치를 설정한 후 YaST {productname} 설정 절차를 실행해야 합니다.

{productname}에 필요한 3가지 다른 볼륨:

* Database volume: [path]``/var/lib/pgsql``
* 채널 볼륨: [path]``/var/spacewalk``
* 캐시: [path]``/var/cache``

모든 볼륨의 파일 시스템 형식으로는 XFS를 사용하는 것이 좋습니다. 또한, 온프레미스 설치의 경우 논리적 볼륨 관리(LVM)를 사용하여 디스크를 관리할 수 있습니다. 리포지토리 저장소의 디스크 크기는 {productname}를 사용하여 관리한 배포 및 채널의 수에 따라 다릅니다. 필요한 예상 크기에 대한 설명은 이 섹션의 테이블을 참조하십시오.

{productname} 서버에서 다음 명령을 사용하여 사용할 수 있는 모든 저장소 장치를 찾습니다.

----
hwinfo --disk | grep -E \장치 파일:
----

[command]``lsblk`` 명령을 사용하여 각 장치의 이름 및 크기를 확인합니다.

장치 이름과 함께 [command]``suma-storage`` 명령을 사용하여 외부 디스크를 데이터베이스 및 리포지토리의 위치로 설정합니다.

----
suma-storage <channel_devicename> [<database_devicename>]
----

외부 저장소 볼륨은 [path]``/manager_storage`` 및 [path]``/pgsql_storage``에 마운트된 XFS 파티션으로 설정됩니다.

채널 데이터 및 데이터베이스 모두에서 동일한 저장소 장치를 사용할 수 있습니다. 채널 리포지토리가 증가하여 저장소가 가득 차 데이터베이스 무결성이 손상될 수 있으므로 이 방법은 권장되지 않습니다. 별도의 저장소 장치를 사용하면 성능도 향상할 수 있습니다. 1개의 저장소 장치를 사용하려면 단일 장치 이름 파라미터와 함께 [command]``suma-storage`` 를 실행합니다.

프록시를 설치하는 경우에는 [command]``suma-storage`` 명령에서 단일 장치 이름 파라미터만 사용할 수 있고 외부 저장소 위치가 Squid 캐시로 설정됩니다.

{productname} 서버 및 프록시에 대한 디스크 파티션을 생성할 때는 권한을 올바르게 설정했는지 확인하십시오.

[path]``/var/lib/pgsql``의 경우:

* 소유자: 읽기, 쓰기, 실행
* 그룹: 읽기, 실행
* 사용자: 없음

[path]``/var/spacewalk``의 경우:

* 소유자: 읽기, 쓰기, 실행
* 그룹: 읽기, 쓰기, 실행
* 사용자: 읽기, 실행

다음 명령으로 권한 확인:

----
ls -l /var/lib/pgsql /var/spacewalk
----

출력은 다음과 같아야 합니다.

----
drwxr-x--- 1 postgres postgres /var/lib/pgsql
drwxrwxr-x 1 wwwrun   www      /var/spacewalk
----

필요한 경우, 다음 명령으로 권한 변경:

----
chmod 750 /var/lib/pgsql
chmod 775 /var/spacewalk
----

그리고 다음으로 소유자 변경:

----
chown postgres:postgres /var/lib/pgsql
chown wwwrun:www /var/spacewalk
----
