[[installation-network-requirements]]
= 네트워크 요구사항

이 섹션에서는 {productname}의 네트워크 및 포트 요구사항에 대한 자세한 설명을 제공합니다.

FQDN(정규화된 도메인 이름)::
{productname} 서버는 FQDN이 올바르게 확인되어야 합니다. FQDN을 확인할 수 없는 경우 여러 다른 구성 요소에서 심각한 문제가 발생할 수 있습니다.
+
호스트 이름 및 DNS의 구성에 대한 자세한 내용은 https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-network.html#sec-network-yast-change-host를 참조하십시오.

호스트 이름 및 IP 주소::
클라이언트가 {productname} 도메인 이름을 올바르게 확인하도록 하려면, 서버 및 클라이언트 머신 모두 작동하는 DNS 서버에 연결되어야 합니다. 또한, 역방향 조회도 올바르게 구성되었는지 확인해야 합니다.
+
DNS 서버 설정에 대한 자세한 내용은 https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-dns.html을 참조하십시오.

{sle} 미디어에서 설치 시 프록시 사용::
내부 네트워크에 위치하고 {scc}에 액세스할 수 없는 경우, 설치 중에 프록시를 설정 및 사용할 수 있습니다.
+
{sle} 설치 중에 {scc}에 액세스하기 위해 프록시를 구성하는 것에 대한 자세한 내용은 https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-boot-parameters.html#sec-boot-parameters-advanced-proxy를 참조하십시오.


[IMPORTANT]
====
{productname}의 호스트 이름에는 대문자가 포함되지 않아야 합니다. 그러지 않으면 _jabberd_에서 오류가 발생하게 됩니다. {productname}의 호스트 이름은 신중하게 선택해야 합니다. 서버 이름을 변경할 수 있지만 변경을 계획한 후 진행하는 것이 중요합니다. 서버의 호스트 이름을 변경하면 서버에 연결된 모든 클라이언트가 변경 사항을 인식해야 합니다.
====


프로덕션 환경에서 {productname} 서버와 클라이언트는 항상 방화벽을 사용해야 합니다. 전체 필수 포트 목록은 xref:installation:ports.adoc[]을 참조하십시오.


연결이 끊긴 설정 및 포트 구성에 대한 자세한 내용은 xref:administration:disconnected-setup.adoc#client-cfg-reg-with-bootstrap-disconnected[]를 참조하십시오.
