[[pubcloud-setup]]
= 공용 클라우드 설정

로그인하기 전 업데이트를 수신하려면 {productname} 서버를 {scc}에 등록해야 합니다.

[IMPORTANT]
====
YaST {productname} 설정 절차를 실행하기 전에 저장소 장치를 설정해야 합니다. 자세한 내용은 xref:installation:pubcloud-requirements.adoc[]을 참조하십시오.
====

클라우드 제공자의 지침에 따라 SSH를 통해 인스턴스에 연결한 후 다음 명령을 실행하여 설정을 시작하십시오.

----
yast2 susemanager_setup
----

메시지를 따르고 설정이 완료될 때까지 기다리십시오.

{yast}를 사용하여 {productname}을(를) 설정하는 방법에 대한 자세한 지침은 xref:installation:server-setup.adoc[]을 참조하십시오.




== 공용 클라우드 모듈 활성화

공용 클라우드 인스턴스에서 {productname}을(를) 사용하려면 공용 클라우드 모듈을 활성화해야 합니다.



.절차: 공용 클라우드 모듈 활성화
. {productname} 서버에서 {yast} 관리 도구를 열고 menu:소프트웨어[소프트웨어 리포지토리]로 이동합니다.
. btn:[추가]를 클릭한 후 [guimenu]``등록 서버에서 확장 및 모듈``을 선택합니다.
. [guimenu]``사용 가능한 확장`` 필드에서 [guimenu]``Public Cloud 모듈``을 선택합니다.

명령줄을 사용하려면 다음 명령으로 모듈을 추가할 수 있습니다.
----
SUSEConnect -p sle-module-public-cloud/15.2/x86_64
----

설치 절차가 완료되면 모든 필수 모듈이 설치되었는지 확인할 수 있습니다. 명령 프롬프트에 다음을 입력:

----
SUSEConnect --status-text
----

공용 클라우드의 {productname} 서버에서 예상되는 모듈은 다음과 같습니다.

* {sles} Basesystem 모듈
* Python 2 모듈
* Server Applications 모듈
* Web and Scripting 모듈
* SUSE Manager Server 모듈
* Public Cloud 모듈



== {webui}에서 설정을 완료합니다.

다음과 같은 주소를 사용하여 웹 브라우저에서 {productname} {webui}를 엽니다.

----
https://<public_IP>
----

관리자 계정으로 {productname} {webui}에 로그인합니다. 사용자 이름과 비밀번호는 공급자에 따라 다릅니다.

.기본 관리자 계정 상세 정보
[cols="1,1,1", options="header"]
|===
| 공급자              | 기본 사용자 이름Username  | Default Password
| Amazon EC2            | ``admin``         | ``<instance-ID>``
| Google Compute Engine | ``admin``         | ``<instance-ID>``
| Microsoft Azure       | ``admin``         | ``<instance-name>-suma``
|===

인스턴스 이름 또는 ID는 공용 클라우드 인스턴스 웹 콘솔 또는 명령 프롬프트에서 검색할 수 있습니다.

Amazon EC2:

----
ec2metadata --instance-id
----

Google Compute Engine:

----
gcemetadata --query instance --id
----

Microsoft Azure:

----
azuremetadata --compute --name
----


관리자 계정에 처음으로 로그인하면 자동으로 생성된 조직 이름이 제공됩니다. menu : Admin[조직]으로 이동하여 조직 이름을 편집하여 변경합니다.


[IMPORTANT]
====
관리자 계정에 처음으로 로그인하는 경우 기본 비밀번호를 변경하여 계정을 보호하십시오.
====

{productname} 서버 설정과 관련한 자세한 내용은 xref:installation:server-setup.adoc[]을 참조하십시오.


{productname} {webui}를 사용하여 필수 소프트웨어 제품을 추가하고 리포지토리 동기화를 예약하십시오. 이를 수행하기 위한 최상의 방법은 menu:Admin[설정 마법사]로 이동하고 프롬프트를 따르는 것입니다.

설정 마법사에 대한 자세한 내용은 xref:installation:setup-wizard.adoc[]을 참조하십시오.


{ubuntu} 또는 {rhel} 클라이언트를 등록하려면 사용자 정의 리포지토리 및 채널을 설정해야 합니다. 자세한 정보는 xref:client-configuration:registration-overview.adoc[]의 관련 섹션을 참조하십시오.


채널을 동기화하려면 menu:Software[관리 > 채널]로 이동하십시오. 생성한 각 채널을 클릭하고 menu:Repositories[동기화] 탭으로 이동한 다음 btn:[지금 동기화]를 클릭합니다. 이 화면에서 동기화를 예약할 수도 있습니다.


[IMPORTANT]
====
클라이언트를 부트스트랩하기 전, 해당 제품에 대해 선택한 모든 채널이 동기화되었는지 확인하십시오.

클라이언트를 부트스트랩하기 전, 해당 제품에 대해 선택한 모든 채널이 동기화되었는지 확인하십시오.
====


{productname} 서버의 설정이 완료되면 클라이언트를 등록할 수 있습니다. 공용 클라우드에 클라이언트를 등록하는 방법에 대한 자세한 내용은 xref:client-configuration:clients-pubcloud.adoc[]을 참조하십시오.
