[[setup-wizard]]
= 설치 마법사

{productname}의 설치를 완료하면 설정 마법사를 사용하여 마지막 몇 단계를 완료할 수 있습니다. 설정 마법사를 사용하면 HTTP 프록시, 조직 인증서 및 {suse} 제품을 구성할 수 있습니다.

설정 마법사는 {productname} {webui}에 처음으로 로그인하면 기본적으로 표시됩니다. menu:관리[설정 마법사]로 이동하여 설정 마법사에 직접 액세스할 수도 있습니다.



== HTTP 프록시 구성

{productname}는 프록시를 사용하여 {scc}(SCC) 또는 기타 원격 서버에 연결할 수 있습니다. 프록시를 구성하려면 [guimenu]``HTTP 프록시``로 이동합니다.

프록시의 호스트 이름을 입력합니다. ``<hostname>:<port>`` 구문을 사용합니다. 예: ``<example.com>:8080``.

필드를 지워 프록시의 사용을 비활성화할 수 있습니다.


[IMPORTANT]
====
{productname} 프록시의 사용자 이름 또는 암호를 선택할 때 ``@`` 또는 ``:`` 문자가 포함되지 않아야 합니다. 이러한 문자는 예약되어 있습니다.
====



== 조직 인증서 구성

{scc} 계정은 조직의 관리 계정과 연결됩니다. {scc} 액세스는 조직 내의 다른 사용자와 공유될 수 있습니다. [guimenu]``조직 인증서`` 탭으로 이동하여 조직 내의 사용자에게 {scc} 계정에 액세스할 수 있는 권한을 부여합니다.

btn:[새 인증서 추가]를 클릭하고 액세스 권한을 부여할 사용자의 사용자 이름 및 암호를 입력한 후 btn:[저장]을 클릭합니다. 액세스 권한을 부여한 사용자를 위한 새 인증서 카드가 표시됩니다. 카드에서 이 버튼을 사용하여 액세스를 수정하거나 철회합니다.

* 인증서 유효성 검사 상태를 확인합니다(녹색 체크 표시 또는 빨간색 엑스자 아이콘).
    SCC로 인증서를 다시 확인하려면 아이콘을 클릭합니다.
* 서버 간 동기화를 위한 기본 인증서를 설정합니다(노란색 별 모양 아이콘).
* 특정 인증서에 연결된 서브스크립션이 나열됩니다(목록 아이콘).
* 인증서를 편집합니다(연필 아이콘).
* 인증서를 삭제합니다(휴지통 아이콘).



== 제품 구성


{suse} 서브스크립션을 통해 다양한 제품에 액세스할 수 있습니다. [guimenu]``제품`` 탭으로 이동하여 사용할 수 있는 제품을 찾아보고 {scc}를 통해 {productname}와(과) 동기화합니다.

필터를 사용하면 설명 또는 아키텍처를 기준으로 제품을 검색할 수 있습니다.

목록은 제품 이름을 기준으로 구성됩니다. 각 제품에 대하여 사용될 수 있는 아키텍처를 살펴볼 수 있습니다. 제품 이름 옆의 화살표를 클릭하여 연결된 채널 및 확장을 확인합니다. btn:[채널] 아이콘을 클릭하여 각 제품과 연결된 전체 채널 목록을 확인합니다.

{sle}{nbsp}15 이상 기반 제품의 경우 필수 패키지와만 동기화하거나 권장 제품도 포함하도록 선택할 수 있습니다. 모든 제품을 동기화하려면 btn:[권장에 포함] 스위치를 켜고 필수 제품만 동기화하려면 이 스위치를 끕니다.

개별 제품을 선택하거나 선택을 취소하여 동기화할 제품을 세부적으로 설정할 수 있습니다.

선택을 완료하면 btn:[제품 추가]를 클릭한 후 btn:[새로 고침]을 클릭하여 동기화를 예약합니다.

각 제품에 대한 동기화 진행률이 제품 이름 옆의 진행률 표시줄에 표시됩니다. 선택한 제품에 따라 동기화에는 최대 몇 시간이 걸릴 수 있습니다. 동기화가 완료되면 새 제품을 {productname}에서 사용할 수 있습니다.

동기화에 실패하면 타사 GPG 키가 원인일 수 있습니다. 제품 동기화 문제 해결에 대한 자세한 내용은 xref:administration:tshoot-sync.adoc[]을 참조하십시오.
