[[proxy-register]]
= 프록시 등록

프록시 시스템은 부트스트랩 스크립트를 사용하여 Salt 클라이언트로 등록됩니다.

이 절차는 활성화 키를 사용한 소프트웨어 채널 설정 및 설치된 프록시를 {productname} 클라이언트로 등록하는 방법에 대해 설명합니다.

[IMPORTANT]
====
활성화 키를 생성하는 동안 올바른 하위 채널을 선택할 수 있기 전, openSUSE Leap 채널이 필요한 모든 하위 채널 및 {productname} 프록시 채널과 올바르게 동기화되었는지 확인합니다.
====



[[proxy-register-procedure]]
.절차: 프록시 등록

. {productname} 서버에서 [command]``spacewalk-common-channels`` 명령을 사용하여 openSUSE Leap 및 {productname} 프록시 채널을 생성합니다.
    [command]``spacewalk-common-channels``는 [package]``spacewalk-utils`` 패키지의 일부입니다.
+
----
spacewalk-common-channels \
opensuse_leap15_2 \
 opensuse_leap15_2-non-oss \
 opensuse_leap15_2-non-oss-updates \
 opensuse_leap15_2-updates \
 opensuse_leap15_2-uyuni-client \
 uyuni-proxy-stable-leap-152
----
+
[systemitem]``uyuni-proxy-stable-leap-152`` 대신, 현재 개발 버전인 [systemitem]``uyuni-proxy-devel-leap``을(를) 사용할 수도 있습니다.
+
자세한 내용은 xref:client-configuration:clients-opensuse.adoc[]을 참조하십시오.
+
. openSUSE Leap을 기본 채널로 그리고 다른 채널을 하위 채널로 하여 활성화 키를 생성합니다.
    활성화 키에 대한 자세한 내용은 xref:client-configuration:activation-keys.adoc[]을 참조하십시오.
. 프록시의 부트스트랩 스크립트를 수정합니다.
    GPG 키를 [systemitem]``ORG_GPG_KEY=`` 파라미터에 추가합니다. 자세한 내용은 xref:client-configuration:clients-opensuse.adoc[]을 참조하십시오. 부트스트랩 스크립트에 대한 자세한 내용은 xref:client-configuration:registration-bootstrap.adoc[]을 참조하십시오.
+
. 스크립트를 사용하여 클라이언트를 부트스트랩합니다.
    자세한 내용은 xref:client-configuration:registration-bootstrap.adoc[]을 참조하십시오.
. menu:Salt[키]로 이동하여 키를 수락합니다.
    키가 수락되면, 새 프록시가 [guimenu]``최근 등록된 시스템`` 섹션의 menu:시스템[개요]에 표시됩니다.
. menu:시스템 정보[소프트웨어 > 소프트웨어 채널]로 이동한 후 프록시 채널이 선택되었는지 확인합니다.

등록된 {productname} 프록시를 설정하려면 xref:uyuni-proxy-setup.adoc[]을 참조하십시오.
