[[channel-management]]
= 채널 관리
:revdate: 2025-02-28
:page-revdate: {revdate}

채널은 소프트웨어 패키지를 그룹화하는 방법입니다.

{productname}에서 채널은 운영 체제 유형, 버전 및 아키텍처별로 그룹화된 기본 채널과 관련 기본 채널과 호환되는 하위 채널과 함께 기본 및 하위 채널로 그룹화됩니다. 클라이언트가 기본 채널에 할당되면 해당 시스템에서만 관련 하위 채널을 설치할 수 있습니다. 이러한 방식으로 채널을 구성하면 호환되는 패키지만 각 시스템에 설치됩니다.

소프트웨어 채널은 리포지토리를 사용하여 패키지를 제공합니다. 채널은 {productname}의 리포지토리를 미러링하고 패키지 이름 및 기타 데이터는 {productname} 데이터베이스에 저장됩니다. 채널과 연결된 리포지토리 수에는 제한이 없습니다. 그런 다음 클라이언트를 적절한 채널에 등록하여 해당 리포지토리의 소프트웨어를 클라이언트에 설치할 수 있습니다.

기본 채널 한 개에만 클라이언트를 할당할 수 있습니다. 그런 다음 해당 기본 채널 및 해당 하위 채널과 연결된 리포지토리에서 클라이언트가 패키지를 설치하거나 업데이트할 수 있습니다.

{productname}는 {productname}를 실행하기 위해 필요한 모든 사항을 제공하는 여러 벤더 채널을 제공합니다. {productname} 관리자 및 채널 관리자에게는 채널 관리 권한이 부여되며, 이를 통해 고유 사용자 정의 채널을 생성 및 관리할 수 있습니다. 환경에서 고유한 패키지를 사용하려면 사용자 정의 채널을 생성할 수 있습니다. 사용자 정의 채널을 기본 채널로 사용하거나 벤더 기본 채널과 연결할 수 있습니다.

사용자 정의 채널에 대한 자세한 내용은 xref:administration:custom-channels.adoc[]에서 확인할 수 있습니다.



== 채널 관리


기본적으로 모든 사용자는 시스템에 채널을 구독할 수 있습니다. {webui}를 사용하여 채널에 대한 제한 사항을 구현할 수 있습니다.

.절차: 채널에 대한 구독자 액세스 제한
. {productname} {webui}에서 menu:소프트웨어[채널 목록]으로 이동하여 편집할 채널을 선택합니다.
. [guimenu]``사용자별 구독 제한 사항`` 섹션을 찾아 [guimenu]``조직 내에서 선택된 사용자만 이 채널 구독 가능``을 선택합니다. btn:[업데이트]를 클릭하여 변경 사항을 저장합니다.
. [guimenu]``구독자`` 탭으로 이동하여 필요에 따라 사용자를 선택하거나 선택을 해제합니다.



[[delete_channels]]
== 채널 삭제

명령 프롬프트에서 벤더 소프트웨어 채널을 삭제할 수 있습니다.

.절차: 벤더 채널 삭제
. {productname} 서버의 명령 프롬프트에서 루트 권한으로 사용 가능한 벤더 채널을 나열하고 삭제할 채널을 기록합니다.
+
----
mgr-sync list channels
----
. 채널을 삭제합니다.
+
----
spacewalk-remove-channel -c <channel-name>
----

ifeval::[{mlm-content} == true]
* 수동으로 채널을 삭제하는 것에 대한 자세한 내용은 xref:administration:removing-channels.adoc[]에서 확인할 수 있습니다.
endif::[]

* 사용자 정의 채널 삭제에 대한 내용은 xref:administration:custom-channels.adoc[]에서 확인할 수 있습니다.
