[[security-master-fingerprint]]
= 마스터 검증 지문에 클라이언트 설정
:revdate: 2024-12-12
:page-revdate: {revdate}


보안 수준이 높은 네트워크 구성에서는 {salt} 클라이언트가 특정 마스터에 연결하고 있는지 확인해야 하는 경우가 있습니다. 클라이언트에서 마스터로 유효성 검사를 설정하려면 먼저 {salt} 미니언 구성 파일에 마스터의 지문을 입력합니다.

* 클라이언트에서 클래식 {salt} 미니언을 사용하는 경우 [path]``/etc/salt/minion.d/custom.conf `` 또는
* 클라이언트에서 {salt} 번들을 사용하는 경우 [path]``/etc/venv-salt-minion/minion.d/custom.conf``

그리고 다음 절차를 따릅니다.

[IMPORTANT]
====
서버 컨테이너 내부의 셸에 액세스하려면 컨테이너 호스트에서 [literal]``mgrctl term``을 실행합니다.
====

.절차: 마스터의 지문을 클라이언트에 추가
. 마스터의 명령 프롬프트에서 루트 권한으로 다음 명령을 사용하여 ``master.pub`` 지문을 찾습니다.
+

----
salt-key -F master
----
+

클라이언트에서 [path]``/etc/salt/minion.d/custom.conf`` 또는 [path]``/etc/venv-salt-minion/minion.d/custom.conf`` 구성 파일을 엽니다. 이 라인을 추가하여 예제 지문을 대체할 마스터의 지문을 입력합니다.
+

----
master_finger: 'ba:30:65:2a:d6:9e:20:4f:d8:b2:f3:a7:d4:65:11:13'
----

. 서비스를 다시 시작합니다. salt-minion의 경우 다음을 실행합니다.
+

----
systemctl restart salt-minion
----
+ 
. 또는 venv-salt-minion의 경우 다음을 실행합니다.
+

----
systemctl restart venv-salt-minion
----

{salt} 번들에 대한 자세한 내용은 xref:client-configuration:contact-methods-saltbundle.adoc[]에서 확인할 수 있습니다.

클라이언트에서 보안 구성에 대한 내용은 link:https://docs.saltproject.io/en/latest/ref/configuration/minion.html[]에서 확인할 수 있습니다.
