[[support]]
= 지원

{productname}에서 {suse}의 지원을 받을 수 있는 권한이 있는 시스템을 관리할 때, [command]``supportconfig`` 또는 [command]``sosreport`` 같은 지원 데이터를 얻을 수 있습니다. 사용자는 관리형 클라이언트에서 데이터를 수집하여 SUSE 글로벌 기술 지원에 직접 업로드할 수 있습니다.

== 서비스 요청 번호 만들기

글로벌 기술 지원에 지원 데이터를 전달하기 전에 먼저 서비스 요청 번호를 생성해야 합니다.

서비스 요청을 생성하려면 https://scc.suse.com/support/requests[]로 이동하여 화면의 안내를 따르십시오. 서비스 요청 번호를 기록해 두십시오.

[NOTE]
====
**개인정보 보호 선언**

{suse}는 시스템 보고서를 기밀 데이터로 취급합니다. {suse}의 개인정보 보호 약속에 대한 자세한 내용은 https://www.suse.com/company/policies/privacy/[]에서 확인할 수 있습니다.
====


== {productname}에서 {suse}로 지원 데이터를 수집하고 업로드합니다.

.절차: {productname} {webui}를 사용한 지원 데이터 수집 및 업로드
[role=procedure]
____
. {productname} {webui}에서 menu:시스템[시스템 목록 > 모두]으로 이동하고 해당 케이스에 추가해야 할 지원 데이터가 있는 클라이언트를 선택합니다.

. 그런 다음 [guimenu]``세부 사항`` 탭으로 이동하여 [guimenu]``지원`` 하위 탭을 선택합니다.

. [literal]``Support Case Number`` 필드에 위에서 생성한 서비스 요청 번호를 입력합니다.

. [literal]``Upload Region`` 필드에서 데이터를 업로드할 서버에 따라 [literal]``EU`` 또는 [literal]``US`` 옵션을 선택합니다.

. [literal]``Command-line Arguments`` 필드에는 대상 시스템에서 데이터 수집을 위해 사용되는 도구에 대한 옵션을 입력할 수 있습니다. 사용될 도구는 이 필드 아래의 팁에서 확인할 수 있습니다.

. [literal]``시작 시간`` 필드에서 이 작업을 실행할 시간을 선택합니다.

. btn:[일정] 버튼을 클릭합니다. 작업이 예약되어 정해진 시간에 실행됩니다. 클라이언트에서 데이터를 수집하여 업로드 서버에 직접 업로드합니다.
____

[NOTE]
====
지원 데이터를 수집할 수 있는 지원되는 제품:

- {productname} 프록시
- 허브 시나리오에서 주변기기 서버로 등록된 {productname} 서버
- 모든 {sle} 및 {opensuse} 클라이언트
- SUSE Liberty 및 호환 클라이언트
- Ubuntu 클라이언트
- Debian 클라이언트
====


[NOTE]
====
기본 {productname} 서버의 지원 데이터를 업로드하려면 컨테이너 호스트에서 [command]``mgradm support config``를 사용합니다.
====
