[[users]]
= 사용자
:revdate: 2025-07-24
:page-revdate: {revdate}

{productname} 관리자는 새 사용자를 추가하고 권한을 부여하며 사용자를 비활성화 또는 삭제할 수 있습니다. 대규모 사용자를 관리하는 경우 사용자를 시스템 그룹에 할당하여 그룹 수준에서 권한을 관리할 수 있습니다. 언어 및 테마 기본값을 포함하여 {webui}의 시스템 기본값을 변경할 수도 있습니다.


[NOTE]
====
[guimenu]``사용자`` 메뉴는 {productname} 관리자 계정으로 로그인한 경우에만 사용할 수 있습니다.
====


{productname} 사용자를 관리하려면 menu:사용자[사용자 목록 > 전체]로 이동하여 {productname} 서버의 모든 사용자를 확인합니다. 목록의 각 사용자와 관련해서는 사용자 이름, 실명, 할당된 역할, 사용자가 마지막으로 로그인한 날짜 및 사용자의 현재 상태가 표시됩니다. btn:[사용자 생성]을 클릭하여 새 사용자 계정을 생성합니다. 사용자 이름을 클릭하여 [guimenu]``사용자 세부 사항`` 페이지로 이동합니다.

조직에 새 사용자를 추가하려면 btn:[사용자 생성]을 클릭하고 새 사용자에 대한 세부 사항을 입력한 후 btn:[로그인 생성]을 클릭합니다.


[[users.password.requirments]]
== 비밀번호 요구사항


{productname}은(는) 기본값으로 선택되어 배송됩니다.

모든 새 사용자 비밀번호가 조직의 보안 표준을 준수할 수 있도록 {productname} 관리자에는 비밀번호 생성 규칙을 강제 적용할 수 있는 옵션이 있습니다.

{webui}에서 menu:관리자[관리자 구성 > 비밀번호 정책]으로 이동하여 비밀번호 요구 사항을 정의합니다. 다음 필드를 조합하여 사용하십시오.

비밀번호 최소 길이::
이 필드를 사용하여 비밀번호의 최소 길이를 정의합니다.

비밀번호 최대 길이::
이 필드를 사용하여 비밀번호의 최대 길이를 정의합니다.

숫자 필요::
이 필드를 사용하여 비밀번호에 숫자(0~9)를 포함해야 하는지 여부를 지정합니다.

소문자 필요::
이 필드를 사용하여 비밀번호에 소문자(a~z)를 포함해야 하는지 여부를 지정합니다.

대문자 필요::
이 필드를 사용하여 비밀번호에 대문자(A~Z)를 포함해야 하는지 여부를 지정합니다.

연속 문자 제한::
이 필드를 사용하여 연속 문자를 제한할지 여부를 지정합니다.

특수 문자 필요::
이 필드를 사용하여 비밀번호에 특수 문자를 포함해야 하는지 여부를 지정합니다.

허용되는 특수 문자::
이 필드는 [literal]``특수 문자 필요``가 선택된 경우에만 활성화됩니다. 이 필드를 사용하여 허용되는 특수 문자(예: [literal]``!@#$%&*``)를 지정하십시오.

문자 발생 횟수 제한::
이 필드를 사용하여 제한된 문자 발생 횟수를 지정합니다.

최대 문자 발생 횟수::
이 필드를 사용하여 최대 문자 발생 횟수를 지정합니다.

btn:[저장] 버튼을 클릭하여 변경된 비밀번호 설정을 저장합니다.

btn:[초기화]를 사용하여 설정을 기본값으로 변경합니다.


[NOTE]
====
{productname}은(는) 다음 기본값으로 배송됩니다.

* 최소 비밀번호 길이: 4
* 최대 비밀번호 길이: 32
* 대문자 필요: 선택됨
====


== 계정 비활성화 및 삭제

더 이상 필요하지 않은 사용자 계정을 비활성화 또는 삭제할 수 있습니다. 비활성화된 사용자 계정은 언제든지 다시 활성화할 수 있습니다. 삭제된 사용자 계정은 표시되지 않으며 검색할 수 없습니다.

사용자는 자신의 계정을 비활성화할 수 있습니다. 그러나 사용자에게 관리자 역할이 있는 경우 해당 역할을 제거해야 계정을 비활성화할 수 있습니다.

비활성화된 사용자는 {productname} {webui}에 로그인하거나 작업을 예약할 수 없습니다. 비활성화되기 전에 사용자가 예약한 작업은 작업 대기열에 남아 있습니다. 비활성화된 사용자는 {productname} 관리자가 다시 활성화할 수 있습니다.


[[administrator-roles]]
== 사용자 역할

사용자에게는 여러 역할을 할당할 수 있으며, 1개의 역할에 언제든지 2명 이상의 사용자가 할당될 수 있습니다. 항상 1명 이상의 활성 {productname} 관리자가 있어야 합니다.

{productname} 관리자 역할을 제외한 사용자의 역할을 변경하려면, menu:사용자[사용자 목록 > 전체]로 이동하여 변경할 사용자를 선택하고 필요에 따라 관리자 역할을 선택하거나 선택을 취소합니다.

사용자의 {productname} 관리자 역할을 변경하려면 menu:관리자[사용자]로 이동하여 필요에 따라 [guimenu]``{productname} 관리자이십니까?``를 선택하거나 선택을 취소합니다.


[cols="1,1", options="header"]
.사용자 역할 권한
|===
| 역할 이름 | 설명
| {productname} 관리자 | 다른 사용자의 권한 변경 등 모든 기능을 수행할 수 있습니다.
| 조직 관리자 | 활성화 키, 구성, 채널 및 시스템 그룹을 관리합니다.
| 활성화 키 관리자 | 활성화 키를 관리합니다.
| 이미지 관리자 | 이미지 프로파일, 빌드 및 저장을 관리합니다.
| 구성 관리자 | 시스템 구성을 관리합니다.
| 채널 관리자 | 채널을 전 세계적으로 구독할 수 있도록 하고 새 채널 생성 등 소프트웨어 채널을 관리합니다.
| 시스템 그룹 관리자 | 시스템 그룹 생성 및 삭제, 기존 그룹에 클라이언트 추가, 그룹에 대한 사용자 액세스 관리 등 시스템 그룹을 관리합니다.
| 일반 사용자 | 표준 수준의 액세스 권한을 제공합니다. 새로 생성된 사용자는 이 역할에 자동으로 할당됩니다.
|===



== 추가 역할 만들기

{productname}의 역할 기반 접근 제어(RBAC)를 사용하면 추가 역할을 생성해 사용자 권한을 세밀하게 조정할 수 있습니다. 역할 관리 방법에 대한 자세한 내용은 xref:administration:role-based-access-control.adoc[]에서 확인할 수 있습니다.



== 사용자 권한 및 시스템

클라이언트를 관리하기 위해 시스템 그룹을 생성한 경우 관리할 사용자에게 그룹을 할당할 수 있습니다.

사용자를 시스템 그룹에 할당하려면 menu:사용자[사용자 목록]으로 이동하여 편집할 사용자 이름을 클릭하고 [guimenu]``시스템 그룹`` 탭으로 이동합니다. 할당할 그룹을 확인하고 btn:[기본값 업데이트]를 클릭합니다.

사용자에 기본 시스템 그룹을 한 개 이상 선택할 수도 있습니다. 사용자가 새 클라이언트를 등록하면 기본적으로 선택한 시스템 그룹에 할당됩니다. 그러면 사용자는 새로 등록된 클라이언트에 즉시 액세스할 수 있습니다.

// I really don't understand what this is. Need a sentence or two to explain it.  --LKB 2020-04-29
외부 그룹을 관리하려면 menu:사용자[시스템 그룹 구성]으로 이동하고 [guimenu]``외부 인증`` 탭으로 이동합니다. btn:[외부 그룹 생성]을 클릭하여 새 외부 그룹을 생성합니다. 그룹에 이름을 할당하고 적절한 시스템 그룹에 할당합니다.

시스템 그룹에 대한 자세한 내용은 xref:reference:systems/system-groups.adoc[]에서 확인할 수 있습니다.


사용자가 관리할 수 있는 개별 클라이언트를 확인하려면 menu:사용자[사용자 목록]으로 이동하여 편집할 사용자 이름을 클릭하고 [guimenu]``시스템`` 탭으로 이동합니다. 일괄 작업을 수행하려면 목록에서 클라이언트를 선택하여 시스템 세트 관리자에 추가할 수 있습니다.

시스템 세트 관리자에 대한 자세한 내용은 xref:client-configuration:system-set-manager.adoc[]에서 확인할 수 있습니다.



== 사용자 및 채널 권한

채널의 컨텐트를 사용하는 구독자 또는 채널을 직접 관리할 수 있는 관리자로 조직 내의 소프트웨어 채널에 사용자를 할당할 수 있습니다.

사용자가 채널을 구독하려면, menu:사용자[사용자 목록]으로 이동하여 편집할 사용자 이름을 클릭하고 menu:채널 권한[구독] 탭으로 이동합니다. 할당할 채널을 확인하고 btn:[권한 업데이트]를 클릭합니다.

사용자에게 채널 관리 권한을 부여하려면 menu:사용자[사용자 목록]으로 이동하여 편집할 사용자 이름을 클릭하고 menu:채널 권한[관리] 탭으로 이동합니다. 할당할 채널을 확인하고 btn:[권한 업데이트]를 클릭합니다.

목록의 일부 채널은 구독할 수 없습니다. 왜냐하면 일반적으로 사용자 관리자 상태 또는 채널 전역 설정 때문입니다.



== 사용자 기본 언어

새 사용자를 생성할 때 {webui}에 사용할 언어를 선택할 수 있습니다. 사용자를 생성한 후 menu:홈[내 기본 설정]으로 이동하여 언어를 변경할 수 있습니다.

기본 언어는 ``rhn.conf`` 구성 파일에 구성되어 있습니다. 기본 언어를 변경하려면 [path]``/etc/rhn/rhn.conf`` 파일을 열고 다음 라인을 추가하거나 편집합니다.

----
web.locale = <LANGCODE>
----

파라미터가 설정되지 않은 경우 기본 언어는 ``en_US``입니다.

다음은 {productname}에서 사용할 수 있는 언어입니다.

ifeval::[{mlm-content} == true]

[[langcodes-mlm]]
.사용할 수 있는 언어 코드
[cols="1,1,1", options="header"]
|===
| 언어 코드 | 언어   | 지역
| ``en_US``     | 영어    | 미국
| ``zh_CN``     | 중국어   | 본토, 간체
|===
endif::[]

ifeval::[{uyuni-content} == true]

[[langcodes-uyuni]]
.사용할 수 있는 언어 코드
[cols="1,1,1", options="header"]
|===
| 언어 코드 | 언어   | 지역
| ``bn_IN``     | 벵골어     | 인도
| ``ca``        | 카탈루냐어    |
| ``de``        | 독일어     |
| ``en_US``     | 영어    | 미국
| ``es``        | 스페인어    |
| ``fr``        | 프랑스어     |
| ``gu``        | 구자라트어   |
| ``hi``        | 힌디어      |
| ``it``        | 이탈리아어    |
| ``ja``        | 일본어   |
| ``ko``        | 한국어     |
| ``pa``        | 펀자브어    |
| ``pt``        | 포르투갈어 |
| ``pt_BR``     | 포르투갈어 | 브라질
| ``ru``        | 러시아어    |
| ``ta``        | 타밀어      |
| ``zh_CN``     | 중국어    | 본토, 간체
| ``zh_TW``     | 중국어    | 대만, 번체
|===


[IMPORTANT]
====
{uyuni}의 번역은 커뮤니티에서 제공하며 정확하지 않거나 불완전할 수 있습니다. 번역을 사용할 수 없는 경우 {webui}는 기본적으로 영어(``en_US``)로 설정됩니다.
====

endif::[]



=== 사용자 기본 인터페이스 테마

기본적으로 {productname} {webui}는 사용자가 설치한 제품에 적합한 테마를 사용합니다. {uyuni} 또는 {susemgr} 색상을 반영하도록 테마를 변경할 수 있습니다. {susemgr} 테마에는 어두운 옵션도 있습니다.

``rhn.conf`` 구성 파일에서 기본 테마를 변경할 수 있습니다. 기본 테마를 변경하려면 [path]``/etc/rhn/rhn.conf`` 파일을 열고 다음 라인을 추가하거나 편집합니다.

----
web.theme_default = <THEME>
----

[[webui-themes]]
.사용할 수 있는 웹 UI 테마
[cols="1,1,1", options="header"]
|===
| 테마 이름            | 색상    | 스타일
| ``suse-light`` | {susemgr} | 밝게
| ``suse-dark``  | {susemgr} | 어둡게
| ``uyuni``      | {uyuni}   | 밝게
|===
