= {productname} {productnumber} Documentation


== What is {productname}?

{productname} is a solution for organizations that require absolute control over maintenance and package deployment on their servers. {productname} enables you to manage large sets of Linux systems and keep them up to date, with automated software management, asset management, and system provisioning. {productname} allows you to maintain a high level of security while effectively managing system life-cycle requirements.

{productname} uses Salt to provide event-driven configuration and management control. The Salt-master orchestrates tens of thousands of Salt clients ({productname} Clients) using remote execution.

{productname} offers seamless management of {sle}, {opensuse}, {rhel}, {centos}, {oracle}, {debian} and {ubuntu} client systems, no matter if on-premise, on public cloud, private cloud, hybrid cloud or even multi-cloud environments.


== Available Documentation

The following documentation is available for {productname} version {productnumber}.


[cols=4*,,  options="header"]
|===
| Document | Format | Document | Format

| Installation Guide | xref:installation:install-overview.adoc[HTML] link:../pdf/uyuni_installation_guide.pdf[PDF] | Administration Guide | xref:administration:admin-overview.adoc[HTML] link:../pdf/uyuni_administration_guide.pdf[PDF]
| Client Configuration Guide | xref:client-configuration:client-config-overview.adoc[HTML] link:../pdf/uyuni_client-configuration_guide.pdf[PDF] | Salt Guide | xref:salt:salt-overview.adoc[HTML] link:../pdf/uyuni_salt_guide.pdf[PDF]
| Upgrade Guide | xref:upgrade:upgrade-overview.adoc[HTML] link:../pdf/uyuni_upgrade_guide.pdf[PDF] | Retail Guide | xref:retail:retail-overview.adoc[HTML] link:../pdf/uyuni_retail_guide.pdf[PDF]
| Reference Guide | xref:reference:reference-overview.adoc[HTML] link:../pdf/uyuni_reference_guide.pdf[PDF] | |
|===
