[[workflow-client-update]]

= Update Clients

This workflow shows how to automate updating the clients registered at {productname} using recurring actions.

// FIXME uncomment on 4.3 backport
// The workflow is applicable for Salt clients.


== Use Case / Situation

Automated update of clients is benefitial when:

- update of a large number of clients is wanted
- the workflow should not be re-done every execution
- a dedicated maintenance window exists


== Outcome / Resolution

Successful completion of this workflow results in consistent and supportable state.


== Preparation

// FIXME 4.3 backport wersion
// Before you start, you should have a number of {salt} clients onboarded.
Before you start, you should have a number of clients onboarded.
It may make sense to have them sorted into groups you want to update together.
In this workflow we use a system group named [literal]``infra-services``.


== Step-by-step Workflow Instructions

To update a client two steps are required.
A third step is optional but it is highly recommended to finalize the update process.

.Procedure 1: Creating a recurring action to update {salt} itself
[role=procedure]
. As an example we create the action to update {salt} itself as a recurring action for all systems in the organization.
In the {productname} {webui} go to menu:Home[My Organization > Recurring Actions] and click btn:[Create].
. Select `Action Type` "Custom State" and enter a `Schedule Name` like "update-salt"
. Select a schedule.
  For example, `Weekly`: Wednesday, 9:00 am.
. Assign the `update-salt` state by selecting the checkbox.
. Save the action by clicking btn:[Save Changes].
. You can edit the execution order of the states if needed.
  Click btn:[Confirm] to confirm the order.
. Click btn:[Create Schedule] to save the action.

Procedure 2: Create a recurring action to apply all available updates to the systems:
[role=procedure]
. As an example we create the action to apply all updates as a recurring action for a system group called "infra-services".
In the {productname} Web UI go to Systems > System Groups and click on "infra-services".
. Now go to `Recurring Actions` and click on `Create`.
. Select `Action Type` "Custom State" and enter a `Schedule Name` like "full-system-update"
. Select a Schedule. E.g. `Weekly`: Wednesday, 9:30 am .
Keep enough time between this action and the "update-salt" action.
The "update-salt" actions must be finished on all systems before this action should be executed.
. Assign the states `util.syncall`, `certs`, `channels` and `uptodate` by selecting the checkboxes.
. Save the action by clicking on `Save Changes`
. You can edit the execution order of the states. The order should be `util.syncall`, `certs`, `channels` and finally `uptodate`.
Click on `Confirm` to store the order.
. To save the action, click on `Create Schedule`.

The `uptodate` state perform also a reboot, if an update request this. This can be prevented if wanted. For example at systems which use live patching.

Procedure 3: Configure systems to not reboot when apply the `uptodate` state:
[role=procedure]
. In the {productname} Web UI go to Systems > Custom System Info and click `Create Key`.
. Enter "mgr_reboot_if_needed" as `Key Label` and set as `Description` 
'Define if the up2date state should perform a reboot if needed. Set to "false" if this is not wanted'
. Click on `Create Key` to store the new key.
. To assign values to multiple systems, go in the {productname} Web UI to Systems > Overview and select the checkbox for all systems you want to modify.
These system are not in the System Set Manager (SSM)
. Select in the left menu System Set Manager and select `Misc > Custom Values` in the tab bar.
. Click on `mgr_reboot_if_needed` and enter "false" as `Value`.
. Click on `Set Values` to save.

Procedure 4: Create a recurring action to run a highstate after the update:
. As an example we create the action to apply the highstate for the same group which was fully updated before.
In the {productname} Web UI go to Systems > System Groups and click on "infra-services".
. Now go to `Recurring Actions` and click on `Create`.
. Select `Action Type` "Highstate" and enter a `Schedule Name` like "highstate"
. Select a Schedule. E.g. `Weekly`: Wednesday, 10:30 am.
Again keep enough time between this action and the "full-system-update" action.
. To save the action, click on `Create Schedule`.


== Related topics

* For more information about recurring actions, see xref:administration/actions.adoc#_recurring_actions[].
* For more information about custom info values, see xref:client-configuration/custom-info.adoc[].

