[[workflow-clients-update-rec-actions]]
= Clients Update Using Recurring Actions

This workflow shows how to automate updating the clients registered at {productname} using recurring actions.

The workflow is applicable for {salt} clients only.


== Use Case / Situation

Automated update of clients is benefitial when:

* update of a large number of clients is wanted
* the workflow should not be re-done every execution
* a dedicated maintenance window exists.


== Outcome / Resolution

Successful completion of this workflow results in consistent and supportable state.


== Preparation

Before you start, you should have a number of {salt} clients onboarded.
It may make sense to have them sorted into groups you want to update together.
In this workflow we use a system group named [literal]``infra-services``.


== Step-by-Step Workflow Instructions

To update a client two steps are required.
A third step is optional but highly recommended to finalize the update process.


.Procedure 1: Creating a Recurring Action to Update {salt} Itself
[role=procedure]
. As an example, we create the action to update {salt} itself as a recurring action for all systems in the organization.
  In the {productname} {webui}, navigate to menu:Home[My Organization > Recurring Actions] and click btn:[Create].
. Select [literal]``Action Type`` **Custom State** and enter a [literal]``Schedule Name`` like [literal]``update-salt``.
. Select a schedule.
  For example, ** Weekly: Wednesday, 9:00 am **.
. Assign the [literal]``update-salt`` state by selecting the checkbox.
. Click btn:[Save Changes] to save the action.
. You can edit the execution order of the states if needed.
  Click btn:[Confirm] to confirm the order.
. Click btn:[Create Schedule] to save the action.


.Procedure 2: Creating a Recurring Action to Apply All Available Updates to the Systems
[role=procedure]
. As an example we create the action to apply all updates as a recurring action for a system group called "infra-services".
  In the {productname} {webui} go to menu:Systems[System Groups] and click on [literal]``infra-services``.
. Now go to [literal]``Recurring Actions`` and click btn:[Create].
. Select [literal]``Action Type`` **Custom State** and enter a [literal]``Schedule Name`` like [literal]``full-system-update``.
. Select a Schedule. 
  For example, ** Weekly: Wednesday, 9:30 am **.
  Keep enough time between this action and the [literal]``update-salt`` action.
  The [literal]``update-salt`` actions must be finished on all systems before this action should be executed.
. Assign the states [literal]``util.syncall``, [literal]``certs``, [literal]``channels`` and [literal]``uptodate` by selecting the checkboxes.
. Save the action by clicking btn:[Save Changes].
. You can edit the execution order of the states. 
  The order should be [literal]``util.syncall``, [literal]``certs``, [literal]``channels``, and finally [literal]``uptodate``.
  Click btn:[Confirm] to store the order.
. Click btn:[Create Schedule] to save the action.

[WARNING]
====  
The [literal]``uptodate` also performs a reboot, if an update requests it. 
This reboot be prevented if needed. 
For example, the systems which use live patching need to prevent the rebooting following the update.
====


.Procedure 3: Configuring Systems to Not Reboot After the [literal]``uptodate`` State is Applied
[role=procedure]
. In the {productname} [web ui} go to menu:Systems[Custom System Info] and click btn:[Create Key].
. Enter "mgr_reboot_if_needed" as `Key Label` and set as `Description`.
  Define if the [literal]``uptodate`` state should perform a reboot if needed. 
  Set to [literal]``False`` if this is not wanted.
. Click btn:[Create Key] to store the new key.
. To assign values to multiple systems, navigate in the {productname} {webui} to menu:Systems[Overview] and select the checkbox for all systems you want to modify.
  These system are not in the System Set Manager (SSM).
. Select in the left menu System Set Manager and select menu:Misc[Custom Values] in the tab bar.
. Click [literal]``mgr_reboot_if_needed`` and enter **False** as [literal]``Value``.
. Click btn:[Set Values] to save.


.Procedure 4: Creating a Recurring Action to Run a Highstate After the Update
[role=procedure]
. As an example, we create the action to apply the highstate for the same group which was fully updated before.
  In the {productname} {webui}, navigate to menu:Systems[System Groups] and click [literal]``infra-services``.
. Go to `Recurring Actions` and click btn:[Create].
. Select [literal]``Action Type`` **Highstate** and enter a [literal]``Schedule Name`` like [literal]``highstate``.
. Select a Schedule.
  For example, ** Weekly: Wednesday, 10:30 am **.
  Again, keep enough time between this action and the [literal]``full-system-update`` action.
. Click btn:[Create Schedule] to save the action.



[[cw-update-background]]
== Background Information on [literal]``uptodate`` State


. The [systemitem]``uptodate`` state applies critical patches to the update components.

+

--

..  On {suse}-based systems, the state executes the command:

+

[source,shell]
----
zypper --non-interactive patch --updatestack-only
----

+

And then, the state also updates {salt}.

.. On all the other systems, not based on {suse}, the state only updates {salt}.

--

. The state runs the package manager, such as [command]``dnf``, [command]``yum``, [command]``apt``, or [command]``zypper`` based on what is available on the client operating system to update the rest of the packages.

+

--

.. The state lists all of the upgradable packages, based on the synchronized package repositories in {productname}.

.. The state upgrades the packages to their latest available version by using the client's package manager.
 The executed command depends on the operating system of the client:

... For Debian-based clients, such as Debian or Ubuntu, the action executes [command]``apt dist-upgrade -q -y $PACKAGES``.
... For RPM-based clients that are not SUSE, such as Red Hat Enterprise Linux or SUSE Liberty Linux, the action executes [command]``yum --quiet -y update $PACKAGES`` or [command]``dnf --quiet -y upgrade $PACKAGES`` (depending on the package manager the client is using).
... For non-transactional SUSE clients, such as SUSE Linux Enterprise 15, the action executes [command]``zypper --non-interactive --auto-agree-with-licenses update $PACKAGES``.
... For transactional {suse} clients, the action executes the same in a transactional shell.

--

+

// . version 4.3" if SUMULIMA detects that reboot is necessary, for 4.3.x, it will automatically reboot that client.

+

// 5.0 and later

. If {productname} detects that  [systemitem]``reboot`` is necessary, {productname} will automatically reboot that client.

+


For more information, see the [literal]``reboot_info.py`` module: https://github.com/uyuni-project/uyuni/blob/master/susemanager-utils/susemanager-sls/src/modules/reboot_info.py



== Related Topics

* For more information about recurring actions, see xref:administration:actions.adoc#recurring_actions[Recurring Actions].
* For more information about custom info values, see xref:client-configuration:custom-info.adoc[].
