[[workflow-removing-channel]]
= Removing channel


== Use case

This workflow shows how to manually remove SUSE provided channels from {productname} and to clean up end-of-life products, to reclaim space or for other purposes.



== Step-by-step instructions

Manual channel removal consists of the following phases:

. <<preparing-to-remove-channel>>
. <<removing-channels>>
. <<cleaning-up-channel-packages>>


[[preparing-to-remove-channel]]
=== Preparing to remove a channel

Before removing a channel, you must identify the label for the channel to be removed.
It can be done with {webui} or on the command line.

[IMPORTANT]
====
* Be careful not to remove channels that systems are currently subscribed to, or that you are planning on subscribing a system to.
* If there are systems that are currently subscribed to a channel that you want to delete, do not remove the channel until those systems are upgraded or unsubscribed.
====


==== Identifying Channel labels

.Procedure: Identifying channel labels using {webui}
[role=procedure]
. In the SUSE Manager {webui}, in the sidebar navigate to menu:Software[Channel List > All]
. This page displays the [label]``Channel Name``.
  If you select the link for a channel name, you will see the field for [literal]``Channel Label``.
. Identify the channel, and child channels, to be removed.


.Procedure: Identifying channel labels using the command line
[role=procedure]

. You can get a list of channels by running the following command:
+
----
spacewalk-remove-channel -l
----


====  Verify channel system subscriptions

.Procedure: Verifying channel system subscriptions using {webui}

. In the {productname} {webui}, in the sidebar navigate to menu:Software[Channel List > All].
. Locate [literal]``Systems`` column on the right.
. Check the [literal]``Systems`` column for the channel, or any child channels, that you want to remove.


.Procedure: Verify Channel System Subscriptions using the command line

. Run the following command:
+
----
spacecmd -- softwarechannel_listsystems <Channel Label>
---- 


[[removing-channel]]
=== Removing channel

A channel, with its metadata, can be removed in the SUMA command line by using the [literal]``spacewalk-remove-channel`` command. 
This command does not remove the packages themselves from the filesystem. 

Removing packages from the filesystem is described in <<cleaning-up-channel-packages>>.



==== Removing an individual channel

.Procedure: Removing an individual channel using the command line

. To remove an individual channel run the following command:
+
----
spacewalk-remove-channel -c channel-label
----
+
. To remove multiple channels at the same time, use [literal]``-c`` flag for each channel, followed by the [literal]``channel-label``. 
  For example:
+
----
spacewalk-remove-channel -c channel-label1 -c channel-label2
----


==== Removing a Parent and all its Children

.Procedure: Removing a Parent and all its Children
. It is also possible to remove a parent channel with all of its children, like this:
+
----
spacewalk-remove-channel -a sles12-sp5-pool-x86_64
----


[[cleaning-up-channel-packages]]
=== Cleaning up channel packages

==== Running the synchronization

.Procedure: Running the synchronization
. After removing a channel, run the command ``spacewalk-repo-sync`` on all remaining channels, or wait for the operation to complete automatically.
. Alternatively, for all currently added channels running the following command:
+
----
mgr-sync refresh --refresh-channels
----


==== Remove packages from the database via the {webui}

.Procedure: Remove Packages from the database via the {webui}
. After removing the channel, you need to delete the packages from the database via the {webui}.
. In the {productname} {webui} navigate to menu:SUSEManager[Software > Manage > Packages].
. Select [literal]``Package in no channel``, and delete the packages.



==== Clean the packages From the filesystem

.Procedure: Clean the packages from the filesystem
. The following command checks for anything that is still showing in the filesystem, but not in the SUMA database and then removes it.
+
----
# spacewalk-data-fsck -r -S -C -O
----
+
[WARNING]
====
The final cleanup command can take several minutes, or even hours to complete.
====



== Related topics

* For more information about deleting channels, see see xref:administration:channel-management.adoc#delete_channels[Delete channels].
