[[workflow-install-from-selfinstall-on-ppc]]
= Installing {productname} on {ppc64le}

This guide demonstrates how to set up {productname} Server using SelfInstall ISO image on {ppc64le} machine.



== Use Case

This workflow outlines the steps to install {productname} on a {ppc64le} architecture using the SelfInstall ISO image. 
This method is used to create a container host for {productname}, allowing for efficient management of your systems.

== Outcome 

Successful completion of this workflow results in successful installation of {productname} Server running on a {ppc64le} system.

== Step-by-step Instructions

[NOTE]
====
This workflow is complex and time-consuming.
Make sure that adequate testing is done before deploying the procedure in live environment.
====

.Procedure: Prepare the Prerequisites
[role=procedure]
. A physical or virtual machine that supports the {ppc64le} architecture.
. Access to the SUSE SelfInstall ISO image for {productname} (either 512 or 4096 block size, depending on your disk configuration).
. Sufficient storage for the root disk (40GB recommended) and a separate, large, fast storage device for persistent volumes.
. Network connectivity for registration and updates from SCC.
. A valid LCM+ subscription key.

											
.Procedure: Installation Steps
[role=procedure]				
						
. *Download and Prepare the Installation Media*
.. Download the SelfInstall ISO image for the appropriate physical block size (512 or 4096) from suse.com. 
   Example: [literal]``SUSE-Manager-Server.ppc64le-5.0.2-SelfInstall-ppc-4096-2024.12.install.iso``
.. Create a new instance with a root disk size of 40GB (recommended).
.. Attach the SelfInstall ISO as a virtual CD and attach large, fast storage for the persistent volume.

. *Boot from SelfInstall ISO*
.. Boot from the SelfInstall ISO and follow the on-screen prompts.
.. Select the desired disk for the root partition [literal]``(/)``. The system will copy the disk image to the selected volume.

. *Finalize Installation and Initial Setup*
.. Shut down the instance and remove the virtual CD-ROM from the boot sequence.
.. Start the instance. It will boot from the newly installed {productname} host OS.
.. The system will adapt to the disk size and allow you to log in

. *Register with SCC and Apply Updates*
.. Register the server with SCC using the `SUSEConnect` command, including the SUSE Manager Server Extension.
.. Use your ppc64le LCM+ subscription key for registration.
.. Apply all available updates using [literal]``transactional-update``.
.. Reboot the system as directed.

. *Install Required Packages*
.. Install the packages to use this instance as a container host for {productname}
+
----
transactional-update pkg install netavark podman \ 
mgradm mgrctl uyuni-storage-setup-server 
----
+
.. Provision persistent storage for {productname}
+
----
mgr-storage-server $device
----
+
Ensure [literal]``$device`` points to the fast, persistent storage.
+
For more information, see xref:installation-and-upgrade:container-deployment/mlm/server-deployment-mlm.adoc#_persistent_volumes[Persistent Volumes].
+
.. Follow the documentation from here to continue with deployment
xref:installation-and-upgrade:container-deployment/mlm/server-deployment-mlm.adoc#_deploy_with_mgradm[Server Deployment].
