[[proxy-conversion-from-client-uyuni]]
= Proxy conversion from client

== Introduction

This chapter describes a new way in which {productname} proxy can be registered with {productname} server.
It is simpler, more user-friendly, and less error-prone.

The main principle consists of using a functionality within {webui} which converts an already onboarded client to a proxy.

The client which is a candidate for conversion to proxy must adhere to the following pre-requisites:

* it must alredy be onboarded
* it is reachable
* it has access to client tools 

ifeval::[{mlm-content} == true]
* it is a transactional system
endif::[]


== Convert the client to {productname} Proxy

The process of conversion is done entirely from the {webui} for already registered clients. 
For more information about client onboarding, see xref:client-configuration:registration-overview.adoc[].

The following two procedures describe the client conversion to a proxy.
Either procedure can be used, and will achieve the same outcome.

.Procedure: Converting client to {productname} Proxy using dedicated button
. For the client chosen to be converted to proxy, go to its [literal]``Overview`` page.
. Click button btn:[Convert to Proxy].
. Wait for the conversion to complete.
. Confirm that the conversion has been successful by locating a new tab [literal]``Proxy`` on the [literal]``Overview`` page.


.Procedure: Converting client to {productname} Proxy by changing client's properties
. For the client chosen to be converted to proxy, go to its [literal]``Properties`` page.
. Locate the section [literal]``Add-on System Types``.
. Check the option [literal]``Proxy``.
. Click button btn:[Update Properties].
. Confirm that the conversion has been successful by locating a new tab [literal]``Proxy`` on the [literal]``Overview`` page.
