[[proxy-setup-containers-uyuni]]
= Containerized {productname} Proxy Setup
ifeval::[{mlm-content} == true]
:noindex:
endif::[]

Once container host for {productname} Proxy containers is prepared, setup of containers require few additional steps to finish configuration.

.Procedure
. Generate {productname} Proxy configuration archive file
. Transfer configuration archive to the container host prepared in installation step and extract it
. Start the proxy sevices with [literal]``mgrpxy``

include::../generate_proxy_config.adoc[]


[[proxy-setup-containers-transfer-config]]
== Transfer {productname} Proxy Configuration

Both [command]``spacecmd`` command  and generating via {webui} ways create a configuration archive.
This archive needs to be made available on container host.
Transfer this generated archive to the container host.

For installation instructions to use the archive to get the proxy containers, see xref:installation-and-upgrade:container-deployment/uyuni/proxy-container-installation-uyuni.adoc[].


[[proxy-setup-containers-transfer-start]]
== Start {productname} Proxy Containers

Container can be started with the [literal]``mgrpxy`` command.

[[proc-setup-containers-setup-start]]
.Procedure: Start {productname} Proxy Containers

. Run command:
+
----
mgrpxy start uyuni-proxy-pod
----
+
. Check if all containers started up as expected by calling:
+
----
podman ps
----

Five {productname} Proxy containers should be present and should be part of [literal]``proxy-pod`` container pod.

* proxy-salt-broker
* proxy-httpd
* proxy-tftpd
* proxy-squid
* proxy-ssh
