[[proxy-setup-containers-uyuni]]
= Containerized {productname} Proxy Setup
:description: Heres the corrected sentence Learn how to set up and configure containerized SUSE Manager Proxy containers with step-by-step instructions. The original sentence
:revdate: 2024-07-04
:page-revdate: {revdate}
:page-author: SUSE Product & Solution Documentation Team
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Manager
:page-product-version: 5.0
ifeval::[{suma-content} == true]
:noindex:
endif::[]

Once container host for {productname} Proxy containers is prepared, setup of containers require few additional steps to finish configuration.

1. Generate {productname} Proxy configuration archive file
2. Transfer configuration archive to the container host prepared in installation step and extract it
3. Start the proxy sevices with [literal]``mgrpxy``


ifndef::backend-pdf[]
include::installation-and-upgrade:partial$container-deployment/generate_proxy_config.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../partials/container-deployment/generate_proxy_config.adoc[]
endif::[]

[[proxy-setup-containers-transfer-config]]
== Transfer {productname} Proxy configuration

Both [command]``spacecmd`` command  and {webui} ways generate a configuration archive.
This archive needs to be made available on container host.

Transfer this generated archive to the container host.

For installation instructions to use the archive to get the proxy containers, see xref:installation-and-upgrade:container-deployment/uyuni/proxy-container-installation-uyuni.adoc[].

[[proxy-setup-containers-transfer-start]]
== Start {productname} Proxy containers

Container can now be started with the [literal]`mgrpxy` command:

[[proc-setup-containers-setup-start]]
.Procedure: Start {productname} Proxy containers

----
mgrpxy start uyuni-proxy-pod
----

Check if all containers started up as expected by calling

----
podman ps
----

Five {productname} Proxy containers should be present:

- proxy-salt-broker
- proxy-httpd
- proxy-tftpd
- proxy-squid
- proxy-ssh

And should be part of [literal]``proxy-pod`` container pod.

