[[installation-proxy-containers-uyuni]]
= Install containerized {productname} Proxy
ifeval::[{suma-content} == true]
:noindex:
endif::[]

[NOTE]
====

ifeval::[{uyuni-content} == true]
Only {opensuse} Leap 15.3 and newer are supported to be used as container host for {productname} Proxy containers.
endif::[]

ifeval::[{suma-content} == true]
Only {sles} 15 SP5 or {micro} {microversion} and newer are supported to be used as container host for {productname} Proxy containers.
endif::[]

====



[[installation-proxy-containers-requirements]]
== Container host requirements

.Proxy Container host hardware requirements
[cols="3*", options="header"]
|===
| Hardware
| Details
| Recommendation

| CPU
|
| Minimum 2 dedicated 64-bit CPU cores

| RAM
| Test Server
| Minimum 2{nbsp}GB

|
| Production Server
| Minimum 8{nbsp}GB

| Disk Space
|
| Minimum 100{nbsp}GB
|===

.Proxy Container host software requirements
[cols="3*", options="header"]
|===
| Software
| Details
| Remark

| Connection Method
| Salt
| Host must be configured as a Salt client
|===

[IMPORTANT]
====
To ensure that domain name of the {productname} Server can be resolved by the clients:
* Both container proxy and client machines must be connected to a DNS server
* Reverse lookup must work
====



[[installation-proxy-containers-services]]
== Install container services on the host system

[NOTE]
====
Container host to be used as a base for {productname} Proxy containers needs to be first registered as a client to the {productname} Server.

For more information about registering client to the {productname} Server, see xref:client-configuration:registration-overview.adoc[].
====

ifeval::[{suma-content} == true]
[NOTE]
====
[literal]``Containers Module`` is required to be available for container host on a {sles} machine.
====
endif::[]

{productname} Proxy containers are using [literal]``podman`` and [literal]``systemd`` to run and manage all proxy containers.

First step is to install the [literal]``mgrpxy`` utility provided by the package of the same name.

ifeval::[{suma-content} == true]
The [literal]``mgrpxy`` package is available in the {productname} Proxy product repositories.
endif::[]

ifeval::[{uyuni-content} == true]
The [literal]``mgrpxy`` package is available in the container utils repository: pick the one matching the distribution in: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/.
endif::[]

To install them run:

----
zypper in helm mgrpxy
----



[[proc-installation-proxy-containers-mgrpxy]]
.Procedure: Installation of container utility tool [literal]``mgrpxy`` for {productname} Proxy

. Assign [literal]``Containers Module`` software channel to the container host in the {productname}.
For more information about assigning software channels to the system, see xref:administration:channel-management.adoc[].

. Log in as `root` on the container host.

. Manually install [literal]``mgrpxy`` package:
+

----
zypper install mgrpxy
----



[[installation-proxy-containers-customize-config]]
== Install {productname} Proxy containers

{productname} Proxy containers require some volumes to be mounted for long term storage.
Those volumes are automatically created by [literal]``podman`` and can be listed using the [command]``podman volume ls`` command.
By default, [literal]``podman`` stores the files of the volumes in [path]``/var/lib/containers/storage/volumes``.
The volumes are named:

- [path]``uyuni-proxy-squid-cache``
- [path]``uyuni-proxy-rhn-cache``
- [path]``uyuni-proxy-tftpboot``

To override default volume settings, create the volumes prior to the first start of the pod using the  [command]``podman volume create`` command.

By default, the [package]``uyuni-proxy-systemd-services`` package creates these three directories that can be used to mount external disks:

----
/var/lib/uyuni/proxy-rhn-cache
/var/lib/uyuni/proxy-squid-cache
/var/lib/uyuni/proxy-tftpboot 
----

If [path]``/etc/fstab`` has these entries:

----
/dev/uyuni-proxy/rhn-cache    /var/lib/uyuni/proxy-rhn-cache    xfs 	defaults 0 0
/dev/uyuni-proxy/squid-cache  /var/lib/uyuni/proxy-squid-cache  xfs 	defaults 0 0
/dev/uyuni-proxy/tftpboot     /var/lib/uyuni/proxy-tftpboot     xfs 	defaults 0 0
----

Run these commands to create custom volumes:

----
podman volume create --driver local --opt device=/dev/mapper/uyuni--proxy-rhn--cache --opt type=xfs uyuni-proxy-rhn-cache
podman volume create --driver local --opt device=/dev/mapper/uyuni--proxy-squid--cache --opt type=xfs uyuni-proxy-squid-cache
podman volume create --driver local --opt device=/dev/mapper/uyuni--proxy-tftpboot --opt type=xfs uyuni-proxy-tftpboot
----

To install the systemd service starting the {productname} proxy, run the [command]``mgrpxy install podman /path/to/config.tar.gz`` command.

It is possible to add custom arguments passed to podman container pod with the one or more [literal]``--podman-arg`` parameters to the install command.

It is possible to modify the tag to use for container images with the [literal]``--tag=latest`` parameter to the install command.

[IMPORTANT]
====
Changing the containers images and version parameters is dangerous and can cause a non-functional system.
====



=== Using a custom container image for a service

By default, the {productname} Proxy suite is set to use the same image version and registry path for each of its services.
However, it is possible to override the default values for a specific service using the install parameters ending with [literal]``-tag`` and [literal]``-image``.

For example, use it like this:

----
mgrpxy install podman --httpd-tag 0.1.0 --httpd-image registry.opensuse.org/uyuni/proxy-httpd /path/to/config.tar.gz
----

It adjusts the configuration file for the httpd service, where [path]``registry.opensuse.org/uyuni/proxy-httpds`` is the image to use and [literal]``0.1.0`` is the version tag, before restarting it.

To reset the values to defaults, run the install command again without those parameters:

----
mgrpxy install podman /path/to/config.tar.gz
----

This command first resets the configuration of all services to the global defaults and then reloads it.



[[installation-proxy-containers-firewall-rules]]
== Allow network access for provided services on container host firewall

{productname} Proxy containers work as so called node-port service.
This means proxy container pod shares container host network TCP and UDP port space.
For this reason container host firewall must be configured to accept incoming traffic on ports used by {productname} Proxy containers.
Those ports are:

- 69/UDP - TFTP
- 80/TCP - HTTP
- 443/TCP - HTTPS
- 4505/TCP - Salt
- 4506/TCP - Salt
- 8022/TCP - SSH

Continue with setting up the installed {productname} Proxy as a containers at xref:installation-and-upgrade:container-deployment/uyuni/proxy-container-setup-uyuni.adoc[].
