= {productname} Server Air-gapped Deployment
ifeval::[{suma-content} == true]
:noindex:
endif::[]

== What is air-gapped deployment?

Air-gapped deployment refers to the setup and operation of any networked system that is physically isolated from insecure networks, especially the internet. This type of deployment is commonly used in high-security environments such as military installations, financial systems, critical infrastructure, and anywhere sensitive data is handled and must be protected from external threats.

You can easily deploy container images using [systemitem]``Podman``, [systemitem]``Docker``, or [systemitem]``Skopeo`` on a machine with internet access. 

Pull the desired image then, save the image as a tar archive. For example:

.Podman
----
podman pull registry.suse.com/suse/manager/5.0/x86_64/server:5.0.0-beta2
podman save --output server.tar registry.suse.com/suse/manager/5.0/x86_64/server:5.0.0-beta2
----

.Docker
----
docker pull registry.suse.com/suse/manager/5.0/x86_64/server:5.0.0-beta2
docker save --output server.tar registry.suse.com/suse/manager/5.0/x86_64/server:5.0.0-beta2
----


.Skopeo
----
skopeo copy docker://registry.suse.com/suse/manager/5.0/x86_64/server:5.0.0-beta2 docker-archive:server.tar:registry.suse.com/suse/manager/5.0/x86_64/server:5.0.0-beta2
----

Transfer the resulting [filename]``server-image.tar`` to the Server container host and load it using the following command:

.Load the Server Image
----
podman load -i server.tar
----

