= {productname} Server Air-gapped Deployment
:revdate: 2025-07-25
:page-revdate: {revdate}
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

== What is Air-gapped Deployment?


Air-gapped deployment refers to the setup and operation of any networked system that is physically isolated from insecure networks, especially the internet. This type of deployment is commonly used in high-security environments such as military installations, financial systems, critical infrastructure, and anywhere sensitive data is handled and must be protected from external threats.

You can easily pull container images using [systemitem]``Podman`` or [systemitem]``Docker`` on a machine with internet access. 

.Procedure
. Pull the desired images, then save the images as a [literal]``tar`` archive. 
For example:
+
.Podman
----
podman pull registry.opensuse.org/uyuni/server:latest registry.opensuse.org/uyuni/server-postgresql:latest
podman save --output images.tar registry.opensuse.org/uyuni/server:latest registry.opensuse.org/uyuni/server-postgresql:latest
----
+
.Docker
----
docker pull registry.opensuse.org/uyuni/server:latest registry.opensuse.org/uyuni/server-postgresql:latest
docker save --output images.tar registry.opensuse.org/uyuni/server:latest registry.opensuse.org/uyuni/server-postgresql:latest
----
+
. Transfer the resulting [filename]``images.tar`` to the Server container host and load it using the following command:
+
.Load the server image
----
podman load -i images.tar
----

== Obtaining Container Images for Salt Formulas in Air-Gapped Environments

Some formulas, like Bind and DHCP (Kea), also use containers. If you plan to use them in an air-gapped environment, you need to pull their images, save them to an archive, and load them on your {productname} Proxy or another managed system.

The images are available from `registry.opensuse.org`.

.Procedure: Obtaining Formula Images for Air-Gapped Environments
. On a system with Internet access, pull the required images. For example:
+
[source,shell]
----
podman pull registry.opensuse.org/opensuse/bind:latest
podman pull registry.opensuse.org/opensuse/kea:latest
----
. Save the images to a TAR archive:
+
[source,shell]
----
podman save -o formula-images.tar registry.opensuse.org/opensuse/bind:latest registry.opensuse.org/opensuse/kea:latest
----
. Transfer the `formula-images.tar` file to your air-gapped system.
. Load the images on the air-gapped system:
+
[source,shell]
----
podman load -i formula-images.tar
----

=== Deploy {productname} on {opensuse} {tumbleweed}

{productname} also provides all the needed container images in RPM packages that can be installed on the system.

[NOTE]
====
User should make the needed RPM available on the internal network. That can be done by using a second {productname} Server or any kind of mirror.
====

.Procedure: Install {productname} on {opensuse} {tumbleweed} in Air-gapped
. Install {opensuse} {tumbleweed}.
. Update the system.
. Install tools packages and image packages (replace $ARCH$ with the correct architecture):

+

[source,shell]
----
zypper install mgradm* mgrctl* uyuni-server*-image*
----

+

. Deploy {productname} with [command]``mgradm``. In an Air-gapped environment you may want to use the option [command]``--pullPolicy Never``.


For more detailed information about installing {productname} Server on {opensuse} {tumbleweed}, see xref:container-deployment/uyuni/server-deployment-uyuni.adoc[Server Deployment].

To upgrade {productname} Server, users should upgrade all packages in the system and follow the procedures defined in xref:container-management/updating-server-containers.adoc[Server Upgrade].

