= {productname} Server Air-gapped Deployment
ifeval::[{mlm-content} == true]
:noindex:
endif::[]

== What is Air-gapped Deployment?

Air-gapped deployment refers to the setup and operation of any networked system that is physically isolated from insecure networks, especially the internet. This type of deployment is commonly used in high-security environments such as military installations, financial systems, critical infrastructure, and anywhere sensitive data is handled and must be protected from external threats.

You can easily deploy container images using [systemitem]``Podman``, [systemitem]``Docker``, or [systemitem]``Skopeo`` on a machine with internet access. 

.Procedure
. Pull the desired image, then save the image as a [literal]``tar`` archive. 
For example:
+
.Podman
----
podman pull registry.opensuse.org/uyuni/server:latest
podman save --output server.tar registry.opensuse.org/uyuni/server:latest
----
+
.Docker
----
docker pull registry.opensuse.org/uyuni/server:latest
docker save --output server.tar registry.opensuse.org/uyuni/server:latest
----
+
.Skopeo
----
skopeo copy docker://registry.opensuse.org/uyuni/server:latest docker-archive:server.tar:registry.opensuse.org/uyuni/server:latest
----
+
. Transfer the resulting [filename]``server-image.tar`` to the Server container host and load it using the following command:
+
.Load the server image
----
podman load -i server.tar
----

