name: Check RevDate in ASCIIDOC files

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-revdate:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      with:
        fetch-depth: 0

    - name: 'Set up Python'
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b #v5.3.0
      with:
        python-version: '3.x' # Latest avalable version, so we don't need to worry about bumping

    - name: 'Check revdate fields'
      run: python3 .github/scripts/check_revdate.py --grace-days 7 --exclude-patterns _attributes.adoc attributes- nav- README.adoc workflow-
