name: Enforced checkstyle
on: push

jobs:
 run:
   name: Check ifeval syntax
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repo
     uses: actions/checkout@v2

   - name: Check ifeval syntax
     run: find -name "*\.adoc" -type f  | xargs -I {} ./enforcing_checkstyle --filename {} --ifeval

   - name: Check comments on nav file
     run: find -name "nav*\.adoc" -type f  | xargs -I {} ./enforcing_checkstyle --filename {} --comment
