# We keep this workflow without using uyuni-docs-helper as it interacts directly with the repository
name: Find unused files
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3

    - name: Look for unused files
      run: ./scripts/find_unused
