name: Check ifeval syntax
on: push

jobs:
 run:
   name: Check ifeval syntax
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repo
     uses: actions/checkout@v2

   - name: Check ifeval syntax
     run: ifeval_routine -c
