name: translation_test_cs_cz

on:
  push:
    branches:
      - manager-4.3

env:
  LANG: "cs_CZ.UTF-8"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: '[CHECKOUT] Master'
      uses: actions/checkout@v3

    - name: '[TOOLCHAIN] Set up Ruby 3.0'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: '[TOOLCHAIN] Set up NodeJS'
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: '[TOOLCHAIN] po4a'
      run: |
        wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Utils/xUbuntu_20.04/Release.key
        sudo apt-key add Release.key
        sudo add-apt-repository -y -u 'deb https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Utils/xUbuntu_20.04/ ./'
        sudo apt-get install -y po4a
    - name: '[TOOLCHAIN] Install Asciidoctor and Asciidoctor PDF'
      run: |
        gem install asciidoctor
        gem install asciidoctor-pdf --pre
        sudo apt-get install -y graphicsmagick
        sudo apt-get install -y libgraphicsmagick1-dev
        gem install prawn-gmagick -v 0.0.9
        gem install rouge -v 3.30.0
        gem install pygments.rb
        gem install coderay
        asciidoctor --version
        asciidoctor-pdf --version
        
    - name: '[BUILD] UYUNI Japanese PDF Documents'
      run: |
        sudo locale-gen cs_CZ.UTF-8
        sudo update-locale LANG=cs_CZ.UTF-8
        make configure-uyuni
        make pdf-all-uyuni-cs
