name: Update translation files

on:
  push:
    branches:
    - 'master'
    - 'manager-4.3'
    - 'manager-4.3-MU-4.3.[0-9][0-9]?'
    - 'manager-5.0'
    - 'manager-5.0-MU-5.0.[0-9][0-9]?'
    - 'manager-5.1'
    - 'manager-5.1-MU-5.1.[0-9][0-9]?'

jobs:
  run:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/uyuni-project/uyuni-docs-builder:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v4

    - name: Build toolchain binary
      run: task setup

    - name: Update gettext files
      run: task pot

    - name: Commit changes, if any
      uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 #v10.0.0
      with:
        author_name: Galaxy CI
        author_email: galaxy-ci@suse.de
        message: 'Automatic commit: update translation files'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
