[[ref-images-list]]
= Image List

include::{localesdir-ref}[]



The menu:Images[Image List] section displays your current operating system images.

Click btn:[Import] to import a new Docker image.
You can only import new images created from a Docker image using this mechanism.
To import images based on Kiwi instead, see xref:administration:image-management.adoc[].

Click btn:[Refresh] to update the list.

Perform bulk actions by checking images in the list.
Click btn:[Delete] to bulk delete images.

[[image-list-columns]]
[cols="1,1", options="header"]
.Image List Columns
|===
| Column               | Description
| Name                 | Name of the image.
| Version and Revision | Version and revision of the image.
| Updates              | Any updates that are currently available for the image.
| Patches and Packages | Any patches or packages that are currently available for the image.
| Build                | The current status of the build: ``Built``, ``Scheduled``, ``Building`` or ``Failed``.
| Last Modified        | The time and date the image was last modified.
|===

For more information about images, see xref:administration:image-management.adoc[].