= ディストリビューションのアップグレードとサーバ移行
:revdate: 2025-10-19
:page-revdate: {revdate}


[IMPORTANT]
====
* {productname} 5.0は、アップグレード前に停止する必要があります。
* {productname} 5.0は、ホストOSとして{sl-micro} 6.1および{sles} 15 SP7上ではサポートされていません。
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::installation-and-upgrade:partial$snippet-ssl-requirements.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::../../../../../partials/snippet-ssl-requirements.adoc[leveloffset=+1]
endif::[]

移行中に、サーバSSL証明書とCAチェーンはソースサーバからコピーされるため、データベース証明書のみが必要となります

[NOTE]
====
{productname} 5.0 peripheral servers are always using third-party SSL certificates. If the hub server has generated the certificates for the peripheral server, it needs to generate the certificate for the peripheral database too.

On the hub server, run the following command for each of the peripheral server to migrate.

[source, shell]
----
mgrctl exec -ti -- rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="COUNTRY" \
  --set-state="STATE" --set-city="CITY" --set-org="ORGANIZATION" \
  --set-org-unit="ORGANIZATION UNIT" --set-email="name@example.com" \
  --set-hostname=<hostname>-reportdb --set-cname="example.com" --set-cname=db --set-cname=reportdb
----

使用するファイルはサーバコンテナ内にあり、新しい周辺機器サーバホストにコピーする必要があります。

. [literal]``/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT`` as the root CA

. [literal]``/root/ssl-build/<hostname>-reportdb/server.crt`` as the db certificate

. [literal]``/root/ssl-build/<hostname>-reportdb/server.key`` as the db certificate's key.
====


== クライアントツールのブランド変更

{productname} {productnumber}では、サポート対象のすべてのオペレーティングシステム向けに、ブランド変更されたクライアントツールセットが導入されています。この移行はシームレスに行われ、新しい製品同期を実行するユーザは、更新されたチャンネル名にのみ気づくはずです。

以前に{productname} 4.3または5.0に登録されていたクライアントが使用していた[literal]``SUSE Manager Client Tools for XYZ``という名前のチャンネルは、バージョン5.1では利用できなくなり、5.1では更新を受け取らなくなります。

移行後もレガシチャンネルは既存のクライアントに割り当てられたままですが、対応するリポジトリは削除されています。

継続的な更新を確実に行うには、ユーザは以下の操作を実行する必要があります。

* 関連製品の新しい[literal]``SUSE Multi-Linux Manager Client Tools for XYZ``チャンネルをミラーリングし、適切なクライアントに割り当てる。
* 古い[literal]``SUSE Manager Client Tools for XYZ``チャンネルの割り当てを解除する。

これにより、古いクライアントツールに基づくCLMプロジェクトも適宜調整する必要があります。

ワークフロー例については、 xref:common-workflows:workflow-switch-to-new-client-tools-channels.adoc[]を参照してください。



== {sle-micro} 5.5から{sl-micro} 6.1



このドキュメントでは、{productname} 5.0 Serverが配備された{sle-micro} 5.5ホストを{sl-micro} 6.1にアップグレードし、{productname} {productnumber}に移行するためのテスト済みプロシージャについて説明します。


=== 前提条件

[IMPORTANT]
====
{sl-micro} 6.1 uses NetworkManager as the network managing service. If your server is using wicked as the network manager it **must** be migrated to NetworkManager before upgrading the Operating System. For more information on migrating to NetworkManager see: https://documentation.suse.com/sle-micro.

* {productname} 5.0が{sle-micro} 5.5にインストールされ、実行されている。

* システムは登録済みであり、{scc}にアクティブなサブスクリプションがある。
* NetworkManager as the network managing service

====


=== ディストリビューションのアップグレードとサーバ移行

.プロシージャ: {productname} 5.0から{productname} {productnumber}への移行
[role=procedure]
____

. 現在の製品ステータスを確認します。

+

[source, console]
----
SUSEConnect --status-text
----

+

確認:

* ベースOS: `SUSE Linux Enterprise Micro 5.5`

* 拡張機能: `SUSE Manager Server 5.0拡張機能`

+

. システムが更新されていることを確認します。

+

[source, console]
----
transactional-update patch
----

+

--

* パッチが適用された場合、移行を続行する前に、サーバを停止し、システムを再起動してください。

+

[source, console]
----
mgradm stop
reboot
----

* 更新が見つからなかった場合、移行ステップに直接進むことができます。

--

+

. 移行を開始します。

+

[source, console]
----
transactional-update migration --auto-agree-with-licenses --gpg-auto-import-keys
----

+

プロンプトに従って、**SUSE Linux Micro 6.1**および**{productname} Server Extension 5.1**への利用可能な移行を選択します。

+

. サーバを停止し、再起動して変更を適用します。

+

[source, console]
----
mgradm stop
reboot
----

+

. 再起動後のチェックを実行します。

+

アップグレードされたOSと{productname}拡張機能を確認します。

+

[source, console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

以下が表示されるはずです。

* [literal]``PRETTY_NAME="SUSE Linux Micro 6.1"``

* [literal]``SUSE Multi-Linux Manager Server 5.1 Extension``

+

. Enable root SSH access (_if required_).
+
SL Micro 6.1 disables root login via SSH by default.
+
Edit `/etc/ssh/sshd_config.d/sshd.conf`:

+

[source, console]
----
PermitRootLogin yes
----

+

サービスを再起動します。

+

[source, shell]
----
systemctl restart sshd
----

+

詳細については、xref:administration:troubleshooting/tshoot-remote-root-on-micro.adoc[]を参照してください。

+

. {productname}ツールを確認します。

+

[source, console]
----
mgradm --version
----

+

予想される出力:

+

* バージョン[literal]``5.1.11``以降

* リファレンス[literal]``5.1.0``以降

. サーバコンテナをアップグレードします。

+

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-ptf-loss-during-upgrade.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-ptf-loss-during-upgrade.adoc[]
endif::[]

+

[source, console]
----
mgradm start
mgradm upgrade podman
----

+

プロンプトに従い、新しい5.1.0コンテナをプルして設定します。


. 実行中のコンテナを確認します。

+

[source, console]
----
podman ps
----

+

以下が表示されるはずです。

* [literal]``server:5.1.0``以降

* [literal]``server-postgresql:5.1.0``以降

____


[NOTE]
====
アップグレード中に[literal]``uyuni-db``や[litarl]``saline``などのサービスがない場合のエラーは、以前にインストールされていない場合は無視できます。
====


=== 移行の完了

システムは現在、SL Micro 6.1上で{productname} 5.1を実行しています。 本番運用を再開する前に設定を検証してください。 このサーバに{productname} 5.0プロキシが接続されている場合は、xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-51.adoc[]ガイドに進み、プロキシホストをアップグレードしてください。

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]



== {sles} 15 SP6から15 SP7

このドキュメントでは、SUSE Multi-Linux Manager 5.0 Serverが配備されたSUSE Linux Enterprise Server 15 SP6ホストをSUSE Multi-Linux Manager 5.1を備えたSUSE Linux Enterprise Server 15 SP7にアップグレードするためのテスト済みプロシージャについて説明します。


=== 前提条件

* SUSE Multi-Linux Manager 5.0がSUSE Linux Enterprise Server 15 SP6 にインストールされ、実行されている。
* システムはSUSEカスタマーセンター(SCC)に登録済みで、有効なサブスクリプションがある。
* 続行する前にバックアップ作成されていることを確認する。



=== ディストリビューションのアップグレードとサーバ移行

.プロシージャ: {productname} 5.0から{productname} {productnumber}への移行
[role=procedure]
____

. 現在の製品ステータスを確認します。

+

[source, console]
----
SUSEConnect --status-text
----

+

確認:

+

* ベースOS: [literal]``SUSE Linux Enterprise Server 15 SP6``

* 拡張機能: [literal]``SUSE Manager Server 5.0拡張機能``

+

. すべてのシステムパッチを適用します。

+

[source, console]
----
zypper patch
----

+

. サーバを停止し、更新スタックが更新された場合は再起動します。

+

[source, console]
----
mgradm stop
reboot
----

+

. Zypperの移行ツールを起動します。

+

[source, console]
----
zypper migration
----

+

Zypperは、可能な移行ターゲットと詳細を表示します。

+

. 適切なターゲットを選択し、プロンプトに従って移行を実行します。

. 移行が完了したら、サーバを停止して、システムを再起動します。

+

[source, console]
----
mgradm stop
reboot
----

+

. 再起動後のチェックを実行します。

+

アップグレードされたOSと{productname}拡張機能を確認します。
+

[source, console]
----
cat /etc/os-release
SUSEConnect --status-text
----

+

以下が表示されるはずです。

* [literal]``VERSION="15-SP7"``

* [literal]``SUSE Multi-Linux Manager Server 5.1 Extension for SLE``

+

. {productname}ツールのバージョンを確認します。

+

[source, console]
----
mgradm --version
----

+

予想される出力:

* バージョン[literal]``5.1.11``以降

* イメージタグ[literal]``5.1.0``以降

+

. サーバコンテナをアップグレードします。

+

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-ptf-loss-during-upgrade.adoc[]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-ptf-loss-during-upgrade.adoc[]
endif::[]

+

[source, console]
----
mgradm start
mgradm upgrade podman
----

+

プロンプトに従って新しいコンテナイメージを取得し、環境を再設定します。

+

. 実行中のコンテナを確認します。

+

[source, console]
----
podman ps
----

+

予想されるコンテナ:

* [literal]``server:5.1.0``以降

* [literal]``server-postgresql:5.1.0``以降

____


=== 移行の完了

システムは現在、SUSE Linux Enterprise Server 15 SP7上で{productname} 5.1を実行しています。 本番運用を再開する前に設定を検証してください。 このサーバに{productname} 5.0プロキシが接続されている場合は、xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-51.adoc[]に進んでください。

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]
