= Distribution Upgrade and Server Migration from 5.0 to 5.2
:revdate: 2026-02-09
:page-revdate: {revdate}


[IMPORTANT]
====
* {productname} 5.0は、アップグレード前に停止する必要があります。
====

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::installation-and-upgrade:partial$snippet-ssl-requirements.adoc[leveloffset=+1]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-hardened-tmpdir.adoc[leveloffset=+2]
include::../../../../../partials/snippet-ssl-requirements.adoc[leveloffset=+1]
endif::[]

移行中に、サーバSSL証明書とCAチェーンはソースサーバからコピーされるため、データベース証明書のみが必要となります

[NOTE]
====
{productname} 5.0 peripheral servers are always using third-party SSL certificates. If the hub server has generated the certificates for the peripheral server, it needs to generate the certificate for the peripheral database too.

On the hub server, run the following command for each of the peripheral server to migrate.

[source, shell]
----
mgrctl exec -ti -- rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="COUNTRY" \
  --set-state="STATE" --set-city="CITY" --set-org="ORGANIZATION" \
  --set-org-unit="ORGANIZATION UNIT" --set-email="name@example.com" \
  --set-hostname=<hostname>-reportdb --set-cname="example.com" --set-cname=db --set-cname=reportdb
----

使用するファイルはサーバコンテナ内にあり、新しい周辺機器サーバホストにコピーする必要があります。

. ルートCAとして、[litteral]``/root/ssl-build/RHN-ORG-TRUSTED-SSL-CERT``
. [litteral]``/root/ssl-build/<hostname>-reportdb/server.crt`` as the db certificate and
. [litteral]``/root/ssl-build/<hostname>-reportdb/server.key`` as the db certificate's key.
====


== {sle-micro} 5.5 to {sl-micro} 6.2



This document provides the tested procedure to upgrade a {sle-micro} 5.5 host deployed with {productname} 5.0 Server to {sl-micro} 6.2 and migrate to {productname} {productnumber}.


=== 前提条件

* {productname} 5.0が{sle-micro} 5.5にインストールされ、実行されている。
* システムは登録済みであり、{scc}にアクティブなサブスクリプションがある。


=== ディストリビューションのアップグレードとサーバ移行

.プロシージャ: {productname} 5.0から{productname} {productnumber}への移行
[role=procedure]
____

. 現在の製品ステータスを確認します。

+

[source, console]
----
SUSEConnect --status-text
----

+

確認:

* ベースOS: `SUSE Linux Enterprise Micro 5.5`
* 拡張機能: `SUSE Manager Server 5.0拡張機能`

+

. システムが更新されていることを確認します。

+

[source, console]
----
transactional-update patch
----

+

--

* パッチが適用された場合、移行を続行する前に、サーバを停止し、システムを再起動してください。

+

[source, console]
----
mgradm stop
reboot
----

* 更新が見つからなかった場合、移行ステップに直接進むことができます。

--

+

. 移行を開始します。

+

[source, console]
----
transactional-update migration --auto-agree-with-licenses --gpg-auto-import-keys
----

+

Follow the prompts and select the available migration to **SUSE Linux Micro 6.2** and **{productname} Server Extension {productnumber}**.

+

. サーバを停止し、再起動して変更を適用します。

+

[source, console]
----
mgradm stop
reboot
----

+

. 再起動後のチェックを実行します。

+

Verify {productname} extension and {productname} version:

+

[source, console]
----
SUSEConnect --status-text
mgradm --version
----

+

予想される出力:

* Extension: [literal]``SUSE Multi-Linux Manager Server {productnumber} Extension``
* Version: referencing [literal]``5.2.0`` or higher

+

. Verify PostgreSQL database version.

+

[source, console]
----
podman ps
----

+

予想される出力:

* [literal]``server:5.2.0`` or higher
* [literal]``server-postgresql:5.2.0`` or higher

+

. Verify running containers:

+

[source, console]
----
podman ps
----

+

You should see all the expected server containers are up and running.

____


=== 移行の完了

The server host system is now running {sl-micro} 6.2 with updated {productname} {productnumber} Server packages.

If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-52.adoc[Proxy Migration 5.0 > 5.2] guide to upgrade the proxy host.

Validate your setup before resuming production operations.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]


== {sles} 15 SP6から15 SP7

This document provides the procedure to upgrade a {sles} 15 SP6 host deployed with {productname} 5.0 Server to {sles} 15 SP7 and migrate to {productname} {productnumber}.


=== 前提条件

* {productname} 5.0 is installed and running on {sles} 15 SP6.
* システムは登録済みであり、{scc}にアクティブなサブスクリプションがある。


=== ディストリビューションのアップグレードとサーバ移行

.Procedure: Upgrade and Migrate {productname} on {sles} 15 SP6
[role=procedure]
____

. 現在の製品ステータスを確認します。

+

[source, console]
----
SUSEConnect --status-text
----

+

確認:

* Base OS: `SUSE Linux Enterprise Server 15 SP6`
* 拡張機能: `SUSE Manager Server 5.0拡張機能`

+

. システムが更新されていることを確認します。

+

[source, console]
----
zypper patch
----

+

If patches were applied, stop the server and then reboot before proceeding:

+

[source, console]
----
mgradm stop
reboot
----

+

. Perform the migration to SP7 and {productname} {productnumber}.

+

[source, console]
----
zypper migration
----

+

Select to migrate to:

* `{sles} 15 SP7`
* `{productname} Server Extension {productnumber}`

+

. Stop the server and reboot.

+

[source, console]
----
mgradm stop
reboot
----

+

. 再起動後のチェックを実行します。

+

Verify {productname} extension:

+

[source, console]
----
SUSEConnect --status-text
----

+

予想される出力:

* Extension: [literal]``SUSE Multi-Linux Manager Server {productnumber} Extension``

+

. Verify {productname} version.

+

[source, console]
----
mgradm --version
----

+

予想される出力:

* Version: referencing [literal]``5.2.0`` or higher

+

. Verify containers:

+

[source, console]
----
podman ps
----

+

予想される出力:

* [literal]``server:5.2.0`` or higher
* [literal]``server-postgresql:5.2.0`` or higher

____


=== 移行の完了

The server host system is now running {sles} 15 SP7 with updated {productname} {productnumber} Server packages.

If you have a {productname} 5.0 proxy connected to this server, proceed to the xref:installation-and-upgrade:container-deployment/mlm/migrations/proxy/proxy-mlm-50-52.adoc[Proxy Migration 5.0 > 5.2] guide to upgrade the proxy host.

Validate your setup before resuming production operations.

ifndef::backend-pdf[]
include::installation-and-upgrade:partial$snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]

ifdef::backend-pdf[]
include::../../../../../partials/snippet-database-backup-volume.adoc[leveloffset=+2]
endif::[]
